### DISCUSSION TITLE
Full backup instead of incremental after disaster recovery

### DISCUSSION THREAD

**Discussion by KonstantinNosov** [longhorn/longhorn#10138] [Q&A]
I have backups managed by velero. A schedule with only pv and pvc included and daily execution
It creates incremental backup on daily basis if everything is ok.

If I destroy k8s cluster and recreate it from  scratch with data restore from backup (k8s nodes are VMs on proxmox cluster)  - next day backup is created as full, new backupvolume is created on longhorn side. Thus the space consumed on backup target is used inefficient.

Automation that builds cluster from scratch and restores backups ensures that pvc/pv backups are restored first (both velero and longhorn processing are respected) and only after it any workloads are created so I'm sure pvc/pv are restored rather than newly created. 

Am I missing something e.g. need to add some longhorn resources like backupvolumes to velero backup or it is just how longhorn works and nothing may be done about it?

_I assume longhorn just creates new volume `volumes.longhorn.io` and thus new `backupvolumes.longhorn.io` is created for next backup, but have now idea how to preserve `volumes.longhorn.io` id to avoid it_

Velero schedule for backing up volumes
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  labels:
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/part-of: infrastructure
    argocd.argoproj.io/instance: infrastructure-prod_infrastructure-prod
    velero.io/csi-volumesnapshot-class: 'true'
  name: daily-volumes
  namespace: velero
spec:
  schedule: 30 0 * * *
  skipImmediately: false
  template:
    csiSnapshotTimeout: 1h0m0s
    hooks: {}
    includedNamespaces:
      - '*'
    includedResources:
      - pv
      - pvc
    metadata: {}
    ttl: 336h0m0s
  useOwnerReferencesInBackup: false
```

restores are per namespace

```
apiVersion: velero.io/v1
kind: Restore
metadata:
   finalizers:
    - restores.velero.io/external-resources-finalizer
  labels:
    argocd.argoproj.io/instance: subsystems_cicd-prod-bootstrap
    velero.io/csi-volumesnapshot-class: 'true'
  name: cicd-prod-daily-volumes-initial
  namespace: velero
 pec:
  backupName: daily-volumes-20250104003029
  excludedResources:
    - nodes
    - events
    - events.events.k8s.io
    - backups.velero.io
    - restores.velero.io
    - resticrepositories.velero.io
    - csinodes.storage.k8s.io
    - volumeattachments.storage.k8s.io
    - backuprepositories.velero.io
  existingResourcePolicy: update
  hooks: {}
  includedNamespaces:
    - cicd-prod
  itemOperationTimeout: 4h0m0s
  restorePVs: true
  scheduleName: daily-volumes
```
