### DISCUSSION TITLE
Moving Snapshots to a different namespace

### DISCUSSION THREAD

**Discussion by Javex** [longhorn/longhorn#10222] [Q&A]
My goal is to use [restic](https://restic.readthedocs.io/en/stable/) to take backups of all my PVs. One option to achieve this is run a backup pod in the namespace where the PVC exists and perform the backup. However, due to restic's architecture I would prefer to run a central `backup` namespace that takes all backups.

I'm having a bit of trouble in accessing the data that I want to back up from this central namespace. My first idea was to just mount the underlying PV in this namespace, but because the PVC already exists, I can't claim the PV again. Snapshots seem like a much better approach anyway, so I experimented with [CSI Snapshots](https://longhorn.io/docs/1.7.2/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/), but I got stuck and would appreciate some help.

The idea was this: Create a snapshot through CSI (this worked) and then create a new `VolumeSnapshot` (and possibly `VolumeSnapshotContent`) to reference this snapshot. Mount it as a volume to my backup pod, then delete everything again. I have tried with the following:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: backup-snapcontent
spec:
  deletionPolicy: Retain
  driver: hostpath.csi.k8s.io
  source:
    snapshotHandle: snap://pvc-4a4134aa-e356-40ce-96a2-e7c995155400/snapshot-4c15b4d6-ca3f-467e-8072-d59558920abf
  volumeSnapshotRef:
    name: backup-snapshot
    namespace: backup
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: backup-snapshot
  namespace: backup
spec:
  source:
    volumeSnapshotContentName: backup-snapcontent
```

However, the `VolumeSnapshot` remains in `readyToUse: false` forever and there are no log entries that I could find that try to act on this. From reading the [snapshot docs](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) and [spec](https://kubernetes-csi.github.io/docs/api/volume-snapshot.html) I thought this would work, but it's not. What am I doing wrong?
