### DISCUSSION TITLE
imagePullSecrets & Docker Hub pull rate limits

### DISCUSSION THREAD

**Discussion by nlindblo** [longhorn/longhorn#10537] [General]
I was reading yesterday that docker hub will lower the pull rates to 10 pulls per hour for un-authenticated requests from 1st April. Considering the number of pulls required to install all the Longhorn containers and other software in the case of a rebuild or new install, I was thinking I should add a Pull secret to my Helm install to make the pulls authenticated and not hit the rate limit. However, it turns out that there is no option to add a ImagePullSecret unless it's for a private registry. 

How are people planning to get around this, or am I missing something in terms of how this will work ?

https://docs.docker.com/docker-hub/usage/pulls/#:~:text=Starting%20April%201%2C%202025%2C%20all,Unauthenticated%20users%3A%2010%20pulls%2Fhour

**Comment by c3y1huang** [comment]
@nlindblo thank you for the heads-up.
https://github.com/longhorn/longhorn/issues/10538

**Reply by c3y1huang** [reply]
It looks like Longhorn already supports this. https://github.com/longhorn/longhorn/issues/10538#issuecomment-2702637847
@nlindblo could you give it a try?

**Reply by nlindblo** [reply]
I haven't tried it, but reading the air gap installation documentation you linked to, it seems it requires to first pull the images with a script (which will have the same rate limit) and then store them in a private registry. I was hoping to get a helm value something like

global.ImagePullSecret=docker-token

Which would generate

````
spec:
  template:     
    spec:
      imagePullSecrets:
        - name: docker-token
 ````
   That would assume that the secret docker-token is managed outside of the chart

**Reply by SPodjasek** [reply]
My solution for this rate-limit in general was to add pull secret for every default `ServiceAccount`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ...
imagePullSecrets:
  - name: default-registry-pull-secret
```

and if I recall it correctly `kubelet` uses this `default` SA for pulling images.

Anyway, it works for me.
