### DISCUSSION TITLE
Define `backupTargetCredentialSecret` via helm

### DISCUSSION THREAD

**Discussion by BaldFabi** [longhorn/longhorn#10615] [Q&A]
I'm currently tinkering around provisioning new clusters and using Argo to bootstrap the whole default services which are needed in a new cluster.
Longhorn is also deployed using this way with the following yaml

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: longhorn
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1
    helm:
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          logLevel: error
        longhornManager:
          log:
            format: json
        longhornDriver:
          log:
            format: json
```

After successful deploying longhorn with this manifest I thought it would be practical to define the backup too.

So I searched the default values of the helm chart and found 

```yaml
defaultBackupStore:
  # -- Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE")
  backupTarget: ~
  # -- Name of the Kubernetes secret associated with the default backup target.
  backupTargetCredentialSecret: ~
```

So far that makes sense to me. In my prod cluster (running version 1.7.1) it's more or less the same to defined the target and set the credentials using a secret afterwards.

But after thinking about it I was actually expecting from the helm chart, that I could define this necessary secret in one step with the other settings.
Do I really have to deploy longhorn and apply the secret in a second step?

**Comment by mantissahz** [comment]
```yaml
...
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1
    helm:
      releaseName: longhorn
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          logLevel: error
        defaultBackupStore:
          backupTargetCredentialSecret: "backup-secret"
        longhornManager:
          log:
            format: json
        longhornDriver:
          log:
            format: json
...
```

"backup-secret" should be in the same namespace with the Longhorn.
Is it what you want for one step to setup the secret?
