### DISCUSSION TITLE
recuring-job PVC labels are not synced with PV

### DISCUSSION THREAD

**Discussion by Max-LAB** [longhorn/longhorn#10690] [Q&A] [answered]
Hi All, I need a help from you to understand this part. I would like to achieve the transfer of `recuring-job` labels from Persistent Volume Claims (PVCs) to the Persistent Volumes (PVs) that are created from them.

For example, I have a Helm chart for my application deployment where the definition for the PVC is specified, and the PVs are provisioned dynamically.

```yml
{{- if not .Values.volume.pvcExist -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-{{ .Values.global.environment }}-pvc
  namespace: {{ .Values.global.name }}-{{ .Values.global.environment }}
  labels:
    recurring-job-group.longhorn.io/1h: enabled # test with group
    recurring-job.longhorn.io/backup-1h: enabled # test with job
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: longhorn-perf0
{{- end }}
```

After helm charts deployment PVC is created with correct labels

```sh
k get pvc --show-labels

NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE   LABELS
app-test-pvc   Bound    pvc-1147e28b-3a38-4cdc-957b-41a7acc50213   5Gi        RWX            longhorn-perf0   <unset>                 18h   app.kubernetes.io/managed-by=Helm,recurring-job-group.longhorn.io/1h=enabled,recurring-job.longhorn.io/backup-1h=enabled
```

PV is also dinamically created, but when I describe it, I can not see that labels are transfered. 

```
k get lhv -n longhorn-system --show-labels

NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE                                                         AGE   LABELS
pvc-1147e28b-3a38-4cdc-957b-41a7acc50213   v1            attached   healthy                  5368709120   shoot--1d730193fc--cl-test-pool-b8x0rj48zq-z1-797cb-psds6   19h   backup-target=default,longhornvolume=pvc-1147e28b-3a38-4cdc-957b-41a7acc50213,recurring-job-group.longhorn.io/default=enabled,setting.longhorn.io/remove-snapshots-during-filesystem-trim=ignored,setting.longhorn.io/replica-auto-balance=ignored,setting.longhorn.io/snapshot-data-integrity=ignored
```

Now, due to this [closed issue number 7109](https://github.com/longhorn/longhorn/issues/7109) I should be able (after 30 seconds) to see labels inside PV, but that is not the case. I also checked the `longhorn-manager` logs and could not see or find that `syncRecurringJobLabelsToTargetResource` function is triggered. 

I have a couple of questions regarding the functionality I'm trying to implement:

1. Could you please confirm whether it's possible to transfer labels from PVCs to PVs created from them? The Longhorn documentation isn’t very clear on this point.

2. If this transfer is indeed possible, where should I start looking for potential issues? I would greatly appreciate any tips on how to approach troubleshooting this matter.

PS: I am using longhorn version 1.8.1

Thank you all in advance.

**Comment by mantissahz** [comment, marked as answer]
Could you try to add this label `source` first?
`kubectl label pvc/app-test-pvc recurring-job.longhorn.io/source=enabled`

**Reply by Max-LAB** [reply]
@mantissahz you longhorn wizard!! Thank you very much for this . This was exactly what was missing. Now my PVC template looks like this.

```yml
{{- if not .Values.volume.pvcExist -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-{{ .Values.global.environment }}-pvc
  namespace: {{ .Values.global.name }}-{{ .Values.global.environment }}
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/{{ .Values.volume.backup }}: enabled # Accepted values: default (every day at 01:00), 1h-interval, 3h-interval, 5h-interval
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: longhorn-perf0
{{- end }}
```

With, for example `--set volume.backup=1h-interval` during `helm install ...` I can tag my volumes with `job-group` that I previously deployed.
