### DISCUSSION TITLE
preserveUnknownFields make argocd always out of sync

### DISCUSSION THREAD

**Discussion by vnwnv** [longhorn/longhorn#10786] [General]
I'm using argocd with helm to deploy longhorn on my cluster, but some crds always out of sync in argocd.

Here is my application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm-sub
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: starbase-apps
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.8.1"
    helm:
      releaseName: longhorn
      values: |
        preUpgradeChecker:
          jobEnabled: false
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

The argocd diff is 

```
+   preserveUnknownFields: false
```

in these crds

- engineimages.longhorn.io
- engines.longhorn.io
- instancemanagers.longhorn.io
- nodes.longhorn.io
- replicas.longhorn.io
- settings.longhorn.io
- volumes.longhorn.io

Why these crds do not have the `preserveUnknownFields: false`, should i just ignore these?

**Comment by derekbit** [comment]
Ref: https://github.com/longhorn/longhorn/issues/7887

**Reply by vnwnv** [reply]
Thank you!

According to

https://github.com/longhorn/longhorn/issues/7887#issuecomment-1939189021

I found the chart not to explicitly set `spec.preserveUnknownFields: false` for all CRDs.

Maybe we should update the argocd documentation, add something to ignore this.

**Reply by derekbit** [reply]
@vnwnv 
Would you try to submit a PR to update the official document?
https://github.com/longhorn/website/blob/master/content/docs/1.9.0/deploy/install/install-with-argocd.md

**Reply by vnwnv** [reply]
> @vnwnv Would you try to submit a PR to update the official document? https://github.com/longhorn/website/blob/master/content/docs/1.9.0/deploy/install/install-with-argocd.md

No problem! I'll update my config and test tomorrow.

**Reply by innobead** [reply]
Besides, maybe just make that field by default false?

I thought it should be false by default w/o specially setting it.

**Reply by vnwnv** [reply]
I think so. it may default set to `false` since kubernetes 1.20 [api changed](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#api-change-9).

It should be fine without compatible issues, since the kubernetes 1.20 released 3 years before.

related file:
- https://github.com/longhorn/longhorn/blob/master/chart/templates/crds.yaml

**Comment by vnwnv** [comment]
Link to PR https://github.com/longhorn/website/pull/1090

**Comment by jcstryker** [comment]
Hey is there any update on this? Is the CRD going to be updated or do we need to add to the argocd config?

**Reply by vnwnv** [reply]
Currently you may need to add these fields to your Argo CD application file
```yaml
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: engines.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: instancemanagers.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: replicas.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: settings.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
      jsonPointers: ["/spec/preserveUnknownFields"]
```
