### DISCUSSION TITLE
[QUESTION] command Annotation in Installation Requirements manifests ?

### DISCUSSION THREAD

**Discussion by cod3mas0n** [longhorn/longhorn#11008] [Q&A] [answered]
# Question

I'm Wondering Why in the below nfs installation, in the daemonset manifest, the `cmd` is anchored in command annotation? 

```yaml
annotations:
    command: &cmd OS=$(grep.....
```

[longhorn-nfs-installation.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-nfs-installation.yaml)

I can guess
- In case of having no access to the manifest, the command, and what it does, be clear.

Otherwise:

- The `&cmd` anchor could be at the top of the file or another place! as it is a yaml anchor it does nothing to do with the `annotiations`, `kubernetes`, `kubectl`, etc ... . am I right ? or it has another reason ? 

  ```yaml
  command: &cmd bash logic ....

  ```

# Environment

Longhorn version: 1.9.0
Kubernetes version: 1.27

# Additional context

I have tried to change the command placement in the file and delete the annotation, and did the dry-run , was no problem 

```bash
 apply -f longhorn-nfs-installaer.yaml --dry-run=client
```

```yaml
x-command: &cmd OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f 2); fi; if [[ "${OS}" == *"debian"* ]]; then sudo apt-get update -q -y && sudo apt-get install -q -y nfs-common && sudo modprobe nfs; elif [[ "${OS}" == *"suse"* ]]; then sudo zypper --gpg-auto-import-keys -q refresh && sudo zypper --gpg-auto-import-keys -q install -y nfs-client && sudo modprobe nfs; else sudo yum makecache -q -y && sudo yum --setopt=tsflags=noscripts install -q -y nfs-utils && sudo modprobe nfs; fi && if [ $? -eq 0 ]; then echo "nfs install successfully"; else echo "nfs install failed error code $?"; fi
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-nfs-installation
  namespace: longhorn-system
  labels:
    app: longhorn-nfs-installation
spec:
.
.
.
```

```txt
daemonset.apps/longhorn-nfs-installation created (dry run)
```

Also, it was okay with the Docker-compose file in Docker, Docker Swarm. 

```yaml
---
x-restart-policy: &restart-policy
  restart_policy:
    condition: any 
    delay: 5s
    max_attempts: 3
    window: 120s
.
.
.
```
