### DISCUSSION TITLE
Separating longhorn and worker nodes

### DISCUSSION THREAD

**Discussion by NosIreland** [longhorn/longhorn#3317] [Q&A]
Hi,
I have a task to separate worker nodes from longhorn. We want to dedicate nodes only for storage and at the same time we do not want to have our worked nodes just for our workload.
There are 4 worker nodes and 2 storage nodes. I use Rancher UI to install Longhorn from Marketplace
I use node selector and modify:
```
  longhornManager:
    nodeSelector:
      label-key1: "label-value1"
  longhornDriver:
    nodeSelector:
      label-key1: "label-value1"
  longhornUI:
    nodeSelector:
      label-key1: "label-value1"
```
and also
```
defaultSettings:
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
```
as per  [Node Selector](https://longhorn.io/docs/1.2.2/advanced-resources/deploy/node-selector/)
After install I get the desired result and only my storage nodes are visible in Longhorn UI.
But when I deploy app from Marketplace that is on worker node the volume gets correctly created but would not attach. The pod would get stuck in `ContainerCreating` and with warnings:
```
Warning  FailedMount         47s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0 rancher-monitoring-prometheus-token-26bvs config prometheus-nginx]: timed out waiting for the condition       
Warning  FailedAttachVolume  41s (x9 over 2m49s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a1a4e299-ee94-463b-a787-af76c0742710" : rpc error: code = NotFound desc = node worker-1.nodes.local not found
```
In Longhorn GUI the volume shows as Detached. It would attach if I do is manually but that makes no impact to the Pod.
I've seen people having similar issues in [2614](https://github.com/longhorn/longhorn/issues/2614) and have tried with create-default-disk-on-labeled-nodes but that does not seem to work the way I would like to.
If I deploy without nodeSelector and disable scheduling on worker nodes it works fine.

My question is it possible to have separation between storage nodes and worker nodes? If yes, what is the proper method in doing this?

**Comment by NosIreland** [comment]
Just another thing to add, if I set NodeSelector in the GUI, then I have constant loop of terminating /pending/nodeaffinity instance-manager pods
![image](https://user-images.githubusercontent.com/19308746/143412681-ebc99e28-d6b6-4224-833d-23111e8ba1b8.png)

```
instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-62011d50                0/1     Pending        0          0s
instance-manager-r-173c8d38                0/1     Terminating    0          1s
instance-manager-r-3aa00ef2                0/1     Terminating    0          1s
instance-manager-r-173c8d38                0/1     Terminating    0          1s
instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-173c8d38                0/1     Pending        0          0s
instance-manager-r-15c2ed19                0/1     Pending        0          0s
instance-manager-e-babc40cc                0/1     NodeAffinity   0          1s
instance-manager-e-267a8970                0/1     NodeAffinity   0          1s
instance-manager-e-e335cb3f                0/1     NodeAffinity   0          1s
instance-manager-r-173c8d38                0/1     Terminating    0          0s
instance-manager-e-267a8970                0/1     Terminating    0          1s
```

**Comment by derekbit** [comment]
@NosIreland 
you can try the steps in the KB doc https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ .

**Reply by garry-t** [reply]
this in not an solution for his case

**Comment by jenting** [comment]
Link to #3324

**Comment by garry-t** [comment]
nice, I stuck exactly with same design implementation. 
3 nodes run as `storage`. created different storage class which select this node and disk to scheduled only on them. Now I want to start pods from another node, where don't run any longhorn component and  use volume from `storage` nodes. 

I getting misleading error like nodes have not enough storage space, but it is not true. 

one of storage class 

```
resource "kubernetes_manifest" "longhorn-reduced-replica" {
  manifest = {
    apiVersion = "storage.k8s.io/v1"
    kind       = "StorageClass"
    metadata = {
      name = "longhorn-reduced-replica"
    }
    provisioner = "driver.longhorn.io"
    parameters = {
      numberOfReplicas    = "2"
      staleReplicaTimeout = "1440"
      fromBackup          = ""
      nodeSelector        = "storage"
      dataEngine          = "v1"
    }
    reclaimPolicy        = "Retain"
    allowVolumeExpansion = true
    volumeBindingMode    = "WaitForFirstConsumer"

  }
}
```
I use this values 
```
longhorn_values = <<EOT
longhornManager:
  # nodeSelector:
  #   longhorn: "true"
  tolerations:
     - key: "dedicated"
       operator: "Equal"
       value: "longhorn"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "monitoring"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "postgresql"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "rabbitmq"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "db"
       effect: "NoSchedule"
longhornDriver:
  # nodeSelector:
  #   longhorn: "true"
  tolerations:
     - key: "dedicated"
       operator: "Equal"
       value: "postgresql"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "monitoring"
       effect: "NoSchedule"
     - key: "dedicated"
       operator: "Equal"
       value: "longhorn"
       effect: "NoSchedule"

longhornUI:
  nodeSelector:
    longhorn: "true"
  tolerations:
     - key: "dedicated"
       operator: "Equal"
       value: "longhorn"
       effect: "NoSchedule"


defaultSettings:
  nodeDrainPolicy: always-allow
  defaultDataPath: /var/longhorn
  createDefaultDiskLabeledNodes: true
  taintToleration: "dedicated=longhorn:NoSchedule;dedicated=monitoring:NoSchedule;dedicated=postgresql:NoSchedule;dedicated=db:NoSchedule"
# Allow run longhorn system component on all nodes it gives ability yo use longhorn volume at any nodes 
# systemManagedComponentsNodeSelector: "longhorn:true"

persistence:
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultClass: false
  # defaultNodeSelector is disabled because it conflicts with createDefaultDiskLabeledNodes
  # and prevents default disk creation on nodes. Instead, use node tags in storage classes:
  # - longhorn-no-replica and longhorn-reduced-replica use nodeSelector="storage" 
  # - longhorn-monitoring uses nodeSelector="monitoring"
  # This provides granular control without breaking disk creation.
  # defaultNodeSelector:
  #   enabled: true
  #   selector:
  #     longhorn: "true"
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
  EOT
  ```
  
  I disabled these configs
  ```
longhornManager:
  # nodeSelector:
  #   longhorn: "true"
  longhornDriver:
  # nodeSelector:
  #   longhorn: "true"
```
  
  worker nodes appeared in UI, but i can start pod anyway...
