### DISCUSSION TITLE
Problem using private-s3 (not aws) as backup-target

### DISCUSSION THREAD

**Discussion by SattishNavker** [longhorn/longhorn#3371] [Q&A]
In storageclass.yml, I have set "  backingImageDataSourceParameters: '{"url": "http://internal-s3.com:port/"}'  ". Also from longhorn UI added "Backup Target" to "s3://bucketname/" and "Backup Target Credential Secret" to k8s-secrets.  Followed steps as per >> https://longhorn.io/docs/1.2.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore. Note there is no "region" for our local s3 storage (since its not AWS). I receive error >> "ERRO[0020] Fail to list s3: NoCredentialProviders ... "

**Comment by derekbit** [comment]
@SattishNavker 
Make sure to use `echo -n` when generating the base64 encoding for AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_ENDPOINTS.

Steps:
- Create the manifest
```
cat <<EOF >> k8s_secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xxxxxxx
  AWS_SECRET_ACCESS_KEY: xxxxx
  AWS_ENDPOINTS: xxxxx
EOF
```

- Apply the manifest to create the secret
```
kubectl apply -f k8s_secret.yml
```

- Check this has been created by running:
```
kubectl get secrets -n longhorn-system
```
