### DISCUSSION TITLE
Can I apply Longhorn Volume CRD with `kubectl`

### DISCUSSION THREAD

**Discussion by ionut-maxim** [longhorn/longhorn#3429] [Q&A] [answered]
While looking trough the CRD's added by longhorn I saw that there is one for volumes that looks like this:
```yaml
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: test
    recurring-job-group.longhorn.io/default: enabled
  name: test
  namespace: longhorn-system
spec:
  Standby: false
  accessMode: rwo
  backingImage: ""
  baseImage: ""
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:v1.2.3
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ""
  nodeSelector: []
  numberOfReplicas: 1
  replicaAutoBalance: ignored
  revisionCounterDisabled: false
  size: "21474836480"
  staleReplicaTimeout: 20
```

Can I safely create Longhorn volumes by applying manifests like this one?
Is there documentation about this somewhere and what each field represents?
