### DISCUSSION TITLE
[QUESTION] only one longhorn-csi-plugin replica on single node cluster

### DISCUSSION THREAD

**Discussion by PhilipMay** [longhorn/longhorn#3491] [Q&A]
Hi,

I have a single node cluster and do not need any replication. My settings are:

```yaml
persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  defaultReplicaCount: 1
```

When I use this with helm I still have one longhorn-csi-plugin - but I guess I only need one (single node cluster).
How can I do that?

```text
k get pods -n longhorn-system
NAME                                        READY   STATUS    RESTARTS   AGE
csi-attacher-6454556647-dkp4d               1/1     Running   0          25m
csi-provisioner-869bdc4b79-fcpbc            1/1     Running   0          25m
csi-resizer-6d8cf5f99f-n76kj                1/1     Running   0          25m
csi-snapshotter-588457fcdf-hfpj6            1/1     Running   0          25m
engine-image-ei-fa2dfbf0-lccc7              1/1     Running   0          25m
instance-manager-e-208407c3                 1/1     Running   0          25m
instance-manager-r-c2dfa595                 1/1     Running   0          25m
longhorn-csi-plugin-7ftdj                   2/2     Running   0          25m
longhorn-driver-deployer-5f5bd5f89b-zdbsg   1/1     Running   0          26m
longhorn-manager-b899h                      1/1     Running   0          26m
longhorn-ui-5cb4fd47cd-mr7lw                1/1     Running   0          26m
```
