### DISCUSSION TITLE
Unable to drain node

### DISCUSSION THREAD

**Discussion by impsik** [longhorn/longhorn#4102] [Q&A]
I'm trying to use Ansible to automate some kubernetes nodes upgrades etc.
When i try to drain node i get 
`"Failed to delete pod longhorn-system/instance-manager-e-4c4a2936 due to: Too Many Requests"`
Ansible module, kubernetes.core.k8s_drain, is using API as i understand.
I tried as follows: cordon node, then drain and i got the message above.
Sometimes it works, sometimes it does not.
Relevant part of ansible playbook:
```
    - name: Mark node "{{ inventory_hostname|lower }}" as Unschedulable.
      kubernetes.core.k8s_drain:
        state: cordon
        kubeconfig: ~/.kube/config
        name: "{{ inventory_hostname|lower }}"
      delegate_to: localhost

    - name: "Drain node {{ inventory_hostname|lower }}, even if there are pods not managed by a ReplicationController, Job, or DaemonSet on it."
      kubernetes.core.k8s_drain:
        state: drain
        name: "{{ inventory_hostname|lower }}"
        kubeconfig: ~/.kube/config
        delete_options:
          ignore_daemonsets: yes
          delete_emptydir_data: yes
          force: yes
          terminate_grace_period: 0
          wait_sleep: 120
      delegate_to: localhost
```
For testing i installed wordpress from Bitnami ([https://bitnami.com/stack/wordpress/helm]) and this created 2 PVC.
And i have Longhorn also installed, ofc.
Without PVC everything seems to work normally. I'm i doing something wrong here?
