### DISCUSSION TITLE
velero not backup volumes.longhorn.io crd

### DISCUSSION THREAD

**Discussion by gary561** [longhorn/longhorn#4184] [Q&A] [answered]
I manually create longhorn volumes by yaml,then make pv and pvc, deploy a pod use that;
I use velero to backup k8s like this `velero backup create t1`
but after I reset the k8s and use velero restore create --from-backup=t1, a error occur,
volume of myvol is not found;
so after I manually apply the volume.yaml, it become normal;
I wander why this happend.
below is my config yaml file
```yaml
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: myvol
    recurring-job-group.longhorn.io/default: enabled
  name: myvol
  namespace: longhorn-system
spec:
  size: "2147483648"
  accessMode: rwo
  staleReplicaTimeout: 20
  replicaAutoBalance: ignored
  engineImage: longhornio/longhorn-engine:v1.3.0
  dataLocality: disabled
  frontend: blockdev
  fromBackup: ""
  numberOfReplicas: 1
  backingImage: ""
  recurringJobs: null
  Standby: false
  Robustness: ""
  diskSelector: []
  nodeSelector: []
  revisionCounterDisabled: false
```
deploy.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-vol-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle:  myvol
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: longhorn-vol-pv
  resources:
    requests:
      storage: 200M
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc

```
thanks a lot!
