### DISCUSSION TITLE
is it a bug? exposing longhorn-ui via ingress-nginx

### DISCUSSION THREAD

**Discussion by binooetomo** [longhorn/longhorn#4436] [Q&A]
Dear all ...
I read and follow https://longhorn.io/docs/1.3.0/deploy/accessing-the-ui/longhorn-ingress/

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # Ingress class
    kubernetes.io/ingress.class: nginx
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    # nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - longhorn.k8s.jcamp.cloud
    secretName: longhorn.k8s.jcamp.cloud
  rules:
  - host: longhorn.k8s.jcamp.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
```
result of apply
```
kubectl -n longhorn-system describe  ing longhorn-ingress
Name:             longhorn-ingress
Labels:           <none>
Namespace:        longhorn-system
Address:          192.168.1.88
Ingress Class:    <none>
Default backend:  <default>
TLS:
  longhorn.k8s.jcamp.cloud terminates longhorn.k8s.jcamp.cloud
Rules:
  Host                      Path  Backends
  ----                      ----  --------
  longhorn.k8s.jcamp.cloud  
                            /   longhorn-frontend:80 (10.244.1.60:8000)
Annotations:                cert-manager.io/cluster-issuer: letsencrypt-staging
                            kubernetes.io/ingress.class: nginx
                            nginx.ingress.kubernetes.io/auth-realm: Authentication Required 
                            nginx.ingress.kubernetes.io/auth-secret: basic-auth
                            nginx.ingress.kubernetes.io/auth-type: basic
                            nginx.ingress.kubernetes.io/proxy-body-size: 10000m
Events:
  Type    Reason             Age                From                       Message
  ----    ------             ----               ----                       -------
  Normal  CreateCertificate  41m                cert-manager-ingress-shim  Successfully created Certificate "longhorn.k8s.jcamp.cloud"
  Normal  Sync               40m (x2 over 41m)  nginx-ingress-controller   Scheduled for sync

```

when I try to open it via browser, I got '503' from ingress-nginx.

I tried to re read the kind: Service  (longhorn-frontend) and found that it's backend is longhorn-ui.
So I check kind:Deployment (longhorn-ui):
```
kubectl -n longhorn-system describe deployment longhorn-ui
Name:                   longhorn-ui
Namespace:              longhorn-system
CreationTimestamp:      Wed, 17 Aug 2022 09:45:55 +0700
Labels:                 app=longhorn-ui
                        app.kubernetes.io/instance=longhorn
                        app.kubernetes.io/name=longhorn
                        app.kubernetes.io/version=v1.3.1
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=longhorn-ui
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=longhorn-ui
           app.kubernetes.io/instance=longhorn
           app.kubernetes.io/name=longhorn
           app.kubernetes.io/version=v1.3.1
  Containers:
   longhorn-ui:
    Image:      longhornio/longhorn-ui:v1.3.1
    Port:       8000/TCP
    Host Port:  0/TCP
    Environment:
      LONGHORN_MANAGER_IP:  http://longhorn-backend:9500
      LONGHORN_UI_PORT:     8000
    Mounts:
      /var/cache/nginx/ from nginx-cache (rw)
      /var/config/nginx/ from nginx-config (rw)
      /var/run/ from var-run (rw)
  Volumes:
   nginx-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   nginx-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   var-run:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   longhorn-ui-86b56b95c8 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  24m   deployment-controller  Scaled up replica set longhorn-ui-86b56b95c8 to 1

```
Looks like that it's listen port is 8000.

So I edit my longhorn-frontend section to be:
```
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.3.1
    app: longhorn-ui
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  type: ClusterIP
  selector:
    app: longhorn-ui
  ports:
  - name: http
    port: 80
    targetPort: 8000 # changed from 'http' by bino
    nodePort: null
```
Apply that change.

But still got 503.

Kindly please tell me what I have to do/look/read to fix this problem

Sincerely  
-bino-

**Comment by thiscantbeserious** [comment]
The documentation for that is really overcomplicated - its really simple:

It needs to go to service **longhorn-frontend with port 80** not longhorn-ui with port 8000 

So theoretically the first example you've give should be correct already unless there's an error already somewhere.

... 

See my example IngressRoute (traefik - the middleware is not really needed unless you use https)

Advice:

Skip the authentication and SSL until you get it working, then add SSL and an OAuth Middleware and/or RBAC as needed, - not basicAuth (OAuth can be reused for everything and is far more convient and secure then basicAuth).

````
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: svc-longhorn-headers
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"

---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: longhorn-frontend
  namespace: longhorn-system

spec:
  entryPoints: 
    - web
    - websecure
  routes:
  - match: Host(`longhorn.mydomain.com`) 
    kind: Rule
 # middlewares:
 #   - name: svc-longhorn-headers
 #   - name: sso
 #    namespace: traefik-system
    services:
    - name: longhorn-frontend
      port: 80
 # tls:
 #   secretName: my-cert
````

**Reply by binooetomo** [reply]
@thiscantbeserious  thankyou for taking time to response.

If you mean with 'It needs to go to service longhorn-frontend with port 80' is the ingress, yes it go there.
But where the longhorn-frontend have to go in the end?
To the longhorn-ui:8000 right?

Sincerely
-bino-

**Comment by mattmattox** [comment]
@binooetomo Did you create the basic auth secret? (Step 1 and 2)

Also, can you access the Longhorn without the ingress?
Example:
`kubectl -n longhorn-system port-forward service/longhorn-frontend 8080:80`
Then browse to http://localhost:8080

**Reply by binooetomo** [reply]
> @binooetomo Did you create the basic auth secret? (Step 1 and 2)
> 
> Also, can you access the Longhorn without the ingress? Example: `kubectl -n longhorn-system port-forward service/longhorn-frontend 8080:80` Then browse to http://localhost:8080

yes I can.

**Reply by binooetomo** [reply]
I created the basic auth. and the ingress.

I'll back to this discussion on monday.

**Comment by FaraSys** [comment]
```
My work manifest
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn.contoso.com
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/use-port-in-redirects: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  tls:
  - hosts:
      - longhorn.contoso.com
    secretName: tls-contoso
  rules:
  - host: longhorn.contoso.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
```
