### DISCUSSION TITLE
RWX Volumes - Expose NFS Server(s) via Ingress possible/feasible?

### DISCUSSION THREAD

**Discussion by thiscantbeserious** [longhorn/longhorn#4439] [Q&A]
It possible to expose the NFS-Server for RWX-Volumes to the world e.g. via an Ingress (using Traefik f.e. - or even a NodePort would be fine)?

Right now I'm using Longhorn as the Storage Solution for NextCloud (until I find the time, money and hardware to build a TrueNAS storage server). 

So the idea would be to provide an external mount for my Brother Document Scanner which has the ability to scan directly to an NFS-Share.

From

https://longhorn.io/docs/1.3.1/advanced-resources/rwx-workloads/

I seems like that I would have to build that on top of share-manager-<volume-name> which is the respective NFS-Server for that volume - right?

From a quick search related how to do this generally on Kubernetes e.g. for the native NFS Provider not just related to Longhorn I found that somebody is doing it already for OpenEBS:

https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/expose-nfs-server.md#exposing-nfs-server-using-nginx-ingress

Are there any caveats to look for e.g. Authentication or making sure that the volume isnt replicated (not sure how thats handled on RWX-Volumes)?

Generally it seems like a valid use case for businesses too - especially with external services potentionally looking to use it - e.g. for network printers so I'm wondering (not going to jump into the endless discussion about performance downsides).

This here is just my personal cloud hosted om bare metal not even exposed to the world nothing else so things like security/authentication workarounds dont trigger me - I dont even have RBAC setup. Just a OAuth middleware in front of all sensible services that no one but me should touch in my internal network.

Or maybe should I ditch that idea and straightly jump to a dedicated NFS-Server? Tought I really like the aspect of it having the HA-Aspect having this on-top of Longhorn and Kubernetes in case of a hardware failure or maintenance/upgrade not having to configure and setup everything again (seems like a thing lately for me).

Has anybody done/tried something like this already?

**Comment by derekbit** [comment]
@thiscantbeserious 
I think you can create a Longhorn RWO volume and then create a NFS server deployment for exporting the volume
Two ways to expose your NFS exported folder to external network
1. Use NodePort
2. Use nginx-ingress

**Comment by derekbit** [comment]
Here is an example using the `NodePort`

### PVC and NFS Server Deployment

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-vol-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lh-vol-nfs-server
    app.kubernetes.io/component: lh-vol-nfs-server
    app.kubernetes.io/instance: lh-vol-nfs-server
  name: lh-vol-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: lh-vol-nfs-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: lh-vol-nfs-server
    spec:
      containers:
      - env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        image: itsthenetwork/nfs-server-alpine@sha256:7fa99ae65c23c5af87dd4300e543a86b119ed15ba61422444207efc7abd0ba20
        imagePullPolicy: IfNotPresent
        name: lh-vol-nfs-server
        startupProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
        readinessProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /nfsshare
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: lh-vol-pvc
```

### Service

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lh-vol-nfs-server
    app.kubernetes.io/component: lh-vol-nfs-server
    app.kubernetes.io/instance: lh-vol-nfs-server
  name: lh-vol-nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: rpcbind
    port: 111
    protocol: TCP
    targetPort: 111
  selector:
    deployment: lh-vol-nfs-server
  type: NodePort
```

### Find the IP and Port

```
root@rancher50-master:~/nfs-export# k get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP           NODE                NOMINATED NODE   READINESS GATES
lh-vol-nfs-server-cf868cc9f-wxhxb   1/1     Running   0          90s   10.42.3.22   rancher50-worker4   <none>           <none>

root@rancher50-master:~/nfs-export# k get svc
NAME                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                        AGE
kubernetes          ClusterIP   10.43.0.1      <none>        443/TCP                        17h
lh-vol-nfs-server   NodePort    10.43.65.144   <none>        2049:30017/TCP,111:32168/TCP   14s
```

IP: ip of rancher50-worker4
Port: 30017

### Mount the Exported Folder on External Host

mount -t nfs -o nfsvers=4.1,port=30017 {IP}:/ /mnt/nfs
