### DISCUSSION TITLE
Longhorn creating more complex PV / PVC's.

### DISCUSSION THREAD

**Discussion by andrew1044** [longhorn/longhorn#4453] [Q&A]
Hi everyone, I'm trying to create longhorn PV / PVC's as kube manifest files. I've seen references to numerous references to simple PVC's but struggling tp find more complex examples to work from. 

I want to create a volume and pv/pvc such like the screenshots attached, how would this look as yaml file? I am struggling to understand how to create longhorn volumes as manifest files. Also, struggling to understand how to name volumes appropriately. 

![image](https://user-images.githubusercontent.com/38687378/185746494-fee00c59-0c04-4158-bc83-c9ad4bd68870.png)
![image](https://user-images.githubusercontent.com/38687378/185746619-305ea925-e52b-487c-8f0c-233fd1e6ed2a.png)

I do understand that the PVC could look similar to this: 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-simple-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
```

Is there any documentation that outlines all PVC key value pairs applicable to Longhorn? 

Many thanks in advance.

**Comment by derekbit** [comment]
I think you can create a storageClass including volume type, dataLocality and etc., and then create a PVC with the SC.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: best-effort-longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
```
