### DISCUSSION TITLE
fsType = xfs seems not working as expected

### DISCUSSION THREAD

**Discussion by jwenjian** [longhorn/longhorn#4507] [Q&A]
Hi,

Recently, I faced a strange issue, every new created volume contains an empty folder `lost+found`, according to https://github.com/longhorn/longhorn/issues/913 and https://github.com/longhorn/longhorn/issues/1580 , seems this will only happen if the fsType is ext4.

But, I set the fsType to xfs of the storage class, this folder still exists.

seems the storage class parameter not working.

sample storage class:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-server-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: 1
  staleReplicaTimeout: "2880" # 48 hours in minutes
  dataLocality: "best-effort"
  fromBackup: ""
  fsType: "xfs"
```

The file system of the k8s node, is xfs too

```shell
# df -T /var/lib/longhorn/
Filesystem            Type 1K-blocks     Used Available Use% Mounted on
/dev/mapper/rhel-root xfs   73364480 52827256  20537224  73% /

```

The `lost+found` folder in volume (take mongodb data dir as example):

```
drwx--S--- 2 mongodb 1001     4096 Aug 31 09:08 journal
drwx--S--- 2 mongodb 1001     4096 Aug 31 09:21 key.db
drwxrws--- 2 root    1001    16384 Aug 31 09:08 lost+found
-rw------- 1 mongodb 1001        2 Aug 31 09:08 mongod.lock
-rwxr-xr-x 1      99   99 10625024 Aug 31 09:08 mongodb-healthcheck
-rwxr-xr-x 1      99   99    15680 Aug 31 09:08 ps-entry.sh
-rw------- 1 mongodb 1001    36864 Aug 31 09:21 sizeStorer.wt
-rw------- 1 mongodb 1001      114 Aug 31 09:08 storage.bson


```

Longhorn 1.2.3

RKE2 version

```
rke2 --version
rke2 version v1.20.14+rke2r1 (261af292328ba1b0493b95a8796d348007cdc5bf)
go version go1.16.10b7

```

The actual issue for us is, this `lost+found` folder has permission root:root, it prevent non-root user in container to write files into the same folder.

So.

please help
