### DISCUSSION TITLE
Ingress - nginx with sub-path

### DISCUSSION THREAD

**Discussion by jkleinkauff** [longhorn/longhorn#4727] [Q&A]
Hey everyone,

I am facing some issues to setup the longhorn ingress with nginx in front of a sub-path.
There are some posts on the issues/discussions page, but none are working for me - or are incomplete.

Here is my ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /longhorn(/|$)(.*)
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
```

When accessing /longhorn, I just see a blank page,  can't see js and css`s:
![image](https://user-images.githubusercontent.com/58440667/196241296-6ef47042-bcb6-494f-ac98-cedecbfabebf.png)

![image](https://user-images.githubusercontent.com/58440667/196242500-4c33391a-4801-45f7-b0a8-3a7224b3c374.png)

Does anyone still face issues with this kind of setup?

Thanks in advance.
