### DISCUSSION TITLE
Longhorn Helm Chart in ArgoCD

### DISCUSSION THREAD

**Discussion by Vertiwell** [longhorn/longhorn#4790] [Q&A]
I have the following in my ArgoCD Application:
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: v1.3.2

I have dozens of other applications with the same setup, only Longhorn spins forever on `Unknown v1.3.2`, I also tried dropping the v, but it makes no difference.

Any thoughts please?

**Comment by ehudyonasi** [comment]
maybe try with targetRevision: '1.3.2'

**Comment by shuo-wu** [comment]
Created a feature request ticket to track the ArgoCD support: https://github.com/longhorn/longhorn/issues/4853

**Comment by alekc** [comment]
uhm, it does work for me though?
```
project: runtime
source:
  repoURL: 'https://charts.longhorn.io'
  targetRevision: 1.3.2
  helm:
    releaseName: longhorn
    values: |
      fullnameOverride: longhorn
      defaultSettings:
        taintToleration: "home=true:NoSchedule"
        priorityClass: system-node-critical
      longhornManager:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      longhornDriver:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      longhornUI:
        tolerations:
            - effect: NoSchedule
              key: home
              operator: Exists
      persistence:
        reclaimPolicy: Retain
      ingress:
        enabled: true
        host: ***
  chart: longhorn
destination:
  server: 'https://kubernetes.default.svc'
  namespace: longhorn-system
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - Validate=false
    - CreateNamespace=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
```
