### DISCUSSION TITLE
Why can not use iSCSI volume?

### DISCUSSION THREAD

**Discussion by limit001** [longhorn/longhorn#4886] [Q&A]
Question
------------

Sorry for my poor english T T

I want to use longhorn iSCSI volume, so I made this volume 
![image](https://user-images.githubusercontent.com/22145627/202063977-db6b7a6b-3e09-4a9e-a567-f07924d9ca6e.png)
![image](https://user-images.githubusercontent.com/22145627/202064049-681c7132-5b38-4c5b-bc2f-f8619596b056.png)
but, When I use iSCSI volume PVC at k3s Pod
```

kind: Deployment
metadata:
  name: nginx1
  namespace: test

spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx1
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx1
    spec:
      nodeName: master
      containers:
      - name: nginx1
        image: nginx
        volumeMounts:
          - mountPath: workspace
            name: volume1
        ports:
        - containerPort: 80
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: migam001
``` 

then there is error , when make pod 
```
│   Warning  FailedAttachVolume  8h (x36 over 9h)  attachdetach-controller  AttachVolume.Attach failed for volume "migam001" : rpc error: code = InvalidArgument desc = volume migam001 invalid frontend type iscsi                                                                                                                                                                                                            │
```
so I have searched source code of error log~!
I found!
```
// ControllerPublishVolume will attach the volume to the specified node
func (cs *ControllerServer) ControllerPublishVolume(ctx context.Context, req *csi.ControllerPublishVolumeRequest) (*csi.ControllerPublishVolumeResponse, error) {
...
	if volume.Frontend != string(longhorn.VolumeFrontendBlockDev) {
		return nil, status.Errorf(codes.InvalidArgument, "volume %s invalid frontend type %s", volumeID, volume.Frontend)
	}
...`
```
[source code url](﻿https://github.com/longhorn/longhorn-manager/blob/fc07fe8e182a7426d56b4d98f63664b60a088e1c/csi/controller_server.go)
https://github.com/longhorn/longhorn-manager/blob/fc07fe8e182a7426d56b4d98f63664b60a088e1c/csi/controller_server.go

this source code  do not handle iSCSI Frontend Volume~!, volume.Frontend must be BlockDevice, longhorn volume can not be iSCSI frontend

Can I use iSCSI frontend volume in Longhorn~?
Has anyone succeeded in attaching an iSCSI volume?


Environment
------------
- Longhorn version: longhornio/longhorn-engine:v1.3.2
- Kubernetes version: k3s version v1.24.7+k3s1 (7af5b167)
- Node config
  - OS type and version : Rocky Linux 9.0
  -  CPU per node : 2
  -  Memory per node: 4GB

Additional context
-----------------
- there is iSCSI volume like this picture.- 
![image](https://user-images.githubusercontent.com/22145627/202337833-dacd2156-145d-4624-a035-543d2255cba6.png)
  - but pod can not attach that volume

**Comment by shuo-wu** [comment]
Choosing frontend iSCSI means the volume is running as an iSCSI target and you need to do login manually. The target address/endpoint is already provided in the detail part.
If you want to directly use the longhorn volume (which is what you do in the YAML), please use frontend `Block Device` instead.

**Reply by limit001** [reply]
Thanks a lot for answer!!!
but Sorry T T
I'm not sure about manually logging in.
Do I need to connect to iSCSI from the POD? like this yaml? this yaml setting is success!
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: migam-pv001
spec:
  storageClassName: migam004-class
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.42.0.13:3260
    iqn: iqn.2019-10.io.longhorn:migam010
    lun: 1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migam-pvc003
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: migam004-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing2
  labels:
    app: testing2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing2
  template:
    metadata:
      labels:
        app: testing2
        name: testing2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/sleep", "7d"]
        volumeMounts:
        - name: testing2-vol
          mountPath: /var/lib/testing2
      volumes:
      - name: testing2-vol
        persistentVolumeClaim:
          claimName: migam-pvc003
```
sorry, Is there any place (manually logging in) I can refer to?
