### DISCUSSION TITLE
[QUESTION]  Remove longhorn from node in a cluster in rancher

### DISCUSSION THREAD

**Discussion by elton557** [longhorn/longhorn#5119] [Q&A]
Hello, I would like to remove the longhorn from some nodes in my cluster on the rancher, but when I remove it using the command:

kubectl -n longhorn-system delete nodes.longhorn.io <node name>

He removes it, but when restarting the node he inserts it back into the longhorn cluster! I cannot delete this node from rancher, but I want to remove it from longhorn, how do I do it?

**Comment by weizhe0422** [comment]
Hi @elton557, 

Would you mind providing more information about your purpose?

I think maybe you could disable `Node Scheduling` and set `Eviction Requested` to avoid using this node in longhorn system. 
![image](https://user-images.githubusercontent.com/17548901/208897163-7665bcb5-cc15-417c-a3cf-3b735ec3cdd5.png)

And also set the `System Managed Components Node Selector` to deploy components on particular nodes.

**Comment by elton557** [comment]
Hello, it is disabled like the image

<img width="1680" alt="Captura de Tela 2022-12-21 às 09 29 36" src="https://user-images.githubusercontent.com/52458645/208905530-5eae7789-0659-46be-8b0b-15c01d2f1373.png">

however, on the node it is still running longhorn POD, I wish it didn't run any longhorn service on the node so as not to consume resources! so I would like to remove this node from longhorn

<img width="1617" alt="Captura de Tela 2022-12-21 às 09 31 25" src="https://user-images.githubusercontent.com/52458645/208905775-41339d96-2014-4bbb-99a7-97863d9f7ee6.png">

**Comment by JorisPenningsCM** [comment]
If I understand the question correctly you would like to schedule longhorn on specific nodes. I got this to work by labeling all longhorn dedicated nodes(label: "longhorn=true") and changing some values in the values.yaml for our longhorn helm install: (if using rancher to install longhorn you can edit the helm install from the "cluster tools "menu)

values.yaml:
```
defaultSettings:
  systemManagedComponentsNodeSelector: "longhorn:true"

longhornManager:
  nodeSelector:
    longhorn: "true"

longhornDriver:
  nodeSelector: 
    longhorn: "true"

longhornUI:
  nodeSelector: 
    longhorn: "true"
```
