### DISCUSSION TITLE
[KB] OpenSUSE MicroOS requires lvm2 installed to support encrypted volumes

### DISCUSSION THREAD

**Discussion by valkenburg-prevue-ch** [longhorn/longhorn#5332] [Q&A] [answered]
## Question
Is there any way to get encryption at rest to work in my setup?

I follow the exact setup from here (no modifications at all) : https://longhorn.io/docs/1.4.0/advanced-resources/security/volume-encryption/

When creating a pod which mounts a pvc using the encrypted storage class, I get these messages in `describe pod`:
```
  Warning  FailedMount             117s (x2 over 4m12s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[my-crypto], unattached volumes=[my-crypto kube-api-access-8xgp6]: timed out waiting for the condition
  Warning  FailedMount             47s (x9 over 4m58s)   kubelet                  MountVolume.MountDevice failed for volume "pvc-17d29411-dd96-430f-8f3c-f5d4f2c6dd35" : rpc error: code = Internal desc = format of disk "/dev/mapper/pvc-17d29411-dd96-430f-8f3c-f5d4f2c6dd35" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/fae68daabaa7dd42019918098352ecbbdd76a5f7a35b4443146daa3f059a5190/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.46.4 (18-Aug-2021)
The file /dev/mapper/pvc-17d29411-dd96-430f-8f3c-f5d4f2c6dd35 does not exist and no size was specified.
)
```

## Environment

 - Longhorn version: 1.4.0
 - Kubernetes version: k3s, v1.25.6+k3s1
 - Node config
   - OS type and version: OpenSUSE MicroOS 16
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type: node storage
   - Network bandwidth and latency between the nodes: ?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hetzner Cloud

## Additional context
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "International man of mystery."
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"
```

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-crypto-global
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  nodeSelector: "node-storage"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: ext4
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-crypto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-crypto-global
  volumeMode: Filesystem
```

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox2
spec:
  volumes:
    - name: my-crypto
      persistentVolumeClaim:
        claimName: test-crypto
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - name: my-crypto
          mountPath: /crypto
  restartPolicy: Always
```

Yet, `kubectl describe pvc test-crypto` gives:

```
Name:          test-crypto
Namespace:     default
StorageClass:  longhorn-crypto-global
Status:        Bound
Volume:        pvc-17d29411-dd96-430f-8f3c-f5d4f2c6dd35
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
               volume.kubernetes.io/storage-provisioner: driver.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       busybox2
Events:
  Type     Reason                 Age                From                                                                                      Message
  ----     ------                 ----               ----                                                                                      -------
  Warning  ProvisioningFailed     10m                persistentvolume-controller                                                               storageclass.storage.k8s.io "longhorn-crypto-global" not found
  Normal   ExternalProvisioning   10m (x2 over 10m)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
  Normal   Provisioning           10m                driver.longhorn.io_csi-provisioner-64dcbd65b4-7q74w_348b2d01-90a6-4999-a5d8-5fb7685136c0  External provisioner is provisioning volume for claim "default/test-crypto"
  Normal   ProvisioningSucceeded  10m                driver.longhorn.io_csi-provisioner-64dcbd65b4-7q74w_348b2d01-90a6-4999-a5d8-5fb7685136c0  Successfully provisioned volume pvc-17d29411-dd96-430f-8f3c-f5d4f2c6dd35
```
