### DISCUSSION TITLE
Configure BackupTarget via GitOps

### DISCUSSION THREAD

**Discussion by cod-r** [longhorn/longhorn#5766] [Q&A] [answered]
I'm trying to setup longhorn backups via GitOps by creating a `BackupTarget` object like:
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://my-bucket"
  credentialSecret: "longhorn-backup-creds"
  pollInterval: 5m0s
```

but is getting replaced automatically with an empty one.

Is it possible to setup Longhorn without using the UI?

EDIT: using version 1.4.1

**Comment by innobead** [comment]
Have u tired the backup setting resource instead to set the default backup target? 

IIRC, currently the backup target resource is exclusive and only synchronized from the setting.

cc @c3y1huang

**Comment by cod-r** [comment, marked as answer]
Using the `Setting` CRD works. 
But I find it kind of verbose:
```yaml
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: s3://my-bucket
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: longhorn-backup-creds
```

I had a look on the helm chart and the settings are done via a ConfigMap: https://github.com/longhorn/charts/blob/master/charts/longhorn/templates/default-setting.yaml

But if I set something in the ConfigMap it just transfers the settings to a kind `Setting` and it disappears from the ConfigMap. So Argo CD will have a continuous reconciliation loop.
