### DISCUSSION TITLE
[QUESTION] Backup: Is Longhorn skipping "retain" parameter?

### DISCUSSION THREAD

**Discussion by rabbagliettiandrea** [longhorn/longhorn#5836] [General]
## Question
I've the following RecurringJob:

```
NAME          GROUPS            TASK     CRON           RETAIN   CONCURRENCY   AGE   LABELS
backup-ou-5   ["backup-xyz"]   backup   0 3,15 * * *   4        2             35d   {"xyz/customer":"xyz","env":"prod"}
```

but my UI shows the following:

![image](https://user-images.githubusercontent.com/579861/234952547-1d553f5f-65b3-4b39-9509-5a5d57890dbd.png)
![image](https://user-images.githubusercontent.com/579861/234952674-6817a6c3-30d8-4333-b7f4-a0b5eb2c6754.png)

Am I missing something? Why I have only two backups?

## Environment

 - Longhorn version: 1.4.0
 - Kubernetes version: v1.24.11+k3s1
 - Node config
   - OS type and version Ubuntu 22.04
   - CPU per node: 32
   - Memory per node: 128
   - Disk type: NVMe Enterprise Grade
   - Network bandwidth and latency between the nodes: 10Gbit, 1ms
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context
I've also another RecurringJob like:
```
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-general
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: "backup"
  groups:
    - backup-general
  retain: 2
  concurrency: 3
  labels:
    env: prod
```
maybe is overwring the retention?
