### DISCUSSION TITLE
Is it normal that with reclaimPolicy: Retain the files are still deleted from the node?

### DISCUSSION THREAD

**Discussion by Floeig** [longhorn/longhorn#5901] [Q&A] [answered]
Hello,

I'm trying to achive that if I accidentally delete (using the ui or a kubectl command), I can still recover the data trought the nodes.

I've read the doc https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain and it seems `reclaimPolicy: Retain` should do that. 
But when I delete the PVC and the PV (using the UI or the command), the folders on the nodes disapear.

Any idea how to do that?
thank you

**Comment by ChanYiLin** [comment]
Hi, may I know more about the details of the steps you executed?

I have tried
1. create a Volume (through the UI)
2. create a PV,PVC (through the UI)
3. create a pod to use the PVC and write some data
4. delete the pod and the PV,PVC
5. I could still see the `/var/lib/longhorn/replicas/{VOLUME_NAME}`  which stored the real data and could be reused by creating the PV,PVC pointing to the volume again.

**Comment by Floeig** [comment]
Hello @ChanYiLin,

I've tested that again and had the same result
# My Volume
![image](https://github.com/longhorn/longhorn/assets/29572254/b729286d-5f42-4f39-8fe9-4dc4f598f4b9)
# My PVC
![image](https://github.com/longhorn/longhorn/assets/29572254/b8bee17b-5fd2-49a1-b387-8d100c08327d)
# My Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: my-test-pvc
  volumes:
    - name: my-test-pvc
      persistentVolumeClaim:
        claimName: test
```
### Creating a file and testing the result
Then I created a file from the pod:
```bash
root@mypod:/var/www/html# echo "this is a test" > myTest.txt
```
It's all working well and I can see the folder and the file in the node:
![image](https://github.com/longhorn/longhorn/assets/29572254/ccfb7d06-9d0b-470e-bbd8-95f65c70ea9b)

## Deleted the pod & the volume
`❯ k delete -f pod.yaml`
![image](https://github.com/longhorn/longhorn/assets/29572254/331fc378-89db-477a-9bc5-21b871eac197)

### Result
the folder is gone
![image](https://github.com/longhorn/longhorn/assets/29572254/290ecd85-ceff-42e2-9e75-b492a58fb4bf)
