### DISCUSSION TITLE
Node becomes unschedulable due to old container images

### DISCUSSION THREAD

**Discussion by ejweber** [longhorn/longhorn#5962] [General]
This is not a bug and likely does not require a fix. However, it's an issue I ran into and I wanted to put the cause/solution somewhere public for others to find if they come across something similar.

# Symptom

The following appears in `node.status.diskStatus.<disk>.conditions`:

```
Last Transition Time: 6 days ago
Message: the disk default-disk-fd7aeb2fd64320f8(/var/lib/longhorn/) on the node eweber-v124-worker-1ae51dbb-pbxr9 has 16252928000 available, but requires reserved 20763358208, minimal 25% to schedule more replicas
Reason: DiskPressure
Status: False"
```

The message appears to be correct, but it is confusing, because this node currently has no replicas on it and probably shouldn't be even close to full.

# Cause

Using SSH, I traced the space consumption on the node to containerd's container image store:

```
-> du -cha --max-depth=1 /var/lib/rancher/rke2/agent/containerd | grep -E "M|G"
41M     ./containerd.log
43G     ./io.containerd.snapshotter.v1.overlayfs
13M     ./io.containerd.metadata.v1.bolt
14G     ./io.containerd.content.v1.content
4.1M    ./containerd-2023-05-04T14-12-51.496.log.gz
454M    ./io.containerd.grpc.v1.cri
58G     .
58G     total
```

I used crictl to verify that there were many old container images being stored on the node. This was in RKE2, so commands and container runtimes will vary:

```
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
alias crictl='/var/lib/rancher/rke2/bin/crictl'
crictl image list
```

The same information should also be available in the node's Kubernetes status (`node.status.images`). I looked there as well and saw a lot of images, but didn't try to correlate the lists.

The user is NOT expected to clean up these old container images. [Kubelet does it automatically ](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images). However, the default garbage collection thresholds ([HighThresholdPercent and LowThresholdPercent](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)) prevent any action until the disk as at least 80% full and at most 85% full. So, at ~80% full, kubelet is refusing to free up space through garbage collection and Longhorn is refusing to schedule new replicas. This situation may not resolve itself automatically until the node hits the 85% mark.

# Solution

As a quick fix, I used crictl on the node to free up space. This is probably not recommended (Kubernetes expects to have complete control over container images). This was in RKE2, so commands and container runtimes will vary:

```
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
alias crictl='/var/lib/rancher/rke2/bin/crictl'
crictl rmi --prune
```

I followed up by actually modifying the garbage collection `HighThresholdPercent` and `LowThresholdPercent`. This is done by editing the kubelet command line, and of course the "right" way to do this depends on the cluster. My cluster is running on RKE2 and is provisioned by Rancher v2.7, so I just added the arguments in the Rancher UI.

![image](https://github.com/longhorn/longhorn/assets/24213029/92d610df-ccf3-4616-9ab6-905b788b01bc)

The values I used are likely more aggressive than necessary, but I wanted to confirm the behavior, and my other node were ~65% full. After a few minutes (not sure how long exactly), the space consumed by my other nodes dropped considerably as well.

# Additional context

I use this cluster to test Longhorn. As a result, I've probably deployed dozens of Longhorn builds to it, each with its own set of container images. Most clusters won't see this much churn (and this many old images), but I definitely think it's possible for someone to run into this in production.

**Comment by karlkovaciny** [comment]
This happened to me and was the cause of much stress since I thought Longhorn was filling up my disks and had to slowly find my way to the only-visible-with-sudo containerd snapshots folder. Then learning how to get rid of snapshots when Kubernetes tells you not to is hard. On k3s you have to learn there is no kubelet and add this to `/etc/rancher/k3s/config.yaml`.
```
kubelet-arg:
  # Allow Longhorn to trigger garbage collection before it stops scheduling at 75% full
  # https://longhorn.io/docs/1.5.0/references/settings/#storage-minimal-available-percentage
  - "image-gc-high-threshold=74"
  - "image-gc-low-threshold=70"
```

**Comment by zarinbal** [comment]
@ejweber Thanks for this helpful message.

I am posting this for KubeSpray users. There  are two variables to set the limits: [Refrence](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/vars.md)

`kubelet_image_gc_high_threshold` and `kubelet_image_gc_low_threshold `

As a temporary patch, here is my ansible code to clean up and create corn task to clean up every day. 

```
---
- name: Cleanup Containerd on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Remove unused containerd images
      shell: |
        crictl rmi --prune
      ignore_errors: yes

    - name: Clear unused containerd content
      shell: |
        crictl image prune --all
      ignore_errors: yes

    - name: Clear unused containerd snapshots
      shell: |
        crictl image prune --all
      ignore_errors: yes

    - name: Restart containerd and kubelet
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - containerd
        - kubelet

    - name: Create cron job for periodic cleanup
      cron:
        name: "Periodic containerd cleanup"
        minute: "0"
        hour: "2"
        user: "root"
        job: "/usr/local/bin/cleanup-containerd.sh"

    - name: Create cleanup script
      copy:
        dest: /usr/local/bin/cleanup-containerd.sh
        mode: "0755"
        content: |
          #!/bin/bash
          crictl rmi --prune
          crictl image prune --all
          systemctl restart containerd
          systemctl restart kubelet

```
