### DISCUSSION TITLE
Recurring system backup

### DISCUSSION THREAD

**Discussion by reddec** [longhorn/longhorn#6520] [Ideas]
I think it will be nice to have Recurring System Backup out of the box. Something like regular backup, but including PVC/PV definitions.

Correct me if I am wrong, but currently there are two approaches:
- Recurring backup (normal) which requires for restoring quite some effort (due to non-deterministic volume names created by PVC):
  a. use UI for creating PV/PVC and attaching restored volumes
  b. and/or store Longhorn managed manifests somewhere else (ex: via Velero)
- Manually initiate System Backup which already includes everything (so restore is just click 'Restore' button), however, there is no way to make it recurring.

My current workaround (tested and working in prod) is a separate CronJob and curl for 1.5.2 Longhorn REST API (reversed)

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: longhorn-system-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: badouralix/curl-jq@sha256:5dc0d2e780f4098760a8678400e481249bc3c047970251c23dfb6d7ffb93e9d2
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh
              set -e  -x

              # number of backups to keep, including the current one
              KEEP="3"

              # URL for lonhorn service (controller)
              LONGHORN_URL="http://longhorn-frontend.longhorn-system.svc.cluster.local"

              BACKUP_NAME="system-backup-$(date --utc +%Y%m%d%H%M%S)"

              # create task
              curl -f -X POST -H 'Content-Type: application/json' --data-binary @- "${LONGHORN_URL}/v1/systembackups" <<EOF
              {
                  "name":"${BACKUP_NAME}",
                  "volumeBackupPolicy":"always"
              }
              EOF

              # wait for task completion
              while true; do
                  sleep 3
                  STATUS=$(curl -f "${LONGHORN_URL}/v1/systembackups" | jq -r ".data[] | select(.id == \"${BACKUP_NAME}\").state")
                  if [ "1$STATUS" = "1Completed" ] || [ "1$STATUS" = "1Ready" ]; then
                      break
                  fi
              done

              # cleanup the old backups - expected sorted output, from oldest to newest
              for BACKUPID in $(curl -f "${LONGHORN_URL}/v1/systembackups" | jq -r '.data[].id' | head -n -"$SKIP"); do
                  echo "Removing old backup ${BACKUPID}"
                  curl -f -X DELETE "${LONGHORN_URL}/v1/systembackups/${BACKUPID}"
              done
          restartPolicy: Never
```
