### DISCUSSION TITLE
[BUG]  the replica auto balance displayed in the volume details different from the configuration and UI genreal

### DISCUSSION THREAD

**Discussion by leonisir** [longhorn/longhorn#7005] [General]
version：v1.4.4
platform：arm64
install：helmv3

values.yaml
```yaml
...
defaultSettings:
  backupTarget: ~
  backupTargetCredentialSecret: ~
  allowRecurringJobWhileVolumeDetached: ~
  createDefaultDiskLabeledNodes: ~
  defaultDataPath: /opt/longhorn
  defaultDataLocality: ~
  replicaSoftAntiAffinity: ~
  replicaAutoBalance: "best-effort"
...
```

New environment installation
in pvc info
![image](https://github.com/longhorn/longhorn/assets/35453327/f8070161-6c43-47a1-b683-2b0b2baaba79)
in genreal
![image](https://github.com/longhorn/longhorn/assets/35453327/508ba500-e748-4a44-b5ec-bde7289ec69c)

sc info
```yaml
Name:            longhorn
IsDefaultClass:  Yes
Annotations:     longhorn.io/last-applied-configmap=kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            dataLocality=best-effort,fromBackup=,fsType=ext4,numberOfReplicas=2,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

```
