### DISCUSSION TITLE
Can RWX volumes have more than 1024 block size?

### DISCUSSION THREAD

**Discussion by userabcd123** [longhorn/longhorn#7113] [Q&A]
## Environment

 - Longhorn version: 1.5.1 (after this issue we quickly upgraded to 1.5.2 as we were waiting for `storageReservedPercentageForDefaultDisk` to be introduced)
 - Kubernetes version: 1.26.8
 - Node config
   - OS type and version: Debian GNU/Linux version 12
   - Kernel version: 6.1.0-13-amd64
   - CPU per node: 26
   - Memory per node: 57.9GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes:  0.660 ms latency
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare/KVM

## Additional context

We are using ext4 RWX volumes for our microservice inside of kubernetes and there were issues that we've got some data corruption, luckily it was just an image used as a logo in the dev environment, but we are concerned that this could be happening in the future in our production setup. We've also had a node that was unschedulable due to the minimum disk required being 25%. In comparison, the available disk was 24%, and pods for that specific microservice were restarted twice (which we believe was the case for this data corruption/loss). This issue happend on Friday and was noticed on Monday, since then we've:
- Upgraded Longhorn to 1.5.2
- Implemented the Prometheus alerts for Longhorn so we've notified on time before `storageReservedPercentageForDefaultDisk` is almost reached
- Implemented the backups for our volumes (But if we dont notice this kind of issue on time it will do the backups with corrupted data that is what is worrying us...)
- Created the new storageClass which had parameters to set block size to 4kB -- this worked out only for RWO volumes

We've also read that the block size being less than 4kB can lead to this, but RWX volumes could not have that much block size, they would have 1kB no matter what we've specified, we tried to create a new storage class with set parameters that would be creating the volumes with 4kB but they would still be created with 1kB(RWX ones, but for RWO it works as expected), we tried to run command which would change this inside share-manager pod for that volume but it would need to be detached for the command to run, but if its detached the pod is removed as its no longer mounted.

We assume that those were the key factors that lead to the issue, but to be sure, we would like to ask for advice or suggestion on how we can prevent this issue in the future.

Thank you in advance.

**Comment by ChiyoDragon** [comment]
I'm experiencing a similar issue in my Kubernetes environment with Longhorn. Our setup closely resembles the one described, including the use of ext4 RWX volumes, recent upgrades to Longhorn version 1.5.2, and challenges with block size configurations for RWX volumes. Additionally, we've implemented Prometheus alerts and backups, but, like the original poster, we are concerned about potential data corruption and loss.

I'll be closely monitoring this thread for any updates or solutions. It would be greatly appreciated if the community or support team could check into this matter and provide guidance on resolving or preventing such issues in the future.

Thank you in advance for your assistance!

**Comment by derekbit** [comment]
> but RWX volumes could not have that much block size, they would have 1kB no matter what we've specified, we tried to create a new storage class with set parameters that would be creating the volumes with 4kB but they would still be created with 1kB

@userabcd123 Thanks for raising the issue. Would you be able to provide the steps to reproduce or manifest? Thank you.

**Reply by userabcd123** [reply]
Unfortunately no, as this happened on 27th of October(It was on Friday) and we've noticed the issue on 30th October(Monday). This was according to Longhorn UI, as it said that last change happened on 27.10 (that it became unschedulable).

We assume the issue was that the node was unschedulable due to minimum disk space was set to 25% and we had less than that  available during that period, and in the meantime the deployment was redeployed 2-3 times while volume being degraded having only 2 replicas in healthy state.

The issue has happened on the smaller volume, we have Prometheus volume which RWO and is around 40Gi, and  RWX volume used for another service which is around 15Gi(on dev and 150Gi on prod), but issue only happened on this one smaller volume.

Also perhaps worth the mention is that FS Trim failed for those two smaller volumes around two weeks before with error that after searching it seems to indicate corruption(`structure needs cleaning` or something like that), but since everything worked and nobody complained about any errors/issues, we assumed it just did not have anything to trim(as that volume is not changed that frequently as one we use for other service or Prometheus one). Also FS trim was running smoothly for other volumes.

What are your thoughts on all this @derekbit ?

Here is the values file used for deploying Longhorn:

```
---

privateRegistry:
  createSecret: false
  registryUrl: {{ .Values.nexus_url }}
  registrySecret: registry-secret
service:
  ui:
    type: ClusterIP
  manager:
    type: ClusterIP

annotations:
  prometheus.io/longhorn-monitoring: "true"

defaultSettings:
  priorityClass: critical
  backupTarget: {{ .Values.backupTarget }}
  backupTargetCredentialSecret: minio-credentials
  backupCompressionMethod: lz4
  guaranteedInstanceManagerCPU: 10
  storageReservedPercentageForDefaultDisk: "15"

persistence:
  defaultClass: false
  defaultFsType: ext4
  defaultClassReplicaCount: 3
  defaultDataLocality: disabled
  reclaimPolicy: Delete
  migratable: false

image:
  longhorn:
    engine:
      repository: longhornio/longhorn-engine
      tag: 1.5.2
    manager:
      repository: longhornio/longhorn-manager
      tag: 1.5.2
    ui:
      repository: longhornio/longhorn-ui
      tag: 1.5.2
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: 1.5.2
    shareManager:
      repository: longhornio/longhorn-share-manager
      tag: 1.5.2
    backingImageManager:
      repository: longhornio/backing-image-manager
      tag: 1.5.2
    supportBundleKit:
      repository: longhornio/support-bundle-kit
      tag: 0.0.27
  csi:
    kubeletRootDir: /var/lib/kubelet
    attacher:
      repository: longhornio/csi-attacher
      tag: 4.2.0
    provisioner:
      repository: longhornio/csi-provisioner
      tag: 3.4.1
    nodeDriverRegistrar:
      repository: longhornio/csi-node-driver-registrar
      tag: 2.7.0
    resizer:
      repository: longhornio/csi-resizer
      tag: 1.7.0
    snapshotter:
      repository: longhornio/csi-snapshotter
      tag: 6.2.1
    livenessProbe:
      repository: livenessprobe
      tag: v2.9.0
  pullPolicy: IfNotPresent

csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2

ingress:
  enabled: true
  ingressClassName: kong
  host: longhorn-{{ .Values.dns_subdomain }}
  tls: true
  tlsSecret: {{ .Values.tlsSecret}}
  secureBackends: true
  path: /
  annotations:
      konghq.com/preserve-host: "true"
      konghq.com/protocols: https
      konghq.com/plugins: longhorn-basic-auth
      konghq.com/https-redirect-status-code: "301"

longhornManager:
  priorityClass: critical

longhornDriver:
  priorityClass: critical

longhornUI:
  replicas: 1
  priorityClass: critical

...
```
Also manifest for Storage class used for testing:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4" 
  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
```

**Comment by ChiyoDragon** [comment]
Hello @derekbit,

It appears that there hasn't been a response for some time, and we are in need of further information to address the issue effectively. Our main question is: Can RWX volumes have a block size larger than 1024?

Given the urgency of our situation and the importance of resolving this matter, we kindly request your prompt response with any insights or details that could help us move forward.

Your assistance is greatly appreciated.

**Comment by gcapozzo** [comment]
Hi, i am reopening this because is the only topic with mkfsParams and rwx keywords, i need a volume with bytes-per-inode smaller than default (mkfsParams: "-i 8096")
This only works with RWO volumes, when I create the volume with RWX this not working (I am doing df -ih to test it)
Is a bug? A RWX limitation?

**Comment by DamiaSan** [comment]
cc @derekbit

**Reply by derekbit** [reply]
@DamiaSan Please help trace the longhorn-manager CSI plugin codes and see if `mkfsParams` is correctly applied while creating a RWX volume.

**Comment by DamiaSan** [comment]
Hi @gcapozzo , in the logs of CSI plugin (longhorn-manager) you should find a row like the following one:
```
Volume <volume_name> using user and longhorn provided <file_system_type> fs creation params: <parameters>
```
Could you check if the parameters you are specifying when creating the `StorageClass` is correctly received and applied? Otherwise send to us a support bundle so that we can check it for you.
Thanks.

**Reply by gcapozzo** [reply]
Hi, with longhorn 1.7.2, these are the logs:
Created a rwo pvc and a rwx pvc from rancher UI

```
time="2025-03-14T11:46:54Z" level=info msg="CreateVolume: req: {\"capacity_range\":{\"required_bytes\":1073741824},\"name\":\"pvc-a801a105-f9df-42ce-913f-4f8f882f5afd\",\"parameters\":{\"fsType\":\"ext4\",\"mkfsParams\":\"-i 6144\",\"numberOfReplicas\":\"1\",\"staleReplicaTimeout\":\"2880\"},\"volume_capabilities\":[{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}}]}" func=csi.logGRPC file="server.go:130"
time="2025-03-14T11:46:54Z" level=info msg="CreateVolume is called with req name:\"pvc-a801a105-f9df-42ce-913f-4f8f882f5afd\" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:\"fsType\" value:\"ext4\" > parameters:<key:\"mkfsParams\" value:\"-i 6144\" > parameters:<key:\"numberOfReplicas\" value:\"1\" > parameters:<key:\"staleReplicaTimeout\" value:\"2880\" > " func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:81" component=csi-controller-server function=CreateVolume
time="2025-03-14T11:46:54Z" level=info msg="Creating a volume by API client, name: pvc-a801a105-f9df-42ce-913f-4f8f882f5afd, size: 1073741824, accessMode: , dataEngine: v1" func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:237" component=csi-controller-server function=CreateVolume
time="2025-03-14T11:46:57Z" level=info msg="CreateVolume: rsp: {\"volume\":{\"capacity_bytes\":1073741824,\"volume_context\":{\"fsType\":\"ext4\",\"mkfsParams\":\"-i 6144\",\"numberOfReplicas\":\"1\",\"staleReplicaTimeout\":\"2880\"},\"volume_id\":\"pvc-a801a105-f9df-42ce-913f-4f8f882f5afd\"}}" func=csi.logGRPC file="server.go:139"
time="2025-03-14T11:47:10Z" level=info msg="CreateVolume: req: {\"capacity_range\":{\"required_bytes\":1073741824},\"name\":\"pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669\",\"parameters\":{\"fsType\":\"ext4\",\"mkfsParams\":\"-i 6144\",\"numberOfReplicas\":\"1\",\"staleReplicaTimeout\":\"2880\"},\"volume_capabilities\":[{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":5}}]}" func=csi.logGRPC file="server.go:130"
time="2025-03-14T11:47:10Z" level=info msg="CreateVolume is called with req name:\"pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669\" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > parameters:<key:\"fsType\" value:\"ext4\" > parameters:<key:\"mkfsParams\" value:\"-i 6144\" > parameters:<key:\"numberOfReplicas\" value:\"1\" > parameters:<key:\"staleReplicaTimeout\" value:\"2880\" > " func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:81" component=csi-controller-server function=CreateVolume
time="2025-03-14T11:47:10Z" level=info msg="Creating a volume by API client, name: pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669, size: 1073741824, accessMode: rwx, dataEngine: v1" func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:237" component=csi-controller-server function=CreateVolume
time="2025-03-14T11:47:13Z" level=info msg="CreateVolume: rsp: {\"volume\":{\"capacity_bytes\":1073741824,\"volume_context\":{\"fsType\":\"ext4\",\"mkfsParams\":\"-i 6144\",\"numberOfReplicas\":\"1\",\"share\":\"true\",\"staleReplicaTimeout\":\"2880\"},\"volume_id\":\"pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669\"}}" func=csi.logGRPC file="server.go:139"
```

a801a105-f9df-42ce-913f-4f8f882f5afd is the RWO
dfa748bc-c2bc-4ec9-8523-1332860d6669 is the RWX

```
apiVersion: v1
kind: Pod
metadata:
  name: podrwo
  namespace: hsi-prod
spec:
  containers:
    - name: pod
      image: alpine
      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
      volumeMounts:
        - name: pvc
          mountPath: /data
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: rwo-test
apiVersion: v1
kind: Pod
metadata:
  name: podrwx
spec:
  containers:
    - name: pod
      image: alpine
      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
      volumeMounts:
        - name: pvc
          mountPath: /data
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: rwx-test
```

```
/ # df -ih
Filesystem              Inodes      Used Available Use% Mounted on
/dev/longhorn/pvc-a801a105-f9df-42ce-913f-4f8f882f5afd 170.8K        11    170.7K   0% /data 
```
```
/ # df -ih
Filesystem              Inodes      Used Available Use% Mounted on
10.43.144.219:/pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669 64.0K        11     64.0K   0% /data 
```

```
root@Worker-2:/home/ubuntu# tune2fs -l /dev/longhorn/pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669
tune2fs 1.46.5 (30-Dec-2021)
Filesystem volume name:   <none>
Last mounted on:          /export/pvc-dfa748bc-c2bc-4ec9-8523-1332860d6669
Filesystem UUID:          xxxxx
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              65536
Block count:              262144
Reserved block count:     0
Overhead clusters:        12949
Free blocks:              249189
Free inodes:              65525
First block:              0
Block size:               4096
Fragment size:            4096
Group descriptor size:    64
Reserved GDT blocks:      127
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Fri Mar 14 11:57:17 2025
Last mount time:          Fri Mar 14 11:57:17 2025
Last write time:          Fri Mar 14 11:57:17 2025
Mount count:              1
Maximum mount count:      -1
Last checked:             Fri Mar 14 11:57:17 2025
Check interval:           0 (<none>)
Lifetime writes:          533 kB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:	          256
Required extra isize:     32
Desired extra isize:      32
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      xxxxx
Journal backup:           inode blocks
Checksum type:            crc32c
Checksum:                 0xde6f1f08
```

```
root@Worker-3:/home/ubuntu# tune2fs -l /dev/longhorn/pvc-a801a105-f9df-42ce-913f-4f8f882f5afd 
tune2fs 1.46.5 (30-Dec-2021)
Filesystem volume name:   <none>
Last mounted on:          <not available>
Filesystem UUID:          xxxx
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              174848
Block count:              262144
Reserved block count:     0
Overhead clusters:        19781
Free blocks:              242357
Free inodes:              174837
First block:              0
Block size:               4096
Fragment size:            4096
Group descriptor size:    64
Reserved GDT blocks:      127
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         21856
Inode blocks per group:   1366
Flex block group size:    16
Filesystem created:       Fri Mar 14 11:57:30 2025
Last mount time:          Fri Mar 14 11:57:31 2025
Last write time:          Fri Mar 14 11:57:31 2025
Mount count:              1
Maximum mount count:      -1
Last checked:             Fri Mar 14 11:57:30 2025
Check interval:           0 (<none>)
Lifetime writes:          533 kB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:	          256
Required extra isize:     32
Desired extra isize:      32
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      xxxxx
Journal backup:           inode blocks
Checksum type:            crc32c
Checksum:                 0x1523eb3d
```
