### DISCUSSION TITLE
Longhorn volume failed to attach

### DISCUSSION THREAD

**Discussion by mihiruk** [longhorn/longhorn#7204] [Q&A]
following errors are thrown When adding a Longhorn volume to a deployment and starting the deployment. But the health of the.But on the Longhorn side, the volume situation appears to be healthy. The deployment is also not active.

Rancher version :- 2.6.3
Longhorn version :- v100.2.3+up1.3.2

Error :-

MountVolume.MountDevice failed for volume "pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a" : rpc error: code = Aborted desc = volume pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a share not yet available
Unable to attach or mount volumes: unmounted volumes=[vol-wn759 kube-api-access-bsk9v], unattached volumes=[vol-wn759 kube-api-access-bsk9v]: timed out waiting for the condition

The share-manager-pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a pod in the longhorn-system namespace also restarts with the following errors.

Error :-
MountVolume.SetUp failed for volume "kube-api-access-s9m7w" : failed to fetch token: Operation cannot be fulfilled on Pod "share-manager-pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a": the UID in the bound object reference (143411ab-1125-42a8-a887-21b3ce4cef62) does not match the UID in record. The object might have been deleted and then recreated

Can you please help to solve this?

Thanks

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Reply by mihiruk** [reply]
Hi 
Thanks for the prompt reply...
Can you provide us a trusted way to share the support bundle, please?
Any email address?

Thanks

**Reply by derekbit** [reply]
You can please send it to longhorn-support-bundle@suse.com.

**Reply by mihiruk** [reply]
Noted with thanks, will share 
Appreciate!

**Reply by mihiruk** [reply]
attachment was sent via email id of "bravoxavier208@gmail.com"

**Reply by derekbit** [reply]
cc @james-munson

**Reply by mihiruk** [reply]
Hello Team,

Reminder on this and If you find any clue, please update us.

Thanks

**Reply by mihiruk** [reply]
Hello Team,

Do u have any idea about this?

Thanks

**Reply by derekbit** [reply]
Sorry for the late reply.

I found the filesystem of the volume is somehow not clean. You need to fix the issue by`fsck`.

```
2023-11-24T05:52:13.256786691Z time="2023-11-24T05:52:13Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
2023-11-24T05:52:13.256816772Z time="2023-11-24T05:52:13Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
2023-11-24T05:52:13.489621180Z time="2023-11-24T05:52:13Z" level=debug msg="volume pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a device /dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a contains filesystem of format ext4" encrypted=false volume=pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a
2023-11-24T05:52:14.964733503Z time="2023-11-24T05:52:14Z" level=warning msg="failed to mount volume" encrypted=false error="'fsck' found errors on device /dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a but could not correct them: fsck from util-linux 2.36.2\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a contains a file system with errors, check forced.\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: Directory inode 152602, block #0, offset 0: directory corrupted\n\n\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.\n\t(i.e., without -a or -p options)\n" volume=pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a
2023-11-24T05:52:15.057586474Z W1124 05:52:15.057337       1 mount_helper_common.go:133] Warning: "/export/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a" is not a mountpoint, deleting
2023-11-24T05:52:15.061817730Z time="2023-11-24T05:52:15Z" level=debug msg="device /dev/mapper/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a is not an active LUKS device: failed to run cryptsetup args: [status pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a] output:  error: exit status 127"
2023-11-24T05:52:15.061843637Z time="2023-11-24T05:52:15Z" level=fatal msg="Error running start command: 'fsck' found errors on device /dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a but could not correct them: fsck from util-linux 2.36.2\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a contains a file system with errors, check forced.\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: Directory inode 152602, block #0, offset 0: directory corrupted\n\n\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.\n\t(i.e., without -a or -p options)\n."

```

**Reply by derekbit** [reply]
Please refer to https://github.com/longhorn/longhorn/issues/5037#issuecomment-1345182384.

Before executing `fsck`, please back up the volume or copy the replica directory of the volume out on each node as a backup.

Ref: https://longhorn.io/kb/troubleshooting-volume-filesystem-corruption/

**Reply by mihiruk** [reply]
Hello Team,

Thanks a lot, I will execute and let you know.

BR

**Reply by mihiruk** [reply]
Hello Team,

Glad to inform you that the issue has been successfully resolved after executing the above CMDs, thank you very much for the support.

**Reply by derekbit** [reply]
@mihiruk Thanks for the update :)

**Reply by mihiruk** [reply]
@derekbit  can you tell what could be the cause of this problem?
also, this is a government-affiliated system so have to ensure the system is up and running without occurring such issues.
Can you suggest the necessary congurations should be setup to stop this kind of problem from happening in the future?

**Reply by derekbit** [reply]
@mihiruk Did the cluster experience unexpected power outage or network disconnection?

**Reply by mihiruk** [reply]
dear @derekbit no such cases have been reported,
Can something like this happen when memory utilization increases?

**Reply by derekbit** [reply]
> Can something like this happen when memory utilization increases?

I didn't see an unclean filesystem when memory utilization increased.

When a filesystem becomes unclean, it might be due to
- Unexpected power outage
- Unexpected network disconnection between engine and the downstream replicas
- Crash of instance-manager pod or share-manager pod (or NFS server)
- Hardware issues, e.g. memory or underlying disk silent corruption

If the issue happens again, can you help create a support bundle? Then, we can check if there is any clue. Thank you.

cc @shuo-wu @PhanLe1010 @innobead

**Reply by mihiruk** [reply]
hello @derekbit Hope u are doing all good :)
we have experienced the above issue once again :( 
![WhatsApp Image 2024-01-11 at 09 21 25_46bea771](https://github.com/longhorn/longhorn/assets/34314471/764bff11-52d5-4a83-b1f1-3e7bc2b3447e)

**Reply by mihiruk** [reply]
I downloaded the support bundle, shall i  share it with you?

**Reply by derekbit** [reply]
Sure. Please send to longhorn-support-bundle@suse.com.

cc @james-munson for the community coordinator in this sprint.

**Reply by mihiruk** [reply]
Ok , please check the following logs as well
Thank you so much.

time="2024-01-11T03:49:33Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-01-11T03:49:33Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-01-11T03:49:34Z" level=debug msg="volume pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a device /dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a contains filesystem of format ext4" encrypted=false volume=pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a
time="2024-01-11T03:49:34Z" level=warning msg="failed to mount volume" encrypted=false error="'fsck' found errors on device /dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a but could not correct them: fsck from util-linux 2.36.2\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a contains a file system with errors, check forced.\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: Invalid inode number for '.' in directory inode 30886.\n\n\n/dev/longhorn/pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.\n\t(i.e., without -a or -p options)\n" volume=pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a

**Reply by james-munson** [reply]
The same procedure as before should again clear the filesystem corruption and make it operational again.  We'll take a look at the support bundle to see whether there is any suggestion of what might have led to this.

**Reply by james-munson** [reply]
Nothing jumps out in the logs, although that is hard to say definitively.  Grepping for "level=error" along with pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a gives more than 92,000 lines.

The volume name is the same as the previous incident.  In volumes.yaml, the entry for the volume shows:
```yaml
  objectmeta:
    name: minio-06-1-2024
    generatename: ""
    namespace: longhorn-system
    selflink: ""
    uid: a1898e33-21b7-4483-9c16-107f8eda11bf
    resourceversion: "186783640"
    generation: 5
    creationtimestamp: "2024-01-11T06:53:33Z"
    deletiontimestamp: null
    deletiongraceperiodseconds: null
    labels:
      backup-volume: pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a
      longhornvolume: minio-06-1-2024
      recurring-job-group.longhorn.io/default: enabled
    annotations: {}
    ownerreferences: []
    finalizers:
      - longhorn.io
    clustername: ""
    managedfields:
      - manager: longhorn-manager
        operation: Update
        apiversion: longhorn.io/v1beta2
        time: "2024-01-11T06:53:33Z"
        fieldstype: FieldsV1
        fieldsv1: stripped by yq
        subresource: ""
  spec:
    size: 21474836480
    frontend: blockdev
    frombackup: nfs://192.168.189.176:/forms/longhorn-backup?backup=backup-5dbedf3b17ab49f6&volume=pvc-3ca6f4fa-a75c-4a1d-b105-1d920e5aee7a
...
```
Is that the problematic volume (i.e. the corruption may have been pull from the backup)?  Or is it a restore done in lieu of the `fsck` to fix the corruption?
