### DISCUSSION TITLE
"Healthy" volumes  show "Replica Scheduling Failure" although nodes are available and schedulable?

### DISCUSSION THREAD

**Discussion by johanneskastl** [longhorn/longhorn#7226] [Q&A]
- Three node k3s cluster with longhorn 1.5.3 (updated from 1.3.x IIRC over the last years)
- All nodes are shown as available and schedulable
- All nodes have enough free space
- 13 volumes, where 3 are degraded
- 4 healthy volumes that show `Replica Scheduling Failure`

I find no hint why the healthy volumes are showing this replication failure. The event log for the volumes is empty (no data).

Maybe related, the engine upgrades for the healthy issues are running endlessly and never finished, so I fear there is an underlying issue somewhere.

Any idea where to start looking?

Kind Regards,
Johannes

**Comment by derekbit** [comment]
Can you check the logs of longhorn-manager pods?

**Reply by johanneskastl** [reply]
Yes, I can. There are many message and (seems) error message. What am I looking for?

Here are some that sounded related to me:

```
time="2023-11-30T09:37:33Z" level=error msg="Failed to sync Longhorn volume" func=controller.handleReconcileErrorLogging file="utils.go:72" Volume=longhorn-system/pvc-ecc88002-e245-4012-a794-2ffcdd36699e controller=longhorn-volume error="failed to sync longhorn-system/pvc-ecc88002-e245-4012-a794-2ffcdd36699e: create not allowed while custom resource definition is terminating" node=XXX
```

```
time="2023-11-30T09:37:33Z" level=debug msg="Ignoring recurring job labels on Volume pvc-2f154d71-1b0b-4e34-84da-8da39f7b5864 PVC teleport-cluster due to missing source label" func="controller.(*VolumeController).syncPVCRecurringJobLabels" file="volume_controller.go:3692" controller=longhorn-volume node=XXX
```

```
time="2023-11-30T09:37:35Z" level=error msg="Failed to sync Longhorn share manager" func=controller.handleReconcileErrorLogging file="utils.go:72" ShareManager=longhorn-system/pvc-c0530051-
dd1d-4dad-a729-ccaf1ccae2e5 controller=longhorn-share-manager error="failed to sync longhorn-system/pvc-c0530051-dd1d-4dad-a729-ccaf1ccae2e5: volumeattachment.longhorn.io \"pvc-c0530051-dd1d-4dad-a729-ccaf1ccae2e5\" not found" node=XXX
```

```
```

**Comment by johanneskastl** [comment]
No ideas, anyone?

**Reply by grzleadams** [reply]
Is this still happening for you? I'm seeing it on our instance and will open an issue if you haven't resolved it.

**Reply by grzleadams** [reply]
Nevermind, looks like it's already on the radar: https://github.com/longhorn/longhorn/issues/7243

**Reply by johanneskastl** [reply]
I could not resolve this. I wanted to change some things in the cluster anyway, so I tore it down and will build it up from scratch.

**Reply by innobead** [reply]
There should be some reasons for the volume status condition. Have you seen anything?

[/controller/volume_controller.go#L1797-L1806](https://github.com/longhorn/longhorn-manager/blob/a568043026841264d9c98d9ca5a228fb94774eca/controller/volume_controller.go#L1797-L1806)
```go
		if len(aggregatedReplicaScheduledError) == 0 {
			aggregatedReplicaScheduledError.Append(util.NewMultiError(longhorn.ErrorReplicaScheduleSchedulingFailed))
		}
		failureMessage = aggregatedReplicaScheduledError.Join()
		scheduledCondition := types.GetCondition(v.Status.Conditions, longhorn.VolumeConditionTypeScheduled)
		if scheduledCondition.Status == longhorn.ConditionStatusFalse {
			v.Status.Conditions = types.SetCondition(v.Status.Conditions,
				longhorn.VolumeConditionTypeScheduled, longhorn.ConditionStatusFalse,
				scheduledCondition.Reason, failureMessage)
		}
```

**Reply by grzleadams** [reply]
Nope, the volume is working just fine (other than reporting the scheduling failure). I noticed that the volume _does_ have two sets of conditions associated with it that appear identical (except that one's `type` is capitalized and one isn't, with the capitalized one being "correct"):
```
  conditions:                                                                                            
  - lastProbeTime: ""
    lastTransitionTime: "2022-04-25T21:38:33Z"
    message: ""
    reason: ""
    status: "False"
    type: restore
  - lastProbeTime: ""
    lastTransitionTime: "2024-02-19T17:36:16Z"
    message: ""
    reason: ReplicaSchedulingFailure
    status: "False"
    type: scheduled
  - lastProbeTime: ""
    lastTransitionTime: "2022-04-25T21:38:33Z"
    message: ""
    reason: ""
    status: "False"
    type: toomanysnapshots
  - lastProbeTime: ""
    lastTransitionTime: "2024-02-19T18:21:24Z"
    message: ""
    reason: ""
    status: "False"
    type: WaitForBackingImage
  - lastProbeTime: ""
    lastTransitionTime: "2024-02-19T18:21:24Z"
    message: ""
    reason: ""
    status: "False"
    type: TooManySnapshots
  - lastProbeTime: ""
    lastTransitionTime: "2024-02-19T18:21:25Z"
    message: ""
    reason: ""
    status: "True"
    type: Scheduled
  - lastProbeTime: ""
    lastTransitionTime: "2024-02-19T18:21:24Z"
    message: ""
    reason: ""
    status: "False"
    type: Restore
```
On 1.4.4, for a volume without this problem, there's just one set (the lower-case one):
```
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2023-07-19T19:16:52Z"
    message: ""
    reason: ""
    status: "False"
    type: toomanysnapshots
  - lastProbeTime: ""
    lastTransitionTime: "2023-07-19T19:16:52Z"
    message: ""
    reason: ""
    status: "True"
    type: scheduled
  - lastProbeTime: ""
    lastTransitionTime: "2023-07-19T19:16:52Z"
    message: ""
    reason: ""
    status: "False"
    type: restore
```
Is it possible the UI is pulling the older conditions or something?

Edit: For context, this only started occurring after a 1.3.x -> 1.4.4 -> 1.5.3 upgrade.
