### DISCUSSION TITLE
Installing on Talos v1.6.1

### DISCUSSION THREAD

**Discussion by Hr46ph** [longhorn/longhorn#7562] [Q&A] [answered]
I am installing on a Talos cluster. I have the required system extensions installed:
```
# talosctl -n 10.1.1.43 services
NODE          SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
10.1.1.43   apid         Running   OK       3m34s ago     Health check successful
10.1.1.43   containerd   Running   OK       3m37s ago     Health check successful
10.1.1.43   cri          Running   OK       3m34s ago     Health check successful
10.1.1.43   dashboard    Running   ?        3m36s ago     Process Process(["/sbin/dashboard"]) started with PID 2552
10.1.1.43   ext-iscsid   Running   ?        3m33s ago     Started task ext-iscsid (PID 2759) for container ext-iscsid
10.1.1.43   ext-tgtd     Running   ?        3m34s ago     Started task ext-tgtd (PID 2714) for container ext-tgtd
10.1.1.43   kubelet      Running   OK       3m19s ago     Health check successful
10.1.1.43   machined     Running   OK       3m42s ago     Health check successful
10.1.1.43   udevd        Running   OK       3m41s ago     Health check successful
```
and:
```
# talosctl -n 10.1.1.43 get extensions
NODE          NAMESPACE   TYPE              ID   VERSION   NAME               VERSION
10.1.1.43   runtime     ExtensionStatus   0    1         intel-ucode        20231114
10.1.1.43   runtime     ExtensionStatus   1    1         iscsi-tools        v0.1.4
10.1.1.43   runtime     ExtensionStatus   2    1         util-linux-tools   $VERSION
10.1.1.43   runtime     ExtensionStatus   3    1         schematic          bd60d6570ed0ee7e
```
I created the namespace for Longhorn privileged like this:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
```
However, longhorn managers go into a crashloop:
```
longhorn-system   longhorn-driver-deployer-7cc7cc8559-fn8gl   0/1     Init:0/1           0               77s     10.244.1.4    worker-01    <none>           <none>
longhorn-system   longhorn-manager-4drtx                      0/1     CrashLoopBackOff   3 (14s ago)     77s     10.244.1.3    worker-01    <none>           <none>
longhorn-system   longhorn-manager-5gprv                      0/1     CrashLoopBackOff   3 (22s ago)     77s     10.244.5.4    worker-03    <none>           <none>
longhorn-system   longhorn-manager-w5s55                      0/1     CrashLoopBackOff   3 (15s ago)     77s     10.244.4.3    worker-02    <none>           <none>
longhorn-system   longhorn-ui-5d65c99c9b-5nhj7                1/1     Running            0               77s     10.244.5.3    worker-03    <none>           <none>
longhorn-system   longhorn-ui-5d65c99c9b-pnfb5                1/1     Running            0               77s     10.244.4.4    worker-02    <none>           <none>
```
And the logs show:
```
time="2024-01-06T21:15:08Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: invalid mount namespace /host/proc/8165/ns/mnt: failed to execute: nsenter [--mount=/host/proc/8165/ns/mnt mount], output , stderr nsenter: failed to execute mount: No such file or directory\n: exit status 127" func=app.DaemonCmd.func1 file="daemon.go:83"
```
I'm not sure if the reason it can't find iscsi tools is due to the invalid mount namespace?

In any case, I have an extra disk added:
``10.1.1.41   /dev/sdb1    536.61     3.78       532.83          0.70%          /var/mnt/longhorn`

Its mounted here:
```
        disks:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/longhorn
```
and here:
```
    machine:
        kubelet:
            image: ghcr.io/siderolabs/kubelet:v1.29.0
            extraMounts:
                - destination: /var/lib/longhorn
                  type: bind
                  source: /var/mnt/longhorn
                  options:
                    - bind
                    - rshared
                    - rw
```
I have no idea, any help with this would be appreciated!

Thanks!
