### DISCUSSION TITLE
[QUESTION] Need additional configs to run longhorn at single node k8s

### DISCUSSION THREAD

**Discussion by talkraghu** [longhorn/longhorn#7819] [General]
Longhorn version: 1.5.3
Kubernetes version: v1.26.5
Node config
OS type and version : RHEL
Kernel version
CPU per node: 16
Memory per node: 80
Disk type: openstack volume
Network bandwidth and latency between the nodes:
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): openstack

Additional context
I am trying longhorn as a beginner. I tried installing the longhorn at a single node k8s node.

There are 3 instances of attacher, provisoner, snapshotter and resizer pods that get deployed. I believe one instance of each is enough here for single node deployment. 
Can someone share the configs that are to be passed to k8s manifest file (longhorn.yaml) ?

```

[root@rags1node-k8sc-node1-1 longhorn]# kubectl get pods -nlonghorn-system -owide
NAME                                                READY   STATUS    RESTARTS   AGE     IP              NODE              NOMINATED NODE   READINESS GATES
csi-attacher-785fd6545b-hhtxw                       1/1     Running   0          3m40s   10.233.118.42   rags1node-node1   <none>           <none>
csi-attacher-785fd6545b-nvxp6                       1/1     Running   0          3m40s   10.233.118.49   rags1node-node1   <none>           <none>
csi-attacher-785fd6545b-v62xp                       1/1     Running   0          3m40s   10.233.118.45   rags1node-node1   <none>           <none>
csi-provisioner-8658f9bd9c-bpplq                    1/1     Running   0          3m40s   10.233.118.46   rags1node-node1   <none>           <none>
csi-provisioner-8658f9bd9c-lptlf                    1/1     Running   0          3m40s   10.233.118.41   rags1node-node1   <none>           <none>
csi-provisioner-8658f9bd9c-x8f9j                    1/1     Running   0          3m40s   10.233.118.43   rags1node-node1   <none>           <none>
csi-resizer-68c4c75bf5-lcjl2                        1/1     Running   0          3m40s   10.233.118.51   rags1node-node1   <none>           <none>
csi-resizer-68c4c75bf5-mchgv                        1/1     Running   0          3m40s   10.233.118.47   rags1node-node1   <none>           <none>
csi-resizer-68c4c75bf5-qzs2p                        1/1     Running   0          3m40s   10.233.118.50   rags1node-node1   <none>           <none>
csi-snapshotter-7c466dd68f-bmhpc                    1/1     Running   0          3m40s   10.233.118.33   rags1node-node1   <none>           <none>
csi-snapshotter-7c466dd68f-d5k82                    1/1     Running   0          3m40s   10.233.118.48   rags1node-node1   <none>           <none>
csi-snapshotter-7c466dd68f-wlhh8                    1/1     Running   0          3m40s   10.233.118.44   rags1node-node1   <none>           <none>
engine-image-ei-68f17757-f8j2j                      1/1     Running   0          3m52s   10.233.118.39   rags1node-node1   <none>           <none>
instance-manager-88f087c950fe49d5871dede68b17cea0   1/1     Running   0          3m20s   10.233.118.35   rags1node-node1   <none>           <none>
longhorn-csi-plugin-dxrlp                           3/3     Running   0          3m39s   10.233.118.55   rags1node-node1   <none>           <none>
longhorn-driver-deployer-7d5dc67667-nwg4h           1/1     Running   0          3m58s   10.233.118.32   rags1node-node1   <none>           <none>
longhorn-manager-lntj4                              1/1     Running   0          3m58s   10.233.118.52   rags1node-node1   <none>           <none>
longhorn-ui-85cc67494f-ngxmt                        1/1     Running   0          3m58s   10.233.118.36   rags1node-node1   <none>           <none>
[root@rags1node-k8sc-node1-1 longhorn]# 

```

**Comment by talkraghu** [comment]
Got the same.. The CSI_ATTACHER_REPLICA_COUNT, CSI_PROVISIONER_REPLICA_COUNT, CSI_RESIZER_REPLICA_COUNT and CSI_SNAPSHOTTER_REPLICA_COUNT has to be set to 1 at the longhorn-driver-deployer

```
      containers:
        - name: longhorn-driver-deployer
          image: longhornio/longhorn-manager:v1.5.3
          imagePullPolicy: IfNotPresent
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - "longhornio/longhorn-manager:v1.5.3"
          - --manager-url
          - http://longhorn-backend:9500/v1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: CSI_ATTACHER_IMAGE
            value: "longhornio/csi-attacher:v4.2.0"
          - name: CSI_PROVISIONER_IMAGE
            value: "longhornio/csi-provisioner:v3.4.1"
          - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
            value: "longhornio/csi-node-driver-registrar:v2.7.0"
          - name: CSI_RESIZER_IMAGE
            value: "longhornio/csi-resizer:v1.7.0"
          - name: CSI_SNAPSHOTTER_IMAGE
            value: "longhornio/csi-snapshotter:v6.2.1"
          - name: CSI_LIVENESS_PROBE_IMAGE
            value: "longhornio/livenessprobe:v2.9.0"
          - name: CSI_ATTACHER_REPLICA_COUNT
            value: "1"
          - name: CSI_PROVISIONER_REPLICA_COUNT
            value: "1"
          - name: CSI_RESIZER_REPLICA_COUNT
            value: "1"
          - name: CSI_SNAPSHOTTER_REPLICA_COUNT
            value: "1"

```
