### DISCUSSION TITLE
aws-secret not found

### DISCUSSION THREAD

**Discussion by Hr46ph** [longhorn/longhorn#7837] [Q&A] [answered]
I installed a cluster from scratch with Talos 1.6.4 and installed Longhorn 1.6.0 (no upgrade, fresh install).

I add a secret called minio-secret with the following contents (redacted of course):

```
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bla=
  AWS_SECRET_ACCESS_KEY: bla==
  AWS_ENDPOINTS: bla=
```
And in General settings I add the  secret name and backup target to my S3 Bucket and location.

I've done this before on the 1.6.0-RC versions and this worked before so I am puzzled ... I now get this message:

`failed to get default backup target client on longhornio/longhorn-engine:v1.6.0: secret "aws-secret" not found`

I figured oke maybe I didn't use 'minion-secret' and I changed that. So I rename it, apply it and change it in settings to 'aws-secret'. I now have 2 secrets:
```
kubectl get secrets -n longhorn-system
NAME                             TYPE                 DATA   AGE
aws-secret                       Opaque               3      19h
longhorn-webhook-ca              kubernetes.io/tls    2      22h
longhorn-webhook-tls             kubernetes.io/tls    2      22h
minio-secret                     Opaque               3      19h
sh.helm.release.v1.longhorn.v1   helm.sh/release.v1   1      22h
```
Problem is, its still giving that same error message?

Any ideas why that doesn't work anymore?
