### DISCUSSION TITLE
storing replicas on control nodes

### DISCUSSION THREAD

**Discussion by Hr46ph** [longhorn/longhorn#7879] [Q&A] [answered]
I have a 7 node cluster, 3 control planes 4 workers. Each node has 512 GiB SSD so I'm somewhat limited. I dont want to use my control nodes as workers, but I would like to use their storage for replicas.

If this is possible, can someone help me how I can do this? I did a quick search already but if theres a good guide out there please let me know.

Thanks!

**Comment by ctraber** [comment]
Try the follwoing:

Taint control plane nodes e.g. 
`kubectl taint node node1...2...3 node-role.kubernetes.io/control-plane=true:NoSchedule`

Then change the setting in Longhorn UI, like in the screenshot:

<img width="1082" alt="Screenshot 2024-02-07 at 13 23 13" src="https://github.com/longhorn/longhorn/assets/24205688/8648e47b-7c15-4239-bc37-1dae64200a5f">

Works for my setup.

**Reply by Hr46ph** [reply]
Thanks! Sounds easy enough.

Control nodes are already tainted. I checked `kubectl describe node control-01`:
`Taints:             node-role.kubernetes.io/control-plane:NoSchedule`
All three have that set.

In Longhorn I set the field as per your example. It says volumes should be detached before modifying toleration settings, so I drained all workers and even rebooted the nodes. Uncordoned afterwards. When everything was back up, the Longhorn dashboard still only shows 1.6 TiB (4x ~ 400 GiB) from the worker nodes. I expected to see 7 nodes and have ~ 2.8 TiB available.

What can I check to see if its actually picked up the settings?

**Reply by ctraber** [reply]
Can you check if the longhorn pods are running on your control plane nodes.

**Reply by ctraber** [reply]
Just ckecked my setup...
Additionally I have also added the same toleration to longhorn-manage in helm.

**Reply by Hr46ph** [reply]
```
kc get pods -n longhorn-system -o wide | grep 'control-'
csi-attacher-57bc89bccf-gp5mb                       1/1     Running   0             42m   10.244.3.197   control-02   <none>           <none>
csi-attacher-57bc89bccf-npvw4                       1/1     Running   0             43m   10.244.1.147   control-01   <none>           <none>
csi-provisioner-cc988b87c-4rcvq                     1/1     Running   0             42m   10.244.3.4     control-02   <none>           <none>
csi-provisioner-cc988b87c-6jktj                     1/1     Running   0             43m   10.244.1.26    control-01   <none>           <none>
csi-resizer-66c78b47bb-qqnz5                        1/1     Running   0             42m   10.244.3.180   control-02   <none>           <none>
csi-resizer-66c78b47bb-sftpc                        1/1     Running   0             43m   10.244.1.29    control-01   <none>           <none>
csi-snapshotter-6f987b4d44-gnck4                    1/1     Running   0             43m   10.244.1.134   control-01   <none>           <none>
csi-snapshotter-6f987b4d44-wm2mk                    1/1     Running   0             42m   10.244.3.167   control-02   <none>           <none>
engine-image-ei-acb7590c-75kn2                      1/1     Running   0             43m   10.244.3.112   control-02   <none>           <none>
engine-image-ei-acb7590c-nh8c7                      1/1     Running   0             42m   10.244.1.151   control-01   <none>           <none>
engine-image-ei-acb7590c-sbs68                      1/1     Running   0             43m   10.244.2.109   control-03   <none>           <none>
longhorn-csi-plugin-5nmd9                           3/3     Running   5 (42m ago)   43m   10.244.2.235   control-03   <none>           <none>
longhorn-csi-plugin-brqfn                           3/3     Running   2 (42m ago)   42m   10.244.1.212   control-01   <none>           <none>
longhorn-csi-plugin-gmc44                           3/3     Running   5 (42m ago)   43m   10.244.3.94    control-02   <none>           <none>
```

In values.yaml I find these, can you provide a little bit more info on what toleration you have set for longhorn-manager with Helm?

```
global:
  cattle:
  ┊ systemDefaultRegistry: ""
  ┊ windowsCluster:
  ┊ ┊ # Enable this to allow Longhorn to run on the Rancher deployed Windows cluster
  ┊ ┊ enabled: false
  ┊ ┊ # Tolerate Linux node taint
  ┊ ┊ tolerations:
  ┊ ┊ - key: "cattle.io/os"
  ┊ ┊ ┊ value: "linux"
  ┊ ┊ ┊ effect: "NoSchedule"
  ┊ ┊ ┊ operator: "Equal"
  ┊ ┊ # Select Linux nodes
  ┊ ┊ nodeSelector:
  ┊ ┊ ┊ kubernetes.io/os: "linux"
  ┊ ┊ # Recognize toleration and node selector for Longhorn run-time created components
  ┊ ┊ defaultSetting:
  ┊ ┊ ┊ taintToleration: cattle.io/os=linux:NoSchedule
  ┊ ┊ ┊ systemManagedComponentsNodeSelector: kubernetes.io/os:linux
```

and this part:
```
longhornManager:
  log:
  ┊ ## Allowed values are `plain` or `json`.
  ┊ format: plain
  priorityClass: ~
  tolerations: []
  ## If you want to set tolerations for Longhorn Manager DaemonSet, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector: {}
  ## If you want to set node selector for Longhorn Manager DaemonSet, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"
  serviceAnnotations: {}
  ## If you want to set annotations for the Longhorn Manager service, delete the `{}` in the line above
  ## and uncomment this example block
  #  annotation-key1: "annotation-value1"
  #  annotation-key2: "annotation-value2"
```

Cheers!

**Reply by ctraber** [reply, marked as answer]
```yaml
longhornManager:
  log:
    # -- Format of Longhorn Manager logs. (Options: "plain", "json")
    format: plain
  # -- PriorityClass for Longhorn Manager.
  priorityClass: *defaultPriorityClassNameRef
  # -- Toleration for Longhorn Manager on nodes allowed to run Longhorn Manager.
  # tolerations: []
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
 ...
 ```
