### DISCUSSION TITLE
UI error msg: Request failed with status code 502

### DISCUSSION THREAD

**Discussion by mingan666** [longhorn/longhorn#8146] [Q&A]
I'm trying to setup longhorn on k3s cluster with help of helm.
I've tried to follow the instructions on https://longhorn.io/docs/1.6.0/deploy/install/install-with-helm/
The only change I made to the values is to enable access outside the cluster:
```
service:
  ui:
    type: LoadBalancer
    nodePort: null
```
I then created an ingress:
```
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.example.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
```
The frontend is loaded, but it seems like it is not able to use the needed api calls?
I get several "Request failed with status code 502" messages when loading the page or when changing tabs (Node, Volume):
![image](https://github.com/longhorn/longhorn/assets/11653241/f7e00451-7d72-4561-a1c9-79f3c46a829e)

The browser network inspect shows errors like this:
![image](https://github.com/longhorn/longhorn/assets/11653241/60a3dff6-3c7c-46b4-ad36-758ec7ba61f2)

I started with testing testing with ssl redirect (which I use on my other ingresses) with the same errors, but I thought I'd try this as well.
