### DISCUSSION TITLE
RWX : Affinity of Zone

### DISCUSSION THREAD

**Discussion by kevinono62** [longhorn/longhorn#8255] [Ideas]
Hello,

I'm using a multizone Kubernetes cluster (500 km apart), and I've noticed application slowness when an application connects to a volume (RWX) in the remote zone.

![image](https://github.com/longhorn/longhorn/assets/16718366/7798d753-44ab-4373-ae74-f63fd54a3e44)

However, performance is good when connecting to a volume (RWX) in the same zone:

![image](https://github.com/longhorn/longhorn/assets/16718366/52ad7508-9d9f-4164-877c-3efa443c19dd)

I think it would be interesting to add a zone affinity preference for the creation of the "share-manager" pod.

```yaml
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - zone2
        weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - zone1
            - zone2
```

I suggest setting the zone preference when creating the volume.

I wish you a beautiful day.

Best Regards
