### DISCUSSION TITLE
Longhorn can't be installed despite extensions being available...

### DISCUSSION THREAD

**Discussion by o10s** [longhorn/longhorn#8256] [Q&A] [answered]
Hello everyone I need help cause I have been at it for 10 hours straight and can't have it working...

So I have installed talos on a single node bare metal using the following image:
[factory.talos.dev/installer/954a8ed7acae15ec71e8df744294f0dacbe6458f005a3da880902d83034c44c8:v1.6.7](https://factory.talos.dev/image/954a8ed7acae15ec71e8df744294f0dacbe6458f005a3da880902d83034c44c8/v1.6.7/metal-amd64.iso)

This contains the following:
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/thunderbolt
            - siderolabs/i915-ucode
            - siderolabs/realtek-firmware
            - siderolabs/util-linux-tools
            - siderolabs/intel-ice-firmware
            - siderolabs/iscsi-tools
```

I have also changed my installer like so: 
```
install:
  disk: /dev/nvme0n1
  image: factory.talos.dev/installer/954a8ed7acae15ec71e8df744294f0dacbe6458f005a3da880902d83034c44c8:v1.6.7
  wipe: true
```

I have also issued the following command to my node:
```
talosctl --talosconfig=./talosconfig upgrade --image factory.talos.dev/installer/954a8ed7acae15ec71e8df744294f0dacbe6458f005a3da880902d83034c44c8:v1.6.7 -n 10.0.0.31 --preserve
```

Now all of this comes from the documentation available here: [https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#example-bare-metal-with-image-factory](https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#example-bare-metal-with-image-factory)

For longhorn to work I have also allowed the longhorn-system ns to run restricted pods following this doc: [https://www.talos.dev/v1.6/kubernetes-guides/configuration/pod-security/](https://www.talos.dev/v1.6/kubernetes-guides/configuration/pod-security/)

I "Think" I have done everything according to the docs, and have followed what I need to follow... however longhorn always complains... no matter what I do... the error is this one: 
`
time="2024-03-26T14:28:53Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: invalid mount namespace /host/proc/7280/ns/mnt: failed to execute: nsenter [--mount=/host/proc/7280/ns/mnt mount], output , stderr nsenter: failed to execute mount: No such file or directory\n: exit status 127" func=app.DaemonCmd.func1 file="daemon.go:83"`

I am REALLY lost and I have NO IDEA what to do now... cluster is down... so yeah it is severely making me angry...

Please send some help !
Cheers !
