### DISCUSSION TITLE
BUG : Exporting a Volume from a Single Replica.

### DISCUSSION THREAD

**Discussion by kevinono62** [longhorn/longhorn#8270] [General]
Hello,

I use longhorn version 1.6.0.

I'm using the following documentation to retrieve data from a replica: https://longhorn.io/docs/1.6.0/advanced-resources/data-recovery/export-from-replica/

And I have this error in the container logs:

For longhorn 1.6.0 

The libqcow.so.1 library is missing

Log extract:

```
+ set -e
+ mount --rbind /host/dev /dev
+ volume=site-2a63ddfd
+ size=1073741824
Use default frontend TGT block device
+ frontend=
+ '[' -z site-2a63ddfd ']'
+ '[' -z 1073741824 ']'
+ '[' -z ']'
+ echo Use default frontend TGT block device
+ frontend=tgt-blockdev
+ exec longhorn-instance-manager daemon
+ start
+ set +e
+ true
+ /usr/local/bin/grpc_health_probe -addr localhost:8500
longhorn-instance-manager: error while loading shared libraries: libqcow.so.1: cannot open shared object file: No such file or directory
```

On longhorn 1.5.0 and longhorn 1.4.0

```
+ set -e
+ mount --rbind /host/dev /dev
+ volume=site-2a63ddfd
+ size=1073741824
+ frontend=
+ '[' -z site-2a63ddfd ']'
+ '[' -z 1073741824 ']'
+ '[' -z ']'
+ echo Use default frontend TGT block device
Use default frontend TGT block device
+ frontend=tgt-blockdev
+ exec longhorn-instance-manager daemon
+ start
+ set +e
+ true
+ /usr/local/bin/grpc_health_probe -addr localhost:8500
time="2024-03-28T15:56:32Z" level=info msg="Storing process logs at path: /var/log/instances"
[longhorn-instance-manager] time="2024-03-28T15:56:32Z" level=info msg="Instance Manager listening to localhost:8500"
timeout: failed to connect service "localhost:8500" within 1s
+ [[ 2 -eq 0 ]]
+ sleep 1
+ true
+ /usr/local/bin/grpc_health_probe -addr localhost:8500
status: SERVING
+ [[ 0 -eq 0 ]]
+ echo longhorn instance manager is ready
longhorn instance manager is ready
+ break
+ set -e
+ tgtd -f
+ longhorn-instance-manager process create --name site-2a63ddfd-r --binary /usr/local/bin/longhorn --port-count 15 --port-args --listen,localhost: -- replica /volume/ --size 1073741824
+ tee /var/log/tgtd.log
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
[longhorn-instance-manager] time="2024-03-28T15:56:34Z" level=info msg="Process Manager: prepare to create process site-2a63ddfd-r"
[longhorn-instance-manager] time="2024-03-28T15:56:34Z" level=info msg="Process Manager: created process site-2a63ddfd-r"
{
        "name": "site-2a63ddfd-r",
        "binary": "/usr/local/bin/longhorn",
        "args": [
                "replica",
                "/volume/",
                "--size",
                "1073741824",
                "--listen",
                "localhost:10000"
        ],
        "portCount": 15,
        "portArgs": [
                "--listen,localhost:"
        ],
        "processStatus": {
                "state": "starting",
                "errorMsg": "",
                "portStart": 10000,
                "portEnd": 10014
        },
        "deleted": false
}
+ sleep 5
[site-2a63ddfd-r] time="2024-03-28T15:56:34Z" level=info msg="Listening on data server localhost:10001"
[site-2a63ddfd-r] time="2024-03-28T15:56:34Z" level=info msg="Listening on sync agent server localhost:10002"
time="2024-03-28T15:56:34Z" level=info msg="Listening on gRPC Replica server localhost:10000"
[site-2a63ddfd-r] time="2024-03-28T15:56:34Z" level=info msg="Listening on sync localhost:10002"
[longhorn-instance-manager] time="2024-03-28T15:56:34Z" level=info msg="Process site-2a63ddfd-r has started at localhost:10000"

```

### **On longhorn 1.3.0 and longhorn 1.2.0  the documentation it works fine.**

For those interested, I have made a pod kubernetes version of the docker run that could be added to the documentation.

````
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-recovery-replicas
spec:
  containers:
  - name: longhorn-engine
    image: longhornio/longhorn-engine:v1.2.0
    command: ["launch-simple-longhorn", "site-2a63ddfd", "1073741824"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /host/dev
    - name: proc
      mountPath: /host/proc
    - name: volume
      mountPath: /volume
  nodeName: worker1
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: proc
    hostPath:
      path: /proc
  - name: volume
    hostPath:
      path: /var/lib/longhorn/replicas/site-2a63ddfd

````

Have a nice day,
Best Regards
