### DISCUSSION TITLE
[IMPROVEMENT] UI does not find credentials for Backblaze B2 s3-compatible storage for backup

### DISCUSSION THREAD

**Discussion by aagrxyz** [longhorn/longhorn#8594] [General]
## Describe the bug

Adding s3 backup target and the secret, still give an error message in the backup tab in the UI

## To Reproduce

1. Install k3s on a single node, with longhorn
2. Create a secret as follows:
3. 
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-b2
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <redacted>
  AWS_SECRET_ACCESS_KEY: <redacted>
  AWS_ENDPOINTS: <redacted>
---
```

4. Go to UI and set backup target as s3://xyz@us-east-005/ and set secret as longhorn-b2, click Save
5. Error in the UI page

```
failed to get default backup target client on longhornio/longhorn-engine:v1.6.0: could not access s3 without credential secret
```

## Expected behavior

The UI should not show any errors

## Support bundle for troubleshooting

Bundle is too big - 180 MB in size

## Environment

 - Longhorn version: 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: Ubuntu 22.04 server/x86
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 13
