### DISCUSSION TITLE
[QUESTION] Disable automatic snapshot after disk extend

### DISCUSSION THREAD

**Discussion by ynsdll** [longhorn/longhorn#8734] [General]
## What's the task? Please describe

I want to disable automatic snapshot after disk extend.

I use below configs but doesnt works. Whenever ı extend my disk, Longhorn get automatic snapshot and I can not remove it.

## Additional context

```
defaultSettings:
  defaultDataPath: /data/longhorn/
  defaultReplicaCount: 1
  autoCleanupSystemGeneratedSnapshot: true
  autoCleanupRecurringJobBackupSnapshot: true
  storageReservedPercentageForDefaultDisk: 3
  storageMinimalAvailablePercentage: 3

persistence:
  defaultClassReplicaCount: 1
```
