### DISCUSSION TITLE
NFS rwx mode volume. Only owner can read data

### DISCUSSION THREAD

**Discussion by mirisu2** [longhorn/longhorn#8739] [Q&A]
Hi,
I have installed longhorn-system version 1.4.4. Kubernetes version is 1.24.11.
StorageClass:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
parameters:
  fromBackup: ""
  fsType: ext4
  migratable: "false"
  nfsOptions: vers=4.2,noresvport,softerr,timeo=600,retrans=5,rw,sync
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc1
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-rwx
  volumeMode: Filesystem
  volumeName: pvc-ff618a3e-24b5-467b-bde0-634562b42efa
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  phase: Bound
```
Trying to use volume rwx mode. PV is created. share-manager po is running:
```
$ kubectl -n longhorn-system get po | grep pvc-ff618a3e-24b5-467b-bde0-634562b42efa
share-manager-pvc-ff618a3e-24b5-467b-bde0-634562b42efa   1/1     Running   0               7d18h
```
volumeMapping config:
```
    volumeMounts:
    - mountPath: /data
      name: nginx-storage
...
  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: nginx-pvc1
```
pod1:
```
$ kubectl exec -it nginx-daemonset-6gc9h -- bash
root@nginx-daemonset-6gc9h:/# ls -l /data/
total 12
drwx------ 2 root root 12288 Jun  4 13:49 lost+found
root@nginx-daemonset-6gc9h:/# date > /data/date.txt
root@nginx-daemonset-6gc9h:/# cat /data/date.txt
Wed Jun 12 08:32:42 UTC 2024
root@nginx-daemonset-6gc9h:/# 
```
pod2:
```
$ kubectl exec -it nginx-daemonset-8xntc -- bash
root@nginx-daemonset-8xntc:/# ls -l /data/
total 12
drwx------ 2 root root 12288 Jun  4 13:49 lost+found
root@nginx-daemonset-8xntc:/# ls -l /data/
total 13
-rw-r--r-- 1 root root    29 Jun 12 08:32 date.txt
drwx------ 2 root root 12288 Jun  4 13:49 lost+found
root@nginx-daemonset-8xntc:/# cat /data/date.txt 
root@nginx-daemonset-8xntc:/# 
```
but "nfs server" has the data:
```
$ kubectl -n longhorn-system exec -it share-manager-pvc-ff618a3e-24b5-467b-bde0-634562b42efa -- bash
share-manager-pvc-ff618a3e-24b5-467b-bde0-634562b42efa:/ # cat /export/pvc-ff618a3e-24b5-467b-bde0-634562b42efa/date.txt 
Wed Jun 12 08:32:42 UTC 2024
share-manager-pvc-ff618a3e-24b5-467b-bde0-634562b42efa:/ #
```
Can anyone help me? What do I wrong? Why second pod can't read the shared file? What should I check?
