### DISCUSSION TITLE
Is accessMode ReadWriteOncePod supported by Longhorn (v.1.6.2)?

### DISCUSSION THREAD

**Discussion by elaurensx** [longhorn/longhorn#9082] [Q&A]
K3S version: v1.29.6+k3s1

Asking the question after having noticed that the longhorn ui is indicating an **RWO** accessMode for a volume which has been created with the following PVC definition..

```
kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: influxdb-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-3r
```

I also stumbled on [this bug report](https://github.com/longhorn/longhorn/issues/7849), in which @james-munson expects the validating webhook to reject a request for a RWOP volume and @yardenshoham reports that accessMode RWO should eventually be evaluated by the webhook..

.. which seems to be the case when going through the csi-plugin log

`level=info msg="Volume pvc-d41e5f56-de55-416b-ac03-cd45696e8712 with accessMode rwo requesting publishing with attachInput`

but then how do I end up in a situation in which the api-server is reporting an accessMode RWOP for that volume?

```
k get pvc -n <ns>
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                  VOLUMEATTRIBUTESCLASS   AGE
influxdb-data   Bound    pvc-d41e5f56-de55-416b-ac03-cd45696e8712   20Gi       RWOP           longhorn-3r   <unset>                 6h17m
```
