### DISCUSSION TITLE
[QUESTION] PVC not attaching due to problematic iscsid on LXD container

### DISCUSSION THREAD

**Discussion by windowsrefund** [longhorn/longhorn#9284] [General]
I can not create a simple PVC and pod to use it as defined in https://raw.githubusercontent.com/longhorn/longhorn/v1.1.1/examples/pod_with_pvc.yaml

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.21.0
 - Node config
   - OS type and version: Ubuntu 18.04 (can reproduce this with 20.04 as well since both use iscsid version 2.0-874)
 - Underlying Infrastructure: LXD

**Additional context**
This is a 2 node cluser: 1 master, 1 worker. Keeping it small in order to work past this issue.
The iscsid service is running on each node.

Here's the LXD profile
```
config:
  limits.cpu: "2"
  limits.memory: 4GB
  limits.memory.swap: "false"
  linux.kernel_modules: overlay,nf_nat,ip_tables,ip6_tables,br_netfilter,iscsi_tcp
  raw.lxc: |
    lxc.apparmor.profile = unconfined
    lxc.cgroup.devices.allow = a
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: k8s
used_by:
- /1.0/instances/kmaster1
- /1.0/instances/kworker1
```

And back on the container, we can see that the iscsi_tcp kernel module is loaded
```
root@kworker1:~# lsmod | grep iscsi
iscsi_tcp              24576  0
libiscsi_tcp           32768  1 iscsi_tcp
libiscsi               57344  2 libiscsi_tcp,iscsi_tcp
scsi_transport_iscsi   110592  3 libiscsi_tcp,iscsi_tcp,libiscsi
```
Immediately after installing longhorn, I attempt to create a single PVC and pod that uses it with https://raw.githubusercontent.com/longhorn/longhorn/v1.1.1/examples/pod_with_pvc.yaml

I see the following in the logs from the instance-manager pod that attempts to handle the request:
```
2021/05/12 18:53:05 failed to start up frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2019-10.io.longhorn:pvc-83ade826-333d-428b-a119-3098d3f41226 -p 10.244.1.9 --login], output Logging in to [iface: default, target: iqn.2019-10.io.longhorn:pvc-83ade826-333d-428b-a119-3098d3f41226, portal: 10.244.1.9,3260] (multiple)
, stderr, iscsiadm: got read error (0/0), daemon died?
```
From the worker node, I can discover targets provided by the instance-manger pod in question:
```
# iscsiadm -m discovery -p 10.244.1.9:3260 --type sendtargets
10.244.1.9:3260,1 iqn.2019-10.io.longhorn:pvc-83ade826-333d-428b-a119-3098d3f41226
```

However, it seems I can not login?
```
# iscsiadm -m node -L all
Logging in to [iface: default, target: iqn.2019-10.io.longhorn:pvc-83ade826-333d-428b-a119-3098d3f41226, portal: 10.244.1.9,3260] (multiple)
iscsiadm: got read error (0/0), daemon died?
iscsiadm: Could not login to [iface: default, target: iqn.2019-10.io.longhorn:pvc-83ade826-333d-428b-a119-3098d3f41226, portal: 10.244.1.9,3260].
iscsiadm: initiator reported error (18 - could not communicate to iscsid)
iscsiadm: Could not log into all portals
```
At this point, the iscsid service is now in a state of restarting over and over.
