### DISCUSSION TITLE
incremental backups retention policy - what happens when the last full backup expires?

### DISCUSSION THREAD

**Discussion by Androz2091** [longhorn/longhorn#9595] [Q&A] [answered]
Hello,

I am currently using the following recurring job for my longhorn instance:
```yaml
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: offsite-daily-data-config
  namespace: longhorn-system
spec:
  cron: "0 3 * * *" # every day at 3am, send data to S3 bucket
  task: "backup"
  groups:
  - default
  retain: 30 # keep them for 30 days
  concurrency: 1 # upload them one by one to avoid overloading the network
```

From what I've read in the docs and tried, it seems like it does one full backup (~300Gb in my case), and then does incremental ones (~1Gb, my storage is not updating a lot).

My question is about what will happen when the first backup (~300Gb) will expire. Will longhorn have to move the delta (~299Gb) to the 29th backup? Will I lose a bit of the power of incremental backups because Longhorn will have to deal with gigabytes of data to move from the last expiring full backup to the before-last incremental backup?

Thank you
