### DISCUSSION TITLE
Correct deployment with ArgoCD?

### DISCUSSION THREAD

**Discussion by Caroga** [longhorn/longhorn#9613] [Q&A] [answered]
Hello all. As per https://github.com/longhorn/longhorn/issues/4853 it is required to pass the `preUpgradeChecker.jobEnabled: false`  to the helm deployment when using ArgoCD, but it appears not be working for me.
Now I am a novice on this but I did my due diligence and I would like to ask for your help on how to properly deploy longhorn.

**Setup: repo on gitlab.comd**
```
├── longhorn
│   └── helm
│       ├── Chart.yaml
│       └── values.yaml
```

**longhorn/helm/Chart.yaml**
```yaml
apiVersion: v2
name: helm-longhorn
description: A Helm chart for longhorn
type: application
version: 0.1.0
appVersion: "1.7.1"
dependencies:
  - name: longhorn
    version: 1.7.1
    repository: https://charts.longhorn.io
```
**longhorn/helm/values.yaml**
```yaml
preUpgradeChecker:
  jobEnabled: false
```

I am deploying this via the commandline with the following input:
```bash
argocd --core app create services --repo https://repo.com/services.git --path longhorn/helm --values values.yaml --dest-server https://kubernetes.default.svc/ --dest-namespace longhorn --sync-policy auto
```
I've also applied the following parameters:
```bash
--parameter preUpgradeChecker.jobEnabled=false
```
or
```bash
--helm-set preUpgradeChecker.jobEnabled=false
```

But it all fails with the following error:
```
Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn/longhorn-service-account: serviceaccount "longhorn-service-account" not found
```

I have read the related documentation and feel like I am applying this correctly. Why does this fail?

I am aware of the deployment by [applying the manifest directly](https://longhorn.io/docs/1.7.1/deploy/install/install-with-argocd/) but I am convinced that this should work this way as well, right? If not, please let me know.

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by Caroga** [comment]
It was pointed out to me that because of the helm chart dependency setup the yaml configuration needs to be under a matching key.

So the following:
```yaml
dependencies:
  - name: longhorn
 ```
Requires the following change in the `values.yaml`:
```yaml
longhorn: #this was missing
  preUpgradeChecker:
    jobEnabled: false
```

Now it is deploying as expected.

Would you be interested in a change in documentation that displays this setup for deployment as well, next to the deployment using kubectl?

In my opinion this does match gitops appreach for ArgoCD a bit better. Interested to know if you'd want to include this in the documentation, I would be willing to write this out for you.

Kind regards
