### DISCUSSION TITLE
Help | Issues on every upgrade

### DISCUSSION THREAD

**Discussion by pat-s** [longhorn/longhorn#9696] [Q&A]
I am seeking help in what is wrong in my config so that I have issues on every Longhorn upgrade.

## Environment

- Installed via helm chart, deployed via ArgoCD
- Running on k3s (Hetzner)

## Issues

On every upgrade so far (1.6.1 -> 1.6.2, 1.6.2 -> 1.7.0, and now 1.7.0 -> 1.7.1) I am facing the following issues:

- The volumes do not update themselves even though "Concurrent Automatic Engine Upgrade Per Node Limit" is set to 1
- Manual upgrade fails with 

```
cannot upgrade engine for volume pvc-a74057f6-9907-4bb8-8486-4027e622c586 using image longhornio/longhorn-engine:v1.7.2: cannot upgrade engine image for volume pvc-a74057f6-9907-4bb8-8486-4027e622c586 from image longhornio/longhorn-engine:v1.7.1 to image longhornio/longhorn-engine:v1.7.2 because the engine image longhornio/longhorn-engine:v1.7.2 is not deployed on the replicas' nodes or the node that the volume is attached to
```

This happens even though on all nodes both `longhorn-manager` 1.7.1 AND 1.7.2 are running (after the update from 1.7.1 -> 1.7.2).

Deploying new PVCs also fails with `AttachVolume.Attach failed for volume "pvc-a5a5b462-4364-415d-bb82-0f85887fefde" : CSINode auto-xxlarge-amd64-176b90eedffc483a does not contain driver driver.longhorn.io`.

On this specific node, the following pods are running

- `longhornio/longhorn-engine:v1.7.1`
- `longhornio/longhorn-instance-manager:v1.7.2`
- `longhornio/longhorn-manager:v1.7.2`

So, what is wrong in my config so that Longhorn is not able to perform a clean upgrade and deploy the needed pods on its own so that both upgrade and provisioning of new PVCs works?

```yaml
        defaultSettings:
          storageReservedPercentageForDefaultDisk: 25
          kubernetesClusterAutoscalerEnabled: true
          defaultDataPath: /var/longhorn
          logLevel: debug
          replicaAutoBalance: best-effort
          # this auto-updates the engine image on each node after a new version got released and deployed
          concurrentAutomaticEngineUpgradePerNodeLimit: 1
          taintToleration: 'CI=true:NoSchedule'
          allowNodeDrainWithLastHealthyReplica: false
          removeSnapshotsDuringFilesystemTrim: true
          node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
        persistence:
          defaultFsType: ext4
          defaultClassReplicaCount: 3
          defaultClass: true
        longhornUI:
          replicas: 1
        preUpgradeChecker:
          jobEnabled: false
```
