### DISCUSSION TITLE
permission denied with k0s on baremetal

### DISCUSSION THREAD

**Discussion by Edregol** [longhorn/longhorn#9779] [Q&A] [answered]
LONGHORN_CHART_URL          = "https://charts.longhorn.io"
LONGHORN_CHART_NAME         = "longhorn"
LONGHORN_CHART_VERSION      = "1.7.2"

Operating System: ubuntu 24.04.1 lts
Architecture: amd64
k8s version: v1.31.2+k0s.0

Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.2+k0s.0

Number of control plane nodes in the cluster: 1 single node
Disk type (e.g. SSD/NVMe/HDD): NVME
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
Number of Longhorn volumes in the cluster: 1

Hi everyone!

Hope you can help me out. I've installed longhorn with its helm chart on a fresh ubuntu 24.04.1 lts installation. Chart values are mostly default.

These are my changes:
```
longhornUI:
  replicas: 1

persistence:
  defaultClassReplicaCount: 1
  defaultDataLocality: "best-effort"

defaultSettings:
  defaultReplicaCount: 1
  backupTarget: ""
  backupTargetCredentialSecret: ""
  replicaSoftAntiAffinity: false
```

Longhorn boots right up as expected no errors that I would have noticed.

Now if I install another helm chart (traefik in my case) a volume will be created and bound. However the pod gets an access denied when using the volume.

I've found a workaround in a different issue with similar problems. If I let the container run as root everything works:
```
podSecurityContext:
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
```
Obviously this can not be a solution for a production environment. 

In desperation, I tried to give free rein to everything and anything in /var/lib/longhorn: chmod 777 /var/lib/longhorn, but nothing changed.

I am struggling to understand what the root cause of the issue is. Can someone point me in the right direction? The same deployment was working just fine with openEBS and hostpath volumes.

EDIT:

Seems like this issue is exclusive to the traefik helm chart. Cockroach chart and a self created PVC work like a charm
