### DISCUSSION TITLE
Install with helm and value.yaml fail: spec.template.spec.containers[0].image: Required value - how to fix this ?

### DISCUSSION THREAD

**Discussion by n00bsi** [longhorn/longhorn#9788] [General]
got a values.yaml that worked with Version 1.6.x of longhorn...
but with 1.7.x the install fail...

Error: INSTALLATION FAILED: failed to create resource: Deployment.apps "longhorn-ui" is invalid: spec.template.spec.containers[0].image: Required value

here the install command I use:

**$ helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace  -f values.yaml**

here the Error Message I got:

Error: INSTALLATION FAILED: failed to create resource: Deployment.apps "longhorn-ui" is invalid: spec.template.spec.containers[0].image: Required value

**values.yaml**

```
# Default values for longhorn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
  nodeSelector:
    node-role.kubernetes.io/storage: ""
 
  openshift:
    oauthProxy:
      # -- Repository for the OAuth Proxy image. This setting applies only to OpenShift users.
      repository: longhornio/openshift-origin-oauth-proxy
      # -- Tag for the OAuth Proxy image. This setting applies only to OpenShift users. Specify OCP/OKD version 4.1 or later. The latest stable version is 4.14.
      tag: 4.14
  # -- Image pull policy that applies to all user-deployed Longhorn components, such as Longhorn Manager, Longhorn driver, and Longhorn UI.
  pullPolicy: IfNotPresent
 
 
defaultSettings:
  createDefaultDiskLabeledNodes: true
 
 
longhornManager:
  nodeSelector:
    node-role.kubernetes.io/storage: ""
 
longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/storage: ""
 
longhornUI:
  replicas: 2
  nodeSelector:
    node-role.kubernetes.io/storage: ""
 
 
## openshift settings
openshift:
  # -- Setting that allows Longhorn to integrate with OpenShift.
  enabled: true
  ui:
    # -- Route for connections between Longhorn and the OpenShift web console.
    route: "longhorn-ui"
    # -- Port for accessing the OpenShift web console.
    port: 443
    # -- Port for proxy that provides access to the OpenShift web console.
    proxy: 8443
```

What do I need to add to the values.yaml file ?

**Comment by akashsemil** [comment]
Can you try the following value in the values file.

```
openshift:
  enabled: true
  ui:
    route: "longhorn-ui"
	port: 443
	proxy: 8443
  
image:
  openshift:
	oauthProxy:
	  repository: quay.io/openshift/origin-oauth-proxy
	  tag: 4.15  # Use Your OCP/OKD 4.X Version, Current Stable is 4.15
```

**Reply by ds2k5** [reply]
@akashsemil 

thank you I will try tomorrow

**Comment by n00bsi** [comment]
@akashsemil 

did not work for me

```
$  helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace  -f values.yaml
Error: INSTALLATION FAILED: failed to parse values.yaml: error converting YAML to JSON: yaml: line 45: found character that cannot start any token
```


![image](https://github.com/user-attachments/assets/f3baa64e-77ff-4ea9-b580-2a662ac063cd)



```
global:
  # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
  nodeSelector:
    node-role.kubernetes.io/storage: ""

  pullPolicy: IfNotPresent



defaultSettings:
  createDefaultDiskLabeledNodes: true


longhornManager:
  nodeSelector:
    node-role.kubernetes.io/storage: ""

longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/storage: ""

longhornUI:
  replicas: 2
  nodeSelector:
    node-role.kubernetes.io/storage: ""


## openshift settings
openshift:
  # -- Setting that allows Longhorn to integrate with OpenShift.
  enabled: true
  ui:
    # -- Route for connections between Longhorn and the OpenShift web console.
    route: "longhorn-ui"
    # -- Port for accessing the OpenShift web console.
    port: 443
    # -- Port for proxy that provides access to the OpenShift web console.
    proxy: 8443

image:
  openshift:
        oauthProxy:
          repository: quay.io/openshift/origin-oauth-proxy
          tag: 4.15  # Use Your OCP/OKD 4.X Version, Current Stable is 4.15

```

**Comment by n00bsi** [comment]
changed the values.yaml to:
```

global:
  # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
  nodeSelector:
    node-role.kubernetes.io/storage: ""

  openshift:
    oauthProxy:
      # -- Repository for the OAuth Proxy image. This setting applies only to OpenShift users.
      repository: longhornio/openshift-origin-oauth-proxy
      # -- Tag for the OAuth Proxy image. This setting applies only to OpenShift users. Specify OCP/OKD version 4.1 or later. The latest stable version is 4.14.
      tag: 4.16
  # -- Image pull policy that applies to all user-deployed Longhorn components, such as Longhorn Manager, Longhorn driver, and Longhorn UI.
  pullPolicy: IfNotPresent



defaultSettings:
  createDefaultDiskLabeledNodes: true


longhornManager:
  nodeSelector:
    node-role.kubernetes.io/storage: ""

longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/storage: ""

longhornUI:
  replicas: 2
  nodeSelector:
    node-role.kubernetes.io/storage: ""


## openshift settings
openshift:
  # -- Setting that allows Longhorn to integrate with OpenShift.
  enabled: true
  ui:
    # -- Route for connections between Longhorn and the OpenShift web console.
    route: "longhorn-ui"
    # -- Port for accessing the OpenShift web console.
    port: 443
    # -- Port for proxy that provides access to the OpenShift web console.
    proxy: 8443

image:
  longhorn:
    ui:
      repository: longhornio/longhorn-ui
      tag: v1.7.2

```

```
$ helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace  -f values.yaml --version 1.7.1
Error: INSTALLATION FAILED: 1 error occurred:
        * timed out waiting for the condition

```
