### DISCUSSION TITLE
Clarifications on defaultSettings.defaultDataLocality and persistence.defaultDataLocality usage

### DISCUSSION THREAD

**Discussion by fmunteanu** [longhorn/longhorn#9841] [General]
From what I see, `persistence` will set definitions for `longhorn` storage class.

I have the following settings, into Helm chart:

```
defaultSettings:
  defaultDataLocality: strict-local
  replicaAutoBalance: least-effort
persistence:
  defaultDataLocality: disabled
```

I'm trying to understand how `persistence` relates to `defaultSettings` for data locality, I could not find anything relevant into documentation. I would expect when `persistence.defaultDataLocality` is set to `disabled`, it would follow the `defaultSettings. defaultDataLocality` setting?

What happens if the `persistence.defaultDataLocality` is set to `best-effort`, with above `defaultSettings`?
