### ISSUE TITLE
[BUG][v1.8.0-rc1] Error Status When Setting BackupTarget to AWS S3

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10026]
## Describe the bug

When I set the backup target to AWS S3, the status always shows as `ERROR`. However, the same configuration works properly when using MinIO S3 server as the backup target.

```yaml
Spec:
  Backup Target URL:  s3://<backup-target>@us-east-1/
  Credential Secret:  <s3-secret>
  Poll Interval:      5m0s
  Sync Requested At:  2024-12-20T03:10:19Z
Status:
  Available:  false
  Conditions:
    Last Probe Time:       
    Last Transition Time:  2024-12-20T03:04:41Z
    Message:               backup target URL is empty
    Reason:                Unavailable
    Status:                True
    Type:                  Unavailable
  Last Synced At:          2024-12-20T03:04:33Z
  Owner ID:                ryao-180-w2-szdwh-q6lsz
Events:                    <none>
```

## To Reproduce
1. Open the Longhorn UI.
2. Navigate to the settings for backup targets.
3. Edit the default backup target to AWS S3.

## Expected behavior

The default backup target should be successfully set to AWS S3.

## Support bundle for troubleshooting

[supportbundle_a409cc1f-0929-4d73-a2d7-4d7f8902c02a_2024-12-20T03-09-42Z.zip](https://github.com/user-attachments/files/18205595/supportbundle_a409cc1f-0929-4d73-a2d7-4d7f8902c02a_2024-12-20T03-09-42Z.zip)

## Environment

 - Longhorn version: 1.8.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.7+k3s1
   - Number of control plane nodes in the cluster:1
   - Number of worker nodes in the cluster:3
 - Node config 
   - OS type and version: ubuntu24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2
 - Number of Longhorn volumes in the cluster:
