### ISSUE TITLE
[BUG][v1.8.0-rc1] v2 qcow2 backing image checksum no consistent

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#10036]
## Describe the bug

The checksum of the backing image located at https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2 is `bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b`. However, when downloaded using the v2 engine, the calculated checksum changes to `304f3ed30ca6878e9056ee6f1b02b328239f0d0c2c1272840998212f9734b196371560b3b939037e4f4c2884ce457c2cbc9f0621f4f5d1ca983983c8cdf8cd9a`, which matches the checksum of https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw. This issue cannot be reproduced when using the v1 data engine.

## To Reproduce

1. Install Longhorn master/v1.8.0-rc1
2. Enable v2 data engine
3. Deploy backing image `v1-qcow2`, success
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: v1-qcow2
  namespace: longhorn-system
spec:
  dataEngine: v1
  minNumberOfCopies: 3
  sourceType: download
  sourceParameters:
    url: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
  checksum: bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
```
4. Deploy backing image `v2-qcow2`, the checksum calaulated not consistent, creation fail
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: v2-qcow2
  namespace: longhorn-system
spec:
  dataEngine: v2
  minNumberOfCopies: 3
  sourceType: download
  sourceParameters:
    url: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
  checksum: bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
```

can see `spec.dataEngine` = v2 but `status.diskFileStatusMap.dataEngine` = v1

and message
```
message: 'failed to process sync file: the expected checksum bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
        doesn''t match the file actual checksum 304f3ed30ca6878e9056ee6f1b02b328239f0d0c2c1272840998212f9734b196371560b3b939037e4f4c2884ce457c2cbc9f0621f4f5d1ca983983c8cdf8cd9a'
```
![image](https://github.com/user-attachments/assets/90de8655-739f-4a97-b480-317e62e9cdb8)

## Expected behavior

checksum correct

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version: master-head, v1.8.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.31.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15 SP6

## Additional context

did not see this symptom if using raw https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw checksum = `304f3ed30ca6878e9056ee6f1b02b328239f0d0c2c1272840998212f9734b196371560b3b939037e4f4c2884ce457c2cbc9f0621f4f5d1ca983983c8cdf8cd9a` on  v2 backingimage.

Not sure if related to https://github.com/longhorn/longhorn/issues/9876

## Workaround and Mitigation

N/A
