### ISSUE TITLE
[BUG][v1.8.0-rc1] Default backup target is periodically cleared

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10043]
## Describe the bug

I've noticed that the default backup target configuration is being automatically cleared.

## To Reproduce

1. Open the Longhorn UI
2. Navigate to `Setting` > `Backup Target`
3. Configure the default backup target with MinIO settings
4. Wait for a period of time
5. Check the backup target configuration

## Expected behavior

The default backup target should remain configured and not be cleared.

## Support bundle for troubleshooting

[supportbundle_3005eb36-292c-4bad-835e-4a7acd7d6515_2024-12-23T08-26-03Z.zip](https://github.com/user-attachments/files/18227500/supportbundle_3005eb36-292c-4bad-835e-4a7acd7d6515_2024-12-23T08-26-03Z.zip)

## Environment

- Longhorn version: 1.8.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.7+k3s1
   - Number of control plane nodes in the cluster:1
   - Number of worker nodes in the cluster:3
 - Node config 
   - OS type and version: ubuntu24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
As discussed here https://github.com/longhorn/longhorn-ui/pull/755/#pullrequestreview-2508241155
We would like to remove the global settings "backup-target", "backup-target-credential-secret", and "backupstore-poll-interval" for this unsynced scenario.

**Comment by derekbit** [comment]
> As discussed here [longhorn/longhorn-ui#755](https://github.com/longhorn/longhorn-ui/pull/755) We would like to remove the global settings "backup-target", "backup-target-credential-secret", and "backupstore-poll-interval" for this unsynced scenario.

@mantissahz We won't directly remove the settings in v1.8.0, so we still need to figure out a solution.

**Comment by derekbit** [comment]
After discussing with @mantissahz, some tasks need to be addressed 
- [ ]  v1.7.2 behavior: check whether the spec files of the `default` backupTarget resource are cleaned up when user empties the settings `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval`.

If the answer to the above question is true, then the behaviors of the v1.8.0 and older versions are consistent. Then, what we can do for the v1.8.0

- [ ] Installation or Upgrade
  - [ ] We should avoid directly removing the three default settings. Instead, they should be deprecated in v1.8.0 and removed in a later version. Before announcing the deprecation, we need to confirm whether it is feasible to include a **default backupTarget resource YAML** in the Helm chart and manifest. This will allow users to configure the default backupTarget using the new method.
  - [ ] If the answer to the above question is true, add a deprecation announcement in the official document. Currently, we will replace these three settings with a default backupTarget resource YAML in the future. 

- [ ] Runtime
  - [ ] If users attempt to modify the default backupTarget resource through the UI, the operation should be rejected. Instead, the UI should hint users to update the settings via the `Setting` page.
  - [ ] We should also specify that the default backupTarget resource should not be directly updated by editing the resource. Users must update the three settings as done in v1.7.x or earlier versions. Additionally, these three settings will be removed starting from v1.9.0.

cc @c3y1huang @innobead

**Comment by derekbit** [comment]
@c3y1huang @innobead Do you agree with the proposal?

**Comment by mantissahz** [comment]
> v1.7.2 behavior: check whether the spec files of the default backupTarget resource are cleaned up when user empties the settings backup-target, backup-target-credential-secret, and backupstore-poll-interval.

It is confirmed at v1.7.2, the fields `spec.backupTargetURL`, `spec.credentialSecret`, and `spec.pollInterval` of the BackupTarget CR `default` will be updated to the global settings `backup-target`, `backup-target-credential`, and `backupstore-poll-inteval` every hour (`settingControllerResyncPeriod = time.Hour`).

**Comment by mantissahz** [comment]
Summary update:
- Our original plan:
  Remove the global settings `backup-target`, `backup-target-credential-secret`, and `backupstore-poll-interval` from `longhorn-manager` and longhorn chart.
- What we are encountering? Why?
  After removing the settings, we need to have a way to create the `default` backup target, therefore, I add a new YAML file in the `chart/templates` directory as
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels: {{- include "longhorn.labels" . | nindent 4 }}
  namespace: {{ include "release_namespace" . }}
  name: default
spec:
  {{- if .Values.defaultSettings.backupTarget }}
  backupTargetURL: {{ .Values.defaultSettings.backupTarget }}
  {{- end }}
  {{- if .Values.defaultSettings.defaultBackupTarbackupTargetCredentialSecretetSecret }}
  credentialSecret: {{ .Values.defaultSettings.backupTargetCredentialSecret }}
  {{- end }}
  pollInterval: {{ .Values.defaultSettings.backupstorePollInterval | default "5m0s" }}
```
  It succeeded in deploying the manifest YAML file but failed when installing with Helm because the CRD needs to be installed first.
- Potential solution
  1. Move creating the `default` backup target to the post-install hook.
  2. Create the `default` backup target when `longhorn-manager` daemon initializes.
