### ISSUE TITLE
[FEATURE] Add Annotations To longhorn-frontend Service Via Helm

### ISSUE THREAD

**Issue by rfpludwick** [longhorn/longhorn#10110]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

I am using `external-dns` to provide IP addresses to Pi-holes in my homelab. In order for my setup to work, I need to apply an annotation to UI-based services, so I can route an NGINX reverse proxy to the DNS name, rather than to the entire Kubernetes cluster.

## Describe the solution you'd like

Add an annotations block to the Helm chart's definition for the `longhorn-frontend` service: `charts/longhorn/templates/deployment-ui.yaml`

Potential addition to the `charts/longhorn/values.yaml` file could be:

```yaml
uiService:
  # -- Annotations to add to the UI service
  annotations: {}
```

## Describe alternatives you've considered

I have tried no alternatives. Currently my NGINX setup looks like this (some information redacted) without the ability to set an annotation that `external-dns` can pickup:

```
upstream k8s_lh {
    zone           upstream_k8s 128k;

    least_conn;

    server         <node-1>:<node-port>;
    server         <node-2>:<node-port>;
    # and so forth
}
```

## Additional context

Apologies that I'm adding this issue here and not in the `longhorn/charts` repository; that repository does not have GitHub Issues enabled.

**Comment by sherwinf07** [comment]
You've nailed it. It would be nice to add annotations to the service. The issue I have is with Kube-VIP.
Example:
```bash
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: xxx.xxx.xxx.xxx
    kube-vip.io/vipHost: master
```

**Comment by jcwearn** [comment]
For what it's worth, I was able to get annotations added using the following in my HelmRelease:
```yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: longhorn-frontend
            patch: |-
              apiVersion: v1
              kind: Service
              metadata:
                name: longhorn-frontend
                namespace: longhorn-system
                annotations:
                  <your annotation goes here>
```
It would be nice to have an official way to add annotations directly from the helm values, but this worked for me in the meantime.
