### ISSUE TITLE
[BUG] Unable to delete volume snapshots

### ISSUE THREAD

**Issue by reysravanga** [longhorn/longhorn#10188]
## Describe the bug

 There are couple of volume snapshots which we tried deleting and all of them are stuck. 

## To Reproduce

go to longhorn UI choose a volume and try delete a snapshot of it.

## Support bundle for troubleshooting

https://drive.google.com/file/d/1QQKnOikIU1B0KJ8Auijm8XWOWBlwvAt3/view?usp=drive_link

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): https://drive.google.com/file/d/1QQKnOikIU1B0KJ8Auijm8XWOWBlwvAt3/view?usp=drive_link
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubespray - 1.30 k8s version
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: ubuntu 20.4
   - Kernel version:
   - CPU per node: 128
   - Memory per node: 256GB
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@reysravanga Can you provide the name of the problematic volume?

**Comment by reysravanga** [comment]
@derekbit -

PVC Name: minio-pv-claim-cloned 

Volume name : pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf

**Comment by aljabertareq** [comment]
@derekbit any update?

**Comment by derekbit** [comment]
@reysravanga I don't see any deletion failure in the support bundle. Which snapshot failed to delete?

**Comment by reysravanga** [comment]
1d54a134-451e-46f0-8bde-03de8604bde8 this is the snapshot which is stuck

**Comment by PhanLe1010** [comment]
Could you please grant me the access to the support bundle https://drive.google.com/file/d/1QQKnOikIU1B0KJ8Auijm8XWOWBlwvAt3/view?usp=drive_link @reysravanga ?

**Comment by aljabertareq** [comment]
@PhanLe1010 any update?

**Comment by PhanLe1010** [comment]
There are 2 snapshots belong to the volume `pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf` which is currently marked as removed but have not been cleanup:

```yaml
    name: 523498ee-ffb6-454f-9204-adca4a7cdb12
    ownerReferences:
      kind: Volume
      name: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
  spec:
    createSnapshot: false
    labels: "null"
    volume: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
  status:
    checksum: 1c0169183a20e306
    children:
      1d54a134-451e-46f0-8bde-03de8604bde8: true
    creationTime: "2024-06-02T07:44:05Z"
    labels: {}
    markRemoved: true
    ownerID: "null"
    parent: 8af26029-e39a-4037-a484-a00a40bd3231
    readyToUse: false
    restoreSize: 3.758096384e+13
    size: 4.00145379328e+12
    userCreated: true
```
and 
```yaml
    name: 8af26029-e39a-4037-a484-a00a40bd3231
    ownerReferences:
      kind: Volume
      name: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
  spec:
    createSnapshot: false
    labels: "null"
    volume: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
  status:
    checksum: d28ddaff4e12c25b
    children:
      523498ee-ffb6-454f-9204-adca4a7cdb12: true
    creationTime: "2024-03-17T08:31:18Z"
    labels: {}
    markRemoved: true
    ownerID: "null"
    parent: "null"
    readyToUse: false
    restoreSize: 3.758096384e+13
    size: 5.631967670272e+12
    userCreated: true
```
