### ISSUE TITLE
[BUG] v2 engine crash after a rebuilding failure

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#10212]
## Describe the bug

If the source or destination replica fails to start the rebuilding, the dst replica may be cleaned up before [the engine wraps up this failed rebuilding, which then leads to an engine crash](https://github.com/longhorn/longhorn-spdk-engine/blob/5bd1d71da7b66cf45d9ad302737cbf0c1d813dc9/pkg/spdk/engine.go#L1436-L1439).

## To Reproduce

1. Enable the v2 engine feature and prepare block disks
2. Set the data engine to v2 for the storage class 
3. Deploy a workload that keeps writing data into a v2 volume:
  ```
apiVersion: v1
kind: Service
metadata:
  name: writing-sts
  labels:
    app: writing-sts
spec:
  ports:
    - port: 80
      name: web
  selector:
    app: writing-sts
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: writing-sts
  namespace: default
spec:
  selector:
    matchLabels:
      app: writing-sts # has to match .spec.template.metadata.labels
  serviceName: "writing-sts"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: writing-sts # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        command:
          - /bin/sh
          - -c
          - while true; do dd if=/dev/urandom of=/usr/share/nginx/html/data bs=1M count=1000; rm /usr/share/nginx/html/data; done
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 2Gi

  ```
4. Delete an instance manager pods that contains a v2 replica only
5. Wait for the replica to start rebuilding/reusage. => In this case, when Longhorn tries to reuse the dst replica during the rebuilding, the src replica will fail at the preparation stage, leading to the bug mentioned above. As for why the src replica will fail here, we will have another ticket to track it.

## Expected behavior

The rebuilding should not affect the engine state

## Support bundle for troubleshooting

Somehow the src or the dst replica failed to start the rebuilding:
```
[longhorn-instance-manager] time="2025-01-14T20:32:33Z" level=error msg="Failed to disconnect the external src snapshot bdev pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-97699fe8-snap-rebuild-219fe805n1 for rebuilding dst cleanup, will continue" func="spdk.(*Replica).doCleanupForRebuildingDst" file="replica.go:1866" error="error sending message, id 7219, method bdev_nvme_detach_controller, params {pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-97699fe8-snap-rebuild-219fe805 {    }  }: {\"code\": -110,\"message\": \"Connection timed out\"}" lvsName=block-disk lvsUUID=80b0be2d-3dc9-442e-a2bf-eecc903066fb replicaName=pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-405447e7
```
Then the dst replica will be marked as `Failed` and get cleaned up immediately:
```
[instance-manager-73f45a39aa2c343c052c98820f602287] [longhorn-instance-manager] time="2025-01-14T20:32:34Z" level=info msg="Deleting replica  with address 10.42.177.214:20001 from engine" func="log.(*SafeLogger).Infof" file="log.go:73" endpoint=/dev/longhorn/pvc-466a2d3c-f368-4109-892d-3d2226395a51 engineName=pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 frontend=spdk-tcp-blockdev initiatorAddress=10.42.97.192 initiatorCreationRequired=true initiatorIP=10.42.97.192 port=20006 replicaStatusMap="map[pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-97699fe8:0xc000989860 pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-9f322c54:0xc000f01e00]" targetAddress=10.42.97.192 targetCreationRequired=true targetIP=10.42.97.192 targetPort=20006 volumeName=pvc-466a2d3c-f368-4109-892d-3d2226395a51
```

Later on, when the engine handling the rebuilding failure wrap up, it gets crashed:
```
[instance-manager-73f45a39aa2c343c052c98820f602287] [longhorn-instance-manager] time="2025-01-14T20:32:34Z" level=error msg="Engine pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 failed to do the shallow copy for replica pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-405447e7 add" func="spdk.(*Engine).ReplicaAdd.func3.1" file="engine.go:1207" endpoint=/dev/longhorn/pvc-466a2d3c-f368-4109-892d-3d2226395a51 engineName=pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 error="rebuilding error during shallow copy for snapshot : replica is being deleted" frontend=spdk-tcp-blockdev initiatorAddress=10.42.97.192 initiatorCreationRequired=true initiatorIP=10.42.97.192 port=20006 replicaStatusMap="map[pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-97699fe8:0xc000989860 pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-9f322c54:0xc000f01e00]" targetAddress=10.42.97.192 targetCreationRequired=true targetIP=10.42.97.192 targetPort=20006 volumeName=pvc-466a2d3c-f368-4109-892d-3d2226395a51
[instance-manager-73f45a39aa2c343c052c98820f602287] [longhorn-instance-manager] time="2025-01-14T20:32:34Z" level=error msg="Engine pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 failed to finish replica pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-405447e7 add" func="spdk.(*Engine).ReplicaAdd.func3.1" file="engine.go:1214" endpoint=/dev/longhorn/pvc-466a2d3c-f368-4109-892d-3d2226395a51 engineName=pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 error="cannot find the dst replica pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-405447e7 in the engine pvc-466a2d3c-f368-4109-892d-3d2226395a51-e-0 replica status map during replica add finish" frontend=spdk-tcp-blockdev initiatorAddress=10.42.97.192 initiatorCreationRequired=true initiatorIP=10.42.97.192 port=20006 replicaStatusMap="map[pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-97699fe8:0xc000989860 pvc-466a2d3c-f368-4109-892d-3d2226395a51-r-9f322c54:0xc000f01e00]" targetAddress=10.42.97.192 targetCreationRequired=true targetIP=10.42.97.192 targetPort=20006 volumeName=pvc-466a2d3c-f368-4109-892d-3d2226395a51
[insta
```

## Environment

 - Longhorn version: v1.8.0-rc3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
