### ISSUE TITLE
[BUG] insufficient storage;precheck new replica failed after a temporary shutdown of a node

### ISSUE THREAD

**Issue by macrokernel** [longhorn/longhorn#10210]
## Describe the bug

It may be that this is not a bug, but a request for help, as I am new to Longhorn and could have messed up the configuration. Can it be something about the disk tags or affinity?

After a temporary shutdown of a worker node (10 - 30 minutes) all volumes are in the degraded state with the following error messages:
```
Replica Scheduling Failure
Error Message: insufficient storage;precheck new replica failed
```
or
```
Replica Scheduling Failure
Error Message: precheck new replica failed;tags not fulfilled
```
despite of plenty of schedulable space and all nodes being schedulable according to the Longhorn dashboard.

![dashboard](https://github.com/user-attachments/assets/4b8bdd92-c2bb-4f22-9700-5ff474d282dd)

![volumes](https://github.com/user-attachments/assets/5adb370e-6169-4692-ba7e-0b96e59e9db9)

I've also noticed that the instance-manager on the restarted node has only few messages in the log - seems like it is not actually working and this might be causing the issue:
```
$ kubectl -n longhorn-system logs instance-manager-d7c1aeb9b71d5e6e6b8c7c78c747aedc 
Enabling tgtd
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
time="2025-01-15T12:58:32Z" level=info msg="Storing process logs at path: /var/log/instances" func=util.SetUpLogger file="log.go:61"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=warning msg="Failed to add TLS key pair from /tls-files/" func=cmd.start file="start.go:177" error="open /tls-files/tls.crt: no such file or directory"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="Creating gRPC server with no auth" func=cmd.start file="start.go:184"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="Debug pprof server listening on :6060" func=cmd.start.func2 file="start.go:190"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="disk gRPC server listening to 0.0.0.0:8502" func=cmd.start.func4 file="start.go:291"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="proxy gRPC server listening to 0.0.0.0:8501" func=cmd.start.func4 file="start.go:291"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="instance gRPC server listening to 0.0.0.0:8503" func=cmd.start.func4 file="start.go:291"
[longhorn-instance-manager] time="2025-01-15T12:58:33Z" level=info msg="process-manager gRPC server listening to 0.0.0.0:8500" func=cmd.start.func4 file="start.go:291"
[longhorn-instance-manager] time="2025-01-15T12:58:42Z" level=info msg="Start watching instances" func="instance.(*Server).InstanceWatch" file="instance.go:463"
[longhorn-instance-manager] time="2025-01-15T12:58:42Z" level=info msg="Start watching processes" func="instance.(*Server).watchProcess" file="instance.go:621"
[longhorn-instance-manager] time="2025-01-15T12:58:42Z" level=info msg="Start handling notify" func="instance.(*Server).handleNotify" file="instance.go:447"
[longhorn-instance-manager] time="2025-01-15T12:58:42Z" level=info msg="Started new process manager update watch" func="process.(*Manager).ProcessWatch" file="process_manager.go:385"
```

If I delete a failed replica from within the Longhorn UI, the replica is successfully recreated and is in healthy state, and new messages appear in the above mentioned log.

If Longhorn storage classes are created with `numberOfReplicas: "2"` (instead of my desired choice of `numberOfReplicas: "3"`), then the above mentioned errors do not occur, but the replicas on the restarted node are not automatically recovered. 

![numberOfReplicas_2](https://github.com/user-attachments/assets/fad57f69-4706-49d0-b4a2-7c0d1bf60a2a)

## To Reproduce

1 Partition a dedicated disk for Longhorn data on all worker nodes as follows:
|Device|Type|Size|Description|
|----------|---|------|----------|
|/dev/vdb1 |LVM|90 ГБ |Longhorn|
|/dev/vdb2 |LVM|50 ГБ |Rancher Local Path Provisioner|

Configure LVM and create FS:
```shell
sudo pvcreate /dev/vdb{1,2}
sudo vgcreate longhorn /dev/vdb1
sudo lvcreate --size 30716m --name nifi-1 longhorn
sudo lvcreate --size 30716m --name nifi-2 longhorn
sudo lvcreate --size 30716m --name nifi-3 longhorn
sudo mkfs.ext4 /dev/mapper/longhorn-nifi--1
sudo mkfs.ext4 /dev/mapper/longhorn-nifi--2
sudo mkfs.ext4 /dev/mapper/longhorn-nifi--3
sudo vgcreate local /dev/vdb2
sudo lvcreate --extents 100%FREE --name rancher local
sudo mkfs.ext4 /dev/mapper/local-rancher
```

2 Create mount directories and update `/etc/fstab`:
```shell
sudo mkdir -p /longhorn/nifi-{1,2,3}
sudo sh -c 'uuid=$(blkid -s UUID -o value /dev/mapper/longhorn-nifi--1); echo "/dev/disk/by-uuid/$uuid /longhorn/nifi-1 ext4 defaults 0 1" >> /etc/fstab'
sudo sh -c 'uuid=$(blkid -s UUID -o value /dev/mapper/longhorn-nifi--2); echo "/dev/disk/by-uuid/$uuid /longhorn/nifi-2 ext4 defaults 0 1" >> /etc/fstab'
sudo sh -c 'uuid=$(blkid -s UUID -o value /dev/mapper/longhorn-nifi--3); echo "/dev/disk/by-uuid/$uuid /longhorn/nifi-3 ext4 defaults 0 1" >> /etc/fstab'
sudo mount /longhorn/nifi-1
sudo mount /longhorn/nifi-2
sudo mount /longhorn/nifi-3
```

3 Deploy Longhorn helm chart with the following values:
```yaml
persistence:
  reclaimPolicy: Retain
  defaultClass: false
defaultSettings:
  allowCollectingLonghornUsageMetrics: false
  createDefaultDiskLabeledNodes: true
  replicaSoftAntiAffinity: false
  replicaDiskSoftAntiAffinity: false
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 0
  upgradeChecker: false
ingress:
  enabled: true
  ...
```

4 Create Longhorn nodes as follows:
```yaml
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  finalizers:
    - longhorn.io
  name: zone1-k8s-worker1
  namespace: longhorn-system
spec:
  name: zone1-k8s-worker1
  allowScheduling: true
  disks:
    zone1-k8s-worker1-nifi-1:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-1
      storageReserved: 0
      tags:
        - nifi-1
    zone1-k8s-worker1-nifi-2:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-2
      storageReserved: 0
      tags:
        - nifi-2
    zone1-k8s-worker1-nifi-3:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-3
      storageReserved: 0
      tags:
        - nifi-3
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  finalizers:
    - longhorn.io
  name: zone2-k8s-worker1
  namespace: longhorn-system
spec:
  name: zone2-k8s-worker1
  allowScheduling: true
  disks:
    zone2-k8s-worker1-nifi-1:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-1
      storageReserved: 0
      tags:
        - nifi-1
    zone2-k8s-worker1-nifi-2:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-2
      storageReserved: 0
      tags:
        - nifi-2
    zone2-k8s-worker1-nifi-3:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-3
      storageReserved: 0
      tags:
        - nifi-3
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  finalizers:
    - longhorn.io
  name: zone3-k8s-worker1
  namespace: longhorn-system
spec:
  name: zone3-k8s-worker1
  allowScheduling: true
  disks:
    zone3-k8s-worker1-nifi-1:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-1
      storageReserved: 0
      tags:
        - nifi-1
    zone3-k8s-worker1-nifi-2:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-2
      storageReserved: 0
      tags:
        - nifi-2
    zone3-k8s-worker1-nifi-3:
      allowScheduling: true
      evictionRequested: false
      path: /longhorn/nifi-3
      storageReserved: 0
      tags:
        - nifi-3
```

5 Configure Longhorn storage classes:
```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-nifi-1
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: "best-effort"
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "nifi-1"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-nifi-2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: "best-effort"
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "nifi-2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-nifi-3
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: "best-effort"
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "nifi-3"
```

6 Create PVCs:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-c-1-provenance-repository-storage-kz6jx
  namespace: nifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: storage-nifi-1
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-c-2-provenance-repository-storage-5xtb6
  namespace: nifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: storage-nifi-2
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-c-3-provenance-repository-storage-b4db9
  namespace: nifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: storage-nifi-3
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
```

7 Create pods:
```yaml
---
apiVersion: v1  
kind: Pod  
metadata:  
  name: nifi-c-1-provenance-repository-kz6jx
  namespace: nifi
spec:  
  containers:  
    - name: nifi-c-1-provenance-repository-kz6jx
      image: busybox
      command: ["sh", "-c", "dd if=/dev/zero of=/opt/data/file.bin bs=1M count=100; while true; do sleep 10; done"]
      volumeMounts:  
        - mountPath: "/opt/data"
          name: data
  nodeSelector:
    node_type: workers
    kubernetes.io/hostname: zone1-k8s-worker1
  volumes:  
    - name: data
      persistentVolumeClaim:  
        claimName: nifi-c-1-provenance-repository-storage-kz6jx
---
apiVersion: v1  
kind: Pod  
metadata:  
  name: nifi-c-2-provenance-repository-5xtb6
  namespace: nifi
spec:  
  containers:  
    - name: nifi-c-2-provenance-repository-5xtb6
      image: busybox
      command: ["sh", "-c", "dd if=/dev/zero of=/opt/data/file.bin bs=1M count=100; while true; do sleep 10; done"]
      volumeMounts:  
        - mountPath: "/opt/data"
          name: data
  nodeSelector:
    node_type: workers
    kubernetes.io/hostname: zone2-k8s-worker1
  volumes:  
    - name: data
      persistentVolumeClaim:  
        claimName: nifi-c-2-provenance-repository-storage-5xtb6
---
apiVersion: v1  
kind: Pod  
metadata:  
  name: nifi-c-3-provenance-repository-b4db9
  namespace: nifi
spec:  
  containers:  
    - name: nifi-c-3-provenance-repository-b4db9
      image: busybox
      command: ["sh", "-c", "dd if=/dev/zero of=/opt/data/file.bin bs=1M count=100; while true; do sleep 10; done"]
      volumeMounts:  
        - mountPath: "/opt/data"
          name: data
  nodeSelector:
    node_type: workers
    kubernetes.io/hostname: zone3-k8s-worker1
  volumes:  
    - name: data
      persistentVolumeClaim:  
        claimName: nifi-c-3-provenance-repository-storage-b4db9
```

8 Wait for the pods startup completion. Check Longhorn dashboad - all volumes are healthy.

9 Shut down any one of the worker nodes. Wait 5 minutes to make Longhorn realise the outage. Check Longhorn dashboad - all volumes are degraded but there are no errors other than the node is down. 

10 Wait 10 minutes, restart the node. Wait until the node is fully started. Check Longhorn dashboad - all volumes are degraded and having the error message mentioned in the issue description.

## Expected behavior

All volumes should automatically return back to healthy state soon after the cluster node is back up, there should be no errors. This should work with `numberOfReplicas` <= `number of Longhorn nodes`, not just when  `numberOfReplicas` < `number of Longhorn nodes`.

## Support bundle for troubleshooting

Sent a google drive link to longhorn-support-bundle@suse.com.

## Environment

 - Longhorn version: 1.7.2
 - Impacted volume (PV): all volumes
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubespray
 - Kubernetes runtime: cri-o
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.24.2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.5
   - Kernel version: 5.15.0-130-generic
   - CPU per node: control - 2, worker - 4
   - Memory per node: control - 4, worker - 8
   - Disk type (e.g. SSD/NVMe/HDD): HDD, virtualized, 90 GB
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 21
 - NFS client is not installed as RWX support is not required
 - devnode "^sd[a-z0-9]+" blacklist was added to /etc/multipath.conf, multipathd restarted to apply
 - dm_crypt is not loaded as encryption is not required

## Additional context

The PVCs are actually created by the [nifi cluster helm chart](https://github.com/konpyutaika/nifikop). I described a way to recreate the issue without the use of the chart for simplicity. It might not fully replicate the original issue, but the symptoms are looking the same or very similar. At least the error message is the same.

I was initially using `Retain` reclaim policy, but changed that to `Delete` while struggling with the issue. I've also been experimenting with Longhorn configuration settings for a while. All that done after the issue
