### ISSUE TITLE
[Doc] Clarifications on defaultSettings.defaultDataLocality and persistence.defaultDataLocality usage

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#10253]
### Discussed in https://github.com/longhorn/longhorn/discussions/9841

<div type='discussions-op-text'>

<sup>Originally posted by **fmunteanu** November 22, 2024</sup>
From what I see, `persistence` will set definitions for `longhorn` storage class.

I have the following settings, into Helm chart:

```
defaultSettings:
  defaultDataLocality: strict-local
  replicaAutoBalance: least-effort
persistence:
  defaultDataLocality: disabled
```

I'm trying to understand how `persistence` relates to `defaultSettings` for data locality, I could not find anything relevant into documentation. I would expect when `persistence.defaultDataLocality` is set to `disabled`, it would follow the `defaultSettings. defaultDataLocality` setting?

What happens if the `persistence.defaultDataLocality` is set to `best-effort`, with above `defaultSettings`?</div>
