### ISSUE TITLE
[BUG] AttachVolume.Attach failed for volume failed to attach to node1 with the volume is currently attached to different node2

### ISSUE THREAD

**Issue by SaviorVirus** [longhorn/longhorn#10258]
### Describe the Bug

I got error when recreate statefulset. when PV trying to connect error appears: 
AttachVolume.Attach failed for volume "pvc-2efe11a5-8925-4da5-91db-99e5a79d82c8" : rpc error: code = Internal desc = volume pvc-2efe11a5-8925-4da5-91db-99e5a79d82c8 failed to attach to node node3 with attachmentID csi-5051bd6ff47a640274db87dbdb680151efae04475ca387ee370ab30fb36fcea7: the volume is currently attached to different node node1. helps only manual detach and attach to right node.

### Expected Behavior

detach and attach should be automatically 

### Environment

- Longhorn version:  1.6.4
- Impacted volume (PV): pvc-2efe11a5-8925-4da5-91db-99e5a79d82c8
- Installation method Helm
- Kubernetes distro EKS and version: 1.29.5
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 4
- Node config
  - OS type and version: AlmaLinux 9.5 (Teal Serval)
  - Kernel version:  5.14.0-503.21.1.el9_5.x86_64
  - CPU per node: 8 
  - Memory per node: 16 
- Underlying Infrastructure  VMWare

### Workaround and Mitigation

only manual detach and attach to right node.

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Comment by derekbit** [comment]
cc @PhanLe1010

**Comment by SaviorVirus** [comment]
sent it to longhorn-support-bundle@suse.com

**Comment by SaviorVirus** [comment]
same bug
[BUG] err="failed to attach: rpc error: code = Aborted desc = volume pvc-is not ready for workloads" #10146

**Comment by PhanLe1010** [comment]
There are multiple `longhorn-ui` attachment ticket inside the cluster like:
```yaml
    attachmentTicketStatuses:
      longhorn-ui:
        conditions:
        - lastProbeTime: "null"
          lastTransitionTime: "2025-01-16T13:58:12Z"
          message: "null"
          reason: "null"
          status: "True"
          type: Satisfied
        generation: 0
        id: longhorn-ui
        satisfied: true
```

It indicate that user manually attach the volume using Longhorn UI and this might block the CSI attachment when a workload want to use the volume. 

@SaviorVirus Could you try:
1. List all `volumeattachment.longhorn.io` CRs `kubectl -n longhorn-system get volumeattachments.longhorn.io -oyaml`
2. For the CR which has `longhorn-ui` ticket, remove the `longhorn-ui` ticket from the `spec` field  `kubectl -n longhorn-system edit volumeattachments.longhorn.io <volume name>`
3. You should not hit same issue any more
