### ISSUE TITLE
[FEATURE] Support Single Logical Volume Store Across Multiple Disks

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#10260]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

The v2 data engine currently supports only a single logical volume store per disk, limiting the maximum volume size to the disk's capacity. To address this limitation, it should support a single logical volume store spanning multiple disks.

### Describe the solution you'd like

The solution must work for both aio and nvme bdev drivers. One idea is creating a bdev raid consisting of multiple disks.

**Comment by innobead** [comment]
> One idea is creating a bdev raid consisting of multiple disks.

Can u elaborate this a bit? The current design is each replica mapped to a lvol which only can exist in a lvol store. Do u mean you want another raid bdev for each replica instead?

**Comment by derekbit** [comment]
> > One idea is creating a bdev raid consisting of multiple disks.
> 
> Can u elaborate this a bit? The current design is each replica mapped to a lvol which only can exist in a lvol store. Do u mean you want another raid bdev for each replica instead?

The full stack is like

![Image](https://github.com/user-attachments/assets/f39489f4-4327-448a-aeee-7ee201971ce2)

We can leverage the high performance NVMe Bdev in the storage stack.

**Comment by innobead** [comment]
Creative, but might need to see how performance penalties would be.

**Comment by davidcheng0922** [comment]
After discuss with spdk upstream, there is two options for raid type

### RAID Concat:
  - Purpose: capacity aggregation
  - **Data layout: linear / sequential**
  - strip_size_kb: not used
  - **Performance (1 bdev): same as raw disk; no overhead**
  - **Performance (multiple bdevs): no improvement; just larger capacity**
  - Failure behavior: any base disk failure = data lost
  - **SPDK IO path: direct passthrough (minimal CPU usage)**
  - Typical overhead: very low
  - Best use case: merge disks into one larger logical device
  - **Size: sum of all base disks (subject to strip-size alignment truncation)**

### RAID 0:
  - Purpose: performance striping
  - **Data layout: stripes data across disks**
  - strip_size_kb: required (>0)
  - **Performance (1 bdev): slower than raw disk (unnecessary striping overhead)**
  - **Performance (multiple bdevs): higher throughput due to true striping**
  - Failure behavior: any base disk failure = data lost
  - **SPDK IO path: stripe mapping; more CPU overhead**
  - Typical overhead: medium
  - Best use case: multi-disk performance scaling
  - **Size: largest common multiple of strip-aligned capacities across all disks**

**Comment by derekbit** [comment]
@davidcheng0922 
Then, let's adopt **RAID Concat**. WDYT?

**Comment by davidcheng0922** [comment]
Yeah, I agree. I will test if it works.

**Comment by derekbit** [comment]
@davidcheng0922 
Discussed with @innobead. Can you create two lvstores using Linux RAID 0 (3 disks)  and SPDK RAID concat (3 disks) and then compare the IO performance using kbench? 

- volumes
  - single-replica volume (engine and replica are on the same node)
  - 3-replica volume

- kbench.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kbench-pvc
spec:
  volumeMode: Filesystem
  #volumeMode: Block
  storageClassName: longhorn-v2  # replace with your storage class
  #storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 130Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kbench
spec:
  template:
    metadata:
      labels:
        kbench: fio
    spec:
      containers:
      - name: kbench
        image: derekbit/kbench:main6
        #command: ["sleep", "6000000"]
        imagePullPolicy: Always
        env:
#        - name: MODE
#          value: "quick" # for debugging
#        - name: MODE
#          value: "random-read-iops"
#        - name: MODE
#          value: "sequential-read-iops"
#        - name: MODE
#          value: "random-read-bandwidth"
#        - name: MODE
#          value: "sequential-read-bandwidth"
#        - name: MODE
#          value: "random-read-latency"
#        - name: MODE
#          value: "sequential-read-latency"
#        - name: MODE
#          value: "random-write-iops"
#        - name: MODE
#          value: "sequential-write-iops"
#        - name: MODE
#          value: "random-write-bandwidth"
#        - name: MODE
#          value: "sequential-write-bandwidth"
#        - name: MODE
#          value: "random-write-latency"
#        - name: MODE
#          value: "sequential-write-latency"
        - name: MODE
          value: "full" # run all tests
        - name: FILE_NAME
          value: "/volume/test"
        - name: SIZE
          value: "100G" # must be 10% smaller than the PVC size due to filesystem also took space
        - name: CPU_IDLE_PROF
          value: "disabled" # must be "enabled" or "disabled"
        volumeMounts:
        - name: vol
          mountPath: /volume/
        #volumeDevices:
        #- name: vol
        #  devicePath: /volume/test
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: kbench-pvc
  backoffLimit: 0
```
