### ISSUE TITLE
[BUG] V2 engines takes a long time to remove disconnected replicas

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#10273]
### Describe the Bug

When a replica becomes disconnected, the v2 engine can quickly identify the disconnection but takes a long time to remove the replica. And there are lots of removing timeout error logs inside instance manager pods.

### To Reproduce

1. Launch a workload that keeps writing data into a v2 volume
```
apiVersion: v1
kind: Service
metadata:
  name: writing-sts
  labels:
    app: writing-sts
spec:
  ports:
    - port: 80
      name: web
  selector:
    app: writing-sts
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: writing-sts
  namespace: default
spec:
  selector:
    matchLabels:
      app: writing-sts # has to match .spec.template.metadata.labels
  serviceName: "writing-sts"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: writing-sts # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        command:
          - /bin/sh
          - -c
          - while true; do dd if=/dev/urandom of=/usr/share/nginx/html/data bs=1M count=1000; rm /usr/share/nginx/html/data; done
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 2Gi

```
2. Reboot a node that contains a v2 replica only
3. Wait and check the instance manager pod that contains the engine  => The engine will mark the corresponding replica as Failed quickly then take several minutes to stop it (probably after the node recovery). Besides, there are lots of error logs in the IM pod.

### Expected Behavior

The engine should quickly stop the failed replica. There should not be any timeout error logs.

### Support Bundle for Troubleshooting

N/A

### Environment

- Longhorn version: v1.8.0
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
  - Number of control plane nodes in the cluster:
  - Number of worker nodes in the cluster:
- Node config
  - OS type and version:
  - Kernel version:
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
- Number of Longhorn volumes in the cluster:
