### ISSUE TITLE
[IMPROVEMENT] Helm Chart 1.8.0 inconsistent usage of nodePort (cosmetical fix)

### ISSUE THREAD

**Issue by Brice187** [longhorn/longhorn#10299]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

Values.yaml of v1.8.0 (Loc 89 - 99)

```yaml
service:
  ui:
    # -- Service type for Longhorn UI. (Options: "ClusterIP", "NodePort", "LoadBalancer", "Rancher-Proxy")
    type: ClusterIP
    # -- NodePort port number for Longhorn UI. When unspecified, Longhorn selects a free port between 30000 and 32767.
    nodePort: null
  manager:
    # -- Service type for Longhorn Manager.
    type: ClusterIP
    # -- NodePort port number for Longhorn Manager. When unspecified, Longhorn selects a free port between 30000 and 32767.
    nodePort: ""
```
**service.ui.nodePort: null** vs **service.ui.nodePort: ""*

This both items should be templated identically

### Describe the solution you'd like

```yaml
service:
  ui:
    # -- Service type for Longhorn UI. (Options: "ClusterIP", "NodePort", "LoadBalancer", "Rancher-Proxy")
    type: ClusterIP
    # -- NodePort port number for Longhorn UI. When unspecified, Longhorn selects a free port between 30000 and 32767.
    nodePort: null
  manager:
    # -- Service type for Longhorn Manager.
    type: ClusterIP
    # -- NodePort port number for Longhorn Manager. When unspecified, Longhorn selects a free port between 30000 and 32767.
    nodePort: null
```

### Describe alternatives you've considered

...

### Additional context

-
