### ISSUE TITLE
[BUG] Restoring an Existing LH Backup via CSI is broken for Harvester

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#10366]
### Describe the Bug

Harvester uses the steps described in the Reproduce to restore an existing LH backup to a volume via the CSI interface. This was implemented three years ago https://github.com/harvester/harvester/pull/1447

It works as expected until LH v1.8.0. On LH v1.8.0, restoring an existing LH backup via CSI does not work even if I applied the [fix](https://github.com/longhorn/longhorn-manager/pull/3519) provided by @PhanLe1010 

### To Reproduce

**Prerequisite**
- Building a Harvester cluster with the master branch commit `41d3e1b5b1b5d3e9d3a91568638ab8c5b4071f8b`
- Updating Harvester deployment with the image `webberhuang/harvester:issue-7335-head`
  - This contains bump LH v1.8.0
  - This contains the modification to the Harvester controller to match https://github.com/mantissahz/longhorn/blob/5972d80c833cc7fc7d7df3757f0b0d0558f14f7c/enhancements/20240926-multiple-backup-targets-support.md
- Updating Harvester Webhook deployment with the image `webberhuang/harvester-webhook:bump-lh-v1.8-head`
- Configuring backup target with an NFS server
  - https://docs.harvesterhci.io/v1.4/vm/backup-restore#configure-backup-target
  - Making sure LH backuptarget CR `default` is configured correctly
    ```
    apiVersion: longhorn.io/v1beta2
    kind: BackupTarget
    metadata:
      name: default
      namespace: longhorn-system
    
    spec:
      backupTargetURL: nfs://192.188.0.50:/home/webber/volumes
      credentialSecret: ""
      pollInterval: 5m0s
      syncRequestedAt: "2025-02-07T02:19:58Z"
    status:
      available: true
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2025-02-06T10:38:57Z"
        message: ""
        reason: ""
        status: "False"
        type: Unavailable
      lastSyncedAt: "2025-02-07T02:19:59Z"
      ownerID: harvester-node-0
    ```
- Creating an LH backup
  - Creating a PVC `os-vol` from a VM image
  - Creating a VolumeSnapshot `vs-direct`
    ```
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: vs-direct
      namespace: default
    spec:
      source:
        persistentVolumeClaimName: os-vol
      volumeSnapshotClassName: longhorn
    ```
  - An LH backup will be created (assume the backup name is `backup-b1`)

**Steps**
- Restoring the LH backup to a new PVC
  - Creating a VolumeSnapshotContent `vsc-recover` points to backup `backup-b1`
    ```
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshotContent
    metadata:
      name: vsc-recover
    spec:
      deletionPolicy: Delete
      driver: driver.longhorn.io
      source:
        snapshotHandle: bs://os-vol/backup-b1
      volumeSnapshotClassName: longhorn
      volumeSnapshotRef:
        name: vs-recover
        namespace: default
    ```
  - Creating a related VolumeSnapshot `vs-recover`
    ```
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: vs-recover
      namespace: default
    spec:
      source:
        volumeSnapshotContentName: vsc-recover
      volumeSnapshotClassName: longhorn
    ```
  - Creating a new PVC `pvc-recover` from the VolumeSnapshot
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-recover
      namespace: default
      ownerReferences:
    spec:
      accessModes:
      - ReadWriteMany
      dataSource:
        apiGroup: snapshot.storage.k8s.io
        kind: VolumeSnapshot
        name: vs-recover
      resources:
        requests:
          storage: 5Gi
      storageClassName: <backing image related sc>
      volumeMode: Block
    ```
- With LH v1.8.0, the `pvc-recover` creation will have a panic on LH CSI plugin pods
  ```
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin panic: runtime error: invalid memory address or nil pointer dereference
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x1d7a620]
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin goroutine 167 [running]:
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin github.com/longhorn/longhorn-manager/csi.(*ControllerServer).getBackupVolume(0xc0004dfbd0, {0xc000133835, 0x10})
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/csi/controller_server.go:287 +0x2e0
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin github.com/longhorn/longhorn-manager/csi.(*ControllerServer).CreateVolume(0xc0004dfbd0, {0x2ec4740?, 0x10?}, 0xc0003f1200)
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/csi/controller_server.go:130 +0x8ef
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x340ade0?, 0xc000aa28a0?}, {0x2d99bc0?, 0xc0003f1200?})
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go:451 +0xcb
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin github.com/longhorn/longhorn-manager/csi.logGRPC({0x340ade0, 0xc000aa28a0}, {0x2d99bc0, 0xc0003f1200}, 0xc000740960, 0xc00059f0c8)
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/csi/server.go:131 +0x23f
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x2ec4740, 0xc0004dfbd0}, {0x340ade0, 0xc000aa28a0}, 0xc0003f1180, 0x30d7948)
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go:453 +0x143
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b0a00, {0x340ade0, 0xc0008ff770}, 0xc0003ca840, 0xc00096c960, 0x4f71740, 0x0)
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:1392 +0xfc3
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin google.golang.org/grpc.(*Server).handleStream(0xc0001b0a00, {0x340bb78, 0xc000451380}, 0xc0003ca840)
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:1802 +0xbaa
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin google.golang.org/grpc.(*Server).serveStreams.func2.1()
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:1030 +0x7f
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 158
  longhorn-csi-plugin-g2hnc:longhorn-csi-plugin     /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:1041 +0x125
  ```
- With the [fix](https://github.com/longhorn/longhorn-manager/pull/3519) provided by @PhanLe1010, the creation failed with:
  ```
  longhorn-csi-plugin-jncvm:longhorn-csi-plugin time="2025-02-06T08:10:24Z" level=info msg="CreateVolume is called with req name:\"pvc-ed6a0cb7-0e89-4bcf-a6a0-208ea3b87826\"  capacity_range:{required_bytes:5368709120}  volume_capabilities:{block:{}  access_mode:{mode:MULTI_NODE_MULTI_WRITER}}  parameters:{key:\"backingImage\"  value:\"vmi-455d0e24-befe-4738-b132-eaf6d10bfd58\"}  parameters:{key:\"encrypted\"  value:\"false\"}  parameters:{key:\"migratable\"  value:\"true\"}  parameters:{key:\"numberOfReplicas\"  value:\"1\"}  parameters:{key:\"staleReplicaTimeout\"  value:\"30\"}  volume_content_source:{snapshot:{snapshot_id:\"bs://os-vol/backup-be842e7288aa4318\"}}" func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:81" component=csi-controller-server function=CreateVolume
  longhorn-csi-plugin-jncvm:longhorn-csi-plugin time="2025-02-06T08:10:24Z" level=debug msg="cannot find backup volume for volume os-vol" func="csi.(*ControllerServer).getBackupVolumes" file="controller_server.go:292" component=csi-controller-server function=getBackupVolume
  longhorn-csi-plugin-jncvm:longhorn-csi-plugin time="2025-02-06T08:10:24Z" level=error msg="CreateVolume: err: rpc error: code = NotFound desc = failed to restore CSI snapshot bs://os-vol/backup-be842e7288aa4318 of volume os-vol: there is no backup volume" func=csi.logGRPC file="server.go:136"
  ```

### Expected Behavior

Restoring an existing LH backup can be successful on LH v1.8.0

### Support Bundle for Troubleshooting

[supportbundle_6f464c10-7b9a-4cc1-bbaa-74b47e67f5d4_2025-02-07T03-57-49Z.zip](https://github.com/user-attachments/files/18700905/supportbundle_6f464c10-7b9a-4cc1-bbaa-74b47e67f5d4_2025-02-07T03-57-49Z.zip)

### Environment

- Longhorn version: v1.8.0
- Harvester version: master-branch `41d3e1b5b1b5d3e9d3a91568638ab8c5b4071f8b`
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
  - Number of control plane nodes in the cluster:
  - Number of worker nodes in the cluster:
- Node config
  - OS type and version:
  - Kernel version:
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
- Number of Longhorn volumes in the cluster:

### Some Investigation
After some investigation, I found Harvester has used the format `bs://<PVC name>/<backup name>` for `snapshotHandle` since day1 https://github.com/harvester/harvester/blob/80d614997674d323b95ab6525db54b9753d0b1b9/pkg/controller/master/backup/backup.go#L728

But LH expects it to be `bak://<volume name>/<backup name>`, however, it works fine before LH v1.8.0:
- LH [receives a wrong backupvolume name and tries to get a backupvolume resource](https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/csi/controller_server.go#L129-L133)
- The backupvolume CR doesn't exist for sure, however, LH will return a dummy resource without error
  - https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/api/backup.go#L104-L107
  - https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/manager/engine.go#L376-L381
- LH [tries to get related backup with backupvolume](https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/csi/controller_server.go#L135-L138)
  - But the backupvolume doesn't matter during getting the related backup CR
    - https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/api/backup.go#L208-L211
    - https://github.com/longhorn/longhorn-manager/blob/fd2ef9c5ee891fdbc787e475359a48b3f6b0e094/manager/engine.go#L437-L439
- LH can get the backup successfully, and progress the following steps

Since LH v1.8.0, LH has a strict check for the relation between backupvolume CR and backup CR
- Because LH gets a dummy backupvolume resource, [it will panic while checking the backup and backupvolume](https://github.com/longhorn/longhorn-manager/blob/1f343ee4c467de1264682ecb069d8f2a62850977/csi/controller_server.go#L286-L290)
- Even after the panic is [fixed](https://github.com/longhorn/longhorn-manager/pull/3519), [LH will still fail to find a valid backupvolume](https://github.com/PhanLe1010/longhorn-manager/blob/015401289cb7b391848ffca46832d1b12a399974/csi/controller_server.go#L286-L293)
- The restored volume can't be provided

My question is "Since the backupvolume doesn't matter when getting the correct LH backup, can we skip the check between backupvolume and backup?" @derekbit @mantissahz @PhanLe1010 

I have [a PR to skip the check](https://github.com/WebberHuang1118/longhorn-manager/tree/10303-skip-check-backupvolume), and it works as expected so far.

I understand Harvester has used the wrong snapshotHande format (`bs://<PVC name>/<backup name>`) since three years ago, even if Harvester updates the controller, it will have backward compatibility issues for the existing VolumeSnapshot and VolumeSnapshotContent
