### ISSUE TITLE
Add basic auth to longhorn-ui

### ISSUE THREAD

**Issue by OrwillT** [longhorn/longhorn#1039]
I don't know how to describe this issue.

It's proxy by cloudflare. TLS working fine but can't display anything.

I installed longhorn with helm3, Here is my values.yaml file:
```
ingress:
  enabled: true
  host: longhorn.xxx.xxx
  tls: false
service:
  ui:
    type: ClusterIP
```
