### ISSUE TITLE
[BUG] service account helm chart

### ISSUE THREAD

**Issue by AkakievKD** [longhorn/longhorn#10412]
### Describe the Bug

![Image](https://github.com/user-attachments/assets/475e5484-7708-4fa2-bc5d-82350c466ac2)

### Expected Behavior

create service account

### Support Bundle for Troubleshooting

![Image](https://github.com/user-attachments/assets/c6cc7cf6-d6b5-4856-b7a3-70a1ecd9addc)

### Environment

- Longhorn version: 1.8.0

**Comment by AkakievKD** [comment]
i create using argocd

**Comment by derekbit** [comment]
cc @mantissahz @yangchiu

**Comment by mantissahz** [comment]
Hi @AkakievKD,
Did you disable the setting `preUpgradeChecker.jobEnabled`?
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
...
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
...
```
