### ISSUE TITLE
[IMPROVEMENT] Prevent race condition when doing the scheduling

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#10422]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

Volumes can be controlled by different controllers.
There is a chance that multiple controllers are working the scheduling and retrieving the current node/disk capacity at the same time.
Without a locking mechanism for this shared information, a race condition can arise, potentially causing multiple replicas to be placed on the same node, leading to over-provisioning.

### Describe the solution you'd like

There are several solutions for this
1. to have a lock for cluster resources when doing the scheduling
2. only allow one controller to do the scheduling (leader-election)
3. only schedule one replica at a time globally.

### Additional context

Here is the way to reproduce the race condition

0. Set the over provisioned in the setting to 100
1. Disable all the disks in the cluster except for one, lets call it diskX
2. Prepare two PVCs which the sum of the size is large than the diskX (assum diskX is less than 60GB)
3. Two PVC needs to be in separate files. 

```
sc.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataEngine: "v1"
```
```
# pvc1.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 30Gi
```
```
# pvc2.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 30Gi
```
4. Use two terminals to apply these two yamls at the same time. (may need to try several times)
5. There is a chance that both volume's replica are scheduled on the same disk and the disk is over provisioned.

Normally, if we apply two PVC separately, the second one will fail at pre-check and have the message
```
Replica Scheduling Failure
Error Message: disks are unavailable;insufficient storage;precheck new replica failed
```

cc @derekbit @PhanLe1010
