### ISSUE TITLE
Support `Data Locality` option to always keep a replica local to the engine

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1045]
Try to keep a replica local.

1. Need to delay the scheduling to after the volume being used for the first time.
2. Need to migrate replica automatically if there is no local replica on the node.

**Comment by yasker** [comment]
Thought more about this:
1. The setting `Ensure One Replica co-located With Engine` should be exposed as a global option.
    1. We don't need to allow per volume configuration for now because the option will be enabled only when the network condition is bad.
2. There is still a question if we can delay the scheduling of replica, or does it make sense to do that.
3. The basic idea is, if a volume is attached to a node that has no replica, then we will start rebuilding the replica on the node after the volume is attached. Once the rebuilding process is done, we will randomly remove one of the other replicas to keep the replica count as specified.
    1. If the volume was detached before the rebuilding was done, the half-finished replica will be removed automatically even in the current mechanism.

**Comment by PhanLe1010** [comment]
@yasker 
When users choose the option to keep a replica on the same node as the engine. If for some reasons (e.g node tag, disk tag conflict, or not enough space), the replica cannot be migrated to the node. Do we error out and stop the volume or just skip the migration?

**Comment by yasker** [comment]
It's going to be the best effort. We cannot give user zero availability if there is no local disk satisfied the requirement. We should notify the user about that in some way.

**Comment by PhanLe1010** [comment]
**reproduce/test steps:**
1. Create a cluster of 6 nodes and install Longhorn. Having more nodes helps us to be more confident in verifying the PR because the chance of randomly scheduling a replica onto same node as the engine is small. 
1. Create volume `testvol` with `Number of Replicas` = 2
####Case 1: `keep-local-replica-on-same-node-as-engine` set to `false`:
1. Attach `testvol` to a node which does not contain any replica
1. Expected: No new replica is created
####Case 2: `keep-local-replica-on-same-node-as-engine` set to `true`:
1. Attach `testvol` to a node which does not contain any replica
1. Expected: Longhorn starts rebuilding a local replica on the engine's node. After finishing rebuilding the local replica, Longhorn remove one of the other replicas to keep the total number of replicas == 2
1. Assume that the engine is currently on `node-1`. Delete a replica that is not in `node-1`. Verify that Longhorn creates and rebuild a new replica.
1. Delete the replica in `node-1`. Verify that Longhorn creates and rebuilds a new replica on another node. Then Longhorn creates and rebuilds a new replica on `node-1`. After finishing rebuilding, Longhorn delete one replica on a node # `node-1`
Repeat the above 2 cases with volume di

**Comment by yasker** [comment]
Need to investigate the scheduler option as well.

**Comment by PhanLe1010** [comment]
Kubernetes currently only have hard node-affinity for PV https://kubernetes.io/docs/concepts/storage/persistent-volumes/#node-affinity
We may want to consider submitting a PR to the upstream Kubernetes to fix this and use it to implement data locality

**Comment by PhanLe1010** [comment]
**reproduce/test steps:**

1. Create a cluster of 9 worker nodes and install Longhorn. 
Having more nodes helps us to be more confident because the chance of randomly scheduling a replica onto the same node as the engine is small.
1. Using Rancher to install an L7 ingress pointing to `longhorn-backend` service

##### Test volume creation with `dataLocality` is `best-effort`:

1. Open the ingress and go to volume API at `v1/volumes`
1. In the volume API, create volume `testvol` with `Number of Replicas = 2` and `dataLocality` is `best-effort`
1. Attach `testvol` to a node that doesn't contain any replica.
1. Verify that Longhorn schedules a local replica to the same node as the consuming pod. 
   After finishing rebuilding the local replica. Longhorn removes a random replica on other nodes to keep the number of replicas is 2.

##### Test volume creation with `dataLocality` is `disable`:

1. Open the ingress and go to volume API at `v1/volumes`
1. Create another volume, `testvol2`  with `Number of Replicas = 2` and `dataLocality` is `disable`
1. Attach `testvol2` to a node that doesn't contain any replica.
1. Verify that Longhorn doesn't move replica

##### Test volume creation with `dataLocality` is unspecified and `DefaultDataLocality` setting as `diable`:
1. Leave the `DefaultDataLocality` setting as `diable` in Longhorn UI.
1. Open the ingress and go to volume API at `v1/volumes`
1. Create another volume, `testvol3`  with `Number of Replicas = 2` and `dataLocality` is empty
1. Attach `testvol3` to a node that doesn't contain any replica.
1. Verify that the `dataLocality` of `testvol3` is `disable` and that Longhorn doesn't move replica.

##### Test volume creation with `dataLocality` is unspecified and `DefaultDataLocality` setting as `best-effort`:
1. Set the `DefaultDataLocality` setting to `best-effort` in Longhorn UI.
1. Open the ingress and go to volume API at `v1/volumes`
1. Create another volume, `testvol4`  with `Number of Replicas = 2` and `dataLocality` is empty
1. Attach `testvol4` to a node that doesn't contain any replica.
1. Verify that the `dataLocality` of `testvol4` is `best-effort`.
1. Verify that Longhorn schedules a local replica to the same node as the consuming pod. 
   After finishing rebuilding the local replica. 
   Longhorn removes a random replica on other nodes to keep the number of replicas is 2.

##### Test `updateDataLocality` from `disable` to `best-effort`:
1. Open the ingress and go to volume API at `v1/volumes`. Find the action section of `testvol2`
1. Click on the action `updateDataLocality` and change `dataLocality` to `best-effort`
1. Verify that Longhorn schedules a local replica to the same node as the consuming pod. 
   After finishing rebuilding the local replica. 
   Longhorn removes a random replica on other nodes to keep the number of replicas which is 2.
   
##### Test `updateDataLocality` from `best-effort` to `disable` :
1. Open the ingress and go to volume API at `v1/volumes`. Find the action section of `testvol2`
1. Click on the action `updateDataLocality` and change `dataLocality` to `disable`
1. Go to Longhorn UI, increase the `number of replicas` to 3. Wait until the new replica finishes rebuilding.
1. Delete the local replica on the same node as the consuming pod.
1. Verify that Longhorn doesn't move replica 

##### Test volume creation by using storage class with `dataLocality` parameter is `disable`:
1. Create `disable-longhorn` storage class with from this yaml file:
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: disable-longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      dataLocality: "disable"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
    ```
1. create a shell deployment of 1 pod using `ubuntu:xenial` image, and the PVC dynamically created by `disable-longhorn` storage class.
1. The consuming pod is likely scheduled onto a different node than the replica. 
   If this happens, verify that Longhorn doesn't move replica
   
##### Test volume creation by using storage class with `dataLocality` parameter is `best-effort`:
1. Create `best-effort-longhorn` storage class with from this yaml file:
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: best-effort-longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      dataLocality: "best-effort"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
    ```
1. create a shell deployment of 1 pod using `ubuntu:xenial` image, and the PVC dynamically created by `best-effort-longhorn` storage class.
1. The consuming pod is likely scheduled onto a different node than the replica. 
1. If this happens, verify that Longhorn schedules a local replica to the same node as the consuming pod. 
   After finishing rebuilding the local replica, Longhorn removes a random replica on other nodes to keep the number of replicas which is 1.
1. verify that the volume CRD has `dataLocality` is `best-effort`

##### Test volume creation by using storage class with `dataLocality` parameter is unspecified`:
1. Create `unspecified-longhorn` storage class with from this yaml file:
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: unspecified-longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
    ```
1. create a shell deployment of 1 pod using `ubuntu:xenial` image, and the PVC dynamically created by `unspecified-longhorn` storage class.
1. The consuming pod is likely scheduled onto a different node than the replica. 
1. If this happens, depend on `DefaultDataLocality` setting in Longhorn UI, verify that Longhorn does/doesn't migrate a local replica to the same node as the consuming pod.
