### ISSUE TITLE
[BUG] csi keeps creating backup if the backup target is unavailable

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#10501]
### Describe the Bug

Enable the csi volume snapshot
If the backup target is unavailable, Longhorn keeps creating a new backup with Error state

Here is the reasone,

- We return empty backup volume list here
https://github.com/longhorn/longhorn-manager/blob/d63472400dae6ab2427f40b17f3f329bb1c65431/csi/controller_server.go#L279-L295
- Thus, we then get nil when try to get the backup to check if it already exists
https://github.com/longhorn/longhorn-manager/blob/d63472400dae6ab2427f40b17f3f329bb1c65431/csi/controller_server.go#L1294-L1315
- Since the backup is nil, we then create another backup for this csi snapshot CR again
https://github.com/longhorn/longhorn-manager/blob/d63472400dae6ab2427f40b17f3f329bb1c65431/csi/controller_server.go#L816-L829

### To Reproduce

1. Don't set the backup target 
2. Create a VSC with `type: bak`
3. Create a PVC and attach the volume
4. Create the VS
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nginx-bak
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  source:
    persistentVolumeClaimName: nginx
```

By `kubectl get lhb -n longhorn-system`, you can see that every minute, longhorn create a new backup with Error state.

### Expected Behavior

Should avoid creating another backup

### Support Bundle for Troubleshooting

No need

### Environment

- Longhorn version: master-head

### Additional context

cc @PhanLe1010 @mantissahz 

### Workaround and Mitigation

Set the backup target
