### ISSUE TITLE
[TASK] Migrate from charts.rancher.io to charts.longhorn.io

### ISSUE THREAD

**Issue by pbolle** [longhorn/longhorn#10554]
## What's the task? 

The Helm charts https://charts.rancher.io longhorn & longhorn-crd Version 103.3.1+up1.6.2 run on our clusters 
We would like to migrate to the following charts https://charts.longhorn.io cart longhorn 1.7.3
The carts were not installed via the rancher ui, always directly with a helm.

I have found the following help:

https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/
https://www.technowizardry.net/2021/12/upgrading-longhorn-from-helm-2-in-rancher-2-6-the-hard-way/

I have been trying out different scripts for a few days that set either helm.sh/resource-policy=keep and / or meta.helm.sh/release-name=longhorn to various resources.

Unfortunately, I usually end up in a state where longhorn tries to delete the volumes.

Log:

```
failed to create volume: unable to create volume cloned-pvc-3129a839-cc9f-4409-aaa5-cdf769b1af37: create not allowed while custom resource definition is terminating
```

As far as I have seen, there is only a cart finaliser in the CRD in charts.longhorn.io. 
Are there any instructions for the migration or a hint on how to implement this? It would also be completely ok if the cluster is not available for a few hours.

## Additional context

Kernel version 5.14.0-503.23.2.el9_5.x86_64
Kubelet version v1.30.9+rke2r1
os AlmaLinux 9.5

**Comment by voarsh2** [comment]
Can someone clarify?
I am on Rancher 2.7.6, I belive LH was installed via Rancher catalog/apps.
1.7.3 was released over a month ago but I am not seeing the release show up

![Image](https://github.com/user-attachments/assets/47adb87c-5968-4749-a044-8a579a9c4a9c)

![Image](https://github.com/user-attachments/assets/9dcbf99f-2ab6-458b-b1c0-1facb023be8f)

Helm Chart data snippet:

```

spec:
  chart:
    metadata:
      annotations:
        catalog.cattle.io/auto-install: longhorn-crd=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/display-name: Longhorn
        catalog.cattle.io/kube-version: '>= 1.21.0-0'
        catalog.cattle.io/namespace: longhorn-system
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/provides-gvr: longhorn.io/v1beta1
        catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
        catalog.cattle.io/release-name: longhorn
        catalog.cattle.io/type: cluster-tool
        catalog.cattle.io/ui-source-repo: rancher-charts
        catalog.cattle.io/ui-source-repo-type: cluster
        catalog.cattle.io/upstream-version: 1.7.2
      apiVersion: v1
      appVersion: v1.7.2
      description: Longhorn is a distributed block storage system for Kubernetes.
      home: https://github.com/longhorn/longhorn
      icon: >-
        https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
      keywords:
        - longhorn
        - storage
        - distributed
        - block
        - device
        - iscsi
        - nfs
      kubeVersion: '>=1.21.0-0'
      maintainers:
        - email: maintainers@longhorn.io
          name: Longhorn maintainers
      name: longhorn
      sources:
        - https://github.com/longhorn/longhorn
        - https://github.com/longhorn/longhorn-engine
        - https://github.com/longhorn/longhorn-instance-manager
        - https://github.com/longhorn/longhorn-share-manager
        - https://github.com/longhorn/longhorn-manager
        - https://github.com/longhorn/longhorn-ui
        - https://github.com/longhorn/longhorn-tests
        - https://github.com/longhorn/backing-image-manager
      version: 102.5.1+up1.7.2
```

**Comment by pbolle** [comment]
Hello,
we have used the helm  integration of RKE2 for the installation (https://docs.rke2.io/helm) .
We used the following configuration:

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  targetNamespace: longhorn-system
  chart: longhorn
  repo: https://charts.rancher.io
  version: 103.3.1+up1.6.2
```
