### ISSUE TITLE
[BUG] Taint Toleration dont work as expected

### ISSUE THREAD

**Issue by Syntax3rror404** [longhorn/longhorn#10555]
### Describe the Bug

The Taint Tolerations dont work as expected, because not all longhorn service will be deployed to make repilcas scheduable on this node. The ui shows the node as schedulable but the engine is missing at the end to make longhorn able to store replicas.

In my case I want, that also the control-plane can hold replicas, for failover reasons. I have 6 bare-metal nodes with talos so only 3 worker. Each has two dedicated 2TB NVMe drives installed. 

### To Reproduce

6 nodes aka 3+3 control-plane/worker

Install it with this helm values 

```yaml
global:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

persistence:
  defaultClass: false
  defaultFsType: xfs
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain
  dataEngine: v1

defaultSettings:
  defaultDataPath: /var/lib/longhorn/
  storageReservedPercentageForDefaultDisk: 0
  taintToleration: node-role.kubernetes.io/control-plane=true:NoSchedule # doesnt change anything in this case,  only global.tolerations let the node show up as scheduable
```

### Expected Behavior

1. Show up control-plane nodes as scheduable (done) 
2. Install engine on the nodes (missing)
3. Let the nodes accept replicas (missing)

### Support Bundle for Troubleshooting

[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-03-07T14-20-25Z.zip](https://github.com/user-attachments/files/19127951/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-03-07T14-20-25Z.zip)

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): NA
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 3
- Node config
  - OS type and version: Talos 1.9.4
  - Kernel version: 6.12.13
  - CPU per node: Ryzen 5700U
  - Memory per node: 64GB
  - Disk type (e.g. SSD/NVMe/HDD): NVMe
  - Network bandwidth between the nodes (Gbps): 2.5 Gbps
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 3

**Comment by DamiaSan** [comment]
Hi @Syntax3rror404 , have you had a look at https://github.com/longhorn/longhorn/issues/2664 ?

**Comment by derekbit** [comment]
@DamiaSan Remember to update the status to `Waiting For Reporter`

**Comment by Syntax3rror404** [comment]
@DamiaSan I dont see in this referenced issue any relevant information about this problem?! What do you mean exactly?

**Comment by DamiaSan** [comment]
Hi @Syntax3rror404 , could you send a support bundle to further investigate?

**Comment by Syntax3rror404** [comment]
> Hi [@Syntax3rror404](https://github.com/Syntax3rror404) , could you send a support bundle to further investigate?

The support bundle is already attached to this issue. Please scroll up to the top of this issue.

**Comment by DamiaSan** [comment]
> > Hi [@Syntax3rror404](https://github.com/Syntax3rror404) , could you send a support bundle to further investigate?
> 
> The support bundle is already attached to this issue. Please scroll up to the top of this issue.

Sorry, thanks!

**Comment by DamiaSan** [comment]
Looking in the support bundle, here an example of what I discovered.

Into the file `yamls/namespaced/longhorn-system/v1/pods.yaml` we have:
```
 - apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-03-06T14:26:33Z"
    generateName: longhorn-manager-
    labels:
      app: longhorn-manager
  ...
  spec:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
```
Into the file `yamls/cluster/v1/nodes.yaml`we have:
```
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      node-role.kubernetes.io/control-plane: "null"
  ...
  spec:
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
```
The value of taint's key is `null` and not equal to `true` as in the helm chart. Toleration however should apply the same because it checks if the key `Exists`.
Can it be the reason of the issue @c3y1huang ? If not, what else do you suggest to investigate?

cc @derekbit
