### ISSUE TITLE
[BUG] Longhorn Volume Encryption Not Working in Talos 1.9.x

### ISSUE THREAD

**Issue by shelumiel** [longhorn/longhorn#10584]
### Describe the Bug

```
MountVolume.MountDevice failed for volume "pvc-5229e867-2822-4073-b8f7-0c87b9e7978f" : rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-5229e867-2822-4073-b8f7-0c87b9e7978f with LUKS: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/7780/ns/mnt --ipc=/host/proc/7780/ns/ipc cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-5229e867-2822-4073-b8f7-0c87b9e7978f -d /dev/stdin], output , stderr Failed to open key file. : exit status 1
```

The Longhorn configuration remains identical across Talos 1.8.x and 1.9.x, with the encryption key provided via a Kubernetes secret as instructed in Longhorn’s documentation. Encryption works correctly on Talos 1.8.4 but fails on Talos 1.9.x.
I reported this issue to Talos (https://github.com/siderolabs/talos/issues/10473). According to smira’s investigation, the issue may stem from how cryptsetup is invoked with the parameter -d /dev/stdin, which consistently fails. The parameter appears to be the cause of the encryption failure.

### To Reproduce

1. Deploy a Talos cluster running version 1.9.4 or 1.9.5 and configure Longhorn with volume encryption enabled, following the Longhorn documentation (https://longhorn.io/docs/1.8.1/advanced-resources/security/volume-encryption/).
2. Create an encrypted volume and attempt to mount it.
3. Observe that the volume mount fails with the error mentioned above.
4. Replicate the failure manually by running from a privileged pod. Also, note that replacing "-d /dev/stdin" with "-d -" results in a successful execution.
```
nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1 -d /dev/stdin
```

### Expected Behavior

Longhorn volume encryption should function correctly on Talos 1.9.x as it does on Talos 1.8.x. When an encrypted volume is created and mounted, cryptsetup should successfully format and open the volume without errors, allowing it to be used by pods. Specifically, cryptsetup should be invoked with the proper parameter so that the encryption key is correctly read.

### Additional context

Please refer to the conversations at https://github.com/siderolabs/talos/issues/10473. Initially, the issue was reported in relation to Rook Ceph, but I have added my feedback regarding Longhorn.

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): Any encrypted volume
- Installation method: Helm
- Kubernetes distro and version: 1.32.2
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 6
- Node config
  - OS type and version: Talos Linux 1.9.x (except v1.9.0, in which Longhorn volume "creation" fails for a different reason)
  - Kernel version: 6.12.13
  - CPU per node: 8
  - Memory per node: 16GB
  - Disk type (e.g. SSD/NVMe/HDD): SSD
  - Network bandwidth between the nodes (Gbps): 1Gbps

**Comment by c3y1huang** [comment]
Thank you for raising this. Did you first notice the issue with Talos v1.9.0?

> Replicate the failure manually by running from a privileged pod. Also, note that replacing "-d /dev/stdin" with "-d -" results in a successful execution.

Longhorn uses `-d /dev/stdin` because `-d -` requires interactive input. By running the following command directly will fail due to the missing piped input into `/dev/stdin`:
```bash
nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/xvdh -d /dev/stdin
```

The complete execution is equivalent to:
```bash
echo "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/xvdh -d /dev/stdin
```
https://github.com/longhorn/go-common-libs/blob/72871a09bee01932711d953bc0d48a09fa3ddb1e/exec/exec.go#L96-L105

This logic is not specific to Talos; Longhorn uses it for all operating systems. And I don't know why the same Longhorn version works on Talos 1.8.x but not 1.9.x, as IIRC we haven't tested Talos 1.9.x yet. 
https://longhorn.io/docs/1.8.1/best-practices/#operating-system

**Comment by derekbit** [comment]
Mistakenly set **Milestone** and **assignee**. Let's wait for the feedback from Talos team (https://github.com/siderolabs/talos/issues/10473) and determine the next step later.

**Comment by c3y1huang** [comment]
> [@smira](https://github.com/smira) (Talos member) has just posted the following feedback ([siderolabs/talos#10473](https://github.com/siderolabs/talos/issues/10473)):
> 
> > > Longhorn uses -d /dev/stdin because -d - requires interactive input. If you run the following command directly for testing, it should fail due to the missing piped input into /dev/stdin:
> > 
> > 
> > This is not true. The proper way is to follow cryptsetup documentation:
> > ```
> > / # echo "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> > r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d /dev/std
> > in
> > Failed to open key file.
> > / # echo -n "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> > r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d -
> > / # (successfully encrypted)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The -d /dev/stdin simply doesn't work.

Thank you for the feedback. This is interesting because, based on the cryptsetup codebase, `-` is expected to be equivalent to `/dev/stdin`.

- https://web.git.kernel.org/pub/scm/utils/cryptsetup/cryptsetup.git/tree/src/cryptsetup.c?h=v2.7.x#n362
- https://gitlab.com/cryptsetup/cryptsetup/-/blob/v2.7.5/src/cryptsetup.c?ref_type=tags#L362
- https://github.com/siderolabs/pkgs/blob/v1.9.0/Pkgfile#L19-L20

**Comment by derekbit** [comment]
> > [@smira](https://github.com/smira) (Talos member) has just posted the following feedback ([siderolabs/talos#10473](https://github.com/siderolabs/talos/issues/10473)):
> > > > Longhorn uses -d /dev/stdin because -d - requires interactive input. If you run the following command directly for testing, it should fail due to the missing piped input into /dev/stdin:
> > > 
> > > 
> > > This is not true. The proper way is to follow cryptsetup documentation:
> > > ```
> > > / # echo "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> > > r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d /dev/std
> > > in
> > > Failed to open key file.
> > > / # echo -n "passphrase" | nsenter -t 1 -m cryptsetup  -q luksFormat --type luks2 --ciphe
> > > r aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/loop1  -d -
> > > / # (successfully encrypted)

>>>> That said, it makes sense to follow the cryptsetup document. We should test - works for cryptsetup and Talos. What do you think @mantissahz @derekbit ?

@c3y1huang Sure. Could you help test it?

In addition to the differences between using `-d /dev/stdin` and `-d -`, there's also a difference between `echo "passphrase"` and `echo -n "passphrase"`. The former appends a newline char at the end. Could that extra newline be the root cause of the failure?

**Comment by c3y1huang** [comment]
> In addition to the differences between using `-d /dev/stdin` and `-d -`, there's also a difference between `echo "passphrase"` and `echo -n "passphrase"`. The former appends a newline char at the end. Could that extra newline be the root cause of the failure?

Nice catch! Looks like the Talos team is testing the `-` flag in combination with an additional `-n` flag. Not sure if that would make a difference, though.

**Comment by smira** [comment]
From [cryptsetup man page](https://man7.org/linux/man-pages/man8/cryptsetup-luksFormat.8.html):

```
--key-file, -d name
           Read the passphrase from file.

           If the name given is "-", then the passphrase will be read
           from stdin. In this case, reading will not stop at newline
           characters.

           See section NOTES ON PASSPHRASE PROCESSING in [cryptsetup(8)](https://man7.org/linux/man-pages/man8/cryptsetup.8.html)
           for more information.
```

So newlines are not stripped when reading from stdin.

**Comment by c3y1huang** [comment]
> From [cryptsetup man page](https://man7.org/linux/man-pages/man8/cryptsetup-luksFormat.8.html):
> 
> ```
> --key-file, -d name
>            Read the passphrase from file.
> 
>            If the name given is "-", then the passphrase will be read
>            from stdin. In this case, reading will not stop at newline
>            characters.
> 
>            See section NOTES ON PASSPHRASE PROCESSING in [cryptsetup(8)](https://man7.org/linux/man-pages/man8/cryptsetup.8.html)
>            for more information.
> ```
> 
> So newlines are not stripped when reading from stdin.

Thank you, @smira , for your feedback! Maybe you can share any additional insights:
1. It looks like @shelumiel used the same Longhorn version with an identical configuration on Talos 1.8 and 1.9, but the volume encryption error only occurred on Talos 1.9. Do you know if any changes in Talos 1.9 could have triggered this?
1. From your test, using `-d /dev/stdin` with echo (without `-n`) resulted in an error. Does the error still occur when using `echo -n` instead?

**Comment by smira** [comment]
> It looks like @shelumiel used the same Longhorn version with an identical configuration on Talos 1.8 and 1.9, but the volume encryption error only occurred on Talos 1.9. Do you know if any changes in Talos 1.9 could make this difference?

I'm not directly aware of that.

> From your test, using -d /dev/stdin with echo (without -n) resulted in an error. Does the error still occur when using echo -n instead?

The problem is `/dev/stdin`, it simply doesn't work (and it's documented that one should use `-` instead). I don't know where `/dev/stdin` is coming from. It's not a regular file, so I guess `cryptsetup` fails to read from it, while it has special handling for `-`.

**Comment by c3y1huang** [comment]
### Observation

I added logs and ran the `test_csi_encrypted_block_volume` test to collect the behavior of `cryptsetup` when using `-d /dev/stdin` and `-d -` on Longhorn with Talos `1.8` and `1.9`. Based on the logs:

- **Talos 1.8.3:** Using `-d /dev/stdin`, encryption succeeds.
- **Talos 1.9.5:** Using `-d /dev/stdin`, cryptsetup fails to open the key file.
- **Talos 1.9.5:** Using `-d -`, encryption succeeds.

### Proposed Fix
Update Longhorn to the `-d -` for cryptsetup instead of `-d /dev/stdin` for compatibility with newer Talos versions.

---
### Talos 1.8.3 & Longhorn master

```bash
> k get nodes ip-10-0-29-149 -o yaml | grep Talos
    osImage: Talos (v1.8.3)

> ./run.sh -xs -k test_csi_encrypted_block_volume
============================= 1 passed, 389 deselected, 7 warnings in 147.24s (0:02:27) ==============================
```
```log
[longhorn-csi-plugin-x874h longhorn-csi-plugin] time="2025-03-18T22:40:25Z" level=info msg="Encrypting device /dev/longhorn/pvc-5fa02ef5-b89a-4476-a408-9a3abe0a939a with LUKS" func=crypto.EncryptVolume file="crypto.go:103"
[longhorn-csi-plugin-x874h longhorn-csi-plugin] time="2025-03-18T22:40:25Z" level=info msg="[DEBUG] Running cryptsetup [-q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-5fa02ef5-b89a-4476-a408-9a3abe0a939a -d /dev/stdin]" func="ns.(*Executor).LuksFormat" file="crypto.go:42"
[longhorn-csi-plugin-x874h longhorn-csi-plugin] time="2025-03-18T22:40:33Z" level=info msg="Device /dev/longhorn/pvc-5fa02ef5-b89a-4476-a408-9a3abe0a939a is encrypted with LUKS" func=crypto.EncryptVolume file="crypto.go:123"
```

### Talos 1.9.5 & Longhorn master

- `-d /dev/stdin`
    ```bash
    > k get nodes ip-10-0-21-64 -o yaml | grep Talos
        osImage: Talos (v1.9.5)

    > ./run.sh -xs -k test_csi_encrypted_block_volume
    ========================= 1 failed, 389 deselected, 6 warnings, 1 error in 418.13s (0:06:58) =========================
    ```
    ```log
    [longhorn-csi-plugin-d794k longhorn-csi-plugin] time="2025-03-18T10:42:22Z" level=info msg="Encrypting device /dev/longhorn/pvc-30c0c814-3e92-4f24-878b-8b48a32e089b with LUKS" func=crypto.EncryptVolume file="crypto.go:103"
    [longhorn-csi-plugin-d794k longhorn-csi-plugin] time="2025-03-18T10:42:22Z" level=info msg="[DEBUG] Running cryptsetup [-q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-30c0c814-3e92-4f24-878b-8b48a32e089b -d /dev/stdin]" func="ns.(*Executor).LuksFormat" file="crypto.go:42"
    [longhorn-csi-plugin-d794k longhorn-csi-plugin] time="2025-03-18T10:42:22Z" level=error msg="NodeStageVolume: err: rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-30c0c814-3e92-4f24-878b-8b48a32e089b with LUKS: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/167896/ns/mnt --ipc=/host/proc/167896/ns/ipc cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-30c0c814-3e92-4f24-878b-8b48a32e089b -d /dev/stdin], output , stderr Failed to open key file.\n: exit status 1" func=csi.logGRPC file="server.go:136"
    ```

- `-d -`
    ```bash
    > k get nodes ip-10-0-21-64 -o yaml | grep Talos
        osImage: Talos (v1.9.5)

    > ./run.sh -xs -k test_csi_encrypted_block_volume
    ============================= 1 passed, 389 deselected, 7 warnings in 186.52s (0:03:06) ==============================
    ```
    ```log
    [longhorn-csi-plugin-w7vlc longhorn-csi-plugin] time="2025-03-18T10:24:25Z" level=info msg="Encrypting device /dev/longhorn/pvc-bbc40732-60ca-4e79-a337-f54182f777cc with LUKS" func=crypto.EncryptVolume file="crypto.go:103"
    [longhorn-csi-plugin-w7vlc longhorn-csi-plugin] time="2025-03-18T10:24:25Z" level=info msg="[DEBUG] Running cryptsetup [-q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-bbc40732-60ca-4e79-a337-f54182f777cc -d -]" func="ns.(*Executor).LuksFormat" file="crypto.go:40"
    [longhorn-csi-plugin-w7vlc longhorn-csi-plugin] time="2025-03-18T10:24:32Z" level=info msg="Device /dev/longhorn/pvc-bbc40732-60ca-4e79-a337-f54182f777cc is encrypted with LUKS" func=crypto.EncryptVolume file="crypto.go:123"
    ```

**Comment by roger-ryao** [comment]
**Verified on master-head 20250326**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/b265b3f9abd577d20759b5a5feb443bf6230b0f9
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/f5ad885cc32edd66dc92cf525b9e2a233494ed34
- longhorn-share-manager `master-head` https://github.com/longhorn/longhorn-share-manager/commit/87acedee73da6f0b957284adf797afebb9bcd20b


**The test steps**

---

### **1. Clone the Repository**
Clone the `longhorn-tests` repository:

```bash
git clone https://github.com/longhorn/longhorn-tests
```

---

### **2. Modify Terraform Files**
Edit the following files to update configurations:

#### **File: `test_framework/terraform/aws/talos/data.tf`**
```bash
--- a/test_framework/terraform/aws/talos/data.tf
+++ b/test_framework/terraform/aws/talos/data.tf
@@ -2,7 +2,7 @@ data "aws_ami" "talos" {
   most_recent = true
   filter {
     name   = "name"
-    values = ["talos-v${var.os_distro_version}-${var.arch}"]
+    values = ["talos-v${var.os_distro_version}-${var.aws_region}-${var.arch}"]
   }
   owners = [var.aws_ami_talos_account_number]
 }
```

#### **File: `test_framework/terraform/aws/talos/variables.tf`**
```bash
--- a/test_framework/terraform/aws/talos/variables.tf
+++ b/test_framework/terraform/aws/talos/variables.tf
 variable "os_distro_version" {
   type        = string
-  default     = "1.8.3"
+  default     = "1.9.5"
}
 variable "aws_ami_talos_account_number" {
   type        = string
-  default     = "641769369267"
+  default     = "540036508848"
}
```

---

### **3. Build Talos Cluster**
Run the following command to build the Talos cluster:

```bash
longhorn-tests> TF_VAR_k8s_distro_name=k3s LONGHORN_TEST_CLOUDPROVIDER=aws DISTRO=talos ./pipelines/utilities/terraform_setup.sh
```

---

### **4. Retrieve Cluster Configurations**
After the process completes, navigate to the directory:

```bash
longhorn-tests> cd test_framework/terraform/aws/talos
```

Retrieve the `kubeconfig` and `talos_k8s_config` files.

---

### **5. Configure Talos Endpoints**
Set the endpoints and nodes for Talos using `talosctl`:

```bash
talosctl --talosconfig talos_k8s_config config endpoint ${CP_NODE_1_PUBLIC_IP}
talosctl --talosconfig talos_k8s_config config node ${CP_NODE_1_PUBLIC_IP}
```

Example:
```bash
talosctl --talosconfig talos_k8s_config config endpoint 107.23.134.82
talosctl --talosconfig talos_k8s_config config node 107.23.134.82
```

---

### **6. Check Cluster Health**
Verify the Talos cluster health status:

```bash
talosctl --talosconfig talos_k8s_config health
```

Expected output:
```bash
discovered nodes: ["10.0.1.161" "10.0.1.177" "10.0.1.204" "10.0.1.19"]
waiting for etcd to be healthy: OK
waiting for etcd members to be consistent across nodes: OK
waiting for etcd members to be control plane nodes: OK
waiting for apid to be ready: OK
waiting for all nodes memory sizes: OK
```

---

### **7. Create Talos Schematic**
Follow the [Talos Guide](https://www.talos.dev/v1.9/talos-guides/install/boot-assets/#image-factory) to create a schematic file.

#### **File: `longhorn-talos.yaml`**
```yaml
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/iscsi-tools
      - siderolabs/util-linux-tools
```

Upload the schematic file to the Image Factory:

```bash
curl -X POST --data-binary @longhorn-talos.yaml https://factory.talos.dev/schematics
```

Expected response:
```bash
{"id":"613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245"}
```

---

### **8. Upgrade Talos Cluster**
Use the schematic ID to upgrade the cluster:

```bash
talosctl --talosconfig talos_k8s_config upgrade --image factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
```

Upgrade individual nodes:
```bash
talosctl --talosconfig talos_k8s_config -n 10.0.1.161 upgrade --image factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
talosctl --talosconfig talos_k8s_config -n 10.0.1.177 upgrade --image factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
talosctl --talosconfig talos_k8s_config -n 10.0.1.204 upgrade --image factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
```

---

### 9. Create Namespace and Apply Labels

Run the following commands to create the `longhorn-system` namespace and apply the necessary security labels:

```bash
kubectl create ns longhorn-system
kubectl label ns longhorn-system pod-security.kubernetes.io/enforce=privileged
kubectl label ns longhorn-system pod-security.kubernetes.io/enforce-version=latest
kubectl label ns longhorn-system pod-security.kubernetes.io/audit=privileged
kubectl label ns longhorn-system pod-security.kubernetes.io/audit-version=latest
kubectl label ns longhorn-system pod-security.kubernetes.io/warn=privileged
kubectl label ns longhorn-system pod-security.kubernetes.io/warn-version=latest
```

After setting up the namespace and labels, deploy Longhorn :

```bash
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
```
--- 

### **10. Apply Secrets**
Create and apply the `longhorn-crypto` secret:

<details>
<summary>Click to expand YAML for `secret-crypto-global.yaml`</summary>

````yaml
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "cfc35bc9fc4f8518dbda7798b931bd9b2c146b68ae40801c42bf28daacbf3ef7"
  CRYPTO_KEY_PROVIDER: "secret" # Optional
````

</details>

Apply the secret:
```bash
kubectl apply -f secret-crypto-global.yaml
```

---

### **11. Apply StorageClass**
Define and apply the `longhorn-crypto-global` storage class:

<details>
<summary>Click to expand YAML for `longhorn-crypto-global.yaml`</summary>

````yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-crypto-global
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
````

</details>

Apply the storage class:
```bash
kubectl apply -f longhorn-crypto-global.yaml
```

---

### **12. Deploy Encrypted Volumes**
Define and apply deployments using encrypted volumes.

<details>
<summary>Click to expand YAML for `deployment_crypto.yaml`</summary>

````yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:8.0
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:8.0
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
````

</details>

Apply the deployment:
```bash
kubectl apply -f deployment_crypto.yaml
```

---

### **13. Verify Volume and Pod Status**
Ensure that the volumes are attached successfully and pods are working as expected.


## **Result Passed**
