### ISSUE TITLE
feature: shard support

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1061]
Support sharding across different disks (same or different nodes) for one volume.

**Comment by jcambronero** [comment]
hi @yasker, what is the status of this feature please?

**Comment by yasker** [comment]
@jcambronero We haven't scheduled this feature yet. What's your use case? Currently, we're recommending using LVM to aggregate disks on one node to help.

**Comment by jcambronero** [comment]
thank you @yasker , we would like to have the ability to create volumes that are larger that the maximum capacity available on a single node. We're hoping sharding across different nodes would allow us to accomplish this.

**Comment by yasker** [comment]
In that case, yes you will need this feature. We are in the development cycle of v1.1.0 release, targeting October. Once we're done with v1.1.0, we can take a look and see what we can do about this feature.

**Comment by PhilParisot** [comment]
Any updates for this?

**Comment by yasker** [comment]
@PhilParisot we've raised the priority of this issue. We will start working on it in the near future.

**Comment by PhilParisot** [comment]
Awesome thanks @yasker!

**Comment by yasker** [comment]
Also, as an alternative, we can consider LVM in striping mode. But need to know what we should do to deal with the disk failure.

**Comment by michaelandrepearce** [comment]
An approach ive seen in other distributed storage solutions is that a block volume is broken into chunks and chunks are then managed in similar way to how the currently the whole volume is, where then the chunks are individually replicated and moved etc.

**Comment by innobead** [comment]
> I dont see how lvm stripping mode will work as lvm is still local to a single node. The issue i have is that i need a pv larger than a single node. An approach ive seen in other distributed storage solutions is that a block volume is broken into chunks and chunks are then managed in similar way to how the currently the whole volume is, where then the chunks are individually replicated and moved etc.

The definite end goal is to try to leverage all disk resources across the nodes in the future, but right now, what we are looking for is based on the current architecture and design to efficiently enhance in-node disk-based volume management to in-node across-disks-based.

**Comment by michaelpearce-gain** [comment]
@innobead thats pretty much useless, i can manage that in node with LVM today, the issue is that we need PV's larger than disks within a node.

**Comment by mfbrj** [comment]
Sharding in the same node seems to be useless. Anyone can create a node with larger disks. What we neeed is transpararent sharding leveraging the space on several nodes, pehaps with another concept beyond simple replicas. Chunks?

An example of a new Model:
A 512 GB volume compound by 4 chuncks of 128 GB, each chunk with 2 replicas. This volume can easily fit on 8 (4 chunks x 2 replicas) nodes with single 200 GB disk.

**Comment by LaurensVanAcker** [comment]
So striping to double read speeds isn't possible at the moment? Unless you point Longhorn to a volume created by ZFS, mdadm or LVM?

**Comment by IDerr** [comment]
Hi, 
I'm really interested in that feature ! It's hard to store big PVC (9 TB 😢) over single disks or over LVM LV (only 4 ssd per server).... 

Thanks a lot for your great work !

**Comment by IDerr** [comment]
> So striping to double read speeds isn't possible at the moment? Unless you point Longhorn to a volume created by ZFS, mdadm or LVM?

@LaurensVanAcker It should be faster reads, but you'll also have the issue of disk failures, if one disk on your array fails, your node storage (if you merge all yours disk in one array) will go down. But with replicas, you can "bypass" this issue, it'll be a equivalent of a RAID 10. 
Using chunks will be a better way to solve this, at least when you'll be losing a disk, only data from this disk will be invalid instead of the whole node :)

@innobead do you know if this is still a issue that will be fixed, or are you discussing of another way to solve this ?

Thanks a lot for this amazing product :D

**Comment by Ornias1993** [comment]
@yasker I notice you changed this, might be worth while to also keep a ticket open for sharding between multiple disks on the same node.
As it would mean just that single disk has to be recovered, instead of the current go-to lvm/mdadm stripe solution.

**Comment by darthVikes** [comment]
> @jcambronero We haven't scheduled this feature yet. What's your use case? Currently, we're recommending using LVM to aggregate disks on one node to help.

Are you recommending that the drives are in some sort of RAID 1/5/10/etc Hardware/Controller Logical Drive before adding them to an LVM?  Or add X amount of physical drives to the LVM w/ Software Striping?  Or are you saying it's ok to just add the physical drives to an LVM?  Have you seen issues then when the physical drive dies with the LVM?

**Comment by KyleSanderson** [comment]
Any update on this? microceph is on track to make this entire project obsolete as all the gains have been completely squandered...

**Comment by Ornias1993** [comment]
> Any update on this? microceph is on track to make this entire project obsolete as all the gains have been completely squandered...

WTF is microceph?

**Comment by leon-marzahn** [comment]
Any update on this? I'm personally more interested in disk sharding

**Comment by innobead** [comment]
> Any update on this? I'm personally more interested in disk sharding

Still planned for 1.7, and it will be based on the v2 data engine first.

**Comment by rhysperry111** [comment]
I appreciate that this is a complex feature to implement, but am just wondering what the short-term outlook is on it potentially being implemented. Can it really be expected in the next release or two, or is it likely to keep being pushed back?

Only asking because I've got to make design decisions now, but still have quite a while until I need to implement them.

**Comment by cornfeedhobo** [comment]
4 years later, this is still the main feature blocking my adoption of longhorn

**Comment by Ornias1993** [comment]
> @cornfeedhobo What are you using instead?

I use Rook-Ceph:
- It "just works"
- RWX, RWO, Block etc all perfectly viable
- Has LOTS of docs
- Has LOTS of information of users when you run into issues

The area where CEPH is weaker is things like mass hdd storage, but longhorn doesn't support that well at all in the first place

**Comment by linuxfreakus** [comment]
> 4 years later, this is still the main feature blocking my adoption of longhorn

Ceph is on the radar here, because longhorn is severely deficient in this area...  cannot make volumes above about 1TB because it becomes impractical... and the longhorn manager loses its mind sometimes when working on the replicas.... its really unfortunate that we can't have huge volumes made up of multiple underlying volumes.  Its literally THE missing feature.

**Comment by DamiaSan** [comment]
> > 4 years later, this is still the main feature blocking my adoption of longhorn
> 
> Ceph is on the radar here, because longhorn is severely deficient in this area... cannot make volumes above about 1TB because it becomes impractical... and the longhorn manager loses its mind sometimes when working on the replicas.... its really unfortunate that we can't have huge volumes made up of multiple underlying volumes. Its literally THE missing feature.
> 
> Ceph is a huge pain to maintain, so I keep hoping to avoid it.

For the v2 engine, it is scheduled for Longhorn v1.9 (March 2025): Longhorn Engine v2 Sharding (Experimental)
https://github.com/longhorn/longhorn/wiki/Roadmap

**Comment by derekbit** [comment]
The feature involves the architecture design, performance, rebuilding. @c3y1huang will take the lead in designing [V2 Storage Sharding](https://github.com/longhorn/longhorn/issues/1061) and break it down into sub-topics and assign them to team members. Of course, we need more discussions and investigation first.

cc @DamiaSan @shuo-wu @PhanLe1010 @innobead

**Comment by liyimeng** [comment]
So the plan is to support all raid level, including raid5f when landing sharding feature? @derekbit

**Comment by derekbit** [comment]
> So the plan is to support all raid level, including raid5f when landing sharding feature? [@derekbit](https://github.com/derekbit)

Not sure for now. It is still in pre-design stage.

**Comment by derekbit** [comment]
@c3y1huang We can start the study and design from v1.11.0.

cc @innobead

**Comment by xuande** [comment]
Is there any new release plan for Sharding feature? It’s listed as an experimental feature in the Roadmap for V1.12—do we have a GA deadline for it?

**Comment by c3y1huang** [comment]
### Manual Test

#### Preparation
1. **Given** V2 is enabled.
1. **When** creating a sharded volume.
    ```yaml
    apiVersion: longhorn.io/v1beta2
    kind: Volume
    metadata:
      name: ec-vol
      namespace: longhorn-system
    spec:
      size: "1073741824"
      dataEngine: v2
      numberOfReplicas: 1
      dataLocality: disabled
      dataLayout:
        type: sharded
        mode: erasureCoding
        dataChunks: 2
        parityChunks: 1
        stripSizeKB: 64
      frontend: blockdev
      accessMode: rwo
    ```
1. **And** create PV and PVC for the volume.
    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: ec-vol-pv
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      csi:
        driver: driver.longhorn.io
        volumeHandle: ec-vol
        fsType: ext4
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ec-vol-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeName: ec-vol-pv
      storageClassName: ""
    ```
1. **Then** the Volume CR should be created and `detached`.
    ```
    NAME     DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
    ec-vol   v2            detached   unknown                  1073741824          8m22s
    ```
1. **And** the ShardGroup CR should be created and `healthy`.
    ```
    NAME     VOLUME   STATE     NODE            FAILED   AGE
    ec-vol   ec-vol   healthy   ip-10-0-2-214   0        9m45s
    ```
1. **And** the Shard CRs should be created and `normal`.
    ```
    NAME       SHARDGROUP   SLOT   NODE            STATE    ROLE     AGE
    ec-vol-0   ec-vol       0      ip-10-0-2-5     normal   data     10m
    ec-vol-1   ec-vol       1      ip-10-0-2-214   normal   data     10m
    ec-vol-2   ec-vol       2      ip-10-0-2-219   normal   parity   10m
    ```
1. **And** the Engine CR should be created and `stopped`.
	```
	NAME         DATA ENGINE   STATE     NODE   INSTANCEMANAGER   IMAGE   AGE
	ec-vol-e-0   v2            stopped                                    11m
	```

#### Test Attach
1. **When** a pod with the PVC is created.
	```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: ec-test-pod
    spec:
      containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "while true; do sleep 5; done"]
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ec-vol-pvc
	```
1. **Then** the volume is `attached` and `healthy`.
    ```
    NAME     DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE            AGE
    ec-vol   v2            attached   healthy                  1073741824   ip-10-0-2-214   25m
    ```
1. **And** the pod is `Running`.
    ```
    NAME          READY   STATUS    RESTARTS   AGE
    ec-test-pod   1/1     Running   0          49s
    ```
1. **And** can read and write to the pod's `/data`.
    ```
    > k exec -it ec-test-pod -- sh
    / # echo 0 > /data/data.txt
    / # cat /data/data.txt 
    0
    ```
1. **When** recreate pod.
    ```
    > k delete pod ec-test-pod 
    pod "ec-test-pod" deleted
    > k apply -f 02-attach-workload.yaml 
    pod/ec-test-pod created
    ```
1. **Then** data still intact.
    ```
	> k exec -it ec-test-pod -- sh -c "cat /data/data.txt"
    0
    ```

#### Test Snapshot
1. **When** a snapshot is created for the volume.
    ```
    NAME                    VOLUME   CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE       AGE
    snap-39acf82e78ce44e7   ec-vol   2026-07-14T03:46:22Z   true         1073741824    79691776   7s
    ```
1. **And** write to the volume.
    ```
    > k exec -it ec-test-pod -- sh -c "echo 1 > /data/data.txt"
    > k exec -it ec-test-pod -- sh -c "cat /data/data.txt"
    1
    ```
1. **And** delete the pod to detach the volume.
1. **And** attach the volume in maintenance mode.
1. **And** revert the snapshot.
1. **And** detach the volume.
1. **And** create the pod.
1. **Then** check the content in `/data/data.txt` should be `0`.
    ```
    > k exec -it ec-test-pod -- sh -c "cat /data/data.txt"
    0
    ```

#### Test Expansion (dynamically provisioned PVC)##
1. **When** creating a sharded volume with a storage class.
    ```yaml
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: longhorn-ec
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      dataLayout.type: "sharded"
      dataLayout.mode: "erasureCoding"
      dataLayout.dataChunks: "2"
      dataLayout.parityChunks: "1"
      dataLayout.stripSizeKB: "64"
      dataLocality: disabled
      numberOfReplicas: "1"
      dataEngine: "v2"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ec-test
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: longhorn-ec
      resources:
        requests:
          storage: 1Gi
    ```
1. **And** a pod with the PVC is created and attached.
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: ec-test
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ec-test
    ```
1. **And** write some data to the volume.
    ```yaml
    > k exec -it ec-test -- sh -c "echo 2 > /data/data.txt"
    > k exec -it ec-test -- sh -c "cat /data/data.txt"
    2
    ```
1. **Given** record the current volume size.
    ```yaml
    > k -n longhorn-system get volume
    NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE            AGE
    pvc-f733c2a3-de46-43b8-a274-fed63fa05b31   v2            attached   healthy                  1073741824   ip-10-0-2-214   5m38s
    > k exec -it ec-test -- sh -c "df -h /data"
    Filesystem                Size      Used Available Use% Mounted on
    /dev/longhorn/pvc-f733c2a3-de46-43b8-a274-fed63fa05b31
                            973.4M     28.0K    957.4M   0% /data
    ```
1. **When** expand the volume size.
1. **Then** check the volume is expanded.
    ```yaml
    > k -n longhorn-system get volume
    NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE            AGE
    pvc-f733c2a3-de46-43b8-a274-fed63fa05b31   v2            attached   healthy                  2147483648   ip-10-0-2-214   7m34s
    > k exec -it ec-test -- sh -c "df -h /data"
    Filesystem                Size      Used Available Use% Mounted on
    /dev/longhorn/pvc-f733c2a3-de46-43b8-a274-fed63fa05b31
                              1.9G     28.0K      1.9G   0% /data
    ```
1. **And** can read and write.
    ```yaml
    > k exec -it ec-test -- sh -c "cat /data/data.txt"
    2
    > k exec -it ec-test -- sh -c "echo 3 > /data/data.txt"
    > k exec -it ec-test -- sh -c "cat /data/data.txt"
    3
    ```

**Comment by derekbit** [comment]
As discussed, we need the following:

- Add an example under [examples/](https://github.com/longhorn/longhorn/tree/master/examples) in longhorn/longhorn that demonstrates how to create:
  - storageclass.yaml
  - pod_with_pvc.yaml
- Add documentation to the official docs and clearly mark the feature as Experimental, covering:
  - The purpose of the feature
  - The pros and cons compared to replication
  - The functionalities currently supported
  - How to create a volume using this feature
  - Performance benchmarks (can be added later)

cc @PhanLe1010 @shuo-wu @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/bc1d7ff798c791552777f7408d2b7b0365f22686) with test [step](https://github.com/longhorn/longhorn/issues/1061#issuecomment-4965318645) on both amd64 and arm64 clusters

We need the doc https://github.com/longhorn/longhorn/pull/13159 complete before close this ticket.

**Comment by c3y1huang** [comment]
## Bug Identified: EC volume turned read-only during kbench

### RCA

kbench failed when it reached the sequential read bandwidth phase:
```
Benchmarking random read iops
Benchmarking random write iops
Benchmarking sequential read bandwidth
fio: pid=0, err=30/file:filesetup.c:254, func=fsync, error=Read-only file system
open path: No such file or directory
```

With added SPDK logging:
```
blobstore.c:3084:bs_allocate_and_copy_cluster: *WARNING*: Blobstore out of space:
cannot allocate a cluster for a thin-provisioned write (free clusters: 0 of 8439
data clusters); failing writes with ENOSPC until space is freed

nvme_qpair.c: 310: ... WRITE sqid:2 cid:48 nsid:1 lba:67362816 len:256 ...
nvme_qpair.c: 531: ... CAPACITY EXCEEDED (00/81) qid:2 cid:48 ... dnr:0
```

Seems the shards are sized too small to back the full volume. The volume ran out of space.

The manager sizes the shards with [ComputeShardSize](https://github.com/longhorn/longhorn-manager/blob/7fe937a87a4dce61fe81f4c0f9421666c307bf7b/scheduler/shard_scheduler.go#L125-L134): the volume size + the EC front reservation. That budget covers only the EC bdev's own metadata. The engine then builds two more layers on top of the EC bdev: an lvstore ([shardgroup.go#L612](https://github.com/longhorn/longhorn-spdk-engine/blob/0548818e17e9d42b48171f251d22376e6beecafd/pkg/spdk/shardgroup.go#L612)) and, inside it, a thin head lvol at the full volume size ([shardgroup.go#L627](https://github.com/longhorn/longhorn-spdk-engine/blob/0548818e17e9d42b48171f251d22376e6beecafd/pkg/spdk/shardgroup.go#L627)). The lvstore spends some of the EC bdev's space on its own metadata. The shard sizing never budgets for that, so the space behind the head lvol is smaller than the head lvol's size.

```
 what the engine writes to:
 +------------------------------------------------------------------+
 | HEAD LVOL (thin)                 promises 33 GiB  (8,448 units)  |
 +------------------------------------------------------------------+
 | LVSTORE on EC bdev               can store 33 GiB - 36 MiB       |
 |                                            (8,439 units)   <<< too small
 +------------------------------------------------------------------+
 | EC BDEV                          33 GiB + 1.75 MiB               |
 +------------------------------------------------------------------+
 | SHARD LVOL (per disk)            33 GiB + 130 MiB                |
 +------------------------------------------------------------------+

 1 unit = one 4 MiB cluster
```

The head lvol is thin, so creation succeeds. The failure comes later: each first write to a new area claims a cluster from the lvstore. Once the workload has touched enough unique blocks, no free cluster is left. The next first-touch write fails with ENOSPC, the engine's single-leg RAID1 fails its only base, and ext4 remounts read-only.

#### Proposed Fix (WIP)

- **spdk**: improve error logging.
- **go-spdk-engine**: pin the lvstore params and buget the lvstore metadata in the shared ComputeShardSize.
- **longhorn-spdk-engine**: create the lvstore with the pinned params; fail create and expand when the lvstore cannot back the volume size.
- **longhorn-manager**: use the shared ComputeShardSize.

**Comment by c3y1huang** [comment]
Moving the issue back to the implementation phase due to the [identified bug during kbenching](https://github.com/longhorn/longhorn/issues/1061#issuecomment-5030052549).

cc @derekbit @chriscchien

**Comment by c3y1huang** [comment]
@chriscchien we made some code changes to address  https://github.com/longhorn/longhorn/issues/1061#issuecomment-5030052549. Could you help test this again? Thank you.

**Comment by chriscchien** [comment]
Hi @c3y1huang , I retest with test [steps](https://github.com/longhorn/longhorn/issues/1061#issuecomment-5030052549) and the result passed.

In addition, I did a kbench test but encounstered the issue described here : https://github.com/longhorn/longhorn/issues/1061#issuecomment-5030052549

```
ip-10-0-1-253:/home/ec2-user/kbench # k  get pods -w
NAME           READY   STATUS              RESTARTS   AGE
kbench-4rv4p   0/1     ContainerCreating   0          13s
kbench-4rv4p   0/1     ContainerCreating   0          17s
kbench-4rv4p   1/1     Running             0          21s
^Cip-10-0-1-253:/home/ec2-user/kbench # k logs kbench-4rv4p -f
TEST_FILE: /volume/test
TEST_OUTPUT_PREFIX: ./test_device
TEST_SIZE: 30G
MODE: full
Benchmarking random read iops
Benchmarking random write iops
Benchmarking sequential read bandwidth
fio: pid=0, err=30/file:filesetup.c:240, func=write, error=Read-only file system
open path: No such file or directory
Error getting slave device numbers: No such file or directory
fio: io_u error on file /volume/test: Read-only file system: read offset=0, buflen=131072
```
I was using `https://github.com/derekbit/kbench.git` and `derekbit/kbench:latest`, on AWS with c5d.4xlarge instance. Could you point me out if I did unproper setting or image? thank you.

Below are my steps:

   1. Create storage class `longhorn-ec`
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ec
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  dataLayout.type: "sharded"
  dataLayout.mode: "erasureCoding"
  dataLayout.dataChunks: "2"
  dataLayout.parityChunks: "1"
  dataLayout.stripSizeKB: "64"
  dataLocality: disabled
  numberOfReplicas: "1"
  dataEngine: "v2"
```
   2. clone kbench
```
git clone https://github.com/derekbit/kbench.git
cd kbench
```
   3. Change storageclass to  `longhorn-ec`
```
sed -i \
  's/^  #\$storageClassName: longhorn.*$/  storageClassName: longhorn-ec/' \
  deploy/fio.yaml
```
   4. change image to `derekbit/kbench:latest`
```
sed -i \
  's|^[[:space:]]*image: .*kbench.*|        image: derekbit/kbench:latest|' \
  deploy/fio.yaml
```
   5. start kbench
```
kubectl apply -f deploy/fio.yaml
```
   6. The kbench errors when running `sequential read`
```
io: pid=0, err=30/file:filesetup.c:240, func=write, error=Read-only file system
open path: No such file or directory
Error getting slave device numbers: No such file or directory
fio: io_u error on file /volume/test: Read-only file system: read offset=0, buflen=131072
```

[supportbundle_645d5aa2-8fcd-4fb5-9c14-4a06ca262b2a_2026-07-31T07-27-50Z.zip](https://github.com/user-attachments/files/30578422/supportbundle_645d5aa2-8fcd-4fb5-9c14-4a06ca262b2a_2026-07-31T07-27-50Z.zip)
