### ISSUE TITLE
[BUG] Error on git checkout in a container

### ISSUE THREAD

**Issue by icebear74** [longhorn/longhorn#10621]
### Describe the Bug

We have a container, running with a non-root user, with a volume mount on a volume with ReadWriteMany access.
If we now try to clone a Git repository to the volume in this container, an error occurs with the error message Permission denied. (See screenshot)
If the cloning is executed with the root user, this works without problems, also if the access mode is ReadWriteOnce (independent of the user).
The error also only occurs if the cloning is done in a Longhorn volume, outside it works without problems.
I tested with different Git versions (2.47.2, 2.45.1), also with an Alpine and a Debian base image.
 
The error only occurs when cloning a repository. Pull works without problems.
Different repositories were also tested, as well as cloning a Bitbucket and a GitHub repository.
The error occurs regardless of the repository.
 
It was also tested to set the SecurityContext with fsGroup. The error also occurred in this case. (see: https://longhorn.io/docs/1.7.2/nodes-and-volumes/volumes/pvc-ownership-and-permission/)
 
The error occurred after Longhorn was updated from version 1.7.1 to 1.7.3.

### To Reproduce

Here are a Testpod + PV and PVC to test it
```
apiVersion: v1
kind: Pod
metadata:
  name: test-volume-mount
  namespace: test
spec:
  containers:
  - image: alpine/git:v2.47.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
    - mountPath: "/mnt/test"
      name: testmount
  volumes:
    - name: testmount
      persistentVolumeClaim:
        claimName: test-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    longhorn.io/volume-scheduling-error: ''
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  name: test-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: 'true'
      fromBackup: ''
      fsType: ext4
      numberOfReplicas: '3'
      share: 'true'
      staleReplicaTimeout: '30'
      storage.kubernetes.io/csiProvisionerIdentity: 1742457455667-2644-driver.longhorn.io
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: test-pv
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  name: test-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: test-pv
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound]([url](

![Image](https://github.com/user-attachments/assets/fccbc838-985f-4896-9e5c-5f63b8446ee8)

))
```

### Expected Behavior

Git works :)

### Environment

- Longhorn version: happen since 1.7.3 update from 1.7.1 (testet also 1.8.1 in our dev cluster)
- Impacted volume (PV): test-git and sever others to test
- - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): rancher (on dev with kubectl .., same happens)
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 12
- Node config
  - OS type and version: debian 11
  - Kernel version: several
  - CPU per node: several different
  - Memory per node: different
  - Disk type (e.g. SSD/NVMe/HDD): different
  - Network bandwidth between the nodes (Gbps): 20/40 gbit
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): bare (in dev some bare, some vmware)
- Number of Longhorn volumes in the cluster: around 20 ... 

### Workaround and Mitigation

Only to set as RWO or let container start as root
