### ISSUE TITLE
[BUG] Input/Output Error for some pods (after backups?)

### ISSUE THREAD

**Issue by ojsef39** [longhorn/longhorn#10640]
### Describe the Bug

Hey,

i noticed now multiple times over the last week(s) that some pods, especially the ones with (relatively) bigger volumes (like my prometheus instance) will fail with Input/Output Error.

### To Reproduce

Im not sure, i think its caused by my backup schedule?
I can only say for sure it always happens early in the morning sometime after the schedule, always around 4-6 AM, nothing else is scheduled for that time apart from the backup at 3AM

### Expected Behavior

No I/O errors, as this causes downtime while I'm asleep :)

### Support Bundle for Troubleshooting

[supportbundle_e4c83d51-be83-4427-8a44-3a7f85382ae6_2025-03-26T09-54-34Z.zip](https://github.com/user-attachments/files/19464811/supportbundle_e4c83d51-be83-4427-8a44-3a7f85382ae6_2025-03-26T09-54-34Z.zip)
[supportbundle_0bc7f7c6-15d5-4bee-ad36-b48936e9bc06_2025-03-26T09-54-50Z.zip](https://github.com/user-attachments/files/19464810/supportbundle_0bc7f7c6-15d5-4bee-ad36-b48936e9bc06_2025-03-26T09-54-50Z.zip)

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV) _(At least today)_: 
   - Live:
       - pvc-07c01573-b5a1-45a0-bfb7-88acb3005f38
   - Dev:
       - pvc-c2345281-459b-452f-8c66-2562f83abe57
       - pvc-4abc59f8-c290-42e3-8f21-db65671300ec

- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via Flux2
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos v1.9.5
  - Number of control plane nodes in the cluster: 1
  - Number of worker nodes in the cluster: 3
- Node config
  - OS type and version: TalosOS (not sure what this is actually)
  - Kernel version: https://github.com/siderolabs/pkgs/blob/v1.9.0/kernel/build/config-amd64
  - CPU per node: 4 (virtual)
  - Memory per node: 8G
  - Disk type (e.g. SSD/NVMe/HDD): NVMe; BackupStore HDDs
  - Network bandwidth between the nodes (Gbps): VM to VM (not sure); VM to BackupStore 10 Gbits
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox - selfhosted
- Number of Longhorn volumes in the cluster: 7

### Additional context

Ill will try to add more logs tomorrow, as this happens now basically every day, and i expect it to happen tomorrow as well.

Im not sure exactly when this started but i definetely didn't have that issue before 1.8.1 or before using flux, but i doubt that flux is causing this.
For context here is my values file:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: longhorn-system
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn/"
      defaultReplicaCount: 3

    longhornUI:
      replicas: 2

    persistence:
      defaultClass: true
      # -- Reclaim policy that provides instructions for handling of a volume after its claim is released. (Options: "Retain", "Delete")
      reclaimPolicy: Retain

    ingress:
      enabled: true
      annotations:
        blackbox.io/enabled: "true"
        blackbox.io/scheme: "https"
        blackbox.io/path: "/#/dashboard"
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: labca
        traefik.ingress.kubernetes.io/router.middlewares: internal@file

    metrics:
      serviceMonitor:
        enabled: true
```
dev patch:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    ingress:
      host: longhorn.dev.k8.hla1.jhofer.lan

    defaultBackupStore:
    backupTarget: "cifs://st-hdd1.st.hla1.jhofer.lan/HLA1_talos_longhorn_backups"
    backupTargetCredentialSecret: cifs-secret
    pollInterval: 300
    # This is not possible via Helm :(
    # recurringJobs:
    #   - name: "dev-backup"
    #     task: "backup"
    #     cron: "0 3 * * *"
    #     retain: 7
    #     concurrency: 2
    #     labels:
    #       environment: "dev"
```

### Workaround and Mitigation

Scaling down to 0 pods and then scaling up again as described here: https://github.com/longhorn/longhorn/issues/2975
