### ISSUE TITLE
Issue with  CSI_DRIVER_REGISTRAR_IMAGE 

### ISSUE THREAD

**Issue by vispatster** [longhorn/longhorn#1064]
#819 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: longhorn-driver-deployer
  namespace: longhorn-sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - deploy-driver
        - --manager-image
        - $REGURL/longhorn/manager:$TAG
        - --manager-url
        - http://longhorn-backend:9500/v1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CSI_ATTACHER_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        - name: CSI_PROVISIONER_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        - name: CSI_DRIVER_REGISTRAR_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        image:  $URL/longhorn/manager:$TAG
        imagePullPolicy: Always
        name: longhorn-driver-deployer
      initContainers:
      - command:
        - sh
        - -c
        - while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1)
          != "200" ]; do echo waiting; sleep 2; done
        image: $URL/longhorn/manager:$TAG
        imagePullPolicy: IfNotPresent
        name: wait-longhorn-manager
      restartPolicy: Always
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
```

FROM longhornio/longhorn-manager:v0.7.0 AS manager 
FROM quay.io/k8scsi/csi-attacher:v2.0.0 AS csi-attach #CSI_ATTACHER_IMAGE
FROM quay.io/k8scsi/csi-provisioner:v1.4.0 AS csi-pro # CSI_PROVISIONER_IMAGE
FROM quay.io/k8scsi/csi-node-driver-registrar:v1.2.0 AS csi-node #CSI_DRIVER_REGISTRAR_IMAGE

I have been trying to use internal registry. The following deployment keeps taking public image URL. 

Would any other config be required to use private reg URLs? 

Longhorn 7 is deploying attacher and provisioner images without any issue. 

![image](https://user-images.githubusercontent.com/6172619/74787303-d4553e00-527c-11ea-90be-05a0a2b61b4c.png)
