### ISSUE TITLE
[BUG] Longhorn UI does not show up correct when hosted under a context path by nginx

### ISSUE THREAD

**Issue by seazzle** [longhorn/longhorn#10667]
### Describe the Bug

I am using Longhorn in a Microk8s Cluster with 3 Nodes. 
The documentation does not describe how to host longhorn UI under a context path.
However, within other issues I found the follwing ingress configuration - using rewrite-target:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "longhorn-basic-auth"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - secretName: https-secret
      hosts:
        - sub.example.com
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80

```

![Image](https://github.com/user-attachments/assets/101a5e75-a52c-41a5-9c72-884232ba7f7c)

If I access it directly with the IP and the NodePort it works correctly - without any context path

![Image](https://github.com/user-attachments/assets/f1747ce5-8d5f-483b-82cd-ec8f9f04fd81)

### To Reproduce

Try to host longhorn forontend with nginx rewrite rule.

### Expected Behavior

Providing Longhorn UI with a context-path should work.

### Support Bundle for Troubleshooting

[supportbundle_8a409989-10f2-4dd1-99cc-da150d0f99aa_2025-03-31T18-52-05Z.zip](https://github.com/user-attachments/files/19540044/supportbundle_8a409989-10f2-4dd1-99cc-da150d0f99aa_2025-03-31T18-52-05Z.zip)

### Environment

- Longhorn version: 1.8.1
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Microk8s v1.32.3 revision 7964
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 0
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Digital Ocean
- Number of Longhorn volumes in the cluster: 5

### Workaround and Mitigation

Current workaround is access via NodePort. But this does not include Basic Auth security.

**Comment by derekbit** [comment]
cc @houhoucoop

**Comment by houhoucoop** [comment]
Hi @seazzle 
when you access `xxx/longhorn#/dashboard`, the `/longhorn` prefix remains in the API request, resulting in a URL like `xxx/longhorn/v1/nodes`, which causes a 404 error.
To resolve this, we need to strip the `/longhorn` prefix before forwarding it to the backend, e.g.
```
annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
...
spec:
    rules:
        - http:
           paths:
           - path: /longhorn(/|$)(.*)
             pathType: Prefix
             ...
```
