### ISSUE TITLE
[BUG] k8s complains metadata.finalizers: "longhorn.io": prefer a domain-qualified finalizer name including a path

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#10679]
### Describe the Bug

On Harvester, we observe:

```
W0403 13:27:57.404125       7 warnings.go:70] metadata.finalizers: "longhorn.io": prefer a domain-qualified finalizer name including a path (/) to avoid accidental conflicts with other finalizer writers
```

```
harv41:/home/rancher # kk get volume -A
NAMESPACE         NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE    AGE
longhorn-system   pvc-0755f277-3538-4a22-afbf-8a4f1512dad7   v1            detached   unknown                  4294967296            6m59s
longhorn-system   pvc-0aed37e5-927c-4655-9fc7-0dc35bc94bdf   v1            attached   healthy                  10737418240   harv2   2m59s
longhorn-system   pvc-820ea360-46da-4517-8964-43e52255a4ed   v1            attached   healthy                  1073741824    harv2   4m14s

harv41:/home/rancher # kk get volume -A -oyaml | grep final -2
  metadata:
    creationTimestamp: "2025-04-03T13:24:57Z"
    finalizers:
    - longhorn.io
    generation: 3
```

### To Reproduce

Harvester v1.5.0-master-head with LH v1.8.1

### Expected Behavior

The normal finalizers on Harvester are like:

```
- apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/auto-cleanup-system-generated-snapshot: "true"
      harvesterhci.io/replica-replenishment-wait-interval: "600"
    creationTimestamp: "2025-04-04T14:31:15Z"
    finalizers:
    - wrangler.cattle.io/harvester-upgrade-controller
```

### Support Bundle for Troubleshooting

the log has all info

### Environment

- Longhorn version: v1.8.1
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.32
  - Number of control plane nodes in the cluster:
  - Number of worker nodes in the cluster:
- Node config
  - OS type and version:
  - Kernel version:
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
- Number of Longhorn volumes in the cluster:

### Additional context

Observed while issue https://github.com/harvester/harvester/issues/8001 and https://github.com/harvester/harvester/issues/7840
