### ISSUE TITLE
[BUG] can't get out of replica-failed health=faulted state even when img file is mountable

### ISSUE THREAD

**Issue by drewp** [longhorn/longhorn#10706]
### Describe the Bug

Troubleshooting this with James Lu on slack

### To Reproduce

host=dash     (with the only replica) had its net cable unplugged for a  few hours

### Expected Behavior

when dash:/d4/longhorn/replicas/pvc-ec1d7d67-ab8f-416d-b1b2-f876add59c61-20194b66/volume-head-000.img is mountable, its replica should be healthy, or the UI should tell me what to do about it.

### Support Bundle for Troubleshooting

(pending)

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): pvc-ec1d7d67-ab8f-416d-b1b2-f876add59c61-20194b6
- Installation method Kubectl
- Kubernetes distro v1.29.1+k3s1
  - Number of control plane nodes in the cluster: 1
  - Number of worker nodes in the cluster: 4
- Node config
  - OS type and version: ubuntu 24.04
  - Kernel version:
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure Baremetal
- Number of Longhorn volumes in the cluster: ~20

**Comment by drewp** [comment]
We found this with `kubectl -n longhorn-system get nodes.longhorn.io dash -oyaml`:

```
  diskStatus:
    d4:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2024-04-22T07:25:14Z"
        message: Disk d4(/d4/longhorn) on node dash is ready
        reason: ""
        status: "True"
        type: Ready
      - lastProbeTime: ""
        lastTransitionTime: "2025-04-06T05:02:41Z"
        message: Disk d4 (/d4/longhorn) on the node dash has 247463936000 available,
          but requires reserved 0, minimal 25% to schedule more replicas
        reason: DiskPressure
        status: "False"
        type: Schedulable
      diskDriver: ""
      diskName: ""
      diskPath: /d4/longhorn
      diskType: filesystem
      diskUUID: 8a3b890b-5111-4821-ba57-cbcc99669852
      filesystemType: ext2/ext3
      instanceManagerName: instance-manager-9add3abd6670e97cb4ad7af0074d139c
      scheduledBackingImage: {}
      scheduledReplica:
        pvc-ec1d7d67-ab8f-416d-b1b2-f876add59c61-r-76a68e05: 53687091200
        ...
      storageAvailable: 247463936000
      storageMaximum: 1006977314816
      storageScheduled: 89120571392
```

dash:/d4 was 80% full, but needed to be under 75%. I cannot understand why the fraction of  used disk matters here. The avilable space was more than all  my replicas put together.

What would solve this bug report, e.g., is a field on the volume page that says "this volume is unable to be attached because it uses disk dash:/d4 which has under 25% free space". I was nowhere close to discovering that fact without James's help.

What would also avoid my outage altogether would be to drop the mysterious 25% free space requirement.
