### ISSUE TITLE
[BUG] Unable to attach simple PVC with single replica storage class

### ISSUE THREAD

**Issue by Time0o** [longhorn/longhorn#10700]
### Describe the Bug

My apologies if I have made a trivial mistake here, I am not well versed in Kubernetes.

I am unable to attach the simplest of PVCs to a pod when using a longhorn storage class. For context, I am using a cluster created by `kind`.

### To Reproduce

Install longhorn:

```
kubectl create -k "https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.2.0"
kubectl create -k "https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.2.0"
kubectl apply -f "https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml"
```

Create a storage class and PVC:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-registry-seed-volume-storage-class
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-seed-volume
  namespace: docker-registry
spec:
  storageClassName: docker-registry-seed-volume-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

After that I can see:

```
$ ~/bin/kubectl get volumes -n longhorn-system
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE           NODE   AGE
pvc-5ac6fe93-afd9-469b-b341-15397a39859d   v1            detached   unknown                  107374182400          15s
```

And there are no warnings or errors in `kubectl logs -n longhorn-system -l app=longhorn-manager`

I then start a test pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-volume
  namespace: docker-registry
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /test-volume
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: docker-registry-seed-volume
  restartPolicy: Never
```

Which after a while fails with:

```
AttachVolume.Attach failed for volume "pvc-5ac6fe93-afd9-469b-b341-15397a39859d" : rpc error: code = DeadlineExceeded desc = volume pvc-5ac6fe93-afd9-469b-b341-15397a39859d failed to attach to node infra-control-plane with attachmentID csi-d1252b6a1ff5dfc7a29418fec8fce8f71697d6d6de4aeec01cdb8517dcb13f07
```

When I check the replica logs with `kubectl -n longhorn-system describe replica.longhorn.io pvc-5ac6fe93-afd9-469b-b341-15397a39859d` I see a ton of restarts:

```
Events:
  Type    Reason  Age                     From                         Message
  ----    ------  ----                    ----                         -------
  Normal  Stop    2m37s (x19 over 4m38s)  longhorn-replica-controller  Stops pvc-5ac6fe93-afd9-469b-b341-15397a39859d-r-2361bde7
  Normal  Start   6s (x11 over 5m7s)      longhorn-replica-controller  Starts pvc-5ac6fe93-afd9-469b-b341-15397a39859d-r-2361bde7
```

The log of manager pod show some errors but I don't know enough to properly interpret these, I have added them to a gist [here](https://gist.github.com/Time0o/2d51b26d3743a4d60dddb031890145f5)

### Expected Behavior

PVC correctly attaches to pod.

### Support Bundle for Troubleshooting

[supportbundle_ef307b79-b7e8-4179-a096-bf7433b22217_2025-04-09T13-46-27Z.zip](https://github.com/user-attachments/files/19668058/supportbundle_ef307b79-b7e8-4179-a096-bf7433b22217_2025-04-09T13-46-27Z.zip)

### Environment

- Longhorn version: v1.8.1
- Impacted volume (PV): `pvc-5ac6fe93-afd9-469b-b341-15397a39859d`
- Installation method: `kubectl`
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `kind` 0.27.0
  - Number of control plane nodes in the cluster: 1
  - Number of worker nodes in the cluster: 0
- Node config
  - OS type and version: Ubuntu 24.04.2 LTS
  - Kernel version: 6.8.0-52-generic
  - CPU per node: 96
  - Memory per node: 395723536Ki
  - Disk type (e.g. SSD/NVMe/HDD): NVMe
  - Network bandwidth between the nodes (Gbps): ?
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 1
