### ISSUE TITLE
[BUG] attaching encrypted V2 volume fails in a loop on Talos 1.9.5 and LH master-head

### ISSUE THREAD

**Issue by jfroy** [longhorn/longhorn#10763]
### Describe the Bug

I've been trying to setup Longhorn on my homelab cluster, with minio and cnpg as the first use cases. Installing longhorn, defining my storageclass, and starting minio works.

But for cnpg, the initial restore-from-backup pod works, but the primary pod fails. The first time it executes, it errors with an I/O error for the lock file (a pid file), and after that longhorn no longer seems to be able to attach the the volume. Deleting the cnpg pod and deleting the volumeattachment doesn't help.

There are other issues similar to this already filed, but looking at the logs, there are a lot of errors in the io-engine, suggesting this is a longhorn issue, and possibly a longhorn-on-talos issue.

Because this is a homelab and no critical, I deployed longhorn from master-head to have the latest changes, in particular recent patches for Talos. I have also tested with 1.8.x (with Talos patches) and 1.9-dev

### To Reproduce

1. Deploy Longhorn on a Talos 1.9.5 cluster.
2. Create a 2 replica encrypted V2 storageclass.
3. Deploy cnpg using that storage class.

### Expected Behavior

Volume should attach to cnpg pod.

### Support Bundle for Troubleshooting

[supportbundle_0e806914-6824-45d7-917d-b5fcb0b46f74_2025-04-21T17-09-55Z.zip](https://github.com/user-attachments/files/19837440/supportbundle_0e806914-6824-45d7-917d-b5fcb0b46f74_2025-04-21T17-09-55Z.zip)

### Environment

- Longhorn version: master-head (as of 2025-05-21)
  - longhornio/csi-attacher@sha256:33c7ec2ede81280a76c7e65947523777691eff7a021a7c52b45969692a230e56
  - longhornio/csi-provisioner@sha256:d8ce17ca633b8af494e6607743b63631df3d7dafda808fe42555e646093c70d5
  - longhornio/csi-resizer@sha256:0594a761e1cf0b07c1cbe12a11046f448c0bfe27a846ead597e73f93e856a8cb
  - longhornio/csi-snapshotter@sha256:dff0c369ad0dbea80f9c657ae817122c036d2775e3c98c2c62ab6138d2a9d6ec
  - longhornio/longhorn-instance-manager@sha256:4e17c1520e5a48b9ce5dbf72f1f336cbb080552ab441ee00b8f1fc13dd6112e4
  - longhornio/csi-node-driver-registrar@sha256:69cd0517dcd5ca916ad9c8297d3d5370df93c84619cec3d977e8770edf70874f
  - longhornio/longhorn-manager@sha256:c24a28116d4e8b49af1a3048cc62ce7e4cd8a0a26d2bd4ee0e73dfe857c16c48
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): flux helmrelease
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos 1.9.5
  - Number of control plane nodes in the cluster: 3 with tolerations to allow pods
  - Number of worker nodes in the cluster: 0 (see above)
- Node config
  - OS type and version: Talos 1.9.5
  - Kernel version: 6.12
  - CPU per node: variable (8 to 24)
  - Memory per node: variable (16 GB to 128 GB)
  - Disk type (e.g. SSD/NVMe/HDD): nvme
  - Network bandwidth between the nodes (Gbps): 10 Gbps SFP DACs
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
- Number of Longhorn volumes in the cluster: 2

### Additional context

Sample io-engine log entry:

`[longhorn-instance-manager] time="2025-04-21T16:59:13Z" level=error msg="Found error during engine validation and update" func="spdk.(*Engine).ValidateAndUpdate.func2" file="engine.go:839" endpoint=/dev/longhorn/pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050 engineName=pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050-e-0 error="failed to execute: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net lsblk /dev/longhorn/pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050 -n -o NAME,MAJ:MIN --nodeps], output , stderr lsblk: /dev/longhorn/pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050: failed to get sysfs name: No such file or directory\n: exit status 32" frontend=spdk-tcp-blockdev initiatorAddress=10.11.3.208 initiatorCreationRequired=true initiatorIP=10.11.3.208 port=21446 replicaStatusMap="map[pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050-r-4f125c37:0xc000c462a0 pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050-r-8ae9153a:0xc000fa2d50]" targetAddress=10.11.3.208 targetCreationRequired=true targetIP=10.11.3.208 targetPort=21446 volumeName=pvc-67ddebc7-c3f7-4eb4-b569-03de501b0050`

StorageClass:

```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nvme-r2-enc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataEngine: v2
  diskSelector: nvme
  encrypted: "true"
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-nvme-r2-enc"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-nvme-r2-enc"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-nvme-r2-enc"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-expand-secret-name: "longhorn-nvme-r2-enc"
  csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"
```

### Workaround and Mitigation

Haven't found one.
