### ISSUE TITLE
[BUG] longhorn-manager pods hanging on "Webhook leader elected" right after startup

### ISSUE THREAD

**Issue by rizhu** [longhorn/longhorn#10819]
### Describe the Bug

I've deployed longhorn into my k8s cluster and 13 of my 16 `longhorn-manager`s are unhealthy.
```bash
$ kubectl get ds -n longhorn-system longhorn-manager
NAME               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
longhorn-manager   16        16        3       16           3           <none>          3d21h
```
all 13 of the failed pods just have basically these same 3 lines in the logs of the `longhorn-manager` container
```
time="2025-04-25T23:41:32Z" level=debug msg="Failed to get PID (1427415) status" func=proc.GetProcessPIDs file="proc.go:86" error="open /host/proc/1427415/status: no such file or directory"
I0425 23:41:32.803765       1 leaderelection.go:257] attempting to acquire leader lease longhorn-system/longhorn-manager-webhook-lock...
time="2025-04-25T23:41:32Z" level=info msg="Webhook leader elected: <node-name>" func=app.startWebhooksByLeaderElection.func4 file="daemon.go:228"
```
I'm using the official 1.8.1 Helm chart with the following `values.yaml`
```yaml
persistence:
  defaultClassReplicaCount: 2
preUpgradeChecker:
  jobEnabled: false # using Argo
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2
defaultSettings:
  storageOverProvisioningPercentage: 90
  defaultReplicaCount: 2
  systemManagedComponentsNodeSelector: "longhorn-system:enabled"
  guaranteedInstanceManagerCPU: 0
  rwxVolumeFastFailover: true
ingress:
  enabled: true
  ingressClassName: nginx
  host: <host-name>
  path: "/"
  pathType: Prefix
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      <some-prometheus-labels>
```

as probably expected, nothing is listening on port 9501
```bash
# ss -tulpn | grep 9501
#
```
vs on a healthy pod
```bash
# ss -tulpn | grep 9501
tcp   LISTEN 0      4096               *:9501            *:*    users:(("longhorn-manage",pid=1,fd=6))
```
`kubectl top node` and `kubectl describe node` all seem fine for the nodes that these managers are trying to get scheduled on (but open to double-checking if we suspect issue with nodes).

### Expected Behavior

All 16 manager pods are healthy with readiness probe running on port 9501

### Support Bundle for Troubleshooting

Generating support bundle fails with `Request failed with status code 502`

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): N/A, no volumes deployed yet
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm, ArgoCD
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 107
- Node config
  - OS type and version: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)
  - Kernel version: 5.15.0-101-generic
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 0
