### ISSUE TITLE
[IMPROVEMENT] add extraObject in charts

### ISSUE THREAD

**Issue by DrummyFloyd** [longhorn/longhorn#10835]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

Sometimes you may want to add, other CR or other manifests related to `longhorn` deployment 
like `configMap` for grafana dashboards,or `ExternalSecret` or `GrafanaDashboard` to contains. because its related to personal deployment

### Describe the solution you'd like

```yaml
# values.yaml
extraObjects: []
```

### Describe alternatives you've considered

.

### Additional context

common way to add others manifests ith helm charts

**Comment by derekbit** [comment]
@DrummyFloyd Thank you. Could you elaborate more on the purpose and the usage of `extraObjects` in `Is your improvement request related to a feature? Please describe`? Thank you.

**Comment by derekbit** [comment]
@DrummyFloyd Thanks for the contribution. If possible, could you help provide steps to help QA test the improvement? Thank you.

**Comment by DrummyFloyd** [comment]
> [@DrummyFloyd](https://github.com/DrummyFloyd) Thanks for the contribution. If possible, could you help provide steps to help QA test the improvement? Thank you.

one quick test would be something like that 
```yaml
extraObjects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: dummy-cm
    namespace: longhorn-system
  data:
    foo: bar
```


or try to introduce some automatic tests with https://github.com/helm-unittest/helm-unittest

**Comment by innobead** [comment]
longhorn-system should be exclusive for Longhorn components. What cases you need to deploy other resources in the namespace?

**Comment by DrummyFloyd** [comment]
> [@DrummyFloyd](https://github.com/DrummyFloyd) longhorn-system should be exclusive for Longhorn components. What cases you need to deploy other resources in the namespace?
> 
> cc @longhorn/maintainer

when u made some gitops stuff, you want to incoprorate some extra toolings, on bootstrap , to be full declarative.


like secrets managed from `ExternalSecrets` which will be contain into `longhorn` release 
or some homemade dashboard or communauty dashboard from grafana... using extra `configMap` or ` GrafanaDashboard` ..etc

this a classic pattern for helm chart .

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn/commit/6afc49d676220c8cab163c460a0debec7c19ea43), v1.9.x(https://github.com/longhorn/longhorn/commit/fd1fa642e510e6c1f2d52be1344db6c00a95ba97)

Install Longhorn by helm with `extraObjects: []` or below setting, longhorn install/uninstall worked properly and correspond object created.

```yaml
extraObjects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: dummy-cm
    namespace: longhorn-system
  data:
    foo: bar
```
