### ISSUE TITLE
[FEATURE] IPv6 for V2 Data Engine

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#10928]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

This is part of V1 data engine feature parity for [IPv6 for V1 Data Engine](https://github.com/longhorn/longhorn/issues/2259). 

- [ ] The V2 data engine data path supports either the IPv6 protocol exclusively or a dual-stack configuration.  

### Additional context

cc @longhorn/maintainer

**Comment by jamesharr** [comment]
We operate dual stack clusters and eying IPv6 only clusters, so this will be a blocker for us adopting the V2 data engine.

(PS, not complaining -- the longhorn team does some good work, I know this will take time. Registering our use case)

**Comment by COLDTURNIP** [comment]
This ticket is focus on IPv6 support. The dual-stack support for both v1 & v2 engines is handled at #11531

**Comment by derekbit** [comment]
@COLDTURNIP All PRs are merged. If everything is ready and validated, feel free to move it `Ready For Testing`. Thanks.

**Comment by COLDTURNIP** [comment]
## Validation Steps

1. Given a IPv6 single-stack Kubernetes cluster
2. And Longhorn is setup with the latest nightly build
3. And the v2 data engine is enabled with available block disks
4. When setup the following workload with a 3-replica v2 volume
  ```yaml
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: longhorn-v2
  provisioner: driver.longhorn.io
  parameters:
    dataEngine: v2
    numberOfReplicas: "3"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  ---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: test-v2-pvc
  spec:
    accessModes: [ ReadWriteOnce ]
    storageClassName: longhorn-v2
    resources:
      requests:
        storage: 1Gi
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-v2-deployment
    labels:
      app: test-v2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: test-v2
    template:
      metadata:
        labels:
          app: test-v2
      spec:
        containers:
        - name: busybox
          image: busybox
          command:
          - sh
          - -c
          - |
            COUNT=0
            while true; do
              echo "$(date -Iseconds)" >> /data/test.txt
              COUNT=$((COUNT + 1))
              if [ $((COUNT % 60)) -eq 0 ]; then
                tail -n +2 /data/test.txt > /data/test.tmp && mv /data/test.tmp /data/test.txt
                COUNT=0
              fi
              echo '>>> Tail 3 lines of /data/test.txt'
              tail -3 /data/test.txt
              sleep 1
            done
          volumeMounts:
          - name: data
            mountPath: /data
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-v2-pvc
  ```
5. Then the workload will eventually launched without any problem
6. And describe the engine (`kubectl -n longhorn-system describe lhe ...`), `CurrentReplicaAddressMap` indicates that all the components are communicating via IPv6
  ```
  Status:
    Current Replica Address Map:
      pvc-3593b67e-369d-4ccd-b23b-e9e531319373-r-3831f5bd:  [fd42:0:0:2::4]:20001
      pvc-3593b67e-369d-4ccd-b23b-e9e531319373-r-5a98b395:  [fd42:0:0:1::d]:20001
      pvc-3593b67e-369d-4ccd-b23b-e9e531319373-r-bb89e964:  [fd42:0:0:3::6]:20001
  ```
7. And check the workload pod log, it keeps writing & reading data on the attached volume
```
$ kubectl logs -f test-v2-deployment-67b6c648b6-52llx
2026-04-28T10:45:04+00:00
2026-04-28T10:45:05+00:00
>>> Tail 3 lines of /data/test.txt
2026-04-28T10:45:04+00:00
2026-04-28T10:45:05+00:00
2026-04-28T10:45:06+00:00
>>> Tail 3 lines of /data/test.txt
2026-04-28T10:45:05+00:00
2026-04-28T10:45:06+00:00
2026-04-28T10:45:07+00:00
```
