### ISSUE TITLE
[BUG] Helm persistence.backupTargetName not referenced in storageclass template

### ISSUE THREAD

**Issue by jkossis** [longhorn/longhorn#10961]
### Describe the Bug

The helm chart is configured to accept a `persistence.backupTargetName` value, however it is not actually applied in the [storage class template](https://github.com/longhorn/longhorn/blob/master/chart/templates/storageclass.yaml). The documentation [here](https://longhorn.io/docs/1.8.1/nodes-and-volumes/volumes/create-volumes/) notates this added functionality starting with 1.8.0.

### To Reproduce

Nothing needs to be run, it's clear by statically analyzing the template.

### Expected Behavior

The storage class template should apply the value correctly, as notated below:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-storageclass
  ...
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
      ...
    ...
    parameters:
      ...
      backupTargetName: "{{ .Values.persistence.backupTargetName }}"
      ...
```

### Support Bundle for Troubleshooting

N/A

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 1
- Node config
  - OS type and version: Talos v1.9.5
  - Kernel version:
  - CPU per node: 4
  - Memory per node: 8GB
  - Disk type (e.g. SSD/NVMe/HDD): NVMe
  - Network bandwidth between the nodes (Gbps): 1 Gbps
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
- Number of Longhorn volumes in the cluster: 15
