### ISSUE TITLE
[FEATURE] Easier Way to Check Overall Longhorn System Health

### ISSUE THREAD

**Issue by flip111** [longhorn/longhorn#10985]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

It would be a big help if there was one simple way to check if the entire Longhorn system is healthy and ready. Right now, figuring this out takes quite a few steps.

I use a script to install and manage Longhorn. After the Helm chart installs, or after i change some settings, my script needs to make sure Longhorn is fully working before it moves on. Longhorn has many parts: there's the manager pods, the CSI plugin pods, the instance managers on each node, and then the status of the Longhorn nodes themselves (like if they are schedulable and have healthy disks).

To check if Longhorn is okay now, my script does this:
1.  It gets the `nodes.longhorn.io` custom resource for my Kubernetes node. It checks conditions like "Schedulable" and "KernelModulesLoaded". It also counts how many disks are ready and schedulable.
2.  It uses `kubectl` to list the `longhorn-manager` pods and see how many are running.
3.  It lists the `longhorn-csi-plugin` pods and checks if all their containers are ready.
4.  It has to look at all these different things to decide if Longhorn is truly healthy.

This makes my automation script more complicated. And if Longhorn adds new important components in the future, my script might miss checking them unless i update it carefully.

If Longhorn had a single, clear indicator of overall system health, it would make things much easier. My script could just poll that one status.

I think a lot of other people who use Longhorn would find this useful too.
*   **Simpler for Operators:** Anyone running Longhorn could quickly see if the whole storage system is in good shape or if there's a problem somewhere.
*   **Better for Automation:** Scripts for deploying Longhorn, or for deploying applications that depend on Longhorn, could more reliably wait for it to be fully operational.
*   **Easier Monitoring:** It would be simpler to create monitoring dashboards and alerts for Longhorn's overall health.

### Describe the solution you'd like

Here's how i imagine it could work. Maybe Longhorn could have a special Custom Resource, say a `LonghornClusterStatus` CR in the `longhorn-system` namespace. This CR could have a `status` field that shows if the whole system is "Healthy", "Degraded", "Initializing", etc. It could also list the status of important parts.

For example, `kubectl get longhornclusterstatus -n longhorn-system -o yaml` might show something like:

```yaml
apiVersion: longhorn.io/v1beta2 # or a new API group
kind: LonghornClusterStatus
metadata:
  name: cluster-health # or similar
  namespace: longhorn-system
status:
  overallState: "Healthy" # Could be Healthy, Degraded, Reconciling, Error
  lastChecked: "2025-05-27T10:30:00Z"
  conditions:
    - type: AllNodesReady
      status: "True"
      message: "All Longhorn nodes are schedulable and healthy."
    - type: DefaultDisksHealthy
      status: "True"
      message: "All default disks on nodes are ready and schedulable."
    - type: CSIDriverReady
      status: "True"
      message: "Longhorn CSI driver pods are fully operational."
    - type: InstanceManagersReady
      status: "True"
      message: "All Longhorn instance managers are responsive."
    - type: LonghornManagerReady
      status: "True"
      message: "Longhorn manager pods are running and healthy."
  # Optional: summary counts
  nodeCount: 1
  healthyNodeCount: 1
  diskCount: 1
  healthyDiskCount: 1
```

Or, this kind of aggregated health information could be added as conditions to one of the existing global `Setting` CRs that Longhorn already has, like the `backup-target` setting, or a new dedicated global setting for cluster health.

Having a clear, top-level status like this would make it much easier for both people and scripts to understand if Longhorn is good to go or if something needs a closer look.

Thanks for considering it.
