### ISSUE TITLE
[IMPROVEMENT] Schedule at least one replica locally when locality is `best-effort`

### ISSUE THREAD

**Issue by bachmanity1** [longhorn/longhorn#11007]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

When data locality is set to `best-effort`, it does not guarantee that at least one replica will be scheduled on the same node as the pod workload, even if it’s possible. If no replicas are running locally, the volume controller may later migrate one of the replicas to the local node so that eventually at least one replica runs alongside the pod.

However, there doesn’t appear to be anything preventing the replica scheduler from initially placing a replica on the local node. Doing so could reduce unnecessary data movement by avoiding later migrations.

### Describe the solution you'd like

The replica scheduler should attempt to schedule at least one replica on the same node as the pod workload when data locality is set to `best-effort`.

**Comment by COLDTURNIP** [comment]
https://github.com/longhorn/longhorn-manager/blob/master/scheduler/replica_scheduler.go#L532
Maybe we could prioritize for localization rather than only consider the disk usage. WDYT? @shuo-wu @PhanLe1010 @c3y1huang @mantissahz @derekbit @innobead

**Comment by bachmanity1** [comment]
### Replica Scheduling Optimization for Best-Effort Locality

Here’s a quick overview of how replica scheduling works when locality is set to `best-effort`:

1. Volume is created
2. Replicas are created
3. Replicas are scheduled and started
4. Volume is attached
5. One of the replicas might get migrated to the local node (if none are running there)

We want to remove step 5 and make sure that at least one replica is initially started on the local node. But right now, that’s not possible. When replicas are first scheduled in step 3, we don’t yet know which node the volume will be attached to, so we don’t know which one is the local node.

To avoid having to migrate replicas later, we propose to delay scheduling until the volume is attached. That way, we’ll know the local node and can schedule a replica there from the start. I think this behavior makes more sense for `best-effort` locality and is also similar to how `strict-local` works, where replica isn't scheduled or started until the volume is attached.

The logic has been implemented in https://github.com/longhorn/longhorn-manager/pull/3806 and is ready for review.

cc @COLDTURNIP

**Comment by derekbit** [comment]
Thanks @bachmanity1. We will review your PR soon.
I've added you to the developer group. Could you help update the pre-check list https://github.com/longhorn/longhorn/issues/11007#issuecomment-2959125511? Feel free to let me know if you need help. Thank you.

cc @longhorn/dev @innobead

**Comment by derekbit** [comment]
@bachmanity1 Is everything ready? If YES, you can update the status of `Longhorn Sprint` to `Ready For Testing`. Thank you.

**Comment by bachmanity1** [comment]
Hi @derekbit, yes, it's ready for testing, but I don't think I have the rights to update the ticket status. I can't move tickets in the Kanban board.

**Comment by derekbit** [comment]
> Hi [@derekbit](https://github.com/derekbit), yes, it's ready for testing, but I don't think I have the rights to update the ticket status. I can't move tickets in the Kanban board.

Thank you @bachmanity1. Moved to Ready For Testing.

**Comment by chriscchien** [comment]
Hi @bachmanity1 , I can see the replica migrate behavior on master-head when `dataLocality` is `best-effort` on a dynamic provisioned volume, can you take a look on this?

https://github.com/user-attachments/assets/acc78750-4749-4c11-83a7-3a9dcf018d82


1. Create a storage class with one replica and `dataLocality: best-effort`
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: best-effort
```
2. Deploy PVC with above storage class and workload
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: ubuntu:20.04
          stdin: true
          stdinOnce: false
          tty: true
          volumeMounts:
            - name: vol1
              mountPath: /mnt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: vol1
```
3. Form the record video, the `Data Locality` on UI is `best-effort`,  but the replica migrated from node `ip-172-31-43-178` to `ip-172-31-32-249`, this seems actually the step 5 mentioned in the [comment](https://github.com/longhorn/longhorn/issues/11007#issuecomment-2958239852)

**Comment by bachmanity1** [comment]
Hi @chriscchien. Thanks for testing this feature!

>  can see the replica migrate behavior on master-head when dataLocality is best-effort on a dynamic provisioned volume, can you take a look on this?

It's strange because I'm using the same setup as you've described but I don't see that replica migration. Sorry for asking, but are you sure you're using the latest version of `masted-head` image? It seems that default [pullPolicy](https://github.com/longhorn/longhorn/blob/e5333e5ea176fc6de4cd38f7deb52d400840cc3b/chart/values.yaml#L141) in the longhorn helm chart is set to `IfNotPresent`, if you haven't changed this default value then can you change it to `Always`? If you're sure that you're using the latest image can you try creating only pvc (without pod) and check replica status? When pvc is not used by a pod then replicas should be unscheduled (`.spec.nodeID` must be empty).

**Comment by chriscchien** [comment]
Hi @bachmanity1, I created a new cluster and deployed longhorn with `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`, When I create a PVC with workload, I still see the replica migration behavior (not every time). However, when I create a PVC without a workload, I no longer observe replica migration, which matches the improvement described in the [comment](https://github.com/longhorn/longhorn/issues/11007#issuecomment-2958239852).

**Comment by bachmanity1** [comment]
> However, when I create a PVC without a workload, I no longer observe replica migration, which matches the improvement described in the https://github.com/longhorn/longhorn/issues/11007#issuecomment-2958239852.

@chriscchien what about `.spec.nodeID` field of the replica? Is it empty or not?

**Comment by bachmanity1** [comment]
> I created a new cluster and deployed longhorn with kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

Just to avoid confusion with image can you save file locally and change [this line](https://github.com/longhorn/longhorn/blob/e5333e5ea176fc6de4cd38f7deb52d400840cc3b/deploy/longhorn.yaml#L4145) to `Always` and redeploy longhorn.

**Comment by chriscchien** [comment]
> > However, when I create a PVC without a workload, I no longer observe replica migration, which matches the improvement described in the [#11007 (comment)](https://github.com/longhorn/longhorn/issues/11007#issuecomment-2958239852).
> 
> [@chriscchien](https://github.com/chriscchien) what about `.spec.nodeID` field of the replica? Is it empty or not?

It is the node ID

**Comment by chriscchien** [comment]
> > I created a new cluster and deployed longhorn with kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
> 
> Just to avoid confusion with image can you save file locally and change [this line](https://github.com/longhorn/longhorn/blob/e5333e5ea176fc6de4cd38f7deb52d400840cc3b/deploy/longhorn.yaml#L4145) to `Always` and redeploy longhorn.

OK I will do it but actually I am using a new created cluster, so the image is the latest one

**Comment by bachmanity1** [comment]
> > > However, when I create a PVC without a workload, I no longer observe replica migration, which matches the improvement described in the [#11007 (comment)](https://github.com/longhorn/longhorn/issues/11007#issuecomment-2958239852).
> > 
> > 
> > [@chriscchien](https://github.com/chriscchien) what about `.spec.nodeID` field of the replica? Is it empty or not?
> 
> It is the node ID

So, it's not empty? It's strange because the PR I submitted clearly doesn't allow replica to be scheduled until volume is attached.

**Comment by chriscchien** [comment]
> > It is the node ID
> 
> So, it's not empty? It's strange because the PR I submitted clearly doesn't allow replica to be scheduled until volume is attached.

Hi @bachmanity1, yes, in the scenario : create `best-effort` PVC without worklad, the stopped replica have nodeID in spec.
```bash
> kl get replica
NAME                                                  DATA ENGINE   STATE     NODE             DISK                                   INSTANCEMANAGER   IMAGE   AGE
pvc-12c962c0-48f2-46e0-b796-ff161be7e779-r-fae092bc   v1            stopped   ip-172-31-42-2   eed34fe9-ff5c-441b-9989-9f0ece17fac8                             51s
> kl get replica pvc-12c962c0-48f2-46e0-b796-ff161be7e779-r-fae092bc   -o jsonpath='{.spec.nodeID}{"\n"}'
ip-172-31-42-2
```
And the behavior still happen when create `best-effort` PVC with workload, may I know are you using your custom image?

https://github.com/user-attachments/assets/e23810ad-a107-4968-b09e-6863dd3f97e2

Ps. reinstalled with `crictl images -q | xargs crictl rmi` on each node and all image pull policy to `Always`

**Comment by bachmanity1** [comment]
> may I know are you using your custom image?

no, I'm using `master-head` image.
```
  containerStatuses:
  - containerID: containerd://99204baf3662ac3bdbd359e3417a7d022327af568b25e4c3039a8fd072a2e0eb
    image: docker.io/longhornio/longhorn-manager:master-head
    imageID: docker.io/longhornio/longhorn-manager@sha256:c6ec9dc4a155e7060506265ec849ea188ce82ae882698404cdf2f6809593cfbd
    lastState: {}
    name: longhorn-manager
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-07-10T09:33:15Z"
```

@chriscchien can you please check the hash of the image used by your longhorn-manager containers? Does it match `c6ec9dc4a155e7060506265ec849ea188ce82ae882698404cdf2f6809593cfbd`?

>  the stopped replica have nodeID in spec.

This is really strange. I'm not able to reproduce this in my local cluster. In my tests `.spec.nodeID` always stays empty when there is no workload.

```bash
k get lhr -w
NAME                                                  DATA ENGINE   STATE   NODE   DISK   INSTANCEMANAGER   IMAGE   AGE
pvc-8d5131bd-1e81-4fe1-8927-d3f78dac56f8-r-532988dd   v1                                                            0s
pvc-8d5131bd-1e81-4fe1-8927-d3f78dac56f8-r-532988dd   v1                                                            0s
pvc-8d5131bd-1e81-4fe1-8927-d3f78dac56f8-r-532988dd   v1            stopped                                           0s
```

**Comment by chriscchien** [comment]
Hi @bachmanity1, I am using the same longhorn-manager

<img width="1420" height="219" alt="Image" src="https://github.com/user-attachments/assets/de03a5c5-0e19-499a-b90a-ecbbbedd5dee" />

<img width="1851" height="80" alt="Image" src="https://github.com/user-attachments/assets/2356e0d9-1639-4dbe-8872-7e7dcb53f8c3" />

The cluster is fresh cretaed and below is more information of my env
  - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.33.0+k3s1
  - OS type and version: Ubuntu 24.04
  - Kernel version: `6.8.0-1029-aws #31-Ubuntu SMP Wed Apr 23 18:42:41 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bachmanity1** [comment]
@chriscchien  it seems like there was something off with my longhorn installation. After deleting and reinstalling longhorn I'm now able to reproduce same results as described by you. 

When only a PVC is created (with no workload), the longhorn volume is first attached to a node and then gets detached. I'm not sure if this is the expected behavior or if it's the result of a recent change. I don't recall observing this behavior while working on this feature. @derekbit, could you please help clarify this?

```bash
> k get lhv -w
NAME                                       DATA ENGINE   STATE   ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            creating                            2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          0s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    unknown                  2147483648   dev-longhorn-004  3s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648   dev-longhorn-004   8s
pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648                          10s
```

**Comment by derekbit** [comment]
> [@chriscchien](https://github.com/chriscchien) it seems like there was something off with my longhorn installation. After deleting and reinstalling longhorn I'm now able to reproduce same results as described by you.
> 
> When only a PVC is created (with no workload), the longhorn volume is first attached to a node and then gets detached. I'm not sure if this is the expected behavior or if it's the result of a recent change. I don't recall observing this behavior while working on this feature. [@derekbit](https://github.com/derekbit), could you please help clarify this?
> 
> > k get lhv -w
> NAME                                       DATA ENGINE   STATE   ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            creating                            2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    unknown                  2147483648   dev-longhorn-004  3s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648                          10s

Hello @bachmanity1 

I didn't see the issue using the latest master-head images.

Applied the manifest
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 2Gi
```
Observed the same behavior in master-head and v1.9.0.

```
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            creating                             2147483648                      0s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detaching   unknown                  2147483648                      0s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      0s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
```

**Comment by bachmanity1** [comment]
> Observed the same behavior in master-head and v1.9.0.
> 
> ```
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            creating                             2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detaching   unknown                  2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> ```

This is what I observed before deleting and reinstalling Longhorn.

Also, I'm wondering if you can reproduce the results reported by @chriscchien (non-empty node ID for a replica when the locality is set to `best-effort` and the volume is not used by any workload.)

**Comment by derekbit** [comment]
> > Observed the same behavior in master-head and v1.9.0.
> > ```
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            creating                             2147483648                      0s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detaching   unknown                  2147483648                      0s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      0s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> > pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> > ```
> 
> This is what I observed before deleting and reinstalling Longhorn.
> 

I see. My environment is brand new, so the behavior should be without issues.

> Also, I'm wondering if you can reproduce the results reported by [@chriscchien](https://github.com/chriscchien) (non-empty node ID for a replica when the locality is set to `best-effort` and the volume is not used by any workload.)

It's a bit late for me. I will try to reproduce it tomorrow morning and get back to you.

**Comment by bachmanity1** [comment]
> When only a PVC is created (with no workload), the longhorn volume is first attached to a node and then gets detached. I'm not sure if this is the expected behavior or if it's the result of a recent change. I don't recall observing this behavior while working on this feature. [@derekbit](https://github.com/derekbit), could you please help clarify this?
>
> ```
> > k get lhv -w
> NAME                                       DATA ENGINE   STATE   ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1                                             2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            creating                            2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          0s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attaching   unknown                  2147483648          2s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    unknown                  2147483648   dev-longhorn-004  3s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            attached    healthy                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detaching   unknown                  2147483648   dev-longhorn-004   8s
> pvc-65819c8d-1fc8-47b4-b536-3e67f67e8bd2   v1            detached    unknown                  2147483648                          10s
> ```

@derekbit  I’ve confirmed that this behavior is caused by the https://github.com/longhorn/longhorn/issues/11204. The behavior shown above can be seen when value of `offline-replica-rebuilding` is set to `true`. However, when `offline-replica-rebuilding` is set to `false`, the volume remains in the detached state, as described below.

> Observed the same behavior in master-head and v1.9.0.
> 
> ```
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1                                                 2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            creating                             2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detaching   unknown                  2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      0s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> pvc-aaa26271-a7b4-4698-b62f-693c4499a42a   v1            detached    unknown                  2147483648                      2s
> ```

**Comment by derekbit** [comment]
Thanks @bachmanity1 for the investigation. We will disable `offline-replica-rebuilding` util we address the improvements and issues
- https://github.com/longhorn/longhorn/issues/11270
- https://github.com/longhorn/longhorn/issues/11273

cc @mantissahz

**Comment by derekbit** [comment]
@chriscchien The offline rebuilding is disabled. Please revalidate the ticket. Thank you.

**Comment by chriscchien** [comment]
Verified **pass** on longhron master(https://github.com/longhorn/longhorn-manager/commit/dd3a6379705cbc0af5f03710cfd2edb1f35f0aaa)

On a three nodes cluster, the following steps were repeated 10 times without observing any replica-migration behavior
1. Create a storage class with one replica and dataLocality: best-effort
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: best-effort
```
2. Deploy PVC with above storage class and workload
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: ubuntu:20.04
          stdin: true
          stdinOnce: false
          tty: true
          volumeMounts:
            - name: vol1
              mountPath: /mnt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: vol1
```
