### ISSUE TITLE
[DOC] Talos new volumes strategy

### ISSUE THREAD

**Issue by DrummyFloyd** [longhorn/longhorn#11015]
## What's the document you plan to update? Why? Please describe

i wan't to upgrade the documentation of how longhorn need to be configured with new talos  [UserVolumeConfig](https://www.talos.dev/v1.10/reference/configuration/block/uservolumeconfig/) 
in the documents , because from `1.10.x` and higher the actual way from [longhorn(docs](https://longhorn.io/docs/1.9.0/advanced-resources/os-distro-specific/talos-linux-support/) is deprecated

and `--preserve` arguments on `talosctl upgrade ` is no more needed since `1.8` ( is set by default on upgrade operation)

## Additional context

maybe add a new section for newer version of talos ? 

with following example 

`helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --set defaultSettings.defaultDataPath="/var/mnt/longhorn"`

```
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  grow: false
  maxSize: 1700GB
```

```
machine:
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn
        type: bind
        source: /var/mnt/longhorn
        options:
          - bind
          - rshared
          - rw
```

**Comment by derekbit** [comment]
@DrummyFloyd Would you like to submit a PR for the doc update?

**Comment by DrummyFloyd** [comment]
> [@DrummyFloyd](https://github.com/DrummyFloyd) Would you like to submit a PR for the doc update?

yes woud like to make it, but i wanted to ask , if it's something that you will accept ? =)

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
> i wan't to upgrade the documentation of how longhorn need to be configured with new talos [UserVolumeConfig](https://www.talos.dev/v1.10/reference/configuration/block/uservolumeconfig/)
in the documents , because from 1.10.x and higher the actual way from [longhorn(docs](https://longhorn.io/docs/1.9.0/advanced-resources/os-distro-specific/talos-linux-support/) is deprecated

Thanks for bringing this up! PRs to update the docs are definitely welcome. Before moving forward, I just want to clarify a couple of things.

Could you please confirm which part of the current Talos setup is deprecated starting from `v1.10+`? Are you talking about the use of `machine.kubelet.extraMounts`? If you have any official references or links about this deprecation, that would help.

Also, is `UserVolumeConfig` now required in Talos `v1.10+`, or is it more of an optional setup?

> and --preserve arguments on talosctl upgrade  is no more needed since 1.8 ( is set by default on upgrade operation)

Do you happen to have a link or release note that confirms that the --preserve flag is enabled by default in Talos `v1.8+`? It would be helpful to include it in the documentation.

**Comment by DrummyFloyd** [comment]
> > i wan't to upgrade the documentation of how longhorn need to be configured with new talos [UserVolumeConfig](https://www.talos.dev/v1.10/reference/configuration/block/uservolumeconfig/)
> > in the documents , because from 1.10.x and higher the actual way from [longhorn(docs](https://longhorn.io/docs/1.9.0/advanced-resources/os-distro-specific/talos-linux-support/) is deprecated
> 
> Thanks for bringing this up! PRs to update the docs are definitely welcome. Before moving forward, I just want to clarify a couple of things.
> 
> Could you please confirm which part of the current Talos setup is deprecated starting from `v1.10+`? Are you talking about the use of `machine.kubelet.extraMounts`? If you have any official references or links about this deprecation, that would help.
i will let the previsou and add a new sections like 1.10+ version of talos because do't want to force ppl to move to new version 

> Also, is `UserVolumeConfig` now required in Talos `v1.10+`, or is it more of an optional setup?

yes it's like optionnal but recommanded , will avoid to take all disk and use partition to compatimented better stuff with talos EPHEMERAL ( os level ) and ohter stuff like `UserVolumeConfig`, will explains this in the doc dw.

you can  still do only this with no futher config 

```
machine:
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn
        type: bind
        source: /var/mnt/longhorn
        options:
          - bind
          - rshared
          - rw
```


> > and --preserve arguments on talosctl upgrade  is no more needed since 1.8 ( is set by default on upgrade operation)
> 
> Do you happen to have a link or release note that confirms that the --preserve flag is enabled by default in Talos `v1.8+`? It would be helpful to include it in the documentation.

 will indeed do that =) 


will to to this PR this week end
