### ISSUE TITLE
[IMPROVEMENT] Expose SPDK UBLK Parameters

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#11039]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

The SPDK UBLK frontend includes `queue_depth`, `num_queues`, `disable-user-copy` parameters that impact I/O performance. Longhorn can expose these as both global and per-volume settings to help users fine-tune performance.

Ref: https://spdk.io/doc/jsonrpc.html

**Comment by bachmanity1** [comment]
Hi @PhanLe1010, if you haven’t started working on this issue yet, would it be okay if I take it over?

**Comment by PhanLe1010** [comment]
Hi @bachmanity1 I am working on this today. I will push PR soon.
Would be appreciate if you can review PR

**Comment by bachmanity1** [comment]
Hi @PhanLe1010, thanks for the PRs!

I initially got interested in this issue because the benchmark results [mention](https://github.com/longhorn/longhorn/issues/10757#issuecomment-2965730951) that the number of I/O queues might be why NVMe outperforms UBLK. It also says zero-copy is disabled for UBLK, but that seems to be [not true](https://github.com/longhorn/longhorn-instance-manager/blob/v1.9.x/vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/initiator.go#L409).

I tried running some benchmarks using kbench in my local cluster by changing the [hard-coded](https://github.com/longhorn/go-spdk-helper/blob/6d075880c7a2a07fe69f4c69676262673a5a97f6/pkg/initiator/initiator.go#L34) number of queues, but I didn’t see any improvement. NVMe still outperformed UBLK even after increasing the number of queues.

I’m guessing there might be an issue with my test setup, so I wanted to ask if you could run some benchmarks on your side and check whether increasing the number of queues improves performance?

**Comment by PhanLe1010** [comment]
Thanks @bachmanity1 
Surely, I will test it

**Comment by PhanLe1010** [comment]
## Test Plan:

### Case 1: Using UI 
1. Create a v2 volume with UBLK frontend 
2. (Before UI ticket is completed use kubectl) Set ublk queue depth and number of queues to different values
3. Attach the volume to a node
4. Exec into the IM pod on the attached node, run `go-spdk-helper ublk get-disks` to verify 
5. Detach the volume
6. Try to change ublk queue depth and number of queues to different values
7. Attach the volume, verify that change took effect 

### Case 2: Using UI - default setting 
1. Change `Default Ublk Number Of Queue` and `Default Ublk Queue Depth`
2. Create a v2 volume with UBLK frontend. Do NOT set ublk queue depth and number of queues to different values 
4. Attach the volume to a node 
5. Exec into the IM pod on the attached node, run `go-spdk-helper ublk get-disks` to verify that the default value was used

### Case 3: StorageClass - default setting 
1. Create a storageclass as
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-v2-data-engine
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      fsType: "ext4"
      dataEngine: "v2"
      ublkQueueDepth: "256"
      ublkNumberOfQueue: "7"
      frontend: "ublk"
    ```
2. Create a PVC from this SC
3. Attach the volume to a node
4. Exec into the IM pod on the attached node, run `go-spdk-helper ublk get-disks` to verify

**Comment by liyimeng** [comment]
@bachmanity1 Thanks for sharing the test outcome.  Lets see if @PhanLe1010 will come with a better result :D

**Comment by derekbit** [comment]
Added `require/doc` because the new settings are introduced. cc @PhanLe1010

**Comment by PhanLe1010** [comment]
> Added `require/doc` because the new settings are introduced. cc [@PhanLe1010](https://github.com/PhanLe1010)

Pushed doc PR https://github.com/longhorn/website/pull/1249
Thank you!

**Comment by roger-ryao** [comment]
**Verified on master-head 20251121**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/e7640cf54ef88eaad8eb1c842ecf8ee803eee689
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/1656829e00f01dad24755037f02f00964e195a25
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/14a185b582300718b4f6db68c1908692ff51874b

**The test steps**
https://github.com/longhorn/longhorn/issues/11039#issuecomment-3544740242

**Result**

```bash
> kubectl exec instance-manager-98780070e89ece2528333954ca0f8fc7 -n longhorn-system  -- sh -c "go-spdk-helper ublk get-disks"
[
        {
                "bdev_name": "pvc-949fdbc0-2ac3-41a7-b40c-63e684148bd2-e-0",
                "id": 1,
                "num_queues": 7,
                "queue_depth": 256,
                "ublk_device": "/dev/ublkb1"
        }
]
> kubectl exec instance-manager-1998b54d621b076e41879bd584964e8f -n longhorn-system  -- sh -c "go-spdk-helper ublk get-disks"
[
        {
                "bdev_name": "pvc-dc699771-7de8-4333-9b49-41eb61f62bb0-e-0",
                "id": 1,
                "num_queues": 7,
                "queue_depth": 256,
                "ublk_device": "/dev/ublkb1"
        }
]


```

Case 3 test passed, but Case 1 and Case 2 will be verified together once #[12166](https://github.com/longhorn/longhorn/issues/12166) is completed.

**Comment by PhanLe1010** [comment]
### Regarding the performance issue with UBLK

Let's focus on a specific metric such as `random write latency`. In this report https://github.com/longhorn/longhorn/wiki/Performance-Benchmark#results , the random write latency of UBLK fronend with 1 CPU core is worst. 

**However, I just retested today (with identical env) which gave an opposite result. A.K.A UBLK frontend with single CPU core have better `random write latency` than NVME-Of with single CPU core. More specifically:** 




<details>
<summary>This is the number for  NVME-Of with single CPU core (87 usec)</summary>
<br>

```
root@phan-m3-large-x86-01:~/kbench# fio ./fio/latency-random-write.fio --filename=/dev/mapper/testvol --size=200GiB  
rand-write-lat: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.36
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=44.7MiB/s][w=11.4k IOPS][eta 00m:00s]
rand-write-lat: (groupid=0, jobs=1): err= 0: pid=3335774: Thu Nov 27 02:54:34 2025
  write: IOPS=11.4k, BW=44.4MiB/s (46.6MB/s)(2664MiB/60001msec); 0 zone resets
    slat (usec): min=10, max=127, avg=14.58, stdev= 1.21
    clat (usec): min=45, max=3529, avg=72.72, stdev=13.26
     lat (usec): min=77, max=3544, avg=87.30, stdev=13.42
    clat percentiles (usec):
     |  1.00th=[   68],  5.00th=[   69], 10.00th=[   69], 20.00th=[   70],
     | 30.00th=[   71], 40.00th=[   72], 50.00th=[   73], 60.00th=[   73],
     | 70.00th=[   74], 80.00th=[   75], 90.00th=[   78], 95.00th=[   82],
     | 99.00th=[   88], 99.50th=[   92], 99.90th=[  121], 99.95th=[  165],
     | 99.99th=[  396]
   bw (  KiB/s): min=44456, max=46632, per=100.00%, avg=45471.78, stdev=426.69, samples=120
   iops        : min=11114, max=11658, avg=11367.91, stdev=106.67, samples=120
  lat (usec)   : 50=0.01%, 100=99.81%, 250=0.17%, 500=0.01%, 750=0.01%
  lat (usec)   : 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=1.81%, sys=19.11%, ctx=681996, majf=0, minf=36
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,681993,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
```

</details>


<details>
<summary>And this is the number for UBLK frontend with sungle CPU core (67 usec)</summary>
<br>

```
root@phan-m3-large-x86-01:~/kbench# fio ./fio/latency-random-write.fio --filename=/dev/mapper/testvol --size=200GiB  
rand-write-lat: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.36
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=55.0MiB/s][w=14.1k IOPS][eta 00m:00s]
rand-write-lat: (groupid=0, jobs=1): err= 0: pid=3342869: Thu Nov 27 02:57:55 2025
  write: IOPS=14.8k, BW=57.6MiB/s (60.4MB/s)(3458MiB/60001msec); 0 zone resets
    slat (usec): min=4, max=169, avg= 5.07, stdev= 1.12
    clat (nsec): min=1232, max=902157, avg=62175.41, stdev=5852.32
     lat (usec): min=57, max=910, avg=67.24, stdev= 6.52
    clat percentiles (usec):
     |  1.00th=[   57],  5.00th=[   57], 10.00th=[   58], 20.00th=[   59],
     | 30.00th=[   59], 40.00th=[   61], 50.00th=[   62], 60.00th=[   63],
     | 70.00th=[   64], 80.00th=[   66], 90.00th=[   69], 95.00th=[   74],
     | 99.00th=[   81], 99.50th=[   84], 99.90th=[   95], 99.95th=[  112],
     | 99.99th=[  172]
   bw (  KiB/s): min=44408, max=61744, per=100.00%, avg=59028.32, stdev=3307.76, samples=120
   iops        : min=11102, max=15436, avg=14757.06, stdev=826.94, samples=120
  lat (usec)   : 2=0.01%, 20=0.01%, 50=0.01%, 100=99.93%, 250=0.07%
  lat (usec)   : 500=0.01%, 750=0.01%, 1000=0.01%
  cpu          : usr=1.80%, sys=12.48%, ctx=887246, majf=0, minf=36
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,885349,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=57.6MiB/s (60.4MB/s), 57.6MiB/s-57.6MiB/s (60.4MB/s-60.4MB/s), io=3458MiB (3626MB), run=60001-60001msec
```

</details>

Something that I want to check is if you guy try to prefilled with data to avoid the spare file initial write penalty as mentioned in this report https://github.com/longhorn/longhorn/wiki/Longhorn-Performance-Investigation#:~:text=Finally%2C%20we%20are%20testing%20fio%20directly%20on%20the%20block%20device%20to%20bypass%20possible%20filesystem%20effects.%20The%20block%20device%20is%20prefilled%20with%20data%20to%20avoid%20the%20spare%20file%20initial%20write%20penalty.%20For%20example%2C%20prefilling%20with%20this%20command%20sudo%20dd%20if%3D/dev/zero%20of%3D/dev/sdc%20bs%3D1M%20count%3D256000

cc @derekbit @bachmanity1 @liyimeng @shuo-wu

**Comment by bachmanity1** [comment]
> However, I just retested today (with identical env) which gave an opposite result. A.K.A UBLK frontend with single CPU core have better random write latency than NVME-Of with single CPU core. More specifically:

So, you got different results even though you didn’t change any settings, and the only thing you did was prefill the block device with some data?

**Comment by PhanLe1010** [comment]
> > However, I just retested today (with identical env) which gave an opposite result. A.K.A UBLK frontend with single CPU core have better random write latency than NVME-Of with single CPU core. More specifically:
> 
> So, you got different results even though you didn’t change any settings, and the only thing you did was prefill the block device with some data?

Hi @bachmanity1 Yes. Could you give a try with prefill the block device before testing?

I am doing more testing for other metrics than the latency metric

**Comment by PhanLe1010** [comment]
### Update

I completed the UBLK test following the testing parameter at [Longhorn Performance Investigation Report](https://github.com/longhorn/longhorn/wiki/Longhorn-Performance-Investigation) . **The result is expected. UBLK outperformed Nvme-of front end similar to the result from the report**

<img width="851" height="459" alt="Image" src="https://github.com/user-attachments/assets/5e589e58-38ff-4f1d-9ff5-55bd6186c210" />

cc @derekbit @bachmanity1 @shuo-wu 


### Additional context:
* Remember to prefill the volume
* Testing command:
```bash
fio ./fio/latency-random-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63
fio ./fio/latency-random-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63

fio ./fio/bandwidth-sequential-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
fio ./fio/bandwidth-sequential-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16

fio ./fio/iops-random-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
fio ./fio/iops-random-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
```

**Comment by bachmanity1** [comment]
Hi @PhanLe1010, could you please explain what do the parameters shown below mean? Have you configured these using new settings that you've added? The report you shared also mentions about these but back when this report was written it was not possible to configure number of queues so I'm a little confused. Why was these specific values for number of queues and queue depth chosen?

<img width="304" height="101" alt="Image" src="https://github.com/user-attachments/assets/4e84631d-91f2-4231-8bfb-a27fa6d3298d" />

Also, can you put all the kbench settings you use in a separate branch and share a link to it so that it can be reused by others to reproduce your results?

**Comment by PhanLe1010** [comment]
> Hi @PhanLe1010, could you please explain what does this mean? Have you configured these using new settings that you've added? The link you shared also mentions about this but back when it was written it was not possible to configure number of queues so I'm a little confused.
> <img width="304" height="101" alt="Image" src="https://github.com/user-attachments/assets/4e84631d-91f2-4231-8bfb-a27fa6d3298d" />

Hi @bachmanity1 It means this 2 new settings (implemented in this ticket)
```
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
...
spec:
  ublkNumberOfQueue: 32
  ublkQueueDepth: 128
```

> Also, can you put all the kbench settings you use in a separate branch and share a link to it so that it can be reused by others to reproduce your results?

Surely. This is the commit https://github.com/PhanLe1010/kbench/commit/5a08e8877d1e18c9c90564fb08fc47556008fe9e

The detailed testing steps are:
1. Clone the above commit 
1. `cd kbench`
1. Create an v2 volume of 250GiB, 1 replica, with ublk frontend, `ublkNumberOfQueue: 32`, and `ublkQueueDepth: 128`
1. Attach the volume on the same node as replica
1. Prefill the volume `sudo dd if=/dev/zero of=/dev/mapper/testvol bs=1M count=256000`
1. Perform the `fio` test:
    ```bash
    fio ./fio/latency-random-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63
    fio ./fio/latency-random-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63
    
    fio ./fio/bandwidth-sequential-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
    fio ./fio/bandwidth-sequential-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
    
    fio ./fio/iops-random-read.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
    fio ./fio/iops-random-write.fio --filename=/dev/mapper/testvol --size=200GiB --cpus_allowed=4-63 --numjobs=16
    ```
1. Do the same for nvme front end volume
1. If you would like to test 3 replica volume, increase the replica count and repeat

**Comment by shuo-wu** [comment]
I am thinking if we can improve our kbench by providing such an option as `prefill-disk`?

**Comment by roger-ryao** [comment]
> **Verified on master-head 20251121**
> 
> * longhorn `master-head` [e7640cf](https://github.com/longhorn/longhorn/commit/e7640cf54ef88eaad8eb1c842ecf8ee803eee689)
> * longhorn-manager `master-head` [longhorn/longhorn-manager@1656829](https://github.com/longhorn/longhorn-manager/commit/1656829e00f01dad24755037f02f00964e195a25)
> * longhorn-instance-manager `master-head` [longhorn/longhorn-instance-manager@14a185b](https://github.com/longhorn/longhorn-instance-manager/commit/14a185b582300718b4f6db68c1908692ff51874b)
> 
> **The test steps** [#11039 (comment)](https://github.com/longhorn/longhorn/issues/11039#issuecomment-3544740242)
> 
> Case 3 test passed, but Case 1 and Case 2 will be verified together once #[12166](https://github.com/longhorn/longhorn/issues/12166) is completed.

Hi @PhanLe1010 
    I re-tested on `master-head` today using the YAML below to create a StatefulSet with a ublk v2 volume, but the volume failed to attach. However, this exact same method worked fine in my previous test. Could you please help take a look at what might be wrong?

[supportbundle_155fb215-ad5f-4d4f-9aa2-c3da307c17b2_2025-12-09T07-23-59Z.zip](https://github.com/user-attachments/files/24049511/supportbundle_155fb215-ad5f-4d4f-9aa2-c3da307c17b2_2025-12-09T07-23-59Z.zip)

volume name : `pvc-123bbd9e-ef60-4426-bdf6-a8f3dda6af4a`

```yaml
# Service for v2 RWO
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo-v2
  labels:
    app: nginx-state-rwo-v2
spec:
  ports:
  - port: 80
    name: web-rwo-v2
  selector:
    app: nginx-state-rwo-v2
  type: NodePort
---
# StatefulSet for v2 RWO
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo-v2
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo-v2
  serviceName: "nginx-state-rwo-v2"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo-v2
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo-v2
        image: nginx:stable
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-rwo-v2
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn-v2-data-engine"
      resources:
        requests:
          storage: 2Gi
---
# Service for v2 RWX
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx-v2
  labels:
    app: nginx-state-rwx-v2
spec:
  ports:
  - port: 80
    name: web-rwx-v2
  selector:
    app: nginx-state-rwx-v2
  type: NodePort
---
# StatefulSet for v2 RWX
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx-v2
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx-v2
  serviceName: "nginx-state-rwx-v2"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx-v2
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx-v2
        image: nginx:stable
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-rwx-v2
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "longhorn-v2-data-engine"
      resources:
        requests:
          storage: 2Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-v2-data-engine
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataEngine: "v2"
  ublkQueueDepth: "256"
  ublkNumberOfQueue: "7"
  frontend: "ublk"

```
