### ISSUE TITLE
[IMPROVEMENT] add support for custom annotations in the UI service on Longhorn Helm Chart

### ISSUE THREAD

**Issue by josimar-silva** [longhorn/longhorn#11031]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

Add support for custom annotations to the UI service on Longhorn Helm chart

### Describe the solution you'd like

E.g: values.yaml

```yaml
service:
  ui:
    type: "LoadBalancer"
    loadBalancerIP: 192.168.10.101
    annotations:
      external-dns.alpha.kubernetes.io/hostname: longhorn.homelab.lan
      metallb.io/ip-allocated-from-pool: homelab-local-pool
      metallb.universe.tf/allow-shared-ip: longhorn-svc
```

Renderer UI Service definition:
```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: longhorn
    helm.sh/chart: longhorn-1.9.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: longhorn-test
    app.kubernetes.io/version: v1.9.0
    app: longhorn-ui
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.homelab.lan
    metallb.io/ip-allocated-from-pool: homelab-local-pool
    metallb.universe.tf/allow-shared-ip: longhorn-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.101
  selector:
    app: longhorn-ui
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: null
```

### Additional context

https://github.com/longhorn/charts/pull/211
