### ISSUE TITLE
[FEATURE] Standardized way to override container image registry

### ISSUE THREAD

**Issue by marcosbc** [longhorn/longhorn#11064]
### Is your feature request related to a problem? Please describe (👍 if you like this request)

A big part of the Helm charts have standardized on using `global.imageRegistry` as a way to override the image registry, in addition to per-image modifications via `*.registry` (in the same level as `*.repository`). 

### Describe the solution you'd like

We would like this Helm chart to support overriding the container image registry both globally, using the standardized `global.imageRegistry` value, as well as per-image via `$imagePath.registry`.

**Comment by yangchiu** [comment]
Verification failed on master-head (longhorn 637d9e6).

Set `privateRegistry.registrySecret` in `values.yaml` 

```
privateRegistry:
  registrySecret: docker-registry-secret
```

Then install Longhorn:

```
$ helm install longhorn ./longhorn/chart/ --namespace longhorn-system --create-namespace
```

Get an error message:

```
Error: INSTALLATION FAILED: template: longhorn/templates/uninstall-job.yaml:36:34: executing "longhorn/templates/uninstall-job.yaml" at <append>: wrong number of args for append: want 2 got 1
```

cc @marcosbc @derekbit

**Comment by derekbit** [comment]
> Verification failed on master-head (longhorn [637d9e6](https://github.com/longhorn/longhorn/commit/637d9e62fd496fbdcdbfbcd007caaee4ff5116eb)).
> 
> Set `privateRegistry.registrySecret` in `values.yaml`
> 
> ```
> privateRegistry:
>   registrySecret: docker-registry-secret
> ```
> 
> Then install Longhorn:
> 
> ```
> $ helm install longhorn ./longhorn/chart/ --namespace longhorn-system --create-namespace
> ```
> 
> Get an error message:
> 
> ```
> Error: INSTALLATION FAILED: template: longhorn/templates/uninstall-job.yaml:36:34: executing "longhorn/templates/uninstall-job.yaml" at <append>: wrong number of args for append: want 2 got 1
> ```
> 
> cc [@marcosbc](https://github.com/marcosbc) [@derekbit](https://github.com/derekbit)

@yangchiu You should use `registrySecret: [docker-registry-secret]` instead.

**Comment by yangchiu** [comment]
> [@yangchiu](https://github.com/yangchiu) You should use `registrySecret: [docker-registry-secret]` instead.

@derekbit According to [the document](https://longhorn.io/docs/1.9.0/deploy/install/airgap/#use-default-image-name), `privateRegistry.registrySecret` is not an array.

**Comment by yangchiu** [comment]
> > [@yangchiu](https://github.com/yangchiu) You should use `registrySecret: [docker-registry-secret]` instead.
> 
> [@derekbit](https://github.com/derekbit) According to [the document](https://longhorn.io/docs/1.9.0/deploy/install/airgap/#use-default-image-name), `privateRegistry.registrySecret` is not an array.

If `privateRegistry.registrySecret` is set to an array, Longhorn fails to create the secret when `privateRegistry.createSecret` is set to `true`:

```
privateRegistry:
  createSecret: true
  registryUser: username
  registryPasswd: password
  registrySecret: [docker-registry-secret]
``` 

```
$ helm install longhorn ./longhorn/chart/ --namespace longhorn-system --create-namespace
Error: INSTALLATION FAILED: YAML parse error on longhorn/templates/registry-secret.yaml: error unmarshaling JSON: while 
decoding JSON: json: cannot unmarshal array into Go struct field .metadata.name of type string
```

**Comment by marcosbc** [comment]
Sent #11145 to fix the issues reported by @yangchiu.

**Comment by roger-ryao** [comment]
**Verified on v1.10.0-dev-20250629 20250703**

- longhorn v1.10.0-dev-20250629 https://github.com/longhorn/longhorn/commit/0fc2e125698fb029b18c08ee3f3b635f89221763



**The test steps**

1. https://github.com/longhorn/longhorn/issues/11064#issuecomment-2982522434
2. https://github.com/longhorn/longhorn/issues/11064#issuecomment-2988541360


**Result Passed**

1. After following the steps provided in https://github.com/longhorn/longhorn/issues/11064#issuecomment-2982522434, the installation succeeded.
2. After following the steps provided in https://github.com/longhorn/longhorn/issues/11064#issuecomment-2988541360, the expected error was reproduced.

If `privateRegistry.registrySecret` is defined but not a string, an error is thrown. This is because the template currently expects it to be a string.

```console
longhorn> helm install longhorn ./chart/ --namespace longhorn-system --create-namespaceWARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ryao/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ryao/.kube/config
Error: INSTALLATION FAILED: execution error at (longhorn/templates/registry-secret.yaml:4:4): The privateRegistry.registrySecret value must be a string

```

**Comment by yangchiu** [comment]
Reopened due to https://github.com/longhorn/longhorn/issues/11068#issuecomment-3050707376. Using `global.imageRegistry` to set the private registry url and `privateRegistry.registrySecret` to set the private registry secret. `privateRegistry.registrySecret` is not applied while pulling Longhorn component images.

**Comment by marcosbc** [comment]
@yangchiu I couldn't reproduce this issue. Note that, according to the [README](https://github.com/longhorn/longhorn/blob/v1.9.x/chart/README.md#private-registry-settings), `privateRegistry.registrySecret` should only be enabled if secret creation is enabled (`privateRegistry.createSecret`):

> privateRegistry.registrySecret: Kubernetes secret that allows you to pull images from a private registry. **This setting applies only when creation of private registry secrets is enabled.** You must include the private registry name in the secret name.

So the way I tried to reproduce this issue was by using the following command:l

```console
$ helm template longhorn --set global.imageRegistry=myregistry.io --set privateRegistry.createSecret=true --set privateRegistry.registrySecret=mysecretname .
```

Due to this, `privateRegistry.registrySecret` is not meant to be an alias for `global.imagePullSecrets`, because the latter can be used to specify an existing secret name, and does not imply the creation of a new one.

If you think we should update the existing `privateRegistry.registrySecret` so that it acts as an alias to `global.imageRegistry`, even if secrets are not to be created, let me know and I can take care of it.

**Comment by yangchiu** [comment]
> Due to this, `privateRegistry.registrySecret` is not meant to be an alias for `global.imagePullSecrets`, because the latter can be used to specify an existing secret name, and does not imply the creation of a new one.

No, if `privateRegistry.createSecret` is set to `true`, it will automatically generate a secret based on the provided values with the name `privateRegistry.registrySecret`. If `privateRegistry.createSecret` is set to `false`, it uses the existing private registry secret provided in `privateRegistry.registrySecret`.

ref: https://github.com/longhorn/longhorn/pull/3673

**Comment by roger-ryao** [comment]
**Verified on master-head 20250710**

- longhorn master-head https://github.com/longhorn/longhorn/commit/e5333e5ea176fc6de4cd38f7deb52d400840cc3b

**The test steps**

https://github.com/longhorn/longhorn/pull/11252#pullrequestreview-3003538008
https://github.com/longhorn/longhorn/issues/11068#issuecomment-3050707376


**Result Passed**

Verification passed. 
Longhorn helm chart can successfully pull component images from a private registry with the following configuration combinations:

1. `global.imageRegistry` + `privateRegistry.createSecret=false`


Create a docker registry secret:
```bash
kubectl create ns longhorn-system
kubectl -n longhorn-system create secret docker-registry docker-registry-secret --docker-server=lh-registry-xxxxxxxx.longhorn.ninja --docker-username=registry_user --docker-password=registry_password
```


`values.yaml` Configuration
```yaml
global:
  # -- Global override for container image registry.
  imageRegistry: "lh-registry-xxxxxxxx.longhorn.ninja"
```

```yaml
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: false
```

Install Longhorn:
```bash
ryao@ryao-laptop:~/Desktop/longhorn>  helm install longhorn ./chart/ --namespace longhorn-system --create-namespace
```


2. `global.imageRegistry` + `privateRegistry.createSecret=true`


`values.yaml` Configuration
```yaml
global:
  # -- Global override for container image registry.
  imageRegistry: "lh-registry-xxxxxxxx.longhorn.ninja"
```

```yaml
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: true
  # -- URL of a private registry. When unspecified, Longhorn uses the default system registry.
  registryUrl: ~
  # -- User account used for authenticating with a private registry.
  registryUser: "registry_user"
  # -- Password for authenticating with a private registry.
  registryPasswd: "registry_password"
  # -- Kubernetes secret that allows you to pull images from a private registry. This setting applies only when creation of private registry secrets is enabled. You must include the private registry name in the secret name.
  registrySecret: docker-registry-secret
```


3. `privateRegistry.registryUrl` + `privateRegistry.createSecret=true`


`values.yaml` Configuration

```yaml
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: true
  # -- URL of a private registry. When unspecified, Longhorn uses the default system registry.
  registryUrl: "lh-registry-xxxxxxxx.longhorn.ninja"
  # -- User account used for authenticating with a private registry.
  registryUser: "registry_user"
  # -- Password for authenticating with a private registry.
  registryPasswd: "registry_password"
  # -- Kubernetes secret that allows you to pull images from a private registry. This setting applies only when creation of private registry secrets is enabled. You must include the private registry name in the secret name.
  registrySecret: "docker-registry-secret"
```

4. `privateRegistry.registryUrl` + `global.imagePullSecrets`

```bash
kubectl -n longhorn-system create secret docker-registry docker-registry-secret --docker-server=lh-registry-xxxxxxxx.longhorn.ninja --docker-username=registry_user --docker-password=registry_password
```

`values.yaml` Configuration
```yaml
global:
  # -- Global override for container image registry.
  imageRegistry: ~
  # -- Global override for image pull secrets for container registry.
  imagePullSecrets:
    - name: "docker-registry-secret"
```

```yaml
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: false
  # -- URL of a private registry. When unspecified, Longhorn uses the default system registry.
  registryUrl: "lh-registry-xxxxxxxx.longhorn.ninja"
  # -- User account used for authenticating with a private registry.
  registryUser: ~
  # -- Password for authenticating with a private registry.
  registryPasswd: ~
  # -- Kubernetes secret that allows you to pull images from a private registry. This setting applies only when creation of private registry secrets is enabled. You must include the private registry name in the secret name.
  registrySecret: ~
```

5. `global.imageRegistry` + `global.imagePullSecrets`

```bash
kubectl -n longhorn-system create secret docker-registry docker-registry-secret --docker-server=lh-registry-xxxxxxxx.longhorn.ninja --docker-username=registry_user --docker-password=registry_password
```

`values.yaml` Configuration
```yaml
global:
  # -- Global override for container image registry.
  imageRegistry: "lh-registry-xxxxxxxx.longhorn.ninja"
  # -- Global override for image pull secrets for container registry.
  imagePullSecrets:
    - name: "docker-registry-secret"
```

```yaml
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: false
  # -- URL of a private registry. When unspecified, Longhorn uses the default system registry.
  registryUrl: ~
  # -- User account used for authenticating with a private registry.
  registryUser: ~
  # -- Password for authenticating with a private registry.
  registryPasswd: ~
  # -- Kubernetes secret that allows you to pull images from a private registry. This setting applies only when creation of private registry secrets is enabled. You must include the private registry name in the secret name.
  registrySecret: ~
```
