### ISSUE TITLE
[BUG] "mkfsParams" in StorageClass are not passed to share-manager for filesystem formatting

### ISSUE THREAD

**Issue by Florianisme** [longhorn/longhorn#11107]
### Describe the Bug

When specifying "mkfsParams" on a Storage Class, these parameters are not passed down to the share-manager which is responsible for formatting the filesystem once it's initially mounted.

When the share-manager creates an RWX Volume for the first time, it needs to format the underlying filesystem.
The following lines are printed:

> Volume pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c device /dev/longhorn/pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c contains filesystem of format " encrypted=false volume=pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c
Disk "/dev/longhorn/pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c]
Disk successfully formatted (mkfs): ext4 - /dev/longhorn/pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c /export/pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c

The mkfs Parameters from the Storage Class are completely disregarded:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-high-inodes
allowVolumeExpansion: true
parameters:
  mkfsParams: "-i 4096"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

### To Reproduce

1. Create a Custom Storage class with the Parameter "mkfsParams" set
2. Create an RWX PVC using the previously created Storage Class
3. Create a Deployment referencing the previously created PVC
4. Check the Filesystem Parameters (or inode count in my case) of the newly created Volume on the Host

### Expected Behavior

Irrelevant of which Longhorn component formats the underlying filesystem, the mkfs Parameters should be respected.

The mechanism works as intended for RWO volumes which are not formatted by the share-manager.

### Support Bundle for Troubleshooting

As Mail

### Environment

- Longhorn version: 1.8.1
- Impacted volume: pvc-819eec47-14e9-44ab-b2fe-6d8c86c48e5c
- Installation method: Rancher Catalog App
- Kubernetes distro: v1.32.5+rke2r1
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 9
- Node config
  - OS type and version: SLES15 SP6
  - Kernel version: 6.4.0-150600.23.33-default
  - CPU per node: 16
  - Memory per node: 72GB
  - Disk type: SSD
  - Network bandwidth between the nodes (Gbps): 10
- Underlying Infrastructure: VMWare
- Number of Longhorn volumes in the cluster: 13

**Comment by Florianisme** [comment]
The share-manager calls https://github.com/kubernetes/mount-utils/blob/master/mount_linux.go internally.

This is where the formatOptions need to be passed into.


I assume share-manager needs a new parameter which it can then pass down to the underlying function calls.

**Comment by derekbit** [comment]
Thanks @Florianisme for the contribution. I assigned the ticket to you. Feel free to let us know if you need any help.

**Comment by derekbit** [comment]
cc @davidcheng0922  @COLDTURNIP

**Comment by Florianisme** [comment]
@derekbit How can I best test these changes in our cluster? Is there a way to build a Docker Image from my changes which I can deploy?

**Comment by derekbit** [comment]
> [@derekbit](https://github.com/derekbit) How can I best test these changes in our cluster? Is there a way to build a Docker Image from my changes which I can deploy?

You can build the images by longhorn-manager and longhorn-share-manager images by
```
export REPO=<your image registry repo>; export TAG=<your tag>; make
```
Then, push the images to your registry.

Replace the images in your Longhorn cluster.

**Comment by Florianisme** [comment]
I can't get it to work. When I run "make", it starts the Docker build but exits with:

> exec ./scripts/entry: no such file or directory

Edit: Line endings were the culprit. I was building with WSL but had checked out the project from Windows

**Comment by Florianisme** [comment]
@derekbit Successfully tested and ready for review!

**Comment by mantissahz** [comment]
Hi @Florianisme,
Could you help fill out the `Pre Ready-For-Testing Checklist`, especially `Where is the reproduce steps/test steps documented` part? Thank you.

**Comment by Florianisme** [comment]
Hi @mantissahz, sure the steps are documented in the initial issue description under "To Reproduce". Or do you mean something else?

**Comment by derekbit** [comment]
Hello @Florianisme 
You’ve granted permission to edit the [pre-check list](https://github.com/longhorn/longhorn/issues/11107#issuecomment-2980635284). @mantissahz, please help guide @Florianisme in completing the list. Thank you both!

**Comment by Florianisme** [comment]
I have filled out the checklist to my best knowledge @mantissahz. Can you check?

**Comment by mantissahz** [comment]
>I have filled out the checklist to my best knowledge @mantissahz. Can you check?

Looks good. And after all PRs are merged, you can move the Longhorn Sprint status to `Ready For Testing`.
Thank you for the contribution.

**Comment by roger-ryao** [comment]
**Verified on v1.10.0-dev-20250629 20250703**

- longhorn v1.10.0-dev-20250629 https://github.com/longhorn/longhorn/commit/0fc2e125698fb029b18c08ee3f3b635f89221763
- longhorn-manager v1.10.0-dev-20250629 https://github.com/longhorn/longhorn-manager/commit/d75b51f3d7b315bc1dd76625532e41d9f4fa3949

**The test steps**

https://github.com/longhorn/longhorn/issues/11107#issue-3137042627

1. **Create a Custom Storage Class**  
   Define a storage class with the `mkfsParams` parameter:
   ```yaml
   apiVersion: storage.k8s.io/v1
   kind: StorageClass
   metadata:
     name: longhorn-high-inodes
   allowVolumeExpansion: true
   parameters:
     mkfsParams: "-i 4096"  # You can also test with "-i 2048"
   provisioner: driver.longhorn.io
   reclaimPolicy: Delete
   volumeBindingMode: Immediate
   ```

2. **Create a ReadWriteMany (RWX) PVC**  
   Use the custom storage class created in Step 1:
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: deployment-rwx-pvc
   spec:
     accessModes:
       - ReadWriteMany
     storageClassName: longhorn-high-inodes
     resources:
       requests:
         storage: 2Gi
   ```

3. **Deploy a Pod Using the RWX PVC**  
   Deploy a pod that references the PVC:
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: deployment-rwx
     labels:
       app: deployment-rwx
   spec:
     selector:
       matchLabels:
         app: deployment-rwx
     strategy:
       type: Recreate
     template:
       metadata:
         labels:
           app: deployment-rwx
       spec:
         containers:
         - image: ubuntu
           name: deployment-rwx
           command: ["/bin/sleep", "3650d"]
           volumeMounts:
           - name: deployment-rwx-volume
             mountPath: "/data/"
         volumes:
         - name: deployment-rwx-volume
           persistentVolumeClaim:
             claimName: deployment-rwx-pvc
   ```


4. **Verify the Share Manager Logs**  
   Check the logs of the share manager pod to confirm the `mkfsParams` value is applied.

5. **Verify the Inode Count**  
- Formula to Calculate Inodes Count:
   ```
   Inodes count = Total disk size (bytes) / Bytes per inode
   ```
- Example Calculation:
   - For a 2 GB volume with `-i 4096` (bytes per inode):
     ```
     Inodes count = (2 * 1024^3) / 4096 = 524288
     ```

- Check Actual Inode Count:
   Use the `tune2fs` command:
   ```bash
   sudo tune2fs -l /dev/longhorn/<volume-name>
   ```

**Result Passed**


Case 1: `mkfsParams: -i 2048`
   - Share Manager Log:
     ```bash
     I0703 11:13:15.996687       1 mount_linux.go:608] Disk "/dev/longhorn/pvc-0c669b50-058e-4157-aad2-c460e1a86d44" appears to be unformatted, attempting to format as type: "ext4" with options: [-i 2048 -F -m0 /dev/longhorn/pvc-0c669b50-058e-4157-aad2-c460e1a86d44]
     ```
   - Inode Count (via `tune2fs`):
     ```bash
     Inode count: 1048576
     ```

Case 2: `mkfsParams: -i 4096`
   - Share Manager Log:
     ```bash
     I0703 11:26:42.053831       1 mount_linux.go:608] Disk "/dev/longhorn/pvc-d098e9cb-868f-41cb-81e1-0c876ca0d838" appears to be unformatted, attempting to format as type: "ext4" with options: [-i 4096 -F -m0 /dev/longhorn/pvc-d098e9cb-868f-41cb-81e1-0c876ca0d838]
     ```
   - Inode Count (via `tune2fs`):
     ```bash
     Inode count: 524288
     ```

---


- The `mkfsParams` parameter in the custom storage class successfully applied the specified inode configuration (`-i 2048` or `-i 4096`).
- The `Inode count` matches the expected values based on the formula.
