### ISSUE TITLE
[BUG] spdk_tgt crash after replica rebuilding due to bdev_channel_destroy_resource() assert failure

### ISSUE THREAD

**Issue by hookak** [longhorn/longhorn#11109]
### Describe the Bug

After a volume replica has finished rebuilding in a SPDK-based Longhorn engine (dataEngine v2), the source (`src`) replica is removed as expected. During this process, the engine attempts to detach the src replica's bdev from its internal RAID.

At this point, we observed that the engine's SPDK process (`spdk_tgt` on the dst node) crashed with the following assertion failure:

```
spdk_tgt: bdev.c:3966: bdev_channel_destroy_resource: Assertion `TAILQ_EMPTY(&ch->io_submitted)' failed.
```

From the logs, we noticed that `bdev_nvme_disconnected_qpair_cb()` was triggered around the same time, which initiated a controller reset. This likely happened due to the src replica being deleted on the src node, which may have caused the NVMe/TCP connection to drop.

As a result, it seems that the SPDK engine was handling both the disconnection/reset and the bdev removal at nearly the same time. These overlapping operations may have led to a race condition, where the engine proceeded to destroy the bdev channel resources while I/O operations were still in-flight.

This assumption is supported by the coredump, which indicates that there was still an outstanding I/O operation on the bdev at the time of the crash:
```
(gdb) p *ch
...
io_outstanding = 1
io_submitted = {
tqh_first = 0x2000160f4c00,
tqh_last = 0x2000160f4ef0
}
...
(gdb) p ch->bdev->name
$3 = "pvc-6e096d31-ccfd-4f56-9634-a210e9eb6054-r-f543bd44n1"
```

### To Reproduce

1. Create a volumeA with a single replica located on `src-node` and the engine on `dst-node`.
2. Ensure `dst-node` is already running both a replica and engine for a different volumeB.
3. Change the `dataLocality` setting of volumeA from `disabled` to `best-effort` to trigger replica rebuilding `src-node` to `dst-node`.

### Expected Behavior

- Rebuilding should complete without crashing `spdk_tgt`.

### Support Bundle for Troubleshooting

send it by email

### Environment

- Longhorn version: v1.9.0
- Impacted volume (PV): pvc-6e096d31-ccfd-4f56-9634-a210e9eb6054
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.28.11
  - Number of control plane nodes in the cluster: 2
  - Number of worker nodes in the cluster: 12
- Node config
  - OS type and version: RHEL8.8
  - Kernel version: 5.15.27
  - CPU per node: 40
  - Memory per node: 128Gi 
  - Disk type (e.g. SSD/NVMe/HDD): SSD
  - Network bandwidth between the nodes (Gbps): 10Gbps
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 12

**Comment by hookak** [comment]
# Bug Reproduction Scenario

Although not fully confirmed, it appears that two conditions are required to reproduce the crash during volume replica rebuilding:

1. The volume already contains data.
2. Inflight I/O operations are ongoing when the rebuild is triggered.

To validate this hypothesis, the following experiment was conducted:

1. Create a Longhorn volume (`lhv`) using a StorageClass with `dataLocality: disable` and only one replica.
2. Run a pod that continuously creates and deletes files to simulate active I/O.
3. Wait for a few seconds to allow some data to accumulate and active I/O to occur.
4. Change the volume’s `dataLocality` setting to `best-effort` to trigger a replica rebuild.

The pause between steps 2 and 4 is intentional to ensure that meaningful data is written to the volume before the rebuild is triggered.  
This is the reason why we don’t create the volume with `dataLocality: best-effort` from the beginning — doing so would trigger the rebuild immediately, before any data or I/O activity takes place.
After step 4, once the rebuilding completes and the engine attempts to remove the source replica, we observed the following log message followed by a crash in the `spdk_tgt` process:
```
spdk_tgt: bdev.c:3966: bdev_channel_destroy_resource: Assertion `TAILQ_EMPTY(&ch->io_submitted)' failed.
```
These steps were repeated multiple times, and the crash could be reproduced consistently.

---

## YAML and Commands Used

### Step 1 & 2 – Pod Creation and File I/O

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: z-longhorn-pp
spec:
  restartPolicy: Always
  containers:
  - name: longhorn-pod1
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /data/files
        i=0
        while true; do
          echo "[$(date)] [$i] Creating files..."
          for j in $(seq 1 10000); do
            touch /data/files/file_${i}_${j}
            sync
          done
          echo "[$(date)] [$i] Deleting files..."
          rm -rf /data/files/*
          i=$((i + 1))
        done
    livenessProbe:
      exec:
        command:
          - ls
          - /data
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: z-longhorn-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z-longhorn-vol1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lh-ssd-system
  resources:
    requests:
      storage: 10Gi
```

### Step 3 – Trigger Replica Rebuilding


```
kubectl patch lhv {{longhorn_volume}} --type=merge -p '{"spec":{"dataLocality":"best-effort"}}'
```
