### ISSUE TITLE
[BUG] Node update forces a complete rebuild

### ISSUE THREAD

**Issue by Syntax3rror404** [longhorn/longhorn#11113]
### Describe the Bug

If a volume on a node, which gets drained and cordoned etc for a node update, forces longhorn to rebuild a complete pvc in this example over 300GB on the same node after they gets update again.

Also in this case longhorn owns its own NVME drive, which is mounted to kubelet. So every update the NVME gets useless penetrated with over 1TB of writes. 

![Image](https://github.com/user-attachments/assets/d2e55b6e-1ff0-4914-9908-58bdcf740f80)

Tested again on worker 3 after a node update, which confirms this issue to be reproducible. It writes the full 340GB to the same disk. 

![Image](https://github.com/user-attachments/assets/164a5811-a7df-4f24-bba6-c425407ff644)

Whats the proper way to deal with this? 

### To Reproduce

1. Install longhorn
2. Create a pvc with 3 replicas 
3. Update a kernel of a node which holds this replica and reboot it

### Expected Behavior

Replica is failed while node unavailable and recovers its state when node online and syncs its state with other

### Support Bundle for Troubleshooting

This bundle was created after longhorn rebuilds the master 3 pvc. See first picture above.
[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-12T14-56-41Z.zip](https://github.com/user-attachments/files/20711562/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-12T14-56-41Z.zip)

This bundle was created while longhorn rebuilds the worker 3 pvc. See second picture above.
[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-12T15-27-44Z.zip](https://github.com/user-attachments/files/20712069/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-12T15-27-44Z.zip)

### Environment

- Longhorn version: 1.8.1
- Impacted volume (PV): pvc-831eaeae-6074-429b-a28e-04b99f932022
- Installation method: Helm
- Kubernetes distro and version: Talos v1.32.4
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 3
- Node config
  - OS type and version: Talos 1.10.4
  - Kernel version: 6.12.31
  - CPU per node: 16
  - Memory per node: 64GB
  - Disk type: NVME
  - Network bandwidth between the nodes (Gbps): 2.5
- Underlying Infrastructure: Baremetal
- Number of Longhorn volumes in the cluster: 14

**Comment by derekbit** [comment]
For delta rebuilding, Longhorn calculates the checksum of each block both on the source and destination sides and compares the checksums. If the checksums are mismatched, Longhorn sends the block from the healthy side to the other side.

I'm not sure what `complete rebuild` means in the description. Do you mean it is a full rebuilding without delta rebuilding? Can you elaborate more on your expected behavior?

cc @mantissahz

**Comment by mantissahz** [comment]
Ref: longhorn/longhorn #10997

**Comment by derekbit** [comment]
@mantissahz Can you check the support bundle in https://github.com/longhorn/longhorn/issues/11113#issue-3140649375 and see if it is a delta rebuilding or a full rebuilding?

**Comment by Syntax3rror404** [comment]
@derekbit yes a delta rebuild is exactly what I expect with full I meaning a delete and complete copy which is the point of destroying the ssd.

**Comment by derekbit** [comment]
> [@derekbit](https://github.com/derekbit) yes a delta rebuild is exactly what I expect with full I meaning a delete and complete copy which is the point of destroying the ssd.

Took a quick look. The rebuilding reused the failed replica, so it should be a delta rebuilding. If it is a delta rebuilding, there wouldn’t have be lot network traffic while rebuilding snapshots except for the latest snapshot.

**Comment by Syntax3rror404** [comment]
@derekbit This is the problem, expected is delta but longhorn writes everything on the node from scratch

**Comment by derekbit** [comment]
> [@derekbit](https://github.com/derekbit) This is the problem, expected is delta but longhorn writes everything on the node from scratch

Hmm, curious, how do you know Longhorn writes everything thing from scratch?

**Comment by Syntax3rror404** [comment]
> > [@derekbit](https://github.com/derekbit) This is the problem, expected is delta but longhorn writes everything on the node from scratch
> 
> Hmm, curious, how do you know Longhorn writes everything thing from scratch?

Because longhorn needs 2.5 gigabit on network for 20 minutes so ~375 GB

**Comment by Syntax3rror404** [comment]
I can also take a look to get smartctl working in prom, then we can get 100% sure what longhorn writes to the ssd by monitoring TBW.

I dont know if this is needed because also on grafana I can see longhorn writes heavy amount of data about 20 minutes. 

![Image](https://github.com/user-attachments/assets/8be6960e-19fc-4d1a-bb77-7b2514b407a8)

delta rebuilding is not working... :/

**Comment by derekbit** [comment]
> > > [@derekbit](https://github.com/derekbit) This is the problem, expected is delta but longhorn writes everything on the node from scratch
> > 
> > 
> > Hmm, curious, how do you know Longhorn writes everything thing from scratch?
> 
> Because longhorn needs 2.5 gigabit on network for 20 minutes so ~375 GB

Is it the network profiling of the first rebuilding or the second one?

**Comment by Syntax3rror404** [comment]
And again, after 1.9.0 update

![Image](https://github.com/user-attachments/assets/e8691c6f-0f44-4050-8a30-142ded9da2fd)

![Image](https://github.com/user-attachments/assets/91b8445c-cff8-4882-b56a-2f1c5135edba)

@derekbit The picture is from the third one, because I tried again for testing. Also take a look to the IO monitoring above which indicates 300MBits writes over 20 minutes which assumes a full rebuilding. 

And its again a full rebuild which costs for two nodes 600GB writes on two ssds

![Image](https://github.com/user-attachments/assets/ee99aa92-50bf-4e7a-943f-5e30df2171a6)

Today 2 TBW lost because of longhorn. 

From this you can also have a supportbundle if this helps. Now its from updating longhorn, the other examples are from rebooting the nodes. Everything forces a hard rebuild. 

[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-14T03-52-39Z.zip](https://github.com/user-attachments/files/20735388/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-14T03-52-39Z.zip)

Edit after m3 also w1 gets a hard rebuild

![Image](https://github.com/user-attachments/assets/aa25335c-0743-455e-be7c-fdf8715d1da2)

**Comment by derekbit** [comment]
Thanks @Syntax3rror404. We will investigate the issue to see if it is reproducible in our Lab env.
@mantissahz Please follow up with the issue and help investigate it. Thank you.

**Comment by derekbit** [comment]
Noted that @mantissahz will investigate the issue, clarify if it is expected behavior and improve the official document in https://github.com/longhorn/longhorn/issues/11119.

**Comment by mantissahz** [comment]
Hi @Syntax3rror404,
I tried to reproduce the issue by following steps:
1. Create a new k3s cluster - v1.32.4+k3s1 and install Longhorn with master-head images.
2. Create a deployment with a 300 GiB Longhorn volume.
3. Write 3 GiB data into the volume, and then take a snapshot `snap1` without calculating the checksum.
4. Write 1 GiB data into the volume, and then take a snapshot `snap2` without calculating the checksum.
5. Shutdown the worker node `rancher60-worker1` and wait for the replica on this node to be marked as failed.
7. Boot up the worker node `rancher60-worker1` and wait for replica rebuilding
8. Rebuilding is completed.
And there are not many write operations, and almost all read operations, because the data rebuilding is working on comparing the failed replica data integrity (snapshots and volume-head) with the healthy replica.

Could you try to reproduce the issue with setting the `log-level` setting to `Trace`(that could show the debug log if there is any data synchronized from the remote node to the failed replica node)? And generate the support bundle if write operations are large.

If you want to avoid lengthy rebuild times and large write operations, I suggest enabling both `snapshot-data-integrity-immediate-check-after-snapshot-creation` and `fast-replica-rebuild-enabled` settings, then taking a snapshot to generate the checksum file before shutting down the node.

**Comment by Syntax3rror404** [comment]
@mantissahz 

This is with log-level trace after a reboot of the first worker node. 

For easyer debuging you can focus on the pvc: `pvc-831eaeae-6074-429b-a28e-04b99f932022` which also sits on the worker1.

Support bundle while rebuilding: 

[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-20T23-20-23Z.zip](https://github.com/user-attachments/files/20843904/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-20T23-20-23Z.zip)

Support bundle after rebuilding:

[supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-20T23-26-40Z.zip](https://github.com/user-attachments/files/20843950/supportbundle_120dbce5-78c4-42bf-9c75-eb3be3615bc4_2025-06-20T23-26-40Z.zip)

This time it looks like it uses fast rebuilding 

![Image](https://github.com/user-attachments/assets/9974b216-5d26-48fb-9d24-e121c9d8e408)

**Comment by Syntax3rror404** [comment]
@mantissahz I've tryed again on worker2 which holds the container with the `pvc-831eaeae-6074-429b-a28e-04b99f932022` this time it uses a full rebuild for the hole disk after a reboot. 

Only if you rebooting a node which NOT holding the pod with the pvc, the rebuilding will be delta. Se the test above. 

Also if you rebooting all the nodes at the same time, so simulating a power outage, on 3+ replica pvc only n-1 replicas are healthy and the rest are failed and forced to a full rebuild. 

In short:
1. Rebooting a node with pod and replica on the same node = full rebuild
2. Rebooting a node only with replica = delta rebuild
3. Reboot all nodes gracefully at the same time e.g. `talosctl reboot --nodes <all node ips>` = full rebuild for n-1 replicas

Hope this helpes for reproducing this issue.

**Comment by derekbit** [comment]
@mantissahz is investigating the issue to see if it is expected. If it is an issue or a bug, we might need to address it in the upcoming v1.9.1.

cc @roger-ryao @innobead

**Comment by mantissahz** [comment]
Hi @Syntax3rror404, 
Here is my reproduction result for rebooting the pod node.
Use a deployment as (use sleep to control WRITE operations when the workload is back)
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-app-with-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "36000"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: longhorn-vol-pvc
```
Rebooted four times with or without snapshots, and they are almost READ operations like

![Image](https://github.com/user-attachments/assets/0a25fee1-71e7-40bf-a413-c4ce38f3ceb4)

And if I use the deployment with MySQL as
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: longhorn-vol-pvc
```
There will be some WRITE operations when rebuilding is almost completed.


Could you try to reproduce it in your cluster by steps:
1. Path th `log-level` setting to `Trace`.
2. Create the deployment as in the first example.
3. Enter the pod and write some data in the /data directory.
4. Wait for the data to be synced to the volume.
5. Take a snapshot or not.
6. Reboot the pod node.
7. Wait for the rebuilding to be completed.
8. Check whether the full rebuilding is triggered.
Thank you.
