### ISSUE TITLE
[BUG] Volume expansion fails with "unsupported disk encryption format ext4"

### ISSUE THREAD

**Issue by davidfrickert** [longhorn/longhorn#11120]
### Describe the Bug

Unrecoverable error from attempting a volume expansion from 300Gi to 500Gi on an encrypted volume:

```
7h46m (x8759 over 9h)       Warning   FailedMount              Pod/nextcloud-memories-govod-7dd7868486-jpq7n         MountVolume.Setup failed while expanding volume for volume "pvc-4f2cfef5-8dc4-4d4f-856a-b60ad2feb22d" : Expander.NodeExpand failed to expand the volume rpc error: code = InvalidArgument desc = failed to expand shared volume pvc-4f2cfef5-8dc4-4d4f-856a-b60ad2feb22d: rpc error: code = InvalidArgument desc = unsupported disk encryption format ext4
```

Unsure why this happened as volume expansion worked fine in previous longhorn releases.

Solution to bypass this error which is not ideal is to clone the volume and ignore the old one.

### To Reproduce

Not sure. The volume was created in a previous longhorn version and resize attempt mentioned was in 1.9.0 (currently installed) if that matters.

### Expected Behavior

Volume is expanded correctly to new size.

### Support Bundle for Troubleshooting

Will send by e-mail with issue ID

### Environment

- Longhorn version: 1.9.0
- Impacted volume (PV): pvc-4f2cfef5-8dc4-4d4f-856a-b60ad2feb22d
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.33.1+k3s1
  - Number of control plane nodes in the cluster:  3
  - Number of worker nodes in the cluster: 1
- Node config
  - OS type and version: varies, mostly fedora 41/42
  - Kernel version: varies
  - CPU per node: varies
  - Memory per node: varies
  - Disk type (e.g. SSD/NVMe/HDD): SSD
  - Network bandwidth between the nodes (Gbps): 1
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 30+

**Comment by davidfrickert** [comment]
support bundle sent, mail header: "#11120 - Support bundle"

**Comment by davidfrickert** [comment]
the error seen in the event seems to be from this line of code:
https://github.com/longhorn/longhorn-share-manager/blob/e9c5a6d8d3e881f26b369a047bd0de3d97eaeb4c/pkg/rpc/server.go#L161

**Comment by derekbit** [comment]
cc @mantissahz @COLDTURNIP

**Comment by davidfrickert** [comment]
I've managed to restore the original volume by re-creating the PVC that I had previously deleted and assigned to a clone of the volume, which is now assigned to the original problematic volume again and with no issues.

(I also deleted the share manager pod of said problematic volume before recreating the pvc as for whatever reason the volume kept being attached even though no pvc existed)

**Comment by derekbit** [comment]
cc @mantissahz (community coordinator)

**Comment by derekbit** [comment]
@davidfrickert Could you create a RWX volume and the resize it to see if the issue is always hit?

**Comment by derekbit** [comment]
~~@davidfrickert Could you create a RWX volume and then resize it to see if the issue is always hit?~~
~~cc @mantissahz Please follow up on the issue and help the investigation. If the issue is valid, we can fix it in the upcoming v1.9.1.~~

UPDATE: 
Okay, this is day1 issue. I can reproduce the issue on v1.9.0.
```
time="2025-06-26T16:08:41Z" level=info msg="Device /dev/mapper/pvc-253be323-28a4-44a2-ac13-2e383052bb79 contains filesystem of format ext4" filesystem=/export/pvc-253be323-28a4-44a2-ac13-2e383052bb79 volume=pvc-253be323-28a4-44a2-ac13-2e383052bb79
time="2025-06-26T16:08:41Z" level=error msg="Failed to resize mounted filesystem on volume" error="rpc error: code = InvalidArgument desc = unsupported disk encryption format ext4" filesystem=/export/pvc-253be323-28a4-44a2-ac13-2e383052bb79 volume=pvc-253be323-28a4-44a2-ac13-2e383052bb79
```

**Comment by derekbit** [comment]
It is related to https://github.com/longhorn/longhorn/issues/9902.

@mantissahz Please help collaborate with @COLDTURNIP to

- If possible, add a workaround to mitigate the issue if user is hitting the issue first.
- Fix the issue in v1.10.0, v1.9.1 and v1.8.3

Thanks.

**Comment by COLDTURNIP** [comment]
Reproduce steps:

1. Longhorn v1.9.0
2. create storage class and enable encryption
3. create pod/deployment and a PVC for encrypted RWX volume
4. resize and wait for a while

**Comment by COLDTURNIP** [comment]
There are three issues regarding to encrypted RWX volume expansion:

1. Share manager checks the filesystem on wrong device. It point to the mapped device [mentioned in this ticket](https://github.com/longhorn/longhorn/issues/11120#issuecomment-2974111691).
2. After filesystem check, share manager then [check the encryption status](https://github.com/longhorn/longhorn-share-manager/blob/v1.9.0/pkg/crypto/crypto.go#L118). The device would be considered to be closed since it is `is active and is in use` rather than `is active`, thus it won't resize the block device.

**Comment by derekbit** [comment]
@mantissahz @COLDTURNIP 

Could you help clarify
- Will the data be lost after hitting the issue?
- Any mitigation to bring the problematic volume back to the normal state after user hits the issue

**Comment by derekbit** [comment]
> After filesystem check, share manager then [check the encryption status](https://github.com/longhorn/longhorn-share-manager/blob/v1.9.0/pkg/crypto/crypto.go#L118). The device would be considered to be closed since it is is active and is in use rather than is active, thus it won't resize the block device.

@COLDTURNIP What does `in use` mean here? Does it mean the original impl is problematic? 
https://github.com/longhorn/longhorn-share-manager/blob/v1.9.0/pkg/crypto/crypto.go#L118-L121

**Comment by COLDTURNIP** [comment]
> > After filesystem check, share manager then [check the encryption status](https://github.com/longhorn/longhorn-share-manager/blob/v1.9.0/pkg/crypto/crypto.go#L118). The device would be considered to be closed since it is is active and is in use rather than is active, thus it won't resize the block device.
> 
> [@COLDTURNIP](https://github.com/COLDTURNIP) What does `in use` mean here? Does it mean the original impl is problematic? https://github.com/longhorn/longhorn-share-manager/blob/v1.9.0/pkg/crypto/crypto.go#L118-L121

"in use" means the volume is mounted or being read/written. In this case, Ganesha NFS is serving over it.

I think yes, our original implement should not work. In the fix, the checking logic aligns to [RWO volume's](https://github.com/longhorn/longhorn-manager/blob/master/csi/crypto/crypto.go#L241).

**Comment by derekbit** [comment]
> I think yes, our original implement should not work.

Why doesn't the original impl impact the encrypted volume functionality?

**Comment by derekbit** [comment]
@mantissahz @COLDTURNIP 
Please update the mitigation in https://github.com/longhorn/longhorn/issues/11120#issue-3147706271. Thanks.

**Comment by COLDTURNIP** [comment]
## Verification Steps

### Volume attach & detach

Includes both encrypted and non-encrypted volumes.

1. Latest Longhorn with the fix in this story.
1. A secrete for volume encryption
    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
    stringData:
      CRYPTO_KEY_VALUE: "my passphrase"
      CRYPTO_KEY_PROVIDER: "secret"
      CRYPTO_KEY_CIPHER: "aes-xts-plain64"
      CRYPTO_KEY_HASH: "sha256"
      CRYPTO_KEY_SIZE: "256"
      CRYPTO_PBKDF: "argon2i"
    ```
1. An encrypted/non-encrypted storage class. For example to the encrypted one:
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-crypto-global
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      encrypted: "true"
      # global secret that contains the encryption key that will be used for all volumes
      csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
      csi.storage.k8s.io/node-expand-secret-name: "longhorn-crypto"
      csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"
    ```
1. A workload with a 50MB RWX PVC using the defined storage class
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-share
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Mi
      storageClassName: longhorn-crypto-global
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hello-world
      labels:
        app: hello-world
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: hello-world
      template:
        metadata:
          labels:
            app: hello-world
        spec:
          containers:
            - name: hello-world-1
              image: ubuntu:latest
              command: ['sh', '-c', 'while true ; do now=$(date +%s) ; echo $now ; echo $now >>/mnt/data/share/log || echo $now >/mnt/data/share/log ; ls -l /mnt/data/share/log ; sleep 1 ; done']
              volumeMounts:
                - mountPath: /mnt/data/share
                  name: share
            - name: hello-world-2
              image: ubuntu:latest
              command: ['sh', '-c', 'sleep infinity']
              volumeMounts:
                - mountPath: /mnt/data/hello_world_2_share
                  name: share
          volumes:
            - name: share
              persistentVolumeClaim:
                claimName: longhorn-share
    ```
1. Wait for all workload pods ready. `kubectl logs -f` and the workload will keep writing logs to the volume every second.
1. The volume state should be `attached`
1. Check the logs of the share manager pod. There's no error during attaching.
1. Delete the workload deployment and wait (<5min). The encrypted/non-encrypted volume should be `detached` without any error. The `sharemanager` CR should end with `stopped` state.

### Live expansion

Includes both encrypted and non-encrypted volumes.

1. Latest Longhorn with the fix in this story.
1. A secrete for volume encryption (see above)
1. An encrypted/non-encrypted storage class. (see above)
1. A workload with a 50MB RWX PVC using the defined storage class. (see above)
1. Wait for all workload pods ready. `kubectl logs -f` and the workload will keep writing logs to the volume every second.
1. The volume state should be `attached`
1. Expand the volume size from UI to 70MB, then wait for expansion complete (<3min), wait for expansion complete.
1. The workload pods continue work without any error or restart.
1. Check the log of share manager pod, there's no error recorded.
1. Shell into the share manager pod. Check the `/dev/mapper/pvc-xxxxxx` disk size, and it should be resized to 54MB (`desired_size - encryption_header = 70 - 16 = 56MB`)
    ```
    share-manager-pvc-6eb71a23-96d4-4112-a4c5-e0f0a93031f1:/ # fdisk -l | grep /dev/mapper/pvc-6eb71a23-96d4-4112-a4c5-e0f0a93031f1
    Disk /dev/mapper/pvc-6eb71a23-96d4-4112-a4c5-e0f0a93031f1: 54 MiB, 35651584 bytes, 69632 sectors
    ```

**Comment by COLDTURNIP** [comment]
**Question**: Given that the problem is the status mismatch between the underlying device `/dev/longhorn/pvc-...` and the encrypted mapper device `/dev/mapper/pvc-...`, why not offer commands to perform internal volume expansion directly inside the share manager container as a workaround?

**Answer**: The expansion status is maintained in the status of PVC. When the required storage resource spec is change, CSI plugin node server will issue a RPC call, asking the share manager to check the device status and resize. To the issue we're discussing, the PVC status will be stuck:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
...
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "73400320"
  storageClassName: longhorn-crypto-global
  volumeMode: Filesystem
  volumeName: pvc-6eb71a23-96d4-4112-a4c5-e0f0a93031f1
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-01T08:02:39Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
```

Hence we still need a way to correct the PVC even after fixing the size of mapper device.
