### ISSUE TITLE
[BUG] When evicting a replica to another drive on the same node: "sync file list shouldn't contain volume head"

### ISSUE THREAD

**Issue by Arno500** [longhorn/longhorn#11146]
### Describe the Bug

After adding another drive on the same node, and enabling the eviction on the older drive, some PVCs cannot be moved, and I receive the following error:
```
Failed rebuilding replica with Address 10.244.0.53:17911: proxyServer=10.244.0.53:8501 destination=10.244.0.53:17810: failed to add replica tcp://10.244.0.53:17911 for volume: rpc error: code = Unknown desc = sync file list shouldn't contain volume head
```

### To Reproduce

1. Add a new path/drive on the node
2. Enable scheduling on it
3. Enable eviction and disable scheduling on the older path/drive
4. Wait for volumes to not be able to be moved

### Expected Behavior

All volumes should be moved successfully to the new path. Or at least a suggestion about an action to take in this case is given.

### Support Bundle for Troubleshooting

(will upload now)

### Environment

- Longhorn version: 1.9.0
- Impacted volume (PV): `pvc-088ff164-c4e0-448b-a140-a96c8d39c217`
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k0s
  - Number of control plane nodes in the cluster: 1
  - Number of worker nodes in the cluster: 1
- Node config
  - OS type and version: Fedora 42
  - Kernel version: 6.14.11
  - CPU per node: 16
  - Memory per node: 32GB
  - Disk type (e.g. SSD/NVMe/HDD): New path: SAS SSD, old path: SAS HDDs
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
- Number of Longhorn volumes in the cluster: 18

### Additional context

Some volumes successfully moved without any hiccups, I do not know why some cannot.

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by derekbit** [comment]
Weird. I found the volume-head of the problematic volume doesn't have parent `pvc-3e483c0f-64d1-4f80-9fe6-acc689918c37`

```
    snapshots:
      c-2135sq-1f0160af-6bd8-4c7f-83cf-411d3ba7a30a:
        children:
          c-2135sq-a2a2b78c-0953-47a0-a1e5-ec0fd40aacab: true
        created: "2025-06-19T02:01:51Z"
        labels:
          RecurringJob: c-2135sq
        name: c-2135sq-1f0160af-6bd8-4c7f-83cf-411d3ba7a30a
        parent: c-lvwhsu-ae726d08-18f2-443b-b8e8-6c6d7e3c0f11
        removed: false
        size: "34066432"
        usercreated: true
      c-2135sq-2dc8cd69-4cbb-417c-9782-b46de05a82f8:
        children:
          c-lvwhsu-ae726d08-18f2-443b-b8e8-6c6d7e3c0f11: true
        created: "2025-06-15T02:01:13Z"
        labels:
          RecurringJob: c-2135sq
        name: c-2135sq-2dc8cd69-4cbb-417c-9782-b46de05a82f8
        parent: "null"
        removed: false
        size: "228425728"
        usercreated: true
      c-2135sq-a2a2b78c-0953-47a0-a1e5-ec0fd40aacab:
        children:
          ed7253e0-3a91-42c8-9d64-6aa20ed992e9: true
        created: "2025-06-20T02:00:40Z"
        labels:
          RecurringJob: c-2135sq
        name: c-2135sq-a2a2b78c-0953-47a0-a1e5-ec0fd40aacab
        parent: c-2135sq-1f0160af-6bd8-4c7f-83cf-411d3ba7a30a
        removed: false
        size: "18116608"
        usercreated: true
      c-lvwhsu-ae726d08-18f2-443b-b8e8-6c6d7e3c0f11:
        children:
          c-2135sq-1f0160af-6bd8-4c7f-83cf-411d3ba7a30a: true
        created: "2025-06-17T02:59:22Z"
        labels:
          RecurringJob: c-lvwhsu
        name: c-lvwhsu-ae726d08-18f2-443b-b8e8-6c6d7e3c0f11
        parent: c-2135sq-2dc8cd69-4cbb-417c-9782-b46de05a82f8
        removed: false
        size: "38559744"
        usercreated: true
      ed7253e0-3a91-42c8-9d64-6aa20ed992e9:
        children:
          volume-head: true
        created: "2025-06-21T13:38:25Z"
        labels: {}
        name: ed7253e0-3a91-42c8-9d64-6aa20ed992e9
        parent: c-2135sq-a2a2b78c-0953-47a0-a1e5-ec0fd40aacab
        removed: true
        size: "22151168"
        usercreated: false
      volume-head:
        children: {}
        created: "2024-12-09T00:55:38Z"
        labels: {}
        name: volume-head
        parent: "null"
        removed: false
        size: "193163264"
        usercreated: false
```
