### ISSUE TITLE
[IMPROVEMENT] Improve the logging when detecting multiple backup volumes of the same volume on the same backup target

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#11152]
### Is your improvement request related to a feature? Please describe (👍 if you like this request)

Right now when there are multiple backup volumes of the same volume on the same backup target, we silently ignore the error, return nil, and abort the volume syncing: https://github.com/longhorn/longhorn-manager/blob/7b9d2aa08a572b2b8bce35b3ff0e90dfaa1b0eaf/controller/volume_controller.go#L530-L532

User would have no idea of why the volume is stuck. 

### Describe the solution you'd like

Add log or return err directly instead of silent it

**Comment by shuo-wu** [comment]
Notice that this issue can cause **volumes to become stuck in attaching** or other unusual states. It's not only about logging-related issues.

**Comment by derekbit** [comment]
> Notice that this issue can cause **volumes to become stuck in attaching** or other unusual states. It's not only about logging-related issues.

@shuo-wu Is it related to https://github.com/longhorn/longhorn/issues/11154?

**Comment by shuo-wu** [comment]
Not sure. Maybe we can reproduce it by intentionally creating an invalid BackupVolume CR for an attaching volume. If this reproducing method is valid, then we can say it's not related to https://github.com/longhorn/longhorn/issues/11154

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by shuo-wu** [comment]
OK. The idea works. 

Here is the concrete reproducing step:
1. Set up a test backup target
2. Create and attach a volume `vol`
3. Directly create an empty backup for `vol`
4. Detach `vol`
5. Re-attach `vol` (via UI). **Before** the volume being state `attached`, **immediately** create an invalid BackupVolume:
  ```
  echo "
  apiVersion: longhorn.io/v1beta2
  kind: BackupVolume
  metadata:
    labels:
      backup-target: default
      backup-volume: vol
    finalizers:
    - longhorn.io
    name: vol-invalid
    namespace: longhorn-system
  spec:
    backupTargetName: "null"
    volumeName: "null"
  " | kubectl apply -f -
  ```
6. Make the backup target invalid (e.g., remove the secret value for the backup target)

cc @derekbit

**Comment by PhanLe1010** [comment]
I feel like this is a buggy state that might be OK for Longhorn to stop syncing the volume and notify the user. Just like if there are multiple engines, Longhorn stop syncing the volume and notify the user.
However, I am also ok with @shuo-wu's proposal to make it so that Longhorn continue to sync the volume even if we hit this buggy expected state.


The more difficult question would be why there are multiple backup volume CRs of the same volume on the same backup target in the first place. That would be the ticket https://github.com/longhorn/longhorn/issues/11154 Which might need some helps from @mantissahz

**Comment by shuo-wu** [comment]
I just added this missing step:

> 6. Make the backup target invalid (e.g., remove the secret value for the backup target)


It seems that the invalid BackupVolume CR can be cleaned up automatically during the sync-up with the backup target

**Comment by innobead** [comment]
P0 and should regard this as a bug instead of improvemenet.

**Comment by PhanLe1010** [comment]
Hello @shuo-wu @derekbit @mantissahz 

With the PR https://github.com/longhorn/longhorn-manager/pull/3893/files already trying to clean up duplicated backupvolume CR, I think it is best to simply return err here and retry later. The douplicated backup volume CR would be cleaned up and the normal volume sync follow would happen. WDYT?

**Comment by derekbit** [comment]
Hello @PhanLe1010 
Could you help update the pre-check list and move it Ready For Testing? Thank you.

**Comment by PhanLe1010** [comment]
Test plan:

1. Flow the step at https://github.com/longhorn/longhorn/issues/11152#issuecomment-2998440873
1. We should be able to see the log `failed to get backup volume ... datastore: found more than one backup volume with backup target` in one of longhorn-manager pods. This error were silent before which make it difficult for debugging

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/115f8c18b47339e544c3d0b33cd75bf25a0e52a7) with test [steps](https://github.com/longhorn/longhorn/issues/11152#issuecomment-3046890890)

logs related  to `found more than one backup volume with backup target` appears in longhorn-manager log
```
time="2025-07-09T02:48:31Z" level=error msg="Failed to sync Longhorn volume" func=controller.handleReconcileErrorLogging file="utils.go:79" Volume=longhorn-system/vol controller=longhorn-volume error="failed to sync longhorn-system/vol: failed to get backup volume vol for backup target default and volume vol: datastore: found more than one backup volume with backup target default and volume vol" node=ip-172-31-38-131
E0709 02:48:31.872787       1 volume_controller.go:254] "Unhandled Error" err="failed to sync longhorn-system/vol: failed to get backup volume vol for backup target default and volume vol: datastore: found more than one backup volume with backup target default and volume vol" logger="UnhandledError"
```

Note: I am using below in test step 1 to make volume stuck attaching
```
echo "
apiVersion: longhorn.io/v1beta2
kind: BackupVolume
metadata:
  labels:
    backup-target: default
    backup-volume: vol
  finalizers:
  - longhorn.io
  name: vol-invalid
  namespace: longhorn-system
spec:
  backupTargetName: "default"
  volumeName: "vol"
" | kubectl apply -f -
```
