### ISSUE TITLE
[BUG] Can't upgrade 0.7.0 to 0.8.0 in Rancher, something with CRDs

### ISSUE THREAD

**Issue by cyboman32** [longhorn/longhorn#1115]
Trying to upgrade Longhorn 0.7.0 to 0.8.0

Having a message:
Failed to install app longhorn-system. Error: UPGRADE FAILED: kind CustomResourceDefinition with the name "settings.longhorn.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

Longhorn 0.7.0 was Installed in Rancher 2.3.5/k8s 1.17.2 as App (using internal UI for helm charts). Longhorn works very well.

Seems related to https://github.com/longhorn/longhorn/issues/900
Seen this [doc](https://github.com/longhorn/longhorn/blob/master/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-kind-customresourcedefinition-with-the-name-xxx-already-exists-in-the-cluster-and-wasnt-defined-in-the-previous-release), but on small test cluster this effectively removed all volumes, maybe this doc/script need an update for 0.7.0->0.8.0 upgrade

Any advice?

**Comment by yasker** [comment]
@cyboman32 Are you using Rancher App to upgrade from v0.7.0 to v0.8.0? Or you're using the helm chart directly through internal UI? If it's latter, you're using Helm chart from Rancher Apps or from `longhorn/longhorn` repo? Have you modified the default storage class settings?

That document is only written for v0.6.2 to v0.7.0. We didn't expect to see this issue during v0.7.0 to v0.8.0.

**Comment by cyboman32** [comment]
@yasker Yes, I am trying to upgrade longhorn via Rancher Apps web UI. Initially longhorn was installing using those web UI so I am upgrading in it.

Default `longhorn` storage class wasn't touched at all, we just added few of our own like this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: longhorn-retain1
provisioner: driver.longhorn.io
parameters:
    numberOfReplicas: "2"
    staleReplicaTimeout: "30"
reclaimPolicy: Retain
```
