### ISSUE TITLE
[BUG][DOC] OpenShift documentation

### ISSUE THREAD

**Issue by mlacko64** [longhorn/longhorn#11174]
### Describe the Bug

Hello,
OpenShift documentation [here](https://github.com/longhorn/longhorn/blob/master/chart/ocp-readme.md#example-valuesyaml) contain following entry (not working):

```
openshift:
  oauthProxy:
    repository: quay.io/openshift/origin-oauth-proxy
    tag: 4.15  # Use Your OCP/OKD 4.X Version, Current Stable is 4.15
```

Installation will fail with error:
```
Error: INSTALLATION FAILED: 1 error occurred:
* Deployment.apps "longhorn-ui" is invalid: spec.template.spec.containers[0].image: Required value
```

Correct entry should be (missing `image` on first level):

```
image:
  openshift:
    oauthProxy:
      repository: quay.io/openshift/origin-oauth-proxy
      tag: 4.18
```

### To Reproduce

Simply follow mentioned documentation to install on OpenShift cluster

### Expected Behavior

Installation will be successful.

### Support Bundle for Troubleshooting

N/A

### Environment

- Longhorn version: 1.9.0
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: OpenShift 4.18
  - Number of control plane nodes in the cluster: 3
  - Number of worker nodes in the cluster: 8
- Node config
  - OS type and version: Red Hat Enterprise Linux CoreOS 418.94.202506030254-0
  - Kernel version: 5.14.0-427.72.1.el9_4.x86_64
  - CPU per node: 4
  - Memory per node: 16GB
  - Disk type (e.g. SSD/NVMe/HDD): VM disk
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V
- Number of Longhorn volumes in the cluster:
