### ISSUE TITLE
[FEATURE] Set up recurring jobs from the helm chart

### ISSUE THREAD

**Issue by anouarchattouna** [longhorn/longhorn#1129]
**Is your feature request related to a problem? Please describe.**

I would like to install the helm chart enabling recurring jobs 

**Describe the solution you'd like**

Based on how to [Set up recurring jobs using StorageClass](https://github.com/longhorn/longhorn/blob/c91680aa56beedb60c751163194ec5a26177615e/docs/snapshot-backup.md#set-up-recurring-jobs-using-storageclass), be able to use values for `reccurringJobs` parameter from the [chart/templates/storageclass.yaml](https://raw.githubusercontent.com/longhorn/longhorn/master/chart/templates/storageclass.yaml)

**Describe alternatives you've considered**
```yml
parameters:
  numberOfReplicas: "{{ .Values.persistence.defaultClassReplicaCount }}"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
  {{- if .Values.recurringJobs.enable }}
  recurringJobs: "{{ .Values.recurringJobs.jobsList }}"
  {{- end }}
```

**Additional context**
Same goes for `fromBackup` parameter BTW
