### ISSUE TITLE
[FEATURE] UI: Add fstype option when creating a PV for volume

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1135]
**Is your feature request related to a problem? Please describe.**
longhorn/longhorn#994

**Describe the solution you'd like**
User should be able to specify fstype when creating a PV using UI.

**Describe alternatives you've considered**
N/A

**Additional context**
Per [CSIPersistentVolumeSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#csipersistentvolumesource-v1-core) spec, we should be able to support ext4, xfs, nfs

**Comment by yasker** [comment]
Not `nfs`. Provide an input box for user. Can default to `ext4`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
- Create a volume
- Create a PV with xfs filesystem for the volume
- Create PVC for the volume
- Deploy workload to use the volume
```
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-xfs
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: centos:7
    command: ["/bin/sh", "-c", "while true; do :; done"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName:  <VOLUME_PVC_NAME>
```
- Pod should be running and able to access volume in `/data`  **(PASSED)**
