### ISSUE TITLE
[BUG] Volume expansion should be disabled for volumes dynamically provisioned by StorageClass that disabled VolumeExpansion

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1178]
**Describe the bug**
For volumes dynamically provisioned by a new storageclass that doesn't support volume expansion, Volume Expansion should be not allowed.
**To Reproduce**

1. Create a new storageclass `longhorn-sc-2`, set `allowVolumeExpansion` to False
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: false
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
```
2. Create a simple PVC using the new StorageClass
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-simple-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc-2
  resources:
    requests:
      storage: 1Gi
```
3. In Longhorn UI, Expand the Volume.

**Expected behavior**
- User should not be able to expand the volume dynamically provisioned by StorageClass with disabled VolumeExpansion
- UI should inform the user the reason why Volume expansion is disabled.

**Log**
N/A

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04 

**Additional context**
After expanding the volume from longhorn, and expanding PV size 
when trying to expand PVC size, the following error occurs
```
error: persistentvolumeclaims "longhorn-simple-pvc" could not be patched: persistentvolumeclaims "longhorn-simple-pvc" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```
