### ISSUE TITLE
[FEATURE] Prometheus support

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#1180]
**Is your feature request related to a problem? Please describe.**
I would like to monitor the longhorn stuff using Prometheus.

**Describe the solution you'd like**
Expose metrics and provide a servicemonitor in the Helm Chart.

**Describe alternatives you've considered**
The UI already have a bunch of graphs and health information but you cannot get alerted in case of problems.

**Additional context**

**Comment by timmy59100** [comment]
@yasker For the moment how to you recommend that we monitor the volume usages at the moment so they don't get full.

**Comment by tabnul** [comment]
> @yasker For the moment how to you recommend that we monitor the volume usages at the moment so they don't get full.

Also very interested in how to do this..
There are always ways such as querying the api via blackbox exporter.. but thats kind of ugly.

**Comment by abuisine** [comment]
Happy to give it a try as soon as it is available in a rc

**Comment by strowi** [comment]
Also looking forward to this!
With rook we had the vomlume usage show up within kubernetes as `kubelet_volume_stats_used_bytes` / `kubelet_volume_stats_capacity_bytes`.
Which i guess depends on the way the storage-driver integrates with kubernetes.

**Comment by tomdoherty** [comment]
Very interested in access to `kubelet_volume_stats_available_bytes` to allow Strimzi dashboards to work without modification

**Comment by PhanLe1010** [comment]
The code for feature will be divided into 3 parts corresponding to 3 PRs: 

1. Part 1 contains metrics:
     1. longhorn_volume_capacity_bytes
     1. longhorn_volume_actual_size_bytes
     1. longhorn_node_stats_node_status

2. Part 2 contains metrics:
    1. longhorn_instance_manager_requests_cpu_millicpu
    1. longhorn_instance_manager_requests_memory_bytes
    1. longhorn_instance_manager_usage_cpu_millicpu
    1. longhorn_instance_manager_usage_memory_bytes
    1. longhorn_manager_usage_cpu_millicpu
    1. longhorn_manager_usage_memory_bytes

3. Part 3 contains the following metrics:
    1. longhorn_disk_capacity_bytes
    1. longhorn_disk_usage_bytes
    1. longhorn_node_capacity_bytes
    1. longhorn_node_usage_bytes

**Comment by PhanLe1010** [comment]
Basic verifying/testing steps for QA:
1. Install the Prometheus Operator (include a role and service account for it). For example:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - servicemonitors
      - prometheusrules
      - podmonitors
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-operator
  name: prometheus-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator
  template:
    metadata:
      labels:
        app: prometheus-operator
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
          image: quay.io/coreos/prometheus-operator:v0.36.0
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

1. Install a Service Monitor pointing to `longhon-backend` service by selecting `app: longhorn-manager` label. For example:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-backend
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
```

1. Install Prometheus (include a role and service account for it). Include the above `service monitor` in the Prometheus's config. Expose to the Prometheus instance to outside using a service of type NodePort. For example:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/federate"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
            team: backend
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  ports:
    - port: 9090
  selector:
    prometheus: prometheus
```

1. Find the `prometheus` service and access Prometheus web UI using the nodeID and the port .
1. Verify that Prometheus successfully dicorvers all longhorn manager targets.
1. Verify Longhorn correctly exposes the [above metrics](https://github.com/longhorn/longhorn/issues/1180#issuecomment-693003131)
1. Try to deploy workload using Longhorn volume into the cluster. Verify that there is no abnomal data. e.g: volume capacity is 0,  cpu usage is over 4000 milicpu, etc ...
