### ISSUE TITLE
[BUG] - Longhorn should be able to handle multiple storage classes at a time

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1190]
**Describe the bug**
Longhorn should be able to handle multiple storage classes at a time

**To Reproduce**

- Deploy longhorn as an app in Rancher
- Storage class "Longhorn" with Provisioner: "driver.longhorn.io" is created in the cluster.
- Using kubectl, create multiple storage classes with Provisioner: "driver.longhorn.io".
- Storageclass.yaml

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test-new
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
```
- Longhorn should be able to create volumes from both these storage classes at a time.
- Currently only the default storage class "longhorn" is used by the Longhorn app.

**Expected behavior**
Longhorn should be able to create volumes from both these storage classes at a time.

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO Cluster
