### ISSUE TITLE
Interaction with Kubernetes Drain and Cordon operation

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1278]
We need to consider what we should do with the Kubernetes drain and cordon node for maintenance. 

Also, when Kubernetes is doing recommended upgrade, each node will be drained. Need to take care of that scenario as well.

**Comment by yasker** [comment]
What cordon did is add changes to the node spec, including a taint and `unscheduable=true`.

```
spec:
  podCIDR: 10.42.1.0/24
  podCIDRs:
  - 10.42.1.0/24
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2020-05-04T06:15:48Z"
  unschedulable: true
```
