### ISSUE TITLE
[BUG] Set Backup Target has an incorrect example manifest

### ISSUE THREAD

**Issue by Mercwri** [longhorn/longhorn#1292]
Running this on K8s v1.18.2

The minio-secret example manifest has the wrong ket used which will result in the values not being read by longhorn.

Current:
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UuZGVmYXVsdDo5MDAw # http://minio-service.default:9000
```

Changing the key from data to stringData allowed longhorn to read the values and successfully read and create backups.
