### ISSUE TITLE
[BUG]  Storageclass does not work when it has the parameter frontend:iscsi

### ISSUE THREAD

**Issue by antmoveh** [longhorn/longhorn#1403]
**Describe the bug**
- StorageClass.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  frontend: "iscsi"
  standby: "true"
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
#  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},
#                   {"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1,
#                    "labels": {"interval":"2m"}}]'
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```
- But it's still a Block Device
![x](https://user-images.githubusercontent.com/26082792/82853528-9aa96880-9f38-11ea-8af9-0a33a143b129.png)

- I found this bug
- You're not dealing with parameters like frontend standy
- Please repair it
https://github.com/longhorn/longhorn-manager/blob/master/csi/util.go
```
func getVolumeOptions(volOptions map[string]string) (*longhornclient.Volume, error) {
	vol := &longhornclient.Volume{}

	if staleReplicaTimeout, ok := volOptions["staleReplicaTimeout"]; ok {
		srt, err := strconv.Atoi(staleReplicaTimeout)
		if err != nil {
			return nil, errors.Wrap(err, "Invalid parameter staleReplicaTimeout")
		}
		vol.StaleReplicaTimeout = int64(srt)
	}
	if vol.StaleReplicaTimeout <= 0 {
		vol.StaleReplicaTimeout = defaultStaleReplicaTimeout
	}

	if numberOfReplicas, ok := volOptions["numberOfReplicas"]; ok {
		nor, err := strconv.Atoi(numberOfReplicas)
		if err != nil || nor < 0 {
			return nil, errors.Wrap(err, "Invalid parameter numberOfReplicas")
		}
		vol.NumberOfReplicas = int64(nor)
	}

	if fromBackup, ok := volOptions["fromBackup"]; ok {
		vol.FromBackup = fromBackup
	}

	if baseImage, ok := volOptions["baseImage"]; ok {
		vol.BaseImage = baseImage
	}

	if jsonRecurringJobs, ok := volOptions["recurringJobs"]; ok {
		recurringJobs, err := parseJSONRecurringJobs(jsonRecurringJobs)
		if err != nil {
			return nil, errors.Wrap(err, "Invalid parameter recurringJobs")
		}
		vol.RecurringJobs = recurringJobs
	}

	if diskSelector, ok := volOptions["diskSelector"]; ok {
		vol.DiskSelector = strings.Split(diskSelector, ",")
	}

	if nodeSelector, ok := volOptions["nodeSelector"]; ok {
		vol.NodeSelector = strings.Split(nodeSelector, ",")
	}

	return vol, nil
}
```

**Comment by yasker** [comment]
Hi @antmoveh 

Storage Class doesn't support iscsi as frontend. Kubernetes should always use block device as the front-end. Our CSI driver wasn't designed to work with iscsi front-end. What's your use case for exposing the iscsi device to Kubernetes?

**Comment by antmoveh** [comment]
> Hi @antmoveh
> 
> Storage Class doesn't support iscsi as frontend. Kubernetes should always use block device as the front-end. Our CSI driver wasn't designed to work with iscsi front-end. What's your use case for exposing the iscsi device to Kubernetes?

> Now there's a problem with Block devices，
pvc.yaml
```

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```
- When deployment replicas=2, the following error is reported when mounting the PVC
![x1](https://user-images.githubusercontent.com/26082792/82864683-abb5a200-9f57-11ea-84df-f448c61bd7cd.png)
![x2](https://user-images.githubusercontent.com/26082792/82864685-ac4e3880-9f57-11ea-9c0d-bc52fb31b6ec.png)

- Unable to create pv in ReadWriteMany mode
pvc2.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```

![x3](https://user-images.githubusercontent.com/26082792/82864727-cc7df780-9f57-11ea-9535-373fb7eccf10.png)

- I want to know when the deployment replicas>1, how should it be mounted
