### ISSUE TITLE
[BUG] Longhorn app fails to come up on 'pod security policy' enabled cluster.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1459]
**Describe the bug**
Longhorn pods fail to come up healthy on a 'pod security policy' enabled cluster.

**To Reproduce**
1. Create a cluster with pod security policy enabled as 'restricted'.
2. Deploy longhorn app in the cluster
3. Longhorn pods fail to come up healthy.

**Log**
```
$kubectl get pod -n longhorn-system
NAME                                        READY   STATUS             RESTARTS   AGE
longhorn-driver-deployer-86f4565895-r72z2   0/1     Init:0/1           0          4m13s
longhorn-ui-5d4f878cdf-twkpr                0/1     CrashLoopBackOff   5          4m13s
$ kubectl logs longhorn-ui-5d4f878cdf-twkpr -n longhorn-system
2020/06/05 17:54:35 [warn] 1#1: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
2020/06/05 17:54:35 [emerg] 1#1: chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
nginx: [emerg] chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
```

**Environment:**
 - Longhorn version: master- 06-05-2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: Ubuntu 18.04

**Additional information**
There is a work around currently, we can deploy below PSPs overriding the default one which is applicable to longhorn-system namespace only. With these additional PSP, longhorn works fine.
```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: longhorn-default-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
spec:
  privileged: false
  defaultAllowPrivilegeEscalation: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: longhorn-default-psp
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - longhorn-default-psp
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: longhorn-default-psp-binding
roleRef:
  kind: ClusterRole
  name: longhorn-default-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: longhorn-system
```

```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: longhorn-privileged-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-privileged-psp
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - longhorn-privileged-psp
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-privileged-psp-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-privileged-psp
subjects:
- kind: ServiceAccount
  name: longhorn-service-account
  namespace: longhorn-system
```
Refer https://github.com/longhorn/longhorn/pull/1281
