### ISSUE TITLE
[Question] How to create PVC from snapshot or backup with yalm file?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1486]
is it possible to  create new PVC from snapshot or backup with yalm file?

**Comment by meldafrawi** [comment]
You can create StorageClass, and provide backup URL to `fromBackup` parameter, then create a PVC from that StorageClass,  new Longhorn volume gets created, and will restore data from the specified backup

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: <STORAGE_CALSS_NAME>
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: "<BACKUP_URL>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <PVC_NAME>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <STORAGE_CALSS_NAME>
  resources:
    requests:
      storage: <PVC_SIZE>
```
