### ISSUE TITLE
[BUG] kubectl get pvc shows previews CAPACITY value after expand volume by UI

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1497]
**Describe the bug**
kubectl get pvc shows previews CAPACITY value after expand volume by UI

**To Reproduce**
1.  pod_with_pvc1.yaml 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
```
2.  kubectl get pvc
```
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
longhorn-volv-pvc   Bound    pvc-69d31dc1-d59a-48ad-8cfa-def9e1b141ce   5Gi        RWO            longhorn       8m40s
```
3. expand volume by UI from 5Gi to 8Gi
4.  kubectl get pvc
```
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
longhorn-volv-pvc   Bound    pvc-69d31dc1-d59a-48ad-8cfa-def9e1b141ce   5Gi        RWO            longhorn       8m40s
```
 CAPACITY value is still 5Gi, NOT 8Gi

**Expected behavior**
kubectl get pvc should show new  CAPACITY value of 8Gi after expand volume by UI from 5Gi to 8Gi.

**Environment:**
 - Longhorn version:
Longhorn 1.0.0

 - Kubernetes version:
Kubernetes v1.15.6

 - Node OS type and version:
CentOS 7.6 64bit
