### ISSUE TITLE
[BUG] K3S with error rpc error: code = Internal desc = Action [attach] not available

### ISSUE THREAD

**Issue by laeo** [longhorn/longhorn#1551]
**Describe the bug**
Sorry i am newbie to k3s and longhorn, and sorry again for my bad English.
I had following the document to install Longhorn on my k3s cluster with 1 master node and 1 worker.
Then create gitea deployment by using the following YAML

```
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  template:
    metadata:
      name: gitea
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.12
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/data"
            name: "data"
        ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
          - containerPort: 3000
            name: http
            protocol: TCP
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      volumes:
      - name: "data"
        persistentVolumeClaim:
          claimName: gitea-data
  selector:
    matchLabels:
      app: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-web
  namespace: gitea
  labels:
    app: gitea-web
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    app: gitea-ssh
spec:
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh
  selector:
    app: gitea
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
  annotations:
    cert-manager.io/cluster-issuer: "acme-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - gitus.in
    secretName: gitea-web
  rules:
  - host: xxx.example.com
    http:
      paths:
      - backend:
          serviceName: gitea-web
          servicePort: 80
```

But pod stuck in `ContainerCreating` status.

**To Reproduce**
1. Create VLAN by wireguard on CentOS 7 with kernal version 5.7.
2. Install k3s with specified VIP and --flannel-iface.
3. Install Longhorn 1.0 as document detailed.
4. Deploy gitea.

**Expected behavior**
PV mounted in Pod as normal.

**Log**
`kubectl -n gitea describe pod`

```
Name:           gitea-d89bf4b95-6qrqv
Namespace:      gitea
Priority:       0
Node:           izj6cd9x6l987sieuxvhrwz/10.20.30.2
Start Time:     Mon, 06 Jul 2020 05:38:21 +0000
Labels:         app=gitea
                pod-template-hash=d89bf4b95
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/gitea-d89bf4b95
Containers:
  gitea:
    Container ID:
    Image:          gitea/gitea:1.12
    Image ID:
    Ports:          22/TCP, 3000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fn69m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  gitea-data
    ReadOnly:   false
  default-token-fn69m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fn69m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age              From                     Message
  ----     ------              ----             ----                     -------
  Warning  FailedScheduling    <unknown>        default-scheduler        running "VolumeBinding" filter plugin for pod "gitea-d89bf4b95-6qrqv": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling    <unknown>        default-scheduler        running "VolumeBinding" filter plugin for pod "gitea-d89bf4b95-6qrqv": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           <unknown>        default-scheduler        Successfully assigned gitea/gitea-d89bf4b95-6qrqv to izj6cd9x6l987sieuxvhrwz
  Warning  FailedAttachVolume  0s (x2 over 1s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-83693576-6378-4714-848c-02e68740476c" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-83693576-6378-4714-848c-02e68740476c volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-83693576-6378-4714-848c-02e68740476c] map[]}]
```

`kubectl -n gitea get pvc`

```
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
gitea-data   Bound    pvc-83693576-6378-4714-848c-02e68740476c   1Gi        RWO            longhorn       2m18s
```

`kubectl -n gitea get pv`

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS   REASON   AGE
pvc-83693576-6378-4714-848c-02e68740476c   1Gi        RWO            Delete           Bound    gitea/gitea-data   longhorn                2m48s
```

`kubectl -n longhorn-system get pod`

```
NAME                                       READY   STATUS    RESTARTS   AGE
longhorn-ui-8486987944-66wjp               1/1     Running   0          101m
instance-manager-e-47df2e30                1/1     Running   0          101m
instance-manager-r-9c1f9a82                1/1     Running   0          101m
engine-image-ei-eee5f438-z7xpl             1/1     Running   0          101m
engine-image-ei-eee5f438-s57sg             1/1     Running   0          101m
instance-manager-e-545b093c                1/1     Running   0          101m
instance-manager-r-2e35103c                1/1     Running   0          100m
longhorn-manager-xt7kd                     1/1     Running   0          101m
longhorn-manager-5nw2l                     1/1     Running   0          101m
longhorn-driver-deployer-cd74cb75b-wrzvl   1/1     Running   0          101m
csi-attacher-5cc849c8dd-8mgt5              1/1     Running   0          100m
csi-attacher-5cc849c8dd-fr945              1/1     Running   0          100m
csi-resizer-686bd4b6d7-686b8               1/1     Running   0          100m
csi-provisioner-74557755-zn6xc             1/1     Running   0          100m
csi-attacher-5cc849c8dd-2m47j              1/1     Running   0          100m
csi-provisioner-74557755-56zw5             1/1     Running   0          100m
csi-provisioner-74557755-kv7gk             1/1     Running   0          100m
longhorn-csi-plugin-dbtmp                  2/2     Running   0          100m
csi-resizer-686bd4b6d7-gjkkz               1/1     Running   0          100m
csi-resizer-686bd4b6d7-758dg               1/1     Running   0          100m
longhorn-csi-plugin-cwrzc                  2/2     Running   0          100m
```

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: v1.18.4+k3s1
 - Node OS type and version:  CentOS 7 Linux with kernel 5.7.6-1.el7.elrepo.x86_64

**Additional context**
