### ISSUE TITLE
[Question] Longhorn-UI on subpath with Traefik 1.7 ingress controller

### ISSUE THREAD

**Issue by riazarbi** [longhorn/longhorn#1554]
Hello, 

Is there a way to server longhorn-UI on a subpath? We work in a corporate environment and cannot use subdomains. 

I am longhorn on bare metal k3s v1.18.4+k3s1 with metallb as a load balancer and traefik v1.7 as an ingress controller. 

This is what my ingress object looks like  - 

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: longhorn-frontend
          servicePort: http

```

This above ingress object routes correctly at the root path. 

If I change the `path` line to 

```
     - path: /longhorn
```
Then this is what happens in my browser debug 

![image](https://user-images.githubusercontent.com/13433911/86909017-c44cd680-c117-11ea-9c57-69a123031bd6.png)

You can compare to my (working) jupyterlab deployment, which also serves from a subpath

![image](https://user-images.githubusercontent.com/13433911/86909158-f2cab180-c117-11ea-8651-dba19cbd2f67.png)

It looks to me that longhorn is redirecting back to the root path after the initial connection - it doesn't know it is sitting at a subpath.

With jupyterhub I had to set the root path in the helm `values.yaml` so that it would know where to redirect. 

But I cannot find any documented place to set the root path in the longhorn docs. I know it should be possible because the longhorn UI sits behind nginx but I wanted to find out if there is a documented method before I go hacking the image.

**Comment by yasker** [comment]
@smallteeths can you take a look?

**Comment by kaiomatico** [comment]
I have the same problem. I am using traefik in conjunction with basic auth to password-protect the longhorn-frontend, but it only works if the path is set to /  
Hope it is an easy fix :)

**Comment by ianvari** [comment]
I have a similar problem #1745 , but in my case I've actually deployed ngnix, I want to deploy other dashboards and expose through the ingress controller and at this point Longhorn UI is taking it over.

**Comment by smallteeths** [comment]
For the time being, this version only supports path: /. The next version will be updated to support any path. @ianvari @andyjeffries @yasker
If it is a test environment, you can try image wangsiye/longhorn-ui:904c756. Ingress needs to be configured correctly, annotations need to add parameters nginx.ingress.kubernetes.io/rewrite-target: /$2
path is set to /xxx(/|$)(.*)

**Comment by smallteeths** [comment]
I'm using the nginx ingress controller, which may not have the same parameters as traefik. I'll try to configure it sometime! @ianvari @riazarbi

**Comment by jackivanov** [comment]
@smallteeths Is there any ETA on this?

**Comment by si458** [comment]
@smallteeths bump on this issue, any update on time scale?
i really didnt want loads of sumdomains just for management side of things,
i would rather a single domain with sub paths

**Comment by si458** [comment]
Hi All,
ive been able to get the UI by editing the deployment for `longhorn-ui`
and setting the image from `longhornio/longhorn-ui:v1.0.2` to `longhornio/longhorn-ui:master`
and also use the following traefik config:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-stripprefix
  namespace: longhorn-system
spec:
  stripPrefix:
    prefixes:
      - /longhorn
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: longhorn-http
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-test-stripprefix@kubernetescrd
spec:
  rules:
    - host: kubernetes.myserver.com
      http:
        paths:
          - path: /longhorn/
            backend:
              serviceName: longhorn-frontend
              servicePort: 80
```

**Comment by himslm01** [comment]
Very similar to @riazarbi I'm trying to do the same thing in a test k3s cluster (K8s v1.19.2+k3s1 with Træfik v1.81.1).
Like @riazarbi and @si458 I don't want extra sub-domains.

I have an ugly workaround. I've run an Nginx reverse-proxy service between the Træfik ingress and the longhorn-frontend service with some `sub_filter` and `sub_filter_types` directives.

```
    server {
      listen 80 default_server;
      server_name _;

      location /longhorn-dash/ {
        proxy_pass http://longhorn-frontend/;
        sub_filter "href=\"/" "href=\"/longhorn-dash/";
        sub_filter "src=\"/" "src=\"/longhorn-dash/";
        sub_filter "/v1/nodes" "/longhorn-dash/v1/nodes";
        sub_filter "/v1/settings" "/longhorn-dash/v1/settings";
        sub_filter "/v1/events" "/longhorn-dash/v1/events";
        sub_filter "/v1/engineimages" "/longhorn-dash/v1/engineimages";
        sub_filter "/v1/backupvolumes" "/longhorn-dash/v1/backupvolumes";
        sub_filter "/v1/volumes" "/longhorn-dash/v1/volumes";
        sub_filter_types application/javascript application/json ;
        sub_filter_once off;
      }
    }
```
I have no idea if this is going to work fully, there may be other API end-points I've missed (I don't want to just filter `/v1/` because that might catch text I don't want to filter.

The dashboard nearly works with the above - it just complains that there is an `error listing backups: setting backup-target is empty` - but that's probably nothing to do with this issue.

**Comment by riazarbi** [comment]
@smallteeths will this be in the next release?

**Comment by smallteeths** [comment]
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /longhorn/
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
```

![Jietu20201208-133517](https://user-images.githubusercontent.com/27733391/101444352-4573f800-395a-11eb-8774-603c456c9cde.jpg)

Sorry for the late reply,  v1.1.0 will fix this issue. It should be noted that, The last `/` can't be omitted from the access path. @riazarbi

**Comment by riazarbi** [comment]
Since I opened this issue, I'm just going to close the loop. This does indeed work on 1.1.0. However, on k3s `v1.18.8+k3s1` I had to use the following yaml - 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /longhorn/
        pathType: Prefix
        backend:
          serviceName: longhorn-frontend
          servicePort: http


```

Many thanks to everyone who worked on this, it is really appreciated.

**Comment by YiuTerran** [comment]
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: longhorn-ingress
>   namespace: longhorn-system
>   annotations:
>     kubernetes.io/ingress.class: traefik
>     traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
> spec:
>   rules:
>   - http:
>       paths:
>       - path: /longhorn/
>         pathType: Prefix
>         backend:
>           service:
>             name: longhorn-frontend
>             port:
>               number: 80
> ```
> 

I'm currently using k3s v1.26.5+k3s1 and longhorn v1.4.2, but even with this configuration, I can still only see a blank page. There is no problem with using the root path "/". Any ideas?  @smallteeths

**Comment by smallteeths** [comment]
> ```yaml
> /longhorn/
> ```

Could you please try accessing the /longhorn/ path without discarding the `/`.  @YiuTerran

**Comment by YiuTerran** [comment]
![longhorn](https://github.com/longhorn/longhorn/assets/5930695/a3a0b379-03eb-4825-b34d-7f100e3196af)
@smallteeths just as above pic. All return 200 OK, but page is blank.

**Comment by smallteeths** [comment]
Thank you for your feedback. I have tested it myself, and indeed, the returned JavaScript files are empty. I am currently unsure about the reason behind this. Now there is a workaround by adding the following configuration, which is similar to the nginx.ingress.kubernetes.io/rewrite-target of nginx ingress, to resolve it.

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middleware
  namespace: longhorn-system
spec:
  replacePathRegex:
    regex: "^/longhorn(/|$)(.*)"
    replacement: "/${2}"
```

```
 traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-middleware@kubernetescrd
```


<img width="1216" alt="截屏2023-06-13 下午6 25 56" src="https://github.com/longhorn/longhorn/assets/27733391/c4701b00-2af4-4432-aa5a-5c0bec01fcf3">
