### ISSUE TITLE
[Question] engine-image-ei problems when install longhorn offline

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1557]
kubectl get pods --namespace longhorn-system
NAME                                        READY   STATUS             RESTARTS   AGE
engine-image-ei-eee5f438-j5dws              0/1     ImagePullBackOff   0          8m24s

I have image local load

docker images -a |grep longhorn-engine
longhornio/longhorn-engine                           v1.0.0              0cb443571f5b        5 weeks ago         307MB

I edit longhorn.yalm

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      containers:
      - name: longhorn-manager
        image: longhornio/longhorn-manager:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - longhornio/longhorn-engine:v1.0.0
        - --instance-manager-image
        - longhornio/longhorn-instance-manager:v1_20200514
        - --manager-image
        - longhornio/longhorn-manager:v1.0.0
        - --service-account
        - longhorn-service-account
```

But imagePullPolicy: IfNotPresent do not take effect to longhornio/longhorn-engine:v1.0.0 image,  any advice?
