### ISSUE TITLE
[Question] How to mount longhorn pvc in initContainers?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1611]
```
      initContainers:
      - name: init-data
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["echo", "123", ">", "/data/init.txt"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis2-data-volv-pvc
```

But no such file /data/init.txt after pod startup.
