### ISSUE TITLE
[BUG] volume stuck in Attaching if backup is defined in storageclass

### ISSUE THREAD

**Issue by mattmattox** [longhorn/longhorn#1630]
**Describe the bug**

**To Reproduce**
1. Create storageclass with backup schedule
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    io.cattle.field/appId: longhorn-system
  name: longhorn-backup
parameters:
  baseImage: ""
  fromBackup: ""
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 * * * *", "retain":20},
                   {"name":"backup", "task":"backup", "cron":"0 0 * * *", "retain":20}]'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
2. Deploy PVC https://raw.githubusercontent.com/longhorn/longhorn/master/examples/simple_pvc.yaml (NOTE: Change the storageclass from longhorn to longhorn-backup)
3. Deploy Pod https://raw.githubusercontent.com/longhorn/longhorn/master/examples/simple_pod.yaml

**Expected behavior**
For the volume to attach and not get stuck in Attaching

**Log**
Logs: https://app.box.com/s/boi1doz3u0a67igg7hm9tsh0f23bxtua

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version: v1.18.6
 - Node OS type and version: Ubuntu 18.04.4 LTS   4.15.0-112-generic docker://19.3.12

**Additional context**
You can work around this issue by configuring the backup schedule after the volume is created.
