### ISSUE TITLE
Longhorn can't do volume attach if he uses more than one replication.

### ISSUE THREAD

**Issue by gianmarcomurru** [longhorn/longhorn#1632]
I created two storage classes for longhorns, one uses 1 replica, the other 2:
```
Name:            longhorn1
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"meta.helm.sh/release-name":"longhorn","meta.helm.sh/release-namespace":"longhorn-system","storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"app.kubernetes.io/instance":"longhorn","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"longhorn","app.kubernetes.io/version":"v1.0.1","helm.sh/chart":"longhorn-1.0.1"},"managedFields":[{"apiVersion":"storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:allowVolumeExpansion":{},"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{},"f:storageclass.beta.kubernetes.io/is-default-class":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:helm.sh/chart":{}}},"f:parameters":{".":{},"f:baseImage":{},"f:fromBackup":{},"f:numberOfReplicas":{},"f:staleReplicaTimeout":{}},"f:provisioner":{},"f:reclaimPolicy":{},"f:volumeBindingMode":{}},"manager":"Go-http-client","operation":"Update"}],"name":"longhorn1"},"parameters":{"baseImage":"","fromBackup":"","numberOfReplicas":"1","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
,meta.helm.sh/release-name=longhorn,meta.helm.sh/release-namespace=longhorn-system,storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            baseImage=,fromBackup=,numberOfReplicas=1,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

```
Name:            longhorn2
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"meta.helm.sh/release-name":"longhorn","meta.helm.sh/release-namespace":"longhorn-system","storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"app.kubernetes.io/instance":"longhorn","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"longhorn","app.kubernetes.io/version":"v1.0.1","helm.sh/chart":"longhorn-1.0.1"},"managedFields":[{"apiVersion":"storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:allowVolumeExpansion":{},"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{},"f:storageclass.beta.kubernetes.io/is-default-class":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:helm.sh/chart":{}}},"f:parameters":{".":{},"f:baseImage":{},"f:fromBackup":{},"f:numberOfReplicas":{},"f:staleReplicaTimeout":{}},"f:provisioner":{},"f:reclaimPolicy":{},"f:volumeBindingMode":{}},"manager":"Go-http-client","operation":"Update"}],"name":"longhorn2"},"parameters":{"baseImage":"","fromBackup":"","numberOfReplicas":"2","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
,meta.helm.sh/release-name=longhorn,meta.helm.sh/release-namespace=longhorn-system,storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            baseImage=,fromBackup=,numberOfReplicas=2,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

I tried to create two tests, one using the storageclass longhorn1 and the other longhorn2:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
spec:
  storageClassName: longhorn1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pod
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: test-pv-claim
  containers:
    - name: test-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pv-storage
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2-pv-claim
spec:
  storageClassName: longhorn2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test2-pv-pod
spec:
  volumes:
    - name: test2-pv-storage
      persistentVolumeClaim:
        claimName: test2-pv-claim
  containers:
    - name: test2-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test2-pv-storage
```

When I create the resources, the `test2-pv-pod` pod remains in `ContainerCreating` state with error:
```
Events:
  Type     Reason              Age                    From                        Message
  ----     ------              ----                   ----                        -------
  Warning  FailedScheduling    5m35s (x3 over 5m37s)  default-scheduler           running "VolumeBinding" filter plugin for pod "test2-pv-pod": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           5m33s                  default-scheduler           Successfully assigned longhorn-system/test2-pv-pod to k8swrk02
  Warning  FailedAttachVolume  4m29s (x3 over 5m33s)  attachdetach-controller     AttachVolume.Attach failed for volume "pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1 to k8swrk02: volume pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1 not scheduled, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1?action=attach]
  Warning  FailedAttachVolume  83s (x7 over 5m32s)    attachdetach-controller     AttachVolume.Attach failed for volume "pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1 to k8swrk02: volume pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1 not scheduled] from [http://longhorn-backend:9500/v1/volumes/pvc-da810234-e90a-41fc-a519-3bce3d0cf3b1?action=attach]
  Warning  FailedMount         75s (x2 over 3m30s)    kubelet, k8swrk02  Unable to attach or mount volumes: unmounted volumes=[test2-pv-storage], unattached volumes=[test2-pv-storage default-token-kd8fd]: timed out waiting for the condition
```

The other `test-pv-pod` using the `longhorn1` storage class with a replica is running:
```
Events:
  Type     Reason                  Age                From                        Message
  ----     ------                  ----               ----                        -------
  Warning  FailedScheduling        31s (x2 over 31s)  default-scheduler           running "VolumeBinding" filter plugin for pod "test-pv-pod": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               28s                default-scheduler           Successfully assigned longhorn-system/test-pv-pod to k8swrk01
  Normal   SuccessfulAttachVolume  24s                attachdetach-controller     AttachVolume.Attach succeeded for volume "pvc-bc99ae8f-f7bb-46ab-8ef7-694254e1c01b"
  Warning  FailedMount             20s (x2 over 20s)  kubelet, k8swrk01  MountVolume.SetUp failed for volume "pvc-bc99ae8f-f7bb-46ab-8ef7-694254e1c01b" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume pvc-bc99ae8f-f7bb-46ab-8ef7-694254e1c01b
  Normal   Pulling                 16s                kubelet, k8swrk01  Pulling image "nginx"
  Normal   Pulled                  14s                kubelet, k8swrk01  Successfully pulled image "nginx"
  Normal   Created                 14s                kubelet, k8swrk01  Created container test-pv-container
  Normal   Started                 14s                kubelet, k8swrk01  Started container test-pv-container
```
**Environment:**
 - Longhorn version: v1.0.1
 - Kubernetes version: v1.18.6
 - Node OS type and version: Ubuntu 18.04.4 LTS

**Additional context**
I have two worker node, I expect it to work with two replicas.
