### ISSUE TITLE
[BUG] Volume mount fails with RPC "InvalidArgument desc = There is no block device frontend for volume"

### ISSUE THREAD

**Issue by NerdSec** [longhorn/longhorn#1680]
Hi All,

First of all, Rancher is really an amazing piece of software and it has eased my introduction to Kubernetes quite nicely. I can troubleshoot stuff much easily while I learn the internals of Kubernetes in parallel. I deployed Longhorn on Kubernetes from the UI, and have maybe encountered a bug. Let me know how if you need any more inputs! 

Provisioned a Longhorn PVC, and then used the PV to ran a dbench job. Volume mount fails with an RPC error code = InvalidArgument desc = There is no block device frontend for volume pvc-a6a95db2-b252-483a-87ca-11652657745e

```
Events:
  Type     Reason                  From                     Message
  ----     ------                  ----                     -------
  Normal   Scheduled               default-scheduler        Successfully assigned default/dbench-longhorn-rbtl6 to sidcirmkube05
  Normal   SuccessfulAttachVolume  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a6a95db2-b252-483a-87ca-11652657745e"
  Warning  FailedMount             kubelet, kube05          MountVolume.SetUp failed for volume "pvc-a6a95db2-b252-483a-87ca-11652657745e" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume pvc-a6a95db2-b252-483a-87ca-11652657745e
  Normal   Pulling                 kubelet, kube05          Pulling image "sotoaster/dbench:latest"
  Normal   SuccessfulAttachVolume  kubelet, kube05          AttachVolume.Attach succeeded for volume "pvc-a6a95db2-b252-483a-87ca-11652657745e"
  Normal   Scheduled               default-scheduler        Successfully assigned default/dbench-longhorn-rbtl6 to sidcirmkube05
```

Deployed a Rancher managed cluster on a custom node using RKE. Created a PVC using the following yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

Then ran a job using this yaml:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-longhorn
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: sotoaster/dbench:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          - name: FIO_SIZE
            value: 1G
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: longhorn-pvc
  backoffLimit: 4
```

The job runs fine and I get the output without issues. However the performance is not as expected.

```
==================
= Dbench Summary =
==================
Random Read/Write IOPS: 6730/806. BW: 368MiB/s / 63.1MiB/s
Average Latency (usec) Read/Write: 1712.94/
Sequential Read/Write: 361MiB/s / 43.4MiB/s
Mixed Random Read/Write IOPS: 586/191
```

This is significantly slower than what i get using Hostpath, which is probably correct considering this is SDS. My Hostpath drive is via SAN using Fiber Channel (Using a VM on ESXi).

![image](https://user-images.githubusercontent.com/26703835/90123373-5762d700-dd7c-11ea-8a55-c3c1844632ff.png)
