### ISSUE TITLE
[BUG] PVC stuck in pending state with Longhorn SC recurringJobs and certain cron schedules

### ISSUE THREAD

**Issue by stevesim101** [longhorn/longhorn#1688]
**Describe the bug**
When the longhorn storage class is defined with recurringJobs that use certain cron schedules for a backup job, any PVCs created with the storage class remaining in a pending state indefinitely.  This causes the pods that use the PVCs to fail in their creation.  The specific cron schedules that create the problem contain a forward slash.  If the cron schedule does not contain a forward slash, the problem does not occur.

**To Reproduce**
1. Within the manifest for the storage class, set the recurringJobs to any of the samples listed below.

```
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 * * * *", "retain":4},
                   {"name":"backup", "task":"backup", "cron":"30 */6 * * *", "retain":10}]'

  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 * * * *", "retain":4},
                   {"name":"backup", "task":"backup", "cron":"*/360 * * * *", "retain":10}]'
```

2. Apply the manifest to create the storage class.
3. Apply a manifest that creates a new pvc that uses the storage class.
4. Apply a deployment that defines a "volume" with a persistentVolumeClaim that references the name of new newly created pvc within the claimName.  The deployment also contains an entry in "volumeMounts" that references the name of the "volume".
5. Run `kubectl get pvc my-pvc -n my-ns` and note the status.

```
NAMESPACE   NAME     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
my-ns       my-pvc   Pending                                      longhorn       88s
```

6. Run `kubectl get pod my-pod -n my-ns -o yaml` and note the error.

`message: 'running "VolumeBinding" filter plugin for pod "my-pod": pod has unbound immediate PersistentVolumeClaims'`

**Expected behavior**
Pod can successfully complete its volume binding to the already created pvc and the pvc status is listed as "Bound".

**Environment:**
 - Longhorn version: 1.0.1
 - Kubernetes version: 1.18.6
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by shuo-wu** [comment]
1. It's meaningless to set `recurringJobs` twice in a single storageclass.
2. The 2nd recurring job is invalid, which leads to this issue. Do you mean `*/360 * * * *`?

**Comment by stevesim101** [comment]
I never said I was setting `recurringJobs` twice in the same SC definition.  I was simply providing two **separate** examples of `recurringJobs` that I tested.

Yes, I meant `*/360 * * * *`.  Accidental typo when I was creating the issue.

**Comment by shuo-wu** [comment]
Oh, sorry for misunderstanding it. Does it work fine after correcting the typo?

**Comment by stevesim101** [comment]
The typo only existed in the issue, not in my SC manifest.

**Comment by shuo-wu** [comment]
OK. Can you check if the related Longhorn volume is created or not? You can check it via Longhorn UI or the command `kubectl -n longhorn-system get volumes.longhorn.io`. If NO, then can you fetch the log of the pods `longhorn-csi-plugin-xxxxx`?

**Comment by yasker** [comment]
@meldafrawi can you check to see if you can reproduce the issue using the configuration above?

**Comment by meldafrawi** [comment]
@yasker Couldn't reproduce the issue using steps provided

Deployment pods get attached to Longhorn volume without issues.


![image](https://user-images.githubusercontent.com/18232258/90809004-29076d80-e321-11ea-9685-dd68b011238b.png)

![image](https://user-images.githubusercontent.com/18232258/90809024-302e7b80-e321-11ea-9a93-58c3d200a25c.png)

![image](https://user-images.githubusercontent.com/18232258/90809168-5bb16600-e321-11ea-9898-fcc291ccd181.png)

**Comment by meldafrawi** [comment]
Manifest file used (StorageClass + PVC + Deployment + Service)

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-job
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 * * * *", "retain":4},
                  {"name":"backup", "task":"backup", "cron":"30 */6 * * *", "retain":10}]'
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-job
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc

```
