### ISSUE TITLE
enhancement: introducing `Allow volume creation with degraded availability`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1701]
We've made a decision to ~~revert~~ replace the change for #1282 .

Lots of queries after Longhorn v1.0.0 release are related to the scheduling error since many users don't have three nodes available when trying the Longhorn for the first time. Even though Longhorn is designed for a production environment, 

1. Introduce `Allow volume creation with degraded availability`. It would be by default enabled. This option will allow volume creation when there is at least one replica that can be scheduled. This will also allow more replicas to be rebuilt automatically when new nodes added to the cluster.
2. Highlight the best practice in the README and recommend to disable the option in the best practice guide for the production environment.

**Comment by yasker** [comment]
### Test Cases

All of the test cases below assuming:
1. This setting is set to `true`
2. Node level hard anti-affinty is set to `true`
3. There are three nodes available.

#### Volume creation using UI with degraded availability
1. Disable one of the node's scheduling.
2. Create a volume with three replicas.
    1. Volume should be `ready` after creation and doesn't have scheduling error.
    2. Notice it will show volume with three replicas still but one of the replicas cannot be scheduled to any node.
3. Attach the volume.
    1. Volume attachment should be successful.
    2. After the volume is attached, `scheduling error` should be seen.
4. Write data to the volume.
5. Detach the volume
    1. `scheduling error` should be gone.
    2. Notice the additional replica will be removed once the volume is detached, which is different from step 2.2.
6. Reattach the volume to verify the data.
    1. `scheduling error` should be seen again.
7. Enable the scheduling for the third node.
    1. Volume should start rebuilding on the third node soon.
    2. Once the rebuilding starts, the `scheduling error` should be gone.
8. Detach and reattach the volume to verify the data.

#### Volume creation using UI with no availability
1. Disable all nodes' scheduling.
2. Create a volume with three replicas.
    1. Volume should be `NotReady` after creation
    2. `Scheduling error` should be seen from the UI.
    3. Make sure the volume cannot be `attached`.
3. Enable one node's scheduling
    1. Volume should become `Ready` soon.
    2. `Scheduling error` should be gone.
4. Attach the volume. Write data. Detach and reattach the volume to ensure the integrity of the data.

#### Volume creation using CSI with degraded availability
Same with `Volume creation using UI with degraded availability` but use Deployment Pod instead of UI for the test case.

1. Disable one of the node's scheduling.
2. Create a Deployment Pod with a volume and three replicas.
    1. After the volume is attached, `scheduling error` should be seen.
4. Write data to the Pod.
5. Scale down the deployment to 0 to detach the volume.
    1. `scheduling error` should be gone.
6. Scale up the deployment back to 1 verify the data.
    1. `scheduling error` should be seen again from the UI.
7. Enable the scheduling for the third node.
    1. Volume should start rebuilding on the third node soon.
    2. Once the rebuilding starts, the `scheduling error` should be gone.
8. Scale down and back the deployment to verify the data.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 10/21/2020

Validation - **Pass**

The scenarios from https://github.com/longhorn/longhorn/issues/1701#issuecomment-712428057 are working fine.
Validated by toggling between the setting enabled and disabled, functionality holds good.

**Comment by yasker** [comment]
Thanks to @c3y1huang 's contribution to the end-to-end test.

**Comment by gitlawr** [comment]
It doesn't work well in my single node cluster test:

**Env:**
Single node Ubuntu18.04 on AWS, v1.19.4+k3s1 Kubernetes cluster

**Steps:**
1. Deploy longhorn using the chart from v1.1.0 branch (6a301741dcfe3304a42a52c828dfaa68b7d99417)
2. Wait until all longhorn pods are ready.
3. Deploy the following manifests
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc1
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: nginx
    name: task-pv-container
    ports:
    - containerPort: 80
      name: http-server
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: task-pv-storage
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Result:
The pod pends in ContainerCreating status, with the following events:
```
Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Warning  FailedScheduling    19m                 default-scheduler        persistentvolumeclaim "pvc1" not found
  Warning  FailedScheduling    19m                 default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    19m                 default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           18m                 default-scheduler        Successfully assigned default/pod-pvc1 to ip-172-31-21-35
  Warning  FailedAttachVolume  14m (x10 over 18m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-9193a0ca-6a98-4230-9e97-3f7d42a9b4bf" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-9193a0ca-6a98-4230-9e97-3f7d42a9b4bf volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-9193a0ca-6a98-4230-9e97-3f7d42a9b4bf] map[]}]
  Warning  FailedMount         9m57s               kubelet                  Unable to attach or mount volumes: unmounted volumes=[task-pv-storage], unattached volumes=[default-token-qq5hr task-pv-storage]: timed out waiting for the condition
  Warning  FailedMount         52s (x7 over 16m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[task-pv-storage], unattached volumes=[task-pv-storage default-token-qq5hr]: timed out waiting for the condition
  Warning  FailedAttachVolume  23s (x7 over 12m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-9193a0ca-6a98-4230-9e97-3f7d42a9b4bf" : rpc error: code = Internal desc = Post "http://longhorn-backend:9500/v1/volumes/pvc-9193a0ca-6a98-4230-9e97-3f7d42a9b4bf?action=attach": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Logs of longhorn-manager are full of 
```
time="2020-12-09T10:18:11Z" level=error msg="There's no available disk for replica pvc-4d81572f-5f98-4a76-abae-880700a61f71-r-b8a11423, size 1073741824"
time="2020-12-09T10:18:11Z" level=error msg="unable to schedule replica" controller=longhorn-volume frontend=blockdev node=ip-172-31-21-35 owner=ip-172-31-21-35 replica=pvc-4d81572f-5f98-4a76-abae-880700a61f71-r-b8a11423 state=detached volume=pvc-4d81572f-5f98-4a76-abae-880700a61f71
```

Looks like the pod can be ready finally, but it may take tens of minutes before that.

**Comment by PhanLe1010** [comment]
@gitlawr 

Cannot reproduce the problem

**Env:**
Single node Ubuntu18.04 on AWS, v1.19.4+k3s1 Kubernetes cluster

**Steps:**
1. Deploy longhorn using the chart from v1.1.0 branch (6a301741dcfe3304a42a52c828dfaa68b7d99417)
2. Wait until all longhorn pods are ready.
3. Deploy the following manifests
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc1
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: nginx
    name: task-pv-container
    ports:
    - containerPort: 80
      name: http-server
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: task-pv-storage
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
```

I notice that [the reproduce steps](https://github.com/longhorn/longhorn/issues/1701#issuecomment-741685443) don't specify `storageClassName: longhorn`. I think K8s will try to use default storage class in that case. However, it doesn't work for my K3s cluster because it has both `local-path` and `longhorn` marked as the default storageclass. 



Result:
When I add `storageClassName: longhorn`, the volume is able to attach and workload is able to start within 10-15s.
