### ISSUE TITLE
[Question] MountVolume.SetUp failed  -  There is no block device frontend 

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#1712]
I am running longhorn 1.0.2 in a self managed kubernetes cluster
Everything works fine. 
But I observer the following warning when I launch a new POD (in this case a postgresdb)

    MountVolume.SetUp failed for volume "xxx : rpc error: code = InvalidArgument desc = There is no block device frontend for volume xxx

These are the events form the pod description after successful deployment:

```
 Events:                                                                                                                                                                   │
│   Type     Reason                  Age                  From                      Message                                                                                 │
│   ----     ------                  ----                 ----                      -------                                                                                 │
│   Warning  FailedScheduling        <unknown>            default-scheduler         persistentvolumeclaim "dbdata" not found                                                │
│   Warning  FailedScheduling        <unknown>            default-scheduler         persistentvolumeclaim "dbdata" not found                                                │
│   Warning  FailedScheduling        <unknown>            default-scheduler         running "VolumeBinding" filter plugin for pod "postgres-6f8fc59cd8-p5p4g": pod has unbound immediate PersistentVolumeClaims                                                                                                                                      │
│   Normal   Scheduled               <unknown>            default-scheduler         Successfully assigned documents-imixs-com/postgres-6f8fc59cd8-p5p4g to ixchel-worker-2  │
│   Normal   SuccessfulAttachVolume  4m11s                attachdetach-controller   AttachVolume.Attach succeeded for volume "documents-imixs-com-dbdata"                   │
│   Warning  FailedMount             4m6s (x2 over 4m7s)  kubelet, ixchel-worker-2  MountVolume.SetUp failed for volume "documents-imixs-com-dbdata" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume documents-imixs-com-dbdata                                                                              │
│   Normal   Pulled                  4m4s                 kubelet, ixchel-worker-2  Container image "postgres:9.6.1" already present on machine                             │
│   Normal   Created                 4m4s                 kubelet, ixchel-worker-2  Created container postgres                                                              │
│   Normal   Started                 4m4s                 kubelet, ixchel-worker-2  Started container postgres   
```     

My PVC/PV configuation looks like this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: documents-imixs-com-dbdata
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: documents-imixs-com
    name: dbdata
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: xxx
  storageClassName: longhorn-durable

----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 2Gi
  volumeName: "xxx"
```

Is this warning something I should be concerned of or can I still ignore this warning?

Thanks for Help

===
Ralph

**Comment by shuo-wu** [comment]
No, this error message is misleading... It's actually a transient/intermediate error during the attachment, and Kubernetes/Longhorn will try it when the error happens.

**Comment by rsoika** [comment]
ok, thanks for clarifying.

**Comment by yasker** [comment]
The error message issue has been reported multiple times. Let's use this issue to track the fix for the error message.

**Comment by yasker** [comment]
We can change the error message for the volume is not attached to `the volume %v hasn't been attached yet`. Keep the error message for other conditions to `there is no block device frontend xxx`.

**Comment by yasker** [comment]
Also, we need to check why FailedMount was reported, since in the previous step it's already said the attachment is successful.

**Comment by boknowswiki** [comment]
At beginning I failed to reproduce this issue with creating a pod. Thanks @khushboo-rancher for pointing out it's easier to reproduce it with deployment.
The reason we see `FailedMount` after attachment succeed is because in the [ControlPublishVolume](https://github.com/longhorn/longhorn-manager/blob/39eb345604ec391e8c6f5025321ebf19debcc8e7/csi/controller_server.go#L272) we don't check the endpoint, but in `NodePublishVolume` we check [the endpoint](https://github.com/longhorn/longhorn-manager/blob/39eb345604ec391e8c6f5025321ebf19debcc8e7/csi/node_server.go#L61) .

**Comment by boknowswiki** [comment]
Put a test deploy yaml:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: existing
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: dbdata
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: existing
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeName: "existing"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-pv-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: volume-pv-test
        image: nginx:stable-alpine
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - ls
              - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: vol 
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: vol 
        persistentVolumeClaim:
          claimName: dbdata
```
