### ISSUE TITLE
Improve documentation for installing open-iscsi

### ISSUE THREAD

**Issue by dbpolito** [longhorn/longhorn#1741]
I was trying to install Longhorn on EKS and faced the problem with missing open-iscsi, i see it's documented here: https://longhorn.io/docs/1.0.2/deploy/install/#installing-open-iscsi

But for EKS how to ssh into the node, deal with autoscaling, etc.

I was searching a better way for handling this and found out that the approach on openebs is pretty straight forward:

https://openebs.github.io/charts/openebs-ubuntu-setup.yaml
https://openebs.github.io/charts/openebs-amazonlinux-setup.yaml

I think it would be very useful having a more friendly way of installing this on EKS for new comers like me.

Installing on DOKS was smooth.

Thank you for your hard work ❤️

**Comment by yasker** [comment]
Thanks @dbpolito , that's a good idea. We will see if we can include something similar in our next release.

**Comment by dbpolito** [comment]
Just in case someone need, i deployed this and everything is working now:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-amazonlinux-init
  labels:
    app: longhorn-amazonlinux-init
  annotations:
    command: &cmd yum install iscsi-initiator-utils -y && sudo systemctl enable iscsid && sudo systemctl start iscsid
spec:
  selector:
    matchLabels:
      app: longhorn-amazonlinux-init
  template:
    metadata:
      labels:
        app: longhorn-amazonlinux-init
    spec:
      hostNetwork: true
      initContainers:
      - name: init-node
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - sh
          - -c
          - *cmd
        image: alpine:3.7
        securityContext:
          privileged: true
      hostPID: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy:
    type: RollingUpdate
```
