### ISSUE TITLE
[BUG] Unable to restore from backup URL using a storage class.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1754]
**Describe the bug**
Restore of a volume using a storage class having parameter ```fromBackup``` a valid backup URL fails to attach to a pod.

**To Reproduce**
1. Create a Storage class using a valid backup URL.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: "s3://khushboo-test@us-west-1/?backup=backup-59b53aac4bfe&volume=volume-test-2"
```
2. Create a StatefulSet with ```Volume claim Template``` using the longhorn-test storage class.
3. A volume gets created in longhorn and restore completes successfully.
4. Pod fails to come up healthy and shows below error.
```
MountVolume.SetUp failed for volume "pvc-d97eaabb-7de6-403e-b9ae-7b58f0d035c9" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-d97eaabb-7de6-403e-b9ae-7b58f0d035c9 but could not correct them: fsck from util-linux 2.31.1 /dev/longhorn/pvc-d97eaabb-7de6-403e-b9ae-7b58f0d035c9: Superblock has an invalid journal (inode 8). CLEARED. *** journal has been deleted *** /dev/longhorn/pvc-d97eaabb-7de6-403e-b9ae-7b58f0d035c9: Resize inode not valid. /dev/longhorn/pvc-d97eaabb-7de6-403e-b9ae-7b58f0d035c9: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY. (i.e., without -a or -p options) .
```

**Expected behavior**
The pod should successfully come up healthy and should have the data from backup.

**Note**
The same backup restore works fine if restored using longhorn UI.

**Environment:**
 - Longhorn version: Longhorn master- 09/01/2020
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Additional context**
Could be the same as https://github.com/longhorn/longhorn/issues/1750
