### ISSUE TITLE
[BUG] Request failed with status code 405 on delete schedule snapshot

### ISSUE THREAD

**Issue by obeyler** [longhorn/longhorn#1794]
**Describe the bug**
I try to remove a schedule snapshot 
I click on delete 
![image](https://user-images.githubusercontent.com/23224162/93391439-710da780-f86f-11ea-9889-6e04af76cf05.png)

I click on save
Request failed with status code 405
![image](https://user-images.githubusercontent.com/23224162/93391514-8d114900-f86f-11ea-950e-278f21de01fd.png)

and the schedule snapshot stays active

**To Reproduce**
The pv have been created by this storageclass
```
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn-1instance-backuped
        labels:
          app.kubernetes.io/instance: longhorn
          app.kubernetes.io/name: longhorn
          app.kubernetes.io/version: v1.0.2
      provisioner: driver.longhorn.io
      parameters:
        baseImage: ''
        dataLocality: "best-effort"
        fromBackup: ''
        numberOfReplicas: '1'
        recurringJobs: >-
          [ { "name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1 }, {
          "name":"backup", "task":"backup", "cron":"0 0 * * *", "retain":1,
          "labels": { "interval":"1Day" } } ]
        staleReplicaTimeout: '30'
      reclaimPolicy: Delete
```
**Expected behavior**
should be able to delete schedule on PV

**Log**

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18.8
 - Node OS type and version: ubuntu

**Additional context**
