### ISSUE TITLE
port 80: Connection refused when trying to create ingress for Longhorn

### ISSUE THREAD

**Issue by chaets** [longhorn/longhorn#1810]
I am trying to to install Longhorn using kubectl, i am getting issue which creating the ingress for longhorn-system, can anybody help me out

Longhorn 1.02 V
running on AWS EC2 Instance
trying to follow:

https://longhorn.io/docs/1.0.0/deploy/accessing-the-ui/longhorn-ingress/

```
echo "
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: longhorn-frontend
          servicePort: 80
```
I am unable to curl the end point

```
curl -v http://10.201.10.222/ -u 'foo:bar'
*   Trying 10.201.10.222...
* TCP_NODELAY set
* connect to 10.201.10.222 port 80 failed: Connection refused
* Failed to connect to 10.201.10.222 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.201.10.222 port 80: Connection refused
```
