### ISSUE TITLE
[FEATURE] Cloning support

### ISSUE THREAD

**Issue by NULLx76** [longhorn/longhorn#1815]
**Describe the solution you'd like**
Cloning support (VolumePVCDataSource) for the longhorn CSI driver, currently this is not implemented and returns the following error when trying to use it:
```
failed to provision volume with StorageClass "longhorn": CSI driver does not support clone operations: controller CLONE_VOLUME capability is not reported
```

**Describe alternatives you've considered**
Manually cloning the volume, e.g. attaching the old and new volume to the same pod and copying everything over. However this is cumbersome and inelegant.

I've also looked at the possiblity of creating a _new_ volume from the backup of an existing volume, however this doesn't seem possible as of now (or at least I could not find out how to). If this is or could be possible I would also be satisfied.

**Additional context**
Here are some links to official documenation on the topic:
* [Official Documentation](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/)
* [Kubernetes CSI Developer documentation](https://kubernetes-csi.github.io/docs/volume-cloning.html)

**Comment by yasker** [comment]
@NULLx76 You can create a new volume from a backup of an existing volume. You can restore it from the backup into a new volume in Longhorn, then create PV/PVC for the volume, and finally use the PVC with the workload. You can see it from my demo at https://www.youtube.com/watch?v=zJY2uxLtwUk

I will still keep this open to track the volume cloning feature.

**Comment by travnewmatic** [comment]
really wishing longhorn could do clone operation things.  i'm in the process of switching my cluster from local-storage volumes to longhorn, and was expecting (hoping) i could apply this solution: https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/

**Comment by osddeitf** [comment]
+1
I need to switch from local-path volumes (default in K3S), too.

**Comment by joshimoo** [comment]
We currently don't support volume cloning, but for data migration we have an example kubernetes job that you can modify to copy the data from the local-path volume to the new longhorn volume.

https://github.com/longhorn/longhorn-manager/blob/master/examples/data_migration.yaml

**Comment by ayr-ton** [comment]
@joshimoo Do you know a way of using the `data_migration.yaml` copy/pasting from volumes in two different namespaces?

**Comment by sinoon** [comment]
High Needed!!! Please Support !!!

**Comment by PhanLe1010** [comment]
@travnewmatic @osddeitf 
 
 Regarding to the goal:
> switching my cluster from local-storage volumes to longhorn

I don't think CSI volume cloning feature can achieve this goal. From [the document](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/#introduction) you mentioned, the 2 PVC must have the same storageclass

**Comment by PhanLe1010** [comment]
@ayr-ton The steps at https://github.com/longhorn/longhorn/issues/1815#issuecomment-781609692 seems good to me

**Comment by PhanLe1010** [comment]
### Test plan

#### Clone volume that doesn't have backing image
1. Create a PVC:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: source-pvc
    spec:
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ```
1. Specify the `source-pvc` in a pod yaml and start the pod
1. Wait for the pod to be running, write some data to the mount path of the volume
1. Clone a volume by creating the PVC:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: cloned-pvc
    spec:
      storageClassName: longhorn
      dataSource:
        name: source-pvc
        kind: PersistentVolumeClaim
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ```
1. Specify the `cloned-pvc` in a cloned pod yaml and deploy the cloned pod
1. Wait for the `CloneStatus.State` in `cloned-pvc` to be `completed`
1. In 3-min retry loop, wait for the cloned pod to be running
1. Verify the data in `cloned-pvc` is the same as in `source-pvc`
1. In 2-min retry loop, verify the volume of the `clone-pvc` eventually becomes healthy
1. Cleanup the cloned pod, `cloned-pvc`. Wait for the cleaning to finish
1. Scale down the source pod so the `source-pvc` is detached. 
1. Wait for the `source-pvc` to be in detached state
1. Clone a volume by creating the PVC:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: cloned-pvc
    spec:
      storageClassName: longhorn
      dataSource:
        name: source-pvc
        kind: PersistentVolumeClaim
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ```
1. Specify the `cloned-pvc` in a cloned pod yaml and deploy the cloned pod
1. Wait for `source-pvc` to be attached
1. Wait for a new snapshot created in `source-pvc` volume created
1. Wait for the `CloneStatus.State` in `cloned-pvc` to be `completed`
1. Wait for `source-pvc` to be detached
1. In 3-min retry loop, wait for the cloned pod to be running
1. Verify the data in `cloned-pvc` is the same as in `source-pvc`
1. In 2-min retry loop, verify the volume of the `clone-pvc` eventually becomes healthy
1. Cleanup the test

#### Clone volume that has backing image
1. Deploy a storage class that has backing image parameter
  ```yaml
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-bi-parrot
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  parameters:
    numberOfReplicas: "3"
    staleReplicaTimeout: "2880" # 48 hours in minutes
    backingImage: "bi-parrot"
    backingImageURL: "https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2"
  ```
Repeat the `Clone volume that doesn't have backing image` test with `source-pvc` and `cloned-pvc` use `longhorn-bi-parrot` instead of `longhorn` storageclass

#### Interrupt volume clone process

1. Create a PVC:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: source-pvc
    spec:
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ```
1. Specify the `source-pvc` in a pod yaml and start the pod
1. Wait for the pod to be running, write 1GB of data to the mount path of the volume
1. Clone a volume by creating the PVC:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: cloned-pvc
    spec:
      storageClassName: longhorn
      dataSource:
        name: source-pvc
        kind: PersistentVolumeClaim
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ```
1. Specify the `cloned-pvc` in a cloned pod yaml and deploy the cloned pod
1. Wait for the `CloneStatus.State` in `cloned-pvc` to be `initiated`
1. Kill all replicas process of the `source-pvc`
1. Wait for the `CloneStatus.State` in `cloned-pvc` to be `failed`
1. In 2-min retry loop, verify cloned pod cannot start
1. Clean up cloned pod and `clone-pvc`
1. Redeploy `cloned-pvc` and clone pod   
1. In 3-min retry loop, verify cloned pod become running
2. `cloned-pvc` has the same data as `source-pvc`   
1. Cleanup the test
