### ISSUE TITLE
[BUG] Unable to use Privat Network Interface for Inter-host communication

### ISSUE THREAD

**Issue by venomone** [longhorn/longhorn#1837]
**Describe the bug**
If I deploy a new cluster or edit a existing one and I try to set the private IP for inter-host communication my config seems to get ignored. Every time the Deployment/Update of the cluster is done nothing seems to have changed, I still see that the deployment gets executed over the public interface/IP

**To Reproduce**
1. Go to 'Cluster > Edit Cluster '
2. Click on 'Edit as YAML'
3. Perform 'Update network: configs'
4. See nothing has changed

**Expected behaviour**
I setup private IP for inter-host communication like so:
```

  network:
    mtu: 0
    options:
      canal_flannel_backend_type: vxlan
      canal_iface: enp7s0
    plugin: canal
  restore:
    restore: false
```

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.18.8
 - Node OS type and version: Ubuntu 18.04.5

**Additional context**
