### ISSUE TITLE
[Question]Longhorn workloads are not using the custom Priority Class

### ISSUE THREAD

**Issue by kevinsulatra** [longhorn/longhorn#1838]
We have set the priority-class value to the name of a custom Priority Class. However, none of the Longhorn workloads are using it. 
Longhorn Version
`v1.0.2`

PriorityClass
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: longhorn-node-critical
value: 1000000
globalDefault: false
description: "This priority class should be used for longhorn pods only."
```

Longhorn Settings
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target:
    backup-target-credential-secret:
    create-default-disk-labeled-nodes: true # Custom
    default-data-path:
    replica-soft-anti-affinity:
    storage-over-provisioning-percentage:
    storage-minimal-available-percentage:
    upgrade-checker:
    default-replica-count:
    guaranteed-engine-cpu:
    default-longhorn-static-storage-class:
    backupstore-poll-interval:
    taint-toleration: dedicated-execution:NoExecute; dedicated-scheduling:NoSchedule
    priority-class: longhorn-node-critical
    registry-secret:
    auto-salvage:
    disable-scheduling-on-cordoned-node:
    replica-zone-soft-anti-affinity:
    volume-attachment-recovery-policy:
    mkfs-ext4-parameters:
```

Longhorn UI
![image](https://user-images.githubusercontent.com/56389502/94785594-c85f5c00-03c7-11eb-8a52-e56d1979868c.png)
