### ISSUE TITLE
BUG: IP Address of instance manager pods are not sync to the instance manager object sometime

### ISSUE THREAD

**Issue by mfbrj** [longhorn/longhorn#1880]
I have a postgres pod running and I scale it to 0 to do some maintence. The respective Longhorn volume stucked Detaching state. Other 2 pods which were deleted (pod, pv and pvc) get stucked in Deleting state:

![image](https://user-images.githubusercontent.com/835834/96038185-2b77d680-0e3d-11eb-81ae-3e342f4089d8.png)

---
Version: `v1.0.2`

**Comment by mfbrj** [comment]
The problem occours after the 3 k8s masters and most workers rebooted in this dawn. The IP address changed in these nodes. Controlplane was down, I take a couple of hours to restablish it without any data loss in etcd. Cluster got healthy.

In meantime, elasticsearch statefulset didn't goes up. Which I decided to delete because it was just a test workload. So I notice the 2 longhorn volumes stucked in "Deleting" state.

In the other hand, I scale postgres to 0. And the it's Longhorn volume stucked in "Detaching"

I fixed everything just deleting the instance-managers related. The instances were automatically recreated by the cluster and everything came back fine.

![](https://i.imgur.com/1pMqrBc.png)

**Comment by yasker** [comment]
Thanks @mfbrj for the detail explaination.

From the support bundle, I found it's due to the instance manager's IP wasn't updated.

From the IM object:
```
- typemeta:
    kind: InstanceManager
    apiversion: longhorn.io/v1beta1
  objectmeta:
    name: instance-manager-e-1f980f65
    generatename: ""
    namespace: longhorn-system
...
  spec:
    image: longhornio/longhorn-instance-manager:v1_20200514
    nodeid: k8s-worker3
    type: engine
    engineimage: ""
  status:
    ownerid: k8s-worker3
    currentstate: running
    instances:
      pvc-4d6ea615-5c4e-4cf4-b700-9f29afd3ce55-e-bb81bc34:
        spec:
          name: pvc-4d6ea615-5c4e-4cf4-b700-9f29afd3ce55-e-bb81bc34
        status:
          endpoint: ""
          errormsg: ""
          listen: ""
          portend: 10001
          portstart: 10001
          state: running
          type: ""
          resourceversion: 0
    **ip: 10.42.100.239**
    apiminversion: 1
    apiversion: 1
```

But the pod:
```
- typemeta:
    kind: ""
    apiversion: ""
  objectmeta:
    name: instance-manager-e-1f980f65
    generatename: ""
    namespace: longhorn-system
 ....
  spec:
....
    nodename: k8s-worker3
....
  status:
    phase: Running
    conditions:
    - type: Initialized
      status: "True"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2020-10-10T15:23:54Z"
      reason: ""
      message: ""
    - type: Ready
      status: "True"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2020-10-14T15:10:27Z"
      reason: ""
      message: ""
    - type: ContainersReady
      status: "True"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2020-10-14T15:10:27Z"
      reason: ""
      message: ""
    - type: PodScheduled
      status: "True"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2020-10-10T15:23:54Z"
      reason: ""
      message: ""
....
    **podip: 10.42.100.234**
    starttime: "2020-10-10T15:23:54Z"
....
```

It seems due to the restart of the masters, IM controller missed the point to update the pod IP in the IM object, which caused the problem:

https://github.com/longhorn/longhorn-manager/blob/5deb6ef186a4fd8fc8581f05d48cba5a527d9ec6/controller/instance_manager_controller.go#L360
