### ISSUE TITLE
[BUG] slow disk write performance with longhorn raw block device

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1989]
[Copied from https://github.com/rancher/harvester/issues/227]

**Description:**
we are currently using the longhorn as the back-end storage system, during the VM image import process, the disk write performance is comparatively slow when it uses a raw block device mode vs filesystem, will need to make an enhancement on its write performance with raw-block device mode.

**Steps to reproduce:**
1. create a k3s cluster with the latest longhorn(i.e v1.0.2) deployed.
2. apply the following YAML
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc-scratch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: block-volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: kubevirt/cdi-importer:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    env:
    - name: IMPORTER_SOURCE
      value: http
    - name: IMPORTER_ENDPOINT
      value: http://minio.harvester-system:9000/vm-images/image-q56qm
    - name: IMPORTER_CONTENTTYPE
      value: kubevirt
    - name: IMPORTER_IMAGE_SIZE
      value: 10Gi
    - name: OWNER_UID
      value: 937b3fb1-0e12-4dda-84ff-5ed3ea560576
    - name: FILESYSTEM_OVERHEAD
      value: "0"
    - name: INSECURE_TLS
      value: "false"
    - name: IMPORTER_DISK_ID
    - name: IMPORTER_UUID
    - name: IMPORTER_BACKING_FILE
    - name: IMPORTER_THUMBPRINT
    volumeDevices:
    - name: block
      devicePath: /dev/cdi-block-volume
    volumeMounts:
    - mountPath: /scratch
      name: cdi-scratch-vol
    ports:
    - containerPort: 80
  volumes:
  - name: block
    persistentVolumeClaim:
      claimName: block-pvc
  - name: cdi-scratch-vol
    persistentVolumeClaim:
      claimName: block-pvc-scratch
```
3. either download the qcow2 image and run `kubectl cp qcow2_image block-volume-test:/scratch/` to copy the image into the container or exec into the pod and using curl to download the qcow2 image `https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz` and unzip it with($microdnf -y update && microdnf install xz  &&  xz -v -d file_to_unzip)
4. unzip the file into the /scratch path and using `qemu-img` to write to the block device path `i.e. /dev/cdi-block-volume`
`$time qemu-img convert -t none -p -W -O raw /scratch/tmpimage /dev/cdi-block-volume`
5. the time for converting the unzipped image into the block device path is ~7-8 times longer than write to the filesystem with both using the longhorn driver(e.g `time qemu-img convert -t none -p -W -O raw /scratch/tmpimage /scratch/test.raw`)
