### ISSUE TITLE
[QUESTION] Data is not persisting when redeployed and attached with same PV and PVCs

### ISSUE THREAD

**Issue by chaets** [longhorn/longhorn#1998]
Hi everyone
I have deployed Longhorn 1.02 with Rancher 2.5.2,
I problem I am stating is when I am redeploying and attaching with the same PV and PVC the data is not persisting, means all the older data before redeployment is lost, Any clue, what I am doing wrong?

Longorn PV and PVC state in Longhorn UI
```
State: Attached
Health: Healthy
Ready for workload:Ready
Conditions:
restore
scheduled
Frontend:Block Device
Attached Node & Endpoint:
testxxxyyyzzzz.com
/dev/longhorn/pvc-bd6a1bed-b0b3-4efc-b1f8-fe65f7d837ee
Size:
5 Gi
Actual Size:147 Mi
Base Image:
Engine Image:longhornio/longhorn-engine:v1.0.2
Created:14 hours ago
Node Tags:
Disk Tags:
Last Backup:
Last Backup At:
Instance Manager:
instance-manager-e-c2786091
Namespace:insights-preproduction
PVC Name:tsdb-platform-data
PV Name:pvc-bd6a1bed-b0b3-4efc-b1f8-fe65f7d837ee
PV Status:Bound
Pod Name:insights-tsdb-platform-9f8f5ff4c-5zbrp
Pod Status:Running
Workload Name:insights-tsdb-platform-9f8f5ff4c
Workload Type:ReplicaSet
```
Storage Class

```
# Source: insights-storage-class/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: insights-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/name: insights-storage-class
    helm.sh/chart: insights-storage-class-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: insights
    app.kubernetes.io/version: v1.0.2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
```

These are the deployment, service and PVC yaml files,
```
insights-tsdb-platform/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: insights-tsdb-platform
 labels:
  app: insights-tsdb-platform
  chart: "insights-tsdb-platform-0.1.0"
spec:
 replicas: 1
 selector:
  matchLabels:
   app: insights-tsdb-platform
 template:
  metadata:
   labels:
    app: insights-tsdb-platform
  spec:
   securityContext:
    runAsUser: 0
    runAsGroup: 0
   restartPolicy: Always
   imagePullSecrets:
   - name: XXX
   containers:
   - name: "tsdb-platform"
    image: "YYYY:latest-release"
    imagePullPolicy: "IfNotPresent"
    args:
    - "--promscrape.config=/tsdb-platform-data/victoriametrics-platform-edge.yml"
    - "--retentionPeriod=3"
    - "--storageDataPath=/tsdb_platform_data"
    - "--httpListenAddr=:8928"
    ports:
    - containerPort: 8928
    volumeMounts:
    - mountPath: /tsdb-platform-data/
     name: prom-config
    - mountPath: /tsdb-platform/
     name: tsdb-platform-data
    resources:
      limits:
       cpu: 500m
       memory: 512Mi
      requests:
       cpu: 100m
       memory: 128Mi
   volumes:
   - hostPath:
     path: /usr/local/ihi/insights/prometheus/config/
    name: prom-config
   - name: tsdb-platform-data
    persistentVolumeClaim:
     claimName: tsdb-platform-data

# Source: insights-tsdb-platform/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: insights-tsdb-platform
  labels:
    app: insights-tsdb-platform
    chart: "insights-tsdb-platform-0.1.0"
spec:
  type: ClusterIP

  externalIPs:
    - 10.201.10.176
  ports:
  - port: 8928
    targetPort: 8928
    protocol: TCP
    name: tsdb-platform-insights

  selector:
    app: insights-tsdb-platform

# Source: /insights-tsdb-platform/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsdb-platform-data
  labels:
    type: tsdb-platform-data-pvc
    StorageClass: longhorn-static
spec:
  storageClassName: insights-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
as well as if I am doing `Helm uninstall` and `helm install `instead of attaching with old PV it is creating new PV every single time
