### ISSUE TITLE
[BUG] NFS - Provisioning : persistentvolume-controller  storageclass.storage.k8s.io "longhorn" not found

### ISSUE THREAD

**Issue by Raboldar** [longhorn/longhorn#2000]
I was trying to create a NFS provisioner for my Kubernetes Cluster to use for backups. 

I followed the example set at : https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/
After applying the 01-security.yaml I changed the ClusterIP in the deployment file of the 02-longhorn-nfs-provisioner.yaml and changed the size of my VolumeClaim to 25G. The pod longhorn-nfs-provisioner was hanging in the pending state. I took a look the cause of the error : 0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims. 

The PVC description : 
```
Name:          longhorn-nfs-provisioner
Namespace:     longhorn-system
StorageClass:  longhorn
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    longhorn-nfs-provisioner-76cb977b9f-4slmf
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Warning  ProvisioningFailed  108s (x42 over 11m)  persistentvolume-controller  storageclass.storage.k8s.io "longhorn" not found
```
After taking a better look at the 02-longhorn-nfs-provisioner.yaml file. I'm not sure if this is a problem but the storage pool uses a different name that the one that's used in the PVC : 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nfs-provisioner # longhorn backing pvc
  namespace: longhorn-system
spec:
  storageClassName: longhorn ### This should be longhorn-nfs ? 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20G" 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nfs # workload storage class. 
provisioner: nfs.longhorn.io
mountOptions:
  - "vers=4.1"
  - "noresvport"
```
So I tried to change it but the result was the same with the following error : 
```
Name:          longhorn-nfs-provisioner
Namespace:     longhorn-system
StorageClass:  longhorn-nfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: nfs.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    longhorn-nfs-provisioner-76cb977b9f-zlxc8
Events:
  Type     Reason                Age               From                         Message
  ----     ------                ----              ----                         -------
  Warning  ProvisioningFailed    21s               persistentvolume-controller  storageclass.storage.k8s.io "longhorn-nfs" not found
  Normal   ExternalProvisioning  2s (x2 over 17s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "nfs.longhorn.io" or manually created by system administrator

```
Maybe I'm doing it the wrong way. It would be great to have additional documentation because I don't really understand why do we have a Pod/Service for the NFS server when in the example (03-rwx-test.yaml) we are asking directly the Storage Class for a volume that uses NFS.
I'm trying to use it to define a Volume for the backups of my pgo (Postgres Operator) instances. 

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.19.3
 - Node OS type and version: Debian Buster 10

**Comment by yasker** [comment]
@joshimoo any ideas?

**Comment by joshimoo** [comment]
@Raboldar 
Your change is incorrect and unnecessary, the longhorn-nfs-provisioner volume needs to be a regular longhorn volume.


looks like you are missing the longhorn storage class?
`Warning  ProvisioningFailed  108s (x42 over 11m)  persistentvolume-controller  storageclass.storage.k8s.io "longhorn" not found`

What does `kubectl get storageclasses` look like.
example output:
```
jmoody@dev:/tmp/a$ kubectl get storageclasses -n longhorn-system
NAME           PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn       driver.longhorn.io   Delete          Immediate           true                   69d
longhorn-nfs   nfs.longhorn.io      Delete          Immediate           false                  48d
```

**Comment by Raboldar** [comment]
You are right, it was missing. I had deleted it and created a different one.
So to test the feature I create a new longhorn StorageClass:
```
NAME                     PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn                 driver.longhorn.io   Delete          Immediate           true                   2m37s
longhorn-nfs             nfs.longhorn.io      Delete          Immediate           false                  2m15s
main-storage (default)   driver.longhorn.io   Delete          Immediate           true                   16h
```
After which I applied the deployment file : 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-nfs-provisioner
  namespace: longhorn-system
---
kind: Service
apiVersion: v1
metadata:
  name: longhorn-nfs-provisioner
  namespace: longhorn-system
  labels:
    app: longhorn-nfs-provisioner
spec:
  # hardcode a cluster ip for the service
  # so that on delete & recreate of the service the previous pv's still point
  # to this nfs-provisioner, pick a new ip for each new nfs provisioner
  clusterIP: 192.168.1.1 
  ports:
    - name: nfs
      port: 2049
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: longhorn-nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: longhorn-nfs-provisioner
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: longhorn-nfs-provisioner
    spec:
      serviceAccount: longhorn-nfs-provisioner
      containers:
        - name: longhorn-nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: nlockmgr
              containerPort: 32803
            - name: nlockmgr-udp
              containerPort: 32803
              protocol: UDP
            - name: mountd
              containerPort: 20048
            - name: mountd-udp
              containerPort: 20048
              protocol: UDP
            - name: rquotad
              containerPort: 875
            - name: rquotad-udp
              containerPort: 875
              protocol: UDP
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
            - name: statd
              containerPort: 662
            - name: statd-udp
              containerPort: 662
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=nfs.longhorn.io"
            - "-device-based-fsids=false"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: longhorn-nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            exec:
              command:
                - ls
                - /export
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - ls
                - /export
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: longhorn-nfs-provisioner
      # we want really quick failover
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 60
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nfs-provisioner # longhorn backing pvc
  namespace: longhorn-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "55G" # make this 10% bigger then the workload pvc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nfs # workload storage class
provisioner: nfs.longhorn.io
mountOptions:
  - "vers=4.1"
  - "noresvport"
```
Which results in the creation of the following : 
```
csi-attacher               3/3     3            3           13d
csi-provisioner            3/3     3            3           13d
csi-resizer                3/3     3            3           13d
longhorn-driver-deployer   1/1     1            1           13d
longhorn-nfs-provisioner   0/1     1            0           4m24s
longhorn-ui                1/1     1            1           13d

```
I checked the deployed Pod : 
```
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Warning  FailedScheduling    44s                default-scheduler        0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    44s                default-scheduler        0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           37s                default-scheduler        Successfully assigned longhorn-system/longhorn-nfs-provisioner-76cb977b9f-76lnw to worker2
  Warning  FailedAttachVolume  21s (x6 over 37s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-db670825-0013-4bdc-b022-0746baf37ffc" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-db670825-0013-4bdc-b022-0746baf37ffc to worker2: volume pvc-db670825-0013-4bdc-b022-0746baf37ffc not scheduled] from [http://longhorn-backend:9500/v1/volumes/pvc-db670825-0013-4bdc-b022-0746baf37ffc?action=attach]
  Warning  FailedAttachVolume  5s                 attachdetach-controller  AttachVolume.Attach failed for volume "pvc-db670825-0013-4bdc-b022-0746baf37ffc" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to attach volume pvc-db670825-0013-4bdc-b022-0746baf37ffc to worker2: volume pvc-db670825-0013-4bdc-b022-0746baf37ffc not scheduled, code=Server Error] from [http://longhorn-backend:9500/v1/volumes/pvc-db670825-0013-4bdc-b022-0746baf37ffc?action=attach]
```
I checked the longhorn interface and I have 163 Gb Schedulable storage. I took a look at the created PVC and it can't be created : 
The volume is bound to longhorn-nfs-provisioner-76cb977b9f but it can't be scheduled.
The volume was created in the longhorn-system : 
```
pvc-db670825-0013-4bdc-b022-0746baf37ffc   33Gi       RWO            Delete           Bound    longhorn-system/longhorn-nfs-provisioner   longhorn                7m27s
```
Describe : 
```
Name:            pvc-db670825-0013-4bdc-b022-0746baf37ffc
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: driver.longhorn.io
Finalizers:      [kubernetes.io/pv-protection external-attacher/driver-longhorn-io]
StorageClass:    longhorn
Status:          Bound
Claim:           longhorn-system/longhorn-nfs-provisioner
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        33Gi
Node Affinity:   <none>
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            driver.longhorn.io
    FSType:            ext4
    VolumeHandle:      pvc-db670825-0013-4bdc-b022-0746baf37ffc
    ReadOnly:          false
    VolumeAttributes:      numberOfReplicas=2
                           staleReplicaTimeout=2880
                           storage.kubernetes.io/csiProvisionerIdentity=1605500777414-8081-driver.longhorn.io
Events:                <none>

```
And the Claim of the mentioned volume : 
```
Name:          longhorn-nfs-provisioner
Namespace:     longhorn-system
StorageClass:  longhorn
Status:        Bound
Volume:        pvc-db670825-0013-4bdc-b022-0746baf37ffc
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      33Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    longhorn-nfs-provisioner-76cb977b9f-76lnw
Events:
  Type    Reason                 Age                    From                                                                                      Message
  ----    ------                 ----                   ----                                                                                      -------
  Normal  ExternalProvisioning   9m48s (x2 over 9m48s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
  Normal  Provisioning           9m48s                  driver.longhorn.io_csi-provisioner-5549dd6d7f-zw552_0a7827a8-6286-4574-b96d-6bc7f99c2731  External provisioner is provisioning volume for claim "longhorn-system/longhorn-nfs-provisioner"
  Normal  ProvisioningSucceeded  9m46s                  driver.longhorn.io_csi-provisioner-5549dd6d7f-zw552_0a7827a8-6286-4574-b96d-6bc7f99c2731  Successfully provisioned volume pvc-db670825-0013-4bdc-b022-0746baf37ffc
```
The volume apeares as detached in the interface and I get the error "the volume can't be sheduled".
As expected when trying to deploy the nfs-test file the pvc is waiting for a volume to be created : 
```
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  13s (x2 over 26s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "nfs.longhorn.io" or manually created by system administrator```

**Comment by joshimoo** [comment]
@Raboldar I am assuming you deployed the default longhorn storage class which requires 3 replicas with hard anti affinity (i.e. 3 worker nodes)

Do you have 3 worker nodes available? if not set the replica count of your customer storage class to your worker count.
You can then use your custom storage class, for the nfs-provisioner by replacing the reference to the longhorn storage class above.

**Comment by Raboldar** [comment]
I did have 4 Worker Nodes that were available at the moment. Strangely it took a while but it ended up scheduling the volume (took around 15 mins), I don't know what slowed down the process. So if I understand correctly each time that the cluster would need a RWX volume it would create a claim that would use the nfs-longhorn StorageClass ? Is there a scenario where we need to use the nfs-longhorn-deploy (the Pod that's exposed with an IP) ?

**Comment by joshimoo** [comment]
@Raboldar
Correct RWX volumes will need to be created against the longhorn-nfs storage class.
You can change the name of that class as long as you copy the parameters, have a look here for an explanation of what needs to be changed if you plan on running multiple provisioners. 
https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/#multiple-rwx-workloads

I don't understand the last question, I don't know what `nfs-longhorn-deploy` refers to, can you elaborate?

**Comment by Raboldar** [comment]
Sure, I'm sorry, this is no longer a bug related question but I was wondering if there's a scenario where we actually use the defined provisioner service or it's just an internal component used by the NFS longhorn system. (I was talking about the "02-longhorn-nfs-provisioner.yaml"). Supposing I need a NFS provisioner in my cluster, can I use the provisioner service with a different Storage Class ?

As an example: 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 192.168.0.1 # The IP of the provisioner Service.
```
Thanks for the help, I couldn't find the cause of the Volume Scheduling delay. It would be really cool to have just a mention about the longhorn StorageClass that needs to be existent or the fact that it can be replaced with any other StorageClass in the deployment file( "02-longhorn-nfs-provisioner.yaml").
