### ISSUE TITLE
[FEATURE] UI : Dark Theme

### ISSUE THREAD

**Issue by Wykiki** [longhorn/longhorn#2038]
**Is your feature request related to a problem? Please describe.**

Longhorn UI comes with a light theme.
A dark theme would be really nice, to match Rancher's one.

**Describe the solution you'd like**

A dark theme on the Longhorn UI.

**Additional context**
Longhorn rocks !

**Comment by yasker** [comment]
We're planning to rewrite the Longhorn UI during or after v1.2.0 release cycle since we need to refactor the API framework first. We will include a dark theme then.

**Comment by PhanLe1010** [comment]
@Wykiki 

In the meantime, you can use the extension https://darkreader.org/ to "turn on"  Longhorn's dark mode :) 
<img width="1412" alt="Screen Shot 2021-01-12 at 7 21 57 PM" src="https://user-images.githubusercontent.com/22139961/104402583-78864a00-550b-11eb-97c3-97af609e2d2a.png">

**Comment by georglauterbach** [comment]
This would be great. For me, the Darkreader extension does not work at the moment.

**Comment by timothystewart6** [comment]
I am happy to open a PR on Longhorn UI and am very familiar with `react`  however I just want to be sure that the core maintainers would welcome such a PR.

**Comment by PhanLe1010** [comment]
@timothystewart6 We would love to. Feel free to propose a PR.

**Comment by timothystewart6** [comment]
@PhanLe1010 

Any tips on local development?  I've tried port forwarding a pod running in k8s however I can't seem to connect

`kubectl port-forward --namespace longhorn-system longhorn-manager-4w5dd 9500:9500`

Even a `curl` to this pod on `9500` drops the request.  I'd love to work on this but have spent a few hours just getting it running locally.  I have the URL running, but I can't connect to any of the services.  I guess I don't need them to work on this feature however it would be nice if I could point the UI to a port forwarded service.

Thanks!

**Comment by joshimoo** [comment]
The longhorn manager currently only listens on the dedicated pod ip.
A quick solution that comes to mind is to spawn an nginx proxy pod which you can have listen on all interfaces and forward to longhorn-manager service this pod can then also be forwarded via `kubectl port-forward`

**Comment by timothystewart6** [comment]
@joshimoo  Thanks for the tip!  I can give that a shot!  Curious how people have worked on this in the past, just run frontend and backend local?  Or just wing it without services (probably not 😀 )

**Comment by PhanLe1010** [comment]
Another approach is to create an ingress like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  rules:
  - host: 137.184.236.58.nip.io #replace by your host ip
    http:
      paths:
      - backend:
          service:
            name: longhorn-backend
            port:
              number: 9500
        path: /
        pathType: Prefix
```
Then access the backend at `http://137.184.236.58.nip.io/`

**Comment by PhanLe1010** [comment]
@smallteeths Do you have a better idea?

**Comment by smallteeths** [comment]
@timothystewart6  You can use nodePort svc to expose longhorn services directly, then use `LONGHORN_MANAGER_IP="http://localhost:xxxxxx" npm run dev`. 

cc @PhanLe1010

**Comment by timothystewart6** [comment]
I see!  Thank you all so much!  I will give that a shot tomorrow!

**Comment by Mataco817** [comment]
I've been loving lonhorn, excited to see Dark UI in the works <3

**Comment by timothystewart6** [comment]
@smallteeths I don't think you meant `localhost` I think you meant the IP of the node that you exposed the node port on?

I have tried that and I am still getting 504s.

I have created a service exposing node port

```yaml
kind: Service
apiVersion: v1
metadata:
  name: port-example-svc
spec:
  type: NodePort 
  ports:
    - nodePort: 32000
      port: 9500
      targetPort: 5900
     protocol: TCP
```
 Then my node running the service is `192.168.30.12`

Then I ran 

`LONGHORN_MANAGER_IP="http://192.168.30.12:32000" npm run dev`

When I get to the UI, I still get 504s. 

Errors from terminal

```log
[HPM] Error occurred while trying to proxy request /v1/ws/1s/settings from localhost:8080 to http://192.168.30.12:32000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I can ping that machine 

```bash
ping 192.168.30.12
PING 192.168.30.12 (192.168.30.12) 56(84) bytes of data.
64 bytes from 192.168.30.12: icmp_seq=1 ttl=62 time=0.531 ms
64 bytes from 192.168.30.12: icmp_seq=2 ttl=62 time=0.353 ms
```

 What am I missing?  Happy to improve the `README.md` with more documentation once I get this running but it's been a rough start with outdated node, custom webpack configs, and little docs on how to get started.  Thank you!
