### ISSUE TITLE
[BUG] 'last-applied-tolerations' annotation is missing in shareManager pods.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2049]
**Describe the bug**
'last-applied-tolerations' annotation is missing in the Yaml of shareManager pods.

**To Reproduce**
1. Deploy longhorn v1.1.0-rc1 in a cluster having 4 nodes (1 etcd/control plane and 3 worker).
2. Create a RWX volume.
3. Check the Yaml of ShareManager pod.
4. `longhorn.io/last-applied-tolerations` is missing from the YAML.
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 
    cni.projectcalico.org/podIPs: 
  creationTimestamp: "2020-12-08T07:02:24Z"
```

**Expected behavior**
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 
    cni.projectcalico.org/podIPs: 
    longhorn.io/last-applied-tolerations: '[{"key":"persistence","operator":"Equal","value":"true","effect":"NoExecute"}]'
  creationTimestamp: "2020-12-08T07:01:06Z"
```

**Environment:**
 - Longhorn version: v1.1.0-rc1
 - Kubernetes version: 18.12
