### ISSUE TITLE
[BUG]Volumes used by MinIO workloads cannot be attached with state Degraded

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2073]
**Describe the bug**
See the title and the reproducing steps.

**To Reproduce**
1. Launch a new cluster.
2. Deploy Longhorn v1.1.0-rc1 (or master - Dec 10, 2020). Make sure:
  1. the Longhorn StorageClass is the default one.
  2. the Longhorn StorageClass replica count should be greater than the Longhorn cluster worker node count.
3. Fetch the MinIO Chart and install it with `helm`
```
git clone https://github.com/minio/charts.git
cd ./charts/minio
helm install minio . --set persistence.size=1Gi --set resources.requests.memory=100Mi --set mode=distributed
```
4. Verify if all volumes used by MinIO can be attached with state `Degraded` 

**Expected behavior**
all volumes used by MinIO can be attached with state `Degraded` 

**Log**
longhorn-csi-plugin:
```
[longhorn-csi-plugin-qn2mv longhorn-csi-plugin] time="2020-12-10T05:23:50Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"pvc-024fef2f-1f99-42e0-b89d-68fb0b3edfb5\" node_id:\"shuo-cluster-0-worker-2\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"fromBackup\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"5\" > volume_context:<key:\"staleReplicaTimeout\" value:\"2880\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1607577457259-8081-driver.longhorn.io\" > "
[longhorn-csi-plugin-qn2mv longhorn-csi-plugin] time="2020-12-10T05:23:50Z" level=error msg="GRPC error: rpc error: code = Internal desc = Post \"http://longhorn-backend:9500/v1/volumes/pvc-83c016c2-f8f0-4ae0-aa20-f5f2989c2081?action=attach\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```
longhorn-manager:
```
[longhorn-manager-xnljz] 10.42.3.205 - - [10/Dec/2020:05:23:50 +0000] "GET /v1/volumes/pvc-024fef2f-1f99-42e0-b89d-68fb0b3edfb5 HTTP/1.1" 200 4949 "" "Go-http-client/1.1"
......
[longhorn-manager-xnljz] time="2020-12-10T05:23:52Z" level=error msg="There's no available disk for replica pvc-024fef2f-1f99-42e0-b89d-68fb0b3edfb5-r-d04c6efd, size 1073741824"
[longhorn-manager-xnljz] time="2020-12-10T05:23:52Z" level=error msg="unable to schedule replica" controller=longhorn-volume frontend=blockdev node=shuo-cluster-0-worker-3 owner=shuo-cluster-0-worker-3 replica=pvc-024fef2f-1f99-42e0-b89d-68fb0b3edfb5-r-d04c6efd state=detached volume=pvc-024fef2f-1f99-42e0-b89d-68fb0b3edfb5
......
```
Notice that there is **no attach request received by longhorn manager pods**!

**Environment:**
 - Longhorn version: master - Dec 10, 2020
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.19
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 2v
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): 80GB
   - Network bandwidth and latency between the nodes: 23Gbit/s, <0.1ms
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Digital Ocean instance

**Additional context**
- If the volume replica count is not greater than worker node count, all volumes can be attached with state `Healthy`.
- I cannot reproduce it with other StatefulSet YAML files. (volume replica count is greater than the worker node count)

**Comment by shuo-wu** [comment]
There is tons of [conflicts](https://github.com/longhorn/longhorn-manager/blob/b467f4fbb9f936b91830449a125cea04c9b0b6b6/api/volume.go#L206) happens during [updating volume object](https://github.com/longhorn/longhorn-manager/blob/b467f4fbb9f936b91830449a125cea04c9b0b6b6/manager/volume.go#L321) in the VolumeAttach call. As a result, the longhorn manager cannot respond to the CSI plugin then lead to the timeout error of [calling attach](https://github.com/longhorn/longhorn-manager/blob/b467f4fbb9f936b91830449a125cea04c9b0b6b6/csi/controller_server.go#L349):

- Fail to update volume in VolumeAttach call:
```
[longhorn-manager-dv4dl] time="2020-12-10T12:12:31Z" level=debug msg="VolumeManager is attaching volume pvc-eef36232-f57a-4284-a8c1-7c1980a961fc: Prepare to update"
......
[longhorn-manager-dv4dl] time="2020-12-10T12:12:32Z" level=debug msg="VolumeManager is attaching volume pvc-eef36232-f57a-4284-a8c1-7c1980a961fc: Finish updating call with error: unable to attach volume pvc-eef36232-f57a-4284-a8c1-7c1980a961fc to shuo-longhorn-cluster-2-node-1: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-eef36232-f57a-4284-a8c1-7c1980a961fc\": the object has been modified; please apply your changes to the latest version and try again"
```

- Keep [retrying](https://github.com/longhorn/longhorn-manager/blob/b467f4fbb9f936b91830449a125cea04c9b0b6b6/api/volume.go#L206):
```
[longhorn-manager-dv4dl] time="2020-12-10T12:12:32Z" level=debug msg="Encounter conflict when updating obj: unable to attach volume pvc-eef36232-f57a-4284-a8c1-7c1980a961fc to shuo-longhorn-cluster-2-node-1: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-eef36232-f57a-4284-a8c1-7c1980a961fc\": the object has been modified; please apply your changes to the latest version and try again"
```

- Timeout error in the CSI plugin:
```
[longhorn-csi-plugin-mlzkl longhorn-csi-plugin] time="2020-12-10T12:12:30Z" level=info msg="GRPC request: {\"node_id\":\"shuo-longhorn-cluster-2-node-1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"fromBackup\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"2880\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1607602077348-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-eef36232-f57a-4284-a8c1-7c1980a961fc\"}"
[longhorn-csi-plugin-mlzkl longhorn-csi-plugin] time="2020-12-10T12:12:30Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"pvc-eef36232-f57a-4284-a8c1-7c1980a961fc\" node_id:\"shuo-longhorn-cluster-2-node-1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"fromBackup\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"2880\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1607602077348-8081-driver.longhorn.io\" > "
[longhorn-csi-plugin-mlzkl longhorn-csi-plugin] time="2020-12-10T12:12:30Z" level=debug msg="ControllerPublishVolume: volume pvc-eef36232-f57a-4284-a8c1-7c1980a961fc current nodeID is shuo-longhorn-cluster-2-node-1"
......
[longhorn-csi-plugin-mlzkl longhorn-csi-plugin] time="2020-12-10T12:12:40Z" level=error msg="GRPC error: rpc error: code = Internal desc = Post \"http://longhorn-backend:9500/v1/volumes/pvc-eef36232-f57a-4284-a8c1-7c1980a961fc?action=attach\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```


The next is, what causes the conflict, and why this bug happens only in MinIO

**Comment by PhanLe1010** [comment]
I think that the root cause was https://github.com/longhorn/longhorn-manager/pull/795

How do you think?

**Comment by PhanLe1010** [comment]
### Test steps:

**Scenarios 1:**

Test the reproduce steps in the issue's description

**Scenarios 2:**
Deploy the following statefulset. Notice the field `podManagementPolicy: "Parallel"`, it instructs Kubernetes to lunch all pods at the same time and make the issue more likely to happen.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 10 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi
```
Verify that 10 volumes are attached within 30s. 
Verify that the logs of longhorn-csi-plugin doesn't contains this timeout log:
```
[longhorn-csi-plugin-mlzkl longhorn-csi-plugin] time="2020-12-10T12:12:40Z" level=error msg="GRPC error: rpc error: code = Internal desc = Post \"http://longhorn-backend:9500/v1/volumes/pvc-eef36232-f57a-4284-a8c1-7c1980a961fc?action=attach\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```
