### ISSUE TITLE
[BUG]Engine Image fail to reach `ready` state if there are tainted worker node

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2081]
**Describe the bug**
Engine Image fail to reach `ready` state if there are tainted worker node in the cluster and Longhorn doesn't tolerate the taint.

**To Reproduce**
1. Install Longhorn
2. Taint one of the node, then delete the engine image daemonset to allow recreation
3. Volume operations (attach/detach) will fail due to engine image is not ready.

**Expected behavior**
Volume operations should still work.

**Log**
```
2020-12-09T13:34:19.849639616-05:00 time="2020-12-09T18:34:19Z" level=error msg="Error in request: unable to attach volume pvc-xxx to xxx: cannot attach volume pvc-xxx7 with image longhornio/longhorn-engine:v1.0.2: engine image ei-ee18f965 (longhornio/longhorn-engine:v1.0.2) is not ready, it's deploying"
```
```
typemeta:
    kind: ""
    apiversion: ""
  objectmeta:
    name: engine-image-ei-ee18f965
...
  status:
    currentnumberscheduled: 6
    numbermisscheduled: 1
    desirednumberscheduled: 6
    numberready: 6
    observedgeneration: 1
    updatednumberscheduled: 6
    numberavailable: 6
    numberunavailable: 0
    collisioncount: null
    conditions: []
```

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.18.6
 - Node config
   - OS type and version: RHEL
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: 10GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

**Additional context**
It's due to the tainted node prevent the daemonset to reach the full availability, result in engine image object failed to reach ready state.

Ideally, each manager on the node should only care about the engine image status of it's node rather than the whole readiness or not.
