### ISSUE TITLE
[FEATURE]Support CSI fsGroupPolicy

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2131]
https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/

Ref:
#1221
https://github.com/longhorn/longhorn/issues/1842#issuecomment-749522327

Note: Manual test plan is required because:
1. We haven't had the v1.20 test environment ready yet.
2. Need to make sure we can speed up the fsgroup change

Applicable Kubernetes version: v1.20+

**Comment by PhanLe1010** [comment]
From the Kubernetes' code perspective, it looks like everything should work fine.

There are 3 cases we need to consider:
1. Kubernetes v1.19 with `CSIVolumeFSGroupPolicy` enabled
1. Kubernetes v1.20 with `CSIVolumeFSGroupPolicy` disabled
1. Kubernetes v1.20 with `CSIVolumeFSGroupPolicy` enabled

Case#1 and Case#3 should work because when `CSIVolumeFSGroupPolicy` is enabled, Kubernetes automatically fills in the default value for [fsGroupPolicy: ReadWriteOnceWithFSType](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/apis/storage/fuzzer/fuzzer.go#L88). Therefore, we don't have this [error](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/volume/csi/csi_plugin.go#L912)

Case#2 should also work because when `CSIVolumeFSGroupPolicy` is disabled, Kubernetes automatically [clears FSGroupPolicy](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/registry/storage/csidriver/strategy.go#L56) field but it checks the feature [CSIVolumeFSGroupPolicy gate here](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/volume/csi/csi_plugin.go#L882) and returns immediately. Therefore,  we shouldn't have the [error](https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/volume/csi/csi_plugin.go#L912) neither.

**Comment by PhanLe1010** [comment]
@Khushboo already verified that Case#1 and Case#3 working as expected.
We are verifying Case#2

**Comment by khushboo-rancher** [comment]
Validated the longhorn basic functionality with v1.20, It looks good.

As mentioned in the https://github.com/longhorn/longhorn/issues/2131#issuecomment-750746830 Longhorn is validated with the below cases.

1. Kubernetes v1.19 with CSIVolumeFSGroupPolicy enabled
2. Kubernetes v1.20 with CSIVolumeFSGroupPolicy disabled
3. Kubernetes v1.20 with CSIVolumeFSGroupPolicy enabled

Running the integration test on the case#2, will update the result.

**Comment by joshimoo** [comment]
@PhanLe1010 the fuzzer you linked  to is code used only for testing, as recognized by the fact of the usage of random here :)
https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/apis/storage/fuzzer/fuzzer.go#L43

So in the case where the feature gate exists and the driver object exists as well as not having defined a FSgroup setting, we will trigger this error:
https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/volume/csi/csi_plugin.go#L912

**Comment by PhanLe1010** [comment]
@joshimoo 

> the fuzzer you linked to is code used only for testing, as recognized by the fact of the usage of random here :)
https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/apis/storage/fuzzer/fuzzer.go#L43
So in the case where the feature gate is enabled and the driver object exists as well as not having defined a .Spec.FSGroupPolicy setting, we will trigger this error:
https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/volume/csi/csi_plugin.go#L912

Thank you for pointing out the mistake in the coded link. Yeah, it is testing code. The default values are filled here instead https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/apis/storage/v1/defaults.go#L56. So it is not possible that ` the feature gate is enabled and the driver object exists as well as not having defined a .Spec.FSGroupPolicy setting`. Moreover, if K8s don't fill the `.Spec.FSGroupPolicy`, it will break many CSI providers. I think that K8s must already consider that. 

> Do we define .Spec.FSGroupPolicy when creating the driver object?

No, we don't define. We actually cannot define it. The reason is that we are using client-go v1.16, and it doesn't have the field `.Spec.FSGroupPolicy` in CSIDriver struct. So, we depend on the K8s to fill in the default value for `.Spec.FSGroupPolicy`.

**Comment by PhanLe1010** [comment]
# Analysis

### 1. Running pod as non-root user and the problem

It is good practice to run pod as a non-root user to prevent bugs or malicious code from taking over the system. An example of a pod that runs as non-root user could be:
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
```
The above YAML file tells Kubernetes to run every process of every container inside the pod with user ID 1000 and primary group ID 3000. So far so good, processes are not running as root. However, there is a problem here. If the volume `sec-ctx-vol` contains files/directories that the user ID 1000 and the group ID 3000 don't have permission to access, the processes in the pod cannot access those files/directories. In the worst case, if the root of the volume `sec-ctx-vol` don't have read/write permission for user ID 1000 and group ID 3000, all processes cannot access the volume.

### 2.  `fsGroup` and the problem 

To solve the above problem, users can specify the field `fsGroup`  as below:
```
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
```
Upon seeing the field `fsGroup: 2000`, Kubernetes will take the following actions:
 1.  Make sure that all processes of the containers inside the pod are part of the supplementary group ID 2000 
 2. Any new files created in the volume `sec-ctx-vol` will be Group ID 2000
 3. If `fsType` of the PersistentVolumes is defined and the PersistentVolumes's accessModes is RWO, then Kubernetes will attempt to modify the volume ownership and permissions (to be Group ID 2000 in this case) every time the volume is mounted to the pod.

So, adding the field `fsGroup: 2000` solves the problem we see in section 1. However, `fsGroup` introduces a new problem as described in [K8s doc](https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-users-to-skip-recursive-permission-changes-on-mount):
> The side-effect of setting fsGroup is that, each time a volume is mounted, Kubernetes must recursively chown() and chmod() all the files and directories inside the volume - with a few exceptions noted below. This happens even if group ownership of the volume already matches the requested fsGroup, and can be pretty expensive for larger volumes with lots of small files, which causes pod startup to take a long time. 

The bad news is that there is no workaround for this problem in K8s version v1.19 and before. The good news is that K8s v1.20 provides 2 options to solve this problem as discussed in the following sections.

### 3. [pod.spec.securityContext.fsGroupChangePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)
In section 1, K8s never modifies the volume ownership and permissions before giving it to the pod. In section 2, K8s always recursively modifies the volume ownership and permissions before giving it to the pod. Each of them has its own problem as mentioned.

Since version v1.20,  Kubernetes introduces a new beta feature: the field `fsGroupChangePolicy`. When  `fsGroupChangePolicy` is set to `OnRootMismatch`, if the root of the volume already has the correct permissions, the recursive permission and ownership change will be skipped. It means that if users don't change the `pod.spec.securityContext.fsGroup ` between pod's restarts, K8s will only have to check the permissions and ownership of the root and the mounting process will be much faster compared to always recursively change the volumes' ownership and permissions. 

Note that K8s v1.20 still allows users to keep the previous behavior. By setting `fsGroupChangePolicy` to `always`, K8s always changes permission and ownership of the volume when volume is mounted. 

Note: if users don't set `fsGroupChangePolicy`, it will be the same as setting `fsGroupChangePolicy` to `always`

### 4. [csiDriver.spec.fsGroupPolicy](https://kubernetes-csi.github.io/docs/support-fsgroup.html)

For certain volume types, such as NFS or Gluster, the cluster doesn’t perform recursive permission changes even if the pod has a `fsGroup`. So, K8s v1.20 even optimizes the volume's permissions checking process further by allowing the CSI storage providers to explicitly indicate whether or not they support modifying a volume's ownership or permissions when the volume is being mounted.
CSI providers can specify the following values for `csiDriver.spec.fsGroupPolicy`:
* `None`: Indicates that volumes will be mounted with no modifications, as the CSI volume driver does not support these operations.
* `File`: Indicates that the CSI volume driver supports volume ownership and permission change via fsGroup, and Kubernetes may use fsGroup to change permissions and ownership of the volume to match user requested fsGroup in the pod's SecurityPolicy regardless of fstype or access mode.
* `ReadWriteOnceWithFSType`: Indicates that volumes will be examined to determine if volume ownership and permissions should be modified to match the pod's security policy. Changes will only occur if the fsType is defined and the persistent volume's accessModes contains ReadWriteOnly.

Note:
1. If undefined, `csiDriver.spec.fsGroupPolicy` will default to `ReadWriteOnceWithFSType`, keeping the previous behavior.
1. when `csiDriver.spec.fsGroupPolicy` is set to `None` or `File`, it will overwrite the setting for `pod.spec.securityContext.fsGroupChangePolicy`. Users of the CSI provider cannot control the volume's permissions checking process in those cases. 

### Conclusion 
1. As tested in https://github.com/longhorn/longhorn/issues/2131#issuecomment-754182609, Longhorn works with Kubernetes v1.20 by default. Also, Kubernetes automatically set  `csiDriver.spec.fsGroupPolicy=ReadWriteOnceWithFSType` for Longhorn CSI driver since Longhorn doesn't specify it.
2. Longhorn should not change the `csiDriver.spec.fsGroupPolicy` to a value different than the default value `ReadWriteOnceWithFSType` because Longhorn only provides block device storage. Base on the filesystem and volume access mode, the users of Longhorn block devices should be able to control the volume's permissions checking process by setting `pod.spec.securityContext.fsGroupChangePolicy`. If Longhorn sets `csiDriver.spec.fsGroupPolicy` to `None` or `File`, it will overwrite the setting `pod.spec.securityContext.fsGroupChangePolicy`. 

In a nutshell, Longhorn doesn't need to do anything to support `csiDriver.spec.fsGroupPolicy` and `pod.spec.securityContext.fsGroupChangePolicy` in Kubernetes v1.20

----------------------

# Testing

The above analysis is supported by the linked documents and the below tests. 

### 1. Running pod as non-root but don't set `pod.spec.securityContext.fsGroup`
1. Remove the read, write, and execute for other users on Longhorn volume's root. I.e., change permission for Longhorn volume's root to `drwxr-x---`. In order to do that, we will first running the flowing pod as root:
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sec-ctx-vol-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 30Gi  
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. exec into the pod, and create some file
    ```
    root@security-context-demo:/data# id
    uid=0(root) gid=0(root) groups=0(root)
    root@security-context-demo:~# cd /data/
    root@security-context-demo:/data# ls -l
    total 4
    drwxr-xr-x 3 root root 4096 Feb 15 00:05 demo
    root@security-context-demo:/data# ls demo/ -l
    total 16
    drwx------ 2 root root 16384 Feb 15 00:05 lost+found
    root@security-context-demo:/data# chmod 750 demo/
    root@security-context-demo:/data# ls -l
    total 4
    drwxr-x--- 3 root root 4096 Feb 15 00:05 demo
    ```
1. Now delete the above pod, re-deploy the pod as non-root user by adding `runAsUser`, and `runAsGroup `. Note that we don't add `fsGroup `:
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. Exec into the pod. Observe that we cannot access directory `/data/demo` as user ID 1000 and primary group ID 3000
    ```
    I have no name!@security-context-demo:/$ id
    uid=1000 gid=3000 groups=3000
    I have no name!@security-context-demo:/$ ls /data/ -l
    total 4
    drwxr-x--- 3 root root 4096 Feb 15 00:05 demo
    I have no name!@security-context-demo:/$ ls /data/demo -l
    ls: cannot open directory '/data/demo': Permission denied
    I have no name!@security-context-demo:/$ touch /data/demo/file.txt   
    touch: cannot touch '/data/demo/file.txt': Permission denied
    ```
### 2. Running pod as non-root and set `pod.spec.securityContext.fsGroup`
1. Delete the above pod. Re-deploy the pod and add `fsGroup: 2000`  as bellow:
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. Exec into the pod, we can see that Kubernetes did 3 actions as mentioned in section # 2 in the above analysis.
    ```
    I have no name!@security-context-demo:/$ id
    uid=1000 gid=3000 groups=3000,2000
    I have no name!@security-context-demo:/$ ls /data/ -l
    total 4
    drwxrws--- 3 root 2000 4096 Feb 15 00:05 demo
    I have no name!@security-context-demo:/$ cd /data/demo/
    I have no name!@security-context-demo:/data/demo$ ls -l
    total 16
    drwxrws--- 2 root 2000 16384 Feb 15 00:05 lost+found
    I have no name!@security-context-demo:/data/demo$ echo "hello world" > file.txt
    I have no name!@security-context-demo:/data/demo$ ls -l
    total 20
    -rw-r--r-- 1 1000 2000    12 Feb 15 00:46 file.txt
    drwxrws--- 2 root 2000 16384 Feb 15 00:05 lost+found
    ```
1. One key point to take away is that Kubernetes did recursively change ownership and permissions for every file/directory in the Longhorn volume. 
1. Now, to see the problem with recursively change ownership and permissions. Let's create a lot of files inside `/data/demo/files`. We can use the following script to generate the files:
    ```
    #!/bin/bash
    file_prefix="longhorn-file-"

    POSITIONAL=()
    while [[ $# -gt 0 ]]; do
            key="$1"
            case $key in
                    -c|--count)
                    count="$2"
                    shift # past argument
                    shift # past value
                    ;;
                    -h|--help)
                    help="true"
                    shift
                    ;;
                    *)
                    echo "Error! invalid flag: ${key}"
                    help="true"
                    break
                    ;;
            esac
    done

    usage () {
            echo "USAGE: $0 --count 10000"
            echo "  [-c|--count] number of file to be created inside the current folder"
            echo "  [-h|--help] Usage message"
    }

    if [[ $help ]]; then
            usage
            exit 0
    fi

    set -e -x


    if [[ $count ]]; then
        i="0"
            while [ $i -lt $count ]
        do
        dd if=/dev/urandom of="$file_prefix$i" count=1 bs=512
        i=$[$i+1]
        done
    fi
    ```
1. Copy the script into `/data/demo/files/create_file.sh`. 
    ```
    kubectl cp create-file.sh default/security-context-demo:data/demo/files
    ```
1. Create 500000 files of 512 bytes inside `data/demo/files`:
    ```
    I have no name!@security-context-demo:/$ cd /data/demo/files/
    I have no name!@security-context-demo:/data/demo/files$ ls -l
    total 4
    -rwxr-xr-x 1 1000 2000 663 Feb 15 01:02 create-file.sh
    create-file.sh
    I have no name!@security-context-demo:/data/demo/files$ ./create-file.sh --count 500000
    ```
1. Let's see how long it takes Kubernetes to remount Longhorn volume. Let's delete the pod and re-deploy it as in step 1 of this test case. Observe that it takes 3m30s for Kunertes to finish mounting the Longhorn volume.
1. Observe that it takes 15 mins for Kunertes to finish mounting the Longhorn volume if we create 2 millions files inside `/data/demo/files/`

### 3.  Set `pod.spec.securityContext.fsGroupChangePolicy= OnRootMismatch`
1. Delete the pod. Re-deploy the pod with `pod.spec.securityContext.fsGroupChangePolicy= OnRootMismatch`
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. Observe that it takes only 13s for Kubernetes to finish mounting the Longhorn volume and the pod is in running state. It is because we didn't change the `pod.spec.securityContext.fsGroup`. So, it is matched with the volume root group ownership and Kubernetes doesn't recursively perform the chown()and chmod()
1. Let's change the `fsGroup` to 5000, delete the pod, and re-deploy the pod as:
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 5000
        fsGroupChangePolicy: "OnRootMismatch"
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. Because the `fsGroup` doesn't match the volume root group ownership. Kubernetes recursively perform the chown()and chmod(). Observe that it takes 3m30s for Kunertes to finish mounting the Longhorn volume.


### 4.  Test csiDriver.spec. fsGroupPolicy
So far we have seen the behavior of Kubernetes when the `csiDriver.spec.fsGroupPolicy` is set to `ReadWriteOnceWithFSType` which is the default value. Let's see what happens when we  `csiDriver.spec.fsGroupPolicy` is set to `None` which indicates that volumes will be mounted with no modifications.

1. Delete the pod from the previous step. Delete the PVC `sec-ctx-vol-pvc` which will automatically delete the corresponding PV and Longhorn volume.
1. Delete Longhorn CSI driver CR
    ```
    kubectl delete csidriver driver.longhorn.io
    ``` 
1. Re-create Longhorn CSI driver CR with `spec.fsGroupPolicy` set to `None`:
    ```
    apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      annotations:
        driver.longhorn.io/kubernetes-version: v1.20.2+k3s1
        driver.longhorn.io/version: v1.1.0
      creationTimestamp: "2021-02-11T20:01:07Z"
      name: driver.longhorn.io
      resourceVersion: "50138"
      uid: 92358d9f-f82c-4157-975e-ec0120955591
    spec:
      attachRequired: true
      # fsGroupPolicy: None
      podInfoOnMount: true
      volumeLifecycleModes:
      - Persistent
    ```

1. Deploy the following pod:
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sec-ctx-vol-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 30Gi  
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. exec into the pod. Remove the read, write, and execute for other users on Longhorn volume's root. I.e., change permission for Longhorn volume's root to `drwxr-x---`.
    ```
    root@security-context-demo:/data# id
    uid=0(root) gid=0(root) groups=0(root)
    root@security-context-demo:~# cd /data/
    root@security-context-demo:/data# chmod 750 demo/
    root@security-context-demo:/data# ls -l
    total 4
    drwxr-x--- 3 root root 4096 Feb 15 00:05 demo
    ```
1. Now delete the above pod, re-deploy the pod as:
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: security-context-demo
      namespace: default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "Always"
      restartPolicy: Always
      containers:
      - name: sec-ctx-demo
        command: [ "sh", "-c", "sleep 1h" ]
        image: ubuntu
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      volumes:
      - name: sec-ctx-vol
        persistentVolumeClaim:
          claimName: sec-ctx-vol-pvc
    ```
1. Exec into the pod. Observe that we cannot access directory `/data/demo` as user ID 1000, primary group ID 3000, and supplemental group ID 2000
    ```
    I have no name!@security-context-demo:/$ id
    uid=1000 gid=3000 groups=3000,2000
    I have no name!@security-context-demo:/$ ls /data/ -l
    total 4
    drwxr-x--- 3 root root 4096 Feb 15 00:05 demo
    I have no name!@security-context-demo:/$ ls /data/demo -l
    ls: cannot open directory '/data/demo': Permission denied
    I have no name!@security-context-demo:/$ touch /data/demo/file.txt   
    touch: cannot touch '/data/demo/file.txt': Permission denied
    ```
We can see that setting `csiDriver.spec.fsGroupPolicy` to `None` will overwrite the setting `pod.spec.securityContext.fsGroupChangePolicy`. From Longhorn perspective, we don't want to overwrite this as explained in section # 4 in the above analysis.

**Comment by yasker** [comment]
Thanks, @PhanLe1010 , it's a well-written explanation. 

I also feel that we should put this either into our documentation or KB.

After that, I will leave it for QA to verify the result, then we can close it.

**Comment by yasker** [comment]
FYI: During the team meeting, we decide that we should write a KB article for the issue.

**Comment by carpenike** [comment]
Hey Folks,

I'm running into this problem and it seems as though _something_ needs to be set in the csidriver. Even with the securityContext defined in the pod I'm still getting the `kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string`.

I've got this defined in spec.securityContext
```
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
```
