### ISSUE TITLE
[BUG] Volume isn't assigned to node with 2 nodes

### ISSUE THREAD

**Issue by WesleyVestjens** [longhorn/longhorn#2138]
**Describe the bug**
We have a setup with with 2 worker nodes (RKE + Longhorn). We have 3 PVC's that get bound to a PV, but while they should be attached to a node, they remain unattached. The longhorn-manager logs mention that there are no eligible nodes or disks or that there is insufficient space (which is not the case - we have 137 Gi assignable on in total 2 nodes).

**To Reproduce**
I don't really know if this is easily reproducible.

**Expected behavior**
I have configured 2 replicas, so I expect the volumes to come online/be attached to a node since there are 2 nodes/disks available.

**Log**
Sent to the support e-mail address provided.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.2.3, k8s v1.18.12, Docker v20.10.1
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 6x2000MHz
   - Memory per node: 8192Mb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: Virtually non-existant, same private network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): CloudStack

**Additional context**
As discussed on Slack on 25-12-2020: https://cloud-native.slack.com/archives/CNVPEL9U3/p1608822974324500

**Comment by WesleyVestjens** [comment]
On Slack you mentioned it might be related to the ConfigMap, see #2119, but I don't think that's the case, the ConfigMap also refers to 2 replica's:

```
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
[...]
    parameters:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
      fromBackup: ""
      baseImage: ""
```
