### ISSUE TITLE
Unable to write to RWX Volume if user is not root

### ISSUE THREAD

**Issue by venomone** [longhorn/longhorn#2145]
Hey folks,

I have longhorn 1.1.0 installed but the problem is that if I use the natively RWX integration im not able to write to a volume if the container runs as a other user than root uid/gid != 1000 it seems.
Is this Issue already known?

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-pv-claim
  namespace: echo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
```

Kind regards

**Comment by joshimoo** [comment]
This is because in the current share-manager (nfs) server we don't squash and the share manager is running as root.
https://github.com/longhorn/longhorn-share-manager/blob/master/pkg/server/nfs/export.go#L159

squashing comes with it's own problems, I want to make this behavior user defined in a future release.
@venomone as a workaround are you able to `chmod -R +777` or `chown` the nfs mount dir from a root init container?

**Comment by chrisu001** [comment]
@joshimoo. Thanks for your advice

Unfortunately , the workaround is not an option on secured Kubernetes distributions like OKD (rootless containers)  or activated PodSecurityPolicies.
Longhorn RWX-pvs are mounted in OKD as uid=99,gid=99 with 755 permission, so the pod has no write-permissons 

solution might be to to support g+rwx mounts as default, then  
```
      securityContext:
        supplementalGroups: [99]
```
could be used?
sorry.. I am too far away of understanding the chain between longhorn-volumes-> mananger-> nfs->OKD->pod....

**Comment by venomone** [comment]
Well for the moment I will stay with the old-style of deploying NFS shares manually.

**Comment by raelix** [comment]
Hello, @yasker we are facing the same issue with the new Longhorn 1.1.0 and nfs. The volumes are mounted as uid=99,gid=99, Is there a possible automated work-around for this?

Thanks in advance

**Comment by venomone** [comment]
Hello,

well as already explained you can create the share manually, like in version < 1.1

Please check the following example for the NFS:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: longhorn-nfs-provisioner-datastore
spec:
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
    - DAC_READ_SEARCH
    - SYS_RESOURCE
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - hostPath
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: longhorn-nfs-provisioner-datastore
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["datastore-nfs"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: longhorn-nfs-provisioner-datastore
subjects:
  - kind: ServiceAccount
    name: longhorn-nfs-provisioner-datastore
    namespace: longhorn-system
roleRef:
  kind: ClusterRole
  name: longhorn-nfs-provisioner-datastore
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
subjects:
  - kind: ServiceAccount
    name: longhorn-nfs-provisioner-datastore
    namespace: longhorn-system
roleRef:
  kind: Role
  name: leader-locking-longhorn-nfs-provisioner-datastore
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
---
kind: Service
apiVersion: v1
metadata:
  name: longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
  labels:
    app: longhorn-nfs-provisioner-datastore
spec:
  # hardcode a cluster ip for the service
  # so that on delete & recreate of the service the previous pv's still point
  # to this nfs-provisioner, pick a new ip for each new nfs provisioner
  clusterIP: 10.43.99.2
  ports:
    - name: nfs
      port: 2049
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: longhorn-nfs-provisioner-datastore
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-nfs-provisioner-datastore
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: longhorn-nfs-provisioner-datastore
    spec:
      serviceAccount: longhorn-nfs-provisioner-datastore
      containers:
        - name: longhorn-nfs-provisioner-datastore
          image: quay.io/kubernetes_incubator/nfs-provisioner:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: nlockmgr
              containerPort: 32803
            - name: nlockmgr-udp
              containerPort: 32803
              protocol: UDP
            - name: mountd
              containerPort: 20048
            - name: mountd-udp
              containerPort: 20048
              protocol: UDP
            - name: rquotad
              containerPort: 875
            - name: rquotad-udp
              containerPort: 875
              protocol: UDP
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
            - name: statd
              containerPort: 662
            - name: statd-udp
              containerPort: 662
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=nfs.longhorn.io/datastroe-nfs"
            - "-device-based-fsids=false"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: longhorn-nfs-provisioner-datastore
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            exec:
              command:
                - ls
                - /export
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - ls
                - /export
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: longhorn-nfs-provisioner-datastore
      # we want really quick failover
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 60
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nfs-provisioner-datastore
  namespace: longhorn-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 55Gi # make this 10% bigger then the workload pvc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: datastore-nfs # workload storage class
provisioner: nfs.longhorn.io/datastroe-nfs
mountOptions:
  - "vers=4.1"
  - "noresvport"
```


For the PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: datastore-nfs
  resources:
    requests:
      storage: 50Gi
```

and at you deployment yaml:
```
volumeMounts:
        - name: datastore-persistent-storage
          mountPath: /some/path/inside/your/pod
....
volumes:
      - name: datastore-persistent-storage
        persistentVolumeClaim:
          claimName: datastore-pv-claim
```
