### ISSUE TITLE
[BUG] Newly installed 1.1.0 on Kubernetes and UI editing broken

### ISSUE THREAD

**Issue by skandragon** [longhorn/longhorn#2156]
**Describe the bug**

I installed from Helm, and made no changes to the default settings.

When I go to the UI, I see a different experience than I expect.  For example, clicking on "save" for settings does nothing in any tab, although I can create volumes through the UI and delete them.  I can view as well.

I cannot initiate any backups, configure anything (nodes, resize a volume, etc) nor can I save any settings.

I see this in my Browser console:

> Access to XMLHttpRequest at 'wss://longhorn.svc.rpi.flame.org/v1/nodes/kube10.rpi.flame.org' from origin 'https://longhorn.svc.rpi.flame.org' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

**To Reproduce**
* See above for installation and reproduction steps.

**Expected behavior**
UI admin to work. :)

**Environment:**

### Browner
Chrome latest (Version 87.0.4280.88 (Official Build) (x86_64))

Note that it WORKS on Safari, so this may be some sort of Chrome incompatibility.  

### Kubernetes and other

 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubernetes v1.20.0
 - Node config
   - OS type and version: ubuntu 20
   - CPU per node: 3 or 8 cores
   - Memory per node: 8 or 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: 1 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): bare metal

**Comment by skandragon** [comment]
BTW, if desired I can provide access to this cluster's longhorn UI.  Also, longhorn seems pretty amazing so far.

**Comment by joshimoo** [comment]
This seems to be an issue with Traefik (CORS), a previous issues has a workaround.
Can you try the workaround (middleware) mentioned here:
https://github.com/longhorn/longhorn/issues/1442#issuecomment-639761799

**Comment by skandragon** [comment]
This does seem to be a workaround, but I do feel it should not be necessary.  That said, I'll close this issue and let the other track the issue.

Thanks!

**Comment by skandragon** [comment]
I spoke too soon.  I am still having this problem with the work-around applied.  Some things work (triggering a backup, for instance) but editing configuration does not.

**Comment by joshimoo** [comment]
Can you restart your browser with the workaround applied and see what kind of logs you are getting, same as before?

**Comment by skandragon** [comment]
Yep, did that.  In fact, used another computer.  :)

**Comment by joshimoo** [comment]
What error are you getting when trying to change settings?
javascript console error?
loghorn ui log error?

**Comment by skandragon** [comment]
The CORS error reported above.

**Comment by joshimoo** [comment]
@smallteeths Any idea on this, the middleware posted in the other thread seemed to work as a workaround before?

**Comment by skandragon** [comment]
To be sure I've applied it correctly, here is the configuration I have in place:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.svc.rpi.flame.org`)
    middlewares:
    - name: frontend-auth
    services:
    - kind: Service
      name: longhorn-frontend
      port: 80
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
  tls:
    secretName: cert-wildcard
```

**Comment by smallteeths** [comment]
![Jietu20210108-201258](https://user-images.githubusercontent.com/27733391/104014598-42d12080-51ee-11eb-8db8-b2283e363bb9.jpg)
![Jietu20210108-113540](https://user-images.githubusercontent.com/27733391/104014610-4bc1f200-51ee-11eb-90c8-c632fa33e618.jpg)

I tested it and it works @joshimoo . 
I am not sure if this error is related to the middleware `frontend-auth` you configured @skandragon

**Comment by schwebke** [comment]
I am facing the same issue here, for example updating some global settings. These updates are ignored via traefik. Workaround setting the header via traefik does not help.

By direct comparison of direct access via NodePort and access via traefik 2 IngressRoute I am getting a CORS error using traefik. The frontend tries to POST to an ws URL!
Loading via nodeport the POST works, and the POST is targeted to the REST endpoint. This makes also much more sense to me.
Here the two browser consoles side by side -- upper side via traefik, lower side via nodeport:
![screenshot](https://user-images.githubusercontent.com/6435375/104584871-851db600-5663-11eb-838a-90663f55fa22.png)
Is it possible exposing the app through traefik does confuse some URL schemes on the client side?

**Comment by smallteeths** [comment]
Oh, that's weird. It looks like treafik upgraded the http request to a ws request. Is this the only request that reports an error? @schwebke

**Comment by schwebke** [comment]
yes -- and I do not see a upgrade handshake for this one. It's hard to debug with my prod build, but it looks like directly issued via xmlhttprequest to ws://...
@smallteeths

**Comment by smallteeths** [comment]
![Jietu20210114-202420](https://user-images.githubusercontent.com/27733391/104590679-a0f67b80-56a6-11eb-806a-1bc2eb9a819f.jpg)
There is indeed a problem with this, the data returned by the settings ws interface is incorrect under the ingressRoute proxy. @joshimoo 

The correct one should be as shown below
![Jietu20210114-202657](https://user-images.githubusercontent.com/27733391/104590953-ff235e80-56a6-11eb-86c6-39454f557b7b.jpg)

**Comment by timothystewart6** [comment]
CORS websocekt errors here, only fors Longhorn UI. The rest of Rancher + traefik works fine.

UI says `Request failed with status code 405` when trying to create a snapshotbackup

```
```

**Comment by brunnels** [comment]
I can confirm I'm seeing the same.  The workaround middleware is okay for monitoring.  If I want to actually make any changes I have to switch service/longhorn-frontend to LoadBalancer and access the IP directly.

I did notice that while going through traefik I can perform the same action several times and it will eventually work but it's frustrating and inconsistent.

**Comment by innobead** [comment]
Closing, because we have a KB to talk about this issue, https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/.

**Comment by brunnels** [comment]
@innobead The KB talks about the fix being the middleware added to the route but we've already reported in this issue that the middleware fix did not completely resolve all status code 405 errors.

It would also be good if the KB example could be updated to use an `IngressRoute` since most people using traefik 2.x no longer use `Ingress`

**Comment by brunnels** [comment]
@innobead I wanted to confirm I didn't do anything wrong when testing before so I spun up a new cluster and tried again.  I can confirm that the KB article fixes the issues I was experiencing.

I also created a snapshot backup and deleted it to try and replicate @timothystewart6 issue.  I had no problems with this either.

I think my failing before was trying to add the additional header to the middleware defined here https://traefik.io/blog/install-and-configure-traefik-with-helm/ rather than doing a separate middleware.

Here's my IngressRoute:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.cloud.example.org`)
    services:
    - name: longhorn-frontend
      port: 80
    middlewares:
    - name: longhorn-system-svc-longhorn-headers@kubernetescrd
```
