### ISSUE TITLE
[Question] backup/snapshot hooks

### ISSUE THREAD

**Issue by antonum** [longhorn/longhorn#2164]
How do I configure Longhorn backup so it executes some bash scripts in the pod before and after snapshot/backup is taken?

Something similar to [Velero's backup hooks](https://velero.io/docs/v1.5/backup-hooks/#specifying-hooks-as-pod-annotations).

```
  annotations:
    backup.velero.io/backup-volumes: data
    pre.hook.backup.velero.io/command: "['/usr/bin/mysql', '-e', '\"flush tables with read lock;\"']"
    pre.hook.backup.velero.io/container: mysql
    post.hook.backup.velero.io/command: "['/usr/bin/mysql', '-e', '\"unlock tables;\"']"
    post.hook.backup.velero.io/container: MySQL
```

**Environment:**
 - Longhorn version: 1.1
 - Kubernetes version: 1.18.10

**Additional context**
An application running in k8s needs to be backed up in a "consistent" state. There are commands that can be executed to achieve that:
```
app_freeze
do_storage_level_backup
app_thaw

```
