### ISSUE TITLE
[Question] Remote NFS Server

### ISSUE THREAD

**Issue by duhruh** [longhorn/longhorn#2184]
**Question**
Sorry if this isn't the right forum for this type of question but i've been searching all the docs and trying to understand if longhorn even supports this yet.

I have a external NFS server managed by different software and i'm trying to figure out how I could tell longhorn to dynamically mount a directory from that server and provide that to the cluster longhorn is running on.

I assumed longhorn filled in the gap here: https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner for NFS

to allow it to create something like this to be created
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: MY_REMOTE_SERVER_HERE.com
    path: "/"
```

If this functionally does exist i'm having a hard time finding the documentation on it.  Any help or pointers on this would be greatly appreciated 🙏
