### ISSUE TITLE
[FEATURE] Enhance Longhorn data plane on low performance environment (spinning disk, 1GBps network, low CPU etc)

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2206]
Based on the result from #1691 , we found the spinning disk doesn't work well with Longhorn. It's a current limitation but there are still many users using spinning disk out there. We need to investigate the Longhorn data path to find out the bottleneck/root cause of the spinning disk that doesn't work well and easily disconnected from Longhorn.

**Comment by shuo-wu** [comment]
### The way to control latency
1. Use the following script to create a delayed target via  `dmsetup` (Ref: https://enodev.fr/posts/emulate-a-slow-block-device-with-dm-delay.html):
```
#!/bin/sh
size=$(blockdev --getsize $1) # Size in 512-bytes sectors
echo "0 $size delay $1 0 500" | dmsetup create delayed
```
2. Run `fio` tests to verify the latency
3. Mount the corresponding disk `/dev/dm-0` to a mount point then introduce the mount point on Longhorn Node page

@PhanLe1010

**Comment by PhanLe1010** [comment]
Initial test result:

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE with Kubernetes v1.19.7
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 16.04.4 LTS
   - CPU per node: 2
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): EBS volume using spinning disk. The worst type of spinning disk in AWS
      
      <img width="646" alt="Screen Shot 2021-01-26 at 5 27 04 PM" src="https://user-images.githubusercontent.com/22139961/105929428-6670d500-5ffc-11eb-93ac-0cb01f51f478.png">

   - Network bandwidth between the nodes: up to 1 Gbps bandwidth 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2, the nodes are t2.large instances

**Workload:**
I deploy the following statefulset to test the Longhorn system:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell 
  serviceName: "shell"
  replicas: VARIABLE
  template:
    metadata:
      labels:
        app: shell 
    spec:
      restartPolicy: Always
      containers:
      - name: shell
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "n=0; while true; do dd if=/dev/urandom of=/mnt/file count=100000 bs=1K status=progress; sync; cat /mnt/file > /dev/null; rm /mnt/file; n=$((n+1)); echo running count: $n; done"]
        volumeMounts:
        - name: magnetic
          mountPath: /mnt/
        imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: magnetic
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn-magnetic"
      resources:
        requests:
          storage: 5Gi
```
This workload does intensively read/write to Longhorn volumes

**Observation:**
1. Incrementally increase the value `replicas: VARIABLE` from 1 to 3. Everything running ok. An excerpt of the log from one of the workload pod:
   ```
   11148288 bytes (11 MB, 11 MiB) copied, 1 s, 11.1 MB/s
   19811328 bytes (20 MB, 19 MiB) copied, 2 s, 9.9 MB/s 
   27597824 bytes (28 MB, 26 MiB) copied, 3 s, 9.2 MB/s
   39123968 bytes (39 MB, 37 MiB) copied, 4 s, 9.8 MB/s
   51320832 bytes (51 MB, 49 MiB) copied, 5 s, 10.3 MB/s
   63299584 bytes (63 MB, 60 MiB) copied, 6 s, 10.5 MB/s
   75100160 bytes (75 MB, 72 MiB) copied, 7 s, 10.7 MB/s
   87510016 bytes (88 MB, 83 MiB) copied, 8 s, 10.9 MB/s
   99921920 bytes (100 MB, 95 MiB) copied, 9 s, 11.1 MB/s
   100000+0 records in
   100000+0 records out
   102400000 bytes (102 MB, 98 MiB) copied, 9.19789 s, 11.1 MB/s
   running count: 19
   ```
1. Incrementally increase the value `replicas: VARIABLE` to 4 and 5. Volumes start degrading and the system enters a chaotic situation in which many volumes start rebuilding. 

1. From the initial test, It seems the spinning disk is not a no-go for Longhorn, and Longhorn can still work with spinning disks until some load limit. 

**Next step:**
I will increase the network bandwidth to see if we can increase `replicas: VARIABLE` to 4, 5, and above.
