### ISSUE TITLE
[ENHANCEMENT] Change VolumeSnapshotClass API version to v1 from v1beta1 in documentation

### ISSUE THREAD

**Issue by antonum** [longhorn/longhorn#2214]
**Describe the bug**
Volume snapshot is now a released API. Version needs to be changed in documentation example:

Latest k8s documentation: https://kubernetes.io/docs/concepts/storage/volume-snapshots/
Longhorn doc with the old syntax: https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

**To Reproduce**
1. Go to https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
2. VolumeSnapshotClass example is using the old API version:
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1beta1
```

**Expected behavior**
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
```

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: AKS, v1.18.10

My working VolumeSnapshotClass:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: iris-longhorn-snapshot
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: iris-pvc
```
