### ISSUE TITLE
[BUG] Random manager pods seem to be stuck when requested at /v1 uri

### ISSUE THREAD

**Issue by matulek** [longhorn/longhorn#2251]
**Describe the bug**
Randomly manager pods seem to be stuck when requested at /v1 uri

**To Reproduce**
It's hard to provide any reproduction scenario as it occurs on my VPS kubernetes cluster.
Cluster parameters:
Three nodes (one master, two workers), 16 GiB RAM, 4 cores intel x64.
CNI plugin: Calico
Standard Kubespray installation without tweaks.

```
# curl http://longhorn-backend:9500

{"data":[{"actions":{},"id":"v1","links":{"self":"http://longhorn-backend:9500/v1"},"type":"apiVersion"}],"links":{"latest":"http://longhorn-backend:9500/v1","self":"http://longhorn-backend:9500/"},"resourceType":"apiVersion","type":"collection"}
```

```
# curl http://longhorn-backend:9500/v1
... now I can wait forever
```

It doesn't always happen, sometimes longhorn-manager pods work normally. It seems they randomly start in faulty state, but the're reported to be healthy and ready. Now I've got one working and two failing pods.

**Expected behavior**
All manager pods should work and respond.

**Log**
No idea which fragment of which log to attach here, I'd be happy to provide any logs you ask me to.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: vanilla kubernetes cluster deployed on 3x VPS
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: CentOS 8
   - CPU per node: 4
   - Memory per node: 16 GiB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: ~600-800 Mbits/sec
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): probably VMWare (VPS service provided by the external vendor)
 - Number of Longhorn volumes in the cluster: 0 yet

**Additional context**

**Comment by joshimoo** [comment]
Please provide us with a support bundle either attach it here or send it to longhorn-support-bundle@rancher.com
![image](https://user-images.githubusercontent.com/1287163/107722545-6ac90d80-6cdf-11eb-88b2-d4df7c4002a5.png)

**Comment by matulek** [comment]
Due to misbehaving longhorn-manager pods the longhorn-ui is unusable, I can't generate it. I can try to play with manager pods by restarting them until both are working but until then that's everything I see when trying to download the bundle
 ![Uploading obraz.png…]()

**Comment by joshimoo** [comment]
You can follow these instructions to manually generate a support bundle via curl against the backend.
you need to adjust the mentioned parameters, you might need to route this against a running manager instance manually.
https://github.com/longhorn/longhorn/issues/2118#issuecomment-748099002

If that is not possible provide the logs from each longhorn-manager instance.

**Comment by matulek** [comment]
I'm into it, I'll try to get to this at sunday.

**Comment by matulek** [comment]
@joshimoo I'm sorry, I couldn't get to this as fast as I was expecting to.
The service 'longhorn-backend' exposes manager pods which are misbehaving on my setup so generating support bundle with curl ends with connection drop. I'll provide pod logs as attachments. Personally I couldn't find anything 

[longhorn-manager-7hjpn.txt](https://github.com/longhorn/longhorn/files/6005594/longhorn-manager-7hjpn.txt)
[longhorn-manager-dnqtj.txt](https://github.com/longhorn/longhorn/files/6005595/longhorn-manager-dnqtj.txt)

**Comment by PhanLe1010** [comment]
Form the log, it seems that manager pods are repeatedly restarted:
```
UID:\"1571006f-5f62-4127-a126-5adca74228cf\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3288\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Node raws-worker1 is down: the manager pod longhorn-manager-dnqtj is not running"
...
UID:\"c9a63f8a-cb9c-4324-a9df-251dfa5c78dc\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3406\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Node raws-worker2 is down: the manager pod longhorn-manager-7hjpn is not running"
```
But I am not able to figure out why they are restarted constantly from the provided manager logs

**Comment by PhanLe1010** [comment]
After discussing with the team, it could also be the network in the cluster. I see the log:
```
time="2021-02-18T19:56:04Z" level=error msg="Error in request: writev tcp 10.233.115.5:9500->10.233.112.4:45750: i/o timeout"
2021/02/18 19:56:04 http: response.WriteHeader on hijacked connection from github.com/gorilla/handlers.(*responseLogger).WriteHeader (handlers.go:65)
```

Can you help us to do 2 things:
1. Check the status of `longhorn-manager` Daemonset and pods by:
   ```
   kubectl get ds longhorn-manager -n longhorn-system -o yaml
   kubectl get pods <LONGHORN-MANAGER-POD-NAME> -n longhorn-system -o yaml
   ```
   We want to see how many time manager pods restart
2. Can you check the network in the cluster. I.e., the logs of the Calico CNI plugin

**Comment by matulek** [comment]
[yamls.zip](https://github.com/longhorn/longhorn/files/6018138/yamls.zip)

**Comment by PhanLe1010** [comment]
@matulek 

From your provided yaml files, I see that some Longhorn manager pod's container is restarted a few times right after it is started. 
For example, the manager pod `longhorn-manager-shh69` has the following `status.containerStatuses` field:
```
  containerStatuses:
  - containerID: docker://6a280af8feeecb9e71cb0d9c0c7b3e3aff54ec2e07f384c03dc1c691221cf1f2
    image: longhornio/longhorn-manager:v1.1.0
    imageID: docker-pullable://longhornio/longhorn-manager@sha256:3917a6835015d0e5275ef111221af0306c695090204a010865bf992762247889
    lastState:
      terminated:
        containerID: docker://aa5228c73ddf3fa5f79b411d0e00c61fb61eb301e7112d909f868623f1f55f84
        exitCode: 1
        finishedAt: "2021-02-21T16:08:47Z"
        reason: Error
        startedAt: "2021-02-21T16:08:45Z"
    name: longhorn-manager
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2021-02-21T16:09:01Z"
```

We want to investigate why the container inside the manager pod exited with error code. Can you try to monitor `event` of the `longhorn-manager` DaemonSet, `longhorn-manager-xxxxx` pod, and the container inside the pod. Also, can you collect the logs of those manager pod?
