### ISSUE TITLE
[FEATURE] Add support for ingressClassName in helm chart

### ISSUE THREAD

**Issue by Diaoul** [longhorn/longhorn#2257]
**Is your feature request related to a problem? Please describe.**
`kubernetes.io/ingress.class` annotation is progressively replaced with `ingressClassName` in the ingress as of v1.18. See [this related blog post](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/).

**Describe the solution you'd like**
Support for ingressClassName in helm chart

**Describe alternatives you've considered**

**Additional context**
N/A

**Comment by joshimoo** [comment]
Thanks for submitting a pr and suggesting this, we will discuss it and have a look at the pr and document.

**Comment by meldafrawi** [comment]
Testing Steps:

1. Create a k3s cluster (1 controller node, 3 worker nodes)  -- by default k3s use traefik as ingress controller.
2. Create traefik ingressclass
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: traefik-lb
spec:
  controller: traefik.io/ingress-controller
  ```
 3. Using Helm: add ingress-nginx repo
 ```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
```
4. Using Helm, create the default values file
`helm show values ingress-nginx/ingress-nginx > nginx-ingress-values.yml`

5. Edit  `Controller.service.ports` to avoid conflicts between nginx and traefik
e.g:

| Field | Original Value  | Modified Value |
| -------------  | ------------- | ------------- |
| Controller.service.ports.http   |   80  |  33380  |
|  Controller.service.ports.https | 443  |  33443  |
 
 6. Install ingress-nginx using the modified values file.
` helm install ingress-nginx ingress-nginx/ingress-nginx --values nginx-ingress-values.yml`

7. Create nginx ingress class
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: nginx.org/ingress-controller 
```

8. Add/change the following values to Longhorn chart  `values,yml` file

  | Field  | Original Value  | Modified Value |
  | ------------- |  ------------- | ------------- |
  | ingress.enabled |  false  |  false  |
  | ingress.ingressClassName |  not defined  | nginx  |
  | ingress.host |  xip.io  |  <WORKER_NODE_PUBLIC_IP>.xip.io  |
  
 9. Deploy Longhorn
 ```
 kubectl create ns longhorn-system
 helm install --namespace longhorn-system longhorn .
 ```
 10. Check Longhorn UI on http port:
 > http://<WORKER_NODE_PUBLIC_IP>:33380.xip.io it should be accessible 
 
 11. Change ingressClassName
   | Field  | Original Value  | Modified Value |
  | ------------- |  ------------- | ------------- |
  | ingress.ingressClassName |  nginx  | traefik-lb  |

 12. Check Longhorn UI on http port:
 > http://<WORKER_NODE_PUBLIC_IP>:33380.xip.io it should **NOT** be accessible
