### ISSUE TITLE
[BUG] Updating the config map in the Longhorn yaml doesn't set the values of the settings.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2280]
**Describe the bug**
Deploy Longhorn-master after setting some values like `concurrent-automatic-engine-upgrade-per-node-limit` in the Config map in the Longhorn yaml file. The values are not reflected the Longhorn setting once deployed.

**To Reproduce**
1. Deploy Longhorn v1.1.0 on a K8s cluster.
2. Create some volumes and attach them to pods.
3. Change the `concurrent-automatic-engine-upgrade-per-node-limit` value to 2 in the config map. Change some more values in the Config map like below.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target:
    backup-target-credential-secret:
    allow-recurring-job-while-volume-detached:
    create-default-disk-labeled-nodes:
    default-data-path:
    replica-soft-anti-affinity:
    storage-over-provisioning-percentage:
    storage-minimal-available-percentage:
    upgrade-checker:
    default-replica-count:
    default-data-locality:
    guaranteed-engine-cpu:
    default-longhorn-static-storage-class:
    backupstore-poll-interval:
    taint-toleration:
    priority-class:
    auto-salvage:
    auto-delete-pod-when-volume-detached-unexpectedly:
    disable-scheduling-on-cordoned-node:
    replica-zone-soft-anti-affinity:
    volume-attachment-recovery-policy:
    node-down-pod-deletion-policy:
    allow-node-drain-with-last-healthy-replica:true
    mkfs-ext4-parameters:'abc'
    disable-replica-rebuild:
    replica-replenishment-wait-interval:100
    disable-revision-counter:
    system-managed-pods-image-pull-policy:
    allow-volume-creation-with-degraded-availability:false
    auto-cleanup-system-generated-snapshot:
    concurrent-automatic-engine-upgrade-per-node-limit:2
    backing-image-cleanup-wait-interval:
```
4. Deploy Longhorn using kubectl command. Check the Longhorn setting, the values are not reflected.

**Expected behavior**
User should be able to change the `longhorn-default-setting` and deploy Longhorn with those values.

**Environment:**
 - Longhorn version: Longhorn-master `03/01/2021`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s v1.20.4 - RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 1.20
   - CPU per node: 2 vcpus
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 5 Gigabyte
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 10

**Additional context**
