### ISSUE TITLE
[Question] Longhorn UI with Istio instead of Nginx

### ISSUE THREAD

**Issue by jmcclenny-PRE** [longhorn/longhorn#2282]
**Question**
Is it possible to configure the Longhorn UI to work with Istio instead of the Nginx Controller?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: v1.19.3+vmware.1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

**Comment by innobead** [comment]
Istio already supports the core function of Kubernetes ingress, so you should be able to try it based on the example ingress config provided in the doc excluding niginx specific annotations. (ref: https://longhorn.io/docs/1.1.0/deploy/accessing-the-ui/longhorn-ingress/)

BTW, as Istio claims, only the core of Kubernetes ingress functions is supported, and the recommended way is its gateway ingress instead because it has more functions provided.

ref: https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/

**Comment by jmcclenny-PRE** [comment]
We have istio-gateway configured and went down the path of creating a virtual service instead of using nginx-controller/ingress.

However, when we try to navigate to the virtual-service host url, we only get a blank page. Using web tools, the get request returns status 503, Service Unavailable.

Here is our virtual-service config.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn
spec:
  hosts:
  - longhorn.<domain>
  gateways:
  - main.istio-system.svc.cluster.local
  http:
  - route:
    - destination:
        host: longhorn-frontend
        port:
          number: 80
```
