### ISSUE TITLE
[BUG] longhorn-post-upgrade job fails due to "Error: container has runAsNonRoot and image will run as root"

### ISSUE THREAD

**Issue by Martin-Weiss** [longhorn/longhorn#2292]
**Describe the bug**
During config change (helm chart deployed via rancher and then changed values and with activated PSP setting) - we see a pod "longhorn-post-upgrade-knbp2" failing to start with the error "Error: container has runAsNonRoot and image will run as root"

Assumption is that this POD does not fulfill the PSP.

**To Reproduce**
Deploy longhorn 1.1.0 and then change a setting in values for the helm based deployment.
Do this on RKE2 with cis-1.5 profile in default namespace/project.
Deployment was done via Rancher 2.5.5

**Expected behavior**
The pod should run with the proper service account and the service account should have the proper PSP access.

**Log**
Error: container has runAsNonRoot and image will run as root"

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro RKE2 
      rke2 version v1.19.7+rke2r1 (d1430ad44dc162f15a54d093439c20ffb91f559b)
     go version go1.15.5b5
   - Number of management node in the cluster: 3 masters
   - Number of worker node in the cluster: 3 worers
 - Node config
   - OS type and version: SLES 15 SP2
   - CPU per node: 2
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure: vmware esxi
 - Number of Longhorn volumes in the cluster: 3

**Additional context**

Assumption is that this is related to the security settings in RKE2 with cis-1.5 profile

**Comment by joshimoo** [comment]
@khushboo-rancher @meldafrawi are we able to reproduce this internally?

**Comment by Martin-Weiss** [comment]
FYI - same issue with longhorn-uninstall POD..

```
  Normal   Scheduled  2m37s                 default-scheduler  Successfully assigned longhorn-system/longhorn-uninstall-7mtld to s-vz-lev-kt022
  Warning  Failed     30s (x12 over 2m36s)  kubelet            Error: container has runAsNonRoot and image will run as root

```

**Comment by jenting** [comment]
@Martin-Weiss,
To clarify, you only change the helm setting by disabled the PSP?

![image](https://user-images.githubusercontent.com/49380831/110760259-7df0de00-8289-11eb-936c-35d2ec3404a1.png)

**Comment by Martin-Weiss** [comment]
I have PSP already ON during deployment via:

```
    # Configure a pod security policy in the Longhorn namespace to allow privileged pods
    enablePSP: true

```

and then I change i.e. the path to one image or add an annotation, adjust ingress or similar and will see the "error".

i.e. add:

```
ingress:
  annotations:
    test: abc
```

Now I get longhorn-post-upgrade-j5p7c -> CreateContainerConfigError

`Error: container has runAsNonRoot and image will run as root`

`kubectl -n longhorn-system get pod longhorn-post-upgrade-j5p7c -o yaml`

spec:

```
spec:
  containers:
  - command:
    - longhorn-manager
    - post-upgrade
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: docker.io/rancher/longhornio-longhorn-manager:v1.1.0
    imagePullPolicy: IfNotPresent
    name: longhorn-post-upgrade
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: longhorn-service-account-token-std8g
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: s-vz-lev-kt022
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1
    supplementalGroups:
    - 1
  serviceAccount: longhorn-service-account
  serviceAccountName: longhorn-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: longhorn-service-account-token-std8g
    secret:
      defaultMode: 420
      secretName: longhorn-service-account-token-std8g
```

--> could it be that the runAsUser is missing, here?

**Comment by jenting** [comment]
Could you please check the Pod's annotation (which has CreateContainerConfigError error), to make sure which PSP policy it applies? `global-restricted-psp` _or_ `longhorn-psp` or other?

**Comment by Martin-Weiss** [comment]
It is the global-restricted-psp:

```
Annotations:  cni.projectcalico.org/podIP: 172.27.5.13/32
              cni.projectcalico.org/podIPs: 172.27.5.13/32
              kubernetes.io/psp: global-restricted-psp
```

Strange - I see a role, role-binding and the "use longhorn-psp" - but for some reason the Annotation is still "global-restricted-psp". For other longhorn pods I see the annotation "kubernetes.io/psp: longhorn-psp" but not for longhorn-uninstall-n4zwk and  longhorn-post-upgrade-k5xmp.. maybe this is related to the "helm upgrade process" that is done via the helm operator job?

**Comment by jenting** [comment]
@Martin-Weiss,
1. Could you please dump the cluster PSP? `kubectl get psp`
2. Had you change the `enablePSP` value during `helm upgrade`?

I tried to reproduce on rke2 (v1.19.8+rke2r1) with cis-1.5 profile, but all my longhorn Pods assigned PSP would be `global-unrestricted-psp`.

![image](https://user-images.githubusercontent.com/49380831/110900385-a0dcca00-833d-11eb-8d30-43239036982d.png)

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss,
> 
>     1. Could you please dump the cluster PSP? `kubectl get psp`

```
NAME                      PRIV    CAPS        SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
cert-manager              false               RunAsAny   MustRunAs          MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI
cert-manager-cainjector   false               RunAsAny   MustRunAs          MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI
cert-manager-webhook      false               RunAsAny   MustRunAs          MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI
global-restricted-psp     false               RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
longhorn-psp              true    SYS_ADMIN   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            configMap,downwardAPI,emptyDir,secret,projected,hostPath
system-unrestricted-psp   true    *           RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
```

As long as I do not change the helm values I see this:

```
kubectl describe pod -n longhorn-system |grep psp|uniq
              kubernetes.io/psp: longhorn-psp

```

-> just when I change a helm value the two pods get started and have the wrong PSP for some reason

> 
>     2. Had you change the `enablePSP` value during `helm upgrade`?
> 

No

> 
> I tried to reproduce on rke2 (v1.19.8+rke2r1) with cis-1.5 profile, but all my longhorn Pods assigned PSP would be `global-unrestricted-psp`.
> 

Maybe there is a difference in deployment.. I am deploying with putting the helmchart yaml into /var/lib/rancher/rke2/server/manifests/longhorn...yaml. And in that I also do the adjustment, there.

Initial deployment is with "enablePSP: true" (stripped down to the details we need, here):

```
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  jobImage: docker.io/rancher/klipper-helm:v0.4.3
  targetNamespace: longhorn-system
  chartContent: H4sIFAAAAAAA/ykAK2FIUjBjSE0.....
  valuesContent: |-
    enablePSP: true
    ingress:
      enabled: true
      annotations:
        test: abc
.....

```

And then I just add an additional annotation to test i.e.:

```
spec:
  jobImage: docker.io/rancher/klipper-helm:v0.4.3
  targetNamespace: longhorn-system
  chartContent: H4sIFAAAAAAA/ykAK2FIUjBjSE0.....
  valuesContent: |-
    enablePSP: true
    ingress:
      enabled: true
      annotations:
        test: abc
        test2: def
.....
```

Now the helm operator kicks in, does an upgrade of the deployment and I see the two pods with the problem..
