### ISSUE TITLE
[Question] How to revert snapshot?

### ISSUE THREAD

**Issue by mritd** [longhorn/longhorn#2301]
**Question**

How to revert snapshot?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20.4
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 8 vCPU
   - Memory per node: 16g
   - Disk type: VMware
   - Network bandwidth and latency between the nodes: private network(1000M)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

**Additional context**

I created a PVC and a Pod that uses it:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-simple-pvc-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-simple-pod-3
  namespace: default
spec:
  restartPolicy: Always
  containers:
    - name: volume-test
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - ls
            - /data/lost+found
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - name: volv
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: longhorn-simple-pvc-3
```

I found that the snapshot can only be created when the Pod is running, otherwise the UI button is not clickable; when I create the snapshot, I want to revert it, but the UI prompts me to reattach the volume; 

finally I stop forented through the lhexec tool and revert the snapshot, but At this point, the Pod was restarting continuously, and I realized that I had to restart forented. Because there was no relevant documentation, I did not know how to start forented.

The second time I tried to revert the snapshot offline by deleting the Pod, but no snapshot was displayed in the UI at this time, and the lhexec tool did not work.

After reading the design documents and the source code, it seems to have finally found the reason:  Once the engines.longhorn.io CRD instance is in the stop state, lhexec will not work, and the UI interface will lose the snapshot information.

**So is there any documentation on how to revert snapshot?** The UI interface and command line tools have a lot of uncertainty in details, and it is difficult for novices to operate.

Digression: Is the [Architecture and Concepts](https://longhorn.io/docs/1.1.0/concepts/) document outdated or unclear? For example, instance-manager-e/-r pod content, the role of each container, and the calling relationship?
