### ISSUE TITLE
[BUG] Long delay to attach volume when statefulset restart

### ISSUE THREAD

**Issue by ElisaMeng** [longhorn/longhorn#2322]
**Describe the bug**
When using volumeClaimTemplates with longhorn in a statefulset, initial deployment goes ok, but if running 

kubectl rollout restart statefulset, longhorn volume will get failed to mount again. It seems stuck in being state, which is not supposed being like that. 

**To Reproduce**
1. Deploy statefulset workload with volumeClaimTemplates 
2. Wait for all pods get ready
3. run kubectl rollout restart statefulset ...
4. no pod can be started since longhorn volume is being deleted

**Expected behavior**
pod should just restart

**Log**
.
```
7m30s       Normal    Scheduled                pod/seafile-srv-0                                       Successfully assigned cloudoffice/seafile-srv-0 to iserver
7m18s       Normal    SuccessfulAttachVolume   pod/seafile-srv-0                                       AttachVolume.Attach succeeded for volume "pvc-12ee35dc-15f7-4b61-9394-63251b02be18"
6m59s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/seafile-mc:8.0.3" already present on machine
6m59s       Normal    Created                  pod/seafile-srv-0                                       Created container setup
6m59s       Normal    Started                  pod/seafile-srv-0                                       Started container setup
6m58s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "mariadb:10" already present on machine
6m58s       Normal    Created                  pod/seafile-srv-0                                       Created container mariadb
6m58s       Normal    Started                  pod/seafile-srv-0                                       Started container mariadb
6m58s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/elasticsearch-with-ik:5.6.16" already present on machine
6m57s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile-elasticsearch
6m57s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile-elasticsearch
6m57s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "memcached:1.5.6" already present on machine
6m57s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile-memcached
6m57s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile-memcached
6m57s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/seafile-mc:8.0.3" already present on machine
6m56s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile
6m56s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container mariadb
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile-memcached
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile-elasticsearch
3m43s       Normal    Scheduled                pod/seafile-srv-0                                       Successfully assigned cloudoffice/seafile-srv-0 to iserver
100s        Warning   FailedMount              pod/seafile-srv-0                                       Unable to attach or mount volumes: unmounted volumes=[seafile-srv-store], unattached volumes=[seafile-srv-store default-token-w5pdn]: timed out waiting for the condition
31s         Warning   FailedMount              pod/seafile-srv-0                                       MountVolume.WaitForAttach failed for volume "pvc-12ee35dc-15f7-4b61-9394-63251b02be18" : volume attachment is being deleted
7m35s       Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-pvc                   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
7m35s       Normal    Provisioning             persistentvolumeclaim/seafile-srv-pvc                   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-pvc"
7m32s       Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-pvc                   Successfully provisioned volume pvc-12ee35dc-15f7-4b61-9394-63251b02be18
60m         Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-store-seafile-srv-0   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
60m         Normal    Provisioning             persistentvolumeclaim/seafile-srv-store-seafile-srv-0   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-store-seafile-srv-0"
60m         Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-store-seafile-srv-0   Successfully provisioned volume pvc-639c918d-e1b5-47c9-87ed-f4c69d452d5e
32m         Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-store-seafile-srv-0   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
32m         Normal    Provisioning             persistentvolumeclaim/seafile-srv-store-seafile-srv-0   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-store-seafile-srv-0"
32m         Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-store-seafile-srv-0   Successfully provisioned volume pvc-e2e5da4d-c206-422f-9640-c0696dfa9baa
60m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Claim seafile-srv-store-seafile-srv-0 Pod seafile-srv-0 in StatefulSet seafile-srv success
60m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
37m         Warning   FailedCreate             statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv failed error: The POST operation against Pod could not be completed at this time, please try again.
37m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
32m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Claim seafile-srv-store-seafile-srv-0 Pod seafile-srv-0 in StatefulSet seafile-srv success
20m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
20m         Normal    SuccessfulDelete         statefulset/seafile-srv                                 delete Pod seafile-srv-0 in StatefulSet seafile-srv successful
3m43s       Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
3m51s       Normal    SuccessfulDelete         statefulset/seafile-srv                                 delete Pod seafile-srv-0 in StatefulSet seafile-srv successful

```
**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.19.8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: k3os
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): 
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by PhanLe1010** [comment]
What is the yaml file of the stateset and the longhorn storageclass ?

**Comment by ElisaMeng** [comment]
```

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-server
  name: test-server
  
spec:
  replicas: 1
  serviceName: test
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      
      initContainers:
        - image: alpine:3.12
          name: setup
          command:
            - sh 
            - -c 
            - for i in mariadb; do mkdir -p /data/$i;done
          volumeMounts:
          - mountPath: /data
            name: test-server-store
          resources:
            limits:
              cpu: 10m
              memory: 40M
      containers:
      - image: mariadb:10
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: test-server-store
          subPath: mariadb
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 1000m
            memory: 2G
  volumeClaimTemplates:
    - metadata:
        name: test-server-store
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 512Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: test
  
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: test-server
```

@PhanLe1010  btw, If set the volume size to 1G, it works without issue.

**Comment by ElisaMeng** [comment]
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "2"
        staleReplicaTimeout: "2880"
        fromBackup: ""
      #  diskSelector: "ssd,fast"
      #  nodeSelector: "storage,fast"
        recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 3 * * 1", "retain":3},
                         {"name":"backup", "task":"backup", "cron":"0 5 * * 1", "retain":3,
                          "labels": {"interval":"weekly"}}]'
parameters:
  fromBackup: ""
  numberOfReplicas: "2"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 3 * * 1", "retain":3},
    {"name":"backup", "task":"backup", "cron":"0 5 * * 1", "retain":3, "labels": {"interval":"weekly"}}]'
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

`Some more update.  it actually was not failing, but taking a very long time to attach, far longer than the first time it attach.
