### ISSUE TITLE
[Question] There is a way to get restore progress % using command line?

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2327]
**Question**
When I run a backup, for example, is possible to get de backup progress by checking the pod log. I Would like to know if there is a similar way t get restore progress. I try to see the log of the instance responsible for volume/replica without success.

I need something like:
$ kubectl get/logs/describe <some resource> | grep restore-progress 

As output something like:
time="2021-03-11T19:24:00Z" level=debug msg="Restoring backup , current progress 86"

Thanks!
Longhorn version: 1.1.0
Kubernetes version: 1.20

**Additional context**

**Comment by PhanLe1010** [comment]
You can look into the `engines` resource corresponding to the volume inside `longhorn-system` namespace. The restore progress is recorded inside the field `restoreStatus` of the `engine` resource.

For example, `kubectl get engines <ENGINE-NAME> -n longhorn-system -o yaml | grep -A 25 "restoreStatus:"` shows:
```
restoreStatus:
tcp://10.42.1.9:10015:
    backupURL: s3://backupbucket@us-east-1/?backup=backup-9c9b8d87135e4025&volume=testvol1
    currentRestoringBackup: backup-9c9b8d87135e4025
    filename: volume-snap-2f2ac5e5-ffdd-42b4-83be-781714cff6f4.img
    isRestoring: true
    lastRestored: ""
    progress: 72
    state: in_progress
tcp://10.42.2.6:10015:
    backupURL: s3://backupbucket@us-east-1/?backup=backup-9c9b8d87135e4025&volume=testvol1
    currentRestoringBackup: backup-9c9b8d87135e4025
    filename: volume-snap-2f2ac5e5-ffdd-42b4-83be-781714cff6f4.img
    isRestoring: true
    lastRestored: ""
    progress: 85
    state: in_progress
tcp://10.42.3.6:10015:
    backupURL: s3://backupbucket@us-east-1/?backup=backup-9c9b8d87135e4025&volume=testvol1
    currentRestoringBackup: backup-9c9b8d87135e4025
    filename: volume-snap-2f2ac5e5-ffdd-42b4-83be-781714cff6f4.img
    isRestoring: true
    lastRestored: ""
    progress: 72
    state: in_progress
```
Similarly, another way to check backup progress is checking the field `backupStatus` in the engine resource
