### ISSUE TITLE
[IMPROVEMENT] Dump NFS ganesha logs to pod stdout

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2380]
**Is your feature request related to a problem? Please describe.**
Currently, ganesha dumps logs to /tmp/ganesha.log file inside the share-manager container. It could be difficult to retrieve the log file if the pod goes into a crash loop.

**Describe the solution you'd like**
Able to see ganesha log included when using `kubectl logs`

**Describe alternatives you've considered**
`none`

**Additional context**
https://github.com/longhorn/longhorn/issues/2284

**Comment by innobead** [comment]
This will help us to improve the support bundle enrichment w/ more helpful logs.

**Comment by weizhe0422** [comment]
If I add output log with stdout in manager shutdown function to implement gracefully shutdown, am I right?

https://github.com/longhorn/longhorn-share-manager/pkg/server/share_manager.go

**Comment by innobead** [comment]
@weizhe0422 Remember updating the Zenhub pipeline status when working on the issue, so right now, it's time to move to ready-for-testing and provide the testing steps in the check-list-comment which will be created when the issue is moved to `review` pipeline.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/899492/186138926-956082ae-f466-4897-bb51-dc9a98801711.png">

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220913**

- longhorn master-head ([8c87681](https://github.com/longhorn/longhorn/commit/8c876810bcf36a1c7222b59cf8fce49e16a44373)) 
- longhorn-share-manager [v1_20220825](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220825) ( [2cba526](https://github.com/longhorn/longhorn-share-manager/commit/2cba526a55368a7f5f263b204d87b39836855dff))

**The test steps**

1. Install Longhorn Master Ref.([install-with-kubectl](https://longhorn.io/docs/1.4.0/deploy/install/install-with-kubectl/))
2. Create rwx volume and attach to pod. Deploy pod “mypod1”
3. `kubectl apply -f pod_with_pvc.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

4. Check pod `volume-test` and `share-manager-pvc-9174f488-1425-421f-9017-c45afc178000` status

**Result Failed
[longhorn-support-bundle_06960eb3-f5c9-490f-9f38-0c35e4e9ddba_2022-09-13T12-04-23Z.zip](https://github.com/longhorn/longhorn/files/9556842/longhorn-support-bundle_06960eb3-f5c9-490f-9f38-0c35e4e9ddba_2022-09-13T12-04-23Z.zip)
**

1. `share-manager-pvc` and `volume-test` pod failed to Running
![Screenshot_20220913_200447](https://user-images.githubusercontent.com/104337648/189896628-40058414-cc6e-413c-8e38-77cdb94c03cb.png)

C.C @weizhe0422

**Comment by weizhe0422** [comment]
I tried deploying with `longhorn.yaml` in the master branch and I can start `share-manger` without restarting.

![image](https://user-images.githubusercontent.com/17548901/189929100-de495f32-3910-4203-ae74-390a4a63e93e.png)

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220914**

- longhorn master-head ([8c87681](https://github.com/longhorn/longhorn/commit/8c876810bcf36a1c7222b59cf8fce49e16a44373)) 
- longhorn-share-manager [v1_20220825](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220825) ( [2cba526](https://github.com/longhorn/longhorn-share-manager/commit/2cba526a55368a7f5f263b204d87b39836855dff))

**The test steps**

1. Install Longhorn Master Ref.([install-with-kubectl](https://longhorn.io/docs/1.4.0/deploy/install/install-with-kubectl/))
2. Create rwx volume and attach to pod. Deploy pod “mypod1”
`kubectl apply -f pod_with_pvc.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

3. Check pod `volume-test` and `share-manager-pvc-9c670e3f-1c35-4734-b788-84f320029ea0` status

**Result Failed**
[longhorn-support-bundle_a85ccb2d-8613-45b7-8154-0e216d166f02_2022-09-14T04-39-36Z.zip](https://github.com/longhorn/longhorn/files/9563313/longhorn-support-bundle_a85ccb2d-8613-45b7-8154-0e216d166f02_2022-09-14T04-39-36Z.zip)

1. We couldn't find out the `nfs-ganesha` log in the console and in support bundle.
    We still could find out `nfs-ganesha` in the pod's  /tmp/ganesha.log
![Screenshot_20220914_143203](https://user-images.githubusercontent.com/104337648/190077324-3832d0fa-4d55-4c44-8e89-5b59e35e5c8b.png)
![Screenshot_20220914_143632](https://user-images.githubusercontent.com/104337648/190078005-c40c6005-5590-4c94-b18e-83333470f2a9.png)


C.C @weizhe0422

**Comment by weizhe0422** [comment]
Upon closer inspection, I found that it was because I didn't fix completely in the first time, so I send the [2nd PR](https://github.com/longhorn/longhorn-share-manager/pull/41) to fix, and I think it was not included in `v1_20220825`.

![image](https://user-images.githubusercontent.com/17548901/190092575-9e52759c-d84b-4712-994f-e94a24d39559.png)

I try to deploy and verify the version of master-head, and it should be work correctly.

![image](https://user-images.githubusercontent.com/17548901/190090135-20c914cc-14e5-4e0e-a760-f3bcdf1b7110.png)

**Comment by innobead** [comment]
@weizhe0422 For any change to individual components like share manager, instance manager, and backing image manager, please remember asking for building a new image for that, then update related manifests in longhorn and longhorn-manager repos with the new image. 

I just triggered https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220914, so when the image is ready (you can check drone-push), please create PRs to update the manifests.

**Comment by weizhe0422** [comment]
Self-test `longhornio/longhorn-share-manager:v1_20220914` works in my environment.

![image](https://user-images.githubusercontent.com/17548901/190156624-42fb2d43-7bd4-4ecc-9669-031aaa2d544d.png)

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220915**

- longhorn master-head ([bfe44af](https://github.com/longhorn/longhorn/commit/bfe44afdf880007c55bc6530f592e1b2562e7571)) 
- longhorn-share-manager [v1_20220825](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220914) ( [2cba526](https://github.com/longhorn/longhorn-share-manager/commit/2cba526a55368a7f5f263b204d87b39836855dff))

**The test steps**

1. Install Longhorn Master Ref.([install-with-kubectl](https://longhorn.io/docs/1.4.0/deploy/install/install-with-kubectl/))
2. Create rwx volume 
`kubectl apply -f create_5vol_rwx.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-3
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-4
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi      
```
3. Volume attach to the pod. Deploy pod “mypod1”
`kubectl apply -f pod_mount_5vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
      - mountPath: "/data2/"
        name: vol-2
      - mountPath: "/data3/"
        name: vol-3
      - mountPath: "/data4/"
        name: vol-4                                
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1        
    - name: vol-2
      persistentVolumeClaim:
        claimName: vol-2
    - name: vol-3
      persistentVolumeClaim:
        claimName: vol-3
    - name: vol-4
      persistentVolumeClaim:
        claimName: vol-4      
```
4. Check pod `mypod1` and `share-manager-pvc-XXXXX` status

**Result Passed**

1. After executed `kubectl -n longhorn-system logs share-manager-<Longhorn_volume_name>` or `kubetail share-manager |grep nfs-ganesha`,  we would find the nfs-ganesha log in the console and in support bundle


![Screenshot_20220915_104745](https://user-images.githubusercontent.com/104337648/190303713-3b734cf0-ac54-4701-9d75-591b700b1bea.png)
![Screenshot_20220915_104550](https://user-images.githubusercontent.com/104337648/190303738-88a7d1de-7b8e-4636-abcc-56f10395527f.png)

[longhorn-support-bundle_ba58f018-f125-4e45-82aa-2ff2eb64b58b_2022-09-15T02-43-32Z.zip](https://github.com/longhorn/longhorn/files/9571377/longhorn-support-bundle_ba58f018-f125-4e45-82aa-2ff2eb64b58b_2022-09-15T02-43-32Z.zip)
