### ISSUE TITLE
[FEATURE] Add GitHub action for auto-assign PR reviewers

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2382]
**Is your feature request related to a problem? Please describe.**

It'd be good to add the GitHub action for auto-assign PR reviewers for all of the Longhorn projects.

**Describe the solution you'd like**

- Create `.github/auto_assign.yml`
```yaml
addReviewers: true
addAssignees: author

# Set this to the length of the reviewers' list because the default was not including everyone
numberOfReviewers: 4

reviewers:
  - yasker
  - shuo-wu
  - joshimoo
  - innobead
```

- Create `.github/auto_assign.yml`
```yaml
name: "Auto Assign PR Reviewers"
# pull_request_target means that this will run on pull requests but in the context of the base repo.
# This should mean PRs from forks are supported.
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  # Automatically assigns reviewers and owner
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Describe alternatives you've considered**

N/A

**Additional context**

To check would it possible to get the reviewers from the https://github.com/longhorn/longhorn/blob/master/MAINTAINERS
