### ISSUE TITLE
[BUG] uninstall-controller does not cleanup share-manager crds

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2384]
`smInformer` needs to be passed to the uninstall controller.
https://github.com/longhorn/longhorn-manager/blob/fa71929a4893869544f2436fb718171bb6cf1cc2/app/uninstall.go#L133

CacheSync + event handler can be added here:
https://github.com/longhorn/longhorn-manager/blob/fa71929a4893869544f2436fb718171bb6cf1cc2/controller/uninstall_controller.go#L120

Cleanup for the crds can be added here:
https://github.com/longhorn/longhorn-manager/blob/fa71929a4893869544f2436fb718171bb6cf1cc2/controller/uninstall_controller.go#L356-L355

After addressing this double check that all necessary informers are getting passed and every crd type is getting processed in the uninstall-controller code.

**Comment by joshimoo** [comment]
To test the uninstall process, you need to create an orphaned share-manager crd.
Since generally when the volume gets deleted it will cleanup the share-manager crd that is associated with the volume.
You should be able to just copy an existing share-manager crd and change the name.
Example below, should work but haven't tested it so feel free to use your own :)

```
apiVersion: longhorn.io/v1beta1
kind: ShareManager
metadata:
  finalizers:
  - longhorn.io
  labels:
    longhorn.io/component: share-manager
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-b7fc01db-9ab9-46ba-8861-905cf1f2ff13
    longhorn.io/share-manager-image: smi-66674b26
  name: pvc-b7fc01db-9ab9-46ba-8861-905cf1f2ff13
  namespace: longhorn-system
spec:
  image: longhornio/longhorn-share-manager:v1_20210302
```

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
1. Create an orphaned share-manager crd
```
apiVersion: longhorn.io/v1beta1
kind: ShareManager
metadata:
  finalizers:
  - longhorn.io
  labels:
    longhorn.io/component: share-manager
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-b7fc01db-9ab9-46ba-8861-905cf1f2ff13
    longhorn.io/share-manager-image: smi-66674b26
  name: pvc-b7fc01db-9ab9-46ba-8861-905cf1f2ff13
  namespace: longhorn-system
spec:
  image: longhornio/longhorn-share-manager:v1_20210302
```
2. run uninstaller
3. make sure share managers are deleted
