### ISSUE TITLE
[BUG] There is no way to cancel the file syncing when the caller becomes invalid

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2416]
**Describe the bug**
For backing image manager, if a backing image is removed during the file syncing, the syncing goroutine cannot be stopped or cancelled.

**To Reproduce**
1. Deploy backing image managers for 2 nodes.
2. Enter into the 1st manager pod, pull a backing image from the remote.
3. Limit the bandwidth of the 1st manager pod so that it won't syncing the backing image file in several seconds.
4. Enter into the 2nd manager pod, start file syncing from the 1st pod.
5. During the file syncing, directly delete the syncing backing image. --> The file syncing is still running. (To check if the syncing is still running, you may need to manually add some debug logs or enable trace logs.)

**Expected behavior**
The file syncing should be cancelled once the backing image is removed.

**Log**
```
[backing-image-manager-bpf2q] time="2021-03-29T03:20:40Z" level=debug msg="Backing Image: updating processed size to 917504" component=backing-image hostDir=/var/lib/longhorn/backing-images/bi-test-uuid-bi-test name=bi-test senderManagerAddress="10.42.1.245:8000" url="https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img" uuid=uuid-bi-test workDir=/data/backing-images/bi-test-uuid-bi-test


[backing-image-manager-bpf2q] time="2021-03-29T03:20:42Z" level=info msg="Backing Image Manager: prepare to delete backing image" backingImage=bi-test component=backing-image-manager diskPathOnHost=/var/lib/longhorn
[backing-image-manager-bpf2q] time="2021-03-29T03:20:42Z" level=info msg="Backing Image: start to clean up backing image" component=backing-image hostDir=/var/lib/longhorn/backing-images/bi-test-uuid-bi-test name=bi-test senderManagerAddress="10.42.1.245:8000" url="https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img" uuid=uuid-bi-test workDir=/data/backing-images/bi-test-uuid-bi-test
[backing-image-manager-bpf2q] time="2021-03-29T03:20:42Z" level=info msg="Backing Image: cleanup succeeded" component=backing-image hostDir=/var/lib/longhorn/backing-images/bi-test-uuid-bi-test name=bi-test senderManagerAddress="10.42.1.245:8000" url="https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img" uuid=uuid-bi-test workDir=/data/backing-images/bi-test-uuid-bi-test
[backing-image-manager-bpf2q] time="2021-03-29T03:20:42Z" level=info msg="Backing Image Manager: deleted backing image" backingImage=bi-test component=backing-image-manager diskPathOnHost=/var/lib/longhorn


[backing-image-manager-bpf2q] time="2021-03-29T03:20:43Z" level=debug msg="Backing Image: updating processed size to 1048576" component=backing-image hostDir=/var/lib/longhorn/backing-images/bi-test-uuid-bi-test name=bi-test senderManagerAddress="10.42.1.245:8000" url="https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img" uuid=uuid-bi-test workDir=/data/backing-images/bi-test-uuid-bi-test
[backing-image-manager-bpf2q] time="2021-03-29T03:20:45Z" level=debug msg="Backing Image: updating processed size to 1179648" component=backing-image hostDir=/var/lib/longhorn/backing-images/bi-test-uuid-bi-test name=bi-test senderManagerAddress="10.42.1.245:8000" url="https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img" uuid=uuid-bi-test workDir=/data/backing-images/bi-test-uuid-bi-test
```

**Environment:**
 - Longhorn version: v1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
I can add cancelled context for the syncing call.

**Comment by shuo-wu** [comment]
Test step:
1. For convenience, manually launch the backing image manager pods:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: backing-image-manager
  name: backing-image-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: backing-image-manager
  template:
    metadata:
      labels:
        app: backing-image-manager
    spec:
      containers:
      - name: backing-image-manager
        image: longhornio/backing-image-manager:master
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - backing-image-manager
        - --debug
        - daemon
        - --listen
        - 0.0.0.0:8000
        readinessProbe:
          tcpSocket:
            port: 8000
        volumeMounts:
        - name: disk-path
          mountPath: /data
      volumes:
      - name: disk-path
        hostPath:
          path: /var/lib/longhorn/
      serviceAccountName: longhorn-service-account
```
2. Download a backing image in the first pod:
```
# alias bm="backing-image-manager backing-image"
# bm pull --name bi-test --uuid uuid-bi-test --download-url https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img
# bm ls
```
3. In the 2nd pod, limit the bandwidth first so that the downloading won't be done within several seconds
```
tc qdisc del dev eth0 root
tc qdisc add dev eth0 root tbf rate 500kbit latency 0.1ms burst 1000kbit
```
4. Then start to get the backing image file from the 1st BIM pod
```
# alias bm="backing-image-manager backing-image"
# bm sync --name bi-test --uuid uuid-bi-test --download-url https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200729/ubuntu-20.04-minimal-cloudimg-amd64.img --size 208601088 --from-host <the IP of 1st BIM pod> --to-host <the IP of 2nd BIM pod>
# bm ls
```
5. During the syncing, directly deleting the downloading backing image in the 2nd pod
```
# bm delete bi-test
```
6. Wait 1 minute and check the log of the 2nd pod. Make sure there is no download/sync (failure) related logs after the deletion. Then restarting sync without deletion, the backing image can be downloaded successfully.
