### ISSUE TITLE
[FEATURE] rwx shared directory should be rw accessible when running as non-root user

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2418]
**Describe the bug**
The rwx shared directory seems not rw accessible when the consumer pod is running as non-root user.

**To Reproduce**
1. Create rwx pvc with pod running as non-root user.
2. Create file in /data/

**Expected behavior**
Able to create file.

**Log**
`n/a`

**Environment:**
 - Longhorn version: 1.1.0

**Additional context**
From discussion in https://github.com/longhorn/longhorn/issues/2357.

**Comment by innobead** [comment]
cc @joshimoo any idea?

**Comment by c3y1huang** [comment]
This doesn't look like a bug anymore but is more related to kubernetes consumer pod mount behavior.
https://github.com/kubernetes/kubernetes/issues/77986

Since we've exported the NFS as root. The consumer pod then needs to access with the same user. With the current design, there are two ways to resolve when the consumer pod is running as non-root.
1. Use securityContext to enforce to run as root user.
2. Use initContainer to overwrite mount directory permission.
https://stackoverflow.com/questions/50156124/kubernetes-nfs-persistent-volumes-permission-denied

**Comment by c3y1huang** [comment]
I will close this for now. Please re-open if this needs another look.

**Comment by c3y1huang** [comment]
Reopen issue for 
* https://github.com/longhorn/longhorn/issues/2357#issuecomment-812718469
* https://github.com/longhorn/longhorn-share-manager/pull/9

**Comment by cocampbe** [comment]
This is actually kind of killing me. I am moving to longhorn and all the RWX volumes use NFSv4 and only root can write to it. I am having to add initContianers to a lot of deployments and statefulsets. This is not ideal. Is there a way to change the way the exports work for a pvc/pv?

**Comment by joshimoo** [comment]
For testing the below deployment can be used, then exec into the pod to create folders & files.
The folders and files should be able to be created with the user/group specified in the security context.
Since we currently don't have any ACL support for the export, this only marginally decreases the security of the volume data.
But allows for non root pods, which is currently not well supported.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwx-non-root
  labels:
    app: rwx-non-root
spec:
  selector:
    matchLabels:
      app: rwx-non-root # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rwx-non-root
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Always
      containers:
      - image: busybox
        name: busybox
        command: [ "sh", "-c", "sleep 1h" ]
        readinessProbe:
          exec:
            command:
              - ls
              - /mnt/vol
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: rwx-non-root
          mountPath: /mnt/vol
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: rwx-non-root
        persistentVolumeClaim:
          claimName: rwx-non-root
```
