### ISSUE TITLE
[FEATURE] Recurring snapshot/backup job supports imagePullSecrets

### ISSUE THREAD

**Issue by kadamkaustubh** [longhorn/longhorn#2432]
**Describe the bug**
Longhorn is deployed with helm chart version 1.1.0 with private registry credentials defined (`systemDefaultRegistry` is not set). The deployment is successful, I am able to create and attach volumes. I created a recurring snapshot schedule for a volume, the cron job is created in `longhorn-system` namespace. the cronjob does not have imagePullSecrets added to the job spec. when the job is triggered, it fails to pull the image with the error `Authentication is required`

**To Reproduce**
1. Deploy longhorn via helm chart version 1.1.0 with private registry details 
```
privateRegistry:
  registryUrl: private-registry.url
  registryUser: registry-user
  registryPasswd: registry-pwd
  registrySecret: registry-secret
```
2. Select a volume and create a recurring snapshot schedule 
3. Check the yaml for cronJob spec
4. CronJob spec will not have the registry secret injected

**Expected behavior**
CronJob spec will have the image pull secret injected
```
  imagePullSecrets:
  - name: registry-secret
```

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 6
   - Number of worker node in the cluster: 6
 - Number of Longhorn volumes in the cluster: 50+
