### ISSUE TITLE
[Question] [Enhancement] Is it possible to set snapshots and backups via yaml

### ISSUE THREAD

**Issue by cocampbe** [longhorn/longhorn#2449]
I am trying to figure out how to add snapshots and backups to volumes via patches, or some something. I know I can create a new storage class, but I just don't like that approach. My idea is to have a more self service way for users to decide whether they want snapshots or backups, etc. I think it would be interesting to use annotations on the pvc and have something like kyverno intercept that and modify the volume and add the snapshot or backup schedule. I have tried adding the following to longhorn volume, but it does not persist.

```
recurringJobs:
  - cron: 0 */4 * * *
    labels: null
    name: c-h85v2g
    retain: 10
    task: snapshot
```

Can info be provided on how this could be done?
