### ISSUE TITLE
[BUG] messy information in support bundle manifests

### ISSUE THREAD

**Issue by gitlawr** [longhorn/longhorn#2490]
**Describe the bug**
When I check the Kubernetes manifests in generated support bundle, I notice that some of the information is incorrect.

**To Reproduce**
1. Deploy Longhorn in a single node cluster(bundled in Harvester)
2. Click on 'Generate Support Bundle'
3. Compare the `yamls/kubernetes/nodes.yaml` in support bundle with the ouput of `kubectl get node -o yaml`

**Result**
```
# snippet from support bundle
  status:
    capacity:
      cpu:
        format: DecimalSI
      devices.kubevirt.io/kvm:
        format: DecimalSI
      devices.kubevirt.io/tun:
        format: DecimalSI
      devices.kubevirt.io/vhost-net:
        format: DecimalSI
      ephemeral-storage:
        format: BinarySI
      hugepages-1Gi:
        format: DecimalSI
      hugepages-2Mi:
        format: DecimalSI
      memory:
        format: BinarySI
      pods:
        format: DecimalSI
```

```
# snippet from kubectl get
  status:
    capacity:
      cpu: "8"
      devices.kubevirt.io/kvm: "110"
      devices.kubevirt.io/tun: "110"
      devices.kubevirt.io/vhost-net: "110"
      ephemeral-storage: 154695504Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 8151072Ki
      pods: "110"
```

This is valid for other resource yamls.

**Log**
Full support bundle:
[longhorn-support-bundle_8ec9972f-e6ad-45b7-b037-256ff9ab6ee2_2021-04-14T06-56-26Z.zip](https://github.com/longhorn/longhorn/files/6308881/longhorn-support-bundle_8ec9972f-e6ad-45b7-b037-256ff9ab6ee2_2021-04-14T06-56-26Z.zip)

**Environment:**
 - Longhorn version: v1.1.1-rc1
 - Installation method: bundled in Harvester
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
