### ISSUE TITLE
[BUG] Workload cannot recover after tainting node

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2517]
**To Reproduce**
1. Install Longhorn v1.1.1-rc2 in a cluster of 3 worker nodes
2. Create a deployment that use a Longhorn RWX/RWO volume of 3 replicas
3. Find the node where the volume is attaching to, let's call node-1
4. Taint node-1 with `k=v:NoExecute`
5. Longhorn cannot reattach volume -> workload cannot restart

**Expected behavior**
Longhorn is able to reattach the volume to new nodes

**Additional context**
* The YAML of the RWX volume shows that `v.Spec.NodeID: phan-v51-worker-3` but volume cannot attach to node-3 because `v.PendingNodeID: phan-v51-worker-1`
* This is not a common use case. We can wait to see the response from the users.

**Comment by PhanLe1010** [comment]
Workaround:
1. Remove the taint
2. Scale down the workload
3. Add the taint
4. Scale back the workload

**Comment by joshimoo** [comment]
needs the volume controller refactor, where the pending node id is removed and all attachment decisions are based on v.spec.NodeID and v.status.CurrentNodeID is only set once the volume is fully attached/detached to reflect the actual state #1310

**Comment by yankcrime** [comment]
>  A bunch of nodes went unresponsive and got tainted and terminated, most pods rescheduled to new nodes eventually. But some ended up in this state where PendingNodeID is pointing to a node that doesn't exist anymore. Now they're stuck and can't be attached to the new node.

I hit this exact scenario recently on 1.4.2 as a result of an infrastructure issue that resulted in one of the nodes in my cluster being replaced after a period of time.  The LHVs had a pendingNodeID in the status that was no longer valid, and this seemed to block the volume being rescheduled elsewhere with the same errors shown above.

There is a workaround for this, but it involved editing etc directly.  For anyone else that stumbles across this, here are the steps:

First, retrieve the key for the LHV:

```
etcdctl get --prefix=true /registry/longhorn.io/volumes/longhorn-system/pvc-9af78444-1609-4989-aeb8-e83f73575bf9
```

Amend the JSON object and remove the values for the `.status.pendingNodeID` and `.status.ownerID`, leaving them empty, i.e:

```json
        "ownerID": "",
        "pendingNodeID": "",
```

Now update that key in etcd:

```
etcdctl put /registry/longhorn.io/volumes/longhorn-system/pvc-9af78444-1609-4989-aeb8-e83f73575bf9 \ 
'{ "apiVersion": "longhorn.io/v1beta2" [..]
```

You don't need to restart anything, after a few seconds if you're watching the UI you should see the status of the volume being updated along with replicas etc.  At that point you can detach / reattach to valid hosts in your cluster.

**Comment by derekbit** [comment]
@yangchiu Can you help verify if the issue is valid? Thank you.

**Comment by derekbit** [comment]
@yangchiu Can you help verify if the issue is valid? Thank you.

**Comment by yangchiu** [comment]
Yes, it's still a valid issue. Following [the test steps](https://github.com/longhorn/longhorn/issues/2517#issue-863269633), after tainted the attached node `ip-10-0-1-109`, the volume got stuck in `attaching` forever with the following status:
```
spec:
  nodeID: ip-10-0-1-109
status:
  ownerID: ip-10-0-1-127
  pendingNodeID: ""

```
And the workload got stuck in `Terminating` and `ContainerCreating` unable to recover:
```
$ kubectl get pods -w -owide
NAME                                  READY   STATUS              RESTARTS   AGE     IP           NODE            NOMINATED NODE   READINESS GATES
longhorn-test-minio-7d5979494-j9wf6   1/1     Running             0          16m     10.42.2.3    ip-10-0-1-35    <none>           <none>
longhorn-test-nfs-6cf649d7fb-vcr2z    1/1     Running             0          16m     10.42.2.4    ip-10-0-1-35    <none>           <none>
mysql-2-6dfc4fdd7b-xwwzs              0/1     Terminating         0          9m23s   10.42.1.18   ip-10-0-1-109   <none>           <none>
mysql-2-6dfc4fdd7b-dmxxj              0/1     ContainerCreating   0          6m4s    <none>       ip-10-0-1-35    <none>           <none>
``` 

[supportbundle_4d8b32af-9537-4bab-a4aa-f5f8b6a45e74_2024-06-28T02-06-07Z.zip](https://github.com/user-attachments/files/16023249/supportbundle_4d8b32af-9537-4bab-a4aa-f5f8b6a45e74_2024-06-28T02-06-07Z.zip)

**Comment by ejweber** [comment]
Thanks, I will look at this one soon.

**Comment by ejweber** [comment]
In 2024 on `master-head` (approaching `v1.7.0`), the behavior observed by @yangchiu is no longer related to `pendingNodeID` etc., as Longhorn's attachment logic has completely changed. That field is completely deprecated in favor of a volume attachment controller to choose which node to attach to based on the current desired state of the world.

Today, after following the test steps, we are in the following situation:

There is one Terminating pod and one ContainerCreating pod.

```
mysql-56c8c6775b-8f5gh                 0/1     Terminating         0                30m    10.42.2.58        eweber-v126-worker-9c1451b4-kgxdq   <none>           <none>
mysql-56c8c6775b-rph8k                 0/1     ContainerCreating   0                28m    <none>            eweber-v126-worker-9c1451b4-rw5hf   <none>           <none>
```

The ContainerCreating pod cannot make progress because of a Multi-Attach error.

```
Warning  FailedAttachVolume  27m   attachdetach-controller  Multi-Attach error for volume "pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9" Volume is already exclusively attached to one node and can't be attached to another
```

In fact, Kubernetes still WANTS the volume attached to the old node. There is only one VolumeAttachment for it.

```
csi-f1a6eae2f691ad48e39aca528454c64f7c46a3e6c446e6f9a8ecd960895bf0b6   driver.longhorn.io   pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9   eweber-v126-worker-9c1451b4-kgxdq   true       31m
```

As a result, there is only one LonghornAttachmentTicket for the old node. Longhorn is trying to reattach the volume to the old node, but it is impossible (since all of the Longhorn components on the old node are down).

```
spec:
    attachmentTickets:
      csi-f1a6eae2f691ad48e39aca528454c64f7c46a3e6c446e6f9a8ecd960895bf0b6:
        generation: 0
        id: csi-f1a6eae2f691ad48e39aca528454c64f7c46a3e6c446e6f9a8ecd960895bf0b6
        nodeID: eweber-v126-worker-9c1451b4-kgxdq
        parameters:
          disableFrontend: "false"
          lastAttachedBy: ""
        type: csi-attacher
    volume: pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9
  status:
    attachmentTicketStatuses:
      csi-f1a6eae2f691ad48e39aca528454c64f7c46a3e6c446e6f9a8ecd960895bf0b6:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-06-28T20:05:58Z"
          message: ""
          reason: ""
          status: "False"
          type: Satisfied
        generation: 0
        id: csi-f1a6eae2f691ad48e39aca528454c64f7c46a3e6c446e6f9a8ecd960895bf0b6
        satisfied: false
```

Longhorn is working correctly. Until Kubernetes tries to detach the volume from the old node, it should continually attempt to reattach it.

The reason we are stuck is found in the kubelet logs on the old node.

```
Jun 28 20:40:37 eweber-v126-worker-9c1451b4-kgxdq k3s[753]: I0628 20:40:37.391775     753 reconciler_common.go:172] "operationExecutor.UnmountVolume started for volume \"mysql-volume\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9\") pod \"942ef69b-2e06-47f3-8bac-cc738c8baa00\" (UID: \"942ef69b-2e06-47f3-8bac-cc738c8baa00\") "
Jun 28 20:40:37 eweber-v126-worker-9c1451b4-kgxdq k3s[753]: E0628 20:40:37.391968     753 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9 podName:942ef69b-2e06-47f3-8bac-cc738c8baa00 nodeName:}" failed. No retries permitted until 2024-06-28 20:42:39.391919153 +0000 UTC m=+10744.364754873 (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "mysql-volume" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-b23fce3b-cada-43a9-89b8-2eb9b97e39c9") pod "942ef69b-2e06-47f3-8bac-cc738c8baa00" (UID: "942ef69b-2e06-47f3-8bac-cc738c8baa00") : kubernetes.io/csi: Unmounter.TearDownAt failed to get CSI client: driver name driver.longhorn.io not found in the list of registered CSI drivers
```

Kubernetes can't tear down the pod because the CSI plugin is not running on the node to respond to `NodeUnpublishVolume` and `NodeUnstageVolume` commands.

We need to consider whether the CSI plugin should be able to tolerate a NoExecute taint. If no, then there's really no way we can expect to make progress.
