### ISSUE TITLE
[BUG] PVC Failed due to instance manager is down

### ISSUE THREAD

**Issue by ruruiye** [longhorn/longhorn#2518]
We have a large PVC which have about 50TB totally with XFS in host instance file system, and we attached it successfully as a minio backend. when we start more job on cloud, the instance manager is down. and the PVC start the *stop* action. but the stop action failed due to the instance manager pod is failed due to no resource in the cluster. Then our PVC can't restart anymore. 

the problem is:
1. how can we avoid the problem like this?
2. if that happened,  how can we recover the storage volume?

![image](https://user-images.githubusercontent.com/52643407/115487909-2e400200-a28c-11eb-8c86-9d80a040ff1f.png)

---
Version: `v1.1.0`

**Comment by shuo-wu** [comment]
I think you are talking about Longhorn volumes rather than PVCs. Longhorn volumes are controlled by instance manager pods. In other words, if an instance manager pod is down, the related volumes will become `Degraded` or `Faulted`. To avoid instance manager pods being evicted by resource exhaust, you can check & config the setting `Guaranteed Engine CPU` first.

**Comment by ruruiye** [comment]
@shuo-wu yes, the failure is due to longhorn volumes failed, I already found the configuration and modified the priority class now, but the next question is how can we recover from the failure? currently the instance manager is back and longhorn volume is still not recover automatically.

**Comment by shuo-wu** [comment]
What's the current volume state? Faulted? 
If the workloads are pods, you need to restart the pods. If workloads are Deployments or StatefulSets, Longhorn should recover the volumes automatically for them.

**Comment by ruruiye** [comment]
@shuo-wu our workflow are Deployments, we use longhorn for the backend of minio, and our minio is not able to start anymore now. we have to delete the longhorn volume and deploy it again.

**Comment by shuo-wu** [comment]
1. If your volumes are Faulted and not salvaged by Longhorn automatically, you may need to do manual salvage. Longhorn will have an auto-salvage-related bug fix in the next release. If you don't understand the current state of the volume, you can take screenshots for the related Longhorn volumes.
2. Deleting the volumes will lead to **data loss**, which is not recommended in your case. You can scale down then scale up the deployments.

**Comment by ruruiye** [comment]
@shuo-wu I have no idea how to do  manual salvage and there seams no doc for that. we are just start using this system and delete volume is OK and we tuned the parameter for to system-cluster level for priority. So I will close this issue and hope we can have auto  salvage bug soon. Thanks!

**Comment by ruruiye** [comment]
@shuo-wu same issue happen again, this time when the instance manager down (we have set the Priority to system-node-critical, and CPU to 0.25), after the volume show fatal, we removed the minio pod and the volume should detached. and then when we start the pod again, we see the error info like this. do you have any idea why the pvc failed to attach? we have see same issue on the other volume too.


![image](https://user-images.githubusercontent.com/52643407/115643427-52184c00-a34f-11eb-93eb-45ddceb8e780.png)

**Comment by shuo-wu** [comment]
What's your environment? k3s?
I saw this issue report in k3s:
https://github.com/k3s-io/k3s/issues/732#issuecomment-533896909

It's unlikely a Longhorn issue. The workaround mentioned in that thread is adding a new role for `system:nodes` but I am not sure if it still works for you.

**Comment by ruruiye** [comment]
@shuo-wu yes, we are running this in k3s, let me try the fix. Thanks!

**Comment by ruruiye** [comment]
@shuo-wu seams its an missing part of CRD, see the linked issue from RKE2. do you have any idea?

**Comment by shuo-wu** [comment]
No... As I mentioned in the Rancher post, Longhorn is not responsible for creating VolumeAttachment CRD.

**Comment by ruruiye** [comment]
after we switch to use rook, in the same cluster, their is no problem. so I really don't know the root cause now

**Comment by shuo-wu** [comment]
That's weird... Can you provide the reproducing step & the environment? Actually, I have not seen this issue before hence I have no more clue right now. I need to reproduce it for further debugging.

**Comment by ruruiye** [comment]
@shuo-wu what I have done:
1. prepare 3 hosts with ubuntu 18.04.5, each.have two storage device, a very large one about 200TB with XFS file system will be used by longhorn
2. create a new RKE2 server with version v1.20.5+rke2r1
3. the configuration for RKE2
    ```
    advertise-address: 172.20.2.200
    bind-address: 172.20.2.200
    tls-san:
      - 172.20.3.250
    node-name: master01.xxx.io
    node-label:
      - "node.kubernetes.io/master=true"
    node-ip: 172.20.2.200
    write-kubeconfig-mode: "0644"
    disable:
      - rke2-ingress-nginx
      - rke2-metrics-server
    resolv-conf: "/etc/rancher/rke2/resolv.conf"
    ```
 4. each node name is registered in the DNS server
 5. deploy longhorn with longhorn/longhorn helm chart
 6. the value for the helm chart
    ```
    image:
      longhorn:
        engine:
          tag: v1.1.0
        manager:
          tag: v1.1.0
        ui:
          tag: v1.1.0
        instanceManager:
          tag: v1_20201216
        shareManager:
          tag: v1_20201204
      csi:
        attacher:
          tag: v2.2.1-lh1
        provisioner:
          tag: v1.6.0-lh1
        nodeDriverRegistrar:
          tag: v1.2.0-lh1
        resizer:
          tag: v0.5.1-lh1
        snapshotter:
          tag: v2.1.1-lh1
    ```
7. once longhorn is ready, we start to create pvc with longhorn as storage class, the pvc is successfully created
8. we remove the pods use the pvc, but let the pvc remained in the namespace
9. create the pod again, try to attach with the pvc
10. the problem happens then
11. you can try with https://bitnami.com/stack/kafka/helm, we are run into problem with this helm chart. but we found minio also have the same problem, so it have nothing to do with which chart we use
