### ISSUE TITLE
[FEATURE] Backing image enhancement

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2530]
- [x] We need to support checksum to validate the integrity of the downloaded backing image.
~- [ ] After downloaded, backing images needs to be stored across different nodes as well, in case one node went down then we might lose the image in the cluster since the internet is not always available in some edge cases. **_(optional, tackle in https://github.com/longhorn/longhorn/issues/2856)_**~
- [x] We also need to initiate the download when the image is added since there is no guarantee that the internet is available when needed later.

**Comment by innobead** [comment]
And some refactoring efforts should be considered in https://github.com/longhorn/longhorn/pull/2617#issuecomment-846966089.

**Comment by innobead** [comment]
@smallteeths Please help update the backing image modal as below to make the margin/indent of the value of `parameters during creation` looks better.

![image](https://user-images.githubusercontent.com/899492/128802127-5bbc3204-9245-46f9-8e92-353f41207f71.png)

**Comment by shuo-wu** [comment]
Will address the 2nd feautre in #2856

**Comment by kaxing** [comment]
Validating in progress with master image(v1.2.0-rc2)

With following test cases:

Node Down
https://longhorn.github.io/longhorn-tests/manual/pre-release/node/backing-image-on-a-down-node/

Longhorn Upgrade
https://longhorn.github.io/longhorn-tests/manual/pre-release/upgrade/backing-image-during-upgrade/

Error Reporting and Retry
https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/

Upload, create via CSI and CRD yaml file
https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.2.0/test-backing-image-upload/

**Comment by kaxing** [comment]
Validation: **PASSED**

Tested with Longhorn v1.2.0-rc2

New feature UI highlight for future reference:

| List of Backing Images | Dialog of creating Backing Image | Dialog of backing image detail |
| - | - | - |
| ![image](https://user-images.githubusercontent.com/602540/131284240-12f13730-e53d-49d6-95da-d85d0fb3a253.png) | ![image](https://user-images.githubusercontent.com/602540/131283866-9e051476-dfd7-4e1d-9760-8333c4d9277a.png) | ![image](https://user-images.githubusercontent.com/602540/131283929-9dd610ca-84bd-4826-b4a9-4ea21d101669.png) |

A note on creating backing image via StorageClass, these are latest parameters:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-bi-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  backingImage: "bi-test"
  backingImageDataSourceType: "download"
  backingImageDataSourceParameters: '{"url": "https://github.com/rancher/k3os/releases/download/v0.20.7-k3s1r0/k3os-amd64.iso"}'
  backingImageChecksum: "SHA512 checksum of the backing image"
```
