### ISSUE TITLE
Fail to attach volume mount [BUG]

### ISSUE THREAD

**Issue by opviel** [longhorn/longhorn#2533]
Installed longhorn via helm chart on a 4-raspi k3s, no arguments.

In the UI, the disk is constantly flapping between attaching and detaching.

Using the test case below, the volume fails to attach.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

The pod fails to attach the volume with the following messages:
```
Events:
  Type     Reason              Age              From                     Message
  ----     ------              ----             ----                     -------
  Warning  FailedScheduling    2m16s            default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    2m16s            default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           2m10s            default-scheduler        Successfully assigned default/volume-test to pi3
  Warning  FailedAttachVolume  10s              attachdetach-controller  AttachVolume.Attach failed for volume "pvc-b8fd8ec7-edb6-416f-b1c8-49888dd8cb1b" : attachdetachment timeout for volume pvc-b8fd8ec7-edb6-416f-b1c8-49888dd8cb1b
  Warning  FailedMount         7s               kubelet                  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[volv default-token-ldwvn]: timed out waiting for the condition
  Warning  FailedAttachVolume  2s (x4 over 9s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-b8fd8ec7-edb6-416f-b1c8-49888dd8cb1b" : rpc error: code = DeadlineExceeded desc = Failed to attach volume pvc-b8fd8ec7-edb6-416f-b1c8-49888dd8cb1b to node pi3
```

These are my longhorn pods:
```
$ kubectl get pods -n longhorn | grep -v NAME | sort
csi-attacher-5dcdcd5984-gzqrm               1/1     Running   0          3h43m
csi-attacher-5dcdcd5984-pcxgm               1/1     Running   3          3h43m
csi-attacher-5dcdcd5984-sxzfl               1/1     Running   0          3h43m
csi-provisioner-5c9dfb6446-tvk6j            1/1     Running   5          3h43m
csi-provisioner-5c9dfb6446-whtbm            1/1     Running   3          3h43m
csi-provisioner-5c9dfb6446-zqj6s            1/1     Running   2          3h43m
csi-resizer-6696d857b6-77c6j                1/1     Running   0          3h43m
csi-resizer-6696d857b6-wdqhd                1/1     Running   0          3h43m
csi-resizer-6696d857b6-xlhr8                1/1     Running   3          3h43m
csi-snapshotter-96bfff7c9-bhqtm             1/1     Running   0          3h43m
csi-snapshotter-96bfff7c9-vm68v             1/1     Running   0          3h43m
csi-snapshotter-96bfff7c9-z46kg             1/1     Running   3          3h43m
engine-image-ei-611d1496-9sn4g              1/1     Running   0          3h46m
engine-image-ei-611d1496-kngs8              1/1     Running   0          3h46m
engine-image-ei-611d1496-lm6ts              1/1     Running   1          3h46m
engine-image-ei-611d1496-vp5zn              1/1     Running   1          3h46m
instance-manager-e-84c2d65c                 1/1     Running   0          3h40m
instance-manager-e-dba3eb0c                 1/1     Running   0          3h43m
instance-manager-e-eacf0048                 1/1     Running   0          3h44m
instance-manager-e-fbc3cd5f                 1/1     Running   0          3h45m
instance-manager-r-1b89531a                 1/1     Running   0          3h45m
instance-manager-r-3750ec8d                 1/1     Running   0          3h44m
instance-manager-r-42d5793e                 1/1     Running   0          3h43m
instance-manager-r-ce876010                 1/1     Running   0          3h40m
longhorn-csi-plugin-hpz4b                   2/2     Running   4          3h43m
longhorn-csi-plugin-htjd6                   2/2     Running   0          3h43m
longhorn-csi-plugin-psn28                   2/2     Running   5          3h43m
longhorn-csi-plugin-tq6bq                   2/2     Running   0          3h43m
longhorn-driver-deployer-5d45dcdc5d-gmv4f   1/1     Running   1          3h47m
longhorn-manager-82h8v                      1/1     Running   2          3h47m
longhorn-manager-g4x4x                      1/1     Running   1          3h47m
longhorn-manager-kccdf                      1/1     Running   2          3h47m
longhorn-manager-w2dx5                      1/1     Running   2          3h47m
longhorn-ui-5879656c55-5zl29                1/1     Running   1          3h47m
```

I have found a couple of older issues which indicate that the reason might be unavailability of enough replicas, this however doesn't seem the case.
Being a total newbie, I'm pretty sure I'm just doing something wrong.

Thank you very much for your assistance.

**Environment:**
 - Longhorn version: v1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via git clone
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.20.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Alpine Linux 3.13
   - CPU per node: 4
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe): SDCard
   - Network bandwidth between the nodes: GB LAN
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal on 4 Raspberry Pi 4B
 - Number of Longhorn volumes in the cluster: 1
