### ISSUE TITLE
[FEATURE] Extend CSI Snapshot support to Longhorn snapshot

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2534]
Currently, if the user uses the CSI Snapshotter mechanism, they can only create Longhorn backups (out of cluster).

We would want to extend the CSI Snapshotter to support creating/reverting for Longhorn snapshot (in-cluster) as well.

**Comment by joshimoo** [comment]
This most likely requires the backup refactoring #1761 
So that we have a 1to1 mapping between backups and snapshots as well as have the necessary crds.
At which point the csi snapshot can operate on the crds.

**Comment by yasker** [comment]
It seems CSI snapshotter doesn't support replace in place for now:

https://github.com/container-storage-interface/spec/blob/master/spec.md#createsnapshot
```
Reverting a snapshot, where data in the original volume is erased and replaced with data in the snapshot, is an advanced functionality not every storage system can support and therefore is currently out of scope.
```

Move to planned.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2534?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by PhanLe1010** [comment]
Update:
* Draft PR is up
* LEP is coming up
* Test plan is coming up
---
Test plan
* CreateSnapshot
	* type backup
	* type snapshot
		* volume is attached
		* volume is detached
		* fail to create
	* invalid type


* Create new volume from data source
	* from backup snapshot type
	* from longhorn snapshot type
		* source volume is attached
			* snapshot exist
			* snapshot doesn’t  exist
		* source volume is detached	

* Delete
	* type backup
	* type snapshot
		* volume is detached
		* volume is attached
			* snapshot exist
			* snapshot doesn’t exist

**Comment by PhanLe1010** [comment]
### Test plan

1. Deploy the CSI snapshot CRDs, Controller as instructed at https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
1. Deploy 4 VolumeSnapshotClass:
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-backup-1
    driver: driver.longhorn.io
    deletionPolicy: Delete
    ```
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-backup-2
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: longhorn-backup
    ```   
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-snapshot
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: longhorn-snapshot
    ```
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: invalid-class
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: invalid
    ```
1. Create Longhorn volume `test-vol` of 5GB. Create PV/PVC for the Longhorn volume.
1. Create a workload that uses the volume. Write some data to the volume.
   Make sure data persist to the volume by running `sync`
1. Set up a backup target for Longhorn

#### Scenarios 1: CreateSnapshot
  * `type` is `longhorn-backup` or `""` 
    
    * Create a VolumeSnapshot with the following yaml
      ```yaml
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshot
      metadata:
        name: test-snapshot-longhorn-backup
      spec:
        volumeSnapshotClassName: longhorn-backup-1
        source:
          persistentVolumeClaimName: test-vol
      ```
    * Verify that a backup is created.
    * Delete the `test-snapshot-longhorn-backup`
    * Verify that the backup is deleted
    * Create the `test-snapshot-longhorn-backup` VolumeSnapshot with `volumeSnapshotClassName: longhorn-backup-2`
    * Verify that a backup is created.
  * `type` is `longhorn-snapshot`
    * volume is in detached state. 
      * Scale down the workload of `test-vol` to detach the volume.
      * Create `test-snapshot-longhorn-snapshot` VolumeSnapshot with `volumeSnapshotClassName: longhorn-snapshot`.
      * Verify the error `volume ... invalid state ... for taking snapshot` in the Longhorn CSI plugin.
    * volume is in attached state. 
      * Scale up the workload to attach `test-vol`
      * Verify that a Longhorn snapshot is created for the `test-vol`.
  * invalid type
    * Create `test-snapshot-invalid` VolumeSnapshot with `volumeSnapshotClassName: invalid-class`.
    * Verify the error `invalid snapshot type: %v. Must be %v or %v or` in the Longhorn CSI plugin.
    * Delete `test-snapshot-invalid` VolumeSnapshot.

#### Scenarios 2: Create new volume from CSI snapshot
  * From `longhorn-backup` type
    * Create a new PVC with the flowing yaml:
      ```yaml
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-restore-pvc
      spec:
        storageClassName: longhorn
        dataSource:
          name: test-snapshot-longhorn-backup
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      ```
    * Attach the PVC `test-restore-pvc` and verify the data 
    * Delete the PVC
  * From `longhorn-snapshot` type
    * Source volume is attached && Longhorn snapshot exist
        * Create a PVC with the following yaml:
          ```yaml
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: test-restore-pvc
          spec:
            storageClassName: longhorn
            dataSource:
              name: test-snapshot-longhorn-snapshot
              kind: VolumeSnapshot
              apiGroup: snapshot.storage.k8s.io
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
          ```
        * Attach the PVC `test-restore-pvc` and verify the data 
        * Delete the PVC
    * Source volume is detached
      * Scale down the workload to detach the `test-vol`
      * Create the same PVC `test-restore-pvc` as in the `Source volume is attached && Longhorn snapshot exist` section
      * Verify that PVC provisioning failed because the source volume is detached so Longhorn cannot verify the existence of the Longhorn snapshot in the source volume.
      * Scale up the workload to attache `test-vol`  
      * Wait for PVC to finish provisioning and be bounded
      * Attach the PVC `test-restore-pvc` and verify the data
      * Delete the PVC
    * Source volume is attached && Longhorn snapshot doesn’t  exist
      * Find the VolumeSnapshotContent of the VolumeSnapshot `test-snapshot-longhorn-snapshot`.
        Find the Longhorn snapshot name inside the field `VolumeSnapshotContent.snapshotHandle`.
        Go to Longhorn UI. Delete the Longhorn snapshot.
      * Repeat steps in the section `Longhorn snapshot exist` above.
        PVC should be stuck in provisioning because Longhorn snapshot of the source volume doesn't exist.
      * Delete the PVC `test-restore-pvc` PVC
  
#### Scenarios 3: Delete CSI snapshot
  * `longhorn-backup` type
    * Done in the above step
  * `longhorn-snapshot` type
    * volume is attached && snapshot doesn’t exist
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot` and verify that the VolumeSnapshot is deleted.
    * volume is attached && snapshot exist
      * Recreate the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Verify the creation of Longhorn snapshot with the name in the field `VolumeSnapshotContent.snapshotHandle`
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot` 
      * Verify that Longhorn snapshot is removed or marked as removed
      * Verify that the VolumeSnapshot `test-snapshot-longhorn-snapshot` is deleted.
    * volume is detached
      * Recreate the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Scale down the workload to detach `test-vol`
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Verify that VolumeSnapshot `test-snapshot-longhorn-snapshot` is stuck in deleting
