### ISSUE TITLE
[QUESTION] Data takes up more space in a fresh volume

### ISSUE THREAD

**Issue by phybros** [longhorn/longhorn#2560]
**Question**

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 32GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 1Gbe
 - Underlying Infrastructure: Baremetal

If I create a brand new PVC using longhorn, and then copy about 75MB of existing data into it, it takes up almost 300MB inside the volume. I'm trying to get a better understanding of how longhorn provisions the underlying storage so I can better right-size my volumes when creating them, rather than detaching/expanding etc.

Doesn't seem like this always happens? Maybe it happens more with many small files vs few big ones?

**Comment by PhanLe1010** [comment]
By saying ` 300MB inside the volume`, do you mean that 300MB is the `actual size` shown in Longhorn UI as in the picture below?
<img width="240" alt="Screen Shot 2021-05-04 at 9 55 38 PM" src="https://user-images.githubusercontent.com/22139961/117098500-857db200-ad23-11eb-8913-8eb57f9bc225.png">

**Comment by phybros** [comment]
@PhanLe1010 Yes

**Comment by PhanLe1010** [comment]
@phybros 
What is the capacity of the volume?

**Comment by phybros** [comment]
It was 200Mi, and I copied 69Mi into it from another disk (Non-longhorn). And the "actual size" went up to 294Mi and the pod it was attached to complained its disk was out of space.

If there's no obvious answer I can try and reproduce the scenario again if that would help?

**Comment by PhanLe1010** [comment]
I am thinking that the 294Mi `actual size` you see in Longhorn UI is because it includes the size of the filesystem (ext4, xfs, etc,...) + the size of your data. I.g., you have a bank disk and you format the disk and make a filesystem on the disk, the filesystem will consume some space of the disk. 

However, I want to verify that it is the exact reason. Could you try to reproduce it and provide us the reproduce steps?

**Comment by phybros** [comment]
Alright.

on the host i have this script `generate.sh` to create 1000 small files:

```bash
#!/bin/bash

for n in {1..1000}; do
    dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 1024 ))
done
```

on the host:

```bash
$ mkdir testdata #copy the generate.sh into it
$ cd testdata
$ ./generate.sh
# .......lots of output from dd
$ du -sh .
19M
```

and then I created a new `Job` like this:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrator
    spec:
      containers:
        - name: migrator
          image: busybox
          command: ["/bin/sh","-c"]
          args: ["ls -la /sourcedata && mkdir -p /targetdata/data && cp -rT /sourcedata /targetdata/data"]
          volumeMounts:
            - name: target-data
              mountPath: /targetdata
            - name: source-data
              mountPath: /sourcedata
      volumes:
        - name: target-data
          persistentVolumeClaim:
            claimName: longhorn-test-pvc
        - name: source-data
          hostPath:
            path: /testdata
      restartPolicy: Never
```

And of course, it did not show the same issue I had before...

In the Longhorn UI it shows the pv size as `200Mi` and the Actual Size as `22.7Mi`, so there's a tiny bit of overhead but not a huge amount.

Then, I changed the `Job` spec to delete all the files from `/targetdata/data` before copying the new ones in, and now the final Actual Size is `42.3Mi`. Is there any way to reclaim the space from the deleted files?

I think the issue I initially asked about was likely caused by me deleting and re-adding lots of new files to this PVC.
