### ISSUE TITLE
[BUG] Deploying Longhorn through Flux2 wont apply defaultSettings

### ISSUE THREAD

**Issue by Eagleman7** [longhorn/longhorn#2562]
**Describe the bug**
Deploying Longhorn through Flux2 wont apply defaultSettings:

**To Reproduce**

I use the following flux2 config to deploy Longhorn on my cluster:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Delete
      defaultClassReplicaCount: 3
    defaultSettings:
      backupTarget: s3://longhorn@minio/
      backupTargetCredentialSecret: longhorn-backup-secret
      allowRecurringJobWhileVolumeDetached: false
      createDefaultDiskLabeledNodes: false
      defaultDataPath: /var/lib/longhorn/
      defaultDataLocality: disabled
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 10
      upgradeChecker: true
      defaultReplicaCount: 3
      guaranteedEngineCPU: 0.25
      defaultLonghornStaticStorageClass: longhorn-static
      backupstorePollInterval: 300
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: true
      replicaZoneSoftAntiAffinity: true
      volumeAttachmentRecoveryPolicy: wait
      nodeDownPodDeletionPolicy: do-nothing
      allowNodeDrainWithLastHealthyReplica: false
      disableReplicaRebuild: false
      replicaReplenishmentWaitInterval: 600
      disableRevisionCounter: false
      systemManagedPodsImagePullPolicy: if-not-present
      allowVolumeCreationWithDegradedAvailability: true
      autoCleanupSystemGeneratedSnapshot: true
```
However after the deployment on a fresh cluster the defaultSettings cannot be seen in the Longhorn webinterface. I was missing theese settings for example:
```
backupTarget: s3://longhorn@minio/
backupTargetCredentialSecret: longhorn-backup-secret
```

![image](https://user-images.githubusercontent.com/4787591/116974659-bd9ed980-acbe-11eb-8ce3-23396f5a0f54.png)

**Expected behavior**
I would have expected these settings to have been applied:
```
backupTarget: s3://longhorn@minio/
backupTargetCredentialSecret: longhorn-backup-secret
```

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Flux2 (Helm)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RHEL 8.3
   - CPU per node: 3
   - Memory per node: 14
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10Gbe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 25~

**Additional context**
