### ISSUE TITLE
[QUESTION] Don't get Longhorn ServiceMonitor working

### ISSUE THREAD

**Issue by tburschka** [longhorn/longhorn#2563]
**Question**

I'm trying to get the ServiceMonitor for Longhorn to work, but it does not work jet. Anything missing?

Installed Longhorn
```
helm repo add longhorn https://charts.longhorn.io
helm repo update
kubectl create namespace longhorn-system
helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --set csi.kubeletRootDir=/var/lib/kubelet
```

prometheus-storageclass.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "prometheus"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
```

prometheus-values.yaml
```
grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```

Installed Prometheus
```
kubectl apply -f prometheus-storageclass.yaml

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
kubectl create namespace prometheus
helm upgrade --install prometheus prometheus-community/prometheus --namespace prometheus --values prometheus-values.yaml
```

Created a ServiceMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: prometheus
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
```

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: v1.21.0+k3s1
 - Node config 
   - OS type and version: Ubuntu 20.04.2 LTS
   - CPU per node: 8
   - Memory per node: 48
   - Disk type: SSD 1000GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal VServer

**Additional context**
