### ISSUE TITLE
[BUG] helm upgrade won't apply customize default setting

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2570]
**Is your feature request related to a problem? Please describe.**

The longhorn-default-setting ConfigMap sync to settings CR only when settings CR does not exist.
This means that during helm upgrade if the user changes the setting, then it won't applies to settings CR (but applies to longhorn-default-setting ConfigMap _only_)
```shell
helm upgrade longhorn longhorn/longhorn -n longhorn-system \
    --set defaultSettings.backupTarget=<new-backup-target> \
    --set defaultSettings.backupTargetCredentialSecret=<new-backup-target-credential-secret>
```

**Describe the solution you'd like**

I think we could configure the settings CR directly.
So, we don't have to write a setting controller to reconcile to longhorn-default-setting ConfigMap to settings CR.
However, to accomplish it, we need to have a structural schema on CRDs and also, have an admission webhook to validate the input of these settings.

**Describe alternatives you've considered**

N/A

**Additional context**

Related issues
- https://github.com/longhorn/longhorn/issues/2562#issuecomment-832413461
- https://github.com/longhorn/longhorn/issues/2539#issuecomment-827290662
- https://github.com/longhorn/longhorn/issues/2611
- https://github.com/longhorn/longhorn/issues/2744
- https://github.com/longhorn/longhorn/issues/2825
- https://github.com/longhorn/longhorn/issues/3398
- https://github.com/longhorn/longhorn/issues/3458

**Comment by jenting** [comment]
Note: we had a [KB](https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/) to workaround this.

**Comment by jenting** [comment]
We've lots of community issues related to this, we might need to consider raising the priority of this issue.

**Comment by jenting** [comment]
We might need to consider the validating/mutating admission webhook #791 along with this issue to auto-correct the invalid user input, for example:
- if the user input <true|false>, the Longhorn manager help auto-correct to <"true"|"false"> and updates the Setting CR.
- if the user input value but not in our value range, the Longhorn manager falls back to use the default value and updates the Setting CR.

**Comment by innobead** [comment]
> We might need to consider the validating/mutating admission webhook #791 along with this issue to auto-correct the invalid user input, for example:
> 
> * if the user input <true|false>, the Longhorn manager help auto-correct to <"true"|"false"> and updates the Setting CR.
> * if the user input value but not in our value range, the Longhorn manager falls back to use the default value and updates the Setting CR.

We need this, created https://github.com/longhorn/longhorn/issues/3241.

**Comment by jenting** [comment]
Previous the Setting CR is created by the longhorn manager. Make a test on create/upgrade the Setting CR by helm (v3.7.1) directly.

- Install longhorn v1.2.2 by helm
  ```shell
  helm install longhorn longhorn/longhorn -n longhorn-system --create-namespace
  ```
- Change the helm chart (templates/default-setting.yaml)
  ```yaml
  ---
  apiVersion: longhorn.io/v1beta1
  kind: Setting
  metadata:
    name: backup-target
    namespace: {{ include "release_namespace" . }}
  value: {{ .Values.defaultSettings.backupTarget | default "" | quote }}
  ---
  apiVersion: longhorn.io/v1beta1
  kind: Setting
  metadata:
    name: backup-target-credential-secret
    namespace: {{ include "release_namespace" . }}
  value: {{ .Values.defaultSettings.backupTargetCredentialSecret | default "" | quote }}
  ---
  ...
  ---
  ```
- Upgrade to longhorn v1.2.x by helm
  ```shell
  helm upgrade --install longhorn <path-to-the-helm-chart> -n longhorn-system --dry-run

  Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Setting "backup-target" in namespace "longhorn-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "longhorn"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "longhorn-system"
  ```

We can't change the way on change the default setting from ConfigMap to Setting CR directly.

Probably we need to consider always syncing the default setting from ConfigMap to Setting CR instead?
