### ISSUE TITLE
[QUESTION] Longhorn deployment configuration for "dedicated storage node" configuration

### ISSUE THREAD

**Issue by cyclingwithelephants** [longhorn/longhorn#2614]
**Question**
I'm trying to figure out the exact instructions involved in setting up longhorn on a 2 (worker) node k3s cluster consisting of a compute node (hostname `k3s-worker`) and a storage node (hostname `helios64`) backed by an SSD. I'd like to run longhorn in a configuration described as the "dedicated storage node" deployment model in https://rancher.com/blog/2017/announcing-longhorn-microservices-block-storage .

I go into more details below, but broadly speaking I've deployed longhorn (and longhorn only) on the storage node backed by a single disk mounted to /var/lib/longhorn, configured as below, with an example bitwarden deployment deployed to the compute node using a PVC backed by the longhorn storageClass but the pod is stuck in `ContainerCreating` with events
```
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Warning  FailedScheduling    18s               default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    17s               default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           11s               default-scheduler        Successfully assigned vaultwarden/bitwarden-999bb4b6c-fclx7 to k3s-worker
  Warning  FailedAttachVolume  9s (x3 over 11s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-86eb79bb-e398-472b-8b80-1be97e321181" : volume attachment is being deleted
  Warning  FailedAttachVolume  3s (x2 over 7s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-86eb79bb-e398-472b-8b80-1be97e321181" : rpc error: code = NotFound desc = ControllerPublishVolume: the node k3s-worker does not exist.
```

I notice it seems to think that k3s-worker is not healthy, I believe this is "longhorn" healthy rather than "k8s" healthy since k3s-worker is indeed happy and healthy from the POV of the k3s master. 

I believe the crux of my question is: Which longhorn workloads should be running on which node in the "dedicated storage node" configuration and/or what other configuration is required to make this work please?

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: v1.20.7+k3s1
 - Node config
   - OS type and version Debian based armbian on Helios64, ubuntu-20.04.2-server on k3s-worker
   - CPU per node: 6 ARM CPU on helios64 (it's a Helios64), 6 x86 vCPU on k3s-worker
   - Memory per node: 4GB on helios64, 10GB on k3s-worker
   - Disk type: SATA SSD (WD blue so relatively low IOPS)
   - Network bandwidth and latency between the nodes: 1 Gbe, 0.7ms 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**

Longhorn was deployed using kustomize:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.1.1/deploy/longhorn.yaml
patches:
- overlays/config-map-settings.yaml
- overlays/config-map-storage-class.yaml
- overlays/node-selectors/longhorn-driver-deployer.yaml
- overlays/node-selectors/longhorn-manager.yaml
- overlays/node-selectors/longhorn-ui.yaml
```

- overlays/config-map-storage-class.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-storageclass
  namespace: longhorn-system
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
      fromBackup: ""
```

- overlays/config-map-settings.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    default-replica-count: 1
    taint-toleration: storage=true:NoSchedule
    system-managed-components-node-selector: storage:true
```

and I've got 3 node selectors (`helios64` has the label `storage=true` as well as the taint `storage=true:NoSchedule`)
- overlays/node-selectors/longhorn-driver-deployer.yaml
- overlays/node-selectors/longhorn-manager.yaml
- overlays/node-selectors/longhorn-ui.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-ui
  namespace: longhorn-system
---
# That all look like
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storage
                operator: In
                values:
                - "true"
      tolerations:
      - key: "storage"
        operator: "Exists"
        effect: "NoSchedule"
```
