### ISSUE TITLE
[BUG] Workloads rescheduled to other nodes cannot get started after node unavailable

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2618]
**Describe the bug**
When the node or kubelet is down (then get back), the pod is rescheduled to other nodes but the volume succeeds to be reattachment on the old node. As a result, the pod cannot be started.

**To Reproduce**
The possible reproducing step:
1. Launch a pod with a Longhorn volume.
2. Add a NoSchedule taint to the node. Set the tolerations for Longhorn.
3. Crash Kubelet, the engine manager pod, and the pod on the node. 
4. Check if the volume is automatically reattached to the old node but the pod is being started on another node due to the taint.

**Expected behavior**
the volume should be reattached then detached before the pod is rescheduled to another node.

**Log**

**Environment:**
 - Longhorn version: v1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
- We need to find a hotfix of this issue for v1.1.2 and this ticket is for tracking the hotfix. To solve the root cause, we need to rely on [the VolumeController refactoring](https://github.com/longhorn/longhorn/issues/2527)
- The workaround is mentioned in [the Slack thread](https://rancher.slack.com/archives/C017JL8SBTJ/p1621591495014200?thread_ts=1621551310.010000&cid=C017JL8SBTJ). Need to validate then format it to a KB article later.

**Comment by innobead** [comment]
ref: #2629

**Comment by mattmattox** [comment]
I created a workaround script for this issue.
https://github.com/rancherlabs/support-tools/pull/121

**Comment by PhanLe1010** [comment]
@mattmattox 

I am not sure if the script https://github.com/rancherlabs/support-tools/pull/121 can workaround this issue.

The issue is that:
1. Start with pods are crashed on a node
2. Longhorn volume that is detached unexpectedly
3. Longhorn automatically detach the volume by setting `v.Status.PendingNodeID = v.Status.CurrentNodeID`, reset `v.Status.CurrentNodeID = ""`, stop the replicas, stop the engine, and then set the volumes' state to `Detached`
4. Kuberlet try to cleanup the crashed workload pod by sending CSI detach call to Longhorn manager. Longhorn returns `ok` since the volume is in `Detached` state
5. Longhorn continues to auto reattach the volume to the old node by setting `v.Status.CurrentNodeID =the old node`
6. Kuberlet try to start the workload pod on a different pod by sending CSI attach call to the node node. The attach calls always fail because the volume is currently attached to the old node as the result of auto reattachment feature. 

If I understand correctly, the script https://github.com/rancherlabs/support-tools/pull/121 interrupt the volume at the step 2 above and try to unset the `v.spec.nodeID`. This would make the CSI call in step 6 success but the end result is the `v.spec.nodeID` is different than the `v.Status.CurrentNodeID`. This is an error state [here](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/controller/volume_controller.go#L818)

**Comment by shuo-wu** [comment]
One simple workaround of this bug is:
1. Stop the hanging workload pod.
2. Manually detach the volume
3. Restart the workload pod.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2618?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by joshimoo** [comment]
This should be addressed as part of https://github.com/longhorn/longhorn/issues/2527 since at that point only v.Spec.NodeID will be responsible for attach/detach decisions which will then do a correct Detach when the csi-plugin performs that appropriate call.

**Comment by derekbit** [comment]
@yangchiu Can you help validate? Thank you.

**Comment by yangchiu** [comment]
Unable to reproduce on master-head (longhorn-manager 83cd31c) following [the test steps](https://github.com/longhorn/longhorn/issues/2618#issue-899208719).


1. Launch a deployment with a Longhorn volume.
```
apiVersion: v1
kind: Service
metadata:
  name: mysql-2
  labels:
    app: mysql-2
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-2
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-2
  labels:
    app: mysql-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-2 # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-2
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc-2
```

```
$ kubectl get pods -w -owide
NAME                                  READY   STATUS              RESTARTS   AGE     IP          NODE            NOMINATED NODE   READINESS GATES
longhorn-test-nfs-6cf649d7fb-6g8dq    1/1     Running             0          9m27s   10.42.3.4   ip-10-0-1-239   <none>           <none>
longhorn-test-minio-7d5979494-nvntg   1/1     Running             0          9m28s   10.42.2.3   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     ContainerCreating   0          18s     <none>      ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              1/1     Running             0          27s     10.42.2.16   ip-10-0-1-204   <none>           <none>
```

2. Add a NoSchedule taint to the node. Set the tolerations for Longhorn.
```
$ kubectl taint nodes ip-10-0-1-204 key1=value1:NoSchedule
```

3. Crash Kubelet on the node
```
$ ps aux | grep k3s
root       12722  2.1  0.9 850336 148536 ?       Ssl  02:57   0:21 /usr/local/bin/k3s agent
$ kill -9 12722
```
The k3s-agent will automatically restart, and has no effect on the volume and the workload.

4. Crash the engine manager pod on the node
```
$ kubectl delete pod instance-manager-bb3af56a3e0cd4b2a28b4a44e1661f4c -n longhorn-system
```
5. The volume will be detached and reattached, and the pod can be rescheduled to another node.
```
 kubectl get pods -w -owide
NAME                                  READY   STATUS    RESTARTS   AGE     IP           NODE            NOMINATED NODE   READINESS GATES
longhorn-test-nfs-6cf649d7fb-6g8dq    1/1     Running   0          11m     10.42.3.4    ip-10-0-1-239   <none>           <none>
longhorn-test-minio-7d5979494-nvntg   1/1     Running   0          11m     10.42.2.3    ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              1/1     Running   0          2m22s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Error     1 (1s ago)   2m28s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating   1 (1s ago)   2m28s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-9wrzw              0/1     Pending       0            0s      <none>       <none>          <none>           <none>
mysql-2-6dfc4fdd7b-9wrzw              0/1     Pending       0            0s      <none>       ip-10-0-1-239   <none>           <none>
mysql-2-6dfc4fdd7b-9wrzw              0/1     ContainerCreating   0            0s      <none>       ip-10-0-1-239   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating         2 (1s ago)   2m29s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating         2            2m29s   <none>       ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating         2            2m30s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating         2            2m30s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-z9bqb              0/1     Terminating         2            2m30s   10.42.2.16   ip-10-0-1-204   <none>           <none>
mysql-2-6dfc4fdd7b-9wrzw              1/1     Running             0            78s     10.42.3.16   ip-10-0-1-239   <none>           <none>
```
