### ISSUE TITLE
share-manager pod never runs when attempting to use a RWX pvc

### ISSUE THREAD

**Issue by windowsrefund** [longhorn/longhorn#2721]
Longhorn version: 1.1.1

I've got 2 storageclasses configured. 
  * longhorn-rep-2
  * longhorn-rep-1

I've successfully used longhorn-rep-2 via a RWO PVC which tells me the non-NFS pieces are working as expected. 

However, trying to use a RWX PVC against the longhorn-rep-1 storageclass is not working. Here's what the PVC looks like:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"media","namespace":"media"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"4200Gi"}},"storageClassName":"longhorn-rep-1"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2021-06-21T18:25:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: media
  namespace: media
  resourceVersion: "12167"
  uid: df55d2d6-a8f3-462b-bd47-b48b9747ada7
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4200Gi
  storageClassName: longhorn-rep-1
  volumeMode: Filesystem
  volumeName: pvc-df55d2d6-a8f3-462b-bd47-b48b9747ada7
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4200Gi
  phase: Bound
```
Here's a pod definition I'm trying to run against the PVC:
```
apiVersion: v1
kind: Pod
metadata:
  name: media-test
  namespace: media
spec:
  restartPolicy: Always
  containers:
  - name: media-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /media/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: media
      mountPath: /media
    ports:
    - containerPort: 80
  volumes:
  - name: media
    persistentVolumeClaim:
      claimName: media
```
and here's the event I see in the namespace I'm attempting to run the pod in:

```
68s         Warning   FailedAttachVolume      pod/media-test                            AttachVolume.Attach failed for volume "pvc-df55d2d6-a8f3-462b-bd47-b48b9747ada7" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-df55d2d6-a8f3-462b-bd47-b48b9747ada7 to kworker2: cannot attach volume pvc-df55d2d6-a8f3-462b-bd47-b48b9747ada7 because the engine image longhornio/longhorn-engine:v1.1.1 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to] from [http://longhorn-backend:9500/v1/volumes/pvc-df55d2d6-a8f3-462b-bd47-b48b9747ada7?action=attach]
```

This would indicate that 1 of my nodes is not running the engine-image-ei- pod... that's not the case

```
k get pod -n longhorn-system -o wide | grep engine
engine-image-ei-611d1496-mq447                           1/1     Running   0          104m   10.42.2.5    kworker2   <none>           <none>
engine-image-ei-611d1496-827bb                           1/1     Running   0          104m   10.42.1.6    kworker1   <none>           <none>
engine-image-ei-611d1496-lncrk                           1/1     Running   0          104m   10.42.0.7    kmaster    <none>           <none>
engine-image-ei-611d1496-qgz2b 
```

Attaching a support bundle as I'm hoping it will prove more useful than my description above.

**Comment by windowsrefund** [comment]
[longhorn-support-bundle_a97271dc-c513-4630-8cf7-87a592361fce_2021-06-21T19-29-54Z.zip](https://github.com/longhorn/longhorn/files/6689039/longhorn-support-bundle_a97271dc-c513-4630-8cf7-87a592361fce_2021-06-21T19-29-54Z.zip)

**Comment by joshimoo** [comment]
@windowsrefund Do your nodes have a single disk that can store >= 4TB? (4200Gi)

**Comment by windowsrefund** [comment]
No, the storageclass in question uses disks tagged with 'ssd'

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-rep-1
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  diskSelector: "ssd"
```
