### ISSUE TITLE
[BUG] Pod stuck in ContainerCreating when mount longhorn-rwx volume

### ISSUE THREAD

**Issue by everydots** [longhorn/longhorn#2741]
**Describe the bug**
Create a PVC use below script
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-rwx-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2G" # make this 10% bigger then the workload pvc
```

And use below pod template to 
```
apiVersion: v1
kind: Pod
metadata:
  name: jobmanager
  labels:
    app: flink-job
spec:
  restartPolicy: Always
  containers:
    - name: jobmanager
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - sleep 30; touch /opt/flink/test.log; while true; do date >> /opt/flink/test.log; sleep 1; done;
      stdin: true
      tty: true
      livenessProbe:
        exec:
          command:
            - timeout
            - "10"
            - ls
            - /opt/flink
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 10
      volumeMounts:
        - name: volv
          mountPath: /opt/flink
      ports:
        - containerPort: 80
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: longhorn-rwx-pvc
```

But when I try to run the pod, it always stuck and get me the error message below:

![image](https://user-images.githubusercontent.com/16937202/123623229-c7b50280-d83f-11eb-84ba-efc0f03c577d.png)

**To Reproduce**
1. Install longhorn
2. create longhorn rwx pvc
3. create a pod and mount with the pv

**Expected behavior**
The pod run successfully

**Environment:**
 - Longhorn version: **1.1.0**
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  **v1.18.18**
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config 
   - OS type and version:  CentOS
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS m5.medium instance type
 - Number of Longhorn volumes in the cluster:

**Additional context**
