### ISSUE TITLE
[BUG] Longhorn does not use values provided during Helm chart installation

### ISSUE THREAD

**Issue by wojtasool** [longhorn/longhorn#2744]
**Describe the bug**
For the installation we provide custom values for longhorn to use, like default data locality, or number of replicas, etc.
These are reflected in configMap but in UI these are not visible.

**To Reproduce**
1. Define configMap values
2. Install helm chart
3. UI shows defaults instead custom values.

**Expected behavior**
I do want to see custom values beeing used for installation.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (Helm):
 - Kubernetes distro (e.g. RKE//EKS) and version:
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3

**Comment by jenting** [comment]
I think it's duplicate to #2570

**Comment by c3y1huang** [comment]
Hmm, weird. @wojtasool could you provide more info on how have you defined the configMap? Is it by the helm command for example, `helm install longhorn --namespace longhorn-system --set defaultSettings.defaultReplicaCount="5" .
` ?

Is it happening on a  fresh install or upgrade?

**Comment by wojtasool** [comment]
To install we use terraform helm provider.
There is configMap named  default-setting.yaml with content:
```default-data-path: /mnt/data
default-replica-count: 2
backup-target: 
backup-target-credential-secret: 
allow-recurring-job-while-volume-detached: 
create-default-disk-labeled-nodes: 
replica-soft-anti-affinity: 
storage-over-provisioning-percentage: 
storage-minimal-available-percentage: 
upgrade-checker: 
default-data-locality: best-effort
guaranteed-engine-cpu: 5
default-longhorn-static-storage-class: 
backupstore-poll-interval: 
taint-toleration: 
system-managed-components-node-selector: 
priority-class: 
auto-salvage: true
auto-delete-pod-when-volume-detached-unexpectedly: true
disable-scheduling-on-cordoned-node: 
replica-zone-soft-anti-affinity: 
volume-attachment-recovery-policy: 
node-down-pod-deletion-policy: 
allow-node-drain-with-last-healthy-replica: 
mkfs-ext4-parameters: 
disable-replica-rebuild: 
replica-replenishment-wait-interval: 
disable-revision-counter: 
system-managed-pods-image-pull-policy: 
allow-volume-creation-with-degraded-availability: 
auto-cleanup-system-generated-snapshot: 
concurrent-automatic-engine-upgrade-per-node-limit: 
backing-image-cleanup-wait-interval: 
guaranteed-engine-manager-cpu: 5
guaranteed-replica-manager-cpu: 5

```

**Comment by wojtasool** [comment]
I can see in container it is mounted under /var/lib/longhorn-setting/default-setting.yaml and I can see those values I specified. But in UI I can still see that for example default data path is /var/lib/longhorn/

**Comment by wojtasool** [comment]
This is fresh install

**Comment by c3y1huang** [comment]
We [recommend](https://longhorn.io/docs/1.1.1/advanced-resources/deploy/customizing-default-settings/#using-helm) to use the defaultSettings in the [chart/values.yaml](https://github.com/longhorn/longhorn/blob/v1.1.1/chart/values.yaml#L69-L104). Does this not work for you?

**Comment by wojtasool** [comment]
This is how it is set.

**Comment by c3y1huang** [comment]
Got it, do you know if the setting CR already exists before terraform provider runs helm installation? Are you able to try again by clean up the resources and re-install manually with `helm install longhorn/longhorn --name longhorn --namespace longhorn-system --values values.yaml` to see if the result is the same?

**Comment by wojtasool** [comment]
You mean CRD already exist?

**Comment by c3y1huang** [comment]
Referring to the CR if it pre-exists before the helm install then the configmap will not get respected.
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/datastore/longhorn.go#L40-L65 This behavior is explained in https://github.com/longhorn/longhorn/issues/2570.

**Comment by wojtasool** [comment]
Worked on manual installation. But I don't get it why?
Whats the difference?
In both installations any resource didn't existed.

**Comment by c3y1huang** [comment]
I've verified this is happening with [terraform-provider-helm](https://github.com/hashicorp/terraform-provider-helm). And issue was also raised in https://github.com/longhorn/longhorn/issues/2562#issuecomment-842228752.

@wojtasool , the only reason I could think of is the helm provider created the CR then later made an update with the custom values. With this case, we are tracking the fix in https://github.com/longhorn/longhorn/issues/2570. 

The current workaround is to use the helm command instead.

**Comment by wojtasool** [comment]
default-replica-count: 2 is whats actually in default-setting.yaml file after templating. This is how it is defined in helm chart repository.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
data:
  default-setting.yaml: |-
    default-data-path: {{ .Values.defaultSettings.defaultDataPath }}
    default-replica-count: {{ .Values.defaultSettings.defaultReplicaCount }}
    backup-target: {{ .Values.defaultSettings.backupTarget }}
    backup-target-credential-secret: {{ .Values.defaultSettings.backupTargetCredentialSecret }}
    allow-recurring-job-while-volume-detached: {{ .Values.defaultSettings.allowRecurringJobWhileVolumeDetached }}
    create-default-disk-labeled-nodes: {{ .Values.defaultSettings.createDefaultDiskLabeledNodes }}
    replica-soft-anti-affinity: {{ .Values.defaultSettings.replicaSoftAntiAffinity }}
    storage-over-provisioning-percentage: {{ .Values.defaultSettings.storageOverProvisioningPercentage }}
    storage-minimal-available-percentage: {{ .Values.defaultSettings.storageMinimalAvailablePercentage }}
    upgrade-checker: {{ .Values.defaultSettings.upgradeChecker }}
    default-data-locality: {{ .Values.defaultSettings.defaultDataLocality }}
    guaranteed-engine-cpu: {{ .Values.defaultSettings.guaranteedEngineCPU }}
    default-longhorn-static-storage-class: {{ .Values.defaultSettings.defaultLonghornStaticStorageClass }}
    backupstore-poll-interval: {{ .Values.defaultSettings.backupstorePollInterval }}
    taint-toleration: {{ .Values.defaultSettings.taintToleration }}
    system-managed-components-node-selector: {{ .Values.defaultSettings.systemManagedComponentsNodeSelector }}
    priority-class: {{ .Values.defaultSettings.priorityClass }}
    auto-salvage: {{ .Values.defaultSettings.autoSalvage }}

```

**Comment by wojtasool** [comment]
And values.yaml file contains this:

```
defaultSettings:
  backupTarget: ~
  backupTargetCredentialSecret: ~
  allowRecurringJobWhileVolumeDetached: ~
  createDefaultDiskLabeledNodes: ~
  defaultDataPath: /mnt/data
  defaultDataLocality: best-effort
  replicaSoftAntiAffinity: ~
  storageOverProvisioningPercentage: ~
  storageMinimalAvailablePercentage: ~
  upgradeChecker: ~
  defaultReplicaCount: 2
  guaranteedEngineCPU: 5
  defaultLonghornStaticStorageClass: ~
  backupstorePollInterval: ~
  taintToleration: ~
  systemManagedComponentsNodeSelector: ~
  priorityClass: ~
  autoSalvage: true

```
