### ISSUE TITLE
[BUG] High CPU utilization for Longhorn manager sometimes, due to exhaustion of all the available sockets

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2778]
**Describe the bug**
Longhorn manager keeps opening an unbounded number of socket connections to instance manager pod when there is a volume in error state described in the below reproduce steps

**To Reproduce**
1. Create a cluster of 3 worker nodes. Tag `node-1` with the tag `node-1` in Longhorn UI
2. Create a volume with 1 replica, `data-locality` set to `best-effort`, tag set to `node-1`
3. Create PV/PVC from the volume. 
4. Create a pod that uses the PVC. Set node selector for the pod so that it will be schedule on to `node-2`. This makes sure that there is a failed-to-scheduled local replica
5. Wait for the pod to be in running state.
6. Kill the instance manager r on `node-1`.
7. Observe that:
    1. The only replica of the volume (the one on `node-1`) fails but Longhorn doesn't detach/salvage the volume
    2. The `spec.logRequested` of the engine of the volume keep flapping between `true` and `false`. Longhorn manager is repeatedly fetching the logs from the instance manager. It is expected that the log is fetched once but it is not the case here
    3. exec into the instance manager e on the `node-2`, running `ss -a -n | grep :8500 | wc -l` show that number of socket connections from the instance manager to Longhorn manager is increasing unboundedly.   

**Expected behavior**
We should not observe the behavior in step 7 above

**Environment:**
 - Longhorn version: Longhorn v1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): v1.20.8
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 18.04.5 LTS
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 7Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Linode
 - Number of Longhorn volumes in the cluster: 1

**Additional context**
The number of opening socket connections might be related to the high CPU usage issue.

**Comment by PhanLe1010** [comment]
From the code perspective, we have the following issues (to be continued to be updated): 
1. We don't auto detach/salvage the volume when there is a replica that doesn't have `r.Spec.FailedAt == ""`. In this case, the failed local replica is the one that is blocking auto salvage [here](https://github.com/longhorn/longhorn-manager/blob/ac065a8deb96193ffec142bcc7e7345615b57b8d/controller/volume_controller.go#L998-L1004)
2. We forget to close the logs streaming connection [here](https://github.com/longhorn/longhorn-manager/blob/a56ca0f299b90a33690ee2cb1169977b17fd28f2/controller/instance_handler.go#L333-L350) which may be lead to leaking socket connections
...

**Comment by PhanLe1010** [comment]
**Additional context:**

Frankly, I cannot reproduce the problem (Longhorn doesn't auto detach/salvage the volume) by following the seemly very similar steps:
1. Create a cluster of 3 nodes. Tag node-1 with the tag `node-1` in longhorn UI
1. Create a volume with 2 replicas and `node-1` tag 
1. Create PV/PVC from volume.
1. Create a pod that uses the PVC. Wait for the pod to be running
1. Note that at this moment we have 1 running replica and 1 fail to schedule replica (very similar to the reproduced steps in the issue's description)
1. Kill the instance manager r on the `node-1`
1. I observed that Longhorn auto detach/salvage the volume

Looking closer into this case, I am thinking the following flow might have happened:

1. Before killing the instance manager r on `node-1`, there are 2 replicas:
    * `vol3-r-48c876ef` is running replica on `node-1`
    *  `vol3-r-d91f8ec8` is the failed-to-schedule replica
1. Kill the instance manager r on `node-1`.
1. The replica `vol3-r-48c876ef` immediately become failed and has `r.Spec.FailedAt` set
1. `vol3-r-d91f8ec8` is immediately scheduled to `node-1`. Then volume controller quickly marks it failed and set `r.Spec.FailedAt` because the instance manager r is in error state. The spec of the replica at this moment is:
    ```
    spec:
      ...
      failedAt: "2021-07-08T01:16:20Z"
      hardNodeAffinity: ""
      healthyAt: ""
      logRequested: false
      nodeID: phan-v61-worker-2
      ...
    ```
1. Now all replicas have `r.Spec.FailedAt != ""` so the auto detachment/salvage logic triggged [here](https://github.com/longhorn/longhorn-manager/blob/ac065a8deb96193ffec142bcc7e7345615b57b8d/controller/volume_controller.go#L998-L1004)
1. Longhorn cleans up `vol3-r-d91f8ec8` because it failed before ever become healthy [here](https://github.com/longhorn/longhorn-manager/blob/ac065a8deb96193ffec142bcc7e7345615b57b8d/controller/volume_controller.go#L740-L745)
1. Longhorn reattaches the volume, the volume state at this moment:
    * `vol3-r-48c876ef` is running replica on `node-1`
    *  a new the failed-to-schedule replica

**Comment by shuo-wu** [comment]
I can reproduce this issue by following the reproducing step you provide. But it leads to **manager pods high memory consumption** rather than high CPU usage.
Here is the result after around 8 hours of the replica instance manager pod killing. (The volume get stuck and longhorn manager pods continuously dumping the engine manager logs):
```
root@longhorn-manager-7q6mc:/# ss -a -n | grep :8500 | wc -l
14628

$ kl top pod
NAME                                       CPU(cores)   MEMORY(bytes)
csi-attacher-5dcdcd5984-fxgfc              1m           9Mi
csi-attacher-5dcdcd5984-k6bjg              1m           6Mi
csi-attacher-5dcdcd5984-pmpgj              1m           8Mi
csi-provisioner-5c9dfb6446-lz75n           1m           7Mi
csi-provisioner-5c9dfb6446-mpq8d           1m           7Mi
csi-provisioner-5c9dfb6446-rzwg7           1m           5Mi
csi-resizer-6696d857b6-gl4fb               1m           7Mi
csi-resizer-6696d857b6-hhq2t               1m           8Mi
csi-resizer-6696d857b6-v54mq               1m           6Mi
csi-snapshotter-96bfff7c9-bjxl8            4m           5Mi
csi-snapshotter-96bfff7c9-r6c42            1m           4Mi
csi-snapshotter-96bfff7c9-zr7xv            1m           6Mi
engine-image-ei-611d1496-826fn             4m           16Mi
engine-image-ei-611d1496-c5v8z             4m           16Mi
engine-image-ei-611d1496-psnzf             3m           17Mi
instance-manager-e-06297326                4m           6Mi
instance-manager-e-3465d64b                8m           1074Mi
instance-manager-e-99d7093f                2m           7Mi
instance-manager-r-05722059                4m           7Mi
instance-manager-r-68c9c2bf                3m           5Mi
instance-manager-r-6afca555                2m           5Mi
longhorn-csi-plugin-hckcw                  1m           8Mi
longhorn-csi-plugin-jmrnz                  1m           9Mi
longhorn-csi-plugin-vbgzs                  1m           8Mi
longhorn-driver-deployer-84cb76fb6-4zqnw   1m           7Mi
longhorn-manager-7q6mc                     75m          1526Mi
longhorn-manager-8hvn6                     61m          31Mi
longhorn-manager-jprrg                     11m          28Mi
longhorn-ui-6bd7d7f457-lh99f               1m           2Mi

$ kl top nodes
NAME                      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
shuo-cluster-1-master-1   275m         13%    1694Mi          44%
shuo-cluster-1-worker-1   206m         10%    1928Mi          50%
shuo-cluster-1-worker-2   476m         23%    3311Mi          86%
shuo-cluster-1-worker-3   186m         9%     1875Mi          48%
```

**Comment by joshimoo** [comment]
@shuo-wu add additional volumes that are managed by this longhorn-manager <-> instance-manager
Then also wait till you have exhausted all sockets.
You previously also fixed the engine monitor once it loses connection, which was a good change.

You can also run the strace for just the summary.
```
# run strace(2m) summary for process and follow child creation
# will create single file of the form process-summary
timeout 120s strace -c -o process-summary -pf 24999
```
Replace 24999 with the pid of the longhorn-manager binary on the node.
You probably will see a lot of futex contetion once you exhausted all the sockets.

**Comment by shuo-wu** [comment]
Do you mean adding multiple stuck volumes to speed up the socket exhausting? I did saw `futex` in the strace result:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 78.21   11.840590         757     15638      1683 futex
  6.99    1.058598          49     21474         2 nanosleep
  6.49    0.983102          94     10449         6 epoll_pwait
  2.19    0.331355        2761       120         1 waitid
  1.41    0.213530        2272        94        94 connect
```

Can this result (the time `futex` spent) above indicate the `futex` contention? Or isn't this value (78%) high enough?

**Comment by PhanLe1010** [comment]
Using the reproduced steps, I was able to reproduce the high CPU usage once the socket connections were exhausted (must use node with 16GB RAM to be able to exhaust the socket connections. If the amount of RAM is too small, Kubernetes may kill the pods because of OOM before we see the socket connection exhaustion)
* Longhorn manager socket connections:
  ```
  root@longhorn-manager-8sq2n:/# ss -a -n | grep :8500 | wc -l
  28234
  ```
* Top on the node of the affected manager:  
  <img width="601" alt="Screen Shot 2021-07-11 at 2 19 49 AM" src="https://user-images.githubusercontent.com/22139961/125190017-ec21bf00-e1ef-11eb-9032-831dd2dc4ff7.png">
* Kubectl top:
  <img width="493" alt="Screen Shot 2021-07-11 at 2 19 16 AM" src="https://user-images.githubusercontent.com/22139961/125190037-03f94300-e1f0-11eb-8352-75cb5c7ca104.png">
* strace
  ```
  % time     seconds  usecs/call     calls    errors syscall
  ------ ----------- ----------- --------- --------- ----------------
   84.46 9316.826841      123590     75385      5337 futex
   13.56 1496.266842       22982     65107     65107 connect
    0.67   74.178692        1211     61254           close
    0.49   54.423508         793     68616           socket
    0.38   41.520256         615     67546           setsockopt
    0.25   27.507392        1271     21638           nanosleep
    0.05    5.835085         711      8211           epoll_pwait
    0.05    5.291455         814      6502       739 rt_sigreturn
    0.03    3.697038         569      6497           tgkill
    0.03    2.909914         448      6499           getpid
    0.01    0.876263         789      1110       312 read
    0.01    0.633235         935       677         3 write
    0.00    0.531174         879       604        24 epoll_ctl
    0.00    0.222706        1437       155           sched_yield
    0.00    0.073279         535       137           getsockopt
    0.00    0.057332         382       150           getsockname
    0.00    0.055490         417       133           getpeername
    0.00    0.033029       11010         3           clone
    0.00    0.024799         335        74           fcntl
    0.00    0.010904        3635         3           writev
    0.00    0.010263         684        15           pipe2
    0.00    0.008391        2098         4           fstat
    0.00    0.003208         267        12           openat
    0.00    0.001579          79        20         1 accept4
    0.00    0.001542         171         9           rt_sigprocmask
    0.00    0.000076          76         1           newfstatat
    0.00    0.000040          40         1           restart_syscall
  ------ ----------- ----------- --------- --------- ----------------
  ```

**Comment by PhanLe1010** [comment]
Workaround:
Kill the corresponding Longhorn manager pod

**Comment by innobead** [comment]
@PhanLe1010 Please help backport to 1.1.3 branch and update the pre-check list.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

Steps:
    1. Add the tag `node-1` to `node-1`
    2. Create a volume with 1 replica, data-locality set to best-effort,
       and tag set to `node-1`
    3. Create PV/PVC from the volume.
    4. Create a pod that uses the PVC. Set node selector for the pod so that it will be schedule on to `node-2`. This makes sure that there is a failed-to-scheduled local replica

```
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-simple-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - meldafrawi-lh-02
  restartPolicy: Always
  containers:
    - name: volume-test
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - ls
            - /data/lost+found
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - name: volv
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: <VOLUME_CLAIM_NAME>
```

5. Wait for the pod to be in running state, write some data and compute it's checksum.
6. Kill the instance manager r on `node-1`.
7. In a 3-min retry loop, verify that Longhorn salvage the volume
       and the workload pod is restarted. Exec into the workload pod.
       Verify that read/write to the volume is ok
       > Pod is stuck in `CrashLoopBackOff` and i was not able to access the data  **FAILED**
```
Events:
  Type     Reason                  Age                     From                       Message
  ----     ------                  ----                    ----                       -------
  Normal   Scheduled               13m                     default-scheduler          Successfully assigned default/longhorn-simple-pod to meldafrawi-lh-02
  Normal   SuccessfulAttachVolume  13m                     attachdetach-controller    AttachVolume.Attach succeeded for volume "volume-test"
  Normal   Pulled                  10m (x4 over 13m)       kubelet, meldafrawi-lh-02  Container image "nginx:stable-alpine" already present on machine
  Normal   Created                 10m (x4 over 13m)       kubelet, meldafrawi-lh-02  Created container volume-test
  Normal   Killing                 10m (x3 over 10m)       kubelet, meldafrawi-lh-02  Container volume-test failed liveness probe, will be restarted
  Normal   Started                 9m59s (x4 over 13m)     kubelet, meldafrawi-lh-02  Started container volume-test
  Warning  Unhealthy               8m25s (x17 over 10m)    kubelet, meldafrawi-lh-02  Liveness probe failed: ls: /data/lost+found: I/O error
  Warning  BackOff                 3m12s (x29 over 9m20s)  kubelet, meldafrawi-lh-02  Back-off restarting failed container

```
       
8. Exec into the longhorn manager pod on `node-2`.
       Running `ss -a -n | grep :8500 | wc -l` to find the number of socket
       connections from this manager pod to instance manager pods.
       In a 2-min loop, verify that the number of socket connection is <= 20
       > **PASSED**

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps:
    1. Add the tag `node-1` to `node-1`
    2. Create a volume with 1 replica, data-locality set to best-effort,
       and tag set to `node-1`
    3. Create PV/PVC from the volume.
    4. Create a deployment with one pod that uses the PVC. Set node selector for the pod so that it will be schedule on to `node-2`. This makes sure that there is a failed-to-scheduled local replica

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - meldafrawi-lh-02
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: volume-test
```

5. Wait for the pod to be in running state, write some data and compute it's checksum.
6. Kill the instance manager r on `node-1`.
7. In a 3-min retry loop, verify that Longhorn salvage the volume
       and the workload pod is restarted. Exec into the workload pod.
       Verify that read/write to the volume is ok
       > **PASSED**
       
8. Exec into the longhorn manager pod on `node-2`.
       Running `ss -a -n | grep :8500 | wc -l` to find the number of socket
       connections from this manager pod to instance manager pods.
       In a 2-min loop, verify that the number of socket connection is <= 20
       > **PASSED**
