### ISSUE TITLE
[QUESTION] Multiple pods from different namespaces same volume

### ISSUE THREAD

**Issue by erginacta** [longhorn/longhorn#2795]
**Question**
I have two namespaces with pods. They need to share their volume for some tasks.
Is it possible to bind a volume from another namespace?

like having two pvc's pointing to the same volume. The other pvc would just have another namespace.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  name: nfs-dev
  namespace: wildfly
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-custom
  volumeName: pvc-ebc04dc8-0080-413a-adcb-1b210a3c0e98

```
**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes version: v1.20.4
