### ISSUE TITLE
[QUESTION] BackupTarget Secret Injection via HashiCorp Vault

### ISSUE THREAD

**Issue by janlauber** [longhorn/longhorn#2804]
**Question**

Hey Guys
Has anyone tried injecting the BackupTargetSecret into the Longhorn Helm Chart using Hashicorp Vault Injector? Or does anyone have some idea how to implement this?

I just found out, that the secret will be rendered into an yaml file, but I don't know how the longhorn-manager will access the BackupTargetSecret. When I knew how this will take place, it would be easier to design a vault injection.

Thank you very much for your help
greez

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20.8
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

**Comment by janlauber** [comment]
what does the longhorn-manager does with the /var/lib/longhorn-setting/default-setting.yaml file?
where will the backuptarget secret be mounted or converted into a env variable?

**Comment by janlauber** [comment]
So I just took a deeper dive into the code of the longhorn-manager and found what I needed to know.
There is a function called "GetCredentialFromSecret" which implements the mechanism of getting the Values of the provided targetBackupSecret. I think it would be awesome if I can implement another function, called "GetCredentialFromEnv" which allowes us to provide the 3 needed variables to inject them via vault-agent-injector into a OS Env when no Kubernetes Secret is provided.

I'm new in this community and it would be my first contribution to a opensource project and would appreciate it if you keep that in mind when looking at my upcomming PR. :)

**Comment by janlauber** [comment]
@c3y1huang please label this issue to a Feature request

**Comment by janlauber** [comment]
Okey I just found a function, which just does what I requested and was about to implement!
Its the getBackupCredentialEnv() in backups.go

**Comment by janlauber** [comment]
Okey got now a clue how to do this, but I think I need to add sth in the Longhorn helm charts. The ability to start the longhorn-manager with args to load the env variables.
annotations for the deployment (sth like that):
```yaml
annotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/agent-inject-secret-minio-creds: 'flux/minio/creds'
  vault.hashicorp.com/agent-inject-file-minio-creds: 'minio_env'
  vault.hashicorp.com/agent-inject-template-minio-creds: |
    {{- with secret "flux/minio/creds" -}}
      export AWS_ACCESS_KEY_ID="{{ .Data.data.minio_access_key }}"
      export AWS_SECRET_ACCESS_KEY="{{ .Data.data.minio_secret_key }}"
      export AWS_ENDPOINTS="{{ .Data.data.minio_endpoint }}"
    {{- end }}
  vault.hashicorp.com/role: 'minio-longhorn'
```

Now I need to add sth like that for the longhorn-manager:
```yaml
args:
  ['sh', '-c', 'source /vault/secrets/config && <entrypoint script>']
```
