### ISSUE TITLE
[BUG] When data locality is enabled, it does not trigger replica migrations when one is possible

### ISSUE THREAD

**Issue by tyzbit** [longhorn/longhorn#2806]
**Describe the bug**
On my cluster, when data locality is set to `best-effort` for a volume and a pod that consumes the volume is scheduled to a node that is capable of hosting a replica, Longhorn does not schedule a replica on the new node and delete a random replica from an old node as expected.

**To Reproduce**
1. Install Longhorn with data-locality disabled by default
2. Create a workload with a volume (edit: must be RWX, as explained below)
3. Configure the volume to have data-locality: `best-effort` in the UI
4. Start the workload
5. Cordon the nodes that host the existing replicas of the volume
6. Rollout restart the workload such that a pod gets scheduled on a node without a replica
7. Uncordon the nodes (not necessary)
8. Observe that Longhorn does not create a new replica on the node hosting the pod as expected

**Expected behavior**
When data-locality is set to `best-effort`, nodes that are eligible to host replicas for pods without a local replica should build a replica locally and once built, a random other node should remove a replica.

**Log**

Emailed.

Example PVC with data-locality enabled: pvc-579bf140-9022-4a99-8c80-1b38b1595996
Replicas on anchorman and weatherman
Scheduled pod on showman, it runs but a local replica is not created.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04.1 LTS
   - CPU per node: 8
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 2.5Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 24

**Comment by PhanLe1010** [comment]
Thanks @tyzbit for a very detailed and clear issue description. If everyone creates issues like this, it would save us a lot of time guessing around. 

I see that the volume `pvc-579bf140-9022-4a99-8c80-1b38b1595996` is in RWX access mode. Some background information first, in Longhorn, RWX is achieved by having an NFS server on top of a traditional RWO Longhorn volume. When a workload pod attaches an RWX volume, Longhorn attaches the underlying RWO volume to a random node, then create NFS server on that node which uses the RWO volume. Longhorn then mounts the NFS endpoint to the node where the workload pod is scheduled to.  Now if you create another workload pod that uses the RWX volume, Longhorn creates one more NFS endpoint and mount it to the node of the new workload pod. Data locality feature ensures that there is 1 replica of the volume on the same node as the engine of the volume. This makes sure that the volume engine can still read/write to the local replica in case other replicas are disconnected. In this case, the engine of the volume is on the node where the NFS server is running on, not on the node of the workload pods.

Looking into the volume `pvc-579bf140-9022-4a99-8c80-1b38b1595996`, I see that it is attached to the node `anchorman` and there is a local replica on node `anchorman`. Therefore, everything seems working as expected.
```
  status:
    ownerid: anchorman
    state: attached
    robustness: healthy
    currentnodeid: anchorman
    currentimage: longhornio/longhorn-engine:v1.1.2
    kubernetesstatus:
      pvname: pvc-579bf140-9022-4a99-8c80-1b38b1595996
      pvstatus: Bound
      namespace: default
      pvcname: deluge-downloads
      lastpvcrefat: ""
      workloadsstatus:
      - podname: deluge-d8b8c685-pkt9f
        podstatus: Running
        workloadname: deluge-d8b8c685
        workloadtype: ReplicaSet
      - podname: filebrowser-0
        podstatus: Running
        workloadname: filebrowser
        workloadtype: StatefulSet
      - podname: sickchill-0
        podstatus: Running
        workloadname: sickchill
        workloadtype: StatefulSet
      lastpodrefat: ""
```
