### ISSUE TITLE
[FEATURE] Expose iSCSI targets to clients outside of the cluster

### ISSUE THREAD

**Issue by yankcrime** [longhorn/longhorn#2813]
**Is your feature request related to a problem? Please describe.**
iSCSI clients *outside* of the Kubernetes cluster in which Longhorn is installed should be able to connect to volumes created and presented as iSCSI targets.

**Describe the solution you'd like**
[Existing documentation and steps](https://longhorn.io/docs/1.1.2/advanced-resources/iscsi/) are followed.  The volume details should be published with an external IP address instead of the internal cluster IP.

iSCSI initiators should be able to discover and connect to Longhorn volumes via this published cluster external address.

**Additional context**
A similar request is described in #906, however the workaround in this case was to deploy VMs on the same nodes as Kubernetes workers and plumbing in their networking into the overlay.  A better solution would be to enhance Longhorn's functionality to properly expose iSCSI targets externally.

It's possible to at least define a Service of type NodePort that refers to an Endpoint with the IP and port returned by Longhorn when you create a volume with the iSCSI frontend option, for example:

```
kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-iscsi"
spec:
  type: NodePort
  ports:
    - name: "iscsi"
      protocol: "TCP"
      port: 3260
      targetPort: 3260
      nodePort: 0
  selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-iscsi"
subsets:
  - addresses:
      - ip: "10.42.8.9"
    ports:
      - port: 3260
        name: "iscsi"
```

An external client can then perform target discovery using this NodePort, for example:

```
% sudo iscsiadm --mode discoverydb --type sendtargets --portal 192.168.1.120:32615 --discover
10.42.8.9:3260,1 iqn.2019-10.io.longhorn:external
```

However, the IP address and port returned from this discover refers back to the cluster internal address, so attempts to connect to this from outside Kubernetes eventually just timeout.  In addition, even if this did work it'd be targeting a single internal service and so would not be HA.
