### ISSUE TITLE
[QUESTION] Which parameter should I set in helm-chart to pass tolerations to the daemonsets: longhorn-csi-plugin and engine-image-ei?

### ISSUE THREAD

**Issue by Jasstkn** [longhorn/longhorn#2825]
**Question**
Hi! I've been trying using Longhorn but I faced with the following problem: I can't pass tolerations to the daemonsets which are created automatically - longhorn-csi-plugin and engine-image-ei. 

Could you tell me which option in helm-chart should I configure to fix this issue?

My current config is:
```
defaultSettings:
  taintToleration: "infra=true:NoSchedule,node=true:NoSchedule"

longhornManager:
  tolerations:
    - key: "infra"
      operator: "Exists"
    - key: "node"
      operator: "Exists"

longhornDriver:
  tolerations:
    - key: "infra"
      operator: "Exists"
  nodeSelector:
    type: infra

longhornUI:
  tolerations:
    - key: "infra"
      operator: "Exists"
  nodeSelector:
    type: "infra"
```

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: 1.20
 - Node config
   - OS type and version N/A
   - CPU per node: N/A
   - Memory per node: N/A
   - Disk type N/A
   - Network bandwidth and latency between the nodes: N/A
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hybrid (Rancher in Hetzner cloud + some dedicated machines)
