### ISSUE TITLE
[QUESTION] How do I fix the problem when I apply pod on the node which not in Longhorn 

### ISSUE THREAD

**Issue by HuFei2017** [longhorn/longhorn#2826]
**Question**
Hi!
Recently, I get a problem when I apply pod on K8S using default Longhorn storageclass.

I have 3 nodes, which names node02, node03, node04. I plan to install Longhorn on the node04, and running pods on node02 and node03. So, I'm trying to use node selector to specify the node04 as the dedicated node.

I install Longhorn via Rancher, and before installation, I set the nodeselector in the yaml. After installation, I can get the default storageclass named `longhorn`, the UI like this:

![image](https://user-images.githubusercontent.com/32692138/127453295-e78afd97-dcfb-4cb6-a33a-4b6b60d18915.png)

the content of yaml is:
```
---
  image: 
    defaultImage: true
    longhorn: 
      manager: 
        repository: "longhornio/longhorn-manager"
        tag: "v1.1.2"
      engine: 
        repository: "longhornio/longhorn-engine"
        tag: "v1.1.2"
      ui: 
        repository: "longhornio/longhorn-ui"
        tag: "v1.1.2"
      instanceManager: 
        repository: "longhornio/longhorn-instance-manager"
        tag: "v1_20210621"
      shareManager: 
        repository: "longhornio/longhorn-share-manager"
        tag: "v1_20210416"
      backingImageManager: 
        repository: "longhornio/backing-image-manager"
        tag: "v1_20210422"
    csi: 
      attacher: 
        repository: "longhornio/csi-attacher"
        tag: "v2.2.1-lh2"
      provisioner: 
        repository: "longhornio/csi-provisioner"
        tag: "v1.6.0-lh2"
      nodeDriverRegistrar: 
        repository: "longhornio/csi-node-driver-registrar"
        tag: "v1.2.0-lh1"
      resizer: 
        repository: "longhornio/csi-resizer"
        tag: "v0.5.1-lh2"
      snapshotter: 
        repository: "longhornio/csi-snapshotter"
        tag: "v2.1.1-lh2"
  privateRegistry: 
    registryUrl: ""
    registryUser: ""
    registryPasswd: ""
    registrySecret: ""
  longhorn: 
    default_setting: true
  csi: 
    kubeletRootDir: ""
    attacherReplicaCount: "3"
    provisionerReplicaCount: "3"
    resizerReplicaCount: "3"
    snapshotterReplicaCount: "3"
  defaultSettings: 
    backupTarget: ""
    backupTargetCredentialSecret: ""
    allowRecurringJobWhileVolumeDetached: false
    createDefaultDiskLabeledNodes: true
    defaultDataPath: "/var/lib/longhorn/"
    defaultDataLocality: "disabled"
    replicaSoftAntiAffinity: false
    storageOverProvisioningPercentage: "100"
    storageMinimalAvailablePercentage: "10"
    upgradeChecker: false
    defaultReplicaCount: "1"
    defaultLonghornStaticStorageClass: "longhorn-static"
    backupstorePollInterval: "300"
    autoSalvage: true
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
    disableSchedulingOnCordonedNode: true
    replicaZoneSoftAntiAffinity: true
    volumeAttachmentRecoveryPolicy: "wait"
    nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
    allowNodeDrainWithLastHealthyReplica: false
    mkfsExt4Parameters: ""
    disableReplicaRebuild: false
    replicaReplenishmentWaitInterval: "600"
    disableRevisionCounter: false
    systemManagedPodsImagePullPolicy: "if-not-present"
    allowVolumeCreationWithDegradedAvailability: false
    autoCleanupSystemGeneratedSnapshot: true
    concurrentAutomaticEngineUpgradePerNodeLimit: "0"
    backingImageCleanupWaitInterval: "60"
    guaranteedEngineManagerCPU: "12"
    guaranteedReplicaManagerCPU: "12"
    systemManagedComponentsNodeSelector: "name:node04"
  persistence: 
    defaultClass: true
    reclaimPolicy: "Delete"
    defaultClassReplicaCount: "1"
    recurringJobs: 
      enable: false
      jobList: ""
  ingress: 
    enabled: false
    host: "xip.io"
  service: 
    ui: 
      type: "NodePort"
      nodePort: ""
  enablePSP: true
  longhornManager:
    nodeSelector:
      name: "node04"
  longhornDriver:
    nodeSelector:
      name: "node04"
  longhornUI:
    nodeSelector:
      name: "node04"
```

In K8S, I can see the node labels as following:
```
NAME     STATUS   ROLES               AGE   VERSION   LABELS
node01   Ready    controlplane,etcd   21d   v1.20.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node01,kubernetes.io/os=linux,name=node01,node-role.kubernetes.io/controlplane=true,node-role.kubernetes.io/etcd=true
node02   Ready    worker              21d   v1.20.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cassandra=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=node02,kubernetes.io/os=linux,name=node02,node-role.kubernetes.io/worker=true
node03   Ready    worker              21d   v1.20.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cassandra=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=node03,kubernetes.io/os=linux,name=node03,node-role.kubernetes.io/worker=true
node04   Ready    worker              21d   v1.20.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cassandra=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=node04,kubernetes.io/os=linux,name=node04,node-role.kubernetes.io/worker=true
```

the query result of system-managed-components setting as following:
```
kubectl get settings system-managed-components-node-selector -n longhorn-system
NAME                                      VALUE         AGE
system-managed-components-node-selector   name:node04   12m
```

But when I apply my pod, it tells me node02 is not ready. I know the pod will running on the node02, Longhorn only has one node node04.

the content of statefulset yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-headless
  namespace: cassandra
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    targetPort: cql
  - name: intra
    port: 7000
    targetPort: intra
  - name: tls
    port: 7001
    targetPort: tls
  - name: jmx
    port: 7199
    targetPort: jmx
  - name: thrift
    port: 9160
    targetPort: thrift
  selector:
    app: cassandra

-----------------------------------------------

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app: cassandra
spec:
  replicas: 3
  serviceName: cassandra-headless
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: cassandra:3.11.10
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4Gi"
          limits:
            memory: "4Gi"
        ports:
        - containerPort: 7000
          name: intra
        - containerPort: 7001
          name: tls
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra-headless.cassandra.svc.cluster.local,cassandra-1.cassandra-headless.cassandra.svc.cluster.local,cassandra-2.cassandra-headless.cassandra.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "Cassandra"
          - name: TZ
            value: Asia/Shanghai
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nodetool status
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```

the logs of longhorn manager as following:
```
time="2021-07-29T07:53:24Z" level=warning msg="HTTP handling error fail to get node node02: node.longhorn.io \"node02\" not found"
time="2021-07-29T07:53:24Z" level=error msg="Error in request: fail to get node node02: node.longhorn.io \"node02\" not found"
192.168.1.209 - - [29/Jul/2021:07:53:24 +0000] "GET /v1/nodes/node02 HTTP/1.1" 500 216 "" "Go-http-client/1.1"
```

How it happens? What should I do to fix it? Does it mean that I need create pvc manually on node04 to using Longhorn storage?

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: create via Rancher, v1.20.8
 - Node config
   - OS type and version:   CentOS 7.6 1810
   - CPU per node:  8vCPUs
   - Memory per node: 8GiB
   - Disk type  
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by jenting** [comment]
Only the nodes listed in the Node list are able to mount the Longhorn volume.
You could refer to this https://github.com/longhorn/longhorn/issues/2614#issuecomment-846560806

**Comment by HuFei2017** [comment]
Got it, thank you.
I did some try, and I found that, no other nodes will be listed in the Node list when I set `systemManagedComponentsNodeSelector` and `longhornManager.nodeSelector` like I did, all things running on the K8S only Longhorn.
So, how should I do to make all Longhorn components running on the node04, and all the nodes are included in the Node List.

**Comment by HuFei2017** [comment]
What I mean is, I can only allow all csi components and all longhorn deployed components and all longhorn system managed components running on the dedicated node, and I can also see all the nodes listed in the Longhorn Node List.

**Comment by jenting** [comment]
> What I mean is, I can only allow all csi components and all longhorn deployed components and all longhorn system managed components running on the dedicated node, and I can also see all the nodes listed in the Longhorn Node List.

For the workloads which want to use Longhorn volume, the longhorn-manager and replica instance-manager _must_ run on the nodes of the workload Pod's belonged node.
So, in your case, it's impossible.

**Comment by PhanLe1010** [comment]
Btw, you can tell Longhorn to use storage on dedicated nodes though: https://longhorn.io/docs/1.1.2/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes

**Comment by HuFei2017** [comment]
> > What I mean is, I can only allow all csi components and all longhorn deployed components and all longhorn system managed components running on the dedicated node, and I can also see all the nodes listed in the Longhorn Node List.
> 
> For the workloads which want to use Longhorn volume, the longhorn-manager and replica instance-manager _must_ run on the nodes of the workload Pod's belonged node.
> So, in your case, it's impossible.

Thank for your reply, thank you.

I did some try yesterday, and found some interesting thing. If I set `systemManagedComponentsNodeSelector` and `longhornManager.nodeSelector` like Lognhorn doc shows: https://longhorn.io/docs/1.1.2/advanced-resources/deploy/node-selector/ , there will be no longhorn-manager and replica instance-manager running on the other nodes, so I can not attach volume successfully.

For example, if I have 3 windows nodes and 3 linux nodes, and I want install longhorn on linux nodes, so I will set linux nodes with special tag via kubectl. If I set same configurations in the YAML as doc shows, there will be no longhorn-manager and replica instance-manager running on the windows nodes, it will mean I can not run any pods on the windows nodes. Is it a problem for longhorn? Or Is there some error in the document?

the settings：
```
  longhornManager:
    nodeSelector:
      label-key1: "label-value1"
  longhornDriver:
    nodeSelector:
      label-key1: "label-value1"
  longhornUI:
    nodeSelector:
      label-key1: "label-value1"

defaultSettings:
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
```
