### ISSUE TITLE
[BUG] POD readiness and read-only filesystem?

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#2850]
I have an issue which I am facing since I started with kubernetes for more than a year. I am not sure if Longhorn is a reason for my problem but it is in some way related:

I have a simple POD running a postgres container

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels: 
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_PASSWORD
          value: adminadmin
        - name: POSTGRES_USER
          value: admin
        image: postgres:9.6.1
        name: postgres
        livenessProbe:
          exec:
            command: ["psql", "-Uadmin", "-dmydb", "-c", "SELECT 1"]
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 12
        ports:
          - containerPort: 5432        
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
          subPath: postgres
      restartPolicy: Always
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata
```

The data volume is handeld by a durable longhorn persitence volume.
As you can see I also use a livenessProbe to check PostgreSQL. 

Now for some reasons (maybe network problems) suddenly the data volume in longhorn becomes read only. I do not really understand why. 
As a result the LifnessProbe failed and Kubernetes restarts the Container. But the Postres Container stops immediately because of the read-only file system.
I run into a endless CrashLoopBackOff.

If I kill the POD manualy, Kubernetes reschedules the POD and since the great work in version 1.1.2 of longhorn the pod with the Postres container starts within 4 seconds. (Thanks a lot ! In earlier versions I run into the error '...FailedAttachVolume - cannot be attached to the node A since it is already attached to the node B....')

But my question is: how can I define my POD to be rescheduled in case the persistence volume becomes read only for some reason?

Currently in such a situation my customer calls me early in the morning and I restart the pod manually. Which is really an idiotic way of monitoring ;-)
