### ISSUE TITLE
[BUG] Actual size is showing unknown on volume detail page

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2861]
**Describe the bug**
Actual size is showing unknown on volume detail page for volume.

**To Reproduce**
1. In Rancher, while creating a deployment, select create PVC in storage tab.
2. Select Longhorn in storage class and fill out necessary fields.
3. Click create.
4. Go to Longhorn, check the volume created in volume details page.
5. The actual size is appearing as `unknown`

**Expected behavior**
The actual size should show the size properly.

<img width="806" alt="Screen Shot 2021-08-10 at 11 15 19 AM" src="https://user-images.githubusercontent.com/60111667/128914136-90c36125-756f-4c4b-be3b-2e5860a9ff35.png">

Volume :
```
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta1
  kind: Volume
  metadata:
spec:
    Standby: false
    accessMode: rwo
    backingImage: ""
    baseImage: ""
    dataLocality: disabled
    disableFrontend: false
    diskSelector: null
    encrypted: false
    engineImage: longhornio/longhorn-engine:master-head
    fromBackup: ""
    frontend: blockdev
    lastAttachedBy: ""
    migratable: false
    migrationNodeID: ""
    nodeID: node_name
    nodeSelector: null
    numberOfReplicas: 3
    recurringJobs: null
    replicaAutoBalance: ignored
    revisionCounterDisabled: false
    size: "1073741824"
    staleReplicaTimeout: 2880
  status:
    actualSize: 51003392
    conditions:
      restore:
        lastProbeTime: ""
        lastTransitionTime: "2021-08-10T17:46:23Z"
        message: ""
        reason: ""
        status: "False"
        type: restore
      scheduled:
```

**Environment:**
 - Longhorn version: Longhorn-master - `c09ac49` `08/10/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
