### ISSUE TITLE
[QUESTION] Restoring helm-generated pvc's

### ISSUE THREAD

**Issue by xeor** [longhorn/longhorn#2862]
**Question**

I have been testing the backup functionality of longhorn on regular deployments/pvc's and it works as expected.
I can
* Create deployment with a volume using a storageclass, volume is generated and attached.
* Do a backup of that volume
* Reinitialize the whole cluster
* Restore a previous backup
* Create a PV/PVC of the restored volume
* When I recreate the deployment, it will magically get attached to the restored PVC, great!

However, when I am adding helm (and flux) into the mix, the PVC's created contains some annotations and labels;

```yaml
Name:          app-config
Namespace:     app
StorageClass:  longhorn
Status:        Bound
Volume:        pvc-e617bd94-fc84-4b97-9f68-933b230d8386
Labels:        app.kubernetes.io/instance=app
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=app
               app.kubernetes.io/version=2021.6
               helm.sh/chart=app-1.2.3
               helm.toolkit.fluxcd.io/name=app
               helm.toolkit.fluxcd.io/namespace=app
Annotations:   meta.helm.sh/release-name: app
               meta.helm.sh/release-namespace: app
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
...
```

This causes problems when trying to restore with the workflow above. Helm will get this error: `Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim "app-config" in namespace "app" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "app"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "app"`

Is there a way, is it possible, or is it even in the scope of longhorn to backup those annotations?
How would be the best way of attacking this problem? Or is backup of annotations on the roadmap for a later longhorn release?

**Environment:**
 - Longhorn version: v1.1.2
 - Kubernetes version: v1.20.9
 - Node config
   - OS type and version: Flatcar 2905.2.1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
