### ISSUE TITLE
[FEATURE] Support encrypted RWX volumes

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2867]
**Is your feature request related to a problem? Please describe.**
We support PV encryption for RWO volumes via the CSI mechanism.
For RWX volumes we need to add support to the share manager to support encrypted RWX volumes.
This required some changes on the share-manager to use host mounts instead of the inside pod mounts.

**Additional context**
PV encryption is implemented in https://github.com/longhorn/longhorn/issues/1859

**Comment by joshimoo** [comment]
@meldafrawi same testing as for RWO global-crypto and a per PVC test, since then the secret is stored in the PVC namespace and the longhorn share-manager controller will retrieve it and use it. Just need to make sure permissions work correctly for that one.

The per pvc secret, uses a template of the PVC name and will look up a secret for that name. The PVC will remain in pending state till that secret can be retrieved then the create volume call will execute.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Setup:
1. Create a kubernetes cluster with 3 worker nodes, and 1 controller node.
2. Deploy Longhorn (master branch)
3. Create a secret to be used for encryption: Ref: [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)


Test(1): Deploy workload using Encrypted RWX PV with **ext4** filesystem. **(PASSED)**
1. Create a Longhorn volume, and mark check `Encrypted`: true and `Access Mode`: to ReadWriteMany
2. Create a PV/PVC, and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: ext4
3. Deploy a workload using the created PVC.
4. Check read/write operation into the volume.
5. write some data and compute it's checksum

Test(2): Deploy workload using Encrypted RWX PV with **xfs** filesystem. **(PASSED)**
1. Create a Longhorn volume, and mark check `Encrypted`: true and `Access Mode`: to ReadWriteMany
2. Create a PV/PVC, and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: xfs
3. Deploy a workload using the created PVC.
4. Check read/write operation into the volume.
5. write some data and compute it's checksum

Test(3): Provision a volume though creating a PVC from a storage class that support PV encryption  **(PASSED)**

1. Create a storage class that support PV encryption. Ref: [crypto secret](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) 
[storage class](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/storageclass-crypto-global.yaml)

2. Use the following manifest to create a PVC and provision a volume.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-00
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-crypto-global
  volumeMode: Filesystem
```
3. Deploy a workload to consume the PVC
4. make sure you can read/write into the volume.

Test(4): Provision a volume though creating a PVC from a storage class that support PV encryption per volume with  detecated namespace **(PASSED)**

1. Create a storage class that support PV encryption. Ref: [crypto secret](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) 
[storage class](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/storageclass-crypto-global.yaml)

2. Use the following manifest to create a PVC and provision a volume.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-01
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: storageclass-crypto-global
  volumeMode: Filesystem
```
PVC will be in pending state

3. Create a secret with the same PVC name, in `longhorn-system` namespace, the secret use the same data keys as [secret-crypto-global](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)
4. Deploy a workload to consume the PVC
5. Make sure you can read/write into the volume.

Test(5): Provision a volume though creating a PVC from a storage class that support PV encryption per volume with general namespace **(PASSED)**

1. Create a storage class that support PV encryption. Ref: [crypto secret](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) 
[storage class](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/storageclass-crypto-global.yaml)

2. Use the following manifest to create a PVC and provision a volume.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-02
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: storageclass-crypto-per-volume
  volumeMode: Filesystem
```
PVC will be in pending state

3. Create a secret with the same PVC name, and in the same PVC namespace, the secret use the same data keys as [secret-crypto-global](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)
4. Deploy a workload to consume the PVC
5. Make sure you can read/write into the volume.
