### ISSUE TITLE
[FEATURE] Readiness-probe in helm/longhorn-ui

### ISSUE THREAD

**Issue by xeor** [longhorn/longhorn#2884]
**Is your feature request related to a problem? Please describe.**
I am trying building a cluster in a CI/CD pipeline, including deploying longhorn. I want to use the longhorn api in the same pipeline, however, it is unknown when the longhorn api is actually ready.

**Describe the solution you'd like**
Instead of implementing an http-check in the pipeline, this can be fixed as an readiness probe, where these kind of checks should be.

In https://github.com/longhorn/charts/blob/master/charts/longhorn/templates/deployment-ui.yaml, there should be a readiness probe like:

```
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 8000
```

Also see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

The ui/api could then be waited for by kubectl, like: `kubectl wait --for=condition=Ready -n longhorn-system pod -l app=longhorn-ui --timeout 10m`

**Describe alternatives you've considered**
Creating a loop that checks every seconds..

**Additional context**
The readiness-probe is "the" way of doing this. This is exactly what it's ment for :)
