### ISSUE TITLE
[BUG] Unable to mount ext4 volume formatted with parameters "-O casefold"

### ISSUE THREAD

**Issue by lalanikarim** [longhorn/longhorn#2885]
**Describe the bug**
Unable to mount ext4 formatted with `-O casefold` parameter.
Casefold parameter allows ext4 filesystem to support case-insensitive filesystem searches.

Relevant article for *casefold*
https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/

**To Reproduce**
1. Set mkfs-ext4-parameters settings value to "-O casefold"
```
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  name: mkfs-ext4-parameters
  namespace: longhorn-system
value: "-O casefold"
```
2. Create a new pod with PVC
```
apiVersion: v1
kind: Namespace
metadata:
  name: casefold-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casefold-test
  namespace: casefold-test
  labels:
    app: casefold-test
spec:   
  selector:
    matchLabels:
      app: casefold-test
  template:
    metadata:
      namespace: casefold-test
      labels:
        app: casefold-test
    spec:   
      containers:     
      - name: casefold-test
        image: nginx:latest
        volumeMounts:   
        - mountPath: /mnt/casefold
          name: casefold
          readOnly: false
      volumes:   
      - name: casefold
        persistentVolumeClaim:   
          claimName: casefold
          readOnly: false
  replicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casefold
  namespace: casefold-test
spec:
  storageClassName: longhorn
  accessModes:   
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**Expected behavior**
Created volume is correctly mounted on to the pod 

**Log**
```
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f /var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount
Output: mount: /var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f, missing codepage or helper program, or other error.

I0814 21:55:33.674203   11877 mount_linux.go:322] Disk "/dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f]
E0814 21:55:33.682060   11877 mount_linux.go:329] format of disk "/dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f" failed: type:("ext4") target:("/var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount") options:(["defaults"])error:(exit status 1)
time="2021-08-14T21:55:33Z" level=error msg="NodePublishVolume: err: rpc error: code = Internal desc = exit status 1"
time="2021-08-14T21:57:35Z" level=info msg="NodePublishVolume: req: {\"target_path\":\"/var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"baseImage\":\"\",\"csi.storage.k8s.io/ephemeral\":\"false\",\"csi.storage.k8s.io/pod.name\":\"casefold-test-598d574c89-vrhl6\",\"csi.storage.k8s.io/pod.namespace\":\"casefold-test\",\"csi.storage.k8s.io/pod.uid\":\"e5c44b78-e28e-4be0-a69e-21ddca19c215\",\"csi.storage.k8s.io/serviceAccount.name\":\"default\",\"fromBackup\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1628062629675-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f\"}"
time="2021-08-14T21:57:35Z" level=info msg="volume pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f using user provided ext4 fs creation params: -O casefold -E encoding_flags=strict"
time="2021-08-14T21:57:35Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount"
I0814 21:57:35.824247   11877 mount_linux.go:287] `fsck` error fsck from util-linux 2.31.1
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f is mounted.
fsck.ext2: Bad magic number in super-block while trying to open /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f
/dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f: 
The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

E0814 21:57:35.827810   11877 mount_linux.go:140] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f /var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount
Output: mount: /var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f, missing codepage or helper program, or other error.

I0814 21:57:35.870069   11877 mount_linux.go:322] Disk "/dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f]
E0814 21:57:35.880003   11877 mount_linux.go:329] format of disk "/dev/longhorn/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f" failed: type:("ext4") target:("/var/lib/kubelet/pods/e5c44b78-e28e-4be0-a69e-21ddca19c215/volumes/kubernetes.io~csi/pvc-1fb5eaa2-20ce-41e1-9262-a210afcd921f/mount") options:(["defaults"])error:(exit status 1)
time="2021-08-14T21:57:35Z" level=error msg="NodePublishVolume: err: rpc error: code = Internal desc = exit status 1"
```

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.21.3
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 5

**Additional context**
Steps to verify *-O casefold* locally outside of longhorn for reference:
1. Create an arbitrary size file  
`dd if=/dev/zero of=myfs bs=10240 count=10240`  
2. Format with `-O casefold` parameter  
`mkfs -t ext4 -O casefold myfs`  
3. Create a folder to mount  
`mkdir mymount`
4. Mount the filesystem
`sudo mount -t ext4 myfs mymount`

[longhorn-support-bundle_e08c4212-41fb-4ecf-b682-dedea4b78948_2021-08-14T22-10-44Z.zip](https://github.com/longhorn/longhorn/files/6987249/longhorn-support-bundle_e08c4212-41fb-4ecf-b682-dedea4b78948_2021-08-14T22-10-44Z.zip)
