### ISSUE TITLE
[BUG] Cannot create a backing image via a YAML file

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2900]
**Describe the bug**
See the title 

**To Reproduce**
1. Run
```
echo "
apiVersion: longhorn.io/v1beta1
kind: BackingImage
metadata:
  name: bi-test
  namespace: longhorn-system
spec:
  sourceType: download
  sourceParameters:
    url: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
" | kubectl -n longhorn-system apply -f -
```
2. The backing image gets stuck without any disk file

**Expected behavior**
The backing image should contain a ready disk file after downloading

**Environment:**
 - Longhorn version: v1.2.0-preview1
