### ISSUE TITLE
[BUG] Power off node during backup volume restore does not continue restore

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2929]
**Describe the bug**
Power off node during backup volume restore re-attached to another node but does not resume restore. Note: Cannot detach either.
![Screenshot-2021-08-25-14:32:04](https://user-images.githubusercontent.com/22583541/130738392-998679d9-4ec1-440b-8d08-5debb878ddf3.png)

**To Reproduce**
```
1. Create a backup.
2. Create a restore volume from the backup.
3. Power off the volume attached node during the restoring.
4. Wait for the Longhorn node down.
5. Wait for the restore volume being reattached and starting restoring volume with state Degraded.
6. Wait for the restore complete.
```

**Expected behavior**
Volume should continue to restore, complete and change state to `Degraded`.

**Log**
`none`

**Environment:**
 - Longhorn version: master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 
   - Number of worker node in the cluster: 
 - Node config
   - OS type and version: SLES15SP3
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 2

**Additional context**

**Comment by innobead** [comment]
cc @khushboo-rancher it seems a regression.

**Comment by innobead** [comment]
@c3y1huang please help verify. thanks.

**Comment by khushboo-rancher** [comment]
Verified with Master - `08/30/2021`, it's working but don't see the backported PR.

**Comment by shuo-wu** [comment]
> Verified with Master - `08/30/2021`, it's working but don't see the backported PR.

I will prepare the backported PR soon

**Comment by khushboo-rancher** [comment]
I tried with v1.1.3-head `08/30/2021`, it didn't work for me.

**Comment by shuo-wu** [comment]
> I tried with v1.1.3-head `08/30/2021`, it didn't work for me.

To verify this issue In v1.1.3, you need to trigger the restore volume re-updating `LastBackup` after reattachment by clicking the Backup page or setting a short backup target poll interval.

**Comment by kaxing** [comment]
Validation: **PASSED**

Verifying with Longhorn v1.1.3-head(20210831) on EC2 with 1 + 3 nodes
```yaml
        image: longhornio/longhorn-manager:v1.1.3-head
        - longhornio/longhorn-engine:v1.1.3-head
        - longhornio/longhorn-instance-manager:v1_20210621
        - longhornio/longhorn-share-manager:v1_20210416
        - longhornio/backing-image-manager:v1_20210422
        - longhornio/longhorn-manager:v1.1.3-head
        image: longhornio/longhorn-ui:v1.1.3-head
```

0. Update the backup polling interval setting to 30s
1. restore a backup 
2. observe the attached node and reboot that instance immediately
3. the volume will then be attached and begin restoring
Wait for the node come back online
![image](https://user-images.githubusercontent.com/602540/131484777-1f615911-9948-41b1-8363-dfb809643309.png)

The volume will be restored then detached. Create PV/PVC then attaching the volume to the workload scheduling node, the volume data can be access and verified.
