### ISSUE TITLE
[BUG] Deleting the only pod in a single replica ReplicaSet causes an attachment failure of the replacement pods when the volume is RWX.

### ISSUE THREAD

**Issue by rgomez-casa** [longhorn/longhorn#2946]
When you have a RWX volume attached to a pod in a single replica ReplicaSet, if you delete the pod, the replacement pod stays in CreatingContainer mode for some time and Terminates.

This cycle gets repeated a random number of times until one of the pods manages to start properly.
It can take from several seconds to 15 minutes to achieve a correctly connected pod.

If the ReplicaSet has multiple replicas this behavior does not appear. 

**To Reproduce**
Apply a yaml like this:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: longhorn-test
  labels:
    app: longhorn-test
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-test
  template:
    metadata:
      labels:
        app: longhorn-test
    spec:
      containers:
        - name: alpine
          image: docker.io/alpine:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: longhorn-test-volume
              mountPath: "/mnt"
      volumes:
        - name: longhorn-test-volume
          persistentVolumeClaim:
            claimName: longhorn-test-pvc
```

Verify the pod comes up.

```
$ kubectl get pods
NAME                  READY   STATUS    RESTARTS   AGE
longhorn-test-llncs   1/1     Running   0          18m
```

Delete the pod.
```
$ kubectl delete pod longhorn-test-llncs
pod "longhorn-test-llncs" deleted
```

Check the new pod and verify it fails to come up multiple times.
```
$ kubectl get pods
NAME                  READY   STATUS              RESTARTS   AGE
longhorn-test-6vl9s   0/1     Terminating         0          35s
longhorn-test-hxc24   0/1     ContainerCreating   0          3s
longhorn-test-llncs   0/1     Terminating         0          19m

$ kubectl get pods
NAME                  READY   STATUS              RESTARTS   AGE
longhorn-test-hxc24   0/1     ContainerCreating   0          20s

$ kubectl get pods
NAME                  READY   STATUS              RESTARTS   AGE
longhorn-test-hxc24   0/1     Terminating         0          31s
longhorn-test-x8wrp   0/1     ContainerCreating   0          1s
```

Eventually the pod comes up:

```
$ kubectl get pod
NAME                  READY   STATUS    RESTARTS   AGE
longhorn-test-x8wrp   1/1     Running   0          63s
```

**Expected behavior**

We expect the pod to come up and attach the volume on the first attempt.

**Logs**
This is an example of the events as seen from the volume side:

```
Events:
  Type    Reason    Age                    From                               Message
  ----    ------    ----                   ----                               -------
  Normal  Start     37m                    longhorn-kubernetes-pv-controller  Persistent Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 started to use/reuse Longhorn volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03
  Normal  Remount   30m (x2 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:49Z
  Normal  Remount   30m                    longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:50Z
  Normal  Detached  30m (x2 over 37m)      longhorn-volume-controller         volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 has been detached
  Normal  Remount   30m (x4 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:51Z
  Normal  Remount   30m                    longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:52Z
  Normal  Remount   30m (x4 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:53Z
  Normal  Remount   30m (x2 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:54Z
  Normal  Attached  30m (x2 over 37m)      longhorn-volume-controller         volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 has been attached to worker-2.ocp.baremetal.casa.dev
  Normal  Remount   30m (x2 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:13:56Z
  Normal  Remount   30m                    longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:14:03Z
  Normal  Remount   30m (x4 over 30m)      longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:14:04Z
  Normal  Remount   22m (x127 over 30m)    longhorn-volume-controller         (combined from similar events): Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:21:24Z
  Normal  Remount   3m22s (x2 over 3m22s)  longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:40:57Z
  Normal  Remount   3m21s                  longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:40:58Z
  Normal  Remount   2m50s                  longhorn-volume-controller         Volume pvc-8cd3eff2-2a78-413d-aec7-84f27b274d03 requested remount at 2021-08-27T22:41:29Z
```

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Openshift 4.6,4.7,4.8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: We've seen it with 3 dedicated workers, 2 dedicated workers and with 3 masters/workers.
 - Node config
   - OS type and version: Red Hat Enterprise Linux CoreOS 47.83.202102090044-0
   - CPU per node: 8
   - Memory per node: 32
   - Disk type(e.g. SSD/NVMe): HDD/SSD both dedicated and Shared with the OS.
   - Network bandwidth between the nodes: 1GB and 10GB,
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM and Baremetal.
 - Number of Longhorn volumes in the cluster: From 1 to few tens.
