### ISSUE TITLE
[BUG] Loghorn volumes can be resized to any size and does not respect the over-provisioning limit

### ISSUE THREAD

**Issue by Rancheroo** [longhorn/longhorn#2962]
**Describe the bug**
Loghorn volumes can be resized to any size and does not respect the over-provisioning limit

**To Reproduce**
1. Create volume in Loghorn
2. Resize volume to a number that well in excess and should not be allowed. It will be allowed and scheduled for use.

**Expected behavior**
Longhorn should stop resizes that don't respect the over provisioning percentage and not schedule them for use.

**Log**

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): any
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): all
 - Number of Longhorn volumes in the cluster:

**Additional context**
Simple to replicate and easy to see.

**Comment by khushboo-rancher** [comment]
Similar to https://github.com/longhorn/longhorn/issues/2689

**Comment by PhanLe1010** [comment]
Test env:
- Longhorn master, 3 worker nodes
- default `longhorn` storageclass has 3 replicas

Test steps:

### Case 1: Using UI; each replica on a different disk
1. Create a volume of 1GB.
2. Try to expand the volume to over the maximum schedulable amount  (the quantity in the red box in the below picture)
3. Verify that Longhorn blocks the expanding action

### Case 2: Using UI; 2 replicas on a same disk
1. Create a volume of 1GB with 3 replicas
1. Enable `Replica Node Level Soft Anti-Affinity` setting
1. Increase number of replica count to 4, there will be some replicas on the same node
1. Try to expand the volume to over 50% of the maximum schedulable amount  (the quantity in the red box in the below picture)
1. Verify that Longhorn blocks the expanding action because the 2 replicas on the same disk cannot be expanded.

### Case 3: Using CSI
1. Create a PVC with `longhorn` storageclass and storage request of 1GB
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-simple-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    ```
1. Attach the PVC into a workload pod. Exec into the workload pod. 
1. Check the size of the filesystem by `df -h <THE-MOUNT-POINT>`. Make sure it about 1GB
1. Scale down the workload to detach the volume
1. Try to expand the PVC to over 100% of the maximum schedulable amount  (the quantity in the red box in the below picture)
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-simple-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 109Gi
    ```
1. Verify that the PVC cannot finish resizing
1. Scale up the workload. Exec into the workload pod. Check the size of the filesystem by `df -h <THE-MOUNT-POINT>`. Make sure it about 1GB
1. Scale down the workload to detach the volume
1. Note that there is no way to reduce the PVC storage request because this is Kubernetes implementation. So the PVC is stuck in this state.
1. Increase the `Storage Over Provisioning Percentage`
1. Wait for the PVC expansion to finish (could take up to 5 minutes because Kubernetes has maximum 5 minutes backoff limit when operation fails continuously)
1. Scale up the workload
2. Exec into the workload pod. Check the size of the filesystem by `df -h <THE-MOUNT-POINT>`. Make sure it about 109GB

<img width="899" alt="Screen Shot 2021-09-14 at 6 21 25 PM" src="https://user-images.githubusercontent.com/22139961/133354958-af8e4cfc-16ae-4f7c-9c9b-6a5f34a239ea.png">
