### ISSUE TITLE
[BUG] Duplicated default instance manager leads to engine/replica cannot be started

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#3000]
**Describe the bug**
All existing rwx are not attaching anymore after upgrading to 1.2.

**To Reproduce**
Existing volumes are not attaching to redeployed pods. Not even after setting the workload to zero. Restarted longhorn components and longhorn nodes.

**Expected behavior**
Volumes should attach.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.
sent longhorn bundle

AttachVolume.Attach failed for volume "pvc-93aad038-6dda-482f-a8f6-d237a0414561" : rpc error: code = DeadlineExceeded desc = volume pvc-93aad038-6dda-482f-a8f6-d237a0414561 failed to attach to node pax-p-95

**Environment:**
 - Longhorn version: 1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rancher kubernets v1.20.10
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS
   - CPU per node: 12
   - Memory per node: 32G
   - Disk type(e.g. SSD/NVMe): 
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Xen
 - Number of Longhorn volumes in the cluster: 80

**Additional context**

**Comment by yasker** [comment]
Are those using xfs as filesystem? cc @joshimoo

**Comment by timmy59100** [comment]
We did not specify the filesystem type in the storageclass, so according to https://github.com/longhorn/longhorn/issues/2991 it should be ext4

**Comment by joshimoo** [comment]
@timmy59100 thanks for creating this issue, can you sent us a support bundle to `longhorn-support-bundle@Suse.com` referencing this issue.

Can you also describe the behavior on the cluster, is the share-manager pod in the `longhorn-system` namespace getting continuously recreated?

**Comment by PhanLe1010** [comment]
The support bundled was sent over email

**Comment by timmy59100** [comment]
@joshimoo No, the share-managers stays up with the following log constantly:

`time="2021-09-13T20:52:15Z" level=warning msg="waiting with nfs server start, volume is not attached" encrypted=false volume=pvc-93aad038-6dda-482f-a8f6-d237a0414561
`

**Comment by joshimoo** [comment]
Okay just checked the support bundle, this is unrelated to RWX and is similar to this issue:
https://github.com/longhorn/longhorn/issues/2992

**Comment by PhanLe1010** [comment]
@timmy59100 Can you try to delete this instance manager `kubectl delete instancemanager instance-manager-e-8e53eeae -n longhorn-system` ?

**Comment by timmy59100** [comment]
@PhanLe1010 The one volume got attached after deleting the instancemanager. When I try to start the other workloads they are stuck attaching still.

**Comment by timmy59100** [comment]
After waiting a bit every volume got attached.

**Comment by PhanLe1010** [comment]
Can we have a new support bundle?

**Comment by timmy59100** [comment]
sent over email.

**Comment by PhanLe1010** [comment]
Which volume is stuck in attaching?

**Comment by timmy59100** [comment]
> After waiting a bit every volume got attached.

How did you now which instancemanager to kill?

**Comment by PhanLe1010** [comment]
Sorry, I missed the earlier message. 

Apparently, it is because there are multiple instance managers with the same spec (nodeID and image) in the cluster so Longhorn manager is confused and don't know which instance manager to pick to start engine/replica: https://github.com/longhorn/longhorn-manager/blob/5da6ccfbba0c4ae441c6b5101ace541c42271f81/datastore/longhorn.go#L2435

I just tell you to delete one of the extra instance manager among the ones that have the same spec. 

I am looking into how it is possible to have multiple instance managers with the same spec but I don't know why yet. From code perspective, there shouldn't have multiple instance managers with the same spec: https://github.com/longhorn/longhorn-manager/blob/5da6ccfbba0c4ae441c6b5101ace541c42271f81/controller/node_controller.go#L851-L896

**Comment by PhanLe1010** [comment]
@timmy59100  Is there any abnormal event that you observed when you upgrading Longhorn? For example, node reboot, ETCD health problem, etc ...

**Comment by timmy59100** [comment]
@PhanLe1010 It wasn't just after the upgrade. I deleted all instance managers to try to resolve this when the cluster was in a healthy state. But apparently the multiple instance managers with the same spec happened again.

**Comment by PhanLe1010** [comment]
@timmy59100 Do you mean that if you delete all instance manager now, the problem of multiple instance managers with the same spec will happen?

**Comment by PhanLe1010** [comment]
I am trying to reproduce the issue so we can find root cause and fix in the next release

**Comment by timmy59100** [comment]
I don't know for sure if it happens, but deleting all instance managers would crash all workloads?

**Comment by PhanLe1010** [comment]
The workload will crash. Please don't do it in production cluster. 

I am just asking if you meant the reproduce step is deleting all instance managers.

**Comment by timmy59100** [comment]
There issue was initially there with a few volumes. I tried to delete all instance managers and the issue was still there.

**Comment by PhanLe1010** [comment]
@timmy59100 Have you looked into the health of ETCD? Did you have monitoring system setup?

**Comment by timmy59100** [comment]
We have rancher monitoring running. There are some leader elections every few days from etcd, what to look for otherwise?

**Comment by PhanLe1010** [comment]
@timmy59100 I think we can see the ETCD health in Rancher monitoring
<img width="986" alt="Screen Shot 2021-09-21 at 10 25 35 AM" src="https://user-images.githubusercontent.com/22139961/134218441-3c25afc0-4c15-4460-8c0f-78c5ab4ee179.png">
 Can you check it?

**Comment by PhanLe1010** [comment]
Thanks @timmy59100 
There is other graph similar to this https://user-images.githubusercontent.com/22139961/134218671-93a6feb6-fa8d-457d-9775-ac07179b897b.png

**Comment by timmy59100** [comment]
@PhanLe1010 like the second and third graph I provided?

**Comment by hendra-2020** [comment]
This has been happening to me on several occasions even for RWO volumes on longhorn v1.2.2, rke2 1.21.2, ubuntu 20.04.3. They happened to me after node reboot.

**Comment by PhanLe1010** [comment]
Ok. Even though we cannot reproduce the issue in the lab, I think we should still prevent it from happening by cleaning up the extra default instance manager CRs.

**Comment by PhanLe1010** [comment]
From the code flow, it looks to me that multiple default instance managers creation can only happen if [this function ](https://github.com/longhorn/longhorn-manager/blob/b13004c7956d8552086ca7ad09af5579e2730ced/controller/node_controller.go#L929)is run concurrently by different goroutines/processes. The workqueue mechanism in client-go guarantees that there is no 2 go-routines processing the same item simultaneously. This leads me to the theory that maybe there were multiple longhorn manager pods running on the same node at the time. Not 100% sure.

Always, the proposed fix is to hash the node name + image name to create a name for the default instance manager. This makes it impossible to create multiple default instance managers on the same node because they would have the same name and ETCD would reject the later request.

**Comment by PhanLe1010** [comment]
Test steps:
Focus on upgrading test

1. Install Longhorn older versions (1.2x, 1.3.x)
1. Create some volumes. Attach some. Create some recurring jobs
1. Upgrade to master-head version
1. Verify that there is not multiple default instance manager pods on the same node. (I.e., pod with same default instance manager image and instance manager type on same node)
1. Verify detach/attach volume works fine

**Comment by roger-ryao** [comment]
**Verified on master-head 20221212**

- longhorn master-head ([f30875a](https://github.com/longhorn/longhorn/commit/f30875aa58f0e64783cbe7bbd623b3c1e5ba030a)) 
- longhorn-manager master-head ([81f77c6](https://github.com/longhorn/longhorn-manager/commit/81f77c682482e2a721a712ca7ee343b1319f384b)) 


**The test steps**

[Ref #3000 (To Reproduce)](https://github.com/longhorn/longhorn/issues/3000#issuecomment-1344956024)
1. Create 4 volumes.( 2 rwo and 2 rwx )
2. Create deployment

`kubectl apply -f deployment.yaml`
<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>

3. Create statefulset

`kubectl apply -f statefulset.yaml`
<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

4. Create snapshot recurring jobs
5. Upgrade to master-head version


**Result Passed**
1. The detach/attach volume works fine
2. There is not multiple default instance manager pods on the same node
