### ISSUE TITLE
[QUESTION] Is there a way to use Hashicorp Vault that stores the CRYPTO_KEY_VALUE when using encryption

### ISSUE THREAD

**Issue by younesehb** [longhorn/longhorn#3026]
**Question**
Is there a way to use Hashicorp Vault that stores the CRYPTO_KEY_VALUE when using encryption ? 

**Environment:**
 - Longhorn version: v1.2.0
 - Kubernetes version: v1.21.3
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS, kernel version 5.4.0-72-generic
   - CPU per node: 4 CPU
   - Memory per node: 8 GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Exoscale cloud

**Additional context**
When creating the Kubernetes secret that will be used by Longhorn to encrypt persistent volumes, the secret is in clear text.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
# This needs to be encrypted using the Vault later
  CRYPTO_KEY_VALUE: "C_Fm8#$3@x"
  CRYPTO_KEY_PROVIDER: "secret" # this is optional we currently only support direct keys via secrets 
```
I would like to use Hashicorp Vault to avoid having a cleartext value here.
