### ISSUE TITLE
[QUESTION] What is Longhorn nodeSelector?

### ISSUE THREAD

**Issue by mchudinov** [longhorn/longhorn#3038]
What is `nodeSelector` for a Longhorn storage class?

Is it string or a Key-Value pair?

Is it lable for Kubernetes node or is it an annotation for a Kubernetes node?

It looks like it is a string in the example in Longhorn documentation. But in Kubernetes a `nodeSelector` is a key-value pair!

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" 
  nodeSelector: "storage,fast"
```
I marked some nodes in my K8S cluster with label `longhorn=storage-node`. 
How to use only these nodes for Longhorn volumes?
