### ISSUE TITLE
[TASK] Add integration test for upgrading version before v1.2.0 with customized StorageClass

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3046]
**What's the task? Please describe.**
Since v1.2.0, upgrading from older Longhorn version will be automatically converted to the new RecurringJob CRDs.
If recurring jobs were deployed using customized storage jobs, especially with customized StorageClass name, it will not be upgrade or handle by Longhorn deploy process, it will be good to have an automation test to covert this for backward combability when the upgrading path is distant.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Check the customized StoragClass with v1.1.2 or before, then upgrade to v1.2.0 or later
- [ ] Create test case that covers customized StorageClass with the result from above task

**Additional context**
Different StorageClass parameters between versions, as the feature behavior is different,

[For v1.2.0:](https://longhorn.io/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots/#recurring-jobs-assignment-using-a-storageclass)
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobSelector: '[
    {
      "name":"snap",
      "isGroup":true,
    },
    {
      "name":"backup",
      "isGroup":false,
    }
  ]'
```
[For v1.1.2 or before:](https://longhorn.io/docs/1.1.2/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass)
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[
    {
      "name":"snap",
      "task":"snapshot",
      "cron":"*/1 * * * *",
      "retain":1
    },
    {
      "name":"backup",
      "task":"backup",
      "cron":"*/2 * * * *",
      "retain":1
    }
  ]'
```
