### ISSUE TITLE
[BUG] Multiple pods fails to mount if migratable is enabled in storage class

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3053]
**Describe the bug**
Mount failure is observed if migratable is enabled in storage class.

**To Reproduce**
1. Install Longhorn.
2. Create a customized storage class with migratable:true
```
kind: StorageClass
metadata:
  name: longhorn-2
parameters:
  fromBackup: ""
  migratable: "true"
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Create a statefulSet with 2 replicas with rwx volume using above storage class.
4. The second pod mount fails with error
```
MountVolume.MountDevice failed for volume "pvc-90da6bb7-fc7c-4a4f-8cf1-6f998d376dfb" : rpc error: code = InvalidArgument desc = volume pvc-90da6bb7-fc7c-4a4f-8cf1-6f998d376dfb invalid controller count 2
```

**Expected behavior**
Multiple pods should be able to attach and mount to the rwx volume.

**Log**
[longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T18-48-07Z.zip](https://github.com/longhorn/longhorn/files/7213174/longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T18-48-07Z.zip)
Volume name - pvc-36d4c929-0f00-4e84-ba14-91b11b32fb5e
StatefulSet name - wk-4

**Environment:**
 - Longhorn version: v1.2.1-rc1
