### ISSUE TITLE
[QUESTION] How can I install longhorn storage on dedicated node drives e.g. /dev/sdb

### ISSUE THREAD

**Issue by Atharex** [longhorn/longhorn#3060]
**Question**
Like the title says, I did not yet find in the documentation a example, where I can install longhorn on a list of devices available on my nodes (e.g. /dev/sdb) that are formatted, have no file-system and are not mounted

Preferably I would like to install longhorn with a setting like this:
```
nodes:
- name: node1
  devices: 
    - /dev/sdb 
- name: node2
  devices: 
    - /dev/sdb
- name: node3
  devices:
    - /dev/sdb
    - /dev/sdc
- node4
  devices:
    - /dev/sdb
    - /dev/sdc
    - /dev/sde
```

Or in a simpler version if all nodes have the same disk device.
```
devices: /dev/sdb
nodes:
- node1
- node2
...
```

Is something like this already possible?
