### ISSUE TITLE
[QUESTION] predicate matchnodeselector failed for instance-manager pods

### ISSUE THREAD

**Issue by mchudinov** [longhorn/longhorn#3073]
My cluster has 3 dedicated worker storage-nodes with a big disk attached at `/var/lib/data/` and 3 "simple" worker nodes.
These dedicated storage nodes have labels and annotations like this:
```
Labels:                               
  longhorn=storage
  node.longhorn.io/create-default-disk=config                    
Annotations:
  node.longhorn.io/default-disks-config:
  [{"path":"/var/lib/data/","allowScheduling":true,"tags":["storage"]},{"path":"/var/lib/longhorn/","allowScheduling":false}]   
  node.longhorn.io/default-node-tags: ["storage"]
```
longhorn `values.yaml`
```yaml
defaultSettings:
  createDefaultDiskLabeledNodes: true
  systemManagedComponentsNodeSelector: "longhorn:storage"
  defaultDataPath: "/var/vcap/data/"
```
Longhorn is installed using Helm chart:
`helm install longhorn longhorn/longhorn --namespace longhorn-system --values longhorn/values.yaml `

Problems:
1. Longhorn  instance-manager pods scheduled at "simple" worker nodes fail with `predicate matchnodeselector failed` error.
2. A simple pod with a longhorn storage volume fails with error: `CSINode 10.39.148.85 does not contain driver driver.longhorn.io` This node `10.39.148.85` is a simple node, not a storage node.

I want pods that use Longhorn volumes to be created on any worker nodes, while Longhorn storage must be resided on the dedicated "storage" nodes.
Any help is appreciated.
