### ISSUE TITLE
[BUG] longhorn-frontend ingress hsts issue (ssl force redirection issue)

### ISSUE THREAD

**Issue by AlaaAttya** [longhorn/longhorn#3098]
**Describe the bug**
I have configured an ingress route using the configs in the helm values below but when i try to access it from the browser it keeps redirecting me to the SSL url. Note: hsts is disabled from my the whole nginx setup and it works fine with any other route in the same cluster

a dump of the used values

```
image:
  longhorn:
    engine:
      repository: longhornio/longhorn-engine
      tag: v1.1.2-arm64
    manager:
      repository: longhornio/longhorn-manager
      tag: v1.1.2-arm64
    ui:
      repository: longhornio/longhorn-ui
      tag: v1.1.2-arm64
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: v1_20210917-arm64 
    shareManager:
      repository: longhornio/longhorn-share-manager
      tag: v1.1.2-arm64
    backingImageManager:
      repository: longhornio/backing-image-manager
      tag: v1.1.2-arm64
  csi:
    attacher:
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: v3.2.1
    provisioner:
      repository: longhornio/csi-provisioner
      tag: v1.6.0-lh2-arm64
    nodeDriverRegistrar:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v2.3.0
    resizer:
      repository: longhornio/csi-resizer
      tag: v0.5.1-lh1
    snapshotter:
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: v3.0.3    

ingress:
  enabled: true
  host: longhorn.trackxy-staging.alaa.dev
  tls: false
  # path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: false
    nginx.ingress.kubernetes.io/force-ssl-redirect: false


```

Ps: i'm running it on a cluster of raspberry pis model 4 with arm64 OS

**To Reproduce**
1. use the same values to deploy the helm chart
2. try to open the ui from the browser
3. you'll see error like the screen shot below 

![Screenshot 2021-10-02 at 18 19 04](https://user-images.githubusercontent.com/2943218/135724555-f713b1f3-bab4-4645-b9da-a3fb6e2176f4.png)

**Expected behavior**
to have the UI working fine

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.
