### ISSUE TITLE
[FEATURE] Image Naming & Versioning

### ISSUE THREAD

**Issue by dp-42** [longhorn/longhorn#3103]
**Is your feature request related to a problem? Please describe.**
Some users may need/want to use their own CR registry for pulling Longhorn images.

However, currently a Longhorn installation consists of about 11 images that all have a different versioning schema. Therefore, when you want to do some adaptions/updates, you need to take care of every image individually. 

Also, dependency management tools like [renovate](https://github.com/renovatebot/renovate) will struggle with the different versioning.

Here is an example of images used in an Longhorn 1.1.2 installation:

```yaml
engine:
  repository: longhornio/longhorn-engine
  tag: v1.1.2
manager:
  repository: longhornio/longhorn-manager
  tag: v1.1.2
ui:
  repository: longhornio/longhorn-ui
  tag: v1.1.2
instanceManager:
  repository: longhornio/longhorn-instance-manager
  tag: v1_20210621
shareManager:
  repository: longhornio/longhorn-share-manager
  tag: v1_20210416
backingImageManager:
  repository: longhornio/backing-image-manager
  tag: v1_20210422
attacher:
  repository: longhornio/csi-attacher
  tag: v2.2.1-lh2
provisioner:
  repository: longhornio/csi-provisioner
  tag: v1.6.0-lh2
nodeDriverRegistrar:
  repository: longhornio/csi-node-driver-registrar
  tag: v1.2.0-lh1
resizer:
  repository: longhornio/csi-resizer
  tag: v0.5.1-lh2
snapshotter:
  repository: longhornio/csi-snapshotter
  tag: v2.1.1-lh2
```

There are 3 different version naming schema and also the actual version is different for most components. 
This makes automation pretty hard and you need to be very carefully in order to keep track of all the versions per component.

Therefore I kindly request for a more streamlined image tagging concept.

**Describe the solution you'd like**
I would like to have images tagged in the same way. For example, each component that I need to run Longhorn `1.2.0` will have a `1.2.0` tag, so that the image versions are in sync with the Longhorn version. This will allow me to automate the update process and will make clear what version of image to use for what version of Longhorn.

**Describe alternatives you've considered**
Another quite interesting concept that I saw at some other CSI provider: The build a single image that contains all the tools they need. So all their components use the same image, but they call the image with different arguments/parameters.
