### ISSUE TITLE
[BUG] Newly created backup stays in `InProgress` when the volume deleted before backup finished

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3122]
**Describe the bug**
When deleting the volume before the backup finish itself the backup crd will stuck in 

**To Reproduce**
1. Create a backup
2. Delete the volume right away

**Expected behavior**
The unfinished backup item should display a different state after certain time or automatically clean up itself after showing a warning message. (TBD)

**Log**
Unfinished backup item circling in red:
![image](https://user-images.githubusercontent.com/602540/136373082-587dfce1-dbb3-46e0-94c1-2ef16391c8f9.png)
You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.2.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke1 v1.20.11

**Additional context**
<Details>
<Summary>
$ kubectl describe backup backup-2fc09f46d95a4738 -n longhorn-system
</Summary>

```yaml
Name:         backup-2fc09f46d95a4738
Namespace:    longhorn-system
Labels:       backup-volume=restore-interrupt
Annotations:  <none>
API Version:  longhorn.io/v1beta1
Kind:         Backup
Metadata:
  Creation Timestamp:  2021-10-07T09:38:14Z
  Finalizers:
    longhorn.io
  Generation:  1
  Managed Fields:
    API Version:  longhorn.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"longhorn.io":
        f:labels:
          .:
          f:backup-volume:
      f:spec:
      f:status:
    Manager:         longhorn-manager
    Operation:       Update
    Time:            2021-10-07T09:38:14Z
  Resource Version:  785649
  UID:               7e329b7e-b669-427f-a6d4-08d2762945d4
Spec:
  Labels:
    md5:              027e3c7a4b45a81287c38a972ac677dc
    Ver:              2
  Snapshot Name:      63be508a-8dc8-49b5-8a38-873169432380
  Sync Requested At:  0001-01-01T00:00:00Z
Status:
  Backup Created At:
  Labels:                     <nil>
  Last Synced At:             0001-01-01T00:00:00Z
  Messages:                   <nil>
  Owner ID:                   worker3
  Size:
  Snapshot Created At:
  Snapshot Name:
  State:                      InProgress
  URL:
  Volume Backing Image Name:
  Volume Created:
  Volume Name:
  Volume Size:
Events:                       <none>
```

</Details>
