### ISSUE TITLE
[QUESTION] How can I test my http proxy settings are valid?

### ISSUE THREAD

**Issue by chickeaterbanana** [longhorn/longhorn#3136]
**Question**
How can I test my http proxy settings are valid?

**Environment:**
 - Longhorn version: 1.2.2
 - Kubernetes version:
   - Server Version: version.Info
     - Major:"1"
     - Minor:"21"
     - GitVersion:"v1.21.5+rke2r2"
     - GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691"
     - GitTreeState:"clean"
     - BuildDate:"2021-10-04T22:39:02Z"
     - GoVersion:"go1.16.7b7"
     - Compiler:"gc"
     - Platform:"linux/amd64"
 - Node config
   - OS type and version
     - Ubuntu 20.04.
     - `Linux worker03 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
   - CPU per node: 12
   - Memory per node: 64GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes:
   - ca 0.38 ms
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
Longhorn UI Event:
```
Snapshot b6ed9101-4d32-47cc-bdf6-ce65bee66dd7 backup backup-01456eecf24f4b4b label map[KubernetesStatus:{"pvName":"pvc-b066709d-7901-419d-b8b5-275cdad63288","pvStatus":"Bound","namespace":"default","pvcName":"grocy-config-volumeclaim","lastPVCRefAt":"","workloadsStatus":[{"podName":"grocy-deployment-7598c44d69-7hbll","podStatus":"Running","workloadName":"grocy-deployment-7598c44d69","workloadType":"ReplicaSet"}],"lastPodRefAt":""}]: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [--url 10.42.1.27:10000 backup create --dest s3://****@eu-central-003/ --backup-name backup-01456eecf24f4b4b --label KubernetesStatus={"pvName":"pvc-b066709d-7901-419d-b8b5-275cdad63288","pvStatus":"Bound","namespace":"default","pvcName":"grocy-config-volumeclaim","lastPVCRefAt":"","workloadsStatus":[{"podName":"grocy-deployment-7598c44d69-7hbll","podStatus":"Running","workloadName":"grocy-deployment-7598c44d69","workloadType":"ReplicaSet"}],"lastPodRefAt":""} b6ed9101-4d32-47cc-bdf6-ce65bee66dd7], output , stderr, time="2021-10-09T16:28:14Z" level=info msg="Backing up b6ed9101-4d32-47cc-bdf6-ce65bee66dd7 on tcp://10.42.2.184:10000, to s3://****@eu-central-003/" time="2021-10-09T16:28:15Z" level=fatal msg="Error running create backup command: failed to create backup to s3://****@eu-central-003/ for volume pvc-b066709d-7901-419d-b8b5-275cdad63288: rpc error: code = Unknown desc = failed to list objects with param: {\n Bucket: \"****\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} error: AWS Error: RequestError send request failed Get \"https://s3.eu-central-003.backblazeb2.com/****?delimiter=%!F(MISSING)&prefix=%!F(MISSING)\": dial tcp 45.11.37.254:443: connect: network is unreachable\n" , error exit status 1
```

Squid Access Log:
```
1633797759.964    167 10.0.0.4 TCP_TUNNEL/200 6099 CONNECT s3.eu-central-003.backblazeb2.com:443 - HIER_DIRECT/45.11.37.254 -
1633797759.972    175 10.0.0.4 TCP_TUNNEL/200 6099 CONNECT s3.eu-central-003.backblazeb2.com:443 - HIER_DIRECT/45.11.37.254 -
```

I can list backups via the longhorn ui and can see valid requests through squid. But the longhorn-backup-controller fails to generate backups with network is unreachable.

**Comment by shuo-wu** [comment]
If you can access Longhorn via UI and the CSI part works fine, the proxy setup should be fine except for the backup part.
You can refer to this doc and see how to set up proxy for Longhorn backup: https://longhorn.io/docs/1.2.2/snapshots-and-backups/backup-and-restore/set-backup-target/

**Comment by chickeaterbanana** [comment]
My secret has already the corresponding proxy settings:
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backuptarget-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "*****"
  AWS_SECRET_ACCESS_KEY: "*****"
  AWS_ENDPOINTS: "https://s3.eu-central-003.backblazeb2.com"
  HTTP_PROXY: "http://10.0.0.4:3128"
  HTTPS_PROXY: "http://10.0.0.4:3128"
  NO_PROXY: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cluster.local"
  ```

I'm not sure how to debug the backup-container if he uses the proxy.

I already tried the proxy settings without `http://` but this doesn't work either. Can I add some commandline options to get more debug informations?

**Comment by jenting** [comment]
Not sure if you missed adding `192.168.0.0/16` (internal IPs in the cluster) to the `NO_PROXY` variable.

**Comment by chickeaterbanana** [comment]
I have recreated all pods of longhorn and the secret. To be sure the secret is correctly filled I have created a job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-proxy-test
  namespace: longhorn-system
spec:
  template:
    spec:
      volumes:
        - hostPath:
            path: /var/lib/longhorn/
            type: ""
          name: longhorn
      containers:
        - name: test
          image: longhornio/longhorn-manager:v1.2.2
          securityContext:
            runAsUser: 0
          command:
            - /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn
            - backup
            - ls
            - s3://****@eu-central-003/
          volumeMounts:
            - mountPath: /var/lib/longhorn
              name: longhorn
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ENDPOINTS
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: AWS_ENDPOINTS
            - name: HTTPS_PROXY
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: HTTPS_PROXY
            - name: HTTP_PROXY
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: HTTP_PROXY
            - name: NO_PROXY
              valueFrom:
                secretKeyRef:
                  name: longhorn-backuptarget-secret
                  key: NO_PROXY
      restartPolicy: Never
  backoffLimit: 4
  ```
It looks like everything is correctly configured:
```
kubectl -n longhorn-system logs longhorn-proxy-test-f7q9r | head -n 4
{
        "pvc-a810c917-4706-46d7-9e4e-fa5580449098": {
                "Name": "",
                "Size": "0",
```

With this test I should have proved the secret has the correct values, these values can be mounted and the `longhorn backup ls` command can work. But the `longhorn backup create` doesn't work. The error is still the same. To be sure no network policy restrict the traffic, I've created a allow all network policy for all longhorn pods. This change hasn't any effect. I'm not sure how to debug the process further.

I've read a little bit in the source and saw the manager runs a rpc and the backup is running in a separate process/pod. If I look at the logs in combination with the source it seems as the rpc are running as expected and the error messages are transferred from the backuping process to the manager.
