### ISSUE TITLE
[QUESTION] Longhorn s3 backup issues: invalid argument

### ISSUE THREAD

**Issue by rlex** [longhorn/longhorn#3137]
**Question**

Not sure if bug or question, so let's start with question first.

Created s3 bucket, created IAM identity with permissions. IAM keys works, verified with different s3 client software - can list directories and create files.

Created secret named "longhorn-backup-secret":
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: iam_key
  AWS_SECRET_ACCESS_KEY: iam_access_key
```

However, any attempts to use any backup-related functions end up with 

```
error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [backup ls --volume-only s3://my_backup_bucket@eu-central-1/longhorn-cntb], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn: invalid argument
```

**Environment:**
 - Longhorn version: 1.2.2
 - Kubernetes version: 1.22 k3s
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type: nvme
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): kvm

**Additional context**
