### ISSUE TITLE
[FEATURE] CRD for snapshots

### ISSUE THREAD

**Issue by HubbeKing** [longhorn/longhorn#3144]
**Is your feature request related to a problem? Please describe.**
Snapshot RecurringJobs set to Retain X number of snapshots do not touch unrelated snapshots, so if one ever changes the name of the RecurringJob, the old snapshots will stick around forever. These then have to be manually deleted in the UI.
Having a CRD for snapshots would greatly simplify this, as one could prune snapshots using kubectl - much like how one can currently manage backups using kubectl due to the existance of the backups.longhorn.io CRD.

**Describe the solution you'd like**
A CRD for Snapshots. Something like snapshots.longhorn.io, and code in longhorn-manager to ensure that there exists a CRD object for each snapshot for each volume, and that they are in sync.

**Describe alternatives you've considered**
I suppose a browser automation framework might also work for pruning large numbers of snapshots, but this feels janky as all hell.

**Additional context**
Screenshot of v1.2.2 UI showing leftover snapshots from a deleted recurringjob, and a single snapshot from a new RecurringJob with retain set to 4:
https://i.imgur.com/SnlP23P.png

**Comment by jenting** [comment]
I remember we discussed internally that Longhorn needs the snapshot CR. cc @joshimoo @shuo-wu

**Comment by PhanLe1010** [comment]
## Test Plan:
### Innit
1. Create volume: `vol1`, `vol2`
1. Attach and write some data to it

### Create 
1. Create new snapshot CR, volume attached 
    1. Deloy the yaml
       ```
       apiVersion: longhorn.io/v1beta2
       kind: Snapshot
       metadata:
         name: snap001
         namespace: longhorn-system
       spec:
         volume: vol1
         createSnapshot: true    
       ```
    1. Verify that Longhorn provison a new snapshot `snap001` inside Longhorn UI
    1. Run `kubectl get snapshots -n longhorn-system snap001`. Verify the `status` field of the snapshot CR is good (all fields make sense)
    1. Run `kubectl describe snapshots -n longhorn-system snap001`. Verify that the related events sequence is good
1. Create new snapshot CR, volume detached
    1. Detach `vol1`
    1. Deloy the yaml
       ```
       apiVersion: longhorn.io/v1beta2
       kind: Snapshot
       metadata:
         name: snap002
         namespace: longhorn-system
       spec:
         volume: vol1
         createSnapshot: true    
       ```
    1. Run `kubectl get snapshots -n longhorn-system snap001`. Verify the `status` field contains the error message `cannot take snapshot because the volume engine vol1-e-cbc27184 is not running`
    1. Run `kubectl describe snapshots -n longhorn-system snap001`. Verify that the related events cotains the same error
    1. Attach `vol1`
    1. Verify the the snapshot is created inside Longhorn UI and the snapshot CR status looks good
1. Create snapshot using UI
    1. Create a snapshot using Longhorn UI
    1. Verify the the snapshot CR is created with the correct status and related events
1. Create snapshot using recurring job
    1. Setting up a snapshot recurring job with retain count 5 and period very minute
    1. Verify that recurring job is functioning correctly 
1. Create snapshot CR with duplicated name
    1. Deploying the following yaml
       ```
       apiVersion: longhorn.io/v1beta2
       kind: Snapshot
       metadata:
         name: snap002
         namespace: longhorn-system
       spec:
         volume: vol1
         createSnapshot: true    
       ```    
    1. Verify that nothing change
    1. Deploying the following yaml
       ```
       apiVersion: longhorn.io/v1beta2
       kind: Snapshot
       metadata:
         name: snap002
         namespace: longhorn-system
       spec:
         volume: vol2
         createSnapshot: true    
       ```    
    1. Verify that we cannot deploy the yaml because `spec.volume` is immutable 

### Delete
1. Delete snapshot CR, volume attached
    1. Delete the `snap001` CR
    1. Verify the `snap001` CR is deleted and the corresponding snapshot is deleted in Longhorn UI
1. Delete snapshot CR, volume detached
    1. Detach `vol1`
    1. Delete `snap002` CR
    1. Verify the the `snap002` CR is stuck in deleting because the volume is not attached
    1. Verify the related events contains `cannot delete snapshot because the volume engine vol1-e-cbc27184 is not running` by doing `kubectl describe snapshots -n longhorn-system snap002`

1. Delete snapshot CR that is next to volume-head
    1. Attach `vol1`
    1. Verify the `snap002` is still stuck in deleting because it is the snapshot next to volume-head thus cannot be removed
    1. Create a new `snap003` by applying
       ```
       apiVersion: longhorn.io/v1beta2
       kind: Snapshot
       metadata:
         name: snap003
         namespace: longhorn-system
       spec:
         volume: vol1
         createSnapshot: true    
       ```
    1. Verify the `snap003` is created and `snap002` is deleted in both kubectl and Longhorn UI
1. Delete snapshot using UI
    1. Create a new snapshot using Longhorn UI, assume that its name is `abc`
    1. Delete `snap003` using Longhorn UI
    1. Verify the `snap003` are removed in both kubectl and UI
1. Delete snapshot that is next to volume-head using Longhorn UI
    1. delete snapshot `abc`
    1. verify that the snapshot `abc` is stuck in deleting
    1. Verify that snapshot `abc` CR status is correct (e.g `status.markRemoved:true` and `status.readyToUse:false`)

### Others
1. Deleting attached volume with existing snapshot CRs
    1. Create a few more snapshots for `vol1`
    1. Verify that corressponding snapshot CRs are creatred 
    1. Delete `vol1` 
    1. Verify that `vol1`is deleted together with all of its snapshots
1. Deleting detached volume with existing snapshot CRs
    1. Attach `vol2`
    1. Create a few more snapshots for `vol2`
    1. Verify that corressponding snapshot CRs are creatred 
    1. Detach `vol2`
    1. Delete `vol2` 
    1. Verify that `vol2`is deleted together with all of its snapshots
1. Uninstall Longhorn with existing snapshot CRs
	1. Longhorn manager pods are still runing 
        1. Create a few volumes, attach them
        1. Create snapshot for them
        1. Detach some of them
        1. Unistall Longhorn
        1. Verify that the uninstallation succeed 
	1. Longhorn manager pods are death
        1. Create a few volumes, attach them
        1. Create snapshot for them
        1. Detach some of them
        1. Delete Longhorn manager daemonset
        1. Unistall Longhorn
        1. Verify that the uninstallation succeed
