### ISSUE TITLE
[BUG] Recreated pod pends in ContainerCreating after node deletion

### ISSUE THREAD

**Issue by gitlawr** [longhorn/longhorn#3149]
**Describe the bug**
After deleting a node, the pod running on it gets recreated but is stuck in ContainerCreating status.

**To Reproduce**
1. Use Rancher v2.6.1 to provision an AWS rke2 cluster with 1 etcd/control and 4 worker nodes.
2. Install Longhorn 100.1.0+up1.2.2 app.
3. Create the following storageclass
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn2
parameters:
  migratable: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
4. Create the following PVC/Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-n2
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-n2
    spec:
      containers:
      - image: nginx
        name: container-0
        volumeMounts:
        - mountPath: /mnt/test
          name: vol0
      volumes:
      - name: vol0
        persistentVolumeClaim:
          claimName: p2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn2
  volumeMode: Filesystem
```
5. Check which node the pod is running. Delete the node from the cluster.

**Result**
The pod is recreated and scheduled to a new node. But it is always in ContainerCreating status.

Logs from longhorn-manager(ip-172-31-21-141 is the deleted node):
```

time="2021-10-14T08:46:03Z" level=warning msg="HTTP handling error unable to detach volume pvc-4e735445-bcf1-4a70-a4b9-6a4ee1b923e5: migration is not ready yet"
time="2021-10-14T08:46:03Z" level=error msg="Error in request: unable to detach volume pvc-4e735445-bcf1-4a70-a4b9-6a4ee1b923e5: migration is not ready yet"
10.42.18.13 - - [14/Oct/2021:08:46:03 +0000] "POST /v1/volumes/pvc-4e735445-bcf1-4a70-a4b9-6a4ee1b923e5?action=detach HTTP/1.1" 500 282 "" "Go-http-client/1.1"
# and a lot of the following
time="2021-10-14T08:50:38Z" level=debug msg="CheckEngineImageReadiness: nodes [ip-172-31-21-141] don't have the engine image rancher/mirrored-longhornio-longhorn-engine:v1.2.2"
```

**Expected behavior**
The pod gets running on a healthy node.

**Environment:**
 - Longhorn version: v1.2.2

**Additional context**
The pod will be running using RWO PVC, but it takes ~6 minutes after the pod is recreated.
[longhorn-support-bundle_15432e00-ef27-4a1c-92fc-04667fa663ba_2021-10-14T08-38-20Z.zip](https://github.com/longhorn/longhorn/files/7344590/longhorn-support-bundle_15432e00-ef27-4a1c-92fc-04667fa663ba_2021-10-14T08-38-20Z.zip)
