### ISSUE TITLE
[BUG] orphaned pod pod_id found, but error not a directory occurred when trying to remove the volumes dir

### ISSUE THREAD

**Issue by rlex** [longhorn/longhorn#3207]
**Describe the bug**
After unclean node shutdown and probably some other cases, kubelet fails to remove orphaned pod with longhorn PVC

**To Reproduce**
1) Deploy k3s
2) Deploy longhorn
3) Deploy pod with longhorn volume
4) crash node with pod running / kill k3s
5) Observe the logs

**Expected behavior**
No log spam should appear

**Log**
```
k3s[471]: E1102 15:11:01.933125     471 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"5a5fd1bf-bc3c-4600-88d3-321701d3d95a\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=2
```

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster:3
   - Number of worker node in the cluster:4

**Additional context**
I'm not quite sure if this kubelet or longhorn issue. Issue itself is caused due to how kubelet manages orphaned pods cleanup - looks like it calls rmdir and if something is inside said dir it fails to drop directory. In case of longhorn-provisioned volumes, inability to cleanup orphaned pods directories is caused by 
```
vol_data.json
```
file, in my case containing
```
root@master-1:~# cat /var/lib/kubelet/pods/47a9ab25-68e9-4c8a-ab29-a3b3a0500799/volumes/kubernetes.io~csi/pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a/vol_data.json
{"attachmentID":"csi-7b27560c7ac7e905a2f097d3caef3b16ad78e7e138b1b4c6d5c427a4066e9729","driverName":"driver.longhorn.io","nodeName":"master-1","specVolID":"pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a","volumeHandle":"pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a","volumeLifecycleMode":"Persistent"}
```

Removing that dangling file allows kubelet to proceed with orphaned pod cleanup.

There is also this https://github.com/longhorn/longhorn/issues/3080 ticket but seems those are caused by different cases.

**Comment by rlex** [comment]
Additionally: https://github.com/kubernetes/kubernetes/issues/60987#issuecomment-415370444

**Comment by derekbit** [comment]
@rlex , what's your k3s version?

**Comment by rlex** [comment]
v1.22.2+k3s2

**Comment by derekbit** [comment]
@rlex 
I cannot reproduce it in my environment.

Could you please help to provide the following information for narrowing down the problem and further analysis?
- What's your longhorn configuration? number of replicas? Are some nodes unscheduable?
- Pod and PVC yaml files for reproduce
- In your step 4, after the worker nodes crashed, did it re-join to the cluster?
- In your step 5, is the log on the crashed node or other node?
- Provide the log with the above error messages

**Comment by rlex** [comment]
ATM i'm cleaned all my nodes from leftover files, so i can't give you exact configuration.
I used default storageClass with 3 replicas. All nodes are schedulable.
Node with attached PV crashed (kernel panic, probably unrelated to longhorn)
Yes, node rejoined cluster, but pod was already rescheduled and recreated at different node. Log was on crashed node.
I can try digging around in my logs, maybe i can find that error message again.

**Comment by derekbit** [comment]
@rlex 
Here's my step trying to reproduce, but I can't reproduce with multiple trials.
If there is anything I missed or any clue, please let me know, thank you.

1. Deploy k3s (1 masetr + 4 workers)
2. Deploy longhorn with 3 replicas
3. Deploy deployment with longhorn volume
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: volume-test
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      restartPolicy: Always
      containers:
      - name: volume-test
        image: ubuntu:20.04
        command:
          - "sleep"
          - "604800"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: volv
          mountPath: /data
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc
```

4. kill worker not where pod is running by `systemctl stop k3s-agent.service` 
5. After the node becomes NotReady, re-join the worker to the cluster by `systemctl start k3s-agent.service` 
6. Check the logs
