### ISSUE TITLE
[QUESTION] Longhorn Web-UI not loading

### ISSUE THREAD

**Issue by MeranaTona** [longhorn/longhorn#3235]
**Question**
Hi all,

I cant reach the Longhorn Web-UI.

I followed the Longhorn installation guide via helm: https://longhorn.io/docs/1.2.2/deploy/install/install-with-helm/ (including successfull requirements check). Results:
```
kubectl get pods -n longhorn-system
NAME                                        READY   STATUS    RESTARTS      AGE
csi-attacher-75588bff58-7mzcw               1/1     Running   0             63m
csi-attacher-75588bff58-dwst8               1/1     Running   0             63m
csi-attacher-75588bff58-nrk58               1/1     Running   0             63m
csi-provisioner-669c8cc698-cmlvc            1/1     Running   0             63m
csi-provisioner-669c8cc698-jxqlb            1/1     Running   0             63m
csi-provisioner-669c8cc698-whbts            1/1     Running   0             63m
csi-resizer-5c88bfd4cf-l5jpw                1/1     Running   0             63m
csi-resizer-5c88bfd4cf-l9x98                1/1     Running   0             63m
csi-resizer-5c88bfd4cf-sskwt                1/1     Running   0             63m
csi-snapshotter-69f8bc8dcf-56n4f            1/1     Running   0             63m
csi-snapshotter-69f8bc8dcf-jlf8g            1/1     Running   0             63m
csi-snapshotter-69f8bc8dcf-l6qlp            1/1     Running   0             63m
engine-image-ei-d4c780c6-hl6lb              1/1     Running   0             63m
engine-image-ei-d4c780c6-kcmml              1/1     Running   0             63m
engine-image-ei-d4c780c6-mbmq9              1/1     Running   0             63m
engine-image-ei-d4c780c6-njbr2              1/1     Running   0             63m
instance-manager-e-16b797ac                 1/1     Running   0             63m
instance-manager-e-54f9de01                 1/1     Running   0             63m
instance-manager-e-d801ac0e                 1/1     Running   0             63m
instance-manager-e-db5ba766                 1/1     Running   0             63m
instance-manager-r-8f204c95                 1/1     Running   0             63m
instance-manager-r-ad74c0c4                 1/1     Running   0             63m
instance-manager-r-c4807df1                 1/1     Running   0             63m
instance-manager-r-cf6a68ab                 1/1     Running   0             63m
longhorn-csi-plugin-7w8ld                   2/2     Running   0             63m
longhorn-csi-plugin-r8q4n                   2/2     Running   0             63m
longhorn-csi-plugin-r9pqr                   2/2     Running   0             63m
longhorn-csi-plugin-v85ck                   2/2     Running   0             63m
longhorn-driver-deployer-75f68555c9-8nw7d   1/1     Running   0             64m
longhorn-iscsi-installation-jd5zb           1/1     Running   0             84m
longhorn-iscsi-installation-qntvs           1/1     Running   0             84m
longhorn-iscsi-installation-svlrk           1/1     Running   0             84m
longhorn-iscsi-installation-wp22l           1/1     Running   0             84m
longhorn-manager-7mlsn                      1/1     Running   1 (63m ago)   64m
longhorn-manager-8gp7k                      1/1     Running   0             64m
longhorn-manager-jppdb                      1/1     Running   1 (63m ago)   64m
longhorn-manager-jzn42                      1/1     Running   1 (63m ago)   64m
longhorn-nfs-installation-2ml5j             1/1     Running   0             80m
longhorn-nfs-installation-6dlnk             1/1     Running   0             80m
longhorn-nfs-installation-96vdd             1/1     Running   0             80m
longhorn-nfs-installation-m7xr5             1/1     Running   0             80m
longhorn-ui-75ccbd4695-ms4tv                1/1     Running   0             64m
```

Next, I installed a nginx ingress controller, by following the "bare metal" guide on https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal. I added the lines  
```
annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
``` 
to the nginx yaml file. Everthing else is original. The file looks as follows:
```
          secret:
            secretName: ingress-nginx-admission
---
# Source: ingress-nginx/templates/controller-ingressclass.yaml
# We don't support namespaced ingressClass yet
# So a ClusterRole and a ClusterRoleBinding is required
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.6
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.0.4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  name: nginx
  namespace: ingress-nginx
spec:
  controller: k8s.io/ingress-nginx
---
# Source: ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
# before changing this value, check the required kubernetes version
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.6
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.0.4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-webhook
  name: ingress-nginx-admission
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
```
Next, I followed the Longhorn guide for setting up an longhorn UI ingress https://longhorn.io/docs/1.2.2/deploy/accessing-the-ui/longhorn-ingress/. 
With file "auth" containing two entries:
```
user1:$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
user2:$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Results are:
```
kubectl get ingress --all-namespaces
NAMESPACE         NAME               CLASS   HOSTS   ADDRESS        PORTS   AGE
longhorn-system   longhorn-ingress   nginx   *       "my_host_ip"   80      7m32s
```
and:
```
kubectl get svc -n ingress-nginx
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             NodePort    10.97.63.194     <none>        80:31436/TCP,443:30418/TCP   18m
ingress-nginx-controller-admission   ClusterIP   10.107.155.117   <none>        443/TCP                      18m
```

Curling the nodeport twice without credentials (second time I get an completly different answer):
```
curl -v http://my_host_ip:31436/
*   Trying my_host_ip:31436...
* TCP_NODELAY set
* Connected to my_host_ip (my_host_ip) port 31436 (#0)
> GET / HTTP/1.1
> Host: my_host_ip:31436
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Thu, 11 Nov 2021 08:45:55 GMT
< Content-Type: text/html
< Content-Length: 172
< Connection: keep-alive
< WWW-Authenticate: Basic realm="Authentication Required"
<
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host my_host_ip left intact
user1@host:~/longhorn$ curl -v http://my_host_ip:31436/
*   Trying my_host_ip:31436...
* TCP_NODELAY set
* Connected to my_host_ip (my_host_ip) port 31436 (#0)
> GET / HTTP/1.1
> Host: my_host_ip:31436
> User-Agent: curl/7.68.0
> Accept: */*
>
```

curling with credentials:
```
 curl -v http://my_host_ip:31436/ -u user1:xxxxxxxxxxxxxxxxx
*   Trying my_host_ip:31436...
* TCP_NODELAY set
* Connected to my_host_ip:31436 (my_host_ip:31436) port 31436(#0)
* Server auth using Basic with user 'user1'
> GET / HTTP/1.1
> Host: my_host_ip:31436
> Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 10 Nov 2021 13:40:02 GMT
< Content-Type: text/html
< Content-Length: 1025
< Connection: keep-alive
< Last-Modified: Thu, 07 Oct 2021 11:29:55 GMT
< Vary: Accept-Encoding
< ETag: "615eda33-401"
< Cache-Control: max-age=0
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--[if lte IE 10]>
      <script
        src="https://as.alipayobjects.com/g/component/??console-polyfill/0.2.2/index.js,media-match/2.0.2/media.match.min.js"></script>
  <![endif]-->
  <style>
    ::-webkit-scrollbar {
      width: 10px;
      height: 1px;
    }

    ::-webkit-scrollbar-thumb {
      border-radius: 10px;
      -webkit-box-shadow: inset 0 0 5px rgba(0,0,0,0.1);
      background: #535353;
    }
  </style>
<link href="./styles.css?fc8ec4140abd497a1b70" rel="stylesheet"></head>

<body>
  <div id="root"></div>
<script type="text/javascript" src="./runtime~main.2bf68965.js?fc8ec4140abd497a1b70"></script><script type="text/javascript" src="./styles.22f36a89.async.js?fc8ec4140abd497a1b70"></script><script type="text/javascript" src="./main.c3b456f8.async.js?fc8ec4140abd497a1b70"></script></body>

</html>
* Connection #0 to host my_host_ip left intact
```

Entering credentials via my browser (after port forwarding to my local laptop 'ssh -L 31436:localhost:31436 user1@my_host_ip' and then in browser: http://localhost:31436/) will be accepted but the Longhorn Webpage wont be loaded. All I see is the Longhorn symbol on my browser tab.

Any ideas how to fix that?

Thank you in advance.

**Environment:**
 - Longhorn version: 1.2.2
 - Kubernetes version: 1.22.2
 - Underlying Infrastructure: Baremetal
