### ISSUE TITLE
[QUESTION] Mount Longhorn

### ISSUE THREAD

**Issue by MeranaTona** [longhorn/longhorn#3293]
## Question
Hi all,

is it possible to mount Longhorn as a filesystem, so that all files within Longhorn can be accessed?
E.g. "sudo mount /dev/longhorn /my/custom/dir"

Thank you in advance

**Comment by derekbit** [comment]
@MeranaTona 
Do you mean accessed by multiple application pods simultaneously?

**Comment by jenting** [comment]
Could you please tell us what's the problem/scenario you want to achieve?

**Comment by cocampbe** [comment]
If you are asking if you can just mount a volume, but not have the volume presented to a pod, the answer is yes. You would attach the volume to a node, likely in maintenance mode, then mount the block device that maps to the volume.

**Comment by ydcool** [comment]
I have a longhorn pvc in block volume mode , and a pod mount the pvc as volume device, so I wonder how to mount the device in pod? 

```sh
root@vm-ehe32mlb:/# mount  /dev/vm-ehe32mlb-system-volume /mnt
mount: /mnt: permission denied.
```

the pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-ehe32mlb-system-disk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 22Gi
  storageClassName: longhorn-bi-7136193527497474048
  volumeMode: Block
  volumeName: pvc-f3287341-9b82-499e-af6b-7220087901b3
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 22Gi
  phase: Bound
```

the pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fake-launcher-vm-ehe32mlb
spec:
  containers:
  - image: myregistry.com:5000/library/os/ubuntu-20.04:5.1.0
    command: 
    - sh
    - -c
    - tail -f /dev/null
    imagePullPolicy: IfNotPresent
    name: compute
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
        - SYS_NICE
      privileged: false
      runAsNonRoot: false
      runAsUser: 0
    volumeDevices:
    - devicePath: /dev/vm-ehe32mlb-system-volume
      name: vm-ehe32mlb-system-volume
  hostname: vm-ehe32mlb
  nodeName: hci01
  securityContext:
    runAsUser: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: vm-ehe32mlb-system-volume
    persistentVolumeClaim:
      claimName: vm-ehe32mlb-system-disk
```

and the sc: 
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-bi-7136193527497474048
parameters:
  backingImage: "7136193527497474048"
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  migratable: "true"
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
