### ISSUE TITLE
[BACKPORT][IMPROVEMENT][v1.2.3] Simplify the way to record and fetch backup info after introducing Backup CRD

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3298]
Backport #3035

**Comment by chanow816** [comment]
**Validation : Pass**

Validated on Longhorn v1.2.3-rc2

In Engine CR :
```
status:
    backupStatus: null
```

After restart longhorn-manager daemonset, in Backups CR :

```
 status:
    backupCreatedAt: ""
    labels: null
    lastSyncedAt: null
    messages: null
    ownerID: worker2
    progress: 4
    replicaAddress: tcp://10.42.1.16:10015
    size: ""
    snapshotCreatedAt: ""
    snapshotName: 164f9ec5-f84c-4d4c-89c6-6e5e7596abf9
    state: InProgress
    url: ""
    volumeBackingImageName: ""
    volumeCreated: ""
    volumeName: ""
    volumeSize: ""
```

After created error situation, in Backups CR:
Scenario from https://github.com/longhorn/longhorn/issues/1268

```
status:
    backupCreatedAt: ""
    error: |
      failed to put object: backupstore/backupstore/volumes/17/22/bak/blocks/0d/3c/0d3c1e90325af967f22c63e5e4abec76c3aa76119fb1776085488ea8162acd6c.blk response: {

      } error: AWS Error:  XMinioStorageFull Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. <nil>
      507 16C0926C47F8284A
    labels: null
    lastSyncedAt: "2021-12-14T08:40:58Z"
    messages: null
    ownerID: worker2
    progress: 84
    replicaAddress: tcp://10.42.1.16:10015
    size: ""
    snapshotCreatedAt: ""
    snapshotName: 164f9ec5-f84c-4d4c-89c6-6e5e7596abf9
    state: Error
    url: ""
    volumeBackingImageName: ""
    volumeCreated: ""
    volumeName: ""
    volumeSize: ""
```
