### ISSUE TITLE
[BUG] Node selector causes loop or does not attach volumes

### ISSUE THREAD

**Issue by NosIreland** [longhorn/longhorn#3324]
## Describe the bug

if I set NodeSelector in the GUI, then I have constant loop of terminating /pending/nodeaffinity instance-manager pods
image
![image](https://user-images.githubusercontent.com/19308746/143419518-bf372953-36ff-4a3d-bc32-e0656f698f6f.png)
```

instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-62011d50                0/1     Pending        0          0s
instance-manager-r-173c8d38                0/1     Terminating    0          1s
instance-manager-r-3aa00ef2                0/1     Terminating    0          1s
instance-manager-r-173c8d38                0/1     Terminating    0          1s
instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-15c2ed19                0/1     Terminating    0          1s
instance-manager-r-173c8d38                0/1     Pending        0          0s
instance-manager-r-15c2ed19                0/1     Pending        0          0s
instance-manager-e-babc40cc                0/1     NodeAffinity   0          1s
instance-manager-e-267a8970                0/1     NodeAffinity   0          1s
instance-manager-e-e335cb3f                0/1     NodeAffinity   0          1s
instance-manager-r-173c8d38                0/1     Terminating    0          0s
instance-manager-e-267a8970       
```      

If I use node selector and modify yaml before install:
```
  longhornManager:
    nodeSelector:
      label-key1: "label-value1"
  longhornDriver:
    nodeSelector:
      label-key1: "label-value1"
  longhornUI:
    nodeSelector:
      label-key1: "label-value1"
```
and also
```
defaultSettings:
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
```
as per  [Node Selector](https://longhorn.io/docs/1.2.2/advanced-resources/deploy/node-selector/)
After install I get the desired result and only my storage nodes are visible in Longhorn UI.
But when I deploy app from Marketplace that is on worker node the volume gets correctly created but would not attach. The pod would get stuck in `ContainerCreating` and with warnings:
```
Warning  FailedMount         47s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0 rancher-monitoring-prometheus-token-26bvs config prometheus-nginx]: timed out waiting for the condition       
Warning  FailedAttachVolume  41s (x9 over 2m49s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a1a4e299-ee94-463b-a787-af76c0742710" : rpc error: code = NotFound desc = node worker-1.nodes.local not found
```
In Longhorn GUI the volume shows as Detached. It would attach if I do it manually but that makes no impact to the Pod.

## To Reproduce

Steps to reproduce the behavior for Longhorn GUI:
1. Set label on nodes
2. Install Longhorn with default setting using Rancher from Marketplace
3. In Longhorn GUI settings add the label created in step 1 under 'System Managed Components Node Selector' click Save.
4. Watch pods getting created and terminated in longhorn-system `kubectl get pods -n longhorn-system -o wide --watch`

Steps to reproduce the behavior for Longhorn YAML:
1. Set label on nodes
2. From Rancher Marketplace select Longhorn, Edit yaml and change:
```
  longhornManager:
    nodeSelector:
      label-key1: "label-value1"
  longhornDriver:
    nodeSelector:
      label-key1: "label-value1"
  longhornUI:
    nodeSelector:
      label-key1: "label-value1"

defaultSettings:
  systemManagedComponentsNodeSelector: "label-key1:label-value1"
```
3. Install Longorn
4. After install only labeled nodes are visible in Longhorn GUI
5. Install Monitoring app from Marketplace just add Persistent Storage for Prometheus and select Longhorn as Storage Class
6. Watch Volume getting created in Longhorn GUI but it does not attach
7. Watch Prometheus Pod is stuck on creation as it cannot attach Volume
8. Attach Volume in Longhorn manually
9.  Prometheus Pod still cannot attach Volume

## Expected behavior

For GUI setting. The pods should be terminated on non labeled nodes and not try to restart
For YAML the pod should be able to attach the created volume

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.20.11
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 7
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS
   - CPU per node: 8 and up
   - Memory per node: 16GB and up
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0/1

**Comment by derekbit** [comment]
@NosIreland 
According to your description and https://www.reddit.com/r/rancher/comments/r1rvg2/separating_storage_and_worker_nodes_with_longorn/,
you can try the steps in the KB doc https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ .

**Comment by jenting** [comment]
To double confirm, is the worker node install `open-iscsi` and the `iscsid` daemon in running?

**Comment by NosIreland** [comment]
> @NosIreland According to your description and https://www.reddit.com/r/rancher/comments/r1rvg2/separating_storage_and_worker_nodes_with_longorn/, you can try the steps in the KB doc https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ .

I have tried this. Longhorn is deployed as expected but pods will only starts on the storage nodes they will not attach volumes on worker nodes
```
Events:
  Type     Reason              Age                   From                     Message
  ----     ------              ----                  ----                     -------
  Normal   Scheduled           16m                   default-scheduler        Successfully assigned cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-0 to worker1
  Warning  FailedMount         16m                   kubelet                  MountVolume.SetUp failed for volume "tls-assets" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount         14m                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[config prometheus-nginx nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0 kube-api-access-25k52]: timed out waiting for the condition
  Warning  FailedMount         12m                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[prometheus-rancher-monitoring-prometheus-rulefiles-0 kube-api-access-25k52 config prometheus-nginx nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db]: timed out waiting for the condition
  Warning  FailedMount         9m55s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[kube-api-access-25k52 config prometheus-nginx nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0]: timed out waiting for the condition
  Warning  FailedMount         3m5s (x3 over 7m39s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0 kube-api-access-25k52 config prometheus-nginx nginx-home config-out tls-assets]: timed out waiting for the condition
  Warning  FailedMount         50s                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0 kube-api-access-25k52 config prometheus-nginx nginx-home config-out]: timed out waiting for the condition
  Warning  FailedAttachVolume  10s (x9 over 16m)     attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1f8339ed-2c2e-42d3-8d19-d235373882f7" : CSINode worker1 does not contain driver driver.longhorn.io

```



> To double confirm, is the worker node install `open-iscsi` and the `iscsid` daemon in running?

Can you please elaborate? Where is should be running?


I have created additional test environment now with nodes running K3os(1 master, 2 storage and 3 workers) I have done as per https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/  and https://longhorn.io/docs/1.2.2/advanced-resources/deploy/node-selector/
I do get a desired result where longhorn is limited to storage nodes but as before the Pods with PVs would only work if they are running on the storage nodes. If node selector are not used then Pods run fine but Longhorn does have multiple Pods and also reserve CPU for these pods.
We want to have dedicated nodes for storage(with many drives) and dedicated for workloads. Is this scenario is even possible?

Please let me know if you need any logs.
Thank you

**Comment by aintbrokedontfix** [comment]
I am having the same problem exact problem as @NosIreland. I also followed the instructions provided and the result was the same. Some of my volumes would not attach. I also tested DNS resolution from pod to node and resolution functions appropriately. Since the Volumes are being crested via StorageClass, I am assuming my default Frontend is Block Device.

    Longhorn version: v1.2.2
    Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher
    Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.21.6-rancher1-1
        Number of management node in the cluster: 1
        Number of worker node in the cluster: 8
    Node config
        OS type and version: Ubuntu 20.04.3 LTS
        CPU per node: 8 and up
        Memory per node: 16GB and up
        Disk type(e.g. SSD/NVMe):
        Network bandwidth between the nodes:
    Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
    Number of Longhorn volumes in the cluster: 0 they don't attach

**Comment by PhanLe1010** [comment]
@NosIreland @aintbrokedontfix 

There are 3 options in the document https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/.
What you need for this use case is the 1st or the 2nd option (e.g., `https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/` OR `Create a StorageClass that selecting a specific set of nodes`). 

You are using the 3rd option (`Deploy Longhorn components only on a specific set of nodes`) which is mentioned in the document that **the workload cannot start on the non-selected nodes**

**Comment by aintbrokedontfix** [comment]
I tried using the storage=longhorn label and it didn't seem to do anything. 

I have to use taints to accommodate pods onto specific nodes. I have taint-toleration set to match those nodes which allowed csi-attacher, csi-resizer, csi-snapshotter, engine-image-ie, and longhorn-csi-plugin to deploy on those nodes. Should I also add the storage=longhorn label?

**Comment by kinglong08** [comment]
I have encountered the same question and look forward to your answer~

**Comment by agorovoy94** [comment]
The same issue with Longhorn 1.2.2 and Kubernetes 1.22.4

**Comment by aintbrokedontfix** [comment]
> 

@PhanLe1010, 
Are you saying that it is not really possible to separate the "storage" workload from the data processing workload? In other words, longhorn user deployed components (e.g, Manager, Driver Deployer, UI) and system managed components (e.g, Instance Manager, Engine Image, CSI Driver, etc.) must exist in all nodes where pods may need access to storage provided by longhorn? 

Thanks.

**Comment by NosIreland** [comment]
@aintbrokedontfix  Looks like it is not possible to have complete separation unless you want to run your Pods that depend on Longhorn on storage nodes only.
I've tried multiple combinations and if I restrict Manager with nodeselector to storage nodes only, the pods on non storage nodes would not attach the volumes. They would work fine on storage nodes.  Driver and UI can be restricted just to storage nodes and have no impact on pod location.
If that is true, I wish it was clearer in the documentation and at the same time I hope this could be added in the future.

**Comment by PhanLe1010** [comment]
@aintbrokedontfix @NosIreland 

Correct! Longhorn manager, Longhorn engine manager, Longhorn engine image daemonset, Longhorn csi plugin, Longhorn share manager must run on the nodes that the workload pods are running on. Those components are need so Longhorn can do work on the node (e.g., prepare mount point, create the block device, etc, ..)


On the storage nodes, Longhorn will deploy extra component to manage the node storage like: Longhorn replica instance manager. 

In summary, if you want the workload to run on any nodes in the cluster, you want to do the first 2 options as mentioned at https://github.com/longhorn/longhorn/issues/3324#issuecomment-982065064

cc @kinglong08 and @agorovoy94

**Comment by aintbrokedontfix** [comment]
@PhanLe1010, one more question. 

A data processing node with a taint of "node.dataprocessing/class=dp:NoSchedule" would basically repel all things longhorn. Would it be correct to set: 
```
defaultSettings:
     taintToleration: "node.dataprocessing/class=dp:NoSchedule"
```
The expectation is that all the necessary longhorn pods would deploy in nodes with that taint instead of being repelled. Is that a correct expectation?

**Comment by PhanLe1010** [comment]
@aintbrokedontfix 
You need to set `defaultSettings. taintToleration` AND the toleration for the user-deployed components (Manager, UI, Driver Deployer) See doc at https://longhorn.io/docs/1.2.2/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn

**Comment by aintbrokedontfix** [comment]
Ok, I tried that and I must be missing something. I am getting the following error:

```AttachVolume.Attach failed for volume "pvc-eb54e2ce-0ba2-4a99-887a-c282c5664991" : CSINode hostname-here does not contain driver driver.longhorn.io ```

The defaultSettings look like this in the Rancher HELM chart. 
```
defaultSettings:
  createDefaultDiskLabeledNodes: true
  systemManagedComponentsNodeSelector: node-role.kubernetes.io/worker:true
  taintToleration: ':' # this toleration tolerates everything because an empty key with operator Exists matches all keys, values and effects 

...

longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
longhornManager:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
longhornUI:  # not set, I don't care where the UI lands... 
  nodeSelector: {}
  priorityClass: null
  tolerations: []

```

What am I missing? why is driver.longhorn.io missing on the nodes where there is a Taint and available on those nodes where there is no Taint. The longhornManager does exist on all the nodes that have a Taint. 

ps: Taints are ANDs so, how does taintToleration handle having a list where all taints are different?

**Comment by PhanLe1010** [comment]
@aintbrokedontfix 

What is the output of `kubectl get settings taint-toleration -n longhorn-system` ?

**Comment by PhanLe1010** [comment]
You already have Longhorn running in the cluster so you need to use the instruction on the second half of the document page https://longhorn.io/docs/1.2.2/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn
<img width="737" alt="Screen Shot 2021-11-30 at 6 28 59 PM" src="https://user-images.githubusercontent.com/22139961/144161042-c6ee9e47-8af4-49ee-896c-297753a42c80.png">

**Comment by aintbrokedontfix** [comment]
> 

kubectl get settings taint-toleration -n longhorn-system
```
NAME               VALUE   AGE
taint-toleration           11h
```
What is the expected value? 

I have been deleting the longhorn deployment between tries so, every time is brand speaking new (top end of the doc)

**Comment by aintbrokedontfix** [comment]
Ok, I think I spotted the problem.  Values being set through the Rancher HELM chart are not being used. 

I noticed that even after a new deployment, the values for systemManagedComponentsNodeSelector and taintToleration were not being shown in the Longhorn UI. In fact the instructions in the Longhorn UI say to set the value for systemManagedComponentsNodeSelector in the Yaml file and in the UI. It does not say the same about taintToleration in the UI, but once I updated both of them in the UI 2 things happened: 

- all longhorn user and longhorn system managed components appeared in those nodes that had defined taints
- the output of `kubectl get settings taint-toleration -n longhorn-system` changed from empty to `':'`

I installed my application and it attached all the volumes, which it was not doing before. Now I need to test with specific tolerations vs "any". 

Rancher HELM yaml
```
annotations: {}
csi:
  attacherReplicaCount: null
  kubeletRootDir: null
  provisionerReplicaCount: null
  resizerReplicaCount: null
  snapshotterReplicaCount: null
defaultSettings:
  allowNodeDrainWithLastHealthyReplica: null
  allowRecurringJobWhileVolumeDetached: null
  allowVolumeCreationWithDegradedAvailability: null
  autoCleanupSystemGeneratedSnapshot: null
  autoDeletePodWhenVolumeDetachedUnexpectedly: null
  autoSalvage: null
  backingImageCleanupWaitInterval: null
  backingImageRecoveryWaitInterval: null
  backupTarget: null
  backupTargetCredentialSecret: null
  backupstorePollInterval: null
  concurrentAutomaticEngineUpgradePerNodeLimit: null
  concurrentReplicaRebuildPerNodeLimit: null
  createDefaultDiskLabeledNodes: true
  defaultDataLocality: null
  defaultDataPath: null
  defaultLonghornStaticStorageClass: null
  defaultReplicaCount: null
  disableReplicaRebuild: null
  disableRevisionCounter: null
  disableSchedulingOnCordonedNode: null
  guaranteedEngineManagerCPU: null
  guaranteedReplicaManagerCPU: null
  mkfsExt4Parameters: null
  nodeDownPodDeletionPolicy: null
  priorityClass: null
  replicaAutoBalance: null
  replicaReplenishmentWaitInterval: null
  replicaSoftAntiAffinity: null
  replicaZoneSoftAntiAffinity: null
  storageMinimalAvailablePercentage: null
  storageOverProvisioningPercentage: null
  systemManagedComponentsNodeSelector: node-role.kubernetes.io/worker:true
  systemManagedPodsImagePullPolicy: null
  taintToleration: ':' # this toleration tolerates everything because an empty key with operator Exists matches all keys, values and effects 
  upgradeChecker: null
enablePSP: true
global:
  cattle:
    systemDefaultRegistry: ''
image:
  csi:
    attacher:
      repository: rancher/mirrored-longhornio-csi-attacher
      tag: v3.2.1
    nodeDriverRegistrar:
      repository: rancher/mirrored-longhornio-csi-node-driver-registrar
      tag: v2.3.0
    provisioner:
      repository: rancher/mirrored-longhornio-csi-provisioner
      tag: v2.1.2
    resizer:
      repository: rancher/mirrored-longhornio-csi-resizer
      tag: v1.2.0
    snapshotter:
      repository: rancher/mirrored-longhornio-csi-snapshotter
      tag: v3.0.3
  longhorn:
    backingImageManager:
      repository: rancher/mirrored-longhornio-backing-image-manager
      tag: v2_20210820
    engine:
      repository: rancher/mirrored-longhornio-longhorn-engine
      tag: v1.2.2
    instanceManager:
      repository: rancher/mirrored-longhornio-longhorn-instance-manager
      tag: v1_20210731
    manager:
      repository: rancher/mirrored-longhornio-longhorn-manager
      tag: v1.2.2
    shareManager:
      repository: rancher/mirrored-longhornio-longhorn-share-manager
      tag: v1_20210914
    ui:
      repository: rancher/mirrored-longhornio-longhorn-ui
      tag: v1.2.2
  pullPolicy: IfNotPresent
  defaultImage: true
ingress:
  annotations: null
  enabled: false
  host: xip.io
  ingressClassName: null
  secrets: null
  tls: false
  tlsSecret: longhorn.local-tls
longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
longhornManager:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
longhornUI:
  nodeSelector: {}
  priorityClass: null
  tolerations: []
namespaceOverride: ''
persistence:
  backingImage:
    dataSourceParameters: null
    dataSourceType: null
    enable: false
    expectedChecksum: null
    name: null
  defaultClass: true
  defaultClassReplicaCount: 3
  defaultFsType: ext4
  reclaimPolicy: Delete
  recurringJobSelector:
    enable: false
    jobList: []
privateRegistry:
  registryPasswd: null
  registrySecret: null
  registryUrl: null
  registryUser: null
resources: {}
service:
  manager:
    nodePort: ''
    type: ClusterIP
  ui:
    nodePort: null
    type: ClusterIP
longhorn:
  default_setting: false
```

Longhorn UI Screenshot after I updated System Managed Components Node Selector and Kubernetes Taint Toleration
![image](https://user-images.githubusercontent.com/25690442/144236817-f3e5054b-d151-4323-a07e-667d00e97647.png)

**Comment by aintbrokedontfix** [comment]
Hello @PhanLe1010,  Please, riddle me this:

node1 has the following labels and taints:
* label: storage=longhorn
* label: node.longhorn.io/create-default-disk=true
* taint: longhorn.node.storage=true:NoSchedule

node2 has the following labels and taints:
* label: storage=longhorn
* label: node.longhorn.io/create-default-disk=true
* taint: myapp.workload.class/dp=true:NoSchedule

The Rancher HELM Chart provides the following:
```
defaultSettings:
  createDefaultDiskLabeledNodes: true
  systemManagedComponentsNodeSelector: storage=:longhorn
  taintToleration: ':' # this toleration tolerates everything because an empty key with operator Exists matches all keys, values and effects 
...
longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
longhornManager:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: ''
      operator: Exists
      value: ''
...
```

`kubectl get settings taint-toleration -n longhorn-system` shows:
```
NAME               VALUE   AGE
taint-toleration   :       14h
```

`kubectl describe node1` shows:
```
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.azure.com/mode=system
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=HOSTNAME
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=true
                    node.longhorn.io/create-default-disk=true
                    storage=longhorn
Annotations:        csi.volume.kubernetes.io/nodeid: {"driver.longhorn.io":"HOSTNAME"}
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"62:51:32:ae:69:3a"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: IP
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: IP/22
                    projectcalico.org/IPv4IPIPTunnelAddr: IP
                    rke.cattle.io/external-ip: IP
                    rke.cattle.io/internal-ip: IP
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  TIMESTAMP
Taints:             longhorn.node.storage=true:NoSchedule


  Namespace                   Name                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                              ------------  ----------  ---------------  -------------  ---
  cattle-system               cattle-node-agent-l4pnk           0 (0%)        0 (0%)      0 (0%)           0 (0%)         23h
  ingress-nginx               nginx-ingress-controller-6xhf2    0 (0%)        0 (0%)      0 (0%)           0 (0%)         23h
  kube-system                 canal-9497p                       250m (3%)     0 (0%)      0 (0%)           0 (0%)         23h
  longhorn-system             engine-image-ei-0422ab0c-dpcdd    0 (0%)        0 (0%)      0 (0%)           0 (0%)         35m
  longhorn-system             instance-manager-e-3d75fc79       960m (12%)    0 (0%)      0 (0%)           0 (0%)         13h
  longhorn-system             instance-manager-r-eb9284c3       960m (12%)    0 (0%)      0 (0%)           0 (0%)         13h
  longhorn-system             longhorn-csi-plugin-5hjvg         0 (0%)        0 (0%)      0 (0%)           0 (0%)         34m
  longhorn-system             longhorn-manager-qxsm8            0 (0%)        0 (0%)      0 (0%)           0 (0%)         35m
```

`kubectl describe node2` shows:
```
  
Roles:          worker
Labels:        beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=HOSTNAME
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=true
                    node.longhorn.io/create-default-disk=true
                    myapp.workload.class=dp
                    storage=longhorn
Annotations:        csi.volume.kubernetes.io/nodeid: {"driver.longhorn.io":"HOSTNAME"}
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"1e:4a:da:88:8a:bd"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: IP
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: IP/22
                    projectcalico.org/IPv4IPIPTunnelAddr: IP
                    rke.cattle.io/external-ip: IP
                    rke.cattle.io/internal-ip: IP
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  TIMESTAMP
Taints:             myapp.workload.class/dp=true:NoSchedule
Unschedulable:      false


Namespace                   Name                                CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                ------------  ----------  ---------------  -------------  ---
  cattle-system               cattle-node-agent-trlpl             0 (0%)        0 (0%)      0 (0%)           0 (0%)         11h
  ingress-nginx               nginx-ingress-controller-wcbph      0 (0%)        0 (0%)      0 (0%)           0 (0%)         11h
  kube-system                 canal-5nxgc                         250m (1%)     0 (0%)      0 (0%)           0 (0%)         11h
  longhorn-system             csi-provisioner-79c79b8c5-vjnhb     0 (0%)        0 (0%)      0 (0%)           0 (0%)         40m
  longhorn-system             csi-resizer-6dd449d48d-d4klt        0 (0%)        0 (0%)      0 (0%)           0 (0%)         40m
  longhorn-system             csi-resizer-6dd449d48d-dnczd        0 (0%)        0 (0%)      0 (0%)           0 (0%)         40m
  longhorn-system             csi-snapshotter-6dc7486688-fmlbk    0 (0%)        0 (0%)      0 (0%)           0 (0%)         40m
  longhorn-system             engine-image-ei-0422ab0c-jdsfq      0 (0%)        0 (0%)      0 (0%)           0 (0%)         44m
  longhorn-system             instance-manager-e-540ed92a         1920m (12%)   0 (0%)      0 (0%)           0 (0%)         47m
  longhorn-system             instance-manager-r-8e9ed862         1920m (12%)   0 (0%)      0 (0%)           0 (0%)         47m
  longhorn-system             longhorn-csi-plugin-mzzhc           0 (0%)        0 (0%)      0 (0%)           0 (0%)         43m
  longhorn-system             longhorn-manager-q94zd              0 (0%)        0 (0%)      0 (0%)           0 (0%)         44m
```

The labels are the same and the taint-toleration is set to "any"? Shouldn't they contain the same pods? shouldn't the label attract the pods to these 2 nodes while ignoring the node taints altogether? Why are the nodes different?

**Comment by aintbrokedontfix** [comment]
I am also seeing the issue with the node selector and instance-manager pods going into a never ending loop.

**Comment by PhanLe1010** [comment]
> The labels are the same and the taint-toleration is set to "any"? Shouldn't they contain the same pods? shouldn't the label attract the pods to these 2 nodes while ignoring the node taints altogether? Why are the nodes different?

The node-1 and node-2 do contains the essential pods (longhorn-manager, instance-manager, longhorn-csi, engine-image). They look good. The CSI-pod is the pods of deployments and they could land on any eligible nodes

**Comment by PhanLe1010** [comment]
Sorry, I got confused now. Let's restart from the beginning. 

So you have a cluster of how many nodes? 
What are the worker nodes?
What are the labels and taints on each worker nodes?
Which nodes do you want Longhorn to use their disks?
Which nodes are you planning to run the workload on?


Please give me the information and I will provide you the helm config

**Comment by aintbrokedontfix** [comment]
@PhanLe1010 
This is how I had envisioned it:
node 1 = control plane, longhorn manger, UI & Driver Deployer (does not provide storage)
node 2 = longhorn manger, UI & Driver Deployer (provides storage)
node 3 = longhorn manger, UI & Driver Deployer (provides storage)
node 4 = longhorn manger, UI & Driver Deployer (provides storage)
node 5 = dp, longhorn instance manager, engine image, csi driver (does not provide storage)
node 6 = dp, longhorn instance manager, engine image, csi driver (does not provide storage)
node 7 = dp, longhorn instance manager, engine image, csi driver (does not provide storage)
node 8 = stateful, longhorn instance manager, engine image, csi driver (does not provide storage)
node 9 = stateless, longhorn instance manager, engine image, csi driver (does not provide storage)

The goal all along was to separate my application workloads from the longhorn storage duties/workloads. 

I figured out that I was not able to achieve the above unless I told longhorn to deploy the default disk on all my nodes, even if I had no intention to use those nodes for storage, and created a storage class as described [here](https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/). 

I noticed there is something funny about using the `':'` (any taint) in the configuration YAML file. I tried escaping it `'::'` and simply leaving it as `':'` however, in either case, the setting would not appear in the UI. The only way to reliably apply `':'` to `taintToleration` was through the UI. The ':' also seems to trigger a bug that is the genesis of this thread. When applying ':' through the UI you see that the instance-manager Pods get into an infinite loop of terminating pods and starting a new ones as shown in [comment](https://github.com/longhorn/longhorn/issues/3324#issuecomment-982054902).  

Another bit that had me confused was RWX PVCs which my app uses. Going strictly by the requirements in the HELM chart, there was no mention of nfs-common or nfs-client being required; however, that is clearly stated [doc](https://longhorn.io/docs/1.2.2/advanced-resources/rwx-workloads/#requirements) about RWX support. I think that it would be helpful to add a section about that on the HELM chart doc even if it is an experimental feature. 

So far this has been a great learning experience for me, but unfortunately for RWX PVCs Longhorn does not offer a better option than just using NFS provisioned from a Netapp or ANF. 

![image](https://user-images.githubusercontent.com/25690442/144673798-cb18ab70-685c-4ab3-a104-677883dc4c58.png)

**Comment by PhanLe1010** [comment]
Thank you for providing the information! I would recommend the following settings:
1. Don't run workload or any Longhorn component on the control plane node (node-1)
2. Label node-2, node-3, node-4 with the label `node.longhorn.io/create-default-disk=true`
3. Set the following helm values:
```
defaultSettings:
  createDefaultDiskLabeledNodes: true
  taintToleration: <THE TOLERATION THAT TOLERATE ALL WORKER NODE>

...

longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations:
  - <THE TOLERATION THAT TOLERATE ALL WORKER NODE>
longhornManager:
  nodeSelector: {}
  priorityClass: null
  tolerations: 
  - <THE TOLERATION THAT TOLERATE ALL WORKER NODE>
longhornUI:  # not set, I don't care where the UI lands... 
  nodeSelector: {}
  priorityClass: null
  tolerations:
  - <THE TOLERATION THAT TOLERATES ALL WORKER NODE>
```
4. Check Longhorn UI to see if the setting `Create Default Disk on Labeled Nodes` and `Kubernetes Taint Toleration` to see if they get the correct values, if not set it in Longhorn UI


**End Result:**
1. Longhorn only create disk and use storage on node-2, node-3, node-4
2. Longhorn components will run on all worker nodes. This enables Longhorn to provide storage for all worker nodes. Note that Longhorn still only use storage on node-2, node-3, node-4
