### ISSUE TITLE
[BUG] V1.2.3-rc1 volume not become healthy after attached to node

### ISSUE THREAD

**Issue by chanow816** [longhorn/longhorn#3344]
## Describe the bug

In AWS environment, volume not become healthy after attached to node
Stuck at `The volume is in expansion`

## To Reproduce

1. Use Rancher deploy Longhorn `v1.2.3-rc1` and specific instance-manager `v1_20210731-patch`
2. Create volume from UI and attach it to any node
3. In Volume page, volume status keep `Attached` and size icon keep rolling

## Expected behavior

After a moment, volume should become Healthy

## Log or Support bundle

[longhorn-support-bundle_8dad2ad3-c1d5-49a1-a969-f6de93006def_2021-11-30T09-38-55Z.zip](https://github.com/longhorn/longhorn/files/7624631/longhorn-support-bundle_8dad2ad3-c1d5-49a1-a969-f6de93006def_2021-11-30T09-38-55Z.zip)

## Environment

 - Longhorn version: V1.2.3-rc1,  instance-manager: `v1_20210731-patch`
 - Installation method: Kubectl
 - Kubernetes distro and version: RKE, Kubernetes version: v1.21.6
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu AMD64 20.04, t2.xlarge, 20Gi each node
 - Underlying Infrastructure : AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Not happen in v1.1.3-rc2 when using the same cluster

**Comment by joshimoo** [comment]
@chanow816 If you used the chart to deploy you need to create a headless service for the instance-managers.
Can you reproduce this after the headless service below has been created?

```
---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-engine-manager
  namespace: longhorn-system
spec:
  clusterIP: None
  selector:
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: engine
---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-replica-manager
  namespace: longhorn-system
spec:
  clusterIP: None
  selector:
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: replica
---
```
