### ISSUE TITLE
[BUG] Using a backing image created from a YAML file will lead to NPE

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3379]
## Describe the bug

The issue is similar to #2900. In v1.1.x, we didn't realize that we need to support backing image creation via YAML file.

## To Reproduce

1. Create a backing image via YAML:
```
echo "
apiVersion: longhorn.io/v1beta1
kind: BackingImage
metadata:
  name: bi-test
  namespace: longhorn-system
spec:
    imageURL: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
" | kubectl -n longhorn-system apply -f -
```
2. create and attach a volume with this backing image

When trying to attach the volume, all manager pods will crash due to an NPE error

## Expected behavior
Volume attachment should succeed

## Log or Support bundle

```
[longhorn-manager-rrkpx] 	/usr/local/go/src/runtime/panic.go:967 +0x166
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*ReplicaController).CreateInstance(0xc000596700, 0x1a1e1a0, 0xc0010ec580, 0x1d, 0xc000c15440, 0x1)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:390 +0x77c
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*InstanceHandler).createInstance(0xc000513b60, 0xc0004ae390, 0xe, 0x1d10080, 0xc0010ec580, 0x0, 0x0)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/instance_handler.go:362 +0x178
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*InstanceHandler).ReconcileInstanceState(0xc000513b60, 0x1a1e1a0, 0xc0010ec580, 0xc0010ec698, 0xc0010ec7a0, 0xc0004af340, 0x10)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/instance_handler.go:261 +0xb49
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*ReplicaController).syncReplica(0xc000596700, 0xc00059c180, 0x1e, 0x0, 0x0)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:344 +0xd6f
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*ReplicaController).processNextWorkItem(0xc000596700, 0xc000550c00)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:160 +0xcc
[longhorn-manager-rrkpx] github.com/longhorn/longhorn-manager/controller.(*ReplicaController).worker(0xc000596700)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:148 +0x2b
[longhorn-manager-rrkpx] k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00006c4b0)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
[longhorn-manager-rrkpx] k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00006c4b0, 0x3b9aca00, 0x0, 0x1b26001, 0xc00007c7e0)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
[longhorn-manager-rrkpx] k8s.io/apimachinery/pkg/util/wait.Until(0xc00006c4b0, 0x3b9aca00, 0xc00007c7e0)
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
[longhorn-manager-rrkpx] created by github.com/longhorn/longhorn-manager/controller.(*ReplicaController).Run
[longhorn-manager-rrkpx] 	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:141 +0x230
```

## Environment
 - Longhorn version: v1.1.3-rc2

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with following images based on v1.1.3 branch,
```yaml
        image: longhornio/longhorn-manager:v1.1.3-head
        - longhornio/longhorn-engine:v1.1.3-head
        - longhornio/longhorn-instance-manager:v1_20210731
        - longhornio/longhorn-share-manager:v1_20210416_patch1
        - longhornio/backing-image-manager:v1_20210422_patch1
        - longhornio/longhorn-manager:v1.1.3-head
        image: longhornio/longhorn-ui:v1.1.3-head
          image: longhornio/longhorn-manager:v1.1.3-head
          image: longhornio/longhorn-manager:v1.1.3-head
          - longhornio/longhorn-manager:v1.1.3-head
```

Backing Image created from yaml file won't crash the longhorn-manager anymore.
