### ISSUE TITLE
[BUG] The volume remain in attached state even if detach action is called on the volume which is in migration process and old engine node is powered down.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3401]
## Describe the bug
The volume remain in attached state even if detach action is called on the volume which is in migration process and old engine node is powered down.

## To Reproduce

Run the test case 8 with migration rollback scenario. https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/ha-volume-migration

1. Create a migratable volume :
    i. Deploy a migratable StorageClass. e.g., https://github.com/longhorn/longhorn/blob/master/examples/rwx/storageclass-migratable.yaml
    ii. Create a PVC with access mode ReadWriteMany via this StorageClass.
2. Attach a volume to a node and wait for volume running. Then write some data into the volume. Here I would recommend directly restoring a volume (set fromBackup in the StorageClass) and attach it instead.
3. Start the migration by request attaching to another node for the volume.
4. Power down the node which has the old engine. 
5. Detach the new node.
6. Observe the detach API returns 200 but the node doesn't get detached.

## Expected behavior
The node should be detached .

## Log or Support bundle

[longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-13T21-05-43Z.zip](https://github.com/longhorn/longhorn/files/7707252/longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-13T21-05-43Z.zip)
Volume name - pvc-6c9f10e1-7106-4270-b7cf-1d464be84fc1
Time stamp - around 2021-12-13 20:42:00

## Environment

 - Longhorn version: v1.2.3-rc2

## Additional context

https://github.com/longhorn/longhorn/issues/3206#issuecomment-991834156

**Comment by khushboo-rancher** [comment]
cc: @shuo-wu

**Comment by shuo-wu** [comment]
It seems that there is no way to clean up the extra/migration engine & replicas when detaching a degraded volume. Is this a regression?

**Comment by khushboo-rancher** [comment]
This test case was not tested before and power down case with a non-migrating volume is working as per https://longhorn.github.io/longhorn-tests/manual/pre-release/node/

So, in this case if node of old engine goes down and never coming up, the migrating volume can't be recovered?

**Comment by shuo-wu** [comment]
Probably. Unless there is a manual workaround involved.

**Comment by ejweber** [comment]
Flow analysis before fix:

Volume `pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0` is migrating from `eweber-v126-worker-9c1451b4-kgxdq` to `eweber-v126-worker-9c1451b4-6464j` when `eweber-v126-worker-9c1451b4-kgxdq` is powered down.

Before the VolumeAttachment to `eweber-v126-worker-9c1451b4-6464j` is deleted, the migration is stuck (which makes sense).

- `volume.Status.Robustness == unknown`, so `ProcessMigration` can do nothing.
- The volume can't be detached from `volume.Status.CurrentNodeID` because its resources can't be closed.

```
[longhorn-manager-6zdlv] time="2024-06-03T19:40:23Z" level=info msg="Instance manager state is updated from unknown to running after syncing with the pod" func="controller.(*InstanceManagerController).syncStatusWithPod.func1" file="instance_manager_controller.go:376" controller=longhorn-instance-manager instanceManager=instance-manager-699da83c0e9d22726e667344227e096b node=eweber-v126-worker-9c1451b4-6464j nodeID=eweber-v126-worker-9c1451b4-kgxdq
[longhorn-manager-6zdlv] time="2024-06-03T19:40:23Z" level=info msg="Updated the non-error instance manager to state unknown due to node down or deleted" func="controller.(*InstanceManagerController).syncStatusWithNode" file="instance_manager_controller.go:435" controller=longhorn-instance-manager instanceManager=instance-manager-699da83c0e9d22726e667344227e096b node=eweber-v126-worker-9c1451b4-kgxdq nodeID=eweber-v126-worker-9c1451b4-kgxdq
[longhorn-manager-6zdlv] time="2024-06-03T19:40:23Z" level=warning msg="Skip the migration processing since the volume current robustness is unknown" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3744" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationNodeID=eweber-v126-worker-9c1451b4-6464j node=eweber-v126-worker-9c1451b4-6464j owner=eweber-v126-worker-9c1451b4-6464j shareEndpoint= shareState= state=attached volume=pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
[longhorn-manager-6zdlv] time="2024-06-03T19:40:23Z" level=warning msg="Volume is attached but dependent resources are not opened" func="controller.(*VolumeController).reconcileAttachDetachStateMachine" file="volume_controller.go:1638" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v126-worker-9c1451b4-6464j owner=eweber-v126-worker-9c1451b4-6464j shareEndpoint= shareState= state=attached volume=pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
```

```
    migrationNodeID: eweber-v126-worker-9c1451b4-6464j
    nodeID: eweber-v126-worker-9c1451b4-kgxdq
    currentMigrationNodeID: eweber-v126-worker-9c1451b4-6464j
    currentNodeID: eweber-v126-worker-9c1451b4-kgxdq
    state: attached
    robustness: unknown
```

https://github.com/longhorn/longhorn-manager/blob/d887221e5b0f5f5a59b3307d10f5f66dcd0a85a5/controller/volume_controller.go#L3743-L3746

https://github.com/longhorn/longhorn-manager/blob/d887221e5b0f5f5a59b3307d10f5f66dcd0a85a5/controller/volume_controller.go#L1618-L1642

Once the VolumeAttachment to `eweber-v126-worker-9c1451b4-6464j` is deleted, the CSI plugin deletes the attachment ticket to `eweber-v126-worker-9c1451b4-6464j`.

```
 spec:
    attachmentTickets:
      csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73:
        generation: 0
        id: csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73
        nodeID: eweber-v126-worker-9c1451b4-kgxdq
        parameters:
          disableFrontend: "false"
          lastAttachedBy: ""
        type: csi-attacher
    volume: pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
  status:
    attachmentTicketStatuses:
      csi-8a312042b6f89686ec5be8c91d5eb2b8ce21d92e4ca4690117945258ce74de44:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-06-03T19:37:05Z"
          message: The migrating attachment ticket is satisfied
          reason: ""
          status: "True"
          type: Satisfied
        generation: 0
        id: csi-8a312042b6f89686ec5be8c91d5eb2b8ce21d92e4ca4690117945258ce74de44
        satisfied: true
      csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-06-03T19:36:50Z"
          message: ""
          reason: ""
          status: "True"
          type: Satisfied
        generation: 0
        id: csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73
        satisfied: true
```

Then, the volume attachment controller sets `volume.Spec.MigrationNodeID == ""` and cleans up the attachment ticket status.

```
    migrationNodeID: ""
    nodeID: eweber-v126-worker-9c1451b4-kgxdq
    currentMigrationNodeID: eweber-v126-worker-9c1451b4-6464j
    currentNodeID: eweber-v126-worker-9c1451b4-kgxdq
    state: attached
    robustness: unknown
```

```
  spec:
    attachmentTickets:
      csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73:
        generation: 0
        id: csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73
        nodeID: eweber-v126-worker-9c1451b4-kgxdq
        parameters:
          disableFrontend: "false"
          lastAttachedBy: ""
        type: csi-attacher
    volume: pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
  status:
    attachmentTicketStatuses:
      csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-06-03T19:36:50Z"
          message: ""
          reason: ""
          status: "True"
          type: Satisfied
        generation: 0
        id: csi-796ee5f577bde556f9941a7cbbd761a6e5d4e427e4aa0fd72e24c44a86bede73
        satisfied: true
```

Even though `volume.Spec.MigrationNodeID` is cleared, the migration is still stuck in the same place with the same logs.

```
[longhorn-manager-6zdlv] time="2024-06-03T19:41:53Z" level=warning msg="Skip the migration processing since the volume current robustness is unknown" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3744" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationNodeID= node=eweber-v126-worker-9c1451b4-6464j owner=eweber-v126-worker-9c1451b4-6464j shareEndpoint= shareState= state=attached volume=pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
[longhorn-manager-6zdlv] time="2024-06-03T19:41:53Z" level=warning msg="Volume is attached but dependent resources are not opened" func="controller.(*VolumeController).reconcileAttachDetachStateMachine" file="volume_controller.go:1638" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v126-worker-9c1451b4-6464j owner=eweber-v126-worker-9c1451b4-6464j shareEndpoint= shareState= state=attached volume=pvc-db06e8d0-b2bb-4f87-9f9d-891db3b5feb0
[longhorn-manager-6zdlv] time="2024-06-03T19:41:53Z" level=info msg="Instance manager state is updated from unknown to running after syncing with the pod" func="controller.(*InstanceManagerController).syncStatusWithPod.func1" file="instance_manager_controller.go:376" controller=longhorn-instance-manager instanceManager=instance-manager-699da83c0e9d22726e667344227e096b node=eweber-v126-worker-9c1451b4-6464j nodeID=eweber-v126-worker-9c1451b4-kgxdq
[longhorn-manager-6zdlv] time="2024-06-03T19:41:53Z" level=info msg="Updated the non-error instance manager to state unknown due to node down or deleted" func="controller.(*InstanceManagerController).syncStatusWithNode" file="instance_manager_controller.go:435" controller=longhorn-instance-manager instanceManager=instance-manager-699da83c0e9d22726e667344227e096b node=eweber-v126-worker-9c1451b4-kgxdq nodeID=eweber-v126-worker-9c1451b4-kgxdq
```

The situation can't resolve until the node comes back (if it does).
