### ISSUE TITLE
[BUG] The default access mode of a restored RWX volume is RWO

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3444]
## Describe the bug

It should be always the same as the access mode of the original volume

## To Reproduce

1. Create a RWX volume
2. Create a backup for the volume
3. Create a volume from the backup without changing any parameters during the restore
4. The access mode of the restore volume is RWO

## Expected behavior

The access mode of the restore volume should be RWX

## Environment

 - Longhorn version: v1.2.3

## Additional context

This issue is found when investigating https://github.com/longhorn/longhorn/issues/3367

**Comment by khushboo-rancher** [comment]
Similar issue - https://github.com/longhorn/longhorn/issues/2705

**Comment by weizhe0422** [comment]
I found it is because of the default value is `RWO` when trying to restore from backup if leave blank in access mode field. 

I think there are two items need to do:

1. Fill into the `access mode` filed which was come from creating back up.
2. Get the `access mode` value from the latest back up if the request payload is empty.

**Comment by weizhe0422** [comment]
I think the access mode value wasn't saved when create backup.

So, I think maybe we can get the access mode through the volume manager to get from data store like this

```golang
	if vol, err := volume_manager.Get(volumeName); err != nil {
		return nil, err
	} else {
		volAccessMode = vol.Spec.AccessMode
	}

```

WDYT

**Comment by shuo-wu** [comment]
Before the volume is restored to the cluster, there is no volume object hence `volume_manager.Get(volumeName)` always fails... The solution is what I mentioned, Longhorn needs to store the access mode in the labels

**Comment by c3y1huang** [comment]
>   #### Scenario 1
>   
>   1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX) * 1, and both are attached to one node.
>   2. Create backups for each volumes.
>   3. Wait all backups are complete, then delete all volumes.
>   4. Switch to `Backup' page, and click the backup name and the tags filed.
>   5. Select all backups and click `Restore Latest Backup` button without changing any parameters during the restore
>   6. Switch back to `Volume` page and click the name filed.
>   7. CHECK: The access mode should be same as the volume's backup.
>   
>   #### Scenario 2
>   
>   1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX) * 1, and both are attached to one node.
>   2. Create backups for each volumes.
>   3. Wait all backups are complete, then delete all volumes.
>   4. Switch to `Backup' page, and click the backup name and the tags filed.   5.1 Select `ReadWriteOnce`backup volumes and set the access mode as`ReadWriteMany` 5.2 Select`ReadWriteMany`backup volumes and set the access mode as`ReadWriteOnce`
>   5. Switch back to `Volume` page and click the name filed.
>   6. CHECK:
>      7.1 The `ReadWriteOnce` backup volumes  access mode should be `ReadWriteMany` volume
>      7.2 The `ReadWriteMany` backup volumes  access mode should be `ReadWriteOnce` volume

Suggest adding them to the automation e2e.

**Comment by innobead** [comment]
@weizhe0422 Moving back to implementation, because we need to backport this to 1.3.x and 1.2.x.

**Comment by innobead** [comment]
After discussing with @weizhe0422 , no need to backport to 1.2, because the mutation webhook is just introduced from 1.3 only.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220915**

- longhorn master-head ([bfe44af](https://github.com/longhorn/longhorn/commit/bfe44afdf880007c55bc6530f592e1b2562e7571)) 
- longhorn-share-manager [v1_20220914](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220914) ( [2cba526](https://github.com/longhorn/longhorn-share-manager/commit/2cba526a55368a7f5f263b204d87b39836855dff))

**The test steps**
***Scenario 1***
1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX)
`kubectl apply -f create_2vol_rwx+rwo.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
```
2. Volume attach to the pod. Deploy pod `mypod1`
`kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1      
```
3. Create backups for each volumes
4. Wait all backups are complete, then delete all volumes.
5. Switch to `Backup` page, and click the backup name and the tags filed.
6. Select all backups and click Restore Latest Backup button without changing any parameters during the restore
7. Switch back to Volume page and click the name filed.
8. CHECK: The access mode should be same as the volume's backup.

***Scenario 2***
1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX)
`kubectl apply -f create_2vol_rwx+rwo.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
```
2. Volume attach to the pod. Deploy pod `mypod1`
`kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1      
```
3. Wait all backups are complete, then delete all volumes.
4. Switch to `Backup` page, and click the backup name and the tags filed. 
5.1 Select `ReadWriteOnce` backup volumes and set the access mode as `ReadWriteMany` 
5.2 Select `ReadWriteMany` backup volumes and set the access mode as `ReadWriteOnce`
6. Switch back to Volume page and click the name filed.
7.1 The `ReadWriteOnce` backup volumes access mode should be `ReadWriteMany` volume
7.2 The `ReadWriteMany` backup volumes access mode should be `ReadWriteOnce` volume

**Result Passed**
