### ISSUE TITLE
[BUG] backupTarget / backupTargetCredentialSecret are never applied

### ISSUE THREAD

**Issue by EugenMayer** [longhorn/longhorn#3458]
Using this `values.yaml`

```yaml
defaultSettings:
  defaultReplicaCount: {replicas}
  backupTarget: "s3://longhorn@de/"
  backupTargetCredentialSecret: longhorn-minio-creds
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  allowNodeDrainWithLastHealthyReplica: true
persistence:
  defaultClassReplicaCount: ${replicas}
```

It seems like most setting are applied, but backupTarget / backupTargetCredentialSecret are never applied. Tested this with a change on an existing cluster or an a new cluster. With a new cluster, both values are empty, with an existing, the values never change.

Considering how critical both values are, I would mark this one as critical.

Hint: I'am using 1.2.3 and i'am fairly confident this was working with 1.2.2 - any changes to configuration management (configMap replaced with CR introducing a bug?)

## ENV

- RKE2 latest
- longhorn 1.2.3 (helm based installation)
