### ISSUE TITLE
[BUG] recurringJobSelector

### ISSUE THREAD

**Issue by qdupuy** [longhorn/longhorn#3482]
Hello,

How do you tell longhorn to automatically create tasks when they are not present?

```
recurringJobSelector:
        enable: true
        jobList: '[{"name":"b6am","task":"backup","cron":"0 6 * * *","retain":3},{"name":"b12pm","task":"backup","cron":"0 12 * * *","retain":2},{"name":"b6pm","task":"backup","cron":"0 18 * * *","retain":2}]'
My list is present but the tasks doesn’t exist
```

## Environment

 - Longhorn version : 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version : 1.22
   - Number of management node in the cluster : 1
   - Number of worker node in the cluster : 1

 - Node config
 
   - OS type and version: ubuntu 20.04 LTS
   - CPU per node: 4
   - Memory per node: 16
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal) : bare-metal
 - Number of Longhorn volumes in the cluster : 4

## Additional context

See https://rancher-users.slack.com/archives/CC2UQM49Y/p1639750876140300
