### ISSUE TITLE
[BUG] RecurringJob should validate retain field is <= 50 like the UI does

### ISSUE THREAD

**Issue by zcourts** [longhorn/longhorn#3493]
## Describe the bug

It is possible to create a recurring job with the retain field set to a number > 50.
The UI prevents this but using a k8s manifest does not. 
We recently had a misconfigured setup in an automated deployment pipeline which had over 10K for the retain field at a 5 min interval 😵‍💫.
By the time it was noticed all volumes had hundreds of snapshots.

Which lead to a different issue of longhorn becoming almost unresponsive, taking 10+ seconds for any action in the UI to complete i.e. all the HTTP requests to it were this slow. It had also stopped provisioning new volumes.
This is a separate side note but https://github.com/longhorn/longhorn/issues/1826 is needed...
I had to open a tab for each volume and run a script in the browser's console to delete all the snapshots and backups:

WARN: DO NOT just copy and paste it, will delete both backups and snapshots on the volume page indiscriminately. 
```
setInterval(function () { 
    $('.ant-tree li .ant-tree-node-content-wrapper .ant-dropdown-trigger').click(); 
    setTimeout(function () { 
        $('.lh-snapshot-dropdown .ant-dropdown-menu-item:nth-child(3)').click(); 
        $('.ant-tree li .ant-tree-node-content-wrapper .ant-dropdown-trigger').remove();
    }, 1000); 
}, 15000);
```
This eventually worked after several hours of slowly progressing. Once the first few snapshots were deleted longhorn started rebuilding 1 or 2 replicas in some but not all cases which then blocked all attempts to delete snapshots until the rebuild was done further exacerbating the system recovery time.

## To Reproduce

```yaml
      apiVersion: longhorn.io/v1beta1
      kind: RecurringJob
      metadata:
        name: snap 
        namespace: longhorn-system
      spec:
        cron: "0 */5 * * *"
        task: "snapshot"
        groups:
          - default
        retain: 15000 #This should cause it to fail?
        concurrency: 1
```

## Expected behaviour

1. Attempting to create this with kubectl apply or equivalent should fail.
2. There should be a way to delete all or N number of snapshots
3. Alternatively and ideally, if the retain field is changed to a smaller number then longhorn should delete any excess snapshot or backups (with maybe a minimum of 1 in case it is a misconfig not all backups are deleted)

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubespray
   - Number of management node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 32
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 27
