### ISSUE TITLE
[BUG] Backing Image `imageURL` become empty when Longhorn upgrading

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3510]
## Describe the bug

While Backing Image downloading in progress, perform upgrade the Longhorn.
The particular Backing Image will result in problem.

## To Reproduce

1. Install Longhorn v1.1.3 on a fresh cluster
2. Wait until all installation become ready
3. Create a large Backing Image (or control the network bandwidth)
4. Upgrading Longhorn to v1.2.3 while Backing Image downloading in progress
5. Check the Backing Image related pods

## Expected behavior

Backing Image downloading should resume and finish later.

## Log or Support bundle

Backing Image CR with empty URL:
`$ kubectl get backingimage/bi-test -n longhorn-system -o yaml`
```yaml
spec:
  checksum: ""
  disks:
    5d7282ce-c21e-4257-8707-3868187d8dea: {}
    6e00b3e5-460b-41ff-aba3-0670dcb5a20e: {}
    ba918fca-08c5-4a20-a365-d7ab8eedd64d: {}
  imageURL: ""
  sourceParameters:
    url: "" 
```
Also BI-manager says: “Backing Image Manager: failed to start fetching backing image”

## Environment

 - Longhorn version: v1.1.3 to v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm3
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.18.20+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes: 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): hyperkit VMs
 - Number of Longhorn volumes in the cluster: ~5

## Additional context
This is found in upgrading test.
