### ISSUE TITLE
[BUG] Engine Image, randomly readiness-probe process stuck using 1 core entirely

### ISSUE THREAD

**Issue by ghost** [longhorn/longhorn#3555]
## Describe the bug

A few weeks ago I recognized an issue with a process using 1 core of the host entirely. Using `htop` I was able to identify the process to be `sh -c ls /data/longhorn && /data/longhorn version --client-only` which is the readiness probe of the engine image according to the pod's manifest:

```
image: longhornio/longhorn-engine:v1.2.2                                                                                                                                                                           imagePullPolicy: IfNotPresent                                                                                                                                                                                      name: engine-image-ei-d4c780c6                                                                                                                                                                                     readinessProbe:                                                                                                                                                                                                      
  exec:                                                                                                                                                                                                                
    command:                                                                                                                                                                                                           
    - sh                                                                                                                                                                                                               
    - -c                                                                                                                                                                                                               
    - ls /data/longhorn && /data/longhorn version --client-only                                                                                                                                                      
  failureThreshold: 3                                                                                                                                                                                                
  initialDelaySeconds: 5                                                                                                                                                                                             
  periodSeconds: 5                                                                                                                                                                                                   
  successThreshold: 1                                                                                                                                                                                                
  timeoutSeconds: 4
```

I was not able to kill the process, just by rebooting the node I was able to get rid of it.
I observed this behavior for a few weeks now and it seems that this process randomly gets stuck on some nodes. At the moment on one node I have 3 of those processes running and taking 3 cores to 100%. It is very annoying to restart the nodes each time such a process pops up and gets stuck.

![image](https://user-images.githubusercontent.com/61096291/150216891-501ccfc2-11d4-4147-902d-caea39a9a8da.png)

## To Reproduce


As this issue occurs randomly I cannot really reproduce the issue. Additionally I cannot find anything in the logs.

## Expected behavior

The readiness probe process should execute and exit.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 21.10 arm64
   - CPU per node: 1 CPU, 4 Cores
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): USB 3 Flash
   - Network bandwidth between the nodes: 1 GBit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Raspberry Pi 4B 8GB
 - Number of Longhorn volumes in the cluster: 23

## Additional context

It would be interesting if someone else has the same issue and if it is probably a K3s/arm64/Raspberry Pi related issue.
