### ISSUE TITLE
[FEATURE] Btrfs fsType support

### ISSUE THREAD

**Issue by artur9010** [longhorn/longhorn#3588]
## Describe the solution you'd like

Add btrfs fsType support

## Describe alternatives you've considered

I tried to manually format volume as btrfs (attach, log in into node and do mkfs.btrfs on block device) but I got error that btrfs is not supported.

```
MountVolume.MountDevice failed for volume "pvc-34f34bc7-4b42-4fd3-a4b3-d34312beeeb0" : rpc error: code = Internal desc = Could not parse fs info on given filesystem format: btrfs. Supported fs types are: xfs, ext3, ext4
```

**Comment by derekbit** [comment]
Related to [[FEATURE] Support BTRFS](https://github.com/longhorn/longhorn/issues/2090)

**Comment by shuo-wu** [comment]
Close it due to duplication.

**Comment by rfx77** [comment]
The issue has been closed for the wrong reason. This issue and the related issue address a very different topic.

in this issue the question was if we could enable support for fsType btrfs as the fsType of a VOLUME and not the underlaying fs for /var/lib/longhorn.

This would be very usefull in combination with samba pods to enable the previous-versionsbfeature

**Comment by shuo-wu** [comment]
> in this issue the question was if we could enable support for fsType btrfs as the fsType of a VOLUME and not the underlaying fs for /var/lib/longhorn.

Oh you are right. Let me reopen it.

**Comment by derekbit** [comment]
no an issue because mount-utils is supporting btrfs.
https://github.com/longhorn/longhorn-manager/blob/master/vendor/k8s.io/mount-utils/resizefs_linux.go#L138-L151

**Comment by artur9010** [comment]
I don't think its fully supporting btrfs. I've created a storage class with btrfs fsType and tried to create a pvc. There are btrfs tools installed on the node.

```
E0128 21:41:42.658597       1 mount_linux.go:625] format of disk "/dev/longhorn/pvc-222ee761-30bd-4c27-bcd5-d9a332be230e" failed: type:("btrfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/e9c82a75efa188f7af73c7409b65feb2f291b027c38a35e1bc9053a1c67db3f1/globalmount") options:("defaults") errcode:(executable file not found in $PATH) output:() 
```

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-btrfs
parameters:
  dataEngine: v1
  fsType: btrfs
  numberOfReplicas: "3"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-btrfs
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
```
