### ISSUE TITLE
[BUG] pods waiting volume does not exist and no size was specified

### ISSUE THREAD

**Issue by chris93111** [longhorn/longhorn#3628]
## Describe the bug

Hi

Deployment of a postgres not start after reboot cluster, is waiting volume, in UI no error appear

in logs of longhorn-plugin:
```
time="2022-02-15T20:57:51Z" level=debug msg="volume pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf device /dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf contains filesystem of format "
time="2022-02-15T20:57:51Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf/globalmount"
time="2022-02-15T20:57:51Z" level=debug msg="mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf/globalmount try reading dir to make sure it's healthy"
I0215 20:57:51.994188 6283 mount_linux.go:366] Disk "/dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf]
E0215 20:57:52.004627 6283 mount_linux.go:372] format of disk "/dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
The file /dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf does not exist and no size was specified.
)
time="2022-02-15T20:57:52Z" level=error msg="NodeStageVolume: err: rpc error: code = Internal desc = format of disk \"/dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf\" failed: type:(\"ext4\") target:(\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf/globalmount\") options:(\"defaults\") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)\nThe file /dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf does not exist and no size was specified.\n) "
```

## Environment

k3s 3 nodes 1.22.5
longhorn 1.2.2

**Comment by shuo-wu** [comment]
Based on error message `mke2fs 1.45.5 (07-Jan-2020)\nThe file /dev/longhorn/pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf does not exist and no size was specified`, kubelet may wrongly consider the Longhorn volume as attached but actually No. Can you check the Longhorn volume status then?
You can get the detail by `kubectl -n longhorn-system get lhv pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf -oyaml`

**Comment by chris93111** [comment]
Hi @shuo-wu 

```
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  creationTimestamp: "2022-01-27T23:15:31Z"
  finalizers:
  - longhorn.io
  generation: 34
  labels:
    longhornvolume: pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf
    recurring-job-group.longhorn.io/default: enabled
  name: pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf
  namespace: longhorn-system
  resourceVersion: "378628709"
  uid: 192d1498-1117-41f6-9d56-47648a2a5855
spec:
  Standby: false
  accessMode: rwo
  backingImage: ""
  baseImage: ""
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: null
  encrypted: false
  engineImage: longhornio/longhorn-engine:v1.2.2
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: vldsocfg03-node-awx
  nodeSelector: null
  numberOfReplicas: 3
  replicaAutoBalance: ignored
  revisionCounterDisabled: false
  size: "8589934592"
  staleReplicaTimeout: 2880
status:
  actualSize: 313028608
  cloneStatus:
    snapshot: ""
    sourceVolume: ""
    state: ""
  conditions:
    restore:
      lastProbeTime: ""
      lastTransitionTime: "2022-01-27T23:15:32Z"
      message: ""
      reason: ""
      status: "False"
      type: restore
    scheduled:
      lastProbeTime: ""
      lastTransitionTime: "2022-02-15T19:55:59Z"
      message: ""
      reason: ""
      status: "True"
      type: scheduled
    toomanysnapshots:
      lastProbeTime: ""
      lastTransitionTime: "2022-01-27T23:15:32Z"
      message: ""
      reason: ""
      status: "False"
      type: toomanysnapshots
  currentImage: longhornio/longhorn-engine:v1.2.2
  currentNodeID: vldsocfg03-node-awx
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: awx
    pvName: pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf
    pvStatus: Bound
    pvcName: postgres-awx-postgres-0
    workloadsStatus:
    - podName: awx-postgres-0
      podStatus: Pending
      workloadName: awx-postgres
      workloadType: StatefulSet
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  ownerID: vldsocfg03-node-awx
  pendingNodeID: ""
  remountRequestedAt: "2022-02-15T21:01:06Z"
  restoreInitiated: false
  restoreRequired: false
  robustness: healthy
  shareEndpoint: ""
  shareState: ""
  state: attached
```

![image](https://user-images.githubusercontent.com/27526373/154697689-f4dd7d7f-e81b-4cf4-941b-33e1b2afe5c4.png)

**Comment by chris93111** [comment]
after another reboot of the cluster, many volume in the same state
timed out waiting for the condition
volume attachment is being deleted

```
time="2022-02-21T21:39:47Z" level=debug msg="Replica replenishment is delayed until 2022-02-21 21:43:12 +0000 UTC"
time="2022-02-21T21:40:14Z" level=debug msg="Failed replica pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-r-3a04064f will be reused during rebuilding" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=vldsocfg05-node-awx owner=vldsocfg05-node-awx state=attached volume=pvc-3cc9d3d2-ee4e-4169-865c-68313988c902
time="2022-02-21T21:40:15Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-e-80260d18\", UID:\"d485629c-033d-4254-a9e4-0b443aa58a9a\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"400825608\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilding' Start rebuilding replica pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-r-3a04064f with Address 10.42.7.92:10045 for normal engine pvc-3cc9d3d2-ee4e-4169-865c-68313988c902"
time="2022-02-21T21:40:16Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-e-80260d18\", UID:\"d485629c-033d-4254-a9e4-0b443aa58a9a\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"400825608\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilt' Replica pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-r-3a04064f with Address 10.42.7.92:10045 has been rebuilt for volume pvc-3cc9d3d2-ee4e-4169-865c-68313988c902"
time="2022-02-21T21:40:16Z" level=debug msg="Volume pvc-3cc9d3d2-ee4e-4169-865c-68313988c902 snapshot purge started"
time="2022-02-21T21:40:16Z" level=debug msg="Started snapshot purge for volume pvc-3cc9d3d2-ee4e-4169-865c-68313988c902 after rebuild is done"
time="2022-02-21T21:40:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-e-80260d18\", UID:\"d485629c-033d-4254-a9e4-0b443aa58a9a\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"400825608\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilt' Detected replica pvc-3cc9d3d2-ee4e-4169-865c-68313988c902-r-3a04064f (10.42.7.92:10045) has been rebuilt"
time="2022-02-21T21:40:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-3cc9d3d2-ee4e-4169-865c-68313988c902\", UID:\"61d8529c-794a-4b1f-9a58-6362011f37f6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"400798402\", FieldPath:\"\"}): type: 'Normal' reason: 'Healthy' volume pvc-3cc9d3d2-ee4e-4169-865c-68313988c902 became healthy"

time="2022-02-21T21:40:34Z" level=info msg="NodeUnpublishVolume: rsp: {}"
time="2022-02-21T21:40:38Z" level=info msg="NodeStageVolume: req: {\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"fromBackup\":\"\",\"fsType\":\"ext4\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"2880\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1643741991528-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-02e1b034-998b-4d1f-af92-e97399339bf7\"}"
time="2022-02-21T21:40:38Z" level=debug msg="volume pvc-02e1b034-998b-4d1f-af92-e97399339bf7 device /dev/longhorn/pvc-02e1b034-998b-4d1f-af92-e97399339bf7 contains filesystem of format ext4"
time="2022-02-21T21:40:38Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount"
time="2022-02-21T21:40:38Z" level=debug msg="mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount try reading dir to make sure it's healthy"
time="2022-02-21T21:40:38Z" level=debug msg="found existing healthy mount point for volume pvc-02e1b034-998b-4d1f-af92-e97399339bf7 skipping mount"
time="2022-02-21T21:40:38Z" level=info msg="mounted volume pvc-02e1b034-998b-4d1f-af92-e97399339bf7 on node vldsocfg02-node-awx via device /dev/longhorn/pvc-02e1b034-998b-4d1f-af92-e97399339bf7"
time="2022-02-21T21:40:38Z" level=info msg="NodeStageVolume: rsp: {}"
time="2022-02-21T21:40:39Z" level=info msg="NodePublishVolume: req: {\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount\",\"target_path\":\"/var/lib/kubelet/pods/6edc1061-5e17-491f-a67d-acc8eefb9cfa/volumes/kubernetes.io~csi/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"false\",\"csi.storage.k8s.io/pod.name\":\"galaxy-redis-replicas-0\",\"csi.storage.k8s.io/pod.namespace\":\"galaxy\",\"csi.storage.k8s.io/pod.uid\":\"6edc1061-5e17-491f-a67d-acc8eefb9cfa\",\"csi.storage.k8s.io/serviceAccount.name\":\"galaxy-redis\",\"fromBackup\":\"\",\"fsType\":\"ext4\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"2880\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1643741991528-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-02e1b034-998b-4d1f-af92-e97399339bf7\"}"
time="2022-02-21T21:40:39Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount"
time="2022-02-21T21:40:39Z" level=debug msg="mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/globalmount try reading dir to make sure it's healthy"
time="2022-02-21T21:40:39Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/pods/6edc1061-5e17-491f-a67d-acc8eefb9cfa/volumes/kubernetes.io~csi/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/mount"
time="2022-02-21T21:40:39Z" level=debug msg="mount point /var/lib/kubelet/pods/6edc1061-5e17-491f-a67d-acc8eefb9cfa/volumes/kubernetes.io~csi/pvc-02e1b034-998b-4d1f-af92-e97399339bf7/mount try reading dir to make sure it's healthy"
time="2022-02-21T21:40:39Z" level=debug msg="NodePublishVolume: found existing healthy mount point for volume pvc-02e1b034-998b-4d1f-af92-e97399339bf7 skipping mount"
time="2022-02-21T21:40:39Z" level=info msg="NodePublishVolume: rsp: {}"
```

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/27526373/155034592-3db89423-fc7b-4901-bf61-2e049d7eedcd.png">

**Comment by shuo-wu** [comment]
Weird... The log you just posted means that everything works fine. And in Longhorn's perspective, the volume `pvc-55ad4996-2b11-4f3f-9aad-805b8d0620bf` is attached successfully. Is the volume attached to the wrong node?

BTW, after reboot, all replicas on that nodes will crash. This is expected.

**Comment by chris93111** [comment]
@shuo-wu yes no error in logs but volume not mount in pods , is stay in pending and timeout for mount

**Comment by shuo-wu** [comment]
What's the spec node of the pending workload?

**Comment by chris93111** [comment]
@shuo-wu 
```

spec:
  restartPolicy: Always
  serviceAccountName: galaxy-redis
  priority: 0
  subdomain: galaxy-redis-headless
  schedulerName: default-scheduler
  enableServiceLinks: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: master
                app.kubernetes.io/instance: galaxy-redis
                app.kubernetes.io/name: redis
            namespaces:
              - galaxy
            topologyKey: kubernetes.io/hostname
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: vldsocfg01-node-awx
  securityContext:
    fsGroup: 1001
  containers:
    - resources: {}
      readinessProbe:
        exec:
          command:
            - sh
            - '-c'
            - /health/ping_readiness_local.sh 1
        initialDelaySeconds: 20
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      terminationMessagePath: /dev/termination-log
      name: redis
      command:
        - /bin/bash
      livenessProbe:
        exec:
          command:
            - sh
            - '-c'
            - /health/ping_liveness_local.sh 5
        initialDelaySeconds: 20
        timeoutSeconds: 6
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      securityContext:
        runAsUser: 1001
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: start-scripts
          mountPath: /opt/bitnami/scripts/start-scripts
        - name: health
          mountPath: /health
        - name: redis-data
          mountPath: /data
        - name: config
          mountPath: /opt/bitnami/redis/mounted-etc
        - name: redis-tmp-conf
          mountPath: /opt/bitnami/redis/etc/
        - name: tmp
          mountPath: /tmp
        - name: kube-api-access-qpw4k
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/bitnami/redis:6.2.6-debian-10-r103'
      args:
        - '-c'
        - /opt/bitnami/scripts/start-scripts/start-master.sh
  hostname: galaxy-redis-master-0
  serviceAccount: galaxy-redis
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-data-galaxy-redis-master-0
    - name: start-scripts
      configMap:
        name: galaxy-redis-scripts
        defaultMode: 493
    - name: health
      configMap:
        name: galaxy-redis-health
        defaultMode: 493
    - name: config
      configMap:
        name: galaxy-redis-configuration
        defaultMode: 420
    - name: redis-tmp-conf
      emptyDir: {}
    - name: tmp
      emptyDir: {}
    - name: kube-api-access-qpw4k
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  phase: Pending
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-21T21:35:22Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2022-02-21T21:35:22Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [redis]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2022-02-21T21:35:22Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [redis]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-21T21:35:22Z'
  hostIP: 10.X.X.X
  startTime: '2022-02-21T21:35:22Z'
  containerStatuses:
    - name: redis
      state:
        waiting:
          reason: ContainerCreating
      lastState: {}
      ready: false
      restartCount: 0
      image: 'docker.io/bitnami/redis:6.2.6-debian-10-r103'
      imageID: ''
      started: false
  qosClass: BestEffort
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  resourceVersion: '327223130'
  name: redis-data-galaxy-redis-master-0
  uid: 6b1a3c66-5b8e-4781-9c8c-975198f981cd
  creationTimestamp: '2022-02-04T18:01:15Z'
  managedFields:
    - manager: k3s
      operation: Update
      apiVersion: v1
      time: '2022-02-04T18:01:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
          'f:volumeName': {}
    - manager: k3s
      operation: Update
      apiVersion: v1
      time: '2022-02-04T18:01:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
      subresource: status
  namespace: galaxy
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: galaxy-redis
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd
  storageClassName: longhorn
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd
  uid: 15730df9-f402-4572-b512-e3db7bf4f726
  resourceVersion: '327223261'
  creationTimestamp: '2022-02-04T18:01:21Z'
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
  managedFields:
    - manager: csi-provisioner
      operation: Update
      apiVersion: v1
      time: '2022-02-04T18:01:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/provisioned-by': {}
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:claimRef': {}
          'f:csi':
            .: {}
            'f:driver': {}
            'f:fsType': {}
            'f:volumeAttributes':
              .: {}
              'f:fromBackup': {}
              'f:fsType': {}
              'f:numberOfReplicas': {}
              'f:staleReplicaTimeout': {}
              'f:storage.kubernetes.io/csiProvisionerIdentity': {}
            'f:volumeHandle': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
    - manager: k3s
      operation: Update
      apiVersion: v1
      time: '2022-02-04T18:01:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
    - manager: csi-attacher
      operation: Update
      apiVersion: v1
      time: '2022-02-04T18:01:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            'v:"external-attacher/driver-longhorn-io"': {}
spec:
  capacity:
    storage: 8Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd
    fsType: ext4
    volumeAttributes:
      fromBackup: ''
      fsType: ext4
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
      storage.kubernetes.io/csiProvisionerIdentity: 1643741991528-8081-driver.longhorn.io
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: galaxy
    name: redis-data-galaxy-redis-master-0
    uid: 6b1a3c66-5b8e-4781-9c8c-975198f981cd
    apiVersion: v1
    resourceVersion: '327222673'
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
status:
  phase: Bound
---
csi-plugin
time="2022-02-21T21:37:19Z" level=info msg="Listening for connections on address: &net.UnixAddr{Name:\"//csi/csi.sock\", Net:\"unix\"}"
time="2022-02-21T21:37:19Z" level=info msg="GetPluginInfo: req: {}"
time="2022-02-21T21:37:19Z" level=info msg="GetPluginInfo: rsp: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.2.2\"}"
time="2022-02-21T21:37:52Z" level=info msg="NodeGetInfo: req: {}"
time="2022-02-21T21:37:52Z" level=info msg="NodeGetInfo: rsp: {\"node_id\":\"vldsocfg01-node-awx\"}"

manager on node 01
2022/02/21 21:30:40 proto: duplicate proto type registered: VersionResponse
time="2022-02-21T21:30:40Z" level=info msg="Start overwriting built-in settings with customized values"
W0221 21:30:40.983267       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-02-21T21:30:40Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0221 21:30:40.994794       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0221 21:30:41.013601       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-02-21T21:30:41Z" level=info msg="Start upgrading"
time="2022-02-21T21:30:41Z" level=info msg="No API version upgrade is needed"
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Starting storageClass recurring job translation" namespace=longhorn-system translate=storage-class-recurring-jobs
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Finished storageClass recurring job translation" namespace=longhorn-system translate=storage-class-recurring-jobs
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Starting volume recurring job translation" namespace=longhorn-system translate=volume-recurring-jobs
time="2022-02-21T21:30:41Z" level=debug msg="upgrade from v1.1.0 to v1.2.0: Found 0 recurring job" action=create-recurringJob-CRs namespace=longhorn-system translate=volume-recurring-jobs
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Finished volume recurring job translation" namespace=longhorn-system translate=volume-recurring-jobs
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Starting volume cron job cleanup" action=cleanup-applied-volume-cron-jobs namespace=longhorn-system
time="2022-02-21T21:30:41Z" level=debug msg="upgrade from v1.1.0 to v1.2.0: Listing all cron jobs for volume pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd" action=cleanup-applied-volume-cron-jobs namespace=longhorn-system
time="2022-02-21T21:30:41Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Deleted 0 cronjob job for pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd volume" action=cleanup-applied-volume-cron-jobs namespace=longhorn-system
time="2022-02-21T21:30:49Z" level=debug msg="Replica controller picked up" controller=longhorn-replica controllerID=vldsocfg01-node-awx dataPath= node=vldsocfg01-node-awx nodeID=vldsocfg01-node-awx ownerID=vldsocfg04-node-awx replica=pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c
time="2022-02-21T21:34:53Z" level=debug msg="Prepare to create instance pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c"
time="2022-02-21T21:34:53Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c\", UID:\"c622538a-7b7f-46dd-8b6b-5439adb54894\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"400804983\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c"
time="2022-02-21T21:34:54Z" level=debug msg="Instance pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c starts running, IP 10.42.4.234"
time="2022-02-21T21:34:54Z" level=debug msg="Instance pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c starts running, Port 10045"
time="2022-02-21T21:34:54Z" level=debug msg="Instance handler updated instance pvc-6b1a3c66-5b8e-4781-9c8c-975198f981cd-r-da313a5c state, old state stopped, new state running"
```
