### ISSUE TITLE
[IMPROVEMENT] Consolidate volume attach/detach implementation

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3715]
## Is your improvement request related to a feature? Please describe

There are several cases related to (auto) volume attach/detach, right now we leverage the volume attributes to achieve that, but it's better to introduce a new resource (longhorn volumeattachement) to have complete context for each scenario. 

## Describe the solution you'd like

This is an idea from https://github.com/longhorn/longhorn/issues/2527#issuecomment-951901533

## Describe alternatives you've considered

N/A

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1037#issuecomment-1061642104
https://github.com/longhorn/longhorn/issues/2527

cc @shuo-wu @c3y1huang @PhanLe1010 @joshimoo 

Sub-issues:
- [x] https://github.com/longhorn/longhorn/issues/3692
- [x] Refactor auto attachment for recurring job
- [x] https://github.com/longhorn/longhorn/issues/3726
- [x] Refactoring auto attachment when volume is detach unexpectedly. This is a part of the ticket https://github.com/longhorn/longhorn/issues/2527#issuecomment-966597537

**Comment by joshimoo** [comment]
Here is an old PR where I explored the VA refactoring, this wasn't using a dedicated VA crd instead there was dedicated controllers per operation that would be managing desired attachment via setting `v.spec.NodeID` 

while the controller was utilizing `v.status.NodeID` to inform about attachment, there is some refactoring in there that should be applied to the volume controller indepedent of using a VA object. 

-------------

Have a look at the commit messages to see where I was going with this. Some of these have already been applied over time.
Like the csi driver having less and less logic instead having the attach call on the api making the decisions and checking all conditions.

- https://github.com/longhorn/longhorn-manager/pull/857/commits/22eff5d593d49bdc32e43a5852563114da9e95d9
- https://github.com/longhorn/longhorn-manager/pull/857/commits/8926c040e8dd8381ccfb10a05b7d87464d4268d0

-------------

This is the main part of the internal controller change:
- https://github.com/longhorn/longhorn-manager/pull/857/commits/2ac48fd936ee65fd4d9b37d445f76e698319e3a4

-------------

Using a dedicated VA resource to determine attachment seems reasonable, but we would need to think about it whether we want to have it per Node/User and we also need to consider reference counting for the VA, so that a system initiated action can also use the VA and not get cleaned up / clean up a user initiated action.

**Comment by PhanLe1010** [comment]
Adding @joshimoo as assignee as we are  co-working on this ticket

**Comment by PhanLe1010** [comment]
### TODO list for part-2 PR

- [ ]  UI modification to work with new AD mechanism (Longhorn UI -> Longhorn API)
- [ ] Fix unit test of AD and volume controller
- [ ] Consider how to upgrade from the previous Longhorn version which doesn't have VA resource yet 
    - [ ] Upgrade path for the new field `volume.Status.CurrentMigrationNodeID`
- [ ] Implement interrupt mechanism for higher priority attachment ticket
- [ ] Attachment creation and deletion functions are implemented in some controllers. We can probably make it reused by different controllers
- [ ] Test live migration on Harvester deployment 
- [ ] TODO: hadndle cases in which NodeID is empty. Should we detach the volume from all nodes???
- [ ] `func (m *VolumeManager) CreateSnapshotCR` is checking condition before creating the snapshot CR, perhaps this should be handle by webhook

**Comment by PhanLe1010** [comment]
# Test Plan
(In progress...)

## Attachment interruption
1. Create a 20GB PVC using `longhorn` StorageClass. Create a test deployment of 1 pod using the PVC.
2. Exec into the workload pod. Write 6GB of data into the volume's mount point using `dd`. Calculate the checksum of the new file.
3. Note down the `volume.status.ownerID`. Lets say it is `node-1`
4. Scale down the test deployment to detach volume. Edit the deployment YAML so that it will deploy pod on `node-2` when we scale up later.
5. Follow the instruction [here](https://longhorn.io/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup/) to create a CSI snapshot of type backup. Wait for the Longhorn backup to start.
6. Note that the backup controller creates a `backup-controller-xxx` ticket in the VolumeAttachment object of the volume (`kubectl get volumeattachments.longhorn.io -n longhorn-system <VOLUME-NAME>`). The ticket has `nodeID` set to `node-1`
7. While the backup is in-progress, scale up the test deployment.
8. Verify that:
    1. There is an `csi-attacher-xxx` ticket created for the workload pod inside Longhorn VolumeAttachment object. This ticket has `nodeID` set to `node-2`
    2. The `csi-attacher-xxx` ticket interrupt the `backup-controller-xxx`  so that workload pod doesn't have to wait for the backup to finish 
    3. Workload pod is able to start on `node-2`
    4. The in-progress backup failed
    5. The checksum of data matches the calculation above

**Comment by PhanLe1010** [comment]
## Test Upgrade 

### CSI flow

### Live migration
1. Deploy Longhorn older version v1.4.x
1. Create storageclass, PVC, and workload pod-1 as below
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-migratable
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      migratable: "true"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Block
      storageClassName: longhorn-migratable
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-1
      namespace: default
    spec:
      nodeName: <NODE-1>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into pod-1. Write some data `dd if=/dev/urandom of=dev/longhorn/testblk bs=1M count=100`. Caculate checksum `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`
1. Upgrade Longhorn to master-head
1. Deploy workload pod-2 to trigger live migration of volume to new node, NODE-2
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-2
      namespace: default
    spec:
      nodeName: <NODE-2>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Observe that volume engine is available on node-2. Volume is NOT detach during this process
1. Delete pod-1.
1. Observe that volume detached from node-1 but still attaching to node-2 throughout the whole process.
1. Exec into pod-2 and verify checksum matches `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`

### Auto attachment
