### ISSUE TITLE
[IMPROVEMENT] Auto-attach volume for K8s CSI snapshot

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3726]
## Is your improvement request related to a feature? Please describe

Currently, the user can only takes/restores CSI snapshot when the target volume is attached.
We want to support taking/restoring CSI snapshots when the target volume is detached. 
In order to do this, Longhorn needs to auto attach the target volume.

## Additional context

We were thinking about doing auto attachment/detachment inside the Longhorn CSI plugin but at the end decided to wait for the refactoring https://github.com/longhorn/longhorn/issues/3715

**Comment by innobead** [comment]
Removing this from 1.4.0, because it will depend on the progress of https://github.com/longhorn/longhorn/issues/3715.

**Comment by innobead** [comment]
This needs more testing, so decide to move to 1.5 instead of 1.4.x.

**Comment by PhanLe1010** [comment]
## Test Plan:

1. Install the prerequisite at https://longhorn.io/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
1. Deploy 2 VolumeSnapshotClass:
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-backup
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: bak
    ```   
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-snapshot
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: snap
    ```
1. Create Longhorn volume `test-vol` of 5GB. Create PV/PVC for the Longhorn volume.
1. Create a workload that uses the volume. Write some data to the volume.
   Make sure data persist to the volume by running `sync`
1. Set up a backup target for Longhorn

#### Scenarios 1: CreateSnapshot
  * `type` is `bak`
    
    * Create a VolumeSnapshot with the following yaml
      ```yaml
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshot
      metadata:
        name: test-snapshot-longhorn-backup
      spec:
        volumeSnapshotClassName: longhorn-backup
        source:
          persistentVolumeClaimName: test-vol
      ```
    * Scale down the workload to detach the volume
    * Verify that the volume is auto-attached and a backup is created.
    * Delete the `test-snapshot-longhorn-backup`
    * Verify that the backup is deleted
  * `type` is `snap`
    * volume is in detached state. 
      * Scale down the workload of `test-vol` to detach the volume.
      * Create `test-snapshot-longhorn-snapshot-1` VolumeSnapshot with `volumeSnapshotClassName: longhorn-snapshot`.
      * Verify that `test-vol`  is auto-attached and a Longhorn snapshot is created for the `test-vol`.
    * volume is in attached state. 
      * Scale up the workload to attach `test-vol`
      *  Create `test-snapshot-longhorn-snapshot-2` VolumeSnapshot with `volumeSnapshotClassName: longhorn-snapshot`.
      * Verify that a Longhorn snapshot is created for the `test-vol`.

#### Scenarios 2: Create new volume from CSI snapshot
   * Scale down the workload to detach the `test-vol`
  * From `longhorn-backup` type
    * Create a new PVC with the flowing yaml:
      ```yaml
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-restore-pvc
      spec:
        storageClassName: longhorn
        dataSource:
          name: test-snapshot-longhorn-backup
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      ```
    * Attach the PVC `test-restore-pvc` and verify the data 
    * Delete the PVC
  * From `longhorn-snapshot` type
    * Source volume is attached && Longhorn snapshot exist
        * Create a PVC with the following yaml:
          ```yaml
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: test-restore-pvc
          spec:
            storageClassName: longhorn
            dataSource:
              name: test-snapshot-longhorn-snapshot
              kind: VolumeSnapshot
              apiGroup: snapshot.storage.k8s.io
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
          ```
        * Attach the PVC `test-restore-pvc` and verify the data 
        * Delete the PVC
  
#### Scenarios 3: Delete CSI snapshot
  * `bak` type
    * Done in the above step
  * `snap` type
    * volume is attached && snapshot doesn’t exist
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot` and verify that the VolumeSnapshot is deleted.
    * volume is attached && snapshot exist
      * Recreate the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Verify the creation of Longhorn snapshot with the name in the field `VolumeSnapshotContent.snapshotHandle`
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot` 
      * Verify that Longhorn snapshot is removed or marked as removed
      * Verify that the VolumeSnapshot `test-snapshot-longhorn-snapshot` is deleted.
    * volume is detached
      * Recreate the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Scale down the workload to detach `test-vol`
      * Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot`
      * Verify that VolumeSnapshot `test-snapshot-longhorn-snapshot` is stuck in deleting

#### Scenarios 4: Concurrent backup creation & deletion
  * From https://longhorn.github.io/longhorn-tests/manual/pre-release/backup-and-restore/concurrent-backup-creation-deletion/
  * `` and `bak` type
    * Use volume test-vol previous created
    * Connect to node via ssh and issue dd if=/dev/urandom of=/dev/longhorn/dak status=progress
    * Wait for a bunch of data to be written (1GB)
    * take a backup(1) by 
    ```yaml
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshot
      metadata:
        name: test-snapshot-longhorn-backup1
      spec:
        volumeSnapshotClassName: longhorn-backup-1
        source:
          persistentVolumeClaimName: test-vol
      ```
    * wait for a bunch of data to be written (1GB)
    * take a backup(2) by 
    ```yaml
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshot
      metadata:
        name: test-snapshot-longhorn-backup2
      spec:
        volumeSnapshotClassName: longhorn-backup-1
        source:
          persistentVolumeClaimName: test-vol
      ```
    * immediately request deletion of backup(1)
    * verify that backup(2) completes successfully.
    * verify that backup(1) has not been deleted.
    * verify that all blocks mentioned in the backup(2).cfg file are present in the blocks directory.
    * delete backup(1)
    * verify that backup(1) has been deleted.
    * Repeat previous use 'volumeSnapshotClassName: longhorn-backup-2' (bak)

**Comment by weizhe0422** [comment]
## Validation is in progress, will continue to update the results in this comment.

Test steps (refer to https://github.com/longhorn/longhorn/issues/3726#issuecomment-1571038314)

**Preparation**
 1. Enable CSI Snapshot Support on a Cluster: https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
 2. Deploy 2 VolumeSnapshotClass
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1
    metadata:
      name: longhorn-backup
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: bak
    ---
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1
    metadata:
      name: longhorn-snapshot
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: snap
    ```
    ![image](https://github.com/longhorn/longhorn/assets/17548901/810514cb-fe82-45f7-8c1d-9d84577ff102)
 3. Create a 10Gi volume with PVC/PV, and also writing 2Gi data into the mount point.
    ![image](https://github.com/longhorn/longhorn/assets/17548901/9f4c42ec-681d-406f-a241-d4c6fd59d05b)

**Scenarios 1: CreateSnapshot**
 - `type` is `bak`
   1. create VolumeSnapshot for the Longhorn volume
      ```yaml
      apiVersion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshot
      metadata:
        name: test-snapshot-longhorn-backup
      spec:
        volumeSnapshotClassName: longhorn-backup
        source:
          persistentVolumeClaimName: longhorn-volv-pvc-4
      ```
      ![image](https://github.com/longhorn/longhorn/assets/17548901/d5ef55c1-b35c-4612-9da1-e0da0f9bcfee)
   2. delete the POD
      - check the Longhorn volume becomes `Detached`   
        ![image](https://github.com/longhorn/longhorn/assets/17548901/162db8b1-a1a2-4ae8-b9f1-f45014dfeafc)
      - check the backupvolume and backup are created successfully
        ![image](https://github.com/longhorn/longhorn/assets/17548901/ba414b8a-e555-46e3-bc36-204802f82913)
   3. Delete the test-snapshot-longhorn-backup
      ![image](https://github.com/longhorn/longhorn/assets/17548901/9f745a3d-bf99-4991-91f1-4f9e567e141b)
      - check the backup is gone
        ![image](https://github.com/longhorn/longhorn/assets/17548901/9e9a40fe-7533-4928-b7b7-0a2c3562ad61)
 - `type` is `snap`
