### ISSUE TITLE
[BUG] Attached volumes on disabled nodes.

### ISSUE THREAD

**Issue by AzuladoToujours** [longhorn/longhorn#3761]
## Describe the bug
I've been doing some tests on Longhorn volumes to see his resiliency with my cluster setup.
Right now I have 3 nodes dedicated to storage and 3 other nodes dedicated only to workload. From the very installation of Longhorn, I checked the box of [**_Create Default Disk on Labeled Nodes_**](https://longhorn.io/docs/1.2.3/references/settings/#create-default-disk-on-labeled-nodes) and only labeled those nodes intended to storage with the label _**node.longhorn.io/create-default-disk=true**_, even in the Longhorn UI I marked the option of _Disabled_ and _Eviction_ in every node intended to workload.
The problem is whenever I kill a storage node, in some cases, the volume gets attached to one of the disabled nodes. 
Is this normal to happen? It's a bug? 

## To Reproduce

1. Have 3 nodes intended for storage (in order for data replication) and x nodes for the workload.
2. Disable the workload nodes in the UI.
3. Create a volume and see that the volume gets attached successfully to any of the storage nodes.
4. Procced to kill a storage node,  the volume gets degraded.
5. The volume gets attached to a disabled node.

## Expected behavior

The volume gets attached **only to another storage node**.

## Environment

 - Longhorn version: v1.2.3 **AND** v1.2.4 (I installed the v1.2.4 too to see if the issue was already fixed, based on the [response](https://github.com/longhorn/longhorn/issues/3454#issuecomment-1022848380) of the issue [3454](https://github.com/longhorn/longhorn/issues/3454))
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): v1.2.3 Rancher Catalog App - v1.2.4 Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of worker node in the cluster: 6 Workers (3 inteded for workload and 3 inteded for storage)
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 4CPU Storage, 8CPU Workload.
   - Memory per node: 500GB Storage, 50GB Workload.
   - Disk type(e.g. SSD/NVMe): NVMe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare / Baremetal
 - Number of Longhorn volumes in the cluster: 2

## Additional context

Even though I've checked that if the volume gets attached to a workload node, it really doesn't store anything in the **_/var/lib/longhorn/replicas_** of the workload node, it appears strange to me that the volume can get attached to the workload node even if I explicitly said no.

**Comment by kaxing** [comment]
Did a quick check with v1.2.4 and `lhs/create-default-disk-labeled-nodes` set to `"true"`:
Volumes will be attached to wherever the workload is arranged by the K8s. But only those worker nodes with `node.longhorn.io/create-default-disk=true` label, will have the disk to preserve the volume replicas:
![image](https://user-images.githubusercontent.com/602540/159437760-12973d38-e348-4c91-9885-03fbf99b1626.png)

To ask k8s to attach workload to the same storage worker node(s), here is an example from a statefulset:
```yaml
spec:
  serviceName: nginx
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.longhorn.io/create-default-disk
                operator: In
                values:
                - "true"
      containers:
```
Extended check with the setting "Replica Node Level Soft Anti-Affinity" enabled, the replicas will be only created amount those with create-default-disk=true label.
