### ISSUE TITLE
[BUG] HashiCorp Vault and Apache Pulse do not work with Longhorn

### ISSUE THREAD

**Issue by GeroL** [longhorn/longhorn#3766]
## Describe the bug

After some hours the volumes become read-only and do not recover anymore rendering the Vault or Pulse deployment useless
even if there is no usage of these deployments-
The have to be deleted and initialized completely new.

## To Reproduce

1. Deploy Vault or Pulse
2. Use this storageclass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-vault
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  dataLocality: "best-effort" 
  replicaAutoBalance: "best-effort" 
  fsType: "ext4"
```
3.  Init Vault with:
`microk8s kubectl exec -ti vault-0 -n vault -- vault operator init` 
4. Note the root login token
5. Login with
`microk8s kubectl exec -ti vault-0 -n vault -- vault login [token]`
6. Init vault with
    - `microk8s kubectl exec -ti vault-1 -n vault -- vault operator raft join http://vault-0.vault-internal:8200`
    - `microk8s kubectl exec -ti vault-0 -n vault -- vault secrets enable -path=internal kv`
    - `microk8s kubectl exec -ti vault-0 -n vault -- vault auth enable kubernetes`
    - ```bash
      microk8s kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/config \
         kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
         kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
         disable_iss_validation=true \
         disable_local_ca_jwt=true
      ```
    - ```bash
      EOFmicrok8s kubectl exec -ti vault-0 -n vault -- vault policy write internal-app-policy - <<EOF
      path "internal/database/connectionstrings" {
        capabilities = ["read", "list"]
      }

      EOF
      ```
    - ```bash
      microk8s kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/internal-app-role \
          bound_service_account_names=* \
          bound_service_account_namespaces=* \
          policies=internal-app-policy \
          ttl=24h 
      ```

## Expected behavior

Vault should be up and running at least without any usage.
Preferable also while in heavy use.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: microk8s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: Between 4 and 16
   - Memory per node: Between 16GB and 64 GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 2.5GBit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 5

## Additional context
Longhorn almost never crashed for my self developed applications with use deploymentsets
Vault and Pulsar use StatefulSets.
