### ISSUE TITLE
[BUG] pod status is running, pvc status is Terminating. pod can read and wirte

### ISSUE THREAD

**Issue by Nedved-liao** [longhorn/longhorn#3771]
## Describe the bug

i create a statefulset use longhorn, the pvc status is Bound when pod creating. After the POD is created, the PVC state becomes Terminating
But this issue does not exist in all statefulset.

## statefulset yaml
<details>
<summary> statefulset yaml</summary>

```yaml
kind: StatefulSet
metadata:
  annotations:
    cloudlink-cmp/description: ''
  name: mongodb
  namespace: prod-mongo
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-hs
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - MEM=$(echo ${MAX_MEMORY} | awk '{print ($1-1024*1024*1024)/(2*1024*1024*1024)}');
          MEM=$(echo ${MEM} | awk '{if($1 < 0.256){print 0.256} else {print $1}}');
          mkdir -p /data/db/$HOSTNAME; chmod 777 -R /data; echo $MONGO_KEY_FILE_TXT
          > /home/key_file; chown 999 /home/key_file; chmod 400 /home/key_file; sleep
          10; docker-entrypoint.sh mongod --wiredTigerCacheSizeGB ${MEM} --replSet
          rs0 --dbpath /data/db/$HOSTNAME --keyFile /home/key_file;
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_KEY_FILE_TXT
          value: bW9uZ29kYgo=
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Mongo123
        - name: MAX_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: mongodb
              resource: limits.memory
        image: 10.10.0.253/public/mongo:4.2.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: '3'
          initialDelaySeconds: '40'
          periodSeconds: '10'
          tcpSocket:
            port: 27017
          timeoutSeconds: '5'
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - tmp_dir=$(mktemp -d -p /data/db/$HOSTNAME); rmdir ${tmp_dir}; mongo
              127.0.0.1:27017/admin --eval="quit()";
          failureThreshold: '3'
          initialDelaySeconds: '40'
          periodSeconds: '10'
          successThreshold: '1'
          timeoutSeconds: '5'
        resources:
          limits:
            memory: 2Gi
            cpu: '1'
          requests:
            memory: 1Gi
            cpu: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: longhorn
          readOnly: false
          subPath: ''
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: longhorn
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        limits:
          storage: 500Gi
        requests:
          storage: 500Gi
      storageClassName: longhorn
```

</details>

![image](https://user-images.githubusercontent.com/35453327/159618815-439828c3-7551-4977-8986-dacee9b92fed.png)

## Environment

 - Longhorn version: v1.2.4
 - Installation method ：helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.18
   - Number of management node in the cluster: 26
   - Number of worker node in the cluster: 26
 - Node config
   - OS type and version: redhat7.8
   - CPU per node: Arm64V8
   - Memory per node: 32G
   - Disk type(e.g. SSD/NVMe) : SSD
