### ISSUE TITLE
[BUG] Volumens can't be attached anymore

### ISSUE THREAD

**Issue by floriandrott** [longhorn/longhorn#3798]
## Describe the bug

Longhorn was running fine the last weeks. Since two days all the volumes can't be attached anymore. The volumes are attaching and deattaching in a loop. -> Rancher can't use the volumes anymore for the pods.

## To Reproduce

1. No direct steps ... unfortunately. 
2. Using Rancher (v2.6.3) with k3s with Longhorn (v1.2.3)

## Expected behavior

Volumens can be attached to the Rancher pods.

## Log or Support bundle

[longhorn-support-bundle_598b3b59-09b8-4494-b9d1-1d3d4f353462_2022-03-29T08-58-49Z.zip](https://github.com/longhorn/longhorn/files/8369733/longhorn-support-bundle_598b3b59-09b8-4494-b9d1-1d3d4f353462_2022-03-29T08-58-49Z.zip)

## Environment

 - Longhorn version: v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node: 16
   - Memory per node: 64GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 23

## Additional context

I'm not sure what happened to be honest. Everything was working perfectly. Now the volumes are not attaching.

**Comment by PhanLe1010** [comment]
Can you provide the volume name which is stuck in detaching/attaching?

**Comment by floriandrott** [comment]
@PhanLe1010 yes, all volumes are affected. I though it easier to find the issue if not so much deployments are running. Therefore I scaled down the deployments in Rancher which are using 4 volumes. Now only these 4 volumes are in the loop of attaching and de-attaching. The rest is idle because the deployments are scaled to 0.

**Comment by PhanLe1010** [comment]
Okay, this cluster only has 1 node. But the instance manager r is in not ready state:
```
  status:
    phase: Failed
    conditions:
    - type: Initialized
      status: "True"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2022-03-13T13:05:49Z"
      reason: ""
      message: ""
    - type: Ready
      status: "False"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2022-03-28T04:32:12Z"
      reason: ContainersNotReady
      message: 'containers with unready status: [replica-manager]'
    - type: ContainersReady
      status: "False"
      lastprobetime: "0001-01-01T00:00:00Z"
      lasttransitiontime: "2022-03-28T04:32:12Z"
      reason: ContainersNotReady
      message: 'containers with unready status: [replica-manager]'
```

It means Kubelet might have killed the instance manager r because of resources pressure. I can see the ready condition was fliped around `2022-03-29T08:25:06`:
```
      Ready:
        type: Ready
        status: "True"
        lastprobetime: ""
        lasttransitiontime: "2022-03-29T08:25:06Z"
        reason: ""
        message: Node v2202112162120172526 is ready
```


Actions:

* Get the instance-manager-r-xxx pod to running state (by cleanup some resources?)
* Since you only have 1 node, set the csi deployment scale to 1: https://github.com/longhorn/longhorn/blob/bd3655b122e72bad0653783d8edfdada9a50cdab/chart/values.yaml#L74-L77
* Set the volume replica count to 1: https://longhorn.io/docs/0.8.0/users-guide/volume/#changing-replica-count-of-the-volumes
