### ISSUE TITLE
[BUG] Volumes not being scheduled with taints

### ISSUE THREAD

**Issue by Thijmen** [longhorn/longhorn#3818]
## Describe the bug
I have a RKE cluster and have 3 nodes in my cluster with this taint:
`nodetype=storage:NoSchedule`

By setting this up, I only want storage being run on these nodes, no other workloads. 

I followed the documentation on https://longhorn.io/docs/1.2.4/advanced-resources/deploy/taint-toleration/ .

I installed Longhorn via the Marketplace in Rancher.

## To Reproduce

1. Have 3 nodes in your cluster with `nodetype=storage:NoSchedule`
2. Install Longhorn in Rancher via the Marketplace.
2.1 Leave everything (yaml) default, except:
```
defaultSettings:
  taintToleration: nodetype=storage:NoSchedule
longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: nodetype
      operator: Equal
      value: storage
longhornManager:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: nodetype
      operator: Equal
      value: storage
longhornUI:
  nodeSelector: {}
  priorityClass: null
  tolerations:
    - effect: NoSchedule
      key: nodetype
      operator: Equal
      value: storage
```
4. Create a basic volume

## Expected behavior

Volume gets healthy. Currently, it is not: 
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/383903/161561132-8be32869-a50b-420d-9e26-e3cb41d4693d.png">

## Log or Support bundle
[longhorn-support-bundle_5dc9d524-c454-4887-987c-578b72175d85_2022-04-04T14-05-40Z.zip](https://github.com/longhorn/longhorn/files/8410340/longhorn-support-bundle_5dc9d524-c454-4887-987c-578b72175d85_2022-04-04T14-05-40Z.zip)

## Environment

 - Longhorn version: v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3 (and 3 storage nodes, so 6 in total)
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Unlimited (same physical host)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 1
