### ISSUE TITLE
[FEATURE] Make Longhorn UI Listen Binding configurable

### ISSUE THREAD

**Issue by li3** [longhorn/longhorn#3829]
## Is your feature request related to a problem? Please describe

Longhorn UI does not provide an out of the box authentication method. As an administrative tool, this must be secured in some way.

One way is to provide authentication via an Ingress rule as outlined in the [documentation](https://longhorn.io/docs/1.2.4/deploy/accessing-the-ui/longhorn-ingress/). However any pod within the network can still directly access Longhorn UI either via the Service or Pod IP + `8000` port.

Another way to handle authentication is via a sidecar like: https://github.com/oauth2-proxy/oauth2-proxy

However, even with this side car in place, since Longhorn UI binds [0.0.0.0:8000](https://github.com/longhorn/longhorn-ui/blob/eecabc09b59f03750a53815251c48f10c96707c6/nginx.conf.template#L12) by default the UI can still be accessed directly from within the cluster.

## Describe the solution you'd like

I would like the listener to be configurable via an environment variable, just like how [LONGHORN_MANAGER_IP](https://github.com/longhorn/longhorn-ui/blob/eecabc09b59f03750a53815251c48f10c96707c6/Dockerfile#L27) is configured.

This way we can override the listen argument by setting an environment variable like `LONGHORN_UI_LISTEN_PORT` (for example) to something like `localhost:8000`. Ensuring only traffic coming from the localhost (the sidecar) will be listened to.

## Describe alternatives you've considered

We have successfully overriden the `command` and `args` when deploying Longhorn UI to make this work:

```yaml
# ... ommitted beginning of deployment manifest ...
spec:
  containers:
  - name: longhorn-ui
    args:
    - -c
    - mkdir -p /var/config/nginx/ && cp -r /etc/nginx/* /var/config/nginx/; envsubst
      '${LONGHORN_MANAGER_IP}' < /etc/nginx/nginx.conf.template > /var/config/nginx/nginx.conf
      && sed 's/8000/localhost:8000/g' -i /var/config/nginx/nginx.conf && nginx -c
      /var/config/nginx/nginx.conf -g 'daemon off;'
    command:
    - /bin/bash
    env:
    - name: LONGHORN_MANAGER_IP
      value: some_address
    image: longhornio/longhorn-ui:v1.2.3
    # ... omitted rest of container spec ...
  - name: oauth2-proxy
    # ... ommitted rest of container / pod spec ...
```

The args command was built from the dockerfile [CMD](https://github.com/longhorn/longhorn-ui/blob/eecabc09b59f03750a53815251c48f10c96707c6/Dockerfile#L32), unfortunately if this ever changes our ability to run this securely may be compromised.

## Additional context

We have also begun using Network Policies to make sure the pod does not receive traffic from unknown sources. Which is great, but for completeness it'd be nice to make sure the network policy was simply another, but non-critical layer.
