### ISSUE TITLE
[BUG] PVC create from volumsanpshot stuck at pending status(type=snap)

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3860]
## Describe the bug

After add volumesnapshotclass(type=snap) and create volumesnapshot, create PVC from volumesnapshot, the PVC will stuck at pending status

master-head 0418(1c261cab59443013b398c4a99889661cfe2e6fe5)

related to https://github.com/longhorn/longhorn/issues/2534

## To Reproduce

1. Enable [csi snapshot support](https://longhorn.io/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/)  
2. Create Longhorn volume test-vol of 5GB. Create PV/PVC for the Longhorn volume. Attach the volume
3. Deploy snapshotclass (type=snap)
```yaml
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1beta1
metadata:
  name: longhorn-snapshot
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap

```
4. Create volumesnapshot
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-longhorn-snapshot
spec:
  volumeSnapshotClassName: longhorn-snapshot
  source:
    persistentVolumeClaimName: test-vol
```
5. Create PVC from volumesnapshot
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restore-pvc
spec:
  storageClassName: longhorn
  dataSource:
    name: test-snapshot-longhorn-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
6. Will see PVC `test-restore-pvc` stuck at pending status

## Expected behavior

PVC create from volumesnapshot should generated and bring up a PV

## Log or Support bundle

[longhorn-support-bundle_ab3e8554-0924-4c3f-a433-5e8774cceeb7_2022-04-18T01-29-04Z.zip](https://github.com/longhorn/longhorn/files/8502872/longhorn-support-bundle_ab3e8554-0924-4c3f-a433-5e8774cceeb7_2022-04-18T01-29-04Z.zip)

```
E0418 01:07:32.856357 1 snapshot_controller.go:105] createSnapshot for content [snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30]: error occurred in createSnapshotWrapper: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30: "snapshot controller failed to update snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30 on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30\": the object has been modified; please apply your changes to the latest version and try again"
--
Mon, Apr 18 2022 9:07:32 am | E0418 01:07:32.856370 1 snapshot_controller_base.go:261] could not sync content "snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30": failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30: "snapshot controller failed to update snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30 on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30\": the object has been modified; please apply your changes to the latest version and try again"
Mon, Apr 18 2022 9:07:32 am | I0418 01:07:32.856393 1 snapshot_controller.go:267] createSnapshotWrapper: Creating snapshot for content snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30 through the plugin ...
Mon, Apr 18 2022 9:07:32 am | I0418 01:07:32.856464 1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30: "snapshot controller failed to update snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30 on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-9bf91fed-9a9b-4c6a-b963-2a716e7cce30\": the object has been modified; please apply your changes to the latest version and try again"

```

```
[PersistentVolumeClaim test-restore-pvc](https://192.168.122.148:8443/dashboard/c/c-m-pwlqt52x/explorer/event/default/test-restore-pvc.16e6d84254601178)
Failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create volume: unable to create volume pvc-ff801a17-9f7d-4636-8067-595181a0b84d: admission webhook "validator.longhorn.io" denied the request: failed to verify data source: error listing snapshot: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [--url 10.42.0.12:10000 snapshot info], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn: no such file or directory, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
```

## Environment

 - Longhorn version: master-head 0418(1c261cab59443013b398c4a99889661cfe2e6fe5)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.22.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Multipass VM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

So far type=bak not encounter issue
I have tried change `v1beta1` to `v1` in all yaml files but result still the same
