### ISSUE TITLE
[BUG] Volume created from cloned PVC will stuck at Not Ready status

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3886]
## Describe the bug

On master-head 20220422 e2e [test_cloning](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/99/testReport/junit/tests/test_cloning/) all failed, it's due to volume created from cloned PVC will stuck at `Not Ready` status

## To Reproduce

1. Create a PVC
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  storageClassName: longhorn
  accessModes:
     - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```
2. Specify the `source-pvc` in a pod yaml and start the pod
3. Wait for the pod to be running, write some data to the mount path of the volume  
4. Clone a volume by creating the PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-pvc
spec:
  storageClassName: longhorn
  dataSource:
    name: source-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```
5. Observe volume cloned from PVC, it will stuck at `Not Ready `status

## Expected behavior

Volume should ready for workload

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.
[longhorn-support-bundle_50397967-d821-4362-a12f-29a99033f01d_2022-04-22T07-23-04Z.zip](https://github.com/longhorn/longhorn/files/8537853/longhorn-support-bundle_50397967-d821-4362-a12f-29a99033f01d_2022-04-22T07-23-04Z.zip)

Log from csi-snapshotter can see some error as below
```
E0422 08:04:31.000306 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
--
Fri, Apr 22 2022 4:04:53 pm | E0422 08:04:53.482536 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
Fri, Apr 22 2022 4:05:13 pm | E0422 08:05:13.007416 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
Fri, Apr 22 2022 4:05:50 pm | E0422 08:05:50.491749 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
Fri, Apr 22 2022 4:06:11 pm | E0422 08:06:11.505379 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
Fri, Apr 22 2022 4:06:30 pm | E0422 08:06:30.073297 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

## Environment

 - Longhorn version: master-head 20220422 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A
