### ISSUE TITLE
[BUG] Upgrading from v1.2.x to v1.2.4 take a long time if there are many backup CRs in the system

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3980]
## To Reproduce

1. Install Longhorn v1.2.0 or v1.2.1 or v1.2.2 or v1.2.3
2. Create 20k backups in the system (e.g., by using a recurring job)
3. Perform upgrade to Longhorn v1.2.4
4. See that it takes a long time (about 2 hours) for the first Longhorn manager pod to come up

## Expected behavior

it should take less than 15 mins for the first Longhorn manager pod to come up

**Comment by PhanLe1010** [comment]
## Test data:
### Evn:
Number of CP nodes: 3
Number of worker nodes: 5
Node spec: EC2 m5.2xlarge
Longhorn version:  v1.2.x (05/17/2022)
Number of backup CRs in the system: 7.7k
Number of volumes: 300
Number of volumes per node: 60
Recurring backup job:
```
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-backup
  namespace: longhorn-system
spec:
  cron: "*/5 * * * *"
  task: "backup"
  groups:
  - default
  retain: 34
  concurrency: 50
```


### Data

| Setup  | Upgrading Time | Logs |
| ------------- | ------------- | ------------- |
| burst = 10 <br> qps = 5  | 27 mins  | `[longhorn-manager-98qpx] time="2022-05-17T18:26:27Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Deleted 0 cronjob job for vol-192 volume"`  <br>`time="2022-05-17T18:53:01Z" level=info msg="Finish upgrading"` |
| burst = 1000 <br> qps = 1000  | 13 mins  | `[longhorn-manager-vqfmr] time="2022-05-17T18:57:29Z" level=info msg="Start upgrading" `  <br>`time="2022-05-17T19:10:30Z" level=info msg="Finish upgrading"` |
| burst = 10000 <br> qps = 10000  | 13 mins  | `time="2022-05-17T19:13:22Z" level=info msg="Start upgrading" `  <br>`time="2022-05-17T19:26:31Z" level=info msg="Finish upgrading"` |
| burst = 1000 <br> qps = 1000 <br> [cache engines and volumes](https://github.com/longhorn/longhorn-manager/pull/1335)  | 3 seconds | `time="2022-05-17T20:12:31Z" level=info msg="Start upgrading" `  <br>`time="2022-05-17T20:12:34Z" level=info msg="Finish upgrading"` |
