### ISSUE TITLE
[IMPROVEMENT] Change Longhorn API to create/delete snapshot CRs instead of calling engine CLI

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3995]
## Is your improvement request related to a feature? Please describe

After [the snapshot CRD](https://github.com/longhorn/longhorn/issues/3144) is implemented and stable, we should change the Longhorn snapshot create/delete API to create/delete snapshot CRs instead of calling engine CLI

Note that this change will impact all clients: recurring job, e2e test because now the 200 response from snapshot creation/deletion API doesn't mean that the snapshot was successfully created/deleted. The clients have to watch the snapshot CR status for the status.

This is one step close to the goal to operate Longhorn using CRD only

**Comment by PhanLe1010** [comment]
cc @innobead Could you please help to assign milestone

**Comment by innobead** [comment]
This is part of https://github.com/longhorn/longhorn/issues/3715.

**Comment by PhanLe1010** [comment]
We have provided the snapshot CR create/delete/get/list APIs. Currently, CSI plugin, recurring jobs is working with these new API. Longhorn UI is still working with old snapshot APIs (this will be further address in the ticket https://github.com/longhorn/longhorn/issues/5894)

**Test plan:**

#### Scenarios 1: CSI snapshot flow

1. Install the prerequisite at https://longhorn.io/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
1. Deploy VolumeSnapshotClass:
    ```yaml
    kind: VolumeSnapshotClass
    apiVersion: snapshot.storage.k8s.io/v1beta1
    metadata:
      name: longhorn-snapshot
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: snap
    ```
1. Create Longhorn volume `test-vol` of 5GB. Create PV/PVC for the Longhorn volume.
1. Create a workload that uses the volume. Write some data to the volume.
   Make sure data persist to the volume by running `sync`
1. Create `test-snapshot-longhorn-snapshot` VolumeSnapshot with `volumeSnapshotClassName: longhorn-snapshot`.
1. Verify that a Longhorn snapshot CR is created for the `test-vol`.
1. Create a PVC with the following yaml:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-restore-pvc
    spec:
      storageClassName: longhorn
      dataSource:
        name: test-snapshot-longhorn-snapshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
    ```
1. Attach the PVC `test-restore-pvc` and verify the data 
1. Delete the PVC
1. Delete the VolumeSnapshot `test-snapshot-longhorn-snapshot` and verify that the VolumeSnapshot is deleted.
1. Verify that Longhorn snapshot CR is pending removal because it is the snapshot next to volume-head
1. Create `test-snapshot-longhorn-snapshot-2` VolumeSnapshot with `volumeSnapshotClassName: longhorn-snapshot`.
1. Verify that the pending removal Longhorn snapshot CR

#### Scenarios 2: recurring snapshot job

1. Create a volume. Attach. Write some data
1. Create a recurring snapshot job with retain count 2 which run every minutes
1. Verify that the recurring job create/delete snapshot CRs
