### ISSUE TITLE
[BUG] RWX Volume Actual Size Constantly Grows with No Pod Usage

### ISSUE THREAD

**Issue by ProjectInitiative** [longhorn/longhorn#4012]
## Describe the bug

Any newly created RWX PVC continually eats up space on local disk even though nothing is being added within pod volume. Pods are reporting a few kilobytes for a test text file, but inspecting the mount points on the nodes, the .img file keeps growing in size

## To Reproduce

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-test
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2Ti
```

## Expected behavior

Volume does not balloon with no disk usage from pods.

## Support bundle
[longhorn-support-bundle_0ade8d65-060d-4abd-9c8f-6dcdbe6a09d4_2022-05-20T14-10-34Z.zip](https://github.com/longhorn/longhorn/files/8740758/longhorn-support-bundle_0ade8d65-060d-4abd-9c8f-6dcdbe6a09d4_2022-05-20T14-10-34Z.zip)
Support bundle

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 12
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 1GbE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

![image](https://user-images.githubusercontent.com/6314611/169544142-e5a8d039-967f-4006-9949-77a799cc6b38.png)
Next one taken 2 minutes later
![image](https://user-images.githubusercontent.com/6314611/169545176-a0bb96f3-6535-431d-a717-f4ecd2010835.png)
