### ISSUE TITLE
[BUG] Annotations not being applied to ingress

### ISSUE THREAD

**Issue by johnwc** [longhorn/longhorn#4014]
## Describe the bug

We set a annotation on the ingress, but it never was applied to the ingress.

## To Reproduce

1. Deploy chart using annotation on ingress.
2. View ingress that was created, no annotations were created as you added.

## Expected behavior

Ingress gets deployed with applied annotations.

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2

## Additional context

```YAML
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  enabled: true
  host: longhorn.ourdomain.tld
  ingressClassName: nginx-lb
  secrets: null
  tls: true
  tlsSecret: longhorn.local-tls
```

**Comment by PhanLe1010** [comment]
Thanks @johnwc for reporting
I am able to reproduce this issue using Longhorn chart on the Rancher market place.
The problem doesn't happen when install using pure Helm. 
 Need to do more investigation

**Comment by PhanLe1010** [comment]
I am scratching my head not understanding why setting the helm value [here](https://github.com/rancher/charts/blob/4b64d2984fb6f7e0959d7a3e84e3ee44665486b3/charts/longhorn/100.1.2%2Bup1.2.4/values.yaml#L202-L204)  doesn’t take effect.

I am asking for help from Rancher team

**Comment by PhanLe1010** [comment]
Rancher UI ticket is filled at https://github.com/rancher/dashboard/issues/6038

**Comment by riptidewave93** [comment]
For what it's worth I see the same issue with kustomize here, using:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.6.1 # https://artifacthub.io/packages/helm/longhorn/longhorn
  releaseName: longhorn
  namespace: longhorn-system
  includeCRDs: true
  valuesInline:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: XXXX
        external-dns.alpha.kubernetes.io/hostname: XXXX
      ingressClassName: nginx
      host: XXXXX
      tls: true
      tlsSecret: longhorn-ingress-tls
```

I wonder if rancher also uses kustomize underneath...

**Comment by johnwc** [comment]
Still relevant

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by DodoLeDev** [comment]
Hello there!
[The bug has been identified](https://github.com/rancher/dashboard/issues/6038#issuecomment-3598681834), and is related to the [default value of the chart being `null`](https://github.com/longhorn/longhorn/blob/b9962d0f3ed945fb70e1f58a7173392afb2067bf/chart/values.yaml#L575):
```yaml
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  # -- Ingress annotations in the form of key-value pairs.
  annotations:
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: true
```

I have opened a PR to address this issue.

**Comment by mantissahz** [comment]
Hi @DodoLeDev,
Thanks for the contribution.
Could you fill in the information for `Pre Ready-For-Testing Checklist`?

**Comment by DodoLeDev** [comment]
> Could you fill in the information for `Pre Ready-For-Testing Checklist`?

Hello! From what I have seen on other issues, you expect me to update [this comment](https://github.com/longhorn/longhorn/issues/4014#issuecomment-4064350981), but I am unable to edit it. So what should I do?

---

Here is the fixed comment, if you decide to edit it by yourself:

### Pre Ready-For-Testing Checklist

- [x] **Context & Reproduction**
Where are the reproduction or test steps documented?
_1. Go to Rancher UI_
_2. Apps > Charts_
_3. Search for "Longhorn"_
_4. Click **Install**_
_5. In the _installation options_, switch to **Edit YAML**_
_6. Find the `ingress.annotations` key, and fill it with some annotations ([see here](https://github.com/longhorn/longhorn/issues/4014#issue-1244087368) for an example)_
_7. Click **Install** with devtools opened_
_8. Figure out in the network tab that the POST request to install the app has `ingress.annotations: null` (https://github.com/rancher/dashboard/issues/6038#issue-1248731095)_
_9. Once the installation has started, if you check in the **Values YAML** tab, the `ingress.annotations` equals `null`_

- [x] **Workaround**
    Is there a workaround for the issue? If yes, where is it documented?
_For now, either you install Longhorn with pure Helm commands, or you edit the Ingress resource once the installation has finished_

- [x] **Fix / Feature Explanation**
    Does the PR include a clear explanation of the fix or the new feature?
    _Yes_

- [x] **Code Changes**
    Have all required code changes been merged?
_Yes. No internal code changes are required, as it's purely from the Kubernetes side_

- [x] **Deployment Changes (YAML / Helm Chart)**
    Does the PR introduce any deployment changes?
    PR: #12793 
_Yes, but it's transparent for everyone, because it's only about default values, and not about how these are interpreted_

- [ ] Longhorn Enhancement Proposal (LEP) (if labeled require/LEP)
    Has the LEP PR been submitted?
_Don't know what it is_

- [x] Documentation Updates (if labeled require/doc)
    Has the required documentation PR been submitted or merged?
_No documentation is required_

- [ ] Manual Test Plan (if labeled require/manual-test-plan)
    Has the manual test plan been documented?
_Don't know what it is_

**Comment by roger-ryao** [comment]
**Verified on master 20260331**

- longhorn master-head https://github.com/longhorn/longhorn/commit/fdb6a9e1be822aaaae5b28255e97ca5b8c832d1d


**The test steps**

1. Fresh Install via Helm `--set` Flag

```bash
helm install longhorn . \
  --namespace longhorn-system \
  --create-namespace \
  --set ingress.enabled=true \
  --set ingress.host=longhorn.example.com \
  --set ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt \
  --set ingress.ingressClassName=nginx
```

```bash
kubectl get ingress -n longhorn-system -o yaml | grep -A 10 annotations
```

---

2. Fresh Install via `values.yaml`

**values.yaml**:
```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.example.com
  extraHosts: []
  tls: true
  secureBackends: false
  tlsSecret: longhorn-tls
  path: /
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  secrets:
```

```bash
helm install longhorn . \
  --namespace longhorn-system \
  --create-namespace \
  -f values.yaml
```

```bash
kubectl get ingress longhorn-ingress \
  -n longhorn-system \
  -o jsonpath='{.metadata.annotations}' | jq .

kubectl describe ingress longhorn-ingress -n longhorn-system
```

---


3. Upgrade via `values.yaml`

**Diff of `values.yaml` changes**:
```diff
 ingress:
-  enabled: false
-  ingressClassName: ~
-  host: sslip.io
+  enabled: true
+  ingressClassName: nginx
+  host: longhorn.example.com
   extraHosts: []
-  tls: false
+  tls: true
   secureBackends: false
-  tlsSecret: longhorn.local-tls
+  tlsSecret: longhorn-tls
   path: /
   pathType: ImplementationSpecific
-  annotations: {}
+  annotations:
+    cert-manager.io/cluster-issuer: letsencrypt
+    kubernetes.io/tls-acme: "true"
   secrets:
```

```bash
# Fresh install without ingress settings
helm install longhorn . \
  --namespace longhorn-system

# Upgrade with modified values.yaml
helm upgrade longhorn . \
  --namespace longhorn-system \
  -f values.yaml
```

```bash
kubectl get ingress -n longhorn-system -o yaml | grep -A 10 annotations
```

---

**Result Passed**

1. Fresh Install via Helm `--set` Flag

```yaml
annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/ingress.class: nginx
  meta.helm.sh/release-name: longhorn
  meta.helm.sh/release-namespace: longhorn-system
```


---


2. Fresh Install via `values.yaml`

```json
{
  "cert-manager.io/cluster-issuer": "letsencrypt",
  "kubernetes.io/tls-acme": "true",
  "meta.helm.sh/release-name": "longhorn",
  "meta.helm.sh/release-namespace": "longhorn-system"
}
```

```
Name:             longhorn-ingress
Namespace:        longhorn-system
Ingress Class:    nginx
TLS:
  longhorn-tls terminates longhorn.example.com
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  longhorn.example.com  /     longhorn-frontend:80 (10.42.2.183:8000,10.42.3.210:8000)
Annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/tls-acme: true
  meta.helm.sh/release-name: longhorn
  meta.helm.sh/release-namespace: longhorn-system
```




3. Upgrade via `values.yaml`

```yaml
annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/tls-acme: "true"
  meta.helm.sh/release-name: longhorn
  meta.helm.sh/release-namespace: longhorn-system
```
