### ISSUE TITLE
[BUG] Can't delete volumesnapshot if backup removed first 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4107]
## Describe the bug

After using volumesnapshot to create backup, if we delete backup first then delete the volumesnapshot, the volumesnapshot delete will stuck forever  

## To Reproduce

1. Deploy Longhorn v1.3.0-rc3
2. Enable Install the Snapshot CRDs / controller introduced [here](https://longhorn.io/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/) (Use 4.0)
3. Create VolumeSnapshotClass longhorn-backup
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1beta1
metadata:
  name: longhorn-backup
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
```
4. Create Longhorn volume test-vol of 5GB. Create PV/PVC for the Longhorn volume
5. Create a workload that uses the volume. Write some data to the volume
6. Create a VolumeSnapshot
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-longhorn-backup
spec:
  volumeSnapshotClassName: longhorn-backup
  source:
    persistentVolumeClaimName: test-vol
```
7. Verify that a backup is created
8. Verify volumesnpashot test-snapshot-longhorn-backup created
9. Delete backup
10. Delete volumesnapshot by command `kubectl delete volumesnapshot test-snapshot-longhorn-backup`
The delete process will stucked

## Expected behavior

Volumesnpashot should delete successfully

## Log or Support bundle

N/A

## Environment

 - Longhorn version: v1.3.0-rc3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3d
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 1

## Additional context

If run `kubectl delete volumesnapshot test-snapshot-longhorn-backup` when backup exist, Both backup and volumesnapshot will delete successful
