### ISSUE TITLE
[BUG] Unable to drain node using Ansible

### ISSUE THREAD

**Issue by impsik** [longhorn/longhorn#4108]
## Describe the bug

I have 3 workernodes. But sadly i'm not able to drain using Ansible (module: kubernetes.core.k8s_drain)
"msg": "Failed to delete pod longhorn-system/instance-manager-e-4edb318f due to: Too Many Requests"
I guess this module works over API.

## To Reproduce
Ansible play part:
```
    - name: "Drain node {{ inventory_hostname|lower }}, even if there are pods not managed by a ReplicationController, Job, or DaemonSet on it."
      kubernetes.core.k8s_drain:
        state: drain
        name: "{{ inventory_hostname|lower }}"
        kubeconfig: ~/.kube/config
        delete_options:
          ignore_daemonsets: yes
          delete_emptydir_data: yes
          force: yes
          terminate_grace_period: 0
          wait_sleep: 120
      delegate_to: localhost
```

## Expected behavior

worker node will be drained

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.4 LTS
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): HDD ("WDC WD2000FYYZ")
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 3
