### ISSUE TITLE
Adding faster storage class: specified node tag sdd does not exist

### ISSUE THREAD

**Issue by VladoPortos** [longhorn/longhorn#4180]
## Question
Hi all,
I'm not sure what I'm missing. I have added 1x SSD to 3 of my nodes. Then added them in the UI to longhorn, they are visible and shedulable. I have tagged the disk with "ssd" in UI, I have tagged the nodes in the UI where the disks were added with tag "ssd" (Other nodes do not have tags, and the 3 nodes have only tah ssd). 

Added new storage class:

```
 kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  diskSelector: "ssd"
  nodeSelector: "sdd"
```

Makes sense so far, but when creating PVC in storage class `longhorn-fast` I get this:

`  Warning  ProvisioningFailed    3s               driver.longhorn.io_csi-provisioner-869bdc4b79-ml6rw_aae75051-6ac3-4de6-a7c3-d2c7609cefc4  failed to provision volume with StorageClass "longhorn-fast": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=specified node tag sdd does not exist, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
`

Each node in my cluster have dedicated default disk to longhorn default storage class, but I want to have 3 nodes where I have added the SSD to provide longhorn-fast together with the longhorn storage class. I think I have missed one step, but not sure where.

Where else I need to tag them ?

## Environment

 - Longhorn version: 1.3.0
 - Kubernetes version: v1.23.6+k3s1
 - Node config
   - OS type and version: DietPi latest
   - CPU per node: 4
   - Memory per node: 4G
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: No Idea
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Rpi 4 / Baremetal
