### ISSUE TITLE
[BUG] Replica stuck in buggy state with status.currentState is error and the spec.desireState is running

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4197]
## Describe the bug

A Longhorn volume has replica count 1. The volume is trying to attach however, the replica has `status.currentState is error` and the `spec.desireState is running`. This prevent the Longhorn manager pod to start the replica: [code](https://github.com/longhorn/longhorn-manager/blob/79ce2cfde922a7e0966059f72b8aee5f05bff513/controller/instance_handler.go#L249-L267). Also, the engine has not running yet so the replica.spec.failedAt has never been set. The result is that the replica is stuck and volume is stuck in attaching state.

* Replica yaml
  <details close>
  <summary>Click to open</summary>
  <br>
  
  ```
  [12:54 PM] Barathiraja Natarajan
  apiVersion: longhorn.io/v1beta1
  kind: Replica
  metadata:
    name: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199-r-da63eda5
  spec:
    active: true
    backingImage: ""
    baseImage: ""
    dataDirectoryName: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199-5f277b8d
    dataPath: ""
    desireState: running
    diskID: 4ef70f37-55e2-452f-a38d-5fc9eabc048a
    diskPath: /longhorn/
    engineImage: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
    engineName: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199-e-0acc0830
    failedAt: ""
    hardNodeAffinity: us1sxlxk80226
    healthyAt: "2022-06-29T03:25:37Z"
    logRequested: false
    nodeID: us1sxlxk80226
    rebuildRetryCount: 0
    revisionCounterDisabled: false
    salvageRequested: false
    volumeName: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199
    volumeSize: "7516192768"
  status:
    currentImage: ""
    currentState: error
    evictionRequested: false
    instanceManagerName: instance-manager-r-3fc65294
    ip: ""
    logFetched: false
    ownerID: us1sxlxk80226
    port: 0
    salvageExecuted: false
    started: true
  ```
  </details>
* Engine yaml
  <details close>
  <summary>Click to open</summary>
  <br>
  
  ```
  spec:
    instancespec:
      volumename: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199
      volumesize: 7516192768
      nodeid: ""
      engineimage: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      desirestate: stopped
      logrequested: false
      salvagerequested: true
    frontend: blockdev
    replicaaddressmap:
      pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199-r-da63eda5: 10.42.6.133:10045
    upgradedreplicaaddressmap: {}
    backupvolume: ""
    requestedbackuprestore: ""
    requesteddatasource: ""
    disablefrontend: false
    revisioncounterdisabled: false
    active: true
  status:
    instancestatus:
      ownerid: us1sxlxk80233
      instancemanagername: ""
      currentstate: stopped
      currentimage: ""
      ip: ""
      port: 0
      started: false
      logfetched: false
      salvageexecuted: false
    currentsize: 7516192768
    currentreplicaaddressmap:
      pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199-r-da63eda5: 10.42.6.133:10045
    replicamodemap: {}
    endpoint: ""
    lastrestoredbackup: ""
    backupstatus: {}
    restorestatus: {}
    purgestatus: {}
    rebuildstatus: {}
    clonestatus:
      tcp://10.42.13.39:10270:
        iscloning: false
        error: ""
        progress: 0
        state: ""
        fromreplicaaddress: ""
        snapshotname: ""
    snapshots:
      7cb7ea3e-9739-4538-8387-7879e7ce6d7e:
        name: 7cb7ea3e-9739-4538-8387-7879e7ce6d7e
        parent: backup-c-2efe1d11
        children:
          volume-head: true
        removed: true
        usercreated: false
        created: "2022-06-29T03:25:20Z"
        size: "200704"
        labels: {}
      backup-c-2efe1d11:
        name: backup-c-2efe1d11
        parent: ""
        children:
          7cb7ea3e-9739-4538-8387-7879e7ce6d7e: true
        removed: false
        usercreated: true
        created: "2022-06-29T03:01:12Z"
        size: "196759552"
        labels:
          RecurringJob: backup
      volume-head:
        name: volume-head
        parent: 7cb7ea3e-9739-4538-8387-7879e7ce6d7e
        children: {}
        removed: false
        usercreated: false
        created: "2022-06-29T03:25:20Z"
        size: "401408"
        labels: {}
    snapshotserror: ""
    isexpanding: false
    lastexpansionerror: ""
    lastexpansionfailedat: ""
  ```
  </details>

* Volume yaml
  <details close>
  <summary>Click to open</summary>
  <br>
  
  ```
  spec:
    size: 7516192768
    frontend: blockdev
    frombackup: ""
    datasource: ""
    datalocality: best-effort
    stalereplicatimeout: 2880
    nodeid: us1sxlxk80233
    migrationnodeid: ""
    engineimage: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
    backingimage: ""
    standby: false
    diskselector: []
    nodeselector: []
    disablefrontend: false
    revisioncounterdisabled: false
    lastattachedby: ""
    accessmode: rwo
    migratable: false
    encrypted: false
    numberofreplicas: 1
    replicaautobalance: ignored
    baseimage: ""
    recurringjobs: []
  status:
    ownerid: us1sxlxk80233
    state: attaching
    robustness: unknown
    currentnodeid: us1sxlxk80233
    currentimage: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
    kubernetesstatus:
      pvname: pvc-5a12e43b-96e4-4bd9-86e9-d10b1a631199
      pvstatus: Bound
      namespace: rd-dlims-gadr-kafka
      pvcname: data-rd-dlims-gadr-zookeeper-1
      lastpvcrefat: ""
      workloadsstatus:
      - podname: rd-dlims-gadr-zookeeper-1
        podstatus: Pending
        workloadname: rd-dlims-gadr-zookeeper
        workloadtype: StatefulSet
      lastpodrefat: ""
    conditions:
      restore:
        type: restore
        status: "False"
        lastprobetime: ""
        lasttransitiontime: "2022-03-17T21:53:08Z"
        reason: ""
        message: ""
      scheduled:
        type: scheduled
        status: "True"
        lastprobetime: ""
        lasttransitiontime: "2022-06-19T02:00:31Z"
        reason: ""
        message: ""
      toomanysnapshots:
        type: toomanysnapshots
        status: "False"
        lastprobetime: ""
        lasttransitiontime: "2022-03-17T21:53:08Z"
        reason: ""
        message: ""
    lastbackup: backup-bb806770104d42f3
    lastbackupat: "2022-06-29T03:01:14Z"
    pendingnodeid: ""
    frontenddisabled: false
    restorerequired: false
    restoreinitiated: false
    clonestatus:
      sourcevolume: ""
      snapshot: ""
      state: ""
    remountrequestedat: "2022-06-29T04:29:07Z"
    expansionrequired: false
    isstandby: false
    actualsize: 197361664
    lastdegradedat: ""
    shareendpoint: ""
    sharestate: ""
  ```
  </details>

## To Reproduce

Steps to reproduce the behavior: https://github.com/longhorn/longhorn/issues/4197#issuecomment-1175494785

## Expected behavior

The replica shouldn't be in that buggy state. Longhorn should stop the replica and clear the `replica.status` field before attempting to start it again.

## Log or Support bundle

More details can be found at
https://suse.slack.com/archives/C03GV5T0P55/p1656538367100689

## Environment

 - Longhorn version: 1.2.4
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.19.8, RKE

**Comment by PhanLe1010** [comment]
Have not tested yet but an idea to reproduce:
1. Create a volume of 1 replica
2. Somehow mess up the engine binary on the host but still make sure that it passes the liveness probe of the engine deamonset
3. Attach the volume and see the behavior

**Comment by PhanLe1010** [comment]
Workaround:

1. Scale down the workload
2. Manually reset the `spec.nodeId` to `""` by `kubectl edit volumes.longhorn.io <VOLUME-NAME> -n longhorn-system` to detach the volume 
3. Scale up the workload

**Comment by innobead** [comment]
@PhanLe1010 Need to backport to 1.3.1 and 1.2.5. Thanks.

**Comment by PhanLe1010** [comment]
**Test steps:**

Goal: Make sure that Longhorn retries to attach the volume when the replica failed to start

Steps:

1. Create a volume of 1 replica. Let's say the replica is on node01
1. Artificially simulate the replica launching failure by somehow messing up the engine binary on the host but still make sure that it passes the liveness probe of the engine deamonset
    1. Edit the engine-image-xxx daemonset and replace this rediness probe:
        ```
                readinessProbe:
                  exec:
                    command:
                    - sh
                    - -c
                    - ls /data/longhorn && /data/longhorn version --client-only
        ```
        by 
        ```
                readinessProbe:
                  exec:
                    command:
                    - sh
                    - -c
                    - ls /data/longhorn 
        ```
    1. SSH into the node01, cd into longhorn engine binary directory (e.g., `/var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.2.4`) then `rm longhorn && touch longhorn && chmod +x longhorn`

1. Attach the volume to node02 
2. Verify that: Longhorn tries to attach volume but fail to launch replica -> Longhorn detaches volumes -> try attach ... The cycle repeat
3. Delete the engine-image-xxx pod on node01 so that Longhorn redownload the engine binary and replace the fake one we created in the step 2 above
4. Verify that volume successfully attached

**Comment by yangchiu** [comment]
@PhanLe1010 I Followed the [test steps](https://github.com/longhorn/longhorn/issues/4197#issuecomment-1193023991) to verify this issue, but somehow I'm unable to get the expected result.

Is anything wrong in the following steps?

(1) install longhorn master-head (longhorn-manager 70203d6)
(2) create a volume of replica count = 1, the replica is on node-01
(3) `kubectl edit daemonset engine-image-ei-b907910b -n longhorn-system` to: 
```
readinessProbe:
          exec:
            command:
            - sh
            - -c
            - ls /data/longhorn 
```
(4) ssh into node-01, then execute:
```
sudo su -
cd /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/ 
rm longhorn && touch longhorn && chmod +x longhorn
``` 
verify the engine image has been modified:
```
ls -al
# -rwxr-xr-x 1 root root    0 Jul 25 07:21 longhorn
```
(5) attach the volume to another node node-02, the volume eventually stays in detached / faulted state, no repeating cycle:
```
test-1 | Volume | longhorn-volume-controller | Normal | 18 minutes ago | 18 minutes ago | Detached | volume test-1 has been detached
test-1-r-c4daaafc | Replica | longhorn-replica-controller | Normal | 18 minutes ago | 18 minutes ago | Stop | Stops test-1-r-c4daaafc
test-1-r-c4daaafc | Replica | longhorn-replica-controller | Normal | 18 minutes ago | 18 minutes ago | Start | Starts test-1-r-c4daaafc
test-1 | Volume | longhorn-volume-controller | Normal | 22 minutes ago | 22 minutes ago | Detached | volume test-1 has been detached
```
![Screenshot from 2022-07-25 15-42-31](https://user-images.githubusercontent.com/5709208/180724458-7e90b460-7a5e-4db1-be1d-3dfd5a19419c.png)
(6) delete the engine-image-xxx pod on node-01 so that Longhorn re-download the engine binary
`kubectl delete pod engine-image-ei-b907910b-g6mpp -n longhorn-system`
verify the engine image has been re-downloaded and back to normal on node-01:
```
ls -al
-rwxr-xr-x 1 root root 29465584 Jul 21 14:10 longhorn
```
(7) the volume still in detached / faulted state, no re-attaching happened.
```
test-1 | Volume | longhorn-volume-controller | Normal | 30 minutes ago | 30 minutes ago | Detached | volume test-1 has been detached
test-1-r-c4daaafc | Replica | longhorn-replica-controller | Normal | 30 minutes ago | 30 minutes ago | Stop | Stops test-1-r-c4daaafc
test-1-r-c4daaafc | Replica | longhorn-replica-controller | Normal | 30 minutes ago | 30 minutes ago | Start | Starts test-1-r-c4daaafc
test-1 | Volume | longhorn-volume-controller | Normal | 33 minutes ago | 33 minutes ago | Detached | volume test-1 has been detached
```
the support bundle:
[longhorn-support-bundle_ad517fcf-d1a7-44da-8d02-50f172516c48_2022-07-25T07-50-42Z.zip](https://github.com/longhorn/longhorn/files/9179119/longhorn-support-bundle_ad517fcf-d1a7-44da-8d02-50f172516c48_2022-07-25T07-50-42Z.zip)
