### ISSUE TITLE
[BUG] Longhorn doesn't support non aws s3 buckets

### ISSUE THREAD

**Issue by Citrullin** [longhorn/longhorn#4205]
## Describe the bug

As described in [this discussion post](https://github.com/longhorn/longhorn/discussions/4203), I need to backup into a non aws s3 bucket. I got a HTTPs endpoint. But apparently Longhorn doesn't support this. It only supports `s3://`. I guess a new version of the protocol? Not very familiar with s3 and the in and outs.

## To Reproduce

1. Add a HTTPs endpoint to the Longhorn UI.

## Expected behavior

It just works.

## Log or Support bundle

```
error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.0/longhorn [backup ls --volume-only https://k8-backups.s3.fr-par.scw.cloud], output Driver https is not supported! , stderr, time="2022-07-05T04:56:42Z" level=error msg="Driver https is not supported!" , error exit status 1
```

## Environment

 - Longhorn version: 1.30
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8, 1.23
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 18.06
   - CPU per node: 6
   - Memory per node: 64/128
   - Disk type(e.g. SSD/NVMe): NVMe & SSD
   - Network bandwidth between the nodes: 10 Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3 so far, for evaluation purposes only.

**Comment by c3y1huang** [comment]
Ref https://github.com/longhorn/longhorn/issues/1645#issuecomment-865036442

**Comment by Citrullin** [comment]
> Ref [#1645 (comment)](https://github.com/longhorn/longhorn/issues/1645#issuecomment-865036442) , sample [minio-backupstore.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/backupstores/minio-backupstore.yaml#L10) and [doc](https://longhorn.io/docs/1.3.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore).

The documentation doesn't make very clear that you have to insert a fake endpoint in the UI. Also from a design perspective it's not very elegant. Anyway. I get a certificate error, but this part works. Thank you.

**Comment by c3y1huang** [comment]
> The documentation doesn't make very clear that you have to insert a fake endpoint in the UI. Also from a design perspective it's not very elegant. Anyway. I get a certificate error, but this part works. Thank you.

We understand that and we have an [issue](https://github.com/longhorn/website/issues/161) for improvement. Feel free to create a PR for this.

**Comment by Citrullin** [comment]
@c3y1huang I guess it works with CERT etc. but I still get this error now.
```
error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.0/longhorn [backup ls --volume-only s3://longhorn-foobar@gra/], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.0/longhorn: invalid argument
```

**Comment by c3y1huang** [comment]
There are similar issue reported [here](https://github.com/longhorn/longhorn/issues/3137) and [here](https://github.com/longhorn/longhorn/issues/3834). Have you tried to execute the same command from the manager pod to see if there are more clues?

```
Note: Make sure to use echo -n when generating the base64 encoding, otherwise a new line will be added at the end of the string and it will cause error when accessing the S3.
```

**Comment by Citrullin** [comment]
> There are similar issue reported [here](https://github.com/longhorn/longhorn/issues/3137) and [here](https://github.com/longhorn/longhorn/issues/3834). Have you tried to execute the same command from the manager pod to see if there are more clues?
> 
> `Note: Make sure to use echo -n when generating the base64 encoding, otherwise a new line will be added at the end of the string and it will cause error when accessing the S3.`

The command `backup` doesn't exist in the manager container.

**Comment by smolinari** [comment]
I found this issue because I have a similar problem. I'm using Longhorn and wanted to connect to Contabo's pseudo-S3 block storage. I was constantly getting poorly formatted errors from Longhorn , while accessing the Backup tab (which actually was a good thing). The errors were always basically saying the URL to the block storage was incorrect. The first error being, the URL can only have an `s3` protocol. 

At any rate, using the `s3` URL, the different notes posted in this thread and seeing how the final URL was being generated in those errors (sort of), I was able to piece together what I needed and would like to report it here. Maybe it might help someone else. 

The (proper) URL to the block storage was: https://eu2.contabostorage.com

The URL I needed to put in the Longhorn settings under `Backup Target` was: s3://eu2@contabo/longhorn-backups/

This is what my secret looked like. 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3-compatible-backup-target-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5
  AWS_ENDPOINTS: aHR0cHM6Ly9taW5pby1zZXJ2aWNlLmRlZmF1bHQ6OTAwMA==
  VIRTUAL_HOSTED_STYLE: dHJ1ZQ== # true
``` 
The above example is taken from the [virtual hosted style section of the Longhorn docs](https://longhorn.io/docs/1.4.0/snapshots-and-backups/backup-and-restore/set-backup-target/#enable-virtual-hosted-style-access-for-s3-compatible-backupstore). 

Important to note is I had to add the URL under `AWS_ENDPOINTS` like this:  https://contabostorage.com/

Notice the missing subdomain! 

So, the first entry in the `Backup Target` before the `@` will be placed as the subdomain of the `AWS_ENDPOINTS` entry to get the final URL. 

Scott

**Comment by spuxx1701** [comment]
Recently, Hetzner released S3-compatible object storage. In case anyone wants to use that for their backups, I managed to get it to work with this setup:

The following uses `nbg1` as the region and `foo` as the bucket name.

In Longhorn UI's settings, set `Backup Target` to:
```
s3://bfh2rl@nbg1/
```
I believe it actually doesn't matter what comes after the `@`.
In the secrets used to store the credentials, have:
```yaml
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-credentials
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ...
    AWS_SECRET_ACCESS_KEY: ...
    AWS_ENDPOINTS: https://nbg1.your-objectstorage.com
    VIRTUAL_HOSTED_STYLE: "true"
```

**Comment by czroth** [comment]
For Storj, the following works:
```
s3://<bucket_name>@<region>/
s3://longhorn-backup@us1/  # for example
```

Creds:
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-storj-backups
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ...
  AWS_SECRET_ACCESS_KEY: ...
  AWS_DEFAULT_REGION: US1
  AWS_ENDPOINTS: https://gateway.storjshare.io/
  VIRTUAL_HOSTED_STYLE: "true"
```

I'm not sure if the env VIRTUAL_HOSTED_STYLE is necessary.
