### ISSUE TITLE
[BACKPORT][v1.2.x][IMPROVEMENT] Recognize default toleration and node selector to allow Longhorn run on the RKE mixed cluster 

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4273]
https://github.com/longhorn/longhorn/issues/4246
https://github.com/longhorn/longhorn/pull/4262

**Comment by cchien816** [comment]
HI @c3y1huang ,

I encounter engine image can not deploy issue when test this backport issue
[Steps](https://github.com/longhorn/longhorn/issues/4274#issuecomment-1193841308)

Event log
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "engine-image-ei-4dbdb778-j5kr5": Error response from daemon: Windows does not support privileged mode
```
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "discover-proc-kubelet-cmdline": Error response from daemon: Windows does not support privileged mode
```

Support bundle
[longhorn-support-bundle_9e128633-594c-481b-aea6-bd8373a2287e_2022-07-25T10-52-39Z.zip](https://github.com/longhorn/longhorn/files/9180435/longhorn-support-bundle_9e128633-594c-481b-aea6-bd8373a2287e_2022-07-25T10-52-39Z.zip)

Also from UI I can see engine image was deploying on windows nodes.

**Comment by c3y1huang** [comment]
Some notes from the support bundle.
- setting`system-managed-components-node-selector` and `taint-toleration` have empty value.
- `longhorn-default-setting` ConfigMap have correct value for the settings. Not sure why there is `|2-`.
```
  data:
    default-setting.yaml: |2-














      taint-toleration: cattle.io/os=linux:NoSchedule
      system-managed-components-node-selector: kubernetes.io/os:linux
```
