### ISSUE TITLE
Volume randomly changed to Read-only file system

### ISSUE THREAD

**Issue by XzenTorXz** [longhorn/longhorn#428]
We have a pod with 2 volume mounts, both for the same volume:

```
        volumeMounts:
        - mountPath: /var/files
          name: vol1
          subPath: files
        - mountPath: /tmp/sessions
          name: vol1
          subPath: sessions
```

and a pod with one volume mount:
```
        volumeMounts:
        - mountPath: /var/files
          name: vol1
          subPath: files
```

Last week on wednesday we updated to Longhorn 0.4.0, everything worked fine.
On friday we suddenly lost write rights to our sessions subPath, other was still working.
We just got the message `Read-only file system (30)`. I couldnt change the file rights with chmod (ubuntu) with the same error message. The other volume had normal write rights.
Also the Pod wouldnt redeploy. So I removed the session mount and scaled it down to 0. Then everything started up again. I added the session-mount to the 2nd Pod and I had write rights again.

The Logs still spamming this:

> I0311 09:19:11.406212 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
> 
> I0311 09:19:19.329324 1 leaderelection.go:271] lock is held by csi-attacher-6fdc77c485-fjjdk and has not yet expired
> 
> I0311 09:19:19.329347 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
> 
> I0311 09:19:28.092038 1 leaderelection.go:271] lock is held by csi-attacher-6fdc77c485-fjjdk and has not yet expired
> 
> I0311 09:19:28.092055 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
> 
> I0311 09:19:34.462578       1 leaderelection.go:271] lock is held by csi-attacher-6fdc77c485-fjjdk and has not yet expired

Some Data:
Kubernetes:  v1.12.3
Rancher: v2.1.4
Nodes: 1
Longhorn: 0.4.0
