### ISSUE TITLE
[BUG] Wrong conditions in the Chart default-setting manifest for Rancher deployed Windows Cluster feature

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4289]
## Describe the bug

The wrong conditions
https://github.com/longhorn/longhorn/blob/master/chart/templates/default-setting.yaml#L2 https://github.com/longhorn/longhorn/blob/master/chart/templates/default-setting.yaml#L33
will make the `taint-toleration` and `system-managed-components-node-selector` empty in the generated `longhorn.yaml` if windowsCluster is disabled.

It will override the two default settings with empty values in the longhorn-system mistakenly during upgrade.

## To Reproduce

1. git clone https://github.com/longhorn/longhorn.git
2. ./scripts/generate-longhorn-yaml.sh
3. The two fields, `taint-toleration` and `system-managed-components-node-selector`, have empty values:
```
data:
  default-setting.yaml: |-
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    taint-toleration: 
    system-managed-components-node-selector:
```

## Expected behavior

The two fields should be `nil` if the values are not set and `windowsCluster` is disabled in `values.yaml`.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by cchien816** [comment]
**Verified on longhorn master-head `df3462`
Result Pass**

1.  Set `windowsCluster` enable false in values.yaml and run `./scripts/generate-longhorn-yaml.sh`.
2. In generated deploy/longhorn.yaml, can not find `taint-toleration` and `system-managed-components-node-selector` as expected
3. Set `windowsCluster` enable true in values.yaml and run `./scripts/generate-longhorn-yaml.sh`.
4. In deploy/longhorn.yaml, can find `taint-toleration` and `system-managed-components-node-selector` shown below as expected
```
data:
  default-setting.yaml: |-
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    taint-toleration: cattle.io/os=linux:NoSchedule
    system-managed-components-node-selector: kubernetes.io/os:linux
```
