### ISSUE TITLE
[BACKPORT][v1.3.1][BUG] Wrong conditions in the Chart default-setting manifest for Rancher deployed Windows Cluster feature

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4290]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4289

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x head `7a8875`
Result Pass**

1. Set `windowsCluster` enable false in values.yaml and run `./scripts/generate-longhorn-yaml.sh`.
2. In generated deploy/longhorn.yaml, can not find `taint-toleration` and `system-managed-components-node-selector` as expected
3. Set `windowsCluster` enable true in values.yaml and run `./scripts/generate-longhorn-yaml.sh`.
4. In deploy/longhorn.yaml, can find `taint-toleration` and `system-managed-components-node-selector` shown below as expected
```
data:
  default-setting.yaml: |-
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    taint-toleration: cattle.io/os=linux:NoSchedule
    system-managed-components-node-selector: kubernetes.io/os:linux
```
