### ISSUE TITLE
[BUG] New nodes failing to start longhorn-manager

### ISSUE THREAD

**Issue by adamstirk-ct** [longhorn/longhorn#4352]
## Describe the bug

I'm trying to add extra Longhorn nodes to an EKS cluster, but the `longhorn-manager` PODs are not starting up on the new nodes and they error with the following  `level=fatal msg="Error starting manager: fail to set the setting priority-class with invalid value system-cluster-critical: cannot modify priority class setting before all volumes are detached"`

We deploy Longhorn via Helm and the values passed into the Helm chart are as follows:

```yaml
defaultSettings:
  allowVolumeCreationWithDegradedAvailability: false
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /mnt/longhorn
  replicaSoftAntiAffinity: false
  upgradeChecker: true
  replicaAutoBalance: best-effort
  disableSchedulingOnCordonedNode: true
  priorityClass: system-cluster-critical
longhornUI:
  priorityClass: system-cluster-critical
longhornDriver:
  priorityClass: system-cluster-critical
longhornManager:
  priorityClass: system-cluster-critical
```

## To Reproduce

1. Have an EKS cluster of 3 nodes with longhorn installed.
2. Add a volume and wait for it to be attached.
3. Add an extra node.

## Expected behavior

The POD's on the new nodes to be assigned the correct priority class and the PODs to startup as they don't yet have any volumes on them.

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm - Chart Version 1.3.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
   - Number of management node in the cluster: N/A
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Managed EKS
   - CPU per node: 2
   - Memory per node: 8Gb
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EKS
 - Number of Longhorn volumes in the cluster: 4
