### ISSUE TITLE
[BACKPORT][v1.2.x][BUG] Restore from backup sometimes failed if having high frequent recurring backup job w/ retention

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4428]
## Describe the bug

ref: #3055

**Comment by Lichiehyao** [comment]
**Verified on v1.2.5-rc2 20220829**

- longhorn v1.2.5-rc2 ([e931127](https://github.com/longhorn/longhorn/commit/e931127489be3a0c46224a99110f31652a18ebae))

**The test steps**

1. Install Longhorn v1.2.5-rc2 Ref.([install-with-kubectl](https://longhorn.io/docs/1.2.4/deploy/install/install-with-kubectl/))
2. Create a volume "bak" on longhorn
3. Create volume "bak"'s PV(name:bak) & PVC (name:myclaim) from longhorn UI
4. Deploy pod “mypod1” via cli **kubctl apply -f mypod1.yaml**
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: mypod1
  volumes:
    - name: mypod1
      persistentVolumeClaim:
        claimName: myclaim
```
5. Enter mypod1 shell  **kubectl exec --stdin --tty mypod1 -- /bin/bash**
6. execute **echo 'Hello from Kubernetes storage' > /usr/share/nginx/html/index.html**
7. Create recurring back job, 3 retain, 1 concurrency, every minute
8. Create a manual backup
9. Restore manual backup to volume-v1
10. Check whether or not the error was printed

**Result Pass**
- After restored, we didn’t find out the error log.
[longhorn-support-bundle_1878a0bf-5abd-40de-8e5d-e6686e5ba5d6_2022-08-29T04-39-39Z.zip](https://github.com/longhorn/longhorn/files/9441707/longhorn-support-bundle_1878a0bf-5abd-40de-8e5d-e6686e5ba5d6_2022-08-29T04-39-39Z.zip)
