### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] Restore from backup sometimes failed if having high frequent recurring backup job w/ retention

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4429]
## Describe the bug

ref: #3055

**Comment by Lichiehyao** [comment]
**Verified on v1.3.x-head 20220829**
- longhorn v1.3.x-head ([cccabbf](https://github.com/longhorn/longhorn/commit/cefb54500fbde5dbfe5d59c70a2d8170d1075044))
- longhorn-manager v1.3.x-head ( [7f1634c](https://github.com/longhorn/longhorn-manager/commit/7f1634c1e45406c5dbb7e66a25a50ccece375623 ))

**The test steps**

1. Install Longhorn 1.3.x-head
2. Create a volume "bak" on longhorn
3. Create volume "bak"'s PV(name:bak) & PVC (name:myclaim) from longhorn UI
4. Deploy pod “mypod1” via cli kubctl apply -f mypod1.yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: mypod1
  volumes:
    - name: mypod1
      persistentVolumeClaim:
        claimName: myclaim
```

5. Enter mypod1 shell kubectl exec --stdin --tty mypod1 -- /bin/bash
6. execute echo 'Hello from Kubernetes storage' > /usr/share/nginx/html/index.html
7. Create recurring back job, 3 retain, 1 concurrency, every minute
8. Create a manual backup
9. Restore manual backup to volume-v1
10. Check whether or not the error was printed

**Result Pass**

- After restored, we didn’t observe the error symptoms.
[longhorn-support-bundle_ad053f1f-e8fc-478d-b3c4-0a72f9cafa0a_2022-08-29T07-21-02Z.zip](https://github.com/longhorn/longhorn/files/9442469/longhorn-support-bundle_ad053f1f-e8fc-478d-b3c4-0a72f9cafa0a_2022-08-29T07-21-02Z.zip)
