### ISSUE TITLE
[FEATURE] Change NumberOfReplicas only for one deployment

### ISSUE THREAD

**Issue by joepa37** [longhorn/longhorn#4463]
It would be a good option to be able to change the number of replicas for a single deployment or pvc, and override the global configuration NumberOfReplicas.

There are some deployments that don't really require replication, for example elasticsearch eck implement their own index replication internally, and replication on top just takes up disk space unnecessarily.

**Comment by derekbit** [comment]
@joepa37
You can edit the volume's replica count directly.
To change the global setting, you can edit `setting` > `general` > `replica count`.

**Comment by joepa37** [comment]
Yes, I know there is a option to change the global replica count (NumberOfReplicas), for that reason I am asking for "for a single deployment or pvc" feature.

**Comment by derekbit** [comment]
Why not create a dedicated storage class for the volumes?

**Comment by joepa37** [comment]
Thanks for your response. Can I create a second longhorn storage class? 

That would be perfect since the rancher's local-path storage class doesn't support `AllowVolumeExpansion`.

Can I have 
1. Longhorn (default) with 3 `NumberOfReplicas`
2. Longhorn (single) with 1 `NumberOfReplicas`

How can I install the second storage class and prevent kubernetes from getting confused with each other's CRDs?

**Comment by joepa37** [comment]
Solution: I created this second storage class following [this doc resource](https://longhorn.io/docs/1.3.2/references/examples/#storageclass)

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
```

Everything is running smoothly
