### ISSUE TITLE
[TASK] Update preserveUnknownFields fields in longhorn-manager CRD manifest 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4505]
## What's the task? Please describe

Update preserveUnknownFields fields in longhorn-manager CRD manifest 

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

https://github.com/longhorn/longhorn/issues/4340#issuecomment-1232452762

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220907**

longhorn master-head ([3375a5b](https://github.com/longhorn/longhorn/commit/3375a5b6133e927cf949738950e8688657f2dd6d)) 
longhorn-manager master-head ( [aab1ba8](https://github.com/longhorn/longhorn-manager/commit/aab1ba82d7090f4f4cb7c5ee5b990166d379f909 ))

**Environment**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.18.20+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 4
   - Disk type(e.g. SSD/NVMe): 50G
   - Network bandwidth between the nodes:

**The test steps**

1. Install Longhorn 1.0.0
2. Create 5 volumes "vol-0 ~ vol4" on longhorn
3. Create volume's PV & PVC from longhorn UI
4. Deploy pod “mypod1” via cli `kubctl apply -f pod_mount_5vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
      - mountPath: "/data2/"
        name: vol-2
      - mountPath: "/data3/"
        name: vol-3
      - mountPath: "/data4/"
        name: vol-4                                
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1        
    - name: vol-2
      persistentVolumeClaim:
        claimName: vol-2
    - name: vol-3
      persistentVolumeClaim:
        claimName: vol-3
    - name: vol-4
      persistentVolumeClaim:
        claimName: vol-4 
```
5. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash`
6. execute cli 
`dd if=/dev/urandom of=/data0/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test200m.txt count=200 bs=1M conv=fsync status=progress`

7. Upgrade Longhorn to 1.2.3
8. Upgeade volume longhorn engine to 1.2.3
9. Check upgrade status and crds yaml file
```
kubectl get crds nodes.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds engineimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backingimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backuptargets.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds volumes.longhorn.io -o yaml | grep preserveUnknownFields
```
10. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash` and execute cli 
`dd if=/dev/urandom of=/data0/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test20m.txt count=20 bs=1M conv=fsync status=progress`

11. Upgrade Longhorn to master-head
12. Upgeade volume longhorn engine to master-head
13. Check whether or not the error was printed and crds yaml
```
kubectl get crds nodes.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds engineimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backingimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backuptargets.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds volumes.longhorn.io -o yaml | grep preserveUnknownFields
```
14. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash` and execute cli 
`dd if=/dev/urandom of=/data0/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test10m.txt count=10 bs=1M conv=fsync status=progress`

**Result Pass**

After longhorn was upgraded to master-head, we didn’t observe the error symptoms.
[longhorn-support-bundle_37675047-3a93-451c-872f-545ee4bb5d12_2022-09-07T07-51-03Z.zip](https://github.com/longhorn/longhorn/files/9503965/longhorn-support-bundle_37675047-3a93-451c-872f-545ee4bb5d12_2022-09-07T07-51-03Z.zip)

Ref.
https://github.com/longhorn/longhorn/issues/1861
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027
https://github.com/longhorn/longhorn/issues/4505#issue-1356798828
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027
