### ISSUE TITLE
[BACKPORT][v1.3.2] [TASK] Update preserveUnknownFields fields in longhorn-manager CRD manifest

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4506]
## What's the task? Please describe

https://github.com/longhorn/longhorn/issues/4505

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220906**

longhorn v1.3.x-head ([cefb545](https://github.com/longhorn/longhorn/commit/cefb54500fbde5dbfe5d59c70a2d8170d1075044)) 
longhorn-manager v1.3.x-head ( [5dc4b45](https://github.com/longhorn/longhorn-manager/commit/5dc4b457cc2490089e9f96b9f8de35d572a2df2f ))

**The test steps**

1. Install Longhorn 1.1.0
2. Create 5 volumes "vol-0 ~ vol4" on longhorn
3. Create volume's PV & PVC from longhorn UI
4. Deploy pod “mypod1” via cli `kubctl apply -f pod_mount_5vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
      - mountPath: "/data2/"
        name: vol-2
      - mountPath: "/data3/"
        name: vol-3
      - mountPath: "/data4/"
        name: vol-4                                
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1        
    - name: vol-2
      persistentVolumeClaim:
        claimName: vol-2
    - name: vol-3
      persistentVolumeClaim:
        claimName: vol-3
    - name: vol-4
      persistentVolumeClaim:
        claimName: vol-4 
```
5. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash`
6. execute `dd if=/dev/urandom of=/data1/test200m.txt count=200 bs=1M conv=fsync status=progress`
7. Upgrade Longhorn to 1.2.3
8. Upgeade volume longhorn engine to 1.2.3
9. Check upgrade status and crds
```
kubectl get crds nodes.longhorn.io -o yaml 
kubectl get crds engineimages.longhorn.io -o yaml 
kubectl get crds backingimages.longhorn.io -o yaml 
kubectl get crds backuptargets.longhorn.io -o yaml 
kubectl get crds volumes.longhorn.io -o yaml
```
10. Upgrade Longhorn to 1.3.x-head
11. Upgeade volume longhorn engine to 1.3.x-head
11. Check whether or not the error was printed and crds yaml
```
kubectl get crds nodes.longhorn.io -o yaml 
kubectl get crds engineimages.longhorn.io -o yaml 
kubectl get crds backingimages.longhorn.io -o yaml 
kubectl get crds backuptargets.longhorn.io -o yaml 
kubectl get crds volumes.longhorn.io -o yaml
```

**Result Pass**

After restored, we didn’t observe the error symptoms.
[longhorn-support-bundle_941bb17c-5bee-44a5-b032-688f6b832268_2022-09-06T09-00-12Z.zip](https://github.com/longhorn/longhorn/files/9495282/longhorn-support-bundle_941bb17c-5bee-44a5-b032-688f6b832268_2022-09-06T09-00-12Z.zip)
Ref.
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027
https://github.com/longhorn/longhorn/issues/4505#issue-1356798828
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027

**Comment by Lichiehyao** [comment]
After discuss the issue with @derekbit , I need to verify this issue again.
Install Longhorn v1.0.0 > upgrade to v1.2.3 > upgrade to v1.3.x-head.

**Verified on v1.3.x-head 20220907**

longhorn v1.3.x-head ([cefb545](https://github.com/longhorn/longhorn/commit/cefb54500fbde5dbfe5d59c70a2d8170d1075044)) 
longhorn-manager v1.3.x-head ( [5dc4b45](https://github.com/longhorn/longhorn-manager/commit/5dc4b457cc2490089e9f96b9f8de35d572a2df2f ))

**Environment**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.18.20+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 4
   - Disk type(e.g. SSD/NVMe): 50G
   - Network bandwidth between the nodes:

**The test steps**

1. Install Longhorn 1.0.0
2. Create 5 volumes "vol-0 ~ vol4" on longhorn
3. Create volume's PV & PVC from longhorn UI
4. Deploy pod “mypod1” via cli `kubctl apply -f pod_mount_5vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
      - mountPath: "/data2/"
        name: vol-2
      - mountPath: "/data3/"
        name: vol-3
      - mountPath: "/data4/"
        name: vol-4                                
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1        
    - name: vol-2
      persistentVolumeClaim:
        claimName: vol-2
    - name: vol-3
      persistentVolumeClaim:
        claimName: vol-3
    - name: vol-4
      persistentVolumeClaim:
        claimName: vol-4 
```
5. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash`
6. execute cli 
`dd if=/dev/urandom of=/data0/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test200m.txt count=200 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test200m.txt count=200 bs=1M conv=fsync status=progress`
8. Upgrade Longhorn to 1.2.3
9. Upgeade volume longhorn engine to 1.2.3
10. Check upgrade status and crds yaml file
```
kubectl get crds nodes.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds engineimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backingimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backuptargets.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds volumes.longhorn.io -o yaml | grep preserveUnknownFields
```
11. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash` and execute cli 
`dd if=/dev/urandom of=/data0/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test20m.txt count=20 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test20m.txt count=20 bs=1M conv=fsync status=progress`
12. Upgrade Longhorn to 1.3.x-head
13. Upgeade volume longhorn engine to 1.3.x-head
14. Check whether or not the error was printed and crds yaml
```
kubectl get crds nodes.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds engineimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backingimages.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds backuptargets.longhorn.io -o yaml | grep preserveUnknownFields
kubectl get crds volumes.longhorn.io -o yaml | grep preserveUnknownFields
```
15. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash` and execute cli 
`dd if=/dev/urandom of=/data0/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data1/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data2/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data3/test10m.txt count=10 bs=1M conv=fsync status=progress`
`dd if=/dev/urandom of=/data4/test10m.txt count=10 bs=1M conv=fsync status=progress`

**Result Pass**

After longhorn was upgraded to 1.3.x-head, we didn’t observe the error symptoms.


Ref.
https://github.com/longhorn/longhorn/issues/1861
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027
https://github.com/longhorn/longhorn/issues/4505#issue-1356798828
https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027
