### ISSUE TITLE
[BUG] Prometheus metric for backup state (longhorn_backup_state) returns wrong values

### ISSUE THREAD

**Issue by pwurbs** [longhorn/longhorn#4521]
## Describe the bug

According to https://github.com/longhorn/longhorn/issues/2940, a query of metric "longhorn_backup_state" should return these values:
0=New, 1=InProgress, 2=Completed, 3=Error, 4=Unknown
But I get value 3 for all of my obviously successful backups.

## To Reproduce

1. Setup recurring backup job with S3 backup target
2. Query Prometheus 
<html><body>

longhorn_backup_state{backup="backup-002d70d978324b2e", container="longhorn-manager", endpoint="manager", instance="10.42.5.95:9500", job="longhorn-backend", namespace="longhorn-system", pod="longhorn-manager-pj7kp", service="longhorn-backend", volume="pvc-b95ebb95-69a8-402a-ad4c-600fb4372ad3"} | 3
-- | --

</body>
</html>
3. Check backup status in Longhorn UI
<html><body>

backup-002d70d978324b2e | pvc-b95ebb95-69a8-402a-ad4c-600fb4372ad3 | Completed
-- | -- | --

</body>
</html>

--> So, there is a mismatch between expected and actual return value.

## Expected behavior

I expect, that according to documentation a metrics value of 2 is returned for a completed backup.

## Environment

 - Longhorn version: 1.3.1
 - Installation method: Rancher Catalog App/Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE1, v1.22.11
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure: CentOS VMs from OpenTelekomCloud
 - Number of Longhorn volumes in the cluster: 114

**Comment by innobead** [comment]
@mantissahz It seems like a doc issue, and also the original doc PR (https://github.com/longhorn/website/commit/9d8ce1e8) was missed from 1.3.0 & 1.3.1.

Please help with this doc fix. Thanks.

**Comment by pwurbs** [comment]
@innobead What is the correct status code meaning? Thx.

**Comment by innobead** [comment]
> @innobead What is the correct status code meaning? Thx.

https://github.com/longhorn/longhorn-manager/blob/127a37f605b13e133a547dfc89470cf3670e2236/metrics_collector/backup_collector.go#L88-L105

3 means completed.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220916**

- longhorn master-head ([bfe44af](https://github.com/longhorn/longhorn/commit/bfe44afdf880007c55bc6530f592e1b2562e7571)) 
- longhorn-manager master-head( [3ebeaf2](https://github.com/longhorn/longhorn-manager/commit/3ebeaf2046da30ce4362e0c1e18540f45aa22caf))

	
**Pre-requisite**

1. Install Rancher
2. Create cluster
3. Install Monitoring via Rancher APP.
4. install Longhorn via kubectl

**The test steps**

1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX)
`kubectl apply -f create_2vol_rwx+rwo.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
```
2. Volume attach to the pod. Deploy pod `mypod1`
`kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1      
```
3. Create backups for each volumes
4. In the Rancher UI > Monitoring > grafana > grafana login 
**** The default Admin username and password for the Grafana instance is admin/prom-operator ****
5. check backups status and Query Prometheus 


**Result Passed**

1. After query prometheus, we could find out value 0, 2, 3 on  grafana UI
2. The documents are updated on ([v1.3.0](https://longhorn.io/docs/1.3.0/monitoring/metrics/)) ([v1.3.1](https://longhorn.io/docs/1.3.1/monitoring/metrics/)) ([v1.4.0](https://longhorn.io/docs/1.4.0/monitoring/metrics/)) 
![Screenshot_20220916_162945](https://user-images.githubusercontent.com/104337648/190600158-015874ed-8ade-4382-95f6-75d0725e5330.png)
