### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] The default access mode of a restored RWX volume is RWO 

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4528]
## Describe the bug
backport https://github.com/longhorn/longhorn/issues/3444

**Comment by Lichiehyao** [comment]
**Verified on v1.3.x-head 20220915**

- longhorn v1.3.x-head ([cefb545](https://github.com/longhorn/longhorn/commit/cefb54500fbde5dbfe5d59c70a2d8170d1075044)) 
- longhorn-manager v1.3.x-head ([9a5807f](https://github.com/longhorn/longhorn-manager/commit/9a5807f2141fc064579bfc12a2d41cd9b4cd0f51))

**The test steps**
***Scenario 1***
1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX)
`kubectl apply -f create_2vol_rwx+rwo.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
```
2. Volume attach to the pod. Deploy pod `mypod1`
`kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1      
```
3. Create backups for each volumes
4. Wait all backups are complete, then delete all volumes.
5. Switch to `Backup` page, and click the backup name and the tags filed.
6. Select all backups and click Restore Latest Backup button without changing any parameters during the restore
7. Switch back to Volume page and click the name filed.
8. CHECK: The access mode should be same as the volume's backup.

***Scenario 2***
1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX)
`kubectl apply -f create_2vol_rwx+rwo.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
```
2. Volume attach to the pod. Deploy pod `mypod1`
`kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1      
```
3. Wait all backups are complete, then delete all volumes.
4. Switch to `Backup` page, and click the backup name and the tags filed. 
5.1 Select `ReadWriteOnce` backup volumes and set the access mode as `ReadWriteMany` 
5.2 Select `ReadWriteMany` backup volumes and set the access mode as `ReadWriteOnce`
6. Switch back to Volume page and click the name filed.
7.1 The `ReadWriteOnce` backup volumes access mode should be `ReadWriteMany` volume
7.2 The `ReadWriteMany` backup volumes access mode should be `ReadWriteOnce` volume

**Result Passed**
