### ISSUE TITLE
[BUG] share-manager-pvc keep restarting

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4551]
## Describe the bug

Following the [[IMPROVEMENT] Dump NFS ganesha logs to pod stdout](https://github.com/longhorn/longhorn/issues/2380) test steps.
When deploying the POD and mounting RWX PVC volume, observe share-manager-pvc keep restarting.

## To Reproduce

1. Install Longhorn Master Ref.([install-with-kubectl](https://longhorn.io/docs/1.4.0/deploy/install/install-with-kubectl/))
    longhorn-share-manager [v1_20220825](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220825)
2. Create rwx volume and attach to pod. Deploy pod “mypod1”
`kubectl apply -f pod_with_pvc.yaml`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

3. Check pod `volume-test` and `share-manager-pvc-9174f488-1425-421f-9017-c45afc178000` status.
4. `share-manager-pvc-9174f488-1425-421f-9017-c45afc178000` pods will keep loop at `ContainerCreating` -> `Running` -> `Terminating`
![Screenshot_20220913_200447](https://user-images.githubusercontent.com/104337648/189903300-2aa529e8-3f4e-4bb3-bdd6-ce76b2b224c7.png)
## Expected behavior

pod `volume-test` and `share-manager-pvc-9174f488-1425-421f-9017-c45afc178000` should ready.

## Log or Support bundle
[longhorn-support-bundle_06960eb3-f5c9-490f-9f38-0c35e4e9ddba_2022-09-13T12-04-23Z.zip](https://github.com/longhorn/longhorn/files/9557095/longhorn-support-bundle_06960eb3-f5c9-490f-9f38-0c35e4e9ddba_2022-09-13T12-04-23Z.zip)

## Environment

 - Longhorn version:
   - longhorn master-head ([8c87681](https://github.com/longhorn/longhorn/commit/8c876810bcf36a1c7222b59cf8fce49e16a44373)) 
   - longhorn-share-manager [v1_20220825](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220825) ( [2cba526](https://github.com/longhorn/longhorn-share-manager/commit/2cba526a55368a7f5f263b204d87b39836855dff))
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS / KVM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

https://github.com/longhorn/longhorn/issues/2380
