### ISSUE TITLE
[IMPROVEMENT] add possibility to use nodeSelector on the storageClass

### ISSUE THREAD

**Issue by msoGTA** [longhorn/longhorn#4574]
## Is your improvement request related to a feature? Please describe

In order to mount the volume only on the necesary nodes. It is useful to add the possibility to use nodeSelector with the storageClass template like in the documentation.

https://longhorn.io/docs/1.3.1/volumes-and-nodes/storage-tags/

## Describe the solution you'd like

Editing the storageClass.yaml file and the values.yaml file in order to offer this possibility.

Once done, the users could enable this feature and on the UI or within the K8s cluster directly tag the nodes like in the documentation below.

https://longhorn.io/docs/1.4.0/advanced-resources/default-disk-and-node-config/#adding-node-tags-to-new-nodes

**Comment by Lichiehyao** [comment]
Hi @weizhe0422 :
     https://github.com/longhorn/website/pull/591 is not merged yet.

**Comment by weizhe0422** [comment]
Hi @roger-ryao, 

Since longhorn/website#591 has been merged, I changed the issue status to Ready for Testing. 

Thanks a lot!

**Comment by roger-ryao** [comment]
**Verified on master-head 20221117**

- longhorn master-head ([dab0603](https://github.com/longhorn/longhorn/commit/dab06038476c337266936b0fe47a5f0ae0cdaed7)) 
- longhorn-manager master-head ([ed1f742](https://github.com/longhorn/longhorn-manager/commit/ed1f74273fb2d86d85d910ec7a08e2654f477536)) 


**The test steps**

[Ref #4574 (To Reproduce)](https://github.com/longhorn/longhorn/issues/4574#issuecomment-1263185329)

- 1. Add annotation with kubectl `kubectl annotate node <node-name> node.longhorn.io/default-node-tags='["medium"]'`
- 2. Download the latest [helm chart](https://github.com/longhorn/longhorn/tree/master/chart). And 
   edit the `values.yaml` in the PATH `/longhorn/chart`
   and adjust the `persistence.defaultNodeSelector` section like below
    ```yaml
    defaultNodeSelector:
        enable: true # disable by default
        selector: "medium"
    ```
- 3. Install Longhorn via Helm:  `helm install longhorn . --namespace longhorn-system --create-namespace`
- 4. Type `kubectl get sc longhorn -n longhorn-system -o yaml` to check the storageclass has `nodeSelector: "medium"` text
![Screenshot_20221117_155248](https://user-images.githubusercontent.com/104337648/202388279-bba287f6-0159-41e2-abb1-7961152780a6.png)

- 5. Create and deploy customized PVC: `kubectl apply -f longhorn-sc-with-label-pvc`

<details>
<summary>longhorn-sc-with-label-pvc</summary>

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-sc-with-label-pvc
      namespace: longhorn-system
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ```
</details>


- 6. Create and deploy pod: `kubectl apply -f task-pv-pod`

<details>
<summary>task-pv-pod</summary>

   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     name: task-pv-pod
     namespace: longhorn-system
   spec:
     volumes:
       - name: task-pv-storage
         persistentVolumeClaim:
           claimName: longhorn-sc-with-label-pvc
     containers:
       - name: task-pv-container
         image: nginx
         ports:
           - containerPort: 80
             name: "http-server"
         volumeMounts:
           - mountPath: "/usr/share/nginx/html"
             name: task-pv-storage
   ```
</details>


**Result Passed**

The Longhorn volume was generated and the replica was generated on the target node with the annotation
![Screenshot_20221117_155843](https://user-images.githubusercontent.com/104337648/202390009-1a565dfd-34ef-4a22-a041-dce3d7265861.png)
