### ISSUE TITLE
[Improvement] Using specific block size in Longhorn volume's filesystem

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4594]
## What's the task? Please describe

For the [filesystem corruption](https://github.com/longhorn/longhorn/issues/3597) issue, we have a [solution](https://github.com/longhorn/longhorn-engine/pull/745) addressing the issue.

To further avoid the extra data retrieval from RW replicas when user use our supported fs volume (ext4, xfs), we can set the block size of the filesystem on a newly created longhorn volume to a specific block size (4096 bytes).

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

https://github.com/longhorn/longhorn/issues/3597#issuecomment-1251802416

**Comment by derekbit** [comment]
## Pre Ready-For-Testing Checklist
* [ ] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:

* [ ] Is there a workaround for the issue? If so, where is it documented?
The workaround is at:

* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Does the PR include deployment change (YAML/Chart)? If so, where are the PRs for both YAML file and Chart?
The PR for the YAML change is at:
The PR for the chart change is at:

* [ ] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at https://github.com/longhorn/longhorn-manager/pull/1495

* [ ] Which areas/issues this PR might have potential impacts on?
Area: replica, csi, filesystem
Issues

**Comment by derekbit** [comment]
We will adress this issue in https://github.com/longhorn/longhorn/issues/4599 by setting the iSCSI LUN block size to 4096.

**Comment by innobead** [comment]
We can add an explanation to https://longhorn.io/docs/<version>/volumes-and-nodes/create-volumes/ to describe how block size will be determined in different cases. 

Also, mention the change in https://longhorn.io/docs/<version>/deploy/important-notes/ to highlight this new introduction/change.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220930**

- longhorn master-head ([41b92af](https://github.com/longhorn/longhorn/commit/41b92af023ab92061ecdf04a6914325fe32904d5)) 
- longhorn-manager master-head( [350c921](https://github.com/longhorn/longhorn-manager/commit/350c921e6e8b15007a364f92f514c7bc1c40248d))

	
**Pre-requisite**

1. Install Longhorn 1.3.1 via kubectl
2. Create volume **vol-0-ext4** and  **vol-0-xfs**
3. Create volume **vol-0-ext4** PV/PVC with fsType **ext4**
4. Create volme **vol-0-xfs** PV/PVC with fsType **xfs**
5. Create a pod  **mypod1** with pvc on the worker node-1 `kubectl apply -f pod_mount_2vol.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: ryao-lh-13x-pool2-c78392ea-69r2v  # worker node
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0-ext4
      - mountPath: "/data1/"
        name: vol-0-xfs
  volumes:
    - name: vol-0-ext4
      persistentVolumeClaim:
        claimName: vol-0-ext4
    - name: vol-0-xfs
      persistentVolumeClaim:
        claimName: vol-0-xfs    
```
6. Delete pod with PVC `kubectl apply -f pod_mount_2vol.yaml`
7. Attach volume **vol-0-ext4** and **vol-0-xfs** to worker node-1
8. ssh to worker node-1 and  check the iSCSI LUN block size and filesystem block size
```
# ext4
blockdev --getss /dev/sda
tune2fs -l /dev/sda | grep "Block size"

# xfs
blockdev --getss /dev/sdb
xfs_info /dev/sdb
```
10. Create a pod with pvc on the worker node-1 again `kubectl apply -f pod_mount_2vol.yaml`
11. Enter **mypod1** shell mode and write data to volume `kubectl exec -it mypod1 -- /bin/bash`
```
dd if=/dev/urandom of=/data0/20M.txt count=20 bs=1M conv=fsync status=progress
dd if=/dev/urandom of=/data1/20M.txt count=20 bs=1M conv=fsync status=progress
```
12. Record md5 
```
md5sum /data0/20M.txt
md5sum /data1/20M.txt
```
**The test steps**
1. Upgrade Longhorn to master-head
2. Check the data md5 again
3. Delete pod with PVC `kubectl apply -f pod_mount_2vol.yaml`
4. Detach volume **vol-0-ext4** and **vol-0-xfs**
5. Attach volume **vol-0-ext4** and **vol-0-xfs** to worker node-1
6. ssh to worker node-1 and check the iSCSI LUN block size and filesystem block size again.
7. Create a pod **mypod1** with pvc on the worker node-1 again `kubectl apply -f pod_mount_2vol.yaml`
8. Check the data md5 again
9. Enter **mypod1** shell mode and write data to volume `kubectl exec -it mypod1 -- /bin/bash`
```
dd if=/dev/urandom of=/data0/25M.txt count=25 bs=1M conv=fsync status=progress
dd if=/dev/urandom of=/data1/25M.txt count=25 bs=1M conv=fsync status=progress
```
10. Create volume **vol-1-ext4** and  **vol-1-xfs**
11. Create volume **vol-1-ext4** PV/PVC with fsType **ext4**
12. Create volme **vol-1-xfs** PV/PVC with fsType **xfs**
13. Create a pod  **mypod2** with pvc on the worker node-1 `kubectl apply -f pod_mount_2vol_upgrade.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod2
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: ryao-lh-13x-pool2-c78392ea-69r2v  # worker node
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-1-ext4
      - mountPath: "/data1/"
        name: vol-1-xfs
  volumes:
    - name: vol-1-ext4
      persistentVolumeClaim:
        claimName: vol-1-ext4
    - name: vol-1-xfs
      persistentVolumeClaim:
        claimName: vol-1-xfs        

```
14. Delete pod with PVC `kubectl apply -f pod_mount_2vol_upgrade.yaml`
15. Attach volume **vol-1-ext4** and **vol-1-xfs** to worker node-1
16. ssh to worker node-1 and  check the iSCSI LUN block size and filesystem block size

**Result Passed**
1. After upgraded, the the iSCSI LUN block size and filesystem block size were same.
2. The volume could be detached and reattached again. 
3. The old Volume was also accessible and the files in the volume were also correct (checked by the checksum)
4. The new volume's iSCSI LUN block size and filesystem block size was expected.
![Screenshot_20220930_115702](https://user-images.githubusercontent.com/104337648/193194719-094a0a5b-c318-4c5a-80ce-a970cfb12793.png)
