### ISSUE TITLE
[TASK] Support managed K8s distro into testing pipelines

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4621]
## What's the task? Please describe

Allow running tests on EKS/AKS/GKE on demand. 

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

cc @longhorn/qa

**Comment by yangchiu** [comment]
Currently working on implementing EKS pipeline. The EKS cluster can be created by terraform, but:

(1) EKS doesn't provide a way to generate a permanent token to authorize k8s api server, instead it keeps getting a temporary token which will expire after 15 minutes:
```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - lh-tests-ohmi4p49-cluster
      command: aws 
```
Need to figure out a way to generate a permanent token to run our test.

(2) CI account doesn't have permission to create IAM policy for cluster autoscaler https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#iam-policy, need to investigate more before requesting permission.
