### ISSUE TITLE
[BUG] [v1.2.x] The volume's failed replica would not be automatically removed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#4724]
## Describe the bug

After verified the issue [#4696](https://github.com/longhorn/longhorn/issues/4696#issuecomment-1278706196), I find out that. After rebooted the worker node, the volume had 1 healthy replica + 2 unscheduled (N/A) replicas + 2 unscheduled (Failed). The failed replica would not be removed on the build 1.2.x. 
I didn't observe this symption on the **build 1.3.2** and **master-head**. 

## To Reproduce

1. Create a cluster of 1 control node and 1 worker node.
2. Deploy Longhorn 1.2.x Keep every Longhorn settings has default
3. Deploy a test deployment that use pvc provisioned by Longhorn
`kubectl apply -f deployment.yaml`
<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>

4. Observe that there is currently only 1 replica of the volume is scheduled on the worker node. The other 2 replicas are unschedule
5. Restart the worker node

## Expected behavior

After the worker node and pod are online, the failed replica should be automatically removed.

## Log or Support bundle

[longhorn-support-bundle_46143156-4bd7-4134-bf3c-f1011e2ea1bd_2022-10-17T07-13-18Z.zip](https://github.com/longhorn/longhorn/files/9797786/longhorn-support-bundle_46143156-4bd7-4134-bf3c-f1011e2ea1bd_2022-10-17T07-13-18Z.zip)
![Screenshot_20221017_151029](https://user-images.githubusercontent.com/104337648/196112934-65b2d782-283c-45f6-9fef-ee5350b6e3fb.png)
![Screenshot_20221017_151053](https://user-images.githubusercontent.com/104337648/196112951-f517ea7d-1ecb-4858-9fc8-6806cef7512a.png)

## Environment

 - Longhorn version: 1.2.x-head 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: ubunbu 20.04
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2
 - Number of Longhorn volumes in the cluster: two

## Additional context

https://github.com/longhorn/longhorn/issues/4696#issuecomment-1278706196
