### ISSUE TITLE
[TASK] Release 1.2.6

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4751]
**What's the task? Please describe.**
Action items for releasing v1.2.6

**Describe the items of the task (DoD, definition of done) you'd like.**
  - Pre-Release
    - [x] Run e2e regression for pre-GA milestones (`install`, `upgrade`) - @yangchiu 
    - [x] Run security testing of container images for pre-GA milestones - @yangchiu 
    - [x] Verify longhorn chart PR to ensure all artifacts are ready for GA (`install`, `upgrade`)  @cchien816 
       - https://github.com/longhorn/longhorn/pull/4816 (`longhorn/longhorn`)
       - https://github.com/longhorn/charts/pull/81 (`longhorn/charts`)
    - [x] Run core testing (install, upgrade) for GA build from the previous patch and the last patch of the previous feature release (1.1.3). - @roger-ryao 
  - Release
    - [x] Release longhorn/chart from the release branch to publish to ArtifactHub
    - [x] Release note
	     - [x] Deprecation note
	     - [x] Upgrade notes including highlighted notes, deprecation, compatible changes, and others impacting the current users
  - Post-Release
    - [ ] ~Create a new release branch of manager/ui/tests/engine/longhorn instance-manager/share-manager/backing-image-manager~
    - [x] Update https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml @PhanLe1010 
	- [x] Add another request for the rancher charts for the next release (`1.2.7`) @rebeccazzzz  
  - Rancher charts: verify the chart is able to install & upgrade - @khushboo-rancher 
    - [x] rancher/image-mirrors update @PhanLe1010 
        - https://github.com/rancher/image-mirror/pull/311
    - [x] rancher/charts master branch for rancher catalog @PhanLe1010 @weizhe0422 (special fix)
        - https://github.com/rancher/charts/pull/2196
    - [x] rancher/charts dev-2.6 & 2.7 branches for rancher marketplace @PhanLe1010 @weizhe0422 
        - `dev-2.6`: https://github.com/rancher/charts/pull/2197
        - `dev-2.7`: https://github.com/rancher/charts/pull/2195

cc @longhorn/qa

**Comment by roger-ryao** [comment]
**Scenario 1**
1. Fresh install v1.2.6 GA
2. Create deployment `kubectl apply -f statefulset.yaml`
<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

3. Create deployment `kubectl apply -f deployment.yaml`
<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>

4. write data
5. Scale down/up deployment
6. Test replica rebuilding
7. verify data
8. Uninstall

---
**Scenario 2**

1. Fresh install v1.1.3 / 1.2.5
2. Create deployment `kubectl apply -f statefulset.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

3. Create deployment `kubectl apply -f deployment.yaml`
<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>

4. Write data
5. Upgrade to v1.2.6 GA
6. Scale down/up deployment
7. Test replica rebuilding
8. verify data
9. Uninstall
