### ISSUE TITLE
[BUG] FailedAttachVolume DeadlineExceeded when creating large volumes

### ISSUE THREAD

**Issue by tnet-ag** [longhorn/longhorn#4768]
## Describe the bug

env k8 cluster with 2 nodes

On the cluster node2 is a 32 TB HDD (RAID 5 4x 16TB)

Its added as a Disk in the Longhorn UI (Scheduling on)
And I can see it as available space on the dashboard (-> 29.3 Ti)

Unfortually I am not able to create a PVC in that full size

The pod get stuck in ContainerCreating and kubectl describe shows the following error

` Warning  FailedAttachVolume  3s (x5 over 13s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f5c3f16d-b41a-4cc2-8934-40abb639437b" : rpc error: code = DeadlineExceeded desc = volume pvc-f5c3f16d-b41a-4cc2-8934-40abb639437b failed to attach to node node2
`

In the Longhorn UI the Volume is stuck in state attaching forever

-----

**Tried to reduce the size of the volumes and It works fine up to 15 Ti 
The pvc is attached to the desired node**

Tried also to increase the spec.activeDeadlineSeconds  in the pod config to 300+ -> no effect

## To Reproduce

Here my test setup

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 28Ti # DO'ES WORK UP TO 15Ti

---

apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: minio
spec:
  containers:
      - name: my-container
        image: busybox
        command: ["sleep", "100000"]

        volumeMounts:
          - mountPath: "/opt/minio"
            name: minio-pv-storage

  restartPolicy: Never
  volumes:
      - name: minio-pv-storage
        persistentVolumeClaim:
          claimName: minio-pvc
  nodeSelector:
    kubernetes.io/hostname: node2
```

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm/flux
  
helm custom values:  
```
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1

```
