### ISSUE TITLE
[DOC] Explanation of storage class parameters

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4776]
## Is your improvement request related to a feature? Please describe

Add a doc to explain parameters in the storage class supported by Longhorn.

[storage class parameters](https://github.com/longhorn/longhorn/blob/53c9c407ed8238a9b7217a4713b3e17fd84c6c29/chart/templates/storageclass.yaml#L20-L41)
```yaml
      numberOfReplicas: "{{ .Values.persistence.defaultClassReplicaCount }}"
      staleReplicaTimeout: "30"
      fromBackup: ""
      {{- if .Values.persistence.defaultFsType }}
      fsType: "{{ .Values.persistence.defaultFsType }}"
      {{- end }}
      {{- if .Values.persistence.migratable }}
      migratable: "{{ .Values.persistence.migratable }}"
      {{- end }}    
      {{- if .Values.persistence.backingImage.enable }}
      backingImage: {{ .Values.persistence.backingImage.name }}
      backingImageDataSourceType: {{ .Values.persistence.backingImage.dataSourceType }}
      backingImageDataSourceParameters: {{ .Values.persistence.backingImage.dataSourceParameters }}
      backingImageChecksum: {{ .Values.persistence.backingImage.expectedChecksum }}
      {{- end }}
      {{- if .Values.persistence.recurringJobSelector.enable }}
      recurringJobSelector: '{{ .Values.persistence.recurringJobSelector.jobList }}'
      {{- end }}
      dataLocality: {{ .Values.persistence.defaultDataLocality | quote }}
      {{- if .Values.persistence.defaultNodeSelector.enable }}
      nodeSelector: "{{ .Values.persistence.defaultNodeSelector.selector }}"
      {{- end }}
```

## Additional context

https://github.com/longhorn/website/pull/591#pullrequestreview-1142295370
[Issue 4574](https://github.com/longhorn/longhorn/issues/4574)
