### ISSUE TITLE
[BUG] Illegal versioning scheme in Helmchart >= 1.3.2

### ISSUE THREAD

**Issue by Brice187** [longhorn/longhorn#4811]
## Describe the bug

```yaml
apiVersion: v1
appVersion: v1.3.2
description: Longhorn is a distributed block storage system for Kubernetes.
home: https://github.com/longhorn/longhorn
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
keywords:
- longhorn
- storage
- distributed
- block
- device
- iscsi
- nfs
kubeVersion: '>=1.18.0-0 <1.25.0-0'
maintainers:
- email: maintainers@longhorn.io
  name: Longhorn maintainers
name: longhorn
sources:
- https://github.com/longhorn/longhorn
- https://github.com/longhorn/longhorn-engine
- https://github.com/longhorn/longhorn-instance-manager
- https://github.com/longhorn/longhorn-share-manager
- https://github.com/longhorn/longhorn-manager
- https://github.com/longhorn/longhorn-ui
- https://github.com/longhorn/longhorn-tests
- https://github.com/longhorn/backing-image-manager
version: 1.3.2
```

The kubeVersion has to follow **SemVer** (https://helm.sh/docs/topics/charts/#the-kubeversion-field)

The wrong scheme breaks my ArgoCD Deployment (see **Log Bundle**).

## Expected behavior

The Chart.yaml should use following versioning scheme:
```
kubeVersion: >= 1.18.0 < 1.25.0
```

I expect the correct versioning scheme will not break my setup

## Log or Support bundle

```
time="2022-11-02T11:20:31Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-11-02T11:20:31Z\",\"message\":\"rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build .dev/misc/longhorn --enable-helm --load-restrictor LoadRestrictionsNone` failed exit status 1: Error: Error: chart requires kubeVersion: \\u003e=1.18.0-0 \\u003c1.25.0-0 which is incompatible with Kubernetes v1.25.0\\n\\nUse --debug flag to render out invalid YAML\\n: unable to run: 'helm template longhorn --namespace longhorn-system .dev/misc/longhorn/charts/longhorn --values /tmp/kustomize-helm-1430322709/longhorn-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1430322709/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1430322709/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1430322709/helm/.data] (is 'helm' installed?)\",\"type\":\"ComparisonError\"}]}}" application=argocd/longhorn-dev
```

## Environment

 - Longhorn version: 1.3.2
 - Installation method: Helm
 - Kubernetes distro:  K3s v1.24.7
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Underlying Infrastructure: Baremetal
