### ISSUE TITLE
[IMPROVEMENT] Add support for crypto parameters for RWX volumes

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#4829]
## Is your improvement request related to a feature? Please describe

In https://github.com/longhorn/longhorn/issues/3353 we add support for specifying additional crypto parameters for the created volume, this is useful to support FIPS mode as well as embedded systems which might prefer a non default hash/keyderivation function.

## Describe the solution you'd like

One can specify the secret as part of a volume mount, instead of using the env var for the passphrase directly.
Then modify the share-manager process to read and process the parameters from the secret file similiar to the csi plugin.

I eventually want to move the crypto related code into a utils module/package independent from the share-manager / longhorn-manager since they are duplicated at the moment. But we can do that later as well once we have identified other duplicated code functions in the manager, instance-manager, engine, replica code.

## Describe alternatives you've considered

pass the crypto parameters directly, this would work but it's better if the determination is based on the secret since it's the identical process in the csi plugin.

## Additional context

#4784

**Comment by roger-ryao** [comment]
**Verified on master-head 20230601**

- longhorn master-head https://github.com/longhorn/longhorn/commit/ffaa3d2113c2a47008e790df5bccf572f28025a3
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/2a83384208c88904bba67202c5d55b1d36dc6ea3
- longhorn-share-manager master-head https://github.com/longhorn/longhorn-share-manager/commit/c996c5a415b63e599c2d24e7d49ad609d0686ae5

**The test steps**
1. Create a secret such as [secret.yaml](https://github.com/longhorn/longhorn/blob/master/examples/crypto/secret-crypto-customized.yaml) and [storageclass](https://github.com/longhorn/longhorn/blob/master/examples/crypto/storageclass-crypto-global.yaml) that use this secret. Reference: [Volume Encryption](https://longhorn.io/docs/1.5.0/advanced-resources/security/volume-encryption/)

2. Create a deployment with a `RWX` PVC using the storage class created.

<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always    
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```

3. Check if the workload works normally.
4. Check the encryption setup on the worker node volume was attached to by running the following command:
`cryptsetup status [pv-name]`

5. Modify [secret.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-customized.yaml) by changing the `CRYPTO_KEY_CIPHER` to either `aes-cbc-essiv:sha256` or `twofish-xts-plain64`.
6. Repeat steps 2 to 4.
7. Check if the configuration has changed.


**Result Passed**

![Screenshot_20230601_163908](https://github.com/longhorn/longhorn/assets/104337648/1bfba9d9-b2a2-4d55-acd5-4651e66a4d53)

![Screenshot_20230601_163859](https://github.com/longhorn/longhorn/assets/104337648/ad106853-49b5-486e-acf9-4d2880cd999b)
