### ISSUE TITLE
[FEATURE] Deploy Longhorn via ArgoCD

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4853]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Longhorn should support ArgoCD deployment. The issue is from https://github.com/longhorn/longhorn/discussions/4790

**Comment by b34rd-tek** [comment]
You can deploy Longhorn via argocd using helm. In the issue you linked there is a solution example.

**Comment by weizhe0422** [comment]
I try to install Longhorn v1.4.1 via Helm on ArgoCD v2.6.7, and it can be installed well.

<img width="711" alt="截圖 2023-04-17 下午3 15 11" src="https://user-images.githubusercontent.com/17548901/232411816-b9b1a824-be9f-42d3-9ddf-76b3e74da8ca.png">
<img width="1186" alt="截圖 2023-04-17 下午3 12 26" src="https://user-images.githubusercontent.com/17548901/232411182-d5f1f57a-dac6-4056-b87b-f7dee428e59e.png">

**Comment by MohammedNoureldin** [comment]
Version 1.5.1 seems to be not working?

> Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn-system/longhorn-service-account: serviceaccount "longhorn-service-account" not found

**Comment by mantissahz** [comment]
>Version 1.5.1 seems to be not working?

@MohammedNoureldin,
Yes, not tackled with v1.5.1.
At v1.5.2, the pre-upgrade hook can be disabled by setting helmPreUpgradeCheckerJob.enbaled false.

**Comment by innobead** [comment]
This will be supported in 1.6 and 1.5.4. https://github.com/longhorn/longhorn/issues/6415

**Comment by MohammedNoureldin** [comment]
Does the 1.6.0 have the same issue again? I see this issue again

> 
Version 1.5.1 seems to be not working?

Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn-system/longhorn-service-account: serviceaccount "longhorn-service-account" not found

**Comment by jenneron** [comment]
seems to be happening again on 1.6.2

`Warning  FailedCreate  1s (x5 over 16s)  job-controller  Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn-system/longhorn-service-account: serviceaccount "longhorn-service-account" not found`

<details>

<summary>Application manifest</summary>

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: "1.6.2"
    helm:
      releaseName: longhorn
      valuesObject:
        csi:
          # set microk8s-specific kubelet path
          kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet"
          provisionerReplicaCount: 3
          resizerReplicaCount: 3
          snapshotterReplicaCount: 3
        defaultSettings:
          defaultReplicaCount: 3
          createDefaultDiskLabeledNodes: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
      limit: 3
    syncOptions:
    - CreateNamespace=true
```

</details>
