### ISSUE TITLE
[BUG] Failed to use storage network

### ISSUE THREAD

**Issue by juixtu** [longhorn/longhorn#4937]
## Describe the bug (🐛 if you encounter this issue)

I used multus in the kubernetes cluster and created a NetworkAttachmentDefinition. After configuring the storage network in longhorn, I can see that the image-instance pod is restarted, and I can view the corresponding `k8s.v1.cni.cncf.io/networks-status` annotations, However, after creating the volume and performing the attach operation, the following error appears in the longhorn-manager log：

```
time="2022-11-24T17:58:44Z" level=warning msg="Missing k8s.v1.cni.cncf.io/networks-status annotation, use instance-manager-r-f3ec5c07 pod IP 10.42.0.11"
--
Fri, Nov 25 2022 1:58:44 am | time="2022-11-24T17:58:44Z" level=debug msg="Instance haha-r-52b690a3 starts running, Storage IP 10.42.0.11"
Fri, Nov 25 2022 1:58:44 am | time="2022-11-24T17:58:44Z" level=debug msg="Instance haha-r-52b690a3 starts running, IP 10.42.0.11"
Fri, Nov 25 2022 1:58:44 am | time="2022-11-24T17:58:44Z" level=debug msg="Instance haha-r-52b690a3 starts running, Port 10000"
```
The storage IP does not take effect.

## Environment

 - Longhorn version: v1.3.2
 - kubernetes version: v1.22.15
 - Rancher version: 2.6.9 (Use Rancher deploy Longhorn)

## multus configure

NetworkAttachmentDefinition：

```yaml
kind: NetworkAttachmentDefinition
metadata:
  name: demo-192-168-6-0
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens33",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.6.0/24",
        "rangeStart": "192.168.6.180",
        "rangeEnd": "192.168.6.250",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.6.2"
      }
    }'
```

Passing a simple daemonset test, the extra network interface added by multus can communicate across nodes normally

## Instance-manager status after configuring the storage network

![image](https://user-images.githubusercontent.com/29482142/203846400-0bd3f83d-45f4-49a2-b727-c3a4df4c4a9b.png)

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
@juixtu can you provide the support bundle?

**Comment by 2c9** [comment]
- kubernetes: v1.24.8
- longhorn: v1.3.0
- multus: v4.0

Network definition:
```bash
root@supermicro1:~# kubectl -n kube-system get network-attachment-definitions.k8s.cni.cncf.io storage-macvlan -o yaml
```
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage-macvlan
  namespace: kube-system
spec:
  config: '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "eno2", "mode": "bridge",
    "ipam": { "type": "dhcp" } }'
```

All pods have ip addresses and connectivity. Here is example:

```bash
root@supermicro1:~# kubectl -n longhorn-system get pod -l longhorn.io/component=instance-manager -o json | jq '.items[] | .metadata | { pod: .name, node: .labels."longhorn.io/node", ips: [ .annotations."k8s.v1.cni.cncf.io/network-status" | fromjson[] | .ips | add ] } | select(.node=="supermicro1")'
```
```json
{
  "pod": "instance-manager-e-1866ea90",
  "node": "supermicro1",
  "ips": [
    "10.233.125.48",
    "172.16.99.239"
  ]
}
{
  "pod": "instance-manager-r-b71c0ee5",
  "node": "supermicro1",
  "ips": [
    "10.233.125.47",
    "172.16.99.236"
  ]
}
```

- multus: v4.0 Thick Plugin: The same issue "Missing k8s.v1.cni.cncf.io/networks-status annotation ... "
- multus: v4.0 Thin Plugin: 

```bash
root@supermicro1:~# kubectl  -n longhorn-system logs longhorn-manager-cnd5s | grep -i storage
time="2022-12-12T08:56:21Z" level=debug msg="Instance test-r-6e113a36 starts running, Storage IP 172.16.99.236"
time="2022-12-12T08:56:24Z" level=debug msg="Instance test-e-11429f2e starts running, Storage IP 172.16.99.239"
```
