### ISSUE TITLE
[BUG] PVC only works with plural annotation `volumes.kubernetes.io/storage-provisioner: driver.longhorn.io`

### ISSUE THREAD

**Issue by R-Studio** [longhorn/longhorn#4951]
## Describe the bug (🐛 if you encounter this issue)
When I create a PVC (for example by an restore or manually create one), the PVCs are created but get stuck in the `Pending` state and the PV will never be created. _I noticed this bug by try to restore PVC from an Velero backup._

## To Reproduce
1. Create a PVC, the following example that dind't work (stuck in `Pending`):
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: harbor
  name: harbor-registry-manual
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeMode: Filesystem
```

**-> But if I change the annotation `volume.kubernetes.io/storage-provisioner: driver.longhorn.io` to `volumes.kubernetes.io/storage-provisioner: driver.longhorn.io` then it works (the PVC changes its state to `Bound`).**

## Expected behavior
After a short time, the PV will be created and the PVC changes its state to `Bound`.

## Environment
 - Longhorn version: v1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Helm Chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2, v1.24.4+rke2r1
   - Number of management node in the cluster: 4
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
 - Number of Longhorn volumes in the cluster: 18

**Comment by derekbit** [comment]
Cannot reproduce your issue. Works well on my env.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"longhorn-volv-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resource
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2022-11-28T07:43:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: longhorn-volv-pvc
  namespace: default
  resourceVersion: "105931"
  uid: 85e2c38f-06f5-499c-bddc-bcf736a7521f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-85e2c38f-06f5-499c-bddc-bcf736a7521f
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
```

**Comment by derekbit** [comment]
I used v1.3.2.
Can you check the longhorn-manager log and see the related error logs?

**Comment by R-Studio** [comment]
@derekbit the only log I get is:  
![image](https://user-images.githubusercontent.com/7498854/204234004-c8c1fcb0-7c26-47ee-906a-31d93ae53ec4.png)

**Comment by R-Studio** [comment]
@derekbit I have a lot of the following errors, but I don't think this is related to this issue:  
![image](https://user-images.githubusercontent.com/7498854/204249045-fd270fda-7035-420b-8b58-e793b866a5ed.png)

**Comment by weizhe0422** [comment]
Hi @R-Studio, would you mind to try remove annotation and create the PVC again?

**Comment by R-Studio** [comment]
@weizhe0422 your two workarounds are working. But it is really only a workaround, because I can't always touch each PVC on a restore. 

When will be `volume.beta.kubernetes.io` removed?

**Comment by derekbit** [comment]
We have some discussions on the upgrade of the csi-privisioner in https://github.com/longhorn/longhorn-manager/pull/1518#discussion_r1034173395.
Because LH supports kubernetes v1.21.0, we cannot upgrade the csi-privisioner to a newer versio than v2.1.2.

**Comment by R-Studio** [comment]
@derekbit thanks for the info.  👍
I will watch the discussion and hope there is a solution in near future.

**Comment by R-Studio** [comment]
@weizhe0422 & @derekbit I noticed that If I check the PVC resource in the backup both annotations are present:
```yaml
annotations:
  volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
```
So when I run a restore the annotation `volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io` will be removed.  
-> Why and is this the correct behaviour?
