### ISSUE TITLE
[BUG] System restore stuck in restoring if pvc exists with identical name

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5064]
## To Reproduce

1. Create a workload, attach to a volume.
2. Write some data in it.
3. Take backup of volume and take system volume.
4. Delete the volume.
5. Restore the system backup.
6. Volume gets created again and restored the data.
7. Create PV and PVC using Longhorn UI.
8. Restore the system backup again.
9. Restore stuck in restoring state,

## Expected behavior
Restore should succeed, it should skip restoring the volume which is already in the system.

## Log or Support bundle

```
time="2022-12-14T08:26:08Z" level=debug msg="Restoring PersistentVolumeList" backupTargetURL="s3:abc/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:v1.4.0-rc1" error="PersistentVolume \"pvc-0b84678a-187b-44c6-be30-8dcb7d376303\" is invalid: spec.persistentvolumesource: Forbidden: spec.persistentvolumesource is immutable after creation\n\u00a0\u00a0core.PersistentVolumeSource{\n\u00a0\u00a0\t... // 19 identical fields\n\u00a0\u00a0\tLocal: nil,\n\u00a0\u00a0\tStorageOS: nil,\n\u00a0\u00a0\tCSI: &core.CSIPersistentVolumeSource{\n\u00a0\u00a0\t\t... // 2 identical fields\n\u00a0\u00a0\t\tReadOnly: false,\n\u00a0\u00a0\t\tFSType: \"ext4\",\n\u00a0\u00a0\t\tVolumeAttributes: map[string]string{\n+\u00a0\t\t\t\"dataLocality\": \"disabled\",\n-\u00a0\t\t\t\"diskSelector\": \"\",\n+\u00a0\t\t\t\"fromBackup\": \"\",\n+\u00a0\t\t\t\"fsType\": \"ext4\",\n-\u00a0\t\t\t\"nodeSelector\": \"\",\n\u00a0\u00a0\t\t\t\"numberOfReplicas\": \"3\",\n\u00a0\u00a0\t\t\t\"staleReplicaTimeout\": \"30\",\n+\u00a0\t\t\t\"storage.kubernetes.io/csiProvisionerIdentity\": \"1670976305218-8081-driver.longhorn.io\",\n\u00a0\u00a0\t\t},\n\u00a0\u00a0\t\tControllerPublishSecretRef: nil,\n\u00a0\u00a0\t\tNodeStageSecretRef: nil,\n\u00a0\u00a0\t\t... // 2 identical fields\n\u00a0\u00a0\t},\n\u00a0\u00a0}\n" systemRestore=sys-restore-no-volume
```
[supportbundle_53cae9b1-ec77-40ba-aa16-a9171b760e3e_2022-12-14T08-30-09Z.zip](https://github.com/longhorn/longhorn/files/10225845/supportbundle_53cae9b1-ec77-40ba-aa16-a9171b760e3e_2022-12-14T08-30-09Z.zip)

## Environment

 - Longhorn version: v1.4.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by innobead** [comment]
cc @longhorn/qa for QA, this is a good example to create a bug beyond the test case provided by engineering.

**Comment by roger-ryao** [comment]
**Verified on master-head 20221220**

- longhorn master-head ([6b53539](https://github.com/longhorn/longhorn/commit/6b5353973899c6204711ddd4cc157819901b8f80)) 
- longhorn-manager master-head ([71310df](https://github.com/longhorn/longhorn-manager/commit/71310dfcbbd4540143267061ae18f8773663f588)) 

**Verified on v1.4.x-head 20221220**
- longhorn v1.4.x-head ([ffca869](https://github.com/longhorn/longhorn/commit/ffca869ff329d8d53d0490add2d51b845209684b)) 
- longhorn-manager v1.4.x-head ([5fbbfb4](https://github.com/longhorn/longhorn-manager/commit/5fbbfb4112355e3904dcea07478c6b683cc08781)) 


**The test steps**

[Ref #5064 (To Reproduce)](https://github.com/longhorn/longhorn/issues/5064#issue-1496062803)

Steps to reproduce the behavior:

***Scenario 1***

1. Create a workload, attach to a volume.

`kubectl apply -f statefulset.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

2. Write some data in it.
3. Create a volume backup and a system backup.
4. Delete the workload.
5. Delete the volume.
6. Restore the system backup.
7. Volume gets created again and restored the data.
8. Create PV and PVC using Longhorn UI.
9. Restore the system backup again.


***Scenario 2***

1. Create a volume`vol-0` using Longhorn UI.
2. Create a pod, attach to a volume.
`kubectl apply -f pod_mount_1vol.yaml`

<details>
<summary>pod_mount_1vol.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
```
</details>

3. Write some data in it.
4. Create a volume backup and a system backup.
5. Delete POD
6. Delete the volume.
7. Restore the system backup.
8. Volume gets created again and restored the data.
9. Create PV and PVC using Longhorn UI.
10. Restore the system backup again.

**Result Passed**
1. Restore should succeed

CC @khushboo-rancher
