### ISSUE TITLE
Provide a choice to replace revision counter

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#508]
The record of revision counter results in one additional direct_io writes to the disk, which caused the performance penalty, especially this feature is more for data validation purpose.

We will see if we can replace the revision counter using some existing mechanism.

**Comment by yasker** [comment]
The basic design:
1. The engine will ask replica for the FIEMAP of the volume head and compare them. They should be the same.
2. If not all replicas report the same FIEMAP, check the timestamp for the last access time of volume head (precision is nanoseconds). Accept the latest one and the ones with the same FIEMAP as it.
    2.1. This will require servers to have NTP servers running.
    2.2. One enhancement is Longhorn manager should warn about time disparity on the different nodes.

On top of this, the user can still manually choose which replicas to be taken into consideration when `salvage` the volume from `faulted` state.

**Comment by boknowswiki** [comment]
Created UI issue at https://github.com/longhorn/longhorn/issues/1839

**Comment by boknowswiki** [comment]
@khushboo-rancher , can you use this UI image `wangsiye/longhorn-ui:71f804a` to test this feature? Since I just filed a UI issue for this feature, and it's a long holiday in China now, @smallteeths probably can't work on this UI changes very soon, and we can unblock our side with this UI image. Please let me know if you have any concern. Thanks.

**Comment by boknowswiki** [comment]
Filed engine integration test at [#1840 ](https://github.com/longhorn/longhorn/issues/1840)

**Comment by meldafrawi** [comment]
Validation: **WIP**

**Steps to test:**
-  `Diable Revision Counter` Setting should be disabled by default.  (**PASS**)
- `Disable Revision Counter` property can be set per volume at creation time.

General Steps:
1. Disable scheduling on Node2, and Node3
2. Set `Replica Node Level Soft Anti-Affinity` to True
3. Create a volume with 2 replicas, all replicas should scheduled to Node1
4. Attach a volume to a node, mount it to a directory
5. Identify and exec to `instance-manager-r-xxx` pod scheduled to Node1
6. Identify volume replicas names and PIDs.

| Replica Name  | Replica PID |
| ------------- | ------------- |
| Replica 1  | PID1  |
| Replica 2  | PID2  |

7. Using the following line, write data to the volume to `data.txt` file
`$ for x in {1..1000000}; do echo $x >> <PATH_TO_VOLUME_MNT_DIR>/data.txt ; sleep 0.01; sync; echo $x ;done`

Test case (1): `Automatic salvage`: True, `Disable Revision Counter:`  False

Test case (2): `Automatic salvage`: True, `Disable Revision Counter:`  True

Test case (3): `Automatic salvage`: False, `Disable Revision Counter:`  False

Test case (4): `Automatic salvage`: False, `Disable Revision Counter:`  True

**Comment by meldafrawi** [comment]
Validation(2/2): **PASS**

Steps to test(1):
1. Install Longhorn v1.0.2
2. Create a volume used by some workload
3. Upgrade Longhorn  `master`, 
4. Verify `Disable Revision Counter` property doesn't exist for volume before upgrading Longhorn engine image
5. Upgrade Longhorn engine image.
6. Volumes should have `Disable Revision Counter` set to False.  (**PASS**)
7. Verify global `Disable Revision Counter` is set to False by default.

Steps to test(2):
1. Create a new StogrageClass using:

```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: no-rev-count-longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "2"
      disableRevisionCounter: "true"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
```
2. Create a PVC using
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-simple-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: no-rev-count-longhorn
  resources:
    requests:
      storage: 1Gi
```
3. Create a workload to consume the created PVC
4. Check created volume replicas,  `revision.counter` file should NOT exist.
