### ISSUE TITLE
[FEATURE] Auto Trim via recurring job

### ISSUE THREAD

**Issue by atropos112** [longhorn/longhorn#5186]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
First of all, thank you a lot for the hard work you put into 1.4.0, feels like Christmas. One of my favorite features that came was the Trim feature, I had crazy cases where my PVC had 120GB and i trimmed it down to 3GB, a game changer. I've noticed these massive trim's are more noticeable with storage which gain & lose data at high rate. This will mean that I have to "manually" (click a button that is) trim the PVC every few days/weeks. 

## Describe the solution you'd like
Longhorn has recurring jobs for snaps and backups, why not have one for trimming? Or perhaps have this automated based on how much data went through a PVC (that I imagine is a lot less feasible than the other recurring job option). Another possible alternative is to create an API endpoint/ kubectl command I can automate this with.

## Describe alternatives you've considered
Like already mentioned I could do it manually , and for RWX I could automate those too (calling `kubectl exec ...` on the share pod). I am unsure how I could automate it for RWO. 

## Additional context
To be clear, the feature you produced is fantastic and I realize me saying "here is an improvement, make it better" doesn't seem to show that but I do really mean it, thank you for your hard work.

**Comment by migs35323** [comment]
+1, 
for some reason when i seen volume trimming was released on longhorn i was assuming it was done automatically based in a threshold or something.
With the recurring job i believe we get the flexibility make it to trim before a backup (so 120gb of a volume that actually holds 3gb of data doesn't take a day to backup) 
OR after a backup is done (to be better safe than sorry)

**Comment by haoyixin** [comment]
+1

**Comment by LP0101** [comment]
Until this is implemented, I wrote up a quick python container to do it. It's very barebones, so I'd recommend tweaking the script a bit if you want to use it, but it should give you the right idea.
https://github.com/LP0101/longhorn-auto-trim

It uses API calls to trim RWO volumes. For RWX volumes, it execs into the respective share-manager pod and runs `fstrim` manually.

**Comment by atropos112** [comment]
Thank you for your script @LP0101 , much appreciated. You made me realise that `<longhorn url>/v1` is a thing, thats a gold mine i am never getting out of.

**Comment by Dunge** [comment]
This is kinda a must have. Just a week of Prometheus running with default parameters and the disk space grow exponentially, fast going double the space it use for real. I can't imagine the amount of disk space wasted by people using Longhorn without trimming.

@LP0101 Thanks for the script. Just pointing out there a space missing in the Dockerfile after ENTRYPOINT otherwise it won't build.

Sample of kubernetes cronJob using it daily (change image registry and secret *** to one with the docker built):

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: longhorn-auto-trim
  namespace: default
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: ***
          containers:
          - name: longhorn-system
            image: ***/longhorn-auto-trim:1.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
```

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-manager `a91c62`) with test [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20230309-recurring-filesystem-trim.md)

Auto trim recurring job created by yaml wokred properly.
Wait UI merged to test again then close this ticket

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-manager `023dd3`, longhorn-ui `5219e4`)

Steps
1. Create recurring job task/type = `filesystem-trim` from yaml or UI
```yaml
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: recurring-fs-trim-per-min
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '5/3 * * * ?'
  groups: []
  labels: {}
  name: recurring-fs-trim-per-min
  retain: 0
  task: filesystem-trim
```
2. Create workload with volume, write data into volume mount point
3. Delete data from volume mount point, `volume.status.actualSize` did not changed.
4. `volume.status.actualSize` changes after trim file system recurring job execute.
5. Repeat above steps few more times, each round went smoothly without problem

**Comment by szechp** [comment]
i used your exact same setup:

```yaml
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: fs-trim
  namespace: longhorn
spec:
  concurrency: 1
  cron: '0 1 * * *'
  groups: []
  labels: {}
  name: fs-trim
  retain: 0
  task: filesystem-trim
```

but in the pod that should do the trimming i get:

```
time="2023-10-10T01:00:01Z" level=info msg="Setting allow-recurring-job-while-volume-detached is false"
time="2023-10-10T01:00:01Z" level=info msg="Got volumes from label recurring-job.longhorn.io/trim-fs=enabled"
time="2023-10-10T01:00:01Z" level=info msg="Found 0 volumes with recurring job trim-fs"
```
