### ISSUE TITLE
[BUG] 1.4.0 failed to install on tainted node: longhorn driver deployer failed to work, discover-proc-kubelet-cmdline pod always Pending

### ISSUE THREAD

**Issue by jwenjian** [longhorn/longhorn#5306]
## Describe the bug (🐛 if you encounter this issue)

A single node cluster, if the node has a taint, longhorn driver deployer will in error status since it is trying to wait for the pod `discover-proc-kubelet-cmdline` to be ready, but the pod has no tolerations and in Pending status.

## To Reproduce

1. prepare a single node cluster(this also applied to multi-nodes cluster if all the nodes has a taint)
2. Add a taint to the node `kubectl taint node <node name> taintlabel=taintvalue:NoSchedule`
3. following [here](https://longhorn.io/docs/1.4.0/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn) to customize helm values to add toleration to longhorn pods
4. helm install

## Expected behavior

All longhorn pods are running and ready, longhorn installed successfully and works normally

## Log or Support bundle

NA

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke2 version v1.24.9+rke2r2
   - Number of management node in the cluster: 
   - Number of worker node in the cluster: 
 - Node config
   - OS type and version: Linux master 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

   - CPU per node: 
   - Memory per node: 
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster:

## Additional context

Logs of driver deployer pod:

```
longhorn-driver-deployer W0117 09:00:56.039511       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig │
│ longhorn-driver-deployer time="2023-01-17T09:00:56Z" level=debug msg="Deploying CSI driver"                                                              │
│ longhorn-driver-deployer time="2023-01-17T09:00:56Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:00:57Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:00:58Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:00:59Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:01:00Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:01:01Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"        │
│ longhorn-driver-deployer time="2023-01-17T09:01:02Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending" 
```

Describe of pod `discover-proc-kubelet-cmdline`

```
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s                                                                   │
│                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s                                                                 │
│ Events:                                                                                                                                                  │
│   Type     Reason            Age   From               Message                                                                                            │
│   ----     ------            ----  ----               -------                                                                                            │
│   Warning  FailedScheduling  55s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {testtaint: true}. preemption: 0/1 nodes are av │
│ ailable: 1 Preemption is not helpful for scheduling.                       
```

**Comment by jwenjian** [comment]
Fixed by setting helm value: `defaultSettings.taintToleration`

**Comment by jwenjian** [comment]
Seems the `defaultSettings.taintToleration`, `defaultSettings.systemManagedComponentsNodeSelector` is not working as expected, the csi-attacher, csi-resizer ... still have no toleration & node selector after helm chart installed

This 2 settings can be changed in longhorn UI which also have some document error:

For systemManagedComponentNodeSelector, the valid value is "key:value" instead of "key=value" as described in docs (and UI tips)

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by PhanLe1010** [comment]
> This 2 settings can be changed in longhorn UI, works well

This makes sense because after the Longhorn already running inside the cluster, users have to use UI to change the Longhorn setting. Changing the value inside helm value `defaultsettings` will not have any effect. This is documented in the website https://longhorn.io/docs/1.4.0/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-after-longhorn-has-been-installed

> But the longhorn UI have some document error:
For systemManagedComponentNodeSelector, the actual valid value is "key:value" instead of "key=value" as described in docs (and UI tips)

Could you please collaborate more? I tried ` "key:value" ` and it failed in Longhorn UI. This one `"key=value"` is also in valid. Which part of the document are you referring to?

**Comment by jwenjian** [comment]
> I tried "key:value" and it failed in Longhorn UI. This one "key=value" is also in valid. Which part of the document are you referring to?

The document in the Longhorn UI settings page

**Comment by jwenjian** [comment]
> Changing the value inside helm value defaultsettings will not have any effect

It does not take effect while installing longhorn via Helm

**Comment by PhanLe1010** [comment]
> > Changing the value inside helm value defaultsettings will not have any effect
> 
> It does not take effect while installing longhorn via Helm

You need to change the setting using Longhorn UI after Longhorn is already deployed

**Comment by PhanLe1010** [comment]
> When I input test=true, this error message shows.

`test=true` is an invalid value. Note that the UI is saying that `key=value:` format is valid. It means that `test=true:` would be a valid setting

**Comment by jwenjian** [comment]
I am following [this doc](https://longhorn.io/docs/1.4.0/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn) to setup taint / toleration / node selectors while installing longhorn, if I am not miss-understanding, changing helm values should also works.

**Comment by jwenjian** [comment]
> > When I input test=true, this error message shows.
> 
> `test=true` is an invalid value. Note that the UI is saying that `key=value:` format is valid. It means that `test=true:` would be a valid setting but not `test=true`

UI text seems indicate that I should use `test=true`:

![image](https://user-images.githubusercontent.com/25657798/216262111-4cf7ec40-ee6e-47ce-8e9d-fb586e5378bc.png)

**Comment by jwenjian** [comment]
By running on node with:

```sh
kubectl label node <node name> test=true
kubectl taint node <node name> test=true:NoSchedule
```

With below Helm values, the issue fixed, both toleration & node selector works for all longhorn pods:

```yaml
defaultSettings:
  taintToleration: "test=true:NoSchedule"
  systemManagedComponentsNodeSelector: "test:true"

longhornManager:
  log:
    ## Allowed values are `plain` or `json`.
    format: plain
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  ## If you want to set tolerations for Longhorn Manager DaemonSet, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn Manager DaemonSet, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"
  serviceAnnotations: {}
  ## If you want to set annotations for the Longhorn Manager service, delete the `{}` in the line above
  ## and uncomment this example block
  #  annotation-key1: "annotation-value1"
  #  annotation-key2: "annotation-value2"

longhornDriver:
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  ## If you want to set tolerations for Longhorn Driver Deployer Deployment, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn Driver Deployer Deployment, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"

longhornUI:
  replicas: 2
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  ## If you want to set tolerations for Longhorn UI Deployment, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn UI Deployment, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"

longhornConversionWebhook:
  replicas: 2
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  ## If you want to set tolerations for Longhorn conversion webhook Deployment, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn conversion webhook Deployment, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"

longhornAdmissionWebhook:
  replicas: 2
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  ## If you want to set tolerations for Longhorn admission webhook Deployment, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn admission webhook Deployment, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"

longhornRecoveryBackend:
  replicas: 2
  priorityClass: ~
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  ## If you want to set tolerations for Longhorn recovery backend Deployment, delete the `[]` in the line above
  ## and uncomment this example block
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  nodeSelector:
    test: "true"
  ## If you want to set node selector for Longhorn recovery backend Deployment, delete the `{}` in the line above
  ## and uncomment this example block
  #  label-key1: "label-value1"
  #  label-key2: "label-value2"

                                 
```
