### ISSUE TITLE
[BUG] Longhorn 1.4.0:  Unable to attach or mount volumes

### ISSUE THREAD

**Issue by vasiliy-ul** [longhorn/longhorn#5385]
## Describe the bug (🐛 if you encounter this issue)

I have a test cluster with 2 VM nodes where I run tests for downstream KubeVirt builds with Longhorn storage. Previously I was using Longhorn 1.3.2, and it was working well. After updating to 1.4.0 I now see an issue that a usual run of the test suite somehow breaks the environment and the pods requesting Longhorn PVCs cannot be started anymore:

```
Warning  FailedMount             2m29s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[test-pvc], unattached volumes=[kube-api-access-pmp7m test-pvc]: timed out waiting for the condition
  Warning  FailedMount             49s (x4 over 6m52s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-4e76dc58-e9dd-4403-9d44-7917a46d5d5a" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             12s (x3 over 7m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[test-pvc], unattached volumes=[test-pvc kube-api-access-pmp7m]: timed out waiting for the condition
```

<details>
  <summary>pvc.yaml</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-wffc
  volumeMode: Filesystem
```
</details>

<details>
  <summary>pod.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  terminationGracePeriodSeconds: 0
  nodeName: node02
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: test
    volumeMounts:
    - mountPath: /test-pvc
      name: test-pvc
  volumes:
  - name: test-pvc
    persistentVolumeClaim:
      claimName: test-pvc
```
</details>

It seems that on the node there are leftover stuck processes, potentially preventing Longhorn from serving the PVCs: 
```
# pstree -tal 22415
longhorn-manage -d csi --nodeid=node02 --endpoint=unix:///csi/csi.sock --drivername=driver.longhorn.io --manager-url=http://longhorn-backend:9500/v1
  |-xfs_io -c statfs /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/fe5cac4835a10b85521ff1f0c9206b18fe0580802af2e7c94c33da647623ce60/globalmount
  |-xfs_io -c statfs /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/7bc8e7e0565a9ebe2da57cb7a2b75b56face2e1f9769edade6556c14eb356ea6/globalmount
  |-xfs_io -c statfs /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/eca2c0a7a19007b94908bf568ea45f597a065ac591962a593d46f2779aa51ba7/globalmount
  |-xfs_io -c statfs /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b3afa89d8e4c51aa3eaea7674524a88431762598c1823f40ec427f3c3aa45ff1/globalmount
...
```

## To Reproduce

Not yet sure how to reproduce the issue 100% reliably. As mentioned above, this happens after running the KubeVirt test suite, which includes many tests. Probably still need to detect the exact tests that cause the breakage.

If that may help, below are the storage classes with parameters used by the test suite:

<details>
  <summary>Longhorn storage classes</summary>

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: "xfs"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-wffc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
allowVolumeExpansion: true
parameters:
  fromBackup: ""
  fsType: "xfs"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-migratable
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
allowVolumeExpansion: true
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: "xfs"
  migratable: "true"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

</details>

## Expected behavior

Pods with Longhorn PVCs should start normally.

## Log or Support bundle

- [supportbundle_33a9f1b8-ea20-4795-ac06-9b9412c64c98_2023-02-10T12-08-14Z.zip](https://github.com/longhorn/longhorn/files/10722139/supportbundle_33a9f1b8-ea20-4795-ac06-9b9412c64c98_2023-02-10T12-08-14Z.zip)
- [kubelet.log](https://github.com/longhorn/longhorn/files/10722143/kubelet.log)

## Environment

 - Longhorn version: **1.4.0**
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.10+rke2r1
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by vasiliy-ul** [comment]
A small update here: I've managed to find the exact tests that seems to break things:

https://github.com/kubevirt/kubevirt/blob/6e41ae7787c1b48ac9a633c61a54444ea947242c/tests/storage/hotplug.go#L1067

I tried to run it on a clean cluster install with Longhorn 1.4.0 and after that I cannot start pods with pvcs anymore.

**Comment by vasiliy-ul** [comment]
I see that after the test run there is a leftover volume:

```
W0214 13:33:19.796435       1 controller.go:1013] Retrying syncing volume "pvc-d7083f5d-b220-4a67-b785-924905053a8e", failure 12
E0214 13:33:19.796472       1 controller.go:1031] error syncing volume "pvc-d7083f5d-b220-4a67-b785-924905053a8e": persistentvolume pvc-d7083f5d-b220-4a67-b785-924905053a8e is still attached to node node02
I0214 13:33:19.796621       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-d7083f5d-b220-4a67-b785-924905053a8e", UID:"b2c579d9-5ade-4b1f-8298-975686fb3218", APIVersion:"v1", ResourceVersion:"9488", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' persistentvolume pvc-d7083f5d-b220-4a67-b785-924905053a8e is still attached to node node02
```

It looks like an `nfs` volume... and the server seems gone:
```
node02:~ # mount | grep nfs
10.43.54.123:/pvc-d7083f5d-b220-4a67-b785-924905053a8e on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/7b0776c0c41569d213e57494a557a9ce52e2ecae396dea6e0954e6e353bc469b/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.54.123)
10.43.54.123:/pvc-d7083f5d-b220-4a67-b785-924905053a8e on /var/lib/kubelet/pods/f13759aa-4ed5-4988-bd43-076d21508206/volumes/kubernetes.io~csi/pvc-d7083f5d-b220-4a67-b785-924905053a8e/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.54.123)
node02:~ # dmesg | grep nfs
[ 1050.273916] FS-Cache: Netfs 'nfs' registered for caching
[ 1050.276493] nfs: Deprecated parameter 'intr'
[ 1308.077833] nfs: server 10.43.54.123 not responding, still trying
[ 1342.189511] nfs: server 10.43.54.123 not responding, timed out
[ 1430.957380] nfs: server 10.43.54.123 not responding, still trying
[ 1522.192016] nfs: server 10.43.54.123 not responding, timed out
```
Can this be the actual issue? Smth wrong with the volumes cleanup?

**Comment by vasiliy-ul** [comment]
Steps to reproduce the problem with volumes cleanup. Use the bellow yamls:

<details>
  <summary>Storage class</summary>

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: "xfs"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
</details>

<details>
  <summary>PVC</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn-default
  volumeMode: Filesystem
```
</details>

<details>
  <summary>Pod1 - assigned to node01</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  terminationGracePeriodSeconds: 0
  nodeName: node01
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: test
    volumeMounts:
    - mountPath: /test-pvc-default
      name: test-pvc-default
  volumes:
  - name: test-pvc-default
    persistentVolumeClaim:
      claimName: test-pvc-default
```
</details>

<details>
  <summary>Pod2 - assigned to node02</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  terminationGracePeriodSeconds: 0
  nodeName: node02
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: test
    volumeMounts:
    - mountPath: /test-pvc-default
      name: test-pvc-default
  volumes:
  - name: test-pvc-default
    persistentVolumeClaim:
      claimName: test-pvc-default
```
</details>

1. Create the Storage class
2. Create PVC
3. Create Pod1
4. Create Pod2

After that, the PVC will be mounted on both nodes via NFS and `share-manager-pvc-*` pod will appear in the `longhorn-system` namespace. Then, if both pods are deleted, `share-manager-pvc-*` will terminate with an error in the log `Device /dev/mapper/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 is not an active LUKS device`:

```
15/02/2023 09:29:31 : epoch 63eca580 : share-manager-pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 : nfs-ganesha-33[svc_13] longhorn_rm_clid :CLIENT ID :EVENT :Remove client '20%3ALinux%20NFSv4.1%20node01' from recovery backend share-manager-pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 (20%3ALinux%20NFSv4.1%20node01)
time="2023-02-15T09:29:32Z" level=info msg="share manager received signal terminated to exit"
time="2023-02-15T09:29:32Z" level=info msg="NFS server is shutting down" encrypted=false volume=pvc-f9f6c6ce-9809-46c9-b64d-627389a77392
time="2023-02-15T09:29:32Z" level=error msg="NFS server exited with error" encrypted=false error="ganesha.nfsd failed with error: signal: killed, output: " volume=pvc-f9f6c6ce-9809-46c9-b64d-627389a77392
W0215 09:29:32.346235       1 mount_helper_common.go:133] Warning: "/export/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392" is not a mountpoint, deleting
time="2023-02-15T09:29:32Z" level=debug msg="Device /dev/mapper/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 is not an active LUKS device" error="failed to run cryptsetup args: [status pvc-f9f6c6ce-9809-46c9-b64d-627389a77392] output:  error: exit status 4"
```

As a result, on one of the nodes there will be leftover NFS mounts:
```
# mount | grep nfs
10.43.143.31:/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/479c5925e09a6a268042fa8657f45fdfa4570992e4f3a956183a9afa9825ae68/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.143.31)
10.43.143.31:/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392 on /var/lib/kubelet/pods/41c89dff-0b14-4829-8219-c295d80cc0fb/volumes/kubernetes.io~csi/pvc-f9f6c6ce-9809-46c9-b64d-627389a77392/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.143.31)
10.43.117.111:/pvc-f242da65-f25e-4c95-9051-5d5da5601d77 on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/05a4aae19bd1982d3c82e09a83880e66a687adb0fb1e8676d6df5a67abe4aeac/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.117.111)
10.43.117.111:/pvc-f242da65-f25e-4c95-9051-5d5da5601d77 on /var/lib/kubelet/pods/e94ae86a-35db-413e-8856-8504927ae1da/volumes/kubernetes.io~csi/pvc-f242da65-f25e-4c95-9051-5d5da5601d77/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=10.43.117.111)
```

... and the corresponding Longhorn Volumes will not be cleaned-up:
```
# k get lhv -A
NAMESPACE         NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE        NODE   AGE
longhorn-system   pvc-f242da65-f25e-4c95-9051-5d5da5601d77   detached   unknown                  268435456          17m
longhorn-system   pvc-f9f6c6ce-9809-46c9-b64d-627389a77392   detached   unknown                  268435456          22m
```
