### ISSUE TITLE
[FEATURE] Install Opt-In NetworkPolicies 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5403]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

We have network policy manifest examples for Longhorn workloads already, but for the least privilege, it would be better to install them by default; however, they will only take effect after a policy network plugin gets installed and need to consider different installed ingress reverse proxy. It would be good to provide an opt-in policy installation.

For user-facing components like longhorn-ui, there could be a reverse proxy ahead, so should allow users to configure the ingress setting (ex: from, ports) of the installed policy based on their installed provider. (ex: https://github.com/longhorn/longhorn/pull/5378/files)

## Describe the solution you'd like

Install network policy manifests by default with customizable ingress setting for user-facing components. 

## Additional context

cc @longhorn/dev

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by dgiebert** [comment]
@innobead I have added it to the base helm chart as an optional field and worked on the questions.

**Comment by innobead** [comment]
> @innobead I have added it to the base helm chart as an optional field and worked on the questions.

Thanks. @ChanYiLin will help review that.

**Comment by ChanYiLin** [comment]
Verified

### longhorn-manager
can only be accessed by following pods
- [x] 1. longhorn-manager
- [x] 2. longhorn-ui
- [x] 3. longhorn-csi-plugin
- [x] 4. recurring-job.longhorn.io/longhorn.io/job-task (verified that recurring job works)
- [x] 6. longhorn-driver-deployer

It cannot be accessed by following pods
- instance-manager-e/r
  - [x] verified volume create/attach/detach works
- backing-image-manager/backing-image-data-source
  - [x] verified backingimage upload/export works

Note: 
Would like to know if we should allow instance-manager and backing image related pods to access longhorn-manager?

### lonhghorn-ui
can be accessed by traefik (networkPolicies.type == "k3s")

Note:
Need to do some modification if users deploy traefik by themselves using helm
the namespace would be default


This PR is basically copy the examples to the helm chart and add a opt flag
Nothing change from this issue: https://github.com/longhorn/longhorn/issues/1805#issuecomment-964724830

cc @shuo-wu @PhanLe1010 @innobead

**Comment by shuo-wu** [comment]
@ChanYiLin Can you help review this based on the test result?

**Comment by yangchiu** [comment]
Installed Longhorn `master-head` with networkPolicies `enabled`, recurring job seems not working:

1. Create a `k3s` cluster
2. Enable `networkPolices` in `values.yaml`: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml#L25
3. Install Longhorn:
```
helm install longhorn ./longhorn/chart/ --namespace longhorn-system
```
4. On Longhorn UI, create a volume and create a recurring job for it:
![Screenshot from 2023-05-30 13-43-00](https://github.com/longhorn/longhorn/assets/5709208/cdb1f5ce-a87f-4322-b750-5481b74e10b3)
5. Wait for a while, there is no snapshot being created
6. Manually click the `Take Snapshot` button, a snapshot can be created without problem

@ChanYiLin Can you help to check if there's anything wrong in the above test steps? Thank you!

**Comment by ChanYiLin** [comment]
Hi @yangchiu 
I have tested it in my environment and it worked
Is it because your recurring job didn't specify `Groups` so there was no volume selected to create snapshot?

**Comment by ChanYiLin** [comment]
I have tested it in k3s and it seems there is a network policy delay issue which will lead to recurring job failed
https://github.com/k3s-io/k3s/issues/947
```
❯ k logs job/c-01ejjr-28091947 -n longhorn-system
time="2023-05-31T07:07:00Z" level=debug msg="Setting allow-recurring-job-while-volume-detached is false"
time="2023-05-31T07:07:00Z" level=debug msg="Get volumes from label recurring-job.longhorn.io/c-01ejjr=enabled"
time="2023-05-31T07:07:00Z" level=debug msg="Get volumes from label recurring-job-group.longhorn.io/default=enabled"
time="2023-05-31T07:07:00Z" level=info msg="Found 1 volumes with recurring job c-01ejjr"
time="2023-05-31T07:07:00Z" level=info msg="Creating job" concurrent=1 groups=default job=c-01ejjr labels="{\"RecurringJob\":\"c-01ejjr\"}" retain=1 task=snapshot volume=test-1
time="2023-05-31T07:07:00Z" level=error msg="Failed to create new job for volume" concurrent=1 error="could not create longhorn-manager api client: Get \"http://longhorn-backend:9500/v1\": dial tcp 10.43.141.117:9500: connect: connection refused" groups=default job=c-01ejjr labels="{\"RecurringJob\":\"c-01ejjr\"}" retain=1 task=snapshot volume=test-1
```

but in my cluster (using kubeadm to build k8s cluster), there is no such delay


### Reproduce Steps
with networkpolicy [ref](https://github.com/longhorn/longhorn/pull/5950/files#diff-e1d61d65a87a786abeca7d117e7f61be487181aa484d4c12d140f65ed70d0631R1)
```
spec:
  ingress:
  - from:
...
    - podSelector:
        matchExpressions:
        - key: recurring-job.longhorn.io
          operator: Exists
        matchLabels:
          longhorn.io/managed-by: longhorn-manager
...
```

manually create the pod with following commands
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    job-name: test
    longhorn.io/managed-by: longhorn-manager
    recurring-job.longhorn.io: test
  name: test
  namespace: longhorn-system
spec:
  containers:
  - command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do curl http://longhorn-backend:9500/v1 && sleep 5; done;" ]
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: longhornio/longhorn-manager:master-head
    imagePullPolicy: IfNotPresent
```
<img width="1046" alt="截圖 2023-05-31 下午4 04 20" src="https://github.com/longhorn/longhorn/assets/7100904/730ae918-bb86-43cf-9ea8-31d0998e378f">

For the several early tries, it failed to connect to longhorn-manager, then it succeeded

cc @innobead @yangchiu
