### ISSUE TITLE
[FEATURE] Email or Slack notification when backup completes

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#542]
This would be great to keep an eye on the status of backups. Thanks

**Comment by yasker** [comment]
We may able to support webhook for e.g. Slack. But email would need a SMTP server, which would be more complex.

**Comment by vitobotta** [comment]
Slack is even better! :)

**Comment by dnauck** [comment]
Or MS Teams ;)

**Comment by yasker** [comment]
Keep it open.

**Comment by yasker** [comment]
It's a part of https://github.com/longhorn/longhorn/issues/928 .

**Comment by yasker** [comment]
The backup status will be added to v1.2.0. Also, we will utilize Prometheus for the backup status notification.

**Comment by PatrickHuetter** [comment]
Sounds good that you're utilizing Prometheus. So it should be possible to configure it to get alerts only on failures.

**Comment by jenting** [comment]
I know @qdupuy monitors the backup creation failed and sends an Email notification, possibly @qdupuy could provide some information on how to configure it :pray:

**Comment by qdupuy** [comment]
Hi,

Here are the alert rules I put on prometheus : 

```
  groups:
  - name: longhorn.rules
    rules:
    - alert: LonghornVolumeActualSpaceUsedWarning
      annotations:
        description: The actual space used by Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.
        summary: The actual used space of Longhorn volume is over 90% of the capacity.
      expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
      for: 5m
      labels:
        issue: The actual used space of Longhorn volume {{$labels.volume}} on {{$labels.node}} is high.
        severity: warning
    - alert: LonghornVolumeStatusCritical
      annotations:
        description: Longhorn volume {{$labels.volume}} on {{$labels.node}} is Fault for
          more than 2 minutes.
        summary: Longhorn volume {{$labels.volume}} is Fault
      expr: longhorn_volume_robustness == 3
      for: 5m
      labels:
        issue: Longhorn volume {{$labels.volume}} is Fault.
        severity: critical
    - alert: LonghornVolumeStatusWarning
      annotations:
        description: Longhorn volume {{$labels.volume}} on {{$labels.node}} is Degraded for
          more than 5 minutes.
        summary: Longhorn volume {{$labels.volume}} is Degraded
      expr: longhorn_volume_robustness == 2
      for: 5m
      labels:
        issue: Longhorn volume {{$labels.volume}} is Degraded.
        severity: warning
    - alert: LonghornNodeStorageWarning
      annotations:
        description: The used storage of node {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.
        summary:  The used storage of node is over 70% of the capacity.
      expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > 70
      for: 5m
      labels:
        issue: The used storage of node {{$labels.node}} is high.
        severity: warning
    - alert: LonghornDiskStorageWarning
      annotations:
        description: The used storage of disk {{$labels.disk}} on node {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.
        summary:  The used storage of disk is over 70% of the capacity.
      expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 70
      for: 5m
      labels:
        issue: The used storage of disk {{$labels.disk}} on node {{$labels.node}} is high.
        severity: warning
    - alert: LonghornNodeDown
      annotations:
        description: There are {{$value}} Longhorn nodes which have been offline for more than 5 minutes.
        summary: Longhorn nodes is offline
      expr: longhorn_node_total - (count(longhorn_node_status{condition="ready"}==1) OR on() vector(0))
      for: 5m
      labels:
        issue: There are {{$value}} Longhorn nodes are offline
        severity: critical
    - alert: LonghornIntanceManagerCPUUsageWarning
      annotations:
        description: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is {{$value}}% for
          more than 5 minutes.
        summary: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is over 300%.
      expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 > 300
      for: 5m
      labels:
        issue: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} consumes 3 times the CPU request.
        severity: warning
    - alert: LonghornNodeCPUUsageWarning
      annotations:
        description: Longhorn node {{$labels.node}} has CPU Usage / CPU capacity is {{$value}}% for
          more than 5 minutes.
        summary: Longhorn node {{$labels.node}} experiences high CPU pressure for more than 5m.
      expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 > 90
      for: 5m
      labels:
        issue: Longhorn node {{$labels.node}} experiences high CPU pressure.
        severity: warning
```

Then, for the notification by mail and/or slack. I use alertmanager.

To deploy prometheus and alertmanager, I took the prometheus-community helm charts.

Here are a few configurations :

```
  alertmanagers:
    - static_configs:
      - targets:
        - 'prometheus-alertmanager.monitoring.svc.cluster.local:80'
 ```

```
alertmanagerFiles:
  alertmanager.yml:
    global:
      smtp_smarthost: 'mail.x:587'
      smtp_hello: alertmanager
      smtp_from: 'alertmanager@x'
      smtp_auth_username: 'alertmanager@x'
      smtp_auth_password: 'x'
      smtp_require_tls: true
      slack_api_url: 'x'

    receivers:
      - name: slack
        slack_configs:
          - channel: '#infra-alerts'
            send_resolved: true
            username: 'AlertManager - x'
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

              *Description:* {{ .Annotations.description }}

              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              
              {{ end }}
      - name: email
        email_configs:
          - to: 'support@x'
            from: 'alertmanager@x'

    route:
      group_wait: 1m
      group_interval: 15m
      receiver: slack
      repeat_interval: 2h
```

Then, I create a scrape_config dedicated to longhorn by putting the ip addresses of the pods because I don't have a prometheus-operator.

```
    scrape_configs:
      - job_name: longhorn-manager
        metrics_path: /metrics
        static_configs:
          - targets:
            - x:9500
```

I hope this will help you.
