### ISSUE TITLE
[BUG] Failed to create the pod due to the inability to mount the volume.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5521]
## Describe the bug (🐛 if you encounter this issue)

After creating a volume on K8s version `v1.24`, we upgraded to K8s version `1.25` and then upgraded Longhorn to version `1.4.1-rc2`. However, when we try to create a pod with a volume, the status sometimes gets stuck at 'ContainerCreating'

I have never tested it before, so I'm not sure if it is a reasonable step to take. However, I would appreciate your help in checking.

![Screenshot_20230309_161628](https://user-images.githubusercontent.com/104337648/223971688-53fa78c9-9cf5-47f8-9254-97705870872e.png)

## To Reproduce

1. Create a K3s `1.24.10` cluster with 3 worker nodes and 1 control plane.
2. Install longhorn `v1.4.0`
3. 4 detached volumes with data.(vol-0 vol-1 vol-2 & vol-3)
4. 2 deployments of one pod. 1 statefulset of 10 pods.
   1.    `kubectl apply -f statefulset.yaml`
   2.    `kubectl apply -f deployment.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 10 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>
   
5. Upgrade K8s to 1.25.6.
6. Create a pod `ubuntu-mount2vol` and attach `vol-0` & `vol-1` 
7. Create a pod `ubuntu-mountvol2` and attach `vol-2` .

<details>
<summary>ubuntu-mount2vol.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mount2vol
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0
      - mountPath: "/data1/"
        name: vol-1
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
    - name: vol-1
      persistentVolumeClaim:
        claimName: vol-1

```
</details>

<details>
<summary>ubuntu-mountvol2.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol2
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-2
  volumes:
    - name: vol-2
      persistentVolumeClaim:
        claimName: vol-2
```
</details>

<details>
<summary>ubuntu-mountvol3.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol3
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-3
  volumes:
    - name: vol-3
      persistentVolumeClaim:
        claimName: vol-3
```
</details>

8. `Auto Salvage` set to disable.
9. upgrade longhorn to `v1.4.1-rc2`.
10. Delete pods `ubuntu-mount2vol` and `ubuntu-mountvol2` and make vol-0 , vol-1 and vol-2 is detached.
11. Create a pod `ubuntu-mount2vol` and attach `vol-0` & `vol-1` 
12. Create a pod `ubuntu-mountvol2` and attach `vol-2` .
13. Create a pod `ubuntu-mountvol3` and attach `vol-3` .

## Expected behavior

we can create a pod successfully without the status getting stuck at 'ContainerCreating'

## Log or Support bundle

[supportbundle_81547a3b-99eb-412d-91fc-ae17dae44556_2023-03-09T08-47-19Z.zip](https://github.com/longhorn/longhorn/files/10929514/supportbundle_81547a3b-99eb-412d-91fc-ae17dae44556_2023-03-09T08-47-19Z.zip)

[ubuntu-mountvol3-des.log](https://github.com/longhorn/longhorn/files/10929890/ubuntu-mountvol3-des.log)
[ubuntu-mountvol2-des.log](https://github.com/longhorn/longhorn/files/10929891/ubuntu-mountvol2-des.log)
[ubuntu-mount2vol-des.log](https://github.com/longhorn/longhorn/files/10929892/ubuntu-mount2vol-des.log)

## Environment

 - Longhorn version: 1.4.0 upgrade to 1.4.1-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.24 upgrade to 1.25
   - Number of management node in the cluster:1
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
I feel the steps are too long and mix everything together...
Suggest providing the mores specific information such as the failed operation and narrow down the issue.

**Comment by innobead** [comment]
The context is uncertain, need to clarify a bit. Add `require/qa-reproduce` label. 

cc @longhorn/qa

**Comment by roger-ryao** [comment]
I have encountered a Multipathd issue. After discussing with @c3y1huang 
 and following the steps outlined in https://longhorn.io/kb/troubleshooting-volume-with-multipath/, we were able to successfully create a pod without the status getting stuck at 'ContainerCreating'.
 
 ---
 **Steps to reproduce the behavior:**
1. Create a K3s `1.24.10` cluster with 3 worker nodes and 1 control plane.
2. Install longhorn `v1.4.0`
3. 1 detached volumes with data.(vol-0)
4. 2 deployments of one pod. 1 statefulset of 10 pods.
   1.    `kubectl apply -f statefulset.yaml`
   2.    `kubectl apply -f deployment.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 10 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>
   
5. Upgrade K8s to 1.25.6.
6. `Auto Salvage` set to disable.
7. upgrade longhorn to `v1.4.1-rc2`.
8. Create a pod `ubuntu-mountvol0` and attach `vol-0` 

<details>
<summary>ubuntu-mountvol0.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol0
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-0
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
```
</details>
