### ISSUE TITLE
[BUG] RWX volume is stuck at detaching when the attached node is down 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5558]
## Describe the bug (🐛 if you encounter this issue)

The RWX volume is stuck at detaching when the attached node is down. The root cause is the side effect of the fix https://github.com/longhorn/longhorn/issues/5507. To prevent that nfs-ganesha sever mounts the dead volume, the engine controller tries to delete the engine instance. If the attached node is down and does not come back, the deletion won't succeed and then retry again and again. Then, the volume will be stuck at detaching state.

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Workaround
- Delete the down node
- Delete the unknown instancemanager of the down node 

## Additional context

https://cloud-native.slack.com/archives/CNVPEL9U3/p1678784583120039

**Comment by innobead** [comment]
cc @longhorn/qa Do we have node down case for RWX volume (share manager pod)?

**Comment by innobead** [comment]
@derekbit Lets provide the workaround first.

cc @shuo-wu @PhanLe1010 @c3y1huang

**Comment by derekbit** [comment]
For the stuck issue, the workarounds
1. Delete the down node
2. Delete the unknown instancemanager

Any risk for the second solution? cc @shuo-wu @PhanLe1010 @c3y1huang

**Comment by innobead** [comment]
> > cc @longhorn/qa Do we have node down case for RWX volume (share manager pod)?
> 
> Hi @innobead I think I may have observed the same symptoms as the user mentioned in the Slack channel. I also asked a question about it on [#5488 (comment)](https://github.com/longhorn/longhorn/issues/5488#issuecomment-1467838260). I searched for the node down case for RWX volumes in our manual test cases this afternoon, but I didn't find it.

@khushboo-rancher Can you confirm if we don't have the test case for RWX? We should have that if not yet.

**Comment by khushboo-rancher** [comment]
We have test cases for RWX volumes with node down/restart/kubelet restart etc - https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/single-replica-node-down/ , https://longhorn.github.io/longhorn-tests/manual/pre-release/node/kubelet-restart-on-a-node/

I feel most of the node down/reboot test cases are scenario based and we can make them better by consolidating them. Having these test cases at one place (under one category) will reduce the chance of missing them.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230320**

- longhorn master-head ([86d0669](https://github.com/longhorn/longhorn/commit/86d06696dfdca947b651ae7f8ac8114873461147))
- longhorn-manager master-head ([b818813](https://github.com/longhorn/longhorn-manager/commit/b81881360c3496a8bb9e7dd05437e2805e81bb92))

*The test steps**

1. Deploy longhorn with 3 replicas
2. Set `node-down-pod-deletion-policy` = `delete-deployment-pod`
3. Create deployment and mount the volume
`kubectl apply -f deployment.yaml`

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc

```
</details>

4. After pod running, shutdown the node which node attached to
Old pod terminated success
5. Check whether the volume has been successfully attached to the new node and whether the new pod is running.

**Result Passed**

I have tested the creation of a deployment with RWO|RWX volume, and the test passed.

**Comment by roger-ryao** [comment]
Reopen the issue, and let's consider testing another scenario where the node network is disconnected.

**Comment by roger-ryao** [comment]
The behavior of the Longhorn storage system when the node network is disconnected on the master head is different in comparison to version 1.3.3-rc1. As a result, I need more time to perform additional testing to identify any potential issues related to this scenario. Therefore, I will focus on testing the 1.3.3 release first, and then I will verify this issue again.

**Comment by derekbit** [comment]
> The behavior of the Longhorn storage system when the node network is disconnected on the master head is different in comparison to version 1.3.3-rc1. As a result, I need more time to perform additional testing to identify any potential issues related to this scenario. Therefore, I will focus on testing the 1.3.3 release first, and then I will verify this issue again.

What's the difference?

**Comment by roger-ryao** [comment]
> > The behavior of the Longhorn storage system when the node network is disconnected on the master head is different in comparison to version 1.3.3-rc1. As a result, I need more time to perform additional testing to identify any potential issues related to this scenario. Therefore, I will focus on testing the 1.3.3 release first, and then I will verify this issue again.
> 
> What's the difference?

**The test steps**

1. Deploy longhorn with 3 replicas
2. Set `node-down-pod-deletion-policy` = `delete-deployment-pod`
3. Create deployment and mount the volume
`kubectl apply -f deployment.yaml`

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc

```
</details>

4. After pod running, the share-manager-pvc pod on the worker-node-2. deployment workload pod mysql-dep-rwx-556d8cb75c-8bjmk on the   worker-node-1
5. Disconnect the network of the worker-node-1 & worker-node-2 360 seconds.
(sudo nohup ./network_down.sh 360)
script link: https://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip
5. Check whether the old pod has been terminated.
6. Verify whether the volume has been successfully attached to the new node and whether the new pod is running.

In version 1.3.3-rc1, we observed that both the `share-manager-pvc` pod and the `deployment workload` pod were successfully attached to the new node, and the new pod was running before node connection.

In the master-head, we need to wait for node connection before observing that the `share-manager-pvc` pod and the `deployment workload` pod have been successfully attached to the new node and the new pod is running.

We are unable to generate the support bundle at the moment. Once the issue at https://github.com/longhorn/longhorn/issues/5073 is resolved, I will provide it.

**Comment by derekbit** [comment]
Weird.

I can see the sharemanager pod moved to another node, and the deployment is recreated as well
```
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   1/1     Terminating   0          115s   10.42.4.18   rancher60-worker2   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   1/1     Terminating   0          115s   10.42.4.18   rancher60-worker2   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   1/1     Terminating   0          115s   10.42.4.18   rancher60-worker2   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   0/1     Pending       0          0s     <none>       <none>              <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   0/1     Pending       0          0s     <none>       rancher60-worker1   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   0/1     ContainerCreating   0          0s     <none>       rancher60-worker1   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   0/1     Running             0          9s     10.42.1.18   rancher60-worker1   <none>           <none>
share-manager-pvc-92b8ca19-d909-4b87-9340-7946653c749d   1/1     Running             0          11s    10.42.1.18   rancher60-worker1   <none>           <none>
```

**Comment by MohamedShaj** [comment]
which version has the fix of RWX volume is stuck at detaching when the attached node is down and what is the stable version to go for production ??

**Comment by MohamedShaj** [comment]
> #5073

Tha fix for #5558 is tagged in [Longhorn v1.3.3-rc2 release](https://github.com/longhorn/longhorn/releases/tag/v1.3.3-rc2) , right now we are using v1.4.1 stable version, how to change to this fix version ...if we change any issue will be occuring ??

can you say the steps to fix the RWX volume detach stuck from v.1.3.3-rc2

**Comment by derekbit** [comment]
> We are trying with resilience factor, for eg, we have a cluster of 10nodes where LH is installed for dynamic storage of volumes with 5 replicas, and now manually if I stop the server via AWS or gCP console, the RWX volumes are getting into detaching state and get stuck, even I tried the above workaround I can see this notification as below

Can you delete the unknown instancemanagers?
You can list the instancemanager by
```
kubectl -n longhorn-system get instancemanagers
```
Then, you can see the unknown `instance-manager-e-xxx` which is on the down node and delete it .

**Comment by roger-ryao** [comment]
**Verified on master-head 20230329**

- longhorn master-head ([6764850](https://github.com/longhorn/longhorn/commit/6764850dcacac08c296002a2504d165a3e1da4da))
- longhorn-manager master-head ([79acd76](https://github.com/longhorn/longhorn-manager/commit/79acd764ed501dc29f978d2be47a80941d10ecb4))

**The test steps**

1. Deploy longhorn with 3 replicas
2. Set `node-down-pod-deletion-policy` = `delete-deployment-pod`
3. Create deployment and mount the volume
`kubectl apply -f deployment.yaml`

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc

```
</details>

4. After pod running, disconnect the network of the node that the `share-manager-pvc` pod attached to for 180 seconds.
(sudo nohup ./network_down.sh 180)
script link : thttps://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip
5. Check whether the old `share-manager-pvc` pod has been terminated.
6. Check whether the new `share-manager-pvc` pod is running.

**Result Passed**

I have tested the creation of a deployment with a RWX volume, and the test passed.
