### ISSUE TITLE
[IMPROVEMENT] Merge conversion/admission webhook and recovery backend services into longhorn-manager

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5590]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The conversion/admission webhook and recovery backend services are deployed as `Deployment`. Despite the anti-affinity for these services, there's still a chance that these deployments' replicas are on the same worker node. In the event that a worker node fails due to a network partition or a power outage, the services will be irresponsive until their pods are recreated on different worker nodes. The single node failure will result in the whole Longhorn cluster getting stuck. To achieve high availability, it is better to deploy these three services by `DaemonSet` rather than `Deployment`, as they are critical components for resource operation (conversion/admission webhooks) and RWX volume operation (recovery backend).

**Comment by innobead** [comment]
cc @shuo-wu @PhanLe1010 @c3y1huang 

This needs to discuss. Is it possible to just leverage longhorn-manager for those purpose?

**Comment by derekbit** [comment]
> cc @shuo-wu @PhanLe1010 @c3y1huang
> 
> This needs to discuss. Is it possible to just leverage longhorn-manager for those purpose?

These services are actually creating servers and then receiving/handling the requests. I think merging them into longhorn-manager is a good idea.

**Comment by innobead** [comment]
I see. Btw do we use requiredDuringSchedulingIgnoredDuringExecution or prefer instead for these deployments? If the former， it should be able to ensure availability.

**Comment by PhanLe1010** [comment]
Agree that we should move the webhook into Longhorn manager because Longhorn manager cannot function without these webhook anyways. And Longhorn manager is already a daemonset

**Comment by innobead** [comment]
Sounds good to me. For drain story, it will be more simplified than now.

**Comment by derekbit** [comment]
> requiredDuringSchedulingIgnoredDuringExecution

We use`preferredDuringSchedulingIgnoredDuringExecution` currently for best effort.

**Comment by innobead** [comment]
Yeah, just noticed that it's preferred, so best efforts. Thanks @derekbit raised this, this improvement will make our services more stable. 👍

**Comment by innobead** [comment]
@ChanYiLin Please help with this and check with @derekbit if having any questions. Thanks.

**Comment by ChanYiLin** [comment]
Update Scope:
- [ ] longhorn/manager: make conversion/admission webhook use different port
- [ ] longhorn/longhorn/chart: put webhook/recovery container into manager daemonset
- [ ] longhorn/manager: `uninstall controller` doesn't have to uninstall conversion/admission webhook and recovery deployment (ref: [code](https://github.com/longhorn/longhorn-manager/blob/master/controller/uninstall_controller.go#L299))

**Comment by innobead** [comment]
@ChanYiLin we need to ensure webhook and recover backend will continue serving during and after the upgrade.

**Comment by ChanYiLin** [comment]
Do we have ref or doc for this part
Like how to test if is still serving during upgrading
Does our e2e cover this part?

**Comment by derekbit** [comment]
> Do we have ref or doc for this part Like how to test if is still serving during upgrading Does our e2e cover this part?

1. Fresh installation: all pods are created and running successfull
2. Install v1.4.1 and then upgrade to patched version: all pods are created and running successfully. Old webhook pods should be terminated. The old webhook should keep running until there is no RWX volume using it.

**Comment by ChanYiLin** [comment]
> > Do we have ref or doc for this part Like how to test it is still serving during upgrading Does our e2e cover this part?
> 
> 1. Fresh installation: all pods are created and running successfuly
> 2. Install v1.4.1 and then upgrade to patched version: all pods are created and running successfully. Old webhook and recovery-backend pods should be terminated.

Thanks!

**Comment by PhanLe1010** [comment]
An issue come up on top of my head: how do we make sure that the webhook containers are running before longhorn-manager container?

In the current implementation, we use init containers inside Longhorn manager pod to wait for webhook services to start before starting the longhorn-manager containers.

However, when we decided to put webhook containers inside longhorn-manager pod, the init containers mechanism might not work anymore because webhook services will not be available at the time when the init containers run. 

One of the alternate solutions I am thinking about is directly doing the webhook service check inside the longhorn-manager container code (i.e., ping and wait for webhook service at [here](https://github.com/longhorn/longhorn-manager/blob/0e366f8867fcad3a5681919aa4399f93e54033c4/app/daemon.go#L139) before the upgrade logic)  

What do you think @innobead  @derekbit @shuo-wu @ChanYiLin

**Comment by PhanLe1010** [comment]
Also related to this topic, I am wondering if we should put all the csi-xxx pods into the longhorn-csi-plugin daemonset for the same HA reason. longhorn-csi-plugin cannot function without these csi-xxx pods anyways so I am thinking why not combine them into the same daemonset.

**Comment by ChanYiLin** [comment]
> An issue come up on the top of my head: **how do we make sure that the webhook containers are running before longhorn-manager container?**
> 
> In the current implementation, we use init containers inside Longhorn manager pod to wait for webhook services to start before starting the longhorn-manager container.
> 
> However, once we decide to put webhook containers inside longhorn-manager pod, the init containers mechanism might not work anymore because webhook services will not be available at the time when the init containers run.
> 
> One of the alternate solutions I am thinking about is directly doing the webhook service check inside the longhorn-manager container code (i.e., ping and wait for webhook service at [here](https://github.com/longhorn/longhorn-manager/blob/0e366f8867fcad3a5681919aa4399f93e54033c4/app/daemon.go#L139) before the upgrade logic)
> 
> What do you think @innobead @derekbit @shuo-wu @ChanYiLin

Thanks for the reminder, it is indeed a problem!
I just did some research and found there is a feature in K8s which can force the containers in the pod to be created in order.
ref: [attach-handler-lifecycle-event](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/)
in this way we only need to add some code or new command in webhook to return true to lifecycle hook when the webhook is ready
So the Pod can create next container to achieve creating containers in order.
What do you think?

**Comment by ChanYiLin** [comment]
Or even easier, put init container command to lifecycle.poststart.exec.command

example: (assume conversion is on port 9443 and admission is on port 8443)
```
spec:
  containers:
  - name: longhorn-conversion-webhook
    lifecycle:
      postStart:
        exec:
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://localhost:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done']
    ...
  - name: longhorn-admission-webhook
    lifecycle:
      postStart:
        exec:
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://localhost:8443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done']
    ...
  - name: longhorn-recovery-backend
    ...
  - name: longhorn-manager
    ...
```

**Comment by PhanLe1010** [comment]
Great quick finding @ChanYiLin 👍

From a quick reading, I am afraid that we have some issues with the approach:
1. The official doc doesn't make this guarantee [but it turns out that the Kubelet code that starts the container blocks the start of the next container until the post-start handler terminates.](https://stackoverflow.com/questions/69423932/container-initialization-order-in-pod-on-k8s#:~:text=but%20it%20turns%20out%20that%20the%20Kubelet%20code%20that%20starts%20the%20container%20blocks%20the%20start%20of%20the%20next%20container%20until%20the%20post%2Dstart%20handler%20terminates.) We would have to dig into the K8s code to figureout 
2. Even if the above statement is true, K8s starts containers inside pod in parallel so it could be like: longhorn-manager container start -> it has no `postStart` -> webhook container start -> it has `postStart` but doesn't have any effect now that longhorn-manager container already started

What do you think?

**Comment by derekbit** [comment]
Another thought, why not just create go routines for the webhook and recovery-backend servers inside the longhorn-manager daemon?

**Comment by ChanYiLin** [comment]
I have done some research and verify that the kubelet start the container in order (container list in pod)
For every container start, it will exec the postStart command.
So if the postStart command need to wait, then the kubelet will block until the postStart command return successfully then create next container
code ref: [pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1247](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1247
)

quick example: can verify that container-b start after 10sec
```
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: container-a
    image: nginx:1.14.2
    lifecycle:
      postStart:
        exec:
          command: ['sh', '-c', 'sleep 10']
    ports:
    - name: nginxa
      containerPort: 80
  - name: container-b
    image: nginx:1.14.2
    command: ["/bin/sh","-c"]
    args: ["sed -i 's/listen  .*/listen 81;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    ports:
    - name: nginxb
      containerPort: 81
```
