### ISSUE TITLE
[FEATURE] Add global setting or per-volume setting for enabling filesystem trim on encrypted volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5599]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We've already provided steps for enabling filesystem trim on encrypted volumes in the [official document](https://longhorn.io/docs/1.4.0/volumes-and-nodes/trim-filesystem/#encrypted-volumes). However, it's really handy for users.  We can add a global or per-volume setting for enabling or disabling this functionality, make it more transparent to users, and users can manage them easily inside the Longhorn system.

**Comment by innobead** [comment]
Moving to 1.5 to make the story complete. Also need to respect different types of volume, RWO & RWX.

**Comment by derekbit** [comment]
Need to add the [doc](https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)) in the new setting and let users understand the security issues after enabling trim on encrypted volume.

**Comment by innobead** [comment]
We have some concerns about the security and data loss for this function. Revisit this later. 

https://github.com/longhorn/longhorn-manager/pull/1784#discussion_r1187592468

**Comment by Jamison1** [comment]
Any alternatives to the current manual approach to enabling encrypted volume trim?  

I have a problem with encrypted volumes bloating due to unscheduled snapshots.

Current manual approach:
Remote in to all storage nodes
Get list of all longhorn pvc's
`ls -l /dev/longhorn`

Set allow discards
`sudo cryptsetup --allow-discards --persistent refresh <pvc-ID>`

Enter passphrase
`Enter passphrase for /dev/sdk: <Longhorn_Encryption_Passphrase>`

Manually trim filesystem

The manual approach works, but doesn't seem feasible for a production cluster that is based on automation

**Comment by derekbit** [comment]
@Jamison1 
Before implementing the feature, I think there is no quick way.

Before adding the feature, we'd like to get more feedback. Are you concerned about the security risks in a production environment?
```
Warning: Before enabling TRIM on a drive, make sure the device fully supports TRIM commands, or data loss can occur
WARNING: This command can have a negative security impact because it can make filesystem-level operations visible on the physical device. For example, information leaking filesystem type, used space, etc. may be extractable from the physical device if the discarded blocks can be located later. If in doubt, do not use it.
```

**Comment by Jamison1** [comment]
We use multiple layers of encryption for data at rest.  We also are fairly well versed in trim availability.

If I understand the warning on encryption with respect to the negative security impact - This does not make it less secure than if one disabled encryption entirely and trim'd the drive - correct?  Or am I missing something here?

I think those warnings are appropriate for the documentation.  Perhaps expand on that somewhat to make it more clear for those who check boxes as part of their security protocol.  Also in the UI volume tab when you hover with the cursor over the lock icon it says "Encrypted Volume" - perhaps adding to that to say "Trim Enabled" as a notice/warning.

I would prefer to see the ability to auto trim encrypted volumes enabled through the helm chart values - at time of longhorn installation (this includes any recurring jobs needed to delete, cleanup unscheduled snapshots and trim after).  So that encrypted pvc creation doesn't require any additional UI related steps after creation.

We rely heavily on automation with extensive testing beforehand so any manual processes like having to break out my "10 steps for encrypted Longhorn volumes" with the UI or CLI really throw a wrench in the automation.  We use the UI primarily for monitoring the storage health - and watch the volumes expand due to unscheduled snapshotting without trim.

Additionally, you could also show that encrypted trim is enabled in UI volume settings for encrypted volumes with the option to disable encrypted trim using `cryptsetup --persistent <pvc-id>` or something similar since trim can also be disabled if needed.

When we spin up a cluster, we install quite a few other items after Longhorn with helm that create encrypted pvc's as part of the same automated process.

Without the ability to trim encrypted volumes they can become unusable after XX days due to volume expansion with unscheduled snapshotting and multiple replicas.  IMO this is needed if using encrypted volumes in production.

**Comment by Jamison1** [comment]
@derekbit
Update on encrypted volume expansion.  In testing a new loki write volume it started at 139Mi and after 13 hours it was at 4.45Gi.  As its a test cluster obv it hasn't written 4G in logs.  This appears to be from unscheduled snapshots.  After enabling `allow-discards` on the encrypted volume along with `allow snapshots removal during trim` and selecting `Trim Filesystem` - it dropped from 4.45Gi to 259Mi.  In a matter of minutes it then expanded up to 300Mi - So unless there is some other reason for this volume expansion - Encrypted volumes don't seem very production friendly at the moment without enabling allow-discards.

**Comment by weber-software** [comment]
FYI:

we are using just encrypted volumes in our cluster that are using the same key `longhorn-crypto`.
With the following DaemonSet deployed as a workaround we are enabling discard for all our volumes every hour.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-setup-cypto-discard
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      name: longhorn-setup-cypto-discard
  template:
    metadata:
      labels:
        name: longhorn-setup-cypto-discard
    spec:
      containers:
      - name: longhorn-setup-cypto-discard
        command: ["sh", "-c", "apk add cryptsetup device-mapper && while true; do echo updating now; for LONGHORN_VOLUME in `ls /dev/longhorn/`; do cryptsetup --key-file=/etc/luks/longhorn-crypto/CRYPTO_KEY_VALUE --allow-discards --persistent refresh $LONGHORN_VOLUME; done; echo done; dmsetup table; sleep 1h; done"]
        image: alpine
        # do not specify resource limits for memory because cryptsetup is memory mapping the stuff
        volumeMounts:
        - name: dev
          mountPath: /dev/
        - name: longhorn-crypto
          mountPath: /etc/luks/longhorn-crypto/
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 5
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: longhorn-crypto
        secret:
          secretName: longhorn-crypto
```
