### ISSUE TITLE
[BUG] Volume appears to attach, but not physically mounting on the node. Data doesn't persist

### ISSUE THREAD

**Issue by joshsouza** [longhorn/longhorn#5644]
## Describe the bug (🐛 if you encounter this issue)

Utilizing the [example PVC deployment](https://staging--longhornio.netlify.app/docs/0.8.1/references/examples/) with a basic `bash` container (not mysql, which would write data)
The pod gets scheduled, volume gets created, and everything _appears_ to be operational.
However, upon further investigation, the data does not persist between pod deletion/creation.

Deleting a pod results in the pod being stuck in `Terminating` forever (requiring a `--force` to fully remove), even though the actual docker container for the pod is cleaned up. (I could not find any indication of errors or why it's stuck thus far).
Writing data within the mounted directory, deleting (with force) and allowing a new pod to come up (successfully) results in the data being lost.

The host has `/dev/longhorn/<pvc-name>` available, however `mount -l | grep pvc` has no results, making me think that the volume _isn't_ actually mounted.

Mounting `/dev/longhorn/<pvc-name>` to a directory, and writing a file, then subsequently unmounting, and re-scheduling the pod to a different node, then re-mounting there shows the data written in this way _does_ persist. Thus I think Longhorn is "working" properly, as far as the volume itself (`/dev/longhorn/<pvc-name>`), but it's not actually performing the mount of this volume to the path where docker will bind into the pod.

## To Reproduce

1. Deploy the below test:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-longhorn
  labels:
    app: test-longhorn
spec:
  selector:
    matchLabels:
      app: test-longhorn # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-longhorn
    spec:
      restartPolicy: Always
      containers:
      - image: frolvlad/alpine-bash
        name: bash
        args:
          - bash
          - -c
          - 'date >> /data/last-boot; while true; do sleep 10; done'
        livenessProbe:
          exec:
            command:
              - ls
              - /data/last-boot
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: test-longhorn
```

2. Review the contents of the file within the pod: `kubectl exec -it <pod_name> -- ls /data` (or `kubectl exec -it <pod_name> -- cat /data/last-boot`
3. SSH to node hosting the pod
4. Mount `/dev/longhorn/<pvc-name>` to `/mnt` (or elsewhere)
5. Review contents of mounted volume (in my case, empty)
6. Write a file to `/mnt/test` etc...
7. Delete the pod and ensure it spins up on another node (consider cordoning the current node)
8. Review data in the container again (for me, only one line, the current boot-up, in a working scenario it should have multiple lines)
9. Repeat mount directly on node, and observe contents (in my case, `/mnt/test` exists, but no `last-boot` file

## Expected behavior

Data should persist
Volume should be mounted to a location before docker pod is started

## Log or Support bundle

Support bundle will be attached shortly

## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE, v1.21.4
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3+
 - Node config
   - OS type and version: Ubuntu 22.04.2 LTS   5.15.0-67-generic   docker://23.0.1
   - CPU per node: 4+
   - Memory per node: 16Gi+
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Local network, 100/1000
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox homelab
 - Number of Longhorn volumes in the cluster: 2

## Additional context

I'm sure there's something misconfigured causing this, but as I understand things, I should be pretty vanilla here.

Only odd thing to call out is that I _used_ to be running on RancherOS (Kubelet at `/opt/rke/var/lib/kubelet`), and am now on Ubuntu (Kublet at `/var/lib/kubelet`), and had to follow some of the instructions here: https://longhorn.io/docs/1.4.1/advanced-resources/os-distro-specific/csi-on-rke-and-coreos/
to instruct my kubelet to utilize extra binds:

```
    extra_binds:
    - "/opt/rke/var/lib/kubelet/plugins:/var/lib/kubelet/plugins" 
    - "/opt/rke/var/lib/kubelet/plugins_registry:/var/lib/kubelet/plugins_registry"
``` 

before Longhorn would work (The CSI driver was putting everything in `/opt/rke/var/lib/kubelet/*` instead of `/var/lib/kubelet`).
Without doing this, Longhorn wouldn't work at all on my Ubuntu nodes.
Perhaps that's the problem, but if so, I'm rather confused as to why, and why this would be the outcome behavior.

Reviewing what logs I can, I have yet to be able to identify a smoking gun.
