### ISSUE TITLE
[BUG] RWX volume becomes faulted after the node reconnects

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5658]
## Describe the bug (🐛 if you encounter this issue)

In [node-disconnection](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/node-disconnection/) , case3 step4~5:

node is disconnected for 100 seconds and then reconnected, the volume becomes faulted after the node reconnects

## To Reproduce

Preparation:
1. Disable auto-salvage. 

1. Launch Longhorn.
2. Use statefulset launch a pod with the RWX volume and write some data.
`kubectl apply -f statefulset.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: k8s.gcr.io/nginx-slim:0.8
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 0.5Gi
```
</details>

3. Run command `sync` in pod, make sure data fulshed.
4. Disconnect the node to which the `shared-manager-pvc` is attached for 100 seconds
5. Wait for the node back and the volume reattachment.
6. After the volume is reattached, the pod will be automatically deleted and recreate.
7. Verify the data and the pod still works fine.
8. Repeat step 2~6 for 3 times.
9. Create, Attach, and detach other volumes to the recovered node. All volumes should work fine.
10. Remove Longhorn and repeat step 1~9 for 3 times.
![Screenshot_20230324_161038](https://user-images.githubusercontent.com/104337648/227466424-7caae034-1068-41fd-840e-36c77004d933.png)

## Expected behavior

The volume should be reattached after the node reconnects

## Log or Support bundle

[longhorn-support-bundle_ec7047cb-8d8a-4455-8c13-3e20680696e4_2023-03-24T08-10-11Z.zip](https://github.com/longhorn/longhorn/files/11059954/longhorn-support-bundle_ec7047cb-8d8a-4455-8c13-3e20680696e4_2023-03-24T08-10-11Z.zip)

## Environment

 - Longhorn version: `v1.3.3-rc2`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Rancher`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.24.10+k3s1`
   - Number of management node in the cluster: `1`
   - Number of worker node in the cluster: `3`
 - Node config
   - OS type and version:
   - CPU per node: `4`
   - Memory per node: `16`
   - Disk type(e.g. SSD/NVMe): `SSD`
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster: `1`

## Workaround

Enable salvage
