### ISSUE TITLE
[BUG] Blank Error message: trying to configure minIO S3 backup 

### ISSUE THREAD

**Issue by polhaghverdian** [longhorn/longhorn#5695]
I am trying to setup minIO backup, by partially following these guides.
* https://www.suse.com/c/rancher_blog/using-minio-as-backup-target-for-rancher-longhorn-2/
* https://staging--longhornio.netlify.app/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore

## To Reproduce

**1. First I deployed my secret looking like this:** 
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: KEY
  AWS_SECRET_ACCESS_KEY: SECRET
  AWS_ENDPOINTS: http://192.168.50.10:9000/
```

**2. Added backup target and secret inside Longhorn UI:** 

![Screenshot from 2023-04-01 22-46-34](https://user-images.githubusercontent.com/50968806/229313653-c38a1014-91ec-45f5-b40f-751ef545e4f2.png)

**2. Went to backup section in the UI:** 
I receive an empty error, with no information. Obviously, something isn't working.    

![Screenshot from 2023-04-01 22-44-46](https://user-images.githubusercontent.com/50968806/229313724-8eb57777-efa6-40dc-84bb-715d14ebf9b1.png)

## Log or Support bundle

2023-04-01T20:30:43.922726386Z time="2023-04-01T20:30:43Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=k8s-master-1.k8s.lab
2023-04-01T20:30:43.934746918Z time="2023-04-01T20:30:43Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=k8s-master-1.k8s.lab

## Environment

 - Longhorn version: 1.4.1
 - Installation method: HELM
 - Kubernetes 1.26.4
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
 - Underlying Infrastructure KVM
 - Number of Longhorn volumes in the cluster: 3

## Additional context
I have deployed Longhorn with the following values: 

```
service:
  ui:
    type: NodePort

persistence:
  defaultClassReplicaCount: 3

defaultSettings:
  defaultDataPath: /mnt/data
  taintToleration: node-role.kubernetes.io/master:NoSchedule
  createDefaultDiskLabeledNodes: true
  storageMinimalAvailablePercentage: 10
  defaultReplicaCount: 3

longhornManager:
  tolerations:
  - key: ""
    operator: "Exists"
    effect: "NoSchedule"

longhornDriver:
  tolerations:
  - key: ""
    operator: "Exists"
    effect: "NoSchedule"
```

**Comment by polhaghverdian** [comment]
Problem solved, I remove these from my configuration

```
longhornManager:
  tolerations:
  - key: ""
    operator: "Exists"
    effect: "NoSchedule"

longhornDriver:
  tolerations:
  - key: ""
    operator: "Exists"
    effect: "NoSchedule"
```
