### ISSUE TITLE
[TEST] Execute the Rancher integration test

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5708]
## What's the test to develop? Please describe
The test plan is in the PR - https://github.com/longhorn/longhorn-tests/pull/1295

We'll first execute the test cases of Drain and Upgrade scenarios with Longhorn 1.3.3-rc2

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Drain-using-rancher-ui
       Test cases 1-8 - @chriscchien
       Test cases 9-10 - @roger-ryao 
       Test case of `allow-if-replica-is-stopped` & `always-allow` - @roger-ryao 

- [x] Upgrade-using-rancher-ui
       Test cases 1-3 - @chriscchien 
       Test cases 4-6 - @roger-ryao 
       Test case with `allow-if-replica-is-stopped` - @chriscchien 
       Test case with `always-allow` - @roger-ryao 

~- [ ]  Upgrade-using-suc~ Rancher handles upgrade using suc implicitly 
     ~Test case 1 - @roger-ryao ~
    ~ Test case 2 -  @chriscchien ~

**Comment by chriscchien** [comment]
For test Drain-using-rancher-ui with Rancher `v2.7.1` and Longhorn `v1.3.3-rc2`, test case 1-8 all work well without any problem.

**Comment by chriscchien** [comment]
Below are test **Upgrade-using-rancher-ui** with Rancher `v2.7.1` and Longhorn `v1.3.3-rc2` result

Test with Longhorn default setting of 'Node Drain Policy': `block-if-contains-last-replica`
- [x] 1. Upgrade single node cluster using Rancher UI - RKE2 cluster
- [x] 2. Upgrade multi node cluster using Rancher UI - RKE2 cluster
- [x] 3. Upgrade multi node cluster using Rancher UI - RKE1 cluster

Test with Longhorn setting of 'Node Drain Policy': `allow-if-replica-is-stopped`
- [x] 1. Upgrade multi node cluster using Rancher UI - RKE2 cluster
- [x] 2. Upgrade multi node cluster using Rancher UI - RKE1 cluster
- Encounter 1 time upgrade failure because Rancher server can not connect to rancher container in 1 node, I think it's not related to longhorn and retry 2 more times were all success
- [x] 3. Upgrade multi node cluster using Rancher UI - K3s Imported cluster

**Comment by chriscchien** [comment]
Test **Upgrade-using-suc** with Rancher `v2.7.1` and Longhorn `v1.3.3-rc2` result:

- [x] 1 Test with Longhorn default setting of 'Node Drain Policy': `block-if-contains-last-replica`
- Worked well in imported k3s cluster, upgrade success, can access LH through Rancher proxy
- If k3s cluster create from Rancher server(rke1), system upgrade will fail because in nodes the upgrade controller pod can not find k3s process ID as below, I think it is reasonable but need confirm.
```
k logs apply-k3s-server-on-ip-172-31-24-240-with-2f3e0f77c5e5744-2smq4 -n system-upgrade
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $2}'
+ K3S_PID=
+ ps -p -o 'ppid='
+ xargs
error: process ID list syntax error
```

cc @khushboo-rancher

**Comment by roger-ryao** [comment]
- [x]  Test cases 9-10 
For test case 9-10, which work well without any problems. I recommend adding an additional step: after the drain is complete, uncordon the node using the Rancher UI and verify that the volume data is intact.
I suggest a modification to the test case in https://github.com/longhorn/longhorn-tests/pull/1295/files#r1161571170.

- [x]  Test case of `allow-if-replica-is-stopped`
  - Drain operation on a one node using Rancher UI - default value and `Delete Empty Dir Data` enabled
  - Drain operation on a multiple node using Rancher UI - default value
  - Drain operation on a multiple node using Rancher UI - Force
  
For the test case `allow-if-replica-is-stopped`, which is working well without any problems, I have another suggestion in https://github.com/longhorn/longhorn-tests/pull/1295/files#r1162512977 & 
https://github.com/longhorn/longhorn-tests/pull/1295/files#r1162477597.

**Comment by chriscchien** [comment]
> Test **Upgrade-using-suc** with Rancher `v2.7.1` and Longhorn `v1.3.3-rc2` result:
> 
> * [x]  1 Test with Longhorn default setting of 'Node Drain Policy': `block-if-contains-last-replica`
> * Worked well in imported k3s cluster, upgrade success, can access LH through Rancher proxy
> * If k3s cluster create from Rancher server(rke1), system upgrade will fail because in nodes the upgrade controller pod can not find k3s process ID as below, I think it is reasonable but need confirm.
> 
> ```
> k logs apply-k3s-server-on-ip-172-31-24-240-with-2f3e0f77c5e5744-2smq4 -n system-upgrade
> + upgrade
> + get_k3s_process_info
> + ps -ef
> + grep -E 'k3s .*(server|agent)'
> + grep -E -v '(init|grep|channelserver|supervise-daemon)'
> + awk '{print $2}'
> + K3S_PID=
> + ps -p -o 'ppid='
> + xargs
> error: process ID list syntax error
> ```
> 
> cc @khushboo-rancher

Update : Test Upgrade-using-suc with Rancher v2.7.1 and Longhorn `v1.3.3-rc3` result:

- [x] 1 Test with Longhorn default setting of 'Node Drain Policy': block-if-contains-last-replica
   - Worked well in Rancher provisioned k3s cluster
cc @khushboo-rancher

**Comment by roger-ryao** [comment]
The test cases `4-5` and the test cases with `always-allow` for `Upgrade-using-rancher-ui` were working well without any problems. Only case 6 had unexpected behavior, which I updated the status for in https://github.com/longhorn/longhorn-tests/pull/1295/files#r1163872524.

**Comment by roger-ryao** [comment]
Hi @khushboo-rancher 
    Regarding to `Upgrade multi node cluster using SUC - Concurrency of node to upgrade > 1`. After upgrading k3s, I was able to verify the correct k3s version on the node using kubectl. I also confirmed that volumes were healthy and data was intact after the k3s upgrade completed. However, I noticed that the cluster status in Rancher continued to show 'Updating' and 'Waiting for kubelet to update'. I'm not sure if this is due to a problem with my test method or a Rancher issue.
    
  
![Screenshot_20230413_182200](https://user-images.githubusercontent.com/104337648/231731070-e3d4188d-845f-493b-80d9-e48b40bbdf8d.png)


My test step as below.
    
1. Given Multi node (1 master and 3 worker) K3s cluster provisioned in Rancher with K3s prior version with Longhorn installed
2. AND System Upgrade Controller deployed
`kubectl apply -f system-upgrade-controller.yaml`

<details>
<summary>system-upgrade-controller.yaml</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: v1
data:
  SYSTEM_UPGRADE_CONTROLLER_DEBUG: "false"
  SYSTEM_UPGRADE_CONTROLLER_THREADS: "2"
  SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: "900"
  SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: "99"
  SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: Always
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: rancher/kubectl:v1.21.9
  SYSTEM_UPGRADE_JOB_PRIVILEGED: "true"
  SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: "900"
  SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: 15m
kind: ConfigMap
metadata:
  name: default-controller-env
  namespace: system-upgrade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  selector:
    matchLabels:
      upgrade.cattle.io/controller: system-upgrade-controller
  template:
    metadata:
      labels:
        upgrade.cattle.io/controller: system-upgrade-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - env:
        - name: SYSTEM_UPGRADE_CONTROLLER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['upgrade.cattle.io/controller']
        - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: default-controller-env
        image: rancher/system-upgrade-controller:v0.10.0
        imagePullPolicy: IfNotPresent
        name: system-upgrade-controller
        volumeMounts:
        - mountPath: /etc/ssl
          name: etc-ssl
        - mountPath: /etc/pki
          name: etc-pki
        - mountPath: /etc/ca-certificates
          name: etc-ca-certificates
        - mountPath: /tmp
          name: tmp
      serviceAccountName: system-upgrade
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/ssl
          type: Directory
        name: etc-ssl
      - hostPath:
          path: /etc/pki
          type: DirectoryOrCreate
        name: etc-pki
      - hostPath:
          path: /etc/ca-certificates
          type: DirectoryOrCreate
        name: etc-ca-certificates
      - emptyDir: {}
        name: tmp
```
</details>

3. AND few RWO and RWX volumes attached with node/pod exists
4. AND 1 RWO and 1 RWX volumes unattached
5. AND 1 RWO volume with 50 Gi data
6. When Set the concurrency to `2` in the plan `CR` and upgrade the cluster
`kubectl apply -f k3s-upgrade.yaml`

<details>
<summary>k3s-upgrade.yaml</summary>

```yaml
# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  tolerations: 
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoExecute
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: node-role.kubernetes.io/etcd
    operator: Exists
  serviceAccountName: system-upgrade
  drain:
    force: true
    skipWaitForDeleteTimeout: 60 # 1.18+ (honor pod disruption budgets up to 60 seconds per pod then moves on)
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.24.11+k3s1
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
spec:
  concurrency: 2
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/worker
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  drain:
    force: true
    skipWaitForDeleteTimeout: 60 # 1.18+ (honor pod disruption budgets up to 60 seconds per pod then moves on)
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.24.11+k3s1
```
</details>

7. Then Upgrade should be successful
8. AND Volumes should be healthy and data should be intact after upgrade completes
9. AND The volumes which were attached initially should be attached and the ones which is unattached should be unattached
10. AND Logs should not have any unexpected errors
