### ISSUE TITLE
[BUG] Observing repilca on new IM-r before upgrading of volume

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5729]
## Describe the bug (🐛 if you encounter this issue)

The volumes which are created with previous version appears with the latest version of IM-r before upgrade of volume was triggered.

## To Reproduce

1. Install Longhorn v1.3.2
2. Create volumes, attach to pods and write data into them.
3. Upgrade Longhorn v1.3.3-rc2 with `Automatic Engine Upgrade` disabled. Don't upgrade the volumes
4. Check the volumes, they are on old engine IM but on new replica IM.

## Expected behavior

IM-e and IM-r should be updated only after the volumes are upgraded.

## Log or Support bundle

<img width="2018" alt="Screenshot 2023-04-08 at 12 38 32 AM" src="https://user-images.githubusercontent.com/60111667/230709958-dad7295e-39b7-4b85-8580-487733c64de0.png">
[longhorn-support-bundle_5956057a-fd8d-4084-9021-3e0eb221bb8c_2023-04-08T07-41-05Z.zip](https://github.com/longhorn/longhorn/files/11182765/longhorn-support-bundle_5956057a-fd8d-4084-9021-3e0eb221bb8c_2023-04-08T07-41-05Z.zip)

## Environment

 - Longhorn version: v1.3.3-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.24.6
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

## Additional context

I did cordoned the nodes few times.

**Comment by innobead** [comment]
> IM-e and IM-r should be updated only after the volumes are upgraded.

@derekbit @shuo-wu @PhanLe1010  is this true? I thought replicas will be always upgraded except engine process except we upgrade engine.

**Comment by innobead** [comment]
@c3y1huang can u help check this issue? Thanks.

**Comment by PhanLe1010** [comment]
It is unexpected that replicas move to the new instance managers without engine live upgrade. Lets' me check the reproducing steps.

**Comment by PhanLe1010** [comment]
From the log bundle, let's consider the replica `bi-1-r-14652922` currently running on the new instance-manager-r `instance-manager-r-eda6de98a40a5bd739f564ebe25858a8`:
1. The new instance manager `instance-manager-r-eda6de98a40a5bd739f564ebe25858a8` was created at `2023-04-08T07:29:49Z`
2. There is a replica rebuilding at `2023-04-08T07:37:58Z`
    ```
      objectmeta:
        name: bi-1-e-36af5e7f.1753e58cc64de443
        generatename: ""
        namespace: longhorn-system
        creationtimestamp: "2023-04-08T07:37:58Z"
      involvedobject:
        kind: Engine
        namespace: longhorn-system
        name: bi-1-e-36af5e7f
      reason: Rebuilding
      message: Detected rebuilding replica bi-1-r-14652922 (10.42.2.51:10000)
    ```
It means that after the Longhorn upgrade, one the replica was crashed. As the result, it was recreated on the new instance manager because at this moment the default instance manger is the newer version.

Same thing happens to the replica `bi-1-r-86e3375d`. 

The replica `bi-1-r-434db62a` didn't crash so it remains on the old replica instance manager

I retried the reproducing step without trigger replica rebuild, the replicas remains in the old instance manager pods

**So the behavior is expected.**
