### ISSUE TITLE
Longhorn manager try to describe non existing node label

### ISSUE THREAD

**Issue by paalkr** [longhorn/longhorn#574]
Hi

I have deployed a HA K8s test-cluster on AWS for testing Longhorn, the underlying OS is CoreOS. The cluster has 3 etcd instances, two masters, 3 spotfleet worker nodes and two storage nodes (with a 500GB gp2 ebs volume each). My plan is to run longhorn on the storage nodes only, Any pods on nodes should be able to consume longhorn PVCs.

```
NAME                                        STATUS   ROLES          AGE    VERSION
ip-10-1-43-117.eu-west-1.compute.internal   Ready    master         2d1h   v1.13.5
ip-10-1-43-126.eu-west-1.compute.internal   Ready    node,spot      42h    v1.13.5
ip-10-1-43-24.eu-west-1.compute.internal    Ready    node,storage   105m   v1.13.5
ip-10-1-44-231.eu-west-1.compute.internal   Ready    master         2d1h   v1.13.5
ip-10-1-44-97.eu-west-1.compute.internal    Ready    node,spot      42h    v1.13.5
ip-10-1-45-198.eu-west-1.compute.internal   Ready    node,storage   105m   v1.13.5
ip-10-1-45-87.eu-west-1.compute.internal    Ready    node,spot      42h    v1.13.5
```

This is the state of pods after deploying longhorn. The driver installer waits for the init to finish (basically waiting for the backend service).
NAME                                        READY   STATUS     RESTARTS   AGE
```
engine-image-ei-9bea8a9c-564qj              1/1     Running    0          3h46m
engine-image-ei-9bea8a9c-f98wp              1/1     Running    0          3h46m
engine-image-ei-9bea8a9c-tlg59              1/1     Running    0          3h46m
longhorn-driver-deployer-6b4bfcbd99-92gv5   0/1     Init:0/1   0          3h46m
longhorn-manager-xb85z                      1/1     Running    35         3h46m
longhorn-manager-xdjl9                      1/1     Running    35         3h46m
longhorn-ui-6475bfbbd8-lxtjz                1/1     Running    0          3h46m
```

The managers DaemonSet pods are isolated to the storage nodes (using node selectors and affinity). So this seems to work. 
```
    spec:
      nodeSelector:
        kube-aws.coreos.com/role: storage    
      tolerations:
      - key: kube-aws.coreos.com/role
        operator: Equal
        value: storage
        effect: NoSchedule  
```
But is it the manager pods or the engine pods that a re responsible for adding the ebs volumes and managing the storage pool? The system architecture and which pod is responsible for what is a little unclear to me, after reading the documentation. 

The managers pods are constantly crashlooping, this is the output from the logs
```
...
time="2019-05-25T20:14:14Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-05-25T20:14:20Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-05-25T20:14:20Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:23Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:23Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:26Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-05-25T20:14:30Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:30Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-45-198.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node ip-10-1-43-24.eu-west-1.compute.internal:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-05-25T20:14:32Z" level=fatal msg="Error starting manager: failed to wait for engine image rancher/longhorn-engine:v0.5.0: Wait for engine image rancher/longhorn-engine:v0.5.0 timed out"
```
The manager is trying to parse a node label that deos not exists, `describe node` where the pod runs reveals that it does not have the `node-role.kubernetes.io/worker`, so it's pretty obvious why it fails. But why does the manager try to describe a node label that does not exist on the node?
```
Name:               ip-10-1-43-24.eu-west-1.compute.internal
Roles:              node,storage
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m5a.large
                    beta.kubernetes.io/os=linux
                    cputype=normal
                    failure-domain.beta.kubernetes.io/region=eu-west-1
                    failure-domain.beta.kubernetes.io/zone=eu-west-1a
                    kube-aws.coreos.com/autoscalinggroup=k8s6-Storage-1PWKNJJPPE5BU-Workers-C7BU4PXGMV6R
                    kube-aws.coreos.com/cluster=k8s6
                    kube-aws.coreos.com/launchconfiguration=
                    kube-aws.coreos.com/role=storage
                    kubernetes.io/hostname=ip-10-1-43-24.eu-west-1.compute.internal
                    kubernetes.io/role=node
                    node-role.kubernetes.io/node=
                    node-role.kubernetes.io/storage=
                    node.kubernetes.io/role=storage
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"5a:be:3d:18:cc:89"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.1.43.24
                    kube-aws.coreos.com/securitygroups: k8s6-Network-1AJ9I9AGCOR35-SecurityGroupWorker-5M4RWB63CGHZ
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 25 May 2019 16:42:42 +0200
```
Any help would be appreciated. It's also a little unclear to me how to configure this part of the driver-deployer deployment to use CSI. What do I have to uncomment or change? Do i have to manually choose flexvolume or csi, or is manual selection just an option to override automatic selection?
```
          # manually choose "flexvolume" or "csi"
          #- --driver
          #- flexvolume
          # manually set root directory for flexvolume
          #- --flexvolume-dir
          #- /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
          # manually set root directory for csi
          #- --kubelet-root-dir
          #- /var/lib/rancher/k3s/agent/kubelet
          # manually specify number of CSI attacher replicas
          #- --csi-attacher-replica-count
          #- "3"
          # manually specify number of CSI provisioner replicas
          #- --csi-provisioner-replica-count
          #- "3"
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          # For auto detection, leave this parameter unset
          #- name: FLEXVOLUME_DIR
            # FOR RKE
            #value: "/var/lib/kubelet/volumeplugins"
            # FOR GKE
            #value: "/home/kubernetes/flexvolume/"
```
