### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by hiseth** [longhorn/longhorn#5770]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:  v1.2.6
 - Kubernetes version:  v1.22.1
 - Node config
   - OS type and version   CentOS Linux release 7.9.2009 (Core)
   - CPU per node:   16c
   - Memory per node:  32g
   - Disk type: xfs
   - Network bandwidth and latency between the nodes:  calico
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):   vmware esxi

## Additional context

hello everyone 
how to expose longhorn iscsi port via service ?

this is a rwx volume configuration. i notice "share-manage" match pods.  and  how to expose iscsi?  have to a label match?  how to a label match?
```yaml
  selector:
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pkg-m2-rwx
  clusterIP: 10.0.0.136
  clusterIPs:
    - 10.0.0.136
  type: ClusterIP
```
