### ISSUE TITLE
[IMPROVEMENT] Document GCP bucket backups better at longhorn.io

### ISSUE THREAD

**Issue by cnorling** [longhorn/longhorn#5774]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The [_Setting a Backup Target_](https://staging--longhornio.netlify.app/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/) documentation doesn't give enough information about how to configure backups to a GCP bucket. I'd be willing to submit a PR for this if you feel the documentation is important.

## Describe the solution you'd like

- Document that yes, you do need to use the AWS arguments for GCP
- Document that the necessary region selector needing to be the person's country rather than region (eg: `foo@us` instead of `foo@us-west-3`)
- Document that you need to enable interoperability on the bucket, create an HMAC key, and bind it to a ServiceAccount with permissions to the bucket
- Document what the URL syntax for the bucket path should be

## Describe alternatives you've considered

I suppose not documenting this is an option, but I don't think it's really a good one. I think it would be helpful to people to not have to infer some of this stuff.

## Additional context

There are two issues to this project on github that give some vague insight into how to configure backups to a GCP bucket by using interoperability and an HMAC key, but a lot of the things you need to do aren't explicitly outlined.

https://github.com/longhorn/longhorn/issues/450
https://github.com/longhorn/longhorn/issues/2219

For those of you who are attempting to configure GCP backups and have found this issue, here's the rough working state and steps that I went through:

- create a google storage bucket
- create a serviceaccount that has permissions to create objects in the bucket
- go to the bucket's settings menu and create an HMAC key and bind it to the serviceaccount you just created
- go to longhorn's global settings and configure the backup target to be `s3://${BUCKET_NAME}@us/`
- go to longhorn's global settings and target a secret in the longhorn namespace 
- create the above secret in your k8s cluster with the following parameters:
```yaml
AWS_ENDPOINTS: aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29t      # this is just https://storage.googleapis.com
AWS_SECRET_ACCESS_KEY: jlkf3wjklsrkls/3jlkrjxdlkjkjcxkl      # this is called the hmac secret in GCP
AWS_ACCESS_KEY_ID: GOOG1ELKH3SJLKRJLK3SJLK4RSKULJRLKSIJRLKS  # this is called the hmac access key in GCP
```
