### ISSUE TITLE
[BUG] Longhorn Snapshots are not deleted after expired Backups (Velero) 

### ISSUE THREAD

**Issue by R-Studio** [longhorn/longhorn#5802]
## Describe the bug (🐛 if you encounter this issue)
We are using Velero to create backups from the Kubernetes manifests and the persistent volumes (in our example we backup Harbor).
If we create a backup, Velero saves the K8s manifests to a Object Storage (MinIO) and creates snapshots resources to trigger Longhorn backups with the `velero-plugin-for-csi`. Longhorn writes the backups to another MinIO bucket.
If we **delete a Velero backup** or the **backup is expired**, the **snapshot (`snapshots.longhorn.io`) are not deleted**:
![image](https://user-images.githubusercontent.com/7498854/234019298-e7cd2853-199b-4702-b020-24227c0a13bc.png)

We are using Velero v1.9.4 with `EnableCSI` feature and the following plugins:
- velero/velero-plugin-for-csi:v0.4.0
- velero/velero-plugin-for-aws:v1.6.0

We have the same issue in Velero v1.11.0 with `EnableCSI` feature and the following plugins:
- velero/velero-plugin-for-csi:v0.5.0
- velero/velero-plugin-for-aws:v1.6.0

## To Reproduce
1. Install the newest version of Velero and Rancher-Longhorn
2. In Longhorn configre a S3 Backup Target (we are usng MinIO for this)
3. Enable [CSI Snapshot Support for Longhorn](https://longhorn.io/docs/1.4.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/).
4. Create a backup (for example with the `Schedule` below): `velero backup create --from-schedule harbor-daily-0200`
5. Delete the backup `velero backup delete <BACKUPNAME>`
6. The snapshot (`snapshots.longhorn.io`) is not deleted.

## Expected behavior
The snapshot is deleted.

## Environment
 - Longhorn version: 102.2.0+up1.4.1
 - Velero version: 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher-Longhorn Helm Chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2, v1.25.7+rke2r1
   - Number of management node in the cluster: 1x
   - Number of worker node in the cluster: 3x
 - Node config
   - OS type and version: Ubuntu
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMs on Proxmox
 - Number of Longhorn volumes in the cluster: 17

### Velero Backup Schedule for Harbor
```yaml
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: harbor-daily-0200
  namespace: velero #Must be the namespace of the Velero server
spec:
  schedule: 0 0 * * *
  template:
    includedNamespaces:
    - 'harbor'
    includedResources:
    - '*'
    snapshotVolumes: true
    storageLocation: minio
    volumeSnapshotLocations:
      - longhorn
    ttl: 168h0m0s #7 Days retention
    defaultVolumesToRestic: false
    hooks:
      resources:
        - name: postgresql
          includedNamespaces:
          - 'harbor'
          includedResources:
          - pods
          excludedResources: []
          labelSelector:
            matchLabels:
              statefulset.kubernetes.io/pod-name: harbor-database-0
          pre:
            - exec:
                container: database
                command:
                  - /bin/bash
                  - -c
                  - "psql -U postgres -c \"CHECKPOINT\";"
                onError: Fail
                timeout: 30s
```

### VolumeSnapshotClass
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
```

### VolumeSnapshotClass
In our second cluster, with Velero v1.11.0 installed, we created the following resource (but same issue here):
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    velero.io/csi-volumesnapshot-class: 'true'
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
```

### VolumeSnapshotLocation
```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: longhorn
  namespace: velero
spec:
  provider: longhorn.io/longhorn
```

**Comment by R-Studio** [comment]
I have also opened an issue in velero: https://github.com/vmware-tanzu/velero/issues/6179

**Comment by R-Studio** [comment]
Maybe this issue is related to:
- https://github.com/vmware-tanzu/velero/issues/4383
- https://github.com/vmware-tanzu/velero/issues/3465
- https://github.com/longhorn/longhorn/issues/2029
-

**Comment by weizhe0422** [comment]
Would you mind providing the support bundle which includes the logs of CSI sidecars? Maybe it contains any clues about CSI external-snapshotter was triggered by Velero deleting backups.

**Comment by R-Studio** [comment]
@weizhe0422 here the support bundle. Thanks for any help.
**Info**
- Start Backup: 2023-05-01 09:12:59 +0200 CEST
- Complete Backup: 2023-05-01 09:14:29 +0200 CEST
- Delete Backup: 2023-05-01 09:17:34 +0200 CEST

[supportbundle_a3236774-99ca-4ab5-a2a5-74c925273bb4_2023-05-01T07-20-00Z.zip](https://github.com/longhorn/longhorn/files/11364105/supportbundle_a3236774-99ca-4ab5-a2a5-74c925273bb4_2023-05-01T07-20-00Z.zip)

**Comment by tcoupin** [comment]
Related to https://github.com/longhorn/longhorn/discussions/5797 ?

**Comment by R-Studio** [comment]
@tcoupin thanks but this is not a solution because if I use `--snapshot-volumes=false` then velero does not trigger a backup for the persistent volumes. So Velero only backups the manifests/YAML's.

**Comment by vineetsingh5** [comment]
I am also facing the same issue with v1.9.1
deleting velero backup is cleaning most of the resources related to corresponding backups like **backups.longhorn.io,** **volumesnapshotcontent**, **volumesnapshot** but **snapshot.longhorn.io** is still present in the system.

And backup started failing when number of snapshot objects increased> ~250. 

Sharing both longhorn support bundle as well as snapshot controller logs

[longhorn-support-bundle_8afefff1-085e-4f4e-97ae-3f0a518555ab_2023-05-09T05-19-35Z.zip](https://github.com/longhorn/longhorn/files/11427953/longhorn-support-bundle_8afefff1-085e-4f4e-97ae-3f0a518555ab_2023-05-09T05-19-35Z.zip)

[snapshot-controller.log](https://github.com/longhorn/longhorn/files/11427955/snapshot-controller.log)

**Comment by tcoupin** [comment]
I do not use `--snapshot-volumes=false` but I add a cronjob who deletes the snapshot.longhorn.io refered by backups.longhorn.io.

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: longhorn-system
  name: snapshot-cleaner
rules:
- apiGroups:
  - longhorn.io
  resources:
  - backups
  verbs:
  - 'list'
- apiGroups:
  - longhorn.io
  resources:
  - snapshots
  verbs:
  - 'list'
  - 'delete'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-cleaner
  namespace: longhorn-system
subjects:
- kind: ServiceAccount
  name: sa-snapshot-cleaner
  namespace: longhorn-system
roleRef:
  kind: Role
  name: snapshot-cleaner
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-snapshot-cleaner
  namespace: longhorn-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-cleaner
  namespace: longhorn-system
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 30
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
            - args:
                - '-c'
                - >-
                  cat <(kubectl get backups.longhorn.io -n longhorn-system -o
                  custom-columns=SNAPSHOT:.spec.snapshotName | grep
                  '^snapshot-'|sort|uniq) <(kubectl get snapshot.longhorn.io -n
                  longhorn-system -o custom-columns=SNAPSHOT:.metadata.name |
                  grep '^snapshot-'|sort|uniq)|sort|uniq -c|awk '$1==2 {print
                  $2}'|grep -v '^\n$'|xargs kubectl delete snapshot.longhorn.io
                  -n longhorn-system --wait=false
              command:
                - /bin/bash
              image: bitnami/kubectl:latest
              imagePullPolicy: Always
              name: snapshot-cleaner
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: sa-snapshot-cleaner
          serviceAccountName: sa-snapshot-cleaner
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false

**Comment by R-Studio** [comment]
When I create a backup via the Longhorn GUI and then delete this backup, no snapshots remain (everything works as expected).

**Comment by R-Studio** [comment]
I tried to reproduce the issue again by creating a `VolumeSnapshot` resource and afterwarts delete that and the issue occurs again.

**VolumeSnapshotClass**  
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    velero.io/csi-volumesnapshot-class: 'true'
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
```

**VolumeSnapshot**
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
  namespace: harbor
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: harbor-jobservice
```

![image](https://github.com/longhorn/longhorn/assets/7498854/e58b5068-27b5-4d2d-8d66-4e3336b7b7ca)  

Remove the `VolumeSnapshot`: `kubectl delete volumesnapshot new-snapshot-test -n harbor`

![image](https://github.com/longhorn/longhorn/assets/7498854/90c7c554-b789-4362-bf30-4ebd36b9f2a8)

- Why does Longhorn remain the snapshot?
- Why does it work in the GUI but not without it?

**Comment by R-Studio** [comment]
I still found something interesting in the `snapshot-controller` logs:  
![image](https://github.com/longhorn/longhorn/assets/7498854/f2ccd832-b942-4077-ab71-ac339355fddb)

**Comment by R-Studio** [comment]
Today I upgrade Longhorn from v1.4.1 to v1.4.2 and the issue still occurs. 😔😔

**Comment by R-Studio** [comment]
_Today I noticed that I have deployed a snapshot controller like described in this [documentation](https://longhorn.io/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/).
Although I already had an snapshot controller "rke2-snapshot-controller" on my cluster. I am not sure if this is comes with a rancher update or something. Anyway I removed my snapshot-controller and test the issue again._

**VolumeSnapshotClass**
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    velero.io/csi-volumesnapshot-class: 'true'
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
```

**VolumeSnapshot**
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
  namespace: harbor
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: harbor-jobservice
```

![image](https://github.com/longhorn/longhorn/assets/7498854/60f346d9-dc1f-4837-ba04-de0905504483)  
![image](https://github.com/longhorn/longhorn/assets/7498854/40cb3992-6eeb-46ad-b386-9e60a96c9963)

Remove the `VolumeSnapshot`: `kubectl delete volumesnapshot new-snapshot-test -n harbor`
![image](https://github.com/longhorn/longhorn/assets/7498854/7b057706-6b8d-4d0a-8efc-8600329a9f59)

The same issue occurs but there is some interessting logs:
- After I created the `VolumeSnapshot` the following logs are written:
![image](https://github.com/longhorn/longhorn/assets/7498854/6946532e-1b76-4c62-b692-36a6ccf5e849)
![image](https://github.com/longhorn/longhorn/assets/7498854/8d2539a2-ed3f-44df-8f87-376defcdc335)
