### ISSUE TITLE
[TEST] CSI VolumeSnapshot for BackingImage

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#5822]
## What's the test to develop? Please describe

We are now supporting using CSI VolumeSnapshot to manage BackingImage with following 4 use cases
- Users can use VolumeSnapshot with type `bi` to create/delete BackingImage
- Users can restore a Volume with a VolumeSnapshot (create a Volume with BackingImage)
- Users can restore a Volume with an existing BackingImage (pre-provision)
    - Create the VolumeSnapshot/VolumeSnapshotContent to associate to the existing BackingImage
- Users can restore a Volume with non-existing BackingImage (on-demand provision)
    - Create the VolumeSnapshot/VolumeSnapshotContent to provide BackingImage parameters
    - Create BackingImage based on the parameters when the users create PVC from the VolumeSnapshot 

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

Prerequisite
- Create a VolumeSnaoshotClass with type `bi`
```yaml
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bi
```

- [ ] Case 1. Test Create and Delete BackingImage using VolumeSnapshot with a given Volume

**Given** A Volume `test-vol` attached to a workload
**When** Creating a VolumeSnapshot
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-backing
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  source:
    persistentVolumeClaimName: test-vol
```
**Then** A BackingImage will be created with the follow properties
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: `snapshot-${VolumeSnapshot.uuid}`
  namespace: longhorn-system
spec:
  sourceType: export-from-volume
  sourceParameters:
    volume-name: test-vol
    export-type: raw
```

**When** Deleting the VolumeSnapshot
```shell
> kubectl delete vs/test-snapshot-backing
```

**Then** The BackingImage will be deleted as well

- [ ] Case 2. Test Restore Volume from CSI VolumeSnapshot

**Given** A VolumeSnapshot `test-snapshot-backing` and a BackingImage `snapshot-${VolumeSnapshot.uuid}`
**When** Create a PVC with `dataSource` pointing to VolumeSnapshot
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restore-pvc
spec:
  storageClassName: longhorn
  dataSource:
    name: test-snapshot-backing
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
**Then** a Longhorn Volume will be created using the BackingImage `snapshot-${VolumeSnapshot.uuid}` in its `spec`

- [ ] Case 3. Restore pre-provisioned BackingImage

**Given** a existing BackingImage, VolumeSnapshotContent and VolumeSnapshot
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: test-bi
  namespace: longhorn-system
spec:
  sourceType: download
  sourceParameters:
    url: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
  checksum: bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
```

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: test-existing-backing
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecksum=bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
  volumeSnapshotRef:
    name: test-snapshot-existing-backing
    namespace: default
```

**When** Creating a PVC pointing to the VolumeSnapshot
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restore-existing-backing
spec:
  storageClassName: longhorn
  dataSource:
    name: test-snapshot-existing-backing
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

**Then** a Longhorn Volume will be created using the BackingImage `test-bi` in its `spec`

- [ ] Case 4. Restore on-demand provisioned BackingImage

**Given** a VolumeSnapshotContent and VolumeSnapshot
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: test-existing-backing
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecksum=bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
  volumeSnapshotRef:
    name: test-snapshot-existing-backing
    namespace: default
```

**When** Creating a PVC pointing to the VolumeSnapshot
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restore-existing-backing
spec:
  storageClassName: longhorn
  dataSource:
    name: test-snapshot-existing-backing
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

**Then** a BackingImage `test-bi` will be created
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: test-bi
  namespace: longhorn-system
spec:
  sourceType: download
  sourceParameters:
    url: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
  checksum: bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
```

**Then** a Longhorn Volume will be created using the BackingImage `test-bi` in its `spec`

## Additional context

LEP: https://github.com/longhorn/longhorn/blob/master/enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md#test-plan
