### ISSUE TITLE
[TEST] Implement test case `test_csi_mount_volume_online_expansion`

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5839]
## What's the test to develop? Please describe

Implement test case `test_csi_mount_volume_online_expansion`

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Implement test case
- [ ] Verify on pipeline

## Additional context

N/A

**Comment by yangchiu** [comment]
@chriscchien `test_csi_mount_volume_online_expansion` failed on `master` and `v1.4.x` regression. It would be appreciated if you can take a look it. Thank you!

**Comment by chriscchien** [comment]
The failure on pipeline all failed at `expand_and_wait_for_pvc(core_api, pvc, (EXPANDED_VOLUME_SIZE+1)*Gi)`, it's due to 
wait `status.capacity.storage` time out. I will fix it, thank you

```
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: longhorn-test
    volumeMode: Filesystem
    volumeName: pvc-c5b0c85c-c7b1-4a81-82a8-2e644687fe34
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 4Gi
```
