### ISSUE TITLE
Add support for tolerating tainted nodes

### ISSUE THREAD

**Issue by paalkr** [longhorn/longhorn#584]
Ref
https://github.com/rancher/longhorn/issues/583
https://github.com/rancher/longhorn/issues/574

I have added dedicated nodes intended for Longhorn storage to my cluster, these nodes has EBS volumes attached. Other nodes does not have these extra storage volumes. So to make sure that the dedicated Longhorn nodes are not used for general purpose workloads they are tainted (and labeled).

```
Name:               ip-10-1-43-24.eu-west-1.compute.internal
Roles:              node,storage
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m5a.large
                    beta.kubernetes.io/os=linux
                    cputype=normal
                    failure-domain.beta.kubernetes.io/region=eu-west-1
                    failure-domain.beta.kubernetes.io/zone=eu-west-1a
                    kube-aws.coreos.com/autoscalinggroup=k8s6-Storage-1PWKNJJPPE5BU-Workers-C7BU4PXGMV6R
                    kube-aws.coreos.com/cluster=k8s6
                    kube-aws.coreos.com/launchconfiguration=
                    kube-aws.coreos.com/role=storage
                    kubernetes.io/hostname=ip-10-1-43-24.eu-west-1.compute.internal
                    kubernetes.io/role=node
                    node-role.kubernetes.io/node=
                    node-role.kubernetes.io/storage=
                    node.kubernetes.io/role=storage
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"5a:be:3d:18:cc:89"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.1.43.24
                    kube-aws.coreos.com/securitygroups: k8s6-Network-1AJ9I9AGCOR35-SecurityGroupWorker-5M4RWB63CGHZ
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 25 May 2019 16:42:42 +0200
Taints:             kube-aws.coreos.com/role=storage:NoSchedule
Unschedulable:      false
```

Currently there is no way to specify a taint for the `engine-image DaemonSet`. The result is that the Longhorn system doesn't start all it's components without manual editing of the DaemonSet created by the operator.

**Comment by yasker** [comment]
Let's revisit the issue after the engine process refactoring is done.

**Comment by yasker** [comment]
It's unlikely we will have time to work on this during v0.6.0 release. Push it to v0.7.0 release. We can pick it up from v0.7.0 release if we decided to do a v0.6.1 release instead.

**Comment by jonstelly** [comment]
For anyone else that finds themselves here, I just added a toleration (tolerate everything, just for testing) and it worked.  I added the toleration to the longhorn-manager, engine-image, and longhorn-csi-plugin daemonsets.

(kubernetes dashboard / json)
```
"tolerations": [
  {
    "operator": "Exists"
  }
]
```

(yaml)
```
tolerations:
- operator: "Exists"
```

And it seems

**Comment by paalkr** [comment]
Absolutely, it's possible to make post deployment edits to make tainted nodes work, as I described in this comment https://github.com/longhorn/longhorn/issues/574#issuecomment-496009473

**Comment by jonstelly** [comment]
Ah, I hadn't seen that, I saw that linked issue but didn't see your post with the toleration.  Out of curiosity, is the engine-image the only place I needed to add the toleration? i.e. not longhorn-manager or csi-plugins?

The longhorn documentation is well written and [this](https://rancher.com/blog/2017/announcing-longhorn-microservices-block-storage/) was really helpful, easier to digest than some of the other container attached storage options.  But I have to admit I'm not quite sure yet what function/responsibility maps to which kubernetes component (csi-plugin, etc...)

**Comment by paalkr** [comment]
It depends how you plan to operate the longhorn storage system, and how your kubernetes nodes are organized. I have dedicated nodes intended for longhorn storage backend which is tainted and labeled accordingly. And in that case you would also add taints to the manager DaemonSet. This is easier as the manager DaemonSet is something you deploy to your cluster yourself, and you can modify the asset before deployment.
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      # nodeSelector:
        # kube-aws.coreos.com/role: storage    
      tolerations:
      - key: kube-aws.coreos.com/role
        operator: Equal
        value: storage
        effect: NoSchedule         
      containers:
...

```

The engin-image DaemonSet on the other hand is created by the longhorn controller/operator, so that's why you have to post edit that one.
