### ISSUE TITLE
[TEST] Update test cases to exclude RWX from physical node down test cases

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5900]
## Describe the bug (🐛 if you encounter this issue)

According to the tests performed using https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-down/physical-node-down/ and https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/, we set `node-down-pod-deletion-policy` to `do-nothing` and `delete-statefulset-pod`, and created a `deployment` using a PVC with a 3-replica `RWX` volume. When we shut down the node to which the pod was attached, we found that the replacement pod did not get stuck in the `ContainerCreating` state forever. We didn't need to force delete the terminating pod, and the replacement pod started running successfully.

However, we have not tested `RWX` volume on this case before, and we were able to reproduce this issue on `v1.3.3`, `v1.4.0`, and `v1.4.1`.

## To Reproduce

1. Deploy longhorn with 3 replicas
2. Set node-down-pod-deletion-policy = `do-nothing` or `delete-statefulset-pod`
3. Create a deployment using the `RWX` volume PVC

<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```

4. After pod running, shutdown the node which node attached to

## Expected behavior

I just want to confirm whether the expected behavior is the same as for RWO volumes or not, as mentioned in the "[improve-node-failure-handling](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/)" test case.

## Log or Support bundle

[supportbundle_b97b5a61-66db-4732-9933-f01e1a9c1a8d_2023-05-10T03-46-09Z.zip](https://github.com/longhorn/longhorn/files/11438132/supportbundle_b97b5a61-66db-4732-9933-f01e1a9c1a8d_2023-05-10T03-46-09Z.zip)

## Environment

 - Longhorn version: 1.4.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.23.17+k3s1
   - Number of management node in the cluster:1
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
