### ISSUE TITLE
[BUG] HA 3 replica podAntiAffinity issue for longhorn-ui, longhorn-recovery-backend, longhorn-conversion-webhook, longhorn-admission-webhook

### ISSUE THREAD

**Issue by Jamison1** [longhorn/longhorn#5922]
Using helm to deploy HA longhorn with 3 replicas - one each on 3 dedicated storage nodes.  longhorn-ui, longhorn-recovery-backend, longhorn-conversion-webhook & longhorn-admission-webhook all deploy all 3 replicas on the same node (12 pods on one storage node!) making that node unavailable for the remaining longhorn pods that are still deploying.  I end up with longhorn-csi-plugin unable to deploy on that node (storage-01).  csi-* pods all deploy with podAntiAffinity the way they should.

```
longhorn-system   longhorn-admission-webhook-798f4c6b8b-2c625             1/1     Running     storage-01
longhorn-system   longhorn-admission-webhook-798f4c6b8b-hlxmx             1/1     Running     storage-01
longhorn-system   longhorn-admission-webhook-798f4c6b8b-k56kd             1/1     Running     storage-01
longhorn-system   longhorn-conversion-webhook-54946896dd-7svm6            1/1     Running     storage-01
longhorn-system   longhorn-conversion-webhook-54946896dd-bnh4p            1/1     Running     storage-01
longhorn-system   longhorn-conversion-webhook-54946896dd-wgrml            1/1     Running     storage-01
longhorn-system   longhorn-csi-plugin-dkdhj                               3/3     Running     storage-02
longhorn-system   longhorn-csi-plugin-ncgfp                               0/3     Pending     <none>
longhorn-system   longhorn-csi-plugin-rpjnf                               3/3     Running     storage-03
longhorn-system   longhorn-driver-deployer-67f94f947f-h8nwk               1/1     Running     storage-01
longhorn-system   longhorn-manager-gxfv7                                  1/1     Running     storage-03
longhorn-system   longhorn-manager-gznj6                                  1/1     Running     storage-01
longhorn-system   longhorn-manager-sm248                                  1/1     Running     storage-02
longhorn-system   longhorn-recovery-backend-5ccf9cc847-9nt2p              1/1     Running     storage-01
longhorn-system   longhorn-recovery-backend-5ccf9cc847-9vj7k              1/1     Running     storage-01
longhorn-system   longhorn-recovery-backend-5ccf9cc847-hblfh              1/1     Running     storage-01
longhorn-system   longhorn-ui-7dcddc7c45-5cz92                            1/1     Running     storage-01
longhorn-system   longhorn-ui-7dcddc7c45-rpfxw                            1/1     Running     storage-01
longhorn-system   longhorn-ui-7dcddc7c45-tdqzm                            1/1     Running     storage-01
```

Trying to figure out why podAntiAffinity is not working on the 4 pods described.  Taking longhorn-ui as an example - when looking at the helm chart I can see that `deployment-ui.yaml` has podAntiAffinity for the pod.  It just isn't working for my deployment and I'm not sure why.
```
spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - longhorn-ui
              topologyKey: kubernetes.io/hostname
```
## To Reproduce

1. Deploy with 3 dedicated storage nodes, setting nodeSelector and tolerations for the dedicated nodes in question.
2. Wait for all pods to deploy in HA configuration.
3. Notice 12 pods (3 of each) all deployed on the same node.
4. See `pending` status for `longhorn-csi-plugin` on overallocated node.

## Expected behavior

I expect longhorn pods to follow conventions for podAntiAffinity on all pods deployed through helm which for a 3 replicaset deployment means one pod per node.

## Configs
```
values:
      defaultSettings:
        createDefaultDiskLabeledNodes: true
        upgradeChecker: false
        replicaAutoBalance: best-effort
        systemManagedComponentsNodeSelector: "node-role.kubernetes.io/storage:storage"
        taintToleration: storage=true:NoSchedule
      longhornAdmissionWebhook:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      longhornConversionWebhook:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      longhornDriver:
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      longhornManager:
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      longhornRecoveryBackend:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      longhornUI:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/storage: storage
        tolerations:
          - key: "storage"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
```

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Ansible Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.26.4+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3 + 3 dedicated storage nodes
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 4-5
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Same motherboard/CPU/RAM running VM's on XCP-ng
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Xen/Baremetal
 - Number of Longhorn volumes in the cluster: 3?

## Additional context

I also have a `LimitRange` set for all pods in the longhorn-system namespace for testing pod limits.  If I remove the LimitRange the `longhorn-csi-plugin` will deploy just fine, but thats not the issue here.
```
apiVersion: v1
kind: LimitRange
metadata:
  name: longhorn-resource-limit-range
  namespace: longhorn-system
spec:
  limits:
  - defaultRequest:
      memory: 128Mi
      cpu: 150m
    default:
      memory: 200Mi
    type: Container
```
Typically, I like to use `requiredDuringSchedulingIgnoredDuringExecution:` when using podAntiAffinity.  I noticed the longhorn-ui uses `preferredDuringSchedulingIgnoredDuringExecution:`.
