### ISSUE TITLE
Cannot mount nfs

### ISSUE THREAD

**Issue by itmuckel** [longhorn/longhorn#594]
Hello!

I used the test configuration with nfs-ganesha that you provided in the docs to make a backup of my volumes to a hostPath on a specific node. Also the restore procedure worked fine.

Then I killed the NFS server and restarted it. It had the same configuration, but Longhorn was not able to connect to it / find the existing backups.

I then decided to switch to the newer docker-nfs-server. Here is my configuration file:

```
kind: Service
apiVersion: v1
metadata:
  namespace: longhorn-system
  name: longhorn-nfs
spec:
  selector:
    app: longhorn-nfs
  ports:
  - port: 2049

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: longhorn-system
  name: longhorn-nfs
  labels:
    app: longhorn-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-nfs
  template:
    metadata:
      labels:
        app: longhorn-nfs
    spec:
      nodeSelector:
        kubernetes.io/hostname: myNode
      volumes:
      - name: nfs-volume
        hostPath:
          path: /k8s-backup
          type: DirectoryOrCreate
      containers:
      - name: longhorn-nfs-container
        image: erichough/nfs-server:2.2.1
        env:
        - name: NFS_EXPORT_0
          value: "/opt/backupstore  *(rw,fsid=0,insecure,no_subtree_check,async)"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_MODULE"]
        volumeMounts:
        - name: nfs-volume
          mountPath: "/opt/backupstore"
```

Either it cannot connect to the server or it says "File or Directory doesn't exist". I tried a lot of configurations, but nothing worked. Can anyone spot a mistake in the configuration file or had similar problems?
