### ISSUE TITLE
[FEATURE] v2 volume supports live upgrade for data plane

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6001]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

The data path for SPDK volumes is established through spdk_tgt. To upgrade `spdk_tgt` without downtime, the bdev raids of attached volumes must be live migrated to the new `spdk_tgt`.

Subtasks
- [x] https://github.com/longhorn/longhorn/issues/6647
- [x] https://github.com/longhorn/longhorn/issues/8456
- [x] https://github.com/longhorn/longhorn/issues/8458
- [x] https://github.com/longhorn/longhorn/issues/8464

**Comment by derekbit** [comment]
Current design
![image](https://github.com/longhorn/longhorn/assets/12527233/cfd1e845-d744-4bac-8103-2973cc6ffada)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `84ba8e`)

- V2 volume attach/detach wokerd well
- Below V2 volume restore path worked well
   - Restore V2 volume to RWO V1 volume
   - Restore V2 volume to RWX V1 volume
   - Restore V2 volume to RWO V2 volume

**Comment by derekbit** [comment]
@chriscchien
Can you help verify the data plane APIs by the following steps?

1. Deploy a Longhorn v1.7.0-rc1 2-node cluster (node1: `rancher60-worker1`, node2:  `rancher60-worker2`)
2. Enable v2 data engine
3. Create workloads with v2 volumes
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-v2-data-engine
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  # backup, backingImage and snapshot related parameters are not supported in SPDK preview stage
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataEngine: "v2"
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-1
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test-1
    #image: nginx:stable-alpine
    image: docker.io/derekbit/sleep:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv-1
      mountPath: /data
    ports:
    - containerPort: 80
  nodeName: rancher60-worker1
  volumes:
  - name: volv-1
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-2
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test-2
    #image: nginx:stable-alpine
    image: docker.io/derekbit/sleep:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv-2
      mountPath: /data
    ports:
    - containerPort: 80
  nodeName: rancher60-worker1
  volumes:
  - name: volv-2
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc-2
```

Assume all volumes are running on the node `rancher60-worker1`.

4. Update Longhorn system by
    ```
    git clone https://github.com/derekbit/longhorn.git
    cd longhorn
    git checkout v2-volume-upgrade-control-plane
    helm upgrade longhorn -n longhorn-system ./chart
    ```
  After upgrading the system
    - instance-manager pods for v2 data engine should not be deleted and recreated
    - engines and replicas are still running

5. Set the node `rancher60-worker`'s `spec.upgradeRequested` to `true` by
```
kubectl -n longhorn-system patch nodes.longhorn.io rancher60-worker1 --type='merge' -p '{"spec":{"upgradeRequested":true}}'
```

6. Watch the engine by
```
kubectl -n longhorn-system get engines -o wide -w
```

Check
- Enter the instance-manager on `rancher60-worker1` and run `go-spdk-helper raid get`. You can find there is a raid bdev. It means the target of the volume is moved to `rancher60-worker2`.
- Enter the instance-manager on `rancher60-worker2` and run `go-spdk-helper raid get`. The output is empty

6. Upgrade the engines of the two volumes they are on the same node by
```
kubectl -n longhorn-system patch volume.longhorn.io pvc-0afebdb0-309f-4748-9f34-9ffe6c017abf --type='merge' -p '{"spec":{"image": "longhornio/longhorn-instance-manager:master-head", "targetNodeID":"rancher60-worker2"}}'

kubectl -n longhorn-system patch volume.longhorn.io pvc-2cf20e83-0642-4e25-8538-8f5faab83a4b --type='merge' -p '{"spec":{"image": "longhornio/longhorn-instance-manager:master-head", "targetNodeID":"rancher60-worker2"}}'
```

Check
1. The two engines state changes are `running -> suspended -> running`
2. Their images are updated to `longhornio/longhorn-instance-manager:master-head`.
3. The two volumes become `degraded`
4. Enter the instance-manager on `rancher60-worker1` and run `go-spdk-helper raid get`. The output is empty
5. Enter the instance-manager on `rancher60-worker2` and run `go-spdk-helper raid get`. You can find there is a raid bdev. It means the target of the volume is moved to `rancher60-worker2`.

7. Continue the upgrade task
```
kubectl -n longhorn-system patch volume.longhorn.io pvc-0afebdb0-309f-4748-9f34-9ffe6c017abf --type='merge' -p '{"spec":{"targetNodeID":"rancher60-worker1"}}'

kubectl -n longhorn-system patch volume.longhorn.io pvc-2cf20e83-0642-4e25-8538-8f5faab83a4b --type='merge' -p '{"spec":{"targetNodeID":"rancher60-worker1"}}'
```

Check
- The two engines state changes are `running -> suspended -> running`
- The two volumes are still `degraded`
- Enter the instance-manager on `rancher60-worker1` and run `go-spdk-helper raid get`. You can find there is a raid bdev. It means the target of the volume is moved to `rancher60-worker2`.
- Enter the instance-manager on `rancher60-worker2` and run `go-spdk-helper raid get`. The output is empty
