### ISSUE TITLE
Pod Security Policy result in failed to wait for engine image rancher/longhorn-engine

### ISSUE THREAD

**Issue by ChrisScottThomas** [longhorn/longhorn#603]
I have a PSP enabled cluster, which I am trying to deploy Longhorn to, using the YAML file.
The engine daemonset refuses to create, and I see no errors point to why it's not working, which is frustrating.

All I've done to make it work with PSP, is to add rules allowing the service account to use a privileged psp.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: longhorn-role
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - deployer
  verbs:
  - use
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["pods", "events", "persistentvolumes", "persistentvolumeclaims", "nodes", "proxy/nodes", "pods/log", "secrets", "services", "endpoints", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "statefulsets", "deployments"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["*"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csinodeinfos"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["volumes", "engines", "replicas", "settings", "engineimages", "nodes"]
  verbs: ["*"]
```

The psp being used:
```
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: deployer
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities: ['*']
  volumes: ['*']
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
```

The logs vary from:
```
klf -n longhorn-system longhorn-manager-j4wft
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn replica controller"
time="2019-06-21T07:05:31Z" level=info msg="Start kubernetes controller"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn Engine Image controller"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn node controller"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn volume controller"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn websocket controller"
time="2019-06-21T07:05:31Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn engine controller"
time="2019-06-21T07:05:31Z" level=info msg="Start Longhorn Setting controller"
time="2019-06-21T07:05:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:05:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
E0621 07:05:31.332097       1 engine_image_controller.go:185] fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps "engine-image-ei-9bea8a9c" not found
time="2019-06-21T07:05:31Z" level=warning msg="Dropping Longhorn engine image longhorn-system/ei-9bea8a9c out of the queue: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:05:37Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:05:43Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:05:49Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:05:55Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:01Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:06:01Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
E0621 07:06:01.157403       1 engine_image_controller.go:185] fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps "engine-image-ei-9bea8a9c" not found
time="2019-06-21T07:06:01Z" level=warning msg="Dropping Longhorn engine image longhorn-system/ei-9bea8a9c out of the queue: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:06:01Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:07Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:13Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:19Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:25Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:06:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
E0621 07:06:31.155196       1 engine_image_controller.go:185] fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps "engine-image-ei-9bea8a9c" not found
time="2019-06-21T07:06:31Z" level=warning msg="Dropping Longhorn engine image longhorn-system/ei-9bea8a9c out of the queue: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:06:31Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:37Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:43Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:49Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:06:55Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:01Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:07:01Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
E0621 07:07:01.156313       1 engine_image_controller.go:185] fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps "engine-image-ei-9bea8a9c" not found
time="2019-06-21T07:07:01Z" level=warning msg="Dropping Longhorn engine image longhorn-system/ei-9bea8a9c out of the queue: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:07:01Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:07Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:13Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:19Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:19Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"vm014182\", UID:\"abffe63d-9351-11e9-a4ec-005056980e68\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"729114\", FieldPath:\"\"}): type: 'Warning' reason: 'ManagerPodDown' Node vm014182 is down: the manager pod longhorn-manager-5v9vc is not running"
time="2019-06-21T07:07:24Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"vm014173\", UID:\"ac2c3515-9351-11e9-ba82-005056982ed0\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"729098\", FieldPath:\"\"}): type: 'Warning' reason: 'ManagerPodDown' Node vm014173 is down: the manager pod longhorn-manager-54rkt is not running"
time="2019-06-21T07:07:25Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:07:31Z" level=warning msg="Error syncing Longhorn engine image longhorn-system/ei-9bea8a9c: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
E0621 07:07:31.153547       1 engine_image_controller.go:185] fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps "engine-image-ei-9bea8a9c" not found
time="2019-06-21T07:07:31Z" level=warning msg="Dropping Longhorn engine image longhorn-system/ei-9bea8a9c out of the queue: fail to sync engine image for longhorn-system/ei-9bea8a9c: cannot cleanup daemonset of engine image ei-9bea8a9c: daemonsets.apps \"engine-image-ei-9bea8a9c\" not found"
time="2019-06-21T07:07:31Z" level=fatal msg="Error starting manager: failed to wait for engine image rancher/longhorn-engine:v0.5.0: Wait for engine image rancher/longhorn-engine:v0.5.0 timed out"
```

```
klf -n longhorn-system longhorn-manager-54rkt
time="2019-06-21T07:07:49Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:49Z" level=info msg="Start kubernetes controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn replica controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn engine controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn websocket controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn Setting controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn node controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn volume controller"
time="2019-06-21T07:07:49Z" level=info msg="Start Longhorn Engine Image controller"
time="2019-06-21T07:07:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"vm014173\", UID:\"ac2c3515-9351-11e9-ba82-005056982ed0\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"729338\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node vm014173 is ready"
time="2019-06-21T07:07:50Z" level=debug msg="Requeue longhorn-system/vm014173 due to conflict"
time="2019-06-21T07:07:55Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:07:59Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"vm014175\", UID:\"aa302037-9351-11e9-a4ec-005056980e68\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"729323\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node vm014175 is ready"
time="2019-06-21T07:08:01Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:07Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:13Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:19Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:25Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:31Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:37Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:43Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:49Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:08:55Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:01Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:07Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:13Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:19Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:25Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:31Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:37Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:43Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-06-21T07:09:48Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"vm014182\", UID:\"abffe63d-9351-11e9-a4ec-005056980e68\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"729487\", FieldPath:\"\"}): type: 'Warning' reason: 'ManagerPodDown' Node vm014182 is down: the manager pod longhorn-manager-5v9vc is not running"
time="2019-06-21T07:09:49Z" level=fatal msg="Error starting manager: failed to wait for engine image rancher/longhorn-engine:v0.5.0: Wait for engine image rancher/longhorn-engine:v0.5.0 timed out"
```

Where should I be looking to fix these issues?  Why would adding PSP create such problems?

**Comment by ChrisScottThomas** [comment]
It looks like the engine-image daemonset, created by the manager, isn't inheriting the roles set.  So get's blocked from spawning?

```
k describe daemonset -n longhorn-system engine-image-ei-9bea8a9c
Name:           engine-image-ei-9bea8a9c
Selector:       longhorn=engine-image
Node-Selector:  <none>
Labels:         longhorn=engine-image
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  longhorn=engine-image
  Containers:
   engine-image-ei-9bea8a9c:
    Image:      rancher/longhorn-engine:v0.5.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
    Args:
      -c
      cp /usr/local/bin/longhorn* /data/ && echo installed && trap 'rm /data/longhorn* && echo cleaned up' EXIT && sleep infinity
    Readiness:    exec [ls /data/longhorn] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data/ from data (rw)
  Volumes:
   data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.5.0
    HostPathType:
Events:
  Type     Reason        Age                 From                  Message
  ----     ------        ----                ----                  -------
  Warning  FailedCreate  13s (x15 over 95s)  daemonset-controller  Error creating: pods "engine-image-ei-9bea8a9c-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

**Comment by ChrisScottThomas** [comment]
Adding:
```
serviceAccount: longhorn-service-account
serviceAccountName: longhorn-service-account
```

to the `daemonset.apps/engine-image-ei-9bea8a9c` manually, has made them spawn.  Bad times, as this is generated by the manager...

**Comment by ChrisScottThomas** [comment]
This is the least privileged PSP required to run Longhorn, if anyone else is wanting to do this:
```apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-longhorn-system
spec:
  allowedCapabilities:
  - SYS_ADMIN
  allowedHostPaths:
  - pathPrefix: /var/run/
    readOnly: false
  - pathPrefix: /lib/modules
    readOnly: false
  - pathPrefix: /var/lib/kubelet/plugins
    readOnly: false
  - pathPrefix: /var/lib/rancher/longhorn/
    readOnly: false
  - pathPrefix: /dev/
    readOnly: false
  - pathPrefix: /var/lib/kubelet/plugins/io.rancher.longhorn
    readOnly: false
  - pathPrefix: /var/lib/kubelet/pods
    readOnly: false
  - pathPrefix: /dev
    readOnly: false
  - pathPrefix: /sys
    readOnly: false
  - pathPrefix: /proc/
    readOnly: false
  fsGroup:
    rule: RunAsAny
  privileged: true
  hostPID: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
```

This still requires a manual edit to the engine-image daemonset to make work under PSP/RBAC security, however.

**Comment by yasker** [comment]
@ChrisScottThomas Thanks for reporting this issue with Pod Security Policy. We haven't looked into the PSP yet so that's why you've encountered some problems.

Regarding why Longhorn needs those directories, many of them Longhorn indeed needs. A few I can explain without further looking up into the code:
- `/var/lib/kubelet/plugins`: Kubernetes requires it for CSI driver
- `/var/lib/kubelet/plugins/io.rancher.longhorn`: Same as above
- `/var/lib/kubelet/pods`: Same as above
- `/dev`: Longhorn provides block devices, need to access to the `/dev` for that
- `/proc`: Need to access host namespace for iscsiadm
- `/var/lib/rancher/longhorn/`: default working directory for Longhorn. Also used as the default directory for store data.

A few of them is due to legacy issues and we will double check if they're really needed.

**Comment by ChrisScottThomas** [comment]
No worries :)  In regards to the directory access, IMO it'd be better if they aren't mounted as read/write if they only need to read.  It'd enable a bit more tightening on the PSP and turn some of those `readOnly: false` to true.  If you set any to true, you block the deployment as the volumes are being mounted as rw be default.

```
Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/rancher/longhorn/ from longhorn (rw)
      /var/run/ from varrun (rw)
```
which earns you a bunch of these:
```
Warning  FailedCreate  7s (x12 over 17s)  daemonset-controller  Error creating: pods "longhorn-manager-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].volumeMounts[0].readOnly: Invalid value: false: must be read-only spec.containers[0].volumeMounts[1].readOnly
```

More pressing concern is the need to manually add the serverAccount/serviceAccountName to the engine-image daemonset, in order to get it to deploy.

**Comment by yasker** [comment]
@ChrisScottThomas Thanks for understanding. We will look into the daemonset permission issue. Let's keep this issue open to track the daemonset issue.

**Comment by ChrisScottThomas** [comment]
I stumbled across a potential fix here, which is to add the service account to the longhorn-manager init container.
```
      initContainers:
        - name: wait-longhorn-manager
          image: rancher/longhorn-manager:v0.5.0
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      serviceAccountName: longhorn-service-account
```

Everything started up first time.

**Comment by yasker** [comment]
@ChrisScottThomas You meant, add init container for longhorn-manager fixes the permission issue for the engine daemonset deployment?

**Comment by ChrisScottThomas** [comment]
@yasker - no, this init container exists in the yamls.
https://github.com/longhorn/longhorn/blob/d02316da0d6f0dec07e781edf2cb23aa5d8464fe/deploy/longhorn.yaml#L309

**Comment by meldafrawi** [comment]
Validation: **PASSED**


Steps to test:   Thanks to @shuo-wu
  - Deploy a cluster with Pod Security Policy (psp) enabled. (In Rancher UI, enable psp. choose restricted psp as default psp).
  - In the cluster, delete the default psp. kubectl get psp should return restricted psp only.
  - Verify PSP works: directly deploying Longhorn, no components can be installed
  - Add pod security policy
```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: longhorn-pod-security-policy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
```
  - Modify the service account to use pod security policy
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: longhorn-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
    - longhorn-pod-security-policy
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["pods", "events", "persistentvolumes", "persistentvolumeclaims", "nodes", "proxy/nodes", "pods/log", "secrets", "services", "endpoints", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "statefulsets", "deployments"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["*"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csinodeinfos"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["volumes", "engines", "replicas", "settings", "engineimages", "nodes", "instancemanagers"]
  verbs: ["*"]
```
  - Deploy Longhorn

>> Expected Result: Longhorn components should be working fine.
