### ISSUE TITLE
[BUG] RWX block volumes can not mounted

### ISSUE THREAD

**Issue by 1iza** [longhorn/longhorn#6047]
## Describe the bug (🐛 if you encounter this issue)

When I create a pvc, the volumeMode is block, the accessMode is rwx, the volume is created successfully, but it cannot be mounted to multiple pods on different nodes

## To Reproduce

1. I modified the official rwx example，add the volumeMode attribute
```
apiVersion: v1
kind: Service
metadata:
  name: rwx-test
  labels:
    app: rwx-test
spec:
  ports:
    - port: 80
  selector:
    app: rwx-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-test
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwx-test
  labels:
    app: rwx-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rwx-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rwx-test
    spec:
      containers:
        - image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - sleep 10; touch /data/index.html; while true; do date >> /data/index.html; sleep 1; done;
          name: rwx-test
          stdin: true
          tty: true
          volumeDevices:
            - devicePath: /dev/xvda
              name: rwx-test
        - image: nginx:stable
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeDevices:
            - devicePath: /dev/xvda
              name: rwx-test
      restartPolicy: Always
      volumes:
        - name: rwx-test
          persistentVolumeClaim:
            claimName: rwx-test

```
pods  unable to attach or mount volumes

## Expected behavior

All three pods can be started successfully

## Log or Support bundle

```
longhorn-csi-plugin  time="2023-06-02T03:31:18Z" level=error msg="NodePublishVolume: err: rpc error: code = Internal desc = Could not mount \"/dev/longhorn/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5\" at \"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5/05103faa-cde4-4ab8-967d-e9033e17ae3e\": mount failed: exit status 32\nMounting command: mount\nMounting arguments:  -o bind /dev/longhorn/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5 /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5/05103faa-cde4-4ab8-967d-e9033e17ae3e\nOutput: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5/05103faa-cde4-4ab8-967d-e9033e17ae3e: special device /dev/longhorn/pvc-64a3cbbc-3e65-4ed8-b06d-102d9a4462a5 does not exist.\n"
```

## Environment

 - Longhorn version: v1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  k8s 1.24.10
