### ISSUE TITLE
[BUG] Resize RWX PVC Fails

### ISSUE THREAD

**Issue by 0xEmma** [longhorn/longhorn#6050]
## Describe the bug (🐛 if you encounter this issue)

resize2fs fails to find superblock on resize

## To Reproduce

1. goto longhorn UI
2. resize FS
3. restart pod
4. erorr

## Expected behavior

Resize2fs should happen

## Log or Support bundle
Node 1:

MountVolume.Setup failed while expanding volume for volume "pvc-0eb6d5e9-bda4-4b05-aa2f-dd7644b6e72d" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = resize of device /dev/longhorn/pvc-0eb6d5e9-bda4-4b05-aa2f-dd7644b6e72d failed: exit status 1. resize2fs output: resize2fs 1.46.4 (18-Aug-2021) resize2fs: Device or resource busy while trying to open /dev/longhorn/pvc-0eb6d5e9-bda4-4b05-aa2f-dd7644b6e72d Couldn't find valid filesystem superblock

Node 2:
MountVolume.Setup failed while expanding volume for volume "pvc-0eb6d5e9-bda4-4b05-aa2f-dd7644b6e72d" : Expander.NodeExpand failed to expand the volume : rpc error: code = Unknown desc = unknown filesystem type for volume pvc-0eb6d5e9-bda4-4b05-aa2f-dd7644b6e72d node expansion
## Environment

 - Longhorn version:v1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 32
   - Memory per node: 512gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal + DO
 - Number of Longhorn volumes in the cluster: 11

**Comment by 0xEmma** [comment]
Was able to fix by restoring from snapshot, only thing i could think of would be resizing during a replication caused this.

**Comment by ejweber** [comment]
Thanks for opening the issue @0xEmma. Do you happen to have a support bundle captured when the issue was occurring? Without one, it will be difficult to make much progress here. Replication happens on the backend, and shouldn't affect the ability to resize a volume (and its existing replicas), but anything's possible. It does sound like we had some kind of corruption event occur though.

Were you purposely resizing the volume?

**Comment by 0xEmma** [comment]
Yes I was resizing the volume on purpose. I don't have a support bundle, but let me see if I can recreate the issue

**Comment by 0xEmma** [comment]
Had it occur again @ejweber, no replication in proccess. Got a support bundle this time. should i post it here?

**Comment by ejweber** [comment]
Yes please, @0xEmma. If you are uncomfortable doing so, you can also use longhorn-support-bundle@suse.com.

**Comment by PhanLe1010** [comment]
I don't seem to see the `resize FS` option in UI. Could you give some screenshots for reproducing step @0xEmma ?

**Comment by 0xEmma** [comment]
I was able to trigger this issue two ways @PhanLe1010 

One: Updating the PVC Size in the spec,
Two: "Expand Volume" in the longhorn UI

**Comment by paravibe** [comment]
I have the same issue. My workaround is to scale down the workload then go to Longhorn UI and expand volume to a new size and scale up workload.

**Comment by PhanLe1010** [comment]
I am thinking if this issue is related to the bug we found in https://github.com/longhorn/longhorn/issues/6076. Though it is SLES OS on that ticket. What is the kernel version are you guys using?

**Comment by paravibe** [comment]
@PhanLe1010 
I have 6.0.0-0.deb11.6-amd64

**Comment by 0xEmma** [comment]
> I am thinking if this issue is related to the bug we found in #6076. Though it is SLES OS on that ticket. What is the kernel version are you guys using?

5.15.0-73-generic

**Comment by 0xEmma** [comment]
Upgraded from v1.4.1 -> v1.4.2, and had to resize a PVC again, no error this time

**Comment by PhanLe1010** [comment]
Base on this finding https://github.com/longhorn/longhorn/issues/6076#issuecomment-1583853637, it looks like your kernel versions (5.15 and  6.0) are effected by the upstream bug.

Btw, what are the host filesystem are you using? (output of `df -Th`)

**Comment by 0xEmma** [comment]
I had this occur on both an BTRFS backed node, and a ZFS backed node, with a ext4 zvol for longhorn

**Comment by PhanLe1010** [comment]
@0xEmma Looks like you hit the kernel bug. All of your info matches

**Comment by fabpico** [comment]
> I am thinking if this issue is related to the bug we found in #6076. Though it is SLES OS on that ticket. What is the kernel version are you guys using?

Happens also on kernel version `5.15.0-88-generic`.

**Comment by derekbit** [comment]
@fabpico 
Can you upgrade the kernel? Ref: https://github.com/longhorn/longhorn/issues/6076#issuecomment-1583853637

**Comment by theblinkingusb** [comment]
Just mentioning - I also experienced on v1.5.1 on 5.15.0-91-generic - followed what @paravibe suggested as workaround. Thanks all -

**Comment by technatelogy** [comment]
This happened to me on Longhorn 1.5.3 on an RWX volume on kernel 5.10.0-25-cloud-amd64. @paravibe's workaround worked for me as well.

**Comment by janosmiko** [comment]
The same issue still occurs for us using Longhorn 1.6.1 using RWX volume.
cc: @derekbit

**Comment by derekbit** [comment]
@janosmiko 
Only happened on RWX volumes?

**Comment by janosmiko** [comment]
Yep, only with the RWX volumes and it's pretty easy to reproduce in my cluster with just a pvc and deployment.

pvc
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwx
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
```

deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rwx
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-rwx
  template:
    metadata:
      labels:
        app: test-rwx
    spec:
      containers:
      - name: test-rwx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-rwx
      volumes:
      - name: test-rwx
        persistentVolumeClaim:
          claimName: test-rwx
```

Then I just patch the pvc and restart the workload.

```console
$ kubectl patch -n test pvc test-rwx -p '{"spec":{"resources":{"requests":{"storage":"5Gi"}}}}'
```

However, while I tested it (with attaching it to a pod, and not a deployment) sometimes the share-manager-pvc-xyz pod was restarted.
