### ISSUE TITLE
[BUG] Test case test_inc_restoration_with_multiple_rebuild_and_expansion failed on SLES

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6089]
## Describe the bug (🐛 if you encounter this issue)

I have observed that the test case `test_inc_restoration_with_multiple_rebuild_and_expansion` is failing on **SLES**.
The pod `longhorn-testvol-z4fr1v-dr-pod` is stuck in the `ContainerCreating` status. When I describe the pod, I observe that it has a `FailedMount` error.

```yaml
Events:
  Type     Reason                  Age                            From                     Message
  ----     ------                  ----                           ----                     -------
  Warning  FailedScheduling        <invalid>                      default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Warning  FailedScheduling        <invalid>                      default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Normal   Scheduled               <invalid>                      default-scheduler        Successfully assigned default/longhorn-testvol-z4fr1v-dr-pod to ip-172-31-6-104
  Normal   SuccessfulAttachVolume  <invalid>                      attachdetach-controller  AttachVolume.Attach succeeded for volume "longhorn-testvol-z4fr1v-dr-pv"
  Warning  FailedMount             <invalid> (x5 over <invalid>)  kubelet                  MountVolume.MountDevice failed for volume "longhorn-testvol-z4fr1v-dr-pv" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/longhorn-testvol-z4fr1v-dr /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5956bcd83d8c52a5b4c47fc44f89dc57957a1d8ced23db83c19d63d7372c1dff/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5956bcd83d8c52a5b4c47fc44f89dc57957a1d8ced23db83c19d63d7372c1dff/globalmount: cannot mount; probably corrupted filesystem on /dev/longhorn/longhorn-testvol-z4fr1v-dr.

```

1. The cluster has passed the test on Ubuntu.
2. I also attempted to reproduce the issue manually, but I was unable to reproduce it.

## To Reproduce

1. https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/
2. Verify test result of `test_inc_restoration_with_multiple_rebuild_and_expansion`

## Expected behavior

We should have consistent test results on all distro.

## Log or Support bundle

[supportbundle_25926798-7a96-43ab-9475-7000c75df7a9_2023-06-09T00-16-29Z.zip](https://github.com/longhorn/longhorn/files/11701161/supportbundle_25926798-7a96-43ab-9475-7000c75df7a9_2023-06-09T00-16-29Z.zip)

```python
_________________________________________ test_inc_restoration_with_multiple_rebuild_and_expansion[s3] __________________________________________

set_random_backupstore = None, client = <longhorn.Client object at 0x7fa91850ea30>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7fa918681d30>, volume_name = 'longhorn-testvol-z4fr1v'
storage_class = {'allowVolumeExpansion': True, 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClass', 'metadata': {'name': 'longhorn-test'}, ...}
csi_pv = {'apiVersion': 'v1', 'kind': 'PersistentVolume', 'metadata': {'name': 'longhorn-testvol-s0m67g'}, 'spec': {'accessMode...aleReplicaTimeout': '30'}, 'volumeHandle': 'longhorn-testvol-s0m67g'}, 'persistentVolumeReclaimPolicy': 'Delete', ...}}
pvc = {'apiVersion': 'v1', 'kind': 'PersistentVolumeClaim', 'metadata': {'name': 'pvc-std-pod-for-dr-expansion-and-rebuildin...{'accessModes': ['ReadWriteOnce'], 'resources': {'requests': {'storage': '3Gi'}}, 'storageClassName': 'longhorn-test'}}
pod_make = <function pod_make.<locals>.make_pod at 0x7fa9184da280>

    def test_inc_restoration_with_multiple_rebuild_and_expansion(set_random_backupstore, client, core_api, volume_name, storage_class, csi_pv, pvc, pod_make): # NOQA
        """
        [HA] Test if the rebuild is disabled for the DR volume
        1. Setup a random backupstore.
        2. Create a pod with a volume and wait for pod to start.
        3. Write data to the volume and get the md5sum.
        4. Create the 1st backup for the volume.
        5. Create a DR volume based on the backup
           and wait for the init restoration complete.
        6. Shutdown the pod and wait for the std volume detached.
        7. Offline expand the std volume and wait for expansion complete.
        8. Re-launch a pod for the std volume.
        9. Write more data to the std volume. Make sure there is data in the
           expanded part.
        10. Create the 2nd backup and wait for the backup creation complete.
        11. For the DR volume, delete one replica and trigger incremental restore
            simultaneously.
        12. Wait for the inc restoration complete and the volume becoming Healthy.
        13. Check the DR volume size and snapshot info. Make sure there is only
            one snapshot in the volume.
        14. Online expand the std volume and wait for expansion complete.
        15. Write data to the std volume then create the 3rd backup.
        16. Trigger the inc restore then re-verify the snapshot info.
        17. Activate the DR volume.
        18. Create PV/PVC/Pod for the activated volume
            and wait for the pod start.
        19. Check if the restored volume is state `healthy`
            after the attachment.
        20. Check md5sum of the data in the activated volume.
        21. Crash one random replica. Then verify the rebuild still works fine for
            the activated volume.
        22. Do cleanup.
        """
        update_setting(client, common.SETTING_DEGRADED_AVAILABILITY, "false")
        create_storage_class(storage_class)
    
        original_size = 1 * Gi
        std_pod_name = 'std-pod-for-dr-expansion-and-rebuilding'
        std_pvc_name = "pvc-" + std_pod_name
        pvc['metadata']['name'] = std_pvc_name
        pvc['spec']['storageClassName'] = storage_class['metadata']['name']
        pvc['spec']['resources']['requests']['storage'] = \
            str(original_size)
        create_pvc(pvc)
    
        std_pod_manifest = pod_make(name=std_pod_name)
        std_pod_manifest['spec']['volumes'] = [create_pvc_spec(std_pvc_name)]
        create_and_wait_pod(core_api, std_pod_manifest)
    
        std_pv = wait_and_get_pv_for_pvc(core_api, std_pvc_name)
        assert std_pv.status.phase == "Bound"
        std_volume_name = std_pv.spec.csi.volume_handle
        std_volume = wait_for_volume_healthy(client, std_volume_name)
    
        # Create the 1st backup.
        data_path1 = "/data/test1"
        write_pod_volume_random_data(core_api, std_pod_name,
                                     data_path1, DATA_SIZE_IN_MB_4)
        std_md5sum1 = get_pod_data_md5sum(core_api, std_pod_name, data_path1)
    
        snap1 = create_snapshot(client, std_volume_name)
        std_volume.snapshotBackup(name=snap1.name)
        wait_for_backup_completion(client,
                                   std_volume_name,
                                   snap1.name,
                                   retry_count=600)
        bv, b1 = find_backup(client, std_volume_name, snap1.name)
    
        # Create the DR volume
        dr_volume_name = volume_name + "-dr"
        client.create_volume(name=dr_volume_name, size=str(1 * Gi),
                             numberOfReplicas=3, fromBackup=b1.url,
                             frontend="", standby=True)
        wait_for_volume_creation(client, dr_volume_name)
        wait_for_volume_healthy_no_frontend(client, dr_volume_name)
        wait_for_backup_restore_completed(client, dr_volume_name, b1.name)
    
        # Step 7: Do offline expansion for the std volume.
        delete_and_wait_pod(core_api, std_pod_name)
        wait_for_volume_detached(client, std_volume_name)
        expand_size1 = 2 * Gi
        expand_and_wait_for_pvc(core_api, pvc, expand_size1)
        wait_for_volume_expansion(client, std_volume_name)
        std_volume = wait_for_volume_detached(client, std_volume_name)
        assert std_volume.size == str(expand_size1)
    
        # Re-launch the pod
        create_and_wait_pod(core_api, std_pod_manifest)
        wait_for_volume_healthy(client, std_volume_name)
    
        # Step 9:
        # When the total writen data size is more than 1Gi, there must be data in
        # the expanded part.
        data_path2 = "/data/test2"
        write_pod_volume_random_data(core_api, std_pod_name,
                                     data_path2, DATA_SIZE_IN_MB_4)
        std_md5sum2 = get_pod_data_md5sum(core_api, std_pod_name, data_path2)
        snap2 = create_snapshot(client, std_volume_name)
        std_volume = client.by_id_volume(std_volume_name)
        std_volume.snapshotBackup(name=snap2.name)
        wait_for_backup_completion(client, std_volume_name, snap2.name,
                                   retry_count=600)
        bv, b2 = find_backup(client, std_volume_name, snap2.name)
    
        # Step 11:
        # Pick up a random replica and fail it.
        # Then trigger rebuild and the incremental restoration
        dr_volume = client.by_id_volume(dr_volume_name)
        for r in dr_volume.replicas:
            failed_replica = r.name
            break
        assert failed_replica
        dr_volume.replicaRemove(name=failed_replica)
        client.list_backupVolume()
    
        # Wait for the rebuild start
        wait_for_volume_degraded(client, dr_volume_name)
        running_replica_count = 0
        for i in range(RETRY_COUNTS):
            running_replica_count = 0
            dr_volume = client.by_id_volume(dr_volume_name)
            for r in dr_volume.replicas:
                if r['running'] and not r['failedAt']:
                    running_replica_count += 1
            if running_replica_count == 3:
                break
            time.sleep(RETRY_INTERVAL)
        assert running_replica_count == 3
    
        # Wait for inc restoration & rebuild complete
        wait_for_dr_volume_expansion(client, dr_volume_name, str(expand_size1))
        wait_for_volume_healthy_no_frontend(client, dr_volume_name)
        check_volume_last_backup(client, dr_volume_name, b2.name)
    
        # Verify the snapshot info
        dr_volume = client.by_id_volume(dr_volume_name)
        assert dr_volume.size == str(expand_size1)
        snapshots = dr_volume.snapshotList(volume=dr_volume_name)
        assert len(snapshots) == 2
        for snap in snapshots:
            if snap["name"] != "volume-head":
                assert snap["name"] == "expand-" + str(expand_size1)
                assert not snap["usercreated"]
                assert "volume-head" in snap["children"]
    
        # Step 14: Do online expansion for the std volume.
        expand_size2 = 3 * Gi
        expand_and_wait_for_pvc(core_api, pvc, expand_size2)
        wait_for_volume_expansion(client, std_volume_name)
    
        # Step 15:
        # When the total writen data size is more than 2Gi, there must be data in
        # the 2nd expanded part.
        data_path3 = "/data/test3"
        write_pod_volume_random_data(core_api, std_pod_name,
                                     data_path3, DATA_SIZE_IN_MB_4)
        std_md5sum3 = get_pod_data_md5sum(core_api, std_pod_name, data_path3)
        # Then create the 3rd backup for the std volume
        snap3 = create_snapshot(client, std_volume_name)
        std_volume = client.by_id_volume(std_volume_name)
        std_volume.snapshotBackup(name=snap3.name)
        wait_for_backup_completion(client, std_volume_name, snap3.name)
        bv, b3 = find_backup(client, std_volume_name, snap3.name)
    
        # Step 16:
        # Trigger the restoration for the DR volume.
        client.list_backupVolume()
        check_volume_last_backup(client, dr_volume_name, b3.name)
        wait_for_dr_volume_expansion(client, dr_volume_name, str(expand_size2))
        # Then re-verify the snapshot info
        dr_volume = client.by_id_volume(dr_volume_name)
        assert dr_volume.size == str(expand_size2)
        snapshots = dr_volume.snapshotList(volume=dr_volume_name)
        assert len(snapshots) == 2
        for snap in snapshots:
            if snap["name"] != "volume-head":
                assert snap["name"] == "expand-" + str(expand_size2)
                assert not snap["usercreated"]
                assert "volume-head" in snap["children"]
    
        activate_standby_volume(client, dr_volume_name)
        wait_for_volume_detached(client, dr_volume_name)
    
        dr_pod_name = dr_volume_name + "-pod"
        dr_pv_name = dr_volume_name + "-pv"
        dr_pvc_name = dr_volume_name + "-pvc"
        dr_pod = pod_make(name=dr_pod_name)
        create_pv_for_volume(client, core_api, dr_volume, dr_pv_name)
        create_pvc_for_volume(client, core_api, dr_volume, dr_pvc_name)
        dr_pod['spec']['volumes'] = [create_pvc_spec(dr_pvc_name)]
>       create_and_wait_pod(core_api, dr_pod)

test_ha.py:1175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
common.py:542: in create_and_wait_pod
    wait_pod(pod_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pod_name = 'longhorn-testvol-z4fr1v-dr-pod'

    def wait_pod(pod_name):
        api = get_core_api_client()
    
        pod = None
        for i in range(DEFAULT_POD_TIMEOUT):
            pod = api.read_namespaced_pod(
                name=pod_name,
                namespace='default')
            if pod is not None and pod.status.phase != 'Pending':
                break
            time.sleep(DEFAULT_POD_INTERVAL)
>       assert pod is not None and pod.status.phase == 'Running'
E       AssertionError

common.py:520: AssertionError
```

```yaml
ryao@ryao-laptop:~> k describe pod longhorn-testvol-z4fr1v-dr-pod
Name:         longhorn-testvol-z4fr1v-dr-pod
Namespace:    default
Priority:     0
Node:         ip-172-31-6-104/172.31.6.104
Start Time:   Fri, 09 Jun 2023 08:13:03 +0800
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  sleep:
    Container ID:  
    Image:         busybox:1.34.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true; do date; sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from pod-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mwg2f (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  pod-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  longhorn-testvol-z4fr1v-dr-pvc
    ReadOnly:   false
  kube-api-access-mwg2f:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                            From                     Message
  ----     ------                  ----                           ----                     -------
  Warning  FailedScheduling        <invalid>                      default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Warning  FailedScheduling        <invalid>                      default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Normal   Scheduled               <invalid>                      default-scheduler        Successfully assigned default/longhorn-testvol-z4fr1v-dr-pod to ip-172-31-6-104
  Normal   SuccessfulAttachVolume  <invalid>                      attachdetach-controller  AttachVolume.Attach succeeded for volume "longhorn-testvol-z4fr1v-dr-pv"
  Warning  FailedMount             <invalid> (x5 over <invalid>)  kubelet                  MountVolume.MountDevice failed for volume "longhorn-testvol-z4fr1v-dr-pv" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/longhorn-testvol-z4fr1v-dr /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5956bcd83d8c52a5b4c47fc44f89dc57957a1d8ced23db83c19d63d7372c1dff/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5956bcd83d8c52a5b4c47fc44f89dc57957a1d8ced23db83c19d63d7372c1dff/globalmount: cannot mount; probably corrupted filesystem on /dev/longhorn/longhorn-testvol-z4fr1v-dr.

```

## Environment

 - Longhorn version: v1.5.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.25.9+k3s1
   - Number of management node in the cluster:1
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version: SLES 15-sp4
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):AWS
 - Number of Longhorn volumes in the cluster:
