### ISSUE TITLE
[BUG] Deploy to cluster with windows nodes always fails

### ISSUE THREAD

**Issue by davhdavh** [longhorn/longhorn#6091]
## Describe the bug (🐛 if you encounter this issue)

longhorn will attempt to deploy code on windows nodes even if everything is set to run on linux in helm config

## To Reproduce

1. make config with longhornManager.nodeSelector, longhornUI.nodeSelector, longhornUI.nodeSelector, longhornConversionWebhook.nodeSelector, longhornAdmissionWebhook.nodeSelector, longhornRecoveryBackend.nodeSelector, longhornDriver.nodeSelector all set to kubernetes\\.io/os=linux
2. helm install ...
3. watch deployment schedule stuff on windows nodes

it will always attempt to schedule pod/discover-proc-kubelet-cmdline and pod/engine-image-ei-xxxxxxx-xxxx on windows
e.g.

longhorn-system    pod/engine-image-ei-f9e7c473-5g4gx                        0/1     ImagePullBackOff   0              20m    10.168.197.216   windows <none>           <none>

## Expected behavior

longhorn ignores windows nodes

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm

**Comment by davhdavh** [comment]
also tried setting defaultSettings.taintToleration=kubernetes.io/os:linux:NoSchedule and defaultSettings.systemManagedComponentsNodeSelector=kubernetes.io/os:linux

**Comment by davhdavh** [comment]
it is possible to fix the engine-image by manually editing `kubectl -n longhorn-system edit DaemonSet/engine-image-ei-xxxx` and adding nodeSelector section, but no clue about discover-proc-kubelet-cmdline

**Comment by davhdavh** [comment]
if I drain all windows nodes, it will work... not a very useful solution though

**Comment by davhdavh** [comment]
and every couple of minutes it will then reset the manual changes, which tries to start the pod/engine-image-ei and pod/longhorn-csi-plugin, and kubernetes somehow doesnt like that so it crashes the pod/kube-scheduler, which then crashes the pod/kube-controller-manager

**Comment by PhanLe1010** [comment]
> Steps to reproduce the behavior:
> 1. make config with longhornManager.nodeSelector, longhornUI.nodeSelector, longhornUI.nodeSelector, longhornConversionWebhook.nodeSelector, longhornAdmissionWebhook.nodeSelector, longhornRecoveryBackend.nodeSelector, longhornDriver.nodeSelector all set to kubernetes\\.io/os=linux
> 2. helm install ...
> 3. watch deployment schedule stuff on windows nodes

> also tried setting defaultSettings.taintToleration=kubernetes.io/os:linux:NoSchedule and defaultSettings.systemManagedComponentsNodeSelector=kubernetes.io/os:linux

I think you for got to set the taintToleration for Longhorn UI, Longhorn manager, longhornConversionWebhook, longhornAdmissionWebhook,  longhornDriver

Brw, is your Windows cluster created by Rancher? If yes, we implemented a single setting that automatically apply all of these nodeSelector and taintToleration https://longhorn.io/docs/1.4.2/advanced-resources/deploy/rancher_windows_cluster/#deploy-longhorn-with-supported-helm-chart

**Comment by davhdavh** [comment]
not rancher, and I dont actually want longhorn on the windows machines, they are there for a legacy app that requires windows.
This is my complete config file for helm:
```yaml
defaultSettings:
  defaultReplicaCount: 1
  systemManagedComponentsNodeSelector: "kubernetes.io/os:linux"
  taintToleration:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"

longhornManager:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
longhornUI:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
longhornDriver:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
longhornConversionWebhook:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
longhornAdmissionWebhook:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
longhornRecoveryBackend:
  tolerations:
  - key: "kubernetes.io/os"
    value: "linux"
    effect: "NoSchedule"
    operator: "Equal"
  nodeSelector:
    kubernetes.io/os: linux
```

and it applies those just fine, but the discover-proc-kubelet-cmdline and engine-image are deployed from the manager.


ok, a few hours later while writing this message:

It seems the defaultSettings gets totally ignored. I can see that the configmap is created with the correct values, but when opening the settings page in the UI, it did not find them (blank values)
After I edit them, everything works just fine
