### ISSUE TITLE
[BUG] share-manager terminated during Longhorn upgrading causes rwx volume not working

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6120]
## Describe the bug (🐛 if you encounter this issue)

during Longhorn upgrading, existing `share-manager` will be terminated and never be created again, causes rwx volume not working after upgraded.

## To Reproduce

1. Install Longhorn v1.4.2
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml
```
2. Create rwx volume and workload, make sure it works
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset-rwx
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-statefulset-rwx
  serviceName: test-statefulset-rwx
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset-rwx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: busybox
          imagePullPolicy: IfNotPresent
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts:
            - name: pod-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: pod-data
      spec:
        accessModes: ['ReadWriteMany']
        storageClassName: 'longhorn'
        resources:
          requests:
            storage: 1Gi
```
4. Upgrade Longhorn to `v1.5.0-rc1` or `v1.5.0-rc2` or `master-head`
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.0-rc2/deploy/longhorn.yaml
```
5. During upgrading, `share-manager` is terminated and never being created again
6. The workload using the rwx volume not working, get stuck when trying to access the mount path

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.5.0-rc1, v1.5.0-rc2, master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
