### ISSUE TITLE
[BUG]  Longhorn show different counts of replicas for the same node

### ISSUE THREAD

**Issue by batulziiy** [longhorn/longhorn#6179]
## Describe the bug (🐛 if you encounter this issue)

I have a longhorn instance with 4 nodes and one of the nodes marked as unschedulable. The interesting thing is even though the node has 3 replicas, longhorn Web UI says it has 568 replicas. I don't have that much replicas. 

## Expected behavior

A node expected to be marked as schedulable with the correct number of replicas. 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.1
 - Installation method : helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S 1.26.3
   - Number of management node in the cluster: 4
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Oracle Linux 9.1
   - CPU per node: 2 
   - Memory per node: 256
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 39

## Additional context

![image](https://github.com/longhorn/longhorn/assets/76592232/7870bbfb-657f-4c75-a136-397f9347113b)

**Comment by batulziiy** [comment]
Also it shows only 3 replicas when I click on '568'

**Comment by batulziiy** [comment]
Thanks for your help. Checked replicas and surprisingly I have tons of stopped replicas which are not deleted. 
```kubectl get replicas -n longhorn-system | wc -l```
Update the mutatingwebhookconfigurations accordingly, let's see what will happen.

**Comment by derekbit** [comment]
BTW, you need to do as well

https://github.com/longhorn/longhorn/issues/5762#issue-1669167403

```
You can delete the stopped replicas whose label contains longhornnode: "null" by kubectl command.
These stopped replicas are not managed by longhorn system because of https://github.com/longhorn/longhorn/issues/5762. Due to the lack of the label, longhorn cannot recognize and delete them.
```

**Comment by batulziiy** [comment]
Update : 
Yesterday I deleted more than 7k replicas that matches against label longhornnode=null and state=stopped. However, now I have 565 replicas that are stopped but longhornnode label pointed to the "unschedulable" node. I'm not sure whether they're in use or not.  
Since, I have these 565 replicas exist, "unschedulable" state is still not being cleared. Do you think removing replicas associated to this "unschedulable" node is safe?

**Comment by derekbit** [comment]
@batulziiy 
>  However, now I have 565 replicas that are stopped but longhornnode label pointed to the "unschedulable" node. 

Can you send a support bundle to `longhorn-support-bundle@suse.com`? However, theoretically, these replicas are managed by the longhorn-system. You don't need to delete them by yourself.

**Comment by derekbit** [comment]
@batulziiy 
I checked the replicas.
A normal and managed replica's labels are
```
    labels:
      longhorn.io/backing-image: "null"
      longhorndiskuuid: 6d9e4be6-8eec-4c35-accf-89f0633b91b5
      longhornnode: ickn-ny04-004
      longhornvolume: pvc-16991eb9-6ab7-4073-914d-eed60718f453
```

There are some unmanaged and stopped replicas with labels
```
    labels:
      longhorn.io/backing-image: "null"
      longhorndiskuuid: 2e156510-8c3e-4800-af08-f4eda6340ebe
      longhornnode: ickn-ny04-002
```

You can manually delete them as well.
