### ISSUE TITLE
[BUG] Longhorn doesn't remove the system backups crd on uninstallation

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#6185]
## Describe the bug (🐛 if you encounter this issue)

After Longhorn is uninstalled from a kubernetes cluster, I could still see the `systembackups.longhorn.io` crd and the namespace `Longhorn` stuck in terminating state.

## To Reproduce

1. Install Longhorn 1.5.0-rc2
2. Have some system backups from previous version (Didn't check with the newly created system backups)
3. Uninstall Longhorn
4. Longhorn namespace is stuck in terminating state

## Expected behavior

The `systembackups.longhorn.io` crd should get deleted during uninstallation and the longhorn-system namespace should not stuck in terminating state.

## Log or Support bundle
longhorn-system namespace status:
```
status:
  conditions:
  - lastTransitionTime: "2023-06-23T23:17:20Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2023-06-23T23:17:20Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2023-06-23T23:17:52Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2023-06-23T23:17:20Z"
    message: 'Some resources are remaining: systembackups.longhorn.io has 8 resource
      instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2023-06-23T23:17:20Z"
    message: 'Some content in the namespace has finalizers remaining: longhorn.io
      in 8 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```
[systembackup.yaml.zip](https://github.com/longhorn/longhorn/files/11857825/systembackup.yaml.zip)

## Environment

 - Longhorn version: 1.5.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.26
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
