### ISSUE TITLE
[FEATURE] Share manager HA - Experimental

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6205]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Longhorn share manager is the backend to serve RWX volume by using NFS ganesha. Because it's a single instance, it would be SPOF, even though it has been improved with the recovery backend mechanism at https://github.com/longhorn/longhorn/issues/2293. 

The goal is to make the share manager highly available to improve availability instead of just relying on a shorter recovery time which would be uncertain, really depending on different environmental factors. 

## Additional context

Before 1.4.4 and 1.5.2, there are some Kernel issues that could cause the volume node to get stuck during the node reboot or upgrade if the share manager pod is disconnected because we use hard mode NFS mount. Thus, to resolve this problem, the soft mode will be introduced back with a longer timeout to prevent this situation in 1.4.4, 1.5.2, and 1.6. The detailed context can be checked at https://github.com/longhorn/longhorn/issues/6655#issuecomment-1726948794. However, this could be a potential risk of data loss if the timeout is not well defined. (timeout should at least consider the pod eviction timeout)

Eventually, the hard mode will be readopted together with this feature. Still, it doesn't mean the node stuck situation will not be encountered, but it's just a very rare case at least only if share manager HA nodes are all down or pods all unavailable to lose the HA. 

cc @longhorn/dev-data-plane

**Comment by james-munson** [comment]
Possibly of help: https://github.com/nfs-ganesha/nfs-ganesha/wiki/NFS-Ganesha-and-High-Availability

**Comment by derekbit** [comment]
@james-munson Could you update the status of the feature implementation? Thank you.

**Comment by james-munson** [comment]
There are several items needed before this is ready for release.
- Port the webhook selector changes into the branch and ensure we can turn off the webhook on the node we don't trust.
- Find the remaining paths in which the re-attachment to the new share-manager still tries to communicate with that node, and pre-empt them so they won't just time out.
- If possible, do so only for any share managers with expired leases rather than all on that node, in case there are some that are not expired.
It is unlikely to be done by 1.7.0 release.

**Comment by derekbit** [comment]
> There are several items needed before this is ready for release.
> 
> * Port the webhook selector changes into the branch and ensure we can turn off the webhook on the node we don't trust.
> * Find the remaining paths in which the re-attachment to the new share-manager still tries to communicate with that node, and pre-empt them so they won't just time out.
> * If possible, do so only for any share managers with expired leases rather than all on that node, in case there are some that are not expired.
>   It is unlikely to be done by 1.7.0 release.

cc @james-munson

**Comment by derekbit** [comment]
> There are several items needed before this is ready for release.
> 
> * Port the webhook selector changes into the branch and ensure we can turn off the webhook on the node we don't trust.
> * Find the remaining paths in which the re-attachment to the new share-manager still tries to communicate with that node, and pre-empt them so they won't just time out.
> * If possible, do so only for any share managers with expired leases rather than all on that node, in case there are some that are not expired.
>   It is unlikely to be done by 1.7.0 release.

cc @innobead

**Comment by james-munson** [comment]
Here's a summary of the current status for Share Manager HA.  These items have been accomplished:
- Reliably detect stale lease in share manager controller.
- Mark the node with a condition of "delinquent".
- Port the webhook selector code from #8803, and turn off the label for the delinquent node's service.
- Take ownership of the share manager and delete the old pod.
- Create a new pod with all the user-specified affinities and tolerations, but avoiding the dead node.
- When the pod is scheduled, shift ownership of the volume and engine to the new pod's node.
- Modify the attachment to use the new node.
That's the point at which the testing runs into difficulties.  We know that what we want is possible.  If the check for "node down or deleted" is modified to include delinquent nodes, the failover can occur quickly,  The instance manager's state will be set to unknown, and any resources assigned to that IM will be cleaned up in the normal way.
However, we all agree that is too intrusive a solution given the possible effect on non-RWX volumes.  So the trick is to intercept every controller sync path for resources that belong to RWX volumes that will try to contact the instance manager, or send a request to that node.  If we don't manage that, it won't break things, but the attempt will time out until the node goes to "not ready", and failover is not any faster.

**Comment by james-munson** [comment]
@PhanLe1010 was able to identify the places where a quick check of delinquency could be made for the affected volume's resources without marking the instance manager as down.  With other changes I am currently testing, we should be able to confine the scope not just to RWX volumes in general, but only to those that have failed to keep the lease refreshed, regardless of other RWX volumes on the same node.

**Comment by PhanLe1010** [comment]
TODO:

1. https://github.com/longhorn/longhorn-manager/pull/2811#discussion_r1687302852

**Comment by derekbit** [comment]
@james-munson 
Could you update the `Pre Ready-For-Testing Checklist`? Thank you.

**Comment by ejweber** [comment]
We will also need a https://github.com/longhorn/website PR. At the very least it will have the documentation for the new setting, but I think it probably could use updates to multiple of the following (not sure about all):

- https://longhorn.io/docs/1.7.0/high-availability/ (new page in section?)
- https://longhorn.io/docs/1.7.0/nodes-and-volumes/volumes/rwx-volumes/ (new section on page?)
- https://longhorn.io/docs/1.7.0/deploy/important-notes/

**Comment by derekbit** [comment]
> ## Pre Ready-For-Testing Checklist
> * [x]  Where is the reproduce steps/test steps documented?
>   The reproduce steps/test steps are at:  LEP, [feat(lep): fast failover for RWX volumes #9069](https://github.com/longhorn/longhorn/pull/9069)

@james-munson Can you add verification steps and expected behaviors for QA?

**Comment by james-munson** [comment]
> @james-munson Can you add verification steps and expected behaviors for QA?
Is there more that you would like to see added to the LEP test plan?  Is there a separate document needed?

**Comment by PhanLe1010** [comment]
Regarding to the 2nd TODO item in the list https://github.com/longhorn/longhorn/issues/6205#issuecomment-2244077912, the question was why when we  call syncShareManagerVolume() first then call syncShareManagerPod later result in much longer recovery time for share manager pod.

I tracked it down to this function call inside the sync share manager loop [mountShareManagerVolume](https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L651). The syncloop stuck in this function for 20s. 

I was discussing with @shuo-wu to see why we need to mount and unmount the volume inside share-manager controller like this:
* https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L651
* https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L664

Eventhough we already do that when share manager pod start ([link](https://github.com/longhorn/longhorn-share-manager/blob/7ee089be760272a0b5cd0230733f6e83077c8775/pkg/server/share_manager.go#L138-L141))?

cc @derekbit @c3y1huang @ejweber Any idea?

Shuo and I are thinking of remove the mount/unmount logic inside share manager controller and only have it inside share-manager pod start/termination logic

**Comment by derekbit** [comment]
> Regarding to the 2nd TODO item in the list [#6205 (comment)](https://github.com/longhorn/longhorn/issues/6205#issuecomment-2244077912), the question over there was:
> 
> > Why when we  call syncShareManagerVolume() first then call syncShareManagerPod later result in much longer recovery time for share manager pod?
> 
> I tracked it down to this function call inside the sync share manager loop [mountShareManagerVolume](https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L651). The syncloop stuck in this function for 20s.
> 
> I was discussing with @shuo-wu to see why we need to mount and unmount the volume inside share-manager controller like this:
> 
> * https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L651
> * https://github.com/longhorn/longhorn-manager/blob/18ac5dc6f64396a60b5a8511c864fb831cf5030c/controller/share_manager_controller.go#L664

It is related to the IO error found in https://github.com/longhorn/longhorn/issues/6829

**Comment by ejweber** [comment]
> Even though we already do that when share manager pod start ([link](https://github.com/longhorn/longhorn-share-manager/blob/7ee089be760272a0b5cd0230733f6e83077c8775/pkg/server/share_manager.go#L138-L141))?

Looks like @derekbit found the reason for the unmounting already . And the reason for the mounting appears to be a related timing issue described in https://github.com/longhorn/longhorn/issues/7106 and fixed with https://github.com/longhorn/longhorn-manager/pull/2294.

**Comment by PhanLe1010** [comment]
Ok. Thank you both @derekbit @ejweber 

I will keep the mounting and unmounting logic inside share manager untouch and adding more logic to handling the delinquent case

**Comment by roger-ryao** [comment]
**Verified on master-head 20240729**
- longhorn `master-head` https://github.com/longhorn/longhorn/commit/d5e8a44104f5e03c310870b47da7c8ab55f671b3
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/a05002c662885d0b8381b219593fdb2083c0232d
- longhorn-share-manager `master-head` https://github.com/longhorn/longhorn-share-manager/commit/b017c58ebda0c00c03608013a6046480c337f270

**Verified on v1.7.0-rc2 20240729**
- longhorn `v1.7.0-rc2` https://github.com/longhorn/longhorn/commit/03d5faee809d984a71a17c04da863d571df009bb
- longhorn-manager `v1.7.0-rc2` https://github.com/longhorn/longhorn-manager/commit/f3c05513fa617659ce61d8160b543a5de7559dc0
- longhorn-share-manager `v1.7.0-rc2` https://github.com/longhorn/longhorn-share-manager/commit/4aaf32b21fc2904ddbb8985106627870489c8559

**The test steps**
https://github.com/longhorn/longhorn/blob/e96e25ec14048bfbe7b04b66c30774d2f0b7694d/enhancements/20240325-nfs-server-ha.md


1. Case1
    1. Given The `rwx-volume-fast-failover` setting is enabled.
    ```bash
    > kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs rwx-volume-fast-failover
    > kubectl -n longhorn-system get settings rwx-volume-fast-failover
    NAME                       VALUE   APPLIED   AGE
    rwx-volume-fast-failover   false   true      105m
    ```

    2. And Create RWX volume workload.
    ```yaml
    apiVersion: v1
    kind: PersistentVol
    metadata:
      name: rwx-volume
      namespace: defaul
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Files
      storageClassName:
      resources:
        requests:
          storage: 10Gi
    ```

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app
      namespace: default
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: app
      template:
        metadata:
          labels:
            app: app
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwx-volume
          volumes:
          - name: rwx-volume
            persistentVolumeClaim:
              claimName: rwx-volume
    ```

    3. Then Turn off or restart the node where `share-manager` is running.
    4. Then New `share-manager` pod is created in under 20 seconds.
    5. And workload pod should work work normal be less than 60 seconds.

2. Case2
    1. Given The `rwx-volume-fast-failover` setting is enabled.
    ```bash
    > kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs rwx-volume-fast-failover
    > kubectl -n longhorn-system get settings rwx-volume-fast-failover
    NAME                       VALUE   APPLIED   AGE
    rwx-volume-fast-failover   false   true      105m
    ```

    2. And The `auto-delete-pod-when-volume-detached-unexpectedly` setting is set to false.
    ```bash
    > kubectl -n longhorn-system patch -p '{"value": "false"}' --type=merge lhs  auto-delete-pod-when-volume-detached-unexpectedly
    setting.longhorn.io/auto-delete-pod-when-volume-detached-unexpectedly patched (no change)
    > kubectl -n longhorn-system get setting auto-delete-pod-when-volume-detached-unexpectedly
    NAME                                                VALUE   APPLIED   AGE
    auto-delete-pod-when-volume-detached-unexpectedly   false   true      134m
    ```

    3. And RWX volume workload 1 is created.
    ```yaml
    apiVersion: v1
    kind: PersistentVol
    metadata:
      name: rwx-volume
      namespace: defaul
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Files
      storageClassName:
      resources:
        requests:
          storage: 10Gi
    ```

    ```yaml
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: app
      namespace: default
    spec:
      selector:
        matchLabels:
          app: app
      template:
        metadata:
          labels:
            app: app
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwx-volume
          volumes:
          - name: rwx-volume
            persistentVolumeClaim:
              claimName: rwx-volume
    ```

    4. Then Turn off or restart the node where `share-manager` is running.
    5. Then New `share-manager` pod is created in under 20 seconds.
    6. And workload pod should work work normal be less than 60 seconds.

 
3. Case3
    1. Given Create RWX volume workload.
    ```yaml
    apiVersion: v1
    kind: PersistentVol
    metadata:
      name: rwx-volume
      namespace: defaul
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Files
      storageClassName:
      resources:
        requests:
          storage: 10Gi
    ```

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app
      namespace: default
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: app
      template:
        metadata:
          labels:
            app: app
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwx-volume
          volumes:
          - name: rwx-volume
            persistentVolumeClaim:
              claimName: rwx-volume
    ```

    2. Then scale up replica to 100
    ```bash
    > kubectl scale deployment app --replicas=100
    ```

    3. And check and note the CPU usage of `longhorn-manager` pods.
    ```bash
    > kubectl top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/'
    NAME                                                CPU(cores)   MEMORY(bytes)   
    longhorn-manager-dfnh5                              6m           101Mi           
    longhorn-manager-q5x7l                              9m           67Mi            
    longhorn-manager-wblfk                              5m           65Mi            
    ```

    4. Then delete the `Deployment` workload.
    5. And The `rwx-volume-fast-failover` setting is enabled.
    ```bash
    > kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs rwx-volume-fast-failover
    > kubectl -n longhorn-system get settings rwx-volume-fast-failover
    NAME                       VALUE   APPLIED   AGE
    rwx-volume-fast-failover   false   true      105m
    ```

    6. And Create workload.
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app
      namespace: default
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: app
      template:
        metadata:
          labels:
            app: app
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwx-volume
          volumes:
          - name: rwx-volume
            persistentVolumeClaim:
              claimName: rwx-volume
    ```

    7. Then scale up replica to 100
    ```bash
    > kubectl scale deployment app --replicas=100
    ```

    8. And check and note the CPU usage of `longhorn-manager` pods.
    ```bash
    > kubectl top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/'
    NAME                                                CPU(cores)   MEMORY(bytes)   
    longhorn-manager-dfnh5                              6m           101Mi           
    longhorn-manager-q5x7l                              9m           67Mi            
    longhorn-manager-wblfk                              5m           65Mi            
    ```

    9. Then the CPU use is not significantly larger.
    10. And Check the pod's number on the node
    ```bash
    > kubectl get pods -o wide --selector=app=app --no-headers | awk '{print $7}' | sort | uniq -c | sort -nr
     34 ryao-170-w1-f46fc0cc-mv2ph
     33 ryao-170-w3-41f45a30-kcf75
     33 ryao-170-w2-948d6727-8lsg7
    ```
    11. Then Turn off or restart the node where `share-manager` is running.
    12. Then New `share-manager` pod is created in under 20 seconds.
    13. And workload pod should work work normal be less than 60 seconds.



**Result Passed**

Hi @james-munson : 
Could you help review my **test steps**? I think we should reference the https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.7.0/test-storage-network-support-for-rwx-volume.md and add the manual test plan in `v1.7.0`.

**Comment by james-munson** [comment]
@roger-ryao, good idea to move the detailed test plan into longhorn-tests manual/release-specific.  I'll do that.

For the scale test, what I had in mind was more about multiple deployments, each scaled to 3 pod replicas and 2 or 3 longhorn replicas, and each with its own share-manager.  Sorry if that was unclear.

For the test cases, I was hoping that at least the first two could also be run with NFS "hard" mounts (using the nfsOptions parameter of the storageclass.)  I don't really expect a difference in behavior, though.

Thanks!  This is looking good.

**Comment by roger-ryao** [comment]
> For the scale test, what I had in mind was more about multiple deployments, each scaled to 3 pod replicas and 2 or 3 longhorn replicas, and each with its own share-manager. Sorry if that was unclear.

Hi @james-munson @PhanLe1010 

For case 3, I used the following shell script for testing. It creates 70 RWX volumes and 70 deployments. With 3 worker nodes, the maximum number of pods is 330, so I created 70 RWX volumes instead of 100. Could you review this to see if it aligns with the testing method you want?

```bash
#!/bin/bash

for i in {1..70}; do
  cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-volume-pvc-$i
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-$i
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-$i
  template:
    metadata:
      labels:
        app: app-$i
    spec:
      containers:
      - name: app
        image: busybox
        command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
        volumeMounts:
        - mountPath: /data
          name: rwx-volume-pvc-$i
      volumes:
      - name: rwx-volume-pvc-$i
        persistentVolumeClaim:
          claimName: rwx-volume-pvc-$i
EOF
done
```


`master-head` with `rwx-volume-fast-failover` enabled:
```bash
kubectl top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/'
NAME                                                     CPU(cores)   MEMORY(bytes)   
longhorn-manager-dfnh5                                   36m          139Mi           
longhorn-manager-q5x7l                                   39m          146Mi           
longhorn-manager-wblfk                                   75m          116Mi
```

`master-head` with `rwx-volume-fast-failover` disabled:
```bash
disable
kubectl top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/'NAME                                                     CPU(cores)   MEMORY(bytes)   
longhorn-manager-dfnh5                                   39m          141Mi           
longhorn-manager-q5x7l                                   28m          150Mi           
longhorn-manager-wblfk                                   27m          112Mi
```

`v1.7.0-rc2` with `rwx-volume-fast-failover` enabled:
```bash
> kubectl --kubeconfig ryao-170.yaml top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/' 
NAME                                                     CPU(cores)   MEMORY(bytes)   
longhorn-manager-6949h                                   41m          183Mi           
longhorn-manager-dmtv8                                   22m          120Mi           
longhorn-manager-pgwn8                                   63m          124Mi
```

`v1.7.0-rc2` with `rwx-volume-fast-failover` disabled:
```bash
> kubectl --kubeconfig ryao-170.yaml top pods -n longhorn-system | awk 'NR==1 || /longhorn-manager/'NAME                                                     CPU(cores)   MEMORY(bytes)   
longhorn-manager-6949h                                   38m          181Mi           
longhorn-manager-dmtv8                                   33m          124Mi           
longhorn-manager-pgwn8                                   38m          127Mi 
```

**Comment by PhanLe1010** [comment]
@roger-ryao I will defer to @james-munson to drive the testing but I think beside of monitoring the CPU usage of Longhorn manager, we also need to monitor the number of ETCD/API server requests when enabling fast failover setting. 

Also, when you scale up to 70 RWX deployments, do you see that replicas are evenly distributed across the nodes?

**Comment by roger-ryao** [comment]
> Also, when you scale up to 70 RWX deployments, do you see that replicas are evenly distributed across the nodes?

Hi @PhanLe1010 :
    The cluster status as below.
    
**master-head**
**App Pods Distribution**
```bash
> kubectl get pods -o wide --no-headers | grep app- | awk '{print $7}' | sort | uniq -c 
     69 ryao-test0729-w1-843ab7d3-6h482
     69 ryao-test0729-w2-f09488bb-zpp2h
     69 ryao-test0729-w3-5f09b89c-57hp9
```

**Share Manager Pods Distribution**
```bash
> kubectl get pods -n longhorn-system -o wide | grep share-manager | awk '{print $7}' | sort | uniq -c
     12 ryao-test0729-w1-843ab7d3-6h482
     34 ryao-test0729-w2-f09488bb-zpp2h
     23 ryao-test0729-w3-5f09b89c-57hp9
```

**Replica Distribution**
```bash
> kubectl -n longhorn-system get replica -o wide --no-headers | awk '{print $4}' | sort | uniq -c
     70 ryao-test0729-w1-843ab7d3-6h482
     70 ryao-test0729-w2-f09488bb-zpp2h
     70 ryao-test0729-w3-5f09b89c-57hp9
```

**v1.7.0-rc2**
**App Pods Distribution**
```bash
> kubectl get pods -o wide --no-headers | grep app- | awk '{print $7}' | sort | uniq -c 
     70 ryao-162-w1-c48bcd1c-5mjzf
     70 ryao-162-w2-5dd50923-4wjcn
     70 ryao-162-w3-1811cb30-x7tcj
```

**Share Manager Pods Distribution**
```bash
> kubectl get pods -n longhorn-system -o wide | grep share-manager | awk '{print $7}' | sort | uniq -c
     21 ryao-162-w1-c48bcd1c-5mjzf
     33 ryao-162-w2-5dd50923-4wjcn
     16 ryao-162-w3-1811cb30-x7tcj
```

**Replica Distribution**
```bash
> kubectl -n longhorn-system get replica -o wide --no-headers | awk '{print $4}' | sort | uniq -c
     70 ryao-162-w1-c48bcd1c-5mjzf
     70 ryao-162-w2-5dd50923-4wjcn
     70 ryao-162-w3-1811cb30-x7tcj
```

**Comment by roger-ryao** [comment]
> It creates 70 RWX volumes and 70 deployments. With 3 worker nodes, the maximum number of pods is 330, so I created 70 RWX volumes instead of 100.

Hi @PhanLe1010 & @james-munson : 
      Due to the limitation. If we want to test shutting down a node in case 3, I think creating 40 deployments is a more appropriate number. This way, the number of pods will be close to 200 in this scenario.

**Comment by ejweber** [comment]
> Also, when you scale up to 70 RWX deployments, do you see that replicas are evenly distributed across the nodes?

Looks like the replica distribution is correct @PhanLe1010. I am not sure how @james-munson ended up with the unbalanced situation in his cluster...

**Comment by PhanLe1010** [comment]
> > It creates 70 RWX volumes and 70 deployments. With 3 worker nodes, the maximum number of pods is 330, so I created 70 RWX volumes instead of 100.
> 
> Hi @PhanLe1010 & @james-munson : Due to the limitation. If we want to test shutting down a node in case 3, I think creating 40 deployments is a more appropriate number. This way, the number of pods will be close to 200 in this scenario.

Hi @roger-ryao Surely! Let's test 40 deployments for test 3


Can you also do this test:

1. Disable the fast failover feature
1. Deploy 70 RWX deployments with 70 RWX PVCs
1. Monitor the API server and ETCD server number of requests similar to this report https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md#longhorn-control-plane-performance
1. Enable the fast failover feature. Do these numbers increase too much? I don't know how much is to much yet but we can get the data for reference here first.

**Comment by PhanLe1010** [comment]
> Looks like the replica distribution is correct @PhanLe1010. I am not sure how @james-munson ended up with the unbalanced situation in his cluster...

I see. Thank you. Perhaps we can let @james-munson confirm this point later when he comes back

**Comment by roger-ryao** [comment]
> 3. Monitor the API server and ETCD server number of requests similar to this report https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md#longhorn-control-plane-performance
> 4. Enable the fast failover feature. Do these numbers increase too much? I don't know how much is to much yet but we can get the data for reference here first.


Hi @PhanLe1010 @james-munson :

### **Environment:**
- **Setup**: 1 Control Node + 3 Worker Nodes (using HAL)
- **Longhorn Version**: [Longhorn master-head](https://github.com/longhorn/longhorn/commit/caf599e44fbc8cccbbc3bd4dbc2ad19247ef400c)
- **Workload**: 60 Deployments with 30 RWX volumes with `soft` mount

**12:45-12:58**: RWX Volume Fast Failover is **enabled**.
**13:02-13:15**: RWX Volume Fast Failover is **disabled**.
At 13:00, deleted 60 deployments and volumes, then tested again with RWX Fast Failover **disabled**.

### **Test Results:**

| **Metric**                           | **Fast Failover Enabled** | **Fast Failover Disabled** | **Difference (%)**         |
|--------------------------------------|---------------------------|----------------------------|----------------------------|
| **1. Number of API Requests**        | 59 req/s                  | 37.5 req/s                 | **+57.3%**                 |
| **2. RPC Rate**                      | 57 ops/s                  | 35 ops/s                   | **+62.9%**                 |
| **3. Memory Usage**                  | -                         | -                          | No clear trend             |
| **4. Longhorn Manager CPU/RAM**      | 441MB / 0.18 CPU          | 423MB / 0.18 CPU           | +4.3% RAM / No change (**No clear trend** )  |
| **5. Share Manager CPU/RAM**         | 2.27GB / 0.31 CPU         | 2.21GB / 0.27 CPU          | **+2.7% RAM** / **+14.8% CPU** |

The `memory usage`,  **Longhorn Manager** `CPU` & `RAM` did not show a clear trend, making it difficult to compare between the two configurations.

### **Screenshot:**

1. **API Requests**: 
![Screenshot_20240801_133013](https://github.com/user-attachments/assets/19f0d0ec-777c-4809-8c3e-57c7f287ab57)

2. **RPC Rate**: 
![Screenshot_20240801_142642](https://github.com/user-attachments/assets/a8804533-65c3-460b-9334-1492a37f4be5)
3. **Memory Usage**:
![Screenshot_20240801_142319](https://github.com/user-attachments/assets/305b8f9d-3b55-4085-adf4-cced4246658f)


4. **Longhorn Manager CPU/RAM**: 
![Screenshot_20240801_140110](https://github.com/user-attachments/assets/fc676f6c-0184-434e-898d-211410491a6d)
![Screenshot_20240801_135937](https://github.com/user-attachments/assets/1db5b7bb-112d-4c65-9a64-3aafb0b1951e)

5. **Share Manager CPU/RAM**: 
![Screenshot_20240801_140843](https://github.com/user-attachments/assets/511d88f1-e554-4ade-af6e-a08fe0f45b35)

**Comment by roger-ryao** [comment]
### **Summary (v1.7.x-head Results)**

#### **Environment:**
- **Setup:** 1 Control Node + 3 Worker Nodes
- **Longhorn Version:** v1.7.x-head
- **Workload:** 60 Deployments with 60 RWX volumes mounted with `soft`
- **15:47-16:17**: RWX Volume Fast Failover is **disabled**.
- **After 16:40**: RWX Volume Fast Failover is **enabled**.

#### **Test Results:**

| **Metric**                           | **Fast Failover Enabled** | **Fast Failover Disabled** | **Difference**             |
|--------------------------------------|---------------------------|----------------------------|----------------------------|
| **1. Number of API Requests**        | 59 req/s                  | 37.5 req/s                 | **+57.3%**                 |
| **2. RPC Rate**                      | 57 ops/s                  | 37 ops/s                   | **+54.1%**                 |
| **3. Memory Usage**                  | Higher Peaks/Minima       | Lower Peaks/Minima         | More usage with Fast Failover Enabled |
| **4. Longhorn Manager CPU/RAM**      | 417MB / 0.13 CPU          | 405MB / 0.1 CPU            | **+3% RAM** / **+30% CPU** |
| **5. Share Manager CPU/RAM**         | 2.25GB / 0.26 CPU         | 2.2GB / 0.235 CPU          | **+2.3% RAM** / **+10.6% CPU** |

#### **Screenshot:**

1. **API Requests:** 
![Screenshot_20240801_165727](https://github.com/user-attachments/assets/d967d0c0-b96f-4d98-9504-8b9123000f55)

2. **RPC Rate:** 
![Screenshot_20240801_165643](https://github.com/user-attachments/assets/4dc295b7-fe9d-479d-b143-2656f95f1928)

3. **Memory Usage:** .
![Screenshot_20240801_165833](https://github.com/user-attachments/assets/9a347789-a020-44d0-bf28-f67fdbf2a80b)


4. **Longhorn Manager CPU/RAM:** 
![Screenshot_20240801_173049](https://github.com/user-attachments/assets/0c7d92b5-55ef-4383-aa76-ef05332dd167)
![Screenshot_20240801_173106](https://github.com/user-attachments/assets/7f92b8a5-16d2-427d-ade0-ceadf2dda976)

5. **Share Manager CPU/RAM:** 
![Screenshot_20240801_172839](https://github.com/user-attachments/assets/01879cc5-a067-4c64-a190-6dcdf392b4c9)

![Screenshot_20240801_172912](https://github.com/user-attachments/assets/1333773f-1c01-41c7-9fa3-85a4d1183aee)

**Comment by PhanLe1010** [comment]
Thank you very much @roger-ryao for the awesome testing.

The result looks reasonable/expected to me. Can we make this a test case and set the expectation for the test using the reference data here?

**Comment by ejweber** [comment]
I agree with @PhanLe1010.

1. This behavior looks to be expected.
2. @roger-ryao's test results are incredibly comprehensive!

With the feature enabled, share managers update their leases every 3 seconds. This appears to directly correlate to the increase in PUTs.

`60 RWX volumes * 0.33 lease-update/s = 20 lease-update/s = 20 PUT/s`

We also have an additional WATCH per node, since we are now watching Lease objects. This doesn't really show up in the number of API requests or the RPC rate, since each WATCH is a single API request and no interaction with etcd is required for the watching nodes to receive updates. It can maybe still result in an slight increase in network traffic, but it seems quite likely that the NFS traffic of 60 RWX volumes themselves will dwarf this effect.

**Comment by roger-ryao** [comment]
# How to Set Up a Grafana Testing Environment on Rancher

## 1. Install Monitoring via Rancher Catalog App
- Navigate to the Rancher UI.
- Install the Monitoring app using the Rancher Catalog. This will deploy Prometheus, Grafana, and related components necessary for monitoring.

## 2. Create a ServiceMonitor for Longhorn
- Apply the `longhorn_servicemonitor.yaml` to monitor Longhorn metrics.
```bash
kubectl apply -f longhorn_servicemonitor.yaml
```

- Example longhorn_servicemonitor.yaml:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: default
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
```

## 3. Set Up Prometheus Alertmanager
- Apply the prometheus_alertmanager.yaml to set up the Alertmanager
```bash
kubectl apply -f prometheus_alertmanager.yaml
```
- Example prometheus_alertmanager.yaml:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: longhorn
  namespace: default
spec:
  replicas: 3
```
## 4. Access Grafana Dashboards
- Access the Grafana dashboards through the Rancher UI.
- Log in with the default credentials: admin / prom-operator.
## 5. Import Longhorn Dashboard
- Import the Longhorn dashboard JSON for visualizing Longhorn metrics.
- The dashboard can be found at https://github.com/longhorn/longhorn/blob/master/scalability/dev/control_plane_grafana_dashboard.json
