### ISSUE TITLE
[BUG] Can not delete type=`bi` VolumeSnapshot if related backing image not exist

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6266]
## Describe the bug (🐛 if you encounter this issue)

Delete type=`bi` VolumeSnapshot will stuck if backing image not exist

## To Reproduce

1. Deploy the CSI snapshot CRDs and related Controller [v6.2.1](https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/)
2. Deploy Longhorn
3. Create VolumeSnapshotClass `longhorn-snapshot-vsc`
   <details>
     <summary>manifest</summary>
  
   ```yaml
        kind: VolumeSnapshotClass
        apiVersion: snapshot.storage.k8s.io/v1
        metadata:
            name: longhorn-snapshot-vsc
        driver: driver.longhorn.io
        deletionPolicy: Delete
        parameters:
            type: bi  
   ```
  </details>

4. Create VolumeSnapshotContent `test-on-demand-backing`

   <details>
     <summary>manifest</summary>
  
     ```yaml
        apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshotContent
        metadata:
            name: test-on-demand-backing
        spec:
            volumeSnapshotClassName: longhorn-snapshot-vsc
            driver: driver.longhorn.io
            deletionPolicy: Delete
            source:
                snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecksum=bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b  # NOQA
            volumeSnapshotRef:
                name: test-snapshot-on-demand-backing
                namespace: default
     ```
   </details>
5. Create VolumeSnapshot `test-snapshot-on-demand-backing`
   <details>
     <summary>manifest</summary>
  
     ```yaml
        apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshot
        metadata:
            name: test-snapshot-on-demand-backing
        spec:
            volumeSnapshotClassName: longhorn-snapshot-vsc
            source:
                volumeSnapshotContentName: test-on-demand-backing
     ```
   </details>
6. Delete VolumeSnapshot `test-snapshot-on-demand-backing`, the deletion stuck. (If Longhorn had a backing image named `test-bi` before execute step 6, the delete will success.)

## Expected behavior

Delete should success no matter backing image exist

## Log or Support bundle

longhorn-manager
```
time="2023-07-10T02:03:00Z" level=warning msg="HTTP handling error" error="failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
time="2023-07-10T02:03:00Z" level=error msg="Error in request: failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
10.42.0.31 - - [10/Jul/2023:02:03:00 +0000] "GET /v1/backingimages/test-bi HTTP/1.1" 500 248 "" "Go-http-client/1.1"
time="2023-07-10T02:05:08Z" level=warning msg="HTTP handling error" error="failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
time="2023-07-10T02:05:08Z" level=error msg="Error in request: failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
```

csi-snapshotter
```
E0710 01:55:06.791510       1 snapshot_controller_base.go:283] could not sync content "test-on-demand-backing": failed to delete snapshot "test-on-demand-backing", err: failed to delete snapshot content test-on-demand-backing: "rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found, code=Server Error] from [http://longhorn-backend:9500/v1/backingimages/test-bi]"
```
[supportbundle_f16395ed-43c1-480c-bbb3-eec929c91479_2023-07-10T02-07-09Z.zip](https://github.com/longhorn/longhorn/files/11997084/supportbundle_f16395ed-43c1-480c-bbb3-eec929c91479_2023-07-10T02-07-09Z.zip)

## Environment

 - Longhorn version: master, v1.5.x, v1.4.x
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.3+k3s1
 - Node config
   - OS type and version: Ubuntu 22.04 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

https://github.com/longhorn/longhorn/issues/6231

**Comment by innobead** [comment]
@chriscchien is this a regression? if yes, remember to add the regression label.

@ChanYiLin See if we can fix this in 1.4.3 or need more time on that.

**Comment by innobead** [comment]
@chriscchien is this found from the daily regression? do we have a test case for it?

**Comment by chriscchien** [comment]
> @chriscchien is this found from the daily regression? do we have a test case for it?

We have test case skeleton [here](https://github.com/longhorn/longhorn-tests/blob/1045840d030b34b372a8291ec7f725f6595025cb/manager/integration/tests/test_csi_snapshotter.py#L1370), the test script is under implementing.  This issue observed during test case implementing.

**Comment by innobead** [comment]
Removed from 1.5.1 and 1.4.3 which will be released in near future, so this can be tackled in the following release instead.

**Comment by chriscchien** [comment]
Hi @ChanYiLin,  

After execute step 5 in [reproduce steps](https://github.com/longhorn/longhorn/issues/6266#issue-1795810860), I create a PVC using VolumeSnapshot `test-snapshot-on-demand-backing`

<details>
  <summary>PVC manifest</summary>
  
  ```yaml
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
            name: test-restore-on-demand-backing
        spec:
            storageClassName: longhorn
            dataSource:
                name: test-snapshot-on-demand-backing
                kind: VolumeSnapshot
                apiGroup: snapshot.storage.k8s.io
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 5Gi
  ```
</details>

I can see PVC `test-restore-on-demand-backing` and backing image `test-bi` create success.

Then I try delete volumeSnapshot `test-snapshot-on-demand-backing`, the deletion stuck and can see below log in longhorn-manager. Looks like delete a type='bi 'Volumesnapshot will also need to delete related backing image. In this case, backing image was used by replica make the deletion stuck. And I am wondering if you can help confirm if this is correct behavior, thank you.
```
10.42.1.90 - - [10/Jul/2023:07:13:44 +0000] "GET /v1/backingimages/test-bi HTTP/1.1" 200 954 "" "Go-http-client/1.1"
time="2023-07-10T07:13:44Z" level=warning msg="Rejected operation: Request (user: system:serviceaccount:longhorn-system:longhorn-service-account, longhorn.io/v1beta2, Kind=BackingImage, namespace: longhorn-system, name: test-bi, operation: DELETE)" error="cannot delete backing image test-bi since there are replicas using it" service=admissionWebhook
time="2023-07-10T07:13:44Z" level=warning msg="HTTP handling error" error="failed to delete backing image: admission webhook \"validator.longhorn.io\" denied the request: cannot delete backing image test-bi since there are replicas using it"
time="2023-07-10T07:13:44Z" level=error msg="Error in request: failed to delete backing image: admission webhook \"validator.longhorn.io\" denied the request: cannot delete backing image test-bi since there are replicas using it"
```
