### ISSUE TITLE
[BUG][1.5.0] instance-manager doesn't seem to apply the tolerations

### ISSUE THREAD

**Issue by samip5** [longhorn/longhorn#6313]
## Describe the bug (🐛 if you encounter this issue)

Unable to set tolerations such that instance-manager would deploy

## To Reproduce

1. Taint a node with something that has NoExecute
2. Try to set the values to match so that it would get it
3. See that the pod is tried to schedule on the node
4. See that it fails with `Predicate TaintToleration failed`

## Expected behavior

I would have expected them to be enough.

## Log or Support bundle

not really applicable

## Environment

 - Longhorn version: 1.5.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.26.3+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.10 & Debian 12
   - CPU per node: Varies
   - Memory per node: 8-32GB
   - Disk type(e.g. SSD/NVMe): SATA SSD
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal and KVM
 - Number of Longhorn volumes in the cluster: 22

## Additional context

The values I tried: 
```
    persistence:
      defaultClassReplicaCount: 2
      defaultFsType: xfs
    defaultSettings:
      defaultReplicaCount: 2
      backupTarget: s3://longhorn@us-east-1/
      backupTargetCredentialSecret: minio-secret
      taintToleration:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
    longhornUI:
      nodeSelector:
       kubernetes.io/arch: amd64
    pspEnable: false
    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
````

**Comment by samip5** [comment]
I was too fast to make this, appears to work like it should.

**Comment by derekbit** [comment]
@samip5 
You can try replace
```
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
```
with
```
    - key: "node-role.kubernetes.io/worker1"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
```

Also, don't forget to add `node-role.kubernetes.io/worker1=true:NoExecute` to the setting `taint-toleration`

Ref: https://longhorn.io/docs/1.5.0/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-after-longhorn-has-been-installed
