### ISSUE TITLE
[BUG] Volume Live Upgrade from `v1.3.3` to `v1.3.x` Stuck Due to Identical Engine Images

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6378]
## Describe the bug (🐛 if you encounter this issue)

During a volume live engine upgrade from Longhorn engine `v1.3.3` to `v1.3.x-head`, the upgrade process gets stuck, and Longhorn manager displays the warning message

```bash
time="2023-07-24T06:03:22Z" level=warning msg="Engine image longhornio/longhorn-engine:v1.3.3 and longhornio/longhorn-engine:v1.3.x-head are identical, delay upgrade until detach for volume" accessMode=rwo controller=longhorn-volume engine=pvc-e66033b9-9f7d-4712-8eac-616cac4baaba-e-405520ed frontend=blockdev migratable=false node=ip-10-0-2-198 owner=ip-10-0-2-198 state=attached volume=pvc-e66033b9-9f7d-4712-8eac-616cac4baaba volumeDesiredEngineImage="longhornio/longhorn-engine:v1.3.x-head"
time="2023-07-24T06:03:52Z" level=warning msg="Engine image longhornio/longhorn-engine:v1.3.3 and longhornio/longhorn-engine:v1.3.x-head are identical, delay upgrade until detach for volume" accessMode=rwo controller=longhorn-volume engine=pvc-e66033b9-9f7d-4712-8eac-616cac4baaba-e-405520ed frontend=blockdev migratable=false node=ip-10-0-2-198 owner=ip-10-0-2-198 state=attached volume=pvc-e66033b9-9f7d-4712-8eac-616cac4baaba volumeDesiredEngineImage="longhornio/longhorn-engine:v1.3.x-head"
time="2023-07-24T06:03:24Z" level=warning msg="Engine image longhornio/longhorn-engine:v1.3.3 and longhornio/longhorn-engine:v1.3.x-head are identical, delay upgrade until detach for volume" accessMode=rwx controller=longhorn-volume engine=pvc-ff0dc8f7-e030-4629-9897-39d94bce887a-e-93fbfc7d frontend=blockdev migratable=false node=ip-10-0-2-59 owner=ip-10-0-2-59 shareEndpoint="nfs://10.43.235.133/pvc-ff0dc8f7-e030-4629-9897-39d94bce887a" shareState=running state=attached volume=pvc-ff0dc8f7-e030-4629-9897-39d94bce887a volumeDesiredEngineImage="longhornio/longhorn-engine:v1.3.x-head"
time="2023-07-24T06:03:54Z" level=warning msg="Engine image longhornio/longhorn-engine:v1.3.3 and longhornio/longhorn-engine:v1.3.x-head are identical, delay upgrade until detach for volume" accessMode=rwx controller=longhorn-volume engine=pvc-ff0dc8f7-e030-4629-9897-39d94bce887a-e-93fbfc7d frontend=blockdev migratable=false node=ip-10-0-2-59 owner=ip-10-0-2-59 shareEndpoint="nfs://10.43.235.133/pvc-ff0dc8f7-e030-4629-9897-39d94bce887a" shareState=running state=attached volume=pvc-ff0dc8f7-e030-4629-9897-39d94bce887a volumeDesiredEngineImage="longhornio/longhorn-engine:v1.3.x-head"

```
![Screenshot_20230724_143154](https://github.com/longhorn/longhorn/assets/104337648/4fba662c-d770-459c-a295-506b687d3804)

## To Reproduce

- Install Longhorn `v1.3.3` into a 3-nodes cluster
- Create Deployment

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwo
  labels:
    app: mysql-dep-rwo
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwo # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:8.0
        name: mysql-dep-rwo
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwo
        volumeMounts:
        - name: mysql-dep-rwo-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwo-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:8.0
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```

</details>

- Upgrade Longhorn to `v1.3.x-head`
- Upgrade the engine for the volume
- The volume is stuck in the upgrading process forever

## Expected behavior

I just want to confirm whether the expected behavior is for `v1.3.3` to be upgraded to `v1.3.x-head`.

## Support bundle for troubleshooting

[longhorn-support-bundle_410f5c7d-286d-455b-b6ba-5e59d0f6d145_2023-07-24T06-32-03Z.zip](https://github.com/longhorn/longhorn/files/12142509/longhorn-support-bundle_410f5c7d-286d-455b-b6ba-5e59d0f6d145_2023-07-24T06-32-03Z.zip)

## Environment
> Suggest checking the doc of the best practices of using Longhorn. [here](https://longhorn.io/docs/1.5.1/best-practices)

 - Longhorn version:`v1.3.3` upgrade to `v1.3.x-head`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.15+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLE-15sp4
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1 

## Additional context
NA
