### ISSUE TITLE
KubernetesController does not check driver of PersistentVolumes

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#639]
When checking for `PersistentVolumes` to update the `KubernetesStatus` of a `Volume` in `Longhorn`, the `KubernetesController` does not run a check on the `Spec.CSI.Driver` field to ensure that the `PersistentVolume` is using `Longhorn` (denoted by the value `io.rancher.longhorn`). 

As a result, if `Longhorn` detects a value in `Spec.CSI.VolumeHandle` that matches the name of an existing `Volume` in `Longhorn`, it will update the `KubernetesStatus` of that `Volume` accordingly, even if the `PersistentVolume` is actually using a different driver.

`KubernetesController` needs to be fixed to check the driver and ensure that it's actually specifying `io.rancher.longhorn` as the driver before working with the `PersistentVolume` and managing the `KubernetesStatus` of the `Longhorn Volumes`.

**Comment by yasker** [comment]
@ttpcodes Can you provide a reproduce step?

**Comment by ttpcodes** [comment]
This issue can be reproduced by creating a `Volume` in `Longhorn` and then creating a `PersistentVolume` in `Kubernetes` with a `VolumeHandle` referencing the `Longhorn Volume`. However, set the `Driver` for the `PersistentVolume` to something else that isn't `Longhorn`. Check `Longhorn UI`, and it should indicate the status of the `PersistentVolume`, even though that `PersistentVolume` isn't supposed to be managed by `Longhorn`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - In Longhorn UI, Create a volume with `20 GB` size and name `volume-test`
  - Create a pv using the following manifest, that will create a PV with the same volume handle as longhorn volume, but will use AWS Elastic Block Storage as a driver.

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "20Gi"
  csi:
    driver: "ebs.csi.aws.com"
    fsType: ext4
    volumeHandle: "volume-test"
```
Expected Result: In Longhorn UI, No PV status should be indicated since the volume is not managed by longhorn.
