### ISSUE TITLE
[BUG] Fix errors in questions.yaml

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#6392]
## What's the task? Please describe
I noticed a few small errors from the addition of storage class node selector in https://github.com/longhorn/longhorn/pull/4576

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the document request here.

**Comment by ejweber** [comment]
Small nit. I think this is not a [DOC] type issue since it actually fixes functionality that was broken.

**Comment by innobead** [comment]
@james-munson Let's make sure the issues we are handling need to add to the current milestone. Also, add backport labels if needed.

cc @longhorn/dev

**Comment by innobead** [comment]
@longhorn/qa for any issues with review-coverage label mean we need to see why the bug happens. Is it duo to some missing test case coverage? If yes, need to improve our test case.

**Comment by chriscchien** [comment]
Verified with test [steps](https://github.com/longhorn/longhorn/issues/6392#issuecomment-1652415733)

Can see `nodeSelector` set correctly in storageclass `longhorn` 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        fsType: "ext4"
        dataLocality: "disabled"
        nodeSelector: "ip-172-31-34-163"
```
Following test steps, it will test `rancher/chart` to install longhorn `v1.4.2`, but it can not guarantee `question.yaml` will work  properly on` v1.6.x` too because rancher does not support to install longhorn `v1.6.x` now.

I would like to keep this ticket open until `v1.6.x` rancher chart ready and test again to make sure that the `question.yaml` by install longhorn v1.6.x from Rancher
