### ISSUE TITLE
[BUG] MultiUnmapper floods logs with warnings about size mismatch.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#6406]
## Describe the bug (🐛 if you encounter this issue)
Example logs:
```
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:03.070856388Z [pvc-2735c59d-2afd-4d45-bc9b-8cceaf6dd525-e-e820ee0e] time="2023-07-23T23:00:03Z" level=warning msg="One of the MultiUnmapper get different size 4096 from others 8192"
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:03.071756880Z [pvc-2735c59d-2afd-4d45-bc9b-8cceaf6dd525-e-e820ee0e] time="2023-07-23T23:00:03Z" level=warning msg="One of the MultiUnmapper get different size 4096 from others 8192"
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:03.832448354Z time="2023-07-23T23:00:03Z" level=warning msg="One of the MultiUnmapper get different size 136286208 from others 136282112"
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:11.207079742Z time="2023-07-23T23:00:11Z" level=warning msg="One of the MultiUnmapper get different size 62914560 from others 62918656"
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:30.475903409Z [pvc-0bfcf0f2-7dc5-420a-bd35-83c28a5e7a36-e-e78f4fb8] time="2023-07-23T23:00:30Z" level=warning msg="One of the MultiUnmapper get different size 113254400 from others 113246208"
longhorn-system/instance-manager-e-7c2f73d3fcfb436f0ea4d8b06fc8d883/engine-manager.log:2023-07-23T23:00:39.292607748Z [pvc-0bfcf0f2-7dc5-420a-bd35-83c28a5e7a36-e-e78f4fb8] time="2023-07-23T23:00:39Z" level=warning msg="One of the MultiUnmapper get different size 0 from others 113246208"
```
There are thousands of them - more than 75% of the level=warning logging:
$ grep -r MultiUnmapper | wc
   2026   30380  598407

## To Reproduce

Provide the steps to reproduce the behavior:  Unknown

## Expected behavior

If this is serious, we need to look into why it is happening.  If it is routine, it could be at level=info rather than warning.

## Environment
> Suggest checking the doc of the best practices of using Longhorn. [here](https://longhorn.io/docs/1.5.1/best-practices)

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/6472

**Comment by james-munson** [comment]
In particular, note the comment about size delta always being 4096 bytes:  https://github.com/longhorn/longhorn/issues/6472#issuecomment-1677371225

**Comment by james-munson** [comment]
I think this is happening because the unmapping happens in parallel goroutines.  It seems reasonable to suppose that it catches files at different stages in allocation, and the difference is typically one block.
I will revise that logic to ignore that case, log if the difference is more than that, and return the largest value reported by all the unmapper members.

**Comment by james-munson** [comment]
Almost all implementations of UnmapAt return the input length argument.  The only one that doesn't is longhorn-engine's [replica/diffdisk](https://github.com/longhorn/longhorn-engine/blob/014125a20fd26e78be607365b6d090fe93d1f00f/pkg/replica/diff_disk.go#L282)
It ignores the return value of its own internal call to file.UnmapAt [here](https://github.com/longhorn/longhorn-engine/blob/014125a20fd26e78be607365b6d090fe93d1f00f/pkg/replica/diff_disk.go#L330) and instead accumulates an unmappedSize by taking before-and-after util.GetFileActualSize(filepath), which does a syscall of stat().

Do we have reason to suppose that the logic is mistaken, or is it more likely that the evolution of head and snapshot files is slightly different between replicas as the unmapping walks them all?

**Comment by james-munson** [comment]
It's worth noting (again) that the discrepancy is always VolumeSectorSize = 4096, not BlockSizeLinux = 512.

**Comment by james-munson** [comment]
First idea was to log nothing unless the different is greater than 1 4k sector.  That was not really the answer, since we still want to log *something* every so often, even at that level.

I was hoping that it might be a capability we could import, but there don't seem to be a lot of baked-in solutions to this.  You would think a log package might do that.  But `github.com/sirupsen/logrus` certainly does not, and it doesn't look like others do either.

It also doesn't look as common as I assumed when I filed this defect, fresh into Longhorn.  I'm not sure how some situations produce thousands of them.  Even with many UNMAP calls made from a single TRIM operation, there would still have to be a lot of TRIM activity, either from a filesystem mounted with `discard` option, or else frequently scheduled TRIM operations.

It looks like the best approach (unless and until the difference between replicas is tracked down and proved to be innocuous) is to follow @PhanLe1010's advice and put a meter inside the MultiUnmapperAt structure and just log a subsample of instances.

**Comment by shuo-wu** [comment]
## RCA
The root cause is the race between `unmap` and `write`. Let's take an example"

1. There is a filesystem inside a 2-replica volume, and it containsa  4k data file.
2. At the 1st moment, there is a file deletion coming, and ReplicaA successfully executes it while ReplicaB has not started.
3. At the 2nd moment, a filesystem trim/unmap is coming. Both replicas try to execute it. But because ReplicaB has not deleted the file data, this fstrim or unmap does not take any effect.
4. At the 3rd moment,  ReplicaB executes the file deletion. ==> The inconsistency between 2 replicas occurs.
```                         
                                        ReplicaA           ReplicaB
1. an filesystem with 4k data             data                data 
2. file delete, ReplicaA done            garbage              data 
3. file trim, both replicas done          empty               data
4. file delete, ReplicaB done             empty              garbage 
```

From the filesystem's perspective, the inconsistency in this example may not lead to data corruption. But the file deletion mentioned above can be replaced by a combination of data write and deletion, which will indeed make the filesystem file data messy. Besides, if users try to create a snapshot after the 3rd moment, the snapshot checksum will be different among 2 replicas, which is a kind of volume corruption in Longhorn's perspective.

## Reproducing step
1. Deploy Longhorn with `master-head` YAML and modified images `shuowu/longhorn-manager:unmap`, `shuowu/longhorn-instance-manager:unmap-reproduce`, `shuowu/longhorn-instance-manager:unmap-reproduce`
2. Launch a tiny 2-replica volume and attach it to a node that contains one replica:
```
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  labels:
    backup-target: default
    longhornvolume: vol
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/replica-auto-balance: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: vol
  namespace: longhorn-system
spec:
  accessMode: rwo
  backendStoreDriver: ""
  backingImage: ""
  backupCompressionMethod: lz4
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: ""
  freezeFilesystemForSnapshot: ignored
  fromBackup: ""
  frontend: blockdev
  image: shuowu/longhorn-engine:unmap-reproduce
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ""
  nodeSelector: []
  numberOfReplicas: 2
  replicaAutoBalance: ignored
  replicaDiskSoftAntiAffinity: ignored
  replicaSoftAntiAffinity: ignored
  replicaZoneSoftAntiAffinity: ignored
  restoreVolumeRecurringJob: ignored
  revisionCounterDisabled: false
  size: "16777216"
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 250
  snapshotMaxSize: "0"
  staleReplicaTimeout: 2880
  unmapMarkSnapChainRemoved: ignored
```
3. Access into the instance manager pod the volume engine resides on
4. Make a filesystem for the volume, pre-fill most of the empty space of the filesystem (so that the data write/delete and the unmap have a larger chance to operate the same location then trigger the race), then execute the below script:
```
mkfs.ext4 /dev/longhorn/vol
mkdir -p /mnt/vol
mount -o discard /dev/longhorn/vol /mnt/vol

dd if=/dev/urandom of=/mnt/vol/prefill bs=1M count=12

echo """
#!/bin/bash

while [ 1 ]; 
do 
  dd if=/dev/urandom of=/mnt/vol/testfile bs=1M count=1 conv=fsync status=none
  rm /mnt/vol/testfile
done
""" > fs-write.sh
chmod +x fs-write.sh
nohup ./fs-write.sh > log-fs-write &

echo """
#!/bin/bash

while [ 1 ]; 
do 
  fstrim /mnt/vol
done
""" > fs-trim.sh
chmod +x fs-trim.sh
nohup ./fs-trim.sh > log-fs-trim &
```
5. Monitor the instance manager pod log. There will be error log `One of the MultiUnmapper get different size xxxx from others xxxx` triggered.

## Solution
Since `unmap` is a rare operation compared with the regular IO, and it typically won't take a long time. The simplest solution is to use the engine Write Lock rather than [the Read Lock](https://github.com/longhorn/longhorn-engine/blob/d69d913c81169966d5bdc2bf38539659e663313b/pkg/controller/control.go#L1121) before executing it.
