### ISSUE TITLE
[TEST] Investigate Litmus Chaos for negative testing - Node Reboot

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#6499]
## What's the test to develop? Please describe

Investigate if it's possible to adopt [Litmus Chaos](https://litmuschaos.github.io/litmus/experiments/categories/contents/) to perform operations for negative testing.

## Describe the tasks for the test

- [x] reboot a node
  - https://litmuschaos.github.io/litmus/experiments/categories/nodes/node-restart/
- [X] power off a node, wait for a while, and then power it on
  - https://github.com/longhorn/longhorn/issues/6499#issuecomment-1674180185

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1300#discussion_r1289739749

**Comment by yangchiu** [comment]
This should have higher priority since it could potentially save us from reinventing the wheels.

**Comment by yangchiu** [comment]
I've confirm we can use [this litmus experiment](https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-terminate-by-id/) to control aws ec2 instance power on / power off.

1. install litmus following https://v1-docs.litmuschaos.io/docs/getstarted/#install-litmus:
```
kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.13.8.yaml
```
2. install the litmus experiment (`ec2-terminate-by-id`) we'd like to run and the corresponding service account from https://github.com/litmuschaos/chaos-charts/tree/v1.13.x/charts/kube-aws/ec2-terminate-by-id:
```
kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/v1.13.x/charts/kube-aws/ec2-terminate-by-id/experiment.yaml
kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/v1.13.x/charts/kube-aws/ec2-terminate-by-id/rbac.yaml
```
3. create secret to access aws resources following https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-terminate-by-id/#prerequisites
```
apiVersion: v1
kind: Secret
metadata:
  name: cloud-secret
type: Opaque
stringData:
  cloud_config.yml: |-
    # Add the cloud AWS credentials respectively
    [default]
    aws_access_key_id = XXXXXXXXXXXXXXXXXXX
    aws_secret_access_key = XXXXXXXXXXXXXXX
```
4. Create engine to actually run the experiment from https://raw.githubusercontent.com/litmuschaos/chaos-charts/v1.13.x/charts/kube-aws/ec2-terminate-by-id/engine.yaml. It would create a pod to do the job.
    `EC2_INSTANCE_ID` needs to be modified to the node to be power off.
    `CHAOS_INTERVAL` needs to be modified to how long we want the node being power off.
     And `nodeSelector` is necessary otherwise the created pod could be on the node to be power off.
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'   
  engineState: 'active'
  chaosServiceAccount: ec2-terminate-by-id-sa
  components:
    runner:
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-1-176
  experiments:
    - name: ec2-terminate-by-id
      spec:
        components:
          nodeSelector:
            kubernetes.io/hostname: ip-10-0-1-176
          env: 
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set interval duration (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '180'

             # Instance ID of the target ec2 instance
             # Multiple IDs can also be provided as comma separated values ex: id1,id2
            - name: EC2_INSTANCE_ID
              value: 'i-0bfdebb5bf5a4e2ac'
              
            # provide the region name of the instance
            - name: REGION
              value: 'us-east-1'

            # enable it if the target instance is a part of self-managed nodegroup.
            - name: MANAGED_NODEGROUP
              value: 'disable'              
```
5. view logs to see if it works as expected:
```
kubectl logs ec2-terminate-by-id-7wy56c-4qppd -f
kubectl describe chaosresult nginx-chaos
```


Then the next problem is: Is it possible to integrate the above workflow into our test code?
cc @longhorn/qa @innobead
