### ISSUE TITLE
[BUG]Backup to SMB share fails around 95% with "stale NFS file handle" error in Longhorn v1.5.1

### ISSUE THREAD

**Issue by give-me-data** [longhorn/longhorn#6510]
### Description

I'm using Longhorn v1.5.1 in my k3s HA cluster. I've configured Longhorn to backup volumes to an SMB share (FritzBox SMB and USB Drive). However, whenever I attempt to backup, the process fails around 95% - so data is written into the SMB Share. Surprisingly, the error I receive is related to an NFS file handle, even though I'm using SMB. The specific error message is: 

`open /var/lib/longhorn-backupstore-mounts/192_168_178_1/fritz.nas/Samsung_USB/backupstore/volumes/90/65/pv-paperless-db/volume.cfg: stale NFS file handle`

```yaml
k describe backup backup-d0d4e9d9c95f48af -n longhorn-system
Name:         backup-d0d4e9d9c95f48af
Namespace:    longhorn-system
Labels:       backup-volume=pv-paperless-db
Annotations:  <none>
API Version:  longhorn.io/v1beta2
Kind:         Backup
Metadata:
  Creation Timestamp:  2023-08-12T17:11:13Z
  Finalizers:
    longhorn.io
  Generation:  1
  Managed Fields:
    API Version:  longhorn.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:backup-volume:
      f:spec:
        .:
        f:labels:
          .:
          f:KubernetesStatus:
          f:test:
        f:snapshotName:
        f:syncRequestedAt:
    Manager:      longhorn-manager
    Operation:    Update
    Time:         2023-08-12T17:11:13Z
    API Version:  longhorn.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:backupCreatedAt:
        f:compressionMethod:
        f:error:
        f:labels:
        f:lastSyncedAt:
        f:messages:
        f:ownerID:
        f:progress:
        f:replicaAddress:
        f:size:
        f:snapshotCreatedAt:
        f:snapshotName:
        f:state:
        f:url:
        f:volumeBackingImageName:
        f:volumeCreated:
        f:volumeName:
        f:volumeSize:
    Manager:         longhorn-manager
    Operation:       Update
    Subresource:     status
    Time:            2023-08-12T17:11:50Z
  Resource Version:  47983186
  UID:               91b6dd0a-8abd-4cd3-b445-9ec12b6ecee7
Spec:
  Labels:
    Kubernetes Status:               {"pvName":"pv-paperless-db","pvStatus":"Bound","namespace":"paperless","pvcName":"pvc-paperless-db","lastPVCRefAt":"","workloadsStatus":[{"podName":"paperless-db-0","podStatus":"Running","workloadName":"paperless-db","workloadType":"StatefulSet"}],"lastPodRefAt":""}
    longhorn.io/volume-access-mode:  rwo
    Test:                            1
  Snapshot Name:                     400473d8-d1ad-4f99-8175-c53cd3978fb0
  Sync Requested At:                 <nil>
Status:
  Backup Created At:          
  Compression Method:         
  Error:                      open /var/lib/longhorn-backupstore-mounts/192_168_178_1/fritz.nas/Samsung_USB/backupstore/volumes/90/65/pv-paperless-db/volume.cfg: stale NFS file handle
  Labels:                     <nil>
  Last Synced At:             2023-08-12T17:11:50Z
  Messages:                   <nil>
  Owner ID:                   node02
  Progress:                   95
  Replica Address:            tcp://10.42.0.15:10000
  Size:                       
  Snapshot Created At:        2023-08-12T17:11:13Z
  Snapshot Name:              400473d8-d1ad-4f99-8175-c53cd3978fb0
  State:                      Error
  URL:                        
  Volume Backing Image Name:  
  Volume Created:             
  Volume Name:                
  Volume Size:                5368709120
```

Notably, data does get written to the SMB share before the backup process fails, indicating that there's some level of successful interaction with the share.

### Environment:

- Longhorn version: v1.5.1
- Kubernetes distribution and version: k3s v1.26.5+k3s1
- Node OS and version: Ubuntu 23.04
- Number of nodes:  4 (3 Master and 1 Worker) nodes with 3 Worker offline (drained and storage is disabled)

### Steps to Reproduce:
 
- Set up Longhorn v1.5.1 in the Kubernetes cluster.
- Configure Longhorn to use an SMB share (cifs://192.168.178.1/fritz.nas/Samsung_USB ; Fritzbox USB Share) as the backup target.
- Initiate a backup of a volume.
- Observe the backup process failing around 95%.

### Expected Behavior:
The backup should complete successfully and store the backup on the SMB share.

### Actual Behavior:
The backup process fails around 95% and throws the aforementioned "stale NFS file handle" error.

### Additional Context:

- There are no unwanted NFS mounts in the cluster. I've verified this using the `mount | grep nfs` command.
- The cluster has the necessary permissions to write to the SMB share. I've confirmed that data gets written to the share before the backup process fails.
- I've reviewed the logs, but there are no unusual entries that might hint at the root cause.
- I can successfully mount the SMB share manually from the nodes.
- Three of my nodes are intentionally offline, but they have been drained and storage on them is disabled.

Any assistance or insights into this issue would be greatly appreciated.
