### ISSUE TITLE
[BUG] Deleting the PV before the VolumeSnapshot backing image is created results in a corrupt image

### ISSUE THREAD

**Issue by dhedberg** [longhorn/longhorn#6541]
## Describe the bug (🐛 if you encounter this issue)

When creating a volume snapshot of `type: bi`, it's possible to remove the volume before the backing image is fully created. This results in an incomplete backing image being created without any obvious errors reported.

```yaml
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
# [..]
status:
  boundVolumeSnapshotContentName: snapcontent-b1fa93b9-6744-4cbc-aa25-275ae048c6ba
  creationTime: "2023-08-17T08:49:06Z"
  readyToUse: true
  restoreSize: 50Gi

---
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  creationTimestamp: "2023-08-17T08:49:06Z"
  name: snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b
# [..]
status:
  checksum: 4494ac3658b9b177aced356fd137db70605dfb44d86a2a26c4a7992d6abab6f4158005644399be4749e24c7762299841264b20187c4737881914532be0aa61d0
  diskFileStatusMap:
    8ee38cf0-0170-45c1-878e-7d91b6fc3fe0:
      lastStateTransitionTime: "2023-08-17T08:56:06Z"
      message: ""
      progress: 100
      state: ready
```

Expected size of this backing image is around 24G based on a similar image, but only 14G of data was transferred:
```
# ls -lh snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/
total 14G
-rw-r--r-- 1 root root 50G Aug 17 10:51 backing
-rw-r--r-- 1 root root 485 Aug 17 10:56 backing.cfg

# du -hs snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/
14G	snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/

# sha512sum snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/backing
4494ac3658b9b177aced356fd137db70605dfb44d86a2a26c4a7992d6abab6f4158005644399be4749e24c7762299841264b20187c4737881914532be0aa61d0  snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/backing

# fsck.ext4 -nf snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/backing
e2fsck 1.46.4 (18-Aug-2021)
Superblock has an invalid journal (inode 8).
Clear? no

Journal superblock is corrupt.
Fix? no

fsck.ext4: The journal superblock is corrupt while checking journal for snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/backing
e2fsck: Cannot proceed with file system check

snapshot-b1fa93b9-6744-4cbc-aa2-a0b27d6b-687d4a35/backing: ********** WARNING: Filesystem still has errors **********
```

(Incidentally I've set export-type to qcow2 in the VolumeSnapshotClass but I've never seen it produce a qcow2, is that expected?)

## To Reproduce

1. Create a "large enough" PV that creating the backing image takes some amount of time. In the current case tested, the PV had only one replica and dataLocality set to strict-local
3. Create a VolumeSnapshot of the PV with type: bi
4. Immediately delete the PV
5. After some delay, the deletion goes through while the backing image creation is still transferring data

This results in a seemingly successfully created VolumeSnapshot with a corrupt backing image.
