### ISSUE TITLE
[BUG] Create pvc from clone or volumesnapshot leads to  wrong fs type, bad option, bad superblock ( xfs only )

### ISSUE THREAD

**Issue by jsalatiel** [longhorn/longhorn#6555]
## Describe the bug (🐛 if you encounter this issue)
Can not create a valid pvc from a clone  or volumesnapshot.

## To Reproduce
Deploy the following volumesnapshot class
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
```
Now from any running pod using some pvc, try to clone directly from the pvc like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: wptst
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: data-wp-mariadb-0
```
or create a snapshot and clone from the snapshot:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: data-wp-mariadb-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: wptst
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

Now create a pod to use any of the pvcs above ( cloned from the pvc or snapshot  )
The pod will be stuck on ContainerCreating with this in the description:
```
Mounting arguments: -t xfs -o defaults /dev/longhorn/pvc-37d26f92-637a-487e-99e2-2a769654d412 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/1bc564a4f2b5d7790a745a506fd7cbd1f6621da64dad2943134989fd77c10b47/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/1bc564a4f2b5d7790a745a506fd7cbd1f6621da64dad2943134989fd77c10b47/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-37d26f92-637a-487e-99e2-2a769654d412, missing codepage or helper program, or other error.
```

I found out this problem by mistake when testing the new velero with datamover. The backup fails because the container using a cloned pvc will never start.

## Expected behavior
The cloned volume should work and not be corrupted like it appears to be.

## Support bundle for troubleshooting
https://file.io/wlOvOLo7g6F3

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubespray
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: almalinux 9.2
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM

**Comment by ChanYiLin** [comment]
It might because of the filesystem corruption when cloning or taking the snapshot from the original Volume

I can see the content is synced from this replica `pvc-48436166-5972-4fa3-858e-03f77e92f033-r-064a800f` of the origin volume

Can you help me to 
1. if the original volume has more than 2 replicas, delete the replica `pvc-48436166-5972-4fa3-858e-03f77e92f033-r-064a800f` to let it rebuild 
2. try the same process again, take the snapshot and create the pvc from it, see if this time works

In addition, to understand how did the filesystem corrupt, we might need to look into the replica's data
If possible, could you email as the content of the replicas folder?
`/var/lib/longhorn/replicas/<XXX>` (you can get the path by hovering the `/var/lib/longhorn/` words from the replicas of the volume on UI )
email address: longhorn-support-bundle@Suse.com

**Comment by jsalatiel** [comment]
I had to destroy that cluster. I will replicate the problem and give you the information you asked.

**Comment by maudrid** [comment]
I've been able to recreate this problem using longhorn 1.6.2.
All my volumes are xfs. When running velero, it creates snapshots and then tries to mount the snapshots.
Most of the volumes mount with no ptoblem, but the same 2 volumes have this issue whenever I try to run the backup.
```
MountVolume.MountDevice failed for volume "pvc-7e054eac-c2e9-42f5-b625-16c435cad56c" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t xfs -o defaults /dev/longhorn/pvc-7e054eac-c2e9-42f5-b625-16c435cad56c /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/758ba1f51bf3c2edddc25fd36d7cb956f7668a2ed774c38abe9088e22b230108/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/758ba1f51bf3c2edddc25fd36d7cb956f7668a2ed774c38abe9088e22b230108/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-7e054eac-c2e9-42f5-b625-16c435cad56c, missing codepage or helper program, or other error.
```
```
MountVolume.MountDevice failed for volume "pvc-ccb61f91-041d-4b5f-a7c8-6e07004fbfb8" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t xfs -o defaults /dev/longhorn/pvc-ccb61f91-041d-4b5f-a7c8-6e07004fbfb8 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5d5c93e55cb0295d7c32d3fcca0b62ca0e8864ba295c7c86940dbbe2023940f4/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5d5c93e55cb0295d7c32d3fcca0b62ca0e8864ba295c7c86940dbbe2023940f4/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-ccb61f91-041d-4b5f-a7c8-6e07004fbfb8, missing codepage or helper program, or other error.
```
I created a support bundle.

**Comment by derekbit** [comment]
@maudrid
Could you provide the steps to reproduce? Thanks.

**Comment by maudrid** [comment]
Here are the steps I followed on RKE1:
1. Installed a custom helm chart that created 3 PGO database clusters with 2 replicas each (including 3 pgbackrest volumes total), 1 mongo db cluster of 3 nodes,  1 minio cluster of 2 nodes (4 volumes each).
2. Install another minio instance for testing velero backups in the velero namespace
3. All of the above are using this storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-xfs
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  fromBackup: ''
  fsType: xfs
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate

```
5. Install velero:
```
./velero install --provider aws  --bucket velero --secret-file ./minio-credentials --backup-location-config="region=minio,s3ForcePathStyle='true',s3Url=http://minio:9000" --plugins=velero/velero-plugin-for-aws:v1.11.0 --use-node-agent --features=EnableCSI
```
6. Create the volume snapshot class:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
deletionPolicy: Delete
driver: driver.longhorn.io
parameters:
  type: snap
```
7. Create the velero backup
```
./velero backup create my-namespace-backup --snapshot-move-data --include-namespaces="my-namespace" --or-selector="postgres-operator.crunchydata.com/pgbackrest-repo=repo1 or v1.min.io/tenant=minio-ha or mongo-backup=true" --exclude-resources="pods,namespaces,services,endpoints,jobs.batch,cronjobs.batch,endpointslices.discovery.k8s.io,secrets,controllerRevisions,statefulSets,volumeSnapshotClass" 
```
As stated before, most of the volumes snapshot and the velero data mover can mount them and back them up to S3 successfully, except for 2.
