### ISSUE TITLE
[FEATURE] Longhorn snapshot space management

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6563]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, when creating a longhorn snapshot (in-cluster) of a volume will not respect any provision factors except the fixed upper limit of the number of volume snapshots, so it would cause unexpected disk space exhaustion which means it's unable to prevent this beforehand by having a better space plan. 

The goal is to introduce a mechanism to manage snapshot space usage when creating snapshots. 

## Describe the solution you'd like

When creating a snapshot, should respect the below factors. All factors should be considered together.
- A customized max number of snapshots allowed globally or volume-specific setting.
- A quota for snapshot usage global, node, or disk-specific. This will be another factor to impact replica scheduling.
- Introduce snapshot scheduling like replica scheduling to determine if the disk space is enough for creating a snapshot next to the replica. (cross disks allowed). This should be similar to creating a volume by respecting disk usage first.

## Additional context

cc @longhorn/dev

**Comment by FrankYang0529** [comment]
My proposal to this feature is that:

* [ ] 1. Add a setting `snapshot-max-count`. The default value is `250`. This complies with [the current fixed limit](https://github.com/longhorn/longhorn-engine/blob/8b4c80ab174b4f454a992ff998b6cb1041faf63d/pkg/replica/replica.go#L33).
* [ ] 2. Add `snapshotMaxCount` and `snapshotMaxSize` to Volume spec. The default `snapshotMaxCount` is from the `snapshot-max-count` setting. The default `snapshotMaxSize` is `0`, which means no limit on size.
* [ ] 3. Enforce the limit in [the engine controller](https://github.com/longhorn/longhorn-engine/blob/8b4c80ab174b4f454a992ff998b6cb1041faf63d/pkg/controller/control.go#L205-L207). If either count/size reaches the limit, the system doesn't allow to create a snapshot.

**Comment by innobead** [comment]
As discussed with @FrankYang0529 , we will focus on the first item below to introduce the fundamental limitation for snapshot creation. About the intelligent part for snapshot scheduling (item 2 and 3), they will be planned in the future depending on user feedback. 

> 1. A customized max number of snapshots allowed globally or volume-specific setting.
> 2. A quote for snapshot usage global, node, or disk specific. This will be another factor to impact replica scheduling.
> 3. Introduce snapshot scheduling like replica scheduling to determine if the disk space is enough for creating a snapshot next to the replica. (cross disks allowed). This should be similar to creating a volume by respecting disk usage first.

**Comment by innobead** [comment]
@derekbit @FrankYang0529 do we need to reduce the current default number snapshot 250? What's the common number in other solutions? 

It seems decreasing the number is also helpful to prevent potential disk exhaustion. WDYT?

**Comment by derekbit** [comment]
I'm fine with the number, but we can reduce the default value to a smaller number

Maximum snapshot numbers in some products
- [OpenEBS](https://openebs.io/docs/main/introduction/features): no limit for cstor and 512 for jiva
- [Rook/Ceph](https://rook.io/docs/rook/v1.11/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/): 400

**Comment by innobead** [comment]
@FrankYang0529 need to update chart manifests at https://github.com/longhorn/longhorn/pull/7479/files, also deploy/longhorn.yaml which is generated by https://github.com/longhorn/longhorn/blob/master/scripts/generate-longhorn-yaml.sh

**Comment by yangchiu** [comment]
@FrankYang0529 Are these settings available on Longhorn UI? I can't find related settings when creating a volume from Longhorn UI. 

If using API to create a volume, when I called the `create` action with `snapshotMaxCount` and `snapshotMaxSize` fields:
```
$ curl --header "Content-Type: application/json"   --request POST   --data '{"size": "1073741824", "name": "test-7", "snapshotMaxCount": 250, "snapshotMaxSize": 2357198848}'   http://34.199.50.114:30000/v1/volumes?action=create
```
It seems take no effects:
```
$ kubectl get volumes test-7 -n longhorn-system -oyaml | grep snapshot
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 250
  snapshotMaxSize: "0"
    snapshot: ""
```

Could you help to elaborate more on how to create a volume with specific `snapshotMaxCount` and `snapshotMaxSize`? Thank you!

**Comment by FrankYang0529** [comment]
Hi @yangchiu, thanks for testing the feature. Unfortunately, UI is not ready currently. @innobead, do we want to move to ready for testing after UI is ready?

My test steps is using YAML directly.

### volume-with-max-count

```yaml
# volume-with-max-count.yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: test-vol-with-max-count
  namespace: longhorn-system
spec:
  frontend: blockdev
  numberOfReplicas: 2
  size: "2147483648"
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 3
  snapshotMaxSize: "0"
```
1. `k apply -f volume-with-max-count.yaml`
2. Attach with maintenance mode.
3. Take 2 snapshots.
4. Revert to the first snapshot.
5. Take 1 snapshot.
6. Revert to the first snapshot.
7. Take 1 snapshot. (should be failed)
8. Delete 1 snapshot.
9. Take 1 snapshot again.

### volume-with-max-size

```yaml
# volume-with-max-size.yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: test-vol-with-max-size
  namespace: longhorn-system
spec:
  engineImage: frankyang/longhorn-engine:arm64-latest
  frontend: blockdev
  numberOfReplicas: 2
  size: "1073741824" # 1G
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 250
  snapshotMaxSize: "2357198848" # 2.2G
```

```yaml
# pod-with-max-size.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-volume-with-max-size
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: test-vol-with-max-size
```

1. `k apply -f volume-with-max-size.yaml`
2. Create PV/PVC.
3. `k apply -f pod-with-max-size.yaml`
4. Get into pod shell.
5. `cd /data`
6. `dd if=/dev/urandom of=file1 bs=100M count=10`
7. Take a snapshot.
8. `rm file1`
9. `dd if=/dev/urandom of=file2 bs=100M count=10`
10. Take a snapshot.
11. `rm file2`
12. `dd if=/dev/urandom of=file3 bs=100M count=10`
13. Take a snapshot. (should be failed)

**Comment by innobead** [comment]
UI can be later but please ensure we have an UI ticket for this feature.

cc @scures

**Comment by yangchiu** [comment]
Related to https://github.com/longhorn/longhorn/issues/7555#issuecomment-1878120572

**Comment by innobead** [comment]
@FrankYang0529 :point_up: Please provide the UI change need for @scures in https://github.com/longhorn/longhorn/issues/7522.

**Comment by yangchiu** [comment]
@FrankYang0529

Tested on master-head (longhorn-manager 7a56d71). If I use `updateSnapshotMaxCount` action to update snapshot max count, It seems take no effect:

1. Create volume with `snapshot max count = 3`:
```
cat << EOF > volume-with-max-count.yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: test-vol-with-max-count
  namespace: longhorn-system
spec:
  frontend: blockdev
  numberOfReplicas: 2
  size: "2147483648"
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 3
  snapshotMaxSize: "0"
EOF
kubectl apply -f volume-with-max-count.yaml
```
2. Create 3 snapshots from UI
3. Try to create 4th snapshot from UI, error message shown: 
```
failed to create snapshot: proxyServer=10.42.2.8:8501 destination=10.42.2.8:10010: 
failed to snapshot volume: rpc error: code = Unknown desc = failed to create snapshot for volume 10.42.2.8:10010: 
rpc error: code = Unknown desc = snapshot count usage 3 is equal or larger than snapshotMaxCount 3
```
4. Call API to update snapshot max count:
```
curl --header "Content-Type: application/json" \
>   --request POST \
>   --data '{"snapshotMaxCount": 4}' \
>   http://54.221.209.46:30000/v1/volumes/test-vol-with-max-count?action=updateSnapshotMaxCount
```
5. Look up volume `test-vol-with-max-count`, the `snapshotMaxCount` value has been updated to `4`:
```
$ kubectl get volumes -n longhorn-system test-vol-with-max-count -oyaml | grep snapshot
      {"apiVersion":"longhorn.io/v1beta2","kind":"Volume","metadata":{"annotations":{},"name":"test-vol-with-max-count","namespace":"longhorn-system"},"spec":{"frontend":"blockdev","numberOfReplicas":2,"size":"2147483648","snapshotDataIntegrity":"ignored","snapshotMaxCount":3,"snapshotMaxSize":"0"}}
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 4
  snapshotMaxSize: "0"
    snapshot: ""
```
6. Try to create 4th snapshot from UI again, error message still shown: 
![error-snapshot](https://github.com/longhorn/longhorn/assets/5709208/966e1b9c-deab-4be7-9da7-56154f098c57)

Could you help to confirm this? Thank you!
