### ISSUE TITLE
[QUESTION] Longhorn volume filesystem different from host drive - performance/integrity concerns?

### ISSUE THREAD

**Issue by ncecsc** [longhorn/longhorn#6636]
## Question

What are the possible performance and integrity impacts for my data if I have an SSD configured with xfs, and the dynamic volume longhorn generates for a workload is ext4? Will the mismatch reduce the I/O performance etc.?

Would it be better to have the volumes and the host drive filesystems match (either both xfs or ext4) - why?

## Environment

 - Longhorn version: 1.4.0
 - Kubernetes version: 1.26.3
 - Node config
   - OS type and version RHEL9
   - Kernel version 5.14.0-284.11.1.el9_2.x86_64
   - CPU per node: 32
   - Memory per node: 64GB
   - Disk type SSD
   - Network bandwidth and latency between the nodes: 10G Bonded
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context

As an aside - Is the default volume filesystem longhorn generates ext4? I've set default as xfs (see below), and I've also made a custom storage class which omits the fsType field, but seems to generate ext4 volumes. Is this intentional behaviour?

longhorn.yaml
```
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      fromBackup: ""
      fsType: "xfs"
      dataLocality: "disabled"
```
custom-storage-class.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ariel-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "2"
```
kubectl describe pv <pv>
```
Name:            pvc-6a0dae22-a944-4b63-af14-360a483b78aa
Labels:          <none>
Annotations:     longhorn.io/volume-scheduling-error: 
                 pv.kubernetes.io/provisioned-by: driver.longhorn.io
Finalizers:      [kubernetes.io/pv-protection external-attacher/driver-longhorn-io]
StorageClass:    sc-ariel-storage
Status:          Bound
Claim:           wazuh/wazuh-manager-master-0
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        10Gi
Node Affinity:   <none>
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            driver.longhorn.io
    FSType:            ext4
    VolumeHandle:      pvc-6a0dae22-a944-4b63-af14-360a483b78aa
    ReadOnly:          false
    VolumeAttributes:      numberOfReplicas=2
                           storage.kubernetes.io/csiProvisionerIdentity=1693834631721-8081-driver.longhorn.io
Events:                <none>
```

Thanks in advance!
