### ISSUE TITLE
[IMPROVEMENT] Support both NFS `hard` and `soft` with custom `timeo` and `retrans` options for RWX volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6655]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When a RWX volume is attached, a share-manager pod embedded with a userspace NFS server is created and the volume is exported. A remote exported share is `hard` mounted by Longhorn, and it is then provided to the workload. When the share-manager pod or embedded NFS server is somehow crashed or unreachable, the 'hard mount' option keeps the client trying to connect to NFS server and prevents data loss.

It has been reported that a reboot hangs when the NFS share is hard mounted and that the connection to the NFS server is lost during I/O operations.

- https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1577120
- https://bugzilla.redhat.com/show_bug.cgi?id=1312002
- https://access.redhat.com/solutions/3339001

The root cause is the Linux kernel is trying to maintain filesystem stability. Linux kernel will not allow a filesystem to be unmounted until all its pending IO is written back to storage, and the system can't shut down until all file systems are
unmounted. Currently, the bug/issue is not resolved.

A feasible workaround is using `soft` instead. It is possible to mitigate the potential data loss by using the sync mount option. However, the `sync` option makes the RWX volumes unusable in most practical applications due to poor IO performance.

As discussed with @innobead, at the trade-off the potential data loss and IO performance, the Longhorn system can use both the "hard" option and allow users to use the "soft" option with long custom [`timeo` and `retrans`](https://linux.die.net/man/5/nfs) values.

## Additional context

cc @james-munson

**Comment by james-munson** [comment]
This is for use as a mounted volume, but a similar ticket exists for backup target mount options:  #6608 

They are separate cases, and would not share a common configuration, but is the answer in either case to allow a list of mount options (or maybe even a customized mount command) and if specified, use that string instead of the default set of mount options?

**Comment by derekbit** [comment]
> They are separate cases, and would not share a common configuration, but is the answer in either case to allow a list of mount options (or maybe even a customized mount command) and if specified, use that string instead of the default set of mount options?

Yes, I think we can allow a list of mount options.

**Comment by derekbit** [comment]
### Options

There are two **mount options** in the storage class 
#### mountOptions

The options are recorded in the `pv.spec.mountOptions`. share-manager controller will fetch the options from the PV and append them the share-manager pod's container `args`. Longhorn block device will be mounted with the custom options and exported as a NFS share. ([code](https://github.com/longhorn/longhorn-manager/blob/v1.5.1/controller/share_manager_controller.go#L710-L734))

#### parameters.nfsOptions
For a RWX volume, CSI's `NodeStageVolume` will retrieve the `nfsOptions` in a storage class. ([code](https://github.com/longhorn/longhorn-manager/blob/v1.5.1/csi/node_server.go#L380-L386))

- If the value is empty, the NFS client uses the options
   ```
		mountOptions = []string{
			"vers=4.1",
			"noresvport",
			"intr",
			"hard",
		}
   ```
- If the value is given, NFS client will use the given options instead.

### v1.4 and v1.5

Users can create a storage class with `nfsOptions` if they want to switch to `soft` mode for avoiding the reboot hang issue
```
vers=4.1,noresvport,intr,soft,timeo=30,retrans=200
```
Here, the timeout is 30 milliseconds and retransmission is 200.

The multiplication of `timeo` and `retrans` should be long enough and larger than pod eviction time. Then, If the share-manager pod is not back or a replacement is created, the client can reconnect to it without data loss.


### v1.6+

The reboot hang issue in the Linux kernel is known but without a fix currently. To improve the stability, `soft` mode with long timeout will be used for mounting a NFS share.

**Comment by innobead** [comment]
@derekbit Can we make the default soft mode in upcoming 1.4.4 and 1.5.2 if no any compatibility concerns? It seems it happens at runtime, so we would expect the NFS mount (share manager) will be changed to soft after restarting the share manager pod, correct?

**Comment by derekbit** [comment]
> Can we make the default soft mode in upcoming 1.4.4 and 1.5.2 if no any compatibility concerns?

Sure. Not compatibility concern.
The setting will be applied after the share-manager pod is restarted.

**Comment by innobead** [comment]
After discussing with @derekbit , we will investigate the feasibility of introducing hard mode back when share manager HA is introduced in 1.7. https://github.com/longhorn/longhorn/issues/6205

**Comment by roger-ryao** [comment]
Hi @derekbit 
1. Create a directory to mount the NFS share: `mkdir -p /mnt/nfs_share`
2. Mount the NFS share from the server with this command: `mount -t nfs XX.XX.XX.XX:/var/nfs /mnt/nfs_share`
3. Start a data writing process in the background: `dd if=/dev/zero of=/mnt/nfs_share/a &`
4. Shutdown the NFS server.
5. Reboot the client machine.
6. After rebooting the client, check the syslog on the `Ubuntu 22.04` machine for any relevant information.
    we didn't see `umount.nfs: /mnt: device is busy` information in the syslog

**Comment by innobead** [comment]
> Hi @derekbit
> 
> 1. Create a directory to mount the NFS share: `mkdir -p /mnt/nfs_share`
> 2. Mount the NFS share from the server with this command: `mount -t nfs XX.XX.XX.XX:/var/nfs /mnt/nfs_share`
> 3. Start a data writing process in the background: `dd if=/dev/zero of=/mnt/nfs_share/a &`
> 4. Shutdown the NFS server.
> 5. Reboot the client machine.

Before rebooting the client machine, did you wait until the IO is stuck? I assume what you tested in the current implementation, hard mode, correct? 

@derekbit should we have the above criteria when testing? it seems this case is not always able to reproduce.

**Comment by derekbit** [comment]
> should we have the above criteria when testing? it seems this case is not always able to reproduce.

On-the-fly IO is required. Yes, it is not easy to reproduce...

**Comment by innobead** [comment]
@roger-ryao  probably can have a script to run n times to see whether it's able to reproduce if you are running this locally.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230926**

- longhorn master-head https://github.com/longhorn/longhorn/commit/c0a258afef108e8dc77e87751de4653a792b6ff4
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a0c13a2ee20b2b3ccb9a5aea0ab66f927508b4d0

**The test steps**

**Scenario 1: RWX Volume with Hard Mount**
1. Deploy an RWX volume with the following storage class settings (`nfsOptions: "hard,timeo=50,retrans=1"`)
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  nfsOptions: "hard,timeo=50,retrans=1"
```
2. Create a Pod that mounts this volume.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
#  annotations:
#    volume.beta.kubernetes.io/storage-class: longhorn-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc

```



3. Verify that the remote export mount by Longhorn is in **hard** mode
```bash
kubectl exec -it volume-test -- /bin/bash -c "mount | grep nfs"
```

```bash
10.43.78.52:/pvc-433cb644-d339-4158-a477-6e1b82a903c1 on /data type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=50,retrans=1,sec=sys,clientaddr=10.0.2.43,local_lock=none,addr=10.43.78.52)
```

**Scenario 2: RWX Volume with Soft Mount**
1. Deploy an RWX volume with the following storage class settings (`nfsOptions: "soft,timeo=250,retrans=5"`)
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  nfsOptions: "soft,timeo=250,retrans=5"
```

2. Create a Pod that mounts this volume

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
#  annotations:
#    volume.beta.kubernetes.io/storage-class: longhorn-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc

```


3. Verify that the remote export mount by Longhorn is in **soft** mode
```bash
kubectl exec -it volume-test -- /bin/bash -c "mount | grep nfs"
``` 

```bash
10.43.22.27:/pvc-93725304-9c5f-46e6-bb04-ab2ae6bfc6dd on /data type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=250,retrans=5,sec=sys,clientaddr=10.0.2.43,local_lock=none,addr=10.43.22.27)
```

**Result Passed**

The test passes if the respective NFS mount options (hard or soft) are correctly configured and observed when checking the mounted volumes.
