### ISSUE TITLE
[BUG] Failed upgrade from 1.4.1 to 1.5.1 via helm

### ISSUE THREAD

**Issue by hagaram** [longhorn/longhorn#6681]
Hi, I'm unable to upgrade to the newest longhorn version. Have you got any clue what might be wrong ? 

## Describe the bug (if you encounter this issue)

Upgrade fails
```
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
	* job failed: BackoffLimitExceeded

```

## To Reproduce

```
 helm upgrade longhorn longhorn/longhorn --namespace longhorn-system
```

## Expected behavior

Upgrades succeeds

## Additional context

```
+ longhorn-pre-upgrade-4djfm › longhorn-pre-upgrade
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade panic: unrecognized command: pre-upgrade
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade goroutine 1 [running]:
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade main.cmdNotFound(0x20adfdb, {0x7ffe1bf170c8, 0x0})
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x67
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade github.com/urfave/cli.ShowCommandHelp(0xc000544f20, {0x7ffe1bf170c8, 0xb})
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x188
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade github.com/urfave/cli.glob..func1(0xc000541040)
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x34
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade github.com/urfave/cli.HandleAction({0x1ccdc60, 0x21aefd0}, 0xb)
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:523 +0xa8
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade github.com/urfave/cli.(*App).Run(0xc0004a5340, {0xc00004c040, 0x2, 0x2})
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:285 +0x734
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade main.main()
longhorn-pre-upgrade-4djfm longhorn-pre-upgrade 	/go/src/github.com/longhorn/longhorn-manager/main.go:68 +0xa6a
- longhorn-pre-upgrade-4djfm › longhorn-pre-upgrade

```

**Comment by james-munson** [comment]
Odd.  "pre-upgrade" is a v1.5 command, and would be appropriate for an upgrade from 1.5.x to something, but it is apparently being given to a 1.4 longhorn-manager which doesn't support it.

**Comment by hagaram** [comment]
That doesnt seem to be a case.

This is the job generated by helm upgrade:

```
# Source: longhorn/templates/preupgrade-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
  name: longhorn-pre-upgrade
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    helm.sh/chart: longhorn-1.5.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.5.1
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      name: longhorn-pre-upgrade
      labels:
        app.kubernetes.io/name: longhorn
        helm.sh/chart: longhorn-1.5.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.5.1
    spec:
      containers:
      - name: longhorn-pre-upgrade
        image: longhornio/longhorn-manager:master-head
        imagePullPolicy: IfNotPresent
        command:
        - longhorn-manager
        - pre-upgrade
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: longhorn-service-account

```



And this is the help of executed command when I run debug pod with the same image as the generated job.
```
NAME:
   longhorn-manager - Longhorn Manager

USAGE:
   longhorn-manager [global options] command [command options] [arguments...]

VERSION:
   v1.5.0-dev

COMMANDS:
   daemon                       
   recurring-job                
   deploy-driver                
   csi                          
   conversion-webhook           
   admission-webhook            
   recovery-backend             
   post-upgrade                 
   uninstall                    
   system-rollout               
   migrate-for-pre-070-volumes  
   help, h                      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d     enable debug logging level [$RANCHER_DEBUG]
   --log-json, -j  log in json format [$RANCHER_LOG_JSON]
   --help, -h      show help
   --version, -v   print the version

``` 

It really seems to be missing
