### ISSUE TITLE
[IMPROVEMENT] Prevent unexpected engine creation

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6682]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In order to prevent an unexpected engine from being created, improve the validation webhook to disallow invalid creation in at least the below cases. 
- RWO volume (not migratable), only one engine resource allowed
- RWX volume (not migratable), only one engine resource allowed
- RWO volume + migratable, at most two engine resources allowed to create
- etc

Theoretically, each engine creation should be exclusively handled by one volume controller, but to prevent any potential concurrent creation issue, leveraging the global validation webhook can ensure the expected number of resources.  

## Additional context

cc @longhorn/dev

**Comment by ejweber** [comment]
I completed an implementation (https://github.com/longhorn/longhorn-manager/pull/2154) that works as expected in "normal" cases.. However, after discussing with @PhanLe1010 and @james-munson, I am concerned that this is really just "best-effort".

Theoretically, we are generating duplicate engines for one of two reasons:

1. Two separate volume controllers reconcile the same volume at the same time, and both decide to create an engine.
2. A single volume controller reconciles a volume twice in quick succession. Because it writes new engines directly to the API server, but reads them from the cache, it is possible for it to reconcile again before its cache is updated, not realize it has already created an engine, and create one again.

The webhook is susceptible to the same potential problems.

1. Two separate webhooks may respond to the two separate volume controllers at the same time. Both may allow engine creation, since they are operating in parallel.
2. A single webhook may respond to subsequent engine creations. If the webhook's cache hasn't updated, it may allow duplicate engine creation.

I haven't actually been able to cause either to happen in practice. In 100 attempts to quickly create duplicate engines for a volume, the new webhook implementation was successful every time. However, I think the possibility is there.

One potential way to entirely prevent the possibility of creating duplicate engines is to generate the engine name idempotently. If both separate volume controllers (in option 1) or both reconcile attempts (in option 2) used the same engine name, the Kubernetes API server is guaranteed to reject one of the creation attempts. The challenge to this approach is with migratable volumes. A migratable volume may legitimately have many engines in its lifetime (although always only a maximum of two at a time). Perhaps we can use the volume name and the `spec.migrationNodeID` field to generate an engine name that ensures only one additional engine is ever created during a migration?

**Comment by innobead** [comment]
> Theoretically, we are generating
> The webhook is susceptible to the same potential problems.
> 
> 
> 1. Two separate webhooks may respond to the two separate volume controllers at the same time. Both may allow engine creation, since they are operating in parallel.

This is interesting. Can u elaborate this a bit? Have u checked the related code? 

> 2. A single webhook may respond to subsequent engine creations. If the webhook's cache hasn't updated, it may allow duplicate engine creation.
> 
What's webhook cache here? Is it created by our own implementation or part of k8s?

cc @PhanLe1010 @james-munson

**Comment by PhanLe1010** [comment]
> What's webhook cache here? Is it created by our own implementation or part of k8s?

It is the cache in the client-go datastore informer which used by both our controller as well as the webhook

**Comment by innobead** [comment]
Then should we use non-cache API to get that? Using cache for validation seems potentially causing unexpected results for any case.

**Comment by PhanLe1010** [comment]
> Then should we use non-cache API to get that? Using cache for validation seems potentially causing unexpected results for any case.

Sound goods. Perhaps we can replace all get operations from getting from the cache to getting directly from ETCD. Maybe we want to double check the performance degraded because every update operation is going through webhook and the webhook is doing extra request to ECTD every time. 

> P.S. If parallel execution is for validation then it is reasonable but for mutation, it seems inappropriate design due to potential concurrency issue.

If we can do this, combined with the caching change above, I think we will solve the problem. However, if we do this then we would need to run the leader election for webhook and somehow make the webhook a single thread. I would imagine that the performance gets hit.

**Comment by innobead** [comment]
Phan, where do u see mutation webhook will be executed in parallel? I want to clarify this more. From my impression, it will be executed through a service endpoint, so eventually there is only one execution. Please correct me if any incorrect or missing.

**Comment by PhanLe1010** [comment]
I am thinking about the scenarios in which 2 engine creation requests (from one volume controller or 2 volume controllers) come to the webhook service endpoint. The 1st request hit webhook pod 1, the 2nd request hit webhook pod 2. Now both webhook pods lookup ETCD to see if any engine CR exist. They found none and both decide to create engine CR.

**Comment by innobead** [comment]
> I am thinking about the scenarios in which 2 engine creation requests (from one volume controller or 2 volume controllers) come to the webhook service endpoint. The 1st request hit webhook pod 1, the 2nd request hit webhook pod 2. Now both webhook pods lookup ETCD to see if any engine CR exist. They found none and both decide to create engine CRs. 
> 
This should be related to cache u mentioned.
> 
> Also, even if the 2 requests hit one webhook pod, it is possible that 2 go routines are handling them in parallel? 
> 
I assume go routines you mean here is how k8s executes the webhook? If yes, we need to understand the implementation.

**Comment by PhanLe1010** [comment]
> > I am thinking about the scenarios in which 2 engine creation requests (from one volume controller or 2 volume controllers) come to the webhook service endpoint. The 1st request hit webhook pod 1, the 2nd request hit webhook pod 2. Now both webhook pods lookup ETCD to see if any engine CR exist. They found none and both decide to create engine CRs. 
> > 
> This should be related to cache u mentioned.

I think it is a bit different than the caching issue. The caching issue is about 1st request create engine-1 CR, then the data is not updated in the cache yet when the second request try to create engine-2 CR. This might be fix by not using the cache. 

The problem I mentioned is about:
* webhook pod-1 receives a request to create engine-1 CR and webhook pod-2 receives a request to create engine-2 CR at the **same time**
* both webhook pod-1 and pod-2 lookup to see if there are any engine CR in ETCD. At this moment, ETCD answers to both webhook pods that there is no engine CR yet
* now both webhook pod-1 and pod-2 allow the creation of engine-1 and engine-2 requests.

**Comment by PhanLe1010** [comment]
> I assume go routines you mean here is how k8s executes the webhook? If yes, we need to understand the implementation.

Agree that we should investigate more

**Comment by innobead** [comment]
> I think it is a bit different than the caching issue. The caching issue is about 1st request create engine-1 CR, then the data is not updated in the cache yet when the second request try to create engine-2 CR. This might be fixed by not using the cache.
> 
> The problem I mentioned is about:
> 
> * webhook pod-1 receives a request to create engine-1 CR and webhook pod-2 receives a request to create engine-2 CR at the **same time**
> * both webhook pod-1 and pod-2 lookup to see if there are any engine CR in ETCD. At this moment, ETCD answers to both webhook pods that there is no engine CR yet
> * now both webhook pod-1 and pod-2 allow the creation of engine-1 and engine-2 requests.

I see, then this would be a concurrent issue. If the engine name is the same, should see if etcd would make it sequential creation or not.    Need to clarify this as well.

**Comment by PhanLe1010** [comment]
> I see, then this would be a concurrent issue. If the engine name is the same, should see if etcd would make it sequential creation or not. Need to clarify this as well.

I think if engine is the same, we should be fine. One of the 2 requests will be rejected by ETCD.

**Comment by PhanLe1010** [comment]
I updated the PR to get engines uncached from the API server. It should solve the caching issue and make it more resilient.

**Comment by PhanLe1010** [comment]
Test steps:
Use the test step here https://github.com/longhorn/longhorn-manager/pull/2154#issuecomment-1724316372 with the `duplicate-test.yaml` as:
```
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  finalizers:
    - longhorn.io
  labels:
    longhornvolume: testvol
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/replica-auto-balance: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: 'testvol'
  namespace: longhorn-system
spec:
  Standby: false
  accessMode: rwo
  backendStoreDriver: v1
  backingImage: ''
  backupCompressionMethod: lz4
  dataLocality: disabled
  dataSource: ''
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:master-head
  fromBackup: ''
  frontend: blockdev
  lastAttachedBy: ''
  migratable: false
  migrationNodeID: ''
  nodeID: ''
  nodeSelector: []
  numberOfReplicas: 3
  offlineReplicaRebuilding: disabled
  replicaAutoBalance: ignored
  replicaDiskSoftAntiAffinity: ignored
  replicaSoftAntiAffinity: ignored
  replicaZoneSoftAntiAffinity: ignored
  restoreVolumeRecurringJob: ignored
  revisionCounterDisabled: false
  size: '21474836480'
  snapshotDataIntegrity: ignored
  staleReplicaTimeout: 20
  unmapMarkSnapChainRemoved: ignored
---
apiVersion: longhorn.io/v1beta2
kind: Engine
metadata:
  finalizers:
    - longhorn.io
  labels:
    longhornnode: ''
    longhornvolume: testvol
  name: 'testvol-e-05a27075'
  namespace: longhorn-system
spec:
  active: true
  backendStoreDriver: v1
  backupVolume: ''
  desireState: stopped
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:master-head
  frontend: blockdev
  logRequested: false
  nodeID: ''
  replicaAddressMap: {}
  requestedBackupRestore: ''
  requestedDataSource: ''
  revisionCounterDisabled: false
  salvageRequested: false
  unmapMarkSnapChainRemovedEnabled: false
  upgradedReplicaAddressMap: {}
  volumeName: testvol
  volumeSize: '21474836480'
---
apiVersion: longhorn.io/v1beta2
kind: Engine
metadata:
  finalizers:
    - longhorn.io
  labels:
    longhornnode: ''
    longhornvolume: testvol
  name: 'testvol-e-05a27076'
  namespace: longhorn-system
spec:
  active: true
  backendStoreDriver: v1
  backupVolume: ''
  desireState: stopped
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:master-head
  frontend: blockdev
  logRequested: false
  nodeID: ''
  replicaAddressMap: {}
  requestedBackupRestore: ''
  requestedDataSource: ''
  revisionCounterDisabled: false
  salvageRequested: false
  unmapMarkSnapChainRemovedEnabled: false
  upgradedReplicaAddressMap: {}
  volumeName: testvol
  volumeSize: '21474836480'
```

**Comment by PhanLe1010** [comment]
I am not sure why we need the `require/doc` label. Any idea @innobead?

**Comment by innobead** [comment]
By default, any new implementation/enhancement issues will be added with this label via issue template. If it's not needed, let's just remove this.

In this case, we don't need it.

**Comment by PhanLe1010** [comment]
### Reproduce

1. Deploy Longhorn v1.5.1 chart with this customized Longhorn manager image `phanle1010/longhorn-manager:6682-duplicate-engines-v1-5-1-reproduce`. This longhorn-manager image injects some API errors into the code flow which makes the race condition more likely to happen. The code for the image is https://github.com/PhanLe1010/longhorn-manager/commit/ba452614cbfc9f030c880aa691114b1d9e19c3ea
2. Run this script that create and delete the volume 100 times:
    ```bash
    for i in {1..100}; do kubectl apply -f duplicate-test.yaml; if [[ $(kubectl get engine --no-headers -n longhorn-system | wc -l) > 1 ]]; then echo "Test FAILED: multiple engine detected"; break; fi; sleep 5; kubectl delete volume -n longhorn-system testvol; sleep 10; done
    ```
    with the `duplicate-test.yaml` is:
    ```yaml
    apiVersion: longhorn.io/v1beta2
    kind: Volume
    metadata:
      finalizers:
        - longhorn.io
      labels:
        longhornvolume: testvol
        recurring-job-group.longhorn.io/default: enabled
        setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
        setting.longhorn.io/replica-auto-balance: ignored
        setting.longhorn.io/snapshot-data-integrity: ignored
      name: 'testvol'
      namespace: longhorn-system
    spec:
      Standby: false
      accessMode: rwo
      backendStoreDriver: v1
      backingImage: ''
      backupCompressionMethod: lz4
      dataLocality: disabled
      dataSource: ''
      disableFrontend: false
      diskSelector: []
      encrypted: false
      engineImage: longhornio/longhorn-engine:master-head
      fromBackup: ''
      frontend: blockdev
      lastAttachedBy: ''
      migratable: false
      migrationNodeID: ''
      nodeID: ''
      nodeSelector: []
      numberOfReplicas: 3
      offlineReplicaRebuilding: disabled
      replicaAutoBalance: ignored
      replicaSoftAntiAffinity: ignored
      replicaZoneSoftAntiAffinity: ignored
      restoreVolumeRecurringJob: ignored
      revisionCounterDisabled: false
      size: '21474836480'
      snapshotDataIntegrity: ignored
      staleReplicaTimeout: 20
      unmapMarkSnapChainRemoved: ignored
    ```
3. Verify that there the script failed after about 3-10 loop run. Check that the volume has multiple active engines at this point.

### RCA

1. When the [volume controller sees no engine](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_controller.go#L1514), it creates the engine by calling [createEngine](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_controller.go#L3289-L3290)
2. The `createEngine()` method, create the engine CR by [calling kubenetes API ](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/datastore/longhorn.go#L1040-L1041)and wait for the engine to appear in the informer cache by calling [verifyCreation](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/datastore/longhorn.go#L1048-L1050) 
3. If for some reason, the kubernetes API creation call succeded but `verifyCreation` call failed because of some transient error, the code flow will return error to [this defer function](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_controller.go#L406-L444) . **Note that his transient error is the first error that I manually injected in code of the reproducing steps above, [link](https://github.com/PhanLe1010/longhorn-manager/commit/ba452614cbfc9f030c880aa691114b1d9e19c3ea#diff-5ce3d8738a74c1992779c63c7ebc931b7a76840818a36843834b6b10ba8540adR1049)**
4. Now, assume that the update volume status in the defer function failed with the transient API conflict error [here](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_controller.go#L435), the volume will immediately re-equeue [here](https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_controller.go#L441) . **Note that this is the 2nd transient error that I injected in the reproducing steps, [link](https://github.com/PhanLe1010/longhorn-manager/commit/ba452614cbfc9f030c880aa691114b1d9e19c3ea#diff-3238708d588203a9b8f1360b6d4b391c0c7a628fb1b2fac36efbbafe930f5e79R439)**
5. Now volume controller immediately reconciles the volume CR with engine CR exist in ETCD but not exist in engine informer cache yet (it takes time to sync ETCD to our controller informer cache)
6. In this sync loop, the volume controller will wrongly create a new engine with a random name.
7. The end result is that we have 2 active engines and the volume is stuck forever.

**Comment by PhanLe1010** [comment]
## Test steps:

### Case 1: Verify no duplicate engine CR even if we manually inject the API errors into the code flow

1. Deploy Longhorn v1.5.1 chart with this customized Longhorn manager image `phanle1010/longhorn-manager:6682-duplicate-engines-v1-5-1-reproduce-and-fix`. This longhorn-manager image injects some API errors into the code flow which makes the race condition more likely to happen. This image also contains the fix so that we don't create duplicated engine CRs even if there are API errors injected. The code for the image is https://github.com/PhanLe1010/longhorn-manager/commit/be58fc9c80ec8cc13029207f4239184852a015cc
2. Run this script that create and delete the volume 100 times:
    ```bash
    for i in {1..100}; do kubectl apply -f duplicate-test.yaml; sleep 1; if [[ $(kubectl get engine --no-headers -n longhorn-system | wc -l) > 1 ]]; then echo "Test FAILED: multiple engine detected"; break; fi; sleep 2; kubectl delete volume -n longhorn-system testvol; sleep 3; done
    ```
    with the `duplicate-test.yaml` is:
    ```yaml
    apiVersion: longhorn.io/v1beta2
    kind: Volume
    metadata:
      finalizers:
        - longhorn.io
      labels:
        longhornvolume: testvol
        recurring-job-group.longhorn.io/default: enabled
        setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
        setting.longhorn.io/replica-auto-balance: ignored
        setting.longhorn.io/snapshot-data-integrity: ignored
      name: 'testvol'
      namespace: longhorn-system
    spec:
      Standby: false
      accessMode: rwo
      backendStoreDriver: v1
      backingImage: ''
      backupCompressionMethod: lz4
      dataLocality: disabled
      dataSource: ''
      disableFrontend: false
      diskSelector: []
      encrypted: false
      engineImage: longhornio/longhorn-engine:master-head
      fromBackup: ''
      frontend: blockdev
      lastAttachedBy: ''
      migratable: false
      migrationNodeID: ''
      nodeID: ''
      nodeSelector: []
      numberOfReplicas: 3
      offlineReplicaRebuilding: disabled
      replicaAutoBalance: ignored
      replicaSoftAntiAffinity: ignored
      replicaZoneSoftAntiAffinity: ignored
      restoreVolumeRecurringJob: ignored
      revisionCounterDisabled: false
      size: '21474836480'
      snapshotDataIntegrity: ignored
      staleReplicaTimeout: 20
      unmapMarkSnapChainRemoved: ignored
    ```
3. Verify that the script do NOT fail after 100 loop run

### Case 2: test the script with Longhorn master

1. Uninstall the previous Longhorn installation. Install the Longhorn master version
1. Rerun the above script and verify that script pass on Longhorn master

### Case 3: Manually create duplicated engines
Uninstall the previous Longhorn installation. Install the Longhorn master version

Ref @ejweber 's test cases https://github.com/longhorn/longhorn-manager/pull/2154#issuecomment-1724316372

Create a duplicate engine for a non-migratable volume:

1. Create a volume in the UI.
3. Copy the yaml for the engine that is automatically created.
4. Edit the yaml to have a different name.
5. Attempt to apply the yaml.
6. `The request is invalid: spec.volumeName: engine creation would result in 2 engines for non-migratable volume`

Create two duplicate engines for a migratable volume:

1. Create a migratable storage class.
2. Create a PVC that references the storage class.
3. Copy the yaml for the engine that is automatically created TWICE.
4. Edit BOTH yamls to have different names.
5. Apply the first yaml.
7. Attempt to apply the second yaml.
8. `The request is invalid: spec.volumeName: engine creation would result in 3 engines for migratable volume`

### Case 4: Manual migration and  Upgrade test 

1. Deploy Longhorn older version v1.5.x
1. Create storageclass, PVC, and workload pod-1 as below
    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-migratable
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      migratable: "true"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Block
      storageClassName: longhorn-migratable
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-1
      namespace: default
    spec:
      nodeName: <NODE-1>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into pod-1. Write some data `dd if=/dev/urandom of=dev/longhorn/testblk bs=1M count=100`. Caculate checksum `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`
1. Upgrade Longhorn to master-head
1. Verify that the volume is NOT detached during this process.
1. Exec into pod-1 and verify checksum matches `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum` 
1. Deploy workload pod-2 to trigger live migration of volume to new node, NODE-2
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-2
      namespace: default
    spec:
      nodeName: <NODE-2>
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Observe that volume engine is available on node-2. Volume is NOT detach during this process
1. Delete pod-1.
1. Observe that volume detached from node-1 but still attaching to node-2 throughout the whole process.
1. Observer that there is only one engine with suffix `-1`
1. Exec into pod-2 and verify checksum matches `dd if=dev/longhorn/testblk bs=1M count=100 | md5sum`
1. Apply `pod-1` again. Wait for `pod-1` to be running
1. Delete `pod-2`, Observer that there is only one engine with suffix `-2`

### Case 5: e2e tests
Make sure that our daily e2e tests pass
