### ISSUE TITLE
[BUG] Cannot detach volume

### ISSUE THREAD

**Issue by h-e-l-o** [longhorn/longhorn#6688]
## Describe the bug (🐛 if you encounter this issue)

No pod is using the volume, but it cannot be detached because it immediately gets reattached automatically. 

From what I can see, the corresponding `VolumeAttachment` object has an attachment ticket that cannot be deleted (if deleted, it's immediately recreated):

```
spec:
  attachmentTickets:
    volume-rebuilding-controller-pvc-150c0bbc-25d6-4fe2-b76b-6bce680d6975:
      generation: 0
      id: volume-rebuilding-controller-pvc-150c0bbc-25d6-4fe2-b76b-6bce680d6975
      nodeID: rkemetal1
      parameters:
        disableFrontend: 'true'
      type: volume-rebuilding-controller
  volume: pvc-150c0bbc-25d6-4fe2-b76b-6bce680d6975
```

## To Reproduce

Don't know.

## Expected behavior

The volume should stay in the "detached" state.

## Support bundle for troubleshooting

Please remove the bundle once you've downloaded it.

## Environment

Longhorn 1.5.1.
