### ISSUE TITLE
[IMPROVEMENT] Reject strict-local + RWX volume creation

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6735]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When the server node is down, the `RWX` nfs server is unable to create on another node because of the `strict-local` volume.
Maybe we should reject `strict-local` + `RWX`.

Also `strict-local` is for distributed application only. Distributed application means it has replication capability, so they will only `RWO`.

## Additional context

https://suse.slack.com/archives/C02DR3N5T24/p1695171814534559

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by COLDTURNIP** [comment]
PR: longhorn/longhorn-manager#3334

**Comment by mantissahz** [comment]
>PR: https://github.com/longhorn/longhorn-manager/pull/3334

Hi @COLDTURNIP,

Move the status of `Longhorn Sprint` to `Review` to make the bot create `Pre Ready-For-Testing Checklist` and update the list.
Then you could move the status to `Ready for Testing`

**Comment by COLDTURNIP** [comment]
# Test Steps

- Step 1. a Longhorn-ready cluster
- Step 2. create a storage class (see attached example)
  - `provisioner: driver.longhorn.io`
  - `parameters.dataLocality: strict-local`
  - `parameters.migratable: false`
- Step 3. create a workload, with a PVC that claim a `ReadWriteMany` volume of given above class
- Step 4. verify the cluster
  - the pods of the workload must stick as pending because of PV
  - check the status of created PVC, it must be pending, and one of the event indicates that `access mode rwx (migratable: false) is incompatible with data locality strict-local mode`

The following example resources can be created/cleanup by `kubectl apply -f example.yaml` and `kubectl delete -f example.yaml`

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-6735-strict-local-rwx
provisioner: driver.longhorn.io
parameters:
  dataEngine: v1
  numberOfReplicas: "1"
  dataLocality: strict-local
  migratable: "false"
  staleReplicaTimeout: "30"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 6735-strict-local-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: longhorn-6735-strict-local-rwx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 6735-strict-local-rwx-verify
  labels:
    app: 6735-strict-local-rwx-verify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 6735-strict-local-rwx-verify
  template:
    metadata:
      labels:
        app: 6735-strict-local-rwx-verify
    spec:
      containers:
        - name: 6735-strict-local-rwx-verify
          image: busybox
          command: ['sh', '-c', 'while true ; do now=$(date +%s) ; echo $now ; for vol in share1 share2 share3 ; do echo $now >>/mnt/data/${vol}/log || echo $now >/mnt/data/${vol}/log ; done ; ls -l $(find /mnt/data -name log) ; sleep 1 ; done']
          volumeMounts:
            - mountPath: /mnt/data/share1
              name: share1
      volumes:
        - name: share1
          persistentVolumeClaim:
            claimName: 6735-strict-local-rwx
```
