### ISSUE TITLE
kubernetes: Add raw block device support 

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#678]
We should support a raw block device in Kubernetes.

**Comment by shuo-wu** [comment]
Cannot support it now:
1. The min version of Kubernetes which enables the feature `CSIBlockVolume` by default is v1.14. (Beta):
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

2. The CSI Provisioner starts to support block volume since v1.0.1:
https://github.com/kubernetes-csi/external-provisioner/releases/tag/v1.0.1

**Comment by yasker** [comment]
We are not ready to drop the support for Kubernetes v1.14- yet. Move to v0.7.0 release.

**Comment by meldafrawi** [comment]
Validation: **WIP**

Steps to test:
  - Create a StatefulSet using Longhorn raw block volume using:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeDevices:
        - devicePath: /dev/longhorn/testblk
          name: block-vol
  volumeClaimTemplates:
  - metadata:
      name: block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
```
> **Expexed result: Longhorn volume created and attached to web-0 pod** 

- Inside `web-0` pod write data to block device, Execute:
```
$ echo -ne "This is test data" > test.txt
$ DATA_SIZE=$(wc -c test.txt | awk '{print $1}')
$ dd if=test.txt of=/dev/longhorn/testblk bs=${DATA_SIZE} count=1 seek=0
```

- Verify data written using: 
`dd if=/dev/longhorn/testblk status=none bs=${DATA_SIZE} count=1 skip=0`

- Scale statefulset using:
`kubectl scale statefulset --replicas=2 web `

> **Expexed result: another Longhorn volume created and attached to web-1 pod**
