### ISSUE TITLE
[BUG] defaultSettings from ConfigMap not applied to Setting CR

### ISSUE THREAD

**Issue by Alexsaphir** [longhorn/longhorn#6815]
## Describe the bug (🐛 if you encounter this issue)

When deploying Longhorn with helm, default settings can be specified, like the following.
```
    defaultSettings:
      defaultReplicaCount: 2
```

A configmap is then created:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    default-replica-count: 2
```

Through the UI we can see that the setting was not applied. 

![image](https://github.com/longhorn/longhorn/assets/8057321/8311575c-e387-4627-b054-a10180f74945)

In the CR created by Longhorn we can find the following:
```
apiVersion: longhorn.io/v1beta2
kind: Setting
value: '3'
```

## To Reproduce

Deploy Longhorn using helm on a new k3s cluster.

## Expected behavior

The value used by Longhorn should match the one set by default.

## Environment

K3s cluster managed with Flux on baremetal.

## Additional context

On my side setting backupTarget yields the same issue found in  #6740.  

I think the issue come from some part of the code creating the CR Setting, but I was not able to find how those resources were created.
