### ISSUE TITLE
Second disk on node, not selected by defined sc

### ISSUE THREAD

**Issue by urbaman** [longhorn/longhorn#6816]
## Question

Hi,

I added a disk on the same node(s) where the default disk are, then tagged the default disks as "vdisk" and the added disks as "nvme".
I also added diskSelector: "vdisk" on the defualt sc, and created a similar sc with diskSelector: "nvme".

When I create a test pvc and pod with the default sc, it regularly schedules the volume on the defautl disk tagged vdisk, but when I create the same pvc and pod changing the sc to the created sc, it schedules on "vdisk" tagged disks instead of the "nvme" tagged ones.

Do I miss something?

```
kubectl describe sc longhorn-vdisk
Name:            longhorn-vdisk
IsDefaultClass:  Yes
Annotations:     longhorn.io/last-applied-configmap=kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-vdisk
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "6"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  diskSelector: "vdisk"
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            dataLocality=disabled,diskSelector=vdisk,fromBackup=,fsType=ext4,numberOfReplicas=6,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

```
kubectl describe sc longhorn-nvme
Name:            longhorn-nvme
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"longhorn-nvme"},"parameters":{"dataLocality":"disabled","diskSelector":"nvme","fromBackup":"","fsType":"ext4","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}

Provisioner:           driver.longhorn.io
Parameters:            dataLocality=disabled,diskSelector=nvme,fromBackup=,fsType=ext4,numberOfReplicas=3,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-vdisk
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-2
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc-2
```

## Environment

 - Longhorn version: 1.5.1
 - Kubernetes version: 1.28.2
 - Node config
   - OS type and version Ubuntu 22.04
   - Kernel version 5.15.0-84-generic
   - CPU per node: 16
   - Memory per node: 32
   - Disk type: vdisk is virtual, nvme is nvme
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM on Proxmox
