### ISSUE TITLE
Test node down scenario

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#684]
For v0.6.0. Manual test first.

**Comment by meldafrawi** [comment]
Validation: **WIP**

Manual test steps:
  - Create a pod with longhorn volume using: https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pvc.yaml
  - Write data to "/data" directory and compute it's checksum
  - Shutdown the node which the pod scheduled to.
  >> Expected result: pod should be rescheduled to another node.
  - Access the pod and verify the data checksum
  >> Expected result: Longhorn volume should be able to be used on the new node and checksum should match.

**Comment by meldafrawi** [comment]
Validation: **FAILED**

Manual test steps:
  - Create a Deployment with one pod attached to longhorn volume mount to `/data`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  labels:
    name: volume-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: volume-test
  template:
    metadata:
      labels:
        name: volume-test
    spec:
      containers:
      - name: volume-test
        image: nginx:stable-alpine
        volumeMounts:
        - name: volv
          mountPath: /data
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc

```

  - Write data to the `/data/` directory and compute it's checksum
  - Shutdown the node which the pod scheduled to.
  >> Expected result: pod should be in terminating state, and another pod will be starting to be created.
  >> replicas on the down node should be in `Failed` state, Longhorn should create new replicas respecting `Replica Soft Anti-Affinity` settings. **(FAILED)**  
  - Manually delete the terminating pod.
  >> pod should be deleted, and the other pod should be in running state, longhorn volume attached to it. 
  - Access the pod and verify the data checksum
  >> Expected result: Longhorn volume should be able to be used on the new node and checksum should match.

>> Actual Result: 
Longhorn is not starting new replicas replacing `Failed` ones.

![Screenshot from 2019-09-10 20-56-11](https://user-images.githubusercontent.com/18232258/64650738-29fd0300-d420-11e9-9d2d-62df18773548.png)
![Screenshot from 2019-09-10 20-56-22](https://user-images.githubusercontent.com/18232258/64650739-29fd0300-d420-11e9-958b-5e5e96813a36.png)
