### ISSUE TITLE
[BUG]filesystem trim RecurringJob times out (volumes where files are frequently created and deleted)

### ISSUE THREAD

**Issue by kgtkr** [longhorn/longhorn#6868]
## Describe the bug (🐛 if you encounter this issue)
filesystem trim RecurringJob times out on volumes where files are frequently created and deleted

log
```
time="2023-10-09T18:00:50Z" level=info msg="Created job" concurrent=1 groups= job=filesystem-trim labels="{\"RecurringJob\":\"filesystem-trim\"}" retain=0 task=filesystem-trim volume=mastodon-redis
time="2023-10-09T18:00:50Z" level=info msg="Creating job" concurrent=1 groups= job=filesystem-trim labels="{\"RecurringJob\":\"filesystem-trim\"}" retain=0 task=filesystem-trim volume=mastodon-minio
time="2023-10-09T18:00:50Z" level=info msg="job starts running" labels="map[RecurringJob:filesystem-trim]" namespace=longhorn-system retain=0 snapshotName=filesyst-5b896d47-0104-455b-a88b-de06def62593 task=filesystem-trim volumeName=mastodon-minio
time="2023-10-09T18:00:50Z" level=info msg="Running recurring filesystem trim for volume mastodon-minio" labels="map[RecurringJob:filesystem-trim]" namespace=longhorn-system retain=0 snapshotName=filesyst-5b896d47-0104-455b-a88b-de06def62593 task=filesystem-trim volumeName=mastodon-minio
time="2023-10-09T18:01:50Z" level=error msg="Failed to run job for volume" concurrent=1 error="failed to complete filesystem-trim for : Post \"http://longhorn-backend:9500/v1/volumes/mastodon-minio?action=trimFilesystem\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" groups= job=filesystem-trim labels="{\"RecurringJob\":\"filesystem-trim\"}" retain=0 task=filesystem-trim volume=mastodon-minio
```

## To Reproduce
Prepare a volume of around 50GB where files are frequently created and deleted.
Configure filesystem trim RecurringJob

## Expected behavior
job is successful
In fact, if you use the fstrim command, it will take some time, but it will finish.

## Environment

 - Longhorn version:v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:k3s
   - Number of management node in the cluster:4
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:Ubuntu22.04
   - Kernel version:
   - CPU per node:4core
   - Memory per node:4
   - Disk type(e.g. SSD/NVMe/HDD):ssd
   - Network bandwidth between the nodes:1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:9
 - Impacted Longhorn resources:
   - Volume names:mastodon-minio

**Comment by DamiaSan** [comment]
Could you describe better what you mean with _frequently created and deleted_? Just to try to reproduce it.

**Comment by kgtkr** [comment]
@DamiaSan 
This is an app where files are frequently file created and deleted, like object storage(minio).
fstrim will significantly reduce the size of that volume.

**Comment by kgtkr** [comment]
maybe relate?
#5976 #6575

**Comment by DamiaSan** [comment]
> maybe relate? #5976 #6575

They seems different from your problem, in those cases the recurring jobs makes snapshots, not trim. But maybe there could be something related to the recurring job itself ...
Can you provide a support bundle?

**Comment by kgtkr** [comment]
@DamiaSan Since the size limit that can be uploaded to github is exceeded, I will share it on google drive.
https://drive.google.com/file/d/1dOgczuJ6-AFHfEQDPMNDvbC72gqC-TJW/view?usp=sharing

**Comment by lucatr** [comment]
Facing the exact same issue with trimming minio volumes, which as described earlier has a high write/delete rate. Running the trim in the UI directly it completes without throwing an error, but takes quite some time to finish. I therefore suspect that this is just a timeout issue. I couldn't find an option to increase the timeout for a RecurringJob.

Any updates or workarounds for this issue?

**Comment by innobead** [comment]
@shuo-wu @c3y1huang any ideas for configurable timeout of recurring jobs?

**Comment by lucatr** [comment]
@innobead @shuo-wu @c3y1huang any ideas or workarounds to solve this issue? Could we make the timeout configurable?

**Comment by R-Studio** [comment]
@innobead, @shuo-wu, @c3y1huang any updates on this?

**Comment by derekbit** [comment]
I just realized our trim command is executed synchronously. To address the timeout issue for a big volume, we probably can handle it in a synchronous way.

**Comment by derekbit** [comment]
cc @c3y1huang @shuo-wu

**Comment by derekbit** [comment]
@c3y1huang Could you help update the status of the ticket? Thanks.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240728**
- longhorn `master-head` https://github.com/longhorn/longhorn/commit/d5e8a44104f5e03c310870b47da7c8ab55f671b3
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/a05002c662885d0b8381b219593fdb2083c0232d

**Verified on v1.7.x-head 20240728**
- longhorn `v1.7.x-head` https://github.com/longhorn/longhorn/commit/a94f6fe44b923d07475f87d8e80bc3981c709b06
- longhorn-manager `v1.7.x-head` https://github.com/longhorn/longhorn-manager/commit/3dc6ecc0941dd7df0d027d3c65ce2d798b1af90f

**The test steps**
1. Create StatefulSet and mount the volume
`kubectl apply -f statefulset.yaml`

<details>
<summary>statefulset.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwo
  labels:
    app: nginx-state-rwo
spec:
  ports:
  - port: 80
    name: web-state-rwo
  selector:
    app: nginx-state-rwo
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwo
spec:
  selector:
    matchLabels:
      app: nginx-state-rwo # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwo"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwo # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwo
        image: nginx:stable
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      accessModes:
#        - ReadWriteOnce
#        - ReadWriteMany
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-state-rwx
  labels:
    app: nginx-state-rwx
spec:
  ports:
  - port: 80
    name: web-state-rwx
  selector:
    app: nginx-state-rwx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-state-rwx
spec:
  selector:
    matchLabels:
      app: nginx-state-rwx # has to match .spec.template.metadata.labels
  serviceName: "nginx-state-rwx"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-state-rwx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-state-rwx
        image: nginx:stable
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web-state-rwx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]      
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 50Gi

```
</details>

2. Add a volume filesystem trim RecurringJob.

3. Continuously write 10 GB of data to the volume.
`./run-multiple-times.sh`

<details>
<summary>run-multiple-times.sh</summary>

```bash
#!/bin/bash

# Number of iterations
iterations=100

# File size in MBs (you can adjust this as needed)
file_size=10240

for (( i=1; i<=iterations; i++ ))
do
  echo "Iteration $i of $iterations"
# Write some data to the volume and sync
  kubectl exec -it web-state-rwo-0 -- /bin/bash -c "dd if=/dev/urandom of=/usr/share/nginx/html/"$file_size"m bs=1M count=$file_size oflag=direct status=progress && md5sum /usr/share/nginx/html/"$file_size"m"
  kubectl exec -it web-state-rwx-0 -- /bin/bash -c "dd if=/dev/urandom of=/usr/share/nginx/html/"$file_size"m bs=1M count=$file_size oflag=direct status=progress && md5sum /usr/share/nginx/html/"$file_size"m"
  kubectl exec -it web-state-rwo-0 -- /bin/bash -c "sync"
  kubectl exec -it web-state-rwx-0 -- /bin/bash -c "sync"
  echo "Completed iteration $i"
done
```
</details>

**Result Passed**

1. The filesystem trim RecurringJob ran successfully.
2. No error message `Failed to run job for volume` was observed in the support bundle.
