### ISSUE TITLE
[BUG] Backing Image Data Inconsistency if it's Exported from a Backing Image Backed Volume

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#6899]
## Describe the bug (🐛 if you encounter this issue)
The volume encounters a data integrity issue, if it's from a backing image, and such backing image is exported by a volume backed by another backing image.

## To Reproduce
1. Preparing a Harvester v1.2.0-head cluster (for using volume as an OS root disk)
2. Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
3. Creating volume **vol1** from **img1**
4. Creating a VM with **vol1** as the root disk, and writing some data
5. Issuing sync on filesystem, e.q. `$ sudo sync`
6. Stopping VM, and waiting until **vol1** is completely detached
7. Exporting **vol1** as **img2**
8. Creating  **vol2** from **img2**
9. Comparing data content between **vol1** and **vol2**, the data is inconsistent
10. Running `e2fsck -v` on **vol2**, fsck will report filesystem errors and require data repair

## Expected behavior
The data of **vol1** and **vol2** should be consistent.

## Support bundle for troubleshooting
[supportbundle_066aa8ed-a12b-4ccc-971c-59404ee44cd4_2023-10-16T07-46-44Z.zip](https://github.com/longhorn/longhorn/files/12913647/supportbundle_066aa8ed-a12b-4ccc-971c-59404ee44cd4_2023-10-16T07-46-44Z.zip)

## Environment

 - Longhorn version: v1.4.3
 - Harvester version: v1.2.0-head
 - Number of Longhorn volumes in the cluster: 2
 - Impacted Longhorn resources:
   - Volume names: pvc-b8bd9013-e8e9-449d-9c25-6c6c0824d0b3, pvc-de64dd95-b0c1-4ce9-864a-88d38e06d9d3

## Additional context

- If **vol1** is not backed by backing image, there is no data inconsistency found between **vol1** and **vol2**
- A single node Harvester cluster should be enough to reproduce this issue

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by WebberHuang1118** [comment]
Some observations with the following steps:
1. Preparing a Harvester v1.2.0-head single node cluster (for using volume as an OS root disk)
2. Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1** with replica number is 1
3. Checking data usage of **img1** (mapped to `bi default-image-s9rfj`), which is `640MB` ![data_usage_origin_img](https://github.com/longhorn/longhorn/assets/19387129/c79d04d3-cb9e-4383-8a07-19212c74de01)
4. Creating volume **os-vol** (mapped to `volume pvc-c3b1a434-86ee-453b-afc7-a52fe113c059`) from **img1** with claim size 10GB
5. Creating a VM with  **os-vol** as the root disk
6. Stopping VM, and waiting until **os-vol** is completely detached
7. Exporting **os-vol** as **os-vol.img** (mapped to `bi default-image-j8ghr`) with replica number is 1
8. Checking replica data usage of **os-vol**, which is `523MB` ![data_usage_os_vol](https://github.com/longhorn/longhorn/assets/19387129/bd756b83-c28d-4336-9512-4789f8a8ef23)
9. Checking data usage of **os-vol.img**, which is `2507MB` ![data_usage_os_vol_img](https://github.com/longhorn/longhorn/assets/19387129/ac8aa9d4-1620-4ba0-a5c5-2493a50fe1b3)
     - For the data usage, **os-vol.img**(2507MB) is much greater than the summation of **img1**(640MB) and **os-vol**(523MB)
     - The **os-vol.img**'s data usage shouldn't be greater than the summation of **img1**'s and **os-vol**'s ?
10. Creating volume **copy-vol** from **os-vol.img** with claim size 10GB
11. Comparing data content between **os-vol** and **copy-vol** with `$cmp -l os-vol copy-vol`
12. From the compare result [cmp.log](https://github.com/longhorn/longhorn/files/13184929/cmp.log), there are several continuous byte ranges overwritten with zero in the synthetic volume, **copy-vol**

Thanks

**Comment by ChanYiLin** [comment]
Note: From Longhorn side, we can't reproduce the issue

Longhorn side reproduce steps
1. Create a BackingImageA
2. Create a Volume with the BackingImageA
3. Write some data to the Volume
4. Get the checksum of the Volume
5. Export the BackingImageB from the Volume
6. Get the checksum of the BackingImageB
7. Checksum is the same

**Comment by innobead** [comment]
@WebberHuang1118 Please work with @ChanYiLin to reproduce the issue.

**Comment by WebberHuang1118** [comment]
From the above reproduce steps https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,

After step7 in https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,
since the VM is stopped and the volume is detached, IMHO, this issue could be reduced to "if the exported backing image content is the same as the source volume ?"

As I described in step9 https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,
the original backing image size is 640MB and the volume is 523MB, however, the synthesized backing image's grows to 2507MB (> (640MB + 523MB)).

If we create a new volume and compare its content to the source volume, the content is inconsistent. However, if the source volume is not a backing image backed volume, there is no such data inconsistency.

**Comment by WebberHuang1118** [comment]
I found a method to reproduce a similar case without Harvester-specific operations (no VM operation, only creating PVC from backing image and I/O access)

Detailed steps:
- Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
- Creating PVC **os-vol** from **img1** with claim size 10GB and 1 replica number
- Applying the following yaml to mount **os-vol** as block mode in the pod
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: block-volume-test
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/os-vol
        name: os-vol
    volumes:
      - name: os-vol
        persistentVolumeClaim:
          claimName: os-vol
  ```  
- Issuing filesystem expand and I/O on **os-vol**
  -  Enter pod **block-volume-test**
  -  Install fdisk
     - $ apt update; apt install -y fdisk
  - Expanding filesystem on **os-vol**
    - Check device (/dev/sda for exmaple) mapped to **os-vol** by device number
    - $ fdisk /dev/sda
      - d 1 n 1 default default No w
    - $ resize2fs /dev/sda1
  - Mounting /dev/sda1 and writing I/O into it
    - $ mkdir /data; $ mount -t ext4 /dev/sda1 /data
    - $ dd if=/dev/zero of=/data/file bs=1M count=2048
  - Flushing data to storage for **os-vol**
    - $ umount /data
  -  Delete pod **block-volume-test**, and waiting until **os-vol**'s LH volume detach
- Exporting os-vol as os-vol.img

**Comment by WebberHuang1118** [comment]
I found a method to reproduce a similar case without Harvester-specific operations (no VM operation, only creating PVC from backing image and I/O access)

Detailed steps:
- Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
- Creating PVC **os-vol** from **img1** with claim size 10GB and 1 replica number
- Applying the following yaml to mount **os-vol** as block mode in the pod
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: block-volume-test
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/os-vol
        name: os-vol
    volumes:
      - name: os-vol
        persistentVolumeClaim:
          claimName: os-vol
  ```  
- Issuing filesystem expand and I/O on **os-vol**
  -  Enter pod **block-volume-test**
  -  Install fdisk
     - $ apt update; apt install -y fdisk
  - Expanding filesystem on **os-vol**
    - Check device (/dev/sda for exmaple) mapped to **os-vol** by device number
    - $ fdisk /dev/sda
      - d 1 n 1 default default No w
    - $ resize2fs /dev/sda1
  - Mounting /dev/sda1 and writing I/O into it
    - $ mkdir /data; $ mount -t ext4 /dev/sda1 /data
    - $ dd if=/dev/zero of=/data/file bs=1M count=2048
  - Flushing data to storage for **os-vol**
    - $ umount /data
  -  Delete pod **block-volume-test**, and waiting until **os-vol**'s LH volume detach
- Exporting **os-vol** as image **os-vol.img**
- Creating PVC **copy-vol** from **os-vol.img** with claim size 10GB
- Comparing data content between **os-vol** and **copy-vol** with `$cmp -l os-vol copy-vol`
  - The data content is different between the two PVC, **os-vol** and **copy-vol**
- Finding filesystem error on **copy-vol** with` $e2fsck -c /dev/copy-vol`
  - There is no filesystem error on **os-vol**

**Comment by ChanYiLin** [comment]
I can reproduce the issue, will look into how we export BackingImage

**Comment by ChanYiLin** [comment]
## BackingImage Export Mechanism

Volume is composed of a series of snapshots and a BackingImage
```
Volume = BackingImage -> snap1 -> head
```

When Exporting Volume to another BackingImage [code](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L352)
1. create a snapshot
2. create an in-memory replica by `OpenSnapshot()` from that snaphot
3. `preload()` the block index map (including BackingImage)
  - so we know where to find the latest data in each block
5. use `SyncContent()` from sparse-tools to sync the replica content to BackingImage Datasource
  - we use `GetDataLayout()` to see if the block is hole or data

## Volume Cloning Mechanism

Is totally the same as exporting BackingImage except it won't load BackingImage when doing `preload()

**Comment by ChanYiLin** [comment]
## Volume Cloning Test
1. Creating BackingImage **img1** with Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img))
2. Creating StorageClass
  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-test
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "1"
    staleReplicaTimeout: "2880"
    backingImage: "img1"
  ```
2. Creating PVC **os-vol** from **img1** with claim size 5GB and 1 replicas
4. Mount **os-vol** as block mode in the pod
5. Issuing filesystem expand and I/O on **os-vol**
6. Cloning **os-vol** to another volume **os-cloned** by applying the YAML
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: os-cloned
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    storageClassName: longhorn-test
    resources:
      requests:
        storage: 5Gi
    dataSource:
      name: os-vol
      kind: PersistentVolumeClaim
  ```
7. attach both **os-vol** and **os-cloned** to the host and check the checksum are the same
