### ISSUE TITLE
[BUG] volume xyz has already attached to node xyz with incompatible parameters

### ISSUE THREAD

**Issue by marcinsiembida** [longhorn/longhorn#6918]
## Describe the bug (🐛 if you encounter this issue)

After Longhorn upgrade and maintenance I can not attach volume to any node. I tried to attach it to other nodes beside the one on picture, but it shows what you can see on the picture and when I am attaching it to the node that it seems to be attached, it tells that it has incompatible parameters.

![image](https://github.com/longhorn/longhorn/assets/48014776/37b77a43-eabe-4308-bee1-90811689464e)

## To Reproduce

To be honest I do not know how and when exactly it happened.

## Expected behavior

Volume should attach to any node.

## Support bundle for troubleshooting

I can't upload it here, file is too big.

## Environment

Longhorn version: 1.5.1
Installation method: Helm
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
Number of management node in the cluster: 3
Number of worker node in the cluster: 3
Node config
OS type and version: Ubuntu 22.04 LTS
Kernel version:
CPU per node: 8
Memory per node: 32gb
Disk type(e.g. SSD/NVMe/HDD): HDD
Network bandwidth between the nodes: 1Gb/s
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Xen Orchestra/XCP-ng
Number of Longhorn volumes in the cluster: 9
Impacted Longhorn resources: as on picture
Volume names: as on picture

**Comment by marcinsiembida** [comment]
I can not do it both ways on my company desktop, only way I think I can send it is via slack

**Comment by derekbit** [comment]
@marcinsiembida 

The volume is already attached with `disableFrontend: "true"` via the Longhorn API or UI.
Before attaching the volume with a workload via CSI with `disableFrontend: "true"`, you need to detach it first.

```
  spec:
    attachmentTickets:
      csi-b1ecf2118eec5276e0cc13a828287e35d23dc5c722dac8034d7c64b0c2195956:
        generation: 0
        id: csi-b1ecf2118eec5276e0cc13a828287e35d23dc5c722dac8034d7c64b0c2195956
        nodeID: k8s-plrnd-worker-3
        parameters:
          disableFrontend: "false"
          lastAttachedBy: "null"
        type: csi-attacher
      longhorn-ui:
        generation: 0
        id: longhorn-ui
        nodeID: k8s-plrnd-worker-3
        parameters:
          disableFrontend: "true"
          lastAttachedBy: "null"
        type: longhorn-api
    volume: pvc-23bee362-8192-45ee-8fc9-162811bfd207
  status:
    attachmentTicketStatuses:
      csi-b1ecf2118eec5276e0cc13a828287e35d23dc5c722dac8034d7c64b0c2195956:
        conditions:
        - lastProbeTime: "null"
          lastTransitionTime: "2023-10-04T11:03:24Z"
          message: volume pvc-23bee362-8192-45ee-8fc9-162811bfd207 has already attached
            to node k8s-plrnd-worker-3 with incompatible parameters
          reason: AttachedWithIncompatibleParameters
          status: "False"
          type: Satisfied
        generation: 0
        id: csi-b1ecf2118eec5276e0cc13a828287e35d23dc5c722dac8034d7c64b0c2195956
        satisfied: false
      longhorn-ui:
        conditions:
        - lastProbeTime: "null"
          lastTransitionTime: "2023-10-04T11:03:22Z"
          message: "null"
          reason: "null"
          status: "True"
          type: Satisfied
        generation: 0
        id: longhorn-ui
        satisfied: true
```
