### ISSUE TITLE
[TEST] add fleet gitops

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6935]
## What's the test to develop? Please describe

add fleet gitops

**Comment by innobead** [comment]
cc @Anarkis

**Comment by yangchiu** [comment]
According to [fleet official document](https://fleet.rancher.io/gitrepo-content#how-repos-are-scanned), `Chart.yaml` existing in the target repo is enough to deploy the application:
```
The following files are looked for to determine the how the resources will be deployed.
Chart.yaml: The resources will be deployed as a Helm chart. 
```
So following [the tutorial](https://fleet.rancher.io/quickstart#install) and create a `GitRepo` target to `longhorn` repo to install longhorn:
```
helm repo add fleet https://rancher.github.io/fleet-helm-charts/

helm -n cattle-fleet-system install --create-namespace --wait fleet-crd fleet/fleet-crd
helm -n cattle-fleet-system install --create-namespace --wait fleet fleet/fleet

cat > longhorn-gitrepo.yaml << "EOF"
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: https://github.com/longhorn/longhorn.git
  branch: master
  paths:
  - chart
EOF

kubectl apply -f longhorn-gitrepo.yaml
kubectl -n fleet-local get fleet
```
But the above steps will lead to all longhorn components installed in `default` namespace, which is not what we expect. Also the installation will be stuck in `Modified` status instead of `Synced` with message:
```
Modified(1) [Bundle longhorn-chart]; customresourcedefinition.apiextensions.k8s.io engineimages.longhorn.io modified {"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}; customresourcedefinition.apiextensions.k8s.io nodes.longhorn.io modified {"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}; customresourcedefinition.apiextensions.k8s.io volumes.longhorn.io modified {"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}} 
```
It's because some custom resource definitions have been modified after longhorn installation, so there are different from what's defined in the original repo, and causes `Synced` status unable to be reached. For example the status field of `EngineImage`, it should be empty in [the original crds.yaml](https://github.com/longhorn/longhorn/blob/master/chart/templates/crds.yaml):
```
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
But after longhorn installed, values in these fields are modified:
```
status:
  acceptedNames:
    kind: EngineImage
    listKind: EngineImageList
    plural: engineimages
    shortNames:
    - lhei
    singular: engineimage
  conditions:
  - lastTransitionTime: "2023-12-05T07:00:40Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-12-05T07:00:40Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta2
```
But first we try to solve the namespace problem by modifying the `longhorn-gitrepo.yaml`. Specifying `targetNamespace: longhorn-system` and reinstall again:
```
cat > longhorn-gitrepo.yaml << "EOF"
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: https://github.com/longhorn/longhorn.git
  branch: master
  targetNamespace: longhorn-system
  paths:
  - chart
EOF

kubectl apply -f longhorn-gitrepo.yaml
kubectl -n fleet-local get fleet
```
The installation will still fail with error message:
```
Error while running post render on files: invalid cluster scoped object [name=backingimagedatasources.longhorn.io kind=CustomResourceDefinition apiVersion=apiextensions.k8s.io/v1] found, consider using "defaultNamespace", not "namespace" in fleet.yaml 
```
It's possibly because `CustomResourceDefinition` is not namespaced, and if `targetNamespace` is specified, fleet will enforce __all__ resources be in this namespace and isn't smart enough to know which resource is not namespaced.

So we have 2 issues to be solved:

1. We need to make fleet ignore `crds` being modified
2. We need to make longhorn be able to be installed in the correct namespace

We can introduce a `fleet.yaml` file for customization to achieve the above.

According to https://fleet.rancher.io/bundle-diffs, a `diff` section in `fleet.yaml` can be used to ignore resources modification:
```
diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: volumes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
```
And by adding `defaultNamespace` field in `fleet.yaml`, it specify the default namespace to install resources:
```
defaultNamespace: longhorn-system
```
By [adding the `fleet.yaml` to longhorn repo](https://github.com/yangchiu/longhorn/blob/fleet/chart/fleet.yaml), the above issues can be solved, and longhorn can be successfully installed without problem:
```
cat > longhorn-gitrepo.yaml << "EOF"
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: https://github.com/yangchiu/longhorn.git
  branch: fleet
  paths:
  - chart
EOF

kubectl apply -f longhorn-gitrepo.yaml
kubectl -n fleet-local get fleet
# longhorn installed without problem
```
But if we don't want to add `fleet.yaml` in longhorn repo, we can leave these issues to users and let them handle the `fleet.yaml` file themselves by [adding `fleet.yaml` to their own project and treat longhorn as uptream helm chart](https://github.com/yangchiu/fleet-demo/blob/master/fleet.yaml) (which means we have to publish the chart first, not able to directly install by branches like master, v1.5.x):
```
defaultNamespace: longhorn-system
helm:
  repo: https://charts.longhorn.io
  chart: longhorn
  revision: 1.5.1
  releaseName: longhorn
diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: volumes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
```
And then create a `GitRepo` target to user's custom repo to install longhorn:
```
cat > longhorn-gitrepo.yaml << "EOF"
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: https://github.com/yangchiu/fleet-demo.git
  branch: master
EOF

kubectl apply -f longhorn-gitrepo.yaml
kubectl -n fleet-local get fleet
# longhorn also installed without problem
```

cc @innobead
