### ISSUE TITLE
[BUG] Version 1.5.1 cannot be deployed with ArgoCD

### ISSUE THREAD

**Issue by MohammedNoureldin** [longhorn/longhorn#6946]
## Describe the bug (🐛 if you encounter this issue)

Longhorn deployment via Argo CD fails, the syncing hangs stuck in the pre-upgrade job.

> Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn-system/longhorn-service-account: serviceaccount "longhorn-service-account" not found

## To Reproduce

Create a longhorn application in Argo CD and try to sync Longhorn.

## Expected behavior

Longhorn should be deployable by ArgoCD

## Environment

 - Longhorn version: 1.5.1
 - Installation method: ArgoCD with Helm
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context

Trying to install Longhorn using Helm directly and not with Argo CD works, which means the nodes are properly configured.

Argo CD application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: anchor
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.5.1
      helm:
        valuesObject: {{ lookup('template', 'applications/longhorn/values.yaml') | from_yaml }}
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```

values.yaml:

**Notice**: Trying also without any custom values also did **not** work.
```
persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: disabled
  reclaimPolicy: Retain
ingress:
  enabled: true
  ingressClassName: nginx
  host: "longhorn.{{ domain_name }}"
```
