### ISSUE TITLE
[BUG] longhorn manager isn't annotated with iam.amazonaws.com/role

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6947]
## Describe the bug (🐛 if you encounter this issue)

Related to test case `test_aws_iam_role_arn`.

Whether longhorn manager will be automatically annotated with `iam.amazonaws.com/role` is affected by when `AWS_IAM_ROLE_ARN` secret is set.

* If `AWS_IAM_ROLE_ARN` secret exists in the first place, longhorn manager won't be annotated:

(1) create s3 backup target secret with `AWS_IAM_ROLE_ARN`:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  AWS_DEFAULT_REGION: XXX
  AWS_IAM_ROLE_ARN: XXX
```

(2) set backup target url & secret through longhorn ui to use this secret
(3) longhorn manager won't be annotated:
```
$ kubectl describe pod longhorn-manager-cn7kn -n longhorn-system  | grep Annotations
Annotations:  <none>
```

* If `AWS_IAM_ROLE_ARN` secret doesn't exist in the first place, but edit the s3 backup target secret to add `AWS_IAM_ROLE_ARN` secret, longhorn manager will be annotated:

(1) create s3 backup target secret without `AWS_IAM_ROLE_ARN`:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  AWS_DEFAULT_REGION: XXX
```
(2) set backup target url & secret through longhorn ui to use this secret
(3) longhorn manager won't be annotated at this moment:
```
$ kubectl describe pod longhorn-manager-cn7kn -n longhorn-system  | grep Annotations
Annotations:  <none>
```
(4) edit the secret to add `AWS_IAM_ROLE_ARN` secret:
```
$ kubectl edit secrets aws-cred-secret -n longhorn-system
# add AWS_IAM_ROLE_ARN: XXX
```
(5) check longhorn manager, it's been annotated:
```
$ kubectl describe pod longhorn-manager-cn7kn -n longhorn-system | grep Annotations
Annotations:  iam.amazonaws.com/role: test-aws-iam-role-arn
```

Need to confirm if it's the expected behavior.

## Environment

 - Longhorn version: master-head, v1.4.4-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

related to https://github.com/longhorn/longhorn/issues/6912
