### ISSUE TITLE
[BUG] Failing to mount encrypted volumes

### ISSUE THREAD

**Issue by sfackler** [longhorn/longhorn#7033]
## Describe the bug (🐛 if you encounter this issue)

I have a new Longhorn install running on Rocky 8 with the storage class configured to encrypt volumes. Unfortunately, the `luksOpen` step fails with an exit code of 1 and no other output:

Kubelet log entry:
```
E1102 16:03:56.427802    1396 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a podName: nodeName:}" failed. No retries permitted until 2023-11-02 16:05:58.427784623 -0400 EDT m=+1079.475999719 (durationBeforeRetry 2m2s). Error: MountVolume.MountDevice failed for volume "pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a") pod "longhorn-test" (UID: "b7bdf74b-b915-408b-9c72-c65f34859fec") : rpc error: code = Internal desc = failed to run cryptsetup args: [luksOpen /dev/longhorn/pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a -d /dev/stdin] output:  error: exit status 1
```

The Longhorn UI shows the volume as healthy and bound.

The same PVC and Pod succeed when I configure the storage class to not encrypt.

The dmesg output seems fine:

```
[  813.211997] iscsi: registered transport (tcp)
[  813.229974] scsi host0: iSCSI Initiator over TCP/IP
[  813.238784] scsi 0:0:0:0: RAID              IET      Controller       0001 PQ: 0 ANSI: 5
[  813.245835] scsi 0:0:0:1: Direct-Access     IET      VIRTUAL-DISK     0001 PQ: 0 ANSI: 5
[  813.256482] scsi 0:0:0:0: Attached scsi generic sg0 type 12
[  813.260557] scsi 0:0:0:1: Attached scsi generic sg1 type 0
[  813.269349] sd 0:0:0:1: Power-on or device reset occurred
[  813.273403] sd 0:0:0:1: scsi_get_vpd_page: VPD page 0xb1 result 68 > 64 bytes
[  813.277648] sd 0:0:0:1: [sda] 20480 512-byte logical blocks: (10.5 MB/10.0 MiB)
[  813.283589] sd 0:0:0:1: [sda] Write Protect is off
[  813.287053] sd 0:0:0:1: [sda] Mode Sense: 69 00 10 08
[  813.287200] sd 0:0:0:1: [sda] Write cache: disabled, read cache: enabled, supports DPO and FUA
[  814.270771] sd 0:0:0:1: [sda] Attached SCSI disk
[  829.987182] device-mapper: uevent: version 1.0.3
```

## To Reproduce

Storage Class:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn-crypto
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  dataLocality: disabled
  encrypted: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

LUKS Secret:
```yaml
apiVersion: v1
data:
  CRYPTO_KEY_CIPHER: YWVzLXh0cy1wbGFpbjY0
  CRYPTO_KEY_HASH: c2hhMjU2
  CRYPTO_KEY_PROVIDER: c2VjcmV0
  CRYPTO_KEY_SIZE: MjU2
  CRYPTO_KEY_VALUE: OUZ6T2tKMG4xdTJuOEl1Ug==
  CRYPTO_PBKDF: YXJnb24yaQ==
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
type: Opaque
```

PersistentVolumeClaim:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test
  namespace: longhorn-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: longhorn
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
```

Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
  namespace: longhorn-system
spec:
  containers:
  - command:
    - sh
    - -c
    - echo hello world > /mnt/volume/hello.txt && cat /mnt/volume/hello.txt
    image: alpine:3.18
    name: main
    volumeMounts:
    - mountPath: /mnt/volume
      name: volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: longhorn-test
```

## Expected behavior

The volume should mount and the `longhorn-test` pod should successfully run and exit.

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Rocky 8
   - Kernel version: 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Wed Sep 20 15:55:39 UTC 2023
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe/HDD): EBS
   - Network bandwidth between the nodes: N/A
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2 m6a.xlarge
 - Number of Longhorn volumes in the cluster: 1
 - Impacted Longhorn resources:
   - Volume names: pvc-42a56a5f-2b82-4453-a0bf-53b63f9f7a1a
