### ISSUE TITLE
[QUESTION] Help for use aditionnal disk with longhorn (no disk visible)

### ISSUE THREAD

**Issue by ymohl-cl** [longhorn/longhorn#7043]
## Question

Hello, i try to setup a k3s cluster on a vps (ovh) with only one node. After install K3s and Helm, i would to install longhorn with data path defined to an other disk.

## Environment

 - Longhorn version: 1.5.2
 - k3s version: v1.27.7+k3s1
 - Kubernetes version: v1.27.7+k3s1
 - Node config
   - OS type and version: Debian latest
   - Kernel version bookworm
   - CPU per node: 4
   - Memory per node: 8Go
   - Disk type: 1 partition 20Go ssd for the file system + 1 partition 60Go ssd for longhorn formated by ext4
   - Network bandwidth and latency between the nodes: n/a
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): N/A

## Additional context

After a basic installation of k3s and helm, i run the longhorn installation like this:
The partition 2 is mounted on /database

```
sudo kubectl create ns longhorn-storage
sudo kubectl config set-context --current --namespace=longhorn-storage

helm repo add longhorn https://charts.longhorn.io
helm repo update

helm install longhorn longhorn/longhorn --namespace longhorn-storage \
	--set defaultSettings.createDefaultDiskLabeledNodes=true \
	--set defaultSettings.defaultDataPath=/database/longhorn

# change default storage class
sudo cp /var/lib/rancher/k3s/server/manifests/local-storage.yaml /var/lib/rancher/k3s/server/manifests/custom-local-storage.yaml
sudo sed -i -e "s/storageclass.kubernetes.io\/is-default-class: \"true\"/storageclass.kubernetes.io\/is-default-class: \"false\"/g" /var/lib/rancher/k3s/server/manifests/custom-local-storage.yaml
```

After the installations, all pods which need storage like postgres stay in "ContainerCreating" status and error message :

```
Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedAttachVolume  15s (x19 over 22m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a4...." : rpc error: code = Aborted desc = volume pvc-a4... is not ready for workloads
```

from the longhorn UI, volumes stay in detached, nodes disabled and no storage specifier.
longhorn manager is ready:

```
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:
```
    
The new storage class created:

```
Name:            longhorn
IsDefaultClass:  Yes
Annotations:     longhorn.io/last-applied-configmap=kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            dataLocality=disabled,fromBackup=,fsType=ext4,numberOfReplicas=3,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

I do not understood that i missed .. if someone could help me 👍 🙏 

Thank

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Comment by ymohl-cl** [comment]
i am not sure what you mean by support bundle ? I train on the infrastructure system and i don't know the expected resource you want

**Comment by derekbit** [comment]
Ref: https://longhorn.io/docs/1.5.2/advanced-resources/support-bundle/
BTW, you can check the error messages in longhorn-manager pod's log first.

**Comment by ymohl-cl** [comment]
yep i have attach the support bundle in my previous message ;) thank 🙏

**Comment by derekbit** [comment]
error message in longhorn-manager
```
2023-11-05T14:22:18.694704490+01:00 time="2023-11-05T13:22:18Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1610" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=paapscool.fr owner=paapscool.fr replica=pvc-ad27829b-1f73-44b4-a64d-107dda77d85f-r-fa5480eb state=detached volume=pvc-ad27829b-1f73-44b4-a64d-107dda77d85f
2023-11-05T14:22:18.694709674+01:00 time="2023-11-05T13:22:18Z" level=error msg="There's no available node for replica pvc-e74e4bf1-c54a-4c9a-aac6-ddd5909aabf0-r-97affa18, size 8589934592" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:68"
```

The `status.diskStatus` of `nodes.longhorn.io` `paapscool.fr`
```
    diskStatus:
      ssd:
        conditions:
        - lastProbeTime: "null"
          lastTransitionTime: "2023-11-05T11:52:20Z"
          message: Disk ssd(/database) on node paapscool.fr is ready
          reason: "null"
          status: "True"
          type: Ready
        - lastProbeTime: "null"
          lastTransitionTime: "2023-11-05T11:52:20Z"
          message: the disk ssd(/database) on the node paapscool.fr has 62704844800
            available, but requires reserved 64424509440, minimal 25% to schedule
            more replicas
          reason: DiskPressure
          status: "False"
          type: Schedulable
```

The volume nominal size is `10737418240` which exceeds the disk available size.
