### ISSUE TITLE
[BUG] ReadWriteMany(RWX) is not available when the K3s node offline(No internet access)

### ISSUE THREAD

**Issue by JiangLingJun** [longhorn/longhorn#7078]
## Environment
K3s version v1.24.8+k3s1 (https://github.com/k3s-io/k3s/commit/648004e4faeaf9e8705386342e95ec9bd211c2b8)
- Installation method:  Binary installation, offline
go version go1.18.8
Node(s) CPU architecture, OS, and Version:
node23: arch64, Ubuntu 20.04.6 LTS, kernel version 5.10.110 Core:8 Ram:32G
node22: arch64, Ubuntu 20.04.6 LTS, kernel version 5.10.110 Core:8 Ram:32G
node21: arch64, Ubuntu 20.04.5 LTS, kernel version 5.10.104-tegra (with Nvidia GPU) Core:8 Ram:32G

Longhorn Version: Charts Longhorn (101.1.0+up1.3.2)
- Installation method: Rancher app store, install offline via a self-managed image repository. 

Cluster Configuration:
```
3 server nodes , HA mode
node23 (11.1.1.23)
node22 (11.1.1.22)
node21 (11.1.1.21)
```

## Describe the bug 
Starting a pod on node23 and the pod mounted a dir via longhorn. 
① In the case of the node23 online, the mount operation is successful (node23 connects to the network from another NIC). Once node23 disconnected from the network, the mount fails. 
node23 online and the mount situation:
<img width="319" alt="12799874f30d551ed32baed0990551a" src="https://github.com/longhorn/longhorn/assets/17744561/26698c64-c46d-4ff2-9d0c-e64817cdc054">

Why the clientaddr is 192.168.1.123? The clientaddr is belong to the NIC which can access the Internet.
<img width="863" alt="2b86b72f1e2b3a9c7eafd13dd736925" src="https://github.com/longhorn/longhorn/assets/17744561/6b2dc1a3-99d0-4e59-be6a-7dc18505de6e">

node23 offline(disconnect the cable which the NIC can access the Internet), after about 2 minutes:
<img width="317" alt="98f0b7e95e32f239a37b3b58689c210" src="https://github.com/longhorn/longhorn/assets/17744561/cfbd9848-3d87-4bf4-8fd0-bf6b137fb33b">

② In the case of  the node23 offline, the pod can not running normal and the description as below:
<img width="865" alt="62505c8538ed05d74b92b4da0206ad7" src="https://github.com/longhorn/longhorn/assets/17744561/d203c007-6a08-499d-8e17-85b856e6947a">

and after executing command "mount -v | grep nfs", nothing output.

## To Reproduce
1. kubectl apply -f busybox-sc.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-longhorn-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
```

2. kubectl apply -f busybox-pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pv-claim
  labels:
    type: longhorn
    app: example
spec:
  storageClassName: my-longhorn-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
```
3. kubectl apply -f busybox-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: deploymysql
                values:
                - "true"
                operator: In  
      containers:
      - image: library/busybox:latest
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 4000
        volumeMounts:
        - name: busybox-persistent-storage
          mountPath: /tmp/
      volumes:
      - name: busybox-persistent-storage
        persistentVolumeClaim:
          claimName: busybox-pv-claim
```

## Expected behavior
Regardless of the network environment, the busybox pod running normal and the tmp directory can be used for RWX, and the data is stored in the Longhorn distributed system.

## Additional context
① when the PVC accessModes is set to ReadWriteOnce instead of ReadWriteMany, everything works fine.
② longhorn images in my self-managed image repository:
```
docker.io/rancher/mirrored-longhornio-csi-attacher:v3.4.0
docker.io/rancher/mirrored-longhornio-csi-node-driver-registrar:v2.5.0
docker.io/rancher/mirrored-longhornio-csi-provisioner:v2.1.2
docker.io/rancher/mirrored-longhornio-csi-resizer:v1.2.0
docker.io/rancher/mirrored-longhornio-csi-snapshotter:v3.0.3
docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.3.2
docker.io/rancher/mirrored-longhornio-longhorn-instance-manager:v1_20221003
docker.io/rancher/mirrored-longhornio-longhorn-manager:v1.3.2
docker.io/rancher/mirrored-longhornio-longhorn-ui:v1.3.2
docker.io/rancher/mirrored-longhornio-backing-image-manager:v3_20221003
docker.io/rancher/mirrored-longhornio-longhorn-share-manager:v1_20221003
docker.io/rancher/mirrored-kiwigrid-k8s-sidecar:1.12.3
```
