### ISSUE TITLE
[BUG] Encrypted volume doesn't have a filesystem

### ISSUE THREAD

**Issue by nrogerarkhn** [longhorn/longhorn#7101]
## Describe the bug (🐛 if you encounter this issue)

Longhorn encrypted volume isn't formatted and can't be mounted despite fsType being set.

## To Reproduce

Deploy the following manifest:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: arkhn
stringData:
  CRYPTO_KEY_VALUE: "Your encryption passphrase"
  CRYPTO_KEY_PROVIDER: "secret"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-encrypted
provisioner: driver.longhorn.io
allowVolumeExpansion: false
parameters:
  encrypted: "true"
  fromBackup: ""
  numberOfReplicas: "2"
  staleReplicaTimeout: "60"
  fsType: ext4
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "default"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc-encrypted
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-encrypted
```
The PVC is created but without a filesystem and can't be directly mounted.

## Expected behavior
The PVC is created formatted (here with ext4) and can be directly mounted.

## Support bundle for troubleshooting
[supportbundle_e7878bff-1bfd-4e2c-94c0-f59976ddb144_2023-11-14T16-47-49Z.zip](https://github.com/longhorn/longhorn/files/13352109/supportbundle_e7878bff-1bfd-4e2c-94c0-f59976ddb144_2023-11-14T16-47-49Z.zip)

## Environment

 - Longhorn version: 1.5.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via ArgoCD
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Debian 12
   - Kernel version: 6.1.0-13-cloud-amd64
   - CPU per node: 16
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes: 1Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1
 - Impacted Longhorn resources: Encrypted volume
   - Volume names: pvc-3e20929c-1469-43b4-b049-6ec316c05f64 (auto-generated)

## Additional context
Worked with unencrypted volumes, but would be nice to have with encrypted ones.

Thanks for the help!
