### ISSUE TITLE
[BUG] Deep spikes in the Longhorn public telemetry graph

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7105]
## Describe the bug (🐛 if you encounter this issue)

Deep spikes in the Longhorn public telemetry graph
![Screenshot 2023-11-14 at 3 38 20 PM](https://github.com/longhorn/longhorn/assets/22139961/ba737197-32f5-4c5b-8001-a3a0d9ffd071)

## To Reproduce

Go to https://metrics.longhorn.io/

## Expected behavior

Smoother graphs with no outlier

## Additional context:

Looks like the deep spikes in the graph is corresponding to the upgrade responder server pods being killed by OOM. Perhaps the server need more resource as the number of Longhorn nodes increased.

```yaml
    lastState:
      terminated:
        containerID: docker://f9e9b44a7ddc68b8b4f12029d789afec01679a3470dd7797fcf2a3b6c88ae3d2
        exitCode: 137
        finishedAt: "2023-11-14T21:22:05Z"
        reason: OOMKilled
        startedAt: "2023-11-12T03:51:04Z"
```
