### ISSUE TITLE
[BUG] Test case `test_csi_minimal_volume_size` failed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7170]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_csi_minimal_volume_size` failed on [master-haed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/729/testReport/tests/test_csi/test_csi_minimal_volume_size/)

After deleting the `PVC`, the associated `PV` and `volume` will be automatically deleted. 
I also attempted to reproduce the issue manually, but I couldn't replicate it.

```python
        common.delete_and_wait_pvc(core_api, pvc_name)
        common.delete_and_wait_pv(core_api, pv_name)
>       wait_for_volume_detached(client, vol_name)

test_csi.py:913: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:1898: in wait_for_volume_detached
    return wait_for_volume_status(client, name,
common.py:1951: in wait_for_volume_status
    wait_for_volume_creation(client, name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f36bdac6730>, name = 'longhorn-testvol-nb7bcx'

    def wait_for_volume_creation(client, name):
        for i in range(RETRY_COUNTS):
            volumes = client.list_volume()
            found = False
            for volume in volumes:
                if volume.name == name:
                    found = True
                    break
            if found:
                break
            time.sleep(RETRY_INTERVAL)
>       assert found
E       AssertionError

common.py:1877: AssertionError

```

## To Reproduce

Execute the test case on Jenkins server
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5294/

## Expected behavior

Have consistent test result in all branches result

## Support bundle for troubleshooting

[supportbundle_ff6710b1-8d4b-44f6-8b79-e733ce04fa8d_2023-11-22T08-40-26Z.zip](https://github.com/longhorn/longhorn/files/13435911/supportbundle_ff6710b1-8d4b-44f6-8b79-e733ce04fa8d_2023-11-22T08-40-26Z.zip)

## Environment

  - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.26.10+k3s2`
   - Number of management node in the cluster:`1`
   - Number of worker node in the cluster:`3`
 - Node config
   - OS type and version: `SLES 15-sp5`
   - Kernel version:
   - CPU per node: `4 cores`
   - Memory per node: `16GB`
   - Disk type(e.g. SSD/NVMe/HDD): `SSD`
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster:`1`
 - Impacted Longhorn resources:
   - Volume names: `longhorn-testvol-nb7bcx`

## Additional context

N/A

**Comment by roger-ryao** [comment]
Due to https://github.com/longhorn/longhorn/issues/6916, we need to update the related test case.
- https://github.com/longhorn/longhorn-tests/pull/1591

**Comment by roger-ryao** [comment]
> ## Describe the bug (🐛 if you encounter this issue)
> Test case `test_csi_minimal_volume_size` failed on [master-haed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/729/testReport/tests/test_csi/test_csi_minimal_volume_size/)
> 
> After deleting the `PVC`, the associated `PV` and `volume` will be automatically deleted. I also attempted to reproduce the issue manually, but I couldn't replicate it.

I couldn't replicate it due to my `persistentVolumeReclaimPolicy` being set to `Retain` in the longhorn-testvol-pv.yaml After changing the `persistentVolumeReclaimPolicy` to `Delete`, we were able to reproduce it manually.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-testvol-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  csi:
    driver: driver.longhorn.io
    volumeHandle: longhorn-testvol
    volumeAttributes:
      numberOfReplicas: "2"
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-testvol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: ''
  volumeName: longhorn-testvol-pv
```
