### ISSUE TITLE
[BUG] Deleting a PVC bound to a CSI PV, will delete associated volume and the CSI PV in result.

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7172]
## Describe the bug (🐛 if you encounter this issue)

From [test_csi_minimal_volume_size](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/729/testReport/tests/test_csi/test_csi_minimal_volume_size/)

Test case `test_csi_minimal_volume_size` failed because deleting a PVC bound to a CSI PV also result in the deletion of both associated volume and the CSI PV.

Can manually reproduced and can not reproduce on v1.5.3

## To Reproduce

1. Create a `volume.longhorn.io` `longhorn-testvol`, size=100MB
2. Creaet CSI PV `longhorn-testvol-pv`
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-testvol-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: '10485760'
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '30'
    volumeHandle: longhorn-testvol
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
```
3. Create PVC `longhorn-testvol-pvc`
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-testvol-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '5242880'
  storageClassName: ''
  volumeName: longhorn-testvol-pv
```
4. Delete PVC `longhorn-testvol-pvc`
5. CSI PV `longhorn-testvol-pv` and volume `longhorn-testvol` delete too

## Expected behavior

From test [steps](https://github.com/longhorn/longhorn-tests/blob/6be418e1d425fa9f07cd247aad7488e10d153336/manager/integration/tests/test_csi.py#L871), the PV and volume should not be deleted and this is the behavior on `v1.5.3`

## Support bundle for troubleshooting

Can find below log in csi-provisioner after delete PVC  `longhorn-testvol-pvc`
```
2023-11-22T08:57:09.545112171Z I1122 08:57:09.544975       1 controller.go:1509] delete "longhorn-testvol-pv": started
2023-11-22T08:57:09.548795793Z I1122 08:57:09.548687       1 controller.go:1524] delete "longhorn-testvol-pv": volume deleted
```
longhorn-manager
```
2023-11-22T08:51:43.745620930Z time="2023-11-22T08:51:43Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"longhorn-testvol\", UID:\"2a4feacf-655a-4bcd-8721-5d515eab09b7\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"9231\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' Deleting volume longhorn-testvol" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:298"
```

[supportbundle_e88ea81e-c6d2-4002-b188-c284192c27a5_2023-11-22T09-08-45Z.zip](https://github.com/longhorn/longhorn/files/13436063/supportbundle_e88ea81e-c6d2-4002-b188-c284192c27a5_2023-11-22T09-08-45Z.zip)

## Environment

 - Longhorn version: v1.6.0-dev(`07a87d`)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.2+k3s1
  
## Additional context

https://github.com/longhorn/longhorn/issues/7001
