### ISSUE TITLE
[BUG] Deadlock for RWX volume if an error occurs in its share-manager pod

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7183]
## Describe the bug (🐛 if you encounter this issue)

This is a regression introduced by https://github.com/longhorn/longhorn-manager/pull/2294 (for https://github.com/longhorn/longhorn/issues/7106).

When an error occurs in a share-manager pod, its phase transitions to `completed`. The share-manager controller is unable to restart the pod or update the status of the ShareManager CR because it continuously fails to contact the share manager process to attempt a remount.

Before https://github.com/longhorn/longhorn-manager/pull/2294, the share-manager controller did not attempt to contact the dead share manager process, so there was no deadlock.

## To Reproduce

1. Install Longhorn v1.6.0-dev.
2. Deploy the example NGINX deployment (`examples/rwx/rwx-nginx-deployment.yaml` in the longhorn/longhorn repo).
3. Identify the share manager pod.
4. Kill NFS-Ganesha inside the share-manager pod:
   `kubectl exec -n longhorn-system share-manager-pvc-9216f564-379e-4fd8-861b-e335ccbe8211 -- pkill ganesha.nfsd`
5. The share-manager pod remains in the `completed` phase and is not restarted.
    ```
    NAME                                                     READY   STATUS      RESTARTS   AGE
    share-manager-pvc-9216f564-379e-4fd8-861b-e335ccbe8211   0/1     Completed   0          12m
    ```
6. The longhorn-manager pod repeatedly logs a failure to sync the share-manager.
    ```
    [longhorn-manager-nf4lv] W1122 17:36:53.403245       1 logging.go:59] [core] [Channel #727 SubChannel #728] grpc: addrConn.createTransport failed to connect to {Addr: "10.42.59.152:9600", ServerName: "10.42.59.152:9600", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.42.59.152:9600: i/o timeout"
    [longhorn-manager-nf4lv] time="2023-11-22T17:36:53Z" level=error msg="Failed to sync Longhorn share manager" func=controller.handleReconcileErrorLogging file="utils.go:72" ShareManager=longhorn-system/pvc-9216f564-379e-4fd8-861b-e335ccbe8211 controller=longhorn-share-manager error="failed to sync longhorn-system/pvc-9216f564-379e-4fd8-861b-e335ccbe8211: failed to mount share manager pod share-manager-pvc-9216f564-379e-4fd8-861b-e335ccbe8211: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.59.152:9600: i/o timeout\"" node=eweber-v125-worker-e472db53-9kz5b
    ```
7. The ShareManager CR's status is not updated. It still shows as `running`.
    ```
    NAME                                       STATE     NODE                                AGE
    pvc-9216f564-379e-4fd8-861b-e335ccbe8211   running   eweber-v125-worker-e472db53-9kz5b   16m
    ```

## Expected behavior

Before https://github.com/longhorn/longhorn-manager/pull/2294, the share-manager pod would be successfully restarted.

## Support bundle for troubleshooting

There is a support bundle in the related CNCF Slack thread:
https://cloud-native.slack.com/archives/CNVPEL9U3/p1700618585865019

There are other issues in that support bundle as well, so the reproduce may be a bit easier to work with.

## Additional context

After https://github.com/longhorn/longhorn-manager/pull/2294, in the share-manager controller, we always attempt a gRPC call to the share-manager pod to do a remount if `status.state == running` in the ShareManager CR.

https://github.com/longhorn/longhorn-manager/blob/3a66afaa7ec086f7f6ec6ebb10fd6797ac30830d/controller/share_manager_controller.go#L543-L545

However, we do not update the `status.state` of the ShareManager CR until AFTER this point in the reconcile loop.

https://github.com/longhorn/longhorn-manager/blob/3a66afaa7ec086f7f6ec6ebb10fd6797ac30830d/controller/share_manager_controller.go#L688-L711

So we indefinitely reconcile. We cannot do a remount because the share-manager pod is dead, and we cannot learn the share-manager pod is dead because we error out while attempting to reconcile.

**Comment by derekbit** [comment]
A workaround is to manually update the status of the share manager resource to `error`.

`kubectl -n longhorn-system patch lhsm pvc-b08581d7-f48c-4b27-8083-7f24b89ba4ea --type=merge --subresource status --patch 'status: {state: error}'`

**Comment by innobead** [comment]
@derekbit let's add this issue to https://github.com/longhorn/longhorn/wiki/Outstanding-Known-Issues-of-Releases.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `23a995`) with test [steps](https://github.com/longhorn/longhorn/issues/7183#issue-2006844619)

Kill NFS-Ganesha inside the share-manager pod, share manager pod will restart and RWX volume worked well after share manager pod ready.

**Comment by voarsh2** [comment]
So is this being fixed in the NEXT bugfix release?

**Comment by derekbit** [comment]
@voarsh2 Yes.

**Comment by voarsh2** [comment]
Good thing I didn't upgrade to this version (mostly, because I couldn't, because it takes you weeks to get the Helm Chart updated), so I guess I wait another month or so for you to upgrade the Helm Chart twice..........)

**Comment by cod-r** [comment]
Should we expect a quick release of 1.5.4 with this fix like we got for 1.5.3?

**Comment by innobead** [comment]
We will not have a quick release 1.5.4 following 1.5.3, because this scenario will only occur rarely, and also there is a workaround provided by @derekbit .  1.5.4 is still planned and will follow the regular release cadence, which is scheduled after 1.6.0.

**Comment by cod-r** [comment]
Is it better to stay on 1.5.2 instead if we don't use the encrypted volumes?

**Comment by voarsh2** [comment]
> Is it better to stay on 1.5.2 instead if we don't use the encrypted volumes?

That's what I want to know.......

> We will not have a quick release 1.5.4 following 1.5.3, because this scenario will only occur rarely in a specific case, and also there is a workaround provided by @derekbit . 1.5.4 is still planned and will follow the regular release cadence, which is scheduled after the upcoming 1.6.0.

I'm confused, is https://github.com/longhorn/longhorn-manager/pull/2312 merged into 1.6.x then?
I don't know about you, but RXW workloads have given me hell in the past, and they sure do crash, so I'm thinking the 1.5.3 error that I might get, is more than probable......... ? So I shouldn't upgrade to 1.5.3 and wait 6 months for 1.6.x? (Just a guess, because I don't know your release schedule)

**Comment by ejweber** [comment]
v1.6.0 is on the roadmap for Q4 2023: https://github.com/longhorn/longhorn/wiki/Roadmap#longhorn-v16-q4-2023.

It may not drop before the end of the year, but it is definitely coming sooner than later.

**Comment by voarsh2** [comment]
> v1.6.0 is on the roadmap for Q4 2023: https://github.com/longhorn/longhorn/wiki/Roadmap#longhorn-v16-q4-2023.
> 
> It may not drop before the end of the year, but it is definitely coming sooner than later.

Ah yes, I think I'll wait then. :)
Don't want any *more* RXW related problems.

**Comment by SISheogorath** [comment]
I added an alerting simple alerting rule for kube-prometheus-stack

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: longhorn-issue-7183
  namespace: longhorn-system
spec:
  groups:
  - name: longhorn.rules
    rules:
    - alert: LonghornShareManagerOff
      annotations:
        description: Longhorn share manager count is off by {{$value}}. This is likely due to a recent bug in Longhorn. https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359
        summary: Longhorn share manager count is off by {{$value}} for 5m.
      expr: count(sum by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_access_mode{access_mode="ReadWriteMany"}) * on (namespace, persistentvolumeclaim) group_right kube_persistentvolumeclaim_info{storageclass=~"longhorn.*"}) - sum(kube_pod_info{namespace="longhorn-system", pod=~"share-manager-.*"}) > 0
      for: 5m
      labels:
        issue: Longhorn share manager count is off by {{$value}} for 5m.
        severity: critical
```

It simply counts the number of share-manager pods and the amount of PVCs with longhorn storage class and RWX access mode. This should alert most relevant cases. (Might be useful to explicitly check for state running, but I might add that later on.)

**Comment by SISheogorath** [comment]
Given the (understandable) lack of releases in the past few days, I decided to add a little additional mitigation to the problem:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: longhorn-hotfix-7183
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: longhorn-hotfix-7183
          containers:
          - image: docker.io/bitnami/kubectl:1.28
            name: longhorn-hotfix
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: "1"
                memory: 256Mi
            command:
              - /bin/bash
            args:
              - -c
              - |
                for i in $(kubectl get lhsm -n longhorn-system --no-headers -o custom-columns=NAME:metadata.name); do 
                  if kubectl get pods --no-headers -n longhorn-system "share-manager-$i" | grep -v Running; then 
                    kubectl patch lhsm -n longhorn-system --type=merge --subresource status --patch 'status: {state: error}' $i
                  fi
                done
          restartPolicy: OnFailure
  schedule: '*/5 * * * *'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-hotfix-7183
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-hotfix-7183
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "longhorn.io"
  resources:
  - sharemanagers
  - sharemanagers/status
  verbs:
  - patch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-hotfix-7183
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-hotfix-7183
subjects:
- kind: ServiceAccount
  name: longhorn-hotfix-7183
```

This cronjob checks for running share-manager pods for each sharemanager object (assuming that all RWX shares are supposed to be mounted) and patch them as errored if this isn't the case.

It's not perfect and I didn't test it too much yet, but it's basically what I did for the alert above manually, now it's automated. :)

You can just `kubectl apply -n longhorn-system -f [./path/to/above.yaml](https://git.shivering-isles.com/shivering-isles/infrastructure-gitops/-/raw/b230eb310e9f27e53d8dfba3fbaa9581a797795d/infrastructure/longhorn/hotfix-7183.yaml)`. Of course, use at your own risk.
