### ISSUE TITLE
Driver Deployer Stucks Init:0/1 State

### ISSUE THREAD

**Issue by akuscu-smartpulse** [longhorn/longhorn#723]
I have 1master 1 slave kubernetes bare metal for test purposes.When i try to deploy longhorn with kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
But longhorn driver stucks Init:0/1 state.
here are manager logs :
```
time="2019-09-16T15:22:26Z" level=info msg="Start kubernetes controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn Engine Image controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn node controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn websocket controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn Setting controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn engine controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn replica controller"
time="2019-09-16T15:22:26Z" level=info msg="Start Longhorn volume controller"
time="2019-09-16T15:22:28Z" level=debug msg="Updated setting default-engine-image to rancher/longhorn-engine:v0.5.0"
time="2019-09-16T15:22:28Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"kubernames-slave\", UID:\"cbbd348d-ff41-49b5-94cd-eb718826014b\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"9793\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node kubernames-slave is ready"
time="2019-09-16T15:22:28Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:22:28Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"kubernames-slave\", UID:\"cbbd348d-ff41-49b5-94cd-eb718826014b\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"9793\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Disk /var/lib/rancher/longhorn/ on node kubernames-slave is ready"
time="2019-09-16T15:22:28Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"kubernames-slave\", UID:\"cbbd348d-ff41-49b5-94cd-eb718826014b\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"9793\", FieldPath:\"\"}): type: 'Normal' reason: 'Schedulable' Disk /var/lib/rancher/longhorn/ on node kubernames-slave is schedulable"
time="2019-09-16T15:22:28Z" level=debug msg="Created engine image ei-9bea8a9c (rancher/longhorn-engine:v0.5.0)"
time="2019-09-16T15:22:28Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-09-16T15:22:28Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:22:29Z" level=debug msg="Engine Image Controller kubernames-slave picked up ei-9bea8a9c (rancher/longhorn-engine:v0.5.0)"
time="2019-09-16T15:22:29Z" level=info msg="Created daemon set engine-image-ei-9bea8a9c for engine image ei-9bea8a9c (rancher/longhorn-engine:v0.5.0)"
time="2019-09-16T15:22:34Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-09-16T15:22:40Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-09-16T15:22:46Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-09-16T15:22:52Z" level=debug msg="Waiting for engine image rancher/longhorn-engine:v0.5.0 to be ready"
time="2019-09-16T15:22:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:22:56Z" level=info msg="Engine image ei-9bea8a9c (rancher/longhorn-engine:v0.5.0) become ready"
time="2019-09-16T15:22:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:22:57Z" level=debug msg="Failed to check for the latest upgrade: Post https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade: dial tcp: i/o timeout"
time="2019-09-16T15:22:58Z" level=debug msg="Engine image rancher/longhorn-engine:v0.5.0 is ready"
time="2019-09-16T15:22:58Z" level=info msg="Listening on 10.244.1.149:9500"
time="2019-09-16T15:23:06Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:23:06Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:23:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:23:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:23:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:23:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:07Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:07Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:07Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:24:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:08Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:08Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:26Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
time="2019-09-16T15:25:56Z" level=error msg="Error while parsing the value of the label node-role.kubernetes.io/worker in node kubernames-slave:strconv.ParseBool: parsing \"\": invalid syntax"
```
Here are fdisk -l results on slave:

```
Disk /dev/loop0: 89 MiB, 93327360 bytes, 182280 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 88.7 MiB, 92983296 bytes, 181608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sda: 30 GiB, 32212254720 bytes, 62914560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 68537E6B-67AA-4777-AE05-57ABEC2180A2

Device     Start      End  Sectors Size Type
/dev/sda1   2048     4095     2048   1M BIOS boot
/dev/sda2   4096 62912511 62908416  30G Linux filesystem
```
here are kubectl get po -A : 
```
default           traefik-67cf65b85b-fjt7x                    1/1     Running    0          98m
kube-system       canal-f2rzv                                 3/3     Running    0          101m
kube-system       canal-nfksv                                 3/3     Running    0          99m
kube-system       coredns-5c98db65d4-bb2r8                    1/1     Running    0          101m
kube-system       coredns-5c98db65d4-lk8dq                    1/1     Running    0          101m
kube-system       etcd-kubernates-master                      1/1     Running    0          100m
kube-system       kube-apiserver-kubernates-master            1/1     Running    0          100m
kube-system       kube-controller-manager-kubernates-master   1/1     Running    0          100m
kube-system       kube-proxy-bbvp4                            1/1     Running    0          99m
kube-system       kube-proxy-z5lnv                            1/1     Running    0          101m
kube-system       kube-scheduler-kubernates-master            1/1     Running    0          100m
longhorn-system   engine-image-ei-9bea8a9c-b69f2              1/1     Running    0          7m40s
longhorn-system   longhorn-driver-deployer-5d94b4b959-6v4fl   0/1     Init:0/1   0          7m46s
longhorn-system   longhorn-manager-4hvv4                      1/1     Running    0          7m46s
longhorn-system   longhorn-ui-6bddf979f4-zvkgt                1/1     Running    6          7m46s

```
kubectl get nodes : 

```
NAME                STATUS   ROLES    AGE    VERSION
kubernames-slave    Ready    <none>   100m   v1.15.2
kubernates-master   Ready    master   102m   v1.15.2
```

**Comment by yasker** [comment]
@akuscu-smartpulse The error you see in the manager log is not critical. The init process of `longhorn-driver-deployer` is trying to reach the manager through `longhorn-backend` service, and it seems it's down.

Can you open the UI? UI should use the same `longhorn-backend` service and if it doesn't work, the services function of kubernetes may have some issues.

**Comment by akuscu-smartpulse** [comment]
I can not reach UI with curl and from browser.I can reach the backend service using clusterIP.My other kubernetes services and pods working correctly.I tried with kubeadm reset and setup cluster again but the result is same.I also tried remove and pull again docker images but same.
Curl to clusterIP of backend gives me this result:
curl 10.107.87.211:9500
> {"data":[{"actions":{},"id":"v1","links":{"self":"http://10.107.87.211:9500/v1"},"type":"apiVersion"}],"links":{"late"resourceType":"apiVersion","type":"collection"}

**Comment by akuscu-smartpulse** [comment]
When i try with ubuntu 16 it seems ok now.I will try again later with ubuntu 18 and notice the result.

**Comment by akuscu-smartpulse** [comment]
Ok i understand the problem.Actually i have multiple ip on the node.So when i use only 1 network card it working correctly but when i bind other interfaces it reproduces same problem.I tried give metrics to interfaces but no effect.If i find a solution i will write it down

**Comment by akuscu-smartpulse** [comment]
I added a new 1 network card node and change yaml file like this:
```
.
.
.
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      hostNetwork: true #--> I added hostnetwork
      containers:
      - name: longhorn-manager
        image: rancher/longhorn-manager:v0.5.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - rancher/longhorn-engine:v0.5.0
        - --manager-image
        - rancher/longhorn-manager:v0.5.0
        - --service-account
        - longhorn-service-account
        ports:
        - containerPort: 9500
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: varrun
          mountPath: /var/run/
        - name: longhorn
          mountPath: /var/lib/rancher/longhorn/
          mountPropagation: Bidirectional
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: varrun
        hostPath:
          path: /var/run/
      - name: longhorn
        hostPath:
          path: /var/lib/rancher/longhorn/
      serviceAccountName: longhorn-service-account
.
.
.
```

After that it is running normally.Is this hostNetwork:true definition proper for use ?
