### ISSUE TITLE
[BUG] Volume conditions are not represented in the UI for v1.4.x and newer

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7241]
## Describe the bug (🐛 if you encounter this issue)

In v1.3.x, volume conditions appeared on the volume list and volume details pages of the UI.

![image](https://github.com/longhorn/longhorn/assets/24213029/150f1d29-7ef7-4a6b-8efd-c4d2e02ed632)

![image](https://github.com/longhorn/longhorn/assets/24213029/3cfa1552-62ee-4d9b-98b8-05b7866d7027)

In v1.4.x and beyond, this is no longer the case.

![image](https://github.com/longhorn/longhorn/assets/24213029/cf962c40-9bc2-4bc3-a594-5fb7ca749e1f)

![image](https://github.com/longhorn/longhorn/assets/24213029/ab86cd0f-09b0-460f-9e3a-a6e130af9bbb)

## To Reproduce

1. Install Longhorn.
2. (optional) Set `allow-volume-creation-with-degraded-availability` to false.
3. (optional) Disable scheduling on all but one node.
4. Create a volume.
5. Notice that the volume's conditions are not represented on either page. (With the optional steps, notice you don't see any indication of a replica scheduling error.)

## Additional context

Discovered while investigating https://github.com/longhorn/longhorn/issues/7231.

**Comment by innobead** [comment]
@m-ildefons when working on issues, please remember to update the status of the Zenhub pipeline as well to reflect the issue state. 

![image](https://github.com/longhorn/longhorn/assets/899492/cf851a0c-9dad-4807-8431-11ff1e475504)

**Comment by m-ildefons** [comment]
Thanks for the reminder, I've installed the Zenhub plugin and requested access to the org on Zenhub. I'll assign it as soon as I've joined there and have permissions to do so.

**Comment by innobead** [comment]
> Thanks for the reminder, I've installed the Zenhub plugin and requested access to the org on Zenhub. I'll assign it as soon as I've joined there and have permissions to do so.

Sent the invitation to you, so you should be able to update issues around the Zenhub board.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `d916e4`) with test [steps](https://github.com/longhorn/longhorn/issues/7241#issue-2021270590)

Volume condition `type: Scheduled` now represented in UI when `status: "False"`
![image](https://github.com/longhorn/longhorn/assets/73337386/94317e86-6f4b-472d-8c11-0a9aeb5e4fde)
![image](https://github.com/longhorn/longhorn/assets/73337386/5be25cd9-124e-41d8-8bf2-7602f4172b3b)

<details>
  <summary>conditions</summary>

```yaml
> k get volume -A -o yaml | grep conditions -A 25
    conditions:
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-28T04:18:37Z"
      message: ""
      reason: ""
      status: "False"
      type: WaitForBackingImage
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-28T04:18:37Z"
      message: ""
      reason: ""
      status: "False"
      type: TooManySnapshots
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-28T06:28:25Z"
      message: replica scheduling failed
      reason: ReplicaSchedulingFailure
      status: "False"
      type: Scheduled
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-28T04:18:38Z"
      message: ""
      reason: ""
      status: "False"
      type: Restore
    currentImage: longhornio/longhorn-engine:master-head
```
</details>
