### ISSUE TITLE
[FEATURE] Offline volume migration from v1 to v2 data engine

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7267]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Support an offline volume migration to let users migrate their v1 volumes to v2. 

## Additional context

https://communities.vmware.com/t5/ESXi-Discussions/How-to-move-VM-between-different-storage/td-p/2738307

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
Moved to 1.13.0, since we can leverage CDI to achieve this in-place migration. cc @derekbit @COLDTURNIP

**Comment by derekbit** [comment]
FYR

# Longhorn v1 to v2 Volume Migration Guide Using CDI

This guide provides instructions for migrating data from a Longhorn v1 volume to a Longhorn v2 volume (SPDK/NVMe-oF) using Containerized Data Importer (CDI) in a Kubernetes cluster.

---

## 1. Prerequisites

Before starting the migration process:

1. **CDI Installed**: Ensure Containerized Data Importer (CDI) is installed and running in your Kubernetes cluster.
2. **V2 StorageClass**: Verify that a StorageClass configured for the Longhorn v2 Data Engine (`dataEngine: v2`) is available (e.g., `longhorn-v2`).
3. **Scale Down Workload**: Scale down your application's Deployment, StatefulSet, or Pod to `0` replicas to detach the v1 PVC. **This step is critical to prevent `Multi-Attach` (RWO) volume conflicts during cloning.**

---

## 2. Migration Procedure

### Step 1: Create the DataVolume Manifest

Create a `DataVolume` custom resource (CR) specifying your existing v1 PVC as the source and your v2 StorageClass as the target.

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: app-data-v2
  namespace: default
spec:
  source:
    pvc:
      name: app-data-v1 # Existing Longhorn v1 PVC
      namespace: default
  pvc:
    storageClassName: longhorn-v2 # Longhorn v2 StorageClass
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi # Must be equal to or greater than source size
```

### Step 2: Apply Manifest and Monitor Migration

Apply the `DataVolume` resource and monitor the cloning progress:

```bash
kubectl apply -f datavolume.yaml
kubectl get dv app-data-v2 -n default -w
```

Wait until the `PHASE` displays **`Succeeded`** and `PROGRESS` reaches **`100.0%`**.

### Step 3: Reattach Workload to New v2 PVC

Once completed, CDI generates a target PVC named `app-data-v2`. Update your application's workload manifest to reference this new PVC, then scale your application back up.

```yaml
volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: app-data-v2
```
`
