### ISSUE TITLE
[BUG] 1.5.1: AttachVolume.Attach failed for volume "pvc-xxx » […] volume pvc-xxx failed to attach to node node0x with attachmentID csi-xxx

### ISSUE THREAD

**Issue by CaptainKrby** [longhorn/longhorn#7313]
## Describe the bug (🐛 if you encounter this issue)

Sometimes, after cordon / drain from a cluster node, some pods remain in the pending state. 

The events generally display :

```
LAST SEEN   TYPE      REASON               OBJECT                           MESSAGE
75s         Warning   FailedAttachVolume   pod/keycloak-test-postgresql-0   AttachVolume.Attach failed for volume "pvc-b91abf30-485d-4aeb-96e1-938a50bdb291" : rpc error: code = Internal desc = volume pvc-b91abf30-485d-4aeb-96e1-938a50bdb291 failed to attach to node node03 with attachmentID csi-a782ae047fc39dbf4c999f20196ca3ce16d7d9bf7cb5382a57839f1c2b9f6e8a: the volume is currently attached to different node node04
10m         Warning   FailedMount          pod/keycloak-test-postgresql-0   Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[dshm data kube-api-access-cjdtl]: timed out waiting for the condition
```

I have no way of getting this pod to work again, and the volume seems healthy on the UI.

## Environment

 - Longhorn version: 1.5.1
 - Installation method: Helm
 - Kubernetes distro (Official Kubernetes with Kubespray and version: 1.24
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Debian 10
   - Kernel version: 4.19.0-25-amd64
   - CPU per node: 96
   - Memory per node: 256
   - Disk type(e.g. SSD/NVMe/HDD): SSD

My support bundle is ~600 mb, I'll prepare the upload and send it to the support.

**Comment by CaptainKrby** [comment]
I have read this discussion but I haven't found the answer to my problem, so I'll have to look into it further.

If it helps, I've already noticed in the past that AttachmentID ticket was set to null in some cases. 
But I don't know any further…

Here's an example of the volumeattachment pvc-b91abf30-485d-4aeb-96e1-938a50bdb291  :

```
status:
  attachmentTicketStatuses:
    csi-a782ae047fc39dbf4c999f20196ca3ce16d7d9bf7cb5382a57839f1c2b9f6e8a:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2023-11-14T10:52:36Z"
        message: 'the volume is currently attached to different node node04 '
        reason: ""
        status: "False"
        type: Satisfied
      generation: 0
      id: csi-a782ae047fc39dbf4c999f20196ca3ce16d7d9bf7cb5382a57839f1c2b9f6e8a
      satisfied: false
    longhorn-ui:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2023-11-13T19:20:55Z"
        message: ""
        reason: ""
        status: "True"
        type: Satisfied
      generation: 0
      id: longhorn-ui
      satisfied: true
```

FYI we only provision Longhorn volumes by doing a `kubectl apply -f pvc.yaml`, nothing with the Longhorn UI directly.
