### ISSUE TITLE
[IMPROVEMENT] Remove static sessionAffinity: ClientIP set in most services if not required

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7399]
## What's the task? Please describe

Longhorn API doesn't require sessions as each API call should be independent. Although backing image download and upload are present, the internal forwarding is handled by Longhorn manager and not the load balancer layer. However, most services have sessionAffinity hard-coded with ClientIP. 

[/charts/longhorn/templates/services.yaml#L1-L16](https://github.com/longhorn/charts/blob/728dfbcad8f23cca4574db0b61937015ebadb1dd/charts/longhorn/templates/services.yaml#L1-L16)
```yaml
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-conversion-webhook
  name: longhorn-conversion-webhook
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: longhorn-conversion-webhook
  ports:
  - name: conversion-webhook
    port: 9443
    targetPort: conversion-wh
```

**Comment by ejweber** [comment]
The scope of this issue is to investigate whether or not we can remove `sessionAffinity: ClientIP` from our services, and that will be my primary area of investigation. However, the broader context from one user can be summarized as follows:

Can Longhorn run in an "multitenant" environment in which some nodes related to one tenant can only talk to other nodes related to one tenant? `sessionAffinity: ClientIP`  makes this difficult, because after the Kubernetes network control plane decides randomly which destination IP address to resolve a service to, it will not make another decision for 10800 (configured by Longhorn) seconds. If, instead, the Kubernetes network control plane might make a different decision every time a connection attempt was made, a pod in one tenant would have a reasonable chance of getting connected to a pod backing a service in the same tenant.

Before getting started with the main investigation, I decided to try to understand exactly how/why Longhorn cannot work in the "multitenant" environment today.

### Setup

In a two node cluster, temporarily ensure it is impossible for one node (`kgxdq`) to route traffic to another node (`nn4rg`) and vice-versa.

```
root@eweber-v126-worker-9c1451b4-kgxdq:~# ip route
default via 143.198.224.1 dev eth0 proto static 
10.42.0.0/24 via 10.42.0.0 dev flannel.1 onlink 
10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink
10.42.2.0/24 dev cni0 proto kernel scope link src 10.42.2.1 
10.42.3.0/24 via 10.42.3.0 dev flannel.1 onlink 
10.48.0.0/16 dev eth0 proto kernel scope link src 10.48.0.37 
10.124.0.0/20 dev eth1 proto kernel scope link src 10.124.0.31 
143.198.224.0/20 dev eth0 proto kernel scope link src 143.198.232.225

root@eweber-v126-worker-9c1451b4-kgxdq:~# ip route del 10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink

# Repeat on the other node.
```

- `kgxdq` runs pods on `10.42.2.x` and can't communicate with `10.42.1.x`.
- `nn4rg` runs pods on `10.42.1.x` and can't communicate with `10.42.2.x`.

### Test

Attempt to access the `longhorn-backend` service from the `longhorn-csi-plugin` on each node.

```
# Executed inside the pod on nn4rg.

longhorn-csi-plugin-h2z28:/ # curl -k longhorn-backend:9500
curl: (28) Failed to connect to longhorn-backend port 9500 after 129625 ms: Couldn't connect to server

longhorn-csi-plugin-h2z28:/ # host longhorn-backend
longhorn-backend.longhorn-system.svc.cluster.local has address 10.43.2.254

longhorn-csi-plugin-h2z28:/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 6a:57:bf:7c:47:d3 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.1.172/24 brd 10.42.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::6857:bfff:fe7c:47d3/64 scope link 
       valid_lft forever preferred_lft forever
```

### Deep dive

- https://pauldally.medium.com/session-affinity-and-kubernetes-proceed-with-caution-8e66fd5deb05
- https://msazure.club/kubernetes-services-and-iptables/
- https://linux.die.net/man/8/iptables

Examining the iptables rules on `nn4rg`, we see the following:

```
root@eweber-v126-worker-9c1451b4-nn4rg:~# iptables -t nat -L

Chain KUBE-SERVICES (2 references)
KUBE-SVC-NQL64TY2T3FWFXFQ  tcp  --  anywhere             10.43.2.254          /* longhorn-system/longhorn-backend:manager cluster IP */ tcp dpt:9500

Chain KUBE-SVC-NQL64TY2T3FWFXFQ (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.42.0.0/16         10.43.2.254          /* longhorn-system/longhorn-backend:manager cluster IP */ tcp dpt:9500
KUBE-SEP-W3Y4QUAIHX5U3K5C  all  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager -> 10.42.1.171:9500 */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-W3Y4QUAIHX5U3K5C side: source mask: 255.255.255.255
KUBE-SEP-N5TYH7GRWXGGDHYU  all  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager -> 10.42.2.150:9500 */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-N5TYH7GRWXGGDHYU side: source mask: 255.255.255.255
KUBE-SEP-W3Y4QUAIHX5U3K5C  all  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager -> 10.42.1.171:9500 */ statistic mode random probability 0.50000000000
KUBE-SEP-N5TYH7GRWXGGDHYU  all  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager -> 10.42.2.150:9500 */

Chain KUBE-SEP-N5TYH7GRWXGGDHYU (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.42.2.150          anywhere             /* longhorn-system/longhorn-backend:manager */
DNAT       tcp  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager */ recent: SET name: KUBE-SEP-N5TYH7GRWXGGDHYU side: source mask: 255.255.255.255 tcp to:10.42.2.150:9500

Chain KUBE-SEP-W3Y4QUAIHX5U3K5C (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.42.1.171          anywhere             /* longhorn-system/longhorn-backend:manager */
DNAT       tcp  --  anywhere             anywhere             /* longhorn-system/longhorn-backend:manager */ recent: SET name: KUBE-SEP-W3Y4QUAIHX5U3K5C side: source mask: 255.255.255.255 tcp to:10.42.1.171:9500
```

During PREROUTING, if a packet is destined for the longhorn-backend ClusterIP (`10.43.2.254`), we jump to the chain that handles load balancing (`KUBE-SVC-NQL64TY2T3FWFXFQ`).

The chain that handles load balancing (`KUBE-SVC-NQL64TY2T3FWFXFQ`) has two kinds of rules:

- The first set of rules are for packets from source IPs that have already been balanced in the last configured number of seconds (10800). If, for example, the source IP is in the `KUBE-SEP-W3Y4QUAIHX5U3K5C` list, we jump to the `KUBE-SEP-W3Y4QUAIHX5U3K5C` chain.
- The second set of rules are for packets from source IPs that have not already been balanced. Probabilities are used to ensure we have an equal chance to jump to any related chain (e.g. `KUBE-SEP-W3Y4QUAIHX5U3K5C`).
  
When we jump to a related chain, we update the associated list with the source IP and then change the destination of the packet to the one configured (e.g. `10.42.2.150`).

The lists are stored in /proc. In this example, packets from `10.42.1.185` are routed to `10.42.1.171` because the source happened to end up in the `KUBE-SEP-W3Y4QUAIHX5U3K5C` list.

```
root@eweber-v126-worker-9c1451b4-nn4rg:~# cat /proc/net/xt_recent/KUBE-SEP-W3Y4QUAIHX5U3K5C
src=10.42.1.185 ttl: 64 last_seen: 4463900565 oldest_pkt: 3 4463900279, 4463900564, 4463900565
```

The attempt at routing from the `longhorn-csi-plugin` pod on `nn4rg` above failed because that pod's source IP address ended up in the wrong list. Its packets were destined for `10.42.2.150`, which we we configured its host not to be able to talk to.

```
root@eweber-v126-worker-9c1451b4-nn4rg:~# grep "" /proc/net/xt_recent/*
/proc/net/xt_recent/KUBE-SEP-N5TYH7GRWXGGDHYU:src=10.42.1.172 ttl: 64 last_seen: 4465135466 oldest_pkt: 5 4465095240, 4465119790, 4465120849, 4465122431, 4465135466
/proc/net/xt_recent/KUBE-SEP-W3Y4QUAIHX5U3K5C:src=10.42.1.185 ttl: 64 last_seen: 4463900565 oldest_pkt: 3 4463900279, 4463900564, 4463900565
```

We can fix the "problem" by removing its entry in the KUBE-SEP-N5TYH7GRWXGGDHYU list and trying again. This time, we happen to load balance to a longhorn-backend pod we can actually talk to (though it's equally likely to end up in the same "bad" list).

```
root@eweber-v126-worker-9c1451b4-nn4rg:~# echo / >/proc/net/xt_recent/KUBE-SEP-N5TYH7GRWXGGDHYU

longhorn-csi-plugin-h2z28:/ # curl -k longhorn-backend:9500
{"data":[{"actions":{},"id":"v1","links":{"self":"http://longhorn-backend:9500/v1"},"type":"apiVersion"}],"links":{"latest":"http://longhorn-backend:9500/v1","self":"http://longhorn-backend:9500/"},"resourceType":"apiVersion","type":"collection"}

root@eweber-v126-worker-9c1451b4-nn4rg:~# grep "" /proc/net/xt_recent/*
/proc/net/xt_recent/KUBE-SEP-W3Y4QUAIHX5U3K5C:src=10.42.1.185 ttl: 64 last_seen: 4463900565 oldest_pkt: 3 4463900279, 4463900564, 4463900565
/proc/net/xt_recent/KUBE-SEP-W3Y4QUAIHX5U3K5C:src=10.42.1.172 ttl: 64 last_seen: 4465265740 oldest_pkt: 1 4465265740
```

### Conclusion

It's fairly easy to understand why tenancy (when set up this way) can cause major problems for Longhorn. It's not 100% clear that removing `sessionAffinity: ClientIP` will allow Longhorn to work normally in this environment. It depends how gracefully we handle connection failures.

- What happens if a `longhorn-csi-plugin` pod fails to contact the `longhorn-backend` service on its first attempt?
- How many times will it retry?
- What happens in the off chance that each time it retries, the Kubernetes network control plane chooses the same backend pod?

**Comment by ejweber** [comment]
We have had `sessionAffinity: ClientIP` on certain services since the first time we ran Longhorn in Kubernetes: https://github.com/longhorn/longhorn/pull/22. There is no discussion in that PR of any particular reason why it would be desirable.

Today we have it in four services:

```
eweber@laptop:~/longhorn> kl get service -oyaml | grep -e "sessionAffinity: ClientIP" -B 6
    - name: admission-webhook
      port: 9502
      protocol: TCP
      targetPort: admission-wh
    selector:
      app: longhorn-manager
    sessionAffinity: ClientIP
--
    - name: manager
      port: 9500
      protocol: TCP
      targetPort: manager
    selector:
      app: longhorn-manager
    sessionAffinity: ClientIP
--
    - name: conversion-webhook
      port: 9501
      protocol: TCP
      targetPort: conversion-wh
    selector:
      app: longhorn-manager
    sessionAffinity: ClientIP
--
    - name: recovery-backend
      port: 9503
      protocol: TCP
      targetPort: recov-backend
    selector:
      app: longhorn-manager
    sessionAffinity: ClientIP
```
