### ISSUE TITLE
[IMPROVEMENT] Reject the creation of encrypted v2 volume in validating webhook

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7404]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Based on https://github.com/longhorn/longhorn/issues/7355, reject the creation of encrypted v2 volume in validating webhook in current implementation.

**Comment by innobead** [comment]
For v2, no need to backport.

**Comment by chriscchien** [comment]
Hi @derekbit ,

When I create a v2 volume with `encrypted: "true"`, the volume will create success but `volume.spec.encrypted` will become `false` without any warning message(no matter from UI or by yaml), and can not find the message "encrypted volume is not supported for backend store driver v2" added in the [PR](https://github.com/longhorn/longhorn-manager/pull/2393/files), not sure if this is acceptable, thank you.


storageclass
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-enc
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn-crypto
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  dataLocality: disabled
  encrypted: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  backendStoreDriver: "v2"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
secrect
```yaml
apiVersion: v1
data:
  CRYPTO_KEY_VALUE: "Your encryption passphrase"
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
```

PVC
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test
  namespace: longhorn-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-enc
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
```
