### ISSUE TITLE
[BUG] Unable to create snapshot: cannot get engine client because it isn't deployed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7438]
## Describe the bug (🐛 if you encounter this issue)

Run test case `test_engine_image_daemonset_restart` Repeatedly. After engine image DaemonSet restarted, even though the engine image `status.conditions[0].status` has become `True`:
```
status:
    buildDate: "2023-12-05T06:21:33+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 9
    conditions:
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-25T09:44:10Z"
      message: Engine image ei-b907910b (longhornio/longhorn-engine:master-head) is
        fully deployed on all ready nodes
      reason: ""
      status: "True"
      type: ready
```
It failed at `create_snapshot` step with error message with reproducibility ~ `20%`:
```
longhorn.ApiError: (ApiError(...), '500 : 
failed to create snapshot: cannot get client for volume longhorn-testvol-rayxu0 on node ip-10-0-2-245: cannot get engine client with image longhornio/longhorn-engine:master-head because it isn\'t deployed\n
{\'code\': 500, \'detail\': \'\', \'message\': "failed to create snapshot: cannot get client for volume longhorn-testvol-rayxu0 on node ip-10-0-2-245: cannot get engine client with image longhornio/longhorn-engine:master-head because it isn\'t deployed", \'status\': 500}')
```

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5560/

Not sure if it's a bug or the test case needs to be refined.

## To Reproduce

Run test case `test_engine_image_daemonset_restart` Repeatedly

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by innobead** [comment]
From master? this should be a transient issue while merging some v2 changes. Let's revisit this issue later after all related PRs are merged.

cc @derekbit @shuo-wu

**Comment by PhanLe1010** [comment]
Hi @yangchiu How did you capture the state of the engine image at the time the test failed?
```
status:
    buildDate: "2023-12-05T06:21:33+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 9
    conditions:
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-25T09:44:10Z"
      message: Engine image ei-b907910b (longhornio/longhorn-engine:master-head) is
        fully deployed on all ready nodes
      reason: ""
      status: "True"
      type: ready
```
