### ISSUE TITLE
[BUG] Delete kubernetes node did not remove `node.longhorn.io` 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7475]
## Describe the bug (🐛 if you encounter this issue)

Delete a kubernetest node which contains replica, did not remove `node.longhorn.io`. `node.longhorn.io` kept in `reason: KubernetesNodeGone` and `status: "False"` even though add back the kubernetes node.

And delete the not ready `node.longhorn.io` rejected by webhook.
```
status:
  autoEvicting: false
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2023-12-28T08:49:48Z"
    message: 'Kubernetes node missing: node ip-172-31-45-203 has been removed from
      the cluster and there is no manager pod running on it'
    reason: KubernetesNodeGone
    status: "False"
    type: Ready
```
```
> k get nodes
NAME               STATUS   ROLES                  AGE     VERSION
ip-172-31-41-5     Ready    control-plane,master   13m     v1.28.2+k3s1
ip-172-31-45-203   Ready    <none>                 2m24s   v1.28.2+k3s1
ip-172-31-40-231   Ready    <none>                 13m     v1.28.2+k3s1
> k get nodes.longhorn.io -n longhorn-system
NAME               READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
ip-172-31-45-203   False   true                            9m16s
ip-172-31-41-5     True    true              True          12m
ip-172-31-40-231   True    true              True          12m
```

Can reproduce in v1.5.3, but not in v1.5.2, in v1.5.2,  `nodes.longhorn.io` deleted immediately after kubernetes node deleted

## To Reproduce

1. Install Longhorn on 3 worker node cluser
2. Create and attach a 3 replicas volume, wait volume healthy
3. Delete 1 of the kubernetes node `kubectl delete node <node name>`
4. Related `nodes.longhorn.io` not deleted and the `Ready status: False`
5. Add back the deleted kubernetes node  the `nodes.longhorn.io` still in not ready status
6. Reboot the added back node. `nodes.longhorn.io` still in not ready status

## Expected behavior

`nodes.longhorn.io` should Ready after the deleted kubermetes node added back.

## Support bundle for troubleshooting
[supportbundle_e68e0970-6a59-4dc2-8b26-d50cb6a66e16_2023-12-28T09-01-45Z.zip](https://github.com/longhorn/longhorn/files/13784915/supportbundle_e68e0970-6a59-4dc2-8b26-d50cb6a66e16_2023-12-28T09-01-45Z.zip)

## Environment

 - Longhorn version: v1.6.0-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.2+k3s1

## Additional context

N/A
