### ISSUE TITLE
[BUG] V2 volume is attached to a node first, the V1 volume will fails to attach.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7511]
## Describe the bug (🐛 if you encounter this issue)

I first created a `V2` volume `vol-0` via the UI and created a pod to mount volume `vol-0`. Then, I created a `V1` volume `vol-1`, and attempted to attach `vol-1` to one of the nodes. However, `vol-1` continuously appears in an 'attaching detaching' loop.

![Recording 2024-01-02 at 17 10 49](https://github.com/longhorn/longhorn/assets/104337648/68a52dc4-fc0a-490d-b7ac-dc8b74b19f48)

```console
Events:
  Type     Reason                Age                   From                        Message
  ----     ------                ----                  ----                        -------
  Normal   Detached              13m                   longhorn-volume-controller  volume vol-1 has been detached
  Normal   Remount               13m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:04:32Z
  Normal   Remount               13m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:04:47Z
  Normal   Remount               12m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:05:03Z
  Normal   Remount               12m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:05:19Z
  Normal   Remount               12m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:05:34Z
  Normal   Remount               12m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:05:50Z
  Normal   Detached              11m (x7 over 13m)     longhorn-volume-controller  volume vol-1 has been detached
  Normal   Remount               11m                   longhorn-volume-controller  Volume vol-1 requested remount at 2024-01-02T09:06:05Z
  Warning  DetachedUnexpectedly  3m26s (x66 over 13m)  longhorn-volume-controller  Engine of volume vol-1 dead unexpectedly, reattach the volume
```

## To Reproduce

1. Create one v2 1Gib volume "vol-0" on longhorn
1. Create volume's PV & PVC from longhorn UI
1. Deploy pod “mypod1” via cli `kubctl apply -f pod_mount_1vol.yaml`

    <details>
    <summary>pod_mount_1vol.yaml</summary>
    
    ```yaml
    kind: Pod
    apiVersion: v1
    metadata:
      name: ubuntu-mountvol0
      namespace: default
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
          - mountPath: "/data/"
            name: vol-0
      volumes:
        - name: vol-0
          persistentVolumeClaim:
            claimName: vol-0
    ```
    </details>

1. Create one v1 1Gib volume `vol-1` on longhorn
1. Attach `vol-1` to one of the nodes

## Expected behavior

`vol-1` should be attached

## Support bundle for troubleshooting

[supportbundle_3a85620c-00d7-4b51-a262-9f58ac9a441c_2024-01-02T09-11-33Z.zip](https://github.com/longhorn/longhorn/files/13808646/supportbundle_3a85620c-00d7-4b51-a262-9f58ac9a441c_2024-01-02T09-11-33Z.zip)

## Environment

 - Longhorn version: `master-head`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.27.8+k3s2`
   - Number of management node in the cluster: `1`
   - Number of worker node in the cluster: `3`
 - Node config
   - OS type and version: `ubuntu 22.04`
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2 t2.xlarge
 - Number of Longhorn volumes in the cluster: 2
 - Impacted Longhorn resources:
   - Volume names: vol-1
