### ISSUE TITLE
[BUG] Remove v2 volume rebuild snapshot could cause volume stuck in detaching/faulted state

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7573]
## Describe the bug

When deleted replicas of an attached v2 volume, detaching the volume is necessary to trigger replica rebuilding. When detached the volume and replica rebuilding triggered, there were some `rebuild-*` snapshots being created:
![rebuild](https://github.com/longhorn/longhorn/assets/5709208/56e66d5c-3942-4d20-a851-1f8d4bb2fc3a)
After the replica rebuilding completed, re-attached the volume, and tried to remove these `rebuild-*` snapshots, the volume could get stuck in detaching/faulted state:
![faulted-2](https://github.com/longhorn/longhorn/assets/5709208/11edb358-94d4-4d4b-99b3-6146f10a9303)

## To Reproduce

1. Create v2 volume environment
2. Create v2 volume `test-1` from UI, and also create PV/PVC for it from UI
3. Create pod to use this volume:
```
cat << EOF > pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
EOF
kubectl apply -f pod.yaml
```
4. write some data to the volume:
```
dd if=/dev/urandom of=/data/test-1 bs=3M count=1024
```
5. delete replicas of this volume from UI
6. detach the volume to trigger replica rebuilding
```
kubectl delete -f pod.yaml
```
7. replica rebuilding triggered, and there are some `rebuild-*` snapshots created
8. re-attach the volume by:
```
kubectl apply -f pod.yaml
```
9. try to remove `rebuild-*` snapshots from UI
10. volume could get stuck in detaching/faulted state

## Support bundle for troubleshooting

[supportbundle_cbabf3df-d2bb-4981-b527-0ebf65b49c6a_2024-01-08T02-01-38Z.zip](https://github.com/longhorn/longhorn/files/13855732/supportbundle_cbabf3df-d2bb-4981-b527-0ebf65b49c6a_2024-01-08T02-01-38Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager a601b9b)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->
