### ISSUE TITLE
[BUG] Deleting instance-manager pod causes v2 volume stuck in attaching/detaching loop

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7579]
## Describe the bug

Deleting instance-manager pod of the node which a v2 volume attached to will cause the v2 volume stuck in attaching/detaching loop.

## To Reproduce

1. Create v2 volume environment
2. Create a v2 volume `test-1` with 3 replicas from UI and also create PV/PVC for it from UI
3. Create a pod for it:
```
cat << EOF > pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
EOF
kubectl apply -f pod.yaml
```
4. Delete the instance-manager pod of the node which the volume attached to:
```
# the volume attached to ip-10-0-1-91
# instance-manager-5da32a419628abfbb1c6417858beb92c   1/1     Running   0             4m2s    10.42.1.41   ip-10-0-1-91    <none>
$ kubectl delete pod instance-manager-5da32a419628abfbb1c6417858beb92c -n longhorn-system
```
5. The instance-manager will be recreated and running, but the volume gets stuck in attaching/detaching loop:
![att](https://github.com/longhorn/longhorn/assets/5709208/6b0dddb3-64da-4b25-bd5e-e11eb7758ad6)
![de](https://github.com/longhorn/longhorn/assets/5709208/47bb7d41-72f5-4965-afc7-fd8a80a3a673)

## Support bundle for troubleshooting

[supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T05-50-15Z.zip](https://github.com/longhorn/longhorn/files/13856613/supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T05-50-15Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager a601b9b)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1 
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3 
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->
