### ISSUE TITLE
[IMPROVEMENT] Increase the hugepage size for spdk_tgt to 2GiB

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7606]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

To address some feedback from uses and increase better UX, increase the hugepage size for spdk_tgt to 2GiB.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn `d918ad`)

Setup v2 engine environment by [instructions](https://longhorn.io/docs/1.6.0/spdk/quick-start/) and then install longhorn by both kubectl and helm, after longhorn ready, all nodes have `hugepages-2Mi: 2Gi` value in `status.capacity` and `status.allocatable`

```
status:
  addresses:
  - address: 172.31.47.74
    type: InternalIP
  - address: ip-172-31-47-74
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "98672037811"
    hugepages-1Gi: "0"
    hugepages-2Mi: 2Gi
    memory: 14268920Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 101430960Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: 2Gi
    memory: 16366072Ki
    pods: "110"
```
```
> kubectl get node -o yaml | grep huge
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
      hugepages-1Gi: "0"
      hugepages-2Mi: 2Gi
```
