### ISSUE TITLE
Volume Attaching Timeout - Failed to attache

### ISSUE THREAD

**Issue by aljabertareq** [longhorn/longhorn#7629]
## Describe the bug

Volume attaching timeout. Kakfa and Minio instances failed to attaché. 

## Environment

 - Longhorn version: 1.4.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s v1.23.5
   - Number of control plane nodes in the cluster: 2
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 20.04.6 LTS
   - Kernel version: 5.4.0-166-generic
   - CPU per node: 96 and 128 for 2 nodes
   - Memory per node: 33 and 40 for 2 nodes
   - Disk type (e.g. SSD/NVMe/HDD): One node is HDD and the other one is SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 17

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by aljabertareq** [comment]
@derekbit Can you please help? It took us 3 hours to get this up and running.

**Comment by derekbit** [comment]
@aljabertareq 
Would you be able to provide a support bundle for further investigation? Thank you.

cc @james-munson for the community coordinator of this sprint

**Comment by james-munson** [comment]
Just to be clear, it did eventually attach, correct?  The issue is about the time it took?
The volumes.yaml shows that volume as attached:
``` yaml
    currentNodeID: node1
      expansionRequired: false
      frontendDisabled: false
      isStandby: false
      kubernetesStatus:
        lastPVCRefAt: "null"
        lastPodRefAt: "null"
        namespace: avs
        pvName: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
        pvStatus: Bound
        pvcName: minio-pv-claim-cloned
        workloadsStatus:
          - podName: minio-6dd56bd767-qp67r
            podStatus: Running
            workloadName: minio-6dd56bd767
            workloadType: ReplicaSet
      lastBackup: "null"
      lastBackupAt: "null"
      lastDegradedAt: "null"
      ownerID: node1
      pendingNodeID: "null"
      remountRequestedAt: "2024-01-10T22:17:01Z"
      restoreInitiated: false
      restoreRequired: false
      robustness: healthy
      shareEndpoint: "null"
      shareState: "null"
      state: attached
```
And cluster/storage.k8s.io/v1/volumeattachments.yaml shows it attached as well:
```yaml
  - apiVersion: storage.k8s.io/v1
    kind: VolumeAttachment
    metadata:
      annotations:
        csi.alpha.kubernetes.io/node-id: node1
      creationTimestamp: "2024-01-10T21:59:34Z"
      finalizers:
        - external-attacher/driver-longhorn-io
      managedFields:
...
      name: csi-baef1bd4fbd4f963e849e1345359e542eaf2bab7a7e33135f546f14a7d9a5949
      resourceVersion: "124700040"
      uid: 3a412db5-daaa-43bf-9f67-39302c839d46
    spec:
      attacher: driver.longhorn.io
      nodeName: node1
      source:
        persistentVolumeName: pvc-e9b4c5e1-1c5d-4428-bd0e-a02167136cbf
    status:
      attached: true
```

By the way, the volume also shows:
```yaml
      numberOfReplicas: 1
```
which is a dangerous way to operate.
