### ISSUE TITLE
[BUG] Longhorn deploys pods on Windows nodes when installed with Helm

### ISSUE THREAD

**Issue by ehemmerlin** [longhorn/longhorn#7656]
## Describe the bug

When installing Longhorn with Helm, some pods are deployed on Windows nodes, even if node selector is specified to target only Linux nodes.

## To Reproduce

On a Kubernetes cluster composed of Linux and Windows nodes, deploy Longhorn with Helm.

## Expected behavior

Longhorn deployed on Linux nodes.

## Environment

 - Longhorn version: v1.5.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: On-prem
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3 Linux and 2 Windows
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VSphere VM
 - Number of Longhorn volumes in the cluster: 14

**Comment by doctorpangloss** [comment]
These `patchesStrategicMerge` resolve the issue. It's not related to being installed with helm. The controllers just have to add these resources with nodeselectors.
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-attacher
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app: csi-attacher
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-provisioner
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app: csi-provisioner
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-resizer
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app: csi-resizer
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-snapshotter
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app: csi-snapshotter
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-csi-plugin
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app: longhorn-csi-plugin
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: engine-image-ei-b907910b
  namespace: longhorn-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-b907910b
  template:
    metadata:
      labels:
        app: engine-image-ei-b907910b
    spec:
      nodeSelector:
        kubernetes.io/os: linux
```
