### ISSUE TITLE
[FEATURE] Longhorn block-type disks supports different SPDK disk bdev drivers

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7672]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, Longhorn block-type disks rely on SPDK AIO bdev driver. However, AIO bdev driver does not support UNMAP operation ([codes](https://github.com/longhorn/spdk/blob/longhorn/module/bdev/aio/bdev_aio.c#L520-L532)), and hence trimming filesystem on a v2 volume is infeasible.

To support filesystem feature, a disk can be managed by [NVMe bdev](https://github.com/longhorn/spdk/blob/longhorn/module/bdev/nvme/bdev_nvme.c#L2571) for a NVMe device or [Virtio Block](https://github.com/longhorn/spdk/blob/longhorn/module/bdev/virtio/bdev_virtio_blk.c#L224) for a virtio device.
Ref: https://spdk.io/doc/bdev.html

- [x] Support bind, unbind, disk-status, disk-driver commands in spdk setup.sh
- [x] Support disk management by SPDK NVMe or virtio bdev 
- [x] Document update

**Comment by derekbit** [comment]
@innobead  Can I pick up the ticket?

**Comment by innobead** [comment]
100% go ahead to take it! @derekbit

**Comment by roger-ryao** [comment]
I encountered the issue https://github.com/longhorn/longhorn/issues/8846, so I could not verify this ticket.

Test Steps for Clearer Verification

1. Verify the detection of **VirtIO** disk
    1. Get the BDF of the disk by `ls -al /sys/block`
    ```
    # lsblk 
    vda                 252:0    0    50G  0 disk 
    ├─vda1              252:1    0     1M  0 part 
    ├─vda2              252:2    0     2G  0 part /boot
    └─vda3              252:3    0    48G  0 part 
      └─ubuntu--vg-ubuntu--lv
                        253:0    0    48G  0 lvm  /var/lib/kubelet/pods/e864c8e7-c552-4082-9788-158e0937625d/volume-subpaths/admin-kubeconfig/proxy/0
                                                  /var/lib/kubelet/pods/e864c8e7-c552-4082-9788-158e0937625d/  volume-subpaths/user-kubeconfig/helm/1
                                                  /
    vdb                 252:16   0    20G  0 disk

    # ls -al /sys/block/
    lrwxrwxrwx  1 root root 0 Jun 28  2024 vda -> ../devices/pci0000:00/0000:00:02.4/0000:05:00.0/virtio3/block/vda
    lrwxrwxrwx  1 root root 0 Jun 28  2024 vdb -> ../devices/pci0000:00/0000:00:02.5/0000:06:00.0/virtio4/block/vdb

    ```
    2. Add the disk to `node.spec.disks`
    `kubuctl -n longhorn-system edit nodes.longhorn.io w1`


    ```yaml
        default-disk-block-1:
          allowScheduling: true
          diskDriver: auto
          diskType: block
          evictionRequested: false
          path: 0000:00:02.5
          storageReserved: 0
          tags: []
    ```

2. Verify the detection of **NVMe** disk
   ```sh
       ip-10-0-2-210:/home/ec2-user # lsblk
        NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
        nvme0n1     259:0    0   100G  0 disk 
        ├─nvme0n1p1 259:2    0     2M  0 part 
        ├─nvme0n1p2 259:3    0    20M  0 part /boot/efi
        └─nvme0n1p3 259:4    0   100G  0 part /
        nvme1n1     259:1    0 186.3G  0 disk /var/lib/longhorn
                                              /opt/local-path-provisioner
                                              /mnt/sda1

        ip-10-0-2-46:/home/ec2-user # ls -al /sys/block
        total 0
        drwxr-xr-x  2 root root 0 Jun 28 02:35 .
        dr-xr-xr-x 13 root root 0 Jun 28 02:35 ..
        lrwxrwxrwx  1 root root 0 Jun 28 02:35 nvme0n1 -> ../devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
        lrwxrwxrwx  1 root root 0 Jun 28 02:35 nvme1n1 -> ../devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1
    ```

    2. Add the disk to `node.spec.disks`
    `kubuctl -n longhorn-system edit nodes.longhorn.io w1`


    ```yaml
        default-disk-block-1:
          allowScheduling: true
          diskDriver: auto
          diskType: block
          evictionRequested: false
          path: 0000:00:1f.0
          storageReserved: 0
          tags: []
    ```

3. Verify disk driver aio
    Ref. https://longhorn.io/docs/1.7.0/v2-data-engine/quick-start/

**Comment by roger-ryao** [comment]
Hi @derekbit :
     I failed to detect the `NVMe` disk / `VirtIO` disk, could you help me confirm if it’s a configuration error on my part or an actual issue?

**Verified on master-head 20240701**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/765a34927cc54f3af5a0c6d0acb2690ed053fa03
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/ce53ab12b56448e3dbadf37bd92fd0f5e2ad11e7
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/73cc005a5a22204486c4522606a16daaee7137d4
- go-common-libs `main` https://github.com/longhorn/go-common-libs/commit/d78642cff5e1e810d919ba3db2698a4acff59a99
- longhorn-spdk-engine `main` https://github.com/longhorn/longhorn-spdk-engine/commit/c2002ae0216ff14f4b54cb2ba9649dd2ac41396a
- go-spdk-helper `main` https://github.com/longhorn/go-spdk-helper/commit/99b2a18336b501ab46bcf47772e568965b6d0b2c
- spdk `longhorn-1.6` https://github.com/longhorn/spdk/commit/7a6125fda83e0b8ad0ca22d99f6f3b0e96302691

**The test steps**
https://github.com/longhorn/longhorn/issues/7672#issuecomment-1956174494

**Result**
I failed to detect the NVMe disk / VirtIO disk
```
root@ryao-test-w1-b2e0a61d-dhjlv:/home/ubuntu# ls -al /sys/block
total 0
lrwxrwxrwx  1 root root 0 Jul  1 03:28 nvme0n1 -> ../devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
lrwxrwxrwx  1 root root 0 Jul  1 03:28 nvme1n1 -> ../devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1
```

```
root@ryao-test-w1-b2e0a61d-dhjlv:/home/ubuntu# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0          7:0    0  24.4M  1 loop /snap/amazon-ssm-agent/6312
loop1          7:1    0  55.6M  1 loop /snap/core18/2745
loop2          7:2    0  63.3M  1 loop /snap/core20/1879
loop3          7:3    0 111.9M  1 loop /snap/lxd/24322
loop4          7:4    0  53.2M  1 loop /snap/snapd/19122
loop5          7:5    0    20G  0 loop 
loop6          7:6    0     4G  0 loop 
nvme1n1      259:0    0 186.3G  0 disk 
nvme0n1      259:1    0   100G  0 disk 
├─nvme0n1p1  259:2    0  99.9G  0 part /
├─nvme0n1p14 259:3    0     4M  0 part 
└─nvme0n1p15 259:4    0   106M  0 part /boot/efi

```

**error message**
```
Last Transition Time: 39 minutes ago
Message: Disk disk-1(0000:00:1f.0) on node ryao-test-w1-b2e0a61d-dhjlv is not ready: failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Unknown desc = failed to get disk driver for disk disk-1: failed to get disk status for BDF 0000:00:1f.0: failed to extract JSON from output: 0000:00:04.0 (1d0f 8061): Active devices: mount@nvme0n1:nvme0n1p1,mount@nvme0n1:nvme0n1p15, so not binding PCI dev
Reason: NoDiskInfo
Status: False
```
Support bundle
[supportbundle_e6e41a98-75c1-44a1-93ef-9f43052c116b_2024-07-01T05-47-06Z.zip](https://github.com/user-attachments/files/16048479/supportbundle_e6e41a98-75c1-44a1-93ef-9f43052c116b_2024-07-01T05-47-06Z.zip)

**Comment by derekbit** [comment]
`spdk/script/setup.sh` is broken after upgrading to longhorn-v24.05...

**Comment by roger-ryao** [comment]
## Test Steps to Verify the Detection of NVMe Disk with Ubuntu 24.04 AMI (ami-0cf2b4e024cdb6960)

### 1. Create a Longhorn Cluster Using AWS EC2 `c5d.2xlarge` Machines with an NVMe Disk

**Command to List Block Devices:**
```sh
root@ryao-test-24-w3-81ccd9ae-9gm9j:/home/ubuntu# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0          7:0    0  55.7M  1 loop /snap/core18/2812
loop1          7:1    0  25.2M  1 loop /snap/amazon-ssm-agent/7983
loop2          7:2    0  38.7M  1 loop /snap/snapd/21465
loop3          7:3    0    20G  0 loop 
nvme1n1      259:0    0 186.3G  0 disk 
nvme0n1      259:1    0   100G  0 disk 
├─nvme0n1p1  259:2    0    99G  0 part /
├─nvme0n1p14 259:3    0     4M  0 part 
├─nvme0n1p15 259:4    0   106M  0 part /boot/efi
└─nvme0n1p16 259:5    0   913M  0 part /boot

### 2. Enable v2 Data Engine

### 3. Get the BDF of the Disk

```sh
root@ryao-test-24-w3-81ccd9ae-9gm9j:/home/ubuntu# ls -al /sys/block/
lrwxrwxrwx  1 root root 0 Jul  1 07:07 loop7 -> ../devices/virtual/block/loop7
lrwxrwxrwx  1 root root 0 Jul  1 07:07 nvme0n1 -> ../devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
lrwxrwxrwx  1 root root 0 Jul  1 07:07 nvme1n1 -> ../devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1
```

### 4. Add the Disk to node.disks

```yaml
disk-1:
  allowScheduling: true
  diskDriver: auto
  diskType: block
  evictionRequested: false
  path: 0000:00:1f.0
  storageReserved: 0
  tags: []
```

### 5. Check the node.status.diskStatus

```yaml
disk-1:
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2024-07-01T07:30:30Z"
    message: |
      Disk disk-1(0000:00:1f.0) on node ryao-test-24-w1-7595aee4-js2c6 is not ready: failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Unknown desc = failed to get disk driver for disk disk-1: failed to get disk status for BDF 0000:00:1f.0: failed to extract JSON from output: 0000:00:04.0 (1d0f 8061): Active devices: mount@nvme0n1:nvme0n1p1,mount@nvme0n1:nvme0n1p15,mount@nvme0n1:nvme0n1p16, so not binding PCI dev
    reason: NoDiskInfo
    status: "False"
    type: Ready
  - lastProbeTime: ""
    lastTransitionTime: "2024-07-01T07:30:30Z"
    message: Disk disk-1 (0000:00:1f.0) on the node ryao-test-24-w1-7595aee4-js2c6
      is not ready
    reason: DiskNotReady
    status: "False"
    type: Schedulable

```

![Screenshot_20240701_153707](https://github.com/longhorn/longhorn/assets/104337648/dc7670c0-2f7f-4c93-8b74-3a7492a99cc4)

**Comment by derekbit** [comment]
> `spdk/script/setup.sh` is broken after upgrading to longhorn-v24.05...

The update in the upstream causes the issue. I will check it.
cc @DamiaSan

**Comment by derekbit** [comment]
@roger-ryao ready for testing. It is fixed in https://github.com/longhorn/spdk/commit/a6478cde7e0cff2fb09992868308a7387aa5202a

**Comment by roger-ryao** [comment]
**Verified on master-head 20240702**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/765a34927cc54f3af5a0c6d0acb2690ed053fa03
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/ce53ab12b56448e3dbadf37bd92fd0f5e2ad11e7
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/73cc005a5a22204486c4522606a16daaee7137d4
- go-common-libs `main` https://github.com/longhorn/go-common-libs/commit/d78642cff5e1e810d919ba3db2698a4acff59a99
- longhorn-spdk-engine `main` https://github.com/longhorn/longhorn-spdk-engine/commit/c2002ae0216ff14f4b54cb2ba9649dd2ac41396a
- go-spdk-helper `main` https://github.com/longhorn/go-spdk-helper/commit/99b2a18336b501ab46bcf47772e568965b6d0b2c
- spdk `longhorn-v24.05` https://github.com/longhorn/spdk/commit/a6478cde7e0cff2fb09992868308a7387aa5202a

**The test steps**
https://github.com/longhorn/longhorn/issues/7672#issuecomment-2196463534

**Result Passed**

- [x] 1. Verify the detection of **VirtIO** disk
- [x] 2. Verify the detection of **NVMe** disk
- [x] 3. Verify disk driver **aio**

```yaml
     disk-8:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-07-02T08:55:32Z"
          message: Disk disk-8(/dev/loop3) on node ryao-master-w3-2e5975a5-88vmf is
            ready
          reason: ""
          status: "True"
          type: Ready
        - lastProbeTime: ""
          lastTransitionTime: "2024-07-02T08:55:32Z"
          message: Disk disk-8(/dev/loop3) on node ryao-master-w3-2e5975a5-88vmf is
            schedulable
          reason: ""
          status: "True"
          type: Schedulable
        diskDriver: aio
        diskName: disk-8
        diskPath: /dev/loop3
        diskType: block
        diskUUID: 1e995e68-512b-4e16-9c39-9b7323587bcf
        filesystemType: ""
        instanceManagerName: instance-manager-70555e5a4cb268c931ccebb4751e78a7
        scheduledReplica: {}
        storageAvailable: 21286092800
        storageMaximum: 21389901824
        storageScheduled: 0
      disk-9:
        conditions:
        - lastProbeTime: ""
          lastTransitionTime: "2024-07-02T09:00:32Z"
          message: Disk disk-9(0000:00:1f.0) on node ryao-master-w3-2e5975a5-88vmf
            is ready
          reason: ""
          status: "True"
          type: Ready
        - lastProbeTime: ""
          lastTransitionTime: "2024-07-02T09:00:32Z"
          message: Disk disk-9(0000:00:1f.0) on node ryao-master-w3-2e5975a5-88vmf
            is schedulable
          reason: ""
          status: "True"
          type: Schedulable
        diskDriver: nvme
        diskName: disk-3n1
        diskPath: 0000:00:1f.0
        diskType: block
        diskUUID: eae57130-dacb-4868-92b8-58d74b1382f8
        filesystemType: ""
        instanceManagerName: instance-manager-70555e5a4cb268c931ccebb4751e78a7
        scheduledReplica: {}
        storageAvailable: 199124582400
        storageMaximum: 199216857088
        storageScheduled: 0

    disk-2:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2024-07-02T10:30:10Z"
        message: Disk disk-2(0000:06:00.0) on node w2 is ready
        reason: ""
        status: "True"
        type: Ready
      - lastProbeTime: ""
        lastTransitionTime: "2024-07-02T10:30:10Z"
        message: Disk disk-2(0000:06:00.0) on node w2 is schedulable
        reason: ""
        status: "True"
        type: Schedulable
      diskDriver: virtio-blk
      diskName: disk-2
      diskPath: "0000:06:00.0"
      diskType: block
      diskUUID: 2ff33ec9-040a-4888-bb10-e777eeaa45d6
      filesystemType: ""
      instanceManagerName: instance-manager-90ba8efa65287c9ab398d99db79cd6de
      scheduledReplica:
        vol-0-r-ae05dad3: 2147483648
      storageAvailable: 21181235200
      storageMaximum: 21389901824
      storageScheduled: 2147483648

```
