### ISSUE TITLE
[BUG] Toleration not being applied to engine-image and csi-plugin

### ISSUE THREAD

**Issue by fmunteanu** [longhorn/longhorn#7677]
## Describe the bug

When applying tolerations to `longhornDriver` and `longhornManager` into helm chart, they are not automatically added to `engine-image` and `csi-plugin` DaemonSets, which should be default behaviour.

## To Reproduce

Control plane nodes are tainted with `node-role.kubernetes.io/master=true:NoSchedule`, helm chart settings:

```
          longhornDriver:
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Equal
                value: 'true'
                effect: NoSchedule
          longhornManager:
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Equal
                value: 'true'
                effect: NoSchedule
```

## Expected behavior

Tolerations should also be applied to `engine-image` and `csi-plugin` DaemonSets.

## Environment

 - Longhorn Helm chart version: v1.5.3
 - Impacted volume (PV): Non related
 - Installation method: Helm
 - Kubernetes distro and version: K3s v1.29.0+k3s1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.04.3 arm64
   - Kernel version: 5.15.0-1044-raspi
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type): SSD
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure: Baremetal
 - Number of Longhorn volumes in the cluster: 3
