### ISSUE TITLE
[BUG] Negative test case failed: Stop Volume Node Kubelet For More Than Pod Eviction Timeout While Workload Heavy Writing

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7694]
## Describe the bug

During negative test case `Stop Volume Node Kubelet For More Than Pod Eviction Timeout While Workload Heavy Writing` executing, after stopped kubelet (k3s-agent) service on the volume attached node for more than pod eviction timeout, the workload pod gets stuck in `Terminating` state forever.

```
NAME                     READY   STATUS        RESTARTS   AGE   IP           NODE            NOMINATED NODE   READINESS GATES
longhorn-test-minio      1/1     Running       0          15h   10.42.3.3    ip-10-0-2-97    <none>           <none>
test-statefulset-rwo-0   0/1     Terminating   0          15h   10.42.2.25   ip-10-0-2-238   <none>           <none>
```

```
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
pod-data-test-statefulset-rwo-0   Bound    pvc-dc8e8f17-dce7-4ad4-a806-5e959242a068   3Gi        RWO            longhorn-test   15h
```

The test step is like:
```
1. Create statefulset with rwo volume
2. Keep writing data to statefulset
3. Stop volume node kubelet of statefulset for 360 seconds
4. Wait for volume of statefulset healthy
5. Wait for statefulset stable
6. Check statefulset works
```

Currently it's stuck in step 5: `Wait for statefulset stable`: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/150/consoleFull

Lots of error messages in kubelet logs of node `ip-10-0-2-238`. Please see the attached support bundle.

## To Reproduce

Run negative test case `Stop Volume Node Kubelet For More Than Pod Eviction Timeout While Workload Heavy Writing`

## Support bundle for troubleshooting

[supportbundle_04d0770c-250f-4473-89d3-4b12e7540e8a_2024-01-16T03-35-21Z.zip](https://github.com/longhorn/longhorn/files/13945455/supportbundle_04d0770c-250f-4473-89d3-4b12e7540e8a_2024-01-16T03-35-21Z.zip)

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURVek1qSTBPVEl3SGhjTk1qUXdNVEUxTVRJME1UTXlXaGNOTXpRd01URXlNVEkwTVRNeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURVek1qSTBPVEl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSWWRySWwwSGJ0VzhsZTRVVWY3bnBFYXZMaWdUSUVHQWlWdEdlSFp3K08KTUNRc0lSeG9sWFV2a3p3ekpOWkNuZ2lSckFhWHA0WS9uZUhsSE1xMWxFbEdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUdZYk1iTnRvRzV2Mzl4WW5td1ZOCmo5aEpmREV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnUUpTcUNWTG4wREo2TEc0RVN6REZ4RkZUTHcrWU0vQ1QKcU8vZXFVdUFyVVFDSVFEeE5EV09rRlpRNndZT3lIRllWRCsyZ0NZNWozcEpYc1cxMENPVlBUcEZoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.169.50.92:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJUWU2MTdHZ1Q3Smd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekExTXpJeU5Ea3lNQjRYRFRJME1ERXhOVEV5TkRFek1sb1hEVEkxTURFeApOREV5TkRFek1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJamVmN1FuMU5pWnBVN0MKK2ExeFdoaEFhK3pRbHZ4WlFuK3VjM1Y4M1FjOXdVMXlyRDRFVlF0WUFDZzJlTityYnZHakZYd2hLUEU1ZFBqQgpPdUtFd2tHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU1FpM205K1Q5aCt3RHBEME9xYklGNzhudW9KREFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXZDT3lJbXMzR1BKTHJ3Vm5Rb3BHbzU4bHVhRHU0SHBHUFRRdS9xbVU3bzhDSVFEZjNOSzlIRGZzUERJSgpUeTQ0MGg5dzlwaGVZZlh0cnFUMWV4V21CYmI3QVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM01EVXpNakkwT1RJd0hoY05NalF3TVRFMU1USTBNVE15V2hjTk16UXdNVEV5TVRJME1UTXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM01EVXpNakkwT1RJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVHEwUkVnOGE4V3VjZlpsZUQrcm9rTmMzdlpZU3ZGV3VtNExXcmpXWEVJCjhyZ2VjZWV2dXRsclRZei9LWVpWeGpUNFdqZHRDelhWNUQwa05WUHhtT3BRbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVrSXQ1dmZrL1lmc0E2UTlEcW15QgplL0o3cUNRd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFJUlpQcjNYYWdwRjRtWEQ0S2c3VVlyYkFZTGtJekkzCktWaW5TQlVzVmlWR0FpRUF4a3dzMVA3bUlmRUppdHZWYTNnRWFlU1Jmci95SjV1Y1pQbFE2anE2QmRVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlFUkxDcDRpRFZSVnRZdHhGOWVsbzJWSFR4MmFWdm40aFltVExMME1yb3VvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaU41L3RDZlUySm1sVHNMNXJYRmFHRUJyN05DVy9GbENmNjV6ZFh6ZEJ6M0JUWEtzUGdSVgpDMWdBS0RaNDM2dHU4YU1WZkNFbzhUbDArTUU2NG9UQ1FRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
