### ISSUE TITLE
[BUG][v1.6.0-rc1] Negative test case failed: Reboot Node One By One While Workload Heavy Writing

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7695]
## Describe the bug

During negative test case `Reboot Node One By One While Workload Heavy Writing` executing, after rebooted worker nodes one by one, a volume gets stuck in `Attached/Unknown` state unable to recover:
![unknown1](https://github.com/longhorn/longhorn/assets/5709208/791795eb-fa73-45ab-99c9-b9f8d0aa9737)

![unknown2](https://github.com/longhorn/longhorn/assets/5709208/bd2564b4-3983-4945-96b6-f7869d1cfec9)

The test step is like:
```
Create deployment 0 with rwo volume
Create deployment 1 with rwx volume
Create deployment 2 with rwo and strict-local volume
Create statefulset 0 with rwo volume
Create statefulset 1 with rwx volume
Create statefulset 2 with rwo and strict-local volume

Keep writing data to deployment 0
Keep writing data to deployment 1
Keep writing data to deployment 2
Keep writing data to statefulset 0
Keep writing data to statefulset 1
Keep writing data to statefulset 2

Reboot node 0
Reboot node 1
Reboot node 2
Wait for longhorn ready

Check deployment 0 works
Check deployment 1 works
Check deployment 2 works
Check statefulset 0 works
Check statefulset 1 works
Check statefulset 2 works
```

After rebooted all worker nodes, there is a workload unable to recover:
```
test-deployment-rwo-7f4687c9b-pcmz9                 0/1     ContainerCreating   0             14h
```
Because its volume got stuck in `Unknown` state:
```
pvc-caadd40f-9ffc-4def-bc0b-e335606deb5f   v1            attached   unknown                  3221225472   ip-10-0-2-246   14h
```

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/151/console

## To Reproduce

Run negative test case `Reboot Node One By One While Workload Heavy Writing`

## Support bundle for troubleshooting

[supportbundle_3f1de6b6-8752-45ad-ba5a-470fb559e0c4_2024-01-16T03-34-40Z.zip](https://github.com/longhorn/longhorn/files/13945560/supportbundle_3f1de6b6-8752-45ad-ba5a-470fb559e0c4_2024-01-16T03-34-40Z.zip)

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): v1.27.1+k3s1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURVek1qTTNOelF3SGhjTk1qUXdNVEUxTVRNd01qVTBXaGNOTXpRd01URXlNVE13TWpVMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURVek1qTTNOelF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSS0N3YVZPM2ZjMFU4UGNWdE8xSmtFSVMzZWRXSWtwOTVVcHJLTmlJaUgKUzM5YVhLbjBvWlJ1WGtDd2gxRHRENlJPVXhQOVJWTjl5aUJtQmN4VE02bitvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTNia2ZjRm9POG9mMFU2Tkd1eTR2CjBWWmozWTB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUljVTQ1bFpDcmdVL3BURWQ5MkwzSlhXRmMya0c4THoKMU12V2xmamI1ZlY0QWlCdmtEWEZ3SG0ydkwvdHlYNjRLbGMrdW1VdW1ZVERaN05aZkZqSmpMLzIwQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.203.53.21:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJTG9rREJua01jeWd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekExTXpJek56YzBNQjRYRFRJME1ERXhOVEV6TURJMU5Gb1hEVEkxTURFeApOREV6TURJMU5Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMUEgwVFprYW5Vd0JNVFUKTEFuQVR1dlMyYTBNN1VySzJOK2syVGxqS01Rd21Gd2R6T2hHS09SaEI2eTVueFdOaUVYUGVlSU1hTEVOeXUyKwpMRE1yL2NpalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU0tKU2NXb2xiZm1GTXNoY0IwRENOQ0hpMDJJakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTl4YmdTbUkvZWRidUVycUR2L2xRN1VoNVVKdVNic0ZJS1RQR2c5bi9XdThDSVFEdmFvVWR1YmRHSENDaQpZcTBOTFhZeENaU2FIcVRyZ25jaE1DNTR1VTZVNUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM01EVXpNak0zTnpRd0hoY05NalF3TVRFMU1UTXdNalUwV2hjTk16UXdNVEV5TVRNd01qVTAKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM01EVXpNak0zTnpRd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUnhXRW43bFpJOWxxWCtUY3RFTURQdVZvT1lSamE2OFRrRjRtSkE4emR6Cjd5cW05YWo2NzNJR2szSnRGSjUybnVhTGhZM1NSTFh2Qi9YUCs0MElablhubzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVpaVVuRnFKVzM1aFRMSVhBZEF3agpRaDR0TmlJd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNdWhCN0VhN25haXRBamZteGVEQ3ZNdjZQUmQ3N3paCkRtVUllaEtYRUtFUkFpQTZ3QS9Jck4va0hTN0NGbVZKdmNvUklnUDNCNXhGUVZTbk1tMU9PamVWeXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUM4SUpCb3o0OFErUm5heUxqeW9Ra0ZxZkZvdWUxWXJNdmgxUm9iaUFld1ZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFczhmUk5tUnFkVEFFeE5Rc0NjQk82OUxaclF6dFNzclkzNlRaT1dNb3hEQ1lYQjNNNkVZbwo1R0VIckxtZkZZMklSYzk1NGd4b3NRM0s3YjRzTXl2OXlBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
