### ISSUE TITLE
[BUG] Host machine is somehow reboot when running into IO timeout

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7697]
## Describe the bug

spdk raid bdev is exported as a block device by nvme-tcp. If the nvme initiator lost its target, the error message is constantly printed
```
[  623.190380] nvme nvme5: queue 15: timeout request 0x6f type 4
[  623.190411] block nvme5n1: no usable path - requeuing I/O
```
After 600 seconds (default --ctrl-loss-tmo value of  nvme connect ), the host machine is somehow reboot itself.

The issue is related to linux Kernel, and it is gone in `6.5.0-14-generic` and `5.19.0-50-generic`.

## To Reproduce

1. Create a c3.small.x86 machine with Ubuntu 22.04 on Equinix
2. Install rke2
3. Deploy LH with v2-data-engine enabled
4. Create v2 volumes and workloads by
```
#!/bin/bash

for i in {1..10}; do
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stress-ng-pvc-${i}
  namespace: default
spec:
  storageClassName: longhorn-v2-data-engine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-ng-${i}
spec:
  restartPolicy: Always
  containers:
  - name: stress-ng
    image: docker.io/derekbit/volume-stressor:latest
    env:
      - name: HDD
        value: "1"
      - name: HDD_BYTES
        value: "2G"
      - name: TEMP_PATH
        value: "/data"
    volumeMounts:
    - name: stress-ng-vol-${i}
      mountPath: /data
  volumes:
  - name: stress-ng-vol-${i}
    persistentVolumeClaim:
      claimName: stress-ng-pvc-${i}
EOF
done
```
5. Host will be automatically reboot after 600 seconds.

 

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
