### ISSUE TITLE
[BUG] Specifying "default-data-path" before installation does not work

### ISSUE THREAD

**Issue by PowerfooI** [longhorn/longhorn#7698]
## Describe the bug

I specified a custom `default-data-path` in `longhorn-default-setting` ConfigMap before installing longhorn, but it did not work. Longhorn still took `/var/lib/longhorn` as default path, while the space of device that mounted as `/` is small which can not fit the pods' requirements.

## To Reproduce

1. Follow the doc [Customizing default settings](https://longhorn.io/docs/1.5.3/advanced-resources/deploy/customizing-default-settings/#using-helm)
2. Fetch [deploy/longhorn.yaml](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml) to local file
3. Modify `default-data-path` in `longhorn-default-setting` like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.5.3
data:
  default-setting.yaml: |-
    default-data-path: /home/fake.user/longhorn
```
4. Apply the local `longhorn.yaml` with kubectl

## Expected behavior

Longhorn uses coustomized `default-data-path` to store replicas.

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s, v1.28.5+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: Alibaba Group Enterprise Linux Server 7.2 (Paladin)
   - Kernel version: 4.9.151-015.ali3000.alios7.x86_64
   - CPU per node: 22
   - Memory per node: 134
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): -

## Additional context

I had searched all manifests and did not find any pod that used the cm `longhorn-default-setting` as volume. How can the configurations in the configmap be used by longhorn? Thanks for checking the issue!

<img width="909" alt="image" src="https://github.com/longhorn/longhorn/assets/26134111/2d75c776-4209-4dc3-8b38-89c42da6b804">
<img width="619" alt="image" src="https://github.com/longhorn/longhorn/assets/26134111/2b688bad-dd6c-433b-8561-36291395538d">
<img width="2525" alt="image" src="https://github.com/longhorn/longhorn/assets/26134111/ab29313f-6a3a-4b2a-829c-ddb65c457308">

**Comment by shuo-wu** [comment]
The value in ConfigMap will change [this default value](https://github.com/longhorn/longhorn-manager/blob/aaeae7e46b938238c1f7cd80936f626d7ce073dc/types/setting.go#L406), which is invisible for users. But for setting `default-data-path`, you can verify if your customized value is applied by checking Node page or `node.spec.disks.path` (`kubectl -n longhorn-system get lhn -o yaml`)

**Comment by PowerfooI** [comment]
Thanks you for checking this issue!

After I executed command `kubectl -n longhorn-system get lhn -o yaml`, it still shows that the default disk path is `/var/lib/longhorn`. 

```yaml
  spec:
    allowScheduling: true
    disks:
      default-disk-bc53e18b63481a21:
        allowScheduling: true
        diskType: filesystem
        evictionRequested: false
        path: /var/lib/longhorn/
        storageReserved: 18983208960
        tags: []
    evictionRequested: false
    instanceManagerCPURequest: 0
```

Is there any other method that I could try to modify the storage path?

**Comment by eloo** [comment]
hi,
i'm also running into this issue and found also that the `system-managed-components-node-selector` is also not set properly.

Also `default-replica-count` is not working :( 

This bug really block usage of longhorn

**Comment by mantissahz** [comment]
Hi @powerfooI, 

Can you show the value of the setting `default-data-path`?
After the default disk is created, the default disk will not be modified with the setting [create-default-disk-labeled-nodes](https://longhorn.io/docs/1.5.3/references/settings/#create-default-disk-on-labeled-nodes).
I believe the doc [Customizing Default Disks for New Nodes](https://longhorn.io/docs/1.5.3/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes) should help.

Hi @eloo, 

>`system-managed-components-node-selector` is also not set properly.
Also `default-replica-count` is not working.

Could you describe the situation in more detail for these settings?

**Comment by eloo** [comment]
@mantissahz for sure.

i have installed longhorn freshly with flux using the following helmrelease config

```yaml
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    monitoring:
      enabled: false
      createPrometheusRules: true
    defaultSettings:
      systemManagedComponentsNodeSelector: "node-role.kubernetes.io/longhorn:true"
      defaultDataPath: /mnt/k8s/longhorn/
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: false  # custom
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      taintToleration: CriticalAddonsOnly:Exists; node-role.kubernetes.io/control-plane:NoSchedule
    ingress:
      enabled: true
      ingressClassName: traefik-internal
      host: longhorn.${SECRET_INTERNAL_CLUSTER_DOMAIN}
    longhornDriver:
      nodeSelector: &nodeSelector
        node-role.kubernetes.io/longhorn: "true"
      tolerations: &tolerations
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    longhornManager:
      nodeSelector: *nodeSelector
      tolerations: *tolerations
    longhornUI:
      replicas: 1
      nodeSelector: *nodeSelector
```

afterwards i have checked the data path in the longhorn ui for the disks which where created automatically
and found there the wrong path `/var/lib/longhorn`

then i have checked the settings like this
`kubectl get lhs default-data-path -n longhorn-system`
and the value there was also `/var/lib/longhorn`

i hope this helps

**Comment by mantissahz** [comment]
Thank you @eloo,

Are all settings you set in `values.defaultSettings` not applied or only just some like `defaultReplicaCount` and `defaultDataPath` you mentioned?

Could you provide the ConfigMap `longhorn-default-setting` information?
```shell
 kubectl get cm longhorn-default-setting -n longhorn-system -oyaml
```
And what do you mean that `system-managed-components-node-selector` is also not set properly?

Could you provide the support bundle to investigate the settings?

**Comment by eloo** [comment]
here is the current state of the configs get by 
`kubectl get lhs`

```
default-data-path                                                 /mnt/k8s/longhorn/                            23h
system-managed-components-node-selector                           node-role.kubernetes.io/longhorn:true         23h
default-replica-count                                             1                                             23h
create-default-disk-labeled-nodes                                 false                                         23h
storage-over-provisioning-percentage                              100                                           23h
storage-minimal-available-percentage                              25                                            23h
guaranteed-instance-manager-cpu                                   12                                            23h
orphan-auto-deletion                                              false                                         23h
concurrent-automatic-engine-upgrade-per-node-limit                0                                             23h
default-longhorn-static-storage-class                             longhorn-static                               23h
taint-toleration                                                                                                23h
```

as we can see nearly no setting matches what i have configured in the helm chart.
the few which are matching here are adjusted by hand

```
10251  k edit lhs deleting-confirmation-flag
10259* k edit lhs default-data-path
10264* k edit lhs system-managed-components-node-selector
10284* k edit lhs default-replica-count
```

the CM yaml looks like this
```
data:
  default-setting.yaml: |-
    create-default-disk-labeled-nodes: true
    default-data-path: /mnt/k8s/longhorn/
    storage-over-provisioning-percentage: 100
    storage-minimal-available-percentage: 1
    default-replica-count: 1
    default-longhorn-static-storage-class: longhorn
    taint-toleration: CriticalAddonsOnly:Exists; node-role.kubernetes.io/control-plane:NoSchedule
    system-managed-components-node-selector: node-role.kubernetes.io/longhorn:true
    priority-class: longhorn-critical
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
    concurrent-automatic-engine-upgrade-per-node-limit: 1
    orphan-auto-deletion: false
```

we can see that the CM is matching my configuration but these yaml seems not be applied to the `lhs` somehow
not sure how this should be done anyway
