### ISSUE TITLE
[BUG][v1.6.0-rc1] Negative test case failed: Stress Volume Node CPU/Memory When Volume Is Offline Expanding

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7707]
## Describe the bug

During negative test case `Stress Volume Node CPU/Memory When Volume Is Offline Expanding` executing, after offline expansion and scale up the workload to attach the volume, there seems could be an unexpected `detaching` causes the test case failed:
```
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 expand to 5947523072 (10) ...
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 expand to 5947523072 (11) ...
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 expand to 5947523072 (12) ...
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 expand to 5947523072 (13) ...
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 expand to 5947523072 (14) ...
Scaling statefulset test-statefulset-rwo to 1
Waiting for pvc-464dd8e1-e3f0-465b-9648-25cca9183464 attached (0) ...
Assert pvc-464dd8e1-e3f0-465b-9648-25cca9183464 state to be attached but it's detaching
volume  = {'apiVersion': 'longhorn.io/v1beta2', 'kind': 'Volume', 'metadata': {'creationTimestamp': '2024-01-17T02:17:22Z', 'finalizers': ['longhorn.io'], 'generation': 131, 'labels': {'longhornvolume': 'pvc-464dd8e1-e3f0-465b-9648-25cca9183464', 'recurring-job-group.longhorn.io/default': 'enabled', 'setting.longhorn.io/remove-snapshots-during-filesystem-trim': 'ignored', 'setting.longhorn.io/replica-auto-balance': 'ignored', 'setting.longhorn.io/snapshot-data-integrity': 'ignored'}, 'managedFields': [{'apiVersion': 'longhorn.io/v1beta2', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:recurring-job-group.longhorn.io/default': {}}}, 'f:spec': {'.': {}, 'f:Standby': {}, 'f:accessMode': {}, 'f:backendStoreDriver': {}, 'f:backingImage': {}, 'f:backupCompressionMethod': {}, 'f:dataEngine': {}, 'f:dataLocality': {}, 'f:dataSource': {}, 'f:disableFrontend': {}, 'f:encrypted': {}, 'f:engineImage': {}, 'f:fromBackup': {}, 'f:frontend': {}, 'f:image': {}, 'f:lastAttachedBy': {}, 'f:migratable': {}, 'f:migrationNodeID': {}, 'f:nodeID': {}, 'f:numberOfReplicas': {}, 'f:offlineReplicaRebuilding': {}, 'f:replicaAutoBalance': {}, 'f:replicaDiskSoftAntiAffinity': {}, 'f:replicaSoftAntiAffinity': {}, 'f:replicaZoneSoftAntiAffinity': {}, 'f:restoreVolumeRecurringJob': {}, 'f:revisionCounterDisabled': {}, 'f:size': {}, 'f:snapshotDataIntegrity': {}, 'f:snapshotMaxCount': {}, 'f:snapshotMaxSize': {}, 'f:staleReplicaTimeout': {}, 'f:unmapMarkSnapChainRemoved': {}}}, 'manager': 'longhorn-manager', 'operation': 'Update', 'time': '2024-01-17T02:57:00Z'}, {'apiVersion': 'longhorn.io/v1beta2', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'.': {}, 'f:actualSize': {}, 'f:cloneStatus': {'.': {}, 'f:snapshot': {}, 'f:sourceVolume': {}, 'f:state': {}}, 'f:conditions': {}, 'f:currentImage': {}, 'f:currentMigrationNodeID': {}, 'f:currentNodeID': {}, 'f:expansionRequired': {}, 'f:frontendDisabled': {}, 'f:isStandby': {}, 'f:kubernetesStatus': {'.': {}, 'f:lastPVCRefAt': {}, 'f:lastPodRefAt': {}, 'f:namespace': {}, 'f:pvName': {}, 'f:pvStatus': {}, 'f:pvcName': {}, 'f:workloadsStatus': {}}, 'f:lastBackup': {}, 'f:lastBackupAt': {}, 'f:lastDegradedAt': {}, 'f:offlineReplicaRebuildingRequired': {}, 'f:ownerID': {}, 'f:pendingNodeID': {}, 'f:remountRequestedAt': {}, 'f:restoreInitiated': {}, 'f:restoreRequired': {}, 'f:robustness': {}, 'f:shareEndpoint': {}, 'f:shareState': {}, 'f:state': {}}}, 'manager': 'longhorn-manager', 'operation': 'Update', 'subresource': 'status', 'time': '2024-01-17T02:57:00Z'}], 'name': 'pvc-464dd8e1-e3f0-465b-9648-25cca9183464', 'namespace': 'longhorn-system', 'resourceVersion': '10584', 'uid': '7ba963e6-37f4-42e4-a090-0ade7051a5cc'}, 'spec': {'Standby': False, 'accessMode': 'rwo', 'backendStoreDriver': '', 'backingImage': '', 'backupCompressionMethod': 'lz4', 'dataEngine': 'v1', 'dataLocality': 'disabled', 'dataSource': '', 'disableFrontend': False, 'diskSelector': [], 'encrypted': False, 'engineImage': '', 'fromBackup': '', 'frontend': 'blockdev', 'image': 'longhornio/longhorn-engine:v1.6.0-rc1', 'lastAttachedBy': '', 'migratable': False, 'migrationNodeID': '', 'nodeID': '', 'nodeSelector': [], 'numberOfReplicas': 2, 'offlineReplicaRebuilding': 'disabled', 'replicaAutoBalance': 'ignored', 'replicaDiskSoftAntiAffinity': 'ignored', 'replicaSoftAntiAffinity': 'ignored', 'replicaZoneSoftAntiAffinity': 'ignored', 'restoreVolumeRecurringJob': 'ignored', 'revisionCounterDisabled': False, 'size': '5947523072', 'snapshotDataIntegrity': 'ignored', 'snapshotMaxCount': 250, 'snapshotMaxSize': '0', 'staleReplicaTimeout': 30, 'unmapMarkSnapChainRemoved': 'ignored'}, 'status': {'actualSize': 1249947648, 'cloneStatus': {'snapshot': '', 'sourceVolume': '', 'state': ''}, 'conditions': [{'lastProbeTime': '', 'lastTransitionTime': '2024-01-17T02:17:23Z', 'message': '', 'reason': '', 'status': 'False', 'type': 'WaitForBackingImage'}, {'lastProbeTime': '', 'lastTransitionTime': '2024-01-17T02:17:23Z', 'message': '', 'reason': '', 'status': 'False', 'type': 'TooManySnapshots'}, {'lastProbeTime': '', 'lastTransitionTime': '2024-01-17T02:17:23Z', 'message': '', 'reason': '', 'status': 'True', 'type': 'Scheduled'}, {'lastProbeTime': '', 'lastTransitionTime': '2024-01-17T02:17:23Z', 'message': '', 'reason': '', 'status': 'False', 'type': 'Restore'}], 'currentImage': 'longhornio/longhorn-engine:v1.6.0-rc1', 'currentMigrationNodeID': '', 'currentNodeID': 'ip-10-0-2-163', 'expansionRequired': False, 'frontendDisabled': False, 'isStandby': False, 'kubernetesStatus': {'lastPVCRefAt': '', 'lastPodRefAt': '', 'namespace': 'default', 'pvName': 'pvc-464dd8e1-e3f0-465b-9648-25cca9183464', 'pvStatus': 'Bound', 'pvcName': 'pod-data-test-statefulset-rwo-0', 'workloadsStatus': [{'podName': 'test-statefulset-rwo-0', 'podStatus': 'Pending', 'workloadName': 'test-statefulset-rwo', 'workloadType': 'StatefulSet'}]}, 'lastBackup': '', 'lastBackupAt': '', 'lastDegradedAt': '', 'offlineReplicaRebuildingRequired': False, 'ownerID': 'ip-10-0-2-163', 'pendingNodeID': '', 'remountRequestedAt': '', 'restoreInitiated': False, 'restoreRequired': False, 'robustness': 'unknown', 'shareEndpoint': '', 'shareState': '', 'state': 'detaching'}}
```

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/175/
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/177/

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/156/
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/157/

The test step is like:
```
Create statefulset 0 with rwo volume
Write 1024 MB data to statefulset 0

Scale down statefulset 0 to detach volume
Stress the CPU of all worker nodes

Expand statefulset 0 volume by 100 MiB

Wait for statefulset 0 volume size expanded
Scale up statefulset 0 to attach volume
Check statefulset 0 data is intact
```

Test cases could fail at step `Scale up statefulset 0 to attach volume`.

## To Reproduce

Run negative test case `Stress Volume Node CPU When Volume Is Offline Expanding` or `Stress Volume Node Memory When Volume Is Offline Expanding`.

## Support bundle for troubleshooting

[supportbundle_66acd5e0-7771-4776-ad82-35cd03a12a3a_2024-01-17T05-26-54Z.zip](https://github.com/longhorn/longhorn/files/13958986/supportbundle_66acd5e0-7771-4776-ad82-35cd03a12a3a_2024-01-17T05-26-54Z.zip)
[supportbundle_92298154-bb62-4c3a-a9e5-aa1707636e32_2024-01-17T05-26-53Z.zip](https://github.com/longhorn/longhorn/files/13958987/supportbundle_92298154-bb62-4c3a-a9e5-aa1707636e32_2024-01-17T05-26-53Z.zip)

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.4+k3s1 or v1.27.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURVME5UYzFOakV3SGhjTk1qUXdNVEUzTURJeE1qUXhXaGNOTXpRd01URTBNREl4TWpReApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURVME5UYzFOakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTRGY0aThNR2R0RitESVdjWGxkRUZETzRDd3hBN1U3bUF5MVdaeStJelUKdnFyYjltZFNERXgvMElrV21xcTR4citrVnhNb0JSelpuMWJSQWRxamdpbWJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpORW5IMUNTcVlTcnJOUXN5S3dWCmVEWjNsb293Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVjljb2Ezai95ay9GTlpZV3FEZFY0KzUzU3BTaGdVcjAKaFVVYmZ0NUdOV1FDSVFDVmk0VllOWFUrOTVEa1Nyc3BRc29COFJab1d3N2VXSTdZNmxvWFlydHdnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3.218.34.150:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJZXk5K24yQ3EyVWd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekExTkRVM05UWXhNQjRYRFRJME1ERXhOekF5TVRJME1Wb1hEVEkxTURFeApOakF5TVRJME1Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDRE96NHcvZmxKZEw3Y0cKNkdORUJqRkdmc1BaZkpFUnJoUTMvVEdEVEdtdGpsWk1rRmxzMlBUODdZR3VTaHlWU0d3c1JuZW9QcFJacWFMVgpFaFF5WUhhalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUnd6STV4L2tTT1pXeENpVExUVzB0TEtaOWJvREFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCaC9YZFplUUI3M2xyTkZtQWpQTzZlczNCTXJ6dlBQVGE0ZkJJSWNwUmQ5d0lnTWEweDhxMncxZmthcGlNcApGZlpRaGM3NXE0enJYdTgwV1Y3anFZdkhoZzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTURVME5UYzFOakV3SGhjTk1qUXdNVEUzTURJeE1qUXhXaGNOTXpRd01URTBNREl4TWpReApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTURVME5UYzFOakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSZHBFZ0FpMHRXZ01nU1cvRkJZWElCOVFpVEdGcHJ4c1ZGVE5HNGtkQjUKRHU5Wll6a3YzbGhReEdUYWpIUHBBYWtLWkphVnhTZ1ErZTNqaFBoamRMb0pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWNNeU9jZjVFam1Wc1Fva3kwMXRMClN5bWZXNkF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlHcGNINEJKUXE0eTZ0WlFmLzJEcUxjeSt4K2kzcXkKQWFZNW9YU2E0MlRNQWlFQXlDRDk3NjdHeWNTOExOajVwNi8vK0NwRkRnc0NMNkNjOTA5c0pPZzhRcDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5ib2pWMFNqdkhDcmhYSTdWV0dueU9ubEZEWlN1TDNuTlprWTNzTVZkMG5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSU03UGpEOStVbDB2dHdib1kwUUdNVVordzlsOGtSR3VGRGY5TVlOTWFhMk9Wa3lRV1d6WQo5UHp0Z2E1S0hKVkliQ3hHZDZnK2xGbXBvdFVTRkRKZ2RnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURVME5qWTFOVFF3SGhjTk1qUXdNVEUzTURRME1qTTBXaGNOTXpRd01URTBNRFEwTWpNMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURVME5qWTFOVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUVVlzMXloSkZNU1F1elBOeFh6OVBvL0s4b0R1RlVmMEU3SXorTnFrMjYKMnJ0WDFFejFWK05zazYxWXcrZ3pVWmkxM3VSTm1kRUplL2lPQUR5bjZDa3hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXU4ZDVicVRaNE5XMVNPZitFcWQ1CjRhbnNlYVF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVAyWVNhQTFwQ0crcE9BK1E0WUkyVmtmUGxnRWZQTngKK2pVWDU5eHhkRE1SQWlBYmRqYUROLzdtWFQya3Z2T1ZjTVlqbENidjU5SlBpRVMvV0ttZllTdzk2QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://44.197.139.191:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRy9FWEdqME82bWd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekExTkRZMk5UVTBNQjRYRFRJME1ERXhOekEwTkRJek5Gb1hEVEkxTURFeApOakEwTkRJek5Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKNGZrS055S1dkTjg0QWMKTm5vdmgzTDU3MVNHL1VZM2JER1k2OUtsQTFucDZlSTluZEU0MjdRenAxMkFCVzNpaUpxSjJFcGh4OXk5OURFNgo0R1NPQlZTalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU3dwOHZsYW5sQVd4NG5aVi9tS2JiRVFiS0VvakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTRrclNkc1IvOERKOEZZcDhWbnAzR1JHUmVZdzVrTTE4dStCcEZiSUFGbUVDSUNGTHRrdHE0SGZYVW5IdwpUcGxhbC9NclFCVzVkUEk2RzlMUlFFSXozazlwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkVENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTURVME5qWTFOVFF3SGhjTk1qUXdNVEUzTURRME1qTTBXaGNOTXpRd01URTBNRFEwTWpNMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTURVME5qWTFOVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRTXRWR2RsTnloYWdVbVMvZGpVWFdkZHBjUHUwVW14RXVVMTZHQlVvSDYKTzcyRUNWY2RibkxzTVJHWWhXS1VZeXNBSjlUWHFOdDJIOWZ6V3hmMjZsK2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXNLZkw1V3A1UUZzZUoyVmY1aW0yCnhFR3loS0l3Q2dZSUtvWkl6ajBFQXdJRFJnQXdRd0lmSVdPcUl5UjYyY3FvbmFmNi8zNlovbzU1b3ZpZjhrSUUKVHhHbE15Z2U3QUlnY0FFeENudXl3a09ibkZxVklvdmhEalZybVk2WmxQaWVoUVREMERmbmoyWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNDWWIzSTk3dDdRVFp3OTFWeTNRcXBwVFl1d3RGUEwxdzRETjM2VG9NVURvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbmgrUW8zSXBaMDN6Z0J3MmVpK0hjdm52VkliOVJqZHNNWmpyMHFVRFdlbnA0ajJkMFRqYgp0RE9uWFlBRmJlS0ltb25ZU21ISDNMMzBNVHJnWkk0RlZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```

**Comment by PhanLe1010** [comment]
I tried to rerun the test CI it it failed with this error 
```
groovy.lang.MissingPropertyException: No such property: LONGHORN_TESTS_CUSTOM_IMAGE for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
```
Ref: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/224/console

Looks like something is wrong with the jenkins config? Could you help to take a look @yangchiu ?

**Comment by yangchiu** [comment]
@PhanLe1010 I can find https://ci.longhorn.io/job/private/job/longhorn-e2e-test/228/ reproduced this issue. The `kubeconfig` is:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURZd05UVXlPVFF3SGhjTk1qUXdNVEkwTURBeE5EVTBXaGNOTXpRd01USXhNREF4TkRVMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURZd05UVXlPVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWUs2MUxvNGlSR3hLWUNQSUtHdCtwR2Jwenk4aUhvTXFNQ09jVytRTVcKQnhZayt3MVEzcWMvdmZwQmNRZ1hEemxZV3ZwaUV6NEVqeml3NUVOWVZDREtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNpdEtiTFQ3RUVjUFBHKzhyRWFQClFiMVFCVXd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnTEZ5QnZEVGUyZktoN2lRNDZHSXhMMWkwdFVxK2xhYlYKUWZicmdRVW9iSjRDSVFETVJMdzZwZzdiYzdyL25aTEFaVDdBRGhLaWhHNk9UQVZrWllIZFlqS0R3dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://52.20.128.236:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJWnlhdm5KOG9xTHN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekEyTURVMU1qazBNQjRYRFRJME1ERXlOREF3TVRRMU5Gb1hEVEkxTURFeQpNekF3TVRRMU5Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFT0tVSEZ3aEJ0WVFxZEoKWjZ0dVQ1azVncjZaQnVCVmdRajNrcndVZjRZa3JJeU5uM0x2UnQwbk5BMlhvQmRjWVdGTEJvM3dnNGlLQUN6awp0YzZqMTJTalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUnJGOUdrVU1CU1NTaEU3bVUwRlhPcEZsY2ZUekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQXhydHVUUzM4TmZQNmY3dStib0E3T1JjTE5kL3ZyL2hvTUpFRW9hT0xVR2dDSUZZVzJ4WGJwQjFBcmdDUAo5YUJEL3dwM0cwdjZ4UTZtM29PMzJCWFNDVkkvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTURZd05UVXlPVFF3SGhjTk1qUXdNVEkwTURBeE5EVTBXaGNOTXpRd01USXhNREF4TkRVMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTURZd05UVXlPVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSZ1FzdGlIenYvWTZzODFNa2RMc3RvNmx6Wmh3K2F3RXFFS2puR2FtcmcKeE1IYnVkTERLOU9kYXVUSHdGbmtVWFBOY1l6NXNqY2ppQjN2Si9DVEpHYUtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWF4ZlJwRkRBVWtrb1JPNWxOQlZ6CnFSWlhIMDh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSjVQQjRNS0szQklyc0doL1hXK09qTXBrcng0WGlHejgKNm1MVDhueUhFNEFDSVFDRUdoYkFxNW0xOStSaXlKdFNWd1pQWE8wRHViaSswZmwrN2xlK01WU0grdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdBUUIvTlB5VEFVRHJVc1c4V05zYUR3RmlTS2pFSklmcExldnRnRmJZaGFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUTRwUWNYQ0VHMWhDcDBsbnEyNVBtVG1DdnBrRzRGV0JDUGVTdkJSL2hpU3NqSTJmY3U5RwozU2MwRFplZ0YxeGhZVXNHamZDRGlJb0FMT1MxenFQWFpBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
Support bundle is also attached: [supportbundle_5ff640d2-6463-41d1-b0a9-4d81246204b0_2024-01-25T02-52-16Z.zip](https://github.com/longhorn/longhorn/files/14046188/supportbundle_5ff640d2-6463-41d1-b0a9-4d81246204b0_2024-01-25T02-52-16Z.zip)
