### ISSUE TITLE
[IMPROVEMENT] Only restarts pods with volumes in the unexpected Read-Only state 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7728]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

StorageClass supports mount options, so users can mount volumes with the `ro` option.
To prevent from mistakenly restarting a pod using the volume with `ro` option, we can check `persistentVolume.spec.storageClassName. mountOptions` before restarting it.

cc @ChanYiLin

**Comment by derekbit** [comment]
Not sure if there are users using `ro` mount option. If possible, we can make it in v1.6.0.

**Comment by innobead** [comment]
Did you mean a newly created pod or an existing pod? Why will we have this case? I thought the provisioned volume should be immutable after it has been created, why there is a chance to change the mount options?

**Comment by derekbit** [comment]
Both existing pods and newly created pods are possible.
If a volume is really mounted with ro by an user, the restart will be triggered.

**Comment by innobead** [comment]
oh I see!

**Comment by innobead** [comment]
That's fair. BTW, we will support `ReadOnlyMany` in the future, so this needs to consider later.

**Comment by ChanYiLin** [comment]
I have tried to create a PV/PVC with "ro" mountOptions
But I got this error when mount it to the pod.
It seems it is impossible to use mountOptions: "ro" with dynamically provisioned PV/PVC
because we also have to format it when we mount it, but K8s can't do it when we mount it with "ro"

```
  Warning  FailedMount             14s (x6 over 30s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-71fac6ad-774f-4e2a-bdc6-69b175313e0f" : rpc error: code = Internal desc = cannot mount unformatted disk /dev/longhorn/pvc-71fac6ad-774f-4e2a-bdc6-69b175313e0f as we are manipulating it in read-only mode
```

storageclass.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - ro
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: ext4
```

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 5Gi
```

Do you have workable example of how to apply mountOptions: "ro" in PV/PVC?

**Comment by ChanYiLin** [comment]
If the read-only is achieved by pod level
```
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-simple-pod
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: kworker1
  restartPolicy: Always
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: vol
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: test
        readOnly: true // <==== read only
```

Then the read only is only inside the pod
```
root@longhorn-simple-pod:/data# mount | grep "/data"
/dev/longhorn/pvc-eff30572-74f2-4294-8ac2-6cd1e562a946 on /data type ext4 (ro,relatime)
```

from global mount point, it will still be "rw"
```
/dev/longhorn/pvc-eff30572-74f2-4294-8ac2-6cd1e562a946 on /host/var/lib/kubelet/pods/b573aac5-7f12-4e33-aacf-2d300090026b/volumes/kubernetes.io~csi/pvc-eff30572-74f2-4294-8ac2-6cd1e562a946/mount type ext4 (rw,relatime)
```
