### ISSUE TITLE
[BUG] Longhorn volume cannot be mounted after pod restart

### ISSUE THREAD

**Issue by Kjir** [longhorn/longhorn#7737]
## Describe the bug

After upgrading our installation of Airflow, the worker nodes do not start anymore. The pod is initializing, the volume gets attached, but fails to mount.

I tried to force detach the volume, set the stateful set to 0 replicas, and then try again, but to no avail.

The longhorn dashboard says everything is fine with the volume:

![image](https://github.com/longhorn/longhorn/assets/64094/ffede1fb-73ea-466a-a93a-9b194c9c51e9)

The events for the Pod show that the attaching works, but the mounting fails.
```
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Normal   Scheduled               14m                    default-scheduler        Successfully assigned airflow/airflow-worker-0 to kof-k8s-wrk-1
  Normal   SuccessfulAttachVolume  14m                    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-505cce95-5ebb-4c97-889b-ad1d4320ff01"
  Warning  FailedMount             7m50s (x3 over 12m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[logs], unattached volumes=[config kube-api-access-6q78c dags logs]: timed out waiting for the condition
  Warning  FailedMount             3m20s (x2 over 5m35s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[logs], unattached volumes=[dags logs config kube-api-access-6q78c]: timed out waiting for the condition
```

## To Reproduce

It doesn't always happen, but restarting existing pods seems to sometimes trigger this kind of problem.

## Expected behavior

Either the volume should mount successfully, or these should be a clear error somewhere that helps track down the underlying issue.

## Environment

 - Longhorn version: 1.5.1
 - Impacted volume (PV): pvc-505cce95-5ebb-4c97-889b-ad1d4320ff01
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.25.15+rke2r2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 5.15.0-89-generic
   - CPU per node: 12
   - Memory per node: 47Gb
   - Disk type (e.g. SSD/NVMe/HDD): Not currently known
   - Network bandwidth between the nodes (Gbps): Not currently known
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 133

## Additional context

I've faced similar issues in the past and the only thing that seemed to fix the problem was deleting the volume and creating a new one - requiring migration of the data. Luckily this volume only contains the Airflow logs, so losing data is only annoying and not actually harmful.

**Comment by pcellix** [comment]
I have the same issue
https://github.com/longhorn/longhorn/issues/7671

**Comment by pcellix** [comment]
it worked flawlessly with longhorn 1.4.3 and these days I have also to delete the volumes. Good it's only staging data and I skipped upgrading this on prod

**Comment by pcellix** [comment]
Could you guys please do some hot fix version?
constant deletion and backup recreation makes work less easy

**Comment by derekbit** [comment]
@Kjir Can you provide a support bundle?

**Comment by Kjir** [comment]
I already generated the support bundle through the link in the footer. I don't know where it sends the bundle, but the process seemed successful...

-------- Original Message --------

**Comment by derekbit** [comment]
> I already generated the support bundle through the link in the footer. I don't know where it sends the bundle, but the process seemed successful...

You can send the support bundle to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com).

**Comment by Kjir** [comment]
Yes, but that link generates and sends a bundle, it does not create a file for me to send...

-------- Original Message --------

**Comment by Kjir** [comment]
I tried again and this time I managed to download a bundle. I sent a link to it to the e-mail address

**Comment by shuo-wu** [comment]
Just checked the support bundle and found something below:
1. The csi-plugin pod `longhorn-csi-plugin-kzw69`, which is responsible for mounting the volumes including the problematic one on node `kof-k8s-wrk-1`, has the most recent 10 hours logs. In other words, the container inside the pod was restarted 10 hours before you generated the support bundle. 
2. The pod itself creation time is `"2023-12-05T07:01:31Z"`. The container info is
    ```
    - containerID: containerd://ddd3cc7e565a8cfb9a405669e501d6a37b9b7dcdb6216ce9dee51702441a7006
      image: docker.io/rancher/mirrored-longhornio-longhorn-manager:v1.5.1
      imageID: docker.io/rancher/mirrored-longhornio-longhorn-manager@sha256:599bd9dcd9dd4c46c2d7e8e055fae4edb3c824ab59ed96c5cd796566ea90628c
      lastState:
        terminated:
          containerID: containerd://fbb3d87a92cf35b927490f0f7edc8d4ae8d7728fcf334f8cdb353154fabc0585
          exitCode: 143
          finishedAt: "2024-01-07T22:59:42Z"
          reason: Error
          startedAt: "2024-01-07T22:59:06Z"
      name: longhorn-csi-plugin
      ready: true
      restartCount: 71
      started: true
      state:
        running:
    ```
3. I found the below log in the kubernetes version checker pod:
    ```
    2024-01-17T22:56:00.993948507Z time="2024-01-17T22:56:00Z" level=error msg="error syncing 'longhorn-csi-plugin-kzw69/longhorn-system': failed to sync pod longhorn-csi-plugin-kzw69/longhorn-system: failed to check container image \"node-driver-registrar\": failed to get tags from remote registry for \"rancher/mirrored-longhornio-csi-node-driver-registrar\": failed to get docker image: Get \"https://registry.hub.docker.com/v2/repositories/rancher/mirrored-longhornio-csi-node-driver-registrar/tags?page_size=100\": context deadline exceeded (Client.Timeout exceeded while awaiting headers),failed to check container image \"longhorn-liveness-probe\": failed to get tags from remote registry for \"rancher/mirrored-longhornio-livenessprobe\": failed to get docker image: Get \"https://registry.hub.docker.com/v2/repositories/rancher/mirrored-longhornio-livenessprobe/tags?page_size=100\": context deadline exceeded (Client.Timeout exceeded while awaiting headers),failed to check container image \"longhorn-csi-plugin\": failed to get tags from remote registry for \"rancher/mirrored-longhornio-longhorn-manager\": failed to get docker image: Get \"https://registry.hub.docker.com/v2/repositories/rancher/mirrored-longhornio-longhorn-manager/tags?page_size=100\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), requeuing" module=controller
    ```
4. On the other hand, I saw the below volume mounting and unmounting related logs in kubelet of node `kof-k8s-wrk-1`:
    ```
    W0119 17:30:16.379036    1379 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/b9af2f28-46ff-4a22-9d85-2e8ab26b4cb7/volumes/kubernetes.io~csi/pvc-505cce95-5ebb-4c97-889b-ad1d4320ff01/mount and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699

    I0119 19:53:08.937191    1379 reconciler.go:211] "operationExecutor.UnmountVolume started for volume \"logs\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-505cce95-5ebb-4c97-889b-ad1d4320ff01\") pod \"b9af2f28-46ff-4a22-9d85-2e8ab26b4cb7\" (UID: \"b9af2f28-46ff-4a22-9d85-2e8ab26b4cb7\") "
    ```
    I am not sure if the volume fsgroup set issue can be a cause.


I suspect that either of the following is the cause:
1. During the volume mount, something was wrong with this `longhorn-csi-plugin` pod restarting or the network itself. Then kubelet cannot ask this component to handle the mount call.
2. There are lots of files in the volume. Then setting fsgroup would take lots of time then return error `timed out waiting for the condition`

**Comment by Kjir** [comment]
I added the following security context to the pods and containers:

```yaml
securityContexts:
  pod:
    runAsUser: *uid
    fsGroup: *gid
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
    runAsUser: *uid
    fsGroup: *gid
    fsGroupChangePolicy: "OnRootMismatch"
```

This seems to have improved the situation, but not consistently. I observed a startup time between 15 seconds and 3 minutes. It appears to depend on the worker node.

I have generated another support bundle after these further tests, if you're interested let me know and I'll send this one too.

> I found the below log in the kubernetes version checker pod
That pod was not working, but unrelated. I removed it.
