### ISSUE TITLE
[BUG] Use config map to update `default-replica-count` won't apply to `default-replica-count.definition.default` if the value equal to current `default-replica-count.value`

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7755]
## Describe the bug

Use config map to update `default-replica-count`, if the value equals to current value of `default-replica-count.value`, then `default-replica-count.definition.default` won't be updated.

When first time perform test case `test_setting_replica_count_update_via_configmap`, after test complete,  the `default-replica-count.definition.default` will changed to `1` not back to `3` due to above description. And this may have some impact when try rerun some e2e test cases on the same cluster.

## To Reproduce

1. Deploy Longhorn(master-head, v1.6.0-rc2)
2. Update `default-replica-count` to 4 by UI or by edit the CRD
3. From API, the `value: 4`, `definition.default: 3`
![image](https://github.com/longhorn/longhorn/assets/73337386/7e8f4c79-1bb0-4956-9832-67586e4a2cb7)
4. Apply below yaml to update default replica count to 4 by config map
```
apiVersion: v1
data:
  default-setting.yaml: |
    default-replica-count: 4
    priority-class: longhorn-critical
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
```
5. Kubectl replied `configmap/longhorn-default-setting unchanged`, the value of `definition.default` still `3`
6. Apply below yaml to update default replica count to `5` by config map
```
apiVersion: v1
data:
  default-setting.yaml: |
    default-replica-count: 5
    priority-class: longhorn-critical
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
```
![image](https://github.com/longhorn/longhorn/assets/73337386/84ced643-3076-44be-8e69-1e6a198f2a22)
7. Can see both `definition.default` and value updated to `5`

## Expected behavior

Have consistent behavior

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version: master-head, v1.6.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.5+k3s1

## Additional context

N/A
