### ISSUE TITLE
[IMPROVEMENT] Use ensureFolderPath rather than ensureMount for checking folder path in CSI plugin

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7784]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Use ensureFolderPath rather than ensureMount for checking folder path in CSI plugin

**Comment by roger-ryao** [comment]
**Verified on master-head 20240126**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/c3a9f120e30287d5ba1b954a0227f637309dff81
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/c7d9d7c22808a57e7c387459278634fe667124b0

- longhorn `v1.6.x-head` https://github.com/longhorn/longhorn/commit/b34b8735e0c98daa9e4d200d3f17c5cb6056e1f3
- longhorn-manager `v1.6.x-head` https://github.com/longhorn/longhorn-manager/commit/1640c5699b555bab7974f0e22d515d38d903e398

**The test steps**

Deploying Manifests for Different Longhorn Volume Scenarios

Case 1 : non-encrypted RWO block mode volume

- block_rwo_vol_without_encrypt.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-rwo-no-encrypt-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test-rwo-no-encrypt
  labels:
    app: volume-test-rwo-no-encrypt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test-rwo-no-encrypt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: volume-test-rwo-no-encrypt
    spec:
      restartPolicy: Always
      containers:
      - image: nginx
        name: volume-test-rwo-no-encrypt
        volumeDevices:
          - devicePath: /dev/longhorn/testblk
            name: block-vol-rwo-no-encrypt
      volumes:
      - name: block-vol-rwo-no-encrypt
        persistentVolumeClaim:
          claimName: block-rwo-no-encrypt-pvc
```

Case 2 : encrypted RWO block mode volume

- secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "simple"
  CRYPTO_KEY_PROVIDER: "secret"
```

- storageclass_unmigratable_with_encrypted.yaml
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-unmigratable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
#  migratable: "true"
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
```

- block_rwo_vol_with_encrypt.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-rwo-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn-unmigratable
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test-rwo
  labels:
    app: volume-test-rwo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test-rwo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: volume-test-rwo
    spec:
      restartPolicy: Always
      containers:
      - image: nginx
        name: volume-test-rwo
        volumeDevices:
          - devicePath: /dev/longhorn/testblk
            name: block-vol-rwo
      volumes:
      - name: block-vol-rwo
        persistentVolumeClaim:
          claimName: longhorn-block-rwo-pvc
```

Case 3 : encrypted RWX with migratable=true block mode volume

- secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "simple"
  CRYPTO_KEY_PROVIDER: "secret"
```

- storageclass_migratable_with_encrypted.yaml
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-migratable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  migratable: "true"
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
```

- block_rwx_vol_with_encrypt.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: longhorn-migratable
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  labels:
    app: volume-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      restartPolicy: Always
      containers:
      - image: nginx:stable-alpine
        name: volume-test
        volumeDevices:
          - devicePath: /dev/longhorn/testblk
            name: block-vol
      volumes:
      - name: block-vol
        persistentVolumeClaim:
          claimName: longhorn-block-pvc
```

**Result Passed**
