### ISSUE TITLE
[BUG] Faulted RWX volume upon creation

### ISSUE THREAD

**Issue by enzosanchezc** [longhorn/longhorn#7802]
## Describe the bug

Sometimes when multiple RWX PVC are created at the same time with data locality disabled and some pods try to mount them at the same time that the PVCs are created (for example when installing multiple Helm charts in parallel in a Jenkins pipeline), it can happen that the underlying replica of a volume becomes fautled on creation and the volume never recovers, forcing the user to access Longhorn's UI to manually salvage it.

## To Reproduce

1. Create a StorageClass with 1 replica, data locality disabled, fstype ext4, the rest should be default
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx-data
parameters:
  dataLocality: disabled
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Generate a sample manifest that contains a Pod + a PVC. The Pod should mount the PVC:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-rwx-data
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod-pvc
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["tail","-f","/dev/null"]
    volumeMounts:
    - name: test-pvc
      mountPath: /test
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc
```
3. Use the previous manifest as a template to generate 10 replicas of the same Pod + PVC pair:
```bash
mkdir test-pod-pvc
for ID in {01..10}; do sed "s/test-pvc/test-pvc$ID/g;s/test-pod/test-pod$ID/g;s/app: test-pod$ID/app: test-pod/g" test-pod-pvc.yaml > test-pod-pvc/test-pod-pvc-${ID}.yaml; done
```
4. Use a script to apply/remove the manifests until the bug is hitted
```bash
until [ "$(kubectl -n longhorn-system get replicas -o jsonpath="{.items[?(@.spec.failedAt != '')].metadata.name}" | wc -c)" != "0" ]; do
	kubectl -n default delete -f test-pod-pvc/
	kubectl -n longhorn-system wait --for=delete volumes --all
	for MANIFEST in $(ls test-pod-pvc); do
		kubectl -n default apply -f test-pod-pvc/$MANIFEST &
	done
	wait $(jobs -p)
	kubectl -n longhorn-system wait --for=jsonpath='{.status.state}'=attached volumes --all --timeout=60s
done
```
This took me arround 10 cycles to reproduce.
![image](https://github.com/longhorn/longhorn/assets/29806127/e8b79f1a-44f6-432a-ac76-ccb10593b94b)

## Expected behavior

The volume should be created without any issues and mounting should succeed

## Support bundle for troubleshooting

[supportbundle_215c33db-caea-403c-9441-9449f038bdb1_2024-01-29T17-23-02Z.zip](https://github.com/longhorn/longhorn/files/14087603/supportbundle_215c33db-caea-403c-9441-9449f038bdb1_2024-01-29T17-23-02Z.zip)

## Environment

 - Longhorn version: v1.5.3
 - Impacted volume (PV): pvc-65a94bc6-8c8d-47e1-853d-c83dd4631887
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.28.5-rke2r1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Debian 12
   - Kernel version: 6.1.0-15-amd64
   - CPU per node: 12
   - Memory per node: 30Gi
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 2
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 10

## Additional context
-
