### ISSUE TITLE
[BUG] v1.5.x/v1.4.x BackingImage download fails if URL has query parameters

### ISSUE THREAD

**Issue by mazocode** [longhorn/longhorn#7822]
## Describe the bug

Download fails if backing image URL contains query parameters

Error:
```
time="2024-02-01T00:45:19Z" level=fatal msg="Error running data-source command" func=cmd.DataSourceCmd.func1 file="data_source.go:55" error="invalid slice input [url http://foo.bar/repository/image.qcow2?a 1&b 2] since it cannot be converted to a map entry"
```

## To Reproduce

Create a backing image with:
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: idnt-generic-win2k22-v1.0.8
  namespace: longhorn-system
spec:
  sourceParameters:
    url: "http://foo.bar/repository/image.qcow2?a=1&b=2"
  sourceType: download
```

## Expected behavior

Image download succeeds.

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): -
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kueadm
   - Number of control plane nodes in the cluster: 5
   - Number of worker nodes in the cluster: 26
 - Node config
   - OS type and version: Rocky 9
   - Kernel version: 5.14.0-362.13.1.el9_3.x86_64 
   - CPU per node: 112
   - Memory per node: 512GB
   - Disk type (e.g. SSD/NVMe/HDD): NVME
   - Network bandwidth between the nodes (Gbps): 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Comment by derekbit** [comment]
cc @ChanYiLin @shuo-wu

**Comment by ChanYiLin** [comment]
Hi @mazocode 
https://github.com/longhorn/backing-image-manager/blob/master/app/cmd/data_source.go#L90
This has been fixed in v1.6.0 which will be released recently.

We can backport this fix to v1.5.x.

**Comment by innobead** [comment]
@mantissahz Please help test this. Thanks.

cc @longhorn/qa

**Comment by ChanYiLin** [comment]
Hi @mantissahz 
This issue is for v1.5.x
So just test the fix on v1.5.x, thanks!

**Comment by mantissahz** [comment]
Verified `PASSED` with longhorn-manager v1.5.x (e234a4576910) and backing-image-manager v1.5.x (630323c9bd9e)

Created the backing image with querying parameters successfully.
```yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  name: parrot-raw-001
  namespace: longhorn-system
spec:
  sourceParameters:
    url: "https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw?a=2&c=parrot"
  sourceType: download
```
