### ISSUE TITLE
[BUG] Deadlock between volume migration and upgrade after Longhorn upgrade

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7833]
## Describe the bug

After a Longhorn upgrade, a user is stuck with multiple detached volumes that cannot be attached. 

- Each volume is migratable.
- Each volume has multiple engines, one active and one passive. 
- Each volume has `Spec.EngineImage == v1.4.3` and `Status.CurrentImage == v1.3.2`.
- Each volume is currently detached.
- Each volume does not have a `Spec.MigrationNodeID`.

The user is trying to reattach the volumes, but making little progress. The only seemingly relevant `longhorn-manager` log message is:

```
2024-02-02T14:30:29.009262256Z time="2024-02-02T14:30:29Z" level=debug msg="Wait for offline volume upgrade to finish" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=dc-suserchr-03 owner=dc-suserchr-03 shareEndpoint= shareState= state=detached volume=pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700
```

The also see attaches and detaches timing out in the `csi-plugin` logs.

```
2024-02-02T14:30:20.598470274Z time="2024-02-02T14:30:20Z" level=debug msg="Polling volume pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700 state for volume unpublished at 2024-02-02 14:30:20.598423549 +0000 UTC m=+843372.803811468"
2024-02-02T14:30:20.907061648Z time="2024-02-02T14:30:20Z" level=debug msg="Polling volume pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700 state for volume published at 2024-02-02 14:30:20.90689384 +0000 UTC m=+843373.112281789"
```

For each volume, both engines were created long before the Longhorn upgrade occurred. We suspect the volumes were in a long migration (months) due to https://github.com/longhorn/longhorn/issues/6919. This causes each volume to have two VolumeAttachments.

- The first is for the node affected by https://github.com/longhorn/longhorn/issues/6919. We are currently trying to detach from that node.
- The second is for the node the user is trying to attach to. We are trying to attach to that node.

## To Reproduce

1. Install Longhorn v1.4.x.
2. Ensure `concurrent-automatic-engine-upgrade-per-node-limit > 0`.
3. Apply a migratable StorageClass.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  migratable: "true"
```

4. Create a PVC.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: test-sc
  resources:
    requests:
      storage: 1Gi
```

5. Create a VolumeAttachment which attaches the underlying PV to NodeA.

```
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  name: test-va-1
spec:
  attacher: driver.longhorn.io
  nodeName: eweber-v124-worker-92d3fb3f-2gtbm
  source:
    persistentVolumeName: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
```

6. Create a VolumeAttachment which attaches the underlying PV to NodeB.

```
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  name: test-va-2
spec:
  attacher: driver.longhorn.io
  nodeName: eweber-v124-worker-92d3fb3f-kv952
  source:
    persistentVolumeName: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
```

7. Update the longhorn-manager Daemonset to use a different `--engine-image` argument.
8. Observe that the volume is both migrating and updating at the same time.

![image](https://github.com/longhorn/longhorn/assets/24213029/f257f228-317a-467e-99f9-8dbfb5de20fa)

9. Detach the volume from NodeB. The kubectl command doesn't complete and the VolumeAttachment doesn't go away.

```
eweber@laptop:~/issue-files/7833> kl delete -f va-2.yaml 
Warning: deleting cluster-scoped resources, not scoped to the provided namespace
volumeattachment.storage.k8s.io "test-va-2" deleted
```

10. Detach the volume from NodeA. The command completes and the VolumeAttachment goes away. The volume is detached, but it still has a running, non-active engine on NodeA. 

```
eweber@laptop:~/issue-files/7833> kubectl delete -f va-1.yaml 
volumeattachment.storage.k8s.io "test-va-1" deleted

name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    nodeID: ""
      state: ""
    currentImage: webericjames/longhorn-engine:v1.4.x-head
    state: detached

eweber@laptop:~/issue-files/7833> kl get engine -oyaml | grep -e "name: pvc" -e currentState -e active -e engineImage -e currentImage
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: webericjames/longhorn-engine:v1.4.x-head
    currentImage: ""
    currentState: stopped
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-1
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: false
    engineImage: webericjames/longhorn-engine:v1.4.x-head
    currentImage: webericjames/longhorn-engine:v1.4.x-head
    currentState: running
```

11. Attempt to attach the volume to some node. It doesn't seem to matter whether it is NodeA or some other NodeC. There is no change in the state of the volume or its engines. Logs mirror the ones seen by the user.

```
[longhorn-csi-plugin-kknnn longhorn-csi-plugin] time="2024-02-02T21:22:15Z" level=debug msg="Polling volume pvc-07d7ffce-d3a6-40b8-830d-f88dda603522 state for volume unpublished at 2024-02-02 21:22:15.948457254 +0000 UTC m=+3772.613379868" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:953"
[longhorn-csi-plugin-kknnn longhorn-csi-plugin] time="2024-02-02T21:22:16Z" level=debug msg="Polling volume pvc-07d7ffce-d3a6-40b8-830d-f88dda603522 state for volume published at 2024-02-02 21:22:16.457723383 +0000 UTC m=+3773.122645934" func="csi.(*ControllerServer).waitForVolumeState" file="controller_server.go:953"

[longhorn-manager-k8ckk longhorn-manager] time="2024-02-02T21:22:29Z" level=info msg="No need to detach volume pvc-07d7ffce-d3a6-40b8-830d-f88dda603522 since it's not attached to node eweber-v124-worker-92d3fb3f-kv952" func="manager.(*VolumeManager).Detach" file="volume.go:321"
[longhorn-manager-k8ckk longhorn-manager] time="2024-02-02T21:22:45Z" level=debug msg="Wait for offline volume upgrade to finish" func="controller.(*VolumeController).ReconcileVolumeState" file="volume_controller.go:1581" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v124-worker-92d3fb3f-n92hg owner=eweber-v124-worker-92d3fb3f-n92hg shareEndpoint= shareState= state=detached volume=pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
[longhorn-manager-k8ckk longhorn-manager] time="2024-02-02T21:22:52Z" level=debug msg="Volume pvc-07d7ffce-d3a6-40b8-830d-f88dda603522 is already attached to node eweber-v124-worker-92d3fb3f-n92hg" func="manager.(*VolumeManager).Attach" file="volume.go:230"
```

## Expected behavior

We shouldn't be able to get into this situation. If there is any chance a migration is in progress (even some strange broken migration state), we should not attempt to upgrade the volume.

Optionally, we should be able to recover from this situation. Either the migration should revert or the migration should revert so we can make progress.

## Support bundle for troubleshooting

The support bundle cannot be made public.

## Environment

 - Longhorn version: v1.4.3 (upgraded from v1.3.2)
 - Impacted volume (PV): pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700 and others
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Harvester v1.2.1
 - Number of Longhorn volumes in the cluster: 10

A lot changed in this flow between v1.4.x and v1.5.x, so I'm not yet sure if other versions are affected.

## Code analysis

Longhorn automatically upgrades engines if concurrent-automatic-engine-upgrade-per-node-limit > 0.

When determining which volumes are candidates for automatic upgrade, Longhorn does not check if volumes are migrating or otherwise have two engines.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/engine_image_controller.go#L463-L529

As a result, a migrating volume may have its Spec.EngineImage set to a new value (e.g. v1.4.3).
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/engine_image_controller.go#L439

An engine upgrade cannot be completed during a migration.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/volume_controller.go#L2437-L2439

The volume controller cannot process a migration during an upgrade. We are deadlocked.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/volume_controller.go#L3467-L3471

In the user's case, we managed to get the volume detached, so we ended up stuck logging "Wait for offline volume upgrade to finish" with no ability to reattach.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/volume_controller.go#L1548-L1551

From the `longhorn-manager` side, attaches succeed with the following because they have `v.Spec.NodeID == <node>`.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/manager/volume.go#L229-L232

```
2024-02-02T14:30:16.906098541Z time="2024-02-02T14:30:16Z" level=debug msg="Volume pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700 is already attached to node <node>"
```

From the `csi-plugin` side, they fail to register as attached because they have `Status.State == detached`.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/csi/controller_server.go#L911-L914

From the `longhorn-manager` side, detaches succeed with the following because `Spec.NodeID != <node>`.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/manager/volume.go#L320-L323

```
2024-02-02T14:28:58.597166838Z time="2024-02-02T14:28:58Z" level=info msg="No need to detach volume pvc-c8b5e25e-6998-4313-a1cd-783adfbe1700 since it's not attached to node \<node\>"
```

From the `csi-plugin` side, they fail to register as detached because they still have a running engine on \<node\>. This may just be a peculiarity of this user's particular situation.
https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/csi/controller_server.go#L916-L920

**Comment by ejweber** [comment]
Workaround:

1. Scale down the workload so that there is only one stuck VolumeAttachment for the volume. (In my reproduce case, I manually deleted VolumeAttachments since I had previously manually created them. This should NOT be necessary in the real world.) By this point, there are a number of exponential backoffs at work, so be patient! The extra VolumeAttachments may take a couple of minutes to go away.

```
eweber@laptop:~/issue-files/7833> kl get volumeattachment
NAME        ATTACHER             PV                                         NODE                                ATTACHED   AGE
test-va-2   driver.longhorn.io   pvc-07d7ffce-d3a6-40b8-830d-f88dda603522   eweber-v124-worker-92d3fb3f-kv952   true       24m
```

2. Identify the non-active engine. In my reproduce, it should be the engine with the stuck VolumeAttachment. If it is not, do NOT proceed.

```
eweber@laptop:~/issue-files/7833> kl get engine -oyaml | grep -e "name: pvc" -e currentState -e active -e engineImage -e currentImage
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: webericjames/longhorn-engine:v1.4.x-head
    currentImage: ""
    currentState: stopped
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-1
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: false
    engineImage: webericjames/longhorn-engine:v1.4.x-head
    currentImage: webericjames/longhorn-engine:v1.4.x-head
    currentState: running
```

3. Manually delete the non-active engine.

```
eweber@laptop:~/issue-files/7833> kl delete engine pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-1
engine.longhorn.io "pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-1" deleted
```

4, Verify that there are no more VolumeAttachments for the volume. Again, be patient. This may take some time.

```
eweber@laptop:~/issue-files/7833> kl get volumeattachment
No resources found
```

5. The volume should now finish upgrading automatically. Verify all versions.

```
eweber@laptop:~/issue-files/7833> kl get volume -oyaml | grep -e "name: pvc" -e nodeID -e state -e engineImage -e currentImage
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    nodeID: ""
      state: ""
    currentImage: longhornio/longhorn-engine:v1.4.x-head
    state: detached
eweber@laptop:~/issue-files/7833> kl get engine -oyaml | grep -e "name: pvc" -e currentState -e active -e engineImage -e currentImage
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    currentImage: ""
    currentState: stopped
eweber@laptop:~/issue-files/7833> kl get replica -oyaml | grep -e "name: pvc" -e currentState -e active -e engineImage -e currentImage -e engineName
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-r-33f7b553
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    engineName: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
    currentImage: ""
    currentState: stopped
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-r-8a03414e
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    engineName: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
    currentImage: ""
    currentState: stopped
    name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-r-f1ffa707
      name: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522
    active: true
    engineImage: longhornio/longhorn-engine:v1.4.x-head
    engineName: pvc-07d7ffce-d3a6-40b8-830d-f88dda603522-e-0
    currentImage: ""
    currentState: stopped
```

7. Scale up the workload.

**Comment by ejweber** [comment]
I successfully reproduced this issue on master with slightly different (arguably more confusing) behavior.

In this version, both VolumeAttachments actually disappear. So from Kubernetes' perspective, the volume is detached. However, the Longhorn volume still shows as attached to both nodes in the UI and with kubectl:

```
eweber@laptop:~/issue-files/7833> kl get volume -oyaml | grep -ie " name:" -e nodeid -e migration
    name: pvc-8afb95bd-2410-4c67-a1d0-e6de5895e23f
    migrationNodeID: ""
    nodeID: eweber-v126-worker-9c1451b4-kgxdq
    currentMigrationNodeID: eweber-v126-worker-9c1451b4-nn4rg
    currentNodeID: eweber-v126-worker-9c1451b4-kgxdq
    pendingNodeID: ""
```

This may be another bug to investigate. In recent versions, the CSI plugin considers a volume to be detached as soon as it no longer finds an attachment ticket in the spec of its volumeattachment.longhorn.io. And the detach API it calls directly deletes the attachment ticket. So it really isn't checking anything of significance when it is deciding if a volume is detached. (Previous versions would check the volume spec itself).

We are stuck in a stable state in the volume controller.
https://github.com/longhorn/longhorn-manager/blob/2ec649c35486d782731982c9dff1db41c9031c99/controller/volume_controller.go#L1619-L1624

We could make progress there if the volume attachment controller would unset `spec.nodeID`, but it sees we are migrating, so it does not.
https://github.com/longhorn/longhorn-manager/blob/2ec649c35486d782731982c9dff1db41c9031c99/controller/volume_attachment_controller.go#L547-L550

The volume attachment controller also has migration specific code it could be executing, but it is confused by the fact that the volume controller's `processMigration` function is waiting on the upgrade to complete.
https://github.com/longhorn/longhorn-manager/blob/2ec649c35486d782731982c9dff1db41c9031c99/controller/volume_controller.go#L3763-L3767

**Comment by roger-ryao** [comment]
**Verified on master-head 20240305**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/d2b7616691e2d2f89be05004b41cfc48ea342df8
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/8cdf6820620161a0e2b1e71f2994a3c4f763917c

**The test steps**

https://github.com/longhorn/longhorn-manager/pull/2558#issuecomment-1932296348
https://github.com/longhorn/longhorn/issues/7833#issuecomment-1932300425

1. Install Longhorn `v1.6.0`.
1. Ensure concurrent-automatic-engine-upgrade-per-node-limit > 0.
1. Apply a migratable StorageClass.


    storageclass-migratable.yaml
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-migratable
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      fromBackup: ""
      migratable: "true"
    ```

1. Create a PVC

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-pvc
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Block
      storageClassName: longhorn-migratable
      resources:
        requests:
          storage: 1Gi
    ```

1. Create a VolumeAttachment which attaches the underlying PV to NodeA.
    ```yaml
    apiVersion: storage.k8s.io/v1
    kind: VolumeAttachment
    metadata:
      name: test-va-1
    spec:
      attacher: driver.longhorn.io
      nodeName: ryao-161-w1-4e62950f-6nrqh
      source:
        persistentVolumeName: pvc-50930ced-f65d-4cc4-af8b-7b6e4fc0cb39
    ```

1. Create a VolumeAttachment which attaches the underlying PV to NodeB.
    ```yaml
    apiVersion: storage.k8s.io/v1
    kind: VolumeAttachment
    metadata:
      name: test-va-2
    spec:
      attacher: driver.longhorn.io
      nodeName: ryao-161-w2-218e6fb3-c4gcn
      source:
        persistentVolumeName: pvc-50930ced-f65d-4cc4-af8b-7b6e4fc0cb39
    ```

1. Update the longhorn to `master-head`.
1. Notice that the volume is NOT automatically upgraded.
1. Detach the volume from NodeB. The kubectl command completes successfully and the VolumeAttachment goes away.
1. Wait a few seconds and notice that the volume is successfully automatically upgraded.
1. Detach the volume from NodeA. The kubectl command completes successfully and the VolumeAttachment goes away.


**Result Passed**
1. Upgrading from `v1.6.0` to `master-head` passed.
2. Upgrading from `v1.6.x-head` to `master-head` passed.
