### ISSUE TITLE
[BUG] error on upgrading longhorn-manager from 1.5.3 to 1.6.0

### ISSUE THREAD

**Issue by ctraber** [longhorn/longhorn#7834]
## Describe the bug

lognhorn-manager pods not starting after helm upgrade
`helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --version 1.6.0`

## To Reproduce

run helm upgrade

## Expected behavior

longhorn manager updated to 1.6.0 and running

## Error message in longhorn-manager pod:

```

Incorrect Usage: flag provided but not defined: -upgrade-version-check

NAME:
   longhorn-manager daemon - 

USAGE:
   longhorn-manager daemon [command options] [arguments...]

OPTIONS:
   --engine-image value                  Specify Longhorn engine image
   --instance-manager-image value        Specify Longhorn instance manager image
   --share-manager-image value           Specify Longhorn share manager image
   --backing-image-manager-image value   Specify Longhorn backing image manager image
   --support-bundle-manager-image value  Specify Longhorn support bundle manager image
   --manager-image value                 Specify Longhorn manager image
   --service-account value               Specify service account for manager
   --kube-config value                   Specify path to kube config (optional)
   
time="2024-02-02T19:40:51Z" level=fatal msg="Critical error: flag provided but not defined: -upgrade-version-check" func=main.main file="main.go:77"
Incorrect Usage: flag provided but not defined: -upgrade-version-check```

**Comment by PhanLe1010** [comment]
`flag provided but not defined: -upgrade-version-check`, looks like the flag should be `--upgrade-version-check` instead? 

Can you provide the output from `helm template` command?

**Comment by ctraber** [comment]
Here the longhorn-manager part.

seems to be ok `--upgrade-version-check`

```
---
# Source: longhorn/templates/daemonset-sa.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: longhorn
    helm.sh/chart: longhorn-1.6.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.6.0
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: longhorn
        helm.sh/chart: longhorn-1.6.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.6.0
        app: longhorn-manager
    spec:
      containers:
      - name: longhorn-manager
        image: longhornio/longhorn-manager:v1.6.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - "longhornio/longhorn-engine:v1.6.0"
        - --instance-manager-image
        - "longhornio/longhorn-instance-manager:v1.6.0"
        - --share-manager-image
        - "longhornio/longhorn-share-manager:v1.6.0"
        - --backing-image-manager-image
        - "longhornio/backing-image-manager:v1.6.0"
        - --support-bundle-manager-image
        - "longhornio/support-bundle-kit:v0.0.33"
        - --manager-image
        - "longhornio/longhorn-manager:v1.6.0"
        - --service-account
        - longhorn-service-account
        - --upgrade-version-check
        ports:
        - containerPort: 9500
          name: manager
        - containerPort: 9501
          name: conversion-wh
        - containerPort: 9502
          name: admission-wh
        - containerPort: 9503
          name: recov-backend
        readinessProbe:
          httpGet:
            path: /v1/healthz
            port: 9501
            scheme: HTTPS
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: longhorn
          mountPath: /var/lib/longhorn/
          mountPropagation: Bidirectional
        - name: longhorn-grpc-tls
          mountPath: /tls-files/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: longhorn
        hostPath:
          path: /var/lib/longhorn/
      - name: longhorn-grpc-tls
        secret:
          secretName: longhorn-grpc-tls
          optional: true
      priorityClassName: "longhorn-critical"
      serviceAccountName: longhorn-service-account
  updateStrategy:
    rollingUpdate:
      maxUnavailable: "100%"
---

```
