### ISSUE TITLE
[BUG] fsGroup does nothing for ReadWriteOncePod

### ISSUE THREAD

**Issue by btrepp** [longhorn/longhorn#7849]
## Describe the bug

A pvc created with access mode ReadWriteOncePod
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Mi
```

Does not respect/do anything with 

```
fsGroup: 1000
```

Volumes are mounted as root, so un-useable for pods running as non-root.

Doing nothing but change to ReadWriteOnce, solves the issue, but doesn't not give the guarantees of readwriteoncepod

## To Reproduce

1. Create a PVC with ReadWriteOncePod
2. Use this in a non-root deployment and set fsGroup
3. Exec into the pod, observe the mount is owned by root

fsGroup is ignored
## Expected behavior

fsGroup updates ownership similar to ReadWriteOnce

## Environment

 - Longhorn version: 1.60
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: talons
   - Number of control plane nodes in the cluster:3
   - Number of worker nodes in the cluster:2
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

This may actually be a bug in Kubernetes itself?, though I am unsure about the specifics, fsGroup seems to be related a lot to CSI drivers, so raising here.

**Comment by james-munson** [comment]
It is surprising that the volume could be created at all.  The access mode `ReadWriteOncePod` is not recognized by Longhorn, and would be expected to be rejected by the validating webhook.

**Comment by yardenshoham** [comment]
@james-munson I see it as follows:

The volume is created in this line:

https://github.com/longhorn/longhorn-manager/blob/2ec649c35486d782731982c9dff1db41c9031c99/csi/controller_server.go#L228

The log just before it is 
```go
log.Infof("Creating a volume by API client, name: %s, size: %s, accessMode: %v, dataEngine: %v", vol.Name, vol.Size, vol.AccessMode, vol.DataEngine)
```

When I apply the PVC from the report, this line is printed as:
```
time="2024-02-05T19:56:00Z" level=info msg="Creating a volume by API client, name: pvc-0270e0de-ae0a-4d10-9df5-a3b4b134d9a1, size: 104857600, accessMode: , dataEngine: v1" func="csi.(*ControllerServer).CreateVolume" file="controller_server.go:226" component=csi-controller-server function=CreateVolume
```

So `AccessMode` is an empty string. Then in the [mutator](https://github.com/longhorn/longhorn-manager/blob/2ec649c35486d782731982c9dff1db41c9031c99/webhook/resources/volume/mutator.go#L80) we have the code deciding the longhorn access mode:

```go
	if string(volume.Spec.AccessMode) == "" {
		accessModeFromBackup := longhorn.AccessModeReadWriteOnce
                ...
		patchOps = append(patchOps, fmt.Sprintf(`{"op": "replace", "path": "/spec/accessMode", "value": "%s"}`, string(accessModeFromBackup)))
	}
```

So the validating webhook just sees it as `rwo`.

**Comment by ChristianCiach** [comment]
Today we updated longhorn from v1.7.3 to v1.9.2 and this seems to be working correctly now:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: docker.io/library/busybox:latest
        args: ["sleep", "infinity"]
        volumeMounts:
        - name: test-volume
          mountPath: /mnt/test
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: test-pvc
      securityContext:
        fsGroup: 10099
        fsGroupChangePolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn

```

Inside the container:

```
/ # id
uid=0(root) gid=0(root) groups=0(root),10(wheel),10099
/ # stat /mnt/test/
  File: /mnt/test/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 850h/2128d	Inode: 2           Links: 3
Access: (2775/drwxrwsr-x)  Uid: (    0/    root)   Gid: (10099/ UNKNOWN)

```
