### ISSUE TITLE
Upgrade longhorn-manager failing when updating to 1.6.0

### ISSUE THREAD

**Issue by jrocha25** [longhorn/longhorn#7852]
## Describe the bug

I currently have longhorn 1.5.3 installed, using helm:

```bash
helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.5.3 -f k8s/longhorn/values.yaml
```
I have upgraded from version 1.5.1 into 1.5.3, with no problems.

When also using helm to upgrade to version 1.6.0, using helm:

```bash
helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.6.0 -f k8s/longhorn/values.yaml
```

I get the following error from the longhorn managers containers:

```
Incorrect Usage: flag provided but not defined: -upgrade-version-check

NAME:
   longhorn-manager daemon - 

USAGE:
   longhorn-manager daemon [command options] [arguments...]

OPTIONS:
   --engine-image value                  Specify Longhorn engine image
   --instance-manager-image value        Specify Longhorn instance manager image
   --share-manager-image value           Specify Longhorn share manager image
   --backing-image-manager-image value   Specify Longhorn backing image manager image
   --support-bundle-manager-image value  Specify Longhorn support bundle manager image
   --manager-image value                 Specify Longhorn manager image
   --service-account value               Specify service account for manager
   --kube-config value                   Specify path to kube config (optional)
   
time="2024-02-05T15:03:29Z" level=fatal msg="Critical error: flag provided but not defined: -upgrade-version-check" func=main.main file="main.go:77"
```
The containers keep crashing and restarting.

I have read the documentation and [this upgrade is supported](https://longhorn.io/docs/1.6.0/deploy/upgrade/longhorn-manager/)

Am I doing something wrong?

## To Reproduce

Install longhorn, with helm, with version 1.5.1. Upgrade into 1.5.3, using the helm upgrade command. Upgrade into 1.6.0, using the helm upgrade command.

## Expected behavior

The upgrade should successfully upgrade.

## Support bundle for troubleshooting

I get an error when trying to access the website
![image](https://github.com/longhorn/longhorn/assets/51287481/855aca8b-d8f2-48d7-8a40-143d04d0dd50)

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.15.0-91-generic
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 1Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 13

**Comment by innobead** [comment]
Which page you accessed is broken? This should be related to the doc folder structure change for 1.6.0.

Whats the content of your values.yaml?

@ejweber Please help follow up with this.

**Comment by innobead** [comment]
cc @jillian-maroket

**Comment by james-munson** [comment]
The initial symptom is identical to that in https://github.com/longhorn/longhorn/issues/7834

**Comment by derekbit** [comment]
Upgrade using the old value file

```
image:
  longhorn:
    engine:
      repository: longhornio/longhorn-engine
      tag: v1.5.3
    manager:
      repository: longhornio/longhorn-manager
      tag: v1.5.3
    ui:
      repository: longhornio/longhorn-ui
      tag: v1.5.3
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: v1.5.3
    shareManager:
      repository: longhornio/longhorn-share-manager
      tag: v1.5.3
    backingImageManager:
      repository: longhornio/backing-image-manager
      tag: v1.5.3
    supportBundleKit:
      repository: longhornio/support-bundle-kit
      tag: v0.0.27
```
