### ISSUE TITLE
[IMPROVEMENT] RWX volume scheduling

### ISSUE THREAD

**Issue by mazocode** [longhorn/longhorn#7872]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The RWX functionality is hardly usable for us because the share-manager does not honor the storage classes nodeSelector, topology, nor any other nodeSelector configured. This means that it gets scheduled on nodes that are not suitable for this kind of workload or do not match the requirements. In addition, placing it randomly might not be beneficial to the traffic flow.

## Describe the solution you'd like

Add a nodeSelector derived from storage class topolgy configuration or nodeSelector tag. 

## Describe alternatives you've considered

So far I could not find a workaround.

## Additional context

RWX storage class example

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: driver.longhorn.io
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: storage-provisioning/longhorn
    values:
    - ""
metadata:
  name: rep2x-rwx-hdd-fra4-b1c
parameters:
  diskSelector: hdd
  nfsOptions: vers=4.1,noresvport,softerr,timeo=600,retrans=5
  nodeSelector: fra4-b1c
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```

Neither topology nor nodeSelector tag gets honored when scheduling the share-manager pod.
