### ISSUE TITLE
[BUG] Volumes stuck upgrading after 1.5.3 -> 1.6.0 upgrade.

### ISSUE THREAD

**Issue by Eilyre** [longhorn/longhorn#7887]
## Describe the bug

Upgraded the system from version 1.5.3 to 1.6.0 today, to get around the RWX bug. Got to the part of upgrading engines through UI. Did that to all volumes. The amount of replicas went sky high, and the volumes are stuck in the upgrading state.

As there was a volume stuck detaching, I thought restarting the instance manager responsible for it would maybe break it out. It did not, and made things so-so much worse. Now there's even more volumes stuck detaching, all the volumes are declared degraded, and rebuilding replicas won't happen. I cannot now rollback the volumes either, with the error: `cannot do live upgrade for a unhealthy volume`

## To Reproduce

Not sure if it's reproducible.

## Expected behavior

I've done this upgrade method from longhorn version 1.0.2. I had expected it to work the same way, as it did before.

## Support bundle for troubleshooting

Support bundle attached.

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): All of them.
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubeadm, 1.27.4
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Flatcar, latest
   - Kernel version: 6.1.73
   - CPU per node: 128 cores
   - Memory per node: 512 GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 100 gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: ~160

## Additional context

This is a production system, so I am currently fairly worried.

**Comment by ejweber** [comment]
Hello @Eilyre. I am not able to find the support bundle. Can you post the link or send it along to longhorn-support-bundle@suse.com?

**Comment by ejweber** [comment]
So far, I think it has something to do with this (repeated) log:

```
2024-02-07T21:52:16.735525796Z E0207 21:52:16.735294       1 instance_manager_controller.go:1535] failed to update instance map for instance manager instance-manager-2e8a523d8175db7f11d2701a4ffefc33: InstanceManager.longhorn.io "instance-manager-2e8a523d8175db7f11d2701a4ffefc33" is invalid: [status.instanceReplicas.pvc-ecce39fb-7606-40ee-a58a-7cd6a15965c0-r-e89c99fe.status.conditions: Invalid value: "null"
```

We may be stuck because the instance manager controller cannot correctly reflect the status of engines and replicas.

This is a new field in v1.6.0, but so far I am not able to intentionally reproduce this behavior.

https://github.com/longhorn/longhorn-manager/blob/edf23eddc3b6c307031eaa770c3d312c963f25a5/k8s/pkg/apis/longhorn/v1beta2/instancemanager.go#L126-L127

cc @ChanYiLin

**Comment by james-munson** [comment]
> Upgraded the system from version 1.5.3 to 1.6.0 today, to get around the RWX bug.
What issue number is that?

**Comment by Eilyre** [comment]
> > Upgraded the system from version 1.5.3 to 1.6.0 today, to get around the RWX bug.
> 
> What issue number is that?

This one: https://github.com/longhorn/longhorn/issues/7183

**Comment by Eilyre** [comment]
@ejweber Do you think a node or full cluster restart would help the instance manager controllers? 

The logline you pointed out refers to an instance manager with image version 1.5.3. Does that one need to be able to handle the new field? Also, replicas themselves have the status.condition fields nicely filled out.

**Comment by ejweber** [comment]
I am not sure yet, but I think that may also be ineffective. 

I cannot reproduce this behavior in my cluster and it is not seen by the upgrade tests in the CI either. It appears schema validation in the API server is rejecting these update requests, but I'm not sure why that would be the case in your cluster and not others. Are you aware of any cluster hardening you have in place that might affect this behavior?

The issue seems pretty similar to https://github.com/longhorn/longhorn/issues/3352, though that one is very old. The fix for it was to make some map fields nullable and to better ensure we submitted empty objects instead of nil to the Go Kubernetes client. Like the current issue, that one only seemed to be encountered in some clusters/versions.

This is my preferred attempt at a temporary fix. Unfortunately, I cannot validate it without being able to reproduce the issue.

```
kubectl edit crd instancemanagers.longhorn.io
```

Edit it in the following locations so that `nullable: true`:

```
              instanceEngines:
                additionalProperties:
                  properties:
                    spec:
                      properties:
                        backendStoreDriver:
                          description: 'Deprecated: Replaced by field `dataEngine`.'
                          type: string
                        dataEngine:
                          type: string
                        name:
                          type: string
                      type: object
                    status:
                      properties:
                        conditions:
                          additionalProperties:
                            type: boolean
                          nullable: true
                          type: object
						  
              instanceReplicas:
                additionalProperties:
                  properties:
                    spec:
                      properties:
                        backendStoreDriver:
                          description: 'Deprecated: Replaced by field `dataEngine`.'
                          type: string
                        dataEngine:
                          type: string
                        name:
                          type: string
                      type: object
                    status:
                      properties:
                        conditions:
                          additionalProperties:
                            type: boolean
                          nullable: true
                          type: object
						  
              instances:
                additionalProperties:
                  properties:
                    spec:
                      properties:
                        backendStoreDriver:
                          description: 'Deprecated: Replaced by field `dataEngine`.'
                          type: string
                        dataEngine:
                          type: string
                        name:
                          type: string
                      type: object
                    status:
                      properties:
                        conditions:
                          additionalProperties:
                            type: boolean
                          nullable: true
                          type: object
```

**Comment by ejweber** [comment]
This looks like the only map field in status that is not nullable (no map fields in specs are nullable, but I think that probably makes sense). So it's probably a mistake on our part not to make it nullable as well. If the modification gets you unstuck, we need to:

- [ ] Investigate why we don't get this error in CI testing.
- [ ] Probably make the field nullable.

**Comment by Eilyre** [comment]
I am not aware of any non-standard hardening applied to Longhorn. We use Kyverno + PodSecurity + Network policies, but I have kept the `longhorn-system` out of those automated rules, and checking now, I can't find anything that would interfere.

I'll try your solution and get back to you, thank you.

**Comment by ejweber** [comment]
> We use Kyverno + PodSecurity + Network policies, but I have kept the longhorn-system out of those automated rules, and checking now, I can't find anything that would interfere.

The validating webhook configurations for this was in the support bundle, and I also didn't see anything particularly interesting. It seems more likely that your API server itself is responding differently than mine. Not sure why.

**Comment by Eilyre** [comment]
This change seems to have woken the whole Longhorn up, all the volumes started replicating AND upgrading! The in-progress volumes got either attached or detached, and degraded volumes are turning into healthy. Thank you so so much!

Should I make this a permanent patch for my environment, or do you think this is a one-off issue?

**Comment by Eilyre** [comment]
@ejweber As information, some of the volumes rebuilt nicely, but some are still stuck perpetually upgrading. Thankfully it seems that restarting the workload helps it finish rebuilding.

**Comment by ejweber** [comment]
> Should I make this a permanent patch for my environment, or do you think this is a one-off issue?

I would leave it for now. I suspect that we will want to make the change official in the next version of Longhorn, but I need to investigate a bit more.

> Also, are there any logs/information I could provide, if needed to figure out why this happens in some situations?

Not yet. I am going to experiment with your specific version of Kubernetes and see if I can trigger anything. Hopefully you will be available to answer some additional questions later on if I think of any?

Thanks for opening the issue!

**Comment by Eilyre** [comment]
I'll definitely be available, thank you :)

**Comment by ejweber** [comment]
Unfortunately, I still cannot understand why exactly your cluster hit this issue @Eilyre. According to issues linked to https://github.com/longhorn/longhorn/issues/3352 and the associated Kubernetes PR https://github.com/kubernetes/kubernetes/pull/95423/files, this log message shouldn't be possible in Kubernetes v1.20+. (As far as I can tell from browsing the code and reading changelogs, that code hasn't really been touched since.) We introduced `nullable` to avoid some backwards compatibility issues with clusters older than that. However, you are seeing it in v1.27.4.

I personally tested k3s v1.27.5 and ran the CI against k3s v1.27.4 without any problems..

I'm going to go ahead and put together a PR that adds the missing `nullable` to close this one out. Hopefully if anyone else runs into the problem, they can find this issue and reopen it with additional information.

**Comment by innobead** [comment]
@ejweber lets don't forget to add issues to the upcoming milestone (1.7.0).

**Comment by Eilyre** [comment]
I think there's an underlying problem that caused this problem, and is rearing it's head on our cluster again @ejweber. Attach/detach/deletion operations are getting stuck again, but only when the volume needs to attach to another node.

The replicas stay in a weird state: 
![image](https://github.com/longhorn/longhorn/assets/6998508/49e89c0f-76b6-4e87-8c86-798ba497bc4d)

The errors in logs are very similar as before: `Failed to get engine proxy of pvc-58297811-5dc4-4ac3-944d-056512745d8d-e-a4e533b1 for volume pvc-58297811-5dc4-4ac3-944d-056512745d8d`, but there's also a lot of `Invalid gRPC metadata`.

I sent a new version of support bundle.

**Comment by ejweber** [comment]
Can you go ahead and open a new issue @Eilyre? Feel free to link it back to this one, but I think we're looking at something new and different here.

**Comment by Eilyre** [comment]
Made https://github.com/longhorn/longhorn/issues/7915, thank you.

**Comment by ejweber** [comment]
I appear to have accidentally discovered why your cluster in particular ran into the original issue while taking a look at your new support bundle.

Some Longhorn CRDs have the following field and condition (including `instancemanagers.longhonrn.io`, which caused the issue):

- InstanceManager
- Replica
- Setting
- Engine

```
      preserveUnknownFields: true
      conditions:
        - lastTransitionTime: "2021-09-17T16:46:31Z"
          message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
          reason: Violations
          status: "True"
          type: NonStructuralSchema
```

We ran into some upgrade problems related to this back in `v1.3.0` (https://github.com/longhorn/longhorn/discussions/4198), which we fixed by explicitly setting `spec.preserveUnknownFields: false` for a subset of CRDs. Specifically, we could not set `spec.conversion.webhook` if `spec.preserveUnknownFields: true`. However, we decided NOT to explicitly set `spec.preserveUnknownFields: false` for all CRDs (https://github.com/longhorn/longhorn/pull/4237#issuecomment-1194108732).

Now, the four CRDs mentioned above are not considered to have structural schemas, so field pruning for their resources is not done, and the code mentioned in https://github.com/longhorn/longhorn/issues/7887#issuecomment-1935056902 is not effective. It seems that Longhorn has worked fine like this in your cluster for quite some time, but the introduction of the `nullable: false` field to one of the CRDs caused problems. 

This issue was not detected in CI or reproducible in my cluster because it can only be hit if Longhorn was original installed with `apiextensions.k8s.io/v1beta1` APIs (in `v1.0.2-`) and both Longhorn and Kubernetes were upgraded in a particular order.

I think we should explicitly set `spec.preserveUnknownFields: false` for the seven original `apiextensions.k8s.io/v1beta1` (three are set already). This should prevent the issue for users that originally ran old versions of Longhorn.

In the meantime, can you try to do the following for the four affected CRDs mentioned above @Eilyre?

```
kubectl edit -n longhorn-system crd instancemanagers.longhorn.io

# Find and modify the value for preserveUnknownFields to make it false:
spec:
  conversion:
    strategy: None
  group: longhorn.io
  names:
    kind: InstanceManager
    listKind: InstanceManagerList
    plural: instancemanagers
    shortNames:
    - lhim
    singular: instancemanager
  preserveUnknownFields: false
  scope: Namespaced
```
