### ISSUE TITLE
[BUG][v1.5.x] Recurring job fails to create backup when volume detached

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7937]
## Describe the bug

Running test case `test_recurring_jobs_when_volume_detached_unexpectedly[s3]`, it randomly fails to create backup with error message:
```
proxyServer=10.42.3.8:8501 destination=10.42.2.10:10010: 
failed to backup snapshot recurrin-532a51eb-2fda-4efb-8772-b4c41472eabb to backup-2bde369ad7864927: 
rpc error: code = Unknown desc = failed to get volume 10.42.2.10:10010: rpc error: code = Unavailable 
desc = error reading from server: EOF
```

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6238/consoleFull

![backup](https://github.com/longhorn/longhorn/assets/5709208/80b855ed-0849-4940-a9da-e8cf56d47bd7)

The reproducibility is about `1/10`.

## To Reproduce

Running test case `test_recurring_jobs_when_volume_detached_unexpectedly[s3]` repeatedly.

## Support bundle for troubleshooting

[supportbundle_df8064e0-2445-44fd-9af4-63ed76159e29_2024-02-16T02-11-07Z.zip](https://github.com/longhorn/longhorn/files/14304534/supportbundle_df8064e0-2445-44fd-9af4-63ed76159e29_2024-02-16T02-11-07Z.zip)

## Environment

 - Longhorn version: v1.5.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.4+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@mantissahz Please help check this .

**Comment by mantissahz** [comment]
Hi @yangchiu, 
Will this issue also happen with v1.5.3, v1.5.4-rc1, or v1.5.4-rc2?

**Comment by yangchiu** [comment]
> Hi @yangchiu, Will this issue also happen with v1.5.3, v1.5.4-rc1, or v1.5.4-rc2?

This issue is first found on Feb. 8 with longhorn-manager `485f498`, which is `v1.5.4-rc2`: https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-upgrade-tests-sles-amd64/281/
So I believe it doesn't happen in v1.5.4-rc1 or earlier version.

And I also found this issue in v1.6.x-head on Feb. 9 and master-head on Feb. 7:
https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/34/testReport/junit/tests/test_recurring_job/test_recurring_jobs_when_volume_detached_unexpectedly_s3_/ 
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/812/testReport/tests/test_recurring_job/test_recurring_jobs_allow_detached_volume_s3_/

**Comment by innobead** [comment]
@c3y1huang @mantissahz is out today. Please take a look first. Thanks.

**Comment by innobead** [comment]
@yangchiu is this issue also happening in other branch releases?

**Comment by yangchiu** [comment]
> @yangchiu is this issue also happening in other branch releases?

According to https://github.com/longhorn/longhorn/issues/7937#issuecomment-1947706261, it doesn't. Since it's happening from Feb. 7, the only affected release is v1.5.4.

**Comment by mantissahz** [comment]
I think we should check that the engine is running before we start to backup a snapshot as what the snapshot controller does:

Snapshot controller:
https://github.com/longhorn/longhorn-manager/blob/50acc8136199f5042afcf2b5b3c7285edb9b7820/controller/snapshot_controller.go#L439-L458

```golang
    engine, err := sc.getTheOnlyEngineCRforSnapshotRO(snapshot)
    if err != nil {
        return err
    }


    // newly created snapshotCR by user
    if requestCreateNewSnapshot && !alreadyCreatedBefore {
        if err := sc.handleAttachmentTicketCreation(snapshot, false); err != nil {
            return err
        }
        if engine.Status.CurrentState != longhorn.InstanceStateRunning {
            snapshot.Status.Error = fmt.Sprintf("failed to take snapshot because the volume engine %v is not running. Waiting for the volume to be attached", engine.Name)
            return nil
        }
        err = sc.handleSnapshotCreate(snapshot, engine)
        if err != nil {
            snapshot.Status.Error = err.Error()
            return reconcileError{error: err, shouldUpdateObject: true}
        }
    }
```

Backup controller:
https://github.com/longhorn/longhorn-manager/blob/50acc8136199f5042afcf2b5b3c7285edb9b7820/controller/backup_controller.go#L355-L375
```golang
    if backup.Status.LastSyncedAt.IsZero() && backup.Spec.SnapshotName != "" && !bc.backupInFinalState(backup) {
        volume, err := bc.ds.GetVolume(backupVolumeName)
        if err != nil {
            if !apierrors.IsNotFound(err) {
                return err
            }
            err = fmt.Errorf("Cannot find the corresponding volume: %v", err)
            log.WithError(err).Error()
            backup.Status.Error = err.Error()
            backup.Status.State = longhorn.BackupStateError
            backup.Status.LastSyncedAt = syncTime
            return nil // Ignore error to prevent enqueue
        }

        if err := bc.handleAttachmentTicketCreation(backup, backupVolumeName); err != nil {
            return err
        }

        // Check the engine state is running as the snapshot controller does.

        if backup.Status.SnapshotCreatedAt == "" || backup.Status.VolumeSize == "" {
            bc.syncBackupStatusWithSnapshotCreationTimeAndVolumeSize(volume, backup)
        }
```

**Comment by innobead** [comment]
@mantissahz have you tried the patch for this change you suggested?

**Comment by mantissahz** [comment]
>have you tried the patch for this change you suggested?

Yeah, I tested it last night in my local environment and it seems that the issue was gone but there is a flaky issue happening (the error backup will sometimes be changed to be completed with the progress not 100%.) and I am looking into that.
And running https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6312/console this morning.

**Comment by c3y1huang** [comment]
Talked to @mantissahz and we will investigate more on https://github.com/longhorn/longhorn-engine/commit/55c5c5ad6720d37b3243d3bc649c2619aa8a628d.

**Comment by PhanLe1010** [comment]
Looks like I got  different error on Longhorn v1.5.4-rc3:
`proxyServer=10.42.191.99:8501 destination=10.42.191.99:10010: failed to
    backup snapshot c-00cx94-c844d1f7-a38b-4151-8058-e77e9b2f422e to
    backup-dfeb5dad14aa4e6d: rpc error: code = Unknown desc = failed to create
    backup to  for volume testvol: rpc error: code = Unknown desc = missing
    input parameter`

Error logs from instance manager:
`2024-02-21T23:04:13.127508386Z time="2024-02-21T23:04:13Z" level=error msg="Failed to initialize backup backup-55ef929c06664af9" func="rpc.(*SyncAgentServer).BackupCreate" file="server.go:714" error="missing input parameter"`

**Comment by c3y1huang** [comment]
Proposed solution:

Add a recurring job volume-attachement-ticket for the job. This should prevent unnecessary intermediate detachment during snapshot and backup operations triggered by the recurring backup job.

**Comment by c3y1huang** [comment]
> Looks like I got different error on Longhorn v1.5.4-rc3: `proxyServer=10.42.191.99:8501 destination=10.42.191.99:10010: failed to backup snapshot c-00cx94-c844d1f7-a38b-4151-8058-e77e9b2f422e to backup-dfeb5dad14aa4e6d: rpc error: code = Unknown desc = failed to create backup to for volume testvol: rpc error: code = Unknown desc = missing input parameter`
> 
> Error logs from instance manager: `2024-02-21T23:04:13.127508386Z time="2024-02-21T23:04:13Z" level=error msg="Failed to initialize backup backup-55ef929c06664af9" func="rpc.(*SyncAgentServer).BackupCreate" file="server.go:714" error="missing input parameter"`

We've also discussed this in the local meeting. Maybe we can check again after the [fix](https://github.com/longhorn/longhorn/issues/7937#issuecomment-1958575402).

**Comment by PhanLe1010** [comment]
I still need more investigation but I think I kind of see the root cause of race condition that @c3y1huang also saw at https://github.com/longhorn/longhorn/issues/7937#issuecomment-1956182452: 

**The race condition is that we sometimes mark the volumeattachment ticket as satisfied even though the volume has empty spec.NodeID and has started detaching process.**

This is the flow when I watch the changes of the `volume` and `volumeattachment` object when the issue happen:

First, snapshot controller create a VA ticket for the snapshot:
```
spec:
  attachmentTickets:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
    nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses: {}
```

Then, volume.spec is set to the corresponding node:
```
  nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
```

THe snapshot VA ticket initially not satisfied:
```
spec:
  attachmentTickets:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
      nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
      satisfied: false
```
Then, once the volume is attached
```
  shareState: ""
  state: attached
```

Snapshot VA ticket has satisfied true
```
spec:
  attachmentTickets:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
      nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
      satisfied: true
```
Once the snapshot is created, snapshot controller delete the snapshot VA
```
spec:
  attachmentTickets: {}
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses:
    snapshot-controller-recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180:
      satisfied: true
```
This lead to volume.Spec.NodeID being reset
```
nodeID: ""
```
Note that at this moment the volume still have status.state as attached because the volume has not started to detach the volume yet:
```
  currentNodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  robustness: unknown
  shareEndpoint: ""
  shareState: ""
  state: attached
```
Then a backup VA ticket is created
```
spec:
  attachmentTickets:
    backup-controller-backup-d5dbab0da00b422c:
      nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses: {}
```
Then backup VA ticket is immediate set to have `satisfied: true` **even though the volume is being detached**  with the spec.NodeID empty
```
======= Volume =======
spec:
  nodeID: ""
======= VA =========
spec:
  attachmentTickets:
    backup-controller-backup-d5dbab0da00b422c:
      nodeID: phan-v620-recurring-job-pool2-517146b3-rd427
  volume: longhorn-testvol-plb3ix
status:
  attachmentTicketStatuses:
    backup-controller-backup-d5dbab0da00b422c:
      satisfied: true
```
At this moment, backup controller starts to initiate the backup: 
```
  773: 2024-02-22T03:14:11.675121943Z time="2024-02-22T03:14:11Z" level=info msg="Start creating backup backup-d5dbab0da00b422c" func=backup.DoBackupCreate file="main.go:136" pkg=backup
```
The backup later failed because the volume is in detaching process and it start killing engine process:
```
2024-02-22T03:14:11.759819409Z time="2024-02-22T03:14:11Z" level=info msg="Deleting instance longhorn-testvol-plb3ix-e-0" func="controller.(*InstanceHandler).deleteInstance" file="instance_handler.go:497"
```
This is the error:
```
  4417: 2024-02-22T03:14:12.399654154Z time="2024-02-22T03:14:12Z" level=warning msg="Failed to enable the backup monitor for backup backup-d5dbab0da00b422c" func="controller.(*BackupController).reconcile" file="backup_controller.go:384" backup=backup-d5dbab0da00b422c controller=longhorn-backup error="proxyServer=10.42.184.144:8501 destination=10.42.213.11:10010: failed to backup snapshot recurrin-dd970ef8-4431-49b6-9d6c-fabef7d86180 to backup-d5dbab0da00b422c: rpc error: code = Internal desc = failed to create backup: failed to create backup to s3://backupbucket@us-east-1/backupstore for volume longhorn-testvol-plb3ix: rpc error: code = Unavailable desc = error reading from server: EOF" node=phan-v620-recurring-job-pool2-517146b3-69z6d
```
