### ISSUE TITLE
[IMPROVEMENT] Enable Prometheus metrics of the CSI sidecar components 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7938]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

CSI sidecar component has built-in metrics but it is disabled by default. I think we should enable them to get insights like:
1. How longhorn does it take to create/delete Longhorn PVC
2. How Longhorn does it take to finish attaching Longhorn PVC
3. How Longhorn does it take to mount Longhorn PVC
...

These are the main factors to measure the scalability of the Longhorn control plane during the scalability test. 

For example, when enable the csi attacher metrics, we can get information like this which indicate how long it take to finish attaching a Longhorn PVC
```
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.1"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.25"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.5"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="1"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="2.5"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="5"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="10"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="15"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="25"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="50"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="120"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="300"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="600"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="+Inf"} 9
csi_sidecar_operations_seconds_sum{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume"} 66.816478825
csi_sidecar_operations_seconds_count{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume"} 9
```

## Describe the solution you'd like

We can enable the metrics for CSI sidecar components by adding the flag `--http-endpoint`. For example,
* CSI provisioned [link](https://github.com/kubernetes-csi/external-provisioner#:~:text=%2D%2Dhttp%2Dendpoint%3A%20The%20TCP%20network%20address%20where%20the%20HTTP%20server%20for%20diagnostics%2C%20including%20metrics%20and%20leader%20election%20health%20check%2C%20will%20listen%20(example%3A%20%3A8080%20which%20corresponds%20to%20port%208080%20on%20local%20host).%20The%20default%20is%20empty%20string%2C%20which%20means%20the%20server%20is%20disabled)
* CSI attacher [link](https://github.com/kubernetes-csi/external-attacher#:~:text=%2D%2Dhttp%2Dendpoint%3A%20The%20TCP%20network%20address%20where%20the%20HTTP%20server%20for%20diagnostics%2C%20including%20metrics%20and%20leader%20election%20health%20check%2C%20will%20listen%20(example%3A%20%3A8080%20which%20corresponds%20to%20port%208080%20on%20local%20host).%20The%20default%20is%20empty%20string%2C%20which%20means%20the%20server%20is%20disabled)

**Comment by ChanYiLin** [comment]
Waiting for v1.7.0 to be released, so we can add doc to v1.8.0

**Comment by ChanYiLin** [comment]
| Name | Port |
|---|---|
| longhorn-csi-attacher | 8000 | 
| longhorn-csi-provisioner | 8000 |
| longhorn-csi-resizer | 8000 |
| longhorn-csi-snapshotter | 8000 |

### Reproduction steps
1. Install Longhorn and there will be 4 csi related svc in longhorn-manager
2. Create a PVC to let Longhorn create the Volume
3. Attach the Volume by creating a workload with the PVC
4. ssh into longhorn-manager (or port forward) to curl those svc's to get the metrics (`curl localhost:8000/metrics | grep "csi"`)
5. You will obtain the metrics like example

```
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.1"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.25"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="0.5"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="1"} 0
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="2.5"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="5"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="10"} 3
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="15"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="25"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="50"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="120"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="300"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="600"} 9
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume",le="+Inf"} 9
csi_sidecar_operations_seconds_sum{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume"} 66.816478825
csi_sidecar_operations_seconds_count{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerPublishVolume"} 9
```

### PRs
- longhorn-manager: https://github.com/longhorn/longhorn-manager/pull/2978
- longhorn: https://github.com/longhorn/longhorn/pull/9033
- website: https://github.com/longhorn/website/pull/989

**Comment by PhanLe1010** [comment]
Hello @ChanYiLin 

Could you explain a bit about why we need to create the service for the csi-* deployment? Ref https://github.com/longhorn/longhorn/pull/9033/files#diff-99e43a2d30e3793fcf9e5cee927b4f87b910cfeba11224a06d2d8d0f5b041fa5

**Comment by ChanYiLin** [comment]
Hi @PhanLe1010 
You are right, I forgot Prometheus's PodMonitoring.
Then I think we can remove the services.
WDYT? @derekbit

**Comment by ChanYiLin** [comment]
Hi @PhanLe1010 @derekbit 
I have removed the services: https://github.com/longhorn/longhorn/pull/9516
and fix the content of the doc: https://github.com/longhorn/website/pull/989

Please take a look, thanks

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 1925819).

1. Create a volume, take a snapshot, and expand the volume.
2. Check metrics port:
```
$ kubectl get pods -n longhorn-system -l app=csi-attacher -o yaml | grep -A 5 ports 
      ports:
      - containerPort: 8000
        name: csi-attacher
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-attacher
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-attacher
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log


$ kubectl get pods -n longhorn-system -l app=csi-resizer -o yaml | grep -A 5 ports 
      ports:
      - containerPort: 8000
        name: csi-resizer
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-resizer
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-resizer
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log


$ kubectl get pods -n longhorn-system -l app=csi-provisioner -o yaml | grep -A 5 ports 
      ports:
      - containerPort: 8000
        name: csi-provisioner
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-provisioner
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-provisioner
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log


$ kubectl get pods -n longhorn-system -l app=csi-snapshotter -o yaml | grep -A 5 ports 
      ports:
      - containerPort: 8000
        name: csi-snapshotter
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-snapshotter
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
--
      ports:
      - containerPort: 8000
        name: csi-snapshotter
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
```
3. Check metrics path:
```
$ kubectl logs -l app=csi-attacher -n longhorn-system | grep metricsPath
I1105 01:55:12.328378       1 main.go:195] "ServeMux listening" driver="driver.longhorn.io" address=":8000" metricsPath="/metrics"
I1105 01:55:13.657496       1 main.go:195] "ServeMux listening" driver="driver.longhorn.io" address=":8000" metricsPath="/metrics"
```
4. Install Prometheus operator:
```
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
$ helm repo update
$ helm install prometheus-operator prometheus-community/kube-prometheus-stack
```
5. Create cluster role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - servicemonitors
      - prometheusrules
      - podmonitors
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "watch"]
```
6. Create pod monitor:
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-backend
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: csi-snapshotter-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: csi-snapshotter
  namespaceSelector:
    matchNames:
      - longhorn-system
  podMetricsEndpoints:
    - port: csi-snapshotter
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: csi-resizer-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: csi-resizer
  namespaceSelector:
    matchNames:
      - longhorn-system
  podMetricsEndpoints:
    - port: csi-resizer
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: csi-attacher-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: csi-attacher
  namespaceSelector:
    matchNames:
      - longhorn-system
  podMetricsEndpoints:
    - port: csi-attacher
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: csi-provisioner-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: csi-provisioner
  namespaceSelector:
    matchNames:
      - longhorn-system
  podMetricsEndpoints:
    - port: csi-provisioner
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: csi-provisioner-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: csi-provisioner
  namespaceSelector:
    matchNames:
      - longhorn-system
  podMetricsEndpoints:
    - port: csi-provisioner
      path: /metrics
---
```
7. Create service account and expose Prometheus:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/federate"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
            team: backend
  podMonitorSelector:
    matchLabels:
            team: backend
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    nodePort: 30010
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
```
8. Go to `Prometheus UI (http://52.5.90.181:30010/)-> Status -> Targets`. Verify the corrsponding CSI components metrics are shown: 
![csi](https://github.com/user-attachments/assets/148d2cf1-bc71-4afc-8588-a8e6ede5a2f9)



Or directly port-forward the csi sidecar pod, and curl the metrics:
```
$ kubectl port-forward csi-attacher-6c657b85bb-z2s49 8080:8000 -n longhorn-system
Forwarding from 127.0.0.1:8080 -> 8000
Forwarding from [::1]:8080 -> 8000
Handling connection for 8080
```

```
$ curl localhost:8080/metrics
# HELP csi_sidecar_operations_seconds [ALPHA] Container Storage Interface operation duration with gRPC error code status total
# TYPE csi_sidecar_operations_seconds histogram
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="0.1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="0.25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="0.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="2.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="10"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="15"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="50"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="120"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="300"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="600"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities",le="+Inf"} 1
csi_sidecar_operations_seconds_sum{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities"} 0.000555224
csi_sidecar_operations_seconds_count{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Controller/ControllerGetCapabilities"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="0.1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="0.25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="0.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="2.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="10"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="15"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="50"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="120"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="300"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="600"} 1
csi_sidecar_operations_seconds_bucket{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities",le="+Inf"} 1
csi_sidecar_operations_seconds_sum{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities"} 0.000550379
csi_sidecar_operations_seconds_count{driver_name="driver.longhorn.io",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginCapabilities"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="0.1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="0.25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="0.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="2.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="10"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="15"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="50"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="120"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="300"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="600"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo",le="+Inf"} 1
csi_sidecar_operations_seconds_sum{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo"} 0.00078684
csi_sidecar_operations_seconds_count{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/GetPluginInfo"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="0.1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="0.25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="0.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="1"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="2.5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="5"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="10"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="15"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="25"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="50"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="120"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="300"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="600"} 1
csi_sidecar_operations_seconds_bucket{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe",le="+Inf"} 1
csi_sidecar_operations_seconds_sum{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe"} 0.000923654
csi_sidecar_operations_seconds_count{driver_name="unknown-driver",grpc_status_code="OK",method_name="/csi.v1.Identity/Probe"} 1
# HELP process_start_time_seconds [ALPHA] Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.73077576176e+09
```
