### ISSUE TITLE
Add option to disable  longhorn-support-bundle in Longhorn  Helm chart 

### ISSUE THREAD

**Issue by mk-raven** [longhorn/longhorn#8007]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
For security reason we don`t want to use cluster-admin in helm template:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-support-bundle
  labels: {{- include "longhorn.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: longhorn-support-bundle
  namespace: {{ include "release_namespace" . }}
```
## Describe the solution you'd like

So, it will be important to add options in Helm values disable use longhorn-support-bundle.
For example like this:
```
longhorn-support-bundle:
  disable: true
```
And also add it to template.
