### ISSUE TITLE
[BUG] Missed NodeStageVolume after reboot leads to CreateContainerError

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8009]
## Describe the bug

See https://github.com/harvester/harvester/issues/5109#issuecomment-1959808657 for the original context.

1. A workload pod is running with a mounted Longhorn block volume.
2. The workload's node is unexpectedly shut down.
3. The workload pod is force deleted.
4. The workload controller (e.g. Deployment or KubeVirt) schedules an identical pod to the same node.
5. The node starts again.
6. kubelet calls `NodePublishVolume` for the new workload pod without first calling `NodeStageVolume`.
7. The Longhorn CSI plugin bind mounts the regular file at staging target path (previously used by the deleted pod) to target path and returns success.
8. Containerd notices the target path points to a regular file and not a block device leading to a CreateContainerError.

The root cause is likely https://github.com/kubernetes/kubernetes/issues/120455 and https://github.com/kubernetes/kubernetes/issues/117513 which do not yet have fixes.

We can probably mitigate by extending this logic to block volumes: https://github.com/longhorn/longhorn-manager/blob/edf23eddc3b6c307031eaa770c3d312c963f25a5/csi/node_server.go#L171-L208.

## To Reproduce

1. Install Longhorn `v1.6.0` in a single node `v1.27.10+k3s2` cluster.
2. Deploy the below block volume Deployment. Note that there is a `nodeSelector` that restricts it to a single node. This is required for the reproduce.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-vol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-volume-test
  labels:
    app: block-volume-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: block-volume-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: block-volume-test
    spec:
      restartPolicy: Always
      containers:
      - image: nginx:stable-alpine
        name: block-volume-test
        volumeDevices:
        - devicePath: /dev/longhorn/testblk
          name: block-vol
      volumes:
      - name: block-vol
        persistentVolumeClaim:
          claimName: longhorn-block-vol
      nodeSelector:
        kubernetes.io/hostname: <some_node_name>
```

3. Reboot a node like `ssh root@<node> -- reboot -f`.
4. Immediately force delete the running pod (it seems that the --force is REQUIRED) like `kubectl delete pod --force -l app=block-volume-test`.
5. When the node comes back, one pod is stuck `Terminating` and one is stuck in `CreateContainerError`.

```
eweber@laptop:~/longhorn> k get pod
NAME                                 READY   STATUS                 RESTARTS      AGE
block-volume-test-5b48dc8675-dzdjs   0/1     CreateContainerError   0             19m
block-volume-test-5b48dc8675-ptcpj   0/1     Terminating            0             20m

eweber@laptop:~/longhorn> k describe pod block-volume-test-5b48dc8675-dzdjs
...
  Warning  Failed                 20m                 kubelet            Error: failed to generate container "077471bac793a9e2a372f55190e69e3b0157c628fed5b2afb2dcfa9c35e118f1" spec: failed to generate spec: not a device node
...
```

6. The CSI plugin logs show `NodePublishVolume` calls, but no `NodeStageVolume` call.

NOTE: SOMETIMES the old container remains terminating forever with kubelet logs like the following:

```
Feb 22 20:27:39 eweber-v126-worker-9c1451b4-w6977 k3s[761]: E0222 20:27:39.060142     761 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-32417206-5f63-40da-9cba-2246e72bd542 podName:3db9eacc-b946-435a-b57d-c5073a21af61 nodeName:}" failed. No retries permitted until 2024-02-22 20:29:41.06011305 +0000 UTC m=+2501.699373063 (durationBeforeRetry 2m2s). Error: UnmapVolume.UnmapBlockVolume failed for volume "block-vol" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-32417206-5f63-40da-9cba-2246e72bd542") pod "3db9eacc-b946-435a-b57d-c5073a21af61" (UID: "3db9eacc-b946-435a-b57d-c5073a21af61") : blkUtil.DetachFileDevice failed. globalUnmapPath:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev, podUID: 3db9eacc-b946-435a-b57d-c5073a21af61, bindMount: true: failed to remove file /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/3db9eacc-b946-435a-b57d-c5073a21af61: remove /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/3db9eacc-b946-435a-b57d-c5073a21af61: device or resource busy
```

The situation appears to confuse the kubelet in such a way that it never calls `NodeUnpublishVolume`. Instead, it tries to directly delete the file at `/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/216859ca-090c-4f65-878a-de6d480ba8d3`. Since this file is bind mounted into the publish directory, it cannot.

```
Feb 22 20:47:45 eweber-v126-worker-9c1451b4-w6977 k3s[60644]: W0222 20:47:45.385704   60644 volume_path_handler.go:217] Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/216859ca-090c-4f65-878a-de6d480ba8d3/volumeDevices/kubernetes.io~csi/pvc-32417206-5f63-40da-9cba-2246e72bd542
Feb 22 20:47:45 eweber-v126-worker-9c1451b4-w6977 k3s[60644]: W0222 20:47:45.385812   60644 volume_path_handler.go:180] Warning: Unmap skipped because bind mount does not exist on the path: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/216859ca-090c-4f65-878a-de6d480ba8d3
```

```
root@eweber-v126-worker-9c1451b4-w6977:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices# fuser -v /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/*
                     USER        PID ACCESS COMMAND
/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/216859ca-090c-4f65-878a-de6d480ba8d3:
                     root     kernel mount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-32417206-5f63-40da-9cba-2246e72bd542/3db9eacc-b946-435a-b57d-c5073a21af61
/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/3db9eacc-b946-435a-b57d-c5073a21af61:
                     root     kernel mount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-32417206-5f63-40da-9cba-2246e72bd542/3db9eacc-b946-435a-b57d-c5073a21af61
```

A umount gets things unstuck.

```
root@eweber-v126-worker-9c1451b4-w6977:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices# umount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/3db9eacc-b946-435a-b57d-c5073a21af61
root@eweber-v126-worker-9c1451b4-w6977:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices# fuser -v /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/*
                     USER        PID ACCESS COMMAND
/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-32417206-5f63-40da-9cba-2246e72bd542/dev/216859ca-090c-4f65-878a-de6d480ba8d3:
                     root     kernel mount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-32417206-5f63-40da-9cba-2246e72bd542/3db9eacc-b946-435a-b57d-c5073a21af61
```

## Expected behavior

- Best case: kubelet never calls `NodePublishVolume` without `NodeStageVolume`.
- OK case: Longhorn is able to handle it transparently if `NodeStageVolume` is called without `NodePublishVolume`. (Aiming for this as a resolution to this issue.)
- Technically correct case: Longhorn recognizes that `NodeStageVolume` wasn't called and fails `NodePublishVolume`.

## Support bundle for troubleshooting

See context in https://github.com/harvester/harvester/issues/5109.

## Environment

 - Longhorn version: v1.6.0+
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.27.10+k3s2`
