### ISSUE TITLE
Volume Detach After Add New Volume

### ISSUE THREAD

**Issue by akuscu-smartpulse** [longhorn/longhorn#804]
Here are my infrastructure infos:
1 master 1 slave kubernetes cluster.
I've deployed a mongo statefulset with 1 pod with 250 Gi PVC and redis statefulset with 1 pod 25Gi PVC.Both have 2 replicas.
My physical disk size is is 250 GB and my actual mongo db  size is 27 GB.
Here are my yaml file :

```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0.9
        imagePullPolicy: IfNotPresent
        command:
        - "mongod"
        - "--keyFile"
        - "/data/db/rep01.key"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--auth"
        ports:
        - containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db/
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 250Gi
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        imagePullPolicy: IfNotPresent
        args: ["redis-server","/etc/redis/redis.conf","--requirepass", "mypassword", "--appendonly","yes"]
        ports:
        - containerPort: 6379
          hostPort: 6666
        volumeMounts:
        - name: data
          mountPath: /data/
        - name: conf
          mountPath: /etc/redis/
      volumes:
        - name: conf
          configMap:
            name: redis
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 25Gi
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mailserver
spec:
  selector:
    matchLabels:
      app: mailserver
  serviceName: "mailserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image: analogic.io/mailserver
        imagePullPolicy: Never
        ports:
        - containerPort: 25
          hostPort: 25
          name: a
        - containerPort: 80
          hostPort: 880
          name: b
        - containerPort: 110
          hostPort: 110
          name: c
        - containerPort: 143
          hostPort: 143
          name: d
        - containerPort: 443
          hostPort: 4443
          name: e
        - containerPort: 465
 #         hostPort: 465
          name: h
        - containerPort: 587
          hostPort: 587
          name: f
        - containerPort: 993
          hostPort: 993
          name: g
        - containerPort: 995
          hostPort: 995
          name: i
        - containerPort: 4190
#          hostPort: 4190
          name: j
        volumeMounts:
        - name: data
          mountPath: /myfiles #/data
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 100Gi


```
when i want to add a new statefulset with 100 GB size the mongo volume becoming detached state and one of the replica getting fault state.There is no any effect on the redis.

Here are instance manager logs:
https://paste.ubuntu.com/p/2SZQq72t6Z/

csi logs:
https://paste.ubuntu.com/p/VQ5Nv6SNKQ/

https://paste.ubuntu.com/p/ShTK7RTQ3G/
