### ISSUE TITLE
[IMPROVEMENT] Improve the UX of updating danger zone settings

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8070]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Starting from version 1.6.0, users can update danger zone settings and delay their activation until after all volumes are detached. However, there are user experiences that require improvement:

- It is difficult to determine if the settings have taken effect.
  - The Longhorn system can offer a clearer way to help users understand the current status.

- Following the detachment of all volumes, certain actions such as restarting instance manager pods do not occur quickly, might requiring users to wait for several minutes. To expedite the application of the settings, users need to unset and then set them again.

The improvement is inspired when working https://github.com/longhorn/longhorn/issues/8065 with @cometta.
The two UXs make users confused and not easy to know what is happening.

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by innobead** [comment]
The current setting does not have any status. Could consider adding it to enrich the info or at least have an annotation for the status. `applied` or `satisfied` could be a good name for that status.

[/k8s/pkg/apis/longhorn/v1beta2/setting.go#L14-L20](https://github.com/longhorn/longhorn-manager/blob/5c5566b7c52e447bfb03b45ee2d0554a06375768/k8s/pkg/apis/longhorn/v1beta2/setting.go#L14-L20)
```go
type Setting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// The value of the setting.
	Value string `json:"value"`
}
```

**Comment by innobead** [comment]
This involves a CRD update and isn't a critical improvement, so it's no need to backport.

cc @derekbit

**Comment by derekbit** [comment]
@mantissahz Where are we with this issue?

**Comment by mantissahz** [comment]
>@mantissahz Where are we with this issue?

@derekbit, it should be on `ready for testing` for CLI and UI.

**Comment by yangchiu** [comment]
Testing on master-head (longhorn-manager 2d5d202) with the following steps:

1. Create a deployment to create and attach a volume
2. Create a priority class:
```
# Source: longhorn/templates/priorityclass.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "longhorn-critical-1"
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.6.0-dev
description: "Ensure Longhorn pods have the highest priority to prevent any unexpected eviction by the Kubernetes scheduler under node pressure"
globalDefault: false
preemptionPolicy: PreemptLowerPriority
value: 999999
```

```
kubectl apply -f priority-class.yaml -n longhorn-system
```
3. Modify the danger zone setting `priority-class` to `longhorn-critical-1`:

![danger](https://github.com/user-attachments/assets/fda6f5a2-a777-439e-9bae-676adb4e26c0)

4. The field `Applied` of the setting `priority-class` should be `false`:

```
$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                false     80m
```

5. Scale down the deployment to detach the volume

6. The field `Applied` of the setting still be `false`:

```
$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                false     82m
```

7. Modify the field `applied` of the setting to be `true`:

```
$ kubectl patch setting priority-class -n longhorn-system --type='merge' -p '{"status": {"applied": true}}'
setting.longhorn.io/priority-class patched (no change)
yang@yang:~/Code/automation/longhorn-test$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                false     91m
```

In `step 7`, changing the `applied` field from `false` to `true` has no effect. The setting isn't reconciled, and no Longhorn components are restarted to apply the value.

@mantissahz Could you help confirm if there is anything wrong with the test steps above? Thank you!

**Comment by mantissahz** [comment]
@yangchiu could you try the patch again with the option `--subresource=status`?

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 2d5d202) with the following steps:

1. Install/Upgrade Longhorn and create a deployment to create and attach a volume
2. Create a priority class:
```
# Source: longhorn/templates/priorityclass.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "longhorn-critical-1"
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.6.0-dev
description: "Ensure Longhorn pods have the highest priority to prevent any unexpected eviction by the Kubernetes scheduler under node pressure"
globalDefault: false
preemptionPolicy: PreemptLowerPriority
value: 999999
```

```
kubectl apply -f priority-class.yaml -n longhorn-system
```
3. Modify the danger zone setting `priority-class` to `longhorn-critical-1`:

![danger](https://github.com/user-attachments/assets/fda6f5a2-a777-439e-9bae-676adb4e26c0)

4. The field `Applied` of the setting `priority-class` should be `false`:

```
$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                false     80m
```

5. Scale down the deployment to detach the volume

6. The field `Applied` of the setting still be `false`:

```
$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                false     82m
```

7. Modify the field `applied` of the setting to be `true`:

```
$ kubectl patch setting priority-class -n longhorn-system --type='merge' -p '{"status": {"applied": true}}' --subresource=status
```

8. The setting will be reconciled and the setting will be applied to all Longhorn components (Deployments, Daemonsets, and Longhorn CSI drivers)

```
$ kubectl get settings -n longhorn-system | { head -1; grep priority; }
NAME                                                              VALUE                                              APPLIED   AGE
priority-class                                                    longhorn-critical-1                                true      7m50s

$ kubectl describe pod longhorn-csi-plugin-2gfkf -n longhorn-system
Name:                 longhorn-csi-plugin-2gfkf
Namespace:            longhorn-system
Priority:             999999
Priority Class Name:  longhorn-critical-1
Service Account:      longhorn-service-account
Node:                 ip-10-0-1-241/10.0.1.241
Start Time:           Tue, 03 Dec 2024 13:46:29 +0800
Labels:               app=longhorn-csi-plugin
                      controller-revision-hash=7cdb447cc6
                      pod-template-generation=2
```
