### ISSUE TITLE
Request: Declare all workloads in YAML

### ISSUE THREAD

**Issue by ChrisScottThomas** [longhorn/longhorn#808]
Currently when deploying Longhorn, you can only declare the state of:

```
longhorn-manager
longhorn-ui
longhorn-driver-deployer
```

yet we have the following daemonsets:

```
engine-image-ei-3827e67c
longhorn-csi-plugin
```

and the following deployments:

```
csi-provisioner
csi-attacher
```

that can not be declared in YAML.

Is there a reason why this is so?  Not being able to control everything that is deployed via YAML doesn't satisfy the requirements of most Kubernetes users.

This leads to problems, when using config management such as Kustomize. As the workloads that are spawned by others, do not receive changes applied like the ones declared in YAML.  
eg. Using something simple as image tag management in customize:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: longhornio/longhorn-manager
  newTag: v0.6.2
- name: longhornio/longhorn-ui
  newTag: v0.6.2
```

this only gets applied to
```
containers:
        - name: longhorn-driver-deployer
          image: longhornio/longhorn-manager:v0.6.0
```

 but not:
```
command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - longhornio/longhorn-manager:v0.6.0
          ...
```

Which creates mismatches, and requires manual changes.
