### ISSUE TITLE
[IMPROVEMENT] Cannot read/write to block volume when the container is run as non-root

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8088]
## Reproduce

Deploy a PVC with block volumeMode and a pod using that PV with non-root user:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: block-volume-test
  namespace: default
spec:
  securityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    supplementalGroups:
    - 6
  containers:
    - name: block-volume-test
      image: ubuntu:20.04
      command: ["sleep", "360000"]
      imagePullPolicy: IfNotPresent
      volumeDevices:
        - devicePath: /dev/longhorn/testblk
          name: block-vol
  volumes:
    - name: block-vol
      persistentVolumeClaim:
        claimName: longhorn-block-vol
```
Exec into the pod and try to read from the block device. Hitting the permission error:
```
I have no name!@block-volume-test:/$ dd if=/dev/longhorn/testblk bs=1M count=100 
dd: failed to open '/dev/longhorn/testblk': Permission denied
I have no name!@block-volume-test:/$ ls -l /dev/longhorn/testblk 
brw-rw---- 1 root root 8, 0 Feb 29 00:32 /dev/longhorn/testblk
```

## Describe the solution you'd like

I am thinking about 3 investigation directions in the decreasing order of preference:
1. First, is there anyways to tell CSI flow to change ownership of the block device so that the non-root user can use it?
2. If method 1 is not possible, is adding an init container to change the ownership of the block device the best practice?
3. Lastly, is adding the user to root group (group 0) like the one below an acceptable solution?
    ```yaml
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 6
        - 0
    ```

**Comment by PhanLe1010** [comment]
## Analysis 

Our initial investigation directions include the 2 below ideas:
1. Investigate whether there is any way/parameters to change the group of the mounted device (at `/dev/longhorn/testblk` of the example above)
1. Investigate whether we should hard-coding group 6 to the mounted device.

The following are the outcomes of the investigations:

### 1. There is no way in Kubelet flow to change the ownership of the mounted device

Kubernetes has mechanism to change the ownership of a filesystem PVC (as the below PVC) to the same group as the `pod.spec.securityContext.fsGroup` ([link to doc](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)):
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```

However, Kubernetes and CSI flow has no way to change ownership of the block volume mode PVC like this one:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-block-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```
This is confirmed by looking at the code of kubelet:
* This is the location that kubelet make the ownership change [SetVolumeOwnership](https://github.com/kubernetes/kubernetes/blob/2ec63e0d28951bb525a5bce0d9459afa1c71c0bd/pkg/volume/csi/csi_mounter.go#L338-L339) 
* Is it called by [GenerateMountVolumeFunc](https://github.com/kubernetes/kubernetes/blob/2ec63e0d28951bb525a5bce0d9459afa1c71c0bd/pkg/volume/util/operationexecutor/operation_generator.go#L537) 
* Which is only executed when the PVC has Filesystem mode: [link](https://github.com/kubernetes/kubernetes/blob/2ec63e0d28951bb525a5bce0d9459afa1c71c0bd/pkg/volume/util/operationexecutor/operation_executor.go#L945-L950)

### 2. DelegateFSGroupToCSIDriver feature gate

There is a way to ask Kubelet to give up the handling of FSGroup ownership modification and delegate the task to Longhorn CSI plugin https://kubernetes-csi.github.io/docs/support-fsgroup.html#delegate-fsgroup-to-csi-driver. This way, Longhorn CSI plugin can understand and change the ownership of the block mode PVC by ourselves. 

However, I don't prefer this approach because:
1. Now that Kubelet delegate the work to Longhorn CSI plugin, Longhorn CSI plugin would have to handle the whole FSGroup ownership modification logic of Kubelet including the recursive permission changes which are kind of complex and unnecessary. 
1. This feature is only enabled by default since Kubernetes >= 1.23 so maybe we would have to raise the min Kubernetes version 


Additionally, if Kuberlet decides to not change ownership of block volume mode PVC and no one is yelling yet, then I feel that this need is not common. **Therefore, I think that we should not pursue the 1st investigation idea (Investigate whether there is any way/parameters to change the group of the mounted device)**

### 3. Investigate whether we should hard-coding group 6 to the mounted device

From my investigation, ID 6 (gid 6) is typically associated with the "disk" group. This "disk" group usually has access to manage disk-related tasks, such as mounting and unmounting disks or partitions. Ref:
1. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/deployment_guide/s1-users-groups-standard-groups
2. http://www.yolinux.com/TUTORIALS/LinuxTutorialManagingGroups.html#:~:text=The%20typical%20Linux%20installation%20will%20come%20with%20some%20exisitng%20standard%20groups%3A%20(See%20/etc/group)%0AGroup%20IDs%20of%20less%20than%20500%20are%20reserved%20for%20user%20IDs%20employed%20by%20the%20operating%20system%20or%20its%20services.
3. https://unix.stackexchange.com/questions/156473/reasons-behind-the-default-groups-and-users-on-linux#:~:text=disk%20is%20the%20group%20that%20owns%20most%20disk%20drive%20devices

So users who consume the block volume mode PVC usually run as root or added into group ID 6. 

So if Longhorn block device is added to added into group ID 6 by default (instead of the root group currently), we would allow these users to consume the block volume without having to change the ownership of the block volume.

Another supporting factor for this approach is that Kasten mentions other solutions like EKS, GKE, Azure, DO, OCP (under AWS/GKE) is punting the block volume PVC in group 6 by default. 

Therefore, I think it makes sense for Longhorn to put the block device into group 6 by default. 

### 4. Is there any side effect or regression if we hard-code group 6 to the mounted device by default

When we put the Longhorn block device into group 6 by default, there might be 1 usage which will not work anymore. It is the case when user run pod as non-root user and add the the user to root group (gid 0) like:
```yaml
spec:
  securityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    supplementalGroups:
    - 0
```
In this case, user of this pod cannot access the Longhorn block volume since it is non-root and not belong to the default group id 6 (disk group)
Howerver, I think that this corner case is rare as it doesn't not make much as to run user with non-root but put it into root group. We can add a release note to emphasize this behavior change.

cc @connorkuehl @Vicente-Cheng Do you see any workload in Havester which ron as non-root and have root group?

**Comment by PhanLe1010** [comment]
Thank you very much @Vicente-Cheng ! I creat this ticket in Harvester to keep track of your effort https://github.com/harvester/harvester/issues/5318

**Comment by PhanLe1010** [comment]
## Workaround:

1. Adding an init container to change the ownership of the block device the best practice?
1. OR Adding the user to root group (group 0) like:
    ```yaml
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 0
    ```

**Comment by PhanLe1010** [comment]
Could you help to put this important note to the release note when we release Longhorn @innobead https://github.com/longhorn/website/pull/880/files#diff-eb8f2941d7c6fb529d71387948d6fbb9575bb80d5841799905a1dcc743cd3fa2

**Comment by PhanLe1010** [comment]
## Test plan:

### Case 1: Block PVC - v1 engine - non-root user - group 6
1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: block-volume-test
      namespace: default
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 6
      containers:
        - name: block-volume-test
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into the pod, make sure that read/write to the device at `/dev/longhorn/testblk` works

### Case 2: Block PVC - v1 engine - non-root user - group 0

1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: block-volume-test
      namespace: default
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 0
      containers:
        - name: block-volume-test
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into the pod, make sure that read/write to the device at `/dev/longhorn/testblk` does NOT work

### Case 3: Block PVC - v1 engine - root user - group 0

1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: block-volume-test
      namespace: default
    spec:
      containers:
        - name: block-volume-test
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into the pod, make sure that read/write to the device at `/dev/longhorn/testblk` works


### Case 4: Block PVC - v1 engine - root user - group 5
1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: block-volume-test
      namespace: default
    spec:
      securityContext:
        runAsGroup: 5
        runAsUser: 0
      containers:
        - name: block-volume-test
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into the pod, make sure that read/write to the device at `/dev/longhorn/testblk` works

### Case 5: Block PVC - v1 engine - root user - group 6
1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Block
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: block-volume-test
      namespace: default
    spec:
      securityContext:
        runAsGroup: 6
        runAsUser: 0
      containers:
        - name: block-volume-test
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Exec into the pod, make sure that read/write to the device at `/dev/longhorn/testblk` works

### Case 6: Block PVC - v2 engine
Reapeat case 1 - 5 above but with v2 engine 


### Case 7: Filesystem PVC - v1 engine
1. Deploy this yaml
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-simple-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: longhorn-simple-pod
      namespace: default
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: simple-container
          image: ubuntu:20.04
          command: ["sleep", "360000"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volv
              mountPath: /data
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: longhorn-simple-pvc
    ```
1. Exec into the pod, verify that read/write to the directory `/data` is ok. 
1. Check the ownership by `ls -l /data`, verify that the group id of the directory is 2000

### Case 8: Filesystem PVC - v2 engine
Repate case 7 but with v2 engine PVC
