### ISSUE TITLE
[BUG] Helm: Default settings do not work

### ISSUE THREAD

**Issue by klauserber** [longhorn/longhorn#8145]
## Describe the bug

On a fresh Longhorn install with helm the default settings do not take effect

## To Reproduce

I haved installed longhorn with helm and these values:

```
defaultSettings:
  allowRecurringJobWhileVolumeDetached: enabled
  backupTarget: s3://backup-longhorn-bm-isium-de/
  backupTargetCredentialSecret: longhorn-backup-secret
  recurringJobMaxRetention: 14
  storageMinimalAvailablePercentage: 5
ingress:
  enabled: true
  host: longhorn.bm.dc1.isium.de
  ingressClassName: nginx-internal
persistence:
  defaultDataLocality: best-effort
```

## Expected behavior

The settings should be appear in the Longhorn UI
 
## Support bundle for troubleshooting

[supportbundle_4bdc31e4-aaf6-4450-add0-84e8f7054857_2024-03-09T14-39-19Z.zip](https://github.com/longhorn/longhorn/files/14546644/supportbundle_4bdc31e4-aaf6-4450-add0-84e8f7054857_2024-03-09T14-39-19Z.zip)

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): none
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu
   - Kernel version: 5.15.0-100-generic
   - CPU per node: 8
   - Memory per node: 96 GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 10
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

## Additional context

The Configmap `longhorn-default-setting` was correctly created. But when I dig into the templates of the Chart, there is no other resource, that reference the Configmap. How do this work? Is there anything missing?
