### ISSUE TITLE
manager: Add image pull secret as an option for auto deployed workloads

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#819]
From #812

**Comment by martinounap** [comment]
My recommendation is:

-----------
containers:
      - name: longhorn-manager
        image: rancher.repo.tehik.ee/longhornio/longhorn-manager:v0.6.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - {regisryUrl}/longhornio/longhorn-engine:v0.6.2
        - --manager-image
        - {regisryUrl}/longhornio/longhorn-manager:v0.6.2
-----------

lets add there:

- --registry-secret
- {secretName}

and in:
-----------
containers:
        - name: longhorn-driver-deployer
          image: rancher.repo.tehik.ee/longhornio/longhorn-manager:v0.6.2
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - {regisryUrl}/longhornio/longhorn-manager:v0.6.2
-----------
lets add there:
- --registry-secret
- {secretName}

and in:
-----------
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: CSI_ATTACHER_IMAGE
            value: {regisryUrl}/quay.io/k8scsi/csi-attacher:v0.4.2
          - name: CSI_PROVISIONER_IMAGE
            value: {regisryUrl}/quay.io/k8scsi/csi-provisioner:v0.4.2
          - name: CSI_DRIVER_REGISTRAR_IMAGE
            value: {regisryUrl}/quay.io/k8scsi/driver-registrar:v0.4.1     
-----------
lets add:
- name: CSI_REGISTRY_SECRET
  value: {secretName}

Then we could have nice Air Gap installation :)

**Comment by yasker** [comment]
@martinounap 👍this looks good.

**Comment by vispatster** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: longhorn-driver-deployer
  namespace: longhorn-sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - deploy-driver
        - --manager-image
        - $REGURL/longhorn/manager:$TAG
        - --manager-url
        - http://longhorn-backend:9500/v1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CSI_ATTACHER_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        - name: CSI_PROVISIONER_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        - name: CSI_DRIVER_REGISTRAR_IMAGE
          value: $URL/longhorn/$NAME:$TAG
        image:  $URL/longhorn/manager:$TAG
        imagePullPolicy: Always
        name: longhorn-driver-deployer
      initContainers:
      - command:
        - sh
        - -c
        - while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1)
          != "200" ]; do echo waiting; sleep 2; done
        image: $URL/longhorn/manager:$TAG
        imagePullPolicy: IfNotPresent
        name: wait-longhorn-manager
      restartPolicy: Always
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
```
I have been trying to use internal registry. The following deployment keeps taking public image URL. 

Would any other config be required to use private reg URLs? 


![image](https://user-images.githubusercontent.com/6172619/74787303-d4553e00-527c-11ea-90be-05a0a2b61b4c.png)
