### ISSUE TITLE
[BUG] Can't use longhorn with Generic ephemeral volumes

### ISSUE THREAD

**Issue by mueller-tobias** [longhorn/longhorn#8198]
## Describe the bug

We try to rollout open project via it's helm chart. The helm chart is utilizing [Generic ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes). According to the kubernetes documentation this should work out of the box with existing storage providers.

But when i try the example the pod will not be created. The volume is created correctly in longhorn and also the attach is correct, but the setup of the pod fails.

```
MountVolume.SetUp failed for volume "pvc-60ea3b05-bd1b-40ae-b647-4898fc37c3a5" : rpc error: code = Aborted desc = no Pending workload pods for volume pvc-60ea3b05-bd1b-40ae-b647-4898fc37c3a5 to be mounted: map[]
```

## To Reproduce

Use the example from the Kubernetes Documentation to rollout a pod with a generic ephermal volume:

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-app
spec:
  containers:
    - name: my-frontend
      image: busybox:1.28
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "longhorn"
            resources:
              requests:
                storage: 1Gi
```

## Expected behavior

The pod should be created and running.

## Support bundle for troubleshooting

[supportbundle_108a26af-f02f-4163-8c3f-a9bf48c65937_2024-03-18T09-36-04Z.zip](https://github.com/longhorn/longhorn/files/14633999/supportbundle_108a26af-f02f-4163-8c3f-a9bf48c65937_2024-03-18T09-36-04Z.zip)

## Environment

 - Longhorn version: 1.6.0.
 - Impacted volume (PV): pvc-255d1fe4-61ad-4aa2-8062-54b3b4575c60
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.27.10 +rke2r1
   - Number of control plane nodes in the cluster: 5 (3 etcd, 2 cp)
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.15.0-100-generic
   - CPU per node: 8
   - Memory per node: 32 GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware
 - Number of Longhorn volumes in the cluster: 5
