### ISSUE TITLE
[BUG] engine in "deploying" state when there are taints.

### ISSUE THREAD

**Issue by migs35323** [longhorn/longhorn#8199]
## Describe the bug

similar to #1874

I did upgrade longhorn from 1.5.x to 1.6.0
my control planes have the common taint `node-role.kubernetes.io/control-plane:NoSchedule`
I did add tolerations in the chart for the longhorn components, since i am ok with allowing to run critical components in these nodes.
when the new engine was deployed the UI interface is showing "deploying" and the list of nodes in "NodeDeploymentMap" shows "<tainted_node_name>: false" 

I see in the mentioned issue that it's a decision that not all nodes should require to have the engine running, this makes sense, if the node is disabled why run the engine there.
so i am creating issue for this UI/CRD, it can make people think it's failed the deployment or something is stuck. it is not showing the usual "deployed" green state and in the CRD theese nodes exist in the list.

## To Reproduce

have cluster with taints,
add tolerations in the chart for the taint.
upgrade longhorn with engines.

![image](https://github.com/longhorn/longhorn/assets/92784574/48f1426d-d178-49c1-a1d9-5f2bb49bec5f)

**Comment by ejweber** [comment]
I was able to reproduce this behavior by setting the toleration for user-deployed components, but NOT system-deployed components. https://longhorn.io/docs/1.6.0/advanced-resources/deploy/taint-toleration/

I set the following:

```
longhornManager:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

longhornDriver:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

longhornUI:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
```

But I did NOT set the following:

```
  # -- Taint or toleration for system-managed Longhorn components.
  taintToleration: ~
```

As a result, longhorn-manager runs on my master node and creates a nodes.longhorn.io object, but the engine image cannot run on my master node. This leads to the symptoms you are describing:

```
    nodeDeploymentMap:
      eweber-v126-master-7ccf4f43-spxmg: false
      eweber-v126-worker-9c1451b4-kgxdq: true
      eweber-v126-worker-9c1451b4-nn4rg: true
      eweber-v126-worker-9c1451b4-w6977: true
    state: deploying
```

When I add the toleration for system-managed Longhorn components, the situation cannot immediately resolve itself, because all volumes must be detached for the setting change to take effect.

```
  # -- Taint or toleration for system-managed Longhorn components.
  taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
```

```
E0318 21:17:12.723401       1 setting_controller.go:208] failed to sync setting for longhorn-system/storage-network: current state prevents this: failed to apply storage-network setting to Longhorn components when there are attached volumes. It will be eventually applied
```

After detaching all volumes, the situation resolved itself.

```
    nodeDeploymentMap:
      eweber-v126-master-7ccf4f43-spxmg: true
      eweber-v126-worker-9c1451b4-kgxdq: true
      eweber-v126-worker-9c1451b4-nn4rg: true
      eweber-v126-worker-9c1451b4-w6977: true
    state: deployed
```

So, I think in your situation, either:

- You set the toleration on user-deployed but not system-deployed components, or
- You set the toleration on both, but some volumes are detached still.

Can you check whether one of these is the case?

This behavior changed recently for https://github.com/longhorn/longhorn/issues/7173. Before, changing a "danger zone setting" would result in the immediate crash of all volumes that were currently attached. Now, we allow the setting to eventually take effect.

IMO it is correct for the engine image to show as it does in the UI until it can be successfully deployed to the node in question, since the node in question cannot successfully function as a Longhorn node without it.

**Comment by migs35323** [comment]
@ejweber probably it's the second option, very likely not every volume was detached,
i did changed in every place to tolerate the control planes (aka master) nodes, 

i have a question, do i need to detach every workload in longhorn, or i can drain/restart nodes evenly for no downtime?

this is my (complete) values.yaml that was last applied:
```
defaultSettings:
  backupTarget: "s3://<redacted>"
  backupTargetCredentialSecret: <redacted>
  taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
longhornManager:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
longhornDriver:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
longhornUI:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

```
