### ISSUE TITLE
[CI] Add` xfstests` (filesystem testing suite) in CI test

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8246]
## What's the CI task to develop? Please describe

We've encountered some filesystem corruption issues such as https://github.com/longhorn/longhorn/issues/8235.
To minimize the likelihood of filesystem corruption, we can integrate the [xfstests](https://github.com/kdave/xfstests), a filesystem testing suite, into our daily CI tasks to find out potential issues.

## Additional context

cc @yangchiu @shuo-wu @innobead

**Comment by yangchiu** [comment]
I created a statefulset running `ubuntu` container which mount a Longhorn volume like:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-statefulset
  serviceName: test-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts:
            - name: pod-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: pod-data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: 'longhorn'
        resources:
          requests:
            storage: 10Gi
```

And set the required variables:
```
export TEST_DIR=/data
export TEST_DEV=/dev/longhorn/pvc-475486e9-6ae7-4740-9773-c69e9cd87997
```
Then run the test:
```
./check
```
The test complained:
```
common/config: TEST_DEV (/dev/longhorn/pvc-475486e9-6ae7-4740-9773-c69e9cd87997) is not a block device or a network filesystem
```

@derekbit Do you have any suggestion? Thank you!

**Comment by yangchiu** [comment]
Test steps:

1. Create a `statefulset` running a `ubuntu` container with a Longhorn volume using `volumeMode: Block`:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-block-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-block-statefulset
  serviceName: test-block-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: test-block-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts: []
          volumeDevices:
            - name: pod-data
              devicePath: /dev/longhorn/longhorn-test-blk
  volumeClaimTemplates:
    - metadata:
        name: pod-data
      spec:
        volumeMode: Block
        accessModes: ['ReadWriteOnce']
        storageClassName: 'longhorn'
        resources:
          requests:
            storage: 10Gi
```

2. Install required packages in the container:
```
# apt update
# apt install -y acl attr automake bc dbench dump e2fsprogs fio gawk \
        gcc git indent libacl1-dev libaio-dev libcap-dev libgdbm-dev libtool \
        libtool-bin liburing-dev libuuid1 lvm2 make psmisc python3 quota sed \
        uuid-dev uuid-runtime xfsprogs linux> -headers-$(uname -r) sqlite3 \
        libgdbm-compat-dev
# apt install -y exfatprogs f2fs-tools ocfs2-tools udftools xfsdump \
        xfslibs-dev
```

3. Format the block device to `xfs`
```
# mkfs.xfs /dev/longhorn/longhorn-test-blk
meta-data=/dev/longhorn/longhorn-test-blk isize=512    agcount=4, agsize=655360 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=2621440, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Discarding blocks...Done.
```

4. Install `xfstest`:
```
# git clone git://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git
# cd xfstests-dev
# make
# make install
```

5. Export required variables:
```
# mkdir /data
# export TEST_DIR=/data
# export TEST_DEV=/dev/longhorn/longhorn-test-blk
```

6. Run the test:
```
# ./check -R xunit
```

7. After the test completed, test log and report will be in `/xfstests-dev/results/check.log` and `/xfstests-dev/results/result.xml`

@derekbit Could you help check if it's the desired way to run the test?
