### ISSUE TITLE
[BUG] RWX volume is hang on Photon Real Time OS

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8253]
## Describe the bug

When there are multiple pods on the same node access a WAX volume and doing IOs. The mount point of the RWX volume inside the pod is frozen and pod cannot read/write 

## To Reproduce

1. Install Photon OS real time flavor https://packages.vmware.com/photon/5.0/GA/iso/photon-rt-5.0-dde71ec57.x86_64.iso 
1. Install K3s and Longhorn 1.6.0 on it
1. Deploy this workload:
    ```
    # Long-running test with prometheus metric exporter to monitor the data
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-1
    spec:
      volumeMode: Filesystem
      storageClassName: longhorn  # replace with your storage class
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: test-workload
      namespace: default
    spec:
      serviceName: test-workload
      replicas: 1
      selector:
        matchLabels:
          app: test-workload
      podManagementPolicy: Parallel
      template:
        metadata:
          labels:
            app: test-workload
        spec:
          nodeName: photon-02 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
          containers:
            - name: kbench-1
              image: phanle1010/kbench:broadcom
              imagePullPolicy: Always
              env:
                - name: MODE
                  value: "random-write-iops"
                - name: OUTPUT
                  value: /test-result/pvc1
                - name: FILE_NAME
                  value: "/pvc1/test.img"
                - name: SIZE
                  value: "1638M" # 80% of the pvc-1's size
                - name: CPU_IDLE_PROF
                  value: "disabled"
                - name: SKIP_PARSE
                  value: "true"
                - name: LONG_RUN
                  value: "true"
                - name: RATE_IOPS
                  value: "1167"
              volumeMounts:
                - name: pvc1
                  mountPath: /pvc1/
                - name: shared-data
                  mountPath: /test-result
            - name: metric-exporter
              image: phanle1010/kbench:broadcom
              imagePullPolicy: Always
              command:
                - metric-exporter
                - -d
                - start
              env:
                - name: DATA_DIR
                  value: /test-result
                - name: VOLUME_ACCESS_MODE
                  value: rwx
                - name: TEST_MODE
                  value: write-only
                - name: RATE_LIMIT_TYPE
                  value: rate-limit
              ports:
                - containerPort: 8080
                  name: metrics
              volumeMounts:
                - name: shared-data
                  mountPath: /test-result
          volumes:
            - name: shared-data
              emptyDir: {}
            - name: pvc1
              persistentVolumeClaim:
                claimName: pvc-1
    ``` 
1. Scale up the stateful set to 6
1. After 2-6 mins, exec into the pods and check that the mount point of RWX is frozen. I.e., running `ls -l /pvc1` is hang

## Expected behavior

Should not hang

## Environment

 - Longhorn version: Longhorn v1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.7+k3s1	
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 4
 - Node config
   - OS type and version: Photon RT OS https://github.com/vmware/photon/wiki/Downloading-Photon-OS#downloading-photon-os-50-ga
   - Kernel version: 6.1.10-10.ph5-rt
   - CPU per node: 64
   - Memory per node: 503GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 20Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1

## Additional context

When I added an Ubuntu node to the cluster and deploy the sts on to ubuntu node, RWX volume is not frozen

**Comment by PhanLe1010** [comment]
Support bundle and dmesg when the mount point in the pods are hang:
* The problematic volume is pvc-b706aa95-d4b2-42ff-b6c1-b844f3af3409
* 6 workload pods and the share-manager is on node `photon-03`
* The global mount of the RWX volume is also stuck
    ```
    root@photon-03 [ ~ ]# ls -l /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/1a1eb22a8c78f39ae84d894c5d483b7ac44c482a67816b146a742d16f03001c8/globalmount
    <stuck forever>
    ```


[supportbundle_f9c6d852-b61d-470a-8147-009b614febce_2024-03-26T05-15-14Z.zip](https://github.com/longhorn/longhorn/files/14752871/supportbundle_f9c6d852-b61d-470a-8147-009b614febce_2024-03-26T05-15-14Z.zip)

[dmesg.log](https://github.com/longhorn/longhorn/files/14752882/dmesg.log)

**Comment by PhanLe1010** [comment]
@shuo-wu @james-munson I followed your recommendation of manually mounting the nfs server on same node / use Ubuntu:
* Manually mounting the nfs server on same node still work even though the mount points inside pods are stuck
* I install Ubuntu 22.04 on another baremetal node and join that node to this cluster. Then force all pod of the sts on the ubuntu node. Result: no hanging

**Comment by shuo-wu** [comment]
How about launching a new workload pod with the same image then doing a manual mount in the CSI plugin for the pod?

**Comment by PhanLe1010** [comment]
> How about launching a new workload pod with the same image then doing a manual mount in the CSI plugin for the pod?

Sorry Shuo, I don't quite understand this step. Do you mean:
* launch a new pod on same node without the RWX PVC attached 
* Then exec into the pod and mount nfs manually

**Comment by PhanLe1010** [comment]
Simpler reproduce steps:
1. Deploy this simple workload
    ```yaml
    # Long-running test with prometheus metric exporter to monitor the data
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-1
    spec:
      volumeMode: Filesystem
      storageClassName: longhorn  # replace with your storage class
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: test-workload
      namespace: default
    spec:
      serviceName: test-workload
      replicas: 1
      selector:
        matchLabels:
          app: test-workload
      podManagementPolicy: Parallel
      template:
        metadata:
          labels:
            app: test-workload
        spec:
          nodeName: photon-03 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
          containers:
            - name: kbench-1
              image: ubuntu:xenial
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c", "while : ;do dd if=/dev/urandom of=/pvc1/test.img bs=4096 count=102400 conv=notrunc; sleep 1; done"]
              volumeMounts:
                - name: pvc1
                  mountPath: /pvc1/
          volumes:
            - name: pvc1
              persistentVolumeClaim:
                claimName: pvc-1
    ```
1. Check that read/write to `/pvc1` in the pod is ok
1. Scale it up to 6 pods
1. Wait for 5 mins. check that read/write to `/pvc1` in the pods are frozen

**Comment by innobead** [comment]
Does this Only happen in this specific OS? @PhanLe1010 

Is it possible due to nfs host package issue?

**Comment by PhanLe1010** [comment]
> Does this Only happen in this specific OS? @PhanLe1010
> 
> Is it possible due to nfs host package issue?

@innobead it happen in Photon OS RT but doesn't happen on the Ubuntu 22.04 cluster. I am going to test photon OS on RT to see if it can happens 

> Is it possible due to nfs host package issue?

Good idea, I will check this

**Comment by innobead** [comment]
A few things can also be checked:
- if reduce the replica of the workload, will the stuck IO be resolved at runtime?
- during IO stuck, any logs happening in the share manager pod? Are you able to manually mount it in another workload and also encounter the IO stuck issue?

**Comment by PhanLe1010** [comment]
> - if reduce the replica of the workload, will the stuck IO be resolved at runtime?

@innobead No, when scaling down the sts, the pods stuck in pending terminating since the nfs mount cannot be unmount. I have to reboot the node OR kill the share-manager pod to make the workload pod finish terminating. 

> - during IO stuck, any logs happening in the share manager pod? 

There is nothing special in share-manager pod's logs. The logs is just like this after the NFS server start:
```
26/03/2024 22:42:35 : epoch 66034f5b : share-manager-pvc-b706aa95-d4b2-42ff-b6c1-b844f3af3409 : nfs-ganesha-37[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
2024-03-26T22:42:35.882456693Z 26/03/2024 22:42:35 : epoch 66034f5b : share-manager-pvc-b706aa95-d4b2-42ff-b6c1-b844f3af3409 : nfs-ganesha-37[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
26/03/2024 22:42:42 : epoch 66034f5b : share-manager-pvc-b706aa95-d4b2-42ff-b6c1-b844f3af3409 : nfs-ganesha-37[svc_5] longhorn_add_clid :CLIENT ID :EVENT :Add client '23:Linux NFSv4.1 photon-03' to recovery backend share-manager-pvc-b706aa95-d4b2-42ff-b6c1-b844f3af3409
```

> Are you able to manually mount it in another workload and also encounter the IO stuck issue?

Deploying a pod using the RWX volume on the same node will stuck in containerCreating as mentioned at https://github.com/longhorn/longhorn/issues/8253#issuecomment-2021240433.
However, deploying a pod using the RWX on a new node is OK

> Is it possible due to nfs host package issue?

Looks like the Unbuntu one is using 2.6.1 while Photon one is using 2.6.2?
```
root@ubuntu-01:/home/ubuntu# dpkg -l | grep nfs
ii  libnfsidmap1:amd64                     1:2.6.1-1ubuntu1.2                      amd64        NFS idmapping library
ii  nfs-common                             1:2.6.1-1ubuntu1.2                      amd64        NFS support files common to client and server
==============
root@photon-03 [ ~ ]# yum list installed | grep nfs
libnfsidmap.x86_64                           2.6.2-9.ph5               @System
nfs-utils.x86_64                             2.6.2-9.ph5               @System

```

**Comment by PhanLe1010** [comment]
Update:

I did some test with different distribution of workload and share-manager pods. Result:

| share-manager node | workload pods' node | state |
|----------|----------|----------|
| Photon RT OS  | Photon RT OS  | nfs mounts are frozen  |
| Photon RT OS  | Ubtunu 22.04  | nfs mounts are frozen  |
| Ubtunu 22.04  | Ubtunu 22.04  | nfs mounts are NOT frozen  |
| Ubtunu 22.04  | Photon RT OS  | nfs mounts are NOT frozen  |

Looks like the location of the share-manager is what matter

**Comment by PhanLe1010** [comment]
Update:

I did some tests with different distributions of workload pods and share-manager pod. Result:

| share-manager pod's node | workload pods' node | state |
|----------|----------|----------|
| Photon RT OS  | Photon RT OS  | nfs mounts are frozen  |
| Photon RT OS  | Ubtunu 22.04  | nfs mounts are frozen  |
| Ubtunu 22.04  | Photon RT OS  | nfs mounts are frozen but it takes longer time than the above 2 cases |
| Ubtunu 22.04  | Ubtunu 22.04  | nfs mounts are NOT frozen  |

Looks like the location of the share-manager pod is what matter

**Comment by innobead** [comment]
Do we know about the nfs kernel module? But doubt we are able to check it.

**Comment by PhanLe1010** [comment]
> Do we know about the nfs kernel module? But doubt we are able to check it.

Is it this one? 
```
root@photon-03 [ ~ ]# modinfo nfs
filename:       /lib/modules/6.1.10-10.ph5-rt/kernel/fs/nfs/nfs.ko.xz
license:        GPL
author:         Olaf Kirch <okir@monad.swb.de>
alias:          nfs4
alias:          fs-nfs4
alias:          fs-nfs
depends:        sunrpc,fscache,lockd
retpoline:      Y
intree:         Y
name:           nfs
vermagic:       6.1.10-10.ph5-rt SMP preempt_rt mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        7D:F5:20:BC:BD:79:8F:D8:46:EF:B2:DB:45:C4:2F:FC:55:E1:22:EE
sig_hashalgo:   sha512
=========
ubuntu@ubuntu-01:~$ modinfo nfs
filename:       /lib/modules/5.15.0-101-generic/kernel/fs/nfs/nfs.ko
license:        GPL
author:         Olaf Kirch <okir@monad.swb.de>
alias:          nfs4
alias:          fs-nfs4
alias:          fs-nfs
srcversion:     E46B121D3C0A67D41B92D03
depends:        fscache,sunrpc,lockd
retpoline:      Y
intree:         Y
name:           nfs
vermagic:       5.15.0-101-generic SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        7D:31:86:13:F2:76:80:28:1A:E7:90:1A:C6:12:9B:85:D8:E4:8E:E9
sig_hashalgo:   sha512
```

Looks like the one on Photon RT OS is newer

**Comment by shuo-wu** [comment]
The module version seem to be related to the kernel version. I am wondering if there will be a similar issue when Ubuntu kernel version is the same as that of Photon RT OS.

**Comment by PhanLe1010** [comment]
Update:
1. Since each machine has 2 NICs and I saw that some time NFS conntion is going to the 2nd NICs while I specify K3s to use the 1st NIC only. I disable the 2nd NIC on all machines --> NFS mounts are still stuck on Phonton RT node
2. Trying to add a Photon non RT node and test it ...
3. Trying to upgrade kernel and NFS module ...

**Comment by PhanLe1010** [comment]
Update: 

Sorry! After repeatedly stress testing, the Photon non-RT OS with latest kernel 6.1.10-11.ph5 still suffers the NFS mounts frozen 😔

**Comment by innobead** [comment]
As discussed, @PhanLe1010 will also check if nfs mount has problems w/o Longhorn.

**Comment by PhanLe1010** [comment]
Update: 

On Photon non-RT OS with latest kernel 6.1.81-2.ph5, we performed the following tests:

### Case 1: Test with Kubernetes external NFS provisioner + hostPath (without any Longhorn component) ✅
 
![image](https://github.com/longhorn/longhorn/assets/22139961/0d302684-b8bf-4e8f-98db-b84ec649aae0)

<details>
<summary>This is the yaml to deploy this setup</summary>
<be>

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      nodeName: photon-02 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: nlockmgr
              containerPort: 32803
            - name: nlockmgr-udp
              containerPort: 32803
              protocol: UDP
            - name: mountd
              containerPort: 20048
            - name: mountd-udp
              containerPort: 20048
              protocol: UDP
            - name: rquotad
              containerPort: 875
            - name: rquotad-udp
              containerPort: 875
              protocol: UDP
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
            - name: statd
              containerPort: 662
            - name: statd-udp
              containerPort: 662
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=example.com/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/nfs-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["nfs-provisioner"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
     # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-nfs
provisioner: example.com/nfs
mountOptions:
  - vers=4.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-workload
  namespace: default
spec:
  serviceName: test-workload
  replicas: 1
  selector:
    matchLabels:
      app: test-workload
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: test-workload
    spec:
      nodeName: photon-02 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
      containers:
        - name: kbench-1
          image: phanle1010/kbench:broadcom
          imagePullPolicy: IfNotPresent
          env:
            - name: MODE
              value: "random-write-iops"
            - name: OUTPUT
              value: /tmp/pvc1
            - name: FILE_NAME
              value: "/pvc1/test.img"
            - name: SIZE
              value: "1638M" # 80% of the pvc-1's size
            - name: CPU_IDLE_PROF
              value: "disabled"
            - name: SKIP_PARSE
              value: "true"
            - name: LONG_RUN
              value: "true"
            - name: RATE_IOPS
              value: "1000"
          volumeMounts:
            - name: pvc1
              mountPath: /pvc1/
      volumes:
        - name: pvc1
          persistentVolumeClaim:
            claimName: nfs-pvc
```
</details>

**Result: NFS mounts are NOT frozen** 

### Case 2: Test with Kubernetes external NFS provisioner + Longhorn RWO PVC ✅
![image](https://github.com/longhorn/longhorn/assets/22139961/3c3d32c3-48af-498e-9317-c546af663cfe)

<details>
<summary>This is the yaml to deploy this setup</summary>
<be>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-provisioner-storage # longhorn backing pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi" # make this 10% bigger then the workload pvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      nodeName: photon-02 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.k8s.io/sig-storage/nfs-provisioner:v4.0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: nlockmgr
              containerPort: 32803
            - name: nlockmgr-udp
              containerPort: 32803
              protocol: UDP
            - name: mountd
              containerPort: 20048
            - name: mountd-udp
              containerPort: 20048
              protocol: UDP
            - name: rquotad
              containerPort: 875
            - name: rquotad-udp
              containerPort: 875
              protocol: UDP
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
            - name: statd
              containerPort: 662
            - name: statd-udp
              containerPort: 662
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=example.com/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        # - name: export-volume
        #   hostPath:
        #     path: /tmp/nfs-provisioner
        - name: export-volume
          persistentVolumeClaim:
            claimName: nfs-provisioner-storage
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["nfs-provisioner"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
     # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-nfs
provisioner: example.com/nfs
mountOptions:
  - vers=4.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-workload
  namespace: default
spec:
  serviceName: test-workload
  replicas: 1
  selector:
    matchLabels:
      app: test-workload
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: test-workload
    spec:
      nodeName: photon-02 # Replace this one by one of the node in your cluster to force all pods of this workload on that node
      containers:
        - name: kbench-1
          image: phanle1010/kbench:broadcom
          imagePullPolicy: IfNotPresent
          env:
            - name: MODE
              value: "random-write-iops"
            - name: OUTPUT
              value: /tmp/pvc1
            - name: FILE_NAME
              value: "/pvc1/test.img"
            - name: SIZE
              value: "1638M" # 80% of the pvc-1's size
            - name: CPU_IDLE_PROF
              value: "disabled"
            - name: SKIP_PARSE
              value: "true"
            - name: LONG_RUN
              value: "true"
            - name: RATE_IOPS
              value: "1000"
          volumeMounts:
            - name: pvc1
              mountPath: /pvc1/
      volumes:
        - name: pvc1
          persistentVolumeClaim:
            claimName: nfs-pvc
```
</details>

**Result: NFS mounts are NOT frozen** 

### Case 3: Test with Longhorn RWX PVC ❌ 
![image](https://github.com/longhorn/longhorn/assets/22139961/505cbf81-1196-414b-b997-78ed7921f48f)

**Result: NFS mounts are frozen** 


## Analsys:

1. From the test results, we can see that the difference between frozen case (case 3) and non frozen cases (case 1 and case 2) is at Longhorn **CSI/Longhorn share manager** VS **Kubernetes external NFS provisioner + nfs-ganesha**. 
1. Since the workload are mounting the volume OK at the beginning, the Longhorn CSI plugin might not be the culprit. So Is it possible that something is wrong in our Longhorn share-manager?
1. The main component of Longhorn share-manager (frozen case) and Kubernetes external NFS provisioner (non-frozen cases)  is the `nfs-ganesha`. I see that Kubernetes external NFS provisioner is using `nfs-ganesha: V4.0.8` while Longhorn share manager is using `nfs-ganesha: V5.7`:
    ```
    # Kubernetes external NFS provisioner 
    bash-5.2# ./usr/local/bin/ganesha.nfsd -v
    NFS-Ganesha Release = V4.0.8
    
    # Kubernetes external NFS provisioner 
    share-manager-pvc-0bcdb279-04f7-4a8c-a83b-d301c0e37237:/ # ./usr/local/bin/ganesha.nfsd -v
    NFS-Ganesha Release = V5.7
    ```
1. In order to confirm whether `nfs-ganesha` version difference is the culprit, I revert the share-manager to use `nfs-ganesha: V4.2.3`:
    ```
    share-manager-pvc-adf07290-9d3b-4683-8637-da6cedf8fa6b:/ # ./usr/local/bin/ganesha.nfsd -v
    NFS-Ganesha Release = V4.2.3
    ```
    **Result: NFS mounts are NOT frozen** 
1. I am doing more investigating but I suspect that the root cause might be related to:
    * https://github.com/nfs-ganesha/nfs-ganesha/issues/1063
    * https://github.com/nfs-ganesha/nfs-ganesha/issues/1063
