### ISSUE TITLE
[BUG] The parameter (Longhorn Pod Deletion Policy When Node is Down) didn't work

### ISSUE THREAD

**Issue by haiouc** [longhorn/longhorn#8275]
I have tested the feature "Longhorn Pod Deletion Policy When Node is Down" in Longhorn helm chart v1.6.0
I applied the example examples/statefulset.yaml，the parameter "longhorn Pod Deletion Policy When Node is Down" is nothing.

I shut down the node,  it will create a new pod on the other node.
The parameter didn't work. I don't know why. 

if NodeDownPodDeletionPolicy is set to do-nothing | delete-deployment-pod

- wait till the pod.deletionTimestamp has passed
- verify no replacement pod generated, the pod is stuck at terminating forever.

**Comment by haiouc** [comment]
if NodeDownPodDeletionPolicy is set to do-nothing | delete-deployment-pod

- wait till the pod.deletionTimestamp has passed
- verify no replacement pod generated, the pod is stuck at terminating forever.

**Comment by haiouc** [comment]
# kubectl -n longhorn-system get setting node-down-pod-deletion-policy
NAME                            VALUE        AGE
node-down-pod-deletion-policy   do-nothing   17d

`[root@haiouc longhorn]# k get pod -n default -o wide | grep web
web-0        1/1     Running     0    9m20s   172.21.115.66   k8s-med-worker-4    <none>      <none>
web-1        1/1     Running     0    8m47s   172.21.70.115   k8s-med-worker-6    <none>     <none>

[root@haiouc longhorn]# k get nodes    ( shut off a instance on openstack )
NAME                           STATUS   ROLES                  AGE    VERSION
k8s-med-worker-4    Ready    <none>                 296d   v1.23.7
===>>>>
k8s-med-worker-4    NotReady   <none>               296d   v1.23.7

[root@haiouc longhorn]# k get pod -n default -o wide | grep web
web-0    0/1     Terminating   0      100s    <none>          k8s-med-worker-2    <none>           <none>
web-1    1/1     Running              11m     172.21.70.115   k8s-med-worker-6    <none>           <none>

[root@haiouc longhorn]# k get pod -n default -o wide | grep web
web-0    0/1     ContainerCreating   0          69s     <none>          k8s-med-worker-2    <none>           <none>
web-1    1/1     Running             0          13m     172.21.70.115   k8s-med-worker-6    <none>           <none>

[root@haiouc longhorn]# k get pod -n default -o wide | grep web
web-0    1/1     Running       0        5m18s   172.21.7.82     k8s-med-worker-2    <none>           <none>
web-1    1/1     Running       0        17m     172.21.70.115   k8s-med-worker-6    <none> `

**Comment by chriscchien** [comment]
> kubectl -n longhorn-system get setting node-down-pod-deletion-policy NAME VALUE AGE node-down-pod-deletion-policy do-nothing 17d
> 
> ` `[root@haiouc longhorn]# k get pod -n default -o wide | grep web web-0 1/1 Running 0 9m20s 172.21.115.66 k8s-med-worker-4 web-1 1/1 Running 0 8m47s 172.21.70.115 k8s-med-worker-6
> 
> [root@haiouc longhorn]# k get nodes ( shut off a instance on openstack ) NAME STATUS ROLES AGE VERSION k8s-med-worker-4 Ready 296d v1.23.7 ===>>>> k8s-med-worker-4 NotReady 296d v1.23.7
> 
> [root@haiouc longhorn]# k get pod -n default -o wide | grep web web-0 0/1 Terminating 0 100s k8s-med-worker-2 web-1 1/1 Running 11m 172.21.70.115 k8s-med-worker-6

Not sure why you terminated `k8s-med-worker-4` but ` web-0`  pod is terminating on `k8s-med-worker-2` and become running?
> 
> [root@haiouc longhorn]# k get pod -n default -o wide | grep web web-0 0/1 ContainerCreating 0 69s k8s-med-worker-2 web-1 1/1 Running 0 13m 172.21.70.115 k8s-med-worker-6
> 
> [root@haiouc longhorn]# k get pod -n default -o wide | grep web web-0 1/1 Running 0 5m18s 172.21.7.82 k8s-med-worker-2 web-1 1/1 Running 0 17m 172.21.70.115 k8s-med-worker-6 ``

Could you boot on all nodes and shut down the node web-0 applied to again? mean while could you provide logs of command `kubectl get pods -n default -o wide -w | grep web` for more clue? thank you.

**Comment by haiouc** [comment]
I try to install 1.6.1 on another new cluster for testing. It's NOK.   I powered off the dev1-ohn79-k8s-med-worker-2, it will create a new pod on dev1-ohn79-k8s-med-worker-3

`[root@haiouc longhorn]# k get pod -o wide | grep web 
web-0      1/1     Running     0   3m26s   172.21.70.201   dev1-ohn79-k8s-med-worker-6    <none>           <none>
web-1      1/1     Running     0   3m13s   172.21.7.225    dev1-ohn79-k8s-med-worker-2    <none>           <none>

[root@haiouc longhorn]# k get pod -o wide | grep web 
web-0      1/1     Running       0     19m     172.21.70.201   dev1-ohn79-k8s-med-worker-6    <none>           <none>
web-1      1/1     Running       0     7m47s   172.21.9.58     dev1-ohn79-k8s-med-worker-3    <none>           <none>
`

**Comment by haiouc** [comment]
@chriscchien 
Not sure why you shut off k8s-med-worker-4 but  web-0 pod is terminating on k8s-med-worker-2 and become running?
[haiouc]  https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/
Find the node which contains one pod of the StatefulSet/Deployment. Power off the node

then it will create a new pod on  k8s-med-worker-2, wait a moment,  create a new pod on k8s-med-worker-2

**Comment by chriscchien** [comment]
Hi @haiouc, could you provide support bundle here? thank you.

**Comment by haiouc** [comment]
I updated the parameters when installing longhorn with argocd.
`    helm:
      parameters:
        - name: 'metrics.serviceMonitor.enabled'
          value: 'true'
        - name: 'persistence.defaultMkfsParams'
          value: '-i 4096'
        - name: 'preUpgradeChecker.jobEnabled'
          value: 'false'
        - name: 'persistence.defaultClass'
          value: 'false'   `

**Comment by chriscchien** [comment]
Hi @haiouc , are you following the [instruction](https://longhorn.io/docs/1.6.1/deploy/install/install-with-argocd/) in install Longhorn witrh ArgoCD? I stiil can not reproduce.

**Comment by haiouc** [comment]
yes.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: 'https://charts.longhorn.io'
    targetRevision: v1.6.0
    helm:
      parameters:
        - name: 'metrics.serviceMonitor.enabled'
          value: 'true'
        - name: 'persistence.defaultMkfsParams'
          value: '-i 4096'
        - name: 'preUpgradeChecker.jobEnabled'
          value: 'false'
        - name: 'persistence.defaultClass'
          value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```
