### ISSUE TITLE
[BUG] Groups not applied to volumes of storage-class thus RecurringJob not selected

### ISSUE THREAD

**Issue by EugenMayer** [longhorn/longhorn#8287]
## Describe the bug

We are deploying using the official longhorn helm chart and thus deploy a default storage class (with a job list). We also deploy an additional storage class "longhorn-nobackup" with a different job-list via CRD/manifest.

The helm chart configuration is

```yaml
defaultSettings:
  defaultReplicaCount: 1
  backupTarget: nfs://${nfsServer}:${nfsShare}
  defaultLonghornStaticStorageClass: 'longhorn'

  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  nodeDrainPolicy: always-allow
  allowNodeDrainWithLastHealthyReplica: true
  allowCollectingLonghornUsageMetrics: false
  orphanAutoDeletion: true
  v2DataEngine: 1

persistence:
  defaultClassReplicaCount: 1
  migratable: false
  recurringJobSelector:
    enable: true
    jobList:
      - '{"name":"backups", "isGroup":true}'
longhornUI:
  replicas: 1

enablePSP: false
```

And the RecurringJob job is 

```yaml
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backups
spec:
 concurrency: 3
  cron: 20 2 * * *
  groups:
    - backups
  labels:
    schedule: daily
  retain: 3
  task: backup-force-create
```

So it is to be expected, that if the default storage class `longhorn` is used, the volumes are assiged to the group `backups` and then the RecurringJob is run. 

This is not the case, all volume are without group, thus the "default" job is looked for (which does not exists by default).

On thing that might be relevant is, that the PV and PVC is created "manually"(via TF), and the, the volumes with the right names are created manually (by hand). Of course in this case, the target storage-class for the PV is `lonhorn` and thus should be with the group `backups` later on

If of any interest, those are the tf resources

```hcl
# see https://longhorn.io/docs/1.5.3/references/examples/#csi-persistent-volume
resource "kubernetes_persistent_volume" "volume" {
  metadata {
    name = local.volume_name
    annotations = {
      # this annotation is needed so tf knows about it - since longhorn will add this annotation in runtime and tf
      # will see this as an override agaain and again. 
      "longhorn.io/volume-scheduling-error" = ""
    }
  }
  spec {
    capacity = {
      storage = "${var.size}${var.sizeUnit}"
    }
    access_modes                     = [var.access_mode]
    storage_class_name               = local.storage_class_name
    volume_mode                      = "Filesystem"
    persistent_volume_reclaim_policy = var.reclaim_policy
    persistent_volume_source {
      # see https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/persistent_volume#csi
      csi {
        driver        = "driver.longhorn.io"
        volume_handle = "${var.namespace}-${var.name}"
        fs_type       = "ext4"
        read_only     = false
        volume_attributes = {
          numberOfReplicas = var.replica_count
        }
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "claim" {
  depends_on = [kubernetes_persistent_volume.volume]
  metadata {
    name      = var.name
    namespace = var.namespace
  }
  spec {
    storage_class_name = local.storage_class_name
    access_modes       = [var.access_mode]
    resources {
      requests = {
        storage = "${var.size}${var.sizeUnit}"
      }
    }
    volume_name = local.volume_name
  }
}
```

AFAICS on https://longhorn.io/docs/1.5.3/references/examples/#csi-persistent-volume there is no way to define a job-group when creating a PV or PVC, so i assume all this comes from selecting the storage class and what job list the storage class defines. All this is fairly vague in the docs though. Maybe, there is something hidden in the volume-attributes longhorn allows, but it seems there is no spec for that and 

## To Reproduce

- deploy the helm chart with a `jobList` setting like above
- create a RecurringJob like describe above
- create a PVC/PV (manually) for a payload
- then create the volume
- You should now see that the volume has no groups (default) instead of the expected group "backups"

## Expected behavior

Volumes should have group "backups" and select the correct RecurringJob

## Environment

 - Longhorn version: 1.6.1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro : k3s 1.29.2
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: ubuntu jammy 22.04
   - Kernel version: 6.5
   - CPU per node: 4
   - Memory per node: 16
   - Disk type (e.g. SSD/NVMe/HDD): nvme
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal, k3s on kvm
 - Number of Longhorn volumes in the cluster: 10 (homelab)
