### ISSUE TITLE
[BUG] Some users report that sometime, volume cannot be attach after upgrade Longhorn from v1.4.x to v1.5.x due to unexpected `longhorn-ui` attachment ticket

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8339]
## Describe the bug

Some users report that sometime, volume cannot be attach after upgrade Longhorn from v1.4.x to v1.5.x due to unexpected `longhorn-ui` attachment ticket. For example, this ticket https://github.com/longhorn/longhorn/discussions/6281 which has the longhorn-ui ticket in one of the Longhorn volumeattachment object:
```
      longhorn-ui:
        generation: 0
        id: longhorn-ui
        nodeID: k3s-agent-acf067
        parameters:
          disableFrontend: "false"
        type: longhorn-api
```

Since the user confirmed that there is no manual attach action during this time, we need to investigate to see if there is a bug in the upgrade path from v1.4.x to v1.5.x 

## To Reproduce

We don't have reproducing steps

## Expected behavior

If there is no manual attach action during this time, there should be no longhorn-ui AD ticket

## Support bundle for troubleshooting

See ref in the ticket https://github.com/longhorn/longhorn/discussions/6281

## Environment

 - Longhorn version: upgrade from v1.4.x to v1.5.x
