### ISSUE TITLE
[BUG] [v1.5.5-rc1] rwx volume fails to mount on pod

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#8344]
## Describe the bug

When creating a cluster on AWS using the `ubuntu-jammy-22.04-amd64-server-20240301` image, the kernel version is `6.5.0-1014-aws`.

1.  Testing with Longhorn versions `v1.5.5 and v1.5.4` on this kernel resulted in failure.
2.  However, when installing to Longhorn `v1.6.1` without updating the kernel, the issue was resolved, and RWX volumes could be successfully mounted on pods.
3.  Updated kernel version to `6.5.0-1017-aws` + Longhorn versions `v1.5.5` and `v1.5.4` passed successfully.

After discussing with @derekbit , for this issue, I believe we need to discuss whether to backport the `v1.6.x` NFS-Ganesha version to `v1.5.x` or continue recommending users to upgrade the worker node kernel version.

cc @james-munson @derekbit @innobead 
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               62s               default-scheduler        Successfully assigned default/ubuntu-mountvol0 to ryao-155-w3-86892745-sxf82
  Normal   SuccessfulAttachVolume  25s               attachdetach-controller  AttachVolume.Attach succeeded for volume "vol-0"
  Warning  FailedMount             3s (x6 over 25s)  kubelet                  MountVolume.MountDevice failed for volume "vol-0" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /usr/local/sbin/nsmounter
Mounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.43.19.218:/vol-0 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/0507c11c5cae88bed1ea382c2b36f2faa90ff78759812a6c34599ece4336fb48/globalmount
Output: mount.nfs: Protocol not supported
```

## To Reproduce

1. create a rwx volume vol-0
2. Create pod mount vol-0

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol0
  namespace: default
spec:
#  nodeSelector:
#    kubernetes.io/hostname: ryao-160-w2-d001851e-gl4nt # worker node
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-0
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0

```
## Expected behavior

The volume should get mounted normally and the pod start

## Support bundle for troubleshooting
[supportbundle_866bb13a-2fb6-40db-9dce-d70cb7c60c1d_2024-04-11T04-30-11Z.zip](https://github.com/longhorn/longhorn/files/14941435/supportbundle_866bb13a-2fb6-40db-9dce-d70cb7c60c1d_2024-04-11T04-30-11Z.zip)

## Environment

 - Longhorn version: v1.5.5-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.26.15+k3s1`
   - Number of control plane nodes in the cluster: `1`
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version: `Ubuntu 22.04`
   - Kernel version: `6.5.0-1014-aws`
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster: 2

## Additional context

https://github.com/longhorn/longhorn/issues/6857
https://github.com/longhorn/longhorn/issues/6887
