### ISSUE TITLE
[BUG] Do not terminate nfs-ganesha in share-manager pod after failing to access recovery backend

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8345]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Avoid terminating the nfs-ganesha when it fails to access the recovery backend.
Terminating nfs-ganesha can result in NFS clients becoming stuck.

Steps to reproduce

1. Create a 3-node Longhorn v1.5.3 cluster 
2. Create a deployment with a RWX volume
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rwx-vol-pvc
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-workload
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: test-workload
      template:
        metadata:
          labels:
            app: test-workload
        spec:
          containers:
          - name: test-workload
            image: ubuntu:20.04
            command: ["/bin/sh", "-c"]
            args:
              - |
                while true; do
                  dd if=/dev/urandom of=/data/file bs=4K count=400000
                  rm -f /data/file
                done
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: rwx-vol
              mountPath: /data
          volumes:
          - name: rwx-vol
            persistentVolumeClaim:
              claimName: rwx-vol-pvc
     ```
3. Upgrade Longhorn by the customized longhorn-manager image `derekbit/longhorn-manager:v1.5.3-no-rb`. The recovery backend service is removed, so the existing and running share-manager cannot talk to the recovery backend in the new longhorn-manager pod.

4. Update the replicas of the deployment `test-workload` to `3` by  `kubectl edit deployment test-workload`

5. Because the share-manager pod cannot talk to the recovery backend, the share-manager pod will error out. The NFS clients become frozen.
