### ISSUE TITLE
[FEATURE] Allow longhorn to restart pods with custom controllers, while the "Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly" feature is enabled

### ISSUE THREAD

**Issue by janosmiko** [longhorn/longhorn#8353]
## Is your feature request related to a problem?

I'm running several cloudnative-pg Postgres clusters using longhorn volumes. From time-to-time, random instances starting to fail with the following error message:
```
Error: failed to generate container "6883dca9455f25b006e38d47962d8532b517cee6ca0ad32965d7ad4b90daeb91" spec: failed to generate spec: relabel "/var/lib/kubelet/pods/12c69268-3aec-4a51-a219-e93dd47470ab/volumes/kubernetes.io~csi/pvc-0f4e030e-9f8f-4860-b697-5fb77e94cd37/mount" with "system_u:object_r:container_file_t:s0:c319,c917" failed: lsetxattr /var/lib/kubelet/pods/12c69268-3aec-4a51-a219-e93dd47470ab/volumes/kubernetes.io~csi/pvc-0f4e030e-9f8f-4860-b697-5fb77e94cd37/mount/lost+found: read-only file system
```

I assume this issue is described in [this](https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/) article.

The **Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly** feature is enabled in my cluster, but it doesn't handle the issue automatically. 
**My guess is that it happens, because the cloudnative-pg pods are managed by custom controllers.** (But the same would apply to strimzi kafka clusters).

The relevant part of a pod managed by a custom controller looks like this for cnpg pods:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-postgres-1
  namespace: test
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: test-postgres
      uid: 04baf2e3-9f88-416a-b8fe-d109f21bb8d1
      controller: true
      blockOwnerDeletion: true
```

And a kafka pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-kafka-0
  namespace: test
  ownerReferences:
    - apiVersion: core.strimzi.io/v1beta2
      kind: StrimziPodSet
      name: test-kafka
      uid: 129d1598-cd74-4aae-b279-22f6da9bb6f9
      controller: true
      blockOwnerDeletion: false
```

## Describe the solution you'd like

If my guess is correct, please make it possible to allow longhorn to restart pods that are managed by custom controllers, not just StatefulSet, Deployment and Daemonset controllers.

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by janosmiko** [comment]
I think this is still on the table. @derekbit what do you think?

**Comment by w3blogfr** [comment]
Hello, 
I can confirm I have the same issue with Strimzi Operator and v1.6.2
I don't have the issue with other volumes and they are sometime dealing also with lot of data.

**Comment by w3blogfr** [comment]
I asked some advice to Strimzi community and their advice is to make it killed by longhorn  (see https://github.com/orgs/strimzi/discussions/10898).

So, in that case, I would suggest to create an annotation "longhorn.io/delete-pod-on-volume-detach" that allow to bypass the non existent of parent controller when it's true

In kubernetes_pod_controller.go (https://github.com/longhorn/longhorn-manager/blob/2d5d2020faa7e3597638b857f58b5d167bb3f15f/controller/kubernetes_pod_controller.go#L299)
we can probably add a second condition before to skip

```
// Only delete pod which has controller to make sure that the pod will be recreated by its controller
if metav1.GetControllerOf(pod) == nil || (pod.Annotations["longhorn.io/delete-pod-on-volume-detach"] == "true") {
  _log.Warnf("%s. Workload pod is not managed by a controller", logSkip)
  continue
}
```

**Comment by derekbit** [comment]
> I don't know if you think it could be a good added value to have this annotation?

@w3blogfr Good idea too me. WDYT? @ChanYiLin @shuo-wu @innobead

**Comment by ChanYiLin** [comment]
Sounds good, we should allow killing the pods managed by custom controller as well

**Comment by ahmedadelll94** [comment]
Hello @mantissahz,
Could you please confirm if this issue has been resolved? If so, from which version is the fix available — v1.8.0+?
As our tests show the pod-deletion feature now works with Strimzi in v1.6.2

**Comment by shuo-wu** [comment]
It seems that Longhorn is already able to delete pods that have controllers:
https://github.com/longhorn/longhorn-manager/blob/73d4a9f9386838798508687b18dcc03d4e6745c8/controller/kubernetes_pod_controller.go#L309-L310
https://github.com/longhorn/longhorn-manager/blob/73d4a9f9386838798508687b18dcc03d4e6745c8/controller/kubernetes_pod_controller.go#L602-L603

@derekbit should we directly verify and close it?

**Comment by derekbit** [comment]
Sure. We can add `qa/reproduce` label and move to `Ready For Testing`. QA will help verify it. Thank you.

cc @longhorn/qa

**Comment by w3blogfr** [comment]
Hello,

I volunter to test again, for me it was not working in 1.6.2, and code didn't change since.

How I can emulate an unpextected volume detach, what's the best way for that? Kill the instance-manager maybe?

Regards.

**Comment by shuo-wu** [comment]
> How I can emulate an unpextected volume detach, what's the best way for that? Kill the instance-manager maybe?

Yes. Killing the instance manager pod on the node to which the volume is attached. 
To trigger this auto deletion, plz make sure that the related pod has `metadata.ownerReference.controller` set to `true`

**Comment by roger-ryao** [comment]
**Verified on master-head 20250730**

- longhorn master-head https://github.com/longhorn/longhorn/commit/77e5ffc4f9792c8274c9ea2e7fe151287d0655d0


**Verified on v1.8.2 20250730**

- longhorn v1.8.2 https://github.com/longhorn/longhorn/commit/93fe3711988040c2c2d1c0f19409d4a74c3a60e6

**The test steps**

1. **Set up the K3s cluster (v1.33.0+k3s1) on AWS**
2. **Install CloudNativePG Operator v1.22.0**
   ```bash
   kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.22/releases/cnpg-1.22.0.yaml
   ```
3. **Deploy a PostgreSQL Cluster example**
   ```bash
   kubectl apply -f cluster-example.yaml
   ```

   `cluster-example.yaml`:
   ```yaml
   apiVersion: postgresql.cnpg.io/v1
   kind: Cluster
   metadata:
     name: demo-postgres
     namespace: default
   spec:
     instances: 1
     storage:
       size: 1Gi
       storageClass: longhorn
   ```

4. **Verify the pod has `metadata.ownerReference.controller: true`**
   ```bash
   kubectl get pod demo-postgres-1 -o yaml | grep -A 10 "ownerReferences"
   ```

   ```yaml
   ryao@ryao-laptop:~/Downloads/test-record> kubectl get pod demo-postgres-1 -o yaml | grep -A 10 ownerReferences
     ownerReferences:
     - apiVersion: postgresql.cnpg.io/v1
       blockOwnerDeletion: true
       controller: true
       kind: Cluster
       name: demo-postgres
       uid: e5ca62e0-7a20-441f-b63e-fb617a608145
     resourceVersion: "73136"
     uid: b79089c6-db2f-484b-877a-414ecb47918c
   spec:
     affinity:
   ```

5. **Kill the instance manager pod on the node where the volume is attached**
   ```bash
   kubectl -n longhorn-system get pod -o wide | grep instance-manager
   # Find the target instance manager pod, then:
   kubectl -n longhorn-system delete pod <instance-manager-pod-name>
   ```

**Result Passed**

   - The volume will detach and re-attach.
   - The `demo-postgres-1` pod will terminate and a new one will be created automatically.


Hi @shuo-wu @derekbit 
If there are any issues with my test steps, please let me know.
