### ISSUE TITLE
How to mount pvc nonrootuser ? OpenShift 4.15.6

### ISSUE THREAD

**Issue by n00bsi** [longhorn/longhorn#8359]
## Question

How to mount lonhorn pvc in a nonrootuser pod ?

**OpenShift 4.15.6**

![image](https://github.com/longhorn/longhorn/assets/66995098/0e8d4ac9-8e1a-46b6-9be6-29a7c8a47111)

## Environment

 - Longhorn version: 1.6.1
 - Kubernetes version: v1.28.7+f1b5f6c
 - Node config
   - OS type and version: Red Hat Enterprise Linux CoreOS 415.92.202403270524-0
   - Kernel version: 5.14.0-284.59.1.el9_2.x86_64
   - CPU per node: 4vCPUs
   - Memory per node: 8GB Worker / 16 GB Controlplane Nodes
   - Disk type: virtual Disk
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

## Additional context

```
[core@osdemo1 ~]$ oc get pvc -n default
NAME       STATUS   VOLUME     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
demovol1   Bound    demovol1   5Gi        RWO            longhorn-static   3d4h

```

```
[core@osdemo1 ~]$ cat pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: "Always"
  containers:
  - image: alpine:latest
    command: ["sh","-c","mkdir -p /data && chown -R 1001:1001 /data", "tail"]
    args: ["-f", "/dev/null"]
    name: pvc-pod-container
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: demovol1
```

```
[core@osdemo1 ~]$ oc logs pod1 -n default
chown: /data/lost+found: Operation not permitted
chown: /data/lost+found: Operation not permitted
chown: /data: Operation not permitted
chown: /data: Operation not permitted

```

How to build yaml file for a pod, that mount the: demovol1
and that the mounted volume is writeable

If I use the yaml like this:

```
[core@osdemo1 ~]$ cat pod3.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: default
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  containers:
  - image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    name: pvc-pod-container
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: demovol1

```

```
[core@osdemo1 ~]$ oc exec -it pod3 -n default -- sh
~ $ cd /data
sh: cd: can't cd to /data: Permission denied
~ $ ls -la
total 24
dr-xr-xr-x    1 root     root            74 Apr 15 13:58 .
dr-xr-xr-x    1 root     root            74 Apr 15 13:58 ..
drwxr-xr-x    2 root     root         12288 May 18  2023 bin
drwxrwsr-x    3 root     1001          4096 Apr 15 13:59 data
drwxr-xr-x    5 root     root           360 Apr 15 13:58 dev
drwxr-xr-x    1 root     root            66 Apr 15 13:58 etc
drwxr-xr-x    2 nobody   nobody           6 May 18  2023 home
drwxr-xr-x    2 root     root          4096 May 18  2023 lib
lrwxrwxrwx    1 root     root             3 May 18  2023 lib64 -> lib
dr-xr-xr-x  411 root     root             0 Apr 15 13:58 proc
drwx------    2 root     root             6 May 18  2023 root
drwxr-xr-x    3 root     root            42 Apr 15 13:58 run
dr-xr-xr-x   13 root     root             0 Apr 12 09:41 sys
drwxrwxrwt    2 root     root             6 May 18  2023 tmp
drwxr-xr-x    4 root     root            29 May 18  2023 usr
drwxr-xr-x    1 root     root            17 Apr 15 13:58 var

```

**What did I wrong ?**

when delete the pod..... could shortly access
```

[core@osdemo1 ~]$ oc exec -it pod3 -n default -- sh
~ $ cd /data/
/data $ ls -la
total 20
drwxrwsr-x    3 root     1001          4096 Apr 15 14:03 .
dr-xr-xr-x    1 root     root            74 Apr 15 14:03 ..
-rw-rw-r--    1 1001     1001             0 Apr 15 13:59 1
drwxrws---    2 root     1001         16384 Apr 15 11:55 lost+found
/data $ touch 2
/data $ ls -la
total 20
drwxrwsr-x    3 root     1001          4096 Apr 15 14:03 .
dr-xr-xr-x    1 root     root            74 Apr 15 14:03 ..
-rw-rw-r--    1 1001     1001             0 Apr 15 13:59 1
-rw-r--r--    1 1001     1001             0 Apr 15 14:03 2
drwxrws---    2 root     1001         16384 Apr 15 11:55 lost+found
/data $ 
```

```
[core@osdemo1 ~]$ oc exec -it pod3 -n default -- sh
~ $ cd /data/
/data $ ls -la
total 20
drwxrwsr-x    3 root     1001          4096 Apr 15 14:03 .
dr-xr-xr-x    1 root     root            74 Apr 15 14:03 ..
-rw-rw-r--    1 1001     1001             0 Apr 15 13:59 1
-rw-r--r--    1 1001     1001             0 Apr 15 14:03 2
drwxrws---    2 root     1001         16384 Apr 15 11:55 lost+found
/data $ ls -la
ls: .: Permission denied
/data $ 

```

```
[core@osdemo1 ~]$ oc logs pod3 -n default
[core@osdemo1 ~]$ 


```

Looks like only one pod can access the pvc: demovol1 not multible - is this my fault ?
