### ISSUE TITLE
[IMPROVEMENT] Investigate how Longhorn is working with CAPI rolling upgrade

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8362]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We would like to investigate how Longhorn behaves in CAPI rolling upgrade case. How to make Longhorn reuse the replica in during this process instead of creating new replicas?

This reproducing steps is copied from the ticket https://gitlab.com/sylva-projects/sylva-core/-/issues/1141#reproduction-steps 

### Reproduction steps:

1. Deploy Sylva with longhorn with 3 BM nodes.
2. Set `replica-replenishment-wait-interval=80 minutes` for longhorn and `numberOfReplicas: "2"`
3. After deployment is completed, note down the details of longhorn replicas in GUI like name , state and status.
4. Before starting rolling upgrade, set below values in environmental-values
    ```
    kubelet_extra_args:
        max-pods: "228" 
    capm3:
        nodeReuse: true
        automatedCleaningMode: disabled
    ```
5. Start rolling upgrade.
6. Check the status of longhorn replicas after rolling upgrade is completed.

## Expected behavior:
* Longhorn should not create new replica and should reuse existing (i.e. old) replica
* Longhorn should rebuild the data using existing (i.e. old) replica
