### ISSUE TITLE
Using Gi in spec->resources->requests->storage results in 'field can not be less than previous value' after expanding volume

### ISSUE THREAD

**Issue by kdejaeger** [longhorn/longhorn#8381]
## Describe the bug

We are using Rancher / Helm and longhorn 1.5.4. Our storage size is requested in Gi. After making the Gi value higher, the disc is expanded successfully. However longhorn changes the PVC's yaml request value with it's own in Mi, a slightly higher rounded up value, resulting in the 'field can not be less than previous value' error message after next helm deployments.

## To Reproduce

Make a storage class that is expandable, obviously
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Retain"
      volumeBindingMode: Immediate
   
     ...etc...
```

Ask for a PVC of 5Gi and deploy in kubernetes. A 5Gi disc is created ...
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres--data
  labels:

..........etc.......

 spec:
  storageClassName: my-expanding-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

Modify this created yaml and request a a higher disc, f. ex 5.01Gi. This will fire up the resize operation, after half a minute or so the yaml will look the same, except instead of 5.01Gi, it now shows 5132Mi and 5381292032 in the request instead of Gi.
```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '5381292032'
  storageClassName: my-expanding-storageclass
  volumeMode: Filesystem
  volumeName: pvc-xyz....
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5132Mi
  phase: Bound
```
spec->resources->requests->storage is now in bytes and status->capacity->storage is now in Mi. Before this, both were in Gi.

Because of this, next time I deploy with the requested size of 5.01Gi, kubernetes thinks I am requesting a higher value:
```
Error: UPGRADE FAILED: cannot patch "postgres--data" with kind PersistentVolumeClaim: PersistentVolumeClaim "postgres--data" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value
```

## Expected behavior

I'd expect longhorn to keep to the requested value of the provided yaml file (5.01Gi) as is, despite rounding up to a valid Mi value in order to resize the disc, in order to avoid this rounding error after redeployments. Clients should not have to keep a calculator next to there desc in order to work with Gibigytes, Terribytes, Pepibytes, etc ... according to their sizing needs in order to have clean deployment an yaml files.
