### ISSUE TITLE
[BUG] Volumes stuck in Detached state after reboot

### ISSUE THREAD

**Issue by DizzieNight** [longhorn/longhorn#8423]
## Describe the bug

I rebooted my server and my volumes were stuck on Detatching, I noticed some of the replicas were on my master nodes instead of my worker nodes, I have removed them and disabled my master nodes on Longhorn UI. Volumes are now in Detached state and no matter what I do they do not attach to the pods.

Only 2 volumes have attached, not sure how or why. I removed a volume entirely and rebuilt it, still no luck. I also removed the PV and PVC for a couple of different volumes, also no luck.

## To Reproduce

Reboot server and hope it breaks I guess.

## Expected behavior

Volumes should attach to pods that are trying to be created.

## Support bundle for troubleshooting

Support Bundle is attached
[supportbundle_913f7d1d-6412-427c-87ee-1fe64c171768_2024-04-23T09-05-46Z.zip](https://github.com/longhorn/longhorn/files/15074285/supportbundle_913f7d1d-6412-427c-87ee-1fe64c171768_2024-04-23T09-05-46Z.zip)

## Environment

 - Longhorn version: 1.6.1
 - Impacted volume (PV): bazarr, deluge-config, deluge-data, flaresolverr, jfa-go, kavita, lidarr, overseerr, radarr, readarr, sonarr, vaultwarden, whisparr
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.27.10+k3s2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Debian Lunar
   - Kernel version: 6.2.0-1018-kvm
   - CPU per node: 4
   - Memory per node: 6GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox VMs
 - Number of Longhorn volumes in the cluster: 16

## Additional context

I've noticed some logs in the support bundle a 502 Bad Gateway error to 192.168.10.15, which is master node 2. This is the first reboot after changing my dns server to point to my adguard home on my router. Not sure if that has anything to do with it but I checked logs on adguard and it looked fine.

I also see errors about failing to sync replicas, but not sure what to do there.

**Comment by james-munson** [comment]
Support bundle is empty (0 bytes).  Perhaps mail it to longhorn-support-bundle@suse.com

**Comment by ZanderPittari** [comment]
I think the file is too large, will send a link to that email now

**Comment by james-munson** [comment]
logs/longhorn-system/csi-attacher-57c5fd5bdf-x8wmf/csi-attacher.log

```
2024-04-23T19:04:17.278448755+10:00 I0423 09:04:17.278284       1 csi_handler.go:234] Error processing "csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6": failed to attach: rpc error: code = Internal desc = volume bazarr failed to attach to node k3s-worker-1 with attachmentID csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6: Waiting for volume share to be available
```

And also in yamls/namespaced/longhorn-system/longhorn.io/v1beta2/volumeattachments.yaml,
```yaml
   spec:
      attachmentTickets:
        csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6:
          generation: 0
          id: csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6
          nodeID: k3s-worker-1
          parameters:
            disableFrontend: "false"
            lastAttachedBy: "null"
          type: csi-attacher
      volume: bazarr
    status:
      attachmentTicketStatuses:
        csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6:
          conditions:
            - lastProbeTime: "null"
              lastTransitionTime: "2024-04-22T22:09:38Z"
              message: Waiting for volume share to be available
              reason: "null"
              status: "False"
              type: Satisfied
          generation: 0
          id: csi-8ce5e5e7551c2951b0826ae7383457b98a30e0a8251083368f71332205f7d9d6
          satisfied: false
```
That comes from
https://github.com/longhorn/longhorn-manager/blob/2c27d58245028e2475b301ab14021d51a9ef73e1/controller/volume_attachment_controller.go#L741

and therefore from
https://github.com/longhorn/longhorn-manager/blob/2c27d58245028e2475b301ab14021d51a9ef73e1/controller/volume_attachment_controller.go#L914-L918

And indeed its share-manage is not `running`, it is `stopping`, as is every other share-manager.

yamls/namespaced/longhorn-system/longhorn.io/v1beta2/sharemanagers.yaml
```yaml
      name: bazarr
      namespace: longhorn-system
      ownerReferences:
        - apiVersion: longhorn.io/v1beta2
          kind: Volume
          name: bazarr
          uid: e214dc42-a6e8-41e8-8d27-1971c32fddaf
      resourceVersion: "247397410"
      uid: 13836141-afbe-4edd-9881-6665dfb2fb9e
    spec:
      image: longhornio/longhorn-share-manager:v1.6.1
    status:
      endpoint: "null"
      ownerID: k3s-worker-1
      state: stopping
```

Looking into why that would be.
