### ISSUE TITLE
[BUG] Unable to install Longhorn

### ISSUE THREAD

**Issue by Auser448** [longhorn/longhorn#8434]
Hello,

I tried to install Longhorn on K3s using the following tutorial https://docs.k3s.io/storage. In our company, we configured Artifactory as a proxy to reach the Docker Hub so that we do not directly download container images from the Docker Hub but we download them via our Artifactory instead.

After the installation of Longhorn, the pods are stuck in the following state

```
longhorn-system   longhorn-ui-654cbc7fc8-k9h75                     1/1     Running    0                11m
longhorn-system   longhorn-ui-654cbc7fc8-qg8d5                     1/1     Running    0                11m
longhorn-system   longhorn-driver-deployer-64494984f7-htl82        0/1     Init:0/1   0                11m
longhorn-system   longhorn-manager-fvgdw                           1/1     Running    0                7m31s
```

When looking at the logs of the init container of pod longhorn-driver-deployer-64494984f7-htl82, I can see that it is waiting for pod longhorn-manager-fvgdw to run properly even though the pods state is Running. Then, when looking at pod longhorn-manager-fvgdw logs, I can see the following logs

```
time="2024-04-24T12:57:42Z" level=info msg="Waiting for old Longhorn manager pods to be fully removed" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:266"
time="2024-04-24T12:57:42Z" level=info msg="Found old longhorn manager: longhorn-manager-fvgdw with image <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:275"
time="2024-04-24T12:57:43Z" level=info msg="Found old longhorn manager: longhorn-manager-fvgdw with image <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:275"
time="2024-04-24T12:57:44Z" level=info msg="Found old longhorn manager: longhorn-manager-fvgdw with image <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:275"
```

The logs remain the same and the pod is restarted by Kubernetes and the same logs occur again.

When looking at the code here https://github.com/longhorn/longhorn-manager/blob/8919746dcfd7929dd4dcff4813ce37e4379cc5d8/upgrade/upgrade.go#L334, the error seems to be due to the fact that the when the container name is longhorn-manager, Longhorn assumes to have detected a old longhorn manager. However, the only longhorn manager installed and running is the current longhorn manager who displays the log message.

I face the same behaviour either with Longhorn 1.5.3 or 1.6.0 or 1.6.1.

What should I do for the longhorn installation to run properly ?

## To Reproduce

Download the Longhorn YAML file https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml and edit it to add the Artifactory URL in the images names. For example replace longhornio/longhorn-manager:v1.5.3 by <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3

Install longhorn using the following command `k3s kubectl apply -f longhorn.yaml`

## Expected behavior

Longhorn should be successfully installed

## Environment

 - Longhorn version: 1.5.3, 1.6.0, 1.6.1
 - Impacted volume (PV): 
 - Installation method: Kubectl
 - Kubernetes distro : K3s v1.25.16+k3s4 and  v1.29.3+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Amazon Linux version 2
   - Kernel version:  4.14.336-257.568.amzn2.x86_64.
   - CPU per node: 2
   - Memory per node: 8GB
   - Disk type : NVMe
   - Network bandwidth between the nodes (Gbps): N/A
 - Underlying Infrastructure: AWS
 - Number of Longhorn volumes in the cluster: 0

**Comment by james-munson** [comment]
Agree with your analysis.  The question is, where does the manager image name come from that is compared to the discovered `container.Image`?  Following the trail backwards, it seems to be here that upgrade.Upgrade() is called:
https://github.com/longhorn/longhorn-manager/blob/8919746dcfd7929dd4dcff4813ce37e4379cc5d8/app/daemon.go#L173

In that module, it was passed in as a flag to the longhorn-manager app's command line:
https://github.com/longhorn/longhorn-manager/blob/8919746dcfd7929dd4dcff4813ce37e4379cc5d8/app/daemon.go#L123
https://github.com/longhorn/longhorn-manager/blob/8919746dcfd7929dd4dcff4813ce37e4379cc5d8/app/daemon.go#L37-L48

So although it is not possible for you to attach a support bundle, it might be interesting to see the output of `kubectl get daemonset longhorn-manager -o yaml` to look at the arguments.

**Comment by Auser448** [comment]
Thank you @james-munson, when I ran the command `kubectl get daemonset -n longhorn-system longhorn-manager -o yaml `, I saw the following output in the longhorn-manager container spec:

```
spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - longhornio/longhorn-engine:v1.5.3
        - --instance-manager-image
        - longhornio/longhorn-instance-manager:v1.5.3
        - --share-manager-image
        - longhornio/longhorn-share-manager:v1.5.3
        - --backing-image-manager-image
        - longhornio/backing-image-manager:v1.5.3
        - --support-bundle-manager-image
        - longhornio/support-bundle-kit:v0.0.27
        - --manager-image
        - longhornio/longhorn-manager:v1.5.3
        - --service-account
        - longhorn-service-account
      ...
      <OUTPUT_OMITTED>
      ...
      image:<COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3
```

Our company Artifactory registry FQDN was specified in the _image_ section but not in the _command_ section. After adding it also to the _command_ section,  the output becomes as follows and the Longhorn installation succeeds !

```
spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-engine:v1.5.3
        - --instance-manager-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-instance-manager:v1.5.3
        - --share-manager-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-share-manager:v1.5.3
        - --backing-image-manager-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/backing-image-manager:v1.5.3
        - --support-bundle-manager-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/support-bundle-kit:v0.0.27
        - --manager-image
        - <COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3
        - --service-account
        - longhorn-service-account
      ...
      <OUTPUT_OMITTED>
      ...
      image:<COMPANY_ARTIFACTORY_REGISTRY>/longhornio/longhorn-manager:v1.5.3
```
