### ISSUE TITLE
node down scenario: pod stuck at ContainerCreating state

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#847]
related to #635 

Steps to reproduce:

  - Create a Deployment with one pod attached to longhorn volume mount to `/data`

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  labels:
    name: volume-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: volume-test
  template:
    metadata:
      labels:
        name: volume-test
    spec:
      containers:
      - name: volume-test
        image: nginx:stable-alpine
        volumeMounts:
        - name: volv
          mountPath: /data
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc

```
- Shutdown the node which the pod scheduled to.
- Monitor the pods, as soon node is detected to be down, the old pod will be in terminating state.
- Force delete the terminating pod.
`kubectl delete pod TERMINATING_POD_NAME --force --grace-period=0`

- New pod will be stuck in `ContainerCreating` state 
- Inspect stuck pod using `kubectl describe pod STUCK_POD_NAME`
you should see the following error:

`  Warning  FailedAttachVolume  39s   attachdetach-controller  Multi-Attach error for volume "pvc-9b68216f-fcd9-11e9-8054-26db997fc043" Volume is already used by pod(s) TERMINATED_POD_NAME`
