### ISSUE TITLE
[BUG] defaultSettings taintToleration is not applied to engine-image daemon set.

### ISSUE THREAD

**Issue by debugger24** [longhorn/longhorn#8549]
## Describe the bug

defaultSettings taintToleration config in the helm chart and in `longhorn-default-setting` is not applied to engine-image daemon set.

https://github.com/longhorn/longhorn-tests/pull/192 doesn't test `engine-image-ei` daemonset.

## Expected behavior

defaultSettings taintToleration should be applied to all daemonsets.

## Environment

 - Longhorn version: v1.6.1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.28.4+k3s2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Comment by derekbit** [comment]
Ref: https://github.com/longhorn/longhorn/issues/4843

**Comment by PhanLe1010** [comment]
I will try to reproduce this

**Comment by PhanLe1010** [comment]
Cannot reproduce this issue @debugger24 . I tried to install Longhorn v1.6.1 Helm using this default setting:
```yaml
defaultSettings:
  taintToleration: "key=value:NoSchedule"
```
The outcome is that `engine-image-ei` daemonset does have the correct toleration:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '1'
    longhorn.io/last-applied-tolerations: '[{"key":"key","operator":"Equal","value":"value","effect":"NoSchedule"}]'
  name: engine-image-ei-ad735e4a
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-ad735e4a
  template:
    metadata:
    spec:
      tolerations:
        - effect: NoSchedule
          key: key
          operator: Equal
          value: value
```

Could you give more details about how you reproduced it? @debugger24

**Comment by debugger24** [comment]
This was my values override, I didn't pass `defaultSettings.taintToleration` as string but as array.

```yaml
longhornDriver:
  tolerations:
    - key: "###"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
longhornManager:
  tolerations:
    - key: "###"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  taintToleration:
    - key: "###"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
longhornUI:
  replicas: 1
ingress:
  enabled: true
  host: "###"
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  snapshotterReplicaCount: 2
  resizerReplicaCount: 2
```
