### ISSUE TITLE
Volume attach is always in attaching state

### ISSUE THREAD

**Issue by Maxwell1987** [longhorn/longhorn#855]
In the log of longhorn-manager: 
```
time="2019-11-07T08:32:17Z" level=warning msg="pvc-724ce714-c958-498d-8bbf-97ecd89accce-r-b7eba142: time=\"2019-11-07T07:36:20Z\" level=info msg=\"Creating volume /host/var/lib/rancher/longhorn/replicas/pvc-724ce714-c958-498d-8bbf-97ecd89accce-9eaebeb4, size 1073741824/512\""
time="2019-11-07T08:32:17Z" level=warning msg="pvc-724ce714-c958-498d-8bbf-97ecd89accce-r-b7eba142: time=\"2019-11-07T07:36:20Z\" level=fatal msg=\"Error running start replica command: mkdir /host/var/lib/rancher/longhorn/replicas/pvc-724ce714-c958-498d-8bbf-97ecd89accce-9eaebeb4: no such file or directory\""
```
View longhorn-manager's yaml:
```
        volumeMounts:
        - mountPath: /host/dev/
          name: dev
        - mountPath: /host/proc/
          name: proc
        - mountPath: /var/run/
          name: varrun
        - mountPath: /var/lib/rancher/longhorn/
          mountPropagation: Bidirectional
          name: longhorn
        - mountPath: /var/lib/longhorn/setting/
          name: longhorn-default-setting
```
and
```
      volumes:
      - hostPath:
          path: /dev/
          type: ""
        name: dev
      - hostPath:
          path: /proc/
          type: ""
        name: proc
      - hostPath:
          path: /var/run/
          type: ""
        name: varrun
      - hostPath:
          path: /var/lib/rancher/longhorn/
          type: ""
        name: longhorn
```
Is the yaml wrong?

my env:
OS: Ubuntu 18.04
Rancher: 2.3.2 ( upgrade from 2.2.8 )
Kubernetes: 1.16.2 and 1.15.5
Longhorn: 0.6.2

If I modify yaml to:
```
      - hostPath:
          path: /host/var/lib/rancher/longhorn/
          type: ""
        name: longhorn
```
New error is
```
time="2019-11-07T08:45:37Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v0.6.2 to be ready"
```
