### ISSUE TITLE
[FEATURE] Show the orginal namespace and PVC name in backup UI

### ISSUE THREAD

**Issue by mattmattox** [longhorn/longhorn#8619]
## Describe the solution you'd like

When restoring a backup volume, the original volume's metadata is limited to IE. We only store the name, size, and Workload/Pod, making it hard to find volumes in the backup.

For example, if I delete the PVC, I try to restore it from the backup. Unless I have the PV name (pvc-....) documented ahead of time, you kind of need to hope the Workload/Pod matches up (which you can't search by) or that the size is different. IE, "Hey, there is only 1 9.5GB volume, so that must be it."

## Describe alternatives you've considered

We kind of store this information already [here](https://github.com/longhorn/longhorn-manager/blob/23ccdd17f9ef3000038f66ef5b0380134fd7c335/manager/engine.go#L263)

```yaml
spec:
  labels:
    KubernetesStatus: '{"pvName":"pvc-a837dbaa-a79c-47b0-ac87-d1c30e7587d4","pvStatus":"Bound","namespace":"a1-ops-dev","pvcName":"a1-ops-dev-work-c888999c-dj8zq-disk-0-95vg6","lastPVCRefAt":"","workloadsStatus":[{"podName":"virt-launcher-a1-ops-dev-work-c888999c-dj8zq-zsvpq","podStatus":"Running","workloadName":"a1-ops-dev-work-c888999c-dj8zq","workloadType":"VirtualMachineInstance"}],"lastPodRefAt":""}'
    RecurringJob: daily-backup
    longhorn.io/volume-access-mode: rwx
  snapshotName: daily-ba-9dcea0fd-43e0-45f5-a20f-25354a2d91c1
  syncRequestedAt: "2024-04-09T05:54:18Z"
```

We could bring namespace and pvcName values into the UI or update the spec to include these directly.
