### ISSUE TITLE
[BUG] Unable to mount any volumes(RWX/RWO) by any pods

### ISSUE THREAD

**Issue by DreamsOfImran** [longhorn/longhorn#8657]
## Describe the bug
I’m trying to create RWX/RWO volume in specific set of nodes with nodeSelector tags. I could able to create the volumes successfully but unable to attach it to any pods. Its just stuck in infinite `Attaching` & `Detached` loop. The share-manager pod also not coming into the ready state. The pod I’m trying to attach the volume is stuck `ContainerCreating` state. Please help me with fixing this issue.

```
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           5m13s                default-scheduler        Successfully assigned default/marks-dummy-pod to ip-xxxxxx.ec2.internal
  Warning  FailedAttachVolume  87s (x9 over 3m39s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-c29b0af0-ed78-4b21-90a5-bcabe65c005b" : rpc error: code = Internal desc = volume pvc-c29b0af0-ed78-4b21-90a5-bcabe65c005b failed to attach to node ip-xxxxx.ec2.internal with attachmentID csi-2b4f33f818c2cbd53ed4448ac5949a516517a4797a93fa89b15d0f197d90cacd: Waiting for volume share to be available
```

## To Reproduce
pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: longhorn-pvc-flink
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
```
helm-chart-values.yaml
```
metrics:
  serviceMonitor:
    enabled: true
persistence:
  defaultClass: false
  nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  defaultNodeSelector:
    enable: true
    selector: longhorn
longhornUI:
  replicas: 3
  nodeSelector:
    service: "longhorn"
  tolerations:
    - key: "service"
      operator: "Equal"
      value: "longhorn"
      effect: "NoSchedule"
```

[supportbundle_fd0f528d-69f4-4951-b231-95b31aad9fab_2024-05-26T06-07-58Z.zip](https://github.com/longhorn/longhorn/files/15472343/supportbundle_fd0f528d-69f4-4951-b231-95b31aad9fab_2024-05-26T06-07-58Z.zip)
