### ISSUE TITLE
[IMPROVEMENT] The client-go rest client rate limit inside the csi sidecar component might be too small (csi-provisioner, csi-attacjer. csi-snappshotter, csi-attacher) 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8699]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Summary: Looks like the default kubeAPIQPS  (5) and kubeAPIBurst (10)  inside [csi-provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/e7c0bcc89c20bc070e90cf734b51b9256d1e7170/cmd/csi-provisioner/csi-provisioner.go#L103-L104) and [csi-attacher](https://github.com/kubernetes-csi/external-attacher/blob/f30d22b35d45d52d9ca1c2515a0b8119c2d3a4ce/cmd/csi-attacher/main.go#L82-L84) might be too small and slow down the workload starting/detaching time (need to wait for volume provisioning and attaching)

Reproducing step:
1. Deploy a cluster of 1 master node and 3 worker node. Each worker node is an EC2 `m5zn.2xlarge` instance similar as in [this report](https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md#cluster-spec). Make sure each node has 1 TB EBS for Longhorn
1. Deploy Longhorn v1.6.1
1. Create a statefuleset with podManagementPolicy: Parallel
    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      ports:
      - port: 80
        name: web
      selector:
        app: nginx
      type: NodePort
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: web
      namespace: default
    spec:
      podManagementPolicy: Parallel
      selector:
        matchLabels:
          app: nginx
      serviceName: "nginx"
      replicas: 0
      template:
        metadata:
          labels:
            app: nginx
        spec:
          restartPolicy: Always
          terminationGracePeriodSeconds: 10
          containers:
          - name: nginx
            image: registry.k8s.io/nginx-slim:0.8
            livenessProbe:
              exec:
                command:
                  - ls
                  - /usr/share/nginx/html/lost+found
              initialDelaySeconds: 5
              periodSeconds: 5
            ports:
            - containerPort: 80
              name: web
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: www
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "longhorn"
          resources:
            requests:
              storage: 1Gi
    ```
1. Scale the stateful set to 400 pods
1. Observer that it takes 11 minutes to scale up 400 pods
1. There are tone of error message like this int he csi-provisioner: `2024-06-03T18:37:29.827838971Z I0603 18:37:29.827757       1 request.go:697] Waited for 18.057892986s due to client-side throttling, not priority and fairness, request: POST:https://10.43.0.1:443/api/v1/persistentvolumes`

## Describe the solution you'd like

Looks like the default kubeAPIQPS  (5) and kubeAPIBurst (10)  inside [csi-provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/e7c0bcc89c20bc070e90cf734b51b9256d1e7170/cmd/csi-provisioner/csi-provisioner.go#L103-L104) and [csi-attacher](https://github.com/kubernetes-csi/external-attacher/blob/f30d22b35d45d52d9ca1c2515a0b8119c2d3a4ce/cmd/csi-attacher/main.go#L82-L84) might be too small. Increase them to 50 and 100 (same as the Longhorn manager)

## Additional context

This is one test sample scale test that I run (scale from 0 to 500 pods at the same time)
![image](https://github.com/longhorn/longhorn/assets/22139961/cfdc59f7-e128-4f97-9d29-f0e51c842173)
