### ISSUE TITLE
[BUG] Installing Longhorn via ArgoCD: pre-upgrade Job stuck because serviceAccount is not existing

### ISSUE THREAD

**Issue by kastl-ars** [longhorn/longhorn#8707]
## Describe the bug
I am installing Longhorn on a rke2 cluster via ArgoCD. In the background, the helm chart is being used to install.

The ArgoCD sync starts a pre-upgrade Job, that is stuck in "Pending", as it requires a serviceAccount, that does not yet exist. And then everything hangs in limbo forever.

I aborted the sync in the ArgoCD GUI, synced only the serviceAccount and hooray, the next sync went fine and everything installed.

## To Reproduce

Use an ArgoCD application similar to this:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.6.2
      helm:
        releaseName: longhorn
        values: |
          ingress:
            enabled: false
          [...]
```

## Expected behavior

The pre-upgrade job should create the serviceAccount before the job is being created.

## Environment

 - Longhorn version: 1.6.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): ArgoCD/helm, see above
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
   - Number of control plane nodes in the cluster: 1 (which is also a worker)
   - Number of worker nodes in the cluster: 0
  - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0
