### ISSUE TITLE
[IMPROVEMENT] Collect and display disk space usage for the backing images

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8757]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn currently does not collect or display disk space usage for backing images. To help users better manage host storage, we need to improve this functionality as the volumes and replicas.

## Additional context

- UI ticket: https://github.com/longhorn/longhorn/issues/9325

**Comment by ChanYiLin** [comment]
## Test Steps

- Create a sparse file `test` (`$ truncate -s 512M backing.img`)
- Create a BackingImage `test` with this sparse file
- Create a BackingImage with a ubuntu image
- Check the node disk status (`$ kubectl get lhn -n longhorn-system`)
    - a new field `scheduledBackingImage` record the backing image on the disk and its real size
        - `test` real size is smaller than 512M
    - `storageScheduled` includes the size of BackingImage
```
        scheduledBackingImage:
          test: 53248
          ubuntu: 3860852736
        scheduledReplica: {}
        storageAvailable: 32820428800
        storageMaximum: 66257006592
        storageScheduled: 3860905984
```
