### ISSUE TITLE
[DOC] Cannot connect to NFS service

### ISSUE THREAD

**Issue by patrykk21** [longhorn/longhorn#8767]
## What's the document you plan to update? Why? Please describe

I'm not sure whether this is a bug, feature request or a documentation improvement. 
I'm not quite understanding how to achieve what I want to do.

In short: I want 2 pods from different namespaces to access the same data on the same volume.

I installed longhorn and was able to provision a volume by adding a persistent volume claim to my helm installation on namespace A.

I can see that there's a `pvc-2e028e26-6d57-48b9-96d4-67d6e4947f2f` service under the `longhorn-system` namespace.

So what I tried to do is to connect to such service from namespace B. It looks like this
<details>
<summary>PersistentVolume</summary>

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dispenser-audio-2
  namespace: "blender"
  labels:
    app.kubernetes.io/instance: blender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blender
    helm.sh/chart: blender-0.1.0
    app.kubernetes.io/component: any
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "longhorn-ext4-retain-nfs"
  nfs:
    path: "/"
    server: "pvc-2e028e26-6d57-48b9-96d4-67d6e4947f2f.longhorn-system.svc.cluster.local"
```
</details>

After scheduling the pod from namespace B I get the following error
```
MountVolume.SetUp failed for volume "dispenser-audio-2" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs pvc-2e028e26-6d57-48b9-96d4-67d6e4947f2f.longhorn-system.svc.cluster.local:/ /var/lib/kubelet/pods/6d620974-3291-4670-8a72-3b0383c0b3c1/volumes/kubernetes.io~nfs/dispenser-audio-2 Output: mount.nfs: Resource temporarily unavailable
```

I tried mounting manually from inside the pod or to ping the endpoint but they are unreachable.

I read anything I could find online, read the documentation multiple times and searched through issues but I couldn't help myself with this issue.
If anyone could help me solve this I would be very willing to offer a donation for a couple of coffees 😅 

Thank you for your time

## Additional context

_none_
