### ISSUE TITLE
Migrate volumes with `rancher.io/longhorn` provisioner to `driver.longhorn.io`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#878]
As part of CSI 1.1 upgrade, the new provisioner name is introduced. 

We need to help users to migrate from the old provisioners.

**Comment by shuo-wu** [comment]
Test step:
1. Deploy Longhorn v0.6.2 in a new cluster.
2. Launch some workloads. Write data into the Longhorn volumes then get the md5sum.
3. Upgrade Longhorn to v0.7.0 then to the latest. Remember to delete the StorageClass before v0.7.0 upgrade.
4. Create some volumes and PVs via Longhorn and other provisioners.
5. Run `./deploy/scripts/migrate <Running Longhorn volume name>`. It will do nothing but print out `Invalid state running for migrating volume xxx`.
6. Run `./deploy/scripts/migrate <The volume not created by Longhorn>`. It will error out with log `Error migrate volumes: Failed to migrate the old volume xxx: volumes.longhorn.io "xxx" not found`.
7. Run `./deploy/scripts/migrate <The volume created by Longhorn v0.8.0>`. It will do nothing but print out `There is no need to migrate volume xxx: the PV is not created by the old Longhorn`.
8. Shutdown workloads using the Longhorn v0.6.2 volumes and wait for the volumes detached. 
9. Run `./deploy/scripts/migrate --all`. Then the PVs and PVCs of all detached old volumes will be recreated. The PV and PVC is like:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
......
spec:
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: xxx
......


apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
......
spec:
......
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      diskSelector: ""
      nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: xxx
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
status:
  phase: Bound
```
10. Run `kl delete deployment compatible-csi-attacher`
11. Upgrade the engine image then re-deploy workloads for the detached old volumes. The volume can be attached and the data keeps unchanged.
