### ISSUE TITLE
[IMPROVEMENT] Problems mounting XFS volume clones / restored snapshots

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8796]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

XFS does not allow to mount two volumes that have the same UUID on the same machine. This is problematic when using a cloned volume or a restored snapshot - the original volume and the new volume cannot be mounted on the same compute node.

## Reproducing 

Reproducing:
1. Deploy the source-pvc with a pod 
    ```yaml
    allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: longhorn-xfs
    parameters:
      dataLocality: disabled
      disableRevisionCounter: 'true'
      fromBackup: ''
      fsType: xfs
      numberOfReplicas: '1'
      staleReplicaTimeout: '30'
      unmapMarkSnapChainRemoved: ignored
    provisioner: driver.longhorn.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: source-pvc
    spec:
      storageClassName: longhorn-xfs
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: source-pod
      namespace: default
    spec:
      nodeName: phan-v669-pool2-13d1bd68-qvrp8 # replace a a node in your cluster
      restartPolicy: Always
      containers:
      - name: source-pod
        image: ubuntu:xenial
        command: ["sleep", "3600"]
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: source-pvc
    ```
1. Deploy a new pod on same node with cloning-pvc cloned from the previous source-pvc
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: cloned-pvc
    spec:
      storageClassName: longhorn-xfs
      dataSource:
        name: source-pvc
        kind: PersistentVolumeClaim
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: cloning-pod
      namespace: default
    spec:
      nodeName: phan-v669-pool2-13d1bd68-qvrp8 # replace a a node in your cluster
      restartPolicy: Always
      containers:
      - name: cloning-pod
        image: ubuntu:xenial
        command: ["sleep", "3600"]
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: cloned-pvc
    ```
1. See error 
`Warning  FailedMount             0s (x2 over 1s)    kubelet                  MountVolume.MountDevice failed for volume "pvc-f621a3b8-0949-4621-97dc-c5bac2f05b31" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/longhorn/pvc-f621a3b8-0949-4621-97dc-c5bac2f05b31 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/72505ff8a4c307ba2db815cb3b08915c91bcd438400062105d959d89884dc13a/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/72505ff8a4c307ba2db815cb3b08915c91bcd438400062105d959d89884dc13a/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-f621a3b8-0949-4621-97dc-c5bac2f05b31, missing codepage or helper program, or other error.`
