### ISSUE TITLE
[BUG] Orphan longhorn-engine-manager and longhorn-replica-manager services 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8844]
## Describe the bug

When trying StackState, it detects that Longhorn system has 2 orphan longhorn-engine-manager and longhorn-replica-manager services with no available endpoint

![image](https://github.com/longhorn/longhorn/assets/22139961/a576cf33-9297-448e-944e-648398e3d729)

## To Reproduce

Just install a fresh Longhorn 1.5.x or 1.6.x version and see the orphan services 

## Expected behavior

In the past, we had instance manager engine and instance manager replica separately so these services are having selectors to select the correct IM:
```yaml
apiVersion: v1
kind: Service
metadata: 
  name: longhorn-engine-manager
  namespace: longhorn-system
spec: 
  selector: 
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: engine
---
apiVersion: v1
kind: Service
metadata: 
  name: longhorn-replica-manager
  namespace: longhorn-system
spec: 
  selector: 
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: replica
```

However, since 1.5.x, we combined the IM into instance manager AIO but forget to update the selector of the services. I think there are 2 action items:
1.  Investigate whether we need the 2 services. If not perhaps we should remove them
2. If they are still needed, we need to update the selector to point to the instance manager AIO
