### ISSUE TITLE
Pod has unbound immediate PersistentVolumeClaims (repeated 4 times)

### ISSUE THREAD

**Issue by aleksey005** [longhorn/longhorn#888]
After upgrade 0.6.2 to 0.7.0

Workload not start with error:

> Pod has unbound immediate PersistentVolumeClaims (repeated 4 times)

![image](https://user-images.githubusercontent.com/6145279/68943151-6a2f8780-07bb-11ea-92da-f40da04abc6f.png)

**Comment by aleksey005** [comment]
In version 0.7.0, the description of the storage of classes has apparently changed? Later in Longhorn 0.6.2 i create storage classes for ssd and nvme disks:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "ssd"
  nodeSelector: "rancher2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nvme
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "nvme"
  nodeSelector: "rancher2"
```
![image](https://user-images.githubusercontent.com/6145279/68944406-cf38ac80-07be-11ea-9239-2f1832847d36.png)

**Comment by aleksey005** [comment]
Please close.

Correct Storage class yaml: **provisioner: driver.longhorn.io**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "ssd"
  nodeSelector: "rancher2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nvme
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "nvme"
  nodeSelector: "rancher2"
```
