### ISSUE TITLE
[BUG] Encrypted volume can't be mounted to the workload

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9002]
## Describe the bug

in `master-head`, when mounting an encrypted volume to the workload got following error 
It seems it can't find the `cryptsetup` command during mounting
`stderr nsenter: failed to execute cryptsetup: No such file or directory: exit status 127`

```
Events:
  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Normal   Scheduled               19s              default-scheduler        Successfully assigned default/longhorn-simple-pod to kworker1
  Normal   SuccessfulAttachVolume  9s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c961900c-a077-4754-b710-695cdea6bc8e"
  Warning  FailedMount             5s (x4 over 8s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-c961900c-a077-4754-b710-695cdea6bc8e" : rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-c961900c-a077-4754-b710-695cdea6bc8e with LUKS: failed to execute: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-c961900c-a077-4754-b710-695cdea6bc8e -d /dev/stdin], output , stderr nsenter: failed to execute cryptsetup: No such file or directory
: exit status 127

```

## To Reproduce
- create secret
- create storageclass
- create PVC, PV and Volume
- create workload

```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Your encryption passphrase"
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-crypto-global
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto-global
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: longhorn-simple-pod
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: kworker1
  restartPolicy: Always
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: vol
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: longhorn-pvc
```

## Environment
I am sure I can use `cryptsetup` on my host.
But there is no `cryptsetup` command inside `longhorn-csi-plugin`
```
jacklin@jacklin:~/Documents/jacklin/longhorn-manager$ k exec -it po/longhorn-csi-plugin-5sh7m -n longhorn-system /bin/bash -c longhorn-csi-plugin
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
kworker2:/ # cryptsetup 
bash: cryptsetup: command not found
```

## Additional context

cc @c3y1huang @derekbit
