### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by johansmitsnl** [longhorn/longhorn#901]
I first filed it at K3S but with the help there it looks like a Longhorn issue.

See here the details of the issue: rancher/k3s#1042

**Comment by yasker** [comment]
Thanks for reporting. It probably gets something to do with https://github.com/longhorn/longhorn/issues/367 .

And thanks to @ericwilson providing the script to test https://github.com/rancher/k3s/issues/1042#issuecomment-554496269:
```
procs=$(ps -A -o pid,args)
openFiles=$(lsof)
pods=$(k3s crictl ps -a -o json | jq -r '.containers[] | .podSandboxId' | sort -u)
for pod in $pods; do 
  pid=$(echo "$procs" | grep $pod | awk '{ print $1 }')
  [ "$pid" ] || continue
  numOpen=$(echo "$openFiles" | grep -E "^container  *$pid " | wc -l)
  names=$(k3s crictl ps -a -o json | jq -r ".containers[] | select(.podSandboxId | match(\"$pod\")) | .metadata.name")
  echo $numOpen $names
done | sort -r -n
```

The result is at 
```
241873 replica-manager
241854 engine-image-ei-3827e67c engine-image-ei-3827e67c
241779 engine-manager
1125 plex-media-server
765 lb-port-8080 lb-port-443 lb-port-80
585 longhorn-csi-plugin driver-registrar
546 database assistant
405 longhorn-manager longhorn-manager
378 lb-port-51827
378 gitlab-runner
378 gitlab
378 authentication-backend
378 authentication-backend
378 authentication-backend
378 authentication-backend
351 lb-port-32400
351 authentication-backend
351 authentication-backend
```

@johansmitsnl Can we get Longhorn manager and instance manager logs? You can send us a support bundle(which contains all the logs) to `longhorn-support-bundle@rancher.com`

**Comment by yasker** [comment]
This looks like related to Kubernetes(or k3s)'s implementation of probing. @erikwilson

The pods of abnormal large FDs are the pods with either `livenessProbe` or `readinessProbe` set. It's in fact interesting since the pods like `engine-image-ei-3827e67c` don't run anything except copy a file then wait for exiting, so it shouldn't use any more FDs after the copy is done.

And here is an example yaml for a pod of `engine-image-ei-xxx`
```
- args:
    - -c
    - cp /usr/local/bin/longhorn* /data/ && echo installed && trap 'rm /data/longhorn*
      && echo cleaned up' EXIT && sleep infinity
    command:
    - /bin/bash
    image: longhornio/longhorn-engine:v0.7.0
    imagePullPolicy: Always
    name: engine-image-ei-ec95b5ad
    readinessProbe:
      exec:
        command:
        - ls
        - /data/longhorn
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
```

I've tried another pod with `livenessProbe` set, the rate of `lsof` is increasing at the rate of about 4.5 FDs per second. And `lsof` shows most of the FDs are `[eventfd]`.

I've checked another RKE 1.14.6 setup, everything seems normal on that.
