### ISSUE TITLE
[BUG] Share manager pods crashing

### ISSUE THREAD

**Issue by chrisarnott86** [longhorn/longhorn#9124]
## Describe the bug
Share manager pods are periodically getting stuck in a crash cycle. This seems to affect all the share manager pods on a single node at a time. This has happened on two nodes out of four in the cluster. The logs from the affected share managers give errors about the volume not being formatted and the UI shows actual size zero. With draining and re-enabling the affected node the volume does recover normally, but the pods using the volumes are obviously disrupted. dmesg from affected nodes shows errors in relation to block devices (e.g. "Buffer I/O error on dev sdc, logical block 1081664, lost async page write")

## To Reproduce

No specific trigger for the problem has been found.

## Expected behavior

Share manager pods (and hence RWX volumes) are stable.

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): Issue has arisen on different nodes, so no affected volumes can be any RWX volumes.
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.29.6+k3s2
   - Number of control plane nodes in the cluster: 4
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: Debian 11
   - Kernel version: 5.10.0-28-amd64
   - CPU per node: 8 
   - Memory per node: 32G
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): oVirt VMs
 - Number of Longhorn volumes in the cluster: 39

**Comment by derekbit** [comment]
Could you provide a support bundle with the issue?

**Comment by chrisarnott86** [comment]
Bundle sent to longhorn-support-bundle@suse.com via we transfer.

**Comment by chrisarnott86** [comment]
> Could you provide a support bundle with the issue?

Have you managed to retrieve the support bundle that I sent? Is there a better way to send it (800MB)?

**Comment by derekbit** [comment]
cc community coordinator @ChanYiLin

**Comment by chrisarnott86** [comment]
Hi @derekbit and @ChanYiLin, this problem has happened again a few times since I opened this issue. I have an up to date support bundle (~600MB), is there someone who could look into this? Many thanks.

**Comment by derekbit** [comment]
@chrisarnott86 Sure. Can you send us the link for the support bundle? Thanks.

**Comment by chrisarnott86** [comment]
What's the best way of sharing this (given the large size)?

**Comment by derekbit** [comment]
> What's the best way of sharing this (given the large size)?

Upload to a cloud storage and share us the link.

**Comment by chrisarnott86** [comment]
Hi @derekbit and @ChanYiLin. This problem has occurred again, and this time draining one node caused all share-manager pods to restart regardless of which node they were running on. This issue is making our production cluster a lot less reliable than we would want so if someone could look into this I would be very grateful. I appreciate that time and people are limited though!

**Comment by chrisarnott86** [comment]
Hi, @derekbit, @ChanYiLin, @innobead. This has happened again a couple of times. Here's a link to the latest support bundle. https://stir-my.sharepoint.com/:u:/g/personal/cpa00004_students_stir_ac_uk/EQSsZf_p_xpMmtLOlAMtAZUBE5WCsTkfxJiCJZf9meQZ1A?e=YNC3ld The most recent time, and at least one other time the problem seems to coincide with the k3s process being restarted on nodes. After k3s restart it seems some nodes may be fine and on others the share manager pods have a problem. I'm not totally sure if the issue has always coincided with a k3s restart, but it's at least a possible avenue of investigation. Thanks

**Comment by derekbit** [comment]
@chrisarnott86 What's the problematic volume?
I'm aware of the underlying disks are HDDs which are not suitable for Longhorn because the high latencies might lead to engine crash.

@james-munson Can you help investigate the issue? Thanks.

**Comment by james-munson** [comment]
his is showing all the hallmarks of the issues in
  https://github.com/longhorn/longhorn/issues/7802
  https://github.com/longhorn/longhorn/issues/8289
  https://github.com/longhorn/longhorn/issues/8587

There is the "wrong API version received: 0x5250".

```
logs/longhorn-system/instance-manager-66d0b2c72602a704e5e004db1540ba29/instance-manager.log:2024-09-08T10:03:42.328871799+01:00 [grafana-restore-r-42f03829] time="2024-09-08T09:03:41Z" level=error msg="Failed to read" func="dataconn.(*Server).readFromWire" file="server.go:42" error="wrong API version received: 0x5250"
```

There are 5 of those in the logs from 09/02

```
SupportBundles/9124/2024-09-02$ grep -ri "wrong api" | wc
      5      69    1671
```
But more on 09/09:

```
SupportBundles/9124/2024-09-09$ grep -ri "wrong api" | wc
   1811   25082  609934
```

```
2024-09-09T08:41:42.142306889+01:00 [pvc-fed1dcbb-8375-4ebd-b714-6ce0ecc09b41-r-71a69620] time="2024-09-09T07:41:42Z" level=error msg="Invalid gRPC metadata" func=rpc.NewReplicaServer.WithIdentityValidationReplicaServerInterceptor.identityValidationServerInterceptor.func1 file="interceptor.go:37" clientVolumeName=pvc-96f13ccd-8a16-43bc-8512-40396b999382 method=/ptypes.ReplicaService/ReplicaClose serverVolumeName=pvc-fed1dcbb-8375-4ebd-b714-6ce0ecc09b41
```

In the logs from 09/02,
```
grep -ri interceptor | wc
     90    1075   46585
```

And in the logs for 09/09, there are quite a few of them, for various volumes.
```
grep -ri interceptor | wc
   9992  119869 5430379
```
In each case, there is an interruption from kubelet in the events.yaml:

```yaml
    involvedObject:
      kind: Node
      name: k3s4
      uid: k3s4
    kind: Event
    lastTimestamp: "2024-09-02T07:45:19Z"
    message: 'Node k3s4 status is now: NodeNotSchedulable'
...
    involvedObject:
      kind: Node
      name: k3s4
      uid: k3s4
    kind: Event
    lastTimestamp: "2024-09-02T08:00:19Z"
    message: 'Node k3s4 status is now: NodeSchedulable'
```

And

```yaml
    involvedObject:
      kind: Node
      name: k3s3
      uid: k3s3
    kind: Event
    lastTimestamp: "2024-09-09T07:40:46Z"
    message: 'Node k3s3 status is now: NodeNotSchedulable'
...
    involvedObject:
      kind: Node
      name: k3s3
      uid: k3s3
    kind: Event
    lastTimestamp: "2024-09-09T07:44:11Z"
    message: 'Node k3s3 status is now: NodeSchedulable'
```
