### ISSUE TITLE
[BUG] Node block-type disk is unable to unbind after Longhorn uninstall

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9127]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Node block-type disk is unable to unbind after Longhorn uninstall

## Describe the solution you'd like

If we uninstall Longhorn and reinstall Longhorn again, the NVMe disk is not found on the host side. 
We could not add the previously used disk to Longhorn. 
We still need to access the `instance-manager` pod and unbind it manually:
The workaround is simply unbind the disk by `spdk/scripts/setup.sh unbind <BDF>`.

```bash
instance-manager-07620dc5b1e813c9290c48c97ab556de:/ # go-spdk-helper setup unbind 0000:46:00.0
instance-manager-07620dc5b1e813c9290c48c97ab556de:/ # go-spdk-helper setup unbind 0000:00:1f.0
instance-manager-07620dc5b1e813c9290c48c97ab556de:/ # 
```

## Describe alternatives you've considered

1. Create a LH clusters using AWS EC2 `c5d.2xlarge` machines with a NVMe disk
2. Enable v2 data engine
3. Get the BDF of the disk by checking `ls -al /sys/block`.
```bash
root@ip-10-0-2-95:~# ls -al /sys/block/
total 0
lrwxrwxrwx  1 root root 0 Jul 30 10:49 nvme0n1 -> ../devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
lrwxrwxrwx  1 root root 0 Jul 30 10:49 nvme1n1 -> ../devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1
```
4. Add the disk to node.disks
`kubuctl -n longhorn-system edit nodes.longhorn.io w1`
```yaml
        default-disk-block-1:
          allowScheduling: true
          diskDriver: auto
          diskType: block
          evictionRequested: false
          path: 0000:00:1f.0
          storageReserved: 0
          tags: []
```
5. Check the node.status.diskStatus. The disk is detected without any error, and the diskDriver is nvme.
6. Uninstall Longhorn
7. Get the BDF of the disk by checking `ls -al /sys/block`. again.

## Additional context
https://github.com/longhorn/longhorn/issues/8813#issuecomment-2252407817
https://github.com/longhorn/longhorn/issues/9126#issuecomment-2259386841
https://github.com/longhorn/longhorn/issues/7672#issuecomment-1956174494
