### ISSUE TITLE
[BUG] tolerations and node selectors options are ignored for longhorn-csi and engine-image

### ISSUE THREAD

**Issue by b-milescu** [longhorn/longhorn#9136]
## Describe the bug

I've deployed Longhorn in a EKS cluster v1.30 using Helm on 3 dedicated nodes.
I've used the recommendations per the documents https://longhorn.io/docs/1.6.2/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn
This is how my value helm file looks like:

```
defaultSettings:
  taintToleration: "dedicated=storage-node:NoSchedule"
  systemManagedComponentsNodeSelector: "role=storage"

longhornManager:
  nodeSelector:
    role: "storage"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "storage-node"
    effect: "NoSchedule"
longhornDriver:
  nodeSelector:
    role: "storage"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "storage-node"
    effect: "NoSchedule"
longhornUI:
  nodeSelector:
    role: "storage"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "storage-node"
    effect: "NoSchedule"
```

Helm install command:
`helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.6.2 -f values.yaml'

helm get values longhorn -n longhorn-system
```
USER-SUPPLIED VALUES:
defaultSettings:
  systemManagedComponentsNodeSelector: role=storage
  taintToleration: dedicated=storage-node:NoSchedule
longhornDriver:
  nodeSelector:
    role: storage
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: storage-node
longhornManager:
  nodeSelector:
    role: storage
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: storage-node
longhornUI:
  nodeSelector:
    role: storage
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: storage-node
```
## To Reproduce

1. copy/paste the above settings for the value file
2. run the above mentioned command

## Expected behavior

The csi-plugin/engine-image pods should be deployed on the nodes in respect to taints/selectors.

## Environment

 - Longhorn version:  1.6.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS 1.30
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Amazon AL2023
   - Kernel version:
   - CPU per node: varies
   - Memory per node: varies
   - Disk type (e.g. SSD/NVMe/HDD): gp3
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): EKS
 - Number of Longhorn volumes in the cluster: 3
