### ISSUE TITLE
[BUG] Encrypt volume provided size is 16MB shorter than the claimed size

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#9205]
## Describe the bug

LH encrypt volume's actual size is 16MB shorter than the claimed size, this could cause integrity issues for space-sensitive applications.

## To Reproduce (follow test plan in https://github.com/longhorn/longhorn/issues/4883#issuecomment-1619514908)
- Creating secret
  ```
  apiVersion: v1
  kind: Secret
  metadata:
    name: longhorn-crypto
    namespace: longhorn-system
  stringData:
    CRYPTO_KEY_VALUE: "simple"
    CRYPTO_KEY_PROVIDER: "secret"
  ```
- Creating storage class
  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-migratable
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  parameters:
    numberOfReplicas: "1"
    staleReplicaTimeout: "2880" # 48 hours in minutes
    fromBackup: ""
    migratable: "true"
    encrypted: "true"
    csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
    csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
    csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
    csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
    csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
    csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  ```
- Creating encrypted volume
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: longhorn-block-pvc
    namespace: default
  spec:
    accessModes:
      - ReadWriteMany
    volumeMode: Block
    storageClassName: longhorn-migratable
    resources:
      requests:
        storage: 5Gi
  ```
- Attaching encrypted volume to a Linux pod
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: block-volume-test
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/longhorn-block-pvc
        name: longhorn-block-pvc
    volumes:
      - name: longhorn-block-pvc
        persistentVolumeClaim:
          claimName: longhorn-block-pvc
  ```
- Finding the actual dm-crypt device is 16MB shorter than the claimed size
  - The dm-crypt device with 5104 MB (10452992*2^9/2^20) rather than 5GB
  ```
  # dmsetup table
  pvc-4a0ea213-6de7-4fa1-9377-b031d40fdc9e: 0 10452992 crypt aes-xts-plain64 :32:logon:cryptsetup:57fb921a-2059-4628-975c-a057bc4373e8-d0 0 8:0 32768
  ```

## Expected behavior
The provided encrypt size should be the same as the claimed one

## Environment
Longhorn v1.6.2

## Additional context
Found this issue during the survey https://github.com/harvester/harvester/issues/6280
