### ISSUE TITLE
[BUG] Networking between longhorn-csi-plugin and longhorn-manager is broken after upgrading Longhorn to 1.7.0-rc3 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9223]
## Describe the bug

This issue came out the troubleshooting with @bk201, @Vicente-Cheng, @starbops, and myself at the thread https://suse.slack.com/archives/C02DR3N5T24/p1723085198729569

With network policy enabled, networking between longhorn-csi-plugin and longhorn-manager is broken after upgrading Longhorn to 1.7.0-rc3 

## To Reproduce

1. Install Longhorn 1.6.2 with network policy enabled (A.K.A set [this field](https://github.com/longhorn/longhorn/blob/c7a70c96c31a4b1710a6a9dd4a5092551aac1e14/chart/values.yaml#L28) to `true`)
2. Upgrade Longhorn to 1.7.0-rc3 (still with networking policy enable)
3. See that many CSI pod stuck in crash loop. Noticeably, longhorn-csi-plugin pods crashes repeatedly because it cannot reach out to longhorn-backend service:
    ```
    time="2024-08-08T02:46:10Z" level=info msg="CSI Driver: driver.longhorn.io version: v1.7.0-rc3, manager URL http://longhorn-backend:9500/v1" func="csi.(*Manager).Run" file="manager.go:23"
    time="2024-08-08T02:46:20Z" level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": context deadline exceeded (Client
    .Timeout exceeded while awaiting headers)" func=app.CSICommand.func1 file="csi.go:37"
    ```
4. Further notice that longhorn-csi-plugin pod cannot ping longhorn-manager pod on different node but can ping the longhorn-manager pod on the same node

## Expected behavior

Networking between longhorn-csi-plugin and longhorn-manager is not broken 

## Environment

 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.11+rke2r1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3

**Comment by PhanLe1010** [comment]
Update:

Narrowed it down to the problematic network policy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: longhorn
    meta.helm.sh/release-namespace: longhorn-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: longhorn-manager
  namespace: longhorn-system
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: longhorn-manager
        - podSelector:
            matchLabels:
              app: longhorn-ui
        - podSelector:
            matchLabels:
              app: longhorn-csi-plugin
        - podSelector:
            matchExpressions:
              - key: recurring-job.longhorn.io
                operator: Exists
            matchLabels:
              longhorn.io/managed-by: longhorn-manager
        - podSelector:
            matchExpressions:
              - key: longhorn.io/job-task
                operator: Exists
        - podSelector:
            matchLabels:
              app: longhorn-driver-deployer
  podSelector:
    matchLabels:
      app: longhorn-manager
  policyTypes:
    - Ingress
```

If we remove all network policies. Then deploy this one, then longhorn-csi-plugin cannot reach longhorn-manager on other nodes. This is very weird because this `longhorn-manager` network policy specifically allow network between longhorn-csi-plugin and longhorn-manager. Not sure why network is being blocked like this

**Comment by PhanLe1010** [comment]
Simpler reproducing:

1. Install longhorn 1.7.0-rc3
2. Deploy the network policy:
    ```
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: longhorn-manager
      namespace: longhorn-system
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: longhorn-manager
            - podSelector:
                matchLabels:
                  app: longhorn-ui
            - podSelector:
                matchLabels:
                  app: longhorn-csi-plugin
            - podSelector:
                matchExpressions:
                  - key: recurring-job.longhorn.io
                    operator: Exists
                matchLabels:
                  longhorn.io/managed-by: longhorn-manager
            - podSelector:
                matchExpressions:
                  - key: longhorn.io/job-task
                    operator: Exists
            - podSelector:
                matchLabels:
                  app: longhorn-driver-deployer
      podSelector:
        matchLabels:
          app: longhorn-manager
      policyTypes:
        - Ingress
    ```
1. See the longhorn-csi-plugin cannot ping longhorn-manager on different node. 
1. This not happening in longhorn v1.6.2
