### ISSUE TITLE
[BUG] Volume stuck in degraded

### ISSUE THREAD

**Issue by docbobo** [longhorn/longhorn#9279]
## Describe the bug

I have this one volume in my system, that seems to be stuck in Degraded mode. This happened with 1.6.2 and upgrading to 1.7.0 didn't fix this either. With the latter, I am seeing the following in the volumes Events section though:

```
Failed rebuilding replica with Address 10.244.244.251:10000: proxyServer=10.244.122.244:8501 destination=10.244.122.244:10012: failed to add replica tcp://10.244.244.251:10000 for volume: rpc error: code = Unknown desc = failed to prepare rebuilding replica tcp://10.244.244.251:10000 for volume 10.244.122.244:10012: rpc error: code = Unknown desc = failed to set revision counter for tcp://10.244.244.251:10000: failed to set revision counter to 0 for replica 10.244.244.251:10000 from remote: rpc error: code = Unknown desc = BUG: revision file wasn't initialized
```

The only meaningful thing that ever happened to this volume was setting it to `strict-local` as a test, then back to `best-effort`. Having this problem ever since, I believe.

## Environment

 - Longhorn version: 1.7.0
 - Impacted volume (PV): pvc-2064afaf-8de8-48e4-959d-188ed2dd99b3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via ArgoCD
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos 1.7.6
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: Talos
   - Kernel version: 6.6.x I believe
   - CPU per node: 4+4
   - Memory per node: 32GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 1GBe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 18

**Comment by mantissahz** [comment]
Hi @docbobo,

Could you please provide the support bundle and specify which volume is problematic?

**Comment by docbobo** [comment]
Just sent the bundle, @mantissahz. The volume is quoted above, but I also mentioned it in Support Bundle & Email

**Comment by derekbit** [comment]
Always failed to rebuild newly added replica
```
2024-08-22T09:16:33.794528643Z time="2024-08-22T09:16:33Z" level=error msg="Failed to rebuild replica 10.244.244.251:10000" func="controller.(*EngineController).startRebuilding.func2" file="engine_controller.go:1960" controller=longhorn-engine engine=pvc-2064afaf-8de8-48e4-959d-188ed2dd99b3-e-0 error="proxyServer=10.244.122.244:8501 destination=10.244.122.244:10012: failed to add replica tcp://10.244.244.251:10000 for volume: rpc error: code = Unknown desc = failed to prepare rebuilding replica tcp://10.244.244.251:10000 for volume 10.244.122.244:10012: rpc error: code = Unknown desc = failed to set revision counter for tcp://10.244.244.251:10000: failed to set revision counter to 0 for replica 10.244.244.251:10000 from remote: rpc error: code = Unknown desc = BUG: revision file wasn't initialized" node=talos-tp1-n4 volume=pvc-2064afaf-8de8-48e4-959d-188ed2dd99b3
```

- Global setting `disable-revision-counter` is set to `true`
- volume `pvc-2064afaf-8de8-48e4-959d-188ed2dd99b3`'s `spec.revisionCounterDisabled` is `true`
- engine `revisionCounterDisabled`'s `spec.revisionCounterDisabled` is `false`

The newly added replica failed to rebuild because `revisionCounterDisabled` is somehow `false`. The rebuilding process tried to find the revision file, but it was not existing.

A workaround is to manually change the engine `pvc-2064afaf-8de8-48e4-959d-188ed2dd99b3-e-0`'s `spec.revisionCounterDisabled` is `true`.

@docbobo Can you try the workaround? Thank you.

--

@mantissahz Could you help figure out the root cause of the mismatch? If it is a regression, we can fix it v1.7.1.

cc @innobead

**Comment by docbobo** [comment]
Setting `revisionCounterDisabled` tor `true` for the engine does not work. When the volume get attached, it switches to faulted state.

**Comment by derekbit** [comment]
> Setting `revisionCounterDisabled` tor `true` for the engine does not work. When the volume get attached, it switches to faulted state.

Sounds weird. Can you provide a support bundle again?

**Comment by derekbit** [comment]
cc @PhanLe1010

**Comment by docbobo** [comment]
Just sent the new support bundle, @derekbit. Thanks for pointing out the backup.

**Comment by PhanLe1010** [comment]
@docbobo 
Quick question, was this Longhorn installation ever on version 1.4.x?

**Comment by PhanLe1010** [comment]
Oh. I found a SystemBackup CR with version v1.4.2 so it is is `yes` for the above question
```yaml
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
  kind: SystemBackup
  metadata:
    creationTimestamp: "2024-04-26T20:38:27Z"
    labels:
      longhorn.io/version: v1.4.2
    name: "2023-06-23"
    namespace: longhorn-system
  spec:
    volumeBackupPolicy: if-not-present
  status:
    conditions: "null"
    createdAt: "2023-06-23T13:01:48Z"
    gitCommit: 6856fd35ee1739f517b78be9e1c6df38171be458
    lastSyncedAt: "2024-04-26T20:38:27Z"
    managerImage: longhornio/longhorn-manager:v1.4.2
    ownerID: talos-tp1-n1
    state: Ready
    version: v1.4.2
```
