### ISSUE TITLE
How to customize the download address of the image？

### ISSUE THREAD

**Issue by xiaoqge** [longhorn/longhorn#930]
In the process of starting the longhorn service, in the yaml file, I want the images to use their own docker repository addresses, but some mirrors cannot customize the docker repository?For example this：

```
longhorn-csi-plugin-5ngxc                  1/2     ImagePullBackOff   0          8d
longhorn-csi-plugin-74ngr                  2/2     Running            0          8d
longhorn-csi-plugin-88ndm                  1/2     ImagePullBackOff   0          8d
longhorn-csi-plugin-cfnn2                  1/2     ImagePullBackOff   0          8d
longhorn-csi-plugin-jxjpk                  1/2     ImagePullBackOff   0          8d
longhorn-csi-plugin-nvpq5                  2/2     Running            0          8d
longhorn-csi-plugin-qnt26                  1/2     ImagePullBackOff   0          8d
longhorn-csi-plugin-tn4jq                  1/2     ImagePullBackOff   0          8d
```

**Comment by shuo-wu** [comment]
If you want to customize the image for `csi` related Longhorn workloads, you can modify the `longhorn-driver-deployer` in [the longhorn deployment yaml file](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml). e.g.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      initContainers:
        - name: wait-longhorn-manager
          image: <Your longhorn manager image>
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: longhorn-driver-deployer
          image: <Your longhorn manager image>
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - <Your longhorn manager image>
          - --manager-url
          - http://longhorn-backend:9500/v1
          - --csi-attacher-image
          - <Your csi attacher image>
          - --csi-provisioner-image
          - <Your csi provisioner image>
          - --csi-node-driver-registrar-image
          - <Your node driver registrar image>          
...
```

For Longhorn v0.7.0, the default images are `quay.io/k8scsi/csi-attacher:v2.0.0`, `quay.io/k8scsi/csi-provisioner:v1.4.0`, and `quay.io/k8scsi/csi-node-driver-registrar:v1.2.0`.
