### ISSUE TITLE
[IMPROVEMENT] Longhorn CLI should install `cryptsetup`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9315]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The error is found by Longhorn node status

```
status:
  autoEvicting: false
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2024-08-26T16:34:35Z"
    message: Node t3a-xlarge-sles15p6-pool1-b32f42c0-g5dcm is ready
    reason: ""
    status: "True"
    type: Ready
  - lastProbeTime: ""
    lastTransitionTime: "2024-08-26T16:34:35Z"
    message: ""
    reason: ""
    status: "True"
    type: Schedulable
  - lastProbeTime: ""
    lastTransitionTime: "2024-08-26T16:35:05Z"
    message: ""
    reason: ""
    status: "True"
    type: MountPropagation
  - lastProbeTime: ""
    lastTransitionTime: "2024-08-26T16:35:05Z"
    message: 'Missing packages: [cryptsetup]'
    reason: PackagesNotInstalled
    status: "False"
    type: RequiredPackages
```

## Additional context

cc @mantissahz @innobead
