### ISSUE TITLE
[IMPROVEMENT] Add support of new StorageClass parameters to helm chart

### ISSUE THREAD

**Issue by kudodenko** [longhorn/longhorn#9324]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In the latest versions of longhorn, new StorageClass parameters have been added, but helm chart does not support these parameters (eg shareManagerNodeSelector, allowedTopologies and shareManagerTolerations).

## Describe the solution you'd like

Add this parameters to helm chart.

## Describe alternatives you've considered

Didn't consider anything

## Additional context

New parameters described [here](https://longhorn.io/docs/1.7.0/nodes-and-volumes/volumes/rwx-volumes/#sharemanagernodeselector)
But not allowed in helm chart [values.yaml](https://github.com/longhorn/charts/blob/v1.7.x/charts/longhorn/values.yaml)

Thanks in advance!

**Comment by TheFutonEng** [comment]
## Pre Ready-For-Testing Checklist
* [ ] **Context & Reproduction**
    Where are the reproduction or test steps documented?
    Link: N/A

* [x] **Workaround**
    Is there a workaround for the issue? If yes, where is it documented?
    Link: Yes, manually update the `longhorn` `storageClass` to modify the `shareManagerNodeSelector` and `shareManagerTolerations` after a deployment.  This is not an ideal solution and would be better integrated into the Longhorn Helm chart.

* [x] **Fix / Feature Explanation**
    Does the PR include a clear explanation of the fix or the new feature?
    Yes.

* [ ] **Code Changes**
    Have all required code changes been merged?
    PR(s): No, [this](https://github.com/longhorn/longhorn/pull/12970) is the only open PR to introduce the changes (that I am aware of).

* [x] **Deployment Changes (YAML / Helm Chart)**
    Does the PR introduce any deployment changes?
    PR: Yes, the aforementioned [PR](https://github.com/longhorn/longhorn/pull/12970) is purely to introduce deployment changes.

* [ ] **Longhorn Enhancement Proposal (LEP)** *(if labeled `require/LEP`)*
    Has the LEP PR been submitted?
    PR: There is no `require/LEP` label on the ticket.  I imagine this is not required since the PR is only introducing deployment changes.

* [ ] **Documentation Updates** *(if labeled `require/doc`)*
    Has the required documentation PR been submitted or merged?
    PR:

* [ ] **Manual Test Plan** *(if labeled `require/manual-test-plan`)*
    Has the manual test plan been documented?
    Link:

**Comment by COLDTURNIP** [comment]
Verification steps: https://github.com/longhorn/longhorn/pull/12970#issuecomment-4316210313

**Comment by yangchiu** [comment]
Tested on master-head (longhorn/longhorn da2b0e3) by following [the test steps](https://github.com/longhorn/longhorn/pull/12970#issuecomment-4316210313).

1. Install Longhorn via `helm` with the following values:

  ```yaml
  persistence:
    shareManagerNodeSelector:
      enable: true
      selector: "storage:true"
  ```
  
2. Check the value is applied by inspecting the `longhorn-storageclass` ConfigMap:
  
```
$ kubectl get cm longhorn-storageclass -n longhorn-system -o jsonpath='{.data.storageclass\.yaml}'
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  shareManagerTolerations: "storage:true"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  backupTargetName: "default"
```                                                                                                    

3.  Check the value is applied by inspecting the `longhorn` StorageClass:
```
$ kubectl get sc longhorn -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        fsType: "ext4"
        dataLocality: "disabled"
        shareManagerTolerations: "storage:true"
        unmapMarkSnapChainRemoved: "ignored"
        disableRevisionCounter: "true"
        dataEngine: "v1"
        backupTargetName: "default"
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2026-05-04T00:35:34Z"
  name: longhorn
  resourceVersion: "8240"
  uid: 1056e68d-6163-4adf-ba10-ca172a17a7ed
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  shareManagerTolerations: storage:true
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
  
4. Label a node (ip-10-0-1-209) with `storage=true`:

```
$ kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels}{"\n"}{end}'
ip-10-0-1-209	{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"k3s","beta.kubernetes.io/
os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-10-0-1-209","kubernetes.io/os":"linux","node.kubernetes.io/
instance-type":"k3s","storage":"true"}
ip-10-0-1-223	{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"k3s","beta.kubernetes.io/
os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-10-0-1-223","kubernetes.io/os":"linux","node.kubernetes.io/
instance-type":"k3s"}
ip-10-0-1-52	{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"k3s","beta.kubernetes.io/
os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-10-0-1-52","kubernetes.io/os":"linux","node.kubernetes.io/
instance-type":"k3s"}
ip-10-0-1-82	{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"k3s","beta.kubernetes.io/
os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-10-0-1-82","kubernetes.io/os":"linux","node-role.kubernetes.io/
control-plane":"true","node.kubernetes.io/instance-type":"k3s"}
```

5. Create a  `ReadWriteMany` workload using the default Longhorn StorageClass:

```                                                                                                      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rwx
  labels:
    app: deployment-rwx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-rwx
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000       # Arbitrary non-root UID
        runAsGroup: 1000      # Arbitrary non-root GID
        fsGroup: 1000
      containers:
        - image: alpine/git
          imagePullPolicy: IfNotPresent
          name: sleep
          command: [ "/bin/sh", "-c" ]
          args: [ 'while true;do date;sleep 5; done' ]
          volumeMounts:
            - name: pod-data
              mountPath: /data
      volumes:
      - name: pod-data
        persistentVolumeClaim:
          claimName: vol-1                             
```             

6. The share manager pod for the volume is __not__ scheduled only on a node labeled `storage=true`:

```
$ kubectl get pod -n longhorn-system -l longhorn.io/component=share-manager -o wide
NAME                                                     READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
share-manager-pvc-a71a387f-6293-459d-b74a-6b479e37cfbe   1/1     Running   0          22m   10.42.1.27   ip-10-0-1-52   <none>           <none>
``` 

@COLDTURNIP Could you help check if there is anything missing from the steps? Many thanks!

**Comment by COLDTURNIP** [comment]
Hi @yangchiu , the above configmap `longhorn-storageclass` contains a customized `shareManagerTolerations` and does not match the pasted configmap. Could we validate this ticket again with the customized `shareManagerNodeSelector`?

```yaml
persistence:
  shareManagerNodeSelector:
    enable: true
    selector: "storage:true"
```

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn/longhorn 5252122) by following [the test plan](https://github.com/longhorn/longhorn/pull/12970#issuecomment-4316210313).

* **shareManagerNodeSelector**

1. Install Longhorn via Helm with the following values:
```
persistence:
  shareManagerNodeSelector:
    enable: true
    selector: "storage:true"
```
2. Check the setting is applied to the default storage class:
```
$ kubectl get sc longhorn -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  shareManagerNodeSelector: storage:true
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Label a node with `storage=true`:
```
kubectl label node ip-10-0-1-237 storage=true
```
4. Create a workload using RWX PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rwx
  labels:
    app: deployment-rwx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-rwx
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000       # Arbitrary non-root UID
        runAsGroup: 1000      # Arbitrary non-root GID
        fsGroup: 1000
      containers:
        - image: alpine/git
          imagePullPolicy: IfNotPresent
          name: sleep
          command: [ "/bin/sh", "-c" ]
          args: [ 'while true;do date;sleep 5; done' ]
          volumeMounts:
            - name: pod-data
              mountPath: /data
      volumes:
      - name: pod-data
        persistentVolumeClaim:
          claimName: vol-1
```
5. Check share manager pod is running on the labelled node:
```
$ kubectl get pod -n longhorn-system -l longhorn.io/component=share-manager -o wide
share-manager-pvc-ab0c43e9-bd77-4d7c-821b-2232fe9fd783   1/1     Running   0              54s     10.42.3.13   ip-10-0-1-237   <none>           <none>
```

* **shareManagerTolerations**

1. Install Longhorn via Helm with the following values:
```
  persistence:
    shareManagerTolerations:
      enable: true
      tolerations: "dedicated=storage:NoSchedule"
```
2. Check the setting is applied to the default storage class:
```
$ kubectl get sc longhorn -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  shareManagerTolerations: dedicated=storage:NoSchedule
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
2. Delete 2 nodes from the cluster to create a single-node cluster
3. Taint the remaining node with `dedicated=storage:NoSchedule`:
```
kubectl taint nodes ip-10-0-1-237 dedicated=storage:NoSchedule
```
4. Create a workload with toleration to `dedicated=storage:NoSchedule` and using RWX PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rwx
  labels:
    app: deployment-rwx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-rwx
    spec:
      restartPolicy: Always
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "storage"
          effect: "NoSchedule"
      securityContext:
        runAsUser: 1000       # Arbitrary non-root UID
        runAsGroup: 1000      # Arbitrary non-root GID
        fsGroup: 1000
      containers:
        - image: alpine/git
          imagePullPolicy: IfNotPresent
          name: sleep
          command: [ "/bin/sh", "-c" ]
          args: [ 'while true;do date;sleep 5; done' ]
          volumeMounts:
            - name: pod-data
              mountPath: /data
      volumes:
      - name: pod-data
        persistentVolumeClaim:
          claimName: vol-1
```
5.  Check share manager pod is running on the tainted node:
```
$ kubectl get pod -n longhorn-system -l longhorn.io/component=share-manager -o wide
share-manager-pvc-ab0c43e9-bd77-4d7c-821b-2232fe9fd783   1/1     Running   0              54s     10.42.3.13   ip-10-0-1-237   <none>           <none>
```
