### ISSUE TITLE
[IMPROVEMENT] Avoid "full data transfer" when rebuilding two failed replicas

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#9335]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

With the default setting `auto-cleanup-system-generated-snapshot == true` and no user-created snapshots, if two replicas fail before either has the chance to be rebuilt, at least one "full data transfer" is required to bring the volume back to a healthy state. This is true even if there is no I/O between the moment the first replica fails and the last is rebuilt (so the replicas actually contain the exact same data). See the diagram below for a description of why this occurs.

![Full Data Transfer](https://github.com/user-attachments/assets/2f742d24-4adf-42c8-aa1e-23ae784786f6)

## Describe the solution you'd like

The North America team brainstormed this in a sync yesterday. Here are some ideas we generated.

- Add an additional option for `auto-cleanup-system-generated-snapshot` like `conditional`:
   - Don't purge before a rebuild if doing so would not "significantly" decrease consumed space.
   - Don't purge after a rebuild if the volume is still degraded and doing so would not "significantly" decrease consumed space.
- Somehow remember "past names" in on-disk snapshot metadata. E.g., remember that system-snap2 coalesced from system-snap1, so try to rename system-snap1 to system-snap2 on the rebuilding replica and do a delta sync.
   - It's really not clear how this would work. Theoretically every snapshot in the chain has been coalesced from previous snapshots, so where do we stop?
- Under certain conditions, always try to delta sync the base snapshot. In the diagram, `system_snap2` and `system_snap1` are very close to the same. We could use some heuristic (e.g. they use about the same consumed space) to decide to rename `system_snap1` to `system_snap2` when rebuilding replica1 and do a delta sync.

This issue was originally discovered in the context of a cluster undergoing maintenance. node1 was drained and rebooted, then node2 was drained and rebooted. Since node3 still contained healthy replicas, Longhorn did not stop node2 from draining and rebooting. However, this meant that replicas on node1 and replicas on node2 were failed at the same time. It is likely that replicas on node2 required a full data transfer to rebuild. Here are some ideas the North America team brainstormed in context:

- Manually disable `auto-cleanup-system-generated-snapshot` before doing maintenance.
   - This should prevent "full data transfer" occurrences.
   - The user must remember to re-enable it.
   - The user should probably use a recurring job to clean up the system snapshots when maintenance is complete. If they do not, and rebuilds only occur during maintenance, they will accrue many extra snapshots over time.
- Use a recurring job to take a user-created snapshot once per day.
   - Most of the data will be in the user-created snapshot, which can definitely be delta synced.
   - Unless write activity is very heavy, this won't result in too much additional space consumption.
   - In combination with `snapshot-data-integrity-check-after-creating-a-snapshot` (defaults to `false`), the user-created snapshot generally wouldn't need to be synced between replicas at all. This could even speed up rebuilds that don't require a "full data transfer".
- Take a user-created snapshot of all volumes before maintenance.
   - Similar to the above, but on-demand.
   - However, unless the user intentionally cleaned up all of these snapshots, they would consume additional space in perpetuity.

## Additional context

The following example can recreate the behavior.

1. Modify `examples/pod_with_pvc.yaml` to use a 50GiB volume.
2. Deploy `examples/pod_with_pvc.yaml`.
3. Write approximately 40 GiB of data to the volume in multiple files.

```
eweber@laptop:~/longhorn> k exec -it volume-test -- sh

/ # for i in $(seq 0 9); do dd if=/dev/urandom of=/data/file${i} bs=64M count=64; done
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 32.026106 seconds, 127.9MB/s
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 38.964468 seconds, 105.1MB/s
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 37.402134 seconds, 109.5MB/s
...
```

4. Delete a replica and wait for it to rebuild so that a single system snapshot exists behind volume-head. (If there is no system snapshot, we likely can't trigger the issue, but this situation is rare for any volume that has been in use for a long time.)
5. Verify the initial condition by checking the snapshots from the engine's perspective.

```
eweber@laptop:~/longhorn> kl get volume -oyaml | grep actualSize
    actualSize: 44063178752

eweber@laptop:~/longhorn> kl get engine -oyaml | grep snapshots: -A 19
    snapshots:
      691eed9c-9ac1-4595-843b-e3aeb7cb8fc6:
        children:
          volume-head: true
        created: "2024-08-28T16:30:02Z"
        labels: {}
        name: 691eed9c-9ac1-4595-843b-e3aeb7cb8fc6
        parent: ""
        removed: false
        size: "44063178752"
        usercreated: false
      volume-head:
        children: {}
        created: "2024-08-28T16:30:02Z"
        labels: {}
        name: volume-head
        parent: 691eed9c-9ac1-4595-843b-e3aeb7cb8fc6
        removed: false
        size: "0"
        usercreated: false
```

7. Taint the two nodes the engine is NOT running on with `NoExecute` so their replicas fail.

```
eweber@laptop:~/longhorn> kl taint node eweber-v126-worker-9c1451b4-6464j eweber-v126-worker-9c1451b4-kgxdq k=v:NoExecute
node/eweber-v126-worker-9c1451b4-6464j tainted
node/eweber-v126-worker-9c1451b4-kgxdq tainted
```

9. Choose one of the tainted nodes. SSH to it and use `iftop` to monitor its data ingress.
10. Untaint the node and wait for the rebuild to finish.
11. Check instance-manager logs to estimate the rebuild time and iftop for the amount of data transfer. This rebuild does NOT require a "full data transfer".

```
# takes about 2 min 36 s
[instance-manager-699da83c0e9d22726e667344227e096b] [pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-3503405c] time="2024-08-28T16:41:14Z" level=info msg="Replica server starts to snapshot [dc596a3b-d890-4e05-a6d0-82b12581b08a] volume, user created false, created time 2024-08-28T16:41:14Z, labels map[]" func="replica.(*Server).Snapshot" file="server.go:188"
[instance-manager-699da83c0e9d22726e667344227e096b] [pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-3503405c] time="2024-08-28T16:43:50Z" level=info msg="Reloading replica" func="replica.(*Server).Reload" file="server.go:96"

# from iftop (not necessarily all rebuilding related)
RX:                     472MB
```

12. Use `iftop` to monitor the other tainted node.
13. Untaint the node and wait for the rebuild to finish.
14. 9. Check instance-manager logs to estimate the rebuild time and iftop for the amount of data transfer. This rebuild DOES require a "full data transfer".

```
# takes about 3 min 21 s
[instance-manager-699da83c0e9d22726e667344227e096b] [pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-3503405c] time="2024-08-28T17:09:11Z" level=info msg="Replica server starts to snapshot [cd8effbb-9003-4613-9d1b-ec97e7a93bf4] volume, user created false, created time 2024-08-28T17:09:11Z, labels map[]" func="replica.(*Server).Snapshot" file="server.go:188"
[instance-manager-ea5f8778d6c99e747289ff09c322d75a] [pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-d30b68a6] time="2024-08-28T17:12:32Z" level=info msg="Sync agent gRPC server finished rebuilding replica/sync files for replica 10.42.3.11" func="rpc.(*SyncAgentServer).FilesSync.func1" file="server.go:434"

# from iftop (not necessarily all rebuilding related)
RX:                    41.3GB
```

**Comment by ejweber** [comment]
I think the following ideas from above are the most promising.

Best-effort fix:

Add an additional option for `auto-cleanup-system-generated-snapshot` like `conditional`:

- Don't purge before a rebuild if doing so would not "significantly" decrease consumed space.
- Don't purge after a rebuild if the volume is still degraded and doing so would not "significantly" decrease consumed space.

Workaround:

Use a recurring job to take a user-created snapshot once per day.

- Most of the data will be in the user-created snapshot, which can definitely be delta synced.
- Unless write activity is very heavy, this won't result in too much additional space consumption.
- In combination with `snapshot-data-integrity-check-after-creating-a-snapshot` (defaults to false), the user-created snapshot generally wouldn't need to be synced between replicas at all. This could even speed up rebuilds that don't require a "full data transfer".

**Comment by ejweber** [comment]
A similar issue occurs for failed rebuilds, as demonstrated by the following test:

1. Modify `examples/pod_with_pvc.yaml` to use a 50GiB volume.
2. Deploy `examples/pod_with_pvc.yaml`.
3. Modify the volume so that `numReplicas == 2`.
4. Delete the extra replica.
5. Write approximately 40 GiB of data to the volume in multiple files.

```
eweber@laptop:~/longhorn> k exec -it volume-test -- sh

/ # for i in $(seq 0 9); do dd if=/dev/urandom of=/data/file${i} bs=64M count=64; done
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 32.026106 seconds, 127.9MB/s
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 38.964468 seconds, 105.1MB/s
64+0 records in
64+0 records out
4294967296 bytes (4.0GB) copied, 37.402134 seconds, 109.5MB/s
...
```

6. Delete a replica and wait for it to rebuild so that a single system snapshot exists behind volume-head. (If there is no system snapshot, we likely can't trigger the issue, but this situation is rare for any volume that has been in use for a long time.)
7. Verify the initial condition by checking the snapshots from the engine's perspective.

```
eweber@laptop:~/longhorn> kl get volume -oyaml | grep actualSize
    actualSize: 44063178752

eweber@laptop:~/longhorn> kl get engine -oyaml | grep snapshots: -A 100
    snapshots:
      c063ea11-d3a6-41e7-8d20-feef70cf97b3:
        children:
          volume-head: true
        created: "2024-08-28T18:56:11Z"
        labels: {}
        name: c063ea11-d3a6-41e7-8d20-feef70cf97b3
        parent: ""
        removed: true
        size: "44063178752"
        usercreated: false
      volume-head:
        children: {}
        created: "2024-08-28T18:56:11Z"
        labels: {}
        name: volume-head
        parent: c063ea11-d3a6-41e7-8d20-feef70cf97b3
        removed: false
        size: "0"
        usercreated: false
```

8. SSH to the node with the engine and use `iftop` to monitor its data egress.
9. Taint the node the engine is NOT running on with NoExecute so its replica fails.

```
eweber@laptop:~/longhorn> kl taint node eweber-v126-worker-9c1451b4-6464j k=v:NoExecute
node/eweber-v126-worker-9c1451b4-6464j tainted
```

10. Untaint the node.
11. Wait for the replica rebuild to be ongoing.
12. Taint the node again.
13. Wait for the replica rebuild to fail.
14. Untaint the node again.
15. Check instance-manager logs to estimate the rebuild time and iftop for the amount of data transfer. This rebuild DOES require a "full data transfer".

```
[instance-manager-6852914a55e4566d3ddea43529df22e0] [pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-e-0] time="2024-08-28T19:17:42Z" level=info msg="Starting to snapshot: 10.42.4.239:10156 9432741f-6184-4c3c-af6b-5aa4765c5960 UserCreated false Created at 2024-08-28T19:17:42Z, Labels map[]" func="remote.(*Remote).Snapshot" file="remote.go:99"

TX:             cum:   44.1GB
```

The instance-manager logs also indicate the reason for the full transfer. Longhorn purges snapshots before the second rebuilding attempt, leading to a similar situation as above.

```
[pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-7727715b] time="2024-08-28T19:15:41Z" level=info msg="Replica server starts to snapshot [6c9248f3-1264-4fea-b61e-c6bb10fe6962] volume, user created false, created time 2024-08-28T19:15:41Z, labels map[]" func="replica.(*Server).Snapshot" file="server.go:188"

[longhorn-instance-manager] time="2024-08-28T19:15:56Z" level=info msg="Purging snapshots" func="proxy.(*Proxy).SnapshotPurge" file="snapshot.go:321" dataEngine=DATA_ENGINE_V1 engineName=pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-e-0 serviceURL="10.42.4.239:10166" volumeName=pvc-62a34998-deef-484b-bef8-a7f1c49b15e8
[pvc-62a34998-deef-484b-bef8-a7f1c49b15e8-r-7727715b] time="2024-08-28T19:15:56Z" level=info msg="Done replacing disk volume-snap-c063ea11-d3a6-41e7-8d20-feef70cf97b3.img with volume-snap-6c9248f3-1264-4fea-b61e-c6bb10fe6962.img" func="replica.(*Replica).ReplaceDisk" file="replica.go:416"
```

This is quite relevant in the context of cluster maintenance. In a support bundle for the original discussion, we observed the following sequence, which was allowed by the drain policy.

1. Drain node1. replica1 fails.
2. Reboot node1.
3. Start rebuilding node1.
4. Drain node2. replica2 fails. Engine moves off of node2 (due to workload drain). replica1 rebuild fails.
5. Reboot node2.
6. Rebuild replica1. Now full data transfer is required.
7. Rebuild replica2. Full data transfer is required.
