### ISSUE TITLE
[BUG] Unable to access azurite backup store by DNS hostname

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9340]
## Describe the bug

Using https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/backupstores/azurite-backupstore.yaml to create a azurite backup store, and run `az storage container create -n demo --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://0.0.0.0:20001/devstoreaccount1;` to create a container.

(1) **If `AZBLOB_ENDPOINT` is set to `http://azblob-service.default:10000/` in `azblob-secret`:**

```
apiVersion: v1
kind: Secret
metadata:
  name: azblob-secret
  namespace: longhorn-system
type: Opaque
data:
  AZBLOB_ACCOUNT_NAME: ZGV2c3RvcmVhY2NvdW50MQ==
  AZBLOB_ACCOUNT_KEY: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQ==
  AZBLOB_ENDPOINT: aHR0cDovL2F6YmxvYi1zZXJ2aWNlLmRlZmF1bHQ6MTAwMDAv
```

And backup target is set to `azblob://demo@url/`.

Get the following error:

```
failed to list backup volumes in azblob://demo@url/: error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.x-head/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.x-head/longhorn backup ls --volume-only azblob://demo@url/], output GET http://azblob-service.default:10000/devstoreaccount1/demo -------------------------------------------------------------------------------- RESPONSE 404: 404 The specified resource does not exist. ERROR CODE: ResourceNotFound -------------------------------------------------------------------------------- <?xml version="1.0" encoding="UTF-8" standalone="yes"?> <Error> <Code>ResourceNotFound</Code> <Message>The specified resource does not exist. RequestId:c4570a53-a375-4691-a1d8-1fa4b332ab59 Time:2024-08-29T02:25:34.152Z</Message> </Error> -------------------------------------------------------------------------------- , stderr warning: GOCOVERDIR not set, no coverage data emitted time="2024-08-29T02:25:34Z" level=error msg="GET http://azblob-service.default:10000/devstoreaccount1/demo\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 The specified resource does not exist.\nERROR CODE: ResourceNotFound\n--------------------------------------------------------------------------------\n<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n <Code>ResourceNotFound</Code>\n <Message>The specified resource does not exist.\nRequestId:c4570a53-a375-4691-a1d8-1fa4b332ab59\nTime:2024-08-29T02:25:34.152Z</Message>\n</Error>\n--------------------------------------------------------------------------------\n" func=main.ResponseLogAndError file="main.go:47" : exit status 1
```

The url `http://azblob-service.default:10000/devstoreaccount1/demo` to get azurite resource is not correct according to https://github.com/Azure/Azurite/issues/1039#issuecomment-916588540

(2) **If `AZBLOB_ENDPOINT` is not set in `azblob-secret`:**

```
apiVersion: v1
kind: Secret
metadata:
  name: azblob-secret
  namespace: longhorn-system
type: Opaque
data:
  AZBLOB_ACCOUNT_NAME: ZGV2c3RvcmVhY2NvdW50MQ==
  AZBLOB_ACCOUNT_KEY: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQ==
```

And backup target is set to `azblob://demo@azblob-service.default:10000/`.

Get the following error:

```
failed to list backup volumes in azblob://demo@azblob-service.default:10000/: error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.x-head/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.x-head/longhorn backup ls --volume-only azblob://demo@azblob-service.default:10000/], output Get "https://devstoreaccount1.blob.azblob-service.default:10000/demo?comp=list&delimiter=%2F&prefix=%2F&restype=container": dial tcp: lookup devstoreaccount1.blob.azblob-service.default on 10.43.0.10:53: no such host , stderr warning: GOCOVERDIR not set, no coverage data emitted time="2024-08-29T02:30:56Z" level=error msg="Get \"https://devstoreaccount1.blob.azblob-service.default:10000/demo?comp=list&delimiter=%2F&prefix=%2F&restype=container\": dial tcp: lookup devstoreaccount1.blob.azblob-service.default on 10.43.0.10:53: no such host" func=main.ResponseLogAndError file="main.go:47" : exit status 1
```

The url `https://devstoreaccount1.blob.azblob-service.default:10000/demo` follows the rule in https://github.com/Azure/Azurite/issues/1039#issuecomment-916588540, but k8s cannot resolve it: `dial tcp: lookup devstoreaccount1.blob.azblob-service.default on 10.43.0.10:53: no such host`.

Seems the only workable approach is accessing the azurite backup store by `IP` just like https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Setup+Azurite+Backupsotre+For+Testing.

## Environment

 - Longhorn version: v1.7.x-head, master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
