### ISSUE TITLE
[BUG] In Longhorn v1.7.1 restoring v2 volume backup created in v1.6.2 causes faulted volume

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9380]
## Describe the bug

In Longhorn `v1.6.2`, created a `v2` volume and created a backup for it, and upgrade Longhorn to `v1.7.1`, then restore a `v2` volume from the backup, the volume got stuck in Faulted/Unknown state.

## To Reproduce

1. Install Longhorn `v1.6.2`
2. Enable v2  data engine and add a block disk for each node:
![v2-0](https://github.com/user-attachments/assets/05630478-2b9c-4ad5-8fdf-19c8de960e16)
3. Create `longhorn-v2-data-engine` storage class
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/storageclass.yaml
```
4. Create a v2 volume from UI:
![v2-1](https://github.com/user-attachments/assets/23f9ade2-fff6-4f70-abbe-d6a506f75e25)
5. Create PVC/PV with storage class `longhorn-v2-data-engine` for this volume:
![v2-2](https://github.com/user-attachments/assets/07f067ff-6448-438b-b567-d5ccf0bfd0af)
6. Create a pod to write some data to this volume:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
```
7. Create a backup for this volume
8. Upgrade Longhorn to `v1.7.1`:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.7.x/deploy/longhorn.yaml
```
9. Restore a v2 volume from this backup:
![v2-3](https://github.com/user-attachments/assets/36c55f8b-f7a8-4cec-9625-76c4e584690b)
10. The volume stuck in `Faulted/Unknown` state:
![v2-4](https://github.com/user-attachments/assets/6360fa75-e484-474c-9347-dc39ae114885)
![v2-6](https://github.com/user-attachments/assets/9bfe8c67-76de-4d78-8494-757d9b82bfa5)

## Support bundle for troubleshooting

[supportbundle_cfb5993f-3343-42cf-a418-7d8c06fbc1fc_2024-09-04T05-26-32Z.zip](https://github.com/user-attachments/files/16861329/supportbundle_cfb5993f-3343-42cf-a418-7d8c06fbc1fc_2024-09-04T05-26-32Z.zip)

## Environment

 - Longhorn version: v1.7.1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubuntu 24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): aws
 - Number of Longhorn volumes in the cluster:
