### ISSUE TITLE
[BUG]  MapVolume.SetUpDevice failed for volume ... no such device or address

### ISSUE THREAD

**Issue by rajeesh-sdk** [longhorn/longhorn#9426]
## Describe the bug
While redeploying as Statefulset, the first Pod is unable to attach the volume with the following error message:

0s          Warning   FailedMapVolume    pod/aerospike-0         MapVolume.SetUpDevice failed for volume "pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250" : rpc error: code = Internal desc = failed to create file /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250/pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250: open /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250/pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250: no such device or address 

The Volumes are in attached stage and is not showing any errors

## Environment
KubeAdm 1.27

 - Longhorn version: 1.60
 - Impacted volume (PV): pvc-e9e4a78d-82b5-4fdf-9e1b-c3af35b25250
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: KubeAdm
   - Number of control plane nodes in the cluster:3
   - Number of worker nodes in the cluster:3
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.15.0-119
   - CPU per node: 2/4
   - Memory per node: 8/16GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 100G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: Around 50

**Comment by PhanLe1010** [comment]
Is it a block volume mode PVC?

**Comment by phoenix-frozen** [comment]
I... think I might be running into a similar problem?

Dynamically provisioned volume on block-mode storage using the v2 engine.

```
 MapVolume.MapPodDevice failed for volume "pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c" : rpc error: code = Internal desc = failed to bind mount "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c" at "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/284dfa73-7bc7-4833-ac96-43275795e289": mount failed: exit status 32 Mounting command: mount Mounting arguments: -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/284dfa73-7bc7-4833-ac96-43275795e289 Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/284dfa73-7bc7-4833-ac96-43275795e289: special device /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c/pvc-e53cfc8c-fdf5-4588-b212-f77856e7581c does not exist. dmesg(1) may have more information after failed mount system call. 
```

Restarting the node didn't help.

**Comment by derekbit** [comment]
@phoenix-frozen Could you provide a support bundle and provide more information for your case?

**Comment by phoenix-frozen** [comment]
> @phoenix-frozen Could you provide a support bundle and provide more information for your case?

Support bundle, I cannot -- I just had to tear down the cluster and am currently rebuilding it.

What kind of information do you need? Happy to describe whatever you'd like; disk setup, cluster components, other services in the cluster, volume information...

**Comment by innobead** [comment]
Is it possibly related to https://github.com/longhorn/longhorn/issues/8009 or benefit from it? @derekbit @PhanLe1010

**Comment by phoenix-frozen** [comment]
Happening again on my freshly installed cluster. 

#8009 does not appear to be relevant. This happened on a node that took an outage, and my problem is happening on a fresh cluster with a newly-instantiated VM.

I am currently generating a support bundle.

**Comment by phoenix-frozen** [comment]
I... guess the support bundle has been generated?

**Comment by derekbit** [comment]
> I... guess the support bundle has been generated?

 Can you upload it here?

**Comment by phoenix-frozen** [comment]
> > I... guess the support bundle has been generated?
> 
> Can you upload it here?

I'd love to, but... I didn't get an opportunity to download it anywhere. The modal on the webui just disappeared. Where am I supposed to find it?

**Comment by derekbit** [comment]
> > > I... guess the support bundle has been generated?
> > 
> > 
> > Can you upload it here?
> 
> I'd love to, but... I didn't get an opportunity to download it anywhere. The modal on the webui just disappeared. Where am I supposed to find it?

Can try this https://longhorn.io/kb/troubleshooting-create-support-bundle-with-curl/

**Comment by phoenix-frozen** [comment]
Oh, sorry, I have it after all. It's also 700MiB in size, so I can't upload it here.

**Comment by derekbit** [comment]
> Oh, sorry, I have it after all. It's also 700MiB in size, so I can't upload it here.

Can upload it to somewhere and share the link

**Comment by phoenix-frozen** [comment]
https://drive.google.com/file/d/1J3Ja-q26WCR7jV06vwBSl-DGFUaYDil5/view?usp=drive_link

**Comment by phoenix-frozen** [comment]
...

**Comment by derekbit** [comment]
> ...

@phoenix-frozen This is a private share link.

**Comment by proever** [comment]
I think I have the same issue


```
  Warning  FailedMapVolume         62s (x9 over 3m11s)  kubelet                  MapVolume.MapPodDevice failed for volume "pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58" : rpc error: code = Internal desc = failed to bind mount "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58" at "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/69971bdd-b732-4e0f-8fc2-84c3a7a04747": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58 /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/69971bdd-b732-4e0f-8fc2-84c3a7a04747
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/69971bdd-b732-4e0f-8fc2-84c3a7a04747: special device /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58/pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58 does not exist.
       dmesg(1) may have more information after failed mount system call.
```

[supportbundle_cfa58f6c-58e9-4dda-a49d-1286f5be98b0_2025-03-13T01-53-52Z.zip](https://github.com/user-attachments/files/19220516/supportbundle_cfa58f6c-58e9-4dda-a49d-1286f5be98b0_2025-03-13T01-53-52Z.zip)

[supportbundle_cfa58f6c-58e9-4dda-a49d-1286f5be98b0_2025-03-13T02-00-15Z.zip](https://github.com/user-attachments/files/19220502/supportbundle_cfa58f6c-58e9-4dda-a49d-1286f5be98b0_2025-03-13T02-00-15Z.zip)



the first bundle is from the failed volume creation, the second shows one that succeeded.

```
x kubectl get pvc -o wide
NAME                                                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE    VOLUMEMODE
alpine-dv                                            Pending                                                                        longhorn-2     <unset>                 17m    Block
alpine-dv-3                                          Pending                                                                        longhorn-2     <unset>                 114s   Block
prime-cf657dd6-279c-49e8-b2de-25fc383bc965           Bound     pvc-7c409445-aea7-4bc0-b0e5-de7f9e1e0a58   10Gi       RWX            longhorn-2     <unset>                 17m    Block
prime-edf492f2-8ab9-4186-9c16-877f6b86cb4a           Bound     pvc-d4ef160c-2526-4ce2-b7a2-581a580577a1   10Gi       RWO            longhorn-2     <unset>                 114s   Block
prime-edf492f2-8ab9-4186-9c16-877f6b86cb4a-scratch   Bound     pvc-6a63254c-0fd9-4e47-bbb6-b199ccc981ab   10836Mi    RWO            longhorn-2     <unset>                 59s    Filesystem
``` 

the only difference seems to be RWX vs RWO. I am using kubevirt and specified ReadWriteMany under storage access modes, which seems to reliably cause this.

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: alpine-dv
    spec:
      storage:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
      source:
        http:
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
```

removing

```
      storage:
        accessModes:
          - ReadWriteMany
```

"fixes" it.
