### ISSUE TITLE
[FEATURE] Add recurring job label to backup metrics or empty value

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#9429]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Feature request proposed by @YvanGuidoin . See https://github.com/longhorn/longhorn-manager/pull/3034#issue-2435572983.

## Describe the solution you'd like

Add recurring_job field in Backup metrics.

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by c3y1huang** [comment]
Talked to @ChanYiLin , and he will handle this.

**Comment by YvanGuidoin** [comment]
Using any volume `v`

Create a recurring job like this one:
```yaml
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-hourly
  namespace: longhorn-system
spec:
  cron: "@hourly"
  task: "backup"
  groups:
    - hourly
  retain: 24
```

Add group `hourly` to volume `v` and wait for the next automated backup
Create a backup manually after this
Metric `longhorn_backup_actual_size_bytes` should have 2 different values on label `recurring_job`, one empty and `backup-hourly`

Proper size values can be checked by modifying the volume data between the 2 backups I guess
