### ISSUE TITLE
[FEATURE] Support for more LUKS2 encryption options for Argon2id

### ISSUE THREAD

**Issue by Silvest89** [longhorn/longhorn#9478]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
Currently Longhorn supports argon2i through the luks format. However for argon2id more args can be used

Currently supported
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Your encryption passphrase"
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2id"
```

`--pbkdf-memory`, `--pbkdf-parallel` and `--iter-time` that makes for a more customizable argon2id encryption.

## Describe the solution you'd like

Support for more luksformat options.
