### ISSUE TITLE
longhorn-driver-deployer loop after hard reboot

### ISSUE THREAD

**Issue by briceruzand** [longhorn/longhorn#957]
Hi,

I'am using longhorn 0.7.0 installed with rancher 2.2.9 on Kubernetes 1.15.3.
When all my nodes shutdown after a power outage, on reboot longhorn was outage.
 
The pods "longhorn-driver-deployer" do no restart and loop with the following error :

```
time="2019-12-11T14:04:26Z" level=debug msg="Deploying CSI driver"
time="2019-12-11T14:04:26Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-12-11T14:04:27Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-12-11T14:04:28Z" level=info msg="Proc found: kubelet"
time="2019-12-11T14:04:28Z" level=info msg="Detected root dir path: /var/lib/kubelet"
time="2019-12-11T14:04:28Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0"
time="2019-12-11T14:04:29Z" level=fatal msg="Error deploying driver: persistentvolumeclaims \"viky-webapp-uploads-pvc\" not found"
```
All longhorn volumes were not able to be attached.

Longhorn is used has the default storage-class but not for that pvc (RWM) which is not managed by longhorn but build over nfs-server-provisioner which use longhorn.

Why longhorn complain about that PVC and do not setup correctly ?

**Comment by maxaudron** [comment]
I had this same problem after a node restart, and the PVC were indeed not there anymore as i had deleted them earlier. I assume there are some left over resources that didn't get cleaned up.

You can try running `kubectl -n longhorn-system describe volumes.longhorn.io` and see if that volume is in there.

**Comment by shuo-wu** [comment]
There 2 bugs for this issue:
1. The driver deployer wrongly checks all PV and PVC provisioned by any StorageClass. ==> It is already fixed by [this PR ](https://github.com/longhorn/longhorn-manager/pull/477)
2. The driver deployer won't skip the checking even if the PVC does not exist ==> It will be fixed soon.

**Comment by shuo-wu** [comment]
One workaround for this issue:
Manually create PVC for all PVs which have annotation `pv.kubernetes.io/provisioned-by` but don't have related PVCs

PVC Template:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <PVC name. It should be the same as `pv.Spec.ClaimRef.Name`>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <PV size>
  volumeName: <PV name>
  storageClassName: <StorageClass name>
```
