### ISSUE TITLE
Longhorn use /dev/longhorn as Attached Node Endpoint even when defaultSettings.defaultDataPath set to sth else..?

### ISSUE THREAD

**Issue by amir-bialek** [longhorn/longhorn#9606]
Deployed with helm and argocd, default configuration except for:
```
persistence:
  defaultClass: false
  defaultClassReplicaCount: 2

defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /data/storage/k8s-longhorn/pvc  
  defaultReplicaCount: 1

longhornUI:
  replicas: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

preUpgradeChecker:
  jobEnabled: false
```

Looking at volumes created under the `longhorn` storage class, I see that the Attached Node & Endpoint is always ` /dev/longhorn `, and only the replica PVC set to `/data/storage/k8s-longhorn/pvc`.

See image:
![image](https://github.com/user-attachments/assets/f4e341a5-2867-4d7e-ba63-4128d09f48e3)

Have I missed something?
I have a drive mount on path `/data/storage`, I need longhorn to use this path not only for the replica..

Thx
