### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=

### ISSUE THREAD

**Issue by WoodProgrammer** [longhorn/longhorn#963]
Hello, I'm testing longhorn on Rancher cluster, 

I have drained node when my node has been on the power-off state, after then, deployment object created new pod replica but pod still `ContainerCreating` state . That is the describe output of the pod , 

```

  Warning  FailedAttachVolume  1m         attachdetach-controller   AttachVolume.Attach failed for volume "pvc-06fb9fed-a405-480f-a7bb-486446d8d495" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-06fb9fed-a405-480f-a7bb-486446d8d495 volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-06fb9fed-a405-480f-a7bb-486446d8d495] map[salvage:http://longhorn-backend:9500/v1/volumes/pvc-06fb9fed-a405-480f-a7bb-486446d8d495?action=salvage]}]

  Warning  FailedMount         25s        kubelet, ip-172-31-4-128  Unable to attach or mount volumes: unmounted volumes=[mysql-volume], unattached volumes=[mysql-volume default-token-64wcx]: timed out waiting for the condition

```

For unmount the mysql pvc I have updated `lhv` object which assigned the failed instance , and remove the node Id from there . 

```
spec:
  Standby: false
  baseImage: ""
  disableFrontend: false
  diskSelector: null
  engineImage: longhornio/longhorn-engine:v0.7.0
  fromBackup: ""
  frontend: blockdev
  nodeID: ""
```
Longhorn version v0.7.0

How i can fix this issue ?
