### ISSUE TITLE
[BUG] Longhorn deployment issue with mutating webhook  (zarf)

### ISSUE THREAD

**Issue by ido-ziv18** [longhorn/longhorn#9638]
## Describe the bug
We are using zarf to deploy longhorn on an Air-gapped k8s cluster.
zarf uses a mutating webhook on pods to change the image to its own registry.
so, in the daemon-set of `longhorn-manager` itself the image is still kept the same, but on the container the image is modified with the zarf registry URL and an extention to the tag (e.g.: `127.0.0.1:31999/longhornio/longhorn-manager:v1.7.1-zarf-4888888889`)
this triggers the following error in the longhorn-manager:
`time="2024-10-14T11:08:37Z" level=info msg="Found old longhorn manager: longhorn-manager-f5x8p with image 127.0.0.1:31999/longhornio/longhorn-manager:v1.7.1-zarf-4888888889" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:325"`

## To Reproduce
edit the manager daemonset so that the command tag is different from the image tag. 

## Expected behavior
setting the '--upgrade-version-check' to false should allow longhorn to start without triggering the waitForOldLonghornManagersToBeFullyRemoved function.

## Support bundle for troubleshooting
No support bundle can be provided as this issue is with the install prossess

## Environment

 - Longhorn version: 1.7.1
 - Impacted volume (PV): NA
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm with Zarf
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: ubuntu 22
   - Kernel version:
   - CPU per node: 8
   - Memory per node: 32
    - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): virlab
 - Number of Longhorn volumes in the cluster: 0

## Workaround and Mitigation
changing the manager image argument in the daemonset to the zarf-modified image name allows the deployment to proceed, but you cannot make this change via helm (as changing the manager image value will also change the daemonset image value)

**Comment by c3y1huang** [comment]
Interesting to know about Zarf's behavior. 

I don't think we should implement the skip of the manager image version check, as it's in place to address a [past issue](https://github.com/longhorn/longhorn/issues/6294#issuecomment-1724914808). However, we might be able to improve the check.

What do you think @PhanLe1010 @derekbit ?

**Comment by jdmarble** [comment]
I'm running into this problem without zarf but using kustomize to overlay image digests on the default manifests from https://raw.githubusercontent.com/longhorn/longhorn/v1.7.2/deploy/longhorn.yaml . In my case, I can have kustomize also replace the arguments to longhorn-manager with the image names that have the digest as a workaround. This will prevent some automations I'd like to use.

**Comment by derekbit** [comment]
> I'm running into this problem without zarf but using kustomize to overlay image digests on the default manifests from [`v1.7.2`/deploy/longhorn.yaml (raw)](https://raw.githubusercontent.com/longhorn/longhorn/v1.7.2/deploy/longhorn.yaml) . In my case, I can have kustomize also replace the arguments to longhorn-manager with the image names that have the digest as a workaround. This will prevent some automations I'd like to use.

@jdmarble 
Can you elaborate more on how you installed and ran into the issue?

**Comment by jdmarble** [comment]
Yes, here is a simplified kustomization.yaml.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.2/deploy/longhorn.yaml

images:
  - name: longhornio/longhorn-manager
    newTag: v1.7.2@sha256:9b7e5a86aedd9b2abf9af57ccd3a213f8b5183d3de962a539f29f69660d910e0
```

When I deploy using that transformation, it updates the tags of the containers, but not the longhorn-manager's `--manager-image` argument. Relevant portions of the resulting manifest:

```yaml
spec:
  containers:
    command:
      - --manager-image
      - longhornio/longhorn-manager:v1.7.2
    image: longhornio/longhorn-manager:v1.7.2@sha256:9b7e5a86aedd9b2abf9af57ccd3a213f8b5183d3de962a539f29f69660d910e0
```

I think that is why I get similar error messages as OP:

```
longhorn-manager-mk827 longhorn-manager time="2024-10-24T21:58:07Z" level=info msg="Found old longhorn manager: longhorn-manager-c88bt with image longhornio/longhorn-manager:v1.7.2@sha256:9
b7e5a86aedd9b2abf9af57ccd3a213f8b5183d3de962a539f29f69660d910e0" func=upgrade.waitForOldLonghornManagersToBeFullyRemoved file="upgrade.go:325"
```
