### ISSUE TITLE
[FEATURE] Add support for ReadWriteOncePod access mode

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9727]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

ReadWriteOncePod is another Kubernetes access mode that restricts access to just a single pod on a single node at any given time.

## Describe the solution you'd like

Add support for it as another available option for Longhorn volumes.

## Additional context

This [FEATURE] issue created to associate to community PR https://github.com/longhorn/longhorn-manager/pull/3236

**Comment by james-munson** [comment]
@shikanime, please set yourself as "Assignee" and add a comment about the testing done so far on the feature.  Thanks!

**Comment by derekbit** [comment]
Hello @james-munson, cannot assign to @shikanime, so assign to you first. You can handle the remaining tasks. Thank you.

**Comment by derekbit** [comment]
@james-munson Let's merge it to v1.9.

**Comment by derekbit** [comment]
@shikanime Could we assign this ticket to you because you are working on it? Thanks.

**Comment by shikanime** [comment]
Yes no problem

**Comment by derekbit** [comment]
Hello @shikanime 
Could you update the pre-check list and provide the steps to test? Thanks
https://github.com/longhorn/longhorn/issues/9727#issuecomment-3547603610

**Comment by chriscchien** [comment]
Hi @shikanime 

After a dynamic provision a `rwop` volume
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```

The PV and PVC have `ACCESS MODES` in `RWOP`
```bash
# k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM          STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-4683395c-3e17-4458-8e0a-7ee5f6fc113c   2Gi        RWOP           Delete           Bound    default/vol1   longhorn       <unset>                          37s
root@ip-10-0-1-150:/home/ubuntu# k get pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
vol1   Bound    pvc-4683395c-3e17-4458-8e0a-7ee5f6fc113c   2Gi        RWOP           longhorn       <unset>                 44s
```
But in `volume.spec.accessMode`, the value is `rwo`, could you take a look on this? thank you.
```
# kl get volume pvc-4683395c-3e17-4458-8e0a-7ee5f6fc113c -o yaml | grep access
  accessMode: rwo
```

**Comment by shikanime** [comment]
Probably in-between the manager and CSI provisioner, I'll check it out.

**Comment by derekbit** [comment]
@shikanime Could you check when you get a chance whether this issue can be fixed? https://github.com/longhorn/longhorn/issues/9727#issuecomment-3625475851? Thank you

**Comment by derekbit** [comment]
Hello @shikanime 
Thanks for your contribution. If you have time, could you submit a PR in https://github.com/longhorn/website/tree/master/content/docs/1.11.0/nodes-and-volumes/volumes to add the support of RWOP volume? Thank you.

**Comment by shikanime** [comment]
> Hello [@shikanime](https://github.com/shikanime) Thanks for your contribution. If you have time, could you submit a PR in [longhorn/website@`master`/content/docs/1.11.0/nodes-and-volumes/volumes](https://github.com/longhorn/website/tree/master/content/docs/1.11.0/nodes-and-volumes/volumes?rgh-link-date=2025-12-15T06%3A22%3A41.000Z) to add the support of RWOP volume? Thank you.

Support for the RWOP volume documentation has already been merged into the master branch. There isn't much to add, as the RWOP is essentially an RWO with stricter constraints on the Kubernetes scheduling side.

**Comment by derekbit** [comment]
> > Hello [@shikanime](https://github.com/shikanime) Thanks for your contribution. If you have time, could you submit a PR in [longhorn/website@`master`/content/docs/1.11.0/nodes-and-volumes/volumes](https://github.com/longhorn/website/tree/master/content/docs/1.11.0/nodes-and-volumes/volumes?rgh-link-date=2025-12-15T06%3A22%3A41.000Z) to add the support of RWOP volume? Thank you.
> 
> Support for the RWOP volume documentation has already been merged into the master branch. There isn't much to add, as the RWOP is essentially an RWO with stricter constraints on the Kubernetes scheduling side.

Bad memory. Thank you.

**Comment by derekbit** [comment]
Hello @chriscchien 
Please help the UI as well. Thank you.

**Comment by chriscchien** [comment]
Hi @shikanime, in the latest build image, after I deploy below yaml, I still see volume `accessMode: rwo`, could you take a look to see if I missed something? Thank you.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOncePod
  # volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    name: test-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: ubuntu:20.04
          stdin: true
          stdinOnce: false
          tty: true
          volumeMounts:
            - name: vol1
              mountPath: /mnt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: vol1
```

<img width="2143" height="273" alt="Image" src="https://github.com/user-attachments/assets/849a15a1-6494-4093-ba5a-833da31c0ca4" />

**Comment by mantissahz** [comment]
Should not be closed now. reopen it.

**Comment by shikanime** [comment]
@derekbit Can you re-open the issue, my bad about this. I'm stopping using this tag, bad habit.

**Comment by chriscchien** [comment]
Verrified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/399992c8789af3bb23f282df6a0dcf596fbb8bf9)

1. dynamic provision a `ReadWriteOncePod`, UI, pv, pvc and longhorn volume have correct access mode.

<img width="2357" height="423" alt="Image" src="https://github.com/user-attachments/assets/9daf1aa6-3ee2-4489-a5c4-6cc3f39aee11" />

<img width="350" height="170" alt="Image" src="https://github.com/user-attachments/assets/47f2d461-17c3-4445-8089-aae0d66b744c" />

2. In a one node cluster, create workload with below yaml, after first pod running, scale the deployment to 2 replicas, the second stuck at pendine because access mode `rwop`
```
 Warning  FailedScheduling  37s   default-scheduler  0/2 nodes are available: 1 node has pod using PersistentVolumeClaim with the same name and ReadWriteOncePod access mode, 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/2 nodes are available: 1 No preemption victims found for incoming pod, 1 Preemption is not helpful for scheduling.
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOncePod
  # volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    name: test-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: ubuntu:20.04
          stdin: true
          stdinOnce: false
          tty: true
          volumeMounts:
            - name: vol1
              mountPath: /mnt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: vol1

```
