### ISSUE TITLE
[FEATURE]: Automatic online filesystem resize for RWX volumes.

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9736]
## Describe the bug

Fail to resize RWX PVC at filesystem resizing step 

## To Reproduce

1. Create a RWX PVC
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rwx-test
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
    ```
1. Create `pod-1` running on `node-1` and use the `rwx-test` PVC
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-1
      namespace: default
    spec:
      nodeName: node-1 # Replace by your node name
      restartPolicy: Always
      containers:
        - name: volume-test
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - ls
                - /data/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: volv
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: rwx-test
    ```
1. Share manager pod and the volume will be attached to `node-1` as `node-1` has the only workload pod so Longhorn prefer `node-1` at this point
1. Create `pod-2` running on `node-2` and use the `rwx-test` PVC
    ```
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-2
      namespace: default
    spec:
      nodeName: node-2 # Replace by your node name
      restartPolicy: Always
      containers:
        - name: volume-test
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - ls
                - /data/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: volv
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: rwx-test
    ```
1. Delete `pod-1`
1. Note that share manager pod and the volume are still be attached to `node-1`. They cannot move
1. Edit `rwx-test` PVC to have 15Gi size 
1. Observe that PVC failed to finish expansion at NodeExpandVolume step even though Longhorn completed expanding the Longhorn block device. Describing `pod-2` show the error event `Warning  VolumeResizeFailed      14s (x6 over 30s)  kubelet                  NodeExpandVolume.NodeExpandVolume failed for volume "pvc-b84caea2-95ac-497d-8016-714729139371" : Expander.NodeExpand failed to expand the volume : rpc error: code = Unknown desc = unknown filesystem type for volume pvc-b84caea2-95ac-497d-8016-714729139371 node expansion` 
1. Check the logs of longhorn-csi-plugin pod on `node-2` show the errors repeatedly:
    `
    024-10-31T00:18:32.249997014Z time="2024-10-31T00:18:32Z" level=info msg="NodeExpandVolume: req: {\"capacity_range\":{\"required_bytes\":16106127360},\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/752a2bf4a2e40f02050bbbea89c84a349e64d02185b0510f690e8df6cfba0eda/globalmount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":5}},\"volume_id\":\"pvc-b84caea2-95ac-497d-8016-714729139371\",\"volume_path\":\"/var/lib/kubelet/pods/57b80f3d-e3ee-410d-bdae-120e6b5f52bd/volumes/kubernetes.io~csi/pvc-b84caea2-95ac-497d-8016-714729139371/mount\"}" func=csi.logGRPC file="server.go:130"
    2024-10-31T00:18:32.250103911Z time="2024-10-31T00:18:32Z" level=info msg="NodeNodeExpandVolume is called with req volume_id:\"pvc-b84caea2-95ac-497d-8016-714729139371\" volume_path:\"/var/lib/kubelet/pods/57b80f3d-e3ee-410d-bdae-120e6b5f52bd/volumes/kubernetes.io~csi/pvc-b84caea2-95ac-497d-8016-714729139371/mount\" capacity_range:<required_bytes:16106127360 > staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/752a2bf4a2e40f02050bbbea89c84a349e64d02185b0510f690e8df6cfba0eda/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > " 
    func="csi.(*NodeServer).NodeExpandVolume" file="node_server.go:685" component=csi-node-server function=NodeExpandVolume
    2024-10-31T00:18:32.258538618Z time="2024-10-31T00:18:32Z" level=error msg="NodeExpandVolume: err: unknown filesystem type for volume pvc-b84caea2-95ac-497d-8016-714729139371 node expansion" func=csi.logGRPC file="server.go:136"
    `
1. Even if we exec into the share manager pod and resize the filesystem manually like the doc https://longhorn.io/docs/1.7.2/nodes-and-volumes/volumes/expansion/#online , the problem still persists

## Support bundle for troubleshooting
[supportbundle_8cd174d1-55da-4108-9361-c9bb9e9ad55a_2024-10-31T00-29-28Z.zip](https://github.com/user-attachments/files/17580419/supportbundle_8cd174d1-55da-4108-9361-c9bb9e9ad55a_2024-10-31T00-29-28Z.zip)

## Environment

 - Longhorn version: v1.7.2 but could affect all Longhorn versions currently

 - Node config
   - OS type and version: Ubuntu 22.04.4 LTS
   - Kernel version: 5.15.0-113-generic

## RCA:
Start with the current state of the cluster:

![image](https://github.com/user-attachments/assets/c89c0121-ca2a-4522-bd6e-94a53ae318a0)

1. When `kubelet-2` detect that `pod-2` is using a PVC which need filesystem resize, 
2. `kubelet-2` sends a `NodeExpandVolume` gRPC call to `longhorn-csi-plugin-2` pod
3. `longhorn-csi-plugin-2` find the block device path for the device `/dev/longhorn/rwx-test` ([code ref](https://github.com/longhorn/longhorn-manager/blob/235b1ae23f6ad4d26dc56063c95358145e937c09/csi/node_server.go#L732))
4. However, the device `/dev/longhorn/rwx-test` doesn't exist on `node-2`, it is living on `node-1` together with share-manager pod
5. Therefore, when `longhorn-csi-plugin-2` try to get diskformat [here](https://github.com/longhorn/longhorn-manager/blob/235b1ae23f6ad4d26dc56063c95358145e937c09/csi/node_server.go#L735), it does not find the device and enter this [code part ](https://github.com/longhorn/longhorn-manager/blob/235b1ae23f6ad4d26dc56063c95358145e937c09/vendor/k8s.io/mount-utils/mount_linux.go#L687-L693) and return `""` for diskformat 
6. The empty diskformat trigger this log error [unknown filesystem type for volume %v node expansion](https://github.com/longhorn/longhorn-manager/blob/235b1ae23f6ad4d26dc56063c95358145e937c09/csi/node_server.go#L739-L741)
7. Expansion flow is stuck

## Workaround:
1. Note down the current node that the volume is attaching to
2. Scale down or delete all workload pods which are using Longhorn RWX volume 
1. Wait for the Longhorn volume to fully detach
1. Create a test pod which uses the RWX PVC and schedule it to run on the SAME node at step 1
1. Wait for the PVC to successfully to resize
1. Delete the test pod
1. Scale up the rest of the workload pod

## Fixing Proposal
1. `longhorn-csi-plugin-2` pod should make an API call to Longhorn manager pod. Then Longhorn manager pod should make gRPC call to share manager pod to run the filesystem resize command. 
1. OR  `longhorn-csi-plugin-2` pod  should make gRPC call to share manager pod to run the filesystem resize command.

**Comment by derekbit** [comment]
@james-munson Will you create a LEP for the improvement?

**Comment by james-munson** [comment]
> @james-munson Will you create a LEP for the improvement?

Certainly.

See also https://github.com/longhorn/longhorn/issues/6050 and https://github.com/longhorn/longhorn/issues/6216 for previous history.  Of particular interest is the question of whether the online expansion will work for XVS filesystems, as noted in https://github.com/longhorn/longhorn/issues/6216#issuecomment-2293835724

**Comment by derekbit** [comment]
@james-munson Let's use https://github.com/longhorn/longhorn/issues/8118 instead.
It is a feature ticket. Should we backport it?

**Comment by james-munson** [comment]
> @james-munson Let's use #8118 instead. It is a feature ticket. Should we backport it?

Fair enough.  I'll make sure to capture the specific test case that led to this ticket in the test plan for #8118.  

We can certainly backport it, if you desire.  It was requested to be in an escalation - back to 1.5 as well as 1.6 and 1.7, although I'm not sure we are prepared to go that far back.  A couple of cautions about backport:
- It will include multiple PRs, for longhorn/types, longhorn-share-manager, and longhorn-manage.
- It does give the possibility that the user could get the feature in 1.6.4, upgrade to 1.7.2 and lose it because it is only in 1.7.3.

It will also require an update to the docs, of course.

**Comment by derekbit** [comment]
I think it is a new feature. We don't need to backport it. WDYT @innobead @james-munson @PhanLe1010

**Comment by innobead** [comment]
> I think it is a new feature. We don't need to backport it. WDYT @innobead @james-munson @PhanLe1010

Yeah, let's fine. However, we should rename the subject and make it a new feature instead. Also, update the doc to mention volume expansion only works for RWO in the previous versions.

**Comment by james-munson** [comment]
Will do.  Let's use this one, because it has more history in the notes.  I'll close https://github.com/longhorn/longhorn/issues/8118.

**Comment by james-munson** [comment]
# Test Plan

## Expand ext4
On a cluster with Longhorn 1.8 installed, make a simple RWX workload like this, similar to the longhorn/examples/rwx/rwx-nginx-deployment.yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rwx-test
  labels:
    app: rwx-test
spec:
  ports:
    - port: 80
  selector:
    app: rwx-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-test
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwx-test
  labels:
    app: rwx-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rwx-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rwx-test
    spec:
      containers:
        - image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - sleep 10; touch /data/index.html; while true; do  echo "`hostname` `date`" >> /data/index.html; sleep 1; done;
          name: rwx-test
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: rwx-test
        - image: nginx:stable
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: rwx-test
      restartPolicy: Always
      volumes:
        - name: rwx-test
          persistentVolumeClaim:
            claimName: rwx-test

```

Then install it with `kubectl apply -f rwx-test.yaml`.  Wait for it to settle, and then expand it by editing the pvc spec.resources.requests.storage to 5Gi.  Wait a minute or two, and then check that the PVC status reflects the new size and there is no Condition about an expansion being necessary.

## Expand xfs
On a cluster with Longhorn 1.8 installed, make a similar RWX workload, but using a storageclass that requires xfs:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sc-xfs
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "xfs"
```

Install and expand it the same way.

## Ensure off-node expansion

On a 1.8.0 system with this fix, use the setup in Steps to Reproduce [9736](https://github.com/longhorn/longhorn/issues/9736#issue-2625691170)

## Upgrade path

On a system with 1.7.x installed, create an RWX workload as above.  Upgrade the system to 1.8.0.  Edit the PVC to increase the spec storage size.  After a little time, observe that the PVC has an "expansion needed" Condition, and that the CSI plugin logs show a repeated failure of the FilesystemResize call to share-manager.  Delete the share-manager pod to force it to upgrade, and the expansion should then complete.
