### ISSUE TITLE
[BUG] When I repeatedly evict v2 replicas, an error occurs in the engine’s lhim (spdk_tgt).

### ISSUE THREAD

**Issue by hookak** [longhorn/longhorn#9780]
## Describe the bug

To simplify the problem, I ensured that the engine and replicas are not scheduled on the same node. When I repeatedly evict the storage node (where the replicas reside), the Longhorn engine on the node where the workload pod is running restarts due to a broken pipe error in lhim (spdk_tgt).

## To Reproduce

1. Create a pod that uses a v2 Longhorn volume.
2. Evict one of the replica nodes.
3. Repeat step 2.

## Expected behavior

Nothing happend

## Support bundle for troubleshooting
[supportbundle_2e722b58-bed1-415d-b740-4a2f0f135be5_2024-11-11T09-56-18Z.zip](https://github.com/user-attachments/files/17700587/supportbundle_2e722b58-bed1-415d-b740-4a2f0f135be5_2024-11-11T09-56-18Z.zip)

## Environment

 - Longhorn version: v1.7.0
 - Impacted volume (PV): pvc-b9574fbf-8cee-4140-9edd-29615024af72
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  k3s, v1.30.4
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 1

**Comment by derekbit** [comment]
@hookak Thanks for reporting. Does it always happen?

**Comment by hookak** [comment]
@derekbit 
The issue doesn't occur every time. but it happens within three attempts.
And the `spdk_tgt` process is terminated due to a "write: broken pipe" error

* Here is the example of instance manager log
```
[longhorn-instance-manager] time="2024-11-11T09:51:19Z" level=info msg="Removing replica" func="proxy.(*Proxy).ReplicaRemove" file="replica.go:315" engineName=pvc-b9574fbf-8cee-4140-9edd-29615024af72-e-0 replicaAddress="10.42.1.65:20001" replicaName= serviceURL="10.42.4.116:20001" volumeName=
[longhorn-instance-manager] time="2024-11-11T09:51:19Z" level=info msg="Deleting replica  with address 10.42.1.65:20001 from engine" func="spdk.(*Engine).ReplicaDelete" file="engine.go:1280" endpoint=/dev/longhorn/pvc-b9574fbf-8cee-4140-9edd-29615024af72 engineName=pvc-b9574fbf-8cee-4140-9edd-29615024af72-e-0 frontend=spdk-tcp-blockdev ip=10.42.4.116 port=20001 replicaAddressMap="map[pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-5aa59e63:10.42.2.89:20001 pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-706261d2:10.42.0.53:20001 pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-c7fedbf0:10.42.1.65:20001]" volumeName=pvc-b9574fbf-8cee-4140-9edd-29615024af72
[longhorn-instance-manager] time="2024-11-11T09:51:19Z" level=info msg="Removing base bdev pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-c7fedbf0n1 from engine" func="spdk.(*Engine).ReplicaDelete" file="engine.go:1303" endpoint=/dev/longhorn/pvc-b9574fbf-8cee-4140-9edd-29615024af72 engineName=pvc-b9574fbf-8cee-4140-9edd-29615024af72-e-0 frontend=spdk-tcp-blockdev ip=10.42.4.116 port=20001 replicaAddressMap="map[pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-5aa59e63:10.42.2.89:20001 pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-706261d2:10.42.0.53:20001 pvc-b9574fbf-8cee-4140-9edd-29615024af72-r-c7fedbf0:10.42.1.65:20001]" volumeName=pvc-b9574fbf-8cee-4140-9edd-29615024af72
[longhorn-instance-manager] time="2024-11-11T09:51:21Z" level=error msg="Failed to encode during handleSend" func="jsonrpc.(*Client).handleSend" file="client.go:159" error="write unix @->/var/tmp/spdk.sock: write: broken pipe"
```

**Comment by derekbit** [comment]
Thanks @hookak. We will investigate it. Thank you.

@shuo-wu Can you take a look?

**Comment by derekbit** [comment]
Let's try best effort to resolve it in v1.8.0. cc @innobead

**Comment by innobead** [comment]
Are we able to know the cause from the stack track of spdk_tgt logs?

**Comment by hookak** [comment]
I wanted to reproduce the issue and capture the `spdk_tgt` logs for analysis.Oddly, the issue hasn't occured during the tests over the past day.

while testing, I noticed these repeating log entries
```
[2024-11-14 01:39:07.631064] tcp.c:1638:nvmf_tcp_qpair_handle_timeout: *ERROR*: No pdu coming for tqpair=0x10c3ce0 within 30 seconds
[2024-11-14 01:39:37.563433] tcp.c:2250:nvmf_tcp_pdu_ch_handle: *ERROR*: The TCP/IP connection is not negotiated
[2024-11-14 01:39:37.634267] tcp.c:1638:nvmf_tcp_qpair_handle_timeout: *ERROR*: No pdu coming for tqpair=0x1a015d0 within 30 seconds
[2024-11-14 01:40:07.561985] tcp.c:2250:nvmf_tcp_pdu_ch_handle: *ERROR*: The TCP/IP connection is not negotiated
```
It seems these errors may be related to unreleased resources. Could this be causing the issue?

**Comment by derekbit** [comment]
@hookak Did you reproduce the issue manually or run a script?

**Comment by derekbit** [comment]
Attempted to reproduce the issue 20 times using the following manifests and script, but was unsuccessful. Not sure if the issue is gone in `spdk-v25.05`.

@hookak Can you check if the steps to reproduce are correct? 

Thank you.

cc @shuo-wu 

---

- Host Information
  - Longhorn master-head images
  - OS: Ubuntu 24.04
  - Kernel: 6.8.0-62-generic 

<details>
<summary>storageclass.yaml</summary>

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-v2-data-engine
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataEngine: "v2"
```

</details>

<details>
<summary>pod_with_pvc.yaml</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  nodeName: dereksu-c3-small-x86-02
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

</details>


<details>
<summary>pod_with_pvc.yaml with dd</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  nodeName: dereksu-c3-small-x86-02
  containers:
  - name: volume-test
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - |
        while true; do
          dd if=/dev/urandom of=/data/file bs=4K count=100000 oflag=direct
          rm /data/file
        done
    volumeMounts:
    - name: volv
      mountPath: /data
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

</details>

<details>
<summary>Script for repeated node eviction</summary>

```bash
#!/bin/bash

set -euo pipefail

VOLUME_NAME="pvc-c094eff8-c651-44c6-a1ea-cb5f2d793bd9"
NAMESPACE="longhorn-system"
NODE1="dereksu-c3-small-x86-01"
NODE2="dereksu-c3-small-x86-02"
NODE3="dereksu-c3-small-x86-03"
ITERATIONS=10

function evict_node() {
  local node=$1
  echo "[INFO] Evicting Longhorn node $node"
  kubectl patch nodes.longhorn.io "$node" -n "$NAMESPACE" --type=merge -p '{
    "spec": {
      "evictionRequested": true,
      "allowScheduling": false
    }
  }'
}

function unevict_node() {
  local node=$1
  echo "[INFO] Canceling eviction for Longhorn node $node"
  kubectl patch nodes.longhorn.io "$node" -n "$NAMESPACE" --type=merge -p '{
    "spec": {
      "evictionRequested": false,
      "allowScheduling": true
    }
  }'
}

function wait_for_volume_state() {
  local expected_node1=$1
  local expected_node2=$2

  echo "[INFO] Waiting for volume $VOLUME_NAME to be healthy with running replicas on $expected_node1 and $expected_node2..."

  while true; do
    # Get the volume's robustness status
    robustness=$(kubectl get volumes.longhorn.io "$VOLUME_NAME" -n "$NAMESPACE" -o jsonpath='{.status.robustness}')

    # Get all replicas of the volume with their node, owner, and current state
    replicas_json=$(kubectl get replicas.longhorn.io -n "$NAMESPACE" -o json \
      | jq --arg vol "$VOLUME_NAME" '
          .items
          | map(select(.spec.volumeName == $vol))
          | map({node: .spec.nodeID, owner: .status.ownerID, state: .status.currentState})')

    # Count the number of replicas
    replica_count=$(echo "$replicas_json" | jq 'length')

    # Check if all replicas are in the "running" state
    all_running=$(echo "$replicas_json" | jq '[.[] | select(.state != "running")] | length == 0')

    # Get the list of nodes hosting the replicas, sorted for comparison
    replica_nodes=$(echo "$replicas_json" | jq -r '.[].node' | sort)
    expected_nodes=$(echo -e "$expected_node1\n$expected_node2" | sort)

    # Print replica_nodes and expected_nodes for debugging
    echo "[DEBUG] Current replica nodes: $(echo "$replica_nodes" | tr '\n' ' ')"
    echo "[DEBUG] Expected replica nodes: $(echo "$expected_nodes" | tr '\n' ' ')"

    # Check if robustness is healthy, exactly 2 replicas, all running, and replicas on expected nodes
    if [[ "$robustness" == "healthy" ]] && [[ "$replica_count" -eq 2 ]] && [[ "$all_running" == "true" ]]; then
      if diff <(echo "$replica_nodes") <(echo "$expected_nodes") > /dev/null; then
        echo "✅ Volume is healthy with 2 running replicas on nodes: $expected_node1, $expected_node2"
        break
      else
        echo "[WAIT] Replicas not on expected nodes yet: actual=($(echo $replica_nodes)), expected=($(echo $expected_nodes))"
      fi
    else
      echo "[WAIT] robustness=$robustness, replica_count=$replica_count, all_running=$all_running"
    fi

    sleep 5
  done
}


for i in $(seq 1 "$ITERATIONS"); do
  echo ""
  echo "========== Iteration $i/$ITERATIONS =========="

  # Step 1: Evict node1
  evict_node "$NODE1"

  # Step 2~3: Wait until replicas are on node2 and node3
  wait_for_volume_state "$NODE2" "$NODE3"

  # Step 4: Un-evict node1
  unevict_node "$NODE1"

  # Step 5: Evict node3
  evict_node "$NODE3"

  # Step 6: Wait until replicas are on node2 and node1
  wait_for_volume_state "$NODE2" "$NODE1"

  # Step 7: Un-evict node3 for next iteration
  unevict_node "$NODE3"
done

echo ""
echo "🎉 Done with $ITERATIONS iterations!"
```


</details>

**Comment by hookak** [comment]
Hi @derekbit, thanks for checking this issue.

I’ve added more investigation details in [#11109](https://github.com/longhorn/longhorn/issues/11109).
Although I haven’t tested with the Longhorn master-head images yet, I expect the issue will still occur — it also reproduces with upstream SPDK without Longhorn. I’ll confirm with master-head images as well.

I’ve updated the I/O workload; you can test with the following `pod_with_pvc.yaml` to likely reproduce:

<details>
<summary>pod_with_pvc.yaml (meta I/O)</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  restartPolicy: Always
  nodeName: dereksu-c3-small-x86-02
  containers:
  - name: volume-test
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - |
        mkdir -p /data/files
        i=0
        while true; do
          echo "[$(date)] [$i] Creating files..."
          for j in $(seq 1 10000); do
            touch /data/files/file_${i}_${j}
            sync
          done
          echo "[$(date)] [$i] Deleting files..."
          rm -rf /data/files/*
          i=$((i + 1))
        done
    volumeMounts:
    - name: volv
      mountPath: /data
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
```

</details>
