### ISSUE TITLE
[FEATURE] Support full-backup-interval in VolumeSnapshotClass

### ISSUE THREAD

**Issue by kenlasko** [longhorn/longhorn#9821]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

I've been bitten in the past by corruption in a incremental backup and am glad to have the `full-backup-interval` option in `RecurringJob`. It would be nice to extend this capability to the CSI `VolumeSnapshotClass`.

## Describe the solution you'd like
Allow for users to add `full-backup-interval: <somenumericvalue>` to the `parameters` section of a Longhorn `VolumeSnapshotClass`

An example could look like:
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-backup
driver: driver.longhorn.io
deletionPolicy: Retain
parameters:
  type: bak
  full-backup-interval: 4
```
