### ISSUE TITLE
[BUG] Share Managers for RWX volumes are missing after faulty k8s upgrade

### ISSUE THREAD

**Issue by mdsina** [longhorn/longhorn#9828]
## Describe the bug

I updated my k8s cluster. Due network issues etcd on two cp nodes stays in semi-faulted state, that causes some errors. I restarted that nodes and all looks fine except share manager for rwx volumes never coming back.
Also after failure of etcd, rwx volumes becoming fault and shows that all replicas being stopped. I salvage that replicas, they are turning back and replicated to all desired nodes, but that's all.

## To Reproduce

No exact steps to reproduce. Issue happens a while ago.
But what I do:
1. Start upgrading CP in order: CP1 -> CP3 -> CP2. 
2. After updating СP3, it started having problems with the CPU, after which the node started throttling and having network latencies. And it wasn't caught.
3. I upgraded all CP nodes. Start upgrading worker nodes and problems start here. etcd spamming me about failed healthchecks. CP leader start switching continuously. 
4. In between on recovering CP nodes and completing the upgrade, RWX volumes becoming to failed state, that required salvaging.
5. Failed volumes (only 2 and both RWX) was salvaged and becoming healthy.
6. Share Manager for each RWX volume not created. Volumes attached, but cannot be claimed by pods.

## Expected behavior

Longhorn have some mechanisms to invalidate the state? Or something like that.

## Support bundle for troubleshooting

https://drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing

## Environment

 - Longhorn version: 1.7.2
 - Impacted volume (PV): `pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b`, `pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm + flux
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos OS 1.8.1 (K8S version 1.31.1)
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Talos OS 1.8.1 (schematic 131c2104492b574bc1fdb9352febfa63811ec058d25c569c9ce6251f0c7c1f0c)
   - Kernel version: 6.6.54
   - CPU per node: CP1 - 20, CP2 - 4, CP3 - 4, Worker 1 - 20, Worker 2 - 4
   - Memory per node: CP1 - 8GiB, CP2 - 14GiB, CP3 - 4GiB, Worker 1 - 64GiB, Worker 2 - 14GiB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1 CP and 1 Worker - 10G, 2 CP  and 1 W - 2.5G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox KVM 8.2.8 on baremetal
 - Number of Longhorn volumes in the cluster: 21

## Additional context

Longhorn schedules replicas on following nodes: CP2, Worker 1, Worker 2. 
(Worker 3 had hardware issues, so some time ago the disk for replicas was moved to CP2 node 🤷)

Currently I have only two pvc with rwx access mode.
```
❯ kubectl -n longhorn-system get lhsm
NAME                                       STATE     NODE          AGE
pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb   stopped   talos-cp-01   52d
pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b   stopped   talos-cp-02   41d
```

## Workaround and Mitigation

I've tried workaround from https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359 but no luck.
```
> kubectl -n longhorn-system patch lhsm pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb --type=merge --subresource status --patch 'status: {state: error}'
sharemanager.longhorn.io/pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb patched

> kubectl -n longhorn-system patch lhsm pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b --type=merge --subresource status --patch 'status: {state: error}'
sharemanager.longhorn.io/pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b patched
```

```
Volume pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b requested remount at 2024-11-16T14:08:37Z
Volume pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb requested remount at 2024-11-16T14:08:07Z
```

**Comment by james-munson** [comment]
Both volumes have manual attachments made through the UI.  In ./yamls/namespaced/longhorn-system/longhorn.io/v1beta2/volumeattachments.yaml,

```yaml
    spec:
      attachmentTickets:
        longhorn-ui:
          generation: 1
          id: longhorn-ui
          nodeID: talos-worker-02
          parameters:
            disableFrontend: "true"
            lastAttachedBy: "null"
          type: longhorn-api
      volume: pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b
    status:
      attachmentTicketStatuses:
        longhorn-ui:
          conditions:
            - lastProbeTime: "null"
              lastTransitionTime: "2024-10-27T20:51:40Z"
              message: "null"
              reason: "null"
              status: "True"
              type: Satisfied
          generation: 1
          id: longhorn-ui
          satisfied: true
```
and
```yaml
    spec:
      attachmentTickets:
        csi-fa09ce874a259c5f8bdc7072257b732f4050c2f2577b3c683eeaa5c21857fc00:
          generation: 0
          id: csi-fa09ce874a259c5f8bdc7072257b732f4050c2f2577b3c683eeaa5c21857fc00
          nodeID: talos-worker-01
          parameters:
            disableFrontend: "false"
            lastAttachedBy: "null"
          type: csi-attacher
        longhorn-ui:
          generation: 0
          id: longhorn-ui
          nodeID: talos-cp-02
          parameters:
            disableFrontend: "true"
            lastAttachedBy: "null"
          type: longhorn-api
      volume: pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb
    status:
      attachmentTicketStatuses:
        csi-fa09ce874a259c5f8bdc7072257b732f4050c2f2577b3c683eeaa5c21857fc00:
          conditions:
            - lastProbeTime: "null"
              lastTransitionTime: "2024-10-28T17:29:09Z"
              message: Waiting for volume share to be available
              reason: "null"
              status: "False"
              type: Satisfied
          generation: 0
          id: csi-fa09ce874a259c5f8bdc7072257b732f4050c2f2577b3c683eeaa5c21857fc00
          satisfied: false
        longhorn-ui:
          conditions:
            - lastProbeTime: "null"
              lastTransitionTime: "2024-11-16T11:22:40Z"
              message: "null"
              reason: "null"
              status: "True"
              type: Satisfied
          generation: 0
          id: longhorn-ui
          satisfied: true
```

Perhaps try detaching the manual attachment first.  This sounds a lot like https://github.com/longhorn/longhorn/issues/7313#issuecomment-1863606967
