### ISSUE TITLE
Recursive mount in the `longhorn-csi-plugin` for v0.7.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#985]
```
    - args:
      - longhorn-manager
      - -d
      - csi
      - --nodeid=$(NODE_ID)
      - --endpoint=$(CSI_ENDPOINT)
      - --drivername=io.rancher.longhorn
      - --manager-url=http://longhorn-backend:9500/v1
      env:
      - name: NODE_ID
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: CSI_ENDPOINT
        value: unix:///var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock
      image: yasker/longhorn-manager:09570f91
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - -c
            - rm -f /var/lib/kubelet/plugins/io.rancher.longhorn/*
      name: compatible-longhorn-csi-plugin
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - SYS_ADMIN
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/lib/kubelet/plugins
        mountPropagation: Bidirectional
        name: plugin-dir
      - mountPath: /var/lib/kubelet/plugins/io.rancher.longhorn
        name: old-socket-dir
      - mountPath: /var/lib/kubelet/pods
        mountPropagation: Bidirectional
        name: pods-mount-dir
      - mountPath: /dev
        name: host-dev
      - mountPath: /sys
        name: host-sys
      - mountPath: /lib/modules
        name: lib-modules
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: longhorn-service-account-token-gz6hb
        readOnly: true
...
    volumes:
    - hostPath:
        path: /var/lib/kubelet/plugins_registry
        type: Directory
      name: registration-dir
    - hostPath:
        path: /var/lib/kubelet/plugins/driver.longhorn.io
        type: DirectoryOrCreate
      name: socket-dir
    - hostPath:
        path: /var/lib/kubelet/plugins
        type: Directory
      name: plugin-dir
    - hostPath:
        path: /var/lib/kubelet/pods
        type: DirectoryOrCreate
      name: pods-mount-dir
    - hostPath:
        path: /dev
        type: ""
      name: host-dev
    - hostPath:
        path: /sys
        type: ""
      name: host-sys
    - hostPath:
        path: /lib/modules
        type: ""
      name: lib-modules
    - hostPath:
        path: /var/lib/kubelet/plugins/io.rancher.longhorn
        type: DirectoryOrCreate
      name: old-socket-dir
```

We've mounted both `/var/lib/kubelet/plugins` and it's subdirectory `/var/lib/kubelet/plugins/io.rancher.longhorn`, which results in endless 
```
/dev/sda on /var/lib/kubelet/plugins/io.rancher.longhorn type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```
shown on the node for `mount` command.
