### ISSUE TITLE
[TASK] Run regression testing for Longhorn images in Application Collection

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9872]
## What's the task? Please describe

Run regression testing for Longhorn images in Application Collection

**Comment by chriscchien** [comment]
Using images from  Application Collection to deploy longhorn, blew component pods kept in `CrashLoopBackOff` state
- csi-attacher
- csi-provisioner
- csi-resizer
- csi-snapshotter
- longhorn-csi-plugin

[supportbundle_f804d1d4-2fc8-4c71-8c49-c18797c0fae4_2024-12-02T07-47-29Z.zip](https://github.com/user-attachments/files/17974453/supportbundle_f804d1d4-2fc8-4c71-8c49-c18797c0fae4_2024-12-02T07-47-29Z.zip)


![image](https://github.com/user-attachments/assets/dc48077b-eaf2-4bd5-9c5b-01acfe593df1)



My steps:
1. Connect to engineer VPN
2. perforn `helm pull oci://registry.suse.de/home/mbjoerkelund/orchid/helmcharts/longhorn --insecure-skip-tls-verify` to download `longhorn-1.7.2.tgz` and extract the file.
3. In the extrcted folder `longhorn/Chart.yaml`, can see images list below
```yaml
annotations:
  helm.sh/images: |
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2
      name: longhorn-engine
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-manager:1.7.2
      name: longhorn-manager
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-ui:1.7.2
      name: longhorn-ui
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-instance-manager:1.7.2
      name: longhorn-instance-manager
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-share-manager:1.7.2
      name: longhorn-share-manager
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-backing-image-manager:1.7.2
      name: longhorn-backing-image-manager
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/rancher-support-bundle-kit:0
      name: rancher-support-bundle-kit
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-external-attacher:4
      name: kubernetes-csi-external-attacher
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-external-provisioner:5
      name: kubernetes-csi-external-provisioner
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-node-driver-registrar:2
      name: kubernetes-csi-node-driver-registrar
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-external-resizer:1
      name: kubernetes-csi-external-resizer
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-external-snapshotter:8
      name: kubernetes-csi-external-snapshotter
    - image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/kubernetes-csi-livenessprobe:2
      name: kubernetes-csi-livenessprobe
```
5. Use those images to deploy longhorn (I download them all and push those images to my docker hub for test).
6. As a result, csi relate components kept in `CrashLoopBackOff`.

**Comment by chriscchien** [comment]
After the discussion, I am deploy longhorn under ENG VPN and direct pull images from `registry.suse.de`
I can see all pods running, but the engine image kept in deploying state even all engine-image- pod is in running status, therefore it can not run our regression.
```bash
> kl get pods
NAME                                                READY   STATUS    RESTARTS      AGE
csi-attacher-5f8f9b7f46-8pnnz                       1/1     Running   0             11m
csi-attacher-5f8f9b7f46-fhxrs                       1/1     Running   0             11m
csi-attacher-5f8f9b7f46-nq4rb                       1/1     Running   0             9m1s
csi-provisioner-7cb8b6cbb4-bjjd8                    1/1     Running   0             11m
csi-provisioner-7cb8b6cbb4-p7xw9                    1/1     Running   0             11m
csi-provisioner-7cb8b6cbb4-vjq6r                    1/1     Running   0             11m
csi-resizer-6c5c9dc74b-dgsb7                        1/1     Running   0             11m
csi-resizer-6c5c9dc74b-gxkzp                        1/1     Running   2 (10m ago)   11m
csi-resizer-6c5c9dc74b-xnfz2                        1/1     Running   0             11m
csi-snapshotter-867cc95bb4-ch6qm                    1/1     Running   0             11m
csi-snapshotter-867cc95bb4-kdgk5                    1/1     Running   2 (10m ago)   11m
csi-snapshotter-867cc95bb4-lkcfv                    1/1     Running   0             11m
engine-image-ei-526c3641-7jswz                      1/1     Running   0             12m
engine-image-ei-526c3641-clvpm                      1/1     Running   0             12m
engine-image-ei-526c3641-sfhwb                      1/1     Running   0             12m
instance-manager-6b0fbaa5a00166b2c400e2a9e689a308   1/1     Running   0             11m
instance-manager-8911b7791292997a42271c5996572b7f   1/1     Running   0             11m
instance-manager-b5145fcf13663f9ec503259b5957098d   1/1     Running   0             11m
longhorn-csi-plugin-85fdz                           3/3     Running   0             11m
longhorn-csi-plugin-g88cv                           3/3     Running   0             11m
longhorn-csi-plugin-q7fl7                           3/3     Running   0             11m
longhorn-driver-deployer-584f6d87f4-2vjkq           1/1     Running   2 (12m ago)   12m
longhorn-iscsi-installation-bjmk2                   1/1     Running   0             79m
longhorn-iscsi-installation-hvh8d                   1/1     Running   0             79m
longhorn-iscsi-installation-k2cgv                   1/1     Running   0             79m
longhorn-manager-8gn5r                              2/2     Running   0             12m
longhorn-manager-8h6tn                              2/2     Running   0             12m
longhorn-manager-x9vrh                              2/2     Running   0             12m
longhorn-nfs-installation-9mlrg                     1/1     Running   0             79m
longhorn-nfs-installation-drs4v                     1/1     Running   0             79m
longhorn-nfs-installation-v4vxc                     1/1     Running   0             79m
longhorn-ui-6c6ff46b54-9gdsv                        1/1     Running   0             12m
longhorn-ui-6c6ff46b54-gnncj                        1/1     Running   0             12m
```

But the engine image kept in deploying state even all `engine-image-` pod is in running status

- from ui
![image](https://github.com/user-attachments/assets/e351434b-ca3d-4a40-948a-fc24bebe4c32)

- from kubectl, engine image pods running but CR `engineimages.longhorn.io` stuck in deploying.
![image](https://github.com/user-attachments/assets/78048bad-b9a9-49da-9dfc-e6fa24d61026)

cc @derekbit

**Comment by derekbit** [comment]
Dependency issue

```
1: cannot open shared object file: No such file or directory\n: exit status 127" node=worker1
2024-12-02T20:43:05.232292367+08:00 time="2024-12-02T12:43:05Z" level=error msg="Failed to sync Longhorn engine image" func=controller.handleReconcileErrorLogging file="utils.go:79" controller=longhorn-engine-image engineImage=longhorn-system/ei-526c3641 error="failed to sync engine image for longhorn-system/ei-526c3641: cannot get engine version for ei-526c3641 (registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2): cannot get volume version: failed to execute: /var/lib/longhorn/engine-binaries/registry.suse.de-home-mbjoerkelund-orchid-containerfile-longhorn-engine-1.7.2/longhorn [/var/lib/longhorn/engine-binaries/registry.suse.de-home-mbjoerkelund-orchid-containerfile-longhorn-engine-1.7.2/longhorn version --client-only], output , stderr /var/lib/longhorn/engine-binaries/registry.suse.de-home-mbjoerkelund-orchid-containerfile-longhorn-engine-1.7.2/longhorn: error while loading shared libraries: libqcow.so.1: cannot open shared object file: No such file or directory\n: exit status 127" node=worker1
```

**Comment by chriscchien** [comment]
Core test result :
![Screenshot from 2024-12-03 14-36-18](https://github.com/user-attachments/assets/17ad05aa-2b2e-4dc3-b466-1841c20c7490)
- 1 failure rerun pass.
- 3  failures related to engine upgrade test, after volume upgrade to engine image `longhornio/longhorn-test:upgrade-test.10-8.5-4.1-1`, replica not become Healthy therefore those test cases failed( it not happened on longhornio images deployed v1.7.2)
   - test_backing_image.py::test_engine_live_upgrade_with_backing_image
   - test_engine_upgrade.py::test_engine_live_upgrade
   - test_engine_upgrade.py::test_engine_live_upgrade_with_intensive_data_writing

volume name : longhorn-testvol-wsedno
![sceen](https://github.com/user-attachments/assets/23cb5fe7-bdf8-401e-9632-68b05bd95cc0)
[supportbundle_d8359bdc-6c20-4249-9577-5155128050e0_2024-12-03T07-38-53Z.zip](https://github.com/user-attachments/files/17989069/supportbundle_d8359bdc-6c20-4249-9577-5155128050e0_2024-12-03T07-38-53Z.zip)

**Comment by chriscchien** [comment]
Hi @derekbit, support bundle get from fresh installed longhorn and perform test_engine_upgrade.py::test_engine_live_upgrade, thank you.

volume name: longhorn-testvol-aqtu54
[supportbundle_4838adf2-58b6-4b73-b55f-a8bbb7058136_2024-12-03T08-24-28Z.zip](https://github.com/user-attachments/files/17989640/supportbundle_4838adf2-58b6-4b73-b55f-a8bbb7058136_2024-12-03T08-24-28Z.zip)

**Comment by derekbit** [comment]
@chriscchien 
The error is `There's no available disk for replica vol1-r-718124bf, size 1073741824`. Can you increase the disk size?

**Comment by chriscchien** [comment]
Hi @derekbit,

I checked the environment found that the `storageAvailable` is greater then `1073741824`, and I can manually reproduce the synptom by create a 1G volume then upgrade engine to `longhornio/longhorn-test:upgrade-test.10-8.5-4.1-1`, below information for reference, thank you.
```bash
> kl get engineimages
NAME          INCOMPATIBLE   STATE      IMAGE                                                                           REFCOUNT   BUILDDATE   AGE
ei-4754e80a   false          deployed   longhornio/longhorn-test:upgrade-test.10-8.5-4.1-1                              5          2d21h       2m39s
ei-526c3641   false          deployed   registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2   0          42d         23h
>
> kl get nodes.longhorn.io -o yaml | grep storageAvailable
        storageAvailable: 95630131200
        storageAvailable: 94476697600
        storageAvailable: 95315558400
```

**Comment by chriscchien** [comment]
This issue can be reproduce by upgrade volume engine image from `registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2` to `longhornio/longhorn-engine:v1.7.2` and below is the supportbundle, volume name: `testaaa`

[supportbundle_bc1efbca-ecaa-41bb-99e0-fb6afd27e889_2024-12-06T02-48-57Z.zip](https://github.com/user-attachments/files/18032129/supportbundle_bc1efbca-ecaa-41bb-99e0-fb6afd27e889_2024-12-06T02-48-57Z.zip)

**Comment by derekbit** [comment]
The `spec.gitCommit` is empty in the AppCo engine image.

```
  spec:
    image: registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2
  status:
    buildDate: "2024-10-22T12:00:00Z"
    cliAPIMinVersion: 8
    cliAPIVersion: 10
    conditions:
    - lastProbeTime: "null"
      lastTransitionTime: "2024-12-06T02:41:21Z"
      message: Engine image ei-526c3641 (registry.suse.de/home/mbjoerkelund/orchid/containerfile/longhorn-engine:1.7.2)
        is fully deployed on all ready nodes
      reason: "null"
      status: "True"
      type: ready
    controllerAPIMinVersion: 4
    controllerAPIVersion: 5
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: "null"
    incompatible: false
    noRefSince: "2024-12-06T02:45:37Z"
    nodeDeploymentMap:
      worker1: true
      worker2: true
      worker3: true
    ownerID: worker2
    refCount: 0
    state: deployed
    version: v1.7.2
```
