### ISSUE TITLE
[IMPROVEMENT] Encrypted volume online expansion support after k8s 1.29

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#9902]
## What's the document you plan to update? Why? Please describe

According to the document [expansion-encrypted-volume](https://longhorn.io/docs/1.8.0/nodes-and-volumes/volumes/expansion/#encrypted-volume), there are two ways if users want to expand an encrypted volume:
1. online, enable the feature gate (from 1.25 to 1.28 [use-secrets-while-expanding-csi-volumes-on-node-alpha/](https://kubernetes.io/blog/2022/09/21/kubernetes-1-25-use-secrets-while-expanding-csi-volumes-on-node-alpha/))
    Longhorn cannot handle online expansion for encrypted volumes automatically unless you enable the feature gate `CSINodeExpandSecret`
2. offline, use cryptsetup and fs commands

The encrypted volume online expansion can be done by adding parameters in the StorageClass from k8s 1.29 ([csi-node-expand-secret-support-ga](https://kubernetes.io/blog/2023/12/15/csi-node-expand-secret-support-ga/))
The Longhorn team should test it to check if it works and then update the document.

**Comment by derekbit** [comment]
@mantissahz Please check if the feature can work before drafting the official doc.

**Comment by mantissahz** [comment]
>@mantissahz Please check if the feature can work before drafting the official doc.

I tested it (on 12/04) by only adding the parameters to create a new StorageClass in the k8s v1.30.5+k3s1 cluster and it works.
```yaml
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: longhorn-crypto-global
  ...
parameters:
  ...
  csi.storage.k8s.io/node-publish-secret-name: longhorn-encrypted
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-encrypted
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn-encrypted
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-expand-secret-name: longhorn-encrypted       # <-- Added Parameter
  csi.storage.k8s.io/node-expand-secret-namespace: longhorn-system   # <-- Added Parameter
  encrypted: "true"
  ...
```
