### ISSUE TITLE
[FEATURE] Allow stricter restriction of NetworkPolicies

### ISSUE THREAD

**Issue by nroeske** [longhorn/longhorn#9911]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

We use longhorn in our backup stack and are in the process of adding `NetworkPolicies`. Longhorn already offers `NetworkPolicies`. However, these do not quite match our use case. If the `NetworkPolicies` of longhorn are applied, it is possible to access the longhorn components from a different `namespace`.

We would like to be able to restrict access to longhorn only to our own `namespace`, e.g. `longhorn-system`

## Describe the solution you'd like

We would like to be able to restrict access to longhorn only to our own `namespace`, e.g. `longhorn-system`.

A new value can be added to `values.yaml` for this purpose:

```
...
networkPolicies:
  enabled: false
  type: "k3s"
  restrictToNamespace: true
...
```

The `NetworkPolicies` could be extended like this (e.g. backing-image-manager-network-policy.yaml):
```
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backing-image-manager
  namespace: {{ include "release_namespace" . }}
spec:
  podSelector:
    matchLabels:
      longhorn.io/component: backing-image-manager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: longhorn-manager
          {{- if .Values.networkPolicies.restrictToNamespace }}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
          {{- end }}
        - podSelector:
            matchLabels:
              longhorn.io/component: instance-manager
          {{- if .Values.networkPolicies.restrictToNamespace }}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
          {{- end }}
        - podSelector:
            matchLabels:
              longhorn.io/component: backing-image-manager
          {{- if .Values.networkPolicies.restrictToNamespace }}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
          {{- end }}
        - podSelector:
            matchLabels:
              longhorn.io/component: backing-image-data-source
          {{- if .Values.networkPolicies.restrictToNamespace }}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
          {{- end }}
  {{- end }}
```

## Describe alternatives you've considered
A workaround for us  is too add this solution ourselves based on the longhorn `NetworkPolicies`. However, these must be checked with every update of longhorn.

## Additional context
Adding this feature would greatly increase maintainability for us
