### ISSUE TITLE
[BUG] Longhorn v2 volume is stuck in detaching/attaching loop forever if replica crash 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9919]
## To Reproduce

1. Deploy a SC with migratable, v2 data engine, and 1 replica
1. Deploy a pod which use the PVC on a node different than the node of the replica
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-v2-migratable
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      dataEngine: "v2"
      migratable: "true"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-block-vol
      namespace: default
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Block
      storageClassName: longhorn-v2-migratable
      resources:
        requests:
          storage: 2Gi
    ---      
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-1
      namespace: default
    spec:
      nodeName: phan-v701-pool2-dzrts-k86fv
      containers:
        - name: block-volume-test
          image: ubuntu:xenial
          imagePullPolicy: IfNotPresent
          command: ["sleep", "36000"]
          volumeDevices:
            - devicePath: /dev/longhorn/testblk
              name: block-vol
      volumes:
        - name: block-vol
          persistentVolumeClaim:
            claimName: longhorn-block-vol
    ```
1. Crash the instance manager pod of the replica
1. See that the volume stuck in attaching/detaching forever with repeated errors like this:
`2024-12-06T01:38:48.024643810Z [longhorn-instance-manager] time="2024-12-06T01:38:48Z" level=error msg="Found error during engine validation and update" func="spdk.(*Engine).ValidateAndUpdate.func2" file="engine.go:631" endpoint= engineName=pvc-5574f36a-bdc8-4157-991b-99c647d61420-e-1 error="failed to execute: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net lsblk /dev/longhorn/pvc-5574f36a-bdc8-4157-991b-99c647d61420 -n -o NAME,MAJ:MIN --nodeps], output , stderr lsblk: /dev/longhorn/pvc-5574f36a-bdc8-4157-991b-99c647d61420: not a block device\n: exit status 32" frontend=spdk-tcp-blockdev ip=10.42.219.24 port=20003 replicaStatusMap="map[pvc-5574f36a-bdc8-4157-991b-99c647d61420-r-dc1ab6dd:0xc000549cb0]" volumeName=pvc-5574f36a-bdc8-4157-991b-99c647d61420`

## Expected behavior

Volume should be auto salvage then reattach and become healthy

## Support bundle for troubleshooting

[supportbundle_30e4cbd0-7b29-4fbd-b857-e850880cd531_2024-12-06T01-39-26Z.zip](https://github.com/user-attachments/files/18034985/supportbundle_30e4cbd0-7b29-4fbd-b857-e850880cd531_2024-12-06T01-39-26Z.zip)
Volume name: `pvc-5574f36a-bdc8-4157-991b-99c647d61420`

## Environment

 - Longhorn version: master-head - Dec 6th, 2024
