### ISSUE TITLE
Pod failed to mount volumes with xfs filesystem

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#994]
Reproduce steps:
  - Create a volume, attach it to a node.
  -  Format the volume with xfs filesystem
  - Create PV/PVC for the volume
  - Deploy workload to use that volume using 

```
apiVersion: v1
kind: Pod
metadata:
  name: volume-test-xfs
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: centos:7
    command: ["/bin/sh", "-c", "while true; do :; done"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName:  <VOLUME_PVC_NAME>
```

Event logs: `kubectl describe pod volume-test-xfs`

```
ents:
  Type     Reason                  Age               From                                    Message
  ----     ------                  ----              ----                                    -------
  Normal   Scheduled               <unknown>         default-scheduler                       Successfully assigned default/volume-test-xfs to meldafrawi-linode-longhorn-03
  Normal   SuccessfulAttachVolume  36s               attachdetach-controller                 AttachVolume.Attach succeeded for volume "v-test-xfs"
  Warning  FailedMount             1s (x7 over 34s)  kubelet, meldafrawi-linode-longhorn-03  MountVolume.SetUp failed for volume "v-test-xfs" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = failed to mount the volume as "ext4", it already contains xfs. Mount error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/v-test-xfs /var/lib/kubelet/pods/6385084d-3c46-4afa-8469-f0840f7cf8d4/volumes/kubernetes.io~csi/v-test-xfs/mount
Output: mount: /var/lib/kubelet/pods/6385084d-3c46-4afa-8469-f0840f7cf8d4/volumes/kubernetes.io~csi/v-test-xfs/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/v-test-xfs, missing codepage or helper program, or other error.
```
