### ISSUE TITLE
[BUG] v2 volume stuck in crash loop due to replica r.ActiveChain is out of sync

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9942]
## Describe the bug

v2 volume stuck in crash loop (attaching/detaching) due to replica r.ActiveChain is out of sync. In some cases, r.ActiveChain doesn't;t contain lvol head but the lvol head actually exist in the disk. Longhorn doesn't update  r.ActiveChain correctly and keep hitting this error:
`
[2024-12-10 05:37:01.976314] lvol.c:1219:lvs_verify_lvol_name: *ERROR*: lvol with name pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4 already exists
`
`
[longhorn-instance-manager] time="2024-12-10T05:37:01Z" level=error msg="Failed to create replica pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4" func="spdk.(*Replica).Create.func2" file="replica.go:671" error="error sending message, id 652083, method bdev_lvol_create, params { ee6243ce-f323-4de5-8d71-baed8d6c8711 pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4 4096 unmap true}: {\"code\": -17,\"message\": \"File exists\"}" lvsName=v2-disk lvsUUID=ee6243ce-f323-4de5-8d71-baed8d6c8711 replicaName=pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4
`

## To Reproduce

1. Deploy Longhorn master-head 12/09/2024
1. Create SC using v2 dataengine, PVC, and a pod using the PVC
    ```yaml
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn-v2
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880" # 48 hours in minutes
      dataEngine: "v2"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: longhorn-v2-fs-vol
      namespace: default
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-v2
      resources:
        requests:
          storage: 4Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-v2-fs-vol
      namespace: default
    spec:
      nodeName: phan-v701-pool2-dzrts-k86fv
      restartPolicy: Always
      containers:
      - name: volume-test
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
              - ls
              - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-v2-fs-vol
    ```
1. Crash the only replica
1. Check if the volume stuck in the crash loop with error
    `
    [2024-12-10 05:37:01.976314] lvol.c:1219:lvs_verify_lvol_name: *ERROR*: lvol with name pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4 already exists
    `
    `
    [longhorn-instance-manager] time="2024-12-10T05:37:01Z" level=error msg="Failed to create replica pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4" func="spdk.(*Replica).Create.func2" file="replica.go:671" error="error sending message, id 652083, method bdev_lvol_create, params { ee6243ce-f323-4de5-8d71-baed8d6c8711 pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4 4096 unmap true}: {\"code\": -17,\"message\": \"File exists\"}" lvsName=v2-disk lvsUUID=ee6243ce-f323-4de5-8d71-baed8d6c8711 replicaName=pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4
    `
1. If not, repeat step 3

## Expected behavior

Volume should not stuck in crash loop
