### ISSUE TITLE
[BUG] Fail to create v2 volume from VolumeSnapshot with Source:snapshotHandle as Backup

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9965]
## Describe the bug

From test case [test_csi_volumesnapshot_restore_existing_backup](https://github.com/longhorn/longhorn-tests/blob/01efc8f511ef9a24c11030da8540a91d75e4c518/manager/integration/tests/test_csi_snapshotter.py#L549), create v2 volume from VolumeSnapshot where the VolumeSnapshotContent source:snapshotHandle is a backup, the creation will never complete, volume kept in detach, attaching loop.

`pvc-403e3fae-e52f-4e65-883e-f4999e366783`
```bash
> kl get volume -w
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE               AGE
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            attached   unknown                  2147483648   ip-172-31-41-252   4m36s
pvc-8e8057fa-f89f-420b-9733-c6d7c5be1744   v2            attached   healthy                  2147483648   ip-172-31-45-53    18m
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            attached   faulted                  2147483648   ip-172-31-41-252   4m38s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            attached   faulted                  2147483648   ip-172-31-41-252   4m38s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            detaching   faulted                  2147483648   ip-172-31-41-252   4m38s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            detached    faulted                  2147483648                      4m40s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            detached    unknown                  2147483648                      4m40s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            detached    unknown                  2147483648                      4m40s
pvc-403e3fae-e52f-4e65-883e-f4999e366783   v2            detached    unknown                  2147483648                      4m40s

```
    

## To Reproduce
1. Deploy the [CSI snapshot CRDs](https://longhorn.io/docs/1.8.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/).
2. Deploy stoarge class [longhorn-v2-data-engine](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/storageclass.yaml).
3. Enable v2 data engine, dynamic provision PVC `vol1` with storageClassName `longhorn-v2-data-engine` size 2Gi and workload, write data to workload.
4. Create backup manually, record the volume name and backup name
```bash
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE              AGE
pvc-8e8057fa-f89f-420b-9733-c6d7c5be1744   v2            attached   healthy                  2147483648   ip-172-31-45-53   2m42s
>
> kl get backup
NAME                      SNAPSHOTNAME                           SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE       LASTSYNCEDAT
backup-02181ab621804def   018ddde7-37d9-4b1a-a508-9dba56eda851   117440512      2024-12-12T08:30:29Z   Completed   2024-12-12T08:30:38Z
```
5. Create volume VolumeSnapshotClass `longhorn-test`
```yaml
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-test
driver: driver.longhorn.io
deletionPolicy: Delete
```
```bash
> k get volumesnapshotclass
NAME            DRIVER               DELETIONPOLICY   AGE
longhorn-test   driver.longhorn.io   Delete           66m
```
6.  Create VolumeSnapshotContent `vol1-snapcontent` with information get from step 2
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: vol1-snapcontent
spec:
  deletionPolicy: Delete
  driver: driver.longhorn.io
  source:
    snapshotHandle: bs://pvc-8e8057fa-f89f-420b-9733-c6d7c5be1744/backup-02181ab621804def
  volumeSnapshotClassName: longhorn-test
  volumeSnapshotRef:
    name: vol1-volumesnapshot
    namespace: default
```
```bash
> k get volumesnapshotcontent
NAME               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER               VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT        VOLUMESNAPSHOTNAMESPACE   AGE
vol1-snapcontent   true                       Delete           driver.longhorn.io   longhorn-test         vol1-volumesnapshot   default                   7s
```
7. Create VolumeSnapshot `vol1-volumesnapshot`, `source volumeSnapshotContentName: vol1-snapcontent`(created in step6)
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vol1-volumesnapshot
spec:
  volumeSnapshotClassName: longhorn-test
  source:
    volumeSnapshotContentName: vol1-snapcontent
```
```bash
> k get volumesnapshot
NAME                  READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT    CREATIONTIME   AGE
vol1-volumesnapshot   true                     vol1-snapcontent                      longhorn-test   vol1-snapcontent   2m20s          13s
```
8. Create PVC `restore-pvc`, data source VolumeSnapshot `vol1-volumesnapshot`, storageClassName `longhorn-v2-data-engine` created in step 7
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-v2-data-engine
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: vol1-volumesnapshot
```
9. v2 volume created but kept in detach, attaching loop

## Expected behavior

volume creation complete like v1 volume

## Support bundle for troubleshooting

[supportbundle_a5f69c43-deab-4b91-98a2-cf5d582382da_2024-12-12T08-47-14Z.zip](https://github.com/user-attachments/files/18108248/supportbundle_a5f69c43-deab-4b91-98a2-cf5d582382da_2024-12-12T08-47-14Z.zip)

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Similar to https://github.com/longhorn/longhorn/issues/9962 but the steps have a little difference

## Workaround and Mitigation

N/A
