### ISSUE TITLE
[BUG] Frequent Failures When Uploading 512MB Backing Image

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9975]
## Describe the bug

When I verified the issue [#8757](https://github.com/longhorn/longhorn/issues/8757#issuecomment-2311897006), I found that uploading the backing image frequently resulted in a "failed-and-cleanup" status.

```yaml
status:
  checksum: ""
  diskFileStatusMap:
    cda9b69f-8b28-4f2c-ae25-8132020d72cc:
      lastStateTransitionTime: "2024-12-13T07:48:13Z"
      message: 'failed to process sync file: failed to copy the data with timeout:
        unexpected EOF'
      progress: 58
      state: failed-and-cleanup
  diskLastRefAtMap:
    cda9b69f-8b28-4f2c-ae25-8132020d72cc: "2024-12-13T07:44:34Z"
  ownerID: ip-10-0-2-202
  realSize: 0
  size: 536870912
  uuid: 2256f071
  virtualSize: 0

```

![Screenshot_20241213_162307](https://github.com/user-attachments/assets/9d4524b4-59a7-42fb-9cfc-16cc2f38f66c)

## To Reproduce

https://github.com/longhorn/longhorn/issues/8757#issuecomment-2311897006

## Expected behavior

The upload should function normally without any issues.

## Support bundle for troubleshooting

[backingimage.zip](https://github.com/user-attachments/files/18123429/backingimage.zip)

## Additional context

https://github.com/longhorn/longhorn/issues/8757
