### ISSUE TITLE
[BUG] Backing Image Creation with Multiple Copies Fails in Loop

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9976]
## Describe the bug

When attempting to create a backing image  from `export from a longhorn volume` with minimum number of copies : `3`, only one of them is successful. The other two enter a loop of starting, in-progress, and failed states.

![Recording 2024-12-13 at 17 33 19](https://github.com/user-attachments/assets/344dd725-037b-49b2-b959-1e7dc1094e84)

## To Reproduce
 1. Create a Longhorn volume with size 512MB (named `512`)
 2. Mount the volume to a pod
 3. Write 200MB test data to the volume
 4. Create a backing image with following settings:
     - Creation method: "Export from a Longhorn volume"
     - Minimum number of copies: 3
5. Only one backing image copy successfully reaches Ready state
6. The remaining two copies are stuck in a continuous loop: `starting -> in-progress -> failed -> starting`
```yaml
    status:
  checksum: bed698b86339680e63bb887e3fc080c05beed52bfde3a8d2a9df577de4fdb93f8ad9018a317442f48bd6945b85c58d0d2828077e2d18d7a86cf590d438e29f7e
  diskFileStatusMap:
    cc376e72-1b18-49a3-a543-a6457a3ec75f:
      lastStateTransitionTime: "2024-12-13T08:11:17Z"
      message: found mismatching realSize 235278336 reported by backing image manager
        backing-image-manager-b2c6-cc37 in disk cc376e72-1b18-49a3-a543-a6457a3ec75f,
        the realSize recorded in status is 235282432
      progress: 100
      state: failed
```

## Expected behavior

The `export from a longhorn volume` should function normally without any issues.

## Support bundle for troubleshooting

[backingimage.zip](https://github.com/user-attachments/files/18124158/backingimage.zip)

## Environment

 - Longhorn version: `master-head`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: SLES-15sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

- https://github.com/longhorn/longhorn/issues/8757
- https://github.com/longhorn/longhorn/issues/9882
